/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Stage.ClosedEmbeddingClass
public import Hironaka.Resolution.Algebraic.Stage.Tower
import Hironaka.Algebra.Local.QuotientParameters
import Hironaka.Algebra.Local.RegularSystem
import Hironaka.Algebra.RegularSmooth.SchemeForms
import Hironaka.Algebra.Util.JacobsonCover
import Hironaka.Resolution.Algebraic.Stage.ClosedEmbeddingDescent
import Hironaka.Resolution.Algebraic.Stage.ClosedEmbeddingHypersurface
import Hironaka.Resolution.Algebraic.Stage.Coherence
import Hironaka.Scheme.BlowUp.CoordinateSubspace.Smooth
import Hironaka.Scheme.BlowUpSequence.DisjointUnion
import Hironaka.Scheme.BlowUpSequence.Functoriality
import Hironaka.Scheme.BlowUpSequence.Pushforward
import Hironaka.Scheme.BlowUpSequence.RestrictDivisors
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Hironaka.Scheme.IdealSheaf.Order.Semicontinuity
import Hironaka.Scheme.IdealSheaf.Order.Specialization
import Mathlib.Algebra.Order.Module.Field
import Mathlib.AlgebraicGeometry.Morphisms.Etale
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# Claim 71.2 when a component of `X` lies inside `Y`

Kollár's proof of Claim 71.2 [Kol07, 108] takes `Y ⊂ X` to be the bottom of a chain of
hypersurfaces; the chain has length `0` on a component of `X` lying inside `Y`, where `Y ⊂ X` is a
local isomorphism and "every local equation of `Y` is in `I`" says nothing (`max-ord(ker j) = ⊤`).
This module settles that case for the stage functors of the tower, so that the induction of
`Hironaka.Resolution.Algebraic.Stage.ClosedEmbeddingStep` covers every closed embedding:

* `stalkIdeal_ker_eq_bot_of_two_le_ord` — if the ideal of `Y` has order `≥ 2` at a point, its stalk
  there is `0`: the stalk `𝒪_{X,x}` is regular with regular quotient `𝒪_{Y,y}`, so the kernel is
  generated by part of a regular system of parameters ([Sta, Tag 00NR];
  `IsRegularLocalRing.exists_span_eq_maximalIdeal_and_eq_span_image_lt`), none of
  which lies in `𝔪²`
  (`notMem_sq_of_span_eq`) — the part is empty.
* `exists_isClosed_stalkIdeal_ker_eq_bot` — such a point specializes to a closed point of `Y` where
  the stalk of `ker j` is still `0` (upper semicontinuity of the order, `ord_le_ord_of_specializes`;
  the Jacobson property of schemes of finite type over a field).
* `smoothOfRelativeDimension_eq_of_stalkIdeal_ker_eq_bot` — there `dim Y = dim X`: the Krull
  dimensions of the stalks at the closed point agree, the stalk of `Y` being the quotient by `0`.
* `seq_eq_pushforward_of_not_maxOrd_ker_le_one` — the identity of Claim 71.2 in this case, by a
  **two-hypersurface argument**, not in the sources: in `X⁺ := X ×_k 𝔸¹` both `X` (the zero section
  `s`, the graph of a morphism over the separated `𝔸¹ → Spec k`, a closed immersion) and `Y` (along
  `j ≫ s`) are smooth hypersurfaces — `dim X⁺ = dim X + 1 = dim Y + 1`
  (`smoothOfRelativeDimension_Spec_map_algebraMap_mvPolynomial`,
  `isSmoothDivisor_of_smoothOfRelativeDimension`) — and `(X⁺, s_* I, 1, ∅)` is a marked triple with
  `(X, I, 1, ∅)` and `(Y, J, 1, ∅)` closed embeddings of empty boundary. The hypersurface case
  (`Hironaka.Resolution.Algebraic.Stage.ClosedEmbeddingHypersurface`) twice, at the stage `n + 2`,
  gives `s_* BMO(X) = BMO(X⁺) = (j ≫ s)_* BMO(Y) = s_* j_* BMO(Y)`; `s_*` is injective
  (`pushforward_injective`), and the coherence of the tower brings both sides back to the stage
  `n + 1`.

The case is the degenerate end of Kollár's chain; the two-hypersurface argument is bookkeeping on
the hypersurface case of Claim 71.2.
-/

public section

universe u

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry TopologicalSpace Hironaka Scheme
  BlowUpSequence Scheme.IdealSheafData IsLocalRing

namespace Hironaka.Stage

variable {k : Type u} [Field k] [CharZero k]

section Kernel

variable {TX TY : Triple k} (j : TY.X.left ⟶ TX.X.left) [IsClosedImmersion j]
  (hjo : j ≫ (TX.X.left ↘ Spec (.of k)) = TY.X.left ↘ Spec (.of k))

omit [CharZero k] in
include hjo in
/-- The image of a closed embedding of smooth `k`-schemes is smooth over `k`: `V(ker j) ≅ Y`. -/
theorem smooth_ker_subschemeι_comp : Smooth (j.ker.subschemeι ≫ (TX.X.left ↘ Spec (.of k))) := by
  have hiso : IsIso j.toImage :=
    IsClosedImmersion.isIso_of_ker_eq j j.imageι j.toImage j.toImage_imageι
      (Scheme.IdealSheafData.ker_subschemeι _).symm
  have h1 : inv j.toImage ≫ j = j.imageι := (IsIso.inv_comp_eq _).mpr j.toImage_imageι.symm
  have h2 : j.ker.subschemeι ≫ (TX.X.left ↘ Spec (.of k)) = inv j.toImage ≫
    (TY.X.left ↘ Spec (.of k)) := by
    rw [← hjo, ← Category.assoc, h1]
  rw [h2]
  have := TY.smooth
  infer_instance

omit [CharZero k] in
include hjo in
/-- Where the ideal of `Y` has order `≥ 2`, its stalk is `0`: the kernel of the surjection of
regular local rings `𝒪_{X,x} → 𝒪_{Y,y}` is generated by part of a regular system of parameters
([Sta, Tag 00NR];
`IsRegularLocalRing.exists_span_eq_maximalIdeal_and_eq_span_image_lt`),
no member of which lies in `𝔪²`
(`notMem_sq_of_span_eq`). -/
theorem stalkIdeal_ker_eq_bot_of_two_le_ord {x : TX.X.left} (hx : ((2 : ℕ) : ℕ∞) ≤ j.ker.ord x) :
    j.ker.stalkIdeal x = ⊥ := by
  have hsm := smooth_ker_subschemeι_comp j hjo
  have hxs : x ∈ j.ker.support := by
    by_contra h
    have h0 : j.ker.ord x = 0 := (IdealSheafData.ord_eq_zero_iff _ _).mpr h
    rw [h0] at hx
    exact absurd hx (by simp)
  have hreg : IsRegularLocalRing (TX.X.left.presheaf.stalk x) :=
    isRegularLocalRing_stalk (TX.X.left ↘ Spec (.of k)) x
  have hregq : IsRegularLocalRing (TX.X.left.presheaf.stalk x ⧸ j.ker.stalkIdeal x) :=
    isRegularLocalRing_quotient_stalkIdeal j.ker (TX.X.left ↘ Spec (.of k)) hxs
  have hle : j.ker.stalkIdeal x ≤ maximalIdeal (TX.X.left.presheaf.stalk x) ^ 2 := by
    rw [IdealSheafData.ord_eq_ord_stalkIdeal] at hx
    exact le_ord_iff.mp hx
  obtain ⟨m, c, y, hcle, hm, hmax, hK⟩ :=
    IsRegularLocalRing.exists_span_eq_maximalIdeal_and_eq_span_image_lt
      (j.ker.stalkIdeal x)
  rcases Nat.eq_zero_or_pos c with hc | hc
  · subst hc
    rw [hK]
    have : (y '' {i : Fin m | i.val < 0}) = ∅ := by
      ext a
      simp
    rw [this, Ideal.span_empty]
  · exfalso
    have hcm : 0 < m := lt_of_lt_of_le hc hcle
    have hmem : y ⟨0, hcm⟩ ∈ j.ker.stalkIdeal x := by
      rw [hK]
      exact Ideal.subset_span ⟨⟨0, hcm⟩, hc, rfl⟩
    exact notMem_sq_of_span_eq y hmax hm ⟨0, hcm⟩ (hle hmem)

omit [IsClosedImmersion j] in
/-- A point where the stalk of `ker j` is `0` specializes to a closed point of `X` in `Y` where it
is still `0` (upper semicontinuity of the order and the Jacobson property). -/
theorem exists_isClosed_stalkIdeal_ker_eq_bot {d : ℕ}
    [SmoothOfRelativeDimension d (TX.X.left ↘ Spec (.of k))] {x : TX.X.left}
    (hx : j.ker.stalkIdeal x = ⊥) :
    ∃ p : TX.X.left, IsClosed ({p} : Set TX.X.left) ∧ p ∈ j.ker.support ∧
      j.ker.stalkIdeal p = ⊥ := by
  have : IsLocallyNoetherian TX.X.left := (TX.X.left ↘ Spec (.of k)).isLocallyNoetherian_of_field
  have : JacobsonSpace TX.X.left := LocallyOfFiniteType.jacobsonSpace (TX.X.left ↘ Spec (.of k))
  have hxs : x ∈ j.ker.support := by
    rw [IdealSheafData.mem_support_iff_stalkIdeal_le_maximalIdeal, hx]
    exact bot_le
  obtain ⟨p, hp, hps, hxp⟩ :=
    exists_isClosed_singleton_mem_specializes j.ker.support.isClosed hxs
  refine ⟨p, hp, hps, ?_⟩
  have h1 : j.ker.ord x = ⊤ := (IdealSheafData.ord_eq_top_iff j.ker x).mpr hx
  have h2 : j.ker.ord x ≤ j.ker.ord p :=
    IdealSheafData.ord_le_ord_of_specializes j.ker (TX.X.left ↘ Spec (.of k)) d hxp
  rw [h1, top_le_iff] at h2
  exact (IdealSheafData.ord_eq_top_iff j.ker p).mp h2

include hjo in
/-- At a closed point of `X` in `Y` where the stalk of `ker j` is `0`, the Krull dimensions of the
stalks of `X` and of `Y` agree, so `dim Y = dim X`. -/
theorem smoothOfRelativeDimension_eq_of_stalkIdeal_ker_eq_bot {d dY : ℕ}
    [SmoothOfRelativeDimension d (TX.X.left ↘ Spec (.of k))]
    [SmoothOfRelativeDimension dY (TY.X.left ↘ Spec (.of k))] {p : TX.X.left}
    (hp : IsClosed ({p} : Set TX.X.left)) (hps : p ∈ j.ker.support)
    (hbot : j.ker.stalkIdeal p = ⊥) :
    dY = d := by
  have hPF : PerfectField k := PerfectField.ofCharZero
  have hiso : IsIso j.toImage :=
    IsClosedImmersion.isIso_of_ker_eq j j.imageι j.toImage j.toImage_imageι
      (Scheme.IdealSheafData.ker_subschemeι _).symm
  have h1 : inv j.toImage ≫ j = j.imageι := (IsIso.inv_comp_eq _).mpr j.toImage_imageι.symm
  have h2 : j.ker.subschemeι ≫ (TX.X.left ↘ Spec (.of k)) = inv j.toImage ≫
    (TY.X.left ↘ Spec (.of k)) := by
    rw [← hjo, ← Category.assoc, h1]
  have hZ : SmoothOfRelativeDimension dY (j.ker.subschemeι ≫ (TX.X.left ↘ Spec (.of k))) := by
    rw [h2]
    simpa using smoothOfRelativeDimension_comp 0 dY (inv j.toImage) (TY.X.left ↘ Spec (.of k))
  have hX : ringKrullDim (TX.X.left.presheaf.stalk p) = d :=
    Scheme.ringKrullDim_stalk_of_smoothOfRelativeDimension_of_isClosed
      (TX.X.left ↘ Spec (.of k)) d hp
  have hY : ringKrullDim (TX.X.left.presheaf.stalk p ⧸ j.ker.stalkIdeal p) = dY :=
    ringKrullDim_quotient_stalkIdeal_of_isClosed j.ker (TX.X.left ↘ Spec (.of k)) dY
      hps hp
  rw [hbot, ringKrullDim_eq_of_ringEquiv (RingEquiv.quotientBot _), hX] at hY
  exact_mod_cast hY.symm

end Kernel

/-- The degenerate end of the chain of [Kol07, 108] (`c = 0`: a component of `X` inside `Y`,
`max-ord(ker j) = ⊤`), by the two-hypersurface argument. With `Y` of the dimension of `X`
(`smoothOfRelativeDimension_eq_of_stalkIdeal_ker_eq_bot`), embed `X` into `X⁺ := X ×_k 𝔸¹` by the
zero section `s`; both `s` and `j ≫ s` are closed immersions with smooth hypersurfaces as images,
`(X⁺, s_* I, 1, ∅)` is a marked triple, and the hypersurface case at the stage `n + 2` gives
`s_* BMO(X) = BMO(X⁺) = (j ≫ s)_* BMO(Y) = s_* (j_* BMO(Y))`; `s_*` is injective and the coherence
of the tower returns to the stage `n + 1`. -/
theorem seq_eq_pushforward_of_not_maxOrd_ker_le_one (base : OrderReductionStage.{u} 0) {n : ℕ}
    (TX TY : MarkedTriple k) (j : TY.X.left ⟶ TX.X.left) [IsClosedImmersion j]
    (hj : MarkedTriple.ClosedEmbedding TX TY j) (hE : IsEmpty TX.E.ι)
    (hTX : TX.BMOClass (n + 1) 1) (hK : ¬ j.ker.maxOrd ≤ ((1 : ℕ) : ℕ∞)) :
    (((tower base (n + 1)).bmo 1).functor k).seq TX hTX =
      ((((tower base (n + 1)).bmo 1).functor k).seq TY
        (bmoClass_of_closedEmbedding hj hTX)).pushforward j := by
  have hPF : PerfectField k := PerfectField.ofCharZero
  obtain ⟨d, hdle, hd⟩ := hTX.2.1
  obtain ⟨dY, hdY⟩ := TY.smoothOfRelativeDimension
  have hd' : SmoothOfRelativeDimension d (TX.X.left ↘ Spec (.of k)) := hd
  have hdY' : SmoothOfRelativeDimension dY (TY.X.left ↘ Spec (.of k)) := hdY
  -- a point of order `≥ 2`, hence with zero stalk; a closed such point; `dim Y = dim X`
  have hx : ∃ x, ¬ j.ker.ord x ≤ ((1 : ℕ) : ℕ∞) :=
    not_forall.mp fun h => hK ((IdealSheafData.maxOrd_le_iff _).mpr h)
  obtain ⟨x, hx⟩ := hx
  have hx2 : ((2 : ℕ) : ℕ∞) ≤ j.ker.ord x := by
    have h1 : (1 : ℕ∞) < j.ker.ord x := by exact_mod_cast not_le.mp hx
    have h2 : (1 : ℕ∞) + 1 ≤ j.ker.ord x := Order.add_one_le_of_lt h1
    calc ((2 : ℕ) : ℕ∞) = (1 : ℕ∞) + 1 := by norm_num
      _ ≤ j.ker.ord x := h2
  have hbot := stalkIdeal_ker_eq_bot_of_two_le_ord j hj.1.1 hx2
  obtain ⟨p, hp, hps, hpbot⟩ := exists_isClosed_stalkIdeal_ker_eq_bot j (d := d) hbot
  have hdYd : dY = d := smoothOfRelativeDimension_eq_of_stalkIdeal_ker_eq_bot j hj.1.1 hp hps hpbot
  subst dY
  -- the affine line and the product `X⁺ = X ×_k 𝔸¹`
  let A : Type u := MvPolynomial (Fin 1) k
  let q : Spec (CommRingCat.of A) ⟶ Spec (.of k) := Spec.map (CommRingCat.ofHom (algebraMap k A))
  have hq : SmoothOfRelativeDimension 1 q :=
    CoordinateSubspace.smoothOfRelativeDimension_Spec_map_algebraMap_mvPolynomial
      k 1
  let o : Spec (.of k) ⟶ Spec (CommRingCat.of A) :=
    Spec.map (CommRingCat.ofHom (MvPolynomial.constantCoeff (R := k) (σ := Fin 1)))
  let φ : TX.X.left ⟶ Spec (CommRingCat.of A) := (TX.X.left ↘ Spec (.of k)) ≫ o
  let P : Scheme.{u} := Limits.pullback (φ ≫ q) q
  let pr : P ⟶ TX.X.left := pullback.fst (φ ≫ q) q
  let s : TX.X.left ⟶ P := pullback.lift (𝟙 _) φ (Category.id_comp (φ ≫ q))
  have hsp : s ≫ pr = 𝟙 _ := pullback.lift_fst _ _ _
  have hcis : IsClosedImmersion s := inferInstance
  have hprd : SmoothOfRelativeDimension 1 pr :=
    (smoothOfRelativeDimension_isStableUnderBaseChange 1).of_isPullback
      (IsPullback.of_hasPullback (φ ≫ q) q).flip hq
  have hprs : Smooth pr := SmoothOfRelativeDimension.smooth 1 pr
  have hprq : QuasiCompact pr :=
    (inferInstance : MorphismProperty.IsStableUnderBaseChange @QuasiCompact).of_isPullback
      (IsPullback.of_hasPullback (φ ≫ q) q).flip inferInstance
  have hprsep : IsSeparated pr :=
    (inferInstance : MorphismProperty.IsStableUnderBaseChange @IsSeparated).of_isPullback
      (IsPullback.of_hasPullback (φ ≫ q) q).flip inferInstance
  let _ : P.Over (Spec (.of k)) := ⟨pr ≫ (TX.X.left ↘ Spec (.of k))⟩
  have hPd : SmoothOfRelativeDimension (1 + d) (P ↘ Spec (.of k)) :=
    smoothOfRelativeDimension_comp 1 d pr (TX.X.left ↘ Spec (.of k))
  have hPsm : Smooth (P ↘ Spec (.of k)) := SmoothOfRelativeDimension.smooth (1 + d) _
  have : LocallyOfFiniteType (P ↘ Spec (.of k)) :=
    inferInstanceAs (LocallyOfFiniteType (pr ≫ (TX.X.left ↘ Spec (.of k))))
  have : QuasiCompact (P ↘ Spec (.of k)) :=
    inferInstanceAs (QuasiCompact (pr ≫ (TX.X.left ↘ Spec (.of k))))
  have : IsSeparated (P ↘ Spec (.of k)) :=
    inferInstanceAs (IsSeparated (pr ≫ (TX.X.left ↘ Spec (.of k))))
  have hEι : IsEmpty (TX.E.comap pr).ι := hE
  -- the marked triple of `X⁺`
  let TP : MarkedTriple k :=
    { X := .of P
      I := TX.I.map s
      isNonzeroEverywhere :=
        isNonzeroEverywhere_map_of_isClosedImmersion s TX.I TX.isNonzeroEverywhere
      E := TX.E.comap pr
      isSnc := isSnc_of_isEmpty (P ↘ Spec (.of k)) _
      smoothOfRelativeDimension := ⟨1 + d, hPd⟩
      m := 1 }
  have hEP : IsEmpty TP.E.ι := hE
  have hTP : TP.BMOClass (n + 2) 1 := ⟨le_rfl, ⟨1 + d, by omega, hPd⟩, rfl⟩
  -- the two closed embeddings of marked triples
  have ceX : MarkedTriple.ClosedEmbedding TP TX s := by
    refine ⟨⟨?_, rfl, ?_⟩, hTX.2.2⟩
    · change s ≫ pr ≫ (TX.X.left ↘ Spec (.of k)) = TX.X.left ↘ Spec (.of k)
      rw [← Category.assoc, hsp, Category.id_comp]
    · change TX.E = (TX.E.comap pr).comap s
      rw [← DivisorFamily.comap_comp, hsp, DivisorFamily.comap_id]
  have ceY : MarkedTriple.ClosedEmbedding TP TY (j ≫ s) := by
    refine ⟨⟨?_, ?_, ?_⟩, hj.2.trans hTX.2.2⟩
    · change (j ≫ s) ≫ pr ≫ (TX.X.left ↘ Spec (.of k)) = TY.X.left ↘ Spec (.of k)
      rw [Category.assoc, ← Category.assoc s, hsp, Category.id_comp, hj.1.1]
    · change TX.I.map s = TY.I.map (j ≫ s)
      rw [IdealSheafData.map_comp, hj.1.2.1]
    · change TY.E = (TX.E.comap pr).comap (j ≫ s)
      rw [← DivisorFamily.comap_comp, Category.assoc, hsp, Category.comp_id, hj.1.2.2]
  -- `X` and `Y` are smooth hypersurfaces of `X⁺`
  have hisoS : IsIso s.toImage :=
    IsClosedImmersion.isIso_of_ker_eq s s.imageι s.toImage s.toImage_imageι
      (Scheme.IdealSheafData.ker_subschemeι _).symm
  have hsX : IsSmoothDivisor s.ker := by
    have h1 : inv s.toImage ≫ s = s.imageι := (IsIso.inv_comp_eq _).mpr s.toImage_imageι.symm
    have h2 : s.ker.subschemeι ≫ (P ↘ Spec (.of k)) = inv s.toImage ≫
      (TX.X.left ↘ Spec (.of k)) := by
      change s.imageι ≫ pr ≫ (TX.X.left ↘ Spec (.of k)) = _
      rw [← h1, Category.assoc, ← Category.assoc s, hsp, Category.id_comp]
    have hinst : SmoothOfRelativeDimension (1 + d - 1) (s.ker.subschemeι ≫ (P ↘ Spec (.of k))) := by
      rw [show 1 + d - 1 = d by omega, h2]
      simpa using smoothOfRelativeDimension_comp 0 d (inv s.toImage) (TX.X.left ↘ Spec (.of k))
    exact isSmoothDivisor_of_smoothOfRelativeDimension (P ↘ Spec (.of k)) (1 + d) (by omega) s.ker
  have hisoY : IsIso (j ≫ s).toImage :=
    IsClosedImmersion.isIso_of_ker_eq (j ≫ s) (j ≫ s).imageι (j ≫ s).toImage
      (j ≫ s).toImage_imageι (Scheme.IdealSheafData.ker_subschemeι _).symm
  have hsY : IsSmoothDivisor (j ≫ s).ker := by
    have h1 : inv (j ≫ s).toImage ≫ (j ≫ s) = (j ≫ s).imageι :=
      (IsIso.inv_comp_eq _).mpr (j ≫ s).toImage_imageι.symm
    have h2 : (j ≫ s).ker.subschemeι ≫ (P ↘ Spec (.of k)) =
        inv (j ≫ s).toImage ≫ (TY.X.left ↘ Spec (.of k)) := by
      change (j ≫ s).imageι ≫ pr ≫ (TX.X.left ↘ Spec (.of k)) = _
      rw [← h1, Category.assoc, Category.assoc, ← Category.assoc s, hsp, Category.id_comp,
        hj.1.1]
    have hinst : SmoothOfRelativeDimension (1 + d - 1)
        ((j ≫ s).ker.subschemeι ≫ (P ↘ Spec (.of k))) := by
      rw [show 1 + d - 1 = d by omega, h2]
      simpa using smoothOfRelativeDimension_comp 0 d (inv (j ≫ s).toImage)
        (TY.X.left ↘ Spec (.of k))
    exact isSmoothDivisor_of_smoothOfRelativeDimension (P ↘ Spec (.of k)) (1 + d) (by omega)
      (j ≫ s).ker
  -- the hypersurface case twice, at the stage `n + 2`, and the injectivity of `s_*`
  have h1 := tower_bmo_one_eq_pushforward_of_isSmoothDivisor_ker base TP TX s ceX hEP hTP hsX
  have h2 := tower_bmo_one_eq_pushforward_of_isSmoothDivisor_ker base TP TY (j ≫ s) ceY hEP hTP hsY
  have h3 : ((((tower base (n + 1 + 1)).bmo 1).functor k).seq TX
      (bmoClass_of_closedEmbedding ceX hTP)).pushforward s =
      (((((tower base (n + 1 + 1)).bmo 1).functor k).seq TY
        (bmoClass_of_closedEmbedding ceY hTP)).pushforward j).pushforward s := by
    rw [← h1, h2, pushforward_comp]
  have h4 := pushforward_injective s h3
  -- back to the stage `n + 1` by coherence
  have hcX := tower_bmo_coherent base 1 (Nat.le_succ (n + 1)) TX
    (bmoClass_of_closedEmbedding ceX hTP) hTX
  have hcY := tower_bmo_coherent base 1 (Nat.le_succ (n + 1)) TY
    (bmoClass_of_closedEmbedding ceY hTP) (bmoClass_of_closedEmbedding hj hTX)
  rw [← hcX, h4, hcY]

end Hironaka.Stage
