/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Defs
import Hironaka.Algebra.Local.Order
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# Locally finitely generated ideal sheaves: basic properties

The elementary theory of the locally finitely generated ideal sheaves `IdealSheaf 𝒪` of a sheaf of
commutative rings `𝒪` on a topological space.

* A section belongs to `J` iff its germs lie in the stalk ideals (`mem_carrier_iff`), so an ideal
  sheaf is determined by its stalks (`ext`), and ideal sheaves are ordered stalkwise, with `⊤` and
  `⊥` the top and bottom elements.
* The ideal sheaf `ofStalks 𝒪 I hI` has the prescribed stalks (`stalkIdeal_ofStalks`), so the stalks
  of `ofGlobal 𝒪 f` are generated by the germs of the global sections `f_i`
  (`stalkIdeal_ofGlobal`), and those of `⊤`, `⊥` and `I * J` are the unit ideal, the zero ideal and
  the product (`stalkIdeal_top`, `stalkIdeal_bot`, `stalkIdeal_mul`). The sum `I + J` and the
  powers `J ^ n` are built the same way, with the stalkwise sup and power (`stalkIdeal_add`,
  `stalkIdeal_pow`).
* The support is closed (`isClosed_support`: a section with germ `1` at `a` equals `1` near `a`);
  the order vanishes exactly off the support (`ord_eq_zero_iff`) and reverses inclusions
  (`ord_anti`).
* For an ideal sheaf `J` of an analytic manifold, the predicate `IsIrreducible` of Hironaka's
  Definition 2 on the closed subspace defined by `J` (`IsNonsingular` and `IsReduced` are in
  `Defs.lean`, being statement vocabulary).
* `IsInvertible J`, for an ideal sheaf of any sheaf of rings: every stalk is generated by a single
  non-zero-divisor, Hironaka's invertible sheaf of ideals [Hir64, Ch. 0, §2], "everywhere of
  codimension one" [Hir64, Definition 2]; the stalkwise reading of
  `Scheme.IdealSheafData.IsInvertible`.

The spreading of a stalk identity `J_x = (g_1, …, g_k)` to an open neighbourhood of `x` is
`IdealSheaf.exists_opens_stalkIdeal_eq_span` of `Hironaka/Manifold/Snc/Spreading.lean`. On an
analytic manifold the cosupport, the order and its semicontinuity are studied in
`Hironaka/Manifold/IdealSheaf/Order.lean`, and the ideal sheaves of the analytic main theorems
are those of the structure sheaf (`AnalyticManifold.IdealSheaf`).
-/

@[expose] public section

open TopologicalSpace Opposite CategoryTheory

universe u

noncomputable section

namespace Manifold

variable {X : TopCat.{u}} (𝒪 : TopCat.Sheaf CommRingCat.{u} X)

namespace IdealSheaf

variable {𝒪} (J : IdealSheaf 𝒪)

theorem mem_stalkIdeal_iff {b : X} {s : 𝒪.presheaf.stalk b} :
    s ∈ J.stalkIdeal b ↔ ∃ (V : Opens X) (hb : b ∈ V) (g : 𝒪.presheaf.obj (op V)),
      g ∈ J.carrier V ∧ 𝒪.presheaf.germ V b hb g = s := Iff.rfl

theorem germ_mem_stalkIdeal {U : Opens X} {b : X} (hb : b ∈ U) {f : 𝒪.presheaf.obj (op U)}
    (hf : f ∈ J.carrier U) : 𝒪.presheaf.germ U b hb f ∈ J.stalkIdeal b :=
  ⟨U, hb, f, hf, rfl⟩

/-- Sections of the ideal are detected by their germs. -/
theorem mem_carrier_iff {U : Opens X} {f : 𝒪.presheaf.obj (op U)} :
    f ∈ J.carrier U ↔ ∀ x (hx : x ∈ U), 𝒪.presheaf.germ U x hx f ∈ J.stalkIdeal x := by
  refine ⟨fun hf x hx => J.germ_mem_stalkIdeal hx hf, fun h => J.mem_of_locally U f fun x hx => ?_⟩
  obtain ⟨V, hxV, g, hg, hgf⟩ := h x hx
  obtain ⟨W, hxW, iV, iU, hW⟩ := 𝒪.presheaf.germ_eq x hxV hx g f hgf
  exact ⟨W, iU, hxW, hW ▸ J.res_mem iV g hg⟩

theorem ext {I J : IdealSheaf 𝒪} (h : ∀ x, I.stalkIdeal x = J.stalkIdeal x) : I = J := by
  have hc : I.carrier = J.carrier := by
    funext U
    ext f
    rw [I.mem_carrier_iff, J.mem_carrier_iff]
    exact forall_congr' fun x => forall_congr' fun hx => by rw [h x]
  cases I
  cases J
  cases hc
  rfl

instance : LE (IdealSheaf 𝒪) := ⟨fun I J => ∀ x, I.stalkIdeal x ≤ J.stalkIdeal x⟩

theorem le_def {I J : IdealSheaf 𝒪} : I ≤ J ↔ ∀ x, I.stalkIdeal x ≤ J.stalkIdeal x := Iff.rfl

instance : PartialOrder (IdealSheaf 𝒪) where
  le_refl _ _ := le_rfl
  le_trans _ _ _ h h' x := (h x).trans (h' x)
  le_antisymm _ _ h h' := ext fun x => le_antisymm (h x) (h' x)

theorem carrier_mono {I J : IdealSheaf 𝒪} (h : I ≤ J) (U : Opens X) : I.carrier U ≤ J.carrier U :=
  fun _ hf => J.mem_carrier_iff.mpr fun x hx => h x (I.mem_carrier_iff.mp hf x hx)

@[simp]
theorem stalkIdeal_ofStalks (I : ∀ x : X, Ideal (𝒪.presheaf.stalk x)) (hI : HasLocalGenerators I)
    (b : X) : (ofStalks 𝒪 I hI).stalkIdeal b = I b := by
  obtain ⟨U, hb, k, f, hf⟩ := hI.exists_fin b
  obtain ⟨U', hb', k', f', -, hf'⟩ := (ofStalks 𝒪 I hI).locallyFG b
  refine le_antisymm ?_ ?_
  · rintro s ⟨V, hbV, g, hg, rfl⟩
    change g ∈ ⨅ (x : X) (hx : x ∈ V), (I x).comap (𝒪.presheaf.germ V x hx).hom at hg
    simp only [Ideal.mem_iInf, Ideal.mem_comap] at hg
    exact hg b hbV
  · rw [hf b hb, Ideal.span_le]
    rintro s ⟨i, rfl⟩
    refine ⟨U, hb, f i, ?_, rfl⟩
    change f i ∈ ⨅ (x : X) (hx : x ∈ U), (I x).comap (𝒪.presheaf.germ U x hx).hom
    simp only [Ideal.mem_iInf, Ideal.mem_comap]
    intro x hx
    rw [hf x hx]
    exact Ideal.subset_span ⟨i, rfl⟩

variable (𝒪) in
/-- The stalk at `x` of the ideal sheaf generated by global sections `f₁, …, f_k` is generated by
their germs at `x`. -/
theorem stalkIdeal_ofGlobal {k : ℕ} (f : Fin k → 𝒪.presheaf.obj (op ⊤)) (x : X) :
    (ofGlobal 𝒪 f).stalkIdeal x =
      Ideal.span (Set.range fun i => 𝒪.presheaf.germ ⊤ x trivial (f i)) :=
  stalkIdeal_ofStalks _ _ x

/-! ### The unit and zero ideal sheaves, sums, products, powers -/

@[simp] theorem stalkIdeal_top (x : X) : (⊤ : IdealSheaf 𝒪).stalkIdeal x = ⊤ :=
  stalkIdeal_ofStalks _ _ x

@[simp] theorem stalkIdeal_bot (x : X) : (⊥ : IdealSheaf 𝒪).stalkIdeal x = ⊥ :=
  stalkIdeal_ofStalks _ _ x

instance : BoundedOrder (IdealSheaf 𝒪) where
  le_top I x := by rw [stalkIdeal_top]; exact le_top
  bot_le I x := by rw [stalkIdeal_bot]; exact bot_le

theorem carrier_top (U : Opens X) : (⊤ : IdealSheaf 𝒪).carrier U = ⊤ :=
  Ideal.eq_top_iff_one _ |>.mpr <| mem_carrier_iff _ |>.mpr fun x hx => by
    rw [stalkIdeal_top]; exact Submodule.mem_top

/-- The zero ideal sheaf has no nonzero sections (the sheaf condition of `𝒪`). -/
theorem carrier_bot (U : Opens X) : (⊥ : IdealSheaf 𝒪).carrier U = ⊥ := by
  ext f
  rw [mem_carrier_iff, Ideal.mem_bot]
  constructor
  · intro h
    refine TopCat.Presheaf.section_ext 𝒪 U f 0 fun x hx => ?_
    have := h x hx
    rw [stalkIdeal_bot, Ideal.mem_bot] at this
    rw [this, map_zero]
  · rintro rfl x hx
    rw [stalkIdeal_bot, Ideal.mem_bot, map_zero]

/-- The germs of restricted sections are the germs of the sections. -/
theorem range_germ_map {U W : Opens X} (i : W ⟶ U) {b : X} (hb : b ∈ W) {ι : Type*}
    (f : ι → 𝒪.presheaf.obj (op U)) :
    (Set.range fun j => 𝒪.presheaf.germ W b hb (𝒪.presheaf.map i.op (f j))) =
      Set.range fun j => 𝒪.presheaf.germ U b (i.le hb) (f j) := by
  simp only [TopCat.Presheaf.germ_res_apply]

theorem hasLocalGenerators_sup (I J : IdealSheaf 𝒪) :
    HasLocalGenerators fun x => I.stalkIdeal x ⊔ J.stalkIdeal x := by
  intro a
  obtain ⟨U, haU, k, f, -, hf⟩ := I.exists_generators a
  obtain ⟨V, haV, l, g, -, hg⟩ := J.exists_generators a
  refine ⟨U ⊓ V, Opens.mem_inf.mpr ⟨haU, haV⟩, Fin k ⊕ Fin l, inferInstance,
    Sum.elim (fun i => 𝒪.presheaf.map (homOfLE inf_le_left).op (f i))
      (fun j => 𝒪.presheaf.map (homOfLE inf_le_right).op (g j)), fun b hb => ?_⟩
  obtain ⟨hbU, hbV⟩ := Opens.mem_inf.mp hb
  change I.stalkIdeal b ⊔ J.stalkIdeal b = _
  rw [hf b hbU, hg b hbV, ← Submodule.span_union]
  congr 1
  rw [show (fun p => 𝒪.presheaf.germ (U ⊓ V) b hb (Sum.elim
      (fun i => 𝒪.presheaf.map (homOfLE inf_le_left).op (f i))
      (fun j => 𝒪.presheaf.map (homOfLE inf_le_right).op (g j)) p)) =
    Sum.elim (fun i => 𝒪.presheaf.germ (U ⊓ V) b hb (𝒪.presheaf.map (homOfLE inf_le_left).op (f i)))
      (fun j => 𝒪.presheaf.germ (U ⊓ V) b hb (𝒪.presheaf.map (homOfLE inf_le_right).op (g j)))
    from funext fun p => by cases p <;> rfl]
  rw [Set.Sum.elim_range, range_germ_map, range_germ_map]

instance : Add (IdealSheaf 𝒪) := ⟨fun I J => ofStalks 𝒪 _ (hasLocalGenerators_sup I J)⟩

@[simp] theorem stalkIdeal_add (I J : IdealSheaf 𝒪) (x : X) :
    (I + J).stalkIdeal x = I.stalkIdeal x ⊔ J.stalkIdeal x :=
  stalkIdeal_ofStalks _ _ x

@[simp] theorem stalkIdeal_mul (I J : IdealSheaf 𝒪) (x : X) :
    (I * J).stalkIdeal x = I.stalkIdeal x * J.stalkIdeal x :=
  stalkIdeal_ofStalks _ _ x

/-- Powers: `J ^ 0 = ⊤`, `J ^ (n + 1) = J ^ n * J`. -/
def pow (J : IdealSheaf 𝒪) : ℕ → IdealSheaf 𝒪
  | 0 => ⊤
  | n + 1 => J.pow n * J

instance : Pow (IdealSheaf 𝒪) ℕ := ⟨pow⟩

@[simp] theorem stalkIdeal_pow (J : IdealSheaf 𝒪) (n : ℕ) (x : X) :
    (J ^ n).stalkIdeal x = J.stalkIdeal x ^ n := by
  induction n with
  | zero =>
    change (⊤ : IdealSheaf 𝒪).stalkIdeal x = _
    rw [stalkIdeal_top, pow_zero, Ideal.one_eq_top]
  | succ n ih =>
    change (J.pow n * J).stalkIdeal x = _
    rw [stalkIdeal_mul, pow_succ]
    exact congrArg (· * J.stalkIdeal x) ih

/-! ### The cosupport and the order -/

@[simp]
theorem mem_support {x : X} : x ∈ J.support ↔ J.stalkIdeal x ≠ ⊤ := Iff.rfl

/-- The cosupport is closed: a section with germ `1` at `a` equals `1` near `a`. -/
theorem isOpen_compl_support : IsOpen J.supportᶜ := by
  rw [isOpen_iff_forall_mem_open]
  intro x hx
  have h1 : (1 : 𝒪.presheaf.stalk x) ∈ J.stalkIdeal x := by
    rw [not_not.mp hx]; exact Submodule.mem_top
  obtain ⟨V, hxV, g, hg, hg1⟩ := h1
  have hgerm : 𝒪.presheaf.germ V x hxV g = 𝒪.presheaf.germ V x hxV 1 := by rw [hg1, map_one]
  obtain ⟨W, hxW, i, i', hW⟩ := 𝒪.presheaf.germ_eq x hxV hxV g 1 hgerm
  refine ⟨W, fun y hy => ?_, W.2, hxW⟩
  rw [Set.mem_compl_iff, mem_support, not_not, Ideal.eq_top_iff_one]
  have hmem : 𝒪.presheaf.map i.op g ∈ J.carrier W := J.res_mem i g hg
  rw [hW, map_one] at hmem
  simpa only [map_one] using J.germ_mem_stalkIdeal hy hmem

theorem isClosed_support : IsClosed J.support :=
  isOpen_compl_iff.mp J.isOpen_compl_support

/-- In a local ring, a span is the unit ideal iff one of the generators is a unit. -/
theorem _root_.Ideal.span_eq_top_iff_exists_isUnit {R : Type*} [CommRing R] [IsLocalRing R]
    (S : Set R) : Ideal.span S = ⊤ ↔ ∃ s ∈ S, IsUnit s := by
  constructor
  · intro h
    by_contra hcon
    simp only [not_exists, not_and] at hcon
    have hle : Ideal.span S ≤ IsLocalRing.maximalIdeal R :=
      Ideal.span_le.mpr fun s hs => (IsLocalRing.mem_maximalIdeal s).mpr (hcon s hs)
    have h1 : (1 : R) ∈ IsLocalRing.maximalIdeal R := hle (h ▸ Submodule.mem_top)
    exact (IsLocalRing.mem_maximalIdeal 1).mp h1 isUnit_one
  · rintro ⟨s, hs, ⟨u, rfl⟩⟩
    refine (Ideal.eq_top_iff_one _).mpr ?_
    simpa using Ideal.mul_mem_left _ (↑u⁻¹ : R) (Ideal.subset_span hs)

/-- The ideal sheaf is **invertible**: at every point its stalk is generated by a single
non-zero-divisor, i.e. `J` is locally free of rank one — Hironaka's invertible sheaf of ideals
[Hir64, Ch. 0, §2], "everywhere of codimension one" [Hir64, Ch. 0, §5, Definition 2, p. 141], the
condition on the boundary `E` in Main Theorem II'(N). Read at the stalks, as every predicate of
the ideal-sheaf vocabulary is (no main theorem states it, which is why it is not in `Defs.lean`);
compare `Scheme.IdealSheafData.IsInvertible` on schemes, whose stalkwise reading this is
(`isInvertible_iff_forall_stalkIdeal_eq_span`, on a locally Noetherian scheme). -/
def IsInvertible (J : IdealSheaf 𝒪) : Prop :=
  ∀ x : X, ∃ a : 𝒪.presheaf.stalk x,
    a ∈ nonZeroDivisors (𝒪.presheaf.stalk x) ∧ J.stalkIdeal x = Ideal.span {a}

section Order

variable [∀ x : X, IsLocalRing (𝒪.presheaf.stalk x)]

theorem ord_eq_zero_iff {x : X} : J.ord x = 0 ↔ x ∉ J.support := by
  rw [ord, IsLocalRing.ord_eq_zero_iff, mem_support, not_not]

theorem ord_eq_top_of_stalkIdeal_eq_bot {x : X} (h : J.stalkIdeal x = ⊥) : J.ord x = ⊤ := by
  rw [ord, h]; exact IsLocalRing.ord_bot

theorem ord_anti {I J : IdealSheaf 𝒪} (h : I ≤ J) (x : X) : J.ord x ≤ I.ord x :=
  IsLocalRing.ord_anti (h x)

/-- On a generating open set the cosupport is the set of points where every generator is a
non-unit germ. -/
theorem stalkIdeal_eq_top_iff_exists_isUnit {U : Opens X} {k : ℕ}
    {f : Fin k → 𝒪.presheaf.obj (op U)} {b : X} (hb : b ∈ U)
    (hf : J.stalkIdeal b = Ideal.span (Set.range fun i => 𝒪.presheaf.germ U b hb (f i))) :
    J.stalkIdeal b = ⊤ ↔ ∃ i, IsUnit (𝒪.presheaf.germ U b hb (f i)) := by
  rw [hf, Ideal.span_eq_top_iff_exists_isUnit]
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, hu⟩; exact ⟨i, hu⟩
  · rintro ⟨i, hu⟩; exact ⟨_, ⟨i, rfl⟩, hu⟩

end Order

end IdealSheaf

end Manifold

end

/-! ### Predicates on the closed subspace defined by an ideal sheaf of an analytic manifold -/

namespace AnalyticManifold

open scoped Manifold ContDiff

variable {𝕜 : Type} [NontriviallyNormedField 𝕜] {E : Type*} [NormedAddCommGroup E]
  [NormedSpace 𝕜 E]

namespace IdealSheaf

variable {M : AnalyticManifold.{u} 𝕜 E}

/-- The closed analytic subspace defined by `J` is **irreducible** (and nonempty): its set of points
is not the union of two proper Zariski-closed subsets, the cosupports of locally finitely
generated ideal sheaves [BM97, Definitions and remarks 3.9] — Hironaka's "maximal reduced
irreducible analytic subspace" [Hir64, Definition 2, p. 141], as a condition on the set of
points. -/
def IsIrreducible (J : IdealSheaf M) : Prop :=
  J.support.Nonempty ∧ ∀ J₁ J₂ : IdealSheaf M, J.support = J₁.support ∪ J₂.support →
    J.support = J₁.support ∨ J.support = J₂.support

end IdealSheaf

end AnalyticManifold
