/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.AnalyticManifold.Defs
public import Mathlib.RingTheory.RegularLocalRing.Defs
public import Hironaka.Algebra.Local.Defs
public import Hironaka.Manifold.StructureSheaf.Defs
import Hironaka.Manifold.Germ.StalkMap
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# Locally finitely generated ideal sheaves

The ideal sheaves of the `Hironaka` library: for a sheaf of commutative rings `𝒪` on a
topological space `X` (the structure sheaf of an analytic manifold in the applications), a **locally
finitely generated ideal sheaf** `IdealSheaf 𝒪` is a sub-presheaf of ideals `J(U) ⊆ 𝒪(U)` satisfying
the sheaf condition (a section locally in the ideal is in the ideal) and local finite generation:
every point has an open neighbourhood `U` and finitely many sections `f_1, …, f_k ∈ J(U)` whose
germs generate the stalk ideal `J_b` at every `b ∈ U`. This is Hironaka's "coherent sheaf of ideals"
on a non-singular analytic space [Hir64, Main Theorem II''(N), p. 158], coherence being replaced by
local finite generation, and Bierstone–Milman's "sheaf of ideals of finite type" [BM97, §3].

* The stalk ideal `stalkIdeal J b` is the set of germs at `b` of sections of `J` (`stalkIdealOf`).
* Any family of stalk ideals with local generators (`HasLocalGenerators`) is the family of stalks
  of an ideal sheaf (`ofStalks`); this is how the ideal sheaf `ofGlobal 𝒪 f` generated by finitely
  many global sections, the unit and zero ideal sheaves `⊤`, `⊥` and the product `I * J` are
  built, the last with the stalkwise product.
* `IsNonzeroEverywhere J`: every stalk is nonzero, Hironaka's "coherent sheaf of non-zero ideals"
  [Hir64, Main Theorem II''(N), p. 158].
* `support J = {a | J_a ≠ 𝒪_a}`, the set of points of the closed subspace defined by `J`
  (Kollár's `cosupp`; Bierstone–Milman's `V(J)` [BM97, Introduction]).
* When the stalks are local rings, `ord J x` is the order `ν_x(J) = max {p | J_x ⊆ 𝔪_x^p}` of the
  stalk ideal (Hironaka's `ν(J_x)` [Hir64, p. 133]; [Kol07, Definition 47]; [BM97, §3]), the
  `Hironaka` library's `IsLocalRing.ord`.

On analytic manifolds:

* For an analytic map `φ : N → M` and an ideal sheaf `J` of the structure sheaf of `M`, the
  **pullback** `IdealSheaf.pullback J φ hφ` is the ideal sheaf generated by the `f ∘ φ`, `f` a
  section of `J`: Hironaka's total transform `f⁻¹(J)`, "the one generated by `J` with reference to
  `f`" [Hir64, pp. 141–142], and Bierstone–Milman's `σ⁻¹(I) := σ^*(I) · 𝒪` [BM97, Theorem 1.10].
  Its stalk at `b` is the image of `J_{φ b}` under the stalk map `germMap φ hφ b`.
* **The vanishing ideal** `vanishingStalk Z x` of a set `Z` at `x` is the ideal of the germs of
  analytic functions at `x` whose function germ (`stalkToGerm`) vanishes on `Z` near `x`
  (`Germ.VanishesOn`, `vanishingGermIdeal`): the stalk of Hironaka's reduced structure `red` on
  the closed set `Z` [Hir64, Main Theorem II'(N) (iii), p. 156]; Bierstone–Milman's reduced space,
  `𝓘_{X_red} = √𝓘_X` [BM97, Remark 3.14]. Whether these stalks are the stalks of a locally finitely
  generated ideal sheaf (coherence of the ideal of an analytic set) is a separate question, left as
  a guard in the definitions that use them.

For a bundled analytic manifold `M`, `AnalyticManifold.IdealSheaf M` is the type of the ideal
sheaves of its structure sheaf; closed analytic subspaces of `M` (centres, boundaries) are given by
their ideal sheaves. With the unit ideal `⊤`, the inverse image `J.pullback f f.contMDiff` along an
analytic map `f`, its case `restrict` for the inclusion of an open subset, the product `I * J`, the
order `J.ord x` and
`J.IsNonzeroEverywhere`, these are the operations the analytic main theorems use. `stalkRing M x` is
the local ring `𝒪_{M,x}`, and `IsNonsingular J` says that the closed subspace defined by `J` is
non-singular: every one of its points is simple, the quotient `𝒪_{M,x}/J_x` being a regular local
ring [Hir64, p. 121]. `IsReduced J` says that the closed subspace is reduced (every stalk `J_x` is
a radical ideal), and `regularLocus J` is its set of simple points, Włodarczyk's `Reg(Y)`
[Wlo09, Theorem 2.0.2 (2)].
-/

@[expose] public section

open TopologicalSpace Opposite CategoryTheory

universe u v

noncomputable section

namespace Manifold

section Generic

variable {X : TopCat.{u}} (𝒪 : TopCat.Sheaf CommRingCat.{u} X)

/-- The stalk ideal at `b` of a family of ideals of sections closed under restriction: the germs
at `b` of the sections of the ideals (an ideal by common refinement of the open sets). -/
def stalkIdealOf (carrier : ∀ U : Opens X, Ideal (𝒪.presheaf.obj (op U)))
    (res_mem : ∀ {U V : Opens X} (i : U ⟶ V) (f : 𝒪.presheaf.obj (op V)),
      f ∈ carrier V → 𝒪.presheaf.map i.op f ∈ carrier U) (b : X) :
    Ideal (𝒪.presheaf.stalk b) where
  carrier := {s | ∃ (V : Opens X) (hb : b ∈ V) (g : 𝒪.presheaf.obj (op V)),
    g ∈ carrier V ∧ 𝒪.presheaf.germ V b hb g = s}
  zero_mem' := ⟨⊤, trivial, 0, zero_mem _, map_zero _⟩
  add_mem' := by
    rintro s t ⟨V, hbV, g, hg, rfl⟩ ⟨W, hbW, h, hh, rfl⟩
    refine ⟨V ⊓ W, Opens.mem_inf.mpr ⟨hbV, hbW⟩, 𝒪.presheaf.map (homOfLE inf_le_left).op g +
      𝒪.presheaf.map (homOfLE inf_le_right).op h,
      add_mem (res_mem _ _ hg) (res_mem _ _ hh), ?_⟩
    rw [map_add, TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply]
  smul_mem' := by
    rintro r s ⟨V, hbV, g, hg, rfl⟩
    obtain ⟨W, hbW, h, rfl⟩ := 𝒪.presheaf.exists_germ_eq r
    refine ⟨V ⊓ W, Opens.mem_inf.mpr ⟨hbV, hbW⟩, 𝒪.presheaf.map (homOfLE inf_le_right).op h *
      𝒪.presheaf.map (homOfLE inf_le_left).op g,
      Ideal.mul_mem_left _ _ (res_mem _ _ hg), ?_⟩
    rw [smul_eq_mul, map_mul, TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply]

/-- A **locally finitely generated ideal sheaf** of the sheaf of rings `𝒪`: a sub-presheaf of
ideals satisfying the sheaf condition, whose stalk ideals are generated near every point by
finitely many sections. -/
structure IdealSheaf where
  /-- The ideal of sections over each open set. -/
  carrier : ∀ U : Opens X, Ideal (𝒪.presheaf.obj (op U))
  /-- Restriction preserves the ideals (a sub-presheaf). -/
  res_mem : ∀ {U V : Opens X} (i : U ⟶ V) (f : 𝒪.presheaf.obj (op V)),
    f ∈ carrier V → 𝒪.presheaf.map i.op f ∈ carrier U
  /-- The sheaf condition of a sub-presheaf: a section locally in the ideal is in the ideal. -/
  mem_of_locally : ∀ (U : Opens X) (f : 𝒪.presheaf.obj (op U)),
    (∀ x ∈ U, ∃ (V : Opens X) (i : V ⟶ U), x ∈ V ∧ 𝒪.presheaf.map i.op f ∈ carrier V) →
    f ∈ carrier U
  /-- Local finite generation. -/
  locallyFG : ∀ a : X, ∃ (U : Opens X) (_ : a ∈ U) (k : ℕ) (f : Fin k → 𝒪.presheaf.obj (op U)),
    (∀ i, f i ∈ carrier U) ∧ ∀ b (hb : b ∈ U),
      stalkIdealOf 𝒪 carrier res_mem b =
        Ideal.span (Set.range fun i => 𝒪.presheaf.germ U b hb (f i))

namespace IdealSheaf

variable {𝒪} (J : IdealSheaf 𝒪)

/-- The stalk ideal `J_b ⊆ 𝒪_b`. -/
abbrev stalkIdeal (b : X) : Ideal (𝒪.presheaf.stalk b) := stalkIdealOf 𝒪 J.carrier J.res_mem b

/-- Local finite generation, read through `stalkIdeal`: near every point, finitely many sections
of `J` generate the stalk ideal at every point of the neighbourhood. -/
theorem exists_generators (a : X) :
    ∃ (U : Opens X) (_ : a ∈ U) (k : ℕ) (f : Fin k → 𝒪.presheaf.obj (op U)),
      (∀ i, f i ∈ J.carrier U) ∧ ∀ b (hb : b ∈ U),
        J.stalkIdeal b = Ideal.span (Set.range fun i => 𝒪.presheaf.germ U b hb (f i)) :=
  J.locallyFG a

/-- A family of stalk ideals has local generators when every point has an open neighbourhood
and finitely many sections over it whose germs span the ideals at every point of it. -/
def HasLocalGenerators (I : ∀ x : X, Ideal (𝒪.presheaf.stalk x)) : Prop :=
  ∀ a : X, ∃ (U : Opens X) (_ : a ∈ U) (ι : Type) (_ : Fintype ι) (f : ι → 𝒪.presheaf.obj (op U)),
    ∀ b (hb : b ∈ U), I b = Ideal.span (Set.range fun i => 𝒪.presheaf.germ U b hb (f i))

theorem HasLocalGenerators.exists_fin {I : ∀ x : X, Ideal (𝒪.presheaf.stalk x)}
    (hI : HasLocalGenerators I) (a : X) :
    ∃ (U : Opens X) (_ : a ∈ U) (k : ℕ) (f : Fin k → 𝒪.presheaf.obj (op U)),
      ∀ b (hb : b ∈ U), I b = Ideal.span (Set.range fun i => 𝒪.presheaf.germ U b hb (f i)) := by
  obtain ⟨U, ha, ι, _, f, hf⟩ := hI a
  refine ⟨U, ha, Fintype.card ι, f ∘ (Fintype.equivFin ι).symm, fun b hb => ?_⟩
  rw [hf b hb]
  congr 1
  exact ((Fintype.equivFin ι).symm.surjective.range_comp
    fun i => 𝒪.presheaf.germ U b hb (f i)).symm

variable (𝒪) in
/-- The ideal sheaf with prescribed stalk ideals: the sections whose germs lie in the stalk
ideals. -/
def ofStalks (I : ∀ x : X, Ideal (𝒪.presheaf.stalk x)) (hI : HasLocalGenerators I) :
    IdealSheaf 𝒪 where
  carrier U := ⨅ (x : X) (hx : x ∈ U), (I x).comap (𝒪.presheaf.germ U x hx).hom
  res_mem {U V} i f hf := by
    simp only [Ideal.mem_iInf, Ideal.mem_comap] at hf ⊢
    intro x hx
    change 𝒪.presheaf.germ U x hx (𝒪.presheaf.map i.op f) ∈ I x
    rw [TopCat.Presheaf.germ_res_apply]
    exact hf x (i.le hx)
  mem_of_locally U f h := by
    simp only [Ideal.mem_iInf, Ideal.mem_comap]
    intro x hx
    obtain ⟨V, i, hxV, hV⟩ := h x hx
    simp only [Ideal.mem_iInf, Ideal.mem_comap] at hV
    have := hV x hxV
    change 𝒪.presheaf.germ V x hxV (𝒪.presheaf.map i.op f) ∈ I x at this
    rwa [TopCat.Presheaf.germ_res_apply] at this
  locallyFG a := by
    obtain ⟨U, ha, k, f, hf⟩ := hI.exists_fin a
    have hmem : ∀ i, f i ∈ ⨅ (x : X) (hx : x ∈ U), (I x).comap (𝒪.presheaf.germ U x hx).hom := by
      intro i
      simp only [Ideal.mem_iInf, Ideal.mem_comap]
      intro x hx
      rw [hf x hx]
      exact Ideal.subset_span ⟨i, rfl⟩
    refine ⟨U, ha, k, f, hmem, fun b hb => le_antisymm ?_ ?_⟩
    · rintro s ⟨V, hbV, g, hg, rfl⟩
      rw [← hf b hb]
      simp only [Ideal.mem_iInf, Ideal.mem_comap] at hg
      exact hg b hbV
    · rw [Ideal.span_le]
      rintro s ⟨i, rfl⟩
      exact ⟨U, hb, f i, hmem i, rfl⟩

variable (𝒪) in
/-- The ideal sheaf generated by finitely many global sections `f₁, …, f_k` (Hironaka's "sheaf of
ideals generated by a finite number of regular analytic `K`-functions on `G`"):
`IdealSheaf.ofStalks` with the constant family of generators. -/
def ofGlobal {k : ℕ} (f : Fin k → 𝒪.presheaf.obj (op ⊤)) : IdealSheaf 𝒪 :=
  IdealSheaf.ofStalks 𝒪 (fun x => Ideal.span (Set.range fun i => 𝒪.presheaf.germ ⊤ x trivial (f i)))
    fun _ => ⟨⊤, trivial, Fin k, inferInstance, f, fun _ _ => rfl⟩

/-! ### The unit and zero ideal sheaves, products -/

theorem hasLocalGenerators_top :
    HasLocalGenerators (fun x : X => (⊤ : Ideal (𝒪.presheaf.stalk x))) :=
  fun _ => ⟨⊤, trivial, Unit, inferInstance, fun _ => 1, fun b hb => by
    rw [eq_comm, Ideal.eq_top_iff_one]
    exact Ideal.subset_span ⟨(), map_one _⟩⟩

theorem hasLocalGenerators_bot :
    HasLocalGenerators (fun x : X => (⊥ : Ideal (𝒪.presheaf.stalk x))) :=
  fun _ => ⟨⊤, trivial, Empty, inferInstance, fun i => i.elim, fun _ _ => by
    simp only [Set.range_eq_empty, Ideal.span_empty]⟩

instance : Top (IdealSheaf 𝒪) := ⟨ofStalks 𝒪 _ hasLocalGenerators_top⟩
instance : Bot (IdealSheaf 𝒪) := ⟨ofStalks 𝒪 _ hasLocalGenerators_bot⟩

theorem hasLocalGenerators_mul (I J : IdealSheaf 𝒪) :
    HasLocalGenerators fun x => I.stalkIdeal x * J.stalkIdeal x := by
  intro a
  obtain ⟨U, haU, k, f, -, hf⟩ := I.exists_generators a
  obtain ⟨V, haV, l, g, -, hg⟩ := J.exists_generators a
  refine ⟨U ⊓ V, Opens.mem_inf.mpr ⟨haU, haV⟩, Fin k × Fin l, inferInstance,
    fun p => 𝒪.presheaf.map (homOfLE inf_le_left).op (f p.1) *
      𝒪.presheaf.map (homOfLE inf_le_right).op (g p.2), fun b hb => ?_⟩
  obtain ⟨hbU, hbV⟩ := Opens.mem_inf.mp hb
  change I.stalkIdeal b * J.stalkIdeal b = _
  rw [hf b hbU, hg b hbV, Ideal.span_mul_span]
  congr 1
  ext s
  simp only [Set.mem_range, Set.mem_mul, map_mul, TopCat.Presheaf.germ_res_apply, Prod.exists]
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, _, ⟨j, rfl⟩, rfl⟩
    exact ⟨i, j, rfl⟩
  · rintro ⟨i, j, rfl⟩
    exact ⟨_, ⟨i, rfl⟩, _, ⟨j, rfl⟩, rfl⟩

instance : Mul (IdealSheaf 𝒪) := ⟨fun I J => ofStalks 𝒪 _ (hasLocalGenerators_mul I J)⟩

/-! ### Nonzero stalks, the cosupport, the order -/

/-- Hironaka's "coherent sheaf of non-zero ideals" [Hir64, Main Theorem II''(N), p. 158]: every
stalk is nonzero. -/
def IsNonzeroEverywhere (J : IdealSheaf 𝒪) : Prop := ∀ x, J.stalkIdeal x ≠ ⊥

/-- The cosupport `V(J) = {a | J_a ≠ 𝒪_a}`, the set of points of the closed subspace defined by
`J` (Kollár's `cosupp`; [BM97, Introduction]). -/
def support (J : IdealSheaf 𝒪) : Set X := {x | J.stalkIdeal x ≠ ⊤}

section Order

variable [∀ x : X, IsLocalRing (𝒪.presheaf.stalk x)]

/-- The order `ν_a(J) = max {p | J_a ⊆ 𝔪_a^p}` of the ideal sheaf at `a` (Hironaka's `ν(J_x)`
[Hir64, p. 133]; [Kol07, Definition 47]; [BM97, §3]): the `Hironaka` library's `IsLocalRing.ord`
of the stalk ideal. -/
noncomputable def ord (J : IdealSheaf 𝒪) (x : X) : ℕ∞ := IsLocalRing.ord (J.stalkIdeal x)

end Order

end IdealSheaf

end Generic

/-! ### The pullback along an analytic map -/

section Pullback

open Filter
open scoped Manifold ContDiff Topology

variable {𝕜 : Type} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  {E' : Type*} [NormedAddCommGroup E'] [NormedSpace 𝕜 E']
  {N : Type v} [TopologicalSpace N] [ChartedSpace E' N]

variable (φ : N → M) (hφ : ContMDiff 𝓘(𝕜, E') 𝓘(𝕜, E) ω φ)

theorem hasLocalGenerators_pullback (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf.HasLocalGenerators fun b : N => Ideal.map (germMap φ hφ b) (J.stalkIdeal (φ b)) := by
  intro b
  obtain ⟨U, hU, k, f, -, hf⟩ := J.exists_generators (φ b)
  refine ⟨preimageOpens φ hφ U, (mem_preimageOpens φ hφ).mpr hU, Fin k, inferInstance,
    fun i => comapSection φ hφ (f i), fun c hc => ?_⟩
  dsimp only
  have hcU : φ c ∈ U := (mem_preimageOpens φ hφ).mp hc
  rw [hf (φ c) hcU, Ideal.map_span, ← Set.range_comp]
  exact congrArg Ideal.span (congrArg Set.range (funext fun i => germMap_germ φ hφ hcU (f i)))

/-- **The pullback** `φ^* J` of an ideal sheaf under an analytic map, the ideal sheaf generated
by the `f ∘ φ`, `f` a section of `J` (Hironaka's total transform [Hir64, pp. 141–142];
Bierstone–Milman's `σ⁻¹(I)` [BM97, Theorem 1.10]). -/
def IdealSheaf.pullback (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf (structureSheaf 𝕜 E' N) :=
  IdealSheaf.ofStalks _ _ (hasLocalGenerators_pullback φ hφ J)

end Pullback

end Manifold

end

/-! ### The vanishing ideal of a set -/

namespace Manifold

section Vanishing

open Filter Topology
open scoped Manifold ContDiff

variable {𝕜 : Type} [NontriviallyNormedField 𝕜] {M : Type*} [TopologicalSpace M]

/-- The function germ `g` at `x` **vanishes on `Z` near `x`**: some (equivalently every)
representative is zero on `Z ∩ N` for a neighbourhood `N` of `x`. -/
def Germ.VanishesOn (Z : Set M) (x : M) (g : (𝓝 x).Germ 𝕜) : Prop :=
  Filter.Germ.liftOn g (fun f => ∀ᶠ y in 𝓝[Z] x, f y = 0) fun f f' hff' => by
    have e : f =ᶠ[𝓝[Z] x] f' := hff'.filter_mono nhdsWithin_le_nhds
    refine propext ⟨fun h => (h.and e).mono fun y hy => ?_, fun h => (h.and e).mono fun y hy => ?_⟩
    · rw [← hy.2]; exact hy.1
    · rw [hy.2]; exact hy.1

/-- The function germs at `x` vanishing on `Z` near `x` form an ideal of the germ ring. -/
def vanishingGermIdeal (Z : Set M) (x : M) : Ideal ((𝓝 x).Germ 𝕜) where
  carrier := {g | Germ.VanishesOn Z x g}
  zero_mem' := by
    change Germ.VanishesOn Z x ((0 : M → 𝕜) : (𝓝 x).Germ 𝕜)
    exact Eventually.of_forall fun _ => rfl
  add_mem' {a b} := Filter.Germ.inductionOn a fun f => Filter.Germ.inductionOn b fun g
    (hf : Germ.VanishesOn Z x (f : (𝓝 x).Germ 𝕜)) (hg : Germ.VanishesOn Z x (g : (𝓝 x).Germ 𝕜)) =>
    show Germ.VanishesOn Z x ((f + g : M → 𝕜) : (𝓝 x).Germ 𝕜) from
      (hf.and hg).mono fun y hy => by simp only [Pi.add_apply, hy.1, hy.2, add_zero]
  smul_mem' c a := Filter.Germ.inductionOn c fun h => Filter.Germ.inductionOn a fun f
    (hf : Germ.VanishesOn Z x (f : (𝓝 x).Germ 𝕜)) =>
    show Germ.VanishesOn Z x ((h * f : M → 𝕜) : (𝓝 x).Germ 𝕜) from
      hf.mono fun y hy => by simp only [Pi.mul_apply, hy, mul_zero]

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] [ChartedSpace E M]

/-- **The vanishing ideal of `Z` at `x`**: the germs of analytic functions at `x` (stalk of `𝒪_M`)
whose function germ vanishes on `Z` near `x`; the stalk of Hironaka's reduced structure `red` on
the closed set `Z` [Hir64, Main Theorem II'(N) (iii), p. 156]. It depends on `Z` only through
`closure Z` (a continuous germ vanishing on `Z` near `x` vanishes on `closure Z` near `x`); it is
applied to closed sets. -/
noncomputable def vanishingStalk (Z : Set M) (x : M) :
    Ideal ((structureSheaf 𝕜 E M).presheaf.stalk x) :=
  (vanishingGermIdeal Z x).comap (stalkToGerm 𝓘(𝕜, E) ω M x)

end Vanishing

end Manifold

/-! ### The ideal sheaves of an analytic manifold -/

namespace AnalyticManifold

open scoped Manifold ContDiff

variable {𝕜 : Type} [NontriviallyNormedField 𝕜] {E : Type*} [NormedAddCommGroup E]
  [NormedSpace 𝕜 E]

/-- A locally finitely generated ideal sheaf of the sheaf of analytic functions on `M`: Hironaka's
"coherent sheaf of ideals" on a non-singular analytic space [Hir64, Main Theorem II''(N), p. 158].
Closed analytic subspaces of `M` (centres, boundaries) are given by their ideal sheaves. -/
abbrev IdealSheaf (M : AnalyticManifold.{u} 𝕜 E) : Type u :=
  Manifold.IdealSheaf (Manifold.structureSheaf 𝕜 E M)

namespace IdealSheaf

variable {M N : AnalyticManifold.{u} 𝕜 E}

/-- The stalk `𝒪_{M,x}` of the sheaf of analytic functions at `x`, named so that the predicates
below can speak of it. -/
abbrev stalkRing (M : AnalyticManifold.{u} 𝕜 E) (x : M) : Type u :=
  (Manifold.structureSheaf 𝕜 E M).presheaf.stalk x

/-- The closed analytic subspace defined by `J` is **non-singular**: every point of it is simple,
i.e. the local ring `𝒪_{M,x}/J_x` is regular [Hir64, p. 121] (Hironaka: by the Jacobian criterion
and the implicit function theorem, a simple point has a neighbourhood isomorphic to an open subset
of `𝕜ⁿ`). Vacuous on the empty subspace. -/
def IsNonsingular (J : IdealSheaf M) : Prop :=
  ∀ x ∈ J.support, IsRegularLocalRing (stalkRing M x ⧸ J.stalkIdeal x)

/-- The closed analytic subspace defined by `J` is **reduced**: its structure sheaf `𝒪_M/J` has no
nilpotent elements [Hir64, p. 111], i.e. every stalk `J_x` is a radical ideal
(`𝓘_{X_red} = √𝓘_X`, [BM97, Remark 3.14]). -/
def IsReduced (J : IdealSheaf M) : Prop := ∀ x : M, (J.stalkIdeal x).IsRadical

/-- The **simple locus** `Reg(Y)` of the closed analytic subspace `Y` defined by `J`: the points
`x` at which the local ring `𝒪_{M,x}/J_x` of `Y` is regular, Hironaka's simple points of `Y`
[Hir64, p. 121] and Włodarczyk's "set `Reg(Y)` of points where `Y` is smooth"
[Wlo09, Theorem 2.0.2 (2)]. A point off `Y` is not in it: there `J_x = 𝒪_{M,x}`, and the zero
ring is not local, so not regular. `J` is non-singular (`IsNonsingular`) exactly when its support
lies in its simple locus. -/
def regularLocus (J : IdealSheaf M) : Set M :=
  {x | IsRegularLocalRing (stalkRing M x ⧸ J.stalkIdeal x)}

end IdealSheaf

section Restrict

open TopologicalSpace

noncomputable section

/-- The restriction `J|_U` of an ideal sheaf to an open subset: the inverse image ideal sheaf
along the inclusion (along an open embedding the inverse image is the restriction, the stalks at
the points of `U` being those of `J`). -/
abbrev IdealSheaf.restrict {M : AnalyticManifold.{u} 𝕜 E} (J : IdealSheaf M) (U : Opens M) :
    IdealSheaf (M.restrict U) :=
  J.pullback (M.inclusion U) (M.inclusion U).contMDiff

end

end Restrict

end AnalyticManifold
