/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Order
public import Hironaka.Algebra.Derivative.Basic
public import Hironaka.Manifold.Germ.CoordDeriv
import Hironaka.Manifold.Germ.CoordDerivChart
import Hironaka.Manifold.Germ.CoordDerivCoords
import Hironaka.Manifold.IdealSheaf.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The derivative ideal sheaf `D(𝓘)` and its iterates `Dʳ(𝓘)`

Kollár's derivative of an ideal sheaf [Kol07, Definition 73]: on a smooth variety the derivations
`∂/∂x_1, …, ∂/∂x_n` of a system of local coordinates generate the sheaf `Der_X` of derivations,
and the first derivative of an ideal sheaf `I` is the ideal sheaf generated by `I` together with
the derivatives of its elements, "`D(I) := im[Der_X × I → 𝒪_X]`" (73.1) — in terms of generators,
"`D(f_1, …, f_s) = (f_i, ∂f_i/∂x_j)`" — and the higher derivatives are the iterates
`D^{r+1}(I) := D(D^r(I))` (73.2). This module defines `D(J)` and `D^r(J)` for a locally finitely
generated ideal sheaf `J` on an analytic manifold.

The stalk of `D(J)` at `a` is Kollár's (73.1) for the stalk `𝒪_{M,a}` with its `𝕜`-derivations —
the `Hironaka` library's `Ideal.derivative 𝕜 (J.stalkIdeal a) = J_a ⊔ ⨆ δ, ⟨δ(J_a)⟩`
(`Hironaka/Algebra/Derivative/Basic.lean`, with "`I ⊂ D(I)`" built in) — so it is chart-independent
by construction. In a chart `(φ, ψ)` at `a` the coordinate derivations `∂_i = coordDerivStalk`
(`Hironaka/Manifold/Germ/CoordDeriv.lean`) generate the `𝕜`-derivations as an
`𝒪_{M,a}`-module (`coordDerivStalk_mem_span`, from `δ = ∑_i δ(x_i − x_i(a)) ∂_i`), so
`Ideal.derivative_span_eq_of_span` gives Kollár's "`D(f_1, …, f_s) = (f_i, ∂f_i/∂x_j)`": on an
open `V` of the chart inside a generating open set of `J`, the germs of the generators `f_j` and
of their partials `∂_i f_j` (`coordDeriv`, whose germs are the `∂_i` of the germs) generate
`D(J)_b` at every `b ∈ V` (`derivative_stalkIdeal_eq_span`). Hence the family of stalks has local
generators (`hasLocalGenerators_derivative_stalkIdeal`, in the chart at `a` of the maximal atlas
with the coordinates `modelCoord` of the finite-dimensional model space), and
**`IdealSheaf.deriv`** is `ofStalks` with these stalks; **`iteratedDeriv`** is its `r`-fold
iterate (73.2). The partial derivatives are those of Bierstone–Milman's regular coordinate charts
[BM97, (0.3)].

The derivative ideal sheaves give the maximal contact ideals `MC(J) = D^{m−1}(J)` and the
coefficient ideals of the order-reduction algorithm
(`Hironaka/Manifold/IdealSheaf/Tuning.lean`, `Hironaka/Resolution/Analytic/OrderReduction/`).
-/

@[expose] public section

noncomputable section

open TopologicalSpace Opposite CategoryTheory Filter Topology IsLocalRing
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {n : ℕ} (ψ : E ≃L[𝕜] (Fin n → 𝕜))
  (φ : OpenPartialHomeomorph M E) (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {a : M} (ha : a ∈ φ.source)

/-- Kollár's "the derivations `∂/∂x_1, …, ∂/∂x_n` are local generators of `Der_X`"
[Kol07, Definition 73]: every `𝕜`-derivation of the stalk `𝒪_{M,a}` lies in the `𝒪_{M,a}`-span of
the coordinate derivations `∂_i` of the chart — `δ = ∑_i δ(x_i − x_i(a)) ∂_i`. -/
theorem coordDerivStalk_mem_span
    (δ : Derivation 𝕜 ((structureSheaf 𝕜 E M).presheaf.stalk a)
      ((structureSheaf 𝕜 E M).presheaf.stalk a)) :
    δ ∈ Submodule.span ((structureSheaf 𝕜 E M).presheaf.stalk a)
      (Set.range (coordDerivStalk E ψ φ hφ ha)) := by
  have hδ : δ = ∑ i, δ (centredCoord E ψ φ hφ ha i) • coordDerivStalk E ψ φ hφ ha i := by
    ext s
    rw [derivation_sum_apply]
    simp only [Derivation.smul_apply, smul_eq_mul]
    exact derivation_eq_sum_coordDerivStalk E ψ φ hφ ha δ s
  rw [hδ]
  exact Submodule.sum_mem _ fun i _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- Kollár's (73.1) read in a chart ([Kol07, Definition 73]; [BM97, (0.3)]): the derivative
`D(I) = I + ∑_δ ⟨δ(I)⟩` of an ideal `I` of the stalk is generated by `I` and the coordinate
partial derivatives `∂_i f`, `f ∈ I`. -/
theorem derivative_eq_sup_iSup_span_image_coordDerivStalk
    (I : Ideal ((structureSheaf 𝕜 E M).presheaf.stalk a)) :
    Ideal.derivative 𝕜 I =
      I ⊔ ⨆ i, Ideal.span (coordDerivStalk E ψ φ hφ ha i '' (I : Set _)) := by
  conv_lhs => rw [← Ideal.span_eq I]
  rw [Ideal.derivative_span_eq_of_span _ (coordDerivStalk_mem_span ψ φ hφ ha), Ideal.span_union,
    Ideal.span_iUnion, Ideal.span_eq]

namespace IdealSheaf

variable (J : IdealSheaf (structureSheaf 𝕜 E M))

omit ha in
/-- Kollár's "`D(f_1, …, f_s) = (f_i, ∂f_i/∂x_j)`" [Kol07, Definition 73]: on an open `V` of a
chart inside a generating open set `U` of `J`, the derivative of the stalk ideal at `b ∈ V` is
generated by the germs of the generators `f_j` and of their coordinate partial derivatives
`∂_i f_j` (the germ of `∂_i f_j` is `∂_i` of the germ of `f_j`). -/
theorem derivative_stalkIdeal_eq_span {U : Opens M} {k : ℕ}
    (f : Fin k → (structureSheaf 𝕜 E M).presheaf.obj (op U))
    (hf : ∀ b (hb : b ∈ U), J.stalkIdeal b =
      Ideal.span (Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ U b hb (f j)))
    {V : Opens M} (hVU : V ≤ U) (hV : (V : Set M) ⊆ φ.source) {b : M} (hb : b ∈ V) :
    Ideal.derivative 𝕜 (J.stalkIdeal b) = Ideal.span
      ((Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ V b hb
          ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j))) ∪
        ⋃ i, Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ V b hb
          (coordDeriv E ψ φ hφ V hV i
            ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j)))) := by
  have hbφ : b ∈ φ.source := hV hb
  rw [hf b (hVU hb), ← range_germ_map (homOfLE hVU) hb f,
    Ideal.derivative_span_eq_of_span _ (coordDerivStalk_mem_span ψ φ hφ hbφ)]
  refine congrArg Ideal.span (congrArg (_ ∪ ·) (congrArg Set.iUnion (funext fun i => ?_)))
  rw [← Set.range_comp]
  refine congrArg Set.range (funext fun j => ?_)
  exact coordDerivStalk_germ E ψ φ hφ hbφ V hV hb i _

variable [IsManifold 𝓘(𝕜, E) ω M] [FiniteDimensional 𝕜 E]

omit ψ φ hφ ha in
/-- The derivatives of the stalk ideals have local generators: on `U ∩ (chart at a)`, for `U` a
generating open set of `J`, the generators `f_j` and their partials `∂_i f_j` in the chart at `a`
(`modelCoord` the coordinates of the finite-dimensional model space). -/
theorem hasLocalGenerators_derivative_stalkIdeal :
    HasLocalGenerators fun a => Ideal.derivative 𝕜 (J.stalkIdeal a) := by
  intro a
  obtain ⟨U, haU, k, f, -, hf⟩ := J.exists_generators a
  have hφ : chartAt E a ∈ maximalAtlas 𝓘(𝕜, E) ω M := IsManifold.chart_mem_maximalAtlas a
  let V : Opens M := U ⊓ ⟨(chartAt E a).source, (chartAt E a).open_source⟩
  have hV : (V : Set M) ⊆ (chartAt E a).source := fun x hx => hx.2
  have hVU : V ≤ U := inf_le_left
  refine ⟨V, Opens.mem_inf.mpr ⟨haU, mem_chart_source E a⟩,
    Fin k ⊕ Fin (Module.finrank 𝕜 E) × Fin k, inferInstance,
    Sum.elim (fun j => (structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j))
      (fun p => coordDeriv E (modelCoord (𝕜 := 𝕜) (E := E)) (chartAt E a) hφ V hV p.1
        ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f p.2))), fun b hb => ?_⟩
  dsimp only
  rw [J.derivative_stalkIdeal_eq_span (modelCoord (𝕜 := 𝕜) (E := E)) (chartAt E a) hφ f hf hVU
    hV hb]
  congr 1
  ext s
  simp only [Set.mem_range, Set.mem_union, Set.mem_iUnion, Prod.exists, Sum.exists, Sum.elim_inl,
    Sum.elim_inr]

omit ψ φ hφ ha in
/-- **The derivative ideal sheaf `D(J)`** ([Kol07, Definition 73, (73.1)]; [BM97, (0.3)]): the
locally finitely generated ideal sheaf whose stalk at `a` is Kollár's derivative
`Ideal.derivative 𝕜 J_a` of the stalk ideal — generated by `J_a` and all `δ f`, `f ∈ J_a`, `δ` a
`𝕜`-derivation of `𝒪_{M,a}`; in a chart, by `J_a` and the coordinate partials `∂_i f`. -/
def deriv : IdealSheaf (structureSheaf 𝕜 E M) :=
  ofStalks _ (fun a => Ideal.derivative 𝕜 (J.stalkIdeal a))
    J.hasLocalGenerators_derivative_stalkIdeal

omit ψ φ hφ ha in
/-- The stalk of `D(J)` is Kollár's derivative `D(J_a) = J_a ⊔ ∑_δ ⟨δ(J_a)⟩` of the stalk ideal
(`Ideal.derivative`). -/
@[simp]
theorem stalkIdeal_deriv (a : M) :
    J.deriv.stalkIdeal a = Ideal.derivative 𝕜 (J.stalkIdeal a) :=
  stalkIdeal_ofStalks (fun a => Ideal.derivative 𝕜 (J.stalkIdeal a))
    J.hasLocalGenerators_derivative_stalkIdeal a

omit ψ φ hφ ha in
/-- **The higher derivative ideal sheaves** `D^0(J) = J`, `D^{r+1}(J) = D(D^r(J))`
[Kol07, Definition 73, (73.2)]. -/
def iteratedDeriv (r : ℕ) : IdealSheaf (structureSheaf 𝕜 E M) :=
  (fun I : IdealSheaf (structureSheaf 𝕜 E M) => I.deriv)^[r] J

end IdealSheaf

end Manifold

end
