/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Deriv
public import Hironaka.Manifold.IdealSheaf.Basic
import Hironaka.Manifold.Germ.CoordDerivChart
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The derivative ideal sheaf: `𝓘 ⊆ D(𝓘)`, the chart description, the iterates

Properties of `IdealSheaf.deriv` and `iteratedDeriv`
(`Hironaka/Manifold/IdealSheaf/Deriv.lean`), Kollár's derivative ideal sheaves
[Kol07, Definition 73]:

* `le_deriv`: `J ⊆ D(J)` (Kollár's "Note that `I ⊂ D(I)`", built into `Ideal.derivative`);
* `stalkIdeal_deriv_eq_sup_iSup_coordDerivStalk`: in a chart at `a`, `D(J)_a = J_a + ∑_i ∂_i(J_a)`
  with the coordinate derivations (Kollár's "local generators of `Der_X`");
  `coordDeriv_mem_carrier_deriv`: the partial derivative of a section of `J` is a section of
  `D(J)`; `stalkIdeal_deriv_eq_span`: on a generating open set, `D(J)_b = (f_j, ∂_i f_j)`;
* `stalkIdeal_deriv_eq_D`: through the `Hironaka` library's regular coordinates of the stalk
  (`IsLocalRing.RegularCoords`, with the conditions `IsLinearOver 𝕜` and `SpansDerivations 𝕜`
  that the analytic stalk satisfies), `D(J)_a` is the coordinate derivative `c.D J_a`
  (`Ideal.derivative_eq_D`), so the local theory of derivative ideals of the `Hironaka` library
  applies to the stalks;
* the iterates: `iteratedDeriv_zero`, `iteratedDeriv_succ` ((73.2)), `le_iteratedDeriv` (the
  chain `J ⊆ D(J) ⊆ D²(J) ⊆ ⋯`), `iteratedDeriv_add` ([Kol07, Lemma 74 (1)]), and their stalks
  `stalkIdeal_iteratedDeriv` (`= Ideal.derivativeIter`) and `stalkIdeal_iteratedDeriv_eq_Dpow`
  (`= c.Dpow r J_a`).

These are the lemmas through which the derivative ideal sheaves are computed at the stalks in the
maximal-contact and order-reduction arguments.
-/

public section

noncomputable section

open TopologicalSpace Opposite CategoryTheory Filter Topology IsLocalRing
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

namespace IdealSheaf

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M] [IsManifold 𝓘(𝕜, E) ω M]
  [FiniteDimensional 𝕜 E] (J : IdealSheaf (structureSheaf 𝕜 E M))

/-- Kollár's "`I ⊂ D(I)`" [Kol07, Definition 73]. -/
theorem le_deriv : J ≤ J.deriv := fun a => by
  rw [stalkIdeal_deriv]
  exact Ideal.le_derivative _

variable {n : ℕ} (ψ : E ≃L[𝕜] (Fin n → 𝕜)) (φ : OpenPartialHomeomorph M E)
  (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M)

/-- In a chart `(φ, ψ)` at `a`, the stalk of `D(J)` is generated by `J_a` and the coordinate
partial derivatives `∂_i f`, `f ∈ J_a` ([Kol07, Definition 73]; [BM97, (0.3)]). -/
theorem stalkIdeal_deriv_eq_sup_iSup_coordDerivStalk {a : M} (ha : a ∈ φ.source) :
    J.deriv.stalkIdeal a = J.stalkIdeal a ⊔
      ⨆ i, Ideal.span (coordDerivStalk E ψ φ hφ ha i '' (J.stalkIdeal a : Set _)) := by
  rw [stalkIdeal_deriv]
  exact derivative_eq_sup_iSup_span_image_coordDerivStalk ψ φ hφ ha _

/-- The coordinate partial derivative of a section of `J` over an open `V` of the chart is a
section of `D(J)`. -/
theorem coordDeriv_mem_carrier_deriv (V : Opens M) (hV : (V : Set M) ⊆ φ.source)
    {f : (structureSheaf 𝕜 E M).presheaf.obj (op V)} (hf : f ∈ J.carrier V) (i : Fin n) :
    coordDeriv E ψ φ hφ V hV i f ∈ J.deriv.carrier V := by
  rw [mem_carrier_iff]
  intro x hx
  rw [stalkIdeal_deriv, ← coordDerivStalk_germ E ψ φ hφ (hV hx) V hV hx i f]
  exact Ideal.derivation_apply_mem_derivative _ (J.germ_mem_stalkIdeal hx hf)

/-- Kollár's "`D(f_1, …, f_s) = (f_i, ∂f_i/∂x_j)`" [Kol07, Definition 73]: on an open `V` of a
chart inside a generating open set `U` of `J`, the stalk of `D(J)` at `b ∈ V` is generated by the
germs of the generators `f_j` and of their coordinate partial derivatives `∂_i f_j`. -/
theorem stalkIdeal_deriv_eq_span {U : Opens M} {k : ℕ}
    (f : Fin k → (structureSheaf 𝕜 E M).presheaf.obj (op U))
    (hf : ∀ b (hb : b ∈ U), J.stalkIdeal b =
      Ideal.span (Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ U b hb (f j)))
    {V : Opens M} (hVU : V ≤ U) (hV : (V : Set M) ⊆ φ.source) {b : M} (hb : b ∈ V) :
    J.deriv.stalkIdeal b = Ideal.span
      ((Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ V b hb
          ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j))) ∪
        ⋃ i, Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ V b hb
          (coordDeriv E ψ φ hφ V hV i
            ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j)))) := by
  rw [stalkIdeal_deriv]
  exact J.derivative_stalkIdeal_eq_span ψ φ hφ f hf hVU hV hb

/-- For regular coordinates `c` of the stalk (`IsLocalRing.RegularCoords`) with `𝕜`-linear,
spanning derivations, the stalk of `D(J)` is the coordinate derivative `c.D J_a` of the `Hironaka`
library (`Ideal.derivative_eq_D`). -/
theorem stalkIdeal_deriv_eq_D {a : M} [IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk a)]
    (c : RegularCoords ((structureSheaf 𝕜 E M).presheaf.stalk a) n) (hk : c.IsLinearOver 𝕜)
    (hs : c.SpansDerivations 𝕜) : J.deriv.stalkIdeal a = c.D (J.stalkIdeal a) := by
  rw [stalkIdeal_deriv, Ideal.derivative_eq_D c hk hs]

/-! ### The iterates `Dʳ(J)` -/

@[simp] theorem iteratedDeriv_zero : J.iteratedDeriv 0 = J := rfl

/-- `D^{r+1}(J) = D(D^r(J))` [Kol07, Definition 73, (73.2)]. -/
@[simp] theorem iteratedDeriv_succ (r : ℕ) : J.iteratedDeriv (r + 1) = (J.iteratedDeriv r).deriv :=
  Function.iterate_succ_apply' _ _ _

theorem iteratedDeriv_succ' (r : ℕ) : J.iteratedDeriv (r + 1) = J.deriv.iteratedDeriv r :=
  Function.iterate_succ_apply _ _ _

/-- The chain `J ⊆ D(J) ⊆ D²(J) ⊆ ⋯`. -/
theorem le_iteratedDeriv (r : ℕ) : J ≤ J.iteratedDeriv r := by
  induction r with
  | zero => exact le_rfl
  | succ r ih => rw [iteratedDeriv_succ]; exact ih.trans (le_deriv _)

theorem iteratedDeriv_le_succ (r : ℕ) : J.iteratedDeriv r ≤ J.iteratedDeriv (r + 1) := by
  rw [iteratedDeriv_succ]
  exact le_deriv _

/-- `D^r(D^s(J)) = D^{r+s}(J)` [Kol07, Lemma 74 (1)]. -/
theorem iteratedDeriv_add (r s : ℕ) :
    J.iteratedDeriv (r + s) = (J.iteratedDeriv s).iteratedDeriv r :=
  Function.iterate_add_apply _ _ _ _

/-- The stalk of `D^r(J)` is Kollár's `r`-th derivative `D^r(J_a)` of the stalk ideal
(`Ideal.derivativeIter`). -/
theorem stalkIdeal_iteratedDeriv (r : ℕ) (a : M) :
    (J.iteratedDeriv r).stalkIdeal a = Ideal.derivativeIter 𝕜 r (J.stalkIdeal a) := by
  induction r with
  | zero => rfl
  | succ r ih => rw [iteratedDeriv_succ, stalkIdeal_deriv, ih, Ideal.derivativeIter_succ]

/-- Through regular coordinates `c` of the stalk, the stalk of `D^r(J)` is the `Hironaka` library's
`c.Dpow r J_a` (`Ideal.derivativeIter_eq_Dpow`). -/
theorem stalkIdeal_iteratedDeriv_eq_Dpow {a : M}
    [IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk a)]
    (c : RegularCoords ((structureSheaf 𝕜 E M).presheaf.stalk a) n) (hk : c.IsLinearOver 𝕜)
    (hs : c.SpansDerivations 𝕜) (r : ℕ) :
    (J.iteratedDeriv r).stalkIdeal a = c.Dpow r (J.stalkIdeal a) := by
  rw [stalkIdeal_iteratedDeriv, Ideal.derivativeIter_eq_Dpow c hk hs]

end IdealSheaf

end Manifold

end
