/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.IdealSheaf.Derivative.Logarithmic
public import Hironaka.Manifold.Germ.CoordDeriv
public import Hironaka.Manifold.Submanifold.Defs
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.Germ.CoordDerivChart
import Hironaka.Manifold.Germ.CoordDerivCoords
import Hironaka.Manifold.IdealSheaf.Basic
import Hironaka.Manifold.IdealSheaf.Deriv
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The logarithmic derivative ideal sheaf `D(−log S)(𝓘)` along a hypersurface

Kollár's logarithmic derivatives along a smooth hypersurface `S` [Kol07, 87]: the sheaf
`Der_X(−log S)` of derivations preserving the ideal of `S`, which in local coordinates with
`S = (x₁ = 0)` is "`Der_X(−log S) = ⟨x₁ ∂/∂x₁, ∂/∂x₂, …, ∂/∂xₙ⟩`", and the logarithmic derivative
`D(−log S)(I)` of an ideal sheaf, generated by `I` and the images of `I` under these derivations,
with its iterates `D^{r+1}(−log S)(I) := D(−log S)(D^r(−log S)(I))`.

The definition is stalkwise and chart-free: the stalk of `D(−log S)(J)` at `a` is the `Hironaka`
library's `Ideal.logDerivative 𝕜 (I_{S,a}) J_a = J_a ⊔ ∑_δ ⟨δ J_a⟩` over the `𝕜`-derivations `δ`
of `𝒪_{M,a}` preserving the stalk `I_{S,a}` of the reduced ideal sheaf of the hypersurface
(`IsClosedSubmanifold.idealSheaf`, itself chart-independent). The family of stalks has local
generators (so `IdealSheaf.ofStalks` applies, as for `deriv`): in a chart adapted to `S` with
`S = (x_h = 0)`, the derivations `x_h ∂_h` and `∂_j` (`j ≠ h`) generate the preserving derivations
at every point of the chart — at a point of `S` because a derivation is `∑_i δ(x_i − x_i(a)) ∂_i`
and `δ(x_h) ∈ (x_h)`, at a point off `S` because `x_h` is a unit there and all derivations
preserve the unit ideal — so on the chart the germs of the generators `f_j` of `J`, of
`x_h ∂_h f_j` and of `∂_i f_j` (`i ≠ h`) generate the stalks (Kollár's
"`D(f_1, …, f_s) = (f_i, ∂f_i/∂x_j)`" with `∂_h` weighted by `x_h`). The iterates
`D^r(−log S)(J)` are `logDerivIter`. Their properties are in
`Hironaka/Manifold/IdealSheaf/LogDerivLemmas.lean` and their restriction to `S` in
`Hironaka/Manifold/IdealSheaf/LogDerivRestrict.lean`.
-/

@[expose] public section

noncomputable section

open TopologicalSpace Opposite CategoryTheory Set
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

/-! ### The algebraic span lemma for `D(−log J)` -/

namespace Ideal

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- `Ideal.derivative_span_eq_of_span` for the logarithmic derivative (Kollár's description of
`D(−log S)` in coordinates, [Kol07, 87]): if the derivations `der i` preserve `J` and span (over
`A`) the derivations preserving `J`, then `D(−log J)(⟨S⟩) = ⟨S ∪ ⋃_i der i '' S⟩`. -/
theorem logDerivative_span_eq_of_span {ι : Type*} (der : ι → Derivation k A A) {J : Ideal A}
    (hder : ∀ i, (der i).PreservesIdeal J)
    (h : ∀ δ : Derivation k A A, δ.PreservesIdeal J → δ ∈ Submodule.span A (Set.range der))
    (S : Set A) :
    logDerivative k J (Ideal.span S) = Ideal.span (S ∪ ⋃ i, der i '' S) := by
  refine le_antisymm (logDerivative_le_iff.mpr
    ⟨Ideal.span_mono Set.subset_union_left, fun δ hδ f hf => ?_⟩) ?_
  · have hδS : ∀ s ∈ S, δ s ∈ Ideal.span (S ∪ ⋃ i, der i '' S) := by
      intro s hs
      have hmem := h δ hδ
      clear hδ
      induction hmem using Submodule.span_induction with
      | mem δ' hδ' =>
        obtain ⟨i, rfl⟩ := hδ'
        exact Ideal.subset_span (Or.inr (Set.mem_iUnion.mpr ⟨i, ⟨s, hs, rfl⟩⟩))
      | zero => simp
      | add δ₁ δ₂ _ _ h1 h2 => rw [Derivation.add_apply]; exact Ideal.add_mem _ h1 h2
      | smul a δ' _ h' => rw [Derivation.smul_apply, smul_eq_mul]; exact Ideal.mul_mem_left _ _ h'
    induction hf using Submodule.span_induction with
    | mem s hs => exact hδS s hs
    | zero => simp
    | add f g _ _ hf hg => rw [map_add]; exact Ideal.add_mem _ hf hg
    | smul a f hf' hf =>
      rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hf)
        (Ideal.mul_mem_right _ _ (Ideal.span_mono Set.subset_union_left hf'))
  · rw [Ideal.span_le]
    rintro x (hx | hx)
    · exact le_logDerivative (k := k) _ _ (Ideal.subset_span hx)
    · obtain ⟨i, s, hs, rfl⟩ := Set.mem_iUnion.mp hx
      exact derivation_apply_mem_logDerivative (hder i) (Ideal.subset_span hs)

end Ideal

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] (E : Type*) [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {n : ℕ} (ψ : E ≃L[𝕜] (Fin n → 𝕜))
  (φ : OpenPartialHomeomorph M E) (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {a : M} (ha : a ∈ φ.source)

/-! ### The coordinate logarithmic derivations `x_h ∂_h, ∂_j (j ≠ h)` at a point of a chart -/

/-- Kollár's generators of `Der_X(−log S)` in coordinates with `S = (x_h = 0)` [Kol07, 87]: the
family `i ↦ x_h ∂_h` for `i = h`, `∂_i` otherwise, on the stalk at `a`. -/
def logCoordDerivStalk (h i : Fin n) :
    Derivation 𝕜 ((structureSheaf 𝕜 E M).presheaf.stalk a)
      ((structureSheaf 𝕜 E M).presheaf.stalk a) :=
  if i = h then coord E ψ φ hφ ha h • coordDerivStalk E ψ φ hφ ha h
  else coordDerivStalk E ψ φ hφ ha i

theorem logCoordDerivStalk_self (h : Fin n) :
    logCoordDerivStalk E ψ φ hφ ha h h = coord E ψ φ hφ ha h • coordDerivStalk E ψ φ hφ ha h := by
  simp [logCoordDerivStalk]

theorem logCoordDerivStalk_of_ne {h i : Fin n} (hi : i ≠ h) :
    logCoordDerivStalk E ψ φ hφ ha h i = coordDerivStalk E ψ φ hφ ha i := by
  simp [logCoordDerivStalk, hi]

/-- Each `x_h ∂_h`, `∂_j` (`j ≠ h`) preserves the ideal `(x_h)` [Kol07, 87]. -/
theorem logCoordDerivStalk_preservesIdeal (h i : Fin n) :
    (logCoordDerivStalk E ψ φ hφ ha h i).PreservesIdeal (Ideal.span {coord E ψ φ hφ ha h}) := by
  rw [Derivation.preservesIdeal_span_singleton_iff]
  by_cases hi : i = h
  · subst hi
    rw [logCoordDerivStalk_self, Derivation.smul_apply, smul_eq_mul]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)
  · rw [logCoordDerivStalk_of_ne E ψ φ hφ ha hi, coordDerivStalk_coord, ite_eq_right hi, map_zero]
    exact Ideal.zero_mem _

/-- A derivation preserving `(x_h)` is an `𝒪_{M,a}`-combination of `x_h ∂_h` and the `∂_j`,
`j ≠ h` ([Kol07, 87], from `δ = ∑_i δ(x_i − x_i(a)) ∂_i`). -/
theorem mem_span_logCoordDerivStalk_of_preservesIdeal (h : Fin n)
    (δ : Derivation 𝕜 ((structureSheaf 𝕜 E M).presheaf.stalk a)
      ((structureSheaf 𝕜 E M).presheaf.stalk a))
    (hδ : δ.PreservesIdeal (Ideal.span {coord E ψ φ hφ ha h})) :
    δ ∈ Submodule.span ((structureSheaf 𝕜 E M).presheaf.stalk a)
      (Set.range (logCoordDerivStalk E ψ φ hφ ha h)) := by
  have hδ' : δ = ∑ i, δ (centredCoord E ψ φ hφ ha i) • coordDerivStalk E ψ φ hφ ha i := by
    ext s
    rw [derivation_eq_sum_coordDerivStalk E ψ φ hφ ha δ s, IsLocalRing.derivation_sum_apply]
    simp only [Derivation.smul_apply, smul_eq_mul]
  rw [hδ']
  refine Submodule.sum_mem _ fun i _ => ?_
  by_cases hi : i = h
  · subst hi
    obtain ⟨g, hg⟩ := Ideal.mem_span_singleton'.mp (hδ _ (Ideal.mem_span_singleton_self _))
    have hc : δ (centredCoord E ψ φ hφ ha i) = δ (coord E ψ φ hφ ha i) := by
      simp only [centredCoord, map_sub, sub_eq_self]
      exact Derivation.map_algebraMap δ _
    rw [hc, ← hg, mul_smul]
    exact Submodule.smul_mem _ _
      (Submodule.subset_span ⟨i, logCoordDerivStalk_self E ψ φ hφ ha i⟩)
  · exact Submodule.smul_mem _ _
      (Submodule.subset_span ⟨i, logCoordDerivStalk_of_ne E ψ φ hφ ha hi⟩)

/-- On the stalk at a point where `x_h = 0`:
`D(−log (x_h))(⟨T⟩) = ⟨T ∪ x_h ∂_h T ∪ ⋃_{j ≠ h} ∂_j T⟩` ([Kol07, 87], in coordinates). -/
theorem logDerivative_span_coord_eq (h : Fin n)
    (T : Set ((structureSheaf 𝕜 E M).presheaf.stalk a)) :
    Ideal.logDerivative 𝕜 (Ideal.span {coord E ψ φ hφ ha h}) (Ideal.span T) =
      Ideal.span (T ∪ ⋃ i, logCoordDerivStalk E ψ φ hφ ha h i '' T) :=
  Ideal.logDerivative_span_eq_of_span _ (logCoordDerivStalk_preservesIdeal E ψ φ hφ ha h)
    (mem_span_logCoordDerivStalk_of_preservesIdeal E ψ φ hφ ha h) T

/-- At a point where `x_h` is a unit (off the hypersurface), the same family generates the plain
derivative: `D(⟨T⟩) = ⟨T ∪ x_h ∂_h T ∪ ⋃_{j ≠ h} ∂_j T⟩`. -/
theorem derivative_span_eq_span_logCoordDerivStalk (h : Fin n)
    (hu : IsUnit (coord E ψ φ hφ ha h)) (T : Set ((structureSheaf 𝕜 E M).presheaf.stalk a)) :
    Ideal.derivative 𝕜 (Ideal.span T) =
      Ideal.span (T ∪ ⋃ i, logCoordDerivStalk E ψ φ hφ ha h i '' T) := by
  rw [Ideal.derivative_span_eq_of_span _ (coordDerivStalk_mem_span ψ φ hφ ha)]
  refine le_antisymm (Ideal.span_le.mpr ?_) (Ideal.span_le.mpr ?_)
  · rintro x (hx | hx)
    · exact Ideal.subset_span (Or.inl hx)
    · obtain ⟨i, t, ht, rfl⟩ := Set.mem_iUnion.mp hx
      by_cases hi : i = h
      · subst hi
        obtain ⟨v, hv⟩ := hu
        have : coordDerivStalk E ψ φ hφ ha i t =
            (↑v⁻¹ : (structureSheaf 𝕜 E M).presheaf.stalk a) *
              (logCoordDerivStalk E ψ φ hφ ha i i t) := by
          rw [logCoordDerivStalk_self, Derivation.smul_apply, smul_eq_mul, ← mul_assoc, ← hv,
            Units.inv_mul, one_mul]
        rw [this]
        exact Ideal.mul_mem_left _ _
          (Ideal.subset_span (Or.inr (Set.mem_iUnion.mpr ⟨i, ⟨t, ht, rfl⟩⟩)))
      · rw [← logCoordDerivStalk_of_ne E ψ φ hφ ha hi]
        exact Ideal.subset_span (Or.inr (Set.mem_iUnion.mpr ⟨i, ⟨t, ht, rfl⟩⟩))
  · rintro x (hx | hx)
    · exact Ideal.subset_span (Or.inl hx)
    · obtain ⟨i, t, ht, rfl⟩ := Set.mem_iUnion.mp hx
      by_cases hi : i = h
      · subst hi
        rw [logCoordDerivStalk_self, Derivation.smul_apply, smul_eq_mul]
        exact Ideal.mul_mem_left _ _
          (Ideal.subset_span (Or.inr (Set.mem_iUnion.mpr ⟨i, ⟨t, ht, rfl⟩⟩)))
      · rw [logCoordDerivStalk_of_ne E ψ φ hφ ha hi]
        exact Ideal.subset_span (Or.inr (Set.mem_iUnion.mpr ⟨i, ⟨t, ht, rfl⟩⟩))

/-! ### The section-level family and the local generators -/

variable (V : Opens M) (hV : (V : Set M) ⊆ φ.source)

/-- The section-level family `f ↦ x_h · ∂_h f` (`i = h`), `f ↦ ∂_i f` (`i ≠ h`) over `V`. -/
def logCoordDerivSection (h i : Fin n) (f : (structureSheaf 𝕜 E M).presheaf.obj (op V)) :
    (structureSheaf 𝕜 E M).presheaf.obj (op V) :=
  if i = h then coordSection E ψ φ hφ V hV h * coordDeriv E ψ φ hφ V hV h f
  else coordDeriv E ψ φ hφ V hV i f

omit ha in
/-- The germ of `logCoordDerivSection` is `logCoordDerivStalk` of the germ. -/
theorem germ_logCoordDerivSection {b : M} (hb : b ∈ V) (h i : Fin n)
    (f : (structureSheaf 𝕜 E M).presheaf.obj (op V)) :
    (structureSheaf 𝕜 E M).presheaf.germ V b hb (logCoordDerivSection E ψ φ hφ V hV h i f) =
      logCoordDerivStalk E ψ φ hφ (hV hb) h i ((structureSheaf 𝕜 E M).presheaf.germ V b hb f) := by
  unfold logCoordDerivSection logCoordDerivStalk
  split_ifs with hi
  · rw [map_mul, germ_coordSection, ← coordDerivStalk_germ, Derivation.smul_apply, smul_eq_mul]
  · rw [← coordDerivStalk_germ]

variable {S : Set M}

omit ha in
/-- Kollár's "`D(f_1, …, f_s) = (f_i, ∂f_i/∂x_j)`" for the logarithmic derivative along the
hypersurface `S = (x_h = 0)` of an adapted chart, uniformly on an open `V` of the chart contained
in a generating open set `U` of `J`: at every `b ∈ V` the stalk `D(−log S)(J)_b` is generated by
the germs of the `f_j`, of `x_h ∂_h f_j` and of the `∂_i f_j`, `i ≠ h` — at `b ∈ S` by the
description of the preserving derivations, at `b ∉ S` because `x_h(b) ≠ 0`. -/
theorem logDerivative_stalkIdeal_eq_span (hS : IsClosedSubmanifold ψ S 1)
    {σ : Fin 1 ↪ Fin n} (hφS : IsAdaptedChart ψ S φ σ) (J : IdealSheaf (structureSheaf 𝕜 E M))
    {U : Opens M} {k : ℕ} (f : Fin k → (structureSheaf 𝕜 E M).presheaf.obj (op U))
    (hf : ∀ b (hb : b ∈ U), J.stalkIdeal b =
      Ideal.span (Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ U b hb (f j)))
    (hVU : V ≤ U) {b : M} (hb : b ∈ V) :
    Ideal.logDerivative 𝕜 (hS.idealSheaf.stalkIdeal b) (J.stalkIdeal b) = Ideal.span
      ((Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ V b hb
          ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j))) ∪
        ⋃ i, Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ V b hb
          (logCoordDerivSection E ψ φ hφ V hV (σ 0) i
            ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j)))) := by
  have hbφ : b ∈ φ.source := hV hb
  have hgen : J.stalkIdeal b = Ideal.span (Set.range fun j =>
      (structureSheaf 𝕜 E M).presheaf.germ V b hb
        ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j))) := by
    rw [hf b (hVU hb), ← IdealSheaf.range_germ_map (homOfLE hVU) hb f]
  have hfam : ∀ i, (Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ V b hb
      (logCoordDerivSection E ψ φ hφ V hV (σ 0) i
        ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j)))) =
      logCoordDerivStalk E ψ φ hφ hbφ (σ 0) i '' (Set.range fun j =>
        (structureSheaf 𝕜 E M).presheaf.germ V b hb
          ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j))) := by
    intro i
    rw [← Set.range_comp]
    exact congrArg Set.range (funext fun j => germ_logCoordDerivSection E ψ φ hφ V hV hb _ i _)
  simp only [hfam]
  rw [hgen]
  by_cases hbS : b ∈ S
  · rw [hS.isIdealSheafOf_idealSheaf.2 φ σ hφS b hbφ hbS, Set.range_unique]
    exact logDerivative_span_coord_eq E ψ φ hφ hbφ (σ 0) _
  · rw [hS.stalkIdeal_idealSheaf_of_notMem hbS, Ideal.logDerivative_top]
    refine derivative_span_eq_span_logCoordDerivStalk E ψ φ hφ hbφ (σ 0) ?_ _
    rw [← IsLocalRing.notMem_maximalIdeal, mem_maximalIdeal_iff_eval, eval_coord]
    intro h0
    exact hbS ((hφS.2 b hbφ).mpr fun i => by rw [Subsingleton.elim i 0]; exact h0)

variable [IsManifold 𝓘(𝕜, E) ω M]

omit φ hφ ha V hV in
/-- The logarithmic derivatives of the stalk ideals along a hypersurface have local generators:
on an adapted chart at a point of `S` (the generators `f_j`, `x_h ∂_h f_j`, `∂_i f_j`), and off
`S` the plain derivatives. -/
theorem hasLocalGenerators_logDerivative_stalkIdeal (hS : IsClosedSubmanifold ψ S 1)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf.HasLocalGenerators fun a =>
      Ideal.logDerivative 𝕜 (hS.idealSheaf.stalkIdeal a) (J.stalkIdeal a) := by
  intro a
  by_cases haS : a ∈ S
  · obtain ⟨φ, σ, haφ, hφS⟩ := hS.exists_adaptedChart a haS
    obtain ⟨U, haU, k, f, -, hf⟩ := J.exists_generators a
    let V : Opens M := U ⊓ ⟨φ.source, φ.open_source⟩
    have hV : (V : Set M) ⊆ φ.source := fun x hx => hx.2
    have hVU : V ≤ U := inf_le_left
    refine ⟨V, Opens.mem_inf.mpr ⟨haU, haφ⟩, Fin k ⊕ Fin n × Fin k, inferInstance,
      Sum.elim (fun j => (structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j))
        (fun p => logCoordDerivSection E ψ φ hφS.1 V hV (σ 0) p.1
          ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f p.2))), fun b hb => ?_⟩
    dsimp only
    rw [logDerivative_stalkIdeal_eq_span E ψ φ hφS.1 V hV hS hφS J f hf hVU hb]
    congr 1
    ext s
    simp only [Set.mem_range, Set.mem_union, Set.mem_iUnion, Prod.exists, Sum.exists, Sum.elim_inl,
      Sum.elim_inr]
  · have : FiniteDimensional 𝕜 E := ψ.symm.toLinearEquiv.finiteDimensional
    obtain ⟨U, haU, ι, _, f, hf⟩ := J.hasLocalGenerators_derivative_stalkIdeal a
    let V : Opens M := U ⊓ ⟨Sᶜ, hS.isClosed.isOpen_compl⟩
    have hVU : V ≤ U := inf_le_left
    refine ⟨V, Opens.mem_inf.mpr ⟨haU, haS⟩, ι, inferInstance,
      fun j => (structureSheaf 𝕜 E M).presheaf.map (homOfLE hVU).op (f j), fun b hb => ?_⟩
    have hfb := hf b (hVU hb)
    dsimp only at hfb ⊢
    rw [hS.stalkIdeal_idealSheaf_of_notMem hb.2, Ideal.logDerivative_top, hfb,
      ← IdealSheaf.range_germ_map (homOfLE hVU) hb f]

/-! ### The logarithmic derivative ideal sheaf and its iterates -/

omit φ hφ ha V hV in
/-- **The logarithmic derivative ideal sheaf `D(−log S)(J)`** along a closed hypersurface `S`
[Kol07, 87]: the locally finitely generated ideal sheaf whose stalk at `a` is
`Ideal.logDerivative 𝕜 (I_{S,a}) J_a` — generated by `J_a` and all `δ f`, `f ∈ J_a`, `δ` a
`𝕜`-derivation of `𝒪_{M,a}` preserving the ideal of `S`; in an adapted chart `S = (x_h = 0)`, by
`J_a`, `x_h ∂_h f` and `∂_j f` (`j ≠ h`). -/
def IdealSheaf.logDeriv (hS : IsClosedSubmanifold ψ S 1) (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf (structureSheaf 𝕜 E M) :=
  IdealSheaf.ofStalks _
    (fun a => Ideal.logDerivative 𝕜 (hS.idealSheaf.stalkIdeal a) (J.stalkIdeal a))
    (hasLocalGenerators_logDerivative_stalkIdeal E ψ hS J)

omit φ hφ ha V hV in
/-- The stalk of `D(−log S)(J)` at `a` is `D(−log I_{S,a})(J_a)` (`Ideal.logDerivative`). -/
theorem IdealSheaf.stalkIdeal_logDeriv (hS : IsClosedSubmanifold ψ S 1)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) (a : M) :
    (IdealSheaf.logDeriv E ψ hS J).stalkIdeal a =
      Ideal.logDerivative 𝕜 (hS.idealSheaf.stalkIdeal a) (J.stalkIdeal a) :=
  IdealSheaf.stalkIdeal_ofStalks _ (hasLocalGenerators_logDerivative_stalkIdeal E ψ hS J) a

omit φ hφ ha V hV in
/-- The iterates `D^r(−log S)(J)` [Kol07, 87]. -/
def IdealSheaf.logDerivIter (hS : IsClosedSubmanifold ψ S 1) (r : ℕ)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) : IdealSheaf (structureSheaf 𝕜 E M) :=
  (IdealSheaf.logDeriv E ψ hS)^[r] J

omit φ hφ ha V hV in
@[simp] theorem IdealSheaf.logDerivIter_zero (hS : IsClosedSubmanifold ψ S 1)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) : IdealSheaf.logDerivIter E ψ hS 0 J = J := rfl

omit φ hφ ha V hV in
@[simp] theorem IdealSheaf.logDerivIter_succ (hS : IsClosedSubmanifold ψ S 1) (r : ℕ)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf.logDerivIter E ψ hS (r + 1) J =
      IdealSheaf.logDeriv E ψ hS (IdealSheaf.logDerivIter E ψ hS r J) :=
  Function.iterate_succ_apply' _ _ _

omit φ hφ ha V hV in
theorem IdealSheaf.logDerivIter_succ' (hS : IsClosedSubmanifold ψ S 1) (r : ℕ)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf.logDerivIter E ψ hS (r + 1) J =
      IdealSheaf.logDerivIter E ψ hS r (IdealSheaf.logDeriv E ψ hS J) :=
  Function.iterate_succ_apply _ _ _

end Manifold

end
