/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Defs
public import Hironaka.Manifold.StructureSheaf
public import Hironaka.Manifold.BlowUp.Transform.Reduced.StdModel
import Hironaka.Manifold.IdealSheaf.Basic

/-!
# The principal ideal sheaf of a global analytic function

The ideal sheaf `(t)` generated by one global section `t` of the sheaf of analytic functions on an
analytic manifold (`IdealSheaf.principal t`): its stalk at `x` is the principal ideal generated by
the germ of `t` (`stalkIdeal_principal`), and this stalk is the unit ideal exactly where `t` does
not vanish (`stalkIdeal_principal_eq_top_iff`: a germ is a unit iff its value is nonzero), so the
support of `(t)` is the zero set of `t`. The ideal sheaf of a single function, to which the
resolution theorems are applied to monomialize the function (Watanabe's `(f)` [Wat09, Theorem 2.3];
the monomialization of `Hironaka/Resolution/Standard/Analytic.lean`).
-/

@[expose] public section

open TopologicalSpace Opposite
open scoped Manifold ContDiff

noncomputable section

universe u

namespace Manifold

/-- **The principal ideal sheaf `(t)` of a global section `t` of `𝒪_M`** (`IdealSheaf.ofStalks`):
the stalks `span {germ_x t}`, which have the local generator `t`
(`hasLocalGenerators_span_germ_top`). -/
def IdealSheaf.principal {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E]
    [NormedSpace 𝕜 E] {M : AnalyticManifold.{u} 𝕜 E}
    (t : (structureSheaf 𝕜 E M).presheaf.obj (op ⊤)) : AnalyticManifold.IdealSheaf M :=
  IdealSheaf.ofStalks _ _ (hasLocalGenerators_span_germ_top t)

/-- The stalk of `(t)` at `x` is the principal ideal generated by the germ of `t` at `x`. -/
theorem IdealSheaf.stalkIdeal_principal {𝕜 : Type} [RCLike 𝕜] {E : Type*}
    [NormedAddCommGroup E]
    [NormedSpace 𝕜 E] {M : AnalyticManifold.{u} 𝕜 E}
    (t : (structureSheaf 𝕜 E M).presheaf.obj (op ⊤)) (x : M) :
    (IdealSheaf.principal t).stalkIdeal x =
      Ideal.span {(structureSheaf 𝕜 E M).presheaf.germ ⊤ x (Opens.mem_top x) t} :=
  IdealSheaf.stalkIdeal_ofStalks (𝒪 := structureSheaf 𝕜 E M)
    (fun x => Ideal.span {(structureSheaf 𝕜 E M).presheaf.germ ⊤ x (Opens.mem_top x) t})
    (hasLocalGenerators_span_germ_top t) x

/-- The stalk of `(t)` at `x` is the unit ideal iff `t x ≠ 0` (a germ is a unit iff its value is
nonzero: `𝔪_x = ker ev_x`). -/
theorem IdealSheaf.stalkIdeal_principal_eq_top_iff {𝕜 : Type} [RCLike 𝕜] {E : Type*}
    [NormedAddCommGroup E] [NormedSpace 𝕜 E] {M : AnalyticManifold.{u} 𝕜 E}
    (t : (structureSheaf 𝕜 E M).presheaf.obj (op ⊤)) (x : M) :
    (IdealSheaf.principal t).stalkIdeal x = ⊤ ↔ t ⟨x, Opens.mem_top x⟩ ≠ 0 := by
  have h : eval 𝕜 E M x ((structureSheaf 𝕜 E M).presheaf.germ ⊤ x (Opens.mem_top x) t) =
      t ⟨x, Opens.mem_top x⟩ :=
    contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω M 𝕜 ⊤ x (Opens.mem_top x) t
  rw [IdealSheaf.stalkIdeal_principal, Ideal.span_singleton_eq_top,
    ← IsLocalRing.notMem_maximalIdeal, mem_maximalIdeal_iff_eval, h]

end Manifold
