/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Basic
public import Hironaka.Manifold.Germ.StalkMap
import Hironaka.Algebra.Local.Order
import Hironaka.Manifold.IdealSheaf.Vanishing
import Hironaka.Manifold.LocalDiffeomorph
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# Pullback of ideal sheaves under analytic maps

For an analytic map `φ : N → M` and an ideal sheaf `J` of the structure sheaf of `M`, the
**pullback** `φ^* J = IdealSheaf.pullback J φ hφ` is the ideal sheaf generated by the `f ∘ φ`, `f`
a section of `J`: Hironaka's total transform `f⁻¹(J)`, "the one generated by `J` with reference to
`f`" [Hir64, pp. 141–142], and Bierstone–Milman's `σ⁻¹(I) := σ^*(I) · 𝒪` [BM97, Theorem 1.10].

* Its stalk at `b` is the image of `J_{φ b}` under the stalk map `germMap φ hφ b`
  (`stalkIdeal_pullback`), generated near `b` by the germs of the `f_i ∘ φ` for local generators
  `f_i` of `J` (`stalkIdeal_pullback_eq_span`).
* It is monotone (`pullback_le_pullback`), multiplicative (`pullback_mul`, `pullback_pow`,
  `pullback_top`), and the identity pulls back to the identity (`pullback_id_eq_self`);
  `V(φ^* J) = φ⁻¹ V(J)` (`support_pullback`, the stalk map being a local homomorphism).
* The order does not drop under pullback (`ord_le_ord_pullback`) and is preserved at a point where
  `φ` is a local analytic isomorphism (`ord_pullback_of_isLocalDiffeomorphAt`: the stalk map of a
  local inverse is a two-sided inverse).
* Along a diffeomorphism `g`, the vanishing ideal of `g⁻¹ Z` at `x` pulls back to the vanishing
  ideal of `Z` at `g x` (`comap_germMap_vanishingStalk`).

The pullback is the total transform of the analytic main theorems (the inverse image
`J.pullback f f.contMDiff` along an analytic map `f`) and the inverse image along the blow-ups and
local
isomorphisms of the resolution (`Hironaka/Manifold/BlowUp/`).
-/

public section

open TopologicalSpace Opposite CategoryTheory Filter
open scoped Manifold ContDiff Topology

universe u v

noncomputable section

namespace Manifold

variable {𝕜 : Type} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  {E' : Type*} [NormedAddCommGroup E'] [NormedSpace 𝕜 E']
  {N : Type v} [TopologicalSpace N] [ChartedSpace E' N]

/-- `Ideal.map` under a local homomorphism is the unit ideal iff the ideal is. -/
theorem _root_.Ideal.map_eq_top_iff_of_isLocalHom {R S : Type*} [CommRing R] [IsLocalRing R]
    [CommRing S] [IsLocalRing S] (g : R →+* S) [IsLocalHom g] (I : Ideal R) :
    I.map g = ⊤ ↔ I = ⊤ := by
  constructor
  · intro h
    by_contra hI
    have hle : I.map g ≤ IsLocalRing.maximalIdeal S :=
      (Ideal.map_mono (IsLocalRing.le_maximalIdeal hI)).trans (IsLocalRing.map_maximalIdeal_le g)
    have h1 : (1 : S) ∈ IsLocalRing.maximalIdeal S := hle (h ▸ Submodule.mem_top)
    exact (IsLocalRing.mem_maximalIdeal 1).mp h1 isUnit_one
  · rintro rfl
    exact Ideal.map_top g

section Pullback

variable (φ : N → M) (hφ : ContMDiff 𝓘(𝕜, E') 𝓘(𝕜, E) ω φ)

@[simp] theorem IdealSheaf.stalkIdeal_pullback (J : IdealSheaf (structureSheaf 𝕜 E M)) (b : N) :
    (J.pullback φ hφ).stalkIdeal b = Ideal.map (germMap φ hφ b) (J.stalkIdeal (φ b)) :=
  IdealSheaf.stalkIdeal_ofStalks (fun b => Ideal.map (germMap φ hφ b) (J.stalkIdeal (φ b)))
    (hasLocalGenerators_pullback φ hφ J) b

/-- The pullback of ideal sheaves is monotone, for any models (stalkwise, `Ideal.map` is
monotone; `IdealSheaf.pullback_mono` is the same-model form). -/
theorem IdealSheaf.pullback_le_pullback {J K : IdealSheaf (structureSheaf 𝕜 E M)} (h : J ≤ K) :
    J.pullback φ hφ ≤ K.pullback φ hφ := by
  rw [IdealSheaf.le_def]
  intro b
  rw [IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback]
  exact Ideal.map_mono (IdealSheaf.le_def.mp h _)

/-- The pullback of a power of an ideal sheaf is the power of the pullback (stalkwise, `Ideal.map`
of a power). -/
theorem IdealSheaf.pullback_pow (J : IdealSheaf (structureSheaf 𝕜 E M)) (k : ℕ) :
    (J ^ k).pullback φ hφ = (J.pullback φ hφ) ^ k :=
  IdealSheaf.ext fun b => by
    rw [IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pow, IdealSheaf.stalkIdeal_pow,
      IdealSheaf.stalkIdeal_pullback, Ideal.map_pow]

theorem IdealSheaf.stalkIdeal_pullback_eq_span (J : IdealSheaf (structureSheaf 𝕜 E M))
    {U : Opens M} {k : ℕ} {f : Fin k → (structureSheaf 𝕜 E M).presheaf.obj (op U)}
    (hgen : ∀ b (hb : b ∈ U), J.stalkIdeal b =
      Ideal.span (Set.range fun i => (structureSheaf 𝕜 E M).presheaf.germ U b hb (f i)))
    {b : N} (hb : φ b ∈ U) :
    (J.pullback φ hφ).stalkIdeal b = Ideal.span (Set.range fun i =>
      (structureSheaf 𝕜 E' N).presheaf.germ (preimageOpens φ hφ U) b
        ((mem_preimageOpens φ hφ).mpr hb) (comapSection φ hφ (f i))) := by
  rw [IdealSheaf.stalkIdeal_pullback, hgen (φ b) hb, Ideal.map_span, ← Set.range_comp]
  exact congrArg Ideal.span (congrArg Set.range (funext fun i => germMap_germ φ hφ hb (f i)))

/-- `V(φ^* J) = φ⁻¹ V(J)`. -/
@[simp]
theorem IdealSheaf.support_pullback (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    (J.pullback φ hφ).support = φ ⁻¹' J.support := by
  ext b
  rw [Set.mem_preimage, mem_support, mem_support,
    IdealSheaf.stalkIdeal_pullback, not_iff_not]
  exact Ideal.map_eq_top_iff_of_isLocalHom _ _

/-- The order does not drop under pullback (`IsLocalRing.ord_le_ord_map`). -/
theorem IdealSheaf.ord_le_ord_pullback (J : IdealSheaf (structureSheaf 𝕜 E M)) (b : N) :
    J.ord (φ b) ≤ (J.pullback φ hφ).ord b := by
  rw [IdealSheaf.ord, IdealSheaf.ord, IdealSheaf.stalkIdeal_pullback]
  exact IsLocalRing.ord_le_ord_map _ _

/-- For a local isomorphism `φ` at `b`, the stalk map has the stalk map of a local inverse as a
two-sided inverse, so `ν_b(φ^* J) = ν_{φ(b)}(J)`. -/
theorem IdealSheaf.ord_pullback_of_isLocalDiffeomorphAt (J : IdealSheaf (structureSheaf 𝕜 E M))
    {b : N} (h : IsLocalDiffeomorphAt 𝓘(𝕜, E') 𝓘(𝕜, E) ω φ b) :
    (J.pullback φ hφ).ord b = J.ord (φ b) := by
  obtain ⟨Φ, hbΦ, heq⟩ := h.exists_partialDiffeomorph
  have hφb : φ b ∈ Φ.target := heq hbΦ ▸ Φ.map_source hbΦ
  have hinv : Φ.invFun (φ b) = b := by rw [heq hbΦ]; exact Φ.left_inv hbΦ
  have hcomp : (germMapOn Φ.invFun (V := ⟨Φ.target, Φ.open_target⟩) Φ.contMDiffOn_invFun hφb
      hinv).comp (germMap φ hφ b) = RingHom.id _ := by
    refine RingHom.ext fun t => stalkToGerm_injective 𝓘(𝕜, E) ω M (φ b) ?_
    rw [RingHom.comp_apply, stalkToGerm_germMapOn, stalkToGerm_germMap, RingHom.id_apply]
    induction stalkToGerm 𝓘(𝕜, E) ω M (φ b) t using Germ.inductionOn with
    | h k =>
      rw [Germ.coe_compTendsto, Germ.coe_compTendsto]
      refine Germ.coe_eq.mpr ?_
      filter_upwards [Φ.open_target.mem_nhds hφb] with y hy
      simp only [Function.comp_apply]
      have hmem : Φ.invFun y ∈ Φ.source := Φ.map_target hy
      have hri : Φ.toPartialEquiv (Φ.invFun y) = y := Φ.right_inv hy
      rw [heq hmem, hri]
  refine le_antisymm ?_ (IdealSheaf.ord_le_ord_pullback φ hφ J b)
  rw [IdealSheaf.ord, IdealSheaf.ord, IdealSheaf.stalkIdeal_pullback]
  refine (IsLocalRing.ord_le_ord_map (germMapOn Φ.invFun (V := ⟨Φ.target, Φ.open_target⟩)
    Φ.contMDiffOn_invFun hφb hinv) _).trans (le_of_eq ?_)
  rw [Ideal.map_map, hcomp, Ideal.map_id]

end Pullback

/-! ### Pullback algebra and the germ map of a diffeomorphism -/

section Algebra

variable (φ : N → M) (hφ : ContMDiff 𝓘(𝕜, E') 𝓘(𝕜, E) ω φ)

/-- The pullback of a product of ideal sheaves is the product of the pullbacks (stalkwise,
`Ideal.map` of a product). -/
theorem IdealSheaf.pullback_mul (I J : IdealSheaf (structureSheaf 𝕜 E M)) :
    (I * J).pullback φ hφ = I.pullback φ hφ * J.pullback φ hφ :=
  IdealSheaf.ext fun x => by
    rw [IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_mul,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback, Ideal.map_mul]

/-- The pullback of the unit ideal sheaf is the unit ideal sheaf. -/
theorem IdealSheaf.pullback_top : (⊤ : IdealSheaf (structureSheaf 𝕜 E M)).pullback φ hφ = ⊤ :=
  IdealSheaf.ext fun x => by
    rw [IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_top, Ideal.map_top,
      IdealSheaf.stalkIdeal_top]

theorem IdealSheaf.pullback_id_eq_self (J : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf.pullback (𝕜 := 𝕜) (E' := E) (id : M → M) contMDiff_id J = J := by
  refine IdealSheaf.ext fun x => ?_
  rw [IdealSheaf.stalkIdeal_pullback]
  have : germMap (𝕜 := 𝕜) (E' := E) (id : M → M) contMDiff_id x = RingHom.id _ :=
    RingHom.ext (germMap_id x)
  rw [this, Ideal.map_id]
  rfl

variable {M₁ : Type*} [TopologicalSpace M₁] [ChartedSpace E M₁] {M₂ : Type*} [TopologicalSpace M₂]
  [ChartedSpace E M₂] (g : Diffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) M₁ M₂ ω)

/-- The vanishing ideal of `g⁻¹ Z` at `x` pulls back along the germ map of the diffeomorphism `g`
to the vanishing ideal of `Z` at `g x`. -/
theorem comap_germMap_vanishingStalk (Z : Set M₂) (x : M₁) :
    (vanishingStalk (𝕜 := 𝕜) (E := E) (⇑g ⁻¹' Z) x).comap (germMap ⇑g g.contMDiff x) =
      vanishingStalk (𝕜 := 𝕜) (E := E) Z (g x) := by
  ext s
  rw [Ideal.mem_comap, mem_vanishingStalk_iff, mem_vanishingStalk_iff, stalkToGerm_germMap]
  exact Germ.vanishesOn_compTendsto_of_isEmbedding (h := ⇑g) g.toHomeomorph.isEmbedding
    g.toEquiv.surjective Z x _

end Algebra

end Manifold

end
