/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Analytic.OrderReduction.BMO.Step3Monomial.Pieces
public import Hironaka.Manifold.IdealSheaf.Monoid
public import Hironaka.Algebra.Local.Order
public import Hironaka.Manifold.StructureSheaf
import Hironaka.Algebra.Local.CohenIso
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.FiniteSuccession.Functor.Pullback
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.Snc.Coherence
import Hironaka.Manifold.Submanifold.Clopen
import Hironaka.Resolution.Analytic.Principalization.SncClopen
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init

/-!
# The monomial ideal of a piece family

For a piece family realising a boundary family with simple normal crossings, every piece is a closed
hypersurface, a clopen part of its member, and so has a reduced ideal sheaf `𝓘_{piece c}`. The
**monomial ideal** of the family is the finite product `∏_{c < nextComp} 𝓘_{piece c}^{a c}`,
Kollár's `𝒪(−∑ aⱼ Eʲ)` of [Kol07, 111, Step 3] with the exponents read on the connected components
of the members as in [Kol07, Definition–Lemma 110] (the form used by `BMO/MonomialPart.lean`). Its
order at a point is the exponent sum of the face through the point (`ord_monomialIdeal`): the stalk
is generated by the monomial `∏_{c ∋ x} z_c^{a c}` in generators of the pieces' stalks, each of
order one, and the order function of the regular analytic stalk is multiplicative. The file also
derives the invariants of the combinatorial state from the geometry (`valid_of_realizes`): the faces
are nonempty sets of pieces with a common point, closed under nonempty subsets, of cardinality at
most the dimension `n` (at most `n` members of a family with simple normal crossings pass through a
point, [Kol07, Definition 24]), with pairwise distinct labels.
-/

@[expose] public section

open Set Topology Hironaka.Monomial IsLocalRing
open scoped Manifold ContDiff

universe u

namespace Hironaka.Manifold.BMO

open _root_.Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ₀ : E ≃L[𝕜] (Fin n → 𝕜)} {N : AnalyticManifold.{u} 𝕜 E}

/-! ### A hypersurface's stalk ideal is principal with a generator of order one -/

/-- At a point of a closed hypersurface the stalk of its ideal sheaf is generated by one element of
order exactly one, the coordinate of a chart adapted to the hypersurface. -/
theorem _root_.Manifold.IsClosedSubmanifold.exists_generator_stalkIdeal_idealSheaf
    {S : Set N}
    (hS : IsClosedSubmanifold ψ₀ S 1) {x : N} (hx : x ∈ S) :
    ∃ f, hS.idealSheaf.stalkIdeal x = Ideal.span {f} ∧ ordElem f = 1 := by
  obtain ⟨φ, σ, hxφ, hφ⟩ := hS.exists_adaptedChart x hx
  refine ⟨coord E ψ₀ φ hφ.1 hxφ (σ 0), ?_, ?_⟩
  · rw [hS.stalkIdeal_idealSheaf_eq_span hx hφ hxφ, Set.range_unique]
    rfl
  · rw [ordElem_eq_one_iff]
    exact ⟨coord_mem_maximalIdeal_of_eq_zero φ hφ.1 hxφ ((hφ.2 x hxφ).mp hx 0),
      coord_notMem_maximalIdeal_sq φ hφ.1 hxφ⟩

/-- The order of a finite product of powers, when the order function is multiplicative. -/
theorem ordElem_finset_prod_pow {R : Type*} [CommRing R] [IsLocalRing R]
    (hmul : ∀ f g : R, ordElem (f * g) = ordElem f + ordElem g) {ι : Type*} (s : Finset ι)
    (f : ι → R) (a : ι → ℕ) :
    ordElem (∏ i ∈ s, f i ^ a i) = ∑ i ∈ s, (a i : ℕ∞) * ordElem (f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [ordElem_one]
  | insert i s hi ih =>
    rw [Finset.prod_insert hi, Finset.sum_insert hi, hmul, ih, ordElem_pow_of_ordElem_mul hmul]

namespace PieceFamily

open _root_.Manifold

variable (Φ : PieceFamily N) {F : HypersurfaceFamily N} {e : Fin Φ.nextLabel ↪o F.ι}

/-! ### Live pieces are closed hypersurfaces -/

variable {Φ} in
/-- A piece is the trace of its member on the open complement of the other pieces with the same
label. -/
theorem Realizes.exists_isOpen_piece_eq (hΦ : Φ.Realizes F e) {c : ℕ} (hc : c < Φ.nextComp) :
    ∃ O : Set N, IsOpen O ∧ Φ.piece c = F.hyp (e ⟨Φ.label c, Φ.label_lt c hc⟩) ∩ O := by
  classical
  let others : Finset ℕ :=
    (Finset.range Φ.nextComp).filter fun c' => c' ≠ c ∧ Φ.label c' = Φ.label c
  refine ⟨(⋃ c' ∈ others, Φ.piece c')ᶜ, (isClosed_biUnion_finset fun c' _ =>
    Φ.isClosed_piece c').isOpen_compl, Set.Subset.antisymm ?_ ?_⟩
  · intro x hx
    refine ⟨hΦ.piece_subset_hyp hc hx, ?_⟩
    simp only [Set.mem_compl_iff, Set.mem_iUnion, not_exists]
    rintro c' hc' hx'
    have hmem := Finset.mem_filter.mp hc'
    exact hmem.2.1 (hΦ.eq_of_label_eq_of_mem (Finset.mem_range.mp hmem.1) hc hmem.2.2 hx' hx)
  · rintro x ⟨hxh, hxO⟩
    obtain ⟨c', hc', hl, hx'⟩ := (hΦ.mem_hyp_iff _ x).mp hxh
    by_cases hcc : c' = c
    · exact hcc ▸ hx'
    · exfalso
      apply hxO
      simp only [Set.mem_iUnion]
      exact ⟨c', Finset.mem_filter.mpr ⟨Finset.mem_range.mpr hc', hcc, hl⟩, hx'⟩

variable {Φ} in
/-- A piece of a family realising a boundary family with simple normal crossings is a closed
hypersurface, being a clopen part of its member. -/
theorem Realizes.isClosedSubmanifold_piece (hF : F.IsSnc ψ₀) (hΦ : Φ.Realizes F e)
    (c : Fin Φ.nextComp) : IsClosedSubmanifold ψ₀ (Φ.piece c) 1 := by
  obtain ⟨O, hO, hpiece⟩ := hΦ.exists_isOpen_piece_eq c.2
  have h := (hF.1 (e ⟨Φ.label c, Φ.label_lt c c.2⟩)).inter_of_isOpen hO
    (hpiece ▸ Φ.isClosed_piece c)
  rwa [← hpiece] at h

/-! ### The monomial ideal -/

/-- The reduced ideal sheaf `𝓘_{piece c}` of a piece. -/
noncomputable def pieceIdeal (hF : F.IsSnc ψ₀) (hΦ : Φ.Realizes F e) (c : Fin Φ.nextComp) :
    IdealSheaf (structureSheaf 𝕜 E N) :=
  (hΦ.isClosedSubmanifold_piece hF c).idealSheaf

/-- The **monomial ideal** of the family, `∏_{c < nextComp} 𝓘_{piece c}^{a c}`: Kollár's monomial
ideal `𝒪(−∑ aⱼ Eʲ)` of [Kol07, 111, Step 3], with the exponents read on the connected components of
the members ([Kol07, Definition–Lemma 110]). -/
noncomputable def monomialIdeal (hF : F.IsSnc ψ₀) (hΦ : Φ.Realizes F e) :
    IdealSheaf (structureSheaf 𝕜 E N) :=
  ∏ c : Fin Φ.nextComp, Φ.pieceIdeal hF hΦ c ^ Φ.a c

variable (hF : F.IsSnc ψ₀) (hΦ : Φ.Realizes F e)

theorem stalkIdeal_pieceIdeal_of_notMem {c : Fin Φ.nextComp} {x : N} (hx : x ∉ Φ.piece c) :
    (Φ.pieceIdeal hF hΦ c).stalkIdeal x = ⊤ :=
  (hΦ.isClosedSubmanifold_piece hF c).stalkIdeal_idealSheaf_of_notMem hx

theorem exists_generator_stalkIdeal_pieceIdeal {c : Fin Φ.nextComp} {x : N} (hx : x ∈ Φ.piece c) :
    ∃ f, (Φ.pieceIdeal hF hΦ c).stalkIdeal x = Ideal.span {f} ∧ ordElem f = 1 :=
  (hΦ.isClosedSubmanifold_piece hF c).exists_generator_stalkIdeal_idealSheaf hx

open scoped Classical in
/-- The exponent sum of the face through `x`, as a sum over the pieces containing `x`. -/
theorem total_faceAt_eq (x : N) :
    Φ.total (Φ.faceAt x) =
      ∑ c ∈ (Finset.univ.filter fun c : Fin Φ.nextComp => x ∈ Φ.piece c), Φ.a c.1 := by
  rw [total, faceAt, Finset.sum_filter, Finset.sum_filter]
  exact (Fin.sum_univ_eq_sum_range (fun c => if x ∈ Φ.piece c then Φ.a c else 0) Φ.nextComp).symm

open scoped Classical in
/-- The order of the monomial ideal at `x` is the exponent sum of the face through `x`: the stalk is
generated by `∏_{c ∋ x} z_c^{a c}` with each `z_c` of order one, and the order function of the
analytic stalk is multiplicative. -/
theorem ord_monomialIdeal (x : N) :
    (Φ.monomialIdeal hF hΦ).ord x = (Φ.total (Φ.faceAt x) : ℕ∞) := by
  have := finiteDimensional_of_chartIso ψ₀
  have hmul := ordElem_mul_of_algebraRat ((structureSheaf 𝕜 E N).presheaf.stalk x)
  choose! g hg using fun c : Fin Φ.nextComp =>
    Φ.exists_generator_stalkIdeal_pieceIdeal hF hΦ (x := x) (c := c)
  have hstalk : (Φ.monomialIdeal hF hΦ).stalkIdeal x =
      Ideal.span {∏ c ∈ (Finset.univ.filter fun c : Fin Φ.nextComp => x ∈ Φ.piece c),
        g c ^ Φ.a c.1} := by
    rw [monomialIdeal, IdealSheaf.stalkIdeal_finset_prod, ← Finset.prod_filter_mul_prod_filter_not
      Finset.univ (fun c : Fin Φ.nextComp => x ∈ Φ.piece c)]
    have h2 : ∏ c ∈ (Finset.univ.filter fun c : Fin Φ.nextComp => ¬ x ∈ Φ.piece c),
        (Φ.pieceIdeal hF hΦ c ^ Φ.a c.1).stalkIdeal x = 1 := by
      refine Finset.prod_eq_one fun c hc => ?_
      rw [IdealSheaf.stalkIdeal_pow,
        Φ.stalkIdeal_pieceIdeal_of_notMem hF hΦ (Finset.mem_filter.mp hc).2, Ideal.top_pow,
        Ideal.one_eq_top]
    rw [h2, mul_one, ← Ideal.prod_span_singleton]
    refine Finset.prod_congr rfl fun c hc => ?_
    rw [IdealSheaf.stalkIdeal_pow, (hg c (Finset.mem_filter.mp hc).2).1, Ideal.span_singleton_pow]
  rw [IdealSheaf.ord, hstalk, ord_span, Φ.total_faceAt_eq]
  simp only [Set.mem_singleton_iff, iInf_iInf_eq_left]
  rw [ordElem_finset_prod_pow hmul, Nat.cast_sum]
  refine Finset.sum_congr rfl fun c hc => ?_
  rw [(hg c (Finset.mem_filter.mp hc).2).2, mul_one]

/-! ### The six invariants of the state from the geometry -/

/-- A family realising a boundary family with simple normal crossings satisfies the invariants of
the combinatorial state for every mark `m ≥ 1`: in particular a face has at most `n` pieces, since
at most `n` members of a family with simple normal crossings pass through a point ([Kol07,
Definition 24]). -/
theorem valid_of_realizes (hF : F.IsSnc ψ₀) (hΦ : Φ.Realizes F e) {m : ℕ} (hm : 1 ≤ m) :
    Φ.IsValid n m := by
  classical
  refine ⟨hm, fun T hT => Φ.nonempty_of_mem_nerve hT,
    fun T hT c hc => Φ.lt_nextComp_of_mem_nerve hT hc, fun c _ hc => Φ.label_lt c hc,
    fun T hT T' hT' hne => Φ.mem_nerve_of_subset hT (Finset.mem_powerset.mp hT') hne,
    fun T hT => ?_, fun T hT => hΦ.injOn_label_of_mem_nerve hT⟩
  obtain ⟨hsub, -, x, hx⟩ := (Φ.mem_nerve_iff T).mp hT
  have hlt : ∀ ℓ ∈ Φ.labels T, ℓ < Φ.nextLabel := by
    intro ℓ hℓ
    obtain ⟨c, hc, rfl⟩ := Finset.mem_image.mp hℓ
    exact Φ.label_lt c (Finset.mem_range.mp (hsub hc))
  let s : Finset F.ι := (Φ.labels T).attach.image fun ℓ => e ⟨ℓ.1, hlt ℓ.1 ℓ.2⟩
  have hs : ∀ j ∈ s, x ∈ F.hyp j := by
    intro j hj
    obtain ⟨ℓ, -, rfl⟩ := Finset.mem_image.mp hj
    obtain ⟨c, hc, hcl⟩ := Finset.mem_image.mp ℓ.2
    have hcn : c < Φ.nextComp := Finset.mem_range.mp (hsub hc)
    have : (⟨ℓ.1, hlt ℓ.1 ℓ.2⟩ : Fin Φ.nextLabel) = ⟨Φ.label c, Φ.label_lt c hcn⟩ :=
      Fin.ext hcl.symm
    rw [this]
    exact hΦ.piece_subset_hyp hcn (hx c hc)
  have hcard : s.card = T.card := by
    rw [Finset.card_image_of_injective _
        fun ℓ ℓ' h => Subtype.ext (Fin.mk.inj_iff.mp (e.injective h)),
      Finset.card_attach, hΦ.card_labels_of_mem_nerve hT]
  rw [← hcard]
  exact hF.card_le x s hs

end PieceFamily

end Hironaka.Manifold.BMO

