/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.BlowUp.Defs
public import Hironaka.Manifold.Jacobian.Defs
import Hironaka.Manifold.BlowUp.Jacobian
import Hironaka.Manifold.Jacobian.Units
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The Jacobian determinant of the blowing-up

In a blow-up chart `Φ` of index `i` over an adapted chart `φ` of the centre (the charts `V'_i` of
Bierstone–Milman's blowing-up, in which `π` reads `x_i = ξ_i`, `x_j = ξ_i ξ_j` for `j ≠ i`
[BM88, Definition 4.1]), the chart representative of the blowing-up is the chart map `π_i` of the
model blow-up conjugated by the coordinates `ψ` (`IsBlowUpChart.comm`: `ψ ∘ φ ∘ π = π_i ∘ ψ ∘ Φ` on
`Φ.source`, so `φ ∘ π ∘ Φ⁻¹ = ψ⁻¹ ∘ π_i ∘ ψ` on `Φ.target`), whose Jacobian determinant is
`u_{σ i}^{c-1}` (`det_fderiv_blowUpChartMap` of `Hironaka/Manifold/BlowUp/Jacobian.lean`);
conjugation by a linear isomorphism does not change the determinant (`LinearMap.det_conj`). Hence:

* `jacobianFun_blowUpChart`: `J_{φ,Φ}(p) = ψ(Φ p)_{σ i}^{c-1}` on `Φ.source`;
* `jacobianStalk_blowUp`: the stalk of the Jacobian ideal at a point of a blow-up chart of index
  `i` is `(u_{σ i}^{c-1})`, `u_{σ i}` the scaling coordinate germ (`coord`) — by the any-chart form
  `exists_stalk_jacobianStalk_eq_span_of_charts` of `Hironaka/Manifold/Jacobian/Units.lean`
  applied to the chart pair `(φ, Φ)`, the germ of `J_{φ,Φ}` being that of `u_{σ i}^{c-1}`.

Boundary cases: `c = 0` and `c = 1` give exponent `0` and the unit ideal; off the exceptional
divisor `u_{σ i}` is a unit, so the stalk is the unit ideal there too, as
`jacobianStalk_eq_top_of_isLocalDiffeomorphAt` says directly. This is the one-blow-up computation
`det = y^{codim − 1}` behind the Jacobian clause of the principalization theorem
[BM97, Theorem 1.10, the sentence after it]; the ideal-sheaf form is
`Hironaka/Manifold/Jacobian/Bundled.lean`.
-/

public section

open Filter Topology Set TopologicalSpace
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

namespace Manifold

universe u

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {M' : Type u}
  [TopologicalSpace M'] [ChartedSpace E M'] {Y : Set M} {c : ℕ} {π : M' → M}

/-- In a blow-up chart `Φ` of index `i` over the adapted chart `φ`, **the Jacobian determinant of
`π` in the charts `(φ, Φ)` is `u_{σ i}^{c-1}`** (the chart formulas of [BM88, Definition 4.1]): the
chart representative is `ψ⁻¹ ∘ π_i ∘ ψ` (`IsBlowUpChart.comm`), and conjugation by `ψ` does not
change the determinant. -/
theorem jacobianFun_blowUpChart {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n}
    (hφ : IsAdaptedChart ψ Y φ σ) {i : Fin c} {Φ : OpenPartialHomeomorph M' E}
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) {p : M'} (hp : p ∈ Φ.source) :
    jacobianFun 𝕜 π φ Φ p = ψ (Φ p) (σ i) ^ (c - 1) := by
  have _hφ := hφ
  -- on `Φ.target`, `φ ∘ π ∘ Φ⁻¹ = ψ⁻¹ ∘ π_i ∘ ψ`
  have hloc : (φ ∘ π ∘ Φ.symm) =ᶠ[𝓝 (Φ p)] (ψ.symm ∘ blowUpChartMap σ i ∘ ψ) := by
    filter_upwards [Φ.open_target.mem_nhds (Φ.map_source hp)] with v hv
    simp only [Function.comp_apply]
    have hcomm := hΦ.comm (Φ.symm v) (Φ.map_target hv)
    rw [Φ.right_inv hv] at hcomm
    rw [← hcomm, ψ.symm_apply_apply]
  unfold jacobianFun
  rw [hloc.fderiv_eq, ContinuousLinearEquiv.comp_fderiv, ContinuousLinearEquiv.comp_right_fderiv,
    ← det_fderiv_blowUpChartMap σ (ψ (Φ p))]
  exact LinearMap.det_conj
    (fderiv 𝕜 (blowUpChartMap σ i) (ψ (Φ p)) : (Fin n → 𝕜) →ₗ[𝕜] (Fin n → 𝕜))
    ψ.symm.toLinearEquiv

variable [IsManifold 𝓘(𝕜, E) ω M] [IsManifold 𝓘(𝕜, E) ω M'] [T2Space M']
  [SecondCountableTopology M']

/-- At a point `p` of a blow-up chart `Φ` of index `i`, **the stalk of the Jacobian ideal of the
blowing-up is generated by `u_{σ i}^{c-1}`**: in the charts `(φ, Φ)` the Jacobian determinant is
that power of the scaling coordinate, and in any other charts a unit times it. -/
theorem jacobianStalk_blowUp (h : IsBlowUp ψ Y c π) {φ : OpenPartialHomeomorph M E}
    {σ : Fin c ↪ Fin n} (hφ : IsAdaptedChart ψ Y φ σ) {i : Fin c} {Φ : OpenPartialHomeomorph M' E}
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) {p : M'} (hp : p ∈ Φ.source) :
    jacobianStalk π p = Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i) ^ (c - 1)} := by
  obtain ⟨s, hs, hspan⟩ := exists_stalk_jacobianStalk_eq_span_of_charts h.contMDiff hφ.1
    hΦ.mem_maximalAtlas hp (hΦ.source_subset hp)
  have hs' : s = coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i) ^ (c - 1) := by
    apply stalkToGerm_injective 𝓘(𝕜, E) ω M' p
    rw [hs, map_pow, stalkToGerm_coord, ← Germ.coe_pow]
    refine Germ.coe_eq.mpr ?_
    filter_upwards [Φ.open_source.mem_nhds hp] with q hq
    rw [Pi.pow_apply, jacobianFun_blowUpChart hφ hΦ hq, extendSection_of_mem 𝕜 E _ hq]
    rfl
  rw [hspan, hs']

end Manifold
