/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Jacobian.Defs
public import Hironaka.Manifold.BlowUp.Defs
public import Hironaka.Manifold.IdealSheaf.Basic
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.Jacobian.BlowUp
import Hironaka.Manifold.Jacobian.Units
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial
/-!
# The Jacobian ideal on bundled manifolds

`AnalyticMap.jacobianIdeal f` (the ideal sheaf of the Jacobian clause of the principalization
theorem [BM97, Theorem 1.10, the sentence after it]) is
the ideal sheaf `ofStalks` of the stalks `jacobianStalk f` when these have local generators, and
the unit ideal sheaf otherwise. This module reads the two branches
(`jacobianIdeal_eq_of_hasLocalGenerators`, `jacobianIdeal_eq_top_of_not`), notes that the first
branch is always the one taken (`hasLocalGenerators_jacobianStalk`), so that the stalks of the
Jacobian ideal are the `jacobianStalk`s (`jacobianIdeal_stalkIdeal`), and identifies the Jacobian
ideal of the blowing-up along a closed submanifold of codimension `c` with the `(c − 1)`-st power
of the exceptional ideal sheaf `I_F = π^*(𝓘_Y)` (`jacobianIdeal_blowUp_eq_pow`; at the stalks,
`jacobianIdeal_blowUp_stalkIdeal`): at a point `p` with `π p ∈ Y`, an adapted chart at `π p` and a
blow-up chart through `p` (`IsBlowUp.cover`) give both stalks as `(u_{σ i}^{c-1})`
(`jacobianStalk_blowUp`, `stalkIdeal_exceptionalIdealSheaf_eq_span_coord` with
`Ideal.span_singleton_pow`); off `π⁻¹(Y)` both stalks are the unit ideal — `I_F`'s by
`stalkIdeal_exceptionalIdealSheaf_of_notMem`, the Jacobian's because the blowing-up is a local
diffeomorphism there (`IsBlowUp.isLocalDiffeomorphOn_compl`,
`jacobianStalk_eq_top_of_isLocalDiffeomorphAt`). This last case is the whole of the identity when
`c = 0` or `Y = ∅` (then no blow-up chart exists), and the exponent `c − 1 = 0` gives the unit
ideal sheaf on both sides for `c ≤ 1`. The identity is the input of the Jacobian clause along a
sequence of blow-ups (`Hironaka/Resolution/Analytic/Principalization/JacobianMonomial.lean`).
-/

public section

open Filter Topology Set TopologicalSpace
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

namespace Manifold

universe u

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {N N' : AnalyticManifold.{u} 𝕜 E}

/-- The first branch of `AnalyticMap.jacobianIdeal`: when the stalks of the Jacobian ideal have
local generators, the Jacobian ideal is the ideal sheaf with those stalks. -/
theorem jacobianIdeal_eq_of_hasLocalGenerators (f : AnalyticMap N' N)
    (h : IdealSheaf.HasLocalGenerators (𝒪 := structureSheaf 𝕜 E N') (jacobianStalk ⇑f)) :
    AnalyticMap.jacobianIdeal f = IdealSheaf.ofStalks _ _ h :=
  dite_eq_left h

/-- The second branch of `AnalyticMap.jacobianIdeal` (never taken:
`hasLocalGenerators_jacobianStalk`). -/
theorem jacobianIdeal_eq_top_of_not (f : AnalyticMap N' N)
    (h : ¬ IdealSheaf.HasLocalGenerators (𝒪 := structureSheaf 𝕜 E N') (jacobianStalk ⇑f)) :
    AnalyticMap.jacobianIdeal f = ⊤ :=
  dite_eq_right h

/-- **The stalks of the Jacobian ideal are the ideals generated by the germ of the Jacobian
determinant of `f` in the standard charts** ([BM97, Theorem 1.10, the sentence after it]). -/
theorem jacobianIdeal_stalkIdeal (f : AnalyticMap N' N) (a' : N') :
    (AnalyticMap.jacobianIdeal f).stalkIdeal a' = jacobianStalk ⇑f a' := by
  rw [jacobianIdeal_eq_of_hasLocalGenerators f (hasLocalGenerators_jacobianStalk f.contMDiff),
    IdealSheaf.stalkIdeal_ofStalks]

/-- For the blowing-up, at the stalks: in a blow-up chart of index `i` the stalk of the Jacobian
ideal is `(u_{σ i}^{c-1})`. -/
theorem jacobianIdeal_blowUp_stalkIdeal (π : AnalyticMap N' N) {Y : Set N}
    {c : ℕ}
    (h : IsBlowUp ψ Y c π) {φ : OpenPartialHomeomorph N E} {σ : Fin c ↪ Fin n}
    (hφ : IsAdaptedChart ψ Y φ σ) {i : Fin c} {Φ : OpenPartialHomeomorph N' E}
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) {p : N'} (hp : p ∈ Φ.source) :
    (AnalyticMap.jacobianIdeal π).stalkIdeal p =
      Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i) ^ (c - 1)} := by
  rw [jacobianIdeal_stalkIdeal, jacobianStalk_blowUp h hφ hΦ hp]

/-- **The Jacobian ideal of the blowing-up of `N` along a closed submanifold `Y` of codimension `c`
is the `(c − 1)`-st power of the exceptional ideal sheaf `I_F = π^*(𝓘_Y)`** (the chart formulas of
[BM88, Definition 4.1]; the Jacobian ideal of [BM97, Theorem 1.10, the sentence after it]). Stalk
by stalk: through a blow-up chart at points over `Y`, and off `π⁻¹(Y)` both sides are the unit
ideal, the blowing-up being a local diffeomorphism there. -/
theorem jacobianIdeal_blowUp_eq_pow (π : AnalyticMap N' N) {Y : Set N} {c : ℕ}
    (hY : IsClosedSubmanifold ψ Y c) (h : IsBlowUp ψ Y c π) :
    AnalyticMap.jacobianIdeal π = hY.idealSheaf.pullback π h.contMDiff ^ (c - 1) := by
  refine IdealSheaf.ext fun p => ?_
  rw [jacobianIdeal_stalkIdeal, IdealSheaf.stalkIdeal_pow]
  by_cases hpY : π p ∈ Y
  · obtain ⟨φ, σ, hπp, hφ⟩ := hY.exists_adaptedChart (π p) hpY
    obtain ⟨i, Φ, hΦ, hp⟩ := h.cover φ σ hφ p hπp
    rw [jacobianStalk_blowUp h hφ hΦ hp,
      stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hp, Ideal.span_singleton_pow]
  · rw [stalkIdeal_exceptionalIdealSheaf_of_notMem hY h hpY, Ideal.top_pow]
    exact jacobianStalk_eq_top_of_isLocalDiffeomorphAt π.contMDiff
      (h.isLocalDiffeomorphOn_compl ⟨p, hpY⟩)

end Manifold
