/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Jacobian.Defs
import Hironaka.Manifold.Jacobian.Units
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# The chain rule for the Jacobian stalk

For a composite of blow-ups, `det DΠ_r = (det DΠ_{r−1} ∘ π_{r−1}) · det Dπ_{r−1}` (the chain rule
and the multiplicativity of the determinant), so that the Jacobian ideal of a composite is the
product of the pull-back of the outer Jacobian ideal and the inner one. At the stalks of the
Jacobian ideal (`jacobianStalk`) this is
`jacobianStalk (g ∘ f) a = (jacobianStalk g (f a)).map (germMap f a) · jacobianStalk f a`
(`jacobianStalk_comp`): the chart representative of `g ∘ f` in charts `χ` (target) and `φ`
(source) is, near `φ a`, the composite of the representatives of `g` (charts `χ`, `θ`) and of `f`
(charts `θ`, `φ`) through an intermediate chart `θ` at `f a` (`jacobianFun_comp`, the pointwise
chain rule, proved as `fderiv_chartRep_eq` is), so the Jacobian determinants multiply pointwise;
`exists_stalk_jacobianStalk_eq_span_of_charts` turns the three determinant germs into generators
of the three stalks, and `stalkToGerm_germMap` identifies the pulled-back germ with the composite
function germ. Corollaries: when one factor is a local diffeomorphism at the point its Jacobian
stalk is the unit ideal (`jacobianStalk_eq_top_of_isLocalDiffeomorphAt`), so the composite's stalk
is the other factor's (transported along the stalk map, for the inner factor). The chain rule is
the step of the Jacobian ledger along a blow-up sequence
(`Hironaka/Resolution/Analytic/BM97/LedgerStep.lean`), and the corollaries transport the ledger
along the open embeddings and inclusions of the gluing
(`Hironaka/Resolution/Analytic/BM97/LedgerLimit.lean`). The Jacobian clause itself is [BM97, Theorem
1.10, the sentence after it].
-/

public section

open Filter Topology Set TopologicalSpace
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

namespace Manifold

universe u

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M] [IsManifold 𝓘(𝕜, E) ω M]
  {N : Type u} [TopologicalSpace N] [ChartedSpace E N] [IsManifold 𝓘(𝕜, E) ω N]
  {P : Type u} [TopologicalSpace P] [ChartedSpace E P] [IsManifold 𝓘(𝕜, E) ω P]

omit [IsManifold 𝓘(𝕜, E) ω M] [IsManifold 𝓘(𝕜, E) ω N] [IsManifold 𝓘(𝕜, E) ω P] in
/-- The pointwise chain rule: the Jacobian determinant of `g ∘ f` in charts `χ` (target) and `φ`
(source) at a point is the product of the determinants of `g` (charts `χ`, `θ`) at `f y` and of `f`
(charts `θ`, `φ`) at `y`, for any chart `θ` at `f y` — `fderiv_comp` on the local identity
`χ ∘ (g ∘ f) ∘ φ⁻¹ = (χ ∘ g ∘ θ⁻¹) ∘ (θ ∘ f ∘ φ⁻¹)` and `det_clm_comp`. -/
theorem jacobianFun_comp {f : P → N} {g : N → M} (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    (hg : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω g) {χ : OpenPartialHomeomorph M E}
    (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {θ : OpenPartialHomeomorph N E}
    (hθ : θ ∈ maximalAtlas 𝓘(𝕜, E) ω N) {φ : OpenPartialHomeomorph P E}
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω P) {y : P} (hy : y ∈ φ.source) (hfy : f y ∈ θ.source)
    (hgfy : g (f y) ∈ χ.source) :
    jacobianFun 𝕜 (g ∘ f) χ φ y = jacobianFun 𝕜 g χ θ (f y) * jacobianFun 𝕜 f θ φ y := by
  unfold jacobianFun
  have hopen : IsOpen (φ.target ∩ φ.symm ⁻¹' (φ.source ∩ f ⁻¹' θ.source)) :=
    isOpen_target_inter_preimage_symm φ
      (φ.open_source.inter (θ.open_source.preimage hf.continuous))
  have hmem : φ y ∈ φ.target ∩ φ.symm ⁻¹' (φ.source ∩ f ⁻¹' θ.source) :=
    ⟨φ.map_source hy, by rw [mem_preimage, φ.left_inv hy]; exact ⟨hy, hfy⟩⟩
  have hloc : (χ ∘ (g ∘ f) ∘ φ.symm) =ᶠ[𝓝 (φ y)] (χ ∘ g ∘ θ.symm) ∘ (θ ∘ f ∘ φ.symm) := by
    filter_upwards [hopen.mem_nhds hmem] with v hv
    simp only [Function.comp_apply]
    rw [θ.left_inv hv.2.2]
  rw [hloc.fderiv_eq]
  have hB : DifferentiableAt 𝕜 (θ ∘ f ∘ φ.symm) (φ y) := differentiableAt_chartRep hf hθ hφ hy hfy
  have hBy : (θ ∘ f ∘ φ.symm) (φ y) = θ (f y) := by
    simp only [Function.comp_apply, φ.left_inv hy]
  have hA : DifferentiableAt 𝕜 (χ ∘ g ∘ θ.symm) ((θ ∘ f ∘ φ.symm) (φ y)) := by
    rw [hBy]; exact differentiableAt_chartRep hg hχ hθ hfy hgfy
  rw [fderiv_comp (φ y) hA hB, det_clm_comp, hBy]

/-- **The chain rule for the Jacobian stalk**:
`jacobianStalk (g ∘ f) a = (jacobianStalk g (f a)).map (germMap f a) · jacobianStalk f a` — the
three stalks are principal, generated by the determinant germs in the standard charts, and
`jacobianFun_comp` multiplies the germs. -/
theorem jacobianStalk_comp {f : P → N} {g : N → M} (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    (hg : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω g) (a : P) :
    jacobianStalk (𝕜 := 𝕜) (E := E) (g ∘ f) a =
      Ideal.map (germMap f hf a) (jacobianStalk (𝕜 := 𝕜) (E := E) g (f a)) *
        jacobianStalk (𝕜 := 𝕜) (E := E) f a := by
  have hχ := IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) (g (f a))
  have hθ := IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) (f a)
  have hφ := IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) a
  obtain ⟨s₁, hs₁, h₁⟩ := exists_stalk_jacobianStalk_eq_span_of_charts (hg.comp hf) hχ hφ
    (mem_chart_source E a) (mem_chart_source E (g (f a)))
  obtain ⟨s₂, hs₂, h₂⟩ := exists_stalk_jacobianStalk_eq_span_of_charts hg hχ hθ
    (mem_chart_source E (f a)) (mem_chart_source E (g (f a)))
  obtain ⟨s₃, hs₃, h₃⟩ := exists_stalk_jacobianStalk_eq_span_of_charts hf hθ hφ
    (mem_chart_source E a) (mem_chart_source E (f a))
  have key : s₁ = germMap f hf a s₂ * s₃ := by
    apply stalkToGerm_injective 𝓘(𝕜, E) ω P a
    rw [hs₁, map_mul, stalkToGerm_germMap, hs₂, hs₃, Germ.coe_compTendsto, ← Germ.coe_mul,
      Germ.coe_eq]
    have hopen : IsOpen (((chartAt E a).source ∩ f ⁻¹' (chartAt E (f a)).source) ∩
        (g ∘ f) ⁻¹' (chartAt E (g (f a))).source) :=
      ((chartAt E a).open_source.inter
        ((chartAt E (f a)).open_source.preimage hf.continuous)).inter
        ((chartAt E (g (f a))).open_source.preimage (hg.comp hf).continuous)
    filter_upwards [hopen.mem_nhds ⟨⟨mem_chart_source E a, mem_chart_source E (f a)⟩,
      mem_chart_source E (g (f a))⟩] with y hy
    exact jacobianFun_comp hf hg hχ hθ hφ hy.1.1 hy.1.2 hy.2
  rw [h₁, h₂, h₃, Ideal.map_span, Set.image_singleton, Ideal.span_singleton_mul_span_singleton,
    key]

/-- When the outer map is a local diffeomorphism at `f a`, the composite's Jacobian stalk is the
inner map's (the case of an open inclusion after a blow-down). -/
theorem jacobianStalk_comp_of_isLocalDiffeomorphAt_left {f : P → N} {g : N → M}
    (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) (hg : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω g) (a : P)
    (hloc : IsLocalDiffeomorphAt 𝓘(𝕜, E) 𝓘(𝕜, E) ω g (f a)) :
    jacobianStalk (𝕜 := 𝕜) (E := E) (g ∘ f) a = jacobianStalk (𝕜 := 𝕜) (E := E) f a := by
  rw [jacobianStalk_comp hf hg a, jacobianStalk_eq_top_of_isLocalDiffeomorphAt hg hloc,
    Ideal.map_top, Ideal.top_mul]

/-- When the inner map is a local diffeomorphism at `a`, the composite's Jacobian stalk is the
transport of the outer map's along the inner map's stalk map (the case of a glued blow-down after
the open embedding of a piece). -/
theorem jacobianStalk_comp_of_isLocalDiffeomorphAt_right {f : P → N} {g : N → M}
    (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) (hg : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω g) (a : P)
    (hloc : IsLocalDiffeomorphAt 𝓘(𝕜, E) 𝓘(𝕜, E) ω f a) :
    jacobianStalk (𝕜 := 𝕜) (E := E) (g ∘ f) a =
      Ideal.map (germMap f hf a) (jacobianStalk (𝕜 := 𝕜) (E := E) g (f a)) := by
  rw [jacobianStalk_comp hf hg a, jacobianStalk_eq_top_of_isLocalDiffeomorphAt hf hloc,
    Ideal.mul_top]

end Manifold
