/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Defs
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# The Jacobian determinant of an analytic map in charts; the Jacobian ideal

The Jacobian ideal of an analytic map, the ideal sheaf of the Jacobian clause of the
principalization theorem — Bierstone–Milman's "the ideal generated (locally, with respect to any
coordinate system) by the Jacobian determinant of `σ`" [BM97, Theorem 1.10, the sentence after it].

* `jacobianFun f χ φ'` is the Jacobian determinant of `f : N → M` read in a chart `χ` of the target
  and a chart `φ'` of the source: `y ↦ det D(χ ∘ f ∘ φ'⁻¹)(φ' y)`, with Mathlib's
  `ContinuousLinearMap.det` — coordinate-free on the model space `E`, no basis is chosen.
* `jacobianStalk f a'` is the ideal of `𝒪_{N,a'}` generated by the germs of analytic functions
  whose function germ (`stalkToGerm`) is the germ at `a'` of that Jacobian determinant in the
  standard charts `chartAt E (f a')`, `chartAt E a'`. When the Jacobian determinant is analytic
  near `a'` — which holds for every analytic `f` between analytic manifolds
  (`Hironaka/Manifold/Jacobian/Analytic.lean`) — this generating set is a single germ
  (`stalkToGerm` is injective); the definition itself needs no analyticity proof.
* `AnalyticMap.jacobianIdeal f`, for an analytic map of bundled analytic manifolds, is the ideal
  sheaf `ofStalks` of these stalks when they have local generators, and the unit ideal sheaf
  otherwise.

The dependence on the charts is only up to units (chain rule and multiplicativity of the
determinant, the Jacobians of the chart changes being units:
`Hironaka/Manifold/Jacobian/Units.lean`), so the Jacobian ideal is Bierstone–Milman's "with respect
to any coordinate system".
-/

@[expose] public section

open TopologicalSpace Opposite CategoryTheory Filter Topology
open scoped Manifold ContDiff

universe u

namespace Manifold

variable {𝕜 : Type} [NontriviallyNormedField 𝕜] {E : Type*} [NormedAddCommGroup E]
  [NormedSpace 𝕜 E] {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {N : Type u}
  [TopologicalSpace N] [ChartedSpace E N]

variable (𝕜) in
/-- **The Jacobian determinant of `f : N → M` in the charts `χ` (target) and `φ'` (source)** at
`y`, `det D(χ ∘ f ∘ φ'⁻¹)(φ' y)` — the determinant (`ContinuousLinearMap.det`, coordinate-free on
`E`) of the derivative of the chart representative of `f` ("the Jacobian determinant of `σ`",
[BM97, Theorem 1.10, the sentence after it]). The scalar field is explicit, as in `fderiv 𝕜`. -/
noncomputable def jacobianFun (f : N → M) (χ : OpenPartialHomeomorph M E)
    (φ' : OpenPartialHomeomorph N E) (y : N) : 𝕜 :=
  (fderiv 𝕜 (χ ∘ f ∘ φ'.symm) (φ' y)).det

/-- **The stalk at `a'` of the Jacobian ideal of `f`**: the ideal of `𝒪_{N,a'}` generated by the
germs whose function germ (`stalkToGerm`) is the germ at `a'` of the Jacobian determinant of `f` in
the standard charts `chartAt E (f a')` and `chartAt E a'`. The generating set is the single germ of
that analytic function when it is analytic near `a'` (which holds for every analytic `f`), and
empty otherwise. -/
noncomputable def jacobianStalk (f : N → M) (a' : N) :
    Ideal ((structureSheaf 𝕜 E N).presheaf.stalk a') :=
  Ideal.span ((stalkToGerm 𝓘(𝕜, E) ω N a') ⁻¹'
    {((jacobianFun 𝕜 f (chartAt E (f a')) (chartAt E a') : N → 𝕜) : (𝓝 a').Germ 𝕜)})

end Manifold

namespace AnalyticManifold

variable {𝕜 : Type} [NontriviallyNormedField 𝕜] {E : Type*} [NormedAddCommGroup E]
  [NormedSpace 𝕜 E]

open Classical in
/-- The ideal sheaf generated locally, in any analytic coordinates on source and target, by the
Jacobian determinant of `f` [BM97, Theorem 1.10, the sentence after it] — independent of the
coordinates, since a chart change multiplies the determinant by a unit: the ideal sheaf whose
stalk at `a'` is generated by the germ of the Jacobian determinant of `f` in the standard charts
`chartAt (f a')` and `chartAt a'` (`Manifold.jacobianStalk`), when these stalks have
local generators (they do for every analytic `f`: the Jacobian determinant is analytic and its
germ at a nearby point is a unit multiple of the germ in the charts at that point,
`Hironaka/Manifold/Jacobian/`), and the unit ideal sheaf otherwise. -/
noncomputable def _root_.AnalyticMap.jacobianIdeal {M M' : AnalyticManifold.{u} 𝕜 E}
    (f : AnalyticMap M' M) : IdealSheaf M' :=
  if h : Manifold.IdealSheaf.HasLocalGenerators
      (𝒪 := Manifold.structureSheaf 𝕜 E M')
      (Manifold.jacobianStalk (𝕜 := 𝕜) (E := E) ⇑f) then
    Manifold.IdealSheaf.ofStalks _ _ h
  else ⊤

end AnalyticManifold
