/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Jacobian.Analytic
public import Hironaka.Manifold.Germ.StalkMap
import Hironaka.Manifold.Sheaf.LocalRing
import Hironaka.Manifold.Submanifold.Manifold
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# Chart independence of the Jacobian determinant up to units

Bierstone–Milman's Jacobian ideal is "the ideal generated (locally, with respect to any coordinate
system) by the Jacobian determinant" [BM97, Theorem 1.10, the sentence after it]: the Jacobian
determinant of an analytic map `f` in two chart pairs differs by an analytic unit, so the ideal it
generates in `𝒪_{M',a'}` does not depend on the charts, and the stalks of the Jacobian ideal have
local generators.

* **The chain rule** (`fderiv_chartRep_eq`): for chart pairs `(χ, φ')`, `(χ', φ'')` at `a'`,
  `χ' ∘ f ∘ φ''⁻¹ = (χ' ∘ χ⁻¹) ∘ (χ ∘ f ∘ φ'⁻¹) ∘ (φ' ∘ φ''⁻¹)` near `φ''(a')`, so
  `D(χ' ∘ f ∘ φ''⁻¹)(φ'' y) = D(χ' ∘ χ⁻¹)(χ(f y)) ∘ D(χ ∘ f ∘ φ'⁻¹)(φ' y) ∘ D(φ' ∘ φ''⁻¹)(φ'' y)`
  (`fderiv_comp` twice, the two chart changes being analytic by `contDiffOn_chartChange`).
* **Multiplicativity of the determinant** gives `J_{χ',φ''} = a · J_{χ,φ'} · b` with
  `a = det D(χ' ∘ χ⁻¹) ∘ χ ∘ f` and `b = det D(φ' ∘ φ''⁻¹) ∘ φ''` analytic near `a'`
  (`Hironaka/Manifold/Jacobian/Analytic.lean`), and nonvanishing at `a'`: each chart change has
  the inverse chart change as a two-sided inverse, so `det (Dg'(g x)) · det (Dg x) = 1`
  (`det_fderiv_mul_det_fderiv_eq_one`). A germ of `𝒪_{M',a'}` is a unit iff its value at `a'` is
  nonzero (`isUnit_stalk_iff`), so the germ of `a · b` is the unit `u` of
  `exists_unit_jacobianFun_germ_eq`.
* **Consequences.** The stalk `jacobianStalk f a'` — the ideal generated by the germs whose
  function germ is the Jacobian determinant in the standard charts — is generated by one germ
  (`exists_stalk_jacobianStalk_eq_span`: the determinant is analytic, so its germ is the function
  germ of a section, and `stalkToGerm` is injective), by the determinant in any chart pair
  (`exists_stalk_jacobianStalk_eq_span_of_charts`: the unit `u` does not change the ideal,
  `Ideal.span_singleton_mul_left_unit`), and the stalks have local generators
  (`hasLocalGenerators_jacobianStalk`: near `a'` the single section `det D(χ ∘ f ∘ φ'⁻¹) ∘ φ'` for
  the standard charts `χ`, `φ'` at `a'` generates every stalk, by the any-chart form) — so the
  first branch of `AnalyticMap.jacobianIdeal` is always the one taken.
* **Local diffeomorphisms.** Where `f` is a local diffeomorphism its Jacobian determinant is a unit
  (`isUnit_jacobianFun_of_isLocalDiffeomorphAt`: the chart representative of Mathlib's
  `localInverse` is a left inverse of the chart representative of `f`) and the stalk of the
  Jacobian ideal is the unit ideal (`jacobianStalk_eq_top_of_isLocalDiffeomorphAt`) — the case of
  an isomorphism in the principalization theorem, and the off-centre case of the blowing-up
  (`Hironaka/Manifold/Jacobian/BlowUp.lean`).
-/

@[expose] public section

open Filter Topology Set TopologicalSpace Opposite CategoryTheory
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

namespace Manifold

universe u

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {N : Type u} [TopologicalSpace N]
  [ChartedSpace E N] {f : N → M}

section ChainRule

/-- The common domain of two chart pairs: `φ'.source ∩ φ''.source ∩ f⁻¹(χ.source ∩ χ'.source)`. -/
abbrev chartPairDomain (f : N → M) (χ χ' : OpenPartialHomeomorph M E)
    (φ' φ'' : OpenPartialHomeomorph N E) : Set N :=
  (φ'.source ∩ φ''.source) ∩ f ⁻¹' (χ.source ∩ χ'.source)

theorem isOpen_chartPairDomain (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    (χ χ' : OpenPartialHomeomorph M E) (φ' φ'' : OpenPartialHomeomorph N E) :
    IsOpen (chartPairDomain f χ χ' φ' φ'') :=
  (φ'.open_source.inter φ''.open_source).inter
    ((χ.open_source.inter χ'.open_source).preimage hf.continuous)

/-- A chart change `χ' ∘ χ⁻¹` is differentiable at the image `χ x` of a point `x` of
`χ.source ∩ χ'.source`. -/
theorem differentiableAt_chartChange {χ χ' : OpenPartialHomeomorph M E}
    (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M) (hχ' : χ' ∈ maximalAtlas 𝓘(𝕜, E) ω M) {x : M}
    (hx : x ∈ χ.source) (hx' : x ∈ χ'.source) : DifferentiableAt 𝕜 (χ' ∘ χ.symm) (χ x) := by
  have hmem : χ x ∈ χ.target ∩ χ.symm ⁻¹' χ'.source :=
    ⟨χ.map_source hx, by rw [mem_preimage, χ.left_inv hx]; exact hx'⟩
  exact ((contDiffOn_chartChange hχ hχ').differentiableOn (by simp)).differentiableAt
    ((isOpen_target_inter_preimage_symm χ χ'.open_source).mem_nhds hmem)

/-- The chart representative `χ ∘ f ∘ φ'⁻¹` is differentiable at `φ' y` for `y` in
`φ'.source ∩ f⁻¹(χ.source)`. -/
theorem differentiableAt_chartRep (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    {χ : OpenPartialHomeomorph M E} (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    {φ' : OpenPartialHomeomorph N E} (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N) {y : N}
    (hy : y ∈ φ'.source) (hfy : f y ∈ χ.source) :
    DifferentiableAt 𝕜 (χ ∘ f ∘ φ'.symm) (φ' y) := by
  have hmem : φ' y ∈ φ'.target ∩ φ'.symm ⁻¹' (f ⁻¹' χ.source) :=
    mapsTo_chart_target_inter χ φ' ⟨hy, hfy⟩
  exact ((contDiffOn_chartRep hf hχ hφ').differentiableOn (by simp)).differentiableAt
    ((isOpen_target_inter_preimage_symm φ' (χ.open_source.preimage hf.continuous)).mem_nhds hmem)

/-- **The chain rule for the chart representatives**: on the common domain,
`D(χ' ∘ f ∘ φ''⁻¹)(φ'' y) = D(χ' ∘ χ⁻¹)(χ (f y)) ∘ D(χ ∘ f ∘ φ'⁻¹)(φ' y) ∘ D(φ' ∘ φ''⁻¹)(φ'' y)`. -/
theorem fderiv_chartRep_eq (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) {χ χ' : OpenPartialHomeomorph M E}
    (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M) (hχ' : χ' ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    {φ' φ'' : OpenPartialHomeomorph N E} (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N)
    (hφ'' : φ'' ∈ maximalAtlas 𝓘(𝕜, E) ω N) {y : N} (hy : y ∈ chartPairDomain f χ χ' φ' φ'') :
    fderiv 𝕜 (χ' ∘ f ∘ φ''.symm) (φ'' y) =
      (fderiv 𝕜 (χ' ∘ χ.symm) (χ (f y))).comp
        ((fderiv 𝕜 (χ ∘ f ∘ φ'.symm) (φ' y)).comp (fderiv 𝕜 (φ' ∘ φ''.symm) (φ'' y))) := by
  obtain ⟨⟨hy', hy''⟩, hfy, hfy'⟩ := hy
  -- the local identity `χ' ∘ f ∘ φ''⁻¹ = (χ' ∘ χ⁻¹) ∘ (χ ∘ f ∘ φ'⁻¹) ∘ (φ' ∘ φ''⁻¹)`
  have hloc : (χ' ∘ f ∘ φ''.symm) =ᶠ[𝓝 (φ'' y)]
      (χ' ∘ χ.symm) ∘ ((χ ∘ f ∘ φ'.symm) ∘ (φ' ∘ φ''.symm)) := by
    have hopen : IsOpen (φ''.target ∩ φ''.symm ⁻¹' chartPairDomain f χ χ' φ' φ'') :=
      isOpen_target_inter_preimage_symm φ'' (isOpen_chartPairDomain hf χ χ' φ' φ'')
    have hmem : φ'' y ∈ φ''.target ∩ φ''.symm ⁻¹' chartPairDomain f χ χ' φ' φ'' :=
      ⟨φ''.map_source hy'', by
        rw [mem_preimage, φ''.left_inv hy'']; exact ⟨⟨hy', hy''⟩, hfy, hfy'⟩⟩
    filter_upwards [hopen.mem_nhds hmem] with v hv
    have hz' : φ''.symm v ∈ φ'.source := hv.2.1.1
    have hfz : f (φ''.symm v) ∈ χ.source := hv.2.2.1
    simp only [Function.comp_apply]
    rw [φ'.left_inv hz', χ.left_inv hfz]
  rw [hloc.fderiv_eq]
  have hB : DifferentiableAt 𝕜 (φ' ∘ φ''.symm) (φ'' y) :=
    differentiableAt_chartChange hφ'' hφ' hy'' hy'
  have hBy : (φ' ∘ φ''.symm) (φ'' y) = φ' y := by
    simp only [Function.comp_apply, φ''.left_inv hy'']
  have hG : DifferentiableAt 𝕜 (χ ∘ f ∘ φ'.symm) ((φ' ∘ φ''.symm) (φ'' y)) := by
    rw [hBy]; exact differentiableAt_chartRep hf hχ hφ' hy' hfy
  have hA : DifferentiableAt 𝕜 (χ' ∘ χ.symm) (((χ ∘ f ∘ φ'.symm) ∘ (φ' ∘ φ''.symm)) (φ'' y)) := by
    have : ((χ ∘ f ∘ φ'.symm) ∘ (φ' ∘ φ''.symm)) (φ'' y) = χ (f y) := by
      simp only [Function.comp_apply, φ''.left_inv hy'', φ'.left_inv hy']
    rw [this]; exact differentiableAt_chartChange hχ hχ' hfy hfy'
  rw [fderiv_comp (φ'' y) hA (hG.comp (φ'' y) hB), fderiv_comp (φ'' y) hG hB]
  simp only [Function.comp_apply, φ''.left_inv hy'', φ'.left_inv hy']

/-- **The Jacobian determinants in two chart pairs differ by the Jacobians of the two chart
changes**: on the common domain,
`J_{χ',φ''}(y) = det D(χ' ∘ χ⁻¹)(χ(f y)) · J_{χ,φ'}(y) · det D(φ' ∘ φ''⁻¹)(φ'' y)`. -/
theorem jacobianFun_eq_mul (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) {χ χ' : OpenPartialHomeomorph M E}
    (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M) (hχ' : χ' ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    {φ' φ'' : OpenPartialHomeomorph N E} (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N)
    (hφ'' : φ'' ∈ maximalAtlas 𝓘(𝕜, E) ω N) {y : N} (hy : y ∈ chartPairDomain f χ χ' φ' φ'') :
    jacobianFun 𝕜 f χ' φ'' y =
      (fderiv 𝕜 (χ' ∘ χ.symm) (χ (f y))).det *
        (jacobianFun 𝕜 f χ φ' y * (fderiv 𝕜 (φ' ∘ φ''.symm) (φ'' y)).det) := by
  unfold jacobianFun
  rw [fderiv_chartRep_eq hf hχ hχ' hφ' hφ'' hy, det_clm_comp, det_clm_comp]

/-- The Jacobian of a chart change is nonzero at the image of a point of both charts: the inverse
chart change is a two-sided inverse, and `det (Dg'(g x)) · det (Dg x) = 1`. -/
theorem det_fderiv_chartChange_ne_zero {χ χ' : OpenPartialHomeomorph M E}
    (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M) (hχ' : χ' ∈ maximalAtlas 𝓘(𝕜, E) ω M) {x : M}
    (hx : x ∈ χ.source) (hx' : x ∈ χ'.source) : (fderiv 𝕜 (χ' ∘ χ.symm) (χ x)).det ≠ 0 := by
  have hmem : χ x ∈ χ.target ∩ χ.symm ⁻¹' χ'.source :=
    ⟨χ.map_source hx, by rw [mem_preimage, χ.left_inv hx]; exact hx'⟩
  have hgg' : ∀ v ∈ χ.target ∩ χ.symm ⁻¹' χ'.source, (χ ∘ χ'.symm) ((χ' ∘ χ.symm) v) = v := by
    intro v hv
    simp only [Function.comp_apply]
    rw [χ'.left_inv hv.2, χ.right_inv hv.1]
  have hg' : DifferentiableAt 𝕜 (χ ∘ χ'.symm) ((χ' ∘ χ.symm) (χ x)) := by
    have : (χ' ∘ χ.symm) (χ x) = χ' x := by simp only [Function.comp_apply, χ.left_inv hx]
    rw [this]
    exact differentiableAt_chartChange hχ' hχ hx' hx
  have h1 := det_fderiv_mul_det_fderiv_eq_one (isOpen_target_inter_preimage_symm χ χ'.open_source)
    hmem (differentiableAt_chartChange hχ hχ' hx hx') hg' hgg'
  exact right_ne_zero_of_mul_eq_one h1

/-- The stalk element with function germ the Jacobian determinant `J_{χ,φ'}` at a point of
`φ'.source ∩ f⁻¹(χ.source)`: the germ of the section `J_{χ,φ'}` over that open set. -/
noncomputable def jacobianGerm (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    {χ : OpenPartialHomeomorph M E} (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    {φ' : OpenPartialHomeomorph N E} (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N) {a' : N}
    (ha' : a' ∈ φ'.source) (hfa' : f a' ∈ χ.source) : (structureSheaf 𝕜 E N).presheaf.stalk a' :=
  (structureSheaf 𝕜 E N).presheaf.germ
    ⟨φ'.source ∩ f ⁻¹' χ.source, φ'.open_source.inter (χ.open_source.preimage hf.continuous)⟩
    a' ⟨ha', hfa'⟩
    (sectionOfContMDiffOn (jacobianFun 𝕜 f χ φ') _ (contMDiffOn_jacobianFun hf hχ hφ'))

theorem stalkToGerm_jacobianGerm (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    {χ : OpenPartialHomeomorph M E} (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    {φ' : OpenPartialHomeomorph N E} (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N) {a' : N}
    (ha' : a' ∈ φ'.source) (hfa' : f a' ∈ χ.source) :
    stalkToGerm 𝓘(𝕜, E) ω N a' (jacobianGerm hf hχ hφ' ha' hfa') =
      ((jacobianFun 𝕜 f χ φ' : N → 𝕜) : (𝓝 a').Germ 𝕜) :=
  stalkToGerm_germ_sectionOfContMDiffOn _ _ _ _

/-- **The Jacobian determinants of `f` in two chart pairs at `a'` differ by an analytic unit**
(chain rule and multiplicativity of the determinant; "with respect to any coordinate system",
[BM97, Theorem 1.10, the sentence after it]) — the product of the Jacobians of the two chart
changes. -/
theorem exists_unit_jacobianFun_germ_eq (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    {χ χ' : OpenPartialHomeomorph M E} (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    (hχ' : χ' ∈ maximalAtlas 𝓘(𝕜, E) ω M) {φ' φ'' : OpenPartialHomeomorph N E}
    (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N) (hφ'' : φ'' ∈ maximalAtlas 𝓘(𝕜, E) ω N) {a' : N}
    (ha' : a' ∈ φ'.source) (ha'' : a' ∈ φ''.source) (hfa' : f a' ∈ χ.source)
    (hfa'' : f a' ∈ χ'.source) :
    ∃ u : (structureSheaf 𝕜 E N).presheaf.stalk a', IsUnit u ∧
      ((jacobianFun 𝕜 f χ' φ'' : N → 𝕜) : (𝓝 a').Germ 𝕜) =
        stalkToGerm 𝓘(𝕜, E) ω N a' u * ((jacobianFun 𝕜 f χ φ' : N → 𝕜) : (𝓝 a').Germ 𝕜) := by
  -- the two Jacobians of the chart changes, as functions of the point of `N`
  set a : N → 𝕜 := fun y => (fderiv 𝕜 (χ' ∘ χ.symm) (χ (f y))).det with ha_def
  set b : N → 𝕜 := fun y => (fderiv 𝕜 (φ' ∘ φ''.symm) (φ'' y)).det with hb_def
  let W : Opens N := ⟨chartPairDomain f χ χ' φ' φ'', isOpen_chartPairDomain hf χ χ' φ' φ''⟩
  have haW : a' ∈ W := ⟨⟨ha', ha''⟩, hfa', hfa''⟩
  -- `a` is analytic on `W`: `det ∘ D(χ' ∘ χ⁻¹)` composed with the analytic `χ ∘ f`
  have hA : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜) ω a W := by
    have h1 : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜) ω (fun x => (fderiv 𝕜 (χ' ∘ χ.symm) x).det)
        (χ.target ∩ χ.symm ⁻¹' χ'.source) :=
      contMDiffOn_iff_contDiffOn.mpr (contDiffOn_det_fderiv (contDiffOn_chartChange hχ hχ')
        (isOpen_target_inter_preimage_symm χ χ'.open_source))
    have h2 : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜, E) ω (χ ∘ f) W :=
      (contMDiffOn_of_mem_maximalAtlas hχ).comp hf.contMDiffOn fun y hy => hy.2.1
    refine h1.comp h2 fun y hy => ⟨χ.map_source hy.2.1, ?_⟩
    change χ.symm (χ (f y)) ∈ χ'.source
    rw [χ.left_inv hy.2.1]
    exact hy.2.2
  -- `b` is analytic on `W`: `det ∘ D(φ' ∘ φ''⁻¹)` composed with the analytic `φ''`
  have hB : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜) ω b W := by
    have h1 : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜) ω (fun x => (fderiv 𝕜 (φ' ∘ φ''.symm) x).det)
        (φ''.target ∩ φ''.symm ⁻¹' φ'.source) :=
      contMDiffOn_iff_contDiffOn.mpr (contDiffOn_det_fderiv (contDiffOn_chartChange hφ'' hφ')
        (isOpen_target_inter_preimage_symm φ'' φ'.open_source))
    refine h1.comp ((contMDiffOn_of_mem_maximalAtlas hφ'').mono fun y hy => hy.1.2)
      fun y hy => ⟨φ''.map_source hy.1.2, ?_⟩
    change φ''.symm (φ'' y) ∈ φ'.source
    rw [φ''.left_inv hy.1.2]
    exact hy.1.1
  let sa := sectionOfContMDiffOn a W hA
  let sb := sectionOfContMDiffOn b W hB
  let S := (structureSheaf 𝕜 E N).presheaf
  refine ⟨S.germ W a' haW sa * S.germ W a' haW sb, ?_, ?_⟩
  · -- both germs are units: their values at `a'` are nonzero
    refine IsUnit.mul ?_ ?_
    · rw [contMDiffSheafCommRing.isUnit_stalk_iff]
      exact (contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω N 𝕜 W a' haW sa).trans_ne
        (det_fderiv_chartChange_ne_zero hχ hχ' hfa' hfa'')
    · rw [contMDiffSheafCommRing.isUnit_stalk_iff]
      exact (contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω N 𝕜 W a' haW sb).trans_ne
        (det_fderiv_chartChange_ne_zero hφ'' hφ' ha'' ha')
  · rw [map_mul, stalkToGerm_germ_sectionOfContMDiffOn, stalkToGerm_germ_sectionOfContMDiffOn,
      ← Germ.coe_mul, ← Germ.coe_mul]
    refine Germ.coe_eq.mpr ?_
    filter_upwards [W.2.mem_nhds haW] with y hy
    simp only [Pi.mul_apply]
    rw [jacobianFun_eq_mul hf hχ hχ' hφ' hφ'' hy]
    ring

end ChainRule

section Units

variable [IsManifold 𝓘(𝕜, E) ω M] [IsManifold 𝓘(𝕜, E) ω N]

/-- **The stalk of the Jacobian ideal at `a'` is generated by a single germ**, the germ of the
Jacobian determinant in the standard charts (`stalkToGerm` is injective, so the generating set of
`jacobianStalk` is that one germ). -/
theorem exists_stalk_jacobianStalk_eq_span (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) (a' : N) :
    ∃ s : (structureSheaf 𝕜 E N).presheaf.stalk a',
      stalkToGerm 𝓘(𝕜, E) ω N a' s =
          ((jacobianFun 𝕜 f (chartAt E (f a')) (chartAt E a') : N → 𝕜) : (𝓝 a').Germ 𝕜) ∧
        jacobianStalk f a' = Ideal.span {s} := by
  have hχ := IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) (f a')
  have hφ' := IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) a'
  refine ⟨jacobianGerm hf hχ hφ' (mem_chart_source E a') (mem_chart_source E (f a')),
    stalkToGerm_jacobianGerm hf hχ hφ' _ _, ?_⟩
  unfold jacobianStalk
  congr 1
  rw [← stalkToGerm_jacobianGerm hf hχ hφ' (mem_chart_source E a') (mem_chart_source E (f a')),
    ← Set.image_singleton]
  exact (stalkToGerm_injective 𝓘(𝕜, E) ω N a').preimage_image _

/-- **The stalk of the Jacobian ideal at `a'` is generated by the germ of the Jacobian determinant
in any chart pair at `a'`** ("with respect to any coordinate system",
[BM97, Theorem 1.10, the sentence after it]) — that germ is a unit times the standard one. -/
theorem exists_stalk_jacobianStalk_eq_span_of_charts (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f)
    {χ : OpenPartialHomeomorph M E} (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    {φ' : OpenPartialHomeomorph N E} (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N) {a' : N}
    (ha' : a' ∈ φ'.source) (hfa' : f a' ∈ χ.source) :
    ∃ s : (structureSheaf 𝕜 E N).presheaf.stalk a',
      stalkToGerm 𝓘(𝕜, E) ω N a' s = ((jacobianFun 𝕜 f χ φ' : N → 𝕜) : (𝓝 a').Germ 𝕜) ∧
        jacobianStalk f a' = Ideal.span {s} := by
  obtain ⟨s₀, hs₀, hspan⟩ := exists_stalk_jacobianStalk_eq_span hf a'
  obtain ⟨u, hu, hJ⟩ := exists_unit_jacobianFun_germ_eq hf
    (IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) (f a')) hχ
    (IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) a') hφ'
    (mem_chart_source E a') ha' (mem_chart_source E (f a')) hfa'
  refine ⟨u * s₀, ?_, ?_⟩
  · rw [map_mul, hs₀, hJ]
  · rw [hspan, Ideal.span_singleton_mul_left_unit hu]

/-- **The stalks of the Jacobian ideal of an analytic map have local generators**: near `a'`, the
single section `J_{χ,φ'}` for the standard charts `χ`, `φ'` at `a'` generates every stalk, by the
any-chart form. This is the condition under which `AnalyticMap.jacobianIdeal` is the ideal sheaf
with these stalks. -/
theorem hasLocalGenerators_jacobianStalk (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) :
    IdealSheaf.HasLocalGenerators (𝒪 := structureSheaf 𝕜 E N) (jacobianStalk f) := by
  intro a'
  have hχ := IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) (f a')
  have hφ' := IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) a'
  let U : Opens N := ⟨(chartAt E a').source ∩ f ⁻¹' (chartAt E (f a')).source,
    (chartAt E a').open_source.inter ((chartAt E (f a')).open_source.preimage hf.continuous)⟩
  refine ⟨U, ⟨mem_chart_source E a', mem_chart_source E (f a')⟩, Unit, inferInstance,
    fun _ => sectionOfContMDiffOn (jacobianFun 𝕜 f (chartAt E (f a')) (chartAt E a')) U
      (contMDiffOn_jacobianFun hf hχ hφ'), fun b hb => ?_⟩
  obtain ⟨s, hs, hspan⟩ := exists_stalk_jacobianStalk_eq_span_of_charts hf hχ hφ' hb.1 hb.2
  rw [hspan, Set.range_const]
  have hs' : s = (structureSheaf 𝕜 E N).presheaf.germ U b hb
      (sectionOfContMDiffOn (jacobianFun 𝕜 f (chartAt E (f a')) (chartAt E a')) U
        (contMDiffOn_jacobianFun hf hχ hφ')) := by
    apply stalkToGerm_injective 𝓘(𝕜, E) ω N b
    rw [hs, stalkToGerm_germ_sectionOfContMDiffOn]
  rw [hs']

end Units

section LocalDiffeomorph

/-- **Where `f` is a local diffeomorphism its Jacobian determinant is a unit**: the chart
representative `φ' ∘ f⁻¹ ∘ χ⁻¹` of Mathlib's local inverse is a left inverse of `χ ∘ f ∘ φ'⁻¹` near
`φ' a'`, so `det D(χ ∘ f ∘ φ'⁻¹)(φ' a') ≠ 0`. -/
theorem isUnit_jacobianFun_of_isLocalDiffeomorphAt (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) {a' : N}
    (hloc : IsLocalDiffeomorphAt 𝓘(𝕜, E) 𝓘(𝕜, E) ω f a') {χ : OpenPartialHomeomorph M E}
    (hχ : χ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {φ' : OpenPartialHomeomorph N E}
    (hφ' : φ' ∈ maximalAtlas 𝓘(𝕜, E) ω N) (ha' : a' ∈ φ'.source) (hfa' : f a' ∈ χ.source) :
    IsUnit (jacobianFun 𝕜 f χ φ' a') := by
  set g := hloc.localInverse with hg_def
  -- the open set of the source on which the local inverse is available
  let V : Set E := φ'.target ∩ φ'.symm ⁻¹' ((g.target ∩ φ'.source) ∩ f ⁻¹' χ.source)
  have hVopen : IsOpen V :=
    isOpen_target_inter_preimage_symm φ'
      ((g.open_target.inter φ'.open_source).inter (χ.open_source.preimage hf.continuous))
  have hmem : φ' a' ∈ V :=
    ⟨φ'.map_source ha', by
      rw [mem_preimage, φ'.left_inv ha']; exact ⟨⟨hloc.localInverse_mem_target, ha'⟩, hfa'⟩⟩
  -- the left inverse `g' = φ' ∘ g ∘ χ⁻¹`
  set g' : E → E := φ' ∘ g ∘ χ.symm with hg'_def
  have hgg' : ∀ v ∈ V, g' ((χ ∘ f ∘ φ'.symm) v) = v := by
    intro v hv
    obtain ⟨hv1, ⟨hzg, -⟩, hfz⟩ := hv
    simp only [hg'_def, Function.comp_apply]
    rw [χ.left_inv hfz, hloc.localInverse_left_inv hzg, φ'.right_inv hv1]
  -- `g'` is analytic near `χ (f a')`
  have hg'diff : DifferentiableAt 𝕜 g' ((χ ∘ f ∘ φ'.symm) (φ' a')) := by
    let T : Set E := χ.target ∩ χ.symm ⁻¹' (g.source ∩ g ⁻¹' φ'.source)
    have hTopen : IsOpen T :=
      isOpen_target_inter_preimage_symm χ
        (hloc.localInverse_contMDiffOn.continuousOn.isOpen_inter_preimage g.open_source
          φ'.open_source)
    have hTmem : (χ ∘ f ∘ φ'.symm) (φ' a') ∈ T := by
      simp only [Function.comp_apply, φ'.left_inv ha']
      refine ⟨χ.map_source hfa', ?_⟩
      rw [mem_preimage, χ.left_inv hfa']
      refine ⟨hloc.localInverse_mem_source, ?_⟩
      rw [mem_preimage, hloc.localInverse_left_inv hloc.localInverse_mem_target]
      exact ha'
    have hT : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜, E) ω g' T :=
      (contMDiffOn_of_mem_maximalAtlas hφ').comp
        (hloc.localInverse_contMDiffOn.comp
          ((contMDiffOn_symm_of_mem_maximalAtlas hχ).mono inter_subset_left) fun v hv => hv.2.1)
        fun v hv => hv.2.2
    exact ((contMDiffOn_iff_contDiffOn.mp hT).differentiableOn (by simp)).differentiableAt
      (hTopen.mem_nhds hTmem)
  have h1 := det_fderiv_mul_det_fderiv_eq_one hVopen hmem
    (differentiableAt_chartRep hf hχ hφ' ha' hfa') hg'diff hgg'
  exact isUnit_iff_ne_zero.mpr (right_ne_zero_of_mul_eq_one h1)

variable [IsManifold 𝓘(𝕜, E) ω M] [IsManifold 𝓘(𝕜, E) ω N]

/-- **Where `f` is a local diffeomorphism the stalk of the Jacobian ideal is the unit ideal** (the
case of an isomorphism in the principalization theorem, whose Jacobian ideal is the unit ideal;
the off-centre case of the blowing-up). -/
theorem jacobianStalk_eq_top_of_isLocalDiffeomorphAt (hf : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω f) {a' : N}
    (hloc : IsLocalDiffeomorphAt 𝓘(𝕜, E) 𝓘(𝕜, E) ω f a') :
    jacobianStalk (𝕜 := 𝕜) (E := E) f a' = ⊤ := by
  obtain ⟨s, hs, hspan⟩ := exists_stalk_jacobianStalk_eq_span hf a'
  rw [hspan, Ideal.span_singleton_eq_top, contMDiffSheafCommRing.isUnit_stalk_iff]
  change eval 𝕜 E N a' s ≠ 0
  rw [eval_eq_value, hs, Germ.value_ofFun]
  exact (isUnit_jacobianFun_of_isLocalDiffeomorphAt hf hloc
    (IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) (f a'))
    (IsManifold.chart_mem_maximalAtlas (I := 𝓘(𝕜, E)) (n := ω) a')
    (mem_chart_source E a') (mem_chart_source E (f a'))).ne_zero

end LocalDiffeomorph

end Manifold
