/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Submanifold.Restrict
public import Hironaka.Manifold.StructureSheaf
import Hironaka.Analytic.Germ.CoordDiv
import Hironaka.Manifold.Germ.ChartTransport
import Hironaka.Manifold.Submanifold.Manifold
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# The ideal of a closed submanifold in a stalk

The restriction of germs `𝒪_{M,a} →+* 𝒪_{Y,a}` (`Hironaka/Manifold/Submanifold/Restrict.lean`)
is onto — an analytic function on `Y` near `a` extends to `M` along the complementary coordinates
of an adapted chart (`restrictStalk_surjective`) — and its kernel, the ideal `𝓘_{Y,a}` of germs
vanishing on `Y`, is generated by the adapted coordinates `x_{σ i} − x_{σ i}(a)`
(`ker_restrictStalk`): a germ vanishing on `Y` is, in the adapted chart, an analytic function
vanishing on the coordinate subspace `{z_σ = 0}`, hence a combination `∑ z_{σ i} · G_i` with
analytic `G_i` (`exists_sum_coord_mul_of_vanish_on_subspace`), read back on `M` through the chart.
Consequently
`𝒪_{M,a} / 𝓘_{Y,a} ≅ 𝒪_{Y,a}` (`IsRestrictStalk.exists_quotient_equiv'`). This is Hironaka's
"the ideal of `D` in `𝒪_{X,x}` is generated by some of the `z_i`" of a regular system of
parameters [Hir64, Definition 2, p. 141], and Bierstone–Milman's smooth subspace as a coordinate
subspace [BM97, (3.8)(2)]; it is the description of the ideal sheaf of a centre used throughout
the blow-up constructions (`Hironaka/Manifold/BlowUp/Divisor.lean`).
-/

public noncomputable section

open TopologicalSpace Opposite CategoryTheory Filter Topology Set Analytic
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {n : ℕ} {ψ : E ≃L[𝕜] (Fin n → 𝕜)}
  {Y : Set M} {c : ℕ}

/-- The restriction of germs is onto: an analytic function on `Y` near `a` extends along the
complementary coordinates of an adapted chart. -/
theorem IsClosedSubmanifold.restrictStalk_surjective (hY : IsClosedSubmanifold ψ Y c) (a : Y) :
    Function.Surjective (hY.restrictStalk a) := by
  let _i := hY.chartedSpace
  intro t
  obtain ⟨g, hg, V, haV, hgV⟩ := (mem_range_stalkToGerm_iff _ _ _ _ _).mp ⟨t, rfl⟩
  obtain ⟨φ, σ, has, h⟩ := hY.exists_adaptedChart a a.2
  have hchart := h.chartOn_mem_maximalAtlas' hY a.2
  -- the projection onto `Y` along the complementary coordinates, and the extension of `g`
  have hq : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜, Fin (n - c) → 𝕜) ω (fun x => projCompl σ (ψ (φ x)))
      φ.source :=
    ((contMDiff_iff_contDiff.mpr ((contDiff_projCompl σ).comp ψ.contDiff)).contMDiffOn
      (s := univ)).comp (contMDiffOn_of_mem_maximalAtlas (n := ω) h.1) fun _ _ => mem_univ _
  have hge : ContMDiffOn 𝓘(𝕜, Fin (n - c) → 𝕜) 𝓘(𝕜) ω (g ∘ (h.chartOn a.2).symm)
      ((h.chartOn a.2).target ∩ (h.chartOn a.2).symm ⁻¹' V) :=
    hgV.comp ((contMDiffOn_symm_of_mem_maximalAtlas (n := ω) hchart).mono inter_subset_left)
      fun _ hy => hy.2
  have hO : IsOpen ((h.chartOn a.2).target ∩ (h.chartOn a.2).symm ⁻¹' V) :=
    (h.chartOn a.2).symm.isOpen_inter_preimage V.2
  let W : Opens M := ⟨φ.source ∩ (fun x => projCompl σ (ψ (φ x))) ⁻¹'
    ((h.chartOn a.2).target ∩ (h.chartOn a.2).symm ⁻¹' V),
    (((continuous_projCompl σ).comp ψ.continuous).comp_continuousOn
      φ.continuousOn).isOpen_inter_preimage φ.open_source hO⟩
  have hae : a ∈ (h.chartOn a.2).source := has
  have haW : (a : M) ∈ W := by
    refine ⟨has, (h.chartOn a.2).map_source hae, ?_⟩
    change (h.chartOn a.2).symm (h.chartOn a.2 a) ∈ V
    rw [(h.chartOn a.2).left_inv hae]
    exact haV
  have hfW : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜) ω
      ((g ∘ (h.chartOn a.2).symm) ∘ fun x => projCompl σ (ψ (φ x))) W :=
    hge.comp (hq.mono inter_subset_left) fun _ hx => hx.2
  obtain ⟨s, hs⟩ := (mem_range_stalkToGerm_iff _ _ _ _ _).mpr
    ⟨_, rfl, W, haW, hfW⟩
  refine ⟨s, stalkToGerm_injective _ _ _ _ ?_⟩
  rw [hY.stalkToGerm_restrictStalk, hs, germRestrict_coe, hg]
  refine Germ.coe_eq.mpr ?_
  filter_upwards [(h.chartOn a.2).open_source.mem_nhds hae] with y hy
  change g ((h.chartOn a.2).symm (h.chartOn a.2 y)) = g y
  rw [(h.chartOn a.2).left_inv hy]

/-- The germ of functions of a coordinate germ `coord`. -/
theorem stalkToGerm_coord {φ : OpenPartialHomeomorph M E} (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M)
    {a : M} (ha : a ∈ φ.source) (j : Fin n) :
    stalkToGerm 𝓘(𝕜, E) ω M a (coord E ψ φ hφ ha j) =
      ↑(extendSection 𝕜 E (chartSection E ψ φ hφ j)) :=
  stalkToGerm_structureSheaf_germ _ _ _ _

/-- The germ of functions of a constant germ. -/
theorem stalkToGerm_const (a : M) (r : 𝕜) :
    stalkToGerm 𝓘(𝕜, E) ω M a (const 𝕜 E M a r) = ↑(fun _ : M => r) := by
  have h1 := stalkToGerm_structureSheaf_germ (a := a) E (⊤ : Opens M) trivial
    (constSection 𝕜 E M r)
  refine h1.trans ?_
  congr 1
  funext x
  exact extendSection_of_mem 𝕜 E (constSection 𝕜 E M r) (show x ∈ (⊤ : Opens M) from trivial)

/-- The adapted coordinates `x_{σ i} − x_{σ i}(a)` restrict to zero on `Y`. -/
theorem IsClosedSubmanifold.restrictStalk_coord_sub (hY : IsClosedSubmanifold ψ Y c) (a : Y)
    {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} (h : IsAdaptedChart ψ Y φ σ)
    (ha : (a : M) ∈ φ.source) (i : Fin c) :
    hY.restrictStalk a
      (coord E ψ φ h.1 ha (σ i) - const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ h.1 ha (σ i)))) = 0 := by
  let _i := hY.chartedSpace
  refine stalkToGerm_injective _ _ _ _ ?_
  rw [hY.stalkToGerm_restrictStalk, map_zero, map_sub, eval_coord, stalkToGerm_coord,
    stalkToGerm_const, ← Germ.coe_sub, germRestrict_coe]
  refine (Germ.coe_eq.mpr ?_).trans Germ.coe_zero
  filter_upwards [(h.chartOn a.2).open_source.mem_nhds (show a ∈ (h.chartOn a.2).source from ha)]
    with y hy
  have hy' : (y : M) ∈ φ.source := hy
  change extendSection 𝕜 E (chartSection E ψ φ h.1 (σ i)) y - ψ (φ a) (σ i) = 0
  rw [extendSection_of_mem 𝕜 E _ hy']
  change ψ (φ y) (σ i) - ψ (φ a) (σ i) = 0
  rw [(h.2 y hy').mp y.2 i, (h.2 a ha).mp a.2 i, sub_zero]

/-- The ideal of germs vanishing on `Y` is generated by the adapted coordinates
`x_{σ i} − x_{σ i}(a)` [Hir64, Definition 2, p. 141]. -/
theorem IsClosedSubmanifold.ker_restrictStalk (hY : IsClosedSubmanifold ψ Y c) (a : Y)
    {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} (h : IsAdaptedChart ψ Y φ σ)
    (ha : (a : M) ∈ φ.source) :
    RingHom.ker (hY.restrictStalk a) = Ideal.span (Set.range fun i =>
      coord E ψ φ h.1 ha (σ i) - const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ h.1 ha (σ i)))) := by
  classical
  let _i := hY.chartedSpace
  refine le_antisymm (fun s hs => ?_) (Ideal.span_le.mpr ?_)
  · rw [RingHom.mem_ker] at hs
    obtain ⟨U, hU, f, rfl⟩ := (structureSheaf 𝕜 E M).presheaf.exists_germ_eq s
    -- the restriction to `Y` vanishes near `a`: `f = 0` on `Y ∩ W`, `W` open in `M`
    have h1 := hY.stalkToGerm_restrictStalk a ((structureSheaf 𝕜 E M).presheaf.germ U (a : M) hU f)
    rw [hs, map_zero, stalkToGerm_structureSheaf_germ, germRestrict_coe] at h1
    have h2 : ∀ᶠ y : Y in 𝓝 a, extendSection 𝕜 E f (y : M) = 0 := by
      have := Germ.coe_eq.mp (h1.symm.trans Germ.coe_zero.symm)
      filter_upwards [this] with y hy using hy
    obtain ⟨V, hVf, hVo, haV⟩ := eventually_nhds_iff.mp h2
    obtain ⟨W, hWo, hWV⟩ := isOpen_induced_iff.mp hVo
    have hWzero : ∀ x ∈ Y ∩ W, extendSection 𝕜 E f x = 0 := fun x ⟨hxY, hxW⟩ => by
      have : (⟨x, hxY⟩ : Y) ∈ V := by
        rw [← hWV]
        exact hxW
      exact hVf _ this
    have haW : (a : M) ∈ W := by
      have : a ∈ V := haV
      rw [← hWV] at this
      exact this
    -- the function in the adapted chart, centred at `0`
    set b : Fin n → 𝕜 := ψ (φ a) with hb
    have hbσ : ∀ i, b (σ i) = 0 := (h.2 a ha).mp a.2
    set F : (Fin n → 𝕜) → 𝕜 := fun y => extendSection 𝕜 E f (φ.symm (ψ.symm (y + b))) with hF
    -- `F` is analytic near `0`
    have hfa : ContMDiffAt 𝓘(𝕜, E) 𝓘(𝕜) ω (extendSection 𝕜 E f) a :=
      (contMDiffOn_extendBy0 𝓘(𝕜, E) ω M f).contMDiffAt (U.2.mem_nhds hU)
    have hA : AnalyticAt 𝕜 (extendSection 𝕜 E f ∘ φ.symm) (φ a) :=
      (contMDiffAt_iff_contDiffAt.mp
        (ContMDiffAt.comp_of_eq hfa (contMDiffAt_chart_symm E φ ha h.1) (φ.left_inv ha))).analyticAt
    have hT : AnalyticAt 𝕜 (fun y : Fin n → 𝕜 => ψ.symm (y + b)) 0 := by
      have h1 : AnalyticAt 𝕜 (ψ.symm : (Fin n → 𝕜) → E) (0 + b) := by
        have := (ψ.symm : (Fin n → 𝕜) →L[𝕜] E).analyticAt (0 + b)
        rwa [ContinuousLinearEquiv.coe_coe] at this
      have hadd : AnalyticAt 𝕜 (fun y : Fin n → 𝕜 => y + b) 0 :=
        (analyticAt_id : AnalyticAt 𝕜 id (0 : Fin n → 𝕜)).add analyticAt_const
      exact AnalyticAt.comp (g := (ψ.symm : (Fin n → 𝕜) → E)) (f := fun y => y + b) h1 hadd
    have hF0 : AnalyticAt 𝕜 F 0 :=
      hA.comp_of_eq hT (by rw [zero_add, ψ.symm_apply_apply])
    -- the region near `0` where everything is defined
    have hev : ∀ᶠ y in 𝓝 (0 : Fin n → 𝕜), AnalyticAt 𝕜 F y ∧
        ψ.symm (y + b) ∈ φ.target ∧ φ.symm (ψ.symm (y + b)) ∈ W := by
      have hc1 : ContinuousAt (fun y : Fin n → 𝕜 => ψ.symm (y + b)) 0 :=
        (ψ.symm.continuous.comp (continuous_id.add continuous_const)).continuousAt
      have hc1' : ψ.symm (0 + b) = φ a := by rw [zero_add, ψ.symm_apply_apply]
      have hc2 : ContinuousAt (fun y : Fin n → 𝕜 => φ.symm (ψ.symm (y + b))) 0 := by
        refine (φ.continuousAt_symm ?_).comp hc1
        rw [hc1']
        exact φ.map_source ha
      refine hF0.eventually_analyticAt.and (Filter.Eventually.and ?_ ?_)
      · refine hc1.preimage_mem_nhds ?_
        rw [hc1']
        exact φ.open_target.mem_nhds (φ.map_source ha)
      · refine hc2.preimage_mem_nhds ?_
        show W ∈ 𝓝 (φ.symm (ψ.symm (0 + b)))
        rw [hc1', φ.left_inv ha]
        exact hWo.mem_nhds haW
    obtain ⟨ρ, hρ⟩ := exists_polydisc_of_eventually hev
    -- `F` vanishes on the coordinate subspace, so `F = ∑ y_{σ i} G_{σ i}`
    obtain ⟨G, hGan, hFG⟩ := exists_sum_coord_mul_of_vanish_on_subspace (Finset.univ.image σ)
      (fun y hy => (hρ y hy).1) (fun y hy hz => by
        have hp : φ.symm (ψ.symm (y + b)) ∈ φ.source := φ.map_target (hρ y hy).2.1
        have hpY : φ.symm (ψ.symm (y + b)) ∈ Y := by
          refine (h.2 _ hp).mpr fun i => ?_
          rw [φ.right_inv (hρ y hy).2.1, ψ.apply_symm_apply, Pi.add_apply, hbσ, add_zero]
          exact hz (σ i) (Finset.mem_image_of_mem σ (Finset.mem_univ i))
        exact hWzero _ ⟨hpY, (hρ y hy).2.2⟩)
    -- the coefficient germs on `M`
    have hsub : ∀ y, y ∈ polydisc 𝕜 ρ → F y = ∑ i, y (σ i) * G (σ i) y := fun y hy => by
      rw [hFG y hy, Finset.sum_image fun x _ z _ hxz => σ.injective hxz]
    let W' : Opens M := ⟨φ.source ∩ (fun x => ψ (φ x) - b) ⁻¹' polydisc 𝕜 ρ,
      ((ψ.continuous.sub continuous_const).comp_continuousOn φ.continuousOn).isOpen_inter_preimage
        φ.open_source (isOpen_polydisc ρ)⟩
    have haW' : (a : M) ∈ W' := by
      refine ⟨ha, ?_⟩
      change ψ (φ a) - b ∈ polydisc 𝕜 ρ
      rw [hb, sub_self]
      exact fun k => by simpa using ρ.2 k
    have hGi : ∀ i, ∃ t : (structureSheaf 𝕜 E M).presheaf.stalk (a : M),
        stalkToGerm 𝓘(𝕜, E) ω M a t = ↑(fun x => G (σ i) (ψ (φ x) - b)) := fun i => by
      refine (mem_range_stalkToGerm_iff _ _ _ _ _).mpr ⟨_, rfl, W', haW', ?_⟩
      have hG : ContMDiffOn 𝓘(𝕜, Fin n → 𝕜) 𝓘(𝕜) ω (G (σ i)) (polydisc 𝕜 ρ) :=
        contMDiffOn_iff_contDiffOn.mpr
          ((hGan (σ i) (Finset.mem_image_of_mem σ (Finset.mem_univ i))).contDiffOn_of_completeSpace)
      have hlin : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜, Fin n → 𝕜) ω (fun x => ψ (φ x) - b) φ.source :=
        ((contMDiff_iff_contDiff.mpr (ψ.contDiff.sub contDiff_const)).contMDiffOn (s := univ)).comp
          (contMDiffOn_of_mem_maximalAtlas (n := ω) h.1) fun _ _ => mem_univ _
      exact hG.comp (hlin.mono inter_subset_left) fun _ hx => hx.2
    choose t ht using hGi
    -- `s = ∑ (x_{σ i} − x_{σ i}(a)) t_i`, checked on germs of functions
    have hs_eq : (structureSheaf 𝕜 E M).presheaf.germ U (a : M) hU f =
        ∑ i, (coord E ψ φ h.1 ha (σ i) - const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ h.1 ha (σ i)))) *
          t i := by
      apply stalkToGerm_injective 𝓘(𝕜, E) ω M a
      rw [stalkToGerm_structureSheaf_germ, map_sum]
      simp_rw [map_mul, map_sub, eval_coord, stalkToGerm_coord, stalkToGerm_const, ht]
      -- both sides are germs of functions
      have hR : (∑ i, ((↑(extendSection 𝕜 E (chartSection E ψ φ h.1 (σ i))) : (𝓝 (a : M)).Germ 𝕜) -
            ↑(fun _ : M => ψ (φ a) (σ i))) * ↑(fun x => G (σ i) (ψ (φ x) - b))) =
          ↑(∑ i, (extendSection 𝕜 E (chartSection E ψ φ h.1 (σ i)) - fun _ : M => ψ (φ a) (σ i)) *
            fun x => G (σ i) (ψ (φ x) - b)) := by
        change _ = Germ.coeRingHom (𝓝 (a : M)) _
        rw [map_sum]
        rfl
      rw [hR]
      refine Germ.coe_eq.mpr ?_
      filter_upwards [W'.2.mem_nhds haW'] with x hx
      have hx' : x ∈ φ.source := hx.1
      have hF' := hsub (ψ (φ x) - b) hx.2
      rw [hF] at hF'
      dsimp only at hF'
      rw [sub_add_cancel, ψ.symm_apply_apply, φ.left_inv hx'] at hF'
      rw [hF', Finset.sum_apply]
      refine Finset.sum_congr rfl fun i _ => ?_
      simp only [Pi.mul_apply, Pi.sub_apply]
      rw [extendSection_of_mem 𝕜 E _ hx', hb]
      rfl
    rw [hs_eq]
    exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)
  · rintro _ ⟨i, rfl⟩
    exact hY.restrictStalk_coord_sub a h ha i

/-! ## For any map satisfying the specification -/

variable (hY : IsClosedSubmanifold ψ Y c)

/-- The restriction of germs is onto. -/
theorem IsClosedSubmanifold.IsRestrictStalk.surjective' {a : Y}
    {r : (structureSheaf 𝕜 E M).presheaf.stalk (a : M) →+* hY.stalk a}
    (hr : hY.IsRestrictStalk a r) : Function.Surjective r := by
  obtain rfl := IsClosedSubmanifold.IsRestrictStalk.eq hY hr (hY.isRestrictStalk_restrictStalk a)
  exact hY.restrictStalk_surjective a

/-- The kernel of the restriction of germs is generated by the adapted coordinates. -/
theorem IsClosedSubmanifold.IsRestrictStalk.ker_eq_span' {a : Y}
    {r : (structureSheaf 𝕜 E M).presheaf.stalk (a : M) →+* hY.stalk a}
    (hr : hY.IsRestrictStalk a r) {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n}
    (h : IsAdaptedChart ψ Y φ σ) (ha : (a : M) ∈ φ.source) :
    RingHom.ker r = Ideal.span (Set.range fun i =>
      coord E ψ φ h.1 ha (σ i) - const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ h.1 ha (σ i)))) := by
  obtain rfl := IsClosedSubmanifold.IsRestrictStalk.eq hY hr (hY.isRestrictStalk_restrictStalk a)
  exact hY.ker_restrictStalk a h ha

/-- `𝒪_{M,a} / 𝓘_{Y,a} ≅ 𝒪_{Y,a}`. -/
theorem IsClosedSubmanifold.IsRestrictStalk.exists_quotient_equiv' {a : Y}
    {r : (structureSheaf 𝕜 E M).presheaf.stalk (a : M) →+* hY.stalk a}
    (hr : hY.IsRestrictStalk a r) :
    ∃ e : ((structureSheaf 𝕜 E M).presheaf.stalk (a : M) ⧸ RingHom.ker r) ≃+* hY.stalk a,
      ∀ s, e (Ideal.Quotient.mk _ s) = r s :=
  ⟨RingHom.quotientKerEquivOfSurjective hr.surjective', fun _ => rfl⟩

end Manifold
