/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Jacobian.Defs
public import Hironaka.Manifold.Snc.Defs
import Hironaka.Manifold.Jacobian.Bundled
import Hironaka.Resolution.Analytic.Principalization.NormalCrossingsOfMonomial
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The Jacobian ideal times a boundary monomial is a normal-crossings divisor

Bierstone–Milman's sentence after Theorem 1.10: if `J ⊂ 𝒪_{M_k}` is the ideal generated by the
Jacobian determinant of `σ`, then `J · σ⁻¹(I)` is a normal-crossings divisor
[BM97, Theorem 1.10, the sentence after it]. Two tools for that clause: at a point of a manifold
carrying a hypersurface family `G`, two ideal sheaves whose stalks are monomials in the vanishing
ideals of members of `G` through the point have a product of the same form (the index sets unite,
the exponents add; `exists_prod_pow_vanishingStalk_mul`), and when `G` is snc and the Jacobian
stalk of `σ` and the stalk of `J` are such monomials at every point, `jacobianIdeal σ · J` is a
normal-crossings divisor (`isNormalCrossingsDivisor_jacobianIdeal_mul_of_forall_monomial`, through
`isNormalCrossingsDivisor_of_forall_monomial`: the centred coordinates of an snc chart are a
regular system of parameters). The stalks of the Jacobian ideal are
the `jacobianStalk`s (`jacobianIdeal_stalkIdeal`). Used for the Jacobian
clause of the principalization theorem
(`Hironaka/Resolution/Analytic/BM97/JacobianAssembly.lean`).
-/

public section

universe u

open TopologicalSpace
open scoped Manifold ContDiff

namespace Hironaka.Manifold

open _root_.Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}

/-- The product of two boundary monomials of one hypersurface family at a point is a boundary
monomial of the same family: the index sets unite and the exponents add (an exponent extended by
`0` off its index set). -/
theorem exists_prod_pow_vanishingStalk_mul {X : AnalyticManifold.{u} 𝕜 E} (G : HypersurfaceFamily X)
    (J K : AnalyticManifold.IdealSheaf X) (x : X)
    (hJ : ∃ (s : Finset G.ι) (α : G.ι → ℕ), (∀ j ∈ s, x ∈ G.hyp j) ∧
      J.stalkIdeal x = ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ α j)
    (hK : ∃ (s : Finset G.ι) (α : G.ι → ℕ), (∀ j ∈ s, x ∈ G.hyp j) ∧
      K.stalkIdeal x = ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ α j) :
    ∃ (s : Finset G.ι) (α : G.ι → ℕ), (∀ j ∈ s, x ∈ G.hyp j) ∧
      (J * K).stalkIdeal x = ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ α j := by
  classical
  obtain ⟨s, α, hs, hJx⟩ := hJ
  obtain ⟨t, β, ht, hKx⟩ := hK
  refine ⟨s ∪ t, fun j => (if j ∈ s then α j else 0) + (if j ∈ t then β j else 0), ?_, ?_⟩
  · intro j hj
    rcases Finset.mem_union.mp hj with h | h
    · exact hs j h
    · exact ht j h
  · rw [IdealSheaf.stalkIdeal_mul, hJx, hKx]
    simp_rw [pow_add]
    rw [Finset.prod_mul_distrib]
    congr 1
    · calc ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ α j
          = ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ (if j ∈ s then α j else 0) :=
            Finset.prod_congr rfl fun j hj => by rw [if_pos hj]
        _ = ∏ j ∈ s ∪ t,
              vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ (if j ∈ s then α j else 0) :=
            Finset.prod_subset Finset.subset_union_left fun j _ hj => by rw [if_neg hj, pow_zero]
    · calc ∏ j ∈ t, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ β j
          = ∏ j ∈ t, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ (if j ∈ t then β j else 0) :=
            Finset.prod_congr rfl fun j hj => by rw [if_pos hj]
        _ = ∏ j ∈ s ∪ t,
              vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ (if j ∈ t then β j else 0) :=
            Finset.prod_subset Finset.subset_union_right fun j _ hj => by rw [if_neg hj, pow_zero]

/-- If the Jacobian stalk of `σ` and the stalk of `J` are, at every point, monomials in the
vanishing ideals of members of the snc family `G` through the point, then `jacobianIdeal σ · J` is
a normal-crossings divisor [BM97, Theorem 1.10, the sentence after it]. -/
theorem isNormalCrossingsDivisor_jacobianIdeal_mul_of_forall_monomial
    (ψ : E ≃L[𝕜] (Fin n → 𝕜)) {X X' : AnalyticManifold.{u} 𝕜 E}
        (σ : AnalyticMap X' X)
    (G : HypersurfaceFamily X') (hG : G.IsSnc ψ) (J : AnalyticManifold.IdealSheaf X')
    (hσ : ∀ x : X', ∃ (s : Finset G.ι) (h : G.ι → ℕ), (∀ j ∈ s, x ∈ G.hyp j) ∧
      jacobianStalk (𝕜 := 𝕜) (E := E) ⇑σ x =
        ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ h j)
    (hJ : ∀ x : X', ∃ (s : Finset G.ι) (α : G.ι → ℕ), (∀ j ∈ s, x ∈ G.hyp j) ∧
      J.stalkIdeal x = ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ α j) :
    (AnalyticMap.jacobianIdeal σ * J).IsNormalCrossingsDivisor :=
  isNormalCrossingsDivisor_of_forall_monomial (ψ := ψ) G hG _ fun x => by
    obtain ⟨s, h, hs, hx⟩ := hσ x
    exact exists_prod_pow_vanishingStalk_mul G _ J x
      ⟨s, h, hs, by rw [jacobianIdeal_stalkIdeal]; exact hx⟩ (hJ x)

end Hironaka.Manifold
