/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Snc.Defs
public import Hironaka.Manifold.StructureSheaf
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.Germ.TaylorIdeal
import Hironaka.Manifold.IdealSheaf.Basic
import Hironaka.Manifold.Snc.Coherence
import Hironaka.Resolution.Analytic.Principalization.MonomialStalk
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# From the pointwise boundary monomial to a normal-crossings divisor

Bierstone–Milman's normal-crossings divisor is "a principal ideal of finite type, generated
locally by a monomial in suitable coordinates" [BM97, Theorem 1.10]; the predicate
`IsNormalCrossingsDivisor` asks, at every point, for the
stalk to be generated by a monomial in a regular system of parameters. This follows from the
pointwise boundary-monomial form of Kollár's formula [Kol07, 72] in an snc chart of the boundary
at the point: the chart's coordinates, centred at the point, are a regular system of parameters
(`maximalIdeal_eq_span_coord'`, `ringKrullDim_stalk_of_chart`), the vanishing ideal of a member
through the point is generated by its coordinate
(`IsClosedSubmanifold.vanishingStalk_eq_span_coord`, already centred since the member passes
through the point), so the product of powers of the vanishing ideals is the ideal generated by
the corresponding monomial in the coordinates (`isNormalCrossingsDivisor_of_forall_monomial`).
The support of the ideal sheaf lies in the boundary: off it the monomial is the empty product
(`support_subset_of_forall_monomial`). Used for the normal-crossings clauses of the
principalization theorem (`JacobianMonomial.lean`,
`Hironaka/Resolution/Analytic/Wlo09/Monomial.lean`).
-/

@[expose] public section

universe u

open TopologicalSpace IsLocalRing
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

namespace Hironaka.Manifold

open _root_.Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  (ψ : E ≃L[𝕜] (Fin n → 𝕜)) {X : AnalyticManifold.{u} 𝕜 E}

/-- The coordinates of a chart, centred at the point `x`: `z_i − z_i(x)`, the generators of the
maximal ideal of the stalk. -/
noncomputable def chartCentredCoord (φ : OpenPartialHomeomorph X E)
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω X) {x : X} (hx : x ∈ φ.source) (i : Fin n) :
    (structureSheaf 𝕜 E X).presheaf.stalk x :=
  coord E ψ φ hφ hx i - const 𝕜 E X x (eval 𝕜 E X x (coord E ψ φ hφ hx i))

/-- The centred coordinates generate the maximal ideal of the stalk. -/
theorem span_range_chartCentredCoord (φ : OpenPartialHomeomorph X E)
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω X) {x : X} (hx : x ∈ φ.source) :
    Ideal.span (Set.range (chartCentredCoord ψ φ hφ hx)) =
      maximalIdeal ((structureSheaf 𝕜 E X).presheaf.stalk x) :=
  (maximalIdeal_eq_span_coord' E ψ φ hx hφ).symm

/-- A coordinate vanishing at `x` is already centred. -/
theorem chartCentredCoord_eq_coord_of_eq_zero (φ : OpenPartialHomeomorph X E)
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω X) {x : X} (hx : x ∈ φ.source) {i : Fin n}
    (h0 : ψ (φ x) i = 0) : chartCentredCoord ψ φ hφ hx i = coord E ψ φ hφ hx i := by
  unfold chartCentredCoord
  rw [eval_coord, h0, map_zero, sub_zero]

variable {ψ}

/-- The monomial `∏ z_{c j}^{α j}` over the members through the point, as a monomial in all the
coordinates: the exponent of `z_i` is the sum of the `α j` with `c j = i` (zero off the image). -/
theorem prod_pow_sum_ite_eq {R : Type*} [CommMonoid R] {ι : Type*} (s : Finset ι) (z : Fin n → R)
    (cj : ι → Fin n) (α : ι → ℕ) :
    ∏ i, z i ^ (∑ j ∈ s, if cj j = i then α j else 0) = ∏ j ∈ s, z (cj j) ^ α j := by
  classical
  simp_rw [← Finset.prod_pow_eq_pow_sum]
  rw [Finset.prod_comm]
  refine Finset.prod_congr rfl fun j _ => ?_
  simp_rw [pow_ite, pow_zero]
  rw [Finset.prod_ite_eq]
  simp only [Finset.mem_univ, if_true]

/-- An ideal sheaf which is at every point a boundary monomial of the snc family `G` is a
normal-crossings divisor [BM97, Theorem 1.10]: in an snc chart at the point the centred
coordinates are a regular system of parameters and the vanishing ideals of the members through the
point are generated by their coordinates. -/
theorem isNormalCrossingsDivisor_of_forall_monomial (G : HypersurfaceFamily X) (hG : G.IsSnc ψ)
    (J : AnalyticManifold.IdealSheaf X)
    (hJ : ∀ x : X, ∃ (s : Finset G.ι) (α : G.ι → ℕ), (∀ j ∈ s, x ∈ G.hyp j) ∧
      J.stalkIdeal x = ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ α j) :
    J.IsNormalCrossingsDivisor := by
  classical
  intro x
  obtain ⟨s, α, hs, hx⟩ := hJ x
  obtain ⟨φ, c, hc⟩ := hG.exists_isSncChartAt x
  have hxφ : x ∈ φ.source := hc.2.1
  let cj : {j // j ∈ s} → Fin n := fun j => c ⟨j.1, hs j.1 j.2⟩
  refine ⟨n, chartCentredCoord ψ φ hc.1 hxφ,
    fun i => ∑ j ∈ s.attach, if cj j = i then α j.1 else 0,
    ⟨span_range_chartCentredCoord ψ φ hc.1 hxφ, ?_⟩, ?_⟩
  · rw [ringKrullDim_stalk_of_chart E ψ φ hxφ hc.1]
  · have h1 : ∀ j : {j // j ∈ s}, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j.1) x =
        Ideal.span {coord E ψ φ hc.1 hxφ (cj j)} := fun j =>
      (hG.1 j.1).vanishingStalk_eq_span_coord (hc.isAdaptedChart_hyp ⟨j.1, hs j.1 j.2⟩) hxφ
    have h2 : ∀ j : {j // j ∈ s}, chartCentredCoord ψ φ hc.1 hxφ (cj j) =
        coord E ψ φ hc.1 hxφ (cj j) := fun j =>
      chartCentredCoord_eq_coord_of_eq_zero ψ φ hc.1 hxφ
        ((hc.mem_iff ⟨j.1, hs j.1 j.2⟩ hxφ).mp (hs j.1 j.2))
    rw [hx, ← Finset.prod_attach, prod_pow_sum_ite_eq]
    calc ∏ j ∈ s.attach, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j.1) x ^ α j.1
        = ∏ j ∈ s.attach, Ideal.span {coord E ψ φ hc.1 hxφ (cj j) ^ α j.1} := by
          refine Finset.prod_congr rfl fun j _ => ?_
          rw [h1 j, Ideal.span_singleton_pow]
      _ = Ideal.span {∏ j ∈ s.attach, coord E ψ φ hc.1 hxφ (cj j) ^ α j.1} :=
          Ideal.prod_span_singleton _ _
      _ = Ideal.span {∏ j ∈ s.attach, chartCentredCoord ψ φ hc.1 hxφ (cj j) ^ α j.1} := by
          refine congrArg (fun r => Ideal.span {r}) (Finset.prod_congr rfl fun j _ => ?_)
          rw [h2 j]

/-- The support of a pointwise boundary monomial lies in the boundary: off the boundary the
monomial is the empty product, the unit ideal. -/
theorem support_subset_of_forall_monomial (G : HypersurfaceFamily X)
    (J : AnalyticManifold.IdealSheaf X)
    (hJ : ∀ x : X, ∃ (s : Finset G.ι) (α : G.ι → ℕ), (∀ j ∈ s, x ∈ G.hyp j) ∧
      J.stalkIdeal x = ∏ j ∈ s, vanishingStalk (𝕜 := 𝕜) (E := E) (G.hyp j) x ^ α j) :
    J.support ⊆ G.support := by
  intro x hxJ
  obtain ⟨s, α, hs, hx⟩ := hJ x
  by_contra hxG
  have hs0 : s = ∅ :=
    Finset.eq_empty_of_forall_notMem fun j hj => hxG (Set.mem_iUnion.mpr ⟨j, hs j hj⟩)
  rw [hs0, Finset.prod_empty] at hx
  exact (IdealSheaf.mem_support _).mp hxJ (hx.trans Ideal.one_eq_top)

end Hironaka.Manifold
