/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.QuotientMap
import Hironaka.Manifold.IdealSheaf.Pullback
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# The inverse image of an ideal sheaf along the morphism of an analytic map

The stalk map of `Sp(f)` at `x`, for an analytic map `f : M → N` (`ofManifoldHom`: precomposition of
sections with `f`), is the map `germMap f x` of germs, composition with `f`
(`stalkMap_ofManifoldHom_eq_germMap`). Consequently the inverse image `QuotientSpace.comap Sp(f) J`
of an ideal sheaf `J` on `N`, defined for a morphism of locally ringed spaces as the ideal sheaf
generated stalkwise by the image of `J` (the body of `AnalyticSpace.ClosedSubspace.comap`,
the inverse image of a closed subspace used in the statements of the analytic main theorems), is the
pullback `J.pullback f` defined on the manifold side (`comap_ofManifoldHom_eq_pullback`).

For the morphism of spaces of a blow-up this identifies the inverse image of a closed subspace with
the total transform of its ideal sheaf on the manifold [Hir64, Ch. 0, §5, p. 141], and the inverse
image of the centre with the exceptional ideal sheaf. It is used wherever the analytic-space inverse
image and the manifold pullback have to be compared, chiefly the modules of
`Hironaka.Manifold.Sequence.Restrict` that read ideal sheaves on manifolds as closed subspaces.
-/

public section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite Manifold
open scoped Manifold ContDiff

universe u

namespace AnalyticSpace.KLocallyRingedSpace

variable {K : Type} [RCLike K] {E : Type*} [NormedAddCommGroup E] [NormedSpace K E]
  {E' : Type*} [NormedAddCommGroup E'] [NormedSpace K E'] {M : Type u} [TopologicalSpace M]
  [ChartedSpace E M] {N : Type u} [TopologicalSpace N] [ChartedSpace E' N]

/-- The stalk map of `Sp(f)` is the map of germs `germMap f x`: both send the germ of a section `g`
at `f x` to the germ of `g ∘ f` at `x`. -/
theorem stalkMap_ofManifoldHom_eq_germMap (f : M → N) (hf : ContMDiff 𝓘(K, E) 𝓘(K, E') ω f) (x : M)
    (s : (structureSheaf K E' N).presheaf.stalk (f x)) :
    ((ofManifoldHom f hf).1.stalkMap x).hom s = germMap f hf x s := by
  obtain ⟨U, hxU, g, rfl⟩ := TopCat.Presheaf.exists_germ_eq _ s
  have h := congrArg (fun φ => φ.hom g)
    (PresheafedSpace.stalkMap_germ (ofManifoldHomAux f hf) U x hxU)
  simp only [CommRingCat.hom_comp, RingHom.comp_apply] at h
  rw [germMap_germ]
  refine h.trans ?_
  refine TopCat.Presheaf.germ_ext (structureSheaf K E M).presheaf (x := x) (preimageOpens f hf U)
    ((mem_preimageOpens f hf).mpr hxU) (homOfLE fun y hy => hy) (homOfLE fun y hy => hy) ?_
  refine Subtype.ext (funext fun y => ?_)
  exact (comapSection_apply f hf g ⟨y.1, y.2⟩).symm

/-- The inverse image along `Sp(f)` of an ideal sheaf on `N` is its pullback along `f`: stalkwise,
the ideal generated by the image of the stalk ideal under the stalk map [Hir64, Ch. 0, §5, p. 141].
-/
theorem comap_ofManifoldHom_eq_pullback (f : M → N) (hf : ContMDiff 𝓘(K, E) 𝓘(K, E') ω f)
    (J : IdealSheaf (structureSheaf K E' N)) :
    QuotientSpace.comap (ofManifoldHom f hf).1 J = J.pullback f hf := by
  apply IdealSheaf.ext
  intro x
  refine (QuotientSpace.stalkIdeal_comap (ofManifoldHom f hf).1 J x).trans ?_
  refine Eq.trans ?_ (IdealSheaf.stalkIdeal_pullback f hf J x).symm
  exact congrArg (fun φ : (structureSheaf K E' N).presheaf.stalk (f x) →+*
      (structureSheaf K E M).presheaf.stalk x => Ideal.map φ (J.stalkIdeal (f x)))
    (RingHom.ext fun s => stalkMap_ofManifoldHom_eq_germMap f hf x s)

end AnalyticSpace.KLocallyRingedSpace
