/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.ProjectiveBundle.Affine.Defs
public import Hironaka.Algebra.SymmetricAlgebra.Away
public import Mathlib.AlgebraicGeometry.Pullbacks
import Mathlib.AlgebraicGeometry.Cover.Open
import Hironaka.Scheme.BlowUp.Rees.Map
public import Hironaka.Scheme.ProjectiveBundle.Affine.Map

/-!
# Base change of the projective bundle of a module

For a ring map `φ : R → S` and a `φ`-semilinear map `f : M → N` that exhibits `N` as `S ⊗_R M`
(its image spans `N`, and every `φ`-semilinear map out of `M` extends along `f` to an `S`-linear
map out of `N`), the square

```
P(N) ⟶ Spec S
  |        |
P(M) ⟶ Spec R
```

of projective bundles is cartesian [Sta, Tag 01N2]
(`AlgebraicGeometry.affineProjectiveBundle.isPullback_map`). `P(M)` is covered by the charts
`D₊(ι x) = Spec (Sym M)_(ι x)`, `x ∈ M` (the irrelevant ideal is generated by `ι(M)`,
`SymmetricAlgebra.irrelevant_le_span_ι`), the morphism `P(N) ⟶ P(M)` pulls `D₊(ι x)` back to
`D₊(ι (f x))` (`Proj.map_preimage_basicOpen`), and over a chart the square is `Spec` of the pushout
of rings `SymmetricAlgebra.isPushout_away`; a square cartesian over an open cover of a corner is
cartesian (Mathlib's `Scheme.isPullback_of_openCover`). This is the argument of
`AlgebraicGeometry.Proj.isPullback_projMap` for polynomial rings.
-/

@[expose] public section

universe u

open CategoryTheory CategoryTheory.Limits SymmetricAlgebra HomogeneousLocalization

namespace AlgebraicGeometry.affineProjectiveBundle

variable {R : Type u} {M : Type u} [CommRing R] [AddCommGroup M] [Module R M]

/-- The affine open cover of `P(M)` by the charts `D₊(ι x)`, `x ∈ M`. -/
noncomputable def chartCover : (affineProjectiveBundle R M).AffineOpenCover :=
  Proj.affineOpenCoverOfIrrelevantLESpan (grading R M) (fun x : M => ι R M x) (m := fun _ => 1)
    ι_mem_grading_one (fun _ => one_pos) irrelevant_le_span_ι

/-- The chart `D₊(e) = Spec (Sym M)_(e)` of `P(M)` followed by the structure morphism is `Spec` of
the constants `R → (Sym M)_(e)`. -/
theorem awayι_π (e : SymmetricAlgebra R M) (he : e ∈ grading R M 1) :
    Proj.awayι (grading R M) e he one_pos ≫ π R M =
      Spec.map (CommRingCat.ofHom (toAway e)) := by
  rw [π, Proj.awayι_toSpecZero_assoc, ← Spec.map_comp]
  rfl

variable {S : Type u} {N : Type u} [CommRing S] [AddCommGroup N] [Module S N]
variable (φ : R →+* S) (f : M →ₛₗ[φ] N) (hspan : Submodule.span S (Set.range f) = ⊤)

/-- The chart square of `P(N) ⟶ P(M)` over `D₊(ι x)`. -/
theorem isPullback_awayι_map (x : M) :
    IsPullback (Spec.map (CommRingCat.ofHom (Away.map (gradedMap φ f) (ι R M x))))
      (Proj.awayι _ (gradedMap φ f (ι R M x)) ((gradedMap φ f).map_mem (ι_mem_grading_one x))
        one_pos)
      (Proj.awayι _ (ι R M x) (ι_mem_grading_one x) one_pos) (map φ f hspan) :=
  IsOpenImmersion.isPullback _ _ _ _
    (Proj.awayι_comp_map (gradedMap φ f) (irrelevant_le_map_gradedMap φ f hspan) one_pos
      (ι R M x) (ι_mem_grading_one x))
    (by rw [Proj.opensRange_awayι, Proj.opensRange_awayι, map, Proj.map_preimage_basicOpen])

variable (hext : ∀ (T : Type u) [AddCommGroup T] [Module S T] (g : M →ₛₗ[φ] T),
  ∃ g' : N →ₗ[S] T, ∀ x, g' (f x) = g x)
include hext

/-- The base-change square over the chart `D₊(ι x)`, for any pullback of `P(N) ⟶ P(M)` along the
chart: the square `Spec` of `SymmetricAlgebra.isPushout_away`, transported along the
identification of the two pullbacks of the chart square. -/
theorem isPullback_map_aux (x : M) {W' : Scheme.{u}} {a : W' ⟶ affineProjectiveBundle S N}
    {b : W' ⟶ Spec (.of (Away (grading R M) (ι R M x)))}
    (hab : IsPullback a b (map φ f hspan) (Proj.awayι _ (ι R M x) (ι_mem_grading_one x) one_pos)) :
    IsPullback (a ≫ π S N) b (Spec.map (CommRingCat.ofHom φ))
      (Proj.awayι _ (ι R M x) (ι_mem_grading_one x) one_pos ≫ π R M) := by
  have hchart := (isPullback_awayι_map φ f hspan x).flip
  let e := hab.isoIsPullback _ _ hchart
  have he₁ : e.hom ≫ Proj.awayι _ (gradedMap φ f (ι R M x))
      ((gradedMap φ f).map_mem (ι_mem_grading_one x)) one_pos = a :=
    hab.isoIsPullback_hom_fst _ _ hchart
  have he₂ : e.hom ≫ Spec.map (CommRingCat.ofHom (Away.map (gradedMap φ f) (ι R M x))) = b :=
    hab.isoIsPullback_hom_snd _ _ hchart
  refine (isPullback_SpecMap_of_isPushout _ _ _ _
    (isPushout_away φ f x hspan hext)).of_iso' e (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ ?_ ?_ ?_
  · rw [Iso.refl_hom, Category.comp_id, ← awayι_π (gradedMap φ f (ι R M x))
      ((gradedMap φ f).map_mem (ι_mem_grading_one x)), ← Category.assoc, he₁]
  · rw [Iso.refl_hom, Category.comp_id, he₂]
  · simp
  · rw [Iso.refl_hom, Iso.refl_hom, Category.id_comp, Category.comp_id, awayι_π]

/-- **Base change of the projective bundle of a module** [Sta, Tag 01N2]: if `f : M → N` exhibits
`N` as `S ⊗_R M`, the square `P(N) ⟶ Spec S`, `P(N) ⟶ P(M)`, `Spec S ⟶ Spec R`,
`P(M) ⟶ Spec R` is cartesian. It is cartesian over each chart `D₊(ι x)` of `P(M)`
(`isPullback_map_aux` at the canonical pullback), hence cartesian. -/
theorem isPullback_map :
    IsPullback (π S N) (map φ f hspan) (Spec.map (CommRingCat.ofHom φ)) (π R M) :=
  (Scheme.isPullback_of_openCover (map φ f hspan) (π S N) (π R M)
    (Spec.map (CommRingCat.ofHom φ)) (chartCover (R := R) (M := M)).openCover fun x =>
      (isPullback_map_aux φ f hspan hext x (IsPullback.of_hasPullback _ _)).flip).flip

end AlgebraicGeometry.affineProjectiveBundle

namespace AlgebraicGeometry.affineProjectiveBundle

variable {R S : CommRingCat.{u}} {M N : Type u} [AddCommGroup M] [Module R M] [AddCommGroup N]
  [Module S N]

/-- `isPullback_map` for a morphism `φ : R ⟶ S` of `CommRingCat`. -/
theorem isPullback_mapHom (φ : R ⟶ S) (f : M →ₛₗ[φ.hom] N)
    (hspan : Submodule.span S (Set.range f) = ⊤)
    (hext : ∀ (T : Type u) [AddCommGroup T] [Module S T] (g : M →ₛₗ[φ.hom] T),
      ∃ g' : N →ₗ[S] T, ∀ x, g' (f x) = g x) :
    IsPullback (π S N) (mapHom φ f hspan) (Spec.map φ) (π R M) := by
  have := isPullback_map φ.hom f hspan hext
  rwa [CommRingCat.ofHom_hom] at this

end AlgebraicGeometry.affineProjectiveBundle
