/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.SymmetricAlgebra.Defs
public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor

/-!
# The projective bundle of a module

For an `R`-module `M`, the projective bundle `P(M) = Proj (Sym_R M)` over `Spec R`
[Sta, Tag 01OB] is `AlgebraicGeometry.affineProjectiveBundle R M`, with structure morphism
`affineProjectiveBundle.π` (`Proj.toSpecZero` followed by `R ≅ Sym⁰ M`). A ring map `φ : R → S`
and a `φ`-semilinear map `f : M → N` whose image spans `N` induce the morphism
`affineProjectiveBundle.map φ f : P(N) ⟶ P(M)`, Mathlib's `Proj.map` of the graded map
`Sym_R M → Sym_S N`; spanning is the hypothesis of `Proj.map`, that the irrelevant ideal of
`Sym_S N`, generated by `ι(N)`, lies in the ideal generated by the image of that of `Sym_R M`.
These are the pieces of the projective bundle `P(E)` of a quasi-coherent sheaf, glued over the
affine opens [Sta, Tag 01OB].
-/

@[expose] public section

universe u

open CategoryTheory SymmetricAlgebra

namespace SymmetricAlgebra

variable {R : Type u} {M : Type u} [CommRing R] [AddCommGroup M] [Module R M]

/-- The irrelevant ideal of `Sym M` is generated by `ι(M)`: an element of `Symⁱ M = ι(M)ⁱ`,
`i > 0`, is a sum of products with a factor in `ι(M)`. -/
theorem irrelevant_le_span_ι :
    (HomogeneousIdeal.irrelevant (grading R M)).toIdeal ≤ Ideal.span (Set.range (ι R M)) := by
  rw [HomogeneousIdeal.toIdeal_irrelevant_le]
  rintro (_ | i) hi x hx
  · exact absurd hi (lt_irrefl 0)
  change x ∈ LinearMap.range (ι R M) ^ (i + 1) at hx
  rw [pow_succ'] at hx
  change x ∈ Ideal.span (Set.range (ι R M))
  refine Submodule.mul_induction_on hx (fun a ha b _ => ?_) (fun a b ha hb => add_mem ha hb)
  obtain ⟨y, rfl⟩ := ha
  exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨y, rfl⟩)

variable {S : Type u} {N : Type u} [CommRing S] [AddCommGroup N] [Module S N]

/-- The hypothesis of `Proj.map` for the graded map of symmetric algebras: if `f(M)` spans `N`,
the irrelevant ideal of `Sym_S N` lies in the ideal generated by the image of that of `Sym_R M`. -/
theorem irrelevant_le_map_gradedMap (φ : R →+* S) (f : M →ₛₗ[φ] N)
    (hf : Submodule.span S (Set.range f) = ⊤) :
    HomogeneousIdeal.irrelevant (grading S N) ≤
      (HomogeneousIdeal.irrelevant (grading R M)).map (gradedMap φ f) := by
  rw [← toIdeal_le_toIdeal_iff, HomogeneousIdeal.toIdeal_map]
  refine irrelevant_le_span_ι.trans (Ideal.span_le.mpr ?_)
  rintro _ ⟨n, rfl⟩
  have hn : n ∈ Submodule.span S (Set.range f) := hf ▸ Submodule.mem_top
  change ι S N n ∈ _
  induction hn using Submodule.span_induction with
  | mem n hn =>
    obtain ⟨x, rfl⟩ := hn
    have hι : gradedMap φ f (ι R M x) = ι S N (f x) := by
      let := algebraOfRingHom (N := N) φ
      exact lift_ι_apply (ιₛₗ φ f) x
    rw [← hι]
    refine Ideal.mem_map_of_mem _ (HomogeneousIdeal.mem_irrelevant_of_mem _ one_pos ?_)
    simpa only [grading, pow_one] using LinearMap.mem_range_self _ x
  | zero => rw [map_zero]; exact zero_mem _
  | add n n' _ _ hn hn' => rw [map_add]; exact add_mem hn hn'
  | smul c n _ hn =>
    rw [LinearMap.map_smul, Algebra.smul_def]
    exact Ideal.mul_mem_left _ _ hn

end SymmetricAlgebra

namespace AlgebraicGeometry

variable (R : Type u) (M : Type u) [CommRing R] [AddCommGroup M] [Module R M]

/-- **The projective bundle of a module** [Sta, Tag 01OB]: `P(M) = Proj (Sym_R M)`. An `abbrev`,
so that Mathlib's instances on `Proj` apply to it. -/
noncomputable abbrev affineProjectiveBundle : Scheme.{u} := Proj (grading R M)

/-- The structure morphism `P(M) ⟶ Spec R`: `Proj.toSpecZero` followed by `Spec` of the
identification `R ≅ Sym⁰ M`. -/
noncomputable def affineProjectiveBundle.π : affineProjectiveBundle R M ⟶ Spec (.of R) :=
  Proj.toSpecZero (grading R M) ≫ Spec.map (gradingZeroEquiv R M).toCommRingCatIso.hom

variable {R M} {S : Type u} {N : Type u} [CommRing S] [AddCommGroup N] [Module S N]

/-- The morphism of projective bundles `P(N) ⟶ P(M)` induced by a ring map `φ : R → S` and a
`φ`-semilinear map `f : M → N` whose image spans `N`: `Proj.map` of the graded map
`Sym_R M → Sym_S N`. -/
noncomputable def affineProjectiveBundle.map (φ : R →+* S) (f : M →ₛₗ[φ] N)
    (hf : Submodule.span S (Set.range f) = ⊤) :
    affineProjectiveBundle S N ⟶ affineProjectiveBundle R M :=
  Proj.map (gradedMap φ f) (irrelevant_le_map_gradedMap φ f hf)

/-- `affineProjectiveBundle.map` for a morphism `φ : R ⟶ S` of `CommRingCat`. Applied to a
restriction map `Γ(X, V) ⟶ Γ(X, U)` of a scheme, the form with a ring homomorphism makes Lean unify
the ring structures of `↑Γ(X, U)` obtained by two routes, which unfolds the presheaf and times out;
passing the rings as objects of `CommRingCat` avoids it (as for `affineBlowUp.mapHom`). -/
noncomputable def affineProjectiveBundle.mapHom {R S : CommRingCat.{u}} {M N : Type u}
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module S N] (φ : R ⟶ S)
    (f : M →ₛₗ[φ.hom] N) (hf : Submodule.span S (Set.range f) = ⊤) :
    affineProjectiveBundle S N ⟶ affineProjectiveBundle R M :=
  affineProjectiveBundle.map φ.hom f hf

end AlgebraicGeometry
