/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.ProjectiveBundle.Affine.Defs
public import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion
public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Proper

/-!
# Closed immersions into `Proj` and properness of the projective bundle of a module

* `AlgebraicGeometry.Proj.isClosedImmersion_map_of_surjective`: a surjective graded ring map
  `F : A → B` induces a closed immersion `Proj B ⟶ Proj A` [Sta, Tag 01N0]. On the chart `D₊(s)` of
  `Proj A` the morphism is `Spec` of the surjection `(A_s)₀ → (B_{F s})₀`
  (`Proj.awayι_comp_map`, `Proj.map_preimage_basicOpen`), and being a closed immersion is local
  on the target.
* `AlgebraicGeometry.affineProjectiveBundle.isProper_π`: for a finitely generated `R`-module `M`,
  `P(M) = Proj (Sym M) ⟶ Spec R` is proper: `Sym M` is generated over `R` by
  finitely many elements of degree one, and Mathlib's `Proj.toSpecZero` is proper for a graded
  algebra of finite type over its degree-zero part.
-/

@[expose] public section

universe u

open CategoryTheory CategoryTheory.Limits HomogeneousLocalization

namespace AlgebraicGeometry

/-- A surjective graded ring map induces surjections of the degree-zero parts of the localizations
at homogeneous elements. -/
theorem _root_.HomogeneousLocalization.Away.map_surjective {A B : Type*} [CommRing A] [CommRing B]
    {σ τ : Type*} [SetLike σ A] [AddSubgroupClass σ A] [SetLike τ B] [AddSubgroupClass τ B]
    {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ] (F : 𝒜 →+*ᵍ ℬ)
    (hF : Function.Surjective F) {i : ℕ} {s : A} (hs : s ∈ 𝒜 i) :
    Function.Surjective (Away.map F s) := by
  intro z
  obtain ⟨n, b, hb, rfl⟩ := Away.mk_surjective ℬ (F.map_mem hs) z
  obtain ⟨a, rfl⟩ := hF b
  refine ⟨Away.mk 𝒜 hs n (DirectSum.decompose 𝒜 a (n • i)) (Subtype.prop _), ?_⟩
  rw [Away.map_mk]
  congr 1
  rw [GradedRingHom.map_directSumDecompose, DirectSum.decompose_of_mem_same _ hb]



/-- The chart square of `Proj.map`: the chart `D₊(F s)` of `Proj B` is the preimage of the chart
`D₊(s)` of `Proj A`, over which the morphism is `Spec` of `(A_s)₀ → (B_{F s})₀`. -/
theorem Proj.isPullback_awayι_map {A B : Type u} [CommRing A] [CommRing B]
    {σ τ : Type u} [SetLike σ A] [AddSubgroupClass σ A] [SetLike τ B] [AddSubgroupClass τ B]
    {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ] (F : 𝒜 →+*ᵍ ℬ)
    (hF : HomogeneousIdeal.irrelevant ℬ ≤ (HomogeneousIdeal.irrelevant 𝒜).map F)
    {i : ℕ} (hi : 0 < i) (s : A) (hs : s ∈ 𝒜 i) :
    IsPullback (Proj.awayι ℬ (F s) (F.map_mem hs) hi)
      (Spec.map (CommRingCat.ofHom (Away.map F s))) (Proj.map F hF) (Proj.awayι 𝒜 s hs hi) :=
  (IsOpenImmersion.isPullback _ _ _ _ (Proj.awayι_comp_map F hF hi s hs)
    (by rw [Proj.opensRange_awayι, Proj.opensRange_awayι, Proj.map_preimage_basicOpen])).flip

/-- **A surjective graded ring map induces a closed immersion** `Proj B ⟶ Proj A`
[Sta, Tag 01N0]. On the chart `D₊(s)` of `Proj A`, whose preimage is the chart `D₊(F s)` of
`Proj B`, the morphism is `Spec` of the surjection `(A_s)₀ → (B_{F s})₀`; being a closed immersion
is local on the target. -/
theorem Proj.isClosedImmersion_map_of_surjective {A B : Type u} [CommRing A] [CommRing B]
    {σ τ : Type u} [SetLike σ A] [AddSubgroupClass σ A] [SetLike τ B] [AddSubgroupClass τ B]
    {𝒜 : ℕ → σ} {ℬ : ℕ → τ} [GradedRing 𝒜] [GradedRing ℬ] (F : 𝒜 →+*ᵍ ℬ)
    (hF : HomogeneousIdeal.irrelevant ℬ ≤ (HomogeneousIdeal.irrelevant 𝒜).map F)
    (hsurj : Function.Surjective F) : IsClosedImmersion (Proj.map F hF) := by
  refine IsZariskiLocalAtTarget.of_openCover (Proj.affineOpenCover 𝒜).openCover fun j => ?_
  obtain ⟨⟨i, hi⟩, s, hs⟩ := j
  have hsq := Proj.isPullback_awayι_map F hF hi s hs
  have : IsClosedImmersion (Spec.map (CommRingCat.ofHom (Away.map F s))) :=
    IsClosedImmersion.spec_of_surjective _ (Away.map_surjective F hsurj hs)
  exact (MorphismProperty.arrow_mk_iso_iff @IsClosedImmersion
    (Arrow.isoMk (hsq.isoPullback) (Iso.refl _)
      (by simp only [Scheme.Cover.pullbackHom, Iso.refl_hom, Category.comp_id]
          exact hsq.isoPullback_hom_snd))).mp this

namespace affineProjectiveBundle

variable {R : Type u} {M : Type u} [CommRing R] [AddCommGroup M] [Module R M]

/-- For a finitely generated `M`, `Sym M` is of finite type over its degree-zero part `R`: it is
generated by the images of finitely many generators of `M`. -/
theorem finiteType_symmetricAlgebra [Module.Finite R M] :
    Algebra.FiniteType (SymmetricAlgebra.grading R M 0) (SymmetricAlgebra R M) := by
  classical
  obtain ⟨s, hs⟩ := Module.Finite.fg_top (R := R) (M := M)
  refine ⟨⟨s.image (SymmetricAlgebra.ι R M), ?_⟩⟩
  rw [Finset.coe_image, eq_top_iff]
  have hι : ∀ x : M, SymmetricAlgebra.ι R M x ∈ Algebra.adjoin (SymmetricAlgebra.grading R M 0)
      (SymmetricAlgebra.ι R M '' (s : Set M)) := by
    intro x
    have hx : x ∈ Submodule.span R (s : Set M) := hs ▸ Submodule.mem_top
    induction hx using Submodule.span_induction with
    | mem x hx => exact Algebra.subset_adjoin ⟨x, hx, rfl⟩
    | zero => rw [map_zero]; exact zero_mem _
    | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
    | smul c x _ hx =>
      rw [LinearMap.map_smul, Algebra.smul_def]
      exact mul_mem (Subalgebra.algebraMap_mem _
        (algebraMap R (SymmetricAlgebra.grading R M 0) c)) hx
  intro a ha
  clear ha
  induction a using SymmetricAlgebra.induction (R := R) (M := M) with
  | algebraMap r =>
    exact Subalgebra.algebraMap_mem _ (algebraMap R (SymmetricAlgebra.grading R M 0) r)
  | ι x => exact hι x
  | mul a b ha hb => exact mul_mem ha hb
  | add a b ha hb => exact add_mem ha hb

/-- **The projective bundle of a finitely generated module is proper** over `Spec R`: `Sym M` is
of finite type over `R`, and Mathlib's `Proj.toSpecZero` is proper for such graded algebras. -/
theorem isProper_π [Module.Finite R M] : IsProper (π R M) := by
  have := finiteType_symmetricAlgebra (R := R) (M := M)
  rw [π]
  infer_instance

end affineProjectiveBundle

end AlgebraicGeometry
