/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Hironaka.Scheme.Snc.Defs
import Hironaka.Scheme.BlowUp.BlowUpMapSquare
import Hironaka.Scheme.BlowUp.InvertibleSheaf
import Hironaka.Scheme.BlowUpSequence.BaseChangeOrder
import Hironaka.Scheme.BlowUpSequence.PullbackSnc
import Hironaka.Scheme.BlowUpSequence.SmoothParameters
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Snc.HasSncWith
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded
/-!
# Regular systems of parameters and simple normal crossings under a field extension

For `σ : k →+* L` a field extension in characteristic zero and `p : X_{L,σ} → X` the projection of
a cartesian square over `Spec σ`, a regular system of parameters of `𝒪_{X, p y}` extends along the
stalk map to one of `𝒪_{X_{L,σ}, y}`, so the simple normal crossing conditions `IsSncAt`, `IsSnc`
and `HasSncWith` of [Kol07, Definition 24] transport along `p`. These are the analogues, for the
change of fields of [Kol07, 34.2], of `exists_isSncAt_comap_of_smooth`, `isSnc_comap_of_smooth`
and `hasSncWith_comap_of_smooth` for a smooth morphism
(`Hironaka/Scheme/BlowUpSequence/PullbackSnc.lean`), whose proofs are followed step by step. None of
this is in the sources.

## The argument

The algebraic core `exists_isRegularSystemOfParameters_extend` asks of the local homomorphism
`A = 𝒪_{X, p y} → B = 𝒪_{X_{L,σ}, y}` only that both rings be regular (the schemes are smooth over
their fields), that it be local and **formally smooth**, and that `κ(A)/k` be formally smooth
(`k` perfect, `κ(A)` essentially of finite type). The one new fact is the formal smoothness of the
base-change stalk map:

* every field extension of a field of characteristic zero is formally smooth
  (`Algebra.FormallySmooth.of_charZero`): choose a transcendence basis
  (`exists_isTranscendenceBasis'`); `L` is algebraic, hence separable in characteristic zero
  (`Algebra.IsSeparable.of_integral`), over the purely transcendental intermediate field, and
  `Algebra.FormallySmooth.of_algebraicIndependent_of_isSeparable` concludes (the easy direction
  of [Sta, Tag 031X]; no finiteness needed);
* over an affine `U ∋ p y` the morphism `p` restricts to the affine `p⁻¹U = U ×_{Spec k} Spec L`
  (`p` is an affine morphism, the base change of `Spec σ`; the restricted square is the
  restriction square of `p` pasted on the base-change square), and `RingHom.FormallySmooth` is
  stable under base change (`IsStableUnderBaseChange.pullback_fst_appTop`), so `Γ(U) → Γ(p⁻¹U)`
  is formally smooth;
* localizing (`Algebra.FormallySmooth.of_isLocalization`, `comp`) gives `IsSmoothAt Γ(U) q` at
  the prime of `y`, which `formallySmooth_stalkMap_iff` turns into the formal smoothness of the
  stalk map of `p ∣_ U`, hence of `p` (`morphismRestrictStalkMap`).
-/

public section

universe u

open CategoryTheory CategoryTheory.Limits AlgebraicGeometry IsLocalRing Scheme BlowUpSequence

/-! ### Every field extension in characteristic zero is formally smooth -/

/-- A field extension `L/k` with `k` of characteristic zero is formally smooth (the easy direction
of [Sta, Tag 031X]): `L` is separable (`Algebra.IsSeparable.of_integral`) over the purely
transcendental extension generated by a transcendence basis, and separably generated extensions
are formally smooth (`Algebra.FormallySmooth.of_algebraicIndependent_of_isSeparable`). No
finiteness is assumed. -/
theorem Algebra.FormallySmooth.of_charZero {k L : Type u} [Field k] [Field L] [Algebra k L]
    [CharZero k] : Algebra.FormallySmooth k L := by
  obtain ⟨ι, x, hx⟩ := exists_isTranscendenceBasis' k L
  have halg : Algebra.IsAlgebraic (IntermediateField.adjoin k (Set.range x)) L :=
    hx.isAlgebraic_field
  have : CharZero (IntermediateField.adjoin k (Set.range x)) :=
    charZero_of_injective_algebraMap
      (algebraMap k (IntermediateField.adjoin k (Set.range x))).injective
  have : Algebra.IsIntegral (IntermediateField.adjoin k (Set.range x)) L :=
    Algebra.IsAlgebraic.isIntegral
  have : Algebra.IsSeparable (IntermediateField.adjoin k (Set.range x)) L := inferInstance
  exact Algebra.FormallySmooth.of_algebraicIndependent_of_isSeparable hx.1

namespace AlgebraicGeometry

variable {X Y : Scheme.{u}}

section StalkMap

variable {k : Type u} [Field k] {L : Type u} [Field L] {σ : k →+* L}
  {p : Y ⟶ X} {g' : Y ⟶ Spec (.of L)} {g : X ⟶ Spec (.of k)}

/-- The morphism `Spec σ` is formally smooth on global sections when `k` has characteristic zero
(`Algebra.FormallySmooth.of_charZero`, read through `ΓSpecIso`). -/
theorem formallySmooth_appTop_specMap [CharZero k] (σ : k →+* L) :
    (Spec.map (CommRingCat.ofHom σ)).appTop.hom.FormallySmooth := by
  have h1 : (Spec.map (CommRingCat.ofHom σ)).appTop =
      (Scheme.ΓSpecIso (.of k)).hom ≫ CommRingCat.ofHom σ ≫ (Scheme.ΓSpecIso (.of L)).inv := by
    rw [← Category.assoc, ← Scheme.ΓSpecIso_naturality, Category.assoc, Iso.hom_inv_id,
      Category.comp_id]
  have hσ : (CommRingCat.ofHom σ).hom.FormallySmooth := by
    let := σ.toAlgebra
    exact RingHom.formallySmooth_algebraMap.mpr Algebra.FormallySmooth.of_charZero
  rw [h1, CommRingCat.hom_comp, RingHom.FormallySmooth.respectsIso.cancel_left_isIso,
    CommRingCat.hom_comp, RingHom.FormallySmooth.respectsIso.cancel_right_isIso]
  exact hσ

/-- The restriction of `p` over an affine open `U ⊆ X` is formally smooth on global sections:
`p⁻¹U = U ×_{Spec k} Spec L` and formal smoothness is stable under base change
(`IsStableUnderBaseChange.pullback_fst_appTop`). -/
theorem formallySmooth_appTop_morphismRestrict_of_isPullback_specMap [CharZero k]
    (sq : IsPullback p g' g (Spec.map (CommRingCat.ofHom σ))) (U : X.Opens) (hU : IsAffineOpen U) :
    (p ∣_ U).appTop.hom.FormallySmooth := by
  have : IsAffineHom p := property_of_isPullback @IsAffineHom sq inferInstance
  have hW : IsAffineOpen (p ⁻¹ᵁ U) := hU.preimage p
  have : IsAffine (U : Scheme.{u}) := hU
  have : IsAffine ((p ⁻¹ᵁ U : Y.Opens) : Scheme.{u}) := hW
  have sq' : IsPullback (p ∣_ U) ((p ⁻¹ᵁ U).ι ≫ g') (U.ι ≫ g)
      (Spec.map (CommRingCat.ofHom σ)) :=
    (isPullback_morphismRestrict p U).paste_vert sq
  have hpb : (pullback.fst (U.ι ≫ g)
      (Spec.map (CommRingCat.ofHom σ))).appTop.hom.FormallySmooth :=
    RingHom.IsStableUnderBaseChange.pullback_fst_appTop (P := @RingHom.FormallySmooth)
      RingHom.FormallySmooth.isStableUnderBaseChange RingHom.FormallySmooth.respectsIso _ _
      (formallySmooth_appTop_specMap σ)
  have h2 : p ∣_ U =
      sq'.isoPullback.hom ≫ pullback.fst (U.ι ≫ g) (Spec.map (CommRingCat.ofHom σ)) :=
    sq'.isoPullback_hom_fst.symm
  have : IsIso sq'.isoPullback.hom.appTop := by
    refine ⟨sq'.isoPullback.inv.appTop, ?_, ?_⟩
    · rw [← Scheme.Hom.comp_appTop, Iso.inv_hom_id, Scheme.Hom.id_appTop]
    · rw [← Scheme.Hom.comp_appTop, Iso.hom_inv_id, Scheme.Hom.id_appTop]
  rw [h2, Scheme.Hom.comp_appTop, CommRingCat.hom_comp,
    RingHom.FormallySmooth.respectsIso.cancel_right_isIso]
  exact hpb

/-- The stalk map of the projection of a base-change square along a field extension in
characteristic zero is formally smooth: `formallySmooth_stalkMap_iff` on the affine restriction
`p ∣_ U : p⁻¹U → U` with `Γ(U) → Γ(p⁻¹U)` formally smooth and the localization at the prime of `y`
(`IsSmoothAt`), transported to `p` by `morphismRestrictStalkMap`. -/
theorem formallySmooth_stalkMap_of_isPullback_specMap [CharZero k]
    (sq : IsPullback p g' g (Spec.map (CommRingCat.ofHom σ))) (y : Y) :
    (p.stalkMap y).hom.FormallySmooth := by
  obtain ⟨U, hxU⟩ := Scheme.IdealSheafData.exists_affineOpens_mem (p y)
  have hU : IsAffineOpen U.1 := U.2
  have : IsAffineHom p := property_of_isPullback @IsAffineHom sq inferInstance
  have hW : IsAffineOpen (p ⁻¹ᵁ U.1) := hU.preimage p
  have hy : y ∈ p ⁻¹ᵁ U.1 := hxU
  have : IsAffine (U.1 : Scheme.{u}) := hU
  have : IsAffine ((p ⁻¹ᵁ U.1 : Y.Opens) : Scheme.{u}) := hW
  have hres := formallySmooth_appTop_morphismRestrict_of_isPullback_specMap sq U.1 hU
  have hstalk : ((p ∣_ U.1).stalkMap ⟨y, hy⟩).hom.FormallySmooth := by
    let W : Scheme.{u} := (p ⁻¹ᵁ U.1 : Y.Opens)
    let x₀ : W := ⟨y, hy⟩
    let V : W.Opens := (p ∣_ U.1) ⁻¹ᵁ (⊤ : (U.1 : Scheme.{u}).Opens)
    have hV : IsAffineOpen V := by
      change IsAffineOpen ((p ∣_ U.1) ⁻¹ᵁ ⊤)
      rw [Scheme.Hom.preimage_top]
      exact isAffineOpen_top _
    have hx₀ : x₀ ∈ V := trivial
    have key := formallySmooth_stalkMap_iff (f := p ∣_ U.1) (x := x₀)
      (⊤ : (U.1 : Scheme.{u}).Opens) (isAffineOpen_top _) V hV le_rfl hx₀
    refine key.mpr ?_
    have hLE : ((p ∣_ U.1).appLE ⊤ V le_rfl).hom.FormallySmooth := by
      rw [Scheme.Hom.appLE_eq_app]
      exact hres
    let inst := ((p ∣_ U.1).appLE ⊤ V le_rfl).hom.toAlgebra
    have h1 : Algebra.FormallySmooth Γ((U.1 : Scheme.{u}), ⊤) Γ(W, V) :=
      RingHom.formallySmooth_algebraMap.mp hLE
    have h2 : Algebra.FormallySmooth Γ(W, V)
        (Localization.AtPrime (hV.primeIdealOf ⟨x₀, hx₀⟩).asIdeal) :=
      Algebra.FormallySmooth.of_isLocalization (hV.primeIdealOf ⟨x₀, hx₀⟩).asIdeal.primeCompl
    exact Algebra.FormallySmooth.comp Γ((U.1 : Scheme.{u}), ⊤) Γ(W, V) _
  exact (RingHom.FormallySmooth.respectsIso.arrow_mk_iso_iff
    (morphismRestrictStalkMap p U.1 ⟨y, hy⟩)).mp hstalk

/-- The local statement: along the stalk map of the projection of a base-change square along a
field extension in characteristic zero, a regular system of parameters at `p y` extends to one at
`y` (`exists_isRegularSystemOfParameters_extend` with the formal smoothness of the stalk map from
`formallySmooth_stalkMap_of_isPullback_specMap`). -/
theorem exists_isRegularSystemOfParameters_stalkMap_of_isPullback_specMap [CharZero k]
    (sq : IsPullback p g' g (Spec.map (CommRingCat.ofHom σ))) [Smooth g] (y : Y) {n : ℕ}
    (z : Fin n → X.presheaf.stalk (p y)) (hz : IsRegularSystemOfParameters z) :
    ∃ (m : ℕ) (w : Fin m → Y.presheaf.stalk y), IsRegularSystemOfParameters w ∧
      ∃ τ : Fin n → Fin m, Function.Injective τ ∧ ∀ i, w (τ i) = (p.stalkMap y).hom (z i) := by
  have hg' : Smooth g' := smooth_of_isPullback_specMap sq
  let : Algebra k (X.presheaf.stalk (p y)) := g.stalkAlgebra (p y)
  let : Algebra (X.presheaf.stalk (p y)) (Y.presheaf.stalk y) := (p.stalkMap y).hom.toAlgebra
  let : Algebra k (Y.presheaf.stalk y) :=
    ((p.stalkMap y).hom.comp (algebraMap k (X.presheaf.stalk (p y)))).toAlgebra
  have : IsScalarTower k (X.presheaf.stalk (p y)) (Y.presheaf.stalk y) :=
    IsScalarTower.of_algebraMap_eq' rfl
  have : IsRegularLocalRing (X.presheaf.stalk (p y)) :=
    isRegularLocalRing_stalk g (p y)
  have : IsRegularLocalRing (Y.presheaf.stalk y) :=
    isRegularLocalRing_stalk g' y
  have : IsLocalHom (algebraMap (X.presheaf.stalk (p y)) (Y.presheaf.stalk y)) :=
    inferInstanceAs (IsLocalHom (p.stalkMap y).hom)
  have : Algebra.FormallySmooth (X.presheaf.stalk (p y)) (Y.presheaf.stalk y) :=
    RingHom.formallySmooth_algebraMap.mp (formallySmooth_stalkMap_of_isPullback_specMap sq y)
  have : Algebra.EssFiniteType k (X.presheaf.stalk (p y)) :=
    essFiniteType_stalk_of_locallyOfFiniteType g (p y)
  have : Algebra.EssFiniteType k (ResidueField (X.presheaf.stalk (p y))) :=
    inferInstanceAs (Algebra.EssFiniteType k (_ ⧸ maximalIdeal (X.presheaf.stalk (p y))))
  exact exists_isRegularSystemOfParameters_extend (k := k) z hz

/-! ### Simple normal crossings under a field extension -/

/-- The pointwise statement: the simple normal crossing data of `E` at `p y`
([Kol07, Definition 24]) transport to simple normal crossing data of `p⁻¹ E` at `y` (the analogue
of `exists_isSncAt_comap_of_smooth` for the base change). -/
theorem exists_isSncAt_comap_of_isPullback_specMap [CharZero k]
    (sq : IsPullback p g' g (Spec.map (CommRingCat.ofHom σ))) [Smooth g] {E : DivisorFamily X}
    {y : Y} {n : ℕ} {z : Fin n → X.presheaf.stalk (p y)} (hE : E.IsSncAt (p y) z) :
    ∃ (m : ℕ) (w : Fin m → Y.presheaf.stalk y), (E.comap p).IsSncAt y w ∧
      ∃ τ : Fin n → Fin m, Function.Injective τ ∧ ∀ i, w (τ i) = (p.stalkMap y).hom (z i) := by
  obtain ⟨hz, c, hc, hcE⟩ := hE
  obtain ⟨m, w, hw, τ, hτ, hwτ⟩ :=
    exists_isRegularSystemOfParameters_stalkMap_of_isPullback_specMap sq y z hz
  refine ⟨m, w, ⟨hw, ?_⟩, τ, hτ, hwτ⟩
  let ρ : {i : (E.comap p).ι // y ∈ ((E.comap p).component i).support} →
      {i : E.ι // p y ∈ (E.component i).support} :=
    fun i => ⟨i.1, (mem_support_comap_iff_apply (E.component i.1) p y).mp i.2⟩
  have hρ : Function.Injective ρ := fun i j hij =>
    Subtype.ext (show (ρ i).1 = (ρ j).1 from congrArg Subtype.val hij)
  refine ⟨fun i => τ (c (ρ i)), hτ.comp (hc.comp hρ), fun i => ?_⟩
  change ((E.component i.1).comap p).stalkIdeal y = Ideal.span {w (τ (c (ρ i)))}
  have hi := hcE (ρ i)
  change (E.component i.1).stalkIdeal (p y) = Ideal.span {z (c (ρ i))} at hi
  rw [Scheme.IdealSheafData.stalkIdeal_comap, hwτ, hi, Ideal.map_span, Set.image_singleton]

/-- A simple normal crossing family on `X` smooth over `k` pulls back to one on `X_{L,σ}` (Kollár's
`E_{L,σ}`, [Kol07, 34.2]; the analogue of `isSnc_comap_of_smooth` for the base change): the
components' subschemes are regular because their stalks are quotients of the regular local rings
of `X_{L,σ}` by a member of a regular system of parameters. -/
theorem isSnc_comap_of_isPullback_specMap [CharZero k]
    (sq : IsPullback p g' g (Spec.map (CommRingCat.ofHom σ))) [Smooth g] {E : DivisorFamily X}
    (hE : E.IsSnc) : (E.comap p).IsSnc := by
  have hg' : Smooth g' := smooth_of_isPullback_specMap sq
  refine ⟨fun i => ?_, fun y => ?_⟩
  · refine isRegular_subscheme_of_isRegularLocalRing_quotient _ fun y hy => ?_
    obtain ⟨n, z, hz⟩ := hE.2 (p y)
    obtain ⟨m, w, ⟨hw, c, -, hc⟩, -⟩ := exists_isSncAt_comap_of_isPullback_specMap sq hz
    have : IsRegularLocalRing (Y.presheaf.stalk y) := isRegularLocalRing_stalk g' y
    have hy' : y ∈ ((E.comap p).component i).support := hy
    have hZ : ((E.comap p).component i).stalkIdeal y =
        Ideal.span (w '' ↑({c ⟨i, hy'⟩} : Finset (Fin m))) := by
      rw [Finset.coe_singleton, Set.image_singleton]
      exact hc ⟨i, hy'⟩
    exact isRegularLocalRing_quotient_stalkIdeal_of_eq_span hw hZ
  · obtain ⟨n, z, hz⟩ := hE.2 (p y)
    obtain ⟨m, w, hw, -⟩ := exists_isSncAt_comap_of_isPullback_specMap sq hz
    exact ⟨m, w, hw⟩

/-- Simple normal crossings of a closed subscheme with a family ([Kol07, Definition 24, condition
(4)]) are preserved by the base change along a field extension (the analogue of
`hasSncWith_comap_of_smooth`). -/
theorem hasSncWith_comap_of_isPullback_specMap [CharZero k]
    (sq : IsPullback p g' g (Spec.map (CommRingCat.ofHom σ))) [Smooth g] {E : DivisorFamily X}
    {Z : X.IdealSheafData} (hZ : E.HasSncWith Z) : (E.comap p).HasSncWith (Z.comap p) := by
  intro y hy
  obtain ⟨n, z, hsnc, s, hs⟩ := hZ (p y) ((mem_support_comap_iff_apply Z p y).mp hy)
  obtain ⟨m, w, hw, τ, -, hwτ⟩ := exists_isSncAt_comap_of_isPullback_specMap sq hsnc
  refine ⟨m, w, hw, s.image τ, ?_⟩
  rw [Scheme.IdealSheafData.stalkIdeal_comap, hs, Ideal.map_span, Finset.coe_image]
  simp only [Set.image_image]
  exact congrArg Ideal.span (Set.image_congr fun x _ => (hwτ x).symm)

end StalkMap

end AlgebraicGeometry
