/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUpSequence.FunctorVocabulary
import Hironaka.Scheme.BlowUpSequence.InducedData
import Hironaka.Scheme.BlowUpSequence.PullbackInduced
import Hironaka.Scheme.BlowUpSequence.PullbackSmooth
import Hironaka.Scheme.BlowUpSequence.SmoothParameters
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Snc.HasSncWith
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# Simple normal crossings and the order conditions under smooth pullback

A smooth blow-up sequence `B` on `X` pulled back along a smooth morphism `h : Y ⟶ X`
([Kol07, 30.1 and 34.1]; [Wlo05, Proposition 2.4.2]) has induced data equal to the inverse images
of the induced data of `B` (`Hironaka/Scheme/BlowUpSequence/PullbackInduced.lean`). This module
transports the conditions of [Kol07, Definition 66] along `h`:

* simple normal crossings [Kol07, Definition 24]: a regular system of parameters at `h y` extends
  along the stalk map to one at `y` (`Hironaka/Scheme/BlowUpSequence/SmoothParameters.lean`), and
  the components of `h⁻¹ E` through `y` are the inverse images of the components of `E` through `h
  y` (`exists_isSncAt_comap_of_smooth`, `isSnc_comap_of_smooth`, `hasSncWith_comap_of_smooth`);
* the order predicates: `IsOrderSeq.pullback` and `IsOrderGeSeq.pullback` combine the
  identifications of the induced data with the transport of simple normal crossings and with the
  invariance of the order along a center under smooth pullback (`ordAlongEq_comap_of_smooth`).

Kollár deletes the empty blow-ups of the pullback [Kol07, 34.1]; on the predicates used here an
empty center satisfies the order clause vacuously, so the pullback itself is a smooth blow-up
sequence of order `m` ([Wlo05, Proposition 2.4.2 (2)]), and the form with the empty blow-ups
deleted follows in `Hironaka/Scheme/BlowUpSequence/PullbackEraseEmpty.lean`.
-/

public section

universe u

open CategoryTheory AlgebraicGeometry Scheme BlowUpSequence IsLocalRing

namespace AlgebraicGeometry

variable {X Y : Scheme.{u}}

/-- A point lies in the support of the inverse image iff its image lies in the support
(Mathlib's `support_comap`). -/
@[simp]
theorem mem_support_comap_iff_apply (Z : X.IdealSheafData) (h : Y ⟶ X) (y : Y) :
    y ∈ (Z.comap h).support ↔ h y ∈ Z.support := by
  rw [Scheme.IdealSheafData.support_comap]
  exact Iff.rfl

/-! ### Simple normal crossings under smooth pullback -/

section Snc

variable {k : Type u} [Field k] [PerfectField k]

/-- The pointwise statement: simple normal crossing data of `E` at `h y` (a regular system of
parameters `z` with the components through `h y` among its coordinate hypersurfaces,
[Kol07, Definition 24]) transport to such data of `h⁻¹ E` at `y`: `z` extends along the stalk map
to a regular system of parameters `w` (`exists_isRegularSystemOfParameters_stalkMap`), the
components of `h⁻¹ E` through `y` are the inverse images of the components of `E` through `h y`
(`support_comap`), and their stalks are generated by the corresponding `w` (`stalkIdeal_comap`). -/
theorem exists_isSncAt_comap_of_smooth (f : X ⟶ Spec (.of k)) [Smooth f] (h : Y ⟶ X) [Smooth h]
    {E : DivisorFamily X} {y : Y} {n : ℕ} {z : Fin n → X.presheaf.stalk (h y)}
    (hE : E.IsSncAt (h y) z) :
    ∃ (m : ℕ) (w : Fin m → Y.presheaf.stalk y), (E.comap h).IsSncAt y w ∧
      ∃ σ : Fin n → Fin m, Function.Injective σ ∧ ∀ i, w (σ i) = (h.stalkMap y).hom (z i) := by
  obtain ⟨hz, c, hc, hcE⟩ := hE
  obtain ⟨m, w, hw, σ, hσ, hwσ⟩ := exists_isRegularSystemOfParameters_stalkMap f h y z hz
  refine ⟨m, w, ⟨hw, ?_⟩, σ, hσ, hwσ⟩
  let τ : {i : (E.comap h).ι // y ∈ ((E.comap h).component i).support} →
      {i : E.ι // h y ∈ (E.component i).support} :=
    fun i => ⟨i.1, (mem_support_comap_iff_apply (E.component i.1) h y).mp i.2⟩
  have hτ : Function.Injective τ := fun i j hij =>
    Subtype.ext (show (τ i).1 = (τ j).1 from congrArg Subtype.val hij)
  refine ⟨fun i => σ (c (τ i)), hσ.comp (hc.comp hτ), fun i => ?_⟩
  change ((E.component i.1).comap h).stalkIdeal y = Ideal.span {w (σ (c (τ i)))}
  have hi := hcE (τ i)
  change (E.component i.1).stalkIdeal (h y) = Ideal.span {z (c (τ i))} at hi
  rw [Scheme.IdealSheafData.stalkIdeal_comap, hwσ, hi, Ideal.map_span, Set.image_singleton]

/-- A simple normal crossing family on a scheme smooth over `k` pulls back to a simple normal
crossing family along a smooth `h` [Wlo05, Proposition 2.4.2, proof]. The components' subschemes
are regular because their stalks are the quotients of a regular local ring by a member of a
regular system of parameters. -/
theorem isSnc_comap_of_smooth (f : X ⟶ Spec (.of k)) [Smooth f] (h : Y ⟶ X) [Smooth h]
    {E : DivisorFamily X} (hE : E.IsSnc) : (E.comap h).IsSnc := by
  refine ⟨fun i => ?_, fun y => ?_⟩
  · refine isRegular_subscheme_of_isRegularLocalRing_quotient _ fun y hy => ?_
    obtain ⟨n, z, hz⟩ := hE.2 (h y)
    obtain ⟨m, w, ⟨hw, c, -, hc⟩, -⟩ := exists_isSncAt_comap_of_smooth f h hz
    have : IsRegularLocalRing (Y.presheaf.stalk y) :=
      isRegularLocalRing_stalk (h ≫ f) y
    have hy' : y ∈ ((E.comap h).component i).support := hy
    have hZ : ((E.comap h).component i).stalkIdeal y =
        Ideal.span (w '' ↑({c ⟨i, hy'⟩} : Finset (Fin m))) := by
      rw [Finset.coe_singleton, Set.image_singleton]
      exact hc ⟨i, hy'⟩
    exact isRegularLocalRing_quotient_stalkIdeal_of_eq_span hw hZ
  · obtain ⟨n, z, hz⟩ := hE.2 (h y)
    obtain ⟨m, w, hw, -⟩ := exists_isSncAt_comap_of_smooth f h hz
    exact ⟨m, w, hw⟩

/-- Simple normal crossings of a closed subscheme with a family [Kol07, Definition 24 (4)] are
preserved by smooth pullback: the coordinates of `Z` at `h y` map to coordinates of `h⁻¹ Z` at
`y` ("`C'_i` has simple normal crossings with `E'_i`", [Wlo05, Proposition 2.4.2, proof]). -/
theorem hasSncWith_comap_of_smooth (f : X ⟶ Spec (.of k)) [Smooth f] (h : Y ⟶ X) [Smooth h]
    {E : DivisorFamily X} {Z : X.IdealSheafData} (hZ : E.HasSncWith Z) :
    (E.comap h).HasSncWith (Z.comap h) := by
  intro y hy
  obtain ⟨n, z, hsnc, s, hs⟩ := hZ (h y) ((mem_support_comap_iff_apply Z h y).mp hy)
  obtain ⟨m, w, hw, σ, -, hwσ⟩ := exists_isSncAt_comap_of_smooth f h hsnc
  refine ⟨m, w, hw, s.image σ, ?_⟩
  rw [Scheme.IdealSheafData.stalkIdeal_comap, hs, Ideal.map_span, Finset.coe_image]
  simp only [Set.image_image]
  exact congrArg Ideal.span (Set.image_congr fun x _ => (hwσ x).symm)

end Snc

/-! ### The order predicates under smooth pullback -/

section OrderSeq

variable {k : Type u} [Field k]

/-- `IsOrderSeq.pullback` for a smooth `h` with equidimensional source: the relative dimension `n'`
of `h ≫ f` replaces a relative dimension of `h`, the form available when the pulled-back triple is
given. -/
theorem IsOrderSeq.pullback_of_equidim [CharZero k] (f : X ⟶ Spec (.of k)) (n : ℕ)
    [SmoothOfRelativeDimension n f] (h : Y ⟶ X) [Smooth h] (n' : ℕ)
    [SmoothOfRelativeDimension n' (h ≫ f)]
    {S : BlowUpSequence X} {I : X.IdealSheafData} {E : DivisorFamily X} {m : ℕ}
    (hS : S.IsOrderSeq f I E m) : (S.pullback h).IsOrderSeq (h ≫ f) (I.comap h) (E.comap h) m := by
  refine ⟨IsSmooth.pullback f h hS.1, ?_⟩
  rintro ⟨j, hj⟩
  have hj' : j < S.length := by rwa [length_pullback] at hj
  have hsm : Smooth (S.stageMap ⟨j, Nat.lt_succ_of_lt hj'⟩ ≫ f) :=
    IsSmooth.smooth_stageMap (n := n) hS.1 _
  have hsh : Smooth (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    smooth_pullbackStageHom S h _
  have hc : (S.pullback h).center ⟨j, hj⟩ =
      (S.center ⟨j, hj'⟩).comap (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    center_pullback_mk S h j hj'
  have hE : (S.pullback h).totalTransformSeq (E.comap h)
        (⟨j, hj⟩ : Fin (S.pullback h).length).castSucc =
      (S.totalTransformSeq E ⟨j, Nat.lt_succ_of_lt hj'⟩).comap
        (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    totalTransformSeq_pullback_mk S h E j (Nat.lt_succ_of_lt hj')
  have hI : (S.pullback h).weakTransformSeq (I.comap h)
        (⟨j, hj⟩ : Fin (S.pullback h).length).castSucc =
      (S.weakTransformSeq I ⟨j, Nat.lt_succ_of_lt hj'⟩).comap
        (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    IsOrderSeq.weakTransformSeq_pullback_mk_of_equidim f n h n' hS j (Nat.lt_succ_of_lt hj')
  obtain ⟨hsnc, hord⟩ := hS.2 ⟨j, hj'⟩
  rw [hc, hE, hI]
  exact ⟨hasSncWith_comap_of_smooth (S.stageMap ⟨j, Nat.lt_succ_of_lt hj'⟩ ≫ f)
    (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) hsnc, ordAlongEq_comap_of_smooth _ hord⟩

/-- The pullback of a smooth blow-up sequence of order `m` for `(X, I, E)` along a smooth `h` is a
smooth blow-up sequence of order `m` for `(Y, h^* I, h^{-1} E)` ([Wlo05, Proposition 2.4.2];
[Kol07, 34.1]), with no deletion of empty blow-ups: an empty pulled-back center satisfies the order
clause vacuously. Stage by stage: the centers are the inverse images of the centers
(`center_pullback`), the induced families and ideals the inverse images of the induced families
and ideals (`Hironaka/Scheme/BlowUpSequence/PullbackInduced.lean`), and simple normal crossings and
the order transport along the smooth stage lifts (`hasSncWith_comap_of_smooth`,
`ordAlongEq_comap_of_smooth`). -/
theorem IsOrderSeq.pullback [CharZero k] (f : X ⟶ Spec (.of k)) (n : ℕ)
    [SmoothOfRelativeDimension n f] (h : Y ⟶ X) {d : ℕ} [SmoothOfRelativeDimension d h]
    {S : BlowUpSequence X} {I : X.IdealSheafData} {E : DivisorFamily X} {m : ℕ}
    (hS : S.IsOrderSeq f I E m) : (S.pullback h).IsOrderSeq (h ≫ f) (I.comap h) (E.comap h) m := by
  have := SmoothOfRelativeDimension.smooth d h
  have := smoothOfRelativeDimension_comp d n h f
  exact IsOrderSeq.pullback_of_equidim f n h (d + n) hS

/-- The marked form for any smooth `h`: the marked transport needs no relative dimension at
all. -/
theorem IsOrderGeSeq.pullback_of_smooth [CharZero k] (f : X ⟶ Spec (.of k)) (n : ℕ)
    [SmoothOfRelativeDimension n f] (h : Y ⟶ X) [Smooth h]
    {S : BlowUpSequence X} {I : X.IdealSheafData} {m : ℕ} {E : DivisorFamily X}
    (hS : S.IsOrderGeSeq f I m E) :
    (S.pullback h).IsOrderGeSeq (h ≫ f) (I.comap h) m (E.comap h) := by
  refine ⟨IsSmooth.pullback f h hS.1, ?_⟩
  rintro ⟨j, hj⟩
  have hj' : j < S.length := by rwa [length_pullback] at hj
  have hsm : Smooth (S.stageMap ⟨j, Nat.lt_succ_of_lt hj'⟩ ≫ f) :=
    IsSmooth.smooth_stageMap (n := n) hS.1 _
  have hsh : Smooth (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    smooth_pullbackStageHom S h _
  have hc : (S.pullback h).center ⟨j, hj⟩ =
      (S.center ⟨j, hj'⟩).comap (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    center_pullback_mk S h j hj'
  have hE : (S.pullback h).totalTransformSeq (E.comap h)
        (⟨j, hj⟩ : Fin (S.pullback h).length).castSucc =
      (S.totalTransformSeq E ⟨j, Nat.lt_succ_of_lt hj'⟩).comap
        (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    totalTransformSeq_pullback_mk S h E j (Nat.lt_succ_of_lt hj')
  have hI : (S.pullback h).markedTransformSeq (I.comap h) m
        (⟨j, hj⟩ : Fin (S.pullback h).length).castSucc =
      (S.markedTransformSeq I m ⟨j, Nat.lt_succ_of_lt hj'⟩).comap
        (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) :=
    IsOrderGeSeq.markedTransformSeq_comap_pullbackStageHom_mk f n h hS j (Nat.lt_succ_of_lt hj')
  obtain ⟨hsnc, hord⟩ := hS.2 ⟨j, hj'⟩
  rw [hc, hE, hI]
  exact ⟨hasSncWith_comap_of_smooth (S.stageMap ⟨j, Nat.lt_succ_of_lt hj'⟩ ≫ f)
    (S.pullbackStageHom h ⟨j, Nat.lt_succ_of_lt hj'⟩) hsnc, leOrdAlong_comap_of_smooth _ hord⟩

/-- The marked form `≥ m` of `IsOrderSeq.pullback` [Wlo05, Proposition 2.4.2]. -/
theorem IsOrderGeSeq.pullback [CharZero k] (f : X ⟶ Spec (.of k)) (n : ℕ)
    [SmoothOfRelativeDimension n f] (h : Y ⟶ X) {d : ℕ} [SmoothOfRelativeDimension d h]
    {S : BlowUpSequence X} {I : X.IdealSheafData} {m : ℕ} {E : DivisorFamily X}
    (hS : S.IsOrderGeSeq f I m E) :
    (S.pullback h).IsOrderGeSeq (h ≫ f) (I.comap h) m (E.comap h) :=
  have := SmoothOfRelativeDimension.smooth d h
  IsOrderGeSeq.pullback_of_smooth f n h hS

end OrderSeq

end AlgebraicGeometry
