/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.IdealSheaf.Derivative.Sheaf
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Logarithmic derivations and logarithmic derivative ideals

[Kol07, 87]: for a smooth variety `X` and a smooth hypersurface `S ⊂ X`, the sheaf
`Der_X(−log S) ⊂ Der_X` of logarithmic derivations along `S` is "the largest subsheaf that maps
`𝒪_X(−S)` into itself by derivations", and for an ideal sheaf `I`,
`D(−log S)(I) := im[Der_X(−log S) × I → 𝒪_X]`, `D^{r+1}(−log S)(I) := D(−log S)(D^r(−log S)(I))`.
Bierstone and Milman use the same ideals `D_E(I)` for a normal-crossings divisor `E`
[BM08, §3.2].

* Ring level. A derivation `δ` **preserves** an ideal `J` when `δ(J) ⊆ J`
  (`Derivation.PreservesIdeal`; the derivations preserving `J` form the `A`-submodule
  `Derivation.preserving k J` of `Derivation k A A`). The **logarithmic derivative ideal**
  `Ideal.logDerivative k J I` is generated by `I` and the `δ f`, `δ` a `k`-derivation preserving
  `J`, `f ∈ I`: `Ideal.derivative` of `Hironaka/Algebra/Derivative/Basic.lean` with the derivations
  restricted to those preserving `J`; `Ideal.logDerivativeIter` iterates.
  `I ⊆ D(−log J)(I) ⊆ D(I)`, and `D(−log ⊤)(I) = D(I)`: away from `S` every derivation is
  logarithmic.
* Sheaf level. `IdealSheafData.logDerivative f S I` is packaged, like `derivative` of
  `Hironaka/Scheme/IdealSheaf/Derivative/Sheaf.lean`, through Mathlib's `ofIdeals` from the family
  `U ↦ D(−log S(U))(I(U))` for the `k`-algebra structures `f.sectionsAlgebra U`;
  `logDerivativeIter` iterates. The compatibility of the family with restriction to basic opens
  is `Hironaka/Scheme/IdealSheaf/Derivative/LogarithmicLocalization.lean`, the identification of the
  stalks `Hironaka/Scheme/IdealSheaf/Derivative/LogarithmicSheaf.lean`; Kollár's three properties
  (87.1)–(87.3) are `Hironaka/Scheme/IdealSheaf/Derivative/LogarithmicQuotient.lean`,
  `Hironaka/Algebra/Local/LogDeriv.lean` (in coordinates) and
  `Hironaka/Scheme/BlowUpSequence/TransformLogDerivative.lean`.

Used in coordinates (`Hironaka/Algebra/Local/LogDerivCoords.lean`), for the blow-up chart
(`Hironaka/Algebra/Local/BlowUpLiftLog.lean`, `Hironaka/Algebra/Local/ChartLogDerivations.lean`,
`Hironaka/Algebra/Local/TransformLogDerivMap.lean`), for Theorem 88 and Corollary 89 on schemes
(`Hironaka/Scheme/BlowUpSequence/Theorem88Basic.lean`,
`Hironaka/Resolution/Algebraic/Kol07/Corollary89.lean`) and on manifolds
(`Hironaka/Manifold/IdealSheaf/LogDeriv.lean`).
-/

@[expose] public section

namespace Derivation

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- A derivation preserves the ideal `J` (Kollár's "maps `𝒪_X(−S)` into itself by derivations",
[Kol07, 87]). -/
def PreservesIdeal (δ : Derivation k A A) (J : Ideal A) : Prop := ∀ a ∈ J, δ a ∈ J

theorem preservesIdeal_top (δ : Derivation k A A) : δ.PreservesIdeal ⊤ := fun _ _ => trivial

/-- A derivation preserves a principal ideal `(s)` iff `δ s ∈ (s)` (Leibniz). -/
theorem preservesIdeal_span_singleton_iff (δ : Derivation k A A) (s : A) :
    δ.PreservesIdeal (Ideal.span {s}) ↔ δ s ∈ Ideal.span {s} := by
  refine ⟨fun h => h s (Ideal.mem_span_singleton_self s), fun h a ha => ?_⟩
  obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp ha
  rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
  exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ h)
    (Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self s))

/-- The derivations preserving `J`, as an `A`-submodule of the derivations: Kollár's
`Der_X(−log S)` at the level of a ring. -/
def preserving (k : Type*) [CommRing k] [Algebra k A] (J : Ideal A) : Submodule A (Derivation k A A)
    where
  carrier := {δ | δ.PreservesIdeal J}
  add_mem' {δ δ'} hδ hδ' a ha := by
    rw [Derivation.add_apply]
    exact Ideal.add_mem _ (hδ a ha) (hδ' a ha)
  zero_mem' a _ := by rw [Derivation.zero_apply]; exact Ideal.zero_mem _
  smul_mem' c δ hδ a ha := by
    rw [Derivation.smul_apply, smul_eq_mul]
    exact Ideal.mul_mem_left _ _ (hδ a ha)

theorem mem_preserving {J : Ideal A} {δ : Derivation k A A} :
    δ ∈ preserving k J ↔ δ.PreservesIdeal J := Iff.rfl

end Derivation

namespace Ideal

variable (k : Type*) {A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- The **logarithmic derivative ideal** `D(−log J)(I)` of [Kol07, 87], generated by `I` and the
`δ f` for the `k`-derivations `δ` preserving `J` and `f ∈ I`. -/
def logDerivative (J I : Ideal A) : Ideal A :=
  I ⊔ ⨆ (δ : Derivation k A A) (_ : δ.PreservesIdeal J), Ideal.span (δ '' (I : Set A))

/-- `D^r(−log J)(I)` ([Kol07, 87]). -/
def logDerivativeIter (J : Ideal A) (r : ℕ) (I : Ideal A) : Ideal A :=
  (logDerivative k J)^[r] I

variable {k}

theorem le_logDerivative (J I : Ideal A) : I ≤ logDerivative k J I := le_sup_left

theorem derivation_apply_mem_logDerivative {J : Ideal A} {δ : Derivation k A A}
    (hδ : δ.PreservesIdeal J) {I : Ideal A} {f : A} (hf : f ∈ I) : δ f ∈ logDerivative k J I :=
  le_sup_right (a := I) (Ideal.mem_iSup_of_mem δ (Ideal.mem_iSup_of_mem hδ
    (Ideal.subset_span ⟨f, hf, rfl⟩)))

theorem logDerivative_le_iff {J I K : Ideal A} :
    logDerivative k J I ≤ K ↔
      I ≤ K ∧ ∀ δ : Derivation k A A, δ.PreservesIdeal J → ∀ f ∈ I, δ f ∈ K := by
  simp only [logDerivative, sup_le_iff, iSup_le_iff, Ideal.span_le]
  constructor
  · rintro ⟨h1, h2⟩
    exact ⟨h1, fun δ hδ f hf => h2 δ hδ ⟨f, hf, rfl⟩⟩
  · rintro ⟨h1, h2⟩
    refine ⟨h1, fun δ hδ => ?_⟩
    rintro _ ⟨f, hf, rfl⟩
    exact h2 δ hδ f hf

theorem logDerivative_mono {J I I' : Ideal A} (h : I ≤ I') :
    logDerivative k J I ≤ logDerivative k J I' :=
  logDerivative_le_iff.mpr ⟨h.trans (le_logDerivative J I'),
    fun _δ hδ _f hf => derivation_apply_mem_logDerivative hδ (h hf)⟩

/-- `D(−log J)(I) ⊆ D(I)`. -/
theorem logDerivative_le_derivative (J I : Ideal A) : logDerivative k J I ≤ derivative k I :=
  logDerivative_le_iff.mpr ⟨le_derivative I, fun δ _ _f hf => derivation_apply_mem_derivative δ hf⟩

/-- Away from `S` (the unit ideal) every derivation is logarithmic: `D(−log ⊤)(I) = D(I)`. -/
theorem logDerivative_top (I : Ideal A) : logDerivative k ⊤ I = derivative k I :=
  le_antisymm (logDerivative_le_derivative ⊤ I) (derivative_le_iff.mpr ⟨le_logDerivative ⊤ I,
    fun δ _f hf => derivation_apply_mem_logDerivative (Derivation.preservesIdeal_top δ) hf⟩)

@[simp] theorem logDerivativeIter_zero (J I : Ideal A) : logDerivativeIter k J 0 I = I := rfl

@[simp] theorem logDerivativeIter_succ (J : Ideal A) (r : ℕ) (I : Ideal A) :
    logDerivativeIter k J (r + 1) I = logDerivative k J (logDerivativeIter k J r I) :=
  Function.iterate_succ_apply' _ _ _

theorem le_logDerivativeIter (J : Ideal A) (r : ℕ) (I : Ideal A) :
    I ≤ logDerivativeIter k J r I := by
  induction r with
  | zero => exact le_rfl
  | succ r ih => rw [logDerivativeIter_succ]; exact ih.trans (le_logDerivative _ _)

theorem logDerivativeIter_mono (J : Ideal A) (r : ℕ) {I I' : Ideal A} (h : I ≤ I') :
    logDerivativeIter k J r I ≤ logDerivativeIter k J r I' := by
  induction r with
  | zero => exact h
  | succ r ih => rw [logDerivativeIter_succ, logDerivativeIter_succ]; exact logDerivative_mono ih

theorem logDerivativeIter_le_derivativeIter (J : Ideal A) (r : ℕ) (I : Ideal A) :
    logDerivativeIter k J r I ≤ derivativeIter k r I := by
  induction r with
  | zero => rw [logDerivativeIter_zero, derivativeIter_zero]
  | succ r ih =>
    rw [logDerivativeIter_succ, derivativeIter_succ]
    exact (logDerivative_le_derivative _ _).trans (derivative_mono ih)

end Ideal

namespace AlgebraicGeometry.Scheme.IdealSheafData

open CategoryTheory

universe u

variable {k : Type u} [Field k] {X : Scheme.{u}} (f : X ⟶ Spec (.of k))

/-- **The logarithmic derivative ideal sheaf** `D(−log S)(I)` on a scheme over `k` ([Kol07, 87]),
packaged as `derivative` of `Hironaka/Scheme/IdealSheaf/Derivative/Sheaf.lean` is: on each affine
open `U`, `D(−log S(U))(I(U))` for the `k`-algebra structure `f.sectionsAlgebra U`. -/
noncomputable def logDerivative (S I : X.IdealSheafData) : X.IdealSheafData :=
  ofIdeals fun U => letI := f.sectionsAlgebra U.1; Ideal.logDerivative k (S.ideal U) (I.ideal U)

/-- `D^r(−log S)(I)`. -/
noncomputable def logDerivativeIter (S : X.IdealSheafData) (r : ℕ) (I : X.IdealSheafData) :
    X.IdealSheafData :=
  (logDerivative f S)^[r] I

variable (S I : X.IdealSheafData)

@[simp] theorem logDerivativeIter_zero : logDerivativeIter f S 0 I = I := rfl

@[simp] theorem logDerivativeIter_succ (r : ℕ) :
    logDerivativeIter f S (r + 1) I = logDerivative f S (logDerivativeIter f S r I) :=
  Function.iterate_succ_apply' _ _ _

/-- On every affine open, `(D(−log S)(I))(U) ⊆ D(−log S(U))(I(U))` (Mathlib's
`ideal_ofIdeals_le`). -/
theorem ideal_logDerivative_le (U : X.affineOpens) :
    (logDerivative f S I).ideal U ≤
      letI := f.sectionsAlgebra U.1; Ideal.logDerivative k (S.ideal U) (I.ideal U) :=
  ideal_ofIdeals_le _ U

theorem le_logDerivative : I ≤ logDerivative f S I :=
  le_ofIdeals_iff.mpr fun U => letI := f.sectionsAlgebra U.1; Ideal.le_logDerivative _ _

theorem logDerivative_mono {I I' : X.IdealSheafData} (h : I ≤ I') :
    logDerivative f S I ≤ logDerivative f S I' :=
  ofIdeals_mono fun U => letI := f.sectionsAlgebra U.1; Ideal.logDerivative_mono (h U)

/-- `D(−log S)(I) ⊆ D(I)`. -/
theorem logDerivative_le_derivative : logDerivative f S I ≤ derivative f I :=
  ofIdeals_mono fun U => letI := f.sectionsAlgebra U.1; Ideal.logDerivative_le_derivative _ _

end AlgebraicGeometry.Scheme.IdealSheafData
