/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.Derivative

/-!
# The local cosupport lemma in stalk form

[Kol07, Lemma 74 (3)], `cosupp(I, m) = cosupp(Dʳ(I), m − r)` for `r < m`, "char. 0 only!", and
[Wlo05, Lemma 2.6.2], `supp(I, μ) = V(D^{μ−1}(I))` is closed: in a regular local `ℚ`-algebra `R`
with coordinates `c` (`RegularCoords`), for `r < m`,

  `I ⊆ 𝔪ᵐ ⟺ Dʳ(I) ⊆ 𝔪^(m−r)`, in particular `I ⊆ 𝔪ᵐ ⟺ D^{m−1}(I) ⊆ 𝔪 ⟺ D^{m−1}(I) ≠ R`,

equivalently `ord I ≥ m ⟺ D^{m−1}(I) ⊆ 𝔪`. This is `le_ord_iff_le_ord_Dpow` of
`Hironaka/Algebra/Local/Derivative.lean` (proved there through the Euler identity) read through
`le_ord_iff` of `Hironaka/Algebra/Local/Order.lean`; the module restates it in the forms the
sheaf-level cosupport transfer consumes at a stalk `𝒪_{X,x}`
(`Hironaka/Scheme/IdealSheaf/Derivative/Cosupport.lean`): the derivative ideal sheaf has, at a
stalk, Kollár's image ideal over *all* derivations, which contains the coordinate derivative `c.D`
(giving `⟹` from the lemma here) and whose members lower the `𝔪`-adic order by at most one
(`derivation_mem_pow`, giving `⟸` without coordinates).

Used by `Hironaka/Algebra/Derivative/Basic.lean` and
`Hironaka/Scheme/IdealSheaf/Derivative/Cosupport.lean`.
-/

public section

namespace IsLocalRing

open IsLocalRing

/-! ### Any derivation lowers the adic order by at most one -/

section Leibniz

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- Leibniz: a derivation maps `J^(N+1)` into `J^N` for every ideal `J` (the coordinate-free
half of the cosupport lemma). -/
theorem derivation_mem_pow (δ : Derivation k A A) (J : Ideal A) (N : ℕ) {f : A}
    (hf : f ∈ J ^ (N + 1)) : δ f ∈ J ^ N := by
  induction N generalizing f with
  | zero => simp
  | succ N ih =>
    rw [pow_succ'] at hf
    refine Submodule.mul_induction_on hf (fun a ha b hb => ?_) (fun x y hx hy => ?_)
    · rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      refine Ideal.add_mem _ ?_ (Ideal.mul_mem_right _ _ hb)
      rw [pow_succ']
      exact Ideal.mul_mem_mul ha (ih hb)
    · rw [map_add]
      exact Ideal.add_mem _ hx hy

/-- The ideal generated by the derivatives of `J^(N+1)` lies in `J^N`. -/
theorem span_image_derivation_pow_le (δ : Derivation k A A) (J : Ideal A) (N : ℕ) :
    Ideal.span (δ '' (J ^ (N + 1) : Ideal A)) ≤ J ^ N := by
  rw [Ideal.span_le]
  rintro _ ⟨f, hf, rfl⟩
  exact derivation_mem_pow δ J N hf

end Leibniz

/-! ### The cosupport lemma at a regular local ring with coordinates -/

namespace RegularCoords

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ}
  (c : RegularCoords R n) (I : Ideal R)

/-- [Kol07, Lemma 74 (3)]; [Wlo05, Lemma 2.6.2]: for `r < m`, `I ⊆ 𝔪ᵐ ⟺ Dʳ(I) ⊆ 𝔪^(m−r)`;
`le_ord_iff_le_ord_Dpow` in ideal form. -/
theorem le_maximalIdeal_pow_iff_Dpow_le {r m : ℕ} (h : r < m) :
    I ≤ maximalIdeal R ^ m ↔ c.Dpow r I ≤ maximalIdeal R ^ (m - r) := by
  rw [← le_ord_iff, ← le_ord_iff]
  exact c.le_ord_iff_le_ord_Dpow I h

/-- `I ⊆ 𝔪ᵐ ⟺ D^{m−1}(I) ⊆ 𝔪` for `m ≥ 1`. -/
theorem le_maximalIdeal_pow_iff_Dpow_le_maximalIdeal {m : ℕ} (hm : 1 ≤ m) :
    I ≤ maximalIdeal R ^ m ↔ c.Dpow (m - 1) I ≤ maximalIdeal R := by
  rw [c.le_maximalIdeal_pow_iff_Dpow_le I (Nat.sub_lt hm one_pos),
    show m - (m - 1) = 1 by omega, pow_one]

omit [Algebra ℚ R] in
/-- An ideal of a local ring is proper exactly when it lies in the maximal ideal. -/
theorem _root_.IsLocalRing.le_maximalIdeal_iff_ne_top {J : Ideal R} :
    J ≤ maximalIdeal R ↔ J ≠ ⊤ :=
  ⟨fun h htop => (maximalIdeal.isMaximal R).ne_top (top_le_iff.mp (htop ▸ h)),
    fun h => le_maximalIdeal h⟩

/-- `I ⊆ 𝔪ᵐ ⟺ D^{m−1}(I) ≠ R` for `m ≥ 1` ([Wlo05, Lemma 2.6.2],
`supp(I, μ) = V(D^{μ−1}(I))`). -/
theorem le_maximalIdeal_pow_iff_Dpow_ne_top {m : ℕ} (hm : 1 ≤ m) :
    I ≤ maximalIdeal R ^ m ↔ c.Dpow (m - 1) I ≠ ⊤ := by
  rw [c.le_maximalIdeal_pow_iff_Dpow_le_maximalIdeal I hm, le_maximalIdeal_iff_ne_top]

/-- `ord I ≥ m ⟺ D^{m−1}(I) ⊆ 𝔪` for `m ≥ 1`. -/
theorem le_ord_iff_Dpow_le_maximalIdeal {m : ℕ} (hm : 1 ≤ m) :
    (m : ℕ∞) ≤ ord I ↔ c.Dpow (m - 1) I ≤ maximalIdeal R := by
  rw [le_ord_iff]
  exact c.le_maximalIdeal_pow_iff_Dpow_le_maximalIdeal I hm

end RegularCoords

end IsLocalRing
