/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Kol07.Thm35.Disjoin
import Hironaka.Algebra.Local.Regular
import Hironaka.Resolution.Algebraic.Kol07.Thm35.Disjoin.Center
import Hironaka.Resolution.Algebraic.Kol07.Thm35.Disjoin.MeetLocus
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.BlowUp.InvertibleSheaf
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Snc.ParameterSubset
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The disjoining center is the reduced subscheme on Kollár's subset

Kollár blows up "the subset `Z_t` where `k − t` of the transforms intersect" [Kol07, 72], a closed
subset, so the blow-up center is its reduced closed subscheme. The center used here,
`disjoinCenter G (m+1) = ∏_{|s| = m+1} ∑_{i ∈ s} G_i`, has that subset as its support
(`support_disjoinCenter`); this module shows that under the standing hypotheses (members of an snc
family with no `(m+2)`-fold intersections) it is the reduced subscheme: its stalk at a point of
the meet locus is generated by part of a regular system of parameters, a prime ideal
(`isRegularLocalRing_quotient_span_image_finset`), and off the meet locus it is the unit ideal, so
it is a radical ideal sheaf, and the vanishing ideal sheaf of its support is its radical
(Mathlib's `vanishingIdeal_support`).

* `stalkIdeal_radical`: the stalk of the radical is the radical of the stalk (the stalk is a
  localization of the sections over any affine neighbourhood, and localization commutes with
  radicals).
* `disjoinCenter_eq_vanishingIdeal`: the center is the reduced subscheme on Kollár's subset.
-/

public section

universe u

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing Ideal Scheme
  Scheme.IdealSheafData

namespace Hironaka.Sequence

variable {X : Scheme.{u}}

/-- The stalk of the radical of an ideal sheaf is the radical of its stalk: the stalk is the
localization of `Γ(X, U)` at the prime of `x` for any affine `U ∋ x`
(`IsAffineOpen.isLocalization_stalk`), and localization commutes with radicals. -/
theorem stalkIdeal_radical (J : X.IdealSheafData) (x : X) :
    J.radical.stalkIdeal x = (J.stalkIdeal x).radical := by
  obtain ⟨U, hxU⟩ := IdealSheafData.exists_affineOpens_mem x
  rw [IdealSheafData.stalkIdeal_eq_map_germ J U hxU, IdealSheafData.stalkIdeal_eq_map_germ
      J.radical U hxU, IdealSheafData.radical_ideal]
  have hloc := U.2.isLocalization_stalk ⟨x, hxU⟩
  let _i := TopCat.Presheaf.algebra_section_stalk X.presheaf ⟨x, hxU⟩
  exact IsLocalization.map_radical (U.2.primeIdealOf ⟨x, hxU⟩).asIdeal.primeCompl
    (X.presheaf.stalk x) _

/-- An ideal sheaf whose stalks are all radical is radical. -/
theorem radical_eq_self_of_forall_stalkIdeal (J : X.IdealSheafData)
    (h : ∀ x, (J.stalkIdeal x).radical = J.stalkIdeal x) : J.radical = J :=
  Scheme.IdealSheafData.ext_stalkIdeal fun x => by rw [stalkIdeal_radical, h x]

/-- For members of an snc family with no `(m+2)`-fold intersections, the center at multiplicity
`m + 1` is the reduced subscheme on the meet locus: blowing it up is blowing up Kollár's subset
[Kol07, 72]. -/
theorem disjoinCenter_eq_vanishingIdeal {k : Type u} [Field k] (f : X ⟶ Spec (.of k)) [Smooth f]
    {F : DivisorFamily X} (hF : F.IsSnc) {ι : Type*} [Fintype ι] (G : ι → X.IdealSheafData)
    (hG : ∀ i, G i ∈ Set.range F.component) (m : ℕ) (hm : meetLocus G (m + 2) = ⊥) :
    disjoinCenter G (m + 1) = Scheme.IdealSheafData.vanishingIdeal (meetLocus G (m + 1)) := by
  rw [← support_disjoinCenter, IdealSheafData.vanishingIdeal_support]
  symm
  refine radical_eq_self_of_forall_stalkIdeal _ fun x => ?_
  by_cases hx : x ∈ meetLocus G (m + 1)
  · obtain ⟨n, z, hz⟩ := hF.2 x
    obtain ⟨s, hs, -, -⟩ := exists_stalkIdeal_disjoinCenter_eq_span G hG hm hx hz
    rw [hs]
    have := isRegularLocalRing_stalk f x
    have hq := isRegularLocalRing_quotient_span_image_finset hz.1.1.symm hz.1.2 s
    exact ((Ideal.Quotient.isDomain_iff_prime _).mp inferInstance).radical
  · rw [← support_disjoinCenter] at hx
    rw [IdealSheafData.stalkIdeal_eq_top_of_notMem_support _ hx, Ideal.radical_top]

end Hironaka.Sequence
