/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Kol07.Thm35.Disjoin
import Hironaka.Resolution.Algebraic.Kol07.Thm35.Disjoin.Center
import Hironaka.Resolution.Algebraic.Kol07.Thm35.Disjoin.MeetLocus
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Snc.TotalTransformSnc
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# One disjoining step kills the top multiplicity

After the blow-up `π_0 : X_1 → X_0` of `Z_0` with exceptional divisor `F^1`, the birational
transforms `(π_0)^{-1}_* E_1, …, (π_0)^{-1}_* E_k` "do not have any `k`-fold intersections"
[Kol07, 72]. At
multiplicity `m + 1`: if `m + 1` strict transforms met at a point `x'` of `B_Z X`, their originals
would meet at `x = π(x')`, so `x ∈ Z` and `x'` lies on the exceptional divisor `F = π^{-1}(Z)`,
whose stalk at `x'` is generated by a nonzerodivisor `e` (the exceptional ideal is invertible).
Kollár's coordinates `z` at `x` for the snc family make the members through `x` the hyperplanes
`z_{c(i)} = 0` and the center `(z_{c(i)} : i through x)`; the chart computation of the blow-up
writes `π^* z_{c(i)} = u_i e` with the strict transform of the member `i` having stalk `(u_i)` at
`x'` (compare [Hau14, Proposition 5.4 (7)]). All `m + 1` members through `x` have their transforms
through `x'` (there are exactly `m + 1` of them, since there are no `(m+2)`-fold intersections),
so every `u_i` lies in `𝔪_{x'}`; but `F_{x'} = π^* Z_x = (u_i e : i) ⊆ 𝔪_{x'} · (e)`, and
`e ∈ 𝔪_{x'} (e)` forces `(1 − y) e = 0` with `y ∈ 𝔪_{x'}`, impossible for a nonzerodivisor `e`.
Hence no `(m+1)`-fold intersection survives.
-/

public section

universe u

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing Ideal Scheme
  IdealSheafData Scheme.IdealSheafData

namespace Hironaka.Sequence

variable {X : Scheme.{u}}

/-- "The `(π_0)^{-1}_* E_i` do not have any `k`-fold intersections" [Kol07, 72]: after blowing up
the `(m+1)`-fold meet locus, the strict transforms of the members have no `(m+1)`-fold
intersections. -/
theorem meetLocus_strictTransform_disjoinCenter {k : Type u} [Field k] [PerfectField k]
    (f : X ⟶ Spec (.of k)) [Smooth f] {F : DivisorFamily X} (hF : F.IsSnc) {ι : Type*} [Fintype ι]
    (G : ι → X.IdealSheafData) (hG : ∀ i, G i ∈ Set.range F.component) (m : ℕ)
    (hm : meetLocus G (m + 2) = ⊥) :
    meetLocus (fun i => (G i).strictTransform (disjoinCenter G (m + 1))) (m + 1) = ⊥ := by
  classical
  set Z := disjoinCenter G (m + 1) with hZdef
  refine le_bot_iff.mp fun x' hx' => ?_
  rw [mem_meetLocus_iff] at hx'
  obtain ⟨s, hs, hxs⟩ := hx'
  -- the originals of the members through `x'` pass through `x := π x'`
  have hπ : ∀ i ∈ s, Z.blowUpπ x' ∈ (G i).support := fun i hi =>
    π_mem_support_of_mem_support_strictTransformAlong Z (G i) x' (hxs i hi)
  have hx : Z.blowUpπ x' ∈ meetLocus G (m + 1) := (mem_meetLocus_iff G _ _).mpr ⟨s, hs,
      hπ⟩
  -- so `x ∈ Z` and `x'` lies on the exceptional divisor
  have hxZ : Z.blowUpπ x' ∈ Z.support := by
    have hx' := hx
    rwa [← support_disjoinCenter] at hx'
  have hF' : x' ∈ (Z.comap Z.blowUpπ).support := by
    rw [support_comap, ← SetLike.mem_coe, Closeds.coe_preimage]
    exact hxZ
  -- exactly the members of `s` pass through `x`
  set T := (Finset.univ : Finset ι).filter (fun i => Z.blowUpπ x' ∈
      (G i).support) with hT
  have hsT : s ⊆ T := fun i hi => Finset.mem_filter.mpr ⟨Finset.mem_univ i, hπ i hi⟩
  have hTle : T.card ≤ m + 1 := by
    by_contra h
    have hx2 : Z.blowUpπ x' ∈ meetLocus G (m + 2) :=
      (mem_meetLocus_iff_le_card G _ _).mpr (by rw [← hT]; omega)
    rw [hm] at hx2
    simp only [← SetLike.mem_coe, Closeds.coe_bot, Set.mem_empty_iff_false] at hx2
  have hsT' : s = T := Finset.eq_of_subset_of_card_le hsT (hTle.trans hs.symm.le)
  -- Kollár's coordinates at `x` and the center's stalk
  obtain ⟨n, z, hz⟩ := hF.2 (Z.blowUpπ x')
  obtain ⟨S₀, hS₀, -, hS₀mem⟩ := exists_stalkIdeal_disjoinCenter_eq_span G hG hm hx hz
  -- the exceptional ideal at `x'` is generated by a nonzerodivisor `e`
  obtain ⟨e, he_nzd, he⟩ := IsInvertible.exists_mem_nonZeroDivisors_stalkIdeal_eq_span
    (blowUp.isInvertible_comap_π Z) x'
  -- the snc data of the family `F` along the center, in the shape of the chart lemmas
  have hZdata : ∀ y ∈ Z.support, ∃ (n : ℕ) (w : Fin n → X.presheaf.stalk y),
      (span (Set.range w) = maximalIdeal (X.presheaf.stalk y) ∧
        (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk y)) ∧
      (∃ c : {a : F.ι // y ∈ (F.component a).support} → Fin n, Function.Injective c ∧
        ∀ a, (F.component a.1).stalkIdeal y = span {w (c a)}) ∧
      ∃ t : Finset (Fin n), Z.stalkIdeal y = span (w '' ↑t) := by
    intro y hy
    obtain ⟨n', w, ⟨hrs, c, hcinj, hc⟩, t, ht⟩ := hasSncWith_disjoinCenter hF G hG m hm y hy
    exact ⟨n', w, hrs, ⟨c, hcinj, hc⟩, t, ht⟩
  -- every generator `π^* z_j`, `j ∈ S₀`, is `u e` with `u ∈ 𝔪_{x'}`
  have hgen : ∀ j ∈ S₀, ∃ u : Z.blowUp.presheaf.stalk x',
      Z.blowUpπ.stalkMap x' (z j) = u * e ∧
        u ∈ maximalIdeal (Z.blowUp.presheaf.stalk x') := by
    intro j hj
    obtain ⟨i, hix, hij⟩ := hS₀mem j hj
    obtain ⟨a, ha⟩ := hG i
    have hc : (F.component a).stalkIdeal (Z.blowUpπ x') = span {z j} :=
        by rw [ha]; exact hij
    obtain ⟨u, hu, hst⟩ := exists_stalkIdeal_strictTransformAlong_eq_span_of_mem f
      F.component Z hZdata a x' hF' hz.1 hS₀ hc hj he
    refine ⟨u, hu, ?_⟩
    -- the transform of the member `i` passes through `x'` since `i ∈ T = s`
    have hi : i ∈ s := hsT' ▸ Finset.mem_filter.mpr ⟨Finset.mem_univ i, hix⟩
    have hmem := (mem_support_iff_stalkIdeal_le_maximalIdeal _ x').mp (hxs i hi)
    rw [← ha] at hmem
    exact (Ideal.span_singleton_le_iff_mem _).mp (hst ▸ hmem)
  -- `F_{x'} = π^* Z_x ⊆ 𝔪_{x'} (e)`, so `e ∈ 𝔪_{x'} (e)`
  have hle : (Z.comap Z.blowUpπ).stalkIdeal x' ≤
      maximalIdeal (Z.blowUp.presheaf.stalk x') * span {e} := by
    rw [stalkIdeal_comap, hS₀, Ideal.map_span, Ideal.span_le]
    rintro w ⟨_, ⟨j, hj, rfl⟩, rfl⟩
    obtain ⟨u, hu, hu'⟩ := hgen j (Finset.mem_coe.mp hj)
    change Z.blowUpπ.stalkMap x' (z j) ∈ _
    rw [hu]
    exact Ideal.mul_mem_mul hu' (Ideal.mem_span_singleton_self e)
  have hemem : e ∈ maximalIdeal (Z.blowUp.presheaf.stalk x') * span {e} :=
    hle (he ▸ Ideal.mem_span_singleton_self e)
  obtain ⟨y, hy, hye⟩ := Ideal.mem_mul_span_singleton.mp hemem
  -- `(y - 1) e = 0` with `e` a nonzerodivisor forces `1 = y ∈ 𝔪_{x'}`
  have h1 : (y - 1) * e = 0 := by rw [sub_mul, one_mul, hye, sub_self]
  have hy1 : y - 1 = 0 := (mem_nonZeroDivisors_iff.mp he_nzd).2 _ h1
  have : (1 : Z.blowUp.presheaf.stalk x') ∈ maximalIdeal _ := by
    rw [show (1 : Z.blowUp.presheaf.stalk x') = y from (sub_eq_zero.mp hy1).symm]
    exact hy
  exact (maximalIdeal.isMaximal _).ne_top ((Ideal.eq_top_iff_one _).mpr this)

end Hironaka.Sequence
