import Verso
import VersoManual
import VersoBlueprint
import Blueprint.SchemeBlowUp
import Hironaka.Scheme.ProjectiveBundle.Defs

open Verso.Genre
open Verso.Genre.Manual
open Informal
open CategoryTheory AlgebraicGeometry Scheme

set_option verso.blueprint.autoDeps true

#doc (Manual) "Projective morphisms" =>
%%%
tag := "ch-projective"
file := "projective-morphisms"
%%%

Kollár's resolutions are projective morphisms \[Kol07, (2) and (3)\]. Mathlib has
{decl}`Proj` of a graded ring, its functoriality in the ring and sheaves of modules on a scheme with
the notion of a quasi-coherent sheaf of finite type, but no projective bundle over a base scheme and
no projective morphism. The library defines them as in EGA and the Stacks project: the projective
bundle $`\mathbf{P}(\mathcal{E}) = \operatorname{Proj}_X (\operatorname{Sym} \mathcal{E})` of a
quasi-coherent sheaf $`\mathcal{E}` is glued from $`\operatorname{Proj}` of the symmetric algebras of
its modules of sections over the affine opens, as the blow-up is glued from the affine blow-ups
({ref "ch-scheme-blow-up"}[The blow-up along an ideal sheaf]); a morphism is projective if it is a
closed immersion into such a bundle, with $`\mathcal{E}` of finite type, followed by the projection.
The resolutions of the theorems are composites of successions of blow-ups, and these are projective.

# The symmetric algebra and the projective bundle of a module

::::definition "def:symmetric_grading" (lean := "SymmetricAlgebra.grading, SymmetricAlgebra.gradedι, SymmetricAlgebra.gradedAlgebra, SymmetricAlgebra.gradingZeroEquiv, SymmetricAlgebra.algebraOfRingHom, SymmetricAlgebra.ιₛₗ, SymmetricAlgebra.gradedMap")
%%%
paperIdentity := some { label := "[Sta, Tag 01OB]", href := "https://stacks.math.columbia.edu/tag/01OB" }
%%%
Mathlib's `SymmetricAlgebra R M` is the free commutative $`R`-algebra on an $`R`-module $`M`; the
library grades it. The $`n`-th piece `SymmetricAlgebra.grading R M n` is
$`\operatorname{Sym}^n M = \iota(M)^n`, the $`n`-th power of the submodule spanned by the image of
$`M`; the lift of the inclusion of $`M` in degree one into the direct sum of the pieces
({decl}`SymmetricAlgebra.gradedι`) splits the inclusion of the direct sum, which makes it a graded
algebra ({decl}`SymmetricAlgebra.gradedAlgebra`). The degree-zero piece is $`R`
({decl}`SymmetricAlgebra.gradingZeroEquiv`).

A ring map $`\varphi \colon R \to S` and a $`\varphi`-semilinear map $`f \colon M \to N` induce the
graded ring map $`\operatorname{Sym}_R M \to \operatorname{Sym}_S N`, $`\iota m \mapsto \iota f(m)`
({decl}`SymmetricAlgebra.gradedMap`), the lift of $`m \mapsto \iota f(m)` for the $`R`-algebra
structure of $`\operatorname{Sym}_S N` along $`\varphi` ({decl}`SymmetricAlgebra.algebraOfRingHom`,
{decl}`SymmetricAlgebra.ιₛₗ`).
::::

::::definition "def:affine_projective_bundle" (lean := "AlgebraicGeometry.affineProjectiveBundle, AlgebraicGeometry.affineProjectiveBundle.π, AlgebraicGeometry.affineProjectiveBundle.map, AlgebraicGeometry.affineProjectiveBundle.mapHom")
%%%
paperIdentity := some { label := "[Sta, Tag 01OB]", href := "https://stacks.math.columbia.edu/tag/01OB" }
%%%
The *projective bundle* of an $`R`-module $`M` is
$`\mathbf{P}(M) = \operatorname{Proj}(\operatorname{Sym}_R M)` (`affineProjectiveBundle R M`),
with the structure morphism to $`\operatorname{Spec} R` induced by $`R \cong \operatorname{Sym}^0 M`
({decl}`affineProjectiveBundle.π`). For $`M = R^n` it is projective space
$`\mathbb{P}^{n-1}_R`. A ring map $`\varphi \colon R \to S` and a $`\varphi`-semilinear map
$`f \colon M \to N` whose image spans $`N` induce $`\mathbf{P}(N) \to \mathbf{P}(M)` over
$`\operatorname{Spec} \varphi` ({decl}`affineProjectiveBundle.map`, and
{decl}`affineProjectiveBundle.mapHom` for a morphism of {decl}`CommRingCat`): Mathlib's
{decl}`Proj.map` of the graded map, whose hypothesis — the irrelevant ideal of
$`\operatorname{Sym}_S N`, generated by $`\iota(N)`, lies in the ideal generated by the image of that
of $`\operatorname{Sym}_R M` — is the spanning.

When $`f` exhibits $`N` as $`S \otimes_R M`, the square of $`\mathbf{P}(N) \to \mathbf{P}(M)` over
$`\operatorname{Spec} S \to \operatorname{Spec} R` is cartesian \[Sta, Tag 01N2\]
(`affineProjectiveBundle.isPullback_map`). On the chart $`D_+(\iota x)` of $`\mathbf{P}(M)` this
is a pushout of rings: the degree-zero part $`(\operatorname{Sym} M)_{(\iota x)}` of the
localization at $`\iota x` is the free commutative $`R`-algebra on $`M` with $`x = 1`, its elements
being the fractions $`a / (\iota x)^n`, $`a \in \operatorname{Sym}^n M`
(`SymmetricAlgebra.awayLift`, `SymmetricAlgebra.isPushout_away`).
::::

# The projective bundle of a quasi-coherent sheaf

A sheaf of modules on a scheme $`X` is Mathlib's `X.Modules`, with Mathlib's notions of a
quasi-coherent sheaf (`SheafOfModules.IsQuasicoherent`) and of a sheaf of finite type
(`SheafOfModules.IsFiniteType`). For a quasi-coherent $`\mathcal{E}` the sections over a basic open
$`D(r)` of an affine open $`V` are the localization of those over $`V` at $`r` \[Sta, Tags 01I9 and 01IA\], and
for affine opens $`U \subseteq V` the sections over $`U` are the base change
$`\Gamma(X, U) \otimes_{\Gamma(X, V)} \Gamma(\mathcal{E}, V)` \[Sta, Tags 01I9 and 01IA\]
(`Scheme.Modules.isBaseChange_resₗ`): Mathlib's identification of a quasi-coherent sheaf on an
affine scheme $`\operatorname{Spec} R` with the sheaf $`\widetilde{M}` of its global sections, read
on $`X`. So the projective bundles of the modules of sections glue.

::::definition "def:projective_bundle" (lean := "AlgebraicGeometry.Scheme.Modules.restrictionMap, AlgebraicGeometry.projectiveBundleFunctor, AlgebraicGeometry.projectiveBundleNatTrans, AlgebraicGeometry.projectiveBundleGluingData, AlgebraicGeometry.Scheme.Modules.projectiveBundle, AlgebraicGeometry.Scheme.Modules.projectiveBundleπ")
%%%
paperIdentity := some { label := "[Sta, Tag 01OB]", href := "https://stacks.math.columbia.edu/tag/01OB" }
%%%
The *projective bundle* of a quasi-coherent sheaf of modules $`\mathcal{E}` on $`X` is
$`\mathbf{P}(\mathcal{E}) = \operatorname{Proj}_X (\operatorname{Sym} \mathcal{E})`
(`E.projectiveBundle`), with projection `E.projectiveBundleπ` to $`X` \[Sta, Tag 01OB\]. It is glued
by the relative gluing lemma \[Sta, Tag 01LH\] from the functor
{decl}`projectiveBundleFunctor` on the affine opens of $`X`,
$`U \mapsto \mathbf{P}(\Gamma(\mathcal{E}, U))`, whose transition maps are induced by the
restrictions $`\Gamma(\mathcal{E}, V) \to \Gamma(\mathcal{E}, U)`, semilinear along
$`\Gamma(X, V) \to \Gamma(X, U)` ({decl}`Scheme.Modules.restrictionMap`), and from the structure
morphisms $`\mathbf{P}(\Gamma(\mathcal{E}, U)) \to \operatorname{Spec} \Gamma(X, U) \cong U`
({decl}`projectiveBundleNatTrans`), whose naturality squares are pullbacks by quasi-coherence
(`projectiveBundleNatTrans_equifibered`; {decl}`projectiveBundleGluingData`).
::::

# Projective morphisms

::::definition "def:projective" (lean := "AlgebraicGeometry.IsGrothendieckProjective")
%%%
paperIdentity := some { label := "[Sta, Tag 01W8]", href := "https://stacks.math.columbia.edu/tag/01W8" }
%%%
A morphism $`f \colon X \to Y` is *projective* (`IsGrothendieckProjective f`) if $`X` is isomorphic over $`Y`
to a closed subscheme of the projective bundle $`\mathbf{P}(\mathcal{E})` of a quasi-coherent
$`\mathcal{O}_Y`-module $`\mathcal{E}` of finite type: $`f` is a closed immersion
$`X \to \mathbf{P}(\mathcal{E})` followed by the projection \[Sta, Tag 01W8\]. This is
Grothendieck's definition, and the reading of Kollár's "projective morphism". Over a base with an
ample invertible sheaf, a quasi-projective variety over a field for instance, it agrees with being a
closed subscheme of some $`\mathbb{P}^n_Y` \[Sta, Tag 087S\]; in general that condition is stronger,
while asking the condition only over the members of an open cover of $`Y`, *locally projective*, is
weaker, and Kollár's Example 28.1 is a proper, locally projective morphism that is not projective
\[Kol07, Example 28.1\].

A projective morphism is proper (`IsGrothendieckProjective.isProper`): $`\mathbf{P}(\mathcal{E}) \to Y` is
proper for $`\mathcal{E}` of finite type (as in the proof of \[Sta, Tag 01WC\]), being, over an
affine open with finitely generated sections, $`\operatorname{Proj}` of a graded algebra generated
by finitely many elements of degree one. A blow-up of a locally Noetherian scheme along an ideal sheaf $`\mathcal{I}` is
projective (`Scheme.IdealSheafData.isProjective_blowUpπ`, \[Sta, Tag 02NS\]): the surjection
$`\operatorname{Sym} \mathcal{I} \to \bigoplus_n \mathcal{I}^n`, the identity of $`\mathcal{I}` in
degree one, makes it a closed subscheme of $`\mathbf{P}(\mathcal{I})`, the ideal sheaf being a
quasi-coherent sheaf of modules of finite type. As a finite succession of blow-ups of a Noetherian
scheme is one blow-up \[Sta, Tag 080B\], its composite is projective
(`Scheme.BlowUpSequence.isProjective_composite`).
::::
