import Verso
import VersoManual
import VersoBlueprint
import Blueprint.SchemeVocabulary
import Hironaka.Scheme.BlowUp.Transform.Defs

open Verso.Genre
open Verso.Genre.Manual
open Informal
open CategoryTheory AlgebraicGeometry Scheme Scheme.IdealSheafData

set_option verso.blueprint.autoDeps true

-- The figure is a Markdown image in a Manual document; the slide-specific image warning of
-- verso-slides does not apply.
set_option verso.slides.warnOnImage false

#doc (Manual) "The blow-up along an ideal sheaf" =>
%%%
tag := "ch-scheme-blow-up"
file := "scheme-blow-up"
%%%

Every resolution and every principalization in this document is a finite succession of blow-ups
$`\pi \colon \mathrm{Bl}_Z X \to X` of a scheme $`X` along a closed subscheme $`Z`, the *centre*;
Hironaka calls $`\pi` the *monoidal transformation* with centre $`Z`. The blow-up is characterised
by a universal property: it is the least modification of $`X` along which $`Z` becomes a divisor
({ref "sec-universal"}[The universal property]). Mathlib has schemes, {decl}`Proj` of a graded ring
and gluing, but no blow-up. The library constructs the blow-up along an ideal sheaf $`I` in the
usual way: over an affine open $`U = \operatorname{Spec} R` it is $`\operatorname{Proj}` of the Rees
algebra $`\bigoplus_n I(U)^n t^n`, and these affine pieces are glued over the affine opens of $`X`
\[Sta, Tag 01OF\]; \[Hau14, Definition 4.4\]; \[Kol07, Notation 19\]. The construction lives in the
namespaces `AlgebraicGeometry` and `AlgebraicGeometry.Scheme.IdealSheafData`, and the statements use
it directly: the monoidal transformation with centre `D` is the blow-up `D.blowUp`
({bpref "def:blowup_construction"}[]).

The chapter follows the construction: the grading on the Rees algebra, the affine blow-up, the
gluing, the universal property and its consequences, the transforms of an ideal sheaf along a
blow-up, and the remaining names of the statements for a single blow-up. It ends with a worked
example, the resolution of the cusp by blow-ups of points ({ref "sec-cusp"}[Example: resolving
the cusp]).

# The Rees algebra and the affine blow-up

For an ideal $`I` of a ring $`R`, the *Rees algebra* $`R[It] = \bigoplus_{n \geq 0} I^n t^n`, a
subring of $`R[t]`, is graded by the power of $`t`, with $`R` in degree zero; for $`I = 0` it is
$`R`, and for $`I = R` it is $`R[t]`.

For a graded ring $`A = \bigoplus_{n \geq 0} A_n`, the scheme $`\operatorname{Proj} A` has as
points the homogeneous prime ideals not containing the *irrelevant ideal*
$`A_+ = \bigoplus_{n > 0} A_n`. It is covered by the charts
$`D_+(f) = \operatorname{Spec}(A_f)_0` for homogeneous $`f` of positive degree, where $`(A_f)_0` is
the degree-zero part of the localisation, and the inclusion $`A_0 \to (A_f)_0` makes it a scheme
over $`\operatorname{Spec} A_0`. The blow-up of $`\operatorname{Spec} R` along $`V(I)` is
$`\operatorname{Proj} R[It]`, over $`\operatorname{Spec} R` through the degree-zero piece. If
$`I = (f_1, \dots, f_m)`, it is covered by the charts
$`D_+(f_i t) = \operatorname{Spec} R[I / f_i]`, where $`R[I/f_i]` is the subring of $`R_{f_i}`
generated by the fractions $`f_j / f_i` (when $`f_i` is a non-zero-divisor). In such a chart the
inverse image of $`V(I)` is generated by the single element $`f_i`, because
$`f_j = (f_j / f_i) f_i`: the inverse image of the centre is a divisor, visibly. For
$`R = k[x, y]` and $`I = (x, y)` the charts are $`k[x, y/x]` and $`k[x/y, y]`, the two charts of
the plane blown up at the origin: with $`v = y/x` and $`u = x/y` the blow-up map is
$`(x, v) \mapsto (x, xv)` on the first and $`(u, y) \mapsto (uy, y)` on the second, and the
exceptional divisor is $`x = 0` in the first. Geometrically, when $`V(I)` is nowhere dense,
$`\operatorname{Proj} R[It]` is the closure in $`\operatorname{Spec} R \times \mathbb{P}^{m-1}`
of the graph of $`x \mapsto [f_1(x) : \dots : f_m(x)]`, defined off $`V(I)`; over a point of
$`V(I)` it records the limiting directions of approach. For $`I = 0` the irrelevant ideal is zero,
every prime contains it, and $`\operatorname{Proj}` is empty.

::::definition "def:rees" (lean := "reesAlgebra.grading, reesAlgebra.gradedAlgebra, reesAlgebra.gradingZeroEquiv, reesAlgebra.mapOfLe")
%%%
paperIdentity := some { label := "[Hau14, Definition 4.6]", href := "https://arxiv.org/abs/1404.1041" }
%%%
Mathlib's `reesAlgebra I` is the subalgebra $`\bigoplus_n I^n t^n` of $`R[t]`. The library
equips it with its grading: the $`n`-th piece `reesAlgebra.grading I n` consists of the monomials
$`c\, t^n` with $`c \in I^n`. The pieces multiply correctly (`gradedMonoid`) and span the algebra
as an internal direct sum (`isInternal_grading`), which makes it a graded algebra
({decl}`gradedAlgebra`), the input {decl}`Proj` needs. The degree-zero piece is $`R` itself
({decl}`gradingZeroEquiv`, with `algebraMap_mem_grading_zero`).

A ring map $`\varphi \colon R \to S` with $`\varphi(I) \subseteq J` induces a graded map of Rees
algebras ({decl}`mapOfLe`); when $`J = I S` the irrelevant ideal of the target lies in the image of
that of the source (`irrelevant_le_map_mapOfEq`), which is the hypothesis under which {decl}`Proj`
is functorial.
::::

::::definition "def:affine_blowup" (lean := "AlgebraicGeometry.affineBlowUp, AlgebraicGeometry.affineBlowUp.π, AlgebraicGeometry.affineBlowUp.mapOfEq, AlgebraicGeometry.affineBlowUp.mapHom")
%%%
paperIdentity := some { label := "[Hau14, Definition 4.7]", href := "https://arxiv.org/abs/1404.1041" }
%%%
The *affine blow-up* of $`\operatorname{Spec} R` along an ideal $`I` is
`affineBlowUp I`, $`\operatorname{Proj}` of the graded Rees algebra, with the blow-up map
`affineBlowUp.π I` to $`\operatorname{Spec} R` induced by $`R \cong (\operatorname{Rees} I)_0`.
A ring map $`\varphi` with $`\varphi(I) S = J` induces a morphism `affineBlowUp J ⟶ affineBlowUp I`
({decl}`mapOfEq`, and {decl}`mapHom` for a morphism of {decl}`CommRingCat`), lying over
$`\operatorname{Spec} \varphi`; for the restriction to a smaller affine open these are the
transition maps of the gluing. The equality $`\varphi(I) S = J`, and not just an inclusion, is
what makes the induced map of $`\operatorname{Proj}`s defined everywhere: the image of the
irrelevant ideal of $`R[It]` must generate that of $`S[Jt]` up to radical.
::::

# Gluing the affine blow-ups

For a general scheme $`X` and ideal sheaf $`\mathcal{I}`, the blow-up is
$`\operatorname{Proj}_X \bigoplus_n \mathcal{I}^n`, obtained by gluing the affine blow-ups of
$`\operatorname{Spec} \Gamma(X, U)` along $`\mathcal{I}(U)` over the affine opens $`U` of $`X` with
the *relative gluing lemma* \[Sta, Tag 01LH\], in Mathlib's form
{decl}`Scheme.Cover.RelativeGluingData`. The lemma asks that for $`U \subseteq V` the piece over
$`U` be the preimage of $`U` in the piece over $`V` (the natural transformation to the affine cover
is *equifibered*, Mathlib's {decl}`NatTrans.Equifibered`); for blow-ups this holds because blowing
up commutes with restriction to open subsets, a case of the flat pull-back of blow-ups
({ref "sec-universal"}[The universal property]).

::::definition "def:gluing" (lean := "AlgebraicGeometry.affineBlowUpFunctor, AlgebraicGeometry.affineBlowUpNatTrans, AlgebraicGeometry.relativeGluingDataOf, AlgebraicGeometry.blowUpOf, AlgebraicGeometry.blowUpOf.π")
%%%
paperIdentity := some { label := "[Sta, Tag 01LH]", href := "https://stacks.math.columbia.edu/tag/01LH" }
%%%
The affine blow-ups over the affine opens of $`X` form a functor on the poset of affine opens,
`affineBlowUpFunctor I`, $`U \mapsto` `affineBlowUp (I.ideal U)`, with a natural transformation
`affineBlowUpNatTrans I` to the diagram of the directed affine cover of $`X`. Its naturality squares
are pullbacks (`affineBlowUpNatTrans_equifibered`): the blow-up of a smaller affine open is the
restriction of the blow-up of a larger one. Given this, Mathlib's relative gluing along the directed
affine cover ({decl}`relativeGluingDataOf`) produces a scheme over $`X`, `blowUpOf I h` with map
{decl}`blowUpOf.π`. The lemma `affineOpens_isAffineOpen` restates the affineness of an affine open
in the syntactic form the gluing lemmas need.
::::

::::definition "def:blowup_construction" (lean := "AlgebraicGeometry.Scheme.IdealSheafData.blowUp, AlgebraicGeometry.Scheme.IdealSheafData.blowUpπ")
%%%
paperIdentity := some { label := "[Sta, Tag 01OF]", href := "https://stacks.math.columbia.edu/tag/01OF" }
%%%
The *blow-up of $`X` along $`I`* is `I.blowUp`, the glued scheme `blowUpOf I` applied to the
pullback property of the squares, with the blow-up map `I.blowUpπ : I.blowUp ⟶ X`
\[Sta, Tag 01OF\]; \[Hau14, Definition 4.4\]; \[Kol07, Notation 19\].

These are the names the statements use: the *monoidal transformation* of $`X` with centre the
closed subscheme of ideal sheaf $`D` is `D.blowUp`, with projection `D.blowUpπ` (Hironaka's $`f`)
\[Hir64, Ch. 0, §2\].
::::

# The universal property
%%%
tag := "sec-universal"
%%%

A morphism $`f \colon Y \to X` is *admissible* for $`Z` if the inverse image $`f^{-1}(Z)` is an
effective Cartier divisor on $`Y`: its ideal sheaf $`f^{-1}\mathcal{I}_Z \cdot \mathcal{O}_Y` is
invertible, locally generated by one non-zero-divisor ({bpref "def:invertible"}[]). The blow-up
$`\pi \colon \mathrm{Bl}_Z X \to X` is admissible for $`Z` and terminal among admissible
morphisms: every admissible $`f` factors as $`f = \pi \circ \tilde f` for a unique
$`\tilde f \colon Y \to \mathrm{Bl}_Z X` \[Sta, Tag 0806\]; it is Kollár's $`B_Z X`
\[Kol07, Notation 19\]. Being so characterised, it is unique up to unique isomorphism over $`X`,
and the following facts, which the statements rely on, follow.

- *If $`Z` is already a Cartier divisor, $`\pi` is an isomorphism.* In particular the blow-up
  with empty centre ($`\mathcal{I}_Z = \mathcal{O}_X`, the ideal sheaf `⊤`) changes nothing, and
  $`\pi` is an isomorphism over $`X \setminus Z`.
- *Blow-ups pull back.* For $`h \colon Y \to X` the blow-up of $`Y` along $`h^{-1}(Z)` maps to
  $`\mathrm{Bl}_Z X` over $`h`, and when $`h` is flat (an open immersion, or a smooth morphism)
  the square is cartesian, $`\mathrm{Bl}_{h^{-1}Z} Y = \mathrm{Bl}_Z X \times_X Y`
  \[Sta, Tag 0805\]. This is the step behind the pull-back of a succession of blow-ups
  ({bpref "def:sequence_ops"}[]), and so behind the compatibility of the functorial theorems with
  smooth morphisms ({bpref "def:commutes_smooth"}[]).
- *Blowing up a whole component deletes it.* If $`Z` contains an irreducible component of a
  reduced $`X`, then $`\mathcal{I}_Z` vanishes there and $`\mathrm{Bl}_Z X` has nothing over that
  component. Main Theorem II uses this in a degenerate case ({bpref "thm:mt2"}[]).
- *Smooth centre in smooth ambient.* If $`X` is smooth and $`Z` is smooth of codimension
  $`c \geq 2`, then $`\mathrm{Bl}_Z X` is smooth and $`E = \pi^{-1}(Z) \to Z` is the bundle of
  projective spaces $`\mathbb{P}^{c-1}` of normal directions $`\mathbb{P}(N_{Z/X})`. The
  principalization theorems blow up only such centres, and assert this of their successions
  ({bpref "def:hironaka_conditions"}[], {bpref "def:principalized_by"}[]); a resolution of a
  singular $`X` is read off from such a succession by restriction to the strict transforms of
  $`X`, whose centres need not be smooth \[Kol07, Warning 23\].

*The centre is a subscheme, not a set.* The blow-up depends on the ideal, not only on its zero
set. Blowing up the plane along $`(x, y)` gives a smooth surface. Blowing it up along $`(x^2, y)`,
which has the same zero set, gives a surface with a chart
$`\operatorname{Spec} k[x, y, u]/(yu - x^2)`, which is singular. This is why the library takes the
centre as an ideal sheaf, `D : X.IdealSheafData`, and why "the centre is smooth" is a condition on
the subscheme.

::::definition "def:blowup_lift" (lean := "AlgebraicGeometry.Scheme.IdealSheafData.blowUp.lift, AlgebraicGeometry.Scheme.Hom.blowUpMap")
%%%
paperIdentity := some { label := "[Sta, Tag 0806]", href := "https://stacks.math.columbia.edu/tag/0806" }
%%%
A morphism $`f \colon Y \to X` along which the inverse image of $`I` is invertible lifts through the
blow-up (`blowUp.exists_lift`, \[Sta, Tag 0806\]; \[Hau14, Theorem 4.18 (a)\]); {decl}`blowUp.lift`
is a lift, chosen from this existence statement. In particular, when $`I` itself is invertible the
blow-up map is an isomorphism, its inverse being the lift of the identity
(`blowUp.isIso_π_of_isInvertible`, \[Kol07, Warning 20\]); this covers the empty centre $`I = \top`.

For $`h \colon Y \to X`, the composite of the blow-up map of $`Y` along $`h^{-1}(D)` with $`h`
pulls $`D` back to an invertible ideal (`isInvertible_comap_π_comp`), so it lifts to the morphism
of blow-ups `Scheme.Hom.blowUpMap h D : (D.comap h).blowUp ⟶ D.blowUp` over $`h`
\[Kol07, Definition 30, 30.1\]; \[Sta, Tag 0805\]. This is how successions of blow-ups are pulled
back along morphisms ({bpref "def:sequence_ops"}[]).
::::

# Transforms along a blow-up

::::definition "def:transforms_along" (lean := "AlgebraicGeometry.Scheme.IdealSheafData.colon, AlgebraicGeometry.Scheme.IdealSheafData.saturate, AlgebraicGeometry.exceptionalOrderAlong, AlgebraicGeometry.Scheme.IdealSheafData.controlledTransformAlong, AlgebraicGeometry.Scheme.IdealSheafData.weakTransformAlong, AlgebraicGeometry.Scheme.IdealSheafData.strictTransformAlong")
%%%
paperIdentity := some { label := "[Hau14, Definitions 6.2 and 6.8]", href := "https://arxiv.org/abs/1404.1041" }
%%%
For a morphism $`\pi \colon B \to X`, an ideal sheaf $`E` on $`B` (the exceptional divisor, in the
application) and an ideal sheaf $`J` on $`X` with total transform $`J^* = \pi^{-1}(J)`:

- the colon ideal sheaf $`(I : K)`, the largest ideal sheaf $`L` with $`L K \le I` ({decl}`colon`),
  and the $`K`-power saturation $`\bigcup_i (I : K^i)` ({decl}`saturate`);
- the *exceptional order* ({decl}`exceptionalOrderAlong`): the largest $`m` with $`E^m` dividing
  $`J^*` \[Hir64, Ch. 0, §5, p. 142\];
- the *controlled transform* with control $`c`, $`(J^* : E^c)` ({decl}`controlledTransformAlong`,
  \[Hau14, Definition 6.8\]; \[Kol07, Definition 60\]);
- the *weak transform* ({decl}`weakTransformAlong`), the controlled transform with the exceptional
  order as control: $`J^*` divided by the largest power of $`E` dividing it;
- the *strict transform* ({decl}`strictTransformAlong`), the $`E`-saturation of $`J^*`
  \[Hau14, Definition 6.2\]; \[Sta, Tag 080D\].

The weak transform divides by one exponent for the whole exceptional divisor. For an irreducible
non-singular centre this is Hironaka's weak transform, the exponent being the order of $`J` along
the centre; see {bpref "def:transforms"}[] for the convention for a disconnected centre.
::::

# The exceptional divisor and the push-forward of a blow-up

::::definition "def:exceptional_divisor" (lean := "AlgebraicGeometry.Scheme.IdealSheafData.exceptionalDivisor, AlgebraicGeometry.Scheme.Hom.pushforwardBlowUp")
%%%
paperIdentity := some { label := "[Hir64, Ch. 0, §2]", href := "https://doi.org/10.2307/1970486" }
%%%
Along the monoidal transformation `D.blowUp` ({bpref "def:blowup_construction"}[]),
`D.exceptionalDivisor` is the inverse image ideal sheaf $`f^{-1}(D)` of the centre on the blow-up.
For a closed immersion $`j \colon Y \to X` and a centre $`Z \subseteq Y`,
`j.pushforwardBlowUp Z : Z.blowUp ⟶ (Z.map j).blowUp` is the induced closed immersion onto the
strict transform of $`Y`, the blow-up of $`X` along $`j_* Z` \[Kol07, Definition 30, 30.2 and
30.3\], a closed immersion by the instance `Scheme.instIsClosedImmersionPushforwardBlowUp`.
::::

::::definition "def:transforms" (lean := "AlgebraicGeometry.Scheme.IdealSheafData.weakTransform, AlgebraicGeometry.Scheme.IdealSheafData.strictTransform, AlgebraicGeometry.Scheme.IdealSheafData.reducedTransform")
%%%
paperIdentity := some { label := "[Hir64, Ch. 0, §5, p. 142]", href := "https://doi.org/10.2307/1970486" }
%%%
Along the monoidal transformation with centre $`D`:

- `J.weakTransform D` is Hironaka's weak transform of $`J`: for $`D` non-singular and irreducible,
  $`f^{-1}(J)` is divisible by the $`m`-th power of the ideal of $`f^{-1}(D)`, $`m` the order of
  $`J` at the generic point of $`D`, and the weak transform is the quotient;
- `Y.strictTransform D` is the strict (birational) transform of the closed subscheme $`Y`
  \[Hir64, Ch. 0, §2, pp. 129–130\]; \[Kol07, Definition 30, 30.2\];
- `E.reducedTransform D` is Hironaka's $`\mathrm{red}(f^{-1}(E) \cup f^{-1}(D))`, the reduced
  closed subscheme of the blow-up on that set of points, the next boundary in Main Theorems II and
  II(N).
::::

# Example: resolving the cusp
%%%
tag := "sec-cusp"
%%%

Take the cusp $`C = \{y^2 = x^3\}` in the plane, singular at the origin, and blow up the plane at
the origin. In the chart $`(x, v) \mapsto (x, xv)` the equation becomes $`x^2 v^2 = x^3`, that is,
$`x^2 (v^2 - x) = 0`. The factor $`x^2` is the exceptional divisor $`E_1 = \{x = 0\}`, counted
twice. What remains, $`x = v^2`, is the *strict transform* $`C_1`, the closure of the part of
$`\pi^{-1}(C)` lying off $`E_1`: a parabola, which is smooth. In the other chart,
$`(u, y) \mapsto (uy, y)`, the equation is $`y^2(1 - u^3 y) = 0` and $`C_1` does not meet $`E_1`.
Over $`\mathbb{C}` the cusp is the image of $`t \mapsto (t^2, t^3)`, and $`C_1` is its smooth
parametrising curve, with $`v = y/x = t`.

*The curve on its own.* The strict transform of $`C` is the blow-up of $`C` itself at the point
\[Sta, Tag 080E\]. So $`C_1 \to C` is a succession of one blow-up of $`C` that is a strong
resolution ({bpref "def:strong_resolution"}[], {bpref "thm:strong_resolution"}[]): $`C_1` is
smooth, the map is an isomorphism away from the cusp point, and the preimage of
$`\operatorname{Sing} C = \{0\}` is one point on a smooth curve, a simple normal crossings
divisor. Whether Kollár's resolution functor assigns exactly this blow-up to $`C` depends on his
construction; the theorems assert only these properties.

*Inside the plane.* Viewed in the plane, $`C_1` is *tangent* to $`E_1` at the origin of the chart
(the parabola $`x = v^2` touches the line $`x = 0`), in the horizontal direction, the tangent line
$`y = 0` of the cusp. Making the curve and all the exceptional curves cross normally takes two more
blow-ups of points, each computed, like the first, in local coordinates centred at the point.

![The embedded resolution of the cusp by three blow-ups of points](static/cusp-sequence.svg)

1. *Blow up the tangency point.* In the chart $`x = vw` the equation $`x^2(v^2 - x)` becomes
   $`v^3 w^2 (v - w)`: the new exceptional curve $`E_2 = \{v = 0\}` with multiplicity $`3`, the
   strict transform of $`E_1` as $`\{w = 0\}` with multiplicity $`2`, and $`C_2 = \{v = w\}`. The
   three curves meet transversally in pairs, but all three pass through one point, which is not
   normal crossings ({ref "sec-normal-crossings"}[Normal crossings]).
2. *Blow up the triple point.* In the chart $`w = vs` the equation becomes $`v^6 s^2 (1 - s)`: the
   new curve $`E_3 = \{v = 0\}` with multiplicity $`6`, the strict transform of $`E_1` at
   $`s = 0`, $`C_3` at $`s = 1`, and $`E_2` at $`s = \infty` (in the other chart). The curves
   $`E_1`, $`C_3`, $`E_2` each cross $`E_3` transversally at distinct points, and none of them meet
   each other. The total transform $`6E_3 + 3E_2 + 2E_1 + C_3` has simple normal crossings.

This embedded problem is the one the proofs solve. Kollár's proof embeds $`X` in a smooth ambient
space and principalizes the ideal of $`X` ({bpref "thm:principalization"}[]), making its pull-back
the ideal of a simple normal crossings divisor, as $`v^6 s^2 (1 - s)` is above; the resolution of
$`X` is read off from that succession, restricted to $`X` and stopped at the right moment (the
proof sketch after {bpref "thm:resolution"}[]).
