/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.CoordsOver
public import Mathlib.RingTheory.Kaehler.Basic
import Hironaka.Algebra.Order.Cosupport
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The derivative of an ideal

[Kol07, Definition 73]: on a smooth scheme over a field `k`, with `Der_X` the sheaf of derivations
`𝒪_X → 𝒪_X`, the first derivative of an ideal sheaf `I` is the ideal sheaf `D(I)` generated by all
derivatives of elements of `I`, `D(I) := im[Der_X × I → 𝒪_X]` (73.1); in terms of generators,
`D(f₁, …, f_s) = (fᵢ, ∂fᵢ/∂xⱼ)`; the higher derivatives are `D^{r+1}(I) := D(Dʳ(I))` (73.2).

This module is the affine-local layer: for a `k`-algebra `A` and an ideal `J`,
`Ideal.derivative k J := J ⊔ (δ f : δ ∈ Der_k(A, A), f ∈ J)` (so `J ⊆ D(J)` by definition; Kollár
derives it from `f = ∂(xf)/∂x − x ∂f/∂x`) and its iterates `Ideal.derivativeIter k r J`. Proved
here: the universal property `derivative_le_iff`; a derivation lowers the `N`-adic order by at
most one, `J ⊆ N^{a+1} ⇒ D(J) ⊆ Nᵃ` (`derivative_le_pow`, `derivativeIter_le_pow`); `D` commutes
with sums (a derivation is additive) and `Dʳ Dˢ = D^{r+s}` ([Kol07, Lemma 74 (1)]); the product
rule `D(JK) ⊆ D(J) K + J D(K)` and `Dʳ(JK) ⊆ ∑ᵢ Dⁱ(J) D^{r−i}(K)` ([Kol07, Lemma 74 (2)]);
Kollár's description by generators when the derivations `der i` generate `Der_k(A, A)`
(`derivative_span_eq_of_span`), which holds for the dual derivations of a basis of `Ω_{A/k}`
(`derivation_mem_span_range_dualBasis`, through Mathlib's `Der_k(A, A) ≅ Hom_A(Ω_{A/k}, A)`); and,
for a regular local `ℚ`-algebra with coordinates (`RegularCoords`) whose coordinate derivations
are `k`-linear and span the `k`-derivations (`Hironaka/Algebra/Local/CoordsOver.lean`), the
identification of Kollár's ideal with the coordinate derivative `c.D` of
`Hironaka/Algebra/Local/Derivative.lean` (`derivative_eq_D`, `derivativeIter_eq_Dpow`; the inclusion
`c.D J ≤ D(J)` needs only `k`-linearity, `D_le_derivative`).

The sheaf `D(I)` is `Hironaka/Scheme/IdealSheaf/Derivative/Sheaf.lean` and the logarithmic version
`Hironaka/Scheme/IdealSheaf/Derivative/Logarithmic.lean`. Used throughout `Hironaka/Derivative`,
`Hironaka/Sequence`, `Hironaka/MaximalContact`, `Hironaka/Tuning` and `Hironaka/Balanced`, for the
blow-up chart (`Hironaka/Algebra/Local/BlowUpLiftTransform.lean`,
`Hironaka/Algebra/Local/TransformDerivMap.lean`) and for the derivative ideal sheaves on manifolds
(`Hironaka/Manifold/IdealSheaf/Deriv.lean`).
-/

@[expose] public section

namespace Ideal

variable (k : Type*) {A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- **The derivative of an ideal** ([Kol07, (73.1)]): the ideal generated by `J` and all
derivatives `δ f` of its elements under the `k`-derivations of `A`. -/
def derivative (J : Ideal A) : Ideal A :=
  J ⊔ ⨆ δ : Derivation k A A, Ideal.span (δ '' (J : Set A))

/-- **Higher derivatives** ([Kol07, (73.2)]): `D⁰(J) = J`, `D^{r+1}(J) = D(Dʳ(J))`. -/
def derivativeIter (r : ℕ) (J : Ideal A) : Ideal A :=
  (derivative k)^[r] J

variable {k}

/-- `J ⊆ D(J)`: by definition here; Kollár's `f = ∂(xf)/∂x − x ∂f/∂x` in [Kol07, Definition 73]. -/
theorem le_derivative (J : Ideal A) : J ≤ derivative k J :=
  le_sup_left

/-- `δ f ∈ D(J)` for `f ∈ J`. -/
theorem derivation_apply_mem_derivative (δ : Derivation k A A) {J : Ideal A} {f : A}
    (hf : f ∈ J) : δ f ∈ derivative k J :=
  le_sup_right (a := J) (Submodule.mem_iSup_of_mem δ (Ideal.subset_span ⟨f, hf, rfl⟩))

/-- The universal property of `D(J)`: it lies in `K` iff `J` and all derivatives of elements of
`J` do. -/
theorem derivative_le_iff {J K : Ideal A} :
    derivative k J ≤ K ↔ J ≤ K ∧ ∀ δ : Derivation k A A, ∀ f ∈ J, δ f ∈ K := by
  simp only [derivative, sup_le_iff, iSup_le_iff, Ideal.span_le]
  constructor
  · rintro ⟨h1, h2⟩
    exact ⟨h1, fun δ f hf => h2 δ ⟨f, hf, rfl⟩⟩
  · rintro ⟨h1, h2⟩
    refine ⟨h1, fun δ => ?_⟩
    rintro _ ⟨f, hf, rfl⟩
    exact h2 δ f hf

theorem derivative_mono {J K : Ideal A} (h : J ≤ K) : derivative k J ≤ derivative k K :=
  derivative_le_iff.mpr ⟨h.trans (le_derivative K),
    fun δ _f hf => derivation_apply_mem_derivative δ (h hf)⟩

@[simp] theorem derivativeIter_zero (J : Ideal A) : derivativeIter k 0 J = J := rfl

@[simp] theorem derivativeIter_succ (r : ℕ) (J : Ideal A) :
    derivativeIter k (r + 1) J = derivative k (derivativeIter k r J) :=
  Function.iterate_succ_apply' _ _ _

theorem derivativeIter_succ' (r : ℕ) (J : Ideal A) :
    derivativeIter k (r + 1) J = derivativeIter k r (derivative k J) :=
  Function.iterate_succ_apply _ _ _

theorem le_derivativeIter (r : ℕ) (J : Ideal A) : J ≤ derivativeIter k r J := by
  induction r with
  | zero => exact le_rfl
  | succ r ih => rw [derivativeIter_succ]; exact ih.trans (le_derivative _)

theorem derivativeIter_mono (r : ℕ) {J K : Ideal A} (h : J ≤ K) :
    derivativeIter k r J ≤ derivativeIter k r K := by
  induction r with
  | zero => exact h
  | succ r ih => rw [derivativeIter_succ, derivativeIter_succ]; exact derivative_mono ih

/-- Leibniz for the derivative ideal: `J ⊆ N^(a+1)` gives `D(J) ⊆ N^a` — every derivation lowers
the `N`-adic order by at most one (`IsLocalRing.derivation_mem_pow`). -/
theorem derivative_le_pow {J N : Ideal A} {a : ℕ} (h : J ≤ N ^ (a + 1)) :
    derivative k J ≤ N ^ a :=
  derivative_le_iff.mpr ⟨h.trans (Ideal.pow_le_pow_right (Nat.le_succ a)),
    fun δ _f hf => IsLocalRing.derivation_mem_pow δ N a (h hf)⟩

/-- `J ⊆ N^(a+r)` gives `Dʳ(J) ⊆ N^a` (the easy half of [Kol07, Lemma 74 (3)], for all
derivations). -/
theorem derivativeIter_le_pow {J N : Ideal A} {a r : ℕ} (h : J ≤ N ^ (a + r)) :
    derivativeIter k r J ≤ N ^ a := by
  induction r generalizing a with
  | zero => simpa using h
  | succ r ih =>
    rw [derivativeIter_succ]
    exact derivative_le_pow (ih (a := a + 1) (by rw [add_right_comm]; exact h))


/-! ### Sums and products -/

/-- `D` commutes with arbitrary sums of ideals, a `k`-derivation being additive. -/
theorem derivative_iSup {ι : Sort*} (J : ι → Ideal A) :
    derivative k (⨆ i, J i) = ⨆ i, derivative k (J i) := by
  refine le_antisymm (derivative_le_iff.mpr ⟨iSup_le fun i =>
      (le_derivative (J i)).trans (le_iSup (fun i => derivative k (J i)) i), fun δ f hf => ?_⟩)
    (iSup_le fun i => derivative_mono (le_iSup J i))
  induction hf using Submodule.iSup_induction' with
  | mem i f hf => exact Submodule.mem_iSup_of_mem i (derivation_apply_mem_derivative δ hf)
  | zero => simp
  | add f g _ _ hf hg => rw [map_add]; exact Ideal.add_mem _ hf hg

/-- `D(J + K) = D(J) + D(K)`. -/
theorem derivative_sup (J K : Ideal A) :
    derivative k (J ⊔ K) = derivative k J ⊔ derivative k K := by
  refine le_antisymm (derivative_le_iff.mpr ⟨sup_le_sup (le_derivative J) (le_derivative K), ?_⟩)
    (sup_le (derivative_mono le_sup_left) (derivative_mono le_sup_right))
  intro δ f hf
  obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp hf
  rw [map_add]
  exact Ideal.add_mem _ (Ideal.mem_sup_left (derivation_apply_mem_derivative δ ha))
    (Ideal.mem_sup_right (derivation_apply_mem_derivative δ hb))

/-- [Kol07, Lemma 74 (1)]: `Dʳ(Dˢ(J)) = D^{r+s}(J)`. -/
theorem derivativeIter_derivativeIter (r s : ℕ) (J : Ideal A) :
    derivativeIter k r (derivativeIter k s J) = derivativeIter k (r + s) J :=
  (Function.iterate_add_apply _ _ _ _).symm

/-- [Kol07, Lemma 74 (2)] for `r = 1`, for all `k`-derivations: Leibniz,
`D(JK) ⊆ D(J) K + J D(K)`. -/
theorem derivative_mul_le (J K : Ideal A) :
    derivative k (J * K) ≤ derivative k J * K ⊔ J * derivative k K := by
  refine derivative_le_iff.mpr ⟨le_sup_left.trans' (Ideal.mul_mono (le_derivative J) le_rfl), ?_⟩
  intro δ f hf
  refine Submodule.mul_induction_on hf (fun a ha b hb => ?_) (fun f g hf hg => ?_)
  · rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    exact Ideal.add_mem _
      (Ideal.mem_sup_right (Ideal.mul_mem_mul ha (derivation_apply_mem_derivative δ hb)))
      (Ideal.mem_sup_left
        (mul_comm b _ ▸ Ideal.mul_mem_mul (derivation_apply_mem_derivative δ ha) hb))
  · rw [map_add]
    exact Ideal.add_mem _ hf hg

/-- [Kol07, Lemma 74 (2)], for all `k`-derivations: the product rule
`Dʳ(JK) ⊆ ∑_{i ≤ r} Dⁱ(J) D^{r−i}(K)`, by induction on `r` from the case `r = 1`. -/
theorem derivativeIter_mul_le (r : ℕ) (J K : Ideal A) :
    derivativeIter k r (J * K) ≤
      ⨆ i ∈ Finset.range (r + 1), derivativeIter k i J * derivativeIter k (r - i) K := by
  induction r with
  | zero => exact le_iSup₂_of_le 0 (Finset.mem_range.mpr Nat.zero_lt_one) le_rfl
  | succ r ih =>
    rw [derivativeIter_succ]
    calc derivative k (derivativeIter k r (J * K))
        ≤ derivative k (⨆ i ∈ Finset.range (r + 1),
            derivativeIter k i J * derivativeIter k (r - i) K) := derivative_mono ih
      _ = ⨆ i ∈ Finset.range (r + 1),
            derivative k (derivativeIter k i J * derivativeIter k (r - i) K) := by
          rw [derivative_iSup]
          exact iSup_congr fun i => derivative_iSup _
      _ ≤ ⨆ i ∈ Finset.range (r + 1 + 1),
            derivativeIter k i J * derivativeIter k (r + 1 - i) K := by
          refine iSup₂_le fun i hi => ?_
          have hi' : i ≤ r := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
          refine (derivative_mul_le _ _).trans (sup_le ?_ ?_)
          · rw [← derivativeIter_succ, show r - i = r + 1 - (i + 1) by omega]
            exact le_iSup₂_of_le (i + 1) (Finset.mem_range.mpr (by omega)) le_rfl
          · rw [← derivativeIter_succ, show r - i + 1 = r + 1 - i by omega]
            exact le_iSup₂_of_le i (Finset.mem_range.mpr (by omega)) le_rfl

/-! ### Generators -/

section Generators

open KaehlerDifferential

/-- Kollár's description by generators, `D(f₁, …, f_s) = (fᵢ, ∂fᵢ/∂xⱼ)` ([Kol07, Definition 73]):
when the derivations `der i` generate `Der_k(A, A)` as an `A`-module, `D(⟨S⟩) = ⟨S, der i s⟩`; by
Leibniz, the derivative of an `A`-combination of the generators lies in the ideal they generate. -/
theorem derivative_span_eq_of_span {ι : Type*} (der : ι → Derivation k A A)
    (h : ∀ δ : Derivation k A A, δ ∈ Submodule.span A (Set.range der)) (S : Set A) :
    derivative k (Ideal.span S) = Ideal.span (S ∪ ⋃ i, der i '' S) := by
  refine le_antisymm (derivative_le_iff.mpr
    ⟨Ideal.span_mono Set.subset_union_left, fun δ f hf => ?_⟩) ?_
  · have hδS : ∀ s ∈ S, δ s ∈ Ideal.span (S ∪ ⋃ i, der i '' S) := by
      intro s hs
      induction h δ using Submodule.span_induction with
      | mem δ' hδ' =>
        obtain ⟨i, rfl⟩ := hδ'
        exact Ideal.subset_span (Or.inr (Set.mem_iUnion.mpr ⟨i, ⟨s, hs, rfl⟩⟩))
      | zero => simp
      | add δ₁ δ₂ _ _ h1 h2 => rw [Derivation.add_apply]; exact Ideal.add_mem _ h1 h2
      | smul a δ' _ h' => rw [Derivation.smul_apply, smul_eq_mul]; exact Ideal.mul_mem_left _ _ h'
    induction hf using Submodule.span_induction with
    | mem s hs => exact hδS s hs
    | zero => simp
    | add f g _ _ hf hg => rw [map_add]; exact Ideal.add_mem _ hf hg
    | smul a f hf' hf =>
      rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hf)
        (Ideal.mul_mem_right _ _ (Ideal.span_mono Set.subset_union_left hf'))
  · rw [Ideal.span_le]
    rintro x (hx | hx)
    · exact le_derivative _ (Ideal.subset_span hx)
    · obtain ⟨i, s, hs, rfl⟩ := Set.mem_iUnion.mp hx
      exact derivation_apply_mem_derivative (der i) (Ideal.subset_span hs)

/-- Kollár's "the derivations `∂/∂x₁, …, ∂/∂xₙ` are local generators of `Der_X`"
([Kol07, Definition 73]): for a basis `b` of `Ω_{A/k}`, the dual derivations `b.coord i ∘ d`
generate `Der_k(A, A)`; Mathlib's `linearMapEquivDerivation` identifies `Der_k(A, A)` with
`Hom_A(Ω_{A/k}, A)`, on which the `b.coord i` form the dual basis. -/
theorem derivation_mem_span_range_dualBasis {ι : Type*} [Finite ι]
    (b : Module.Basis ι A (Ω[A⁄k])) (δ : Derivation k A A) :
    δ ∈ Submodule.span A (Set.range fun i => linearMapEquivDerivation k A (b.coord i)) := by
  cases nonempty_fintype ι
  set L := linearMapEquivDerivation k A (M := A) with hL
  have hφ : L.symm δ = ∑ i, (L.symm δ) (b i) • b.coord i := by
    refine b.ext fun j => ?_
    rw [LinearMap.sum_apply]
    simp only [LinearMap.smul_apply, Module.Basis.coord_apply, Module.Basis.repr_self, smul_eq_mul]
    rw [Finset.sum_eq_single j (fun x _ hx => by rw [Finsupp.single_eq_of_ne hx, mul_zero])
      (fun h => (h (Finset.mem_univ j)).elim), Finsupp.single_eq_same, mul_one]
  have hδ : δ = ∑ i, (L.symm δ) (b i) • L (b.coord i) := by
    conv_lhs => rw [← L.apply_symm_apply δ, hφ]
    rw [map_sum]
    simp only [LinearEquiv.map_smul]
  rw [hδ]
  exact Submodule.sum_mem _ fun i _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

end Generators

/-! ### Kollár's ideal is the coordinate derivative -/

section Coords

open IsLocalRing

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] [Algebra k R] {n : ℕ}
  (c : RegularCoords R n)

/-- When the coordinate derivations of `c` are `k`-linear and span the `k`-derivations
(`IsLinearOver`, `SpansDerivations`), Kollár's ideal `D(J)` is the coordinate derivative `c.D J` of
`Hironaka/Algebra/Local/Derivative.lean` (Kollár's "the derivations `∂/∂x₁, …, ∂/∂xₙ` are local
generators of `Der_X`", [Kol07, Definition 73]). -/
theorem derivative_eq_D (hk : c.IsLinearOver k) (hs : c.SpansDerivations k) (J : Ideal R) :
    derivative k J = c.D J := by
  refine le_antisymm (derivative_le_iff.mpr ⟨c.le_D J, fun δ f hf => ?_⟩)
    (c.D_le_iff.mpr ⟨le_derivative J, fun i g hg => ?_⟩)
  · rw [hs δ f]
    exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_left _ _ (c.pderiv_mem_D hf i)
  · exact derivation_apply_mem_derivative (c.pderivOver hk i) hg

/-- The coordinate derivative `c.D J` lies in Kollár's ideal as soon as the `∂ᵢ` are `k`-linear
(they are then `k`-derivations); spanning is not needed. -/
theorem D_le_derivative (hk : c.IsLinearOver k) (J : Ideal R) : c.D J ≤ derivative k J :=
  c.D_le_iff.mpr ⟨le_derivative J, fun i _g hg =>
    derivation_apply_mem_derivative (c.pderivOver hk i) hg⟩

/-- `c.Dʳ J ≤ Dʳ(J)` for `k`-linear coordinate derivations. -/
theorem Dpow_le_derivativeIter (hk : c.IsLinearOver k) (r : ℕ) (J : Ideal R) :
    c.Dpow r J ≤ derivativeIter k r J := by
  induction r with
  | zero => exact le_rfl
  | succ r ih =>
    rw [RegularCoords.Dpow_succ, derivativeIter_succ]
    exact (c.D_mono ih).trans (D_le_derivative c hk _)

/-- The iterates: `Dʳ(J) = c.Dʳ(J)` under the same hypotheses. -/
theorem derivativeIter_eq_Dpow (hk : c.IsLinearOver k) (hs : c.SpansDerivations k) (r : ℕ)
    (J : Ideal R) : derivativeIter k r J = c.Dpow r J := by
  induction r with
  | zero => rfl
  | succ r ih => rw [derivativeIter_succ, ih, RegularCoords.Dpow_succ, derivative_eq_D c hk hs]

end Coords

end Ideal
