/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Submanifold.Defs
public import Mathlib.Geometry.Manifold.Sheaf.Basic
import Hironaka.Manifold.IdealSheaf.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The real plane, its origin, and two hypersurface ideal sheaves

The data of two examples over `ℝ`: one showing that the ideal-theoretic strict transform of a
closed subspace can be strictly larger than the closure of its part off the centre
([BM97, Example 3.16]), one showing that the simple locus of a nonempty real-analytic space can
be empty, the phenomenon Hironaka remarks on for reduced spaces ([Hir64, Introduction]). The
theorems about them are in `RealPlaneCircle` and
`RealPlaneStrictTransform`; this file builds the data:

* `realPlane`: `ℝ²` (`Fin 2 → ℝ`) as a bundled analytic manifold with its identity chart;
* `isClosedSubmanifold_origin`: the origin is a closed submanifold of codimension `2` (the
  blow-up of the plane at the origin is then `blowUp _ isClosedSubmanifold_origin`);
* `IdealSheaf.ofSectionOn`: the ideal sheaf generated by one section over an open set that is
  the whole space (`ofStalks` with the constant generator), and its stalks;
* `bm316Ideal`: the ideal sheaf of `x⁴(x−1)² + y²` ([BM97, Example 3.16]), built from the
  coordinate sections `chartSection` of the identity chart;
* `circleIdeal`: the ideal sheaf of `x² + y²`, the standard example of the phenomenon Hironaka
  remarks on [Hir64, Introduction], a reduced real-analytic space whose simple locus is not
  dense (reduced because `x² + y²` is irreducible in the ring `ℝ{x, y}` of convergent power
  series, so the quotient is a domain: `circleSpace_isReduced` of
  `HironakaExamples/Space/CircleReduced.lean`, for the analytic space of the same equation).
-/

@[expose] public section

noncomputable section

open Set TopologicalSpace Opposite CategoryTheory
open scoped Manifold ContDiff Topology

namespace Hironaka.Manifold

open _root_.Manifold

/-! ### A principal ideal sheaf from one section on the whole space -/

section OfSection

variable {X : TopCat} (𝒪 : TopCat.Sheaf CommRingCat X)

/-- The ideal sheaf generated by one section `s` over an open set `U` containing every point
(`ofStalks` with the constant family of generators; the shape of `IdealSheaf.ofGlobal`, with `U`
in place of `⊤`). -/
def _root_.Manifold.IdealSheaf.ofSectionOn (U : Opens X) (hU : ∀ x, x ∈ U) (s : 𝒪.presheaf.obj
    (op U)) :
    IdealSheaf 𝒪 :=
  IdealSheaf.ofStalks 𝒪 (fun x => Ideal.span {𝒪.presheaf.germ U x (hU x) s}) fun _ =>
    ⟨U, hU _, Unit, inferInstance, fun _ => s, fun _ _ => by rw [Set.range_const]⟩

/-- The stalk at `x` of `ofSectionOn U hU s` is generated by the germ of `s` at `x`. -/
theorem _root_.Manifold.IdealSheaf.stalkIdeal_ofSectionOn (U : Opens X) (hU : ∀ x, x ∈ U)
    (s : 𝒪.presheaf.obj (op U)) (x : X) :
    (IdealSheaf.ofSectionOn 𝒪 U hU s).stalkIdeal x = Ideal.span {𝒪.presheaf.germ U x (hU x) s} :=
  IdealSheaf.stalkIdeal_ofStalks _ _ x

end OfSection

/-! ### The real plane and its origin -/

/-- `ℝ²` as a bundled analytic manifold (the model space with its identity chart; an `abbrev` so
that the carrier is seen as `Fin 2 → ℝ`). -/
abbrev realPlane : AnalyticManifold.{0} ℝ (Fin 2 → ℝ) := ⟨Fin 2 → ℝ⟩

/-- The origin of the plane is a closed submanifold of codimension `2` — the identity chart is
adapted to it with all coordinates vanishing. -/
theorem isClosedSubmanifold_origin :
    IsClosedSubmanifold (ContinuousLinearEquiv.refl ℝ (Fin 2 → ℝ)) ({0} : Set realPlane) 2 where
  isClosed := isClosed_singleton
  exists_adaptedChart a _ :=
    ⟨chartAt (Fin 2 → ℝ) a, Function.Embedding.refl (Fin 2), mem_chart_source _ a,
      IsManifold.chart_mem_maximalAtlas a, fun x _ => by
        change x ∈ ({0} : Set (Fin 2 → ℝ)) ↔ ∀ i : Fin 2, x i = 0
        simp only [Set.mem_singleton_iff, funext_iff, Pi.zero_apply]⟩

/-- The source of the identity chart of the plane, as an open set (it is the whole plane). -/
def planeChart : Opens realPlane :=
  ⟨(chartAt (Fin 2 → ℝ) (0 : realPlane)).source, (chartAt (Fin 2 → ℝ) (0 : realPlane)).open_source⟩

theorem mem_planeChart (x : realPlane) : x ∈ planeChart := by
  change x ∈ (chartAt (Fin 2 → ℝ) (0 : realPlane)).source
  rw [chartAt_self_eq, OpenPartialHomeomorph.refl_source]
  exact Set.mem_univ x

/-- The `i`-th coordinate function of the plane as a section of the structure sheaf over the
identity chart (`chartSection`). -/
def planeCoordSection (i : Fin 2) :
    (structureSheaf ℝ (Fin 2 → ℝ) realPlane).presheaf.obj (op planeChart) :=
  chartSection (Fin 2 → ℝ) (ContinuousLinearEquiv.refl ℝ (Fin 2 → ℝ))
    (chartAt (Fin 2 → ℝ) (0 : realPlane)) (IsManifold.chart_mem_maximalAtlas (0 : realPlane)) i

/-! ### The two example hypersurfaces -/

/-- [BM97, Example 3.16]: the section `x⁴(x−1)² + y²`. -/
def bm316Section : (structureSheaf ℝ (Fin 2 → ℝ) realPlane).presheaf.obj (op planeChart) :=
  planeCoordSection 0 ^ 4 * (planeCoordSection 0 - 1) ^ 2 + planeCoordSection 1 ^ 2

/-- [BM97, Example 3.16]: the ideal sheaf of `X = V(x⁴(x−1)² + y²) ⊆ ℝ²`. -/
def bm316Ideal : AnalyticManifold.IdealSheaf realPlane :=
  IdealSheaf.ofSectionOn _ planeChart mem_planeChart bm316Section

theorem stalkIdeal_bm316Ideal (x : realPlane) :
    bm316Ideal.stalkIdeal x =
      Ideal.span {(structureSheaf ℝ (Fin 2 → ℝ) realPlane).presheaf.germ planeChart x
        (mem_planeChart x) bm316Section} :=
  IdealSheaf.stalkIdeal_ofSectionOn (structureSheaf ℝ (Fin 2 → ℝ) realPlane) planeChart
    mem_planeChart bm316Section x

/-- The section `x² + y²`, the standard example of the phenomenon Hironaka remarks on
[Hir64, Introduction]. -/
def circleSection : (structureSheaf ℝ (Fin 2 → ℝ) realPlane).presheaf.obj (op planeChart) :=
  planeCoordSection 0 ^ 2 + planeCoordSection 1 ^ 2

/-- The ideal sheaf of `X = V(x² + y²) ⊆ ℝ²`, with support the origin
(`circleIdeal_cosupport_eq_singleton`) and no simple point (`circleIdeal_regSet_eq_empty`), both
in `RealPlaneCircle`; that `X` is reduced is `circleSpace_isReduced` of
`HironakaExamples/Space/CircleReduced.lean`, for the analytic space of the same equation. -/
def circleIdeal : AnalyticManifold.IdealSheaf realPlane :=
  IdealSheaf.ofSectionOn _ planeChart mem_planeChart circleSection

theorem stalkIdeal_circleIdeal (x : realPlane) :
    circleIdeal.stalkIdeal x =
      Ideal.span {(structureSheaf ℝ (Fin 2 → ℝ) realPlane).presheaf.germ planeChart x
        (mem_planeChart x) circleSection} :=
  IdealSheaf.stalkIdeal_ofSectionOn (structureSheaf ℝ (Fin 2 → ℝ) realPlane) planeChart
    mem_planeChart circleSection x

end Hironaka.Manifold

end
