/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.Rees.Basic
import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.CategoryTheory.Category.Basic
import Mathlib.Data.Rat.Floor
import Mathlib.Data.Sym.Sym2.Init
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.Tactic.Continuity.Init
import Mathlib.Tactic.ContinuousFunctionalCalculus
import Mathlib.Tactic.NormNum.GCD
import Mathlib.Tactic.Positivity.Finset
import Mathlib.Topology.Sheaves.Init
import Hironaka.Scheme.BlowUp.Rees.DegreeZero  -- shake: keep (used only by `example`s)
import Hironaka.Scheme.BlowUp.Rees.Irrelevant  -- shake: keep (used only by `example`s)
import Mathlib.Algebra.MvPolynomial.Basic  -- shake: keep (used only by `example`s)
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Proper  -- shake: keep (used only by `example`s)

/-!
# The graded Rees algebra of `(x, y) ⊆ k[x, y]`, and the affine blow-up as `Proj`

[Hau14, Example 4.34]: for `I = (x, y) ⊆ k[x, y]` the graded Rees algebra is
`k[x, y, u, v]/(xv − yu)` with `deg x = deg y = 0`, `deg u = deg v = 1`, where `u = x t` and
`v = y t`. The `example`s of the first section check this against `reesAlgebra`: the degree-one
piece is the `k[x, y]`-module generated by `u` and `v`; degree zero is `k[x, y]` (the ring
isomorphism `reesAlgebra.gradingZeroEquiv`, and membership as the constant polynomials); and the
relation `x v = y u` holds.

The second section checks that the graded Rees algebra of an arbitrary ideal `I` of a commutative
ring `R` carries the instances Mathlib's `Proj` requires: the affine blow-up
`Proj (reesAlgebra.grading I)`, its structure map to `Spec R` through the degree-zero
identification, the chart cover indexed by `I` through `Proj.affineOpenCoverOfIrrelevantLESpan`
(the irrelevant ideal is generated by the degree-one elements `a t`, `a ∈ I`), and properness
over `Spec R` for finitely generated `I` from `reesAlgebra.finiteType_of_fg` and Mathlib's
instance `IsProper (Proj.toSpecZero 𝒜)`. Each `example` elaborating is the check.
-/

@[expose] public section

namespace Hironaka.BlowUp.Examples

open Polynomial AlgebraicGeometry

noncomputable section

section

variable (k : Type*) [Field k]

/-- The ideal `I = (x, y)` of `k[x, y]` of Hauser's Example 4.34. -/
abbrev xy : Ideal (MvPolynomial (Fin 2) k) := Ideal.span {MvPolynomial.X 0, MvPolynomial.X 1}

/-- `u = x t`, a degree-one generator. -/
def u : reesAlgebra (xy k) :=
  reesAlgebra.degreeOne (xy k) ⟨MvPolynomial.X 0, Ideal.subset_span (by simp)⟩

/-- `v = y t`, a degree-one generator. -/
def v : reesAlgebra (xy k) :=
  reesAlgebra.degreeOne (xy k) ⟨MvPolynomial.X 1, Ideal.subset_span (by simp)⟩

/-- The degree-one piece is the `k[x, y]`-module generated by `u` and `v`. -/
example : reesAlgebra.grading (xy k) 1 = Submodule.span (MvPolynomial (Fin 2) k) {u k, v k} := by
  apply le_antisymm
  · intro p hp
    obtain ⟨c, hc, hpc⟩ := reesAlgebra.mem_grading_iff_exists.mp hp
    rw [pow_one] at hc
    obtain ⟨a, b, rfl⟩ := Ideal.mem_span_pair.mp hc
    refine Submodule.mem_span_pair.mpr ⟨a, b, Subtype.ext ?_⟩
    rw [hpc]
    simp [u, v, smul_monomial]
  · rw [Submodule.span_le]
    rintro _ (rfl | rfl)
    · exact reesAlgebra.degreeOne_mem _
    · exact reesAlgebra.degreeOne_mem _

/-- Degree zero is `k[x, y]`. -/
example : reesAlgebra.grading (xy k) 0 ≃+* MvPolynomial (Fin 2) k :=
  reesAlgebra.gradingZeroEquiv _

/-- Degree zero consists of the constants `r · t⁰`, `r ∈ k[x, y]`. -/
example (p : reesAlgebra (xy k)) :
    p ∈ reesAlgebra.grading (xy k) 0 ↔
      ∃ r : MvPolynomial (Fin 2) k, (p : (MvPolynomial (Fin 2) k)[X]) = C r :=
  reesAlgebra.mem_grading_zero_iff

/-- The relation `x v = y u` of Hauser's presentation `k[x, y, u, v]/(xv − yu)`. -/
example : (MvPolynomial.X 0 : MvPolynomial (Fin 2) k) • v k =
    (MvPolynomial.X 1 : MvPolynomial (Fin 2) k) • u k :=
  Subtype.ext (by simp [u, v, smul_monomial, mul_comm])

end

section DryRun

open AlgebraicGeometry CategoryTheory

universe u

variable {R : Type u} [CommRing R] (I : Ideal R)

/-- The affine blow-up of `Spec R` along `I` is `Proj` of the graded Rees algebra. -/
example : Scheme := Proj (reesAlgebra.grading I)

/-- The structure map `Proj (grading I) ⟶ Spec (grading I 0) ⟶ Spec R`, the second arrow being
`Spec.map` of the ring isomorphism `R ≅ grading I 0`. -/
example : Proj (reesAlgebra.grading I) ⟶ Spec (.of R) :=
  Proj.toSpecZero (reesAlgebra.grading I) ≫
    Spec.map (CommRingCat.ofHom (reesAlgebra.gradingZeroEquiv I).symm.toRingHom)

/-- The affine open cover of the affine blow-up by the charts `D₊(a t)`, `a ∈ I`: the irrelevant
ideal is generated by the degree-one elements. -/
example : (Proj (reesAlgebra.grading I)).AffineOpenCover :=
  Proj.affineOpenCoverOfIrrelevantLESpan (reesAlgebra.grading I) (reesAlgebra.degreeOne I)
    (m := fun _ => 1) (fun a => reesAlgebra.degreeOne_mem a) (fun _ => one_pos)
    (reesAlgebra.irrelevant_le_span_degreeOne I)

/-- Properness of the affine blow-up over `Spec (grading I 0)` for finitely generated `I`: the
Rees algebra is then of finite type over its degree-zero part, and Mathlib's instance applies. -/
example (hI : I.FG) : IsProper (Proj.toSpecZero (reesAlgebra.grading I)) :=
  have := reesAlgebra.finiteType_of_fg I hI
  inferInstance

end DryRun

end

end Hironaka.BlowUp.Examples
