/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.Algebra.MvPolynomial.Eval
public import Mathlib.RingTheory.Derivation.Basic
public import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Algebra.Polynomial.Div
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Data.Nat.Totient
import Mathlib.Data.Rat.Floor
import Mathlib.Data.Sym.Sym2.Init
import Mathlib.Tactic.Continuity.Init
import Mathlib.Tactic.ContinuousFunctionalCalculus
import Mathlib.Tactic.NormNum.GCD
import Mathlib.Tactic.Positivity.Finset

/-!
# A counterexample to the formula (88.2) in Kollár's proof of Theorem 88

The proof of [Kol07, Theorem 88] rewrites the derivatives of a birational transform through the
displayed formula (88.2), which rests on the identity
`∂_{y_1}^j π_*^{-1}(I, m) = π_*^{-1}(∂_{x_1}^j I, m − j)` for the chart coordinate `y_1`. Read for
ideals, with `⟨∂^j J⟩` the ideal generated by the `j`-th partial derivatives of all elements of
`J`, the equality is false, and so is the inclusion
`⟨∂_{y_1}^j π_*^{-1}(I, m)⟩ ⊆ π_*^{-1}(D^j I, m − j)`. This file records the counterexample at
`m = 1`; the conclusion (88.1) of the theorem is not affected in this example, where both sides of
(88.1) are the unit ideal (not checked here).

What this library proves of Theorem 88 is its conclusion (88.1) under Kollár's hypotheses: for one
blow-up in `Hironaka/Resolution/Algebraic/Kol07/Theorem88BlowUp.lean`
(`derivativeIter_markedTransform_eq_iSup`) and along a smooth blow-up sequence of order `≥ m` in
`Hironaka/Resolution/Algebraic/Kol07/Theorem88Sequence.lean`
(`derivativeIter_markedTransformSeq_eq_iSup`), with [Kol07, Corollary 89] in
`Hironaka/Resolution/Algebraic/Kol07/Corollary89.lean`. The proof does not pass through (88.2): it
computes on generators in the chart (`Hironaka/Algebra/Local/TransformDerivIter.lean`,
`Hironaka/Algebra/Local/TransformDerivNormalForm.lean`,
`Hironaka/Algebra/Local/ChartLogDerivations.lean`) with the supporting modules
`Hironaka/Scheme/IdealSheaf/Derivative/FlagCoords.lean`,
`Hironaka/Scheme/IdealSheaf/Derivative/DualSpans.lean` and `Hironaka/Scheme/IdealSheaf/StalkLe.lean`
(flag coordinates, bases of derivations, and the stalk comparison for the sum over `j ≤ s`).

`R = k[x_0, x_1, t]`, `Z = (x_0, x_1)`, `S = (x_0)`, `I = (x_1² + t² x_1)` (`ord_Z I = 1`), the
chart of `x_1` (`x_0 = x_1 y_0`, chart ring `R' = k[y_0, x_1, t]`): `J = π_*^{-1}(I, 1) = (g)` with
`g = x_1 + t²`, and `π_*^{-1}(D I, 0) = (D I) R' = (x_1 g, 2 x_1 + t², t x_1) =: J_1`.

* In characteristic zero the ideal of all first partials contains the ideal itself:
  `u = ∂(y u) − y ∂u` for a derivation with `∂ y = 1` (`mem_of_pderiv_eq_one`). So the all-element
  inclusion `⟨∂_{y_0} J⟩ ⊆ J_1` would force `J ⊆ J_1`, i.e. `g ∈ J_1`.
* `g ∉ J_1` (`transformElem_not_mem`): the `k`-algebra map `R' → k[t]/(t³)`, `y_0 ↦ 0`,
  `x_1 ↦ −t²/2`, `t ↦ t`, kills the three generators of `J_1` and sends `g` to `t²/2 ≠ 0`.

Hence `⟨∂_{y_0} J⟩ ⊄ J_1`, and a fortiori `⟨∂_{y_0} J⟩ ≠ J_1`: both readings of (88.2) fail. The
example is stated in the polynomial chart ring over `ℚ`; the localization at a point of the chart
does not restore the inclusion (the test map factors through the local ring at the origin).
-/

@[expose] public section

namespace Hironaka.Examples.Theorem88

open Polynomial

/-- In characteristic zero (any ring) the ideal of the partials of all elements of an ideal contains
the ideal: `u = D(y u) − y D u` when `D y = 1`. -/
theorem mem_of_pderiv_eq_one {B : Type*} [CommRing B] [Algebra ℚ B] (D : Derivation ℚ B B)
    {y : B} (hy : D y = 1) (u : B) : u = D (y * u) - y * D u := by
  rw [Derivation.leibniz, hy, smul_eq_mul, smul_eq_mul, mul_one]
  ring

/-- The chart ring `k[y_0, x_1, t]` of the chart of `x_1`. -/
abbrev ChartPoly : Type := MvPolynomial (Fin 3) ℚ

/-- `k[t]/(t³)`. -/
abbrev TruncPoly : Type := ℚ[X] ⧸ Ideal.span ({(X : ℚ[X]) ^ 3} : Set ℚ[X])

/-- `c = −1/2` as a constant polynomial. -/
noncomputable abbrev c : ℚ[X] := C (-(1 / 2 : ℚ))

/-- The test map `y_0 ↦ 0`, `x_1 ↦ −t²/2`, `t ↦ t`. -/
noncomputable def φ : ChartPoly →ₐ[ℚ] TruncPoly :=
  MvPolynomial.aeval ![0, Ideal.Quotient.mk _ (c * X ^ 2), Ideal.Quotient.mk _ X]

theorem φ_X1 : φ (MvPolynomial.X 1) = Ideal.Quotient.mk _ (c * X ^ 2) := by
  simp [φ]

theorem φ_X2 : φ (MvPolynomial.X 2) = Ideal.Quotient.mk _ X := by
  simp [φ]

/-- The generators of `J_1 = (x_1 g, 2 x_1 + t², t x_1)` are killed by the test map. -/
theorem span_le_ker :
    Ideal.span {MvPolynomial.X 1 * (MvPolynomial.X 1 + MvPolynomial.X 2 ^ 2),
        2 * MvPolynomial.X 1 + MvPolynomial.X 2 ^ 2, MvPolynomial.X 2 * MvPolynomial.X 1} ≤
      RingHom.ker (φ : ChartPoly →+* TruncPoly) := by
  rw [Ideal.span_le]
  rintro p (rfl | rfl | rfl)
  · rw [SetLike.mem_coe, RingHom.mem_ker, AlgHom.coe_toRingHom, map_mul, map_add, map_pow, φ_X1,
      φ_X2, ← map_pow, ← map_add, ← map_mul, Ideal.Quotient.eq_zero_iff_mem,
      Ideal.mem_span_singleton]
    exact Dvd.intro ((c * c + c) * X) (by ring)
  · rw [SetLike.mem_coe, RingHom.mem_ker, AlgHom.coe_toRingHom, map_add, map_mul, map_pow, φ_X1,
      φ_X2, ← map_pow, map_ofNat, ← map_ofNat (Ideal.Quotient.mk _), ← map_mul, ← map_add,
      Ideal.Quotient.eq_zero_iff_mem]
    have h0 : (2 : ℚ[X]) * (c * X ^ 2) + X ^ 2 = 0 := by
      rw [show (2 : ℚ[X]) = C 2 from (map_ofNat C 2).symm, ← mul_assoc, ← C_mul]
      rw [show C (2 * -(1 / 2 : ℚ)) = -C 1 by rw [← C_neg]; norm_num]
      rw [C_1]
      ring
    rw [h0]
    exact zero_mem _
  · rw [SetLike.mem_coe, RingHom.mem_ker, AlgHom.coe_toRingHom, map_mul, φ_X1, φ_X2, ← map_mul,
      Ideal.Quotient.eq_zero_iff_mem, Ideal.mem_span_singleton]
    exact Dvd.intro c (by ring)

/-- The transformed generator `g = π_*^{-1}(x_1² + t² x_1, 1) = x_1 + t²` does not lie in
`π_*^{-1}(D I, 0) = (x_1 g, 2 x_1 + t², t x_1)`. -/
theorem transformElem_not_mem :
    (MvPolynomial.X 1 + MvPolynomial.X 2 ^ 2 : ChartPoly) ∉
      Ideal.span {MvPolynomial.X 1 * (MvPolynomial.X 1 + MvPolynomial.X 2 ^ 2),
        2 * MvPolynomial.X 1 + MvPolynomial.X 2 ^ 2, MvPolynomial.X 2 * MvPolynomial.X 1} := by
  intro hg
  have h0 : φ (MvPolynomial.X 1 + MvPolynomial.X 2 ^ 2) = 0 := span_le_ker hg
  rw [map_add, map_pow, φ_X1, φ_X2, ← map_pow, ← map_add, Ideal.Quotient.eq_zero_iff_mem,
    Ideal.mem_span_singleton, X_pow_dvd_iff] at h0
  have h2 := h0 2 (by norm_num)
  rw [show c * X ^ 2 + X ^ 2 = C (-(1 / 2 : ℚ) + 1) * X ^ 2 by rw [C_add, C_1]; ring,
    coeff_C_mul_X_pow, if_pos rfl] at h2
  norm_num at h2

end Hironaka.Examples.Theorem88
