/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Balanced.Basic
import HironakaExamples.Balanced.Tuned
import Mathlib.Data.Nat.Choose.Multinomial
public import HironakaExamples.Balanced.Example11
public import HironakaExamples.Balanced.Example106
/-!
# The tuned ideal `I + D(I)²`: general properties, and Kollár's Examples 11 and 106

For an ideal `I` of a `ℚ`-algebra, the tuned ideal `I + D(I)²` has the same derivative as `I`,
`D(I + D(I)²) = D(I)`, by monotonicity of `D` and the Leibniz rule; consequently
`D(I + D(I)²)² = D(I)² ⊆ I + D(I)²`, which says that `I + D(I)²` is D-balanced with respect to `2`
and MC-invariant (the case `s = 2` of [Kol07, Proposition 99, (5) and (8)]). The three theorems of
this file state these facts in the form the examples use; they are the theorems
`Ideal.derivative_sup_derivative_sq`, `Ideal.isDBalanced_sup_derivative_sq` and
`Ideal.mcInvariant_sup_derivative_sq` of `HironakaExamples/Balanced/Tuned.lean`.

The worked instances are `HironakaExamples/Balanced/Example11.lean` and `Example106.lean`, imported
here. In `ℚ[x, y, z]` the partial derivatives of `x² + y³ − z⁶` are `2x`, `3y²`, `−6z⁵`, so
`D(I) = (x, y², z⁵)`, and `I + D(I)²` is generated by seven elements (`z¹⁰ = z⁴(z⁶ − y³) + y³z⁴`);
`x² ∈ D(I)²` but `x² ∉ I` (evaluate at `(1, 0, 1)`), so `I` itself is neither D-balanced nor
MC-invariant; both `I` and `W(I)` lie in `𝔪₀²` and contain an element outside `𝔪₀³` (two partial
derivatives and the evaluation at the origin); the common zeros of `x, y², z⁵` form the origin; and
the two restrictions `x ↦ 0`, `x ↦ −y²` send the seven generators into `(y⁴, y²z⁵, y³z⁴, z⁶ − y³)`
and hit its generators ([Kol07, Example 11]). In `ℚ[x, y, z, w]`,
`D(x³ − y², x⁴ + xz² − w³) = (x², y, z², xz, w²)`, `y² ∈ D(I)²` but `y² ∉ I` (evaluate at
`(1, 1, 0, 1)`), and the orders and the cosupport follow the same pattern ([Kol07, Example 106]).
-/

public section

open MvPolynomial

namespace Hironaka.Examples.TunedIdeal

section General

variable {A : Type*} [CommRing A] [Algebra ℚ A] (I : Ideal A)

/-- `D(I + D(I)²) = D(I)`: the form of `Ideal.derivative_sup_derivative_sq` used by the examples. -/
theorem derivative_sup_derivative_sq :
    Ideal.derivative ℚ (I ⊔ Ideal.derivative ℚ I ^ 2) = Ideal.derivative ℚ I :=
  Ideal.derivative_sup_derivative_sq I

/-- `I + D(I)²` is D-balanced with respect to `2` (`Ideal.isDBalanced_sup_derivative_sq`). -/
theorem isDBalanced_sup_derivative_sq :
    Ideal.IsDBalanced ℚ (I ⊔ Ideal.derivative ℚ I ^ 2) 2 :=
  Ideal.isDBalanced_sup_derivative_sq I

/-- `I + D(I)²` is MC-invariant with respect to `2`: `D(I + D(I)²)² ⊆ I + D(I)²`
(`Ideal.mcInvariant_sup_derivative_sq`). -/
theorem mcInvariant_sup_derivative_sq :
    Ideal.derivative ℚ (I ⊔ Ideal.derivative ℚ I ^ 2) *
        Ideal.derivative ℚ (I ⊔ Ideal.derivative ℚ I ^ 2) ≤
      I ⊔ Ideal.derivative ℚ I ^ 2 :=
  Ideal.mcInvariant_sup_derivative_sq I

end General

section ExampleEleven

open Hironaka.Examples.Example11

/-- `x = X 0` in `ℚ[x, y, z]`. -/
local notation "x" => (X 0 : MvPolynomial (Fin 3) ℚ)
/-- `y = X 1` in `ℚ[x, y, z]`. -/
local notation "y" => (X 1 : MvPolynomial (Fin 3) ℚ)
/-- `z = X 2` in `ℚ[x, y, z]`. -/
local notation "z" => (X 2 : MvPolynomial (Fin 3) ℚ)

end ExampleEleven

section ExampleOneHundredSix

open Hironaka.Examples.Example106

/-- `x = X 0` in `ℚ[x, y, z, w]`. -/
local notation "x" => (X 0 : MvPolynomial (Fin 4) ℚ)
/-- `y = X 1` in `ℚ[x, y, z, w]`. -/
local notation "y" => (X 1 : MvPolynomial (Fin 4) ℚ)
/-- `z = X 2` in `ℚ[x, y, z, w]`. -/
local notation "z" => (X 2 : MvPolynomial (Fin 4) ℚ)
/-- `w = X 3` in `ℚ[x, y, z, w]`. -/
local notation "w" => (X 3 : MvPolynomial (Fin 4) ℚ)

end ExampleOneHundredSix

end Hironaka.Examples.TunedIdeal

