/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Jacobian.Defs
public import Hironaka.Manifold.Snc.Defs
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# The Jacobian ledger

The Jacobian clause of the principalization theorem — the Jacobian ideal of the blow-down times
the pull-back of the ideal is a normal-crossings divisor [BM97, Theorem 1.10, the sentence after
it] — is proved by carrying an inductive invariant along the sequence of blow-ups, a **Jacobian
ledger**: the Jacobian determinant of the composite `Π : M_r → M`, relative to the accumulated
exceptional divisor `E_r` on `M_r`, is at every point a unit times a monomial in the coordinates of
the exceptional components through the point, `det D(x ∘ Π ∘ u⁻¹) = b(u) ∏_j u_j^{h_j}` with `b`
a unit near `u(a)`, `h_j ∈ ℕ` and `h_j > 0` only for exceptional components. The one-blow-up input
is `det = y_k^{codim − 1}` in the blow-up chart (`Hironaka/Manifold/Jacobian/BlowUp.lean`).

The definition here is stalk-level and chart-free: the Jacobian of `Π` is the principal stalk
`jacobianStalk Π x` (spanned by the Jacobian determinant in any chart pair,
`exists_stalk_jacobianStalk_eq_span_of_charts`), so the unit `b` and the chart `x` at `Π a` of the
function form are absorbed by the ideal; the coordinates `u_j` of the components of `E_r` through
`a` generate their vanishing stalks in a simple normal crossings chart
(`IsSncChartAt.mem_vanishingStalk_hyp_iff`). `JacobianLedger ψ f F exc` (the map is written `f`,
`Π` being Lean's pi-notation token) therefore says: at every `x` of the source there is a simple
normal crossings chart of `F` at `x`, and there are finitely many members of `F` through `x` with
exponents, positive only on the exceptional members `exc`, whose vanishing stalks' powers multiply
to `jacobianStalk Π x`. In such a chart the stalk is generated by the monomial `∏ u_{c j}^{h j}` —
the function form `det = b · ∏ u_j^{h_j}` is a corollary, not a second definition. The set
`exc : Set F.ι` marks the exceptional components: for the total transform along a sequence it is
the complement of the range of `originalIdx` (the strict transforms of the original members are the
non-exceptional ones, Kollár's total transform [Kol07, Definition 25]); for the empty start every
member is exceptional. The ledger is established along a blow-up sequence in
`Hironaka/Resolution/Analytic/BM97/LedgerStep.lean` and `LedgerSequence.lean`, and read off as the
Jacobian clause in `Hironaka/Resolution/Analytic/BM97/JacobianAssembly.lean`.
-/

@[expose] public section

open TopologicalSpace
open scoped Manifold ContDiff

namespace Hironaka.Manifold

open _root_.Manifold

universe u

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  (ψ : E ≃L[𝕜] (Fin n → 𝕜)) {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M']

/-- **A Jacobian ledger for `Π : M' → M` relative to the hypersurface family `F` on `M'` with
exceptional members `exc`** — at every point `x` of `M'` there is a simple normal crossings chart of
`F` at `x`, and finitely many members `s` of `F` through `x` with exponents `h`, positive only on
members of `exc`, such that the stalk of the Jacobian ideal of `Π` at `x` (`jacobianStalk`) is the
product of the powers `(vanishing stalk of the member)^{h j}`; in the chart, the monomial
`∏ u_{c j}^{h j}` in the coordinates of the members through `x` generates it. Stalk-level and
chart-free: units and the target chart are absorbed by the ideal. The inductive invariant behind
the Jacobian clause of [BM97, Theorem 1.10, the sentence after it]. -/
def JacobianLedger (f : M' → M) (F : HypersurfaceFamily M') (exc : Set F.ι) : Prop :=
  ∀ x : M',
    (∃ (φ : OpenPartialHomeomorph M' E) (cidx : {j // x ∈ F.hyp j} → Fin n),
      F.IsSncChartAt ψ φ x cidx) ∧
    ∃ (s : Finset F.ι) (h : F.ι → ℕ), (∀ j ∈ s, x ∈ F.hyp j) ∧ (∀ j ∈ s, 0 < h j → j ∈ exc) ∧
      jacobianStalk (𝕜 := 𝕜) (E := E) f x =
        ∏ j ∈ s, (vanishingStalk (𝕜 := 𝕜) (E := E) (F.hyp j) x) ^ h j

end Hironaka.Manifold
