/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Admissible
public import Hironaka.Scheme.BlowUp.Glue.BlowUp
public import Hironaka.Scheme.IdealSheaf.Defs
import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Membership
import Hironaka.Scheme.BlowUp.Glue.Global
import Hironaka.Scheme.BlowUp.Invertible
import Hironaka.Scheme.BlowUp.ProductCenter
import Hironaka.Scheme.BlowUp.Transform.StrictTransform
import Mathlib.Algebra.Order.BigOperators.Ring.Finset

/-!
# Ideal sheaves on the charts of the blow-up

For an ideal sheaf `J'` on `blowUp I` and a chart `blowUp.chart I U a : Spec Γ(X, U)[I(U)/a] ⟶
blowUp I`, the inverse image `J'.comap (chart U a)` is the ideal sheaf of a single ideal
`chartIdeal I J' U a` of the chart ring (`comap_chart_eq_specIdealSheaf`).  This module records
that dictionary and the chart forms of the ideal sheaves entering the composite of two blow-ups
(`Hironaka.Scheme.BlowUp.Composite`); the chart ideal is also the form in which strict transforms
and orders along the exceptional divisor are computed in the worked examples
(`HironakaExamples.Sequence.Remark33Model`, `HironakaExamples.OrderReduction.Example106`,
`Hironaka.Scheme.IdealSheaf.Order.ExceptionalOrder`).

* `specIdealSheaf_le_iff`, `specIdealSheaf_inj`, `specIdealSheaf_pow`, and
  `isInvertible_specIdealSheaf_span_singleton`: `specIdealSheaf` is an order embedding and a
  semiring map from ideals of `R` to ideal sheaves on `Spec R`;
* `blowUp.comap_exceptionalDivisor_chart`: on the chart of `a` the exceptional ideal is `(a)`
  (`affineBlowUp.comap_exceptionalIdeal_chart` through `blowUp.chart_eq`);
* `comap_mul_pow_chart`: `(J' * E^m).comap (chart U a) = specIdealSheaf (J'_a * (a)^m)`;
* `comap_comap_chart`: `(K.comap b).comap (chart U a) = specIdealSheaf (K(U)·Γ(X, U)[I(U)/a])`
  for any ideal sheaf `K` on `X` (`comap_comap_eq_of_chart_π` of
  `Hironaka.Scheme.BlowUp.ProductCenter` at the blow-up
  `AlgebraicGeometry.Scheme.IdealSheafData.blowUp`).
-/

@[expose] public section

namespace AlgebraicGeometry

open Scheme.IdealSheafData

open AlgebraicGeometry CategoryTheory Scheme.IdealSheafData TopologicalSpace

universe u

section Spec

variable {R : Type u} [CommRing R]

/-- On `Spec R` the ideal sheaf of `P` is contained in the ideal sheaf of `Q` iff `P ≤ Q`. -/
theorem specIdealSheaf_le_iff (P Q : Ideal R) : specIdealSheaf P ≤ specIdealSheaf Q ↔ P ≤ Q := by
  have hbij : Function.Bijective (Scheme.ΓSpecIso (.of R)).inv.hom :=
    (Scheme.ΓSpecIso (.of R)).symm.commRingCatIsoToRingEquiv.bijective
  constructor
  · intro h
    have h1 := le_def.mp h ⟨⊤, isAffineOpen_top _⟩
    rw [specIdealSheaf, specIdealSheaf, ofIdealTop_ideal_top, ofIdealTop_ideal_top] at h1
    intro p hp
    have h2 := h1 (Ideal.mem_map_of_mem _ hp)
    rwa [← Ideal.mem_comap, Ideal.comap_map_of_bijective _ hbij] at h2
  · intro h
    refine le_of_isAffine ?_
    rw [specIdealSheaf, specIdealSheaf, ofIdealTop_ideal_top, ofIdealTop_ideal_top]
    exact Ideal.map_mono h

/-- `specIdealSheaf` is injective. -/
theorem specIdealSheaf_inj {P Q : Ideal R} (h : specIdealSheaf P = specIdealSheaf Q) : P = Q :=
  le_antisymm ((specIdealSheaf_le_iff P Q).mp h.le) ((specIdealSheaf_le_iff Q P).mp h.ge)

/-- `specIdealSheaf` is multiplicative on powers. -/
theorem specIdealSheaf_pow (P : Ideal R) (m : ℕ) :
    specIdealSheaf (P ^ m) = specIdealSheaf P ^ m := by
  induction m with
  | zero =>
    rw [pow_zero, pow_zero]
    change ofIdealTop ((1 : Ideal R).map _) = _
    rw [Ideal.one_eq_top, Ideal.map_top, one_eq_top]
    exact le_antisymm le_top (le_of_isAffine (by rw [ofIdealTop_ideal_top]; exact le_top))
  | succ m ih => rw [pow_succ, specIdealSheaf_mul, ih, pow_succ]

/-- The ideal sheaf on `Spec R` of a principal ideal generated by a nonzerodivisor is invertible
(on the affine open `⊤`, transported along `ΓSpecIso`). -/
theorem isInvertible_specIdealSheaf_span_singleton {g : R} (hg : g ∈ nonZeroDivisors R) :
    (specIdealSheaf (Ideal.span {g})).IsInvertible := by
  change (ofIdealTop ((Ideal.span {g}).map _)).IsInvertible
  rw [Ideal.map_span, Set.image_singleton]
  exact isInvertible_ofIdealTop_span_singleton (map_mem_nonZeroDivisors_of_ringEquiv
    (Scheme.ΓSpecIso (.of R)).symm.commRingCatIsoToRingEquiv hg)

/-- Every ideal sheaf on `Spec R` is the ideal sheaf of its ideal of global sections. -/
theorem eq_specIdealSheaf (L : (Spec (.of R)).IdealSheafData) :
    L = specIdealSheaf ((L.ideal ⟨⊤, isAffineOpen_top _⟩).comap
      (Scheme.ΓSpecIso (.of R)).inv.hom) := by
  have hsurj : Function.Surjective (Scheme.ΓSpecIso (.of R)).inv.hom :=
    (Scheme.ΓSpecIso (.of R)).symm.commRingCatIsoToRingEquiv.surjective
  change L = ofIdealTop _
  rw [Ideal.map_comap_of_surjective _ hsurj]
  exact ((equivOfIsAffine (X := Spec (.of R))).left_inv L).symm

/-- The image of a two-generator ideal under a ring map, `f(a, b) = (f a, f b)`: Mathlib's
`Ideal.map_span` with `Set.image_pair`.  Used for the chart substitutions of the worked examples. -/
theorem _root_.Ideal.map_span_pair {A B : Type*} [Semiring A] [Semiring B] {F : Type*}
    [FunLike F A B] [RingHomClass F A B] (f : F) (a b : A) :
    (Ideal.span {a, b}).map f = Ideal.span {f a, f b} := by
  rw [Ideal.map_span, Set.image_pair]

end Spec

section Chart

variable {X : Scheme.{u}} (I : X.IdealSheafData) (J' : (blowUp I).IdealSheafData)
  (U : X.affineOpens) (a : I.ideal U)

/-- The ideal of the chart ring `Γ(X, U)[I(U)/a]` cut out by `J'` on the chart of `a`: the ideal
of `J'.comap (chart U a)` on `⊤`, transported to the chart ring. -/
noncomputable def chartIdeal : Ideal (affineBlowUpAlgebra (I.ideal U) a) :=
  ((J'.comap (blowUp.chart I U a)).ideal ⟨⊤, isAffineOpen_top _⟩).comap
    (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (I.ideal U) a))).inv.hom

theorem comap_chart_eq_specIdealSheaf :
    J'.comap (blowUp.chart I U a) = specIdealSheaf (chartIdeal I J' U a) :=
  eq_specIdealSheaf _

/-- On the chart of `a` the exceptional ideal of the blow-up is the ideal sheaf of `(a)`
(`affineBlowUp.comap_exceptionalIdeal_chart`, through `blowUp.chart_eq`). -/
theorem Scheme.IdealSheafData.blowUp.comap_exceptionalDivisor_chart :
    I.exceptionalDivisor.comap (blowUp.chart I U a) =
      specIdealSheaf (Ideal.span {algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a) a}) := by
  rw [blowUp.chart_eq, comap_comp, blowUp.comap_exceptionalDivisor_ι,
    affineBlowUp.comap_exceptionalIdeal_chart]

/-- The chart form of `J' * E^m`: on the chart of `a` it is the ideal sheaf of `J'_a * (a)^m`. -/
theorem comap_mul_pow_chart (m : ℕ) :
    (J' * I.exceptionalDivisor ^ m).comap (blowUp.chart I U a) =
      specIdealSheaf (chartIdeal I J' U a *
        Ideal.span {algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a) a} ^ m) := by
  rw [comap_mul, comap_pow, comap_chart_eq_specIdealSheaf, blowUp.comap_exceptionalDivisor_chart,
    specIdealSheaf_mul, specIdealSheaf_pow]

/-- The chart form of the inverse image of an ideal sheaf `K` on `X`: on the chart of `a`,
`(K.comap b).comap (chart U a)` is the ideal sheaf of `K(U)·Γ(X, U)[I(U)/a]`
(`comap_comap_eq_of_chart_π` of `Hironaka.Scheme.BlowUp.ProductCenter` at
`AlgebraicGeometry.Scheme.IdealSheafData.blowUp`).
-/
theorem comap_comap_chart (K : X.IdealSheafData) :
    (K.comap (blowUpπ I)).comap (blowUp.chart I U a) =
      specIdealSheaf ((K.ideal U).map (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a))) :=
  comap_comap_eq_of_chart_π I (blowUpπ I) U a (blowUp.chart I U a) (blowUp.chart_π I U a) K

end Chart

end AlgebraicGeometry
