/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Derivative.Basic
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The derivative ideal of a polynomial ideal is generated by the partial derivatives

[Kol07, Definition 73]: "`D(f₁, …, f_s) = (fᵢ, ∂fᵢ/∂xⱼ)`". On a polynomial ring `R[X_i : i ∈ σ]`
every `R`-derivation is the `R[X]`-combination `∑ δ(X_i) ∂_i` of Mathlib's partial derivatives
`MvPolynomial.pderiv` (`derivation_mem_span_range_pderiv`, by `derivation_ext`), so
`Ideal.derivative_span_eq_of_span` of `Hironaka.Derivative` gives `D(⟨S⟩) = ⟨S, ∂_i s⟩`
(`derivative_span_pderiv`). `Ideal.mem_of_C_mul_mem` divides a generator by a nonzero scalar of the
field. These are the tools of the worked examples of this directory.
-/

public section

namespace MvPolynomial

variable {σ R : Type*} [Finite σ] [CommRing R]

/-- Every `R`-derivation of `R[X_i]` into itself is `∑ᵢ δ(X_i) • ∂ᵢ` (the derivations `∂/∂x_j`
generate, [Kol07, Definition 73]). -/
theorem derivation_mem_span_range_pderiv
    (δ : Derivation R (MvPolynomial σ R) (MvPolynomial σ R)) :
    δ ∈ Submodule.span (MvPolynomial σ R) (Set.range (pderiv (R := R) (σ := σ))) := by
  classical
  have := Fintype.ofFinite σ
  rw [Submodule.mem_span_range_iff_exists_fun]
  refine ⟨fun i => δ (X i), derivation_ext fun j => ?_⟩
  rw [IsLocalRing.derivation_sum_apply]
  simp only [Derivation.smul_apply, pderiv_X, Pi.single_apply, smul_eq_mul, mul_ite, mul_one,
    mul_zero]
  rw [Finset.sum_ite_eq Finset.univ j fun i => δ (X i)]
  simp

/-- `D(⟨S⟩) = ⟨S, ∂ᵢ s : s ∈ S⟩` on a polynomial ring [Kol07, Definition 73]. -/
theorem derivative_span_pderiv (S : Set (MvPolynomial σ R)) :
    Ideal.derivative R (Ideal.span S) = Ideal.span (S ∪ ⋃ i, pderiv i '' S) :=
  Ideal.derivative_span_eq_of_span pderiv derivation_mem_span_range_pderiv S

end MvPolynomial

namespace Ideal

variable {K A : Type*} [Field K] [CommRing A] [Algebra K A]

/-- Dividing a member of an ideal by a nonzero scalar: if `q • a ∈ J` with `q ≠ 0` in the field
`K`, then `a ∈ J`. -/
theorem mem_of_algebraMap_mul_mem {J : Ideal A} {q : K} (hq : q ≠ 0) {a : A}
    (h : algebraMap K A q * a ∈ J) : a ∈ J := by
  have : a = algebraMap K A q⁻¹ * (algebraMap K A q * a) := by
    rw [← mul_assoc, ← map_mul, inv_mul_cancel₀ hq, map_one, one_mul]
  rw [this]
  exact J.mul_mem_left _ h

end Ideal

namespace MvPolynomial

variable {σ : Type*} {K : Type*} [Field K]

/-- `Ideal.mem_of_algebraMap_mul_mem` for `MvPolynomial.C`. -/
theorem mem_of_C_mul_mem {J : Ideal (MvPolynomial σ K)} {q : K} (hq : q ≠ 0)
    {a : MvPolynomial σ K} (h : C q * a ∈ J) : a ∈ J :=
  Ideal.mem_of_algebraMap_mul_mem hq (by simpa [algebraMap_eq] using h)

end MvPolynomial
