/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.Oka.Coeff
public import Hironaka.AnalyticSpace.Oka.Stalk
import Hironaka.Analytic.Oka.Lemma
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.RingTheory.MvPowerSeries.NoZeroDivisors

/-!
# The core step of Oka's theorem on the model

After the preparation theorem, the entries `F_1, …, F_p` of the row are Weierstrass polynomials at
the origin and normalized polynomials of degree `< d` at every other point of `U = V × (−r, r)`;
the row `F` then induces an `𝒪(V)`-linear map `𝒪(V)[z_n : m]^p → 𝒪(V)[z_n : m + d]` between
polynomials of bounded degree, whose kernel is finitely generated by the induction hypothesis, and
Oka's lemma turns this into the finite generation of the kernel system of `F` [Fre17, Ch. I, 10.3,
third step of the proof].

`hasLocalGeneratorsOn_polyRow` is that step. For a row `P_j = polyComb V x₀ (pc j)` of polynomial
sections of degree `< d` in the shifted coordinate over `π⁻¹ V`, with `P_0` monic of degree `e < d`
at every point of `V`: if the relations of the coefficient matrix `coeffMatSec pc (d + 3d) (3d)`
over the base are locally finitely generated on `V` (the induction hypothesis in dimension `m`),
then the relations of the row are locally finitely generated on `π⁻¹ V`. At `a ∈ π⁻¹ V`, generators
`A^{(l)}` of the base kernel near `π a` give the polynomial sections
`R^{(l)}_j = Σ_t A^{(l)}_{(j,t)} (x_0 − x₀)^t`; they are relations, by the coefficient
correspondence of `Hironaka.AnalyticSpace.Oka.Coeff`, and they generate: a relation `b` at a point
`a'` is, on the Taylor side, in the span over the convergent series of the relations of `x_0`-degree
`< 3d` (Oka's lemma, `rowKer_le_span_degLt`), each of which is `Ψ_{a'}` of a polynomial vector of
degree `< 3d` (`exists_psi_eq_of_degLt`) whose coefficient vector is a base relation, hence a
combination of the `A^{(l)}`. Every step follows Freitag's text.
-/

@[expose] public noncomputable section

open TopologicalSpace Opposite CategoryTheory Manifold
open Analytic

universe u

namespace AnalyticSpace

variable {K : Type} [RCLike K] {m : ℕ} (ψ : Kn.{u} K (m + 1) ≃L[K] (Fin (m + 1) → K))

/-- The row `j ↦ Σ_t (pc j t ∘ π) (x_0 − x₀)^t` of polynomial sections over `π⁻¹ V`. -/
def polyRow (V : Opens (Kn.{u} K m)) (x0 : K) {q d : ℕ}
    (pc : Fin q → Fin d → (sheafKn K m).presheaf.obj (op V)) :
    Fin q → (sheafKn K (m + 1)).presheaf.obj (op (baseOpens ψ V)) :=
  fun j => polyComb ψ V x0 (pc j)

theorem germ_polyRow {V : Opens (Kn.{u} K m)} {a : Kn.{u} K (m + 1)} (ha : a ∈ baseOpens ψ V)
    (x0 : K)
    {q d : ℕ} (pc : Fin q → Fin d → (sheafKn K m).presheaf.obj (op V)) (j : Fin q) :
    (sheafKn K (m + 1)).presheaf.germ (baseOpens ψ V) a ha (polyRow ψ V x0 pc j) =
      psi ψ a x0 (polyOfCoeff fun t => (sheafKn K m).presheaf.germ V (projKn ψ a) ha (pc j t)) :=
  germ_polyComb_eq_psi ψ ha x0 (pc j)

theorem baseOpens_mono {V V' : Opens (Kn.{u} K m)} (h : V' ≤ V) : baseOpens ψ V' ≤ baseOpens ψ V :=
  fun _ hy => h hy

section Linear

variable {R : Type*} [CommRing R]

/-- The relations of a row over any commutative ring (the kernel of a `1 × p` matrix, `relKer`). -/
abbrev rowKerR {p : ℕ} (G : Fin p → R) : Submodule R (Fin p → R) := relKer fun _ : Fin 1 => G

theorem mem_rowKerR_iff {p : ℕ} (G : Fin p → R) (P : Fin p → R) :
    P ∈ rowKerR G ↔ ∑ j, G j * P j = 0 := by
  rw [rowKerR, mem_relKer_iff]
  exact ⟨fun h => h 0, fun h _ => h⟩

/-- `polyOfCoeff` of a linear combination of coefficient vectors. -/
theorem polyOfCoeff_sum_mul {N k : ℕ} (lam : Fin k → R) (c : Fin k → Fin N → R) :
    polyOfCoeff (fun t => ∑ l, lam l * c l t) = ∑ l, Polynomial.C (lam l) * polyOfCoeff (c l) := by
  unfold polyOfCoeff
  simp only [map_sum, Finset.sum_mul, Finset.mul_sum]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun t _ => Finset.sum_congr rfl fun l _ => ?_
  rw [map_mul, mul_assoc]

end Linear

/-- The third step of the proof of Oka's theorem [Fre17, Ch. I, 10.3]: the relations of a row of
polynomial sections of degree `< d` (the first one monic of degree `e < d` at every point) are
locally finitely generated on `π⁻¹ V`, given that the relations of the coefficient matrix over the
base are locally finitely generated on `V`. -/
theorem hasLocalGeneratorsOn_polyRow {q d e : ℕ} (hd : 0 < d) (he : e < d) (V : Opens (Kn.{u} K m))
    (x0 : K)
    (pc : Fin (q + 1) → Fin d → (sheafKn K m).presheaf.obj (op V))
    (hmonic : ∀ b (hb : b ∈ V),
      (polyOfCoeff fun t => (sheafKn K m).presheaf.germ V b hb (pc 0 t)).Monic ∧
      (polyOfCoeff fun t => (sheafKn K m).presheaf.germ V b hb (pc 0 t)).natDegree = e)
    (hIH : HasLocalGeneratorsOn (sheafKn K m) V ((q + 1) * (3 * d)) fun b hb =>
      relationSubmodule (sheafKn K m) (coeffMatSec pc (d + 3 * d) (3 * d)) b hb) :
    HasLocalGeneratorsOn (sheafKn K (m + 1)) (baseOpens ψ V) (q + 1) fun a ha =>
      relationSubmodule (sheafKn K (m + 1)) (fun _ : Fin 1 => polyRow ψ V x0 pc) a ha := by
  have h3d : 0 < 3 * d := by omega
  intro a ha
  obtain ⟨V', hV'V, hbV', k, A, hA⟩ := hIH (projKn ψ a) ha
  refine ⟨baseOpens ψ V', baseOpens_mono ψ hV'V, hbV', k,
    fun l j => polyComb ψ V' x0 fun t => A l (finProdFinEquiv (j, t)), fun a' ha' => ?_⟩
  -- notation at the point `a'`
  have hV : a' ∈ baseOpens ψ V := baseOpens_mono ψ hV'V ha'
  have hb' : projKn ψ a' ∈ V' := ha'
  have hbV : projKn ψ a' ∈ V := hV'V hb'
  set b0 := projKn ψ a' with hb0
  -- the polynomials at the base stalk
  set Ph : Fin (q + 1) → Polynomial ((sheafKn K m).presheaf.stalk b0) :=
    fun j => polyOfCoeff fun t => (sheafKn K m).presheaf.germ V b0 hbV (pc j t) with hPh
  have hPhdeg : ∀ j, (Ph j).natDegree < d := fun j => natDegree_polyOfCoeff_lt _ hd
  -- the relation system of the row at `a'` is `rowKer (psi Ph)`
  have hrow : relationSubmodule (sheafKn K (m + 1)) (fun _ : Fin 1 => polyRow ψ V x0 pc) a' hV =
      rowKerR fun j => psi ψ a' x0 (Ph j) := by
    rw [relationSubmodule]
    congr 1
    funext _ j
    exact germ_polyRow ψ hV x0 pc j
  -- the base relation system at `b0` is the reindexed coefficient kernel, generated by the `A l`
  have hbase : relKer (coeffMat' Ph (d + 3 * d) (3 * d)) =
      Submodule.span _
        (Set.range fun l => fun i => (sheafKn K m).presheaf.germ V' b0 hb' (A l i)) := by
    rw [← hA b0 hb']
    dsimp only
    rw [relationSubmodule]
    congr 1
    funext l i
    exact (germ_coeffMatSec pc (d + 3 * d) (3 * d) hbV l i).symm
  -- the generators, as `psi` of polynomials
  have hR : ∀ l j, (sheafKn K (m + 1)).presheaf.germ (baseOpens ψ V') a' ha'
      (polyComb ψ V' x0 fun t => A l (finProdFinEquiv (j, t))) =
      psi ψ a' x0 (polyOfCoeff fun t =>
        (sheafKn K m).presheaf.germ V' b0 hb' (A l (finProdFinEquiv (j, t)))) :=
    fun l j => germ_polyComb_eq_psi ψ ha' x0 _
  have hflatA : ∀ l, flatCoeff (fun j t =>
      (sheafKn K m).presheaf.germ V' b0 hb' (A l (finProdFinEquiv (j, t)))) =
      fun i => (sheafKn K m).presheaf.germ V' b0 hb' (A l i) := by
    intro l
    funext i
    simp only [flatCoeff, Prod.mk.eta, Equiv.apply_symm_apply]
  change relationSubmodule (sheafKn K (m + 1)) (fun _ : Fin 1 => polyRow ψ V x0 pc) a' hV = _
  rw [hrow]
  apply le_antisymm
  · -- every relation is a combination of the generators: Oka's Lemma on the Taylor side
    intro bb hbb
    -- the Taylor side
    set T := taylorKn ψ a' with hT
    have hTpsi : ∀ j, (T (psi ψ a' x0 (Ph j)) : MvPowerSeries (Fin (m + 1)) K) =
        ofPoly (((Ph j).map (TKn (knCoord K m) b0)).comp
          (Polynomial.X - Polynomial.C (MvPowerSeries.C (x0 - ψ a' 0)))) := fun j => by
      rw [hT, taylorKn_apply_coe, TKn_psi]
    obtain ⟨F0, hF0def⟩ : ∃ F0 : Analytic.Conv K (m + 1), F0 = T (psi ψ a' x0 (Ph 0)) := ⟨_, rfl⟩
    obtain ⟨F, hFdef⟩ : ∃ F : Fin q → Analytic.Conv K (m + 1),
            ∀ j, F j = T (psi ψ a' x0 (Ph j.succ)) :=
      ⟨fun j => T (psi ψ a' x0 (Ph j.succ)), fun _ => rfl⟩
    have hcons : ∀ j,
        (Fin.cons F0 F : Fin (q + 1) → Analytic.Conv K (m + 1)) j = T (psi ψ a' x0 (Ph j)) := by
      intro j
      refine Fin.cases ?_ (fun j => ?_) j
      · simp [hF0def]
      · simp [hFdef]
    -- the monic entry
    have hQmonic : (((Ph 0).map (TKn (knCoord K m) b0)).comp
        (Polynomial.X - Polynomial.C (MvPowerSeries.C (x0 - ψ a' 0)))).Monic :=
      ((hmonic b0 hbV).1.map _).comp_X_sub_C _
    have hQdeg : (((Ph 0).map (TKn (knCoord K m) b0)).comp
        (Polynomial.X - Polynomial.C (MvPowerSeries.C (x0 - ψ a' 0)))).natDegree = e := by
      rw [Polynomial.natDegree_comp, Polynomial.natDegree_X_sub_C, mul_one,
        Polynomial.natDegree_map_eq_of_injective (TKn_injective (knCoord K m) b0)]
      exact (hmonic b0 hbV).2
    have hF0 : (F0 : MvPowerSeries (Fin (m + 1)) K) =
        ofPoly (((Ph 0).map (TKn (knCoord K m) b0)).comp
        (Polynomial.X - Polynomial.C (MvPowerSeries.C (x0 - ψ a' 0)))) := by
      rw [hF0def, hTpsi]
    have hF : ∀ j, DegLt d (F j : MvPowerSeries (Fin (m + 1)) K) := by
      intro j
      rw [hFdef, hTpsi]
      apply degLt_ofPoly_of_natDegree_lt
      calc (((Ph j.succ).map (TKn (knCoord K m) b0)).comp
            (Polynomial.X - Polynomial.C (MvPowerSeries.C (x0 - ψ a' 0)))).natDegree
          ≤ ((Ph j.succ).map (TKn (knCoord K m) b0)).natDegree *
            (Polynomial.X - Polynomial.C (MvPowerSeries.C (x0 - ψ a' 0))).natDegree :=
            Polynomial.natDegree_comp_le
        _ = ((Ph j.succ).map (TKn (knCoord K m) b0)).natDegree := by
            rw [Polynomial.natDegree_X_sub_C, mul_one]
        _ ≤ (Ph j.succ).natDegree := Polynomial.natDegree_map_le
        _ < d := hPhdeg _
    -- the Taylor image of `bb` is a relation of `(F0, F)`
    have hTb : (fun j => T (bb j)) ∈ rowKer (Fin.cons F0 F) := by
      rw [mem_rowKer_iff]
      have h1 := (mem_rowKerR_iff _ _).1 hbb
      have h2 := congrArg T h1
      rw [map_sum, map_zero] at h2
      rw [← h2]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [hcons, map_mul]
    have hOka := rowKer_le_span_degLt he hQmonic hQdeg F0 hF0 F hF hTb
    -- pull the span back through the Taylor isomorphism, componentwise
    have key : ∀ y (_ : y ∈ Submodule.span (Analytic.Conv K (m + 1))
            (degLtRel (3 * d) (Fin.cons F0 F))),
        (fun j => T.symm (y j)) ∈ Submodule.span ((sheafKn K (m + 1)).presheaf.stalk a')
          (Set.range fun l j => (sheafKn K (m + 1)).presheaf.germ (baseOpens ψ V') a' ha'
            (polyComb ψ V' x0 fun t => A l (finProdFinEquiv (j, t)))) := by
      intro y hy
      induction hy using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨hydeg, hyrel⟩ := hy
        -- `y` is `psi` of a polynomial vector of degree `< 3d`
        have hdeg : ∀ j, DegLt (3 * d) (TKn ψ a' (T.symm (y j))) := fun j => by
          rw [← taylorKn_apply_coe, hT, RingEquiv.apply_symm_apply]
          exact hydeg j
        choose Q hQdeg' hQ using fun j => exists_psi_eq_of_degLt ψ a' x0 h3d (T.symm (y j)) (hdeg j)
        -- the coefficient vectors are a base relation
        obtain ⟨c, hc⟩ : ∃ c : Fin (q + 1) → Fin (3 * d) → (sheafKn K m).presheaf.stalk b0,
            ∀ j, polyOfCoeff (c j) = Q j :=
          ⟨fun j t => (Q j).coeff t, fun j => polyOfCoeff_coeff (Q j) (hQdeg' j)⟩
        have hrel : ∑ j, Ph j * polyOfCoeff (c j) = 0 := by
          apply psi_injective ψ a' x0
          rw [map_sum, map_zero]
          have h1 := (mem_rowKer_iff _ _).1 hyrel
          have h2 := congrArg T.symm h1
          rw [map_sum, map_zero] at h2
          rw [← h2]
          refine Finset.sum_congr rfl fun j _ => ?_
          rw [map_mul, hcons, map_mul, hT, RingEquiv.symm_apply_apply, hc, hQ]
        rw [sum_mul_polyOfCoeff_eq_zero_iff_mem_relKer Ph hPhdeg c h3d, hbase,
          Submodule.mem_span_range_iff_exists_fun] at hrel
        obtain ⟨lam, hlam⟩ := hrel
        -- `T.symm y = Σ_l germMap (lam l) • (germ R l)`
        have hy' : (fun j => T.symm (y j)) = ∑ l, germMapProj ψ a' (lam l) •
            (fun j => (sheafKn K (m + 1)).presheaf.germ (baseOpens ψ V') a' ha'
              (polyComb ψ V' x0 fun t => A l (finProdFinEquiv (j, t))) :
                Fin (q + 1) → (sheafKn K (m + 1)).presheaf.stalk a') := by
          funext j
          rw [← hQ j, ← hc j]
          have hcj : c j = fun t => ∑ l,
              lam l * (sheafKn K m).presheaf.germ V' b0 hb' (A l (finProdFinEquiv (j, t))) := by
            funext t
            have := congrFun hlam (finProdFinEquiv (j, t))
            rw [flatCoeff_apply] at this
            rw [← this]
            simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
          rw [hcj, polyOfCoeff_sum_mul, map_sum]
          simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, hR]
          refine Finset.sum_congr rfl fun l _ => ?_
          rw [map_mul, psi_C]
        rw [hy']
        exact Submodule.sum_mem _ fun l _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨l, rfl⟩)
      | zero =>
        have : (fun j => T.symm ((0 : Fin (q + 1) → Analytic.Conv K (m + 1)) j)) = 0 := by
          funext j; simp
        rw [this]; exact Submodule.zero_mem _
      | add y z _ _ hy hz =>
        have : (fun j => T.symm ((y + z) j)) = (fun j => T.symm (y j)) + fun j => T.symm (z j) := by
          funext j; simp [map_add]
        rw [this]; exact Submodule.add_mem _ hy hz
      | smul s y _ hy =>
        have : (fun j => T.symm ((s • y) j)) = T.symm s • fun j => T.symm (y j) := by
          funext j; simp [map_mul]
        rw [this]; exact Submodule.smul_mem _ _ hy
    have := key _ hOka
    simpa [hT, RingEquiv.symm_apply_apply] using this
  · -- the generators are relations
    rw [Submodule.span_le]
    rintro _ ⟨l, rfl⟩
    rw [SetLike.mem_coe, mem_rowKerR_iff]
    simp only [hR]
    have h1 : ∑ j, Ph j * polyOfCoeff (fun t =>
        (sheafKn K m).presheaf.germ V' b0 hb' (A l (finProdFinEquiv (j, t)))) = 0 := by
      rw [sum_mul_polyOfCoeff_eq_zero_iff_mem_relKer Ph hPhdeg _ h3d, hflatA, hbase]
      exact Submodule.subset_span ⟨l, rfl⟩
    have h2 := congrArg (psi ψ a' x0) h1
    rw [map_sum, map_zero] at h2
    rw [← h2]
    exact Finset.sum_congr rfl fun j _ => (map_mul _ _ _).symm

end AnalyticSpace
