/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.Oka.MainAux
public import Hironaka.AnalyticSpace.Oka.Core
import Hironaka.Analytic.ConvSeries.Units
import Hironaka.Analytic.Rueckert.Basic
import Hironaka.Analytic.Weierstrass.Preparation
import Hironaka.AnalyticSpace.CoherentLemmas
import Hironaka.AnalyticSpace.Oka.Transport
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init

/-!
# Oka's coherence theorem on the model `Kⁿ`

Oka's coherence theorem [Fre17, Ch. I, 10.3], [GR84, Ch. 2]: for an `𝒪(U)`-linear map
`F : 𝒪(U)^p → 𝒪(U)^q` on an open `U ⊆ Kⁿ`, the system of kernels `M_a = ker F_a`, `a ∈ U`, is
coherent, that is, locally finitely generated by germs of sections (`IsCoherent (sheafKn K n)`,
`isCoherent_sheafKn`; for the affine space `(Kⁿ, 𝒜_{Kⁿ})`, `oka_coherent`). The proof follows
Freitag's three steps: the reduction to one row (`isCoherent_of_isCoherent_top`,
`Hironaka.AnalyticSpace.CoherentLemmas`), Oka's lemma at each point
(`Hironaka.Analytic.Oka.Lemma`), and the induction on `n`, which is this module.

At a point `x` of `U`, a row `g` with all germs zero at `x` is zero near `x`
(`exists_res_eq_of_germ_eq`), and the relations of a zero row are everything
(`hasLocalGeneratorsOn_row_zero`); otherwise a nonzero entry is put first
(`hasLocalGeneratorsOn_row_comp_perm`), "after a suitable linear coordinate transformation" (a
choice of the coordinates `ψ`: `TKn_trans` and `exists_substEquiv_isRegularIn` applied to the
product of the nonzero Taylor series) all nonzero entries are `x_0`-regular at `x`, and "by the
preparation theorem" each is a unit times a Weierstrass polynomial
(`exists_unique_weierstrassPreparation`), whose coefficients and unit are realized as sections near
`x` (`exists_TKn_eq`, Mathlib's `TopCat.Presheaf.exists_germ_eq`). The polynomial row (`polyRow`)
has locally finitely generated relations by the core step (`hasLocalGeneratorsOn_polyRow`,
`Hironaka.AnalyticSpace.Oka.Core`, whose hypothesis `hIH` is the induction hypothesis on the base
`Kᵐ` applied to the coefficient matrix), and the units and the identification of the sections near
`x` transport this to the row `g` (`hasLocalGeneratorsOn_row_mul_units`,
`exists_res_eq_of_germ_eq`). The base case `n = 0` is a point: the relations form a finitely
generated submodule of the Noetherian stalk, and every stalk element is the germ of a section.
Freitag writes the proof over `ℂ`; it is carried out here over `K = ℝ` or `ℂ` at once, with the
Weierstrass theorems of `Hironaka.Analytic`, which hold for both fields.

Oka's theorem on the model is the first ingredient of the coherence of the structure sheaf of every
analytic `K`-space (`Hironaka.AnalyticSpace.CoherentAnalytic`), the property (3.8)(3) of [BM97] used
throughout the analytic strand.
-/

public noncomputable section

open TopologicalSpace Opposite CategoryTheory Manifold
open Analytic MvPowerSeries

universe u

namespace AnalyticSpace

variable {K : Type} [RCLike K]

section Aux

variable {R : Type*} [CommRing R]

theorem polyOfCoeff_zero (N : ℕ) : polyOfCoeff (0 : Fin N → R) = 0 := by
  simp [polyOfCoeff]

/-- Reading the Weierstrass coefficients back from the padded list. -/
theorem weierstrassList_rev {e d : ℕ} (he : e < d) (c : Fin e → R) (s : Fin e) :
    weierstrassList e c d ⟨e - 1 - s, by omega⟩ = c s := by
  unfold weierstrassList
  rw [dite_eq_left (by simp; omega)]
  congr 1
  ext
  simp
  omega

end Aux

/-- The base case `n = 0`: `K⁰` is a point, its stalk is Noetherian, and every stalk element is the
germ of a section. -/
theorem isCoherent_sheafKn_zero : IsCoherent (sheafKn.{u} K 0) := by
  intro U p q F x hx
  have hfg : (relationSubmodule (sheafKn K 0) F x hx).FG := IsNoetherian.noetherian _
  obtain ⟨k, v, hv⟩ := Submodule.fg_iff_exists_fin_generating_family.mp hfg
  choose Uv hUv sv hsv using fun lj : Fin k × Fin p =>
    (sheafKn K 0).presheaf.exists_germ_eq (v lj.1 lj.2)
  obtain ⟨V, hV⟩ : ∃ V : Opens (Kn.{u} K 0), V = U ⊓ Finset.univ.inf Uv := ⟨_, rfl⟩
  have hxV : x ∈ V := by
    rw [hV, ← SetLike.mem_coe, Opens.coe_inf]
    exact ⟨hx, mem_finset_inf_opens _ _ fun lj _ => hUv lj⟩
  have hVU : V ≤ U := hV ▸ inf_le_left
  have hVlj : ∀ lj, V ≤ Uv lj := fun lj =>
    hV ▸ inf_le_right.trans (finset_inf_opens_le _ _ (Finset.mem_univ lj))
  refine ⟨V, hVU, hxV, k,
    fun l j => (sheafKn K 0).presheaf.map (homOfLE (hVlj (l, j))).op (sv (l, j)), fun y hy => ?_⟩
  obtain rfl : x = y := Subsingleton.elim x y
  dsimp only
  have : (fun l => fun j => (sheafKn K 0).presheaf.germ V x hy
      ((sheafKn K 0).presheaf.map (homOfLE (hVlj (l, j))).op (sv (l, j)))) = v := by
    funext l j
    rw [TopCat.Presheaf.germ_res_apply]
    exact hsv (l, j)
  rw [this, hv]

/-- The induction step: coherence of `𝒜_{Kᵐ}` gives coherence of `𝒜_{Kᵐ⁺¹}` ([Fre17, Ch. I, 10.3],
third step of the proof). -/
theorem isCoherent_sheafKn_succ (m : ℕ) (ih : IsCoherent (sheafKn.{u} K m)) :
    IsCoherent (sheafKn.{u} K (m + 1)) := by
  refine isCoherent_of_isCoherent_top ?_
  intro U p g _ x hx
  classical
  by_cases hall : ∀ j, (sheafKn K (m + 1)).presheaf.germ U x hx (g j) = 0
  · -- the row is zero near `x`
    choose W hWU hxW hW using fun j =>
      exists_res_eq_of_germ_eq (sheafKn K (m + 1)) hx (g j) 0 (by rw [hall j, map_zero])
    obtain ⟨W', hW'⟩ : ∃ W' : Opens (Kn.{u} K (m + 1)), W' = U ⊓ Finset.univ.inf W := ⟨_, rfl⟩
    have hxW' : x ∈ W' := by
      rw [hW', ← SetLike.mem_coe, Opens.coe_inf]
      exact ⟨hx, mem_finset_inf_opens _ _ fun j _ => hxW j⟩
    have hW'U : W' ≤ U := hW' ▸ inf_le_left
    have hW'j : ∀ j, W' ≤ W j := fun j =>
      hW' ▸ inf_le_right.trans (finset_inf_opens_le _ _ (Finset.mem_univ j))
    refine hasLocalGeneratorsOn_row_of_res hW'U hxW' g (hasLocalGeneratorsOn_row_zero _ fun j => ?_)
    rw [← res_res_eq_res (sheafKn K (m + 1)) (hWU j) (hW'j j), hW j, map_zero, map_zero]
  · -- some entry has a nonzero germ at `x`
    obtain ⟨j0, hj0⟩ := not_forall.mp hall
    obtain ⟨q, rfl⟩ : ∃ q, p = q + 1 := Nat.exists_eq_succ_of_ne_zero (Fin.pos j0).ne'
    -- put it first
    set σ : Equiv.Perm (Fin (q + 1)) := Equiv.swap 0 j0 with hσ
    set g' : Fin (q + 1) → (sheafKn K (m + 1)).presheaf.obj (op U) := g ∘ σ with hg'
    have hg'0 : (sheafKn K (m + 1)).presheaf.germ U x hx (g' 0) ≠ 0 := by
      simp only [hg', Function.comp_apply, hσ, Equiv.swap_apply_left]; exact hj0
    -- the linear change of coordinates making the nonzero Taylor series regular
    set S : Finset (Fin (q + 1)) :=
      Finset.univ.filter fun j => (sheafKn K (m + 1)).presheaf.germ U x hx (g' j) ≠ 0 with hS
    have h0S : (0 : Fin (q + 1)) ∈ S := by simp [hS, hg'0]
    have hSne : ∀ j ∈ S, (sheafKn K (m + 1)).presheaf.germ U x hx (g' j) ≠ 0 := fun j hj =>
      (Finset.mem_filter.mp hj).2
    have hSzero : ∀ j, j ∉ S → (sheafKn K (m + 1)).presheaf.germ U x hx (g' j) = 0 := fun j hj => by
      by_contra h; exact hj (Finset.mem_filter.mpr ⟨Finset.mem_univ _, h⟩)
    set fprod : Analytic.Conv K (m + 1) := ∏ j ∈ S,
      (⟨TKn (knCoord K (m + 1)) x ((sheafKn K (m + 1)).presheaf.germ U x hx (g' j)),
        TKn_mem_conv _ x _⟩ : Analytic.Conv K (m + 1))
      with hfprod
    have hf0 : fprod ≠ 0 := by
      rw [hfprod, Finset.prod_ne_zero_iff]
      intro j hj h
      apply hSne j hj
      apply TKn_injective (knCoord K (m + 1)) x
      rw [map_zero]
      exact congrArg Subtype.val h
    obtain ⟨L, hL⟩ := exists_substEquiv_isRegularIn hf0
    set ψ : Kn.{u} K (m + 1) ≃L[K] (Fin (m + 1) → K) := (knCoord K (m + 1)).trans L.symm with hψ
    have hTψ : ∀ s, TKn ψ x s = (substEquiv L ⟨TKn (knCoord K (m + 1)) x s, TKn_mem_conv _ x s⟩ :
        MvPowerSeries (Fin (m + 1)) K) := by
      intro s
      rw [hψ, TKn_trans, ContinuousLinearEquiv.symm_symm, substEquiv_apply]
    -- regularity of the nonzero entries in the coordinates `ψ`
    have hreg : ∀ j ∈ S,
        ∃ e, IsRegularIn (TKn ψ x ((sheafKn K (m + 1)).presheaf.germ U x hx (g' j))) e := by
      intro j hj
      have hprodT : (substEquiv L fprod : MvPowerSeries (Fin (m + 1)) K) =
          ∏ i ∈ S, TKn ψ x ((sheafKn K (m + 1)).presheaf.germ U x hx (g' i)) := by
        rw [hfprod, map_prod, ← Subalgebra.coe_val, map_prod]
        exact Finset.prod_congr rfl fun i _ => by rw [hTψ]; rfl
      rw [hprodT] at hL
      exact exists_isRegularIn_of_prod S _ hL hj
    choose e' hreg' using hreg
    -- the preparation of each nonzero entry
    have hprep : ∀ j (hj : j ∈ S), ∃ (u : MvPowerSeries (Fin (m + 1)) K)
        (c : Fin (e' j hj) → MvPowerSeries (Fin m) K),
        u ∈ Analytic.Conv K (m + 1) ∧ constantCoeff u ≠ 0 ∧
        (∀ k, c k ∈ Analytic.Conv K m ∧ constantCoeff (c k) = 0) ∧
        TKn ψ x ((sheafKn K (m + 1)).presheaf.germ U x hx (g' j)) =
          u * weierstrassPoly (e' j hj) c := by
      intro j hj
      obtain ⟨u, c, hu, hu0, hc, heq, -⟩ :=
        exists_unique_weierstrassPreparation (TKn_mem_conv ψ x _) (hreg' j hj)
      exact ⟨u, c, hu, hu0, hc, heq⟩
    choose u' c' hu' hu'0 hc' heq' using hprep
    -- the common degree bound
    set d : ℕ := (∑ j ∈ S.attach, e' j.1 j.2) + 1 with hd
    have hd0 : 0 < d := by omega
    have hed : ∀ j (hj : j ∈ S), e' j hj < d := by
      intro j hj
      have : e' j hj ≤ ∑ i ∈ S.attach, e' i.1 i.2 :=
        Finset.single_le_sum (f := fun i : S => e' i.1 i.2) (fun _ _ => Nat.zero_le _)
          (Finset.mem_attach S ⟨j, hj⟩)
      omega
    -- the padded coefficient lists, all convergent
    set wl : Fin (q + 1) → Fin d → MvPowerSeries (Fin m) K :=
      fun j => if hj : j ∈ S then weierstrassList (e' j hj) (c' j hj) d else 0 with hwl
    have hwlconv : ∀ j t, wl j t ∈ Analytic.Conv K m := by
      intro j t
      simp only [hwl]
      split_ifs with hj
      · unfold weierstrassList
        split_ifs
        · exact (hc' j hj _).1
        · exact Subalgebra.one_mem _
        · exact Subalgebra.zero_mem _
      · exact Subalgebra.zero_mem _
    -- sections over the base realizing the coefficient lists at `π x`
    choose gc hgc using fun jt : Fin (q + 1) × Fin d =>
      exists_TKn_eq (knCoord K m) (projKn ψ x) (hwlconv jt.1 jt.2)
    choose Uc hUc sc hsc using fun jt : Fin (q + 1) × Fin d =>
      (sheafKn K m).presheaf.exists_germ_eq (gc jt)
    obtain ⟨V, hV⟩ : ∃ V : Opens (Kn.{u} K m), V = Finset.univ.inf Uc := ⟨_, rfl⟩
    have hx'V : projKn ψ x ∈ V := by rw [hV]; exact mem_finset_inf_opens _ _ fun jt _ => hUc jt
    have hVjt : ∀ jt, V ≤ Uc jt := fun jt => hV ▸ finset_inf_opens_le _ _ (Finset.mem_univ jt)
    set sec : Fin (q + 1) → Fin d → (sheafKn K m).presheaf.obj (op V) :=
      fun j t => (sheafKn K m).presheaf.map (homOfLE (hVjt (j, t))).op (sc (j, t)) with hsec
    have hTsec : ∀ j t, TKn (knCoord K m) (projKn ψ x)
        ((sheafKn K m).presheaf.germ V (projKn ψ x) hx'V (sec j t)) = wl j t := by
      intro j t
      rw [hsec]; dsimp only
      rw [TopCat.Presheaf.germ_res_apply, hsc, hgc]
    -- the coefficient sections of the polynomial row
    set pc : Fin (q + 1) → Fin d → (sheafKn K m).presheaf.obj (op V) :=
      fun j => if hj : j ∈ S then
        weierstrassList (e' j hj) (fun s => sec j ⟨e' j hj - 1 - s, by have := hed j hj; omega⟩) d
      else 0 with hpc
    -- their germs at any base point form the Weierstrass list of the germs of the coefficients
    have hpc_germ : ∀ j (hj : j ∈ S) (b : Kn.{u} K m) (hb : b ∈ V),
        (fun t => (sheafKn K m).presheaf.germ V b hb (pc j t)) =
          weierstrassList (e' j hj) (fun s => (sheafKn K m).presheaf.germ V b hb
            (sec j ⟨e' j hj - 1 - s, by have := hed j hj; omega⟩)) d := by
      intro j hj b hb
      funext t
      simp only [hpc, dite_eq_left hj]
      exact map_weierstrassList _ _ _ _ t
    have hmonic : ∀ b (hb : b ∈ V),
        (polyOfCoeff fun t => (sheafKn K m).presheaf.germ V b hb (pc 0 t)).Monic ∧
        (polyOfCoeff fun t => (sheafKn K m).presheaf.germ V b hb (pc 0 t)).natDegree =
          e' 0 h0S := by
      intro b hb
      rw [hpc_germ 0 h0S b hb, polyOfCoeff_weierstrassList (hed 0 h0S)]
      exact ⟨monic_weierstrassPolynomial _ _, natDegree_weierstrassPolynomial _ _⟩
    -- the Taylor series at `x` of the polynomial row: the Weierstrass polynomials
    set x0 : K := ψ x 0 with hx0
    have hxbase : x ∈ baseOpens ψ V := hx'V
    have hTP : ∀ j (hj : j ∈ S), TKn ψ x ((sheafKn K (m + 1)).presheaf.germ (baseOpens ψ V) x hxbase
        (polyRow ψ V x0 pc j)) = weierstrassPoly (e' j hj) (c' j hj) := by
      intro j hj
      rw [polyRow, TKn_germ_polyComb ψ hxbase, hx0, sub_self, map_zero, map_zero, sub_zero,
        Polynomial.comp_X]
      have hlist : (fun t => TKn (knCoord K m) (projKn ψ x)
          ((sheafKn K m).presheaf.germ V (projKn ψ x) hxbase (pc j t))) =
          weierstrassList (e' j hj) (c' j hj) d := by
        funext t
        rw [congrFun (hpc_germ j hj _ hxbase) t, map_weierstrassList]
        congr 1
        funext s
        rw [hTsec j ⟨e' j hj - 1 - s, by have := hed j hj; omega⟩, hwl]
        simp only [dite_eq_left hj]
        exact weierstrassList_rev (hed j hj) (c' j hj) s
      rw [hlist, polyOfCoeff_weierstrassList (hed j hj),
        ofPoly_weierstrassPolynomial]
    have hTP0 : ∀ j, j ∉ S → (sheafKn K (m + 1)).presheaf.germ (baseOpens ψ V) x hxbase
        (polyRow ψ V x0 pc j) = 0 := by
      intro j hj
      rw [polyRow, germ_polyComb_eq_psi ψ hxbase]
      have : (∑ k : Fin d,
          Polynomial.C ((sheafKn K m).presheaf.germ V (projKn ψ x) hxbase (pc j k)) *
            Polynomial.X ^ (k : ℕ)) = 0 := by
        simp only [hpc, dite_eq_right hj, Pi.zero_apply, map_zero, zero_mul, Finset.sum_const_zero]
      rw [this, map_zero]
    -- the units, as sections near `x`
    set uval : Fin (q + 1) → MvPowerSeries (Fin (m + 1)) K :=
      fun j => if hj : j ∈ S then u' j hj else 1 with huval
    have huvalconv : ∀ j, uval j ∈ Analytic.Conv K (m + 1) := fun j => by
      simp only [huval]; split_ifs with hj
      · exact hu' j hj
      · exact Subalgebra.one_mem _
    have huval0 : ∀ j, constantCoeff (uval j) ≠ 0 := fun j => by
      simp only [huval]; split_ifs with hj
      · exact hu'0 j hj
      · rw [map_one]; exact one_ne_zero
    choose gu hgu using fun j => exists_TKn_eq ψ x (huvalconv j)
    choose Uu hUu su hsu using fun j => (sheafKn K (m + 1)).presheaf.exists_germ_eq (gu j)
    -- the common open around `x` and the identities `g'_j = u_j · P_j` there
    obtain ⟨W₀, hW₀⟩ : ∃ W₀ : Opens (Kn.{u} K (m + 1)),
        W₀ = U ⊓ baseOpens ψ V ⊓ Finset.univ.inf Uu := ⟨_, rfl⟩
    have hxW₀ : x ∈ W₀ := by
      rw [hW₀, ← SetLike.mem_coe, Opens.coe_inf, Opens.coe_inf]
      exact ⟨⟨hx, hxbase⟩, mem_finset_inf_opens _ _ fun j _ => hUu j⟩
    have hW₀U : W₀ ≤ U := hW₀ ▸ inf_le_left.trans inf_le_left
    have hW₀B : W₀ ≤ baseOpens ψ V := hW₀ ▸ inf_le_left.trans inf_le_right
    have hW₀u : ∀ j, W₀ ≤ Uu j := fun j =>
      hW₀ ▸ inf_le_right.trans (finset_inf_opens_le _ _ (Finset.mem_univ j))
    set g₀ : Fin (q + 1) → (sheafKn K (m + 1)).presheaf.obj (op W₀) :=
      fun j => (sheafKn K (m + 1)).presheaf.map (homOfLE hW₀U).op (g' j) with hg₀
    set P₀ : Fin (q + 1) → (sheafKn K (m + 1)).presheaf.obj (op W₀) :=
      fun j => (sheafKn K (m + 1)).presheaf.map (homOfLE hW₀B).op (polyRow ψ V x0 pc j) with hP₀
    set u₀ : Fin (q + 1) → (sheafKn K (m + 1)).presheaf.obj (op W₀) :=
      fun j => (sheafKn K (m + 1)).presheaf.map (homOfLE (hW₀u j)).op (su j) with hu₀
    have hgerm : ∀ j, (sheafKn K (m + 1)).presheaf.germ W₀ x hxW₀ (g₀ j) =
        (sheafKn K (m + 1)).presheaf.germ W₀ x hxW₀ (u₀ j * P₀ j) := by
      intro j
      apply TKn_injective ψ x
      rw [map_mul, hg₀, hP₀, hu₀]
      dsimp only
      rw [TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply,
        TopCat.Presheaf.germ_res_apply, map_mul, hsu, hgu]
      by_cases hj : j ∈ S
      · rw [heq' j hj, hTP j hj, huval]; simp only [dite_eq_left hj]
      · rw [hSzero j hj, hTP0 j hj, map_zero, mul_zero]
    choose W₁ hW₁ hxW₁ hW₁eq using fun j =>
      exists_res_eq_of_germ_eq (sheafKn K (m + 1)) hxW₀ (g₀ j) (u₀ j * P₀ j) (hgerm j)
    -- the units are units near `x`
    have hunit : ∀ j, IsUnit ((sheafKn K (m + 1)).presheaf.germ W₀ x hxW₀ (u₀ j)) := by
      intro j
      rw [← MulEquiv.isUnit_map (taylorKn ψ x).toMulEquiv]
      have : taylorKn ψ x ((sheafKn K (m + 1)).presheaf.germ W₀ x hxW₀ (u₀ j)) =
          ⟨uval j, huvalconv j⟩ := by
        apply Subtype.ext
        rw [taylorKn_apply_coe, hu₀]
        dsimp only
        rw [TopCat.Presheaf.germ_res_apply, hsu, hgu]
      rw [RingEquiv.toMulEquiv_eq_coe, RingEquiv.coe_toMulEquiv, this]
      exact (isUnit_iff_constantCoeff_ne_zero (huvalconv j)).2 (huval0 j)
    choose W₂ hW₂ hxW₂ hW₂u using fun j =>
      exists_isUnit_res_of_isUnit_germ (sheafKn K (m + 1)) hxW₀ (u₀ j) (hunit j)
    obtain ⟨W, hW⟩ : ∃ W : Opens (Kn.{u} K (m + 1)),
        W = Finset.univ.inf W₁ ⊓ Finset.univ.inf W₂ := ⟨_, rfl⟩
    have hxW : x ∈ W := by
      rw [hW, ← SetLike.mem_coe, Opens.coe_inf]
      exact ⟨mem_finset_inf_opens _ _ fun j _ => hxW₁ j, mem_finset_inf_opens _ _ fun j _ => hxW₂ j⟩
    have hWW₁ : ∀ j, W ≤ W₁ j := fun j =>
      hW ▸ inf_le_left.trans (finset_inf_opens_le _ _ (Finset.mem_univ j))
    have hWW₂ : ∀ j, W ≤ W₂ j := fun j =>
      hW ▸ inf_le_right.trans (finset_inf_opens_le _ _ (Finset.mem_univ j))
    have hWW₀ : W ≤ W₀ := (hWW₁ 0).trans (hW₁ 0)
    have hWU : W ≤ U := hWW₀.trans hW₀U
    -- on `W`: `g' = u · P` and the `u_j` are units
    have hrow : (fun j => (sheafKn K (m + 1)).presheaf.map (homOfLE hWU).op (g' j)) =
        fun j => (sheafKn K (m + 1)).presheaf.map (homOfLE hWW₀).op (u₀ j) *
          (sheafKn K (m + 1)).presheaf.map (homOfLE hWW₀).op (P₀ j) := by
      funext j
      rw [← map_mul, ← res_res_eq_res (sheafKn K (m + 1)) (hW₁ j) (hWW₁ j), ← hW₁eq j,
        res_res_eq_res, hg₀]
      dsimp only
      rw [res_res_eq_res]
    have hunits : ∀ j, IsUnit ((sheafKn K (m + 1)).presheaf.map (homOfLE hWW₀).op (u₀ j)) := by
      intro j
      rw [← res_res_eq_res (sheafKn K (m + 1)) (hW₂ j) (hWW₂ j)]
      exact (hW₂u j).map _
    -- the core step for the polynomial row, restricted to `W`
    have hIH := ih V ((q + 1) * (3 * d)) (d + 3 * d) (coeffMatSec pc (d + 3 * d) (3 * d))
    have hcore := hasLocalGeneratorsOn_polyRow ψ hd0 (hed 0 h0S) V x0 pc hmonic hIH
    have hP := hasLocalGeneratorsOn_row_res (hWW₀.trans hW₀B) (polyRow ψ V x0 pc) hcore
    have hPW : HasLocalGeneratorsOn (sheafKn K (m + 1)) W (q + 1) fun y hy =>
        relationSubmodule (sheafKn K (m + 1))
          (fun _ : Fin 1 => fun j => (sheafKn K (m + 1)).presheaf.map (homOfLE hWW₀).op (P₀ j))
          y hy := by
      refine hP.congr fun y hy => ?_
      congr 2
    have huP := hasLocalGeneratorsOn_row_mul_units _ _ hunits hPW
    rw [← hrow] at huP
    -- back to the row `g`
    have hg : HasLocalGeneratorsOn (sheafKn K (m + 1)) W (q + 1) fun y hy =>
        relationSubmodule (sheafKn K (m + 1))
          (fun _ : Fin 1 => fun j => (sheafKn K (m + 1)).presheaf.map (homOfLE hWU).op (g j))
          y hy :=
      hasLocalGeneratorsOn_row_comp_perm _ σ huP
    exact hasLocalGeneratorsOn_row_of_res hWU hxW g hg

/-- **Oka's coherence theorem** [Fre17, Ch. I, 10.3], [GR84, Ch. 2]: the sheaf `𝒜_{Kⁿ}` of analytic
functions on the model `Kⁿ` is coherent, for `K = ℝ` or `ℂ` and every `n`. -/
theorem isCoherent_sheafKn : ∀ n : ℕ, IsCoherent (sheafKn.{u} K n)
  | 0 => isCoherent_sheafKn_zero
  | n + 1 => isCoherent_sheafKn_succ n (isCoherent_sheafKn n)

/-- Oka's coherence theorem for the affine space `(Kⁿ, 𝒜_{Kⁿ})` (`affine K n`): its structure sheaf
is coherent. -/
theorem oka_coherent (n : ℕ) : IsCoherent (affine.{u} K n).toLocallyRingedSpace.𝒪 :=
  isCoherent_sheafKn n

end AnalyticSpace
