/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.Oka.Model
public import Hironaka.Analytic.Rueckert.Subst
public import Hironaka.AnalyticSpace.Coherent
import Hironaka.AnalyticSpace.CoherentLemmas
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init

/-!
# Reductions for the induction of Oka's theorem

Freitag's third step [Fre17, Ch. I, 10.3, proof] first makes the entries `F_1, …, F_p` of the row
`z_n`-general at the origin by a linear change of coordinates, then Weierstrass polynomials by the
preparation theorem. This module provides
the reductions the induction of `Hironaka.AnalyticSpace.Oka.Main` uses at a point `x`:

* `TKn_trans`: the Taylor series in the coordinates `L ∘ knCoord` is the substitution
  `substConv L⁻¹` of the Taylor series in the `ULift` coordinates, so that the linear change of
  coordinates is a choice of `ψ` in the modules on Oka's theorem;
* `exists_isUnit_res_of_isUnit_germ`: a section whose germ is a unit is a unit on a neighbourhood
  (in any sheaf of rings);
* `hasLocalGeneratorsOn_row_mul_units`: local generators of the relations of `(u_j g_j)_j`, for unit
  sections `u_j`, from those of `(g_j)_j` (the units of the preparation theorem);
* `hasLocalGeneratorsOn_row_comp_perm`: local generators of the relations of a row from those of a
  permuted row (the monic entry is put first);
* `hasLocalGeneratorsOn_row_zero`: the relations of a zero row are everything, generated by the unit
  vectors.

The relation system of a row `g` is `relationSubmodule 𝒪 (fun _ : Fin 1 => g)`, the kernel system of
the `1 × p` matrix `g` (`Hironaka.AnalyticSpace.Coherent`), and `HasLocalGeneratorsOn` says that it
is locally finitely generated by germs of sections. None of this is in the sources as a separate
statement.
-/

public noncomputable section

open TopologicalSpace Opposite CategoryTheory Filter Topology Manifold
open Analytic
open scoped Manifold ContDiff

universe u

namespace AnalyticSpace

section CoordChange

variable {K : Type} [RCLike K] {n : ℕ}

/-- Freitag's "linear coordinate transformation" [Fre17, Ch. I, 10.3]: the Taylor series in the
coordinates `L ∘ knCoord` is `substConv L⁻¹` of the Taylor series in the `ULift` coordinates. -/
theorem TKn_trans (L : (Fin n → K) ≃L[K] (Fin n → K)) (a : Kn.{u} K n)
    (s : (sheafKn K n).presheaf.stalk a) :
    TKn ((knCoord K n).trans L) a s =
      (substConv (L.symm : (Fin n → K) →L[K] (Fin n → K))
        ⟨TKn (knCoord K n) a s, TKn_mem_conv _ a s⟩ : MvPowerSeries (Fin n) K) := by
  obtain ⟨U, hU, f, rfl⟩ := (sheafKn K n).presheaf.exists_germ_eq s
  have h1 := (isTaylorHom_TKn ((knCoord K n).trans L) a).2 U hU f
  have h2 := (isTaylorHom_TKn (knCoord K n) a).2 U hU f
  simp only [chartAt_self_eq, OpenPartialHomeomorph.refl_symm, OpenPartialHomeomorph.refl_apply]
    at h1 h2
  refine eq_of_evalSeries_sub_eventuallyEq ((knCoord K n).trans L) a (TKn_mem_conv _ _ _)
    (substConv _ _).2 ?_
  refine h1.symm.trans ?_
  have hLsymm : Tendsto L.symm (𝓝 (((knCoord K n).trans L) a)) (𝓝 ((knCoord K n) a)) := by
    have := L.symm.continuous.tendsto (((knCoord K n).trans L) a)
    rwa [ContinuousLinearEquiv.trans_apply, L.symm_apply_apply] at this
  have h3 := h2.comp_tendsto hLsymm
  have h4 : ∀ y, (extendSection K (Kn.{u} K n) f ∘ id ∘ ((knCoord K n).trans L).symm) y =
      ((extendSection K (Kn.{u} K n) f ∘ id ∘ (knCoord K n).symm) ∘ L.symm) y := by
    intro y
    simp only [Function.comp_apply, id, ContinuousLinearEquiv.symm_trans_apply]
  refine (Filter.EventuallyEq.of_eq (funext h4)).trans (h3.trans ?_)
  have hsub : Tendsto (fun y => y - ((knCoord K n).trans L) a) (𝓝 (((knCoord K n).trans L) a))
      (𝓝 0) := by
    have := (continuous_sub_right (((knCoord K n).trans L) a)).tendsto
      (((knCoord K n).trans L) a)
    rwa [sub_self] at this
  have h5 := (evalSeries_substConv (L.symm : (Fin n → K) →L[K] (Fin n → K))
    ⟨TKn (knCoord K n) a ((sheafKn K n).presheaf.germ U a hU f), TKn_mem_conv _ a _⟩).comp_tendsto
      hsub
  refine Filter.EventuallyEq.trans (Filter.Eventually.of_forall fun y => ?_) h5.symm
  simp only [Function.comp_apply, ContinuousLinearEquiv.trans_apply]
  congr 1
  simp only [id, map_sub, ContinuousLinearEquiv.coe_coe, ContinuousLinearEquiv.symm_apply_apply]

end CoordChange

section Sheaf

variable {X : TopCat.{u}} (F : TopCat.Sheaf CommRingCat.{u} X)

/-- A section whose germ at `x` is a unit is a unit on a neighbourhood of `x`. -/
theorem exists_isUnit_res_of_isUnit_germ {U : Opens X} {x : X} (hx : x ∈ U)
    (s : F.presheaf.obj (op U))
    (hs : IsUnit (F.presheaf.germ U x hx s)) :
    ∃ (W : Opens X) (hWU : W ≤ U) (_ : x ∈ W), IsUnit (F.presheaf.map (homOfLE hWU).op s) := by
  obtain ⟨t, ht⟩ := hs.exists_right_inv
  obtain ⟨V, hV, t', rfl⟩ := F.presheaf.exists_germ_eq t
  have hxUV : x ∈ U ⊓ V := by
    rw [← SetLike.mem_coe, Opens.coe_inf]; exact ⟨hx, hV⟩
  have h1 : F.presheaf.germ (U ⊓ V) x hxUV
      (F.presheaf.map (homOfLE (inf_le_left : U ⊓ V ≤ U)).op s *
        F.presheaf.map (homOfLE (inf_le_right : U ⊓ V ≤ V)).op t') =
      F.presheaf.germ (U ⊓ V) x hxUV 1 := by
    rw [map_mul, TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply, map_one]
    exact ht
  obtain ⟨W, hxW, iW, iW', hW⟩ := TopCat.Presheaf.germ_eq F.presheaf x hxUV hxUV _ _ h1
  have e1 : iW = homOfLE iW.le := Subsingleton.elim _ _
  have e2 : iW' = homOfLE iW'.le := Subsingleton.elim _ _
  rw [e1, e2, map_mul, map_one, ← ConcreteCategory.comp_apply, ← ConcreteCategory.comp_apply,
    ← Functor.map_comp, ← Functor.map_comp, ← op_comp, ← op_comp, homOfLE_comp, homOfLE_comp] at hW
  refine ⟨W, iW.le.trans inf_le_left, hxW, ?_⟩
  exact ⟨⟨_, F.presheaf.map (homOfLE (iW.le.trans inf_le_right)).op t', hW,
    by rw [mul_comm]; exact hW⟩, rfl⟩

end Sheaf

section Rows

variable {X : TopCat.{u}} {𝒪 : TopCat.Sheaf CommRingCat.{u} X} {U : Opens X} {p : ℕ}

/-- A relation of a row: the sum form. -/
theorem mem_relationSubmodule_row_iff (g : Fin p → 𝒪.presheaf.obj (op U)) {y : X} (hy : y ∈ U)
    (a : Fin p → 𝒪.presheaf.stalk y) :
    a ∈ relationSubmodule 𝒪 (fun _ : Fin 1 => g) y hy ↔
      ∑ j, 𝒪.presheaf.germ U y hy (g j) * a j = 0 := by
  rw [mem_relationSubmodule_iff]
  exact ⟨fun h => h 0, fun h _ => h⟩

/-- The relations of a zero row are everything, generated by the unit vectors. -/
theorem hasLocalGeneratorsOn_row_zero (g : Fin p → 𝒪.presheaf.obj (op U)) (hg : ∀ j, g j = 0) :
    HasLocalGeneratorsOn 𝒪 U p fun y hy => relationSubmodule 𝒪 (fun _ : Fin 1 => g) y hy := by
  intro x hx
  refine ⟨U, le_rfl, hx, p, fun l j => if l = j then 1 else 0, fun y hy => ?_⟩
  dsimp only
  have htop : relationSubmodule 𝒪 (fun _ : Fin 1 => g) y hy = ⊤ := by
    rw [eq_top_iff]
    intro a _
    rw [mem_relationSubmodule_row_iff]
    simp [hg]
  rw [htop]
  have : (fun l => fun j => 𝒪.presheaf.germ U y hy
      (if l = j then (1 : 𝒪.presheaf.obj (op U)) else 0)) =
      fun l : Fin p => (Pi.single l (1 : 𝒪.presheaf.stalk y) : Fin p → 𝒪.presheaf.stalk y) := by
    funext l j
    by_cases hlj : l = j
    · subst hlj; simp
    · simp [hlj, Ne.symm hlj]
  rw [this, span_range_single_one_eq_top]

/-- Relations of a permuted row give relations of the row. -/
theorem hasLocalGeneratorsOn_row_comp_perm (g : Fin p → 𝒪.presheaf.obj (op U))
    (σ : Equiv.Perm (Fin p))
    (h : HasLocalGeneratorsOn 𝒪 U p fun y hy => relationSubmodule 𝒪 (fun _ : Fin 1 => g ∘ σ) y hy) :
    HasLocalGeneratorsOn 𝒪 U p fun y hy => relationSubmodule 𝒪 (fun _ : Fin 1 => g) y hy := by
  intro x hx
  obtain ⟨V, hVU, hxV, k, r, hr⟩ := h x hx
  refine ⟨V, hVU, hxV, k, fun l => r l ∘ σ.symm, fun y hy => ?_⟩
  have key : ∀ a : Fin p → 𝒪.presheaf.stalk y,
      a ∈ relationSubmodule 𝒪 (fun _ : Fin 1 => g) y (hVU hy) ↔
        a ∘ σ ∈ relationSubmodule 𝒪 (fun _ : Fin 1 => g ∘ σ) y (hVU hy) := by
    intro a
    rw [mem_relationSubmodule_row_iff, mem_relationSubmodule_row_iff]
    simp only [Function.comp_apply]
    rw [← Equiv.sum_comp σ (fun j => 𝒪.presheaf.germ U y (hVU hy) (g j) * a j)]
  have hry := hr y hy
  dsimp only at hry ⊢
  ext a
  rw [key, hry, Submodule.mem_span_range_iff_exists_fun, Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    funext j
    have := congrFun hc (σ.symm j)
    simpa [Finset.sum_apply, Pi.smul_apply, Function.comp_apply] using this
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    funext j
    have := congrFun hc (σ j)
    simpa [Finset.sum_apply, Pi.smul_apply, Function.comp_apply] using this

/-- Relations of `(u_j g_j)_j` for unit sections `u_j` from those of `(g_j)_j`. -/
theorem hasLocalGeneratorsOn_row_mul_units (g u : Fin p → 𝒪.presheaf.obj (op U))
    (hu : ∀ j, IsUnit (u j))
    (h : HasLocalGeneratorsOn 𝒪 U p fun y hy => relationSubmodule 𝒪 (fun _ : Fin 1 => g) y hy) :
    HasLocalGeneratorsOn 𝒪 U p fun y hy =>
      relationSubmodule 𝒪 (fun _ : Fin 1 => fun j => u j * g j) y hy := by
  intro x hx
  obtain ⟨V, hVU, hxV, k, r, hr⟩ := h x hx
  choose v hv using fun j => (hu j).exists_right_inv
  refine ⟨V, hVU, hxV, k, fun l j => 𝒪.presheaf.map (homOfLE hVU).op (v j) * r l j,
    fun y hy => ?_⟩
  have hry := hr y hy
  dsimp only at hry ⊢
  -- `germ u_j * germ v_j = 1`
  have huv : ∀ j, 𝒪.presheaf.germ U y (hVU hy) (u j) * 𝒪.presheaf.germ V y hy
      (𝒪.presheaf.map (homOfLE hVU).op (v j)) = 1 := by
    intro j
    rw [TopCat.Presheaf.germ_res_apply, ← map_mul, hv j, map_one]
  have key : ∀ a : Fin p → 𝒪.presheaf.stalk y,
      a ∈ relationSubmodule 𝒪 (fun _ : Fin 1 => fun j => u j * g j) y (hVU hy) ↔
        (fun j => 𝒪.presheaf.germ U y (hVU hy) (u j) * a j) ∈
          relationSubmodule 𝒪 (fun _ : Fin 1 => g) y (hVU hy) := by
    intro a
    rw [mem_relationSubmodule_row_iff, mem_relationSubmodule_row_iff]
    refine Eq.congr_left (Finset.sum_congr rfl fun j _ => ?_)
    rw [map_mul]; ring
  ext a
  rw [key, hry, Submodule.mem_span_range_iff_exists_fun, Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    funext j
    have h1 := congrFun hc j
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] at h1 ⊢
    calc ∑ l, c l * (𝒪.presheaf.germ V y hy (𝒪.presheaf.map (homOfLE hVU).op (v j) * r l j))
        = 𝒪.presheaf.germ V y hy (𝒪.presheaf.map (homOfLE hVU).op (v j)) *
          ∑ l, c l * 𝒪.presheaf.germ V y hy (r l j) := by
          rw [Finset.mul_sum]
          refine Finset.sum_congr rfl fun l _ => ?_
          rw [map_mul]; ring
      _ = 𝒪.presheaf.germ V y hy (𝒪.presheaf.map (homOfLE hVU).op (v j)) *
          (𝒪.presheaf.germ U y (hVU hy) (u j) * a j) := by rw [h1]
      _ = a j := by rw [← mul_assoc, mul_comm _ (𝒪.presheaf.germ U y (hVU hy) (u j)), huv, one_mul]
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    funext j
    have h1 := congrFun hc j
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] at h1 ⊢
    rw [← h1, Finset.mul_sum]
    refine Finset.sum_congr rfl fun l _ => ?_
    rw [map_mul, ← mul_assoc, ← mul_assoc, mul_comm (𝒪.presheaf.germ U y (hVU hy) (u j)) (c l),
      mul_assoc (c l), huv, mul_one]

end Rows

end AnalyticSpace
