/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Chart.Cotangent
public import Hironaka.Manifold.BlowUp.Divisor
public import Hironaka.Manifold.Snc.Defs
public import Hironaka.Manifold.Submanifold.Restrict
import Hironaka.Algebra.Local.PrimeProducts
import Hironaka.Algebra.Local.Regular
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.BlowUp.Transform.StrictCharts
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.Germ.TaylorIdeal
import Hironaka.Manifold.IdealSheaf.Basic
import Hironaka.Manifold.IdealSheaf.Vanishing
import Hironaka.Manifold.Snc.Basic
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The reduced ideal sheaf of an snc divisor: coherence and stalks

Hironaka's `red` of the support of a simple normal crossings divisor `F` is the ideal sheaf whose
stalks are the vanishing ideals of `|F|` (`vanishingStalk`); this module shows that these stalks
have local generators — so that `HypersurfaceFamily.idealSheaf` takes its first branch — and
computes them: at a point `a` with snc chart `φ` and indices `c`, the vanishing ideal of `|F|` at
every point `b` of the chart's source near `a` is generated by the single germ
`∏_{j : a ∈ E^j} z_{c j}` (Hironaka's
"the ideal of each irreducible component of `E` is generated by one of the `z_i`"
[Hir64, Definition 2, p. 141]; Bierstone–Milman's normal-crossings divisor, locally
`z_1 ⋯ z_k = 0`, [BM97, Theorem 1.10]). The proof is the classical one, made algebraic:

* near `a` the support is the union of the finitely many components through `a` (local finiteness
  and closedness of the components: `IsSnc.exists_nhds_support_eq`);
* a germ vanishing on the coordinate hyperplane `E^j = {z_k = 0}` near `b ∈ E^j` lies in the kernel
  of the restriction of germs to the submanifold `E^j`, which is `(z_k)`
  (`IsClosedSubmanifold.ker_restrictStalk_eq_span` with the one-index adapted chart); off `E^j`
  the coordinate `z_k` is a unit;
* the coordinates vanishing at `b` are prime elements of the regular local ring `𝒪_{M,b}`
  (`𝒪_b/(z_k)` is regular, `IsRegularLocalRing.quotient_span_singleton`, because
  `z_k ∈ 𝔪_b ∖ 𝔪_b²`: its linear part is the unit vector `e_k`), and no coordinate divides another
  (again by the linear parts), so a germ divisible by each of them is divisible by their product
  (`IsLocalRing.prod_dvd_of_prime_of_not_dvd`).

Consequences: the stalks of `F.idealSheaf` are the vanishing ideals (`stalkIdeal_idealSheaf`), its
cosupport is `|F|` (`cosupport_idealSheaf`), and in an snc chart the stalk at the chart's point is
`(∏_{j : a ∈ E^j} z_{c j})` (`stalkIdeal_idealSheaf_eq_span_prod`). These are the inputs of the
dictionary with Hironaka's predicates (`Hironaka/Manifold/Snc/Dictionary.lean`) and of the
monomial description of the boundary along a resolution.
-/

public section

open TopologicalSpace Filter Topology Opposite CategoryTheory IsLocalRing
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

namespace Manifold

universe u

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]

/-! ### Vanishing ideals: monotonicity and the kernel of the restriction of germs -/

/-- A germ vanishing on `Z'` near `x` vanishes on any `Z ⊆ Z'` near `x`. -/
theorem vanishingStalk_anti {Z Z' : Set M} (h : Z ⊆ Z') (x : M) :
    vanishingStalk (𝕜 := 𝕜) (E := E) Z' x ≤ vanishingStalk Z x := by
  intro s hs
  rw [mem_vanishingStalk_iff] at hs ⊢
  generalize stalkToGerm 𝓘(𝕜, E) ω M x s = g at hs ⊢
  refine Filter.Germ.inductionOn g (fun f (hf : Germ.VanishesOn Z' x (f : (𝓝 x).Germ 𝕜)) => ?_) hs
  rw [Germ.vanishesOn_coe] at hf ⊢
  exact hf.filter_mono (nhdsWithin_mono x h)

/-- The kernel of the restriction of germs to the closed submanifold `Y` at `a ∈ Y` is the
vanishing ideal of `Y` at `a`. -/
theorem IsClosedSubmanifold.ker_restrictStalk_eq_vanishingStalk {Y : Set M} {c : ℕ}
    (hY : IsClosedSubmanifold ψ Y c) {a : M} (ha : a ∈ Y) :
    RingHom.ker (hY.restrictStalk ⟨a, ha⟩) = vanishingStalk (𝕜 := 𝕜) (E := E) Y a := by
  let _i := hY.chartedSpace
  ext s
  rw [RingHom.mem_ker, mem_vanishingStalk_iff]
  have h1 := hY.stalkToGerm_restrictStalk ⟨a, ha⟩ s
  have hinj := stalkToGerm_injective 𝓘(𝕜, Fin (n - c) → 𝕜) ω Y ⟨a, ha⟩
  rw [← hinj.eq_iff, map_zero, h1]
  generalize stalkToGerm 𝓘(𝕜, E) ω M a s = g
  refine Filter.Germ.inductionOn g fun f => ?_
  rw [germRestrict_coe, Germ.vanishesOn_coe, ← Germ.coe_zero, Germ.coe_eq,
    nhdsWithin_eq_map_subtype_coe ha, Filter.eventually_map]
  exact Iff.rfl

namespace HypersurfaceFamily

variable {F : HypersurfaceFamily M} {φ : OpenPartialHomeomorph M E} {a : M}
  {c : {j // a ∈ F.hyp j} → Fin n}

/-- An snc chart at `a` is a chart adapted to each component through `a`, with the single index
of that component (`singleEmb`). -/
theorem IsSncChartAt.isAdaptedChart_hyp (hc : F.IsSncChartAt ψ φ a c) (j : {j // a ∈ F.hyp j}) :
    IsAdaptedChart ψ (F.hyp j.1) φ (singleEmb (c j)) :=
  isAdaptedChart_singleIdx hc.1 fun _ hx => hc.mem_iff j hx

/-- At a point `b` of a component through `a`, a germ vanishes on that component near `b` iff the
component's coordinate divides it. -/
theorem IsSncChartAt.mem_vanishingStalk_hyp_iff (hF : F.IsSnc ψ) (hc : F.IsSncChartAt ψ φ a c)
    (j : {j // a ∈ F.hyp j}) {b : M} (hb : b ∈ φ.source) (hbj : b ∈ F.hyp j.1)
    (s : (structureSheaf 𝕜 E M).presheaf.stalk b) :
    s ∈ vanishingStalk (𝕜 := 𝕜) (E := E) (F.hyp j.1) b ↔ coord E ψ φ hc.1 hb (c j) ∣ s := by
  rw [← (hF.1 j.1).ker_restrictStalk_eq_vanishingStalk hbj,
    (hF.1 j.1).ker_restrictStalk_eq_span hbj (hc.isAdaptedChart_hyp j) hb, Set.range_unique,
    Ideal.mem_span_singleton]
  rfl

end HypersurfaceFamily

/-! ### The coordinates of a chart as elements of the stalk: units, primes, non-divisibility -/

section Coordinates

variable (φ : OpenPartialHomeomorph M E) (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {b : M}
  (hb : b ∈ φ.source)

/-- A coordinate vanishing at `b` lies in the maximal ideal of the stalk. -/
theorem coord_mem_maximalIdeal_of_eq_zero {k : Fin n} (h0 : ψ (φ b) k = 0) :
    coord E ψ φ hφ hb k ∈ maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk b) := by
  rw [mem_maximalIdeal_iff_eval, eval_coord]
  exact h0

/-- A coordinate not vanishing at `b` is a unit of the stalk. -/
theorem isUnit_coord_of_ne_zero {k : Fin n} (h0 : ψ (φ b) k ≠ 0) :
    IsUnit (coord E ψ φ hφ hb k) := by
  rw [← IsLocalRing.notMem_maximalIdeal, mem_maximalIdeal_iff_eval, eval_coord]
  exact h0

/-- The linear part of the coordinate `z_k` is the unit vector `e_k`. -/
theorem linearPart_coord (k i : Fin n) :
    linearPart E ψ φ hφ hb (coord E ψ φ hφ hb k) i = if i = k then 1 else 0 := by
  classical
  rw [linearPart_apply, taylorHom_coord, map_add, MvPowerSeries.coeff_X, MvPowerSeries.coeff_C,
    ite_eq_right (Finsupp.single_ne_zero.mpr one_ne_zero), add_zero]
  by_cases hik : i = k
  · subst hik
    rw [ite_eq_left rfl, ite_eq_left rfl]
  · rw [ite_eq_right hik, ite_eq_right]
    exact fun h => hik ((Finsupp.single_left_inj one_ne_zero).mp h)

/-- A coordinate vanishing at `b` is not in `𝔪_b²`. -/
theorem coord_notMem_maximalIdeal_sq {k : Fin n} :
    coord E ψ φ hφ hb k ∉ maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk b) ^ 2 := by
  intro h
  have h1 := congrFun (linearPart_eq_zero_of_mem_sq E ψ φ hφ hb h) k
  rw [linearPart_coord, ite_eq_left rfl, Pi.zero_apply] at h1
  exact one_ne_zero h1

/-- A coordinate vanishing at `b` is a prime element of the regular local ring `𝒪_{M,b}`: the
quotient by it is regular (`IsRegularLocalRing.quotient_span_singleton`), hence a
domain. -/
theorem prime_coord_of_eq_zero {k : Fin n} (h0 : ψ (φ b) k = 0) :
    Prime (coord E ψ φ hφ hb k) := by
  have hreg := isRegularLocalRing_stalk_of_chart E ψ φ hb hφ
  have hq := (IsRegularLocalRing.quotient_span_singleton
    (coord_mem_maximalIdeal_of_eq_zero φ hφ hb h0) (coord_notMem_maximalIdeal_sq φ hφ hb)).1
  have hdom : IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk b ⧸
      Ideal.span {coord E ψ φ hφ hb k}) := inferInstance
  have hne : coord E ψ φ hφ hb k ≠ 0 := by
    intro h
    exact coord_notMem_maximalIdeal_sq φ hφ hb (h ▸ Submodule.zero_mem _)
  exact (Ideal.span_singleton_prime hne).mp ((Ideal.Quotient.isDomain_iff_prime _).mp hdom)

/-- Two distinct coordinates vanishing at `b` do not divide each other in `𝒪_{M,b}`: their linear
parts are distinct unit vectors. -/
theorem not_coord_dvd_coord_of_ne {k l : Fin n} (hk0 : ψ (φ b) k = 0) (hkl : k ≠ l) :
    ¬ coord E ψ φ hφ hb k ∣ coord E ψ φ hφ hb l := by
  rintro ⟨u, hu⟩
  by_cases hu0 : eval 𝕜 E M b u = 0
  · apply coord_notMem_maximalIdeal_sq φ hφ hb (k := l)
    rw [hu, pow_two]
    exact Ideal.mul_mem_mul (coord_mem_maximalIdeal_of_eq_zero φ hφ hb hk0)
      ((mem_maximalIdeal_iff_eval E u).mpr hu0)
  · have hmem : coord E ψ φ hφ hb l - eval 𝕜 E M b u • coord E ψ φ hφ hb k ∈
        maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk b) ^ 2 := by
      rw [hu, pow_two, Algebra.smul_def, algebraMap_stalk_eq]
      have : coord E ψ φ hφ hb k * u - const 𝕜 E M b (eval 𝕜 E M b u) * coord E ψ φ hφ hb k =
          coord E ψ φ hφ hb k * (u - const 𝕜 E M b (eval 𝕜 E M b u)) := by ring
      rw [this]
      refine Ideal.mul_mem_mul (coord_mem_maximalIdeal_of_eq_zero φ hφ hb hk0) ?_
      rw [mem_maximalIdeal_iff_eval, map_sub, eval_const, sub_self]
    have h1 := congrFun (linearPart_eq_zero_of_mem_sq E ψ φ hφ hb hmem) l
    rw [map_sub, map_smul, Pi.sub_apply, Pi.smul_apply, linearPart_coord, linearPart_coord,
      ite_eq_left rfl, ite_eq_right (Ne.symm hkl), smul_zero, sub_zero, Pi.zero_apply] at h1
    exact one_ne_zero h1

end Coordinates

namespace HypersurfaceFamily

variable {F : HypersurfaceFamily M}

/-! ### The support near a point -/

/-- Near a point `a` the support of an snc divisor is the union of the components through `a`
(local finiteness and closedness). -/
theorem IsSnc.exists_nhds_support_eq (hF : F.IsSnc ψ) (a : M) :
    ∃ V : Set M, IsOpen V ∧ a ∈ V ∧ ∀ x ∈ V, x ∈ F.support ↔ ∃ j, a ∈ F.hyp j ∧ x ∈ F.hyp j := by
  classical
  obtain ⟨U, hU, hfin⟩ := hF.2.1 a
  refine ⟨interior U ∩ ⋂ j ∈ hfin.toFinset.filter (fun j => a ∉ F.hyp j), (F.hyp j)ᶜ,
    isOpen_interior.inter (isOpen_biInter_finset fun j _ => (hF.1 j).isClosed.isOpen_compl),
    ⟨mem_interior_iff_mem_nhds.mpr hU, Set.mem_iInter₂.mpr fun j hj => (Finset.mem_filter.mp hj).2⟩,
    fun x hx => ⟨fun hxs => ?_, fun ⟨j, _, hxj⟩ => Set.mem_iUnion.mpr ⟨j, hxj⟩⟩⟩
  obtain ⟨j, hxj⟩ := Set.mem_iUnion.mp hxs
  refine ⟨j, ?_, hxj⟩
  by_contra haj
  have hjT : j ∈ hfin.toFinset := hfin.mem_toFinset.mpr ⟨x, hxj, interior_subset hx.1⟩
  exact Set.mem_iInter₂.mp hx.2 j (Finset.mem_filter.mpr ⟨hjT, haj⟩) hxj

/-! ### The vanishing ideal of the support in an snc chart -/

variable {φ : OpenPartialHomeomorph M E} {a : M} {c : {j // a ∈ F.hyp j} → Fin n}

/-- In an snc chart `φ` at `a` with indices `c`, on a neighbourhood `V` of `a` where the support is
the union of the components through `a`, the vanishing ideal of the support at any
`b ∈ V ∩ φ.source` is generated by the product of the coordinates of the components through `a`
(indexed by any finset `S` of exactly those components) ([Hir64, Definition 2, p. 141];
[BM97, Theorem 1.10]). -/
theorem IsSncChartAt.vanishingStalk_support_eq (hF : F.IsSnc ψ) (hc : F.IsSncChartAt ψ φ a c)
    {V : Set M} (hV : IsOpen V)
    (hVs : ∀ x ∈ V, x ∈ F.support ↔ ∃ j, a ∈ F.hyp j ∧ x ∈ F.hyp j) {b : M} (hb : b ∈ φ.source)
    (hbV : b ∈ V) (S : Finset F.ι) (hS : ∀ j, j ∈ S ↔ a ∈ F.hyp j) :
    vanishingStalk (𝕜 := 𝕜) (E := E) F.support b =
      Ideal.span {∏ j ∈ S.attach, coord E ψ φ hc.1 hb (c ⟨j.1, (hS j.1).mp j.2⟩)} := by
  classical
  have hmem : ∀ j : {j // j ∈ S}, a ∈ F.hyp j.1 := fun j => (hS j.1).mp j.2
  refine le_antisymm ?_ (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr ?_))
  · -- a germ vanishing on the support is divisible by each coordinate through `b`, hence by the
    -- product (the coordinates of the components missing `b` are units)
    intro s hs
    rw [Ideal.mem_span_singleton,
      ← Finset.prod_filter_mul_prod_filter_not S.attach (fun j => b ∈ F.hyp j.1)]
    have hu : IsUnit (∏ j ∈ S.attach.filter (fun j => ¬ b ∈ F.hyp j.1),
        coord E ψ φ hc.1 hb (c ⟨j.1, hmem j⟩)) := by
      refine Finset.prod_induction _ IsUnit (fun _ _ => IsUnit.mul) isUnit_one fun j hj => ?_
      refine isUnit_coord_of_ne_zero φ hc.1 hb fun h0 => ?_
      exact (Finset.mem_filter.mp hj).2 ((hc.mem_iff ⟨j.1, hmem j⟩ hb).mpr h0)
    rw [IsUnit.mul_right_dvd hu]
    refine prod_dvd_of_prime_of_not_dvd _ _ (fun j hj => ?_)
      (fun i hi j hj hij => ?_) fun j hj => ?_
    · exact prime_coord_of_eq_zero φ hc.1 hb
        ((hc.mem_iff ⟨j.1, hmem j⟩ hb).mp (Finset.mem_filter.mp hj).2)
    · refine not_coord_dvd_coord_of_ne φ hc.1 hb
        ((hc.mem_iff ⟨i.1, hmem i⟩ hb).mp (Finset.mem_filter.mp hi).2) fun h => hij ?_
      have h' : (⟨i.1, hmem i⟩ : {j // a ∈ F.hyp j}) = ⟨j.1, hmem j⟩ := hc.injective h
      have h2 := congrArg Subtype.val h'
      exact Subtype.ext (show i.1 = j.1 from h2)
    · have hbj : b ∈ F.hyp j.1 := (Finset.mem_filter.mp hj).2
      rw [← hc.mem_vanishingStalk_hyp_iff hF ⟨j.1, hmem j⟩ hb hbj]
      exact vanishingStalk_anti (Set.subset_iUnion F.hyp j.1) b hs
  · -- the product vanishes on the support near `b`: every point of the support in `V ∩ φ.source`
    -- lies on a component through `a`, a coordinate hyperplane of the chart
    rw [SetLike.mem_coe, mem_vanishingStalk_iff, map_prod]
    have hcoe : ∀ j : {j // j ∈ S},
        stalkToGerm 𝓘(𝕜, E) ω M b (coord E ψ φ hc.1 hb (c ⟨j.1, hmem j⟩)) =
        ((extendSection 𝕜 E (chartSection E ψ φ hc.1 (c ⟨j.1, hmem j⟩)) : M → 𝕜) :
          (𝓝 b).Germ 𝕜) :=
      fun j => stalkToGerm_coord hc.1 hb _
    simp only [hcoe]
    have hprod : (∏ j ∈ S.attach,
        ((extendSection 𝕜 E (chartSection E ψ φ hc.1 (c ⟨j.1, hmem j⟩)) : M → 𝕜) :
          (𝓝 b).Germ 𝕜)) =
        ((∏ j ∈ S.attach, extendSection 𝕜 E (chartSection E ψ φ hc.1 (c ⟨j.1, hmem j⟩)) : M → 𝕜) :
          (𝓝 b).Germ 𝕜) :=
      (map_prod (Filter.Germ.coeRingHom (𝓝 b)) _ _).symm
    rw [hprod, Germ.vanishesOn_coe]
    filter_upwards [nhdsWithin_le_nhds ((hV.inter φ.open_source).mem_nhds ⟨hbV, hb⟩),
      self_mem_nhdsWithin] with y hyV hys
    obtain ⟨j, haj, hyj⟩ := (hVs y hyV.1).mp hys
    rw [Finset.prod_apply]
    refine Finset.prod_eq_zero (i := ⟨j, (hS j).mpr haj⟩) (Finset.mem_attach _ _) ?_
    rw [extendSection_of_mem 𝕜 E _ hyV.2]
    exact (hc.mem_iff ⟨j, haj⟩ hyV.2).mp hyj

/-! ### Coherence of the vanishing ideal sheaf of the support, and its stalks -/

/-- The vanishing ideals of the support of an snc divisor have local generators: near `a`, the
product of the coordinates of the components through `a` (Hironaka's "the ideal of each
irreducible component of `E` is generated by one of the `z_i`", [Hir64, Definition 2, p. 141]). -/
theorem IsSnc.hasLocalGenerators_vanishingStalk_support (hF : F.IsSnc ψ) :
    IdealSheaf.HasLocalGenerators (𝒪 := structureSheaf 𝕜 E M)
      fun x => vanishingStalk (𝕜 := 𝕜) (E := E) F.support x := by
  classical
  intro a
  obtain ⟨φ, c, hc⟩ := hF.exists_isSncChartAt a
  obtain ⟨V, hV, haV, hVs⟩ := hF.exists_nhds_support_eq a
  let W : Opens M := ⟨V ∩ φ.source, hV.inter φ.open_source⟩
  have hW : W ≤ ⟨φ.source, φ.open_source⟩ := fun _ hx => hx.2
  refine ⟨W, ⟨haV, hc.2.1⟩, Unit, inferInstance, fun _ =>
    (structureSheaf 𝕜 E M).presheaf.map (homOfLE hW).op
      (∏ j ∈ (hF.2.1.point_finite a).toFinset.attach,
        chartSection E ψ φ hc.1 (c ⟨j.1, (hF.2.1.point_finite a).mem_toFinset.mp j.2⟩)),
    fun b hb => ?_⟩
  beta_reduce
  rw [hc.vanishingStalk_support_eq hF hV hVs hb.2 hb.1 _
    fun j => (hF.2.1.point_finite a).mem_toFinset, Set.range_const]
  congr 2
  rw [TopCat.Presheaf.germ_res_apply]
  have key : (structureSheaf 𝕜 E M).presheaf.germ ⟨φ.source, φ.open_source⟩ b hb.2
      (∏ j ∈ (hF.2.1.point_finite a).toFinset.attach,
        chartSection E ψ φ hc.1 (c ⟨j.1, (hF.2.1.point_finite a).mem_toFinset.mp j.2⟩)) =
      ∏ j ∈ (hF.2.1.point_finite a).toFinset.attach,
        coord E ψ φ hc.1 hb.2 (c ⟨j.1, (hF.2.1.point_finite a).mem_toFinset.mp j.2⟩) :=
    map_prod ((structureSheaf 𝕜 E M).presheaf.germ ⟨φ.source, φ.open_source⟩ b hb.2).hom _ _
  exact key.symm

/-- The stalks of the reduced ideal sheaf of an snc divisor are the vanishing ideals of its
support. -/
theorem IsSnc.stalkIdeal_idealSheaf (hF : F.IsSnc ψ) (x : M) :
    F.idealSheaf.stalkIdeal x = vanishingStalk (𝕜 := 𝕜) (E := E) F.support x := by
  unfold HypersurfaceFamily.idealSheaf
  rw [dite_eq_left hF.hasLocalGenerators_vanishingStalk_support, IdealSheaf.stalkIdeal_ofStalks]

/-- The cosupport of the reduced ideal sheaf of an snc divisor is its support. -/
theorem IsSnc.cosupport_idealSheaf (hF : F.IsSnc ψ) :
    (F.idealSheaf (𝕜 := 𝕜) (E := E)).support = F.support := by
  ext x
  rw [IdealSheaf.mem_support, hF.stalkIdeal_idealSheaf]
  constructor
  · intro h
    by_contra hx
    exact h (vanishingStalk_eq_top_of_notMem_closure (by rwa [hF.isClosed_support.closure_eq]))
  · intro hx
    exact vanishingStalk_ne_top_of_mem_closure (by rwa [hF.isClosed_support.closure_eq])

/-- In an snc chart at `a` the reduced ideal sheaf of the divisor is generated at `a` by the
product of the coordinates of the components through `a` ([Hir64, Definition 2, p. 141];
[BM97, Theorem 1.10]). -/
theorem IsSnc.stalkIdeal_idealSheaf_eq_span_prod (hF : F.IsSnc ψ) (hc : F.IsSncChartAt ψ φ a c) :
    F.idealSheaf.stalkIdeal a = Ideal.span {∏ j ∈ (hF.2.1.point_finite a).toFinset.attach,
      coord E ψ φ hc.1 hc.2.1 (c ⟨j.1, (hF.2.1.point_finite a).mem_toFinset.mp j.2⟩)} := by
  rw [hF.stalkIdeal_idealSheaf]
  obtain ⟨V, hV, haV, hVs⟩ := hF.exists_nhds_support_eq a
  exact hc.vanishingStalk_support_eq hF hV hVs hc.2.1 haV _
    fun j => (hF.2.1.point_finite a).mem_toFinset

end HypersurfaceFamily

end Manifold
