/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Snc.Coherence
import Hironaka.Algebra.Local.QuotientParameters
import Hironaka.Algebra.RegularSmooth.ParameterCount
import Hironaka.Algebra.RegularSmooth.QuotientRegular
import Hironaka.Manifold.AdaptedChart
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.Germ.TaylorIdeal
import Hironaka.Manifold.IdealSheaf.Basic
import Hironaka.Manifold.Snc.Spreading
import Hironaka.Manifold.Submanifold.Charts
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Non-singular subspaces are locally closed submanifolds

Hironaka's simple points [Hir64, p. 121]: "by means of the Jacobian criterion and the implicit
function theorem", a point `x` of an analytic `K`-space `X` is simple iff a neighbourhood of `x`
in `X` is isomorphic to an open subset `G` of some `K^d` with its sheaf of analytic functions.
For the closed analytic
subspace `X` of the manifold `M` defined by an ideal sheaf `J` (`IsNonsingular`: every point of the
support has a regular local ring `𝒪_{M,x}/J_x`) this is the dictionary `isNonsingular_iff`: near
every point of its support, `J` is generated by part of the coordinates of a chart adapted to the
support.

* (→): `𝒪_{M,x}` is regular and `𝒪_{M,x}/J_x` is regular, so `J_x` is generated by the first `c`
  members `z_1, …, z_c` of a regular system of parameters `z_1, …, z_m` of `𝒪_{M,x}`
  ([Sta, Tag 00NR];
  `IsRegularLocalRing.exists_span_eq_maximalIdeal_and_eq_span_image_lt`).
  The classes of
  `m` generators of `𝔪_x` in the `m`-dimensional residue-field vector space `𝔪_x/𝔪_x²` are a basis
  (`IsRegularLocalRing.linearIndependent_toCotangent_of_span_eq`), so the `z_j` have independent
  differentials (through the cotangent classes of `Hironaka/Manifold/Chart/Cotangent.lean`,
  after passing from the residue field to `𝕜`), and the chart-extension theorem
  `exists_chart_extending` makes them the coordinates `σ 1, …, σ c` of a chart `e` at `x`. The
  stalk identity `J_x = (z_{σ j})` spreads to a neighbourhood `W` of `x` by the finite generation
  of both sides (`IdealSheaf.exists_opens_stalkIdeal_eq_span`); on `e|_W` the support of `J` is
  the coordinate subspace `{z_{σ j} = 0}` — `J_y ≠ ⊤` iff no `z_{σ j}` is a unit at `y` — so `e|_W`
  is adapted.
* (←): the coordinates `z_{σ j}` vanishing at `x` are part of a regular system of parameters of
  `𝒪_{M,x}` (their classes are part of the basis of `𝔪_x/𝔪_x²` formed by the centred
  coordinates), so `𝒪_{M,x}/(z_{σ j})` is regular
  (`IsRegularLocalRing.quotient_span_range_of_linearIndependent`; [Sta, Tag 00NQ]).

The dictionary is how the non-singularity clause of the main theorems is verified for the centres
and read off on analytic spaces (`Hironaka/AnalyticSpace/SncBoundaryChart.lean`).
-/

public section

open TopologicalSpace Opposite CategoryTheory IsLocalRing Filter Topology
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]

/-! ### From the residue field to `𝕜`: cotangent classes of germs vanishing at the point -/

/-- Germs vanishing at `a` whose classes in `𝔪_a/𝔪_a²` are linearly independent over the residue
field have linearly independent cotangent classes (`cotangentClass`) over `𝕜`: the `𝕜`-action
factors through the residue field, on which `𝕜 → 𝒪_a → 𝒪_a/𝔪_a` is injective. -/
theorem linearIndependent_cotangentClass_of_residueField {a : M} {ι : Type*} [Finite ι]
    (v : ι → (structureSheaf 𝕜 E M).presheaf.stalk a)
    (hv : ∀ i, v i ∈ maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk a))
    (hli : LinearIndependent (ResidueField ((structureSheaf 𝕜 E M).presheaf.stalk a))
      fun i => (maximalIdeal _).toCotangent ⟨v i, hv i⟩) :
    LinearIndependent 𝕜 fun i => cotangentClass E a (v i) := by
  let _ : Fintype ι := Fintype.ofFinite ι
  have hcc : ∀ i, cotangentClass E a (v i) = (maximalIdeal _).toCotangent ⟨v i, hv i⟩ := by
    intro i
    unfold cotangentClass
    congr 1
    ext
    change v i - const 𝕜 E M a (eval 𝕜 E M a (v i)) = v i
    rw [(mem_maximalIdeal_iff_eval E _).mp (hv i), map_zero, sub_zero]
  simp only [hcc]
  rw [Fintype.linearIndependent_iff] at hli ⊢
  intro g hg i
  have h1 : ∀ j, g j • (maximalIdeal _).toCotangent ⟨v j, hv j⟩ =
      Ideal.Quotient.mk (maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk a))
        (const 𝕜 E M a (g j)) • (maximalIdeal _).toCotangent ⟨v j, hv j⟩ := by
    intro j
    rw [← algebraMap_stalk_eq, ← Ideal.Quotient.algebraMap_eq, algebraMap_smul, algebraMap_smul]
  simp_rw [h1] at hg
  have h2 := hli _ hg i
  have h3 : const 𝕜 E M a (g i) ∈ maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk a) :=
    Ideal.Quotient.eq_zero_iff_mem.mp h2
  rw [mem_maximalIdeal_iff_eval, eval_const] at h3
  exact h3

/-! ### The coordinates of a chart as a regular system of parameters -/

section Coordinates

variable (φ : OpenPartialHomeomorph M E) (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {a : M}
  (ha : a ∈ φ.source)

/-- The classes of the centred coordinates `z_i − z_i(a)` form a basis of `𝔪_a/𝔪_a²` over the
residue field (they generate `𝔪_a`, and `dim 𝒪_{M,a} = n`). -/
theorem linearIndependent_toCotangent_coord_sub :
    LinearIndependent (ResidueField ((structureSheaf 𝕜 E M).presheaf.stalk a)) fun i : Fin n =>
      (maximalIdeal _).toCotangent ⟨coord E ψ φ hφ ha i -
        const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ hφ ha i)),
        coord_sub_mem_maximalIdeal E ψ φ ha hφ i⟩ := by
  have hreg := isRegularLocalRing_stalk_of_chart E ψ φ ha hφ
  exact IsRegularLocalRing.linearIndependent_toCotangent_of_span_eq _ _
    (maximalIdeal_eq_span_coord' E ψ φ ha hφ).symm (ringKrullDim_stalk_of_chart E ψ φ ha hφ).symm

/-- The classes of coordinates vanishing at `a` are linearly independent over the residue field
(a subfamily of the basis of the centred coordinates). -/
theorem linearIndependent_toCotangent_coord {c : ℕ} (σ : Fin c ↪ Fin n)
    (h0 : ∀ i, ψ (φ a) (σ i) = 0) :
    LinearIndependent (ResidueField ((structureSheaf 𝕜 E M).presheaf.stalk a)) fun i : Fin c =>
      (maximalIdeal _).toCotangent
        ⟨coord E ψ φ hφ ha (σ i), coord_mem_maximalIdeal_of_eq_zero φ hφ ha (h0 i)⟩ := by
  have h := (linearIndependent_toCotangent_coord_sub φ hφ ha (ψ := ψ)).comp σ σ.injective
  convert h using 1
  funext i
  simp only [Function.comp_apply]
  congr 1
  refine Subtype.ext ?_
  change coord E ψ φ hφ ha (σ i) =
    coord E ψ φ hφ ha (σ i) - const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ hφ ha (σ i)))
  rw [eval_coord, h0 i, map_zero, sub_zero]

/-- The quotient of `𝒪_{M,a}` by coordinates vanishing at `a` is a regular local ring
([Sta, Tag 00NQ]). -/
theorem isRegularLocalRing_quotient_span_coord {c : ℕ} (σ : Fin c ↪ Fin n)
    (h0 : ∀ i, ψ (φ a) (σ i) = 0) :
    IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk a ⧸
      Ideal.span (Set.range fun i => coord E ψ φ hφ ha (σ i))) := by
  have hreg := isRegularLocalRing_stalk_of_chart E ψ φ ha hφ
  exact (IsRegularLocalRing.quotient_span_range_of_linearIndependent _
    (fun i => coord_mem_maximalIdeal_of_eq_zero φ hφ ha (h0 i))
    (linearIndependent_toCotangent_coord φ hφ ha σ h0)).1

end Coordinates

/-! ### The forward direction: a regular quotient stalk gives an adapted chart -/

/-- At a point `x` where `𝒪_{M,x}/J_x` is regular (so `x` lies in the support), there is a chart
adapted to the support of `J` on whose source `J` is generated by the adapted coordinates
([Hir64, p. 121]; [Sta, Tag 00NR], the chart-extension theorem and the spreading of the stalk
identity). -/
theorem exists_adaptedChart_of_isRegularLocalRing_quotient [IsManifold 𝓘(𝕜, E) ω M]
    (J : IdealSheaf (structureSheaf 𝕜 E M)) {x : M}
    (hreg : IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk x ⧸ J.stalkIdeal x)) :
    ∃ (c : ℕ) (φ : OpenPartialHomeomorph M E) (σ : Fin c ↪ Fin n)
      (hφ : IsAdaptedChart ψ J.support φ σ), x ∈ φ.source ∧ ∀ y (hy : y ∈ φ.source),
        J.stalkIdeal y = Ideal.span (Set.range fun i => coord E ψ φ hφ.1 hy (σ i)) := by
  classical
  have _hfd : FiniteDimensional 𝕜 E := ψ.symm.toLinearEquiv.finiteDimensional
  have hreg₀ : IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk x) :=
    isRegularLocalRing_stalk_of_chart E ψ (chartAt E x) (mem_chart_source E x)
      (IsManifold.chart_mem_maximalAtlas x)
  obtain ⟨m, c, z, hcm, hdim, hspan, hI⟩ :=
    IsRegularLocalRing.exists_span_eq_maximalIdeal_and_eq_span_image_lt
      (J.stalkIdeal x)
  have hz : ∀ i, z i ∈ maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk x) := fun i =>
    hspan ▸ Ideal.subset_span ⟨i, rfl⟩
  -- the first `c` parameters generate `J_x`
  let w : Fin c → (structureSheaf 𝕜 E M).presheaf.stalk x := fun j => z (Fin.castLE hcm j)
  have hw : J.stalkIdeal x = Ideal.span (Set.range w) := by
    rw [hI]
    congr 1
    ext s
    constructor
    · rintro ⟨j, hj, rfl⟩
      exact ⟨⟨j.val, hj⟩, congrArg z (Fin.ext rfl)⟩
    · rintro ⟨k, rfl⟩
      exact ⟨Fin.castLE hcm k, k.isLt, rfl⟩
  -- representatives of the parameters as sections
  obtain ⟨U, hxU, g, hg⟩ := exists_sections_of_germs (structureSheaf 𝕜 E M) w
  have hz0 : ∀ j, extendSection 𝕜 E (g j) x = 0 := by
    intro j
    rw [extendSection_of_mem 𝕜 E _ hxU]
    have h1 : eval 𝕜 E M x ((structureSheaf 𝕜 E M).presheaf.germ U x hxU (g j)) = (g j) ⟨x, hxU⟩ :=
      contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω M 𝕜 U x hxU (g j)
    rw [← h1, hg j]
    exact (mem_maximalIdeal_iff_eval E _).mp (hz _)
  have hzc : ∀ j, ContMDiffAt 𝓘(𝕜, E) 𝓘(𝕜) ω (extendSection 𝕜 E (g j)) x := fun j =>
    (contMDiffOn_extendBy0 𝓘(𝕜, E) ω M (g j)).contMDiffAt (U.isOpen.mem_nhds hxU)
  -- independent differentials
  have hliκ := IsRegularLocalRing.linearIndependent_toCotangent_of_span_eq z hz hspan.symm hdim
  have hliw : LinearIndependent (ResidueField ((structureSheaf 𝕜 E M).presheaf.stalk x))
      fun j => (maximalIdeal _).toCotangent ⟨w j, hz _⟩ :=
    hliκ.comp (Fin.castLE hcm) (Fin.castLE_injective hcm)
  have hli𝕜 := linearIndependent_cotangentClass_of_residueField w (fun j => hz _) hliw
  have hind : HasIndependentDifferentialsAt E (fun j => extendSection 𝕜 E (g j)) x := by
    rw [hasIndependentDifferentialsAt_iff_linearIndependent_cotangentClass' E hxU g]
    simpa only [hg] using hli𝕜
  obtain ⟨e, σ, he, hxe, -, hcoord⟩ :=
    exists_chart_extending ψ (fun j => extendSection 𝕜 E (g j)) x hzc hz0 hind
  -- on `e.source ∩ U` the germs of the sections are the coordinates `σ j` of `e`
  have hgerm : ∀ y (hyU : y ∈ U) (hye : y ∈ e.source) j,
      (structureSheaf 𝕜 E M).presheaf.germ U y hyU (g j) = coord E ψ e he hye (σ j) := by
    intro y hyU hye j
    apply stalkToGerm_injective 𝓘(𝕜, E) ω M y
    rw [stalkToGerm_structureSheaf_germ, stalkToGerm_coord, Germ.coe_eq]
    filter_upwards [(e.open_source.inter U.isOpen).mem_nhds ⟨hye, hyU⟩] with y' hy'
    have h1 : extendSection 𝕜 E (g j) y' = ψ (e y') (σ j) := hcoord y' hy'.1 j
    rw [h1, extendSection_of_mem 𝕜 E _ hy'.1]
    rfl
  -- the stalk identity spreads to a neighbourhood `W` of `x`
  have hJx : J.stalkIdeal x = Ideal.span (Set.range fun j =>
      (structureSheaf 𝕜 E M).presheaf.germ U x hxU (g j)) := by
    rw [hw]
    congr 1
    ext s
    simp only [Set.mem_range, hg]
  obtain ⟨W, hxW, hWU, hW⟩ := J.exists_opens_stalkIdeal_eq_span hxU g hJx
  -- the chart `e` restricted to `W`
  have he' : e.restrOpen (W : Set M) W.isOpen ∈ maximalAtlas 𝓘(𝕜, E) ω M := by
    rw [OpenPartialHomeomorph.restrOpen_eq_restr]
    exact restr_mem_maximalAtlas _ he W.isOpen
  have hcoord' : ∀ y (hy : y ∈ (e.restrOpen (W : Set M) W.isOpen).source) j,
      coord E ψ (e.restrOpen (W : Set M) W.isOpen) he' hy (σ j) =
        coord E ψ e he (hy.1 : y ∈ e.source) (σ j) := by
    intro y hy j
    apply stalkToGerm_injective 𝓘(𝕜, E) ω M y
    rw [stalkToGerm_coord, stalkToGerm_coord, Germ.coe_eq]
    filter_upwards [(e.restrOpen (W : Set M) W.isOpen).open_source.mem_nhds hy] with y' hy'
    rw [extendSection_of_mem 𝕜 E _ hy', extendSection_of_mem 𝕜 E _ (hy'.1 : y' ∈ e.source)]
    rfl
  have hstalk : ∀ y (hy : y ∈ (e.restrOpen (W : Set M) W.isOpen).source),
      J.stalkIdeal y = Ideal.span (Set.range fun j =>
        coord E ψ (e.restrOpen (W : Set M) W.isOpen) he' hy (σ j)) := by
    intro y hy
    have hyW : y ∈ W := hy.2
    rw [hW y hyW]
    congr 1
    exact congrArg Set.range (funext fun j => by
      rw [hcoord' y hy j, hgerm y (hWU hyW) hy.1 j])
  have hadapt : IsAdaptedChart ψ J.support (e.restrOpen (W : Set M) W.isOpen) σ := by
    refine ⟨he', fun y hy => ?_⟩
    rw [IdealSheaf.mem_support, hstalk y hy, ne_eq, Ideal.span_eq_top_iff_exists_isUnit]
    constructor
    · intro h i
      by_contra h0
      exact h ⟨_, ⟨i, rfl⟩, isUnit_coord_of_ne_zero _ he' hy h0⟩
    · rintro h ⟨_, ⟨i, rfl⟩, hu⟩
      have h1 := IsLocalRing.notMem_maximalIdeal.mpr hu
      rw [mem_maximalIdeal_iff_eval, eval_coord] at h1
      exact h1 (h i)
  exact ⟨c, e.restrOpen (W : Set M) W.isOpen, σ, hadapt, ⟨hxe, hxW⟩, hstalk⟩

/-! ### The dictionary on bundled manifolds -/

/-- Hironaka's simple points, by the Jacobian criterion and the implicit function theorem
[Hir64, p. 121]: the subspace defined by `J` is non-singular iff, near every point of it, `J` is
the ideal sheaf of a closed submanifold — for some codimension `c` and a chart adapted to the
support, the stalks of `J` at every point of the chart's source are spanned by the adapted
coordinates. -/
theorem isNonsingular_iff {N : AnalyticManifold.{u} 𝕜 E}
    (J : AnalyticManifold.IdealSheaf N) :
    J.IsNonsingular ↔ ∀ x ∈ J.support, ∃ (c : ℕ) (φ : OpenPartialHomeomorph N E)
      (σ : Fin c ↪ Fin n) (hφ : IsAdaptedChart ψ J.support φ σ), x ∈ φ.source ∧
        ∀ y (hy : y ∈ φ.source),
          J.stalkIdeal y = Ideal.span (Set.range fun i => coord E ψ φ hφ.1 hy (σ i)) := by
  constructor
  · intro hJ x hx
    exact exists_adaptedChart_of_isRegularLocalRing_quotient J (hJ x hx)
  · intro h x hx
    obtain ⟨c, φ, σ, hφ, hxφ, hJ⟩ := h x hx
    rw [hJ x hxφ]
    exact isRegularLocalRing_quotient_span_coord φ hφ.1 hxφ σ fun i => (hφ.2 x hxφ).mp hx i

end Manifold
