/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Snc.Basic
public import Hironaka.Manifold.StructureSheaf
import Hironaka.Algebra.Local.PrimeProducts
import Hironaka.Algebra.Local.Regular
import Hironaka.Algebra.RegularSmooth.ParameterCount
import Hironaka.Manifold.AdaptedChart
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.Snc.Dictionary
import Hironaka.Manifold.Snc.NonSingular
import Hironaka.Manifold.Snc.Spreading
import Hironaka.Manifold.Submanifold.Charts
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Hironaka's normal crossings with a centre are Kollár's

The direction Hironaka's Definition 2 [Hir64, Definition 2, p. 141] → [Kol07, Definition 24 (4)]
of the dictionary `hasOnlyNormalCrossingsWith_idealSheaf_iff` (the other direction is in
`Hironaka/Manifold/Snc/Dictionary.lean`). At a point `x` of the closed submanifold `Y`,
Definition 2 gives a regular system of parameters `z_1, …, z_m` of `𝒪_{M,x}` such that every
minimal prime of the stalk `E_x` of the reduced ideal sheaf of the snc divisor `F` is some `(z_i)`
and the ideal `(𝓘_Y)_x` is generated by the `z_i`, `i ∈ s`. Then:

* the `z_i` are the coordinates of a chart `e` at `x` (the chart-extension theorem
  `exists_chart_extending`, as in `Hironaka/Manifold/Snc/NonSingular.lean`);
* `(𝓘_Y)_x` is also generated by the `c` adapted coordinates of a chart of `Y` at `x`; two families
  of parameters generating the same ideal have the same size
  (`IsRegularLocalRing.card_eq_of_span_range_eq`, the dimension count of [Sta, Tag 00NQ] applied
  twice), so `|s| = c`; the identity `(𝓘_Y)_y = (z_i)_{i∈s}` spreads to a neighbourhood
  (`exists_opens_stalkIdeal_eq_span`), where `Y = {z_i = 0, i ∈ s}`, so `e` restricted there is
  adapted to `Y` with the block `s`;
* in the snc chart `φ` of `F` at `x`, `E_x = (∏_{j : x ∈ E^j} w_j)` with `w_j` the coordinate of
  the component `E^j` (`Hironaka/Manifold/Snc/Coherence.lean`); each `(w_j)` is a minimal prime
  of `E_x` (`IsLocalRing.mem_minimalPrimes_span_prod`), hence `(w_j) = (z_{i_j})`, i.e. `w_j`
  and `z_{i_j}` are associated; a unit germ is a nowhere-vanishing function near `x`, so
  `E^j = {w_j = 0} = {z_{i_j} = 0}` near `x` (`exists_nhds_coord_eq_zero_iff_of_associated`), and
  `e` is an snc chart of `F` at `x` with the indices `i_j` (injective, because distinct `w_j` are
  not associated).

With `Hironaka/Manifold/Snc/Dictionary.lean` this shows that, for the reduced ideal sheaf of an
snc family, Hironaka's stalk-local normal crossings with a centre is exactly Kollár's simple normal
crossings with it; the two readings of normal crossings differ only for boundaries that are not
given by an snc family.
-/

public section

open TopologicalSpace Opposite CategoryTheory IsLocalRing Filter Topology
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]

/-! ### A unit germ is a nowhere-vanishing function near the point -/

/-- If the coordinate `z_k` of a chart at `x` and the germ of a section `g` are associated in
`𝒪_{M,x}`, then near `x` the zero sets of `z_k` and of `g` coincide: the unit relating them is a
function without zeros near `x`. -/
theorem exists_nhds_coord_eq_zero_iff_of_associated (φ : OpenPartialHomeomorph M E)
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {x : M} (hx : x ∈ φ.source) (k : Fin n) {U : Opens M}
    (hxU : x ∈ U) (g : (structureSheaf 𝕜 E M).presheaf.obj (op U))
    (hassoc : Associated (coord E ψ φ hφ hx k) ((structureSheaf 𝕜 E M).presheaf.germ U x hxU g)) :
    ∃ V : Set M, IsOpen V ∧ x ∈ V ∧ V ⊆ φ.source ∧ V ⊆ U ∧
      ∀ y ∈ V, (ψ (φ y) k = 0 ↔ extendSection 𝕜 E g y = 0) := by
  obtain ⟨u, hu⟩ := hassoc
  obtain ⟨Va, hxVa, a, ha⟩ := (structureSheaf 𝕜 E M).presheaf.exists_germ_eq
    (u : (structureSheaf 𝕜 E M).presheaf.stalk x)
  let Q : Opens M := ⟨φ.source ∩ (Va : Set M) ∩ U, (φ.open_source.inter Va.2).inter U.2⟩
  have hxQ : x ∈ Q := ⟨⟨hx, hxVa⟩, hxU⟩
  have hQφ : Q ≤ ⟨φ.source, φ.open_source⟩ := fun _ h => h.1.1
  have hQa : Q ≤ Va := fun _ h => h.1.2
  have hQU : Q ≤ U := fun _ h => h.2
  -- the identity `z_k · a = g` of germs at `x`, as sections over `Q`
  have hgerm : (structureSheaf 𝕜 E M).presheaf.germ Q x hxQ
      ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hQφ).op (chartSection E ψ φ hφ k) *
        (structureSheaf 𝕜 E M).presheaf.map (homOfLE hQa).op a) =
      (structureSheaf 𝕜 E M).presheaf.germ Q x hxQ
        ((structureSheaf 𝕜 E M).presheaf.map (homOfLE hQU).op g) := by
    rw [map_mul, TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply,
      TopCat.Presheaf.germ_res_apply, ha]
    exact hu
  obtain ⟨W, hxW, iQ, iQ', hW⟩ := (structureSheaf 𝕜 E M).presheaf.germ_eq x hxQ hxQ _ _ hgerm
  -- the values on `W`
  have hval : ∀ y (hy : y ∈ W), ψ (φ y) k * extendSection 𝕜 E a y = extendSection 𝕜 E g y := by
    intro y hy
    have hyφ : y ∈ φ.source := hQφ (iQ.le hy)
    have hya : y ∈ Va := hQa (iQ.le hy)
    have hyU : y ∈ U := hQU (iQ.le hy)
    have hW' := congrArg ((structureSheaf 𝕜 E M).presheaf.germ W y hy) hW
    rw [TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply, map_mul,
      TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply,
      TopCat.Presheaf.germ_res_apply] at hW'
    have h1 := congrArg (eval 𝕜 E M y) hW'
    rw [map_mul] at h1
    have e1 : eval 𝕜 E M y ((structureSheaf 𝕜 E M).presheaf.germ ⟨φ.source, φ.open_source⟩ y hyφ
        (chartSection E ψ φ hφ k)) = ψ (φ y) k := eval_coord E ψ φ hyφ hφ k
    have e2 : eval 𝕜 E M y ((structureSheaf 𝕜 E M).presheaf.germ Va y hya a) =
        extendSection 𝕜 E a y := by
      rw [extendSection_of_mem 𝕜 E a hya]
      exact contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω M 𝕜 Va y hya a
    have e3 : eval 𝕜 E M y ((structureSheaf 𝕜 E M).presheaf.germ U y hyU g) =
        extendSection 𝕜 E g y := by
      rw [extendSection_of_mem 𝕜 E g hyU]
      exact contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω M 𝕜 U y hyU g
    rw [e1, e2, e3] at h1
    exact h1
  -- `a` does not vanish near `x`
  have hax : extendSection 𝕜 E a x ≠ 0 := by
    rw [extendSection_of_mem 𝕜 E a hxVa]
    have h1 : eval 𝕜 E M x ((structureSheaf 𝕜 E M).presheaf.germ Va x hxVa a) = a ⟨x, hxVa⟩ :=
      contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω M 𝕜 Va x hxVa a
    rw [← h1, ha]
    have h2 := IsLocalRing.notMem_maximalIdeal.mpr u.isUnit
    rwa [mem_maximalIdeal_iff_eval] at h2
  have hcont : ContinuousAt (extendSection 𝕜 E a) x :=
    (contMDiffOn_extendBy0 𝓘(𝕜, E) ω M a).continuousOn.continuousAt (Va.isOpen.mem_nhds hxVa)
  obtain ⟨T, hT, hTo, hxT⟩ := eventually_nhds_iff.mp (hcont.eventually_ne hax)
  refine ⟨(W : Set M) ∩ T, W.isOpen.inter hTo, ⟨hxW, hxT⟩, fun y hy => hQφ (iQ.le hy.1),
    fun y hy => hQU (iQ.le hy.1), fun y hy => ?_⟩
  have h1 := hval y hy.1
  have h2 := hT y hy.2
  constructor
  · intro h0
    rw [← h1, h0, zero_mul]
  · intro h0
    rw [h0] at h1
    exact (mul_eq_zero.mp h1).resolve_right h2

/-! ### The converse dictionary -/

namespace HypersurfaceFamily

variable {F : HypersurfaceFamily M} {Y : Set M} {c : ℕ}

/-- Hironaka's Definition 2 → [Kol07, Definition 24 (4)]: at a point `x` of the closed submanifold
`Y`, a regular system of parameters `z` of `𝒪_{M,x}` whose members generate the minimal primes of
`(F.idealSheaf)_x` and, for `i ∈ s`, the ideal `(𝓘_Y)_x`, yields a chart adapted to `Y` which is
an snc chart of `F` at `x`. -/
theorem exists_adaptedChart_isSncChartAt_of_parameters [IsManifold 𝓘(𝕜, E) ω M] (hF : F.IsSnc ψ)
    (hY : IsClosedSubmanifold ψ Y c) {x : M} (hxY : x ∈ Y) {m : ℕ}
    (z : Fin m → (structureSheaf 𝕜 E M).presheaf.stalk x)
    (hspan : Ideal.span (Set.range z) = maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk x))
    (hdim : (m : WithBot ℕ∞) = ringKrullDim ((structureSheaf 𝕜 E M).presheaf.stalk x))
    (hmin : ∀ P ∈ ((F.idealSheaf (𝕜 := 𝕜) (E := E)).stalkIdeal x).minimalPrimes,
      ∃ i, P = Ideal.span {z i})
    (s : Finset (Fin m)) (hD : hY.idealSheaf.stalkIdeal x = Ideal.span (z '' ↑s)) :
    ∃ (φ : OpenPartialHomeomorph M E) (σ : Fin c ↪ Fin n) (cidx : {j // x ∈ F.hyp j} → Fin n),
      IsAdaptedChart ψ Y φ σ ∧ F.IsSncChartAt ψ φ x cidx := by
  classical
  have _hfd : FiniteDimensional 𝕜 E := ψ.symm.toLinearEquiv.finiteDimensional
  have : Finite {j // x ∈ F.hyp j} := (hF.2.1.point_finite x).to_subtype
  obtain ⟨φ, cF, hc⟩ := hF.exists_isSncChartAt x
  have hxφ : x ∈ φ.source := hc.2.1
  have hreg₀ : IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk x) :=
    isRegularLocalRing_stalk_of_chart E ψ φ hxφ hc.1
  have hz : ∀ i, z i ∈ maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk x) := fun i =>
    hspan ▸ Ideal.subset_span ⟨i, rfl⟩
  have hliκ := IsRegularLocalRing.linearIndependent_toCotangent_of_span_eq z hz hspan hdim
  -- the parameters as the coordinates of a chart `e` at `x`
  obtain ⟨U, hxU, g, hg⟩ := exists_sections_of_germs (structureSheaf 𝕜 E M) z
  have hz0 : ∀ i, extendSection 𝕜 E (g i) x = 0 := by
    intro i
    rw [extendSection_of_mem 𝕜 E _ hxU]
    have h1 : eval 𝕜 E M x ((structureSheaf 𝕜 E M).presheaf.germ U x hxU (g i)) = (g i) ⟨x, hxU⟩ :=
      contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω M 𝕜 U x hxU (g i)
    rw [← h1, hg i]
    exact (mem_maximalIdeal_iff_eval E _).mp (hz i)
  have hzc : ∀ i, ContMDiffAt 𝓘(𝕜, E) 𝓘(𝕜) ω (extendSection 𝕜 E (g i)) x := fun i =>
    (contMDiffOn_extendBy0 𝓘(𝕜, E) ω M (g i)).contMDiffAt (U.isOpen.mem_nhds hxU)
  have hind : HasIndependentDifferentialsAt E (fun i => extendSection 𝕜 E (g i)) x := by
    rw [hasIndependentDifferentialsAt_iff_linearIndependent_cotangentClass' E hxU g]
    simpa only [hg] using linearIndependent_cotangentClass_of_residueField z hz hliκ
  obtain ⟨e, σ₀, he, hxe, -, hcoord⟩ :=
    exists_chart_extending ψ (fun i => extendSection 𝕜 E (g i)) x hzc hz0 hind
  have hgerm : ∀ y (hyU : y ∈ U) (hye : y ∈ e.source) i,
      (structureSheaf 𝕜 E M).presheaf.germ U y hyU (g i) = coord E ψ e he hye (σ₀ i) := by
    intro y hyU hye i
    apply stalkToGerm_injective 𝓘(𝕜, E) ω M y
    rw [stalkToGerm_structureSheaf_germ, stalkToGerm_coord, Germ.coe_eq]
    filter_upwards [(e.open_source.inter U.isOpen).mem_nhds ⟨hye, hyU⟩] with y' hy'
    have h1 : extendSection 𝕜 E (g i) y' = ψ (e y') (σ₀ i) := hcoord y' hy'.1 i
    rw [h1, extendSection_of_mem 𝕜 E _ hy'.1]
    rfl
  -- (1) the centre: the block `s` has `c` members, and `Y = {z_i = 0, i ∈ s}` near `x`
  obtain ⟨φY, σY, hxφY, hφY⟩ := hY.exists_adaptedChart x hxY
  have hDx : hY.idealSheaf.stalkIdeal x =
      Ideal.span (Set.range fun i => coord E ψ φY hφY.1 hxφY (σY i)) :=
    hY.isIdealSheafOf_idealSheaf.2 φY σY hφY x hxφY hxY
  have hDs : hY.idealSheaf.stalkIdeal x = Ideal.span (Set.range fun j : s => z j.1) := by
    rw [hD]
    congr 1
    ext w
    simp only [Set.mem_image, Finset.mem_coe, Set.mem_range, Subtype.exists, exists_prop]
  have hY0 : ∀ i, ψ (φY x) (σY i) = 0 := (hφY.2 x hxφY).mp hxY
  have hcs : s.card = c := by
    have h1 := IsRegularLocalRing.card_eq_of_span_range_eq (fun j : s => z j.1)
      (fun i => coord E ψ φY hφY.1 hxφY (σY i)) (fun j => hz j.1)
      (fun i => coord_mem_maximalIdeal_of_eq_zero φY hφY.1 hxφY (hY0 i))
      (hliκ.comp Subtype.val Subtype.val_injective)
      (linearIndependent_toCotangent_coord φY hφY.1 hxφY σY hY0) (by rw [← hDs, ← hDx])
    simpa only [Fintype.card_coe, Fintype.card_fin] using h1
  have hDx' : hY.idealSheaf.stalkIdeal x = Ideal.span (Set.range fun j : s =>
      (structureSheaf 𝕜 E M).presheaf.germ U x hxU (g j.1)) := by
    rw [hDs]
    congr 1
    ext w
    simp only [Set.mem_range, hg]
  obtain ⟨WD, hxWD, hWDU, hWD⟩ :=
    hY.idealSheaf.exists_opens_stalkIdeal_eq_span hxU (fun j : s => g j.1) hDx'
  -- (2) the components through `x`: their coordinates are associated to parameters
  have hEx := hF.stalkIdeal_idealSheaf_eq_span_prod hc
  have hminj : ∀ j : {j // x ∈ F.hyp j},
      ∃ i, Ideal.span {coord E ψ φ hc.1 hc.2.1 (cF j)} = Ideal.span {z i} := by
    intro j
    have hjS : (⟨j.1, (hF.2.1.point_finite x).mem_toFinset.mpr j.2⟩ :
        {k // k ∈ (hF.2.1.point_finite x).toFinset}) ∈ (hF.2.1.point_finite x).toFinset.attach :=
      Finset.mem_attach _ _
    have hmem := mem_minimalPrimes_span_prod
      (p := fun k : {k // k ∈ (hF.2.1.point_finite x).toFinset} =>
        coord E ψ φ hc.1 hc.2.1 (cF ⟨k.1, (hF.2.1.point_finite x).mem_toFinset.mp k.2⟩))
      (fun k _ => hc.prime_coord _)
      (fun k _ k' _ hkk' => hc.not_coord_dvd fun h => hkk' (by
        have h2 := congrArg Subtype.val h
        exact Subtype.ext (show k.1 = k'.1 from h2)))
      hjS
    rw [← hEx] at hmem
    exact hmin _ hmem
  choose idx hidx using hminj
  have hassoc : ∀ j : {j // x ∈ F.hyp j}, Associated (coord E ψ φ hc.1 hc.2.1 (cF j))
      ((structureSheaf 𝕜 E M).presheaf.germ U x hxU (g (idx j))) := fun j => by
    have h := Ideal.span_singleton_eq_span_singleton.mp (hidx j)
    rwa [← hg (idx j)] at h
  have hnbhd : ∀ j : {j // x ∈ F.hyp j}, ∃ V : Set M, IsOpen V ∧ x ∈ V ∧ V ⊆ φ.source ∧ V ⊆ U ∧
      ∀ y ∈ V, (ψ (φ y) (cF j) = 0 ↔ extendSection 𝕜 E (g (idx j)) y = 0) := fun j =>
    exists_nhds_coord_eq_zero_iff_of_associated φ hc.1 hc.2.1 (cF j) hxU (g (idx j)) (hassoc j)
  choose V hVo hxV hVφ hVU hV using hnbhd
  -- (3) the neighbourhood and the chart
  let N : Set M := e.source ∩ (WD : Set M) ∩ ⋂ j, V j
  have hNo : IsOpen N := (e.open_source.inter WD.isOpen).inter (isOpen_iInter_of_finite hVo)
  have hxN : x ∈ N := ⟨⟨hxe, hxWD⟩, Set.mem_iInter.mpr hxV⟩
  have he' : e.restrOpen N hNo ∈ maximalAtlas 𝓘(𝕜, E) ω M := by
    rw [OpenPartialHomeomorph.restrOpen_eq_restr]
    exact restr_mem_maximalAtlas _ he hNo
  have hxe' : x ∈ (e.restrOpen N hNo).source := ⟨hxe, hxN⟩
  -- adapted to `Y` with the block `s`
  have hadapt : IsAdaptedChart ψ Y (e.restrOpen N hNo)
      ((s.orderEmbOfFin hcs).toEmbedding.trans σ₀) := by
    refine ⟨he', fun y hy => ?_⟩
    have hyW : y ∈ WD := hy.2.1.2
    have hyU : y ∈ U := hWDU hyW
    have hye : y ∈ e.source := hy.2.1.1
    have hmemY : y ∈ Y ↔ hY.idealSheaf.stalkIdeal y ≠ ⊤ := by
      rw [← IdealSheaf.mem_support, hY.cosupport_idealSheaf]
    rw [hmemY, hWD y hyW, ne_eq, Ideal.span_eq_top_iff_exists_isUnit]
    have hu : ∀ j : s, IsUnit ((structureSheaf 𝕜 E M).presheaf.germ U y hyU (g j.1)) ↔
        ψ (e y) (σ₀ j.1) ≠ 0 := fun j => by
      rw [hgerm y hyU hye j.1, ← IsLocalRing.notMem_maximalIdeal, mem_maximalIdeal_iff_eval,
        eval_coord]
    constructor
    · intro h i
      by_contra h0
      have hmem : s.orderEmbOfFin hcs i ∈ s := s.orderEmbOfFin_mem hcs i
      exact h ⟨_, ⟨⟨_, hmem⟩, rfl⟩, (hu ⟨_, hmem⟩).mpr h0⟩
    · rintro h ⟨_, ⟨j, rfl⟩, hunit⟩
      have hj : (j : Fin m) ∈ Set.range (s.orderEmbOfFin hcs) := by
        rw [s.range_orderEmbOfFin hcs]
        exact j.2
      obtain ⟨i, hi⟩ := hj
      apply (hu j).mp hunit
      have h1 := h i
      change ψ (e y) (σ₀ (s.orderEmbOfFin hcs i)) = 0 at h1
      rwa [hi] at h1
  -- an snc chart of `F` at `x`
  have hsnc : F.IsSncChartAt ψ (e.restrOpen N hNo) x fun j => σ₀ (idx j) := by
    refine ⟨he', hxe', fun j y hy => ?_, fun j j' hjj' => ?_⟩
    · have hyN : y ∈ N := hy.2
      have hyV : y ∈ V j := Set.mem_iInter.mp hyN.2 j
      have h1 : extendSection 𝕜 E (g (idx j)) y = ψ (e y) (σ₀ (idx j)) := hcoord y hyN.1.1 (idx j)
      rw [hc.mem_iff j (hVφ j hyV), hV j y hyV, h1]
      exact Iff.rfl
    · have h1 : idx j = idx j' := σ₀.injective hjj'
      have h2 : Ideal.span {coord E ψ φ hc.1 hc.2.1 (cF j)} =
          Ideal.span {coord E ψ φ hc.1 hc.2.1 (cF j')} := by
        rw [hidx j, hidx j', h1]
      by_contra hne
      exact hc.not_coord_dvd (Ne.symm hne) (Ideal.span_singleton_le_span_singleton.mp h2.le)
  exact ⟨e.restrOpen N hNo, _, _, hadapt, hsnc⟩

end HypersurfaceFamily

/-- Hironaka's Definition 2 ↔ [Kol07, Definition 24 (4)]: the reduced ideal sheaf of an snc divisor
has only normal crossings with the ideal sheaf of a closed submanifold `Y` in Hironaka's sense
[Hir64, Definition 2, p. 141] iff `Y` has simple normal crossings with the family of
components. -/
theorem hasOnlyNormalCrossingsWith_idealSheaf_iff
    {N : AnalyticManifold.{u} 𝕜 E}
    {F : HypersurfaceFamily N} (hF : F.IsSnc ψ) {Y : Set N} {c : ℕ}
    (hY : IsClosedSubmanifold ψ Y c) :
    AnalyticManifold.IdealSheaf.HasOnlyNormalCrossingsWith (F.idealSheaf (𝕜 := 𝕜) (E := E))
      hY.idealSheaf ↔ F.HasSncWith ψ Y c := by
  refine ⟨fun h x hxY => ?_,
    fun hsnc => HasSncWith.hasOnlyNormalCrossingsWith_idealSheaf hF hY hsnc⟩
  have hx : x ∈ IdealSheaf.support hY.idealSheaf := by
    rw [hY.cosupport_idealSheaf]
    exact hxY
  obtain ⟨m, z, ⟨hspan, hdim⟩, hmin, s, hD⟩ := h x hx
  exact HypersurfaceFamily.exists_adaptedChart_isSncChartAt_of_parameters hF hY hxY z hspan hdim
    hmin s hD

end Manifold
