/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.Ideal.Span
public import Mathlib.RingTheory.LocalRing.Defs
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic

/-!
# An invertible ideal generated by finitely many elements is generated by one of them

In a local ring `R`, an ideal generated by a non-zero-divisor `a` and also by a finite family
`z₁, …, z_c` is generated by one of the `zᵢ`, which is `a` times a unit. Not in the sources; it is
the ring-theoretic step of the universal property of the monoidal transformation
[Hir64, Ch. 0, §2]: at a point `y` of a space `Y'` mapping to the centre `C`, the inverse image
ideal of `C` in `𝒪_{Y',y}` is generated by the pulled-back coordinates `z₁ ∘ f', …, z_c ∘ f'` of
the centre and, being invertible, also by one non-zero-divisor `a`; the lemma picks the coordinate
that generates it.

The argument: writing `a = Σ bᵢ zᵢ` and `zᵢ = aᵢ a` gives `(Σ bᵢ aᵢ) a = a`, so `Σ bᵢ aᵢ = 1`
because `a` is a non-zero-divisor; in a local ring one summand `bᵢ aᵢ` is then a unit, so `aᵢ`
is a unit and `zᵢ = aᵢ a` generates the ideal.

`AlgebraicGeometry.exists_span_singleton_eq_of_span_range_eq` is the special case of a local domain
and a nonzero generator (there every nonzero element is a non-zero-divisor); the local rings of a
general analytic space are not domains, so the non-zero-divisor form is the one used for the
uniqueness of monoidal transformations of analytic spaces.
-/

public section

namespace Algebra

/-- In a local ring, an ideal generated by a non-zero-divisor `a` and also by finitely many
elements `z i` is generated by one of the `z i`, which is `a` times a unit. Not in the sources;
the non-zero-divisor form of `AlgebraicGeometry.exists_span_singleton_eq_of_span_range_eq`, which
assumes a local domain. -/
theorem exists_unit_mul_eq_of_span_range_eq_span_singleton {R : Type*} [CommRing R] [IsLocalRing R]
    {ι : Type*} [Finite ι] (z : ι → R) (a : R) (ha : a ∈ nonZeroDivisors R)
    (h : Ideal.span (Set.range z) = Ideal.span {a}) :
    ∃ (i : ι) (u : R), IsUnit u ∧ z i = u * a := by
  cases nonempty_fintype ι
  have hmem : a ∈ Ideal.span (Set.range z) := h ▸ Ideal.mem_span_singleton_self a
  obtain ⟨b, hb⟩ := Ideal.mem_span_range_iff_exists_fun.mp hmem
  have hz : ∀ i, ∃ c, c * a = z i := fun i =>
    Ideal.mem_span_singleton'.mp (h ▸ Ideal.subset_span ⟨i, rfl⟩)
  choose c hc using hz
  have key : (∑ i, b i * c i) * a = a := by
    rw [Finset.sum_mul]
    calc ∑ i, b i * c i * a = ∑ i, b i * z i := by
          refine Finset.sum_congr rfl fun i _ => ?_
          rw [mul_assoc, hc i]
      _ = a := hb
  have hsum : ∑ i, b i * c i = 1 := by
    have : (∑ i, b i * c i - 1) * a = 0 := by rw [sub_mul, key, one_mul, sub_self]
    exact sub_eq_zero.mp ((mem_nonZeroDivisors_iff.mp ha).2 _ this)
  by_contra hne
  push Not at hne
  have hall : ∀ i, b i * c i ∈ IsLocalRing.maximalIdeal R := by
    intro i
    by_contra hi
    have hu : IsUnit (b i * c i) := by
      rwa [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, not_not] at hi
    exact hne i (c i) (isUnit_of_mul_isUnit_right hu) (hc i).symm
  have : (1 : R) ∈ IsLocalRing.maximalIdeal R := hsum ▸ Submodule.sum_mem _ fun i _ => hall i
  exact (IsLocalRing.maximalIdeal.isMaximal R).ne_top ((Ideal.eq_top_iff_one _).mpr this)

end Algebra
