/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.BlowUp.Defs
import Hironaka.Manifold.BlowUp.Lift
import Hironaka.Manifold.BlowUp.Transition
import Hironaka.Manifold.IdealSheaf.Pullback
import Hironaka.Manifold.LocalDiffeomorph
import Hironaka.Manifold.Sheaf.LocalRing
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The exceptional divisor and the degenerate centres

For any blowing-up `π : M' → M` with centre `Y` in the sense of `IsBlowUp` [BM88, Definition 4.1]:

* **The exceptional divisor.** In a blow-up chart of index `i` the exceptional divisor
  `F = π⁻¹(Y)` is the hyperplane `{u_i = 0}` (`IsBlowUpChart.mem_preimage_iff`), so `F` is a
  closed submanifold of codimension one (`IsBlowUp.isClosedSubmanifold_preimage`; the exceptional
  divisor of a smooth blow-up is smooth, [Kol07, Notation 19]). The pullback of the ideal sheaf
  of `Y` is the ideal sheaf of `F`: its stalk at a point of a blow-up chart is generated by the
  germ of `u_i` (since `z_i ∘ π = u_i` and `z_j ∘ π = u_i u_j`;
  `IsBlowUp.stalkIdeal_pullback_eq_span_coord`), and this is the ideal of `F` in every adapted
  chart of `F`, because the kernel of the restriction of germs to `F` is generated by the adapted
  coordinate (`IsClosedSubmanifold.ker_restrictStalk`); hence `IsBlowUp.isIdealSheafOf_pullback`.
* **The degenerate centres.** For a centre of codimension one, or an empty centre, the blowing-up
  is a diffeomorphism (the trivial and the empty blow-up of [Kol07, Warning 20]): it is a
  bijective local diffeomorphism (`IsLocalDiffeomorph.toDiffeomorphOfBijective`). For `c = 1` the
  single chart map `π_0` is the identity, `π` reads `φ⁻¹ ∘ Φ` in a blow-up chart, and two blow-up
  charts over one adapted chart have inverses agreeing off the hyperplane, hence everywhere by
  density.

These results enter the uniqueness of the blowing-up (`Hironaka.Manifold.BlowUp.Unique`) and
the transforms of ideal sheaves under it.
-/

@[expose] public section

open TopologicalSpace Topology Filter Opposite CategoryTheory
open scoped Manifold ContDiff Topology
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)}

/-- The block embedding `Fin 1 ↪ Fin n` with value `j`. -/
def singleEmb (j : Fin n) : Fin 1 ↪ Fin n := ⟨fun _ => j, fun _ _ _ => Subsingleton.elim _ _⟩

/-- The one-element embedding `Fin 1 ↪ Fin n` picks the index `j`. -/
@[simp] theorem singleEmb_apply (j : Fin n) (k : Fin 1) : singleEmb j k = j := rfl

/-- For `c = 1` the single chart map is the identity. -/
theorem blowUpChartMap_fin_one (σ : Fin 1 ↪ Fin n) (i : Fin 1) :
    blowUpChartMap (𝕜 := 𝕜) σ i = id := by
  funext u j
  rcases exists_eq_or_forall_ne σ j with ⟨l, rfl⟩ | hj
  · obtain rfl : l = i := Subsingleton.elim l i
    exact blowUpChartMap_apply_scaling σ u
  · exact blowUpChartMap_apply_off σ u hj

variable {M : Type u} [TopologicalSpace M] {Y : Set M} {c : ℕ} {M' : Type u} [TopologicalSpace M']
  [ChartedSpace E M'] {π : M' → M}

/-! ### Blow-up charts for `c = 1` -/

section FinOne

variable {φ : OpenPartialHomeomorph M E} {σ : Fin 1 ↪ Fin n} {i : Fin 1}
  {Φ : OpenPartialHomeomorph M' E}

/-- For `c = 1` a blow-up chart has the target of the adapted chart. -/
theorem IsBlowUpChart.target_eq_of_fin_one (hΦ : IsBlowUpChart ψ π φ σ i Φ) :
    Φ.target = φ.target := by
  ext v
  rw [hΦ.mem_target_iff, blowUpChartMap_fin_one, id, ψ.injective.mem_set_image]

/-- For `c = 1`, `φ ∘ π = Φ` on the source of a blow-up chart. -/
theorem IsBlowUpChart.apply_eq_of_fin_one (hΦ : IsBlowUpChart ψ π φ σ i Φ) {p : M'}
    (hp : p ∈ Φ.source) : φ (π p) = Φ p := by
  have h := hΦ.comm p hp
  rw [blowUpChartMap_fin_one, id] at h
  exact ψ.injective h

/-- For `c = 1`, `π = φ⁻¹ ∘ Φ` on the source of a blow-up chart. -/
theorem IsBlowUpChart.symm_apply_eq_of_fin_one (hΦ : IsBlowUpChart ψ π φ σ i Φ) {p : M'}
    (hp : p ∈ Φ.source) : φ.symm (Φ p) = π p := by
  rw [← hΦ.apply_eq_of_fin_one hp, φ.left_inv (hΦ.source_subset hp)]

end FinOne

variable [ChartedSpace E M]

/-! ### The exceptional divisor -/

section Divisor

variable {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} {i : Fin c}
  {Φ : OpenPartialHomeomorph M' E} {p : M'}

/-- In a blow-up chart of index `i` the exceptional divisor `F = π⁻¹(Y)` is the hyperplane
`{u_i = 0}`. -/
theorem IsBlowUpChart.mem_preimage_iff (hφ : IsAdaptedChart ψ Y φ σ)
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) (hp : p ∈ Φ.source) :
    p ∈ π ⁻¹' Y ↔ ψ (Φ p) (σ i) = 0 := by
  rw [Set.mem_preimage, hφ.2 _ (hΦ.source_subset hp), hΦ.comm p hp]
  exact blowUpChartMap_mem_center_iff σ _

/-- A blow-up chart of index `i` is adapted to the exceptional divisor, with the single block
coordinate `u_i`. -/
theorem IsBlowUpChart.isAdaptedChart_preimage (hφ : IsAdaptedChart ψ Y φ σ)
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) : IsAdaptedChart ψ (π ⁻¹' Y) Φ (singleEmb (σ i)) :=
  ⟨hΦ.mem_maximalAtlas, fun p hp => by
    rw [hΦ.mem_preimage_iff hφ hp]
    exact ⟨fun h _ => h, fun h => h 0⟩⟩

/-- `z_i ∘ π = u_i`: the pullback of the scaling coordinate of the adapted chart is the scaling
coordinate of the blow-up chart. -/
theorem IsBlowUpChart.germMap_coord_self (hπ : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω π)
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) (hΦ : IsBlowUpChart ψ π φ σ i Φ) (hp : p ∈ Φ.source) :
    germMap π hπ p (coord E ψ φ hφ (hΦ.source_subset hp) (σ i)) =
      coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i) := by
  apply stalkToGerm_injective 𝓘(𝕜, E) ω M' p
  rw [stalkToGerm_germMap, stalkToGerm_coord, stalkToGerm_coord, Germ.coe_compTendsto,
    Germ.coe_eq]
  filter_upwards [Φ.open_source.mem_nhds hp] with x hx
  rw [Function.comp_apply, extendSection_of_mem 𝕜 E _ (hΦ.source_subset hx),
    extendSection_of_mem 𝕜 E _ hx]
  change ψ (φ (π x)) (σ i) = ψ (Φ x) (σ i)
  rw [hΦ.comm x hx, blowUpChartMap_apply_scaling]

/-- `z_k ∘ π = u_i u_k` for `k ≠ i`: the pullback of a ratio coordinate. -/
theorem IsBlowUpChart.germMap_coord_of_ne (hπ : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω π)
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) (hΦ : IsBlowUpChart ψ π φ σ i Φ) (hp : p ∈ Φ.source)
    {k : Fin c} (hk : k ≠ i) :
    germMap π hπ p (coord E ψ φ hφ (hΦ.source_subset hp) (σ k)) =
      coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i) * coord E ψ Φ hΦ.mem_maximalAtlas hp (σ k) := by
  apply stalkToGerm_injective 𝓘(𝕜, E) ω M' p
  rw [stalkToGerm_germMap, stalkToGerm_coord, map_mul, stalkToGerm_coord, stalkToGerm_coord,
    Germ.coe_compTendsto, ← Germ.coe_mul, Germ.coe_eq]
  filter_upwards [Φ.open_source.mem_nhds hp] with x hx
  rw [Function.comp_apply, Pi.mul_apply, extendSection_of_mem 𝕜 E _ (hΦ.source_subset hx),
    extendSection_of_mem 𝕜 E _ hx, extendSection_of_mem 𝕜 E _ hx]
  change ψ (φ (π x)) (σ k) = ψ (Φ x) (σ i) * ψ (Φ x) (σ k)
  rw [hΦ.comm x hx, blowUpChartMap_apply_ratio σ _ hk]

variable [IsManifold 𝓘(𝕜, E) ω M'] [T2Space M'] [SecondCountableTopology M']

/-- The exceptional divisor is a closed submanifold of codimension one (the exceptional divisor
of a smooth blow-up is smooth, [Kol07, Notation 19]). -/
theorem IsBlowUp.isClosedSubmanifold_preimage (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) : IsClosedSubmanifold ψ (π ⁻¹' Y) 1 where
  isClosed := hY.isClosed.preimage h.contMDiff.continuous
  exists_adaptedChart := by
    intro p hp
    obtain ⟨φ, σ, ha, hφ⟩ := hY.exists_adaptedChart (π p) hp
    obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p ha
    exact ⟨Φ, singleEmb (σ i), hpΦ, hΦ.isAdaptedChart_preimage hφ⟩

/-- The pullback `π^* I_Y · 𝒪_{M'}` of the ideal sheaf of the centre is locally principal: in a
blow-up chart of index `i` its stalk is generated by the germ of the coordinate `u_i`. -/
theorem IsBlowUp.stalkIdeal_pullback_eq_span_coord (h : IsBlowUp ψ Y c π)
    {J : IdealSheaf (structureSheaf 𝕜 E M)} (hJ : IsIdealSheafOf ψ Y c J)
    (hφ : IsAdaptedChart ψ Y φ σ) (hΦ : IsBlowUpChart ψ π φ σ i Φ) (hp : p ∈ Φ.source) :
    (J.pullback π h.contMDiff).stalkIdeal p =
      Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i)} := by
  rw [IdealSheaf.stalkIdeal_pullback]
  have hπp : π p ∈ φ.source := hΦ.source_subset hp
  by_cases hpY : π p ∈ Y
  · rw [hJ.2 φ σ hφ (π p) hπp hpY, Ideal.map_span]
    refine le_antisymm (Ideal.span_le.mpr ?_) (Ideal.span_le.mpr ?_)
    · rintro _ ⟨_, ⟨k, rfl⟩, rfl⟩
      by_cases hk : k = i
      · subst hk
        rw [hΦ.germMap_coord_self h.contMDiff hφ.1 hp]
        exact Ideal.mem_span_singleton_self _
      · rw [hΦ.germMap_coord_of_ne h.contMDiff hφ.1 hp hk]
        exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)
    · rintro _ rfl
      rw [← hΦ.germMap_coord_self h.contMDiff hφ.1 hp]
      exact Ideal.subset_span ⟨_, ⟨i, rfl⟩, rfl⟩
  · have htop : J.stalkIdeal (π p) = ⊤ := by
      by_contra hne
      exact hpY (hJ.1 ▸ (IdealSheaf.mem_support J).mpr hne)
    rw [htop, Ideal.map_top, eq_comm, Ideal.span_singleton_eq_top,
      contMDiffSheafCommRing.isUnit_stalk_iff]
    change eval 𝕜 E M' p (coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i)) ≠ 0
    rw [eval_coord]
    exact fun h0 => hpY ((hΦ.mem_preimage_iff hφ hp).mpr h0)

/-- The pullback of the ideal sheaf of `Y` is the ideal sheaf of the exceptional divisor. -/
theorem IsBlowUp.isIdealSheafOf_pullback (hY : IsClosedSubmanifold ψ Y c) (h : IsBlowUp ψ Y c π)
    {J : IdealSheaf (structureSheaf 𝕜 E M)} (hJ : IsIdealSheafOf ψ Y c J) :
    IsIdealSheafOf ψ (π ⁻¹' Y) 1 (J.pullback π h.contMDiff) := by
  have hF := h.isClosedSubmanifold_preimage hY
  refine ⟨by rw [IdealSheaf.support_pullback, hJ.1], ?_⟩
  intro Φ' σ' hΦ' p hp hpF
  obtain ⟨φ, σ, ha, hφ⟩ := hY.exists_adaptedChart (π p) hpF
  obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p ha
  rw [h.stalkIdeal_pullback_eq_span_coord hJ hφ hΦ hpΦ]
  have h1 := hF.ker_restrictStalk ⟨p, hpF⟩ (hΦ.isAdaptedChart_preimage hφ) hpΦ
  have h2 := hF.ker_restrictStalk ⟨p, hpF⟩ hΦ' hp
  have e1 : eval 𝕜 E M' p (coord E ψ Φ hΦ.mem_maximalAtlas hpΦ (σ i)) = 0 := by
    rw [eval_coord]
    exact (hΦ.mem_preimage_iff hφ hpΦ).mp hpF
  have e2 : ∀ k : Fin 1, eval 𝕜 E M' p (coord E ψ Φ' hΦ'.1 hp (σ' k)) = 0 := fun k => by
    rw [eval_coord]
    exact (hΦ'.2 p hp).mp hpF k
  simp only [singleEmb_apply, e1, e2, map_zero, sub_zero] at h1 h2
  rw [Set.range_unique] at h1
  rw [← h1, h2]

end Divisor

/-! ### The degenerate centres -/

section Degenerate

variable {φ : OpenPartialHomeomorph M E} {σ : Fin 1 ↪ Fin n} {i : Fin 1}
  {Φ : OpenPartialHomeomorph M' E}

/-- For `c = 1` the blow-down restricted to a blow-up chart, as a partial diffeomorphism onto the
source of the adapted chart (inverse `Φ⁻¹ ∘ φ`). -/
def IsBlowUpChart.partialDiffeomorphOfFinOne (hπ : ContMDiff 𝓘(𝕜, E) 𝓘(𝕜, E) ω π)
    (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) (hΦ : IsBlowUpChart ψ π φ σ i Φ) :
    PartialDiffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) M' M ω where
  toFun := π
  invFun a := Φ.symm (φ a)
  source := Φ.source
  target := φ.source
  map_source' _ hp := hΦ.source_subset hp
  map_target' a ha := Φ.map_target (by rw [hΦ.target_eq_of_fin_one]; exact φ.map_source ha)
  left_inv' p hp := by rw [hΦ.apply_eq_of_fin_one hp, Φ.left_inv hp]
  right_inv' a ha := by
    have hmem : φ a ∈ Φ.target := by rw [hΦ.target_eq_of_fin_one]; exact φ.map_source ha
    rw [← hΦ.symm_apply_eq_of_fin_one (Φ.map_target hmem), Φ.right_inv hmem, φ.left_inv ha]
  open_source := Φ.open_source
  open_target := φ.open_source
  contMDiffOn_toFun := hπ.contMDiffOn
  contMDiffOn_invFun :=
    (contMDiffOn_symm_of_mem_maximalAtlas hΦ.mem_maximalAtlas).comp
      (contMDiffOn_of_mem_maximalAtlas hφ) fun a ha => by
        rw [hΦ.target_eq_of_fin_one]; exact φ.map_source ha

variable [IsManifold 𝓘(𝕜, E) ω M'] [T2Space M'] [SecondCountableTopology M']

/-- For `c = 1` two blow-up charts over one adapted chart have the same inverse: the inverses agree
off the hyperplane (there `π` is injective) and are continuous, and the hyperplane's complement is
dense. -/
theorem IsBlowUpChart.symm_eqOn_of_fin_one (h : IsBlowUp ψ Y 1 π) (hφ : IsAdaptedChart ψ Y φ σ)
    {Φ' : OpenPartialHomeomorph M' E} (hΦ : IsBlowUpChart ψ π φ σ i Φ)
    (hΦ' : IsBlowUpChart ψ π φ σ i Φ') : Set.EqOn Φ.symm Φ'.symm φ.target := by
  have hT : Φ.target = φ.target := hΦ.target_eq_of_fin_one
  have hT' : Φ'.target = φ.target := hΦ'.target_eq_of_fin_one
  have hS : Set.EqOn Φ.symm Φ'.symm {w ∈ φ.target | ψ w (σ i) ≠ 0} := by
    rintro w ⟨hw, hwi⟩
    have hw1 : w ∈ Φ.target := hT ▸ hw
    have hw2 : w ∈ Φ'.target := hT' ▸ hw
    have hπ1 : π (Φ.symm w) = φ.symm w := by
      rw [← hΦ.symm_apply_eq_of_fin_one (Φ.map_target hw1), Φ.right_inv hw1]
    have hπ2 : π (Φ'.symm w) = φ.symm w := by
      rw [← hΦ'.symm_apply_eq_of_fin_one (Φ'.map_target hw2), Φ'.right_inv hw2]
    have hnot : φ.symm w ∉ Y := by
      rw [hφ.2 _ (φ.map_target hw), φ.right_inv hw]
      exact fun hall => hwi (hall i)
    exact h.bijOn_compl.injOn (by rw [Set.mem_preimage, hπ1]; exact hnot)
      (by rw [Set.mem_preimage, hπ2]; exact hnot) (hπ1.trans hπ2.symm)
  have hdense : φ.target ⊆ closure {w ∈ φ.target | ψ w (σ i) ≠ 0} := by
    intro w hw
    have hopen : IsOpen (ψ '' φ.target) := ψ.toHomeomorph.isOpenMap _ φ.open_target
    have hcl := subset_closure_ne σ (i := i) hopen ⟨w, hw, rfl⟩
    have hpre : ψ.toHomeomorph ⁻¹' {v ∈ ψ '' φ.target | v (σ i) ≠ 0} =
        {w ∈ φ.target | ψ w (σ i) ≠ 0} := by
      ext v
      simp only [Set.mem_preimage, Set.mem_ofPred_eq, ContinuousLinearEquiv.coe_toHomeomorph,
        ψ.injective.mem_set_image]
    rw [← hpre, ← ψ.toHomeomorph.preimage_closure]
    exact hcl
  exact hS.of_subset_closure (Φ.continuousOn_symm.mono hT.symm.subset)
    (Φ'.continuousOn_symm.mono hT'.symm.subset) (fun _ hw => hw.1) hdense

/-- For an empty centre the blowing-up is a diffeomorphism (the empty blow-up of
[Kol07, Warning 20]). -/
theorem IsBlowUp.exists_diffeomorph_of_empty (h : IsBlowUp ψ (∅ : Set M) c π) :
    ∃ g : Diffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) M' M ω, ∀ p, g p = π p := by
  have hloc : IsLocalDiffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) ω π := fun p =>
    h.isLocalDiffeomorphOn_compl ⟨p, Set.notMem_empty _⟩
  have hbij : Function.Bijective π := by
    have hb := h.bijOn_compl
    rw [Set.compl_empty, Set.preimage_univ] at hb
    exact Set.bijOn_univ.mp hb
  exact ⟨hloc.toDiffeomorphOfBijective hbij, fun _ => rfl⟩

/-- For a centre of codimension one the blowing-up is a diffeomorphism (the trivial blow-up of
[Kol07, Warning 20]). -/
theorem IsBlowUp.exists_diffeomorph_of_codim_one (hY : IsClosedSubmanifold ψ Y 1)
    (h : IsBlowUp ψ Y 1 π) : ∃ g : Diffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) M' M ω, ∀ p, g p = π p := by
  have hloc : IsLocalDiffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) ω π := by
    intro p
    by_cases hp : π p ∈ Y
    · obtain ⟨φ, σ, ha, hφ⟩ := hY.exists_adaptedChart (π p) hp
      obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p ha
      exact IsLocalDiffeomorphAt.of_eqOn (hΦ.partialDiffeomorphOfFinOne h.contMDiff hφ.1) hpΦ
        fun _ _ => rfl
    · exact h.isLocalDiffeomorphOn_compl ⟨p, hp⟩
  have hbij : Function.Bijective π := by
    refine ⟨fun p q hpq => ?_, fun a => ?_⟩
    · by_cases hp : π p ∈ Y
      · obtain ⟨φ, σ, ha, hφ⟩ := hY.exists_adaptedChart (π p) hp
        obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p ha
        obtain ⟨i', Φ', hΦ', hqΦ'⟩ := h.cover φ σ hφ q (hpq ▸ ha)
        obtain rfl : i' = i := Subsingleton.elim i' i
        have hv : Φ p = Φ' q := by
          rw [← hΦ.apply_eq_of_fin_one hpΦ, ← hΦ'.apply_eq_of_fin_one hqΦ', hpq]
        have hw : Φ p ∈ φ.target := by
          rw [← hΦ.apply_eq_of_fin_one hpΦ]
          exact φ.map_source ha
        have heq := hΦ.symm_eqOn_of_fin_one h hφ hΦ' hw
        rw [Φ.left_inv hpΦ, hv, Φ'.left_inv hqΦ'] at heq
        exact heq
      · have hq : π q ∉ Y := by rw [← hpq]; exact hp
        exact h.bijOn_compl.injOn hp hq hpq
    · by_cases ha : a ∈ Y
      · obtain ⟨φ, σ, haφ, hφ⟩ := hY.exists_adaptedChart a ha
        obtain ⟨Φ, hΦ⟩ := h.exists_chart φ σ hφ 0
        have hmem : φ a ∈ Φ.target := by
          rw [hΦ.target_eq_of_fin_one]
          exact φ.map_source haφ
        refine ⟨Φ.symm (φ a), ?_⟩
        rw [← hΦ.symm_apply_eq_of_fin_one (Φ.map_target hmem), Φ.right_inv hmem, φ.left_inv haφ]
      · obtain ⟨p, -, hp⟩ := h.bijOn_compl.surjOn ha
        exact ⟨p, hp⟩
  exact ⟨hloc.toDiffeomorphOfBijective hbij, fun _ => rfl⟩

end Degenerate

end Manifold
