/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Functor
public import Mathlib.AlgebraicGeometry.Pullbacks
public import Hironaka.Algebra.Proj.Dehomogenize
import Hironaka.Scheme.BlowUp.Rees.Map
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Base change of projective space: `ℙ^{r-1}_S = Spec S ×_{Spec R} ℙ^{r-1}_R`

For a ring map `R → S` and the polynomial ring `R[u_0, …, u_{r-1}]` with its standard grading,
the square

```
Proj S[u] ⟶ Spec S
   |           |
Proj R[u] ⟶ Spec R
```

with `Proj S[u] ⟶ Proj R[u]` Mathlib's `Proj.map` of the coefficient map and the vertical maps
`Proj.toSpecZero` followed by `Spec` of `R → (R[u])₀`, is cartesian [Sta, Tag 01MX]. Mathlib
does not provide this; it is the input for identifying the exceptional divisor of a smooth blow-up
with a projective bundle over the centre.

**Why it holds.**  Both `Proj R[u]` and its base change are covered by the standard
charts `D₊(u_j)`, and `Proj.map` respects them (`Proj.awayι_comp_map`); over `D₊(u_j)` the square
is `Spec` of the ring square `R → S`, `R → (R[u]_{u_j})₀`, `S → (S[u]_{u_j})₀`,
`(R[u]_{u_j})₀ → (S[u]_{u_j})₀`, which is a pushout because both charts are polynomial rings in
the `u_i/u_j` (`AlgebraicGeometry.Proj.isPushout_away`, by dehomogenization).  A square of schemes
that is cartesian over an open cover of one corner is cartesian (Mathlib's
`Scheme.isPullback_of_openCover`).

## Main declarations

* `AlgebraicGeometry.Proj.projToSpec σ R : Proj (homogeneousSubmodule σ R) ⟶ Spec R` — the structure
  map.
* `AlgebraicGeometry.Proj.projMap σ R S : Proj (𝒜 S) ⟶ Proj (𝒜 R)` — `Proj.map` of the coefficient
  map.
* `Hironaka.Proj.isPullback_projMap σ R S :
    IsPullback (projToSpec σ S) (projMap σ R S) (Spec.map (algebraMap R S)) (projToSpec σ R)`,
  and the isomorphism `projBaseChangeIso σ R S` onto Mathlib's `pullback`.
-/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits MvPolynomial HomogeneousLocalization

attribute [local instance] MvPolynomial.gradedAlgebra

namespace AlgebraicGeometry.Proj

variable (σ : Type) (R : Type u) [CommRing R]

/-- The structure morphism `ℙ_R = Proj R[u] ⟶ Spec R`: `Proj.toSpecZero` followed by `Spec` of the
constants `R → (R[u])₀`. -/
noncomputable def projToSpec : Proj (homogeneousSubmodule σ R) ⟶ Spec (.of R) :=
  Proj.toSpecZero _ ≫ Spec.map (CommRingCat.ofHom (algebraMap R (homogeneousSubmodule σ R 0)))

/-- The irrelevant ideal of `R[u]` is generated by the variables. -/
theorem irrelevant_le_span_range_X :
    (HomogeneousIdeal.irrelevant (homogeneousSubmodule σ R)).toIdeal ≤
      Ideal.span (Set.range (X : σ → MvPolynomial σ R)) := by
  rw [HomogeneousIdeal.toIdeal_irrelevant_le]
  intro i hi p hp
  change p ∈ Ideal.span (Set.range (X : σ → MvPolynomial σ R))
  rw [← Set.image_univ, MvPolynomial.mem_ideal_span_X_image]
  intro m hm
  have hm0 : m ≠ 0 := fun h0 => by
    have h := (mem_homogeneousSubmodule _ _).mp hp (mem_support_iff.mp hm)
    rw [h0, map_zero] at h
    exact hi.ne h
  obtain ⟨k, hk⟩ := Finsupp.ne_iff.mp hm0
  exact ⟨k, Set.mem_univ k, hk⟩

/-- The standard chart `Spec (R[u]_{u_j})₀ ⟶ ℙ_R` followed by the structure morphism is `Spec` of
`R → (R[u]_{u_j})₀`. -/
theorem awayι_projToSpec (f : MvPolynomial σ R) (hf : f ∈ homogeneousSubmodule σ R 1) :
    Proj.awayι _ f hf one_pos ≫ projToSpec σ R =
      Spec.map (CommRingCat.ofHom (algebraMap R (Away (homogeneousSubmodule σ R) f))) := by
  rw [projToSpec, Proj.awayι_toSpecZero_assoc, ← Spec.map_comp]
  rfl

/-- The affine open cover of `ℙ_R` by the standard charts `D₊(u_j)`. -/
noncomputable def standardCover : (Proj (homogeneousSubmodule σ R)).AffineOpenCover :=
  Proj.affineOpenCoverOfIrrelevantLESpan (homogeneousSubmodule σ R) X (m := fun _ => 1)
    (X_mem_one R) (fun _ => one_pos) (irrelevant_le_span_range_X σ R)

section BaseChange

variable (S : Type u) [CommRing S] [Algebra R S]

/-- The hypothesis of `Proj.map`: the irrelevant ideal of `S[u]` is generated by the images of the
variables of `R[u]`. -/
theorem irrelevant_le_map_gradedMap :
    HomogeneousIdeal.irrelevant (homogeneousSubmodule σ S) ≤
      (HomogeneousIdeal.irrelevant (homogeneousSubmodule σ R)).map (gradedMap R S) := by
  rw [← toIdeal_le_toIdeal_iff, HomogeneousIdeal.toIdeal_map]
  refine (irrelevant_le_span_range_X σ S).trans (Ideal.span_le.mpr ?_)
  rintro _ ⟨k, rfl⟩
  rw [← gradedMap_X R S k]
  exact Ideal.mem_map_of_mem _
    (HomogeneousIdeal.mem_irrelevant_of_mem _ one_pos (X_mem_one R k))

/-- `Proj` of the coefficient map: `ℙ_S ⟶ ℙ_R`. -/
noncomputable def projMap : Proj (homogeneousSubmodule σ S) ⟶ Proj (homogeneousSubmodule σ R) :=
  Proj.map (gradedMap R S) (irrelevant_le_map_gradedMap σ R S)

/-- The base-change square commutes. -/
theorem projMap_projToSpec :
    projMap σ R S ≫ projToSpec σ R =
      projToSpec σ S ≫ Spec.map (CommRingCat.ofHom (algebraMap R S)) := by
  rw [projMap, projToSpec, projToSpec, map_toSpecZero_assoc, Category.assoc,
    ← Spec.map_comp, ← Spec.map_comp]
  congr 2
  refine CommRingCat.hom_ext (RingHom.ext fun r => Subtype.ext ?_)
  simp [gradedMap_apply]

/-- The chart square of `ℙ_S ⟶ ℙ_R` over `D₊(u_j)`. -/
theorem isPullback_awayι_projMap (j : σ) :
    IsPullback (Spec.map (CommRingCat.ofHom (Away.map (gradedMap R S) (X j))))
      (Proj.awayι _ (gradedMap R S (X j)) ((gradedMap R S).map_mem (X_mem_one R j)) one_pos)
      (Proj.awayι _ (X j) (X_mem_one R j) one_pos) (projMap σ R S) :=
  IsOpenImmersion.isPullback _ _ _ _
    (Proj.awayι_comp_map (gradedMap R S) (irrelevant_le_map_gradedMap σ R S) one_pos (X j)
      (X_mem_one R j))
    (by rw [Proj.opensRange_awayι, Proj.opensRange_awayι, projMap, Proj.map_preimage_basicOpen])

/-- Over the chart `D₊(u_j)` the base-change square is `Spec` of the pushout of rings
`AlgebraicGeometry.Proj.isPushout_away`. -/
theorem isPullback_Spec_away (j : σ) :
    IsPullback
      (Spec.map (CommRingCat.ofHom
        (algebraMap S (Away (homogeneousSubmodule σ S) (gradedMap R S (X j))))))
      (Spec.map (CommRingCat.ofHom (Away.map (gradedMap R S) (X j))))
      (Spec.map (CommRingCat.ofHom (algebraMap R S)))
      (Spec.map (CommRingCat.ofHom (algebraMap R (Away (homogeneousSubmodule σ R) (X j))))) :=
  isPullback_SpecMap_of_isPushout _ _ _ _ (isPushout_away R j S)

/-- The base-change square over the chart `D₊(u_j)`: any pullback of `ℙ_S ⟶ ℙ_R` along the chart,
composed with the structure map, is a pullback of `Spec S ⟶ Spec R` along the chart's structure
map — the square `isPullback_Spec_away` transported along the identification of the two
pullbacks of the chart square. -/
theorem isPullback_projMap_aux (j : σ) {W' : Scheme.{u}} {a : W' ⟶ Proj (homogeneousSubmodule σ S)}
    {b : W' ⟶ Spec (.of (Away (homogeneousSubmodule σ R) (X j)))}
    (hab : IsPullback a b (projMap σ R S) (Proj.awayι _ (X j) (X_mem_one R j) one_pos)) :
    IsPullback (a ≫ projToSpec σ S) b (Spec.map (CommRingCat.ofHom (algebraMap R S)))
      (Proj.awayι _ (X j) (X_mem_one R j) one_pos ≫ projToSpec σ R) := by
  have hchart := (isPullback_awayι_projMap σ R S j).flip
  let e := hab.isoIsPullback _ _ hchart
  have he₁ : e.hom ≫ Proj.awayι _ (gradedMap R S (X j))
      ((gradedMap R S).map_mem (X_mem_one R j)) one_pos = a :=
    hab.isoIsPullback_hom_fst _ _ hchart
  have he₂ : e.hom ≫ Spec.map (CommRingCat.ofHom (Away.map (gradedMap R S) (X j))) = b :=
    hab.isoIsPullback_hom_snd _ _ hchart
  refine (isPullback_Spec_away σ R S j).of_iso' e (Iso.refl _) (Iso.refl _) (Iso.refl _) ?_ ?_
    ?_ ?_
  · rw [Iso.refl_hom, Category.comp_id, ← awayι_projToSpec σ S (gradedMap R S (X j))
      ((gradedMap R S).map_mem (X_mem_one R j)), ← Category.assoc, he₁]
  · rw [Iso.refl_hom, Category.comp_id, he₂]
  · simp
  · rw [Iso.refl_hom, Iso.refl_hom, Category.id_comp, Category.comp_id, awayι_projToSpec]

/-- **Base change of projective space** [Sta, Tag 01MX], for `R[u_0, …, u_{r-1}]`: the
square `ℙ_S ⟶ Spec S`, `ℙ_S ⟶ ℙ_R`, `Spec S ⟶ Spec R`, `ℙ_R ⟶ Spec R` is cartesian.  It is
cartesian over each standard chart `D₊(u_j)` of `ℙ_R` (`isPullback_projMap_aux` at the canonical
pullback), hence cartesian (Mathlib's `Scheme.isPullback_of_openCover`). -/
theorem isPullback_projMap :
    IsPullback (projToSpec σ S) (projMap σ R S) (Spec.map (CommRingCat.ofHom (algebraMap R S)))
      (projToSpec σ R) :=
  (Scheme.isPullback_of_openCover (projMap σ R S) (projToSpec σ S) (projToSpec σ R)
    (Spec.map (CommRingCat.ofHom (algebraMap R S))) (standardCover σ R).openCover fun j =>
      (isPullback_projMap_aux σ R S j (IsPullback.of_hasPullback _ _)).flip).flip

/-- `ℙ_S ≅ Spec S ×_{Spec R} ℙ_R`, compatibly with the projections
(`projBaseChangeIso_hom_fst`, `projBaseChangeIso_hom_snd`). -/
noncomputable def projBaseChangeIso :
    Proj (homogeneousSubmodule σ S) ≅
      pullback (Spec.map (CommRingCat.ofHom (algebraMap R S))) (projToSpec σ R) :=
  (isPullback_projMap σ R S).isoPullback

@[reassoc (attr := simp)]
theorem projBaseChangeIso_hom_fst :
    (projBaseChangeIso σ R S).hom ≫ pullback.fst _ _ = projToSpec σ S :=
  (isPullback_projMap σ R S).isoPullback_hom_fst

@[reassoc (attr := simp)]
theorem projBaseChangeIso_hom_snd :
    (projBaseChangeIso σ R S).hom ≫ pullback.snd _ _ = projMap σ R S :=
  (isPullback_projMap σ R S).isoPullback_hom_snd

end BaseChange

end AlgebraicGeometry.Proj
