/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUpSequence.FunctorVocabulary
public import Hironaka.Scheme.Snc.Dictionary
import Hironaka.Resolution.Algebraic.Snc.DictionaryBoundary
import Hironaka.Scheme.BlowUp.InvertibleSheaf
import Hironaka.Scheme.BlowUpSequence.Triple
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.IdealSheaf.StalkLe
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Snc.DictionaryOrder
import Hironaka.Scheme.Snc.HasSncWith
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded


/-!
# The dictionary, part III: only normal crossings is simple normal crossings of the components

The core of the translation between Hironaka's and Kollár's normal crossing conditions:
[Hir64, Definition 2] asks, at a point `x`, for a regular system of parameters generating "the
ideal of each irreducible component of `E` containing `x`", that is the minimal primes of the
stalk `E_x`, while [Kol07, Definition 24] speaks of the members of a family through `x`. The bridge
is the correspondence, in the local ring `𝒪_{X,x}`, between the minimal primes of `E_x` and the
irreducible components of `V(E)` through `x`:

* on an affine open `U ∋ x`, primes of `𝒪_{X,x}` are the primes of `Γ(U)` inside the prime of `x`
  (the stalk is the localization, Mathlib's `IsAffineOpen.isLocalization_stalk`), points of `U` are
  the primes of `Γ(U)` (`IsAffineOpen.fromSpec`, `primeIdealOf`), specialization is inclusion of
  primes (`PrimeSpectrum.le_iff_specializes`), and a point lies in `V(E)` iff its prime contains
  `E(U)`;
* the reduced irreducible component through a generic point `η` of `V(E)`, the vanishing ideal
  sheaf of `closure {η}`, has on `U` the prime of `η` (`vanishingIdeal_closure_singleton_ideal`)
  and at `x` its image, a prime of `𝒪_{X,x}` containing `E_x`; it is minimal because a prime
  between them is the prime of a point of `V(E)` generizing `η`, hence `η` itself
  (`stalkIdeal_vanishingIdeal_mem_minimalPrimes`); conversely a minimal prime of `E_x` is the prime
  of a point of `V(E) ∩ U` generizing `x`, and that point is a generic point of `V(E)` by
  minimality (`exists_mem_genericPoints_of_mem_minimalPrimes`); distinct generic points give
  distinct primes (`eq_of_stalkIdeal_vanishingIdeal_closure_eq`). This is the same affine-local
  argument as `exists_genericPoint_of_isPrime_stalkIdeal`.

Hence Kollár's local condition for the component family at `x` (`IsSncAt`) is Hironaka's
(`componentFamily_isSncAt_iff`): the injective coordinate assignment to the members through `x` is
the assignment of a coordinate to each minimal prime, and the members of the component family are
regular subschemes because their stalks are generated by a coordinate. The two dictionaries follow
(`isSncBoundaryWith_iff_hasSncWith_componentFamily`,
`isSncBoundary_iff_isSnc_componentFamily`), and with them the first part of clause (iv)
of [Hir64, Main Theorem II] along a sequence of order `d`
(`IsOrderSeq.isSncBoundary_boundarySeq`: Kollár's `E_i` are snc at every stage, and
Hironaka's boundaries are their reduced unions).
-/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing Scheme.IdealSheafData Scheme
  DivisorFamily BlowUpSequence

namespace Hironaka.Sequence

open AlgebraicGeometry

variable {k : Type u} [Field k] {X : Scheme.{u}}

section AffineLocal

variable (U : X.affineOpens)

/-- The prime of `Γ(U)` at a point of the affine open `U` (Mathlib's
`IsAffineOpen.primeIdealOf`). -/
noncomputable abbrev primeAt {η : X} (hη : η ∈ U.1) : PrimeSpectrum Γ(X, U) :=
  (U.2 : IsAffineOpen U.1).primeIdealOf ⟨η, hη⟩

/-- The point of the prime of a point of `U` is the point. -/
theorem fromSpec_primeAt {η : X} (hη : η ∈ U.1) :
    (U.2 : IsAffineOpen U.1).fromSpec (primeAt U hη) = η :=
  (U.2 : IsAffineOpen U.1).fromSpec_primeIdealOf ⟨η, hη⟩

/-- Specialization between points of `U` is inclusion of their primes (Mathlib's
`PrimeSpectrum.le_iff_specializes` transported along the open embedding `fromSpec`). -/
theorem primeAt_le_iff_specializes {η x : X} (hη : η ∈ U.1) (hx : x ∈ U.1) :
    primeAt U hη ≤ primeAt U hx ↔ η ⤳ x := by
  have hU : IsAffineOpen U.1 := U.2
  rw [PrimeSpectrum.le_iff_specializes]
  constructor
  · intro h
    have h' := h.map hU.fromSpec.continuous
    rwa [fromSpec_primeAt, fromSpec_primeAt] at h'
  · intro h
    have h' : hU.fromSpec (primeAt U hη) ⤳ hU.fromSpec (primeAt U hx) := by
      rwa [fromSpec_primeAt, fromSpec_primeAt]
    exact hU.fromSpec.isOpenEmbedding.isInducing.specializes_iff.mp h'

/-- A point of `U` lies in `V(E)` iff `E(U)` lies in its prime. -/
theorem mem_support_iff_le_primeAt (E : X.IdealSheafData) {η : X} (hη : η ∈ U.1) :
    η ∈ E.support ↔ E.ideal U ≤ (primeAt U hη).asIdeal := by
  rw [mem_support_iff_of_mem hη, mem_zeroLocus_iff_le_primeIdealOf U hη]
  rfl

/-- The vanishing ideal sheaf of the closure of a point `η ∈ U` has, on `U`, the prime of `η`: the
preimage of `closure {η}` in `Spec Γ(U)` is the zero locus of that prime, whose vanishing ideal is
the prime (radical). -/
theorem vanishingIdeal_closure_singleton_ideal {η : X} (hη : η ∈ U.1) :
    (vanishingIdeal (Closeds.closure {η})).ideal U = (primeAt U hη).asIdeal := by
  have hU : IsAffineOpen U.1 := U.2
  rw [vanishingIdeal_ideal]
  have h1 : (⇑hU.fromSpec ⁻¹' ((Closeds.closure {η} : Closeds X) : Set X)) =
      PrimeSpectrum.zeroLocus ((primeAt U hη).asIdeal : Set Γ(X, U)) := by
    ext q
    change hU.fromSpec q ∈ closure {η} ↔ ((primeAt U hη).asIdeal : Set Γ(X, U)) ⊆ q.asIdeal
    constructor
    · intro hq
      have h1 : η ⤳ hU.fromSpec q := specializes_iff_mem_closure.mpr hq
      have h2 : hU.fromSpec (primeAt U hη) ⤳ hU.fromSpec q := by rwa [fromSpec_primeAt]
      exact (PrimeSpectrum.le_iff_specializes _ _).mpr
        (hU.fromSpec.isOpenEmbedding.isInducing.specializes_iff.mp h2)
    · intro hq
      have h1 : primeAt U hη ⤳ q := (PrimeSpectrum.le_iff_specializes _ _).mp hq
      have h2 := h1.map hU.fromSpec.continuous
      rw [fromSpec_primeAt] at h2
      exact specializes_iff_mem_closure.mp h2
  exact (congrArg PrimeSpectrum.vanishingIdeal h1).trans
    (by rw [PrimeSpectrum.vanishingIdeal_zeroLocus_eq_radical, (primeAt U hη).isPrime.radical])

end AffineLocal

/-- The stalk at `x ∈ U` of the reduced component through `η ∈ U` is the image in `𝒪_{X,x}` of the
prime of `η`. -/
theorem stalkIdeal_vanishingIdeal_closure_singleton (U : X.affineOpens) {η x : X} (hη : η ∈ U.1)
    (hx : x ∈ U.1) :
    (vanishingIdeal (Closeds.closure {η})).stalkIdeal x =
      ((primeAt U hη).asIdeal).map (X.presheaf.germ U.1 x hx).hom := by
  rw [stalkIdeal_eq_map_germ _ U hx, vanishingIdeal_closure_singleton_ideal]

/-! ### Minimal primes of `E_x` and the irreducible components of `V(E)` through `x` -/

/-- For a generic point `η` of `V(E)` specializing to `x`, the stalk at `x` of the reduced
component `closure {η}` is a minimal prime of `E_x` (the ideal of an "irreducible component of `E`
containing `x`" in [Hir64, Definition 2]): it is the image of the prime of `η`, prime and
containing `E_x`, and a prime between `E_x` and it is the prime of a point of `V(E)` generizing
`η`, which is `η` by genericity. -/
theorem stalkIdeal_vanishingIdeal_mem_minimalPrimes (E : X.IdealSheafData) {η x : X}
    (hη : η ∈ E.support.genericPoints) (hηx : η ⤳ x) :
    (vanishingIdeal (Closeds.closure {η})).stalkIdeal x ∈ (E.stalkIdeal x).minimalPrimes := by
  classical
  obtain ⟨U, hxU⟩ := exists_affineOpens_mem x
  have hU : IsAffineOpen U.1 := U.2
  have hηU : η ∈ U.1 := hηx.mem_open U.1.2 hxU
  let := TopCat.Presheaf.algebra_section_stalk X.presheaf (⟨x, hxU⟩ : U.1)
  have hloc := hU.isLocalization_stalk ⟨x, hxU⟩
  have hyx : primeAt U hηU ≤ primeAt U hxU := (primeAt_le_iff_specializes U hηU hxU).mpr hηx
  have hdisj : Disjoint ((primeAt U hxU).asIdeal.primeCompl : Set Γ(X, U))
      ((primeAt U hηU).asIdeal : Set Γ(X, U)) :=
    Set.disjoint_left.mpr fun a ha hay => ha (hyx hay)
  have hW : (vanishingIdeal (Closeds.closure {η})).stalkIdeal x =
      (primeAt U hηU).asIdeal.map (algebraMap Γ(X, U) (X.presheaf.stalk x)) :=
    stalkIdeal_vanishingIdeal_closure_singleton U hηU hxU
  have hE : E.stalkIdeal x = (E.ideal U).map (algebraMap Γ(X, U) (X.presheaf.stalk x)) :=
    stalkIdeal_eq_map_germ E U hxU
  have hEy : E.ideal U ≤ (primeAt U hηU).asIdeal := (mem_support_iff_le_primeAt U E hηU).mp hη.1
  rw [hW, hE]
  refine ⟨⟨IsLocalization.isPrime_of_isPrime_disjoint _ _ _ (primeAt U hηU).isPrime hdisj,
    Ideal.map_mono hEy⟩, ?_⟩
  rintro Q ⟨hQ, hEQ⟩ hQy
  have hQ' : Q.IsPrime := hQ
  have hqprime : (Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) Q).IsPrime :=
    Ideal.IsPrime.comap _
  have hqy : Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) Q ≤ (primeAt U hηU).asIdeal := by
    have h1 := Ideal.comap_mono (f := algebraMap Γ(X, U) (X.presheaf.stalk x)) hQy
    have h2 := IsLocalization.under_map_of_isPrime_disjoint _ (X.presheaf.stalk x)
      (primeAt U hηU).isPrime hdisj
    change Ideal.under Γ(X, U) Q ≤ Ideal.under Γ(X, U) _ at h1
    rwa [h2] at h1
  have hEq : E.ideal U ≤ Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) Q :=
    Ideal.map_le_iff_le_comap.mp hEQ
  let ξ := hU.fromSpec (⟨_, hqprime⟩ : PrimeSpectrum Γ(X, U))
  have hξU : ξ ∈ (U.1 : Set X) := by
    rw [← hU.range_fromSpec]
    exact ⟨_, rfl⟩
  have hξq : primeAt U hξU = ⟨_, hqprime⟩ :=
    hU.fromSpec.isOpenEmbedding.injective (fromSpec_primeAt U hξU)
  have hξE : ξ ∈ E.support := (mem_support_iff_le_primeAt U E hξU).mpr (by rw [hξq]; exact hEq)
  have hξη : ξ ⤳ η := (primeAt_le_iff_specializes U hξU hηU).mp (by rw [hξq]; exact hqy)
  have hξeq : ξ = η := hη.2 hξE hξη
  have hqeq : (⟨_, hqprime⟩ : PrimeSpectrum Γ(X, U)) = primeAt U hηU := by
    apply hU.fromSpec.isOpenEmbedding.injective
    rw [fromSpec_primeAt]
    exact hξeq
  have hQmap : Ideal.map (algebraMap Γ(X, U) (X.presheaf.stalk x))
      (Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) Q) = Q :=
    IsLocalization.map_under (primeAt U hxU).asIdeal.primeCompl (X.presheaf.stalk x) Q
  rw [← hQmap]
  exact Ideal.map_mono (le_of_eq (congrArg PrimeSpectrum.asIdeal hqeq).symm)

/-- Every minimal prime of `E_x` is the stalk at `x` of the reduced component through a generic
point of `V(E)` specializing to `x`: the prime is the image of a prime of `Γ(U)` inside the prime
of `x`, whose point lies in `V(E)`, generizes `x`, and is generic in `V(E)` by minimality. -/
theorem exists_mem_genericPoints_of_mem_minimalPrimes (E : X.IdealSheafData) {x : X}
    {P : Ideal (X.presheaf.stalk x)} (hP : P ∈ (E.stalkIdeal x).minimalPrimes) :
    ∃ η ∈ E.support.genericPoints, η ⤳ x ∧
      (vanishingIdeal (Closeds.closure {η})).stalkIdeal x = P := by
  classical
  obtain ⟨U, hxU⟩ := exists_affineOpens_mem x
  have hU : IsAffineOpen U.1 := U.2
  let := TopCat.Presheaf.algebra_section_stalk X.presheaf (⟨x, hxU⟩ : U.1)
  have hloc := hU.isLocalization_stalk ⟨x, hxU⟩
  have hPprime : P.IsPrime := hP.1.1
  have hEP : E.stalkIdeal x ≤ P := hP.1.2
  have hE : E.stalkIdeal x = (E.ideal U).map (algebraMap Γ(X, U) (X.presheaf.stalk x)) :=
    stalkIdeal_eq_map_germ E U hxU
  have hpprime : (Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) P).IsPrime :=
    Ideal.IsPrime.comap _
  have hpx : Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) P ≤ (primeAt U hxU).asIdeal := by
    intro a ha
    by_contra hna
    have hu : IsUnit (algebraMap Γ(X, U) (X.presheaf.stalk x) a) :=
      IsLocalization.map_units (X.presheaf.stalk x)
        (⟨a, hna⟩ : (primeAt U hxU).asIdeal.primeCompl)
    exact (IsLocalRing.mem_maximalIdeal _).mp (IsLocalRing.le_maximalIdeal hPprime.ne_top ha) hu
  have hpmap : Ideal.map (algebraMap Γ(X, U) (X.presheaf.stalk x))
      (Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) P) = P :=
    IsLocalization.map_under (primeAt U hxU).asIdeal.primeCompl (X.presheaf.stalk x) P
  have hEp : E.ideal U ≤ Ideal.comap (algebraMap Γ(X, U) (X.presheaf.stalk x)) P :=
    Ideal.map_le_iff_le_comap.mp (hE ▸ hEP)
  let η := hU.fromSpec (⟨_, hpprime⟩ : PrimeSpectrum Γ(X, U))
  have hηU : η ∈ (U.1 : Set X) := by
    rw [← hU.range_fromSpec]
    exact ⟨_, rfl⟩
  have hηp : primeAt U hηU = ⟨_, hpprime⟩ :=
    hU.fromSpec.isOpenEmbedding.injective (fromSpec_primeAt U hηU)
  have hηE : η ∈ E.support := (mem_support_iff_le_primeAt U E hηU).mpr (by rw [hηp]; exact hEp)
  have hηx : η ⤳ x := (primeAt_le_iff_specializes U hηU hxU).mp (by rw [hηp]; exact hpx)
  refine ⟨η, ⟨hηE, fun ξ hξE hξη => ?_⟩, hηx, ?_⟩
  · have hξU : ξ ∈ U.1 := hξη.mem_open U.1.2 hηU
    have hqp : primeAt U hξU ≤ primeAt U hηU := (primeAt_le_iff_specializes U hξU hηU).mpr hξη
    rw [hηp] at hqp
    have hEq : E.ideal U ≤ (primeAt U hξU).asIdeal := (mem_support_iff_le_primeAt U E hξU).mp hξE
    have hdisjq : Disjoint ((primeAt U hxU).asIdeal.primeCompl : Set Γ(X, U))
        ((primeAt U hξU).asIdeal : Set Γ(X, U)) :=
      Set.disjoint_left.mpr fun a ha haq => ha (hpx (hqp haq))
    have hQ : ((primeAt U hξU).asIdeal.map (algebraMap Γ(X, U) (X.presheaf.stalk x))).IsPrime :=
      IsLocalization.isPrime_of_isPrime_disjoint _ _ _ (primeAt U hξU).isPrime hdisjq
    have hEQ : E.stalkIdeal x ≤
        (primeAt U hξU).asIdeal.map (algebraMap Γ(X, U) (X.presheaf.stalk x)) := by
      rw [hE]
      exact Ideal.map_mono hEq
    have hQP : (primeAt U hξU).asIdeal.map (algebraMap Γ(X, U) (X.presheaf.stalk x)) ≤ P := by
      rw [← hpmap]
      exact Ideal.map_mono hqp
    have hPQ : P ≤ (primeAt U hξU).asIdeal.map (algebraMap Γ(X, U) (X.presheaf.stalk x)) :=
      hP.2 ⟨hQ, hEQ⟩ hQP
    have h1 := IsLocalization.under_map_of_isPrime_disjoint _ (X.presheaf.stalk x)
      (primeAt U hξU).isPrime hdisjq
    rw [le_antisymm hQP hPQ] at h1
    have hqeq : primeAt U hξU = ⟨_, hpprime⟩ := PrimeSpectrum.ext h1.symm
    rw [← fromSpec_primeAt U hξU, hqeq]
  · rw [stalkIdeal_vanishingIdeal_closure_singleton U hηU hxU, hηp]
    exact hpmap

/-- Two points specializing to `x` whose reduced components have the same stalk at `x` coincide
(their primes in `Γ(U)` are recovered from the stalk ideals). -/
theorem eq_of_stalkIdeal_vanishingIdeal_closure_eq {η η' x : X} (hηx : η ⤳ x) (hη'x : η' ⤳ x)
    (h : (vanishingIdeal (Closeds.closure {η})).stalkIdeal x =
      (vanishingIdeal (Closeds.closure {η'})).stalkIdeal x) : η = η' := by
  obtain ⟨U, hxU⟩ := exists_affineOpens_mem x
  have hU : IsAffineOpen U.1 := U.2
  have hηU : η ∈ U.1 := hηx.mem_open U.1.2 hxU
  have hη'U : η' ∈ U.1 := hη'x.mem_open U.1.2 hxU
  let := TopCat.Presheaf.algebra_section_stalk X.presheaf (⟨x, hxU⟩ : U.1)
  have hloc := hU.isLocalization_stalk ⟨x, hxU⟩
  have hW : (vanishingIdeal (Closeds.closure {η})).stalkIdeal x =
      (primeAt U hηU).asIdeal.map (algebraMap Γ(X, U) (X.presheaf.stalk x)) :=
    stalkIdeal_vanishingIdeal_closure_singleton U hηU hxU
  have hW' : (vanishingIdeal (Closeds.closure {η'})).stalkIdeal x =
      (primeAt U hη'U).asIdeal.map (algebraMap Γ(X, U) (X.presheaf.stalk x)) :=
    stalkIdeal_vanishingIdeal_closure_singleton U hη'U hxU
  rw [hW, hW'] at h
  have hdisj : ∀ {ζ : X} (hζU : ζ ∈ U.1), ζ ⤳ x →
      Disjoint ((primeAt U hxU).asIdeal.primeCompl : Set Γ(X, U))
        ((primeAt U hζU).asIdeal : Set Γ(X, U)) := fun hζU hζx =>
    Set.disjoint_left.mpr fun a ha haq =>
      ha ((primeAt_le_iff_specializes U hζU hxU).mpr hζx haq)
  have h1 := IsLocalization.under_map_of_isPrime_disjoint _ (X.presheaf.stalk x)
    (primeAt U hηU).isPrime (hdisj hηU hηx)
  have h2 := IsLocalization.under_map_of_isPrime_disjoint _ (X.presheaf.stalk x)
    (primeAt U hη'U).isPrime (hdisj hη'U hη'x)
  have hp : primeAt U hηU = primeAt U hη'U := by
    apply PrimeSpectrum.ext
    rw [← h1, ← h2, h]
  rw [← fromSpec_primeAt U hηU, ← fromSpec_primeAt U hη'U, hp]

/-! ### The dictionary for the family of irreducible components -/

/-- Kollár's local condition [Kol07, Definition 24 (1)–(3)] at `x` for the family of irreducible
components, an injective assignment of coordinates to the members through `x` with
`(E^i)_x = (z_{c(i)})`, is Hironaka's condition on the components [Hir64, Definition 2], every
minimal prime of `E_x` being some `(z_i)`: the members through `x` are exactly the minimal primes
of `E_x` (`stalkIdeal_vanishingIdeal_mem_minimalPrimes`,
`exists_mem_genericPoints_of_mem_minimalPrimes`), distinct members giving distinct primes. -/
theorem componentFamily_isSncAt_iff [NoetherianSpace X] (E : X.IdealSheafData) (x : X) {n : ℕ}
    (z : Fin n → X.presheaf.stalk x) :
    E.componentFamily.IsSncAt x z ↔ IsRegularSystemOfParameters z ∧
      ∀ P ∈ (E.stalkIdeal x).minimalPrimes, ∃ i, P = Ideal.span {z i} := by
  classical
  constructor
  · rintro ⟨hrs, c, -, hc⟩
    refine ⟨hrs, fun P hP => ?_⟩
    obtain ⟨η, hη, hηx, hW⟩ := exists_mem_genericPoints_of_mem_minimalPrimes E hP
    have hxη : x ∈ (E.componentFamily.component ⟨η, hη⟩).support := by
      change x ∈ (vanishingIdeal (Closeds.closure {η})).support
      rw [← SetLike.mem_coe, coe_support_vanishingIdeal]
      exact specializes_iff_mem_closure.mp hηx
    refine ⟨c ⟨⟨η, hη⟩, hxη⟩, ?_⟩
    rw [← hW]
    exact hc ⟨⟨η, hη⟩, hxη⟩
  · rintro ⟨hrs, hmin⟩
    refine ⟨hrs, ?_⟩
    have hspec : ∀ η : {i : E.componentFamily.ι // x ∈ (E.componentFamily.component i).support},
        η.1.1 ⤳ x := by
      intro η
      have := η.2
      change x ∈ (vanishingIdeal (Closeds.closure {η.1.1})).support at this
      rw [← SetLike.mem_coe, coe_support_vanishingIdeal] at this
      exact specializes_iff_mem_closure.mpr this
    have key : ∀ η : {i : E.componentFamily.ι // x ∈ (E.componentFamily.component i).support},
        ∃ i : Fin n, (vanishingIdeal (Closeds.closure {η.1.1})).stalkIdeal x = Ideal.span {z i} :=
      fun η => hmin _ (stalkIdeal_vanishingIdeal_mem_minimalPrimes E η.1.2 (hspec η))
    choose c hc using key
    refine ⟨c, fun η η' hηη' => ?_, hc⟩
    have heq : (vanishingIdeal (Closeds.closure {η.1.1})).stalkIdeal x =
        (vanishingIdeal (Closeds.closure {η'.1.1})).stalkIdeal x := by
      rw [hc η, hc η', hηη']
    have hpt : η.1.1 = η'.1.1 :=
      eq_of_stalkIdeal_vanishingIdeal_closure_eq (hspec η) (hspec η') heq
    exact Subtype.ext (Subtype.ext hpt)

/-- `E` has only normal crossings with `D` [Hir64, Definition 2] iff `D` has simple normal
crossings with the family of irreducible components of `E` [Kol07, Definition 24 (1)–(4)]:
pointwise `componentFamily_isSncAt_iff` with the same clause on the ideal of `D`. -/
theorem isSncBoundaryWith_iff_hasSncWith_componentFamily [NoetherianSpace X]
    (_f : X ⟶ Spec (.of k)) (E D : X.IdealSheafData) :
    IsSncBoundaryWith E D ↔ E.componentFamily.HasSncWith D := by
  constructor
  · intro h x hx
    obtain ⟨n, z, hrs, hmin, s, hs⟩ := h x hx
    exact ⟨n, z, (componentFamily_isSncAt_iff E x z).mpr ⟨hrs, hmin⟩, s, hs⟩
  · intro h x hx
    obtain ⟨n, z, hz, s, hs⟩ := h x hx
    obtain ⟨hrs, hmin⟩ := (componentFamily_isSncAt_iff E x z).mp hz
    exact ⟨n, z, hrs, hmin, s, hs⟩

/-- On `X` smooth over `k`, `E` has only normal crossings [Hir64, Definition 2 with `D = X`] iff
the family of its irreducible components is a simple normal crossing divisor
[Kol07, Definition 24 (1)–(3)]: its members are regular subschemes (at each of their points the
stalk is a coordinate `(z_i)`, so the quotient is a regular local ring) with Kollár's coordinates
at every point. -/
theorem isSncBoundary_iff_isSnc_componentFamily [NoetherianSpace X]
    (f : X ⟶ Spec (.of k)) [Smooth f] (E : X.IdealSheafData) :
    IsSncBoundary E ↔ E.componentFamily.IsSnc := by
  constructor
  · intro h
    refine ⟨fun η => ?_, fun x => ?_⟩
    · apply isRegular_subscheme_of_isRegularLocalRing_quotient
      intro w hw
      obtain ⟨n, z, hrs, hmin, -, -⟩ := h w (by rw [support_bot]; trivial)
      have hwη : η.1 ⤳ w := by
        change w ∈ (vanishingIdeal (Closeds.closure {η.1})).support at hw
        rw [← SetLike.mem_coe, coe_support_vanishingIdeal] at hw
        exact specializes_iff_mem_closure.mpr hw
      obtain ⟨i, hi⟩ := hmin _ (stalkIdeal_vanishingIdeal_mem_minimalPrimes E η.2 hwη)
      have := isRegularLocalRing_stalk f w
      refine isRegularLocalRing_quotient_stalkIdeal_of_eq_span hrs
        (s := {i}) ?_
      change (vanishingIdeal (Closeds.closure {η.1})).stalkIdeal w = _
      rw [hi]
      simp
    · obtain ⟨n, z, hrs, hmin, -, -⟩ := h x (by rw [support_bot]; trivial)
      exact ⟨n, z, (componentFamily_isSncAt_iff E x z).mpr ⟨hrs, hmin⟩⟩
  · intro h x _
    obtain ⟨n, z, hz⟩ := h.2 x
    obtain ⟨hrs, hmin⟩ := (componentFamily_isSncAt_iff E x z).mp hz
    refine ⟨n, z, hrs, hmin, ∅, ?_⟩
    rw [Scheme.IdealSheafData.stalkIdeal_bot]
    simp

section Boundaries

variable [IsNoetherian X] [CharZero k] (f : X ⟶ Spec (.of k)) (n : ℕ)
  [SmoothOfRelativeDimension n f] {S : BlowUpSequence X} (E : X.IdealSheafData)
  [IsReduced E.subscheme]

include f n

/-- The first part of clause (iv) of [Hir64, Main Theorem II], which Hironaka remarks follows
from (iii): along a smooth blow-up sequence of order `d` starting with `(X, J, E.componentFamily)`
for `E` with only normal crossings, every boundary `E_i` has only normal crossings. Kollár's `E_i`
are simple normal crossing divisors at every stage ([Kol07, Definition 25];
`IsOrderSeq.isSnc_totalTransformSeq`) and Hironaka's boundaries are their reduced unions. -/
theorem IsOrderSeq.isSncBoundary_boundarySeq {J : X.IdealSheafData} {d : ℕ}
    (hE : IsSncBoundary E) (h : S.IsOrderSeq f J E.componentFamily d)
    (i : Fin (S.length + 1)) : IsSncBoundary (S.boundarySeq E i) := by
  have hf : Smooth f := SmoothOfRelativeDimension.smooth n f
  have hsnc : E.componentFamily.IsSnc :=
    (isSncBoundary_iff_isSnc_componentFamily f E).mp hE
  have hsnc_i : (S.totalTransformSeq E.componentFamily i).IsSnc :=
    IsOrderSeq.isSnc_totalTransformSeq f n h hsnc i
  rw [boundarySeq_eq_unionIdeal_totalTransformSeq_componentFamily]
  have : SmoothOfRelativeDimension n (S.stageMap i ≫ f) :=
    IsSmooth.stageMap_smoothOfRelativeDimension h.1 i
  have : Smooth (S.stageMap i ≫ f) := SmoothOfRelativeDimension.smooth n _
  exact IsSnc.isSncBoundary_unionIdeal (S.stageMap i ≫ f) hsnc_i

end Boundaries

end Hironaka.Sequence
