/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.Snc.SmoothDivisor
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.SubschemeStalk
import Hironaka.Scheme.Snc.HasSncWith
import Mathlib.AlgebraicGeometry.Morphisms.Proper

/-!
# Smooth divisors are a stalkwise notion: restriction and gluing along open immersions

`IsSmoothDivisor D` (`Hironaka.Scheme.Snc.SmoothDivisor`) asks that `V(D)` be regular and that at
every point `x ∈ V(D)` the stalk `D_x` be generated by an element of `𝔪_x ∖ 𝔪_x²`. Both clauses are
conditions on the stalks of `X` at the points of the support — regularity of `V(D)` at `z` is
regularity of `𝒪_{X,x} / D_x` for `x = ι(z)` (`stalkQuotientEquiv`) — so the notion is *local*: it
restricts along open immersions (`IsSmoothDivisor.comap_of_isOpenImmersion` of
`Hironaka.Resolution.Algebraic.MaximalContact.Restrict`) and it holds as soon as it holds after
restriction to the members of a covering family of open immersions
(`isSmoothDivisor_of_forall_comap`, this module). The stalk of `D.comap f` at `y` is the image of
the stalk of `D` at `f y` under the stalk map of `f` (`stalkIdeal_comap`), an isomorphism of local
rings when `f` is an open immersion, and both clauses transport along a ring isomorphism
(`isSmoothDivisorAt_map`).

Two further facts on ideal sheaves along open immersions, used with these by
`Hironaka.Resolution.Algebraic.Kol07.MaximalContactGlobalization` to glue the hypersurfaces of
maximal contact of the pieces of a disjoint union: the inverse image along an open immersion
commutes with finite intersections (`comap_iInf_of_isOpenImmersion`; on each affine open it is the
inverse image of ideals under a ring isomorphism), and an inclusion of ideal sheaves may be checked
after restriction to a covering family of open immersions (`le_of_forall_comap_le`).

Source: Step 3 of the proof of [Kol07, Theorem 103] ("the disjoint union `H^* := ∐ H^(j) ⊂ ∐ X^(j)`
is a smooth hypersurface of maximal contact"), which uses this locality tacitly.
-/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal
open AlgebraicGeometry.Scheme.IdealSheafData

namespace Hironaka.Snc

open AlgebraicGeometry

variable {X Y : Scheme.{u}}

/-- The **smooth-ideal condition** on an ideal `I` of a local ring `R` — the quotient `R / I` is a
regular local ring and `I` is generated by an element of `𝔪 ∖ 𝔪²`. At a stalk `𝒪_{X,x}` with
`I = D_x` these are the two clauses of `IsSmoothDivisor` at `x`. -/
def IsSmoothIdealAt {R : Type*} [CommRing R] [IsLocalRing R] (I : Ideal R) : Prop :=
  IsRegularLocalRing (R ⧸ I) ∧
    ∃ a : R, a ∈ maximalIdeal R ∧ a ∉ maximalIdeal R ^ 2 ∧ I = span {a}

/-- The **stalkwise smooth-divisor condition** at `x` — the smooth-ideal condition for the stalk
`D_x ⊆ 𝒪_{X,x}`. -/
def IsSmoothDivisorAt (D : X.IdealSheafData) (x : X) : Prop :=
  IsSmoothIdealAt (D.stalkIdeal x)

/-- `D` is a smooth divisor iff the stalkwise condition holds at every point of its support —
regularity of `V(D)` at `z` is regularity of `𝒪_{X, ι z} / D_{ι z}`. -/
theorem isSmoothDivisor_iff_forall_isSmoothDivisorAt (D : X.IdealSheafData) :
    IsSmoothDivisor D ↔ ∀ x ∈ D.support, IsSmoothDivisorAt D x := by
  constructor
  · rintro ⟨hreg, hgen⟩ x hx
    obtain ⟨z, rfl⟩ := exists_subschemeι_eq D hx
    refine ⟨?_, hgen _ hx⟩
    have : IsRegularLocalRing (D.subscheme.presheaf.stalk z) := hreg.isRegularAt z
    exact IsRegularLocalRing.of_ringEquiv (D.stalkQuotientEquiv z).symm
  · intro h
    exact ⟨isRegular_subscheme_of_isRegularLocalRing_quotient D fun w hw => (h w hw).1,
      fun x hx => (h x hx).2⟩

/-- The smooth-ideal condition transports along an isomorphism of local rings — the maximal ideal,
its square and principal ideals are carried to their counterparts. -/
theorem IsSmoothIdealAt.map {R S : Type*} [CommRing R] [CommRing S] [IsLocalRing R]
    [IsLocalRing S] (e : R ≃+* S) {I : Ideal R} (h : IsSmoothIdealAt I) :
    IsSmoothIdealAt (I.map e) := by
  obtain ⟨hreg, a, ha, ha2, hI⟩ := h
  refine ⟨IsRegularLocalRing.of_ringEquiv (Ideal.quotientEquiv I (I.map e) e rfl), e a, ?_, ?_, ?_⟩
  · rw [← map_ringEquiv_maximalIdeal e]
    exact Ideal.mem_map_of_mem _ ha
  · intro h2
    apply ha2
    rw [← map_ringEquiv_maximalIdeal e, ← Ideal.map_pow, ← Ideal.comap_symm, Ideal.mem_comap,
      RingEquiv.symm_apply_apply] at h2
    exact h2
  · rw [hI, Ideal.map_span, Set.image_singleton]

/-- The smooth-ideal condition is invariant under an isomorphism of local rings. -/
theorem isSmoothIdealAt_map_iff {R S : Type*} [CommRing R] [CommRing S] [IsLocalRing R]
    [IsLocalRing S] (e : R ≃+* S) (I : Ideal R) : IsSmoothIdealAt (I.map e) ↔ IsSmoothIdealAt I :=
    by
  refine ⟨fun h => ?_, fun h => h.map e⟩
  have h' := h.map e.symm
  rwa [Ideal.map_symm, Ideal.comap_map_of_bijective _ e.bijective] at h'

/-- Along an open immersion `f`, the stalkwise condition for `D.comap f` at `y` is the condition for
`D` at `f y` — the stalk map of an open immersion is an isomorphism of local rings carrying
`D_{f y}` to `(f^* D)_y` (`stalkIdeal_comap`). -/
theorem isSmoothDivisorAt_comap_iff (D : X.IdealSheafData) (f : Y ⟶ X) [IsOpenImmersion f]
    (y : Y) : IsSmoothDivisorAt (D.comap f) y ↔ IsSmoothDivisorAt D (f y) := by
  have hiso : IsIso (f.stalkMap y) := inferInstance
  let e : X.presheaf.stalk (f y) ≃+* Y.presheaf.stalk y :=
    (asIso (f.stalkMap y)).commRingCatIsoToRingEquiv
  have hmap : (D.comap f).stalkIdeal y = (D.stalkIdeal (f y)).map e := stalkIdeal_comap D f y
  unfold IsSmoothDivisorAt
  rw [hmap]
  exact isSmoothIdealAt_map_iff e _

/-- An ideal sheaf whose restrictions along a covering family of open immersions are smooth divisors
is a smooth divisor. -/
theorem isSmoothDivisor_of_forall_comap {ι : Type*} {Y : ι → Scheme.{u}} (f : ∀ i, Y i ⟶ X)
    [∀ i, IsOpenImmersion (f i)] (hcov : ∀ x : X, ∃ (i : ι) (y : Y i), f i y = x)
    {D : X.IdealSheafData} (h : ∀ i, IsSmoothDivisor (D.comap (f i))) : IsSmoothDivisor D := by
  rw [isSmoothDivisor_iff_forall_isSmoothDivisorAt]
  intro x hx
  obtain ⟨i, y, rfl⟩ := hcov x
  rw [← isSmoothDivisorAt_comap_iff D (f i) y]
  refine (isSmoothDivisor_iff_forall_isSmoothDivisorAt _).1 (h i) y ?_
  rw [support_comap]
  exact hx

/-- The inverse image along an open immersion commutes with finite intersections of ideal sheaves —
on each affine open it is the inverse image of ideals under the ring isomorphism of sections, which
commutes with intersections. -/
theorem comap_iInf_of_isOpenImmersion {ι : Type*} [Finite ι] (I : ι → X.IdealSheafData)
    (f : Y ⟶ X) [IsOpenImmersion f] : (⨅ i, I i).comap f = ⨅ i, (I i).comap f := by
  refine Scheme.IdealSheafData.ext (funext fun U => ?_)
  have h1 : (⨅ i, (I i).comap f).ideal U = ⨅ i, ((I i).comap f).ideal U := by
    rw [ideal_iInf, iInf_apply]
  have h2 : (⨅ i, I i).ideal ⟨f ''ᵁ U, U.2.image_of_isOpenImmersion f⟩ =
      ⨅ i, (I i).ideal ⟨f ''ᵁ U, U.2.image_of_isOpenImmersion f⟩ := by
    rw [ideal_iInf, iInf_apply]
  rw [h1, ideal_comap_of_isOpenImmersion, h2, Ideal.comap_iInf]
  exact iInf_congr fun i => (ideal_comap_of_isOpenImmersion (I i) f U).symm

/-- An inclusion of ideal sheaves may be checked after restriction to a covering family of open
immersions — stalkwise, through the stalk isomorphisms. -/
theorem le_of_forall_comap_le {ι : Type*} {Y : ι → Scheme.{u}} (f : ∀ i, Y i ⟶ X)
    [∀ i, IsOpenImmersion (f i)] (hcov : ∀ x : X, ∃ (i : ι) (y : Y i), f i y = x)
    {I J : X.IdealSheafData} (h : ∀ i, I.comap (f i) ≤ J.comap (f i)) : I ≤ J := by
  refine le_of_stalkIdeal_le fun x => ?_
  obtain ⟨i, y, rfl⟩ := hcov x
  have hiso : IsIso ((f i).stalkMap y) := inferInstance
  let e : X.presheaf.stalk (f i y) ≃+* (Y i).presheaf.stalk y :=
    (asIso ((f i).stalkMap y)).commRingCatIsoToRingEquiv
  have h' : (I.stalkIdeal (f i y)).map e ≤ (J.stalkIdeal (f i y)).map e := by
    have := stalkIdeal_mono (h i) y
    rwa [stalkIdeal_comap, stalkIdeal_comap] at this
  rw [← Ideal.comap_symm, ← Ideal.comap_symm] at h'
  intro a ha
  have := h' (Ideal.mem_comap.mpr (by rwa [RingEquiv.symm_apply_apply]) : e a ∈ _)
  rwa [Ideal.mem_comap, RingEquiv.symm_apply_apply] at this

/-- The inverse image, along `f`, of the direct image of an ideal sheaf along a closed immersion `g`
whose image is disjoint from the image of `f` is the unit ideal — its support is the preimage under
`f` of a closed subset of the image of `g`. -/
theorem comap_map_eq_top_of_disjoint {Z : Scheme.{u}} (I : Y.IdealSheafData) (g : Y ⟶ X)
    [IsClosedImmersion g] (f : Z ⟶ X) (hdisj : Disjoint (Set.range g) (Set.range f)) :
    (I.map g).comap f = ⊤ := by
  rw [← support_eq_bot_iff, support_comap, support_map]
  ext z
  simp only [TopologicalSpace.Closeds.coe_preimage, TopologicalSpace.Closeds.coe_closure,
    Set.mem_preimage, TopologicalSpace.Closeds.coe_bot, Set.mem_empty_iff_false, iff_false]
  intro hz
  have hcl : closure (g '' (I.support : Set Y)) ⊆ Set.range g :=
    closure_minimal (Set.image_subset_range _ _) g.isClosedEmbedding.isClosed_range
  exact Set.disjoint_left.mp hdisj (hcl hz) ⟨z, rfl⟩

end Hironaka.Snc
