/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineAlgebra
public import Hironaka.Scheme.BlowUp.AffineBlowUp.Chart
public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Hironaka.Scheme.BlowUp.InverseImage

/-!
# Admissible morphisms to `Spec R` and the local lifts to the affine blow-up

Vocabulary for the universal property of the affine blow-up `B = affineBlowUp I` of `Spec R`
along `I` [Hau14, Definition 4.4 and Theorem 4.18]; [Sta, Tag 0806]:

* `specIdealSheaf I` — the ideal sheaf of `I` on `Spec R` (the spelling
  `ofIdealTop (I.map (ΓSpecIso R).inv.hom)` used throughout `Hironaka.BlowUp`, as an `abbrev`).
  A morphism `f : Y ⟶ Spec R` is *admissible* for `I` when `(specIdealSheaf I).comap f` is
  invertible (`IdealSheafData.IsInvertible`), that is, when the inverse image of `Z` is an
  effective Cartier divisor on `Y`.
* `sectionsHom f V : R →+* Γ(Y, V)` — the ring map on sections induced by `f` over an open `V`
  (`f♯` composed with `ΓSpecIso`), with `ideal_comap_specIdealSheaf`: the ideal of the
  inverse image sheaf on an affine `V` is `I` extended along it.
* `liftOn f V a hβa hI : (V : Scheme) ⟶ affineBlowUp I` — the local lift of Hauser's proof
  [Hau14, Theorem 4.18, proof (d)]: for an affine open `V` and `a ∈ I` such that `(I·𝒪_Y)(V)` is
  generated by the nonzerodivisor `f♯a`, the composite `V ≅ Spec Γ(V) → Spec R[I/a] → affineBlowUp
  I` through the ring map `δ : R[I/a] → Γ(V)` extending `f♯` (`affineBlowUpAlgebra.lift`), which
  lies over `f` (`liftOn_π`).
-/

@[expose] public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory Scheme.IdealSheafData

universe u

variable {R : Type u} [CommRing R]

/-- The ideal sheaf of `I ⊆ R` on `Spec R` (the global sections of `Spec R` are `R` through
`ΓSpecIso`). -/
noncomputable abbrev specIdealSheaf (I : Ideal R) : (Spec (.of R)).IdealSheafData :=
  Scheme.IdealSheafData.ofIdealTop (I.map (Scheme.ΓSpecIso (.of R)).inv.hom)

variable {Y : Scheme.{u}}

/-- The ring map `R → Γ(Y, V)` induced by `f : Y ⟶ Spec R` on the sections over an open `V`
(`f♯` on `V ⊆ f⁻¹(Spec R)`, composed with `R ≅ Γ(Spec R, ⊤)`). -/
noncomputable def sectionsHom (f : Y ⟶ Spec (.of R)) (V : Y.Opens) : R →+* Γ(Y, V) :=
  (f.appLE ⊤ V le_top).hom.comp (Scheme.ΓSpecIso (.of R)).inv.hom

theorem specIdealSheaf_ideal_top (I : Ideal R) :
    (specIdealSheaf I).ideal ⟨⊤, isAffineOpen_top _⟩ = I.map (Scheme.ΓSpecIso (.of R)).inv.hom := by
  rw [specIdealSheaf, Scheme.IdealSheafData.ofIdealTop_ideal,
    show homOfLE (le_top : (⊤ : (Spec (.of R)).Opens) ≤ ⊤) = 𝟙 _ from rfl, op_id,
    CategoryTheory.Functor.map_id, CommRingCat.hom_id, Ideal.map_id]

/-- The ideal of `(I·𝒪_Y)` on an affine open `V ⊆ Y` is the extension of `I` along
`sectionsHom f V`. -/
theorem ideal_comap_specIdealSheaf (I : Ideal R) (f : Y ⟶ Spec (.of R)) (V : Y.affineOpens) :
    ((specIdealSheaf I).comap f).ideal V = I.map (sectionsHom f V.1) := by
  rw [Scheme.IdealSheafData.ideal_comap_of_le (specIdealSheaf I) f ⟨⊤, isAffineOpen_top _⟩ V le_top,
    specIdealSheaf_ideal_top, Ideal.map_map]
  rfl

section LiftOn

variable (I : Ideal R) (f : Y ⟶ Spec (.of R)) (V : Y.affineOpens) (a : I)
  (hβa : sectionsHom f V.1 a ∈ nonZeroDivisors Γ(Y, V))
  (hI : I.map (sectionsHom f V.1) = Ideal.span {sectionsHom f V.1 a})

/-- The local lift on an affine piece [Hau14, Theorem 4.18, proof (d)]; [Sta, Tag 0806].  For an
affine open `V ⊆ Y` and `a ∈ I` whose image `f♯a` is a nonzerodivisor generating `(I·𝒪_Y)(V)`,
the ring map `δ : R[I/a] → Γ(Y, V)` extending `f♯` (`affineBlowUpAlgebra.lift`) gives
`V ≅ Spec Γ(Y, V) ⟶ Spec R[I/a] ⟶ affineBlowUp I` through the chart of `a`. -/
noncomputable def liftOn : (V.1 : Scheme.{u}) ⟶ affineBlowUp I :=
  V.2.isoSpec.hom ≫
    Spec.map (CommRingCat.ofHom (affineBlowUpAlgebra.lift (sectionsHom f V.1) a.2 hβa hI)) ≫
      affineBlowUp.chart I a

/-- The local lift lands in the chart of `a`. -/
theorem liftOn_eq :
    liftOn I f V a hβa hI = V.2.isoSpec.hom ≫
      Spec.map (CommRingCat.ofHom (affineBlowUpAlgebra.lift (sectionsHom f V.1) a.2 hβa hI)) ≫
        affineBlowUp.chart I a :=
  rfl

/-- The morphism `Spec Γ(Y, V) ⟶ Spec R` induced by `f` is `Spec` of `sectionsHom f V`. -/
theorem isoSpec_hom_specMap_sectionsHom :
    V.2.isoSpec.hom ≫ Spec.map (CommRingCat.ofHom (sectionsHom f V.1)) = V.1.ι ≫ f := by
  have hV : IsAffineOpen V.1 := V.2
  have h := IsAffineOpen.SpecMap_appLE_fromSpec f (isAffineOpen_top (Spec (.of R))) hV
    (le_top : V.1 ≤ f ⁻¹ᵁ ⊤)
  rw [IsAffineOpen.fromSpec_top, Scheme.isoSpec_Spec_inv] at h
  have hι : V.1.ι = hV.isoSpec.hom ≫ hV.fromSpec :=
    (Iso.inv_comp_eq _).mp (IsAffineOpen.isoSpec_inv_ι hV)
  calc hV.isoSpec.hom ≫ Spec.map (CommRingCat.ofHom (sectionsHom f V.1))
      = hV.isoSpec.hom ≫ Spec.map (f.appLE ⊤ V.1 le_top) ≫
          Spec.map (Scheme.ΓSpecIso (.of R)).inv := by
        rw [← Spec.map_comp]
        rfl
    _ = hV.isoSpec.hom ≫ hV.fromSpec ≫ f := by rw [h]
    _ = V.1.ι ≫ f := by rw [hι, Category.assoc]

/-- The local lift lies over `f`: `liftOn ≫ π = V.ι ≫ f` (from `affineBlowUp.chart_π` and
`affineBlowUpAlgebra.lift_comp_algebraMap`). -/
theorem liftOn_π : liftOn I f V a hβa hI ≫ affineBlowUp.π I = V.1.ι ≫ f := by
  rw [liftOn_eq, Category.assoc, Category.assoc, affineBlowUp.chart_π, ← Spec.map_comp,
    ← isoSpec_hom_specMap_sectionsHom f V]
  congr 2
  exact CommRingCat.hom_ext (affineBlowUpAlgebra.lift_comp_algebraMap _ a.2 hβa hI)

end LiftOn

end AlgebraicGeometry
