/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Admissible
public import Hironaka.Scheme.IdealSheaf.Defs
import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Uniqueness
import Hironaka.Scheme.BlowUp.InvertibleSheaf

/-!
# Existence of the lift: the universal property of the affine blow-up

An admissible `f : Y ⟶ Spec R` — one along which `I` becomes invertible — lifts uniquely to the
affine blow-up [Hau14, Theorem 4.18 (a)]; [Sta, Tag 0806]: the affine blow-up is final among the
schemes over `Spec R` on which `I` becomes invertible [Hau14, Definition 4.4].

Existence: `exists_affineOpen_generator` covers `Y` by affine opens `V_y ∋ y` on each of which
`I·Γ(Y, V_y)` is generated by the nonzerodivisor `f♯a_y`, so `liftOn f V_y a_y` gives local lifts
over `f`; on an overlap `V_y ∩ V_{y'}` (an open subscheme of `Y`, admissible by
`isInvertible_comap_comp_of_isOpenImmersion`, and not necessarily affine) the two local lifts
agree by the uniqueness theorem `affineBlowUp.hom_ext`, so they glue
(`Scheme.OpenCover.glueMorphisms`) to `lift f hf : Y ⟶ affineBlowUp I` with `lift f hf ≫ π = f`.
Uniqueness is `affineBlowUp.hom_ext`; together, `existsUnique_lift`.
-/

@[expose] public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits Scheme.IdealSheafData TopologicalSpace

universe u

variable {R : Type u} [CommRing R] (I : Ideal R) {Y : Scheme.{u}}

/-- Admissibility restricts along open immersions: if `f : Y ⟶ Spec R` is admissible for `I`, so
is `j ≫ f` for every open immersion `j : Z ⟶ Y`. -/
theorem isInvertible_comap_comp_of_isOpenImmersion (f : Y ⟶ Spec (.of R))
    (hf : ((specIdealSheaf I).comap f).IsInvertible) {Z : Scheme.{u}} (j : Z ⟶ Y)
    [IsOpenImmersion j] : ((specIdealSheaf I).comap (j ≫ f)).IsInvertible := by
  rw [Scheme.IdealSheafData.comap_comp]
  exact hf.comap_of_isOpenImmersion j

/-- Existence [Hau14, Theorem 4.18 (a)]; [Sta, Tag 0806]: an admissible `f : Y ⟶ Spec R` lifts to
the affine blow-up. -/
theorem affineBlowUp.exists_lift (f : Y ⟶ Spec (.of R))
    (hf : ((specIdealSheaf I).comap f).IsInvertible) :
    ∃ g : Y ⟶ affineBlowUp I, g ≫ affineBlowUp.π I = f := by
  choose V hyV a hβa hI using exists_affineOpen_generator I f hf
  have hcov : IsOpenCover fun y : Y => (V y).1 :=
    top_le_iff.mp fun z _ => Opens.mem_iSup.mpr ⟨z, hyV z⟩
  let 𝒰 : Y.OpenCover := Y.openCoverOfIsOpenCover (fun y => (V y).1) hcov
  let lifts : ∀ y : 𝒰.I₀, 𝒰.X y ⟶ affineBlowUp I := fun y =>
    liftOn I f (V y) (a y) (hβa y) (hI y)
  have hlifts : ∀ y : 𝒰.I₀, lifts y ≫ affineBlowUp.π I = 𝒰.f y ≫ f := fun y =>
    liftOn_π I f (V y) (a y) (hβa y) (hI y)
  have compat : ∀ y y', pullback.fst (𝒰.f y) (𝒰.f y') ≫ lifts y =
      pullback.snd (𝒰.f y) (𝒰.f y') ≫ lifts y' := by
    intro y y'
    refine affineBlowUp.hom_ext I (pullback.fst (𝒰.f y) (𝒰.f y') ≫ 𝒰.f y ≫ f) ?_ _ _ ?_ ?_
    · rw [← Category.assoc]
      exact isInvertible_comap_comp_of_isOpenImmersion I f hf _
    · rw [Category.assoc]
      exact congrArg (fun m => pullback.fst (𝒰.f y) (𝒰.f y') ≫ m) (hlifts y)
    · rw [Category.assoc]
      refine (congrArg (fun m => pullback.snd (𝒰.f y) (𝒰.f y') ≫ m) (hlifts y')).trans ?_
      rw [← Category.assoc, ← pullback.condition, Category.assoc]
  refine ⟨𝒰.glueMorphisms lifts compat, 𝒰.hom_ext _ _ fun y => ?_⟩
  rw [← Category.assoc, Scheme.Cover.ι_glueMorphisms]
  exact hlifts y

/-- **The universal property of the affine blow-up** [Hau14, Definition 4.4 and Theorem 4.18];
[Sta, Tag 0806]: an admissible `f : Y ⟶ Spec R` has exactly one lift. -/
theorem affineBlowUp.existsUnique_lift (f : Y ⟶ Spec (.of R))
    (hf : ((specIdealSheaf I).comap f).IsInvertible) :
    ∃! g : Y ⟶ affineBlowUp I, g ≫ affineBlowUp.π I = f := by
  obtain ⟨g, hg⟩ := affineBlowUp.exists_lift I f hf
  exact ⟨g, hg, fun g' hg' => affineBlowUp.hom_ext I f hf g' g hg' hg⟩

/-- **The lift** of an admissible `f : Y ⟶ Spec R` to the affine blow-up. -/
noncomputable def affineBlowUp.lift (f : Y ⟶ Spec (.of R))
    (hf : ((specIdealSheaf I).comap f).IsInvertible) : Y ⟶ affineBlowUp I :=
  (affineBlowUp.exists_lift I f hf).choose

@[reassoc (attr := simp)]
theorem affineBlowUp.lift_π (f : Y ⟶ Spec (.of R))
    (hf : ((specIdealSheaf I).comap f).IsInvertible) :
    affineBlowUp.lift I f hf ≫ affineBlowUp.π I = f :=
  (affineBlowUp.exists_lift I f hf).choose_spec

/-- Any lift is *the* lift. -/
theorem affineBlowUp.eq_lift (f : Y ⟶ Spec (.of R))
    (hf : ((specIdealSheaf I).comap f).IsInvertible) (g : Y ⟶ affineBlowUp I)
    (hg : g ≫ affineBlowUp.π I = f) : g = affineBlowUp.lift I f hf :=
  affineBlowUp.hom_ext I f hf g _ hg (affineBlowUp.lift_π I f hf)

end AlgebraicGeometry
