/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Admissible
public import Hironaka.Scheme.BlowUp.AffineBlowUp.Exceptional
import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Membership
import Hironaka.Scheme.BlowUp.Cancellation
import Hironaka.Scheme.IdealSheaf.StalkIdeal

/-!
# A lift lands in the chart of every stalk generator

Let `f : Y ⟶ Spec R` be admissible for `I` (the inverse image ideal sheaf `I·𝒪_Y` is invertible),
`g : Y ⟶ B = affineBlowUp I` a lift of `f` (`g ≫ π = f`), `y ∈ Y`, and `a ∈ I` an element whose
image generates the stalk `(I·𝒪_Y)_y`.  Then `g y` lies in the chart of `a`.

This is the step that makes the local patches of Hauser's proof agree on overlaps
[Hau14, Theorem 4.18, proof (a) and (c)] and that the last sentences of [Sta, Tag 0806] rely on,
made explicit; it is what fails without admissibility: the inclusion of the origin into `𝔸²` is
not admissible for the ideal `(x, y)`, and its lifts to the blow-up of the origin are the points
of the exceptional line.

The argument.  The point `g y` lies in the chart of some `b`, where the exceptional ideal has
stalk `(b)` (the criterion `affineBlowUp.mem_chart_iff`) and `a = b · u` with `u` the transport
of `a/b` (`affineBlowUp.exists_factor_of_mem_chart`).  Pulling back along the local homomorphism
`g♯_y : 𝒪_{B, g y} → 𝒪_{Y, y}`: the stalk `(I·𝒪_Y)_y` is the image of the stalk of the exceptional
ideal (`stalkIdeal_comap`), so it is `(f♯b)`; by hypothesis it is `(f♯a)`; and by admissibility
it is generated by a nonzerodivisor, so `f♯b` is a nonzerodivisor
(`mem_nonZeroDivisors_of_span_eq_span`).  From `f♯a = f♯b · g♯u` and `(f♯a) = (f♯b)`,
cancellation (`isUnit_of_span_mul_eq_span`) makes `g♯u` a unit; a local homomorphism reflects
units (`isUnit_map_iff`), so `u` is a unit at `g y`, and `g y` lies in the chart of `a`.
-/

public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory Scheme.IdealSheafData TopologicalSpace

universe u

variable {R : Type u} [CommRing R] (I : Ideal R) {Y : Scheme.{u}}

/-- For a lift `g` of `f`, the stalk of `I·𝒪_Y` at `y` is the image of the stalk of the
exceptional ideal at `g y` under the stalk map of `g`. -/
theorem stalkIdeal_comap_of_comp_π (f : Y ⟶ Spec (.of R)) (g : Y ⟶ affineBlowUp I)
    (hg : g ≫ affineBlowUp.π I = f) (y : Y) :
    ((specIdealSheaf I).comap f).stalkIdeal y =
      ((affineBlowUp.exceptionalIdeal I).stalkIdeal (g y)).map (g.stalkMap y).hom := by
  subst hg
  rw [Scheme.IdealSheafData.comap_comp]
  exact Scheme.IdealSheafData.stalkIdeal_comap _ g y

/-- The image of `r ∈ R` in `𝒪_{Y, y}` under a lift `g` of `f` factors through `𝒪_{B, g y}`. -/
theorem stalkMap_comp_π_germ (f : Y ⟶ Spec (.of R)) (g : Y ⟶ affineBlowUp I)
    (hg : g ≫ affineBlowUp.π I = f) (y : Y) (r : R) :
    g.stalkMap y ((affineBlowUp.π I).stalkMap (g y) ((Spec (.of R)).presheaf.germ ⊤
        (affineBlowUp.π I (g y)) (Opens.mem_top _) ((Scheme.ΓSpecIso (.of R)).inv.hom r))) =
      f.stalkMap y ((Spec (.of R)).presheaf.germ ⊤ (f y) (Opens.mem_top _)
        ((Scheme.ΓSpecIso (.of R)).inv.hom r)) := by
  subst hg
  have h2 := congrArg (fun φ : (Spec (.of R)).presheaf.stalk ((g ≫ affineBlowUp.π I) y) ⟶
        Y.presheaf.stalk y =>
      φ ((Spec (.of R)).presheaf.germ ⊤ ((g ≫ affineBlowUp.π I) y) (Opens.mem_top _)
        ((Scheme.ΓSpecIso (.of R)).inv.hom r)))
    (Scheme.Hom.stalkMap_comp g (affineBlowUp.π I) y)
  exact h2.symm

/-- **A lift lands in the chart of every stalk generator**: a lift `g` of an admissible
`f : Y ⟶ Spec R` sends `y` into the chart of every `a ∈ I` whose image generates the stalk of
`I·𝒪_Y` at `y`. The step behind the agreement of the local patches in
[Hau14, Theorem 4.18, proof (a)]; not stated there in this form. -/
theorem affineBlowUp.mem_chart_of_generates (f : Y ⟶ Spec (.of R))
    (hf : ((specIdealSheaf I).comap f).IsInvertible) (g : Y ⟶ affineBlowUp I)
    (hg : g ≫ affineBlowUp.π I = f) (y : Y) (a : I)
    (ha : ((specIdealSheaf I).comap f).stalkIdeal y =
      Ideal.span {f.stalkMap y ((Spec (.of R)).presheaf.germ ⊤ (f y)
        (Opens.mem_top _) ((Scheme.ΓSpecIso (.of R)).inv.hom a))}) :
    g y ∈ (affineBlowUp.chart I a).opensRange := by
  obtain ⟨b, hb⟩ := affineBlowUp.exists_mem_opensRange_chart I (g y)
  obtain ⟨u, hu, hmem⟩ := affineBlowUp.exists_factor_of_mem_chart I b a (g y) hb
  apply hmem
  -- the stalk of the exceptional ideal at `g y` is generated by the image of `b`
  have hstalk := (affineBlowUp.mem_chart_iff I b (g y)).mp hb
  -- pull back along `g♯_y`: `(I·𝒪_Y)_y = (f♯b)`
  have hJb : ((specIdealSheaf I).comap f).stalkIdeal y =
      Ideal.span {f.stalkMap y ((Spec (.of R)).presheaf.germ ⊤ (f y) (Opens.mem_top _)
        ((Scheme.ΓSpecIso (.of R)).inv.hom b))} := by
    rw [stalkIdeal_comap_of_comp_π I f g hg y, hstalk, Ideal.map_span, Set.image_singleton,
      stalkMap_comp_π_germ I f g hg y b]
  -- `f♯a = f♯b · g♯u`
  have hfa : f.stalkMap y ((Spec (.of R)).presheaf.germ ⊤ (f y) (Opens.mem_top _)
        ((Scheme.ΓSpecIso (.of R)).inv.hom a)) =
      f.stalkMap y ((Spec (.of R)).presheaf.germ ⊤ (f y) (Opens.mem_top _)
        ((Scheme.ΓSpecIso (.of R)).inv.hom b)) * g.stalkMap y u := by
    rw [← stalkMap_comp_π_germ I f g hg y a, ← stalkMap_comp_π_germ I f g hg y b, hu, map_mul]
  -- `f♯b` is a nonzerodivisor: the stalk of the invertible `I·𝒪_Y` has a nonzerodivisor generator
  obtain ⟨h, hh, hJh⟩ := hf.exists_mem_nonZeroDivisors_stalkIdeal_eq_span y
  have hnz : f.stalkMap y ((Spec (.of R)).presheaf.germ ⊤ (f y) (Opens.mem_top _)
      ((Scheme.ΓSpecIso (.of R)).inv.hom b)) ∈ nonZeroDivisors (Y.presheaf.stalk y) :=
    mem_nonZeroDivisors_of_span_eq_span hh (hJb.symm.trans hJh)
  -- cancellation: `g♯u` is a unit, hence `u` is (the stalk map is a local homomorphism)
  have hunit : IsUnit (g.stalkMap y u) :=
    isUnit_of_span_mul_eq_span hnz (by rw [← hfa, ← ha, hJb])
  exact (isUnit_map_iff (g.stalkMap y).hom u).mp hunit

end AlgebraicGeometry
