/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.ClosedSubspace
import Hironaka.Algebra.Local.Order
import Hironaka.AnalyticSpace.HomExt
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Closed subspaces: intersections, unions, reduction, and the predicates through the stalks

The elementary part of the theory of closed subspaces: the constructions on closed subspaces that
need no analysis, and the readings of the predicates of `Hironaka/AnalyticSpace/ClosedSubspace.lean`
through the stalks.

* `E ∩ F` is the subspace of the ideal sheaf **generated by** those of `E` and `F`
  (`inter := E + F`), `E ∪ F` the subspace of their **intersection** (`union`, given local
  generators of the intersection, which `hasLocalGenerators_inf` of
  `Hironaka/AnalyticSpace/CoherentAnalytic.lean` supplies). Their point sets are the intersection
  and the union of the point sets because, in a local ring, a sum of two ideals is the unit ideal
  only if one of them is (`Ideal.sup_eq_top_iff_of_isLocalRing`: two proper ideals lie in the
  maximal ideal), and an intersection is the unit ideal only if both are.
* `red X`, the reduction of `X` [Hir64, Ch. 0, §4], the subspace of the nilradical (given local
  generators of the nilradicals); `|red X| = |X|` because `1` is not nilpotent in a nontrivial
  ring; `red X` is reduced because the nilradical is a radical ideal; `X` is reduced iff every
  stalk has zero nilradical (`nilradical_eq_bot_iff`), iff `X` as the subspace `top X` of itself
  is reduced.
* `X.singularLocus` is the set of points with non-regular local ring (by definition), and `X` is
  non-singular iff every local ring is regular, iff `top X` is non-singular (the stalks of the
  quotient by the zero ideal sheaf are `𝒪_{X,x}/0 ≅ 𝒪_{X,x}`, `RingEquiv.quotientBot`)
  [Hir64, Ch. 0, §1, p. 121].
* The predicates through the stalks. `support`, `le`, `IsNonzeroEverywhere`,
  `IsIrreducible`, `HasOnlyNormalCrossingsWith`, `HasOnlyNormalCrossings` (with `top X = ⊥`) are
  read off by `Iff.rfl`; `top X` has full support and `IsUnit` means empty support; `ord` is `0`
  off the support and `⊤` exactly at a zero stalk (Krull's intersection theorem in the Noetherian
  stalk); the predicates defined through the subspace's structure sheaf — `IsReduced`,
  `IsSimplePointAt`, `IsNonsingular`, `dim` — are read through
  `stalkEquiv : 𝒪_{W,x} ≅ 𝒪_{X,x}/𝓘_x` (reducedness of the quotient is radicality of the ideal,
  `Ideal.isRadical_iff_quotient_reduced`; regularity and Krull dimension are invariant under ring
  isomorphisms), the supremum defining `dim` being bounded by `d` iff each local dimension is
  (`WithBot.unbotD_le_iff`).
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite Manifold

universe u

namespace AnalyticSpace

variable {K : Type} [RCLike K]

/-- In a local ring, a sum of ideals is the unit ideal only if one of them is. -/
theorem _root_.Ideal.sup_eq_top_iff_of_isLocalRing {R : Type*} [CommRing R] [IsLocalRing R]
    {I J : Ideal R} : I ⊔ J = ⊤ ↔ I = ⊤ ∨ J = ⊤ := by
  constructor
  · intro h
    by_contra hcon
    obtain ⟨hI₀, hJ₀⟩ := not_or.mp hcon
    have hI := IsLocalRing.le_maximalIdeal hI₀
    have hJ := IsLocalRing.le_maximalIdeal hJ₀
    exact (IsLocalRing.maximalIdeal.isMaximal R).ne_top (top_le_iff.mp (h ▸ sup_le hI hJ))
  · rintro (h | h)
    · rw [h, top_sup_eq]
    · rw [h, sup_top_eq]

namespace ClosedSubspace

variable {X : AnalyticSpace.{u} K}

/-- `E ∩ F`, the subspace of the ideal sheaf generated by those of `E` and `F`. -/
def inter (E F : ClosedSubspace X) : ClosedSubspace X := E + F

theorem stalkIdeal_inter (E F : ClosedSubspace X) (x : X) :
    (inter E F).stalkIdeal x = E.stalkIdeal x ⊔ F.stalkIdeal x :=
  IdealSheaf.stalkIdeal_add E F x

theorem support_inter (E F : ClosedSubspace X) : (inter E F).support = E.support ∩ F.support := by
  ext x
  change (inter E F).stalkIdeal x ≠ ⊤ ↔ E.stalkIdeal x ≠ ⊤ ∧ F.stalkIdeal x ≠ ⊤
  simp only [ne_eq, stalkIdeal_inter, Ideal.sup_eq_top_iff_of_isLocalRing, not_or]

/-- `E ∪ F`, the subspace of the intersection of the ideal sheaves of `E` and `F`, given local
generators `h` of the intersection. -/
def union (E F : ClosedSubspace X)
    (h : IdealSheaf.HasLocalGenerators (𝒪 := X.toLocallyRingedSpace.𝒪)
      fun x : X => E.stalkIdeal x ⊓ F.stalkIdeal x) : ClosedSubspace X :=
  IdealSheaf.ofStalks _ _ h

theorem stalkIdeal_union (E F : ClosedSubspace X)
    (h : IdealSheaf.HasLocalGenerators (𝒪 := X.toLocallyRingedSpace.𝒪)
      fun x : X => E.stalkIdeal x ⊓ F.stalkIdeal x) (x : X) :
    (union E F h).stalkIdeal x = E.stalkIdeal x ⊓ F.stalkIdeal x :=
  IdealSheaf.stalkIdeal_ofStalks _ _ x

theorem support_union (E F : ClosedSubspace X)
    (h : IdealSheaf.HasLocalGenerators (𝒪 := X.toLocallyRingedSpace.𝒪)
      fun x : X => E.stalkIdeal x ⊓ F.stalkIdeal x) :
    (union E F h).support = E.support ∪ F.support := by
  ext x
  change (union E F h).stalkIdeal x ≠ ⊤ ↔ E.stalkIdeal x ≠ ⊤ ∨ F.stalkIdeal x ≠ ⊤
  simp only [ne_eq, stalkIdeal_union, inf_eq_top_iff, not_and_or]

end ClosedSubspace


variable (X : AnalyticSpace.{u} K)

/-- The reduction `red X` [Hir64, Ch. 0, §4]: the closed subspace of the nilradical, given local
generators `h` of the nilradicals. -/
def red (h : IdealSheaf.HasLocalGenerators (𝒪 := X.toLocallyRingedSpace.𝒪)
    fun x : X => nilradical (X.presheaf.stalk x)) : ClosedSubspace X :=
  IdealSheaf.ofStalks _ _ h

theorem stalkIdeal_red (h : IdealSheaf.HasLocalGenerators (𝒪 := X.toLocallyRingedSpace.𝒪)
    fun x : X => nilradical (X.presheaf.stalk x)) (x : X) :
    (red X h).stalkIdeal x = nilradical (X.presheaf.stalk x) :=
  IdealSheaf.stalkIdeal_ofStalks _ _ x

theorem support_red (h : IdealSheaf.HasLocalGenerators (𝒪 := X.toLocallyRingedSpace.𝒪)
    fun x : X => nilradical (X.presheaf.stalk x)) : (red X h).support = Set.univ := by
  apply Set.eq_univ_of_forall
  intro x
  change (red X h).stalkIdeal x ≠ ⊤
  rw [stalkIdeal_red]
  intro htop
  exact not_isNilpotent_one (mem_nilradical.mp ((Ideal.eq_top_iff_one _).mp htop))

theorem isReduced_iff_nilradical_eq_bot :
    X.IsReduced ↔ ∀ x : X, nilradical (X.presheaf.stalk x) = ⊥ :=
  forall_congr' fun _ => nilradical_eq_bot_iff.symm

/-- The multiple points [Hir64, Ch. 0, §1, p. 121]: the points whose local ring is not regular. -/
theorem singularLocus_eq : singularLocus X = {x | ¬ IsRegularLocalRing (X.presheaf.stalk x)} := rfl

/-- `X` is non-singular iff every local ring is regular [Hir64, Ch. 0, §1, p. 121]. -/
theorem isNonsingular_iff : X.IsNonsingular ↔ ∀ x : X, IsRegularLocalRing (X.presheaf.stalk x) :=
  Set.eq_univ_iff_forall


namespace ClosedSubspace

variable {X : AnalyticSpace.{u} K} (W V E D : ClosedSubspace X)

theorem mem_support_iff (x : X) : x ∈ W.support ↔ W.stalkIdeal x ≠ ⊤ := Iff.rfl

@[simp]
theorem support_top : (top X).support = Set.univ := by
  apply Set.eq_univ_of_forall
  intro x
  change (⊥ : IdealSheaf X.toLocallyRingedSpace.𝒪).stalkIdeal x ≠ ⊤
  rw [IdealSheaf.stalkIdeal_bot]
  exact bot_ne_top

theorem le_iff : W.le V ↔ ∀ x : X, V.stalkIdeal x ≤ W.stalkIdeal x := Iff.rfl

theorem support_mono (h : W.le V) : W.support ⊆ V.support := by
  intro x hx htop
  exact hx (top_le_iff.mp (htop ▸ h x))

theorem isUnit_iff : W.IsUnit ↔ W.support = ∅ := by
  constructor
  · intro h
    apply Set.eq_empty_of_forall_notMem
    intro x hx
    apply hx
    rw [h, IdealSheaf.stalkIdeal_top]
  · intro h
    apply IdealSheaf.ext
    intro x
    rw [IdealSheaf.stalkIdeal_top]
    by_contra hne
    exact Set.notMem_empty x (h ▸ (hne : x ∈ W.support))

theorem isNonzeroEverywhere_iff : W.IsNonzeroEverywhere ↔ ∀ x : X, W.stalkIdeal x ≠ ⊥ := Iff.rfl

theorem isIrreducible_iff :
    W.IsIrreducible ↔ W.support.Nonempty ∧ ∀ Z₁ Z₂ : ClosedSubspace X,
      W.support ⊆ Z₁.support ∪ Z₂.support → W.support ⊆ Z₁.support ∨ W.support ⊆ Z₂.support :=
  Iff.rfl

theorem hasOnlyNormalCrossings_iff :
    E.HasOnlyNormalCrossings ↔ E.HasOnlyNormalCrossingsWith (top X) := Iff.rfl

theorem ord_eq_zero_iff (x : X) : W.ord x = 0 ↔ x ∉ W.support := IdealSheaf.ord_eq_zero_iff W

theorem ord_eq_top_iff (x : X) : W.ord x = ⊤ ↔ W.stalkIdeal x = ⊥ := by
  have : IsNoetherianRing (X.toLocallyRingedSpace.𝒪.presheaf.stalk x) :=
    AnalyticSpace.isNoetherianRing_stalk X x
  exact IsLocalRing.ord_eq_top_iff

/-- The stalk of the subspace at `⟨x, h⟩` is `𝒪_{X,x}/𝓘_x`, so regularity and reducedness of the
subspace at `x` are those of the quotient ring. -/
theorem isRegularLocalRing_space_stalk_iff (x : X) (h : x ∈ W.support) :
    IsRegularLocalRing (W.space.toLocallyRingedSpace.presheaf.stalk ⟨x, h⟩) ↔
      IsRegularLocalRing (X.presheaf.stalk x ⧸ W.stalkIdeal x) := by
  constructor
  · intro hr
    exact hr.of_ringEquiv (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W ⟨x, h⟩)
  · intro hr
    exact hr.of_ringEquiv (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W ⟨x, h⟩).symm

theorem isSimplePointAt_iff (x : X) :
    W.IsSimplePointAt x ↔
      x ∈ W.support ∧ IsRegularLocalRing (X.presheaf.stalk x ⧸ W.stalkIdeal x) := by
  constructor
  · rintro ⟨h, hr⟩
    exact ⟨h, (isRegularLocalRing_space_stalk_iff W x h).mp hr⟩
  · rintro ⟨h, hr⟩
    exact ⟨h, (isRegularLocalRing_space_stalk_iff W x h).mpr hr⟩

theorem isNonsingular_iff_forall :
    W.IsNonsingular ↔
      ∀ x : X, x ∈ W.support → IsRegularLocalRing (X.presheaf.stalk x ⧸ W.stalkIdeal x) := by
  constructor
  · intro hW x hx
    exact (isRegularLocalRing_space_stalk_iff W x hx).mp (hW ⟨x, hx⟩)
  · intro hW y
    exact (isRegularLocalRing_space_stalk_iff W y.1 y.2).mpr (hW y.1 y.2)

theorem isReduced_iff : W.IsReduced ↔ ∀ x : X, (W.stalkIdeal x).IsRadical := by
  constructor
  · intro hW x
    by_cases hx : x ∈ W.support
    · rw [Ideal.isRadical_iff_quotient_reduced]
      have : _root_.IsReduced
          ((QuotientSpace.presheafCommRing X.toLocallyRingedSpace W).stalk ⟨x, hx⟩) :=
        hW ⟨x, hx⟩
      exact isReduced_of_injective
        (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W ⟨x, hx⟩).symm.toRingHom
        (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W ⟨x, hx⟩).symm.injective
    · have : W.stalkIdeal x = ⊤ := not_not.mp hx
      rw [this]
      exact le_top
  · intro hW y
    have hr : _root_.IsReduced (QuotientSpace.fiber X.toLocallyRingedSpace W y) :=
      (Ideal.isRadical_iff_quotient_reduced _).mp (hW y.1)
    exact isReduced_of_injective (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W y).toRingHom
      (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W y).injective

theorem hasOnlyNormalCrossingsWith_iff :
    E.HasOnlyNormalCrossingsWith D ↔ ∀ x : X, x ∈ D.support →
      ∃ (n : ℕ) (z : Fin n → X.presheaf.stalk x),
        (Ideal.span (Set.range z) = IsLocalRing.maximalIdeal (X.presheaf.stalk x) ∧
          (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk x)) ∧
        (∀ P ∈ (E.stalkIdeal x).minimalPrimes, ∃ i, P = Ideal.span {z i}) ∧
        ∃ s : Finset (Fin n), D.stalkIdeal x = Ideal.span (z '' ↑s) := Iff.rfl

theorem dim_le_iff (d : ℕ∞) :
    W.dim ≤ d ↔ ∀ x : X, x ∈ W.support →
      ringKrullDim (X.presheaf.stalk x ⧸ W.stalkIdeal x) ≤ (d : WithBot ℕ∞) := by
  change (⨆ y : W.space,
    (ringKrullDim (W.space.toLocallyRingedSpace.presheaf.stalk y)).unbotD 0) ≤ d ↔ _
  rw [iSup_le_iff]
  constructor
  · intro h x hx
    have e : ringKrullDim (W.space.toLocallyRingedSpace.presheaf.stalk ⟨x, hx⟩) =
        ringKrullDim (X.presheaf.stalk x ⧸ W.stalkIdeal x) :=
      ringKrullDim_eq_of_ringEquiv (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W ⟨x, hx⟩)
    have := h ⟨x, hx⟩
    rw [WithBot.unbotD_le_iff (fun _ => zero_le), e] at this
    exact this
  · intro h y
    have e : ringKrullDim (W.space.toLocallyRingedSpace.presheaf.stalk y) =
        ringKrullDim (X.presheaf.stalk y.1 ⧸ W.stalkIdeal y.1) :=
      ringKrullDim_eq_of_ringEquiv (QuotientSpace.stalkEquiv X.toLocallyRingedSpace W y)
    rw [WithBot.unbotD_le_iff (fun _ => zero_le), e]
    exact h y.1 y.2

end ClosedSubspace


variable (X : AnalyticSpace.{u} K)

theorem isReduced_red (h : IdealSheaf.HasLocalGenerators (𝒪 := X.toLocallyRingedSpace.𝒪)
    fun x : X => nilradical (X.presheaf.stalk x)) : (red X h).IsReduced := by
  rw [ClosedSubspace.isReduced_iff]
  intro x
  rw [stalkIdeal_red]
  exact Ideal.radical_isRadical _

theorem isReduced_iff_isReduced_top : X.IsReduced ↔ (ClosedSubspace.top X).IsReduced := by
  rw [ClosedSubspace.isReduced_iff]
  refine forall_congr' fun x => ?_
  change _root_.IsReduced (X.presheaf.stalk x) ↔
    ((⊥ : IdealSheaf X.toLocallyRingedSpace.𝒪).stalkIdeal x).IsRadical
  rw [IdealSheaf.stalkIdeal_bot, Ideal.isRadical_bot_iff]
  exact Iff.rfl

theorem isNonsingular_iff_isNonsingular_top :
    X.IsNonsingular ↔ (ClosedSubspace.top X).IsNonsingular := by
  rw [isNonsingular_iff, ClosedSubspace.isNonsingular_iff_forall]
  constructor
  · intro h x _
    have hx := h x
    change IsRegularLocalRing
      (X.presheaf.stalk x ⧸ (⊥ : IdealSheaf X.toLocallyRingedSpace.𝒪).stalkIdeal x)
    rw [IdealSheaf.stalkIdeal_bot]
    exact hx.of_ringEquiv (RingEquiv.quotientBot _).symm
  · intro h x
    have hx : x ∈ (ClosedSubspace.top X).support := by
      rw [ClosedSubspace.support_top]
      trivial
    have h1 := h x hx
    change IsRegularLocalRing
      (X.presheaf.stalk x ⧸ (⊥ : IdealSheaf X.toLocallyRingedSpace.𝒪).stalkIdeal x) at h1
    rw [IdealSheaf.stalkIdeal_bot] at h1
    exact h1.of_ringEquiv (RingEquiv.quotientBot _)


end AnalyticSpace
