/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.ClosedSubspace.Defs
public import Hironaka.Manifold.IdealSheaf.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# Closed analytic subspaces: operations and predicates

The operations on the closed subspaces `ClosedSubspace X := IdealSheaf X.𝒪` of an analytic
`K`-space `X` [Hir64, Ch. 0, §1 and §5], [BM97, §3], and the predicates of [Hir64] on them, read
through the ideal sheaf `𝓘` or through the subspace `Y = (S(𝓘), (𝒪_X/𝓘)|_{S(𝓘)})`, whose stalks
are `𝒪_{Y,y} ≅ 𝒪_{X,y}/𝓘_y` (`QuotientSpace.stalkEquiv`).

## Main definitions

* `support` (Hironaka's `S(𝓘)`, the cosupport of the ideal sheaf), `top X` (the zero ideal sheaf,
  `X` as a subspace of itself), `le W V` (`W ⊆ V`, i.e. `𝓘_V ⊆ 𝓘_W`), `IsUnit` (`𝓘 = 𝒪_X`, the
  empty subspace), `IsNonzeroEverywhere` (Hironaka's "coherent sheaf of non-zero ideals": every
  stalk nonzero), `ord` (Hironaka's order `ν(𝓘_x)` of the stalk ideal [Hir64, Ch. 0, §3]).
* `space W`, the subspace `Y = (S(𝓘), (𝒪_X/𝓘)|_{S(𝓘)})` as a `K`-local-ringed space, and through
  its stalks (Hironaka's definitions "for arbitrary local-ringed spaces" [Hir64, Ch. 0, §1,
  p. 121]): `IsReduced W` (every stalk of `𝒪_Y` reduced), `IsNonsingular W` (every stalk of `𝒪_Y`
  regular), `IsSimplePointAt W x` (`x ∈ |Y|` and `𝒪_{Y,x}` regular), `dim W`
  (`sup_{y ∈ |Y|} dim 𝒪_{Y,y}`, the Krull dimension of the stalks [Fre17, II 5.2]).
* `IsIrreducible W`: `|W|` nonempty and contained in a union of two closed analytic subsets only
  if contained in one of them (irreducibility in the Zariski topology of [BM97, 3.9], whose
  closed sets are the supports of closed subspaces; Hironaka's "a maximal reduced irreducible …
  analytic subspace" [Hir64, Ch. 0, §5, Definition 2, p. 141]).
* `IsInvertible E` (`IdealSheaf.IsInvertible` of `Hironaka/Manifold/IdealSheaf/Basic.lean`, as for
  any ideal sheaf): `𝓘_E` is locally free of rank one — at every point the stalk is generated by
  a single non-zero-divisor (Hironaka's invertible sheaf of ideals [Hir64, Ch. 0, §2],
  Definition 2's "everywhere of codimension one").
* `HasOnlyNormalCrossingsWith E D`, `HasOnlyNormalCrossings E`: Hironaka's Definition 2
  [Hir64, Ch. 0, §5] at the stalk level — at every point `x` of `D` a regular system of
  parameters of `𝒪_{X,x}` such that the ideal of each irreducible component of `E` through `x` (a
  minimal prime of `𝓘_{E,x}`) is generated by one parameter and `𝓘_{D,x}` by some of them;
  `D = X` is `D = ⊥`. The two clauses of a regular system of parameters (it generates `𝔪_x`; it
  has as many members as the Krull dimension) are written out. The boundary predicate of the
  resolution theorem, `IsSncBoundary`, reads Definition 2 on global components instead.
* `comap D f`, the inverse image `f⁻¹(𝓘_D)𝒪_Y` of a closed subspace `D ⊆ X` along a morphism
  `f : Y → X` [Hir64, Ch. 0, §5], the total transform of `D` by `f`.
* `IsNormallyFlatAlongAt V W x`: Hironaka's Definition 1 [Hir64, Ch. 0, §4] — with `J` the ideal
  of `W` in `V`, i.e. the image of `𝓘_{W,x}` in `𝒪_{V,x} = 𝒪_{X,x}/𝓘_{V,x}`, the stalk at `x ∈ W`
  of every `gr^p = J^p/J^{p+1}` is a free `𝒪_{W,x} = 𝒪_{V,x}/J`-module. No result of this library
  is proved about normal flatness.

The subspace's `IsReduced` and `IsNonsingular` are those of the analytic space
`closedSubspace X W` by definition; its image in `X` is the support `S(𝓘)`
(`range_toFun_closedSubspaceι`), and a point of the space is simple iff its image is a simple
point of the subspace (`mem_reg_closedSubspace_iff`).
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite Manifold

universe u

namespace AnalyticSpace

variable {K : Type} [RCLike K]

/-- The stalks of the structure sheaf of a locally ringed space, read through `X.𝒪` (a `def` in
Mathlib, so the instance Mathlib states for `X.presheaf.stalk x` is not found for it), are local
rings — the instance `IdealSheaf.ord` asks for on `IdealSheaf X.𝒪`. -/
instance instIsLocalRingStalkSheaf (X : LocallyRingedSpace.{u}) (x : X) :
    IsLocalRing (X.𝒪.presheaf.stalk x) :=
  X.isLocalRing x

namespace ClosedSubspace

variable {X : AnalyticSpace.{u} K}

/-- `X` itself as a closed subspace: the zero ideal sheaf. -/
def top (X : AnalyticSpace.{u} K) : ClosedSubspace X := ⊥

/-- The inclusion `W ⊆ V` of closed subspaces is the reverse inclusion `𝓘_V ⊆ 𝓘_W` of their ideal
sheaves (stalkwise). -/
def le (W V : ClosedSubspace X) : Prop := V ≤ W

/-- The ideal sheaf of the subspace is the unit ideal sheaf, `𝓘 = 𝒪_X`: the empty subspace (the
final clause `J_γ = 𝒪_{X_γ}` of [Hir64, Main Theorem II′(N) (iv), p. 156]). -/
def IsUnit (J : ClosedSubspace X) : Prop := J = ⊤

/-- Every stalk of the ideal sheaf is nonzero (Hironaka's "coherent sheaf of non-zero ideals"
[Hir64, Main Theorem II'(N), p. 156]). -/
def IsNonzeroEverywhere (J : ClosedSubspace X) : Prop := IdealSheaf.IsNonzeroEverywhere J

/-- `ν(𝓘_x)`, the order of the stalk ideal at `x` [Hir64, Ch. 0, §3]: the largest `ν` with
`𝓘_x ⊆ 𝔪_x^ν`, `⊤` when `𝓘_x = 0`. -/
def ord (J : ClosedSubspace X) (x : X) : ℕ∞ := IdealSheaf.ord J x

/-- The subspace `Y = (S(𝓘), (𝒪_X/𝓘)|_{S(𝓘)})` [Hir64, Ch. 0, §1], [BM97, §3] as a
`K`-local-ringed space, with the `K`-structure induced along the canonical morphism `Y ⟶ X`. Its
stalk at `y` is `𝒪_{X,y}/𝓘_y` (`QuotientSpace.stalkEquiv`). -/
abbrev space (W : ClosedSubspace X) : KLocallyRingedSpace.{u} K :=
  X.toKLocallyRingedSpace.quotient W

/-- The subspace is reduced [Hir64, Introduction]: its structure sheaf `𝒪_Y` has no nilpotent
elements, i.e. every stalk of `𝒪_Y` is reduced. -/
def IsReduced (W : ClosedSubspace X) : Prop :=
  ∀ y : W.space, _root_.IsReduced (W.space.toLocallyRingedSpace.presheaf.stalk y)

/-- The subspace is non-singular [Hir64, Ch. 0, §1, p. 121]: every point of `|Y|` is a simple
point of `Y`, its local ring `𝒪_{Y,y}` regular. -/
def IsNonsingular (W : ClosedSubspace X) : Prop :=
  ∀ y : W.space, IsRegularLocalRing (W.space.toLocallyRingedSpace.presheaf.stalk y)

/-- `x` is a simple point of the subspace `W` [Hir64, Ch. 0, §1, p. 121]: `x ∈ |W|` and the local
ring `𝒪_{W,x}` of the subspace at `x` is regular. -/
def IsSimplePointAt (W : ClosedSubspace X) (x : X) : Prop :=
  ∃ h : x ∈ W.support, IsRegularLocalRing (W.space.toLocallyRingedSpace.presheaf.stalk ⟨x, h⟩)

/-- The dimension of the subspace `W` (the dimension of `W` that Main Theorem I'(n) of
[Hir64, Ch. 0, §7, p. 155] uses without defining it there): the supremum over the points `y` of
`|W|` of the Krull dimension of `𝒪_{W,y}` [Fre17, II 5.2] (as an
element of `ℕ∞`; `0` for the empty subspace, whose supremum is over no points; a stalk of a
nonempty subspace is a nontrivial local ring, so no `⊥` is ever read). -/
def dim (W : ClosedSubspace X) : ℕ∞ :=
  ⨆ y : W.space, (ringKrullDim (W.space.toLocallyRingedSpace.presheaf.stalk y)).unbotD 0

/-- The subspace is irreducible, and nonempty (Hironaka's "a maximal reduced irreducible …
analytic subspace" [Hir64, Ch. 0, §5, Definition 2, p. 141]; the Zariski topology of
[BM97, 3.9]): its set of points is not contained in the union of the point sets of two closed
analytic subspaces unless it is contained in one of them. -/
def IsIrreducible (W : ClosedSubspace X) : Prop :=
  W.support.Nonempty ∧ ∀ Z₁ Z₂ : ClosedSubspace X,
    W.support ⊆ Z₁.support ∪ Z₂.support → W.support ⊆ Z₁.support ∨ W.support ⊆ Z₂.support

/-- Hironaka's Definition 2 [Hir64, Ch. 0, §5] for analytic spaces, at the stalk level: `E` has
only normal crossings with `D` if at every point `x` of `D` there is a regular system of
parameters `(z_1, …, z_n)` of `𝒪_{X,x}` (`n` generators of the maximal ideal, `n` the Krull
dimension) such that the ideal of each irreducible component of `E` through `x` (a minimal prime
of `𝓘_{E,x}`) is generated by one of the `z_i` and the ideal `𝓘_{D,x}` of `D` is generated by
some of the `z_i`. Definition 2 presupposes `X` non-singular, `E` reduced and `𝓘_E` invertible;
those are hypotheses of the statements that use the predicate, not part of it. -/
def HasOnlyNormalCrossingsWith (E D : ClosedSubspace X) : Prop :=
  ∀ x ∈ D.support, ∃ (n : ℕ) (z : Fin n → X.presheaf.stalk x),
    (Ideal.span (Set.range z) = IsLocalRing.maximalIdeal (X.presheaf.stalk x) ∧
      (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk x)) ∧
    (∀ P ∈ (E.stalkIdeal x).minimalPrimes, ∃ i, P = Ideal.span {z i}) ∧
    ∃ s : Finset (Fin n), D.stalkIdeal x = Ideal.span (z '' ↑s)

/-- Hironaka's Definition 2 with `D = X` ("we simply say that `E` has only normal crossings"
[Hir64, Ch. 0, §5]): `HasOnlyNormalCrossingsWith E ⊥`, the zero ideal sheaf `⊥` being the ideal
of `X` itself (`top X`). -/
def HasOnlyNormalCrossings (E : ClosedSubspace X) : Prop := HasOnlyNormalCrossingsWith E ⊥

/-! ### Inverse images -/

/-- The inverse image `f⁻¹(𝓘_D)·𝒪_Y` of a closed subspace `D ⊆ X` along a morphism `f : Y → X`
[Hir64, Ch. 0, §5] (the sheaf of ideals generated by the pull-back of `𝓘_D`, the total transform
of `D` by `f`): the closed subspace of `Y` whose stalk at `y` is the ideal generated by the image
of `𝓘_{D, f y}` under the stalk map — `QuotientSpace.comap` on the underlying morphism of locally
ringed spaces. -/
noncomputable def comap {X Y : AnalyticSpace.{u} K} (D : ClosedSubspace X) (f : Y ⟶ X) :
    ClosedSubspace Y :=
  AnalyticSpace.QuotientSpace.comap f.1 D

/-! ### Normal flatness (Hironaka's Definition 1) -/

/-- The `p`-th graded piece `I^p / I^{p+1}` of the `I`-adic filtration of `R`, as a module over
`R/I` (Hironaka's `gr^p`, the stalk of `J^p/J^{p+1}` [Hir64, Ch. 0, §4, Definition 1]; Mathlib
supplies the `R ⧸ I`-module structure on `M ⧸ I • M`). -/
abbrev grPiece {R : Type*} [CommRing R] (I : Ideal R) (p : ℕ) : Type _ :=
  ↥(I ^ p) ⧸ (I • (⊤ : Submodule R ↥(I ^ p)))

/-- The ideal `J` of the subspace `W` in the subspace `V` at the point `x` [Hir64, Ch. 0, §4,
Definition 1]: the image of `𝓘_{W,x}` in `𝒪_{V,x} = 𝒪_{X,x}/𝓘_{V,x}`. -/
def relativeIdeal (V W : ClosedSubspace X) (x : X) :
    Ideal (X.presheaf.stalk x ⧸ V.stalkIdeal x) :=
  (W.stalkIdeal x).map (Ideal.Quotient.mk (V.stalkIdeal x))

/-- Hironaka's Definition 1 [Hir64, Ch. 0, §4]: the analytic subspace `V` of `X` is normally flat
along its subspace `W` at the point `x` of `W` if, with `J` the ideal of `W` in `V`, the stalk at
`x` of `gr^p = J^p/J^{p+1}` is a free `𝒪_{W,x}`-module for every `p ≥ 0`, where
`𝒪_{W,x} = 𝒪_{V,x}/J_x`. With `V = top X` this is "`X` is normally flat along `W` at `x`". No
result of this library is proved about normal flatness. -/
def IsNormallyFlatAlongAt (V W : ClosedSubspace X) (x : X) : Prop :=
  x ∈ W.support ∧ ∀ p : ℕ,
    Module.Free ((X.presheaf.stalk x ⧸ V.stalkIdeal x) ⧸ relativeIdeal V W x)
      (grPiece (relativeIdeal V W x) p)

end ClosedSubspace

end AnalyticSpace

/-! ### The closed subspace as an analytic space -/

open AnalyticSpace.KLocallyRingedSpace AnalyticSpace.QuotientSpace

namespace AnalyticSpace

variable {K : Type} [RCLike K] (X : AnalyticSpace.{u} K)

/-- The image of the closed subspace in `X` is its support `S(𝓘)`. -/
theorem range_toFun_closedSubspaceι (J : IdealSheaf X.toLocallyRingedSpace.𝒪) :
    Set.range (Hom.toFun (closedSubspaceι X J)) = J.support :=
  Subtype.range_coe

theorem mem_reg_closedSubspace_iff (W : ClosedSubspace X) (y : closedSubspace X W) :
    y ∈ regularLocus (closedSubspace X W) ↔ W.IsSimplePointAt (Hom.toFun (closedSubspaceι X W) y) :=
  ⟨fun hr => ⟨y.2, hr⟩, fun ⟨_, hr⟩ => hr⟩

end AnalyticSpace
