/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.Quotient.Defs
public import Mathlib.Geometry.Manifold.Sheaf.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# Analytic `K`-spaces

Hironaka's definition [Hir64, Ch. 0, §1, pp. 119–121] starts from `K ∈ {ℝ, ℂ}` with its standard
topology, the Cartesian power `Kⁿ`, and `𝒜_{Kⁿ}`, the sheaf of germs of analytic `K`-functions on
`Kⁿ` — the sheaf whose stalks are the convergent power series rings
`𝒜_{Kⁿ,x} = K{z₁ - x₁, …, zₙ - xₙ}`. For an open `G ⊆ Kⁿ`, `𝒜_G` is the restriction of `𝒜_{Kⁿ}`
to `G` and `(G, 𝒜_G)` is a `K`-local-ringed space. A **local analytic `K`-space** is
`(S(𝓘), (𝒜_G/𝓘)|_{S(𝓘)})`, where `𝓘 ⊆ 𝒜_G` is the sheaf of ideals generated by finitely many
regular analytic `K`-functions `f₁, …, f_k` on `G` and `S(𝓘)` is the support of `𝒜_G/𝓘`. An
**analytic `K`-space** is a `K`-local-ringed space `X = (X, 𝒪_X)` such that (i) every point `x`
has an open neighbourhood `U` with `(U, 𝒪_X|U)` `K`-isomorphic to a local analytic `K`-space,
(ii) `X` is countable at infinity (a union of countably many compact subsets), and (iii) `X` is
Hausdorff. `An/K` is the full subcategory of `ℜ/K` on the analytic `K`-spaces
[Hir64, Ch. 0, §1, p. 121]. Preanalytic `K`-spaces ((i) and (ii) only) are not needed and are
not defined.

## The local models

* `Kn K n`: `Kⁿ` placed in the universe `u` as `ULift (Fin n → K)`. Analytic `K`-spaces have
  carriers in an arbitrary universe `u` while `K : Type`, and a local model must be a locally
  ringed space in the same universe as the spaces it models; the lift is a linear isometry
  (`ContinuousLinearEquiv.ulift`) and changes nothing else.
* `affine K n = (Kⁿ, 𝒜_{Kⁿ})`: `KLocallyRingedSpace.ofManifold` of `Kⁿ` as an analytic manifold
  over itself, so that `𝒜_{Kⁿ}` is the sheaf of analytic functions and its stalks are the local
  rings of analytic germs (identified with convergent power series rings by `taylorAffine`), with
  the constants as `K`-structure.
* `AnalyticFun K n G = Γ(G, 𝒜_{Kⁿ})` and `analyticSpaceOfOpen K n G = (G, 𝒜_G)`, the restriction
  of `affine K n` to `G`; `toGlobal G` reads an analytic function on `G` as a global section of
  `𝒜_G`.
* `modelIdeal K n G f`, the ideal sheaf `𝓘 = (f₁, …, f_k) ⊆ 𝒜_G` generated by the global sections
  `f_i` (`IdealSheaf.ofGlobal`), and `localModel K n G f = (S(𝓘), (𝒜_G/𝓘)|_{S(𝓘)})`, the quotient
  (`KLocallyRingedSpace.quotient`) of `(G, 𝒜_G)` by `𝓘`.

## The local-model clause

`AnalyticSpace K` extends `KLocallyRingedSpace K` by the fields `locallyModel` (i), `sigmaCompact`
(ii) and `t2` (iii), following the pattern of `AlgebraicGeometry.Scheme`. Clause (i) is stated
**up to an open of the model**: `X|U ≅ (localModel G f)|W` for an open `W` of the local model
`(S(𝓘), (𝒜_G/𝓘)|_{S(𝓘)})`. An open subset of a local analytic `K`-space is again a local
analytic `K`-space (`W = S(𝓘) ∩ G'` for an open `G' ⊆ G`, and `(localModel G f)|W` is the local
model of the restricted equations on `G'`), so the two forms define the same class of spaces. The
form with `W` makes the open subspace `X|U` of an analytic space an analytic space by a formal
argument (open immersions with equal ranges are isomorphic, `KLocallyRingedSpace.isoOfRangeEq`),
whereas the literal form would need that identification of restricted models first, which is a
theorem about the quotient construction (`localModel_restrictOpen_iso`) and not a definition.

## Main definitions

* `AnalyticSpace K`, whose carrier is Hausdorff (`t2`) and σ-compact (`sigmaCompact`);
* the category `An/K`: `X ⟶ Y` (`AnalyticSpace.Hom X Y`) are the `K`-morphisms of the underlying
  `K`-local-ringed spaces (a full subcategory), `Hom.toFun` the underlying map (the coercion `⇑f`);
  an isomorphism of analytic spaces is an isomorphism in `An/K` (Mathlib's `IsIso`);
* `regularLocus X`, the simple points (`x` is simple if `𝒪_{X,x}` is a regular local ring,
  `IsRegularLocalRing`), `singularLocus X` its complement, and `IsNonsingular` (no multiple
  points);
* `IsReduced X`: the structure sheaf has no nilpotents, read through the stalks (every stalk is
  reduced, which is equivalent to every ring of sections being reduced).

These are the objects the resolution theorem for analytic spaces
(`AnalyticSpace.exists_functorial_resolution`) quantifies over.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite

universe u

namespace AnalyticSpace

/-! ### The local models -/

section Model

open Manifold

variable (K : Type) [RCLike K] (n : ℕ)

/-- `Kⁿ`, placed in the universe `u` (a linear isometry away from `Fin n → K`; see the module
docstring). -/
abbrev Kn : Type u := ULift.{u} (Fin n → K)

/-- `(Kⁿ, 𝒜_{Kⁿ})`, the `K`-local-ringed space of the sheaf of regular analytic `K`-functions on
`Kⁿ` [Hir64, Ch. 0, §1]: `Kⁿ` as an analytic manifold over itself. -/
@[implicit_reducible]
def affine : KLocallyRingedSpace.{u} K :=
  KLocallyRingedSpace.ofManifold K (Kn.{u} K n) (Kn.{u} K n)

/-- `Γ(G, 𝒜_{Kⁿ})`: the regular analytic `K`-functions on the open `G ⊆ Kⁿ` (Hironaka's
"elements of `Γ(G, 𝒜_G)`"). -/
abbrev AnalyticFun (G : Opens (Kn.{u} K n)) : Type u :=
  (affine K n).toLocallyRingedSpace.presheaf.obj (op G)

/-- `(G, 𝒜_G)` for an open `G ⊆ Kⁿ`, `𝒜_G` the restriction of `𝒜_{Kⁿ}` to `G`; a `K`-local-ringed
space [Hir64, Ch. 0, §1]. -/
@[implicit_reducible]
def analyticSpaceOfOpen (G : Opens (Kn.{u} K n)) : KLocallyRingedSpace.{u} K :=
  (affine K n).restrictOpen G

/-- An analytic function on `G` as a global section of `𝒜_G` (the restriction map along the
identification of `G` with the top open of the subspace). -/
def toGlobal (G : Opens (Kn.{u} K n)) :
    AnalyticFun K n G →+* (analyticSpaceOfOpen K n G).toLocallyRingedSpace.presheaf.obj (op ⊤) :=
  ((affine K n).toLocallyRingedSpace.presheaf.map
    (homOfLE (le_of_eq (Opens.isOpenEmbedding_obj_top G))).op).hom

/-- The ideal sheaf `𝓘 = (f₁, …, f_k) ⊆ 𝒜_G` of a local model. -/
def modelIdeal (G : Opens (Kn.{u} K n)) {k : ℕ} (f : Fin k → AnalyticFun K n G) :
    IdealSheaf (analyticSpaceOfOpen K n G).toLocallyRingedSpace.𝒪 :=
  IdealSheaf.ofGlobal _ fun i => toGlobal K n G (f i)

/-- The local analytic `K`-space `(S(𝓘), (𝒜_G/𝓘)|_{S(𝓘)})`, `𝓘 = (f₁, …, f_k)` [Hir64, Ch. 0, §1]:
the quotient of `(G, 𝒜_G)` by the ideal sheaf generated by the `f_i`. -/
@[implicit_reducible]
def localModel (G : Opens (Kn.{u} K n)) {k : ℕ} (f : Fin k → AnalyticFun K n G) :
    KLocallyRingedSpace.{u} K :=
  (analyticSpaceOfOpen K n G).quotient (modelIdeal K n G f)

end Model

end AnalyticSpace

/-! ### Analytic spaces -/

open AnalyticSpace

open KLocallyRingedSpace

/-- An analytic `K`-space [Hir64, Ch. 0, §1, p. 120]: a `K`-local-ringed space that is locally
`K`-isomorphic to an open subspace of a local analytic `K`-space, countable at infinity and
Hausdorff. -/
structure AnalyticSpace (K : Type) [RCLike K] extends KLocallyRingedSpace.{u} K where
  /-- Hironaka's (i): every point has an open neighbourhood `U` with `X|U` `K`-isomorphic to a
  local analytic `K`-space (an open subspace `W` of `(S(𝓘), (𝒜_G/𝓘)|_{S(𝓘)})`, see the module
  docstring). -/
  locallyModel : ∀ x : toLocallyRingedSpace, ∃ (U : Opens toLocallyRingedSpace) (_ : x ∈ U)
    (n k : ℕ) (G : Opens (Kn.{u} K n)) (f : Fin k → AnalyticFun K n G)
    (W : Opens (localModel K n G f)),
    Nonempty (KIso (toKLocallyRingedSpace.restrictOpen U) ((localModel K n G f).restrictOpen W))
  /-- Hironaka's (iii): the underlying space is Hausdorff. -/
  t2 : T2Space toLocallyRingedSpace
  /-- Hironaka's (ii): the underlying space is countable at infinity. -/
  sigmaCompact : SigmaCompactSpace toLocallyRingedSpace

namespace AnalyticSpace

variable {K : Type} [RCLike K]

instance : CoeSort (AnalyticSpace.{u} K) (Type u) :=
  ⟨fun X => (X.toLocallyRingedSpace.carrier : Type u)⟩

instance (X : AnalyticSpace.{u} K) : T2Space X := X.t2

instance (X : AnalyticSpace.{u} K) : SigmaCompactSpace X := X.sigmaCompact

/-- The morphisms of `An/K`: the `K`-morphisms of the underlying `K`-local-ringed spaces. A named
type, as `AlgebraicGeometry.Scheme.Hom`, so that `f.restrictSet V`, `f.IsIsoOver V`, … work by dot
notation on `f : X ⟶ Y`. -/
abbrev Hom (X Y : AnalyticSpace.{u} K) : Type u :=
  X.toKLocallyRingedSpace ⟶ Y.toKLocallyRingedSpace

/-- `An/K` is the full subcategory of `ℜ/K` on the analytic `K`-spaces [Hir64, Ch. 0, §1, p. 121]:
the morphisms are the `K`-morphisms of the underlying `K`-local-ringed spaces. -/
instance : Category (AnalyticSpace.{u} K) where
  Hom := Hom
  id X := 𝟙 X.toKLocallyRingedSpace
  comp f g := f ≫ g
  id_comp f := Category.id_comp f
  comp_id f := Category.comp_id f
  assoc f g h := Category.assoc f g h

/-- The underlying continuous map of a morphism of analytic `K`-spaces, the coercion `⇑f`: the
map `KLocallyRingedSpace.Hom.toFun` of the underlying `K`-morphism. -/
@[coe] def Hom.toFun {X Y : AnalyticSpace.{u} K} (f : X ⟶ Y) : X → Y :=
  KLocallyRingedSpace.Hom.toFun f

instance {X Y : AnalyticSpace.{u} K} : CoeFun (X ⟶ Y) (fun _ => X → Y) := ⟨Hom.toFun⟩

/-- The simple points of `X`: those whose local ring `𝒪_{X,x}` is a regular local ring.

Relation to the source.
* **Translation.** `X.regularLocus` is Hironaka's set of simple points [Hir64, Ch. 0, §1, p. 121]
  and Kollár's smooth locus $X^{ns}$; `X.singularLocus` is its complement,
  $\operatorname{Sing} X$. -/
def regularLocus (X : AnalyticSpace.{u} K) : Set X := {x | IsRegularLocalRing (X.presheaf.stalk x)}

/-- The multiple points: the complement of `regularLocus X`. -/
def singularLocus (X : AnalyticSpace.{u} K) : Set X := (regularLocus X)ᶜ

/-- `X` is non-singular: every point is simple [Hir64, Ch. 0, §1, p. 121]. -/
def IsNonsingular (X : AnalyticSpace.{u} K) : Prop := regularLocus X = Set.univ

/-- `X` is reduced when its structure sheaf has no nilpotent elements [Hir64, Introduction]: every
stalk is reduced. -/
def IsReduced (X : AnalyticSpace.{u} K) : Prop := ∀ x : X, _root_.IsReduced (X.presheaf.stalk x)

end AnalyticSpace
