/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.Differential
import Hironaka.Algebra.Local.QuotientParameters
import Hironaka.Algebra.Local.Regular
import Hironaka.Algebra.Local.RegularQuotientDim
import Hironaka.Algebra.Local.RegularSystem
public import Hironaka.AnalyticSpace.ModelIso
import Hironaka.AnalyticSpace.RegularParameters
import Hironaka.AnalyticSpace.RegularStalk
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The Jacobian criterion at a point of a local model

Hironaka proves that simple points are manifold points "by means of jacobian criterion and the
implicit function theorem" [Hir64, Ch. 0, §1, p. 121]. The Jacobian criterion, at a point `z` of
the local model `X = V(f₁, …, f_k) ⊆ G ⊆ Kⁿ` (`isRegularLocalRing_stalk_iff_jacobian`): the stalk
`𝒪_{X,z} ≅ 𝒜_{Kⁿ,z}/(f)_z` is regular iff some `n − d` of the `f_i`, `d = dim 𝒪_{X,z}`, have
linearly independent differentials at `z`. The proof is the commutative algebra of regular
systems of parameters (`Hironaka/Algebra/Local/`) read through the differential: if the quotient is
regular, `(f)_z` is generated by an initial segment `x₁, …, x_c` of a regular system of parameters
(`exists_span_eq_of_isRegularLocalRing_stalk`), whose classes in `𝔪/𝔪²` are independent and span
the image of `(f)_z`; the classes of the `f_i` span the same `c`-dimensional space, so `c` of
them are independent. Conversely `c` of the `f_i` with independent differentials are an initial
segment of a regular system of parameters, `𝒜/(f_σ)` is regular of dimension `n − c`
(`Hironaka/AnalyticSpace/RegularParameters.lean`), and the surjection `𝒜/(f_σ) → 𝒜/(f)` between
local rings of the same dimension `n − c`, from a domain, is an isomorphism
(`Ideal.eq_bot_of_ringKrullDim_quotient_eq`, `Hironaka/Algebra/Local/QuotientParameters.lean`). The
dimension clause is essential: `V(y, y − x²) ⊆ K²` has rank `1` and stalk `K[x]/(x²)`. Used by
`Hironaka/AnalyticSpace/RegPoints.lean` and `Hironaka/AnalyticSpace/DimensionLemmas.lean`.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite Manifold
open IsLocalRing Ideal
open scoped Manifold ContDiff

universe u

namespace AnalyticSpace

variable {K : Type} [RCLike K] {n : ℕ} {G : Opens (Kn.{u} K n)} {k : ℕ}
  {f : Fin k → AnalyticFun K n G}

/-- The stalk of the local model at `z`, read in `𝒜_{Kⁿ,z}`: `𝒪_{X,z} ≅ 𝒜_{Kⁿ,z}/(f)_z`
(`QuotientSpace.stalkEquiv` and Mathlib's `restrictStalkIso`). -/
def stalkEquivQuotientF (z : localModel K n G f) :
    (localModel K n G f).toLocallyRingedSpace.presheaf.stalk z ≃+*
      (affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1 ⧸
        Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j)) :=
  (QuotientSpace.stalkEquiv (analyticSpaceOfOpen K n G).toLocallyRingedSpace (modelIdeal K n G f)
    z).trans
    (Ideal.quotientEquiv
      (QuotientSpace.stalkIdeal (analyticSpaceOfOpen K n G).toLocallyRingedSpace
        (modelIdeal K n G f) z.1)
      (Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j)))
      ((affine K n).toLocallyRingedSpace.restrictStalkIso
        (Opens.isOpenEmbedding (X := (affine K n).toLocallyRingedSpace.toTopCat) G)
          z.1).commRingCatIsoToRingEquiv
      (ModelChartData.map_restrictStalkIso_stalkIdeal (f := f) z.1).symm)

/-- The germs of the `f j` at a point of the support lie in `𝔪`; hence `(f)_z ≤ 𝔪_z`. -/
theorem span_germ_le_maximalIdeal (z : localModel K n G f) :
    Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j)) ≤
      IsLocalRing.maximalIdeal ((affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1) :=
  Ideal.span_le.mpr (by
    rintro _ ⟨j, rfl⟩
    exact germ_mem_maximalIdeal_of_mem_cosupport G f z j)

/-- In the cotangent space `𝔪/𝔪²` of `𝒜_{Kⁿ,q}`, a germ acts through its value:
`a • [g] = a(q) • [g]`. -/
theorem smul_toCotangent_eq (q : Kn.{u} K n)
    (a : (structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q)
    (g : maximalIdeal ((structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q)) :
    a • (maximalIdeal _).toCotangent g =
      Manifold.eval K (Kn.{u} K n) (Kn.{u} K n) q a • (maximalIdeal _).toCotangent g := by
  have hm : a - algebraMap K _ (Manifold.eval K (Kn.{u} K n) (Kn.{u} K n) q a) ∈ maximalIdeal _ :=
    (mem_maximalIdeal_iff_eval (Kn.{u} K n) _).mpr
      (by rw [map_sub, algebraMap_stalk_eq, eval_const, sub_self])
  have h0 := Ideal.Cotangent.smul_eq_zero_of_mem hm ((maximalIdeal _).toCotangent g)
  rw [sub_smul, sub_eq_zero] at h0
  rw [h0, algebraMap_smul]

variable (G f)

/-- The algebraic core of `→` in the Jacobian criterion: if `𝒪_{X,z}` is regular, `(f)_z` is
generated by `c` germs with independent differentials, with `c + dim 𝒪_{X,z} = n` (regular systems
of parameters through the identification `𝒪_{X,z} ≅ 𝒜_{Kⁿ,z}/(f)_z`; independence of the
differentials from independence in `𝔪/𝔪²`). -/
theorem exists_span_eq_of_isRegularLocalRing_stalk (z : localModel K n G f)
    (hreg : IsRegularLocalRing ((localModel K n G f).toLocallyRingedSpace.presheaf.stalk z)) :
    ∃ (c : ℕ) (h : Fin c → (affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1),
      Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j)) =
        Ideal.span (Set.range h) ∧
      LinearIndependent K (fun j => dlin K n z.1.1 (h j)) ∧
      (c : WithBot ℕ∞) +
        ringKrullDim ((localModel K n G f).toLocallyRingedSpace.presheaf.stalk z) =
          ((n : ℕ) : WithBot ℕ∞) := by
  have := isRegularLocalRing_stalk_affine K n z.1.1
  have : IsRegularLocalRing ((affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1 ⧸
      Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j))) :=
    @IsRegularLocalRing.of_ringEquiv _ _ hreg _ _ (stalkEquivQuotientF z)
  obtain ⟨m, c, x, hcm, hm, hx, hI, hdimI⟩ :=
    exists_regularSystemOfParameters_of_quotient_and_ringKrullDim
      (Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j)))
  have hmn : m = n := by
    have := hm.trans (ringKrullDim_stalk_affine K n z.1.1)
    exact_mod_cast this
  subst hmn
  refine ⟨c, fun j => x (Fin.castLE hcm j), ?_, ?_, ?_⟩
  · rw [hI]
    congr 1
    ext s
    constructor
    · rintro ⟨j, hj, rfl⟩
      exact ⟨⟨j.val, hj⟩, by simp⟩
    · rintro ⟨j, rfl⟩
      exact ⟨Fin.castLE hcm j, j.2, rfl⟩
  · have hmem : ∀ j, x (Fin.castLE hcm j) ∈ maximalIdeal _ := fun j =>
      x_mem_maximalIdeal_of_span_eq x hx _
    exact (exists_span_eq_maximalIdeal_extending_iff K _ z.1.1 _ hmem).mp
      ⟨x, Fin.castLEEmb hcm, hx, hm, fun _ => rfl⟩
  · rw [ringKrullDim_eq_of_ringEquiv (stalkEquivQuotientF z), add_comm]
    exact hdimI.trans (ringKrullDim_stalk_affine K _ z.1.1)


/-- A germ of `𝔪_q` in the ideal generated by germs `g i ∈ 𝔪_q` has its cotangent class in the
`K`-span of theirs (the coefficients act through their values). -/
theorem toCotangent_mem_span_of_mem_span (q : Kn.{u} K n) {ι : Type*} [Finite ι]
    (g : ι → (structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q)
    (hg : ∀ i, g i ∈ maximalIdeal ((structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q))
    {s : (structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q}
    (hs : s ∈ maximalIdeal ((structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q))
    (h : s ∈ Ideal.span (Set.range g)) :
    (maximalIdeal _).toCotangent ⟨s, hs⟩ ∈
      Submodule.span K (Set.range fun i => (maximalIdeal _).toCotangent ⟨g i, hg i⟩) := by
  let _ := Fintype.ofFinite ι
  obtain ⟨a, ha⟩ := Ideal.mem_span_range_iff_exists_fun.mp h
  have hsum : (⟨s, hs⟩ : maximalIdeal _) = ∑ i, a i • (⟨g i, hg i⟩ : maximalIdeal _) := by
    ext
    simp only [Submodule.coe_sum, Submodule.coe_smul, smul_eq_mul]
    exact ha.symm
  rw [hsum, map_sum]
  refine Submodule.sum_mem _ fun i _ => ?_
  rw [map_smul, smul_toCotangent_eq]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- The cotangent class of a germ of `𝔪_q`, as `Manifold.cotangentClass`. -/
theorem cotangentClass_eq_toCotangent (q : Kn.{u} K n)
    {s : (structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q}
    (hs : s ∈ maximalIdeal ((structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q)) :
    cotangentClass (Kn.{u} K n) q s = (maximalIdeal _).toCotangent ⟨s, hs⟩ := by
  unfold cotangentClass
  congr 1
  exact Subtype.ext (by
    simp only
    rw [(mem_maximalIdeal_iff_eval (Kn.{u} K n) s).mp hs, map_zero, sub_zero])

/-- Independence of differentials of germs of `𝔪_q` is independence of their classes in `𝔪/𝔪²`
over `K`. -/
theorem linearIndependent_dlin_iff_toCotangent (q : Kn.{u} K n) {ι : Type*} [Finite ι]
    (h : ι → (structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q)
    (hm : ∀ i, h i ∈ maximalIdeal ((structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk q)) :
    LinearIndependent K (fun i => dlin K n q (h i)) ↔
      LinearIndependent K (fun i => (maximalIdeal _).toCotangent ⟨h i, hm i⟩) := by
  have := (linearIndependent_cotangentClass_iff_linearPart (Kn.{u} K n) ContinuousLinearEquiv.ulift
    (chartAt (Kn.{u} K n) q) (IsManifold.chart_mem_maximalAtlas q) (mem_chart_source _ q) h).symm
  simp only [cotangentClass_eq_toCotangent q (hm _)] at this
  exact this

/-- **The Jacobian criterion** (the criterion Hironaka invokes at [Hir64, Ch. 0, §1, p. 121]): at
a point `z` of the local model `X = V(f₁, …, f_k) ⊆ G ⊆ Kⁿ` the stalk `𝒪_{X,z}` is regular iff
some `n − d` of the `f_i`, `d = dim 𝒪_{X,z}`, have linearly independent differentials at `z`. -/
theorem isRegularLocalRing_stalk_iff_jacobian (z : localModel K n G f) :
    IsRegularLocalRing ((localModel K n G f).toLocallyRingedSpace.presheaf.stalk z) ↔
      ∃ (c : ℕ) (σ : Fin c ↪ Fin k),
        (c : WithBot ℕ∞) +
            ringKrullDim ((localModel K n G f).toLocallyRingedSpace.presheaf.stalk z) =
          ((n : ℕ) : WithBot ℕ∞) ∧
        LinearIndependent K (fun j => dlin K n z.1.1
          ((affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j)))) := by
  classical
  constructor
  · intro hreg
    obtain ⟨c, h, hgen, hind, hcount⟩ := exists_span_eq_of_isRegularLocalRing_stalk G f z hreg
    -- classes in `𝔪/𝔪²`
    have hmh : ∀ j, h j ∈ maximalIdeal _ := fun j =>
      (span_germ_le_maximalIdeal z) (hgen ▸ Ideal.subset_span ⟨j, rfl⟩)
    have hmf : ∀ i, (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f i) ∈
        maximalIdeal _ := germ_mem_maximalIdeal_of_mem_cosupport G f z
    let vh : Fin c →
        CotangentSpace ((structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk z.1.1) :=
      fun j => (maximalIdeal _).toCotangent ⟨h j, hmh j⟩
    let vf : Fin k →
        CotangentSpace ((structureSheaf K (Kn.{u} K n) (Kn.{u} K n)).presheaf.stalk z.1.1) :=
      fun i => (maximalIdeal _).toCotangent ⟨_, hmf i⟩
    have hvh : LinearIndependent K vh :=
      (linearIndependent_dlin_iff_toCotangent z.1.1 h hmh).mp hind
    -- the `K`-spans of the classes agree: both are the image of `(f)_z = (h)`
    have hspan : Submodule.span K (Set.range vf) = Submodule.span K (Set.range vh) := by
      apply le_antisymm
      · rw [Submodule.span_le]
        rintro _ ⟨i, rfl⟩
        exact toCotangent_mem_span_of_mem_span z.1.1 h hmh (hmf i)
          (hgen ▸ Ideal.subset_span ⟨i, rfl⟩)
      · rw [Submodule.span_le]
        rintro _ ⟨j, rfl⟩
        exact toCotangent_mem_span_of_mem_span z.1.1 _ hmf (hmh j)
          (hgen.symm ▸ Ideal.subset_span ⟨j, rfl⟩)
    -- `c` of the `vf` are independent
    have hfin : Module.finrank K (Submodule.span K (Set.range vf)) = c := by
      rw [hspan, finrank_span_eq_card hvh, Fintype.card_fin]
    obtain ⟨t, htsub, htspan, htli⟩ := exists_linearIndependent K (Set.range vf)
    have htfin : t.Finite := (Set.finite_range vf).subset htsub
    let _ := htfin.fintype
    have htcard : Fintype.card t = c := by
      rw [← Set.toFinset_card, ← finrank_span_set_eq_card htli, htspan, hfin]
    let e : Fin c ≃ t := (Fintype.equivFinOfCardEq htcard).symm
    have hidx : ∀ u : t, ∃ i, vf i = u.1 := fun u => htsub u.2
    choose idx hidx using hidx
    refine ⟨c, ⟨fun j => idx (e j), fun j j' hjj' => ?_⟩, hcount, ?_⟩
    · exact e.injective (Subtype.ext
        ((hidx (e j)).symm.trans ((congrArg vf hjj').trans (hidx (e j')))))
    change LinearIndependent K fun j => dlin K n z.1.1
      ((affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (idx (e j))))
    refine (linearIndependent_dlin_iff_toCotangent z.1.1 _ (fun j => hmf (idx (e j)))).mpr ?_
    have key : LinearIndependent K (Subtype.val ∘ e) := htli.comp e e.injective
    convert key using 1
    funext j
    exact hidx (e j)
  · rintro ⟨c, σ, hcount, hind⟩
    have := isRegularLocalRing_stalk_affine K n z.1.1
    have hm : ∀ j, (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j)) ∈
        maximalIdeal _ := fun j => germ_mem_maximalIdeal_of_mem_cosupport G f z (σ j)
    have hJ := isRegularLocalRing_quotient_span_range_and_ringKrullDim K n z.1.1
      (fun j => (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j))) hm hind
    have hregJ : IsRegularLocalRing ((affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1 ⧸
        Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j)))) := hJ.1
    have hdimJ : ringKrullDim ((affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1 ⧸
        Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j)))) +
        (c : WithBot ℕ∞) = ((n : ℕ) : WithBot ℕ∞) := hJ.2
    have hJI : Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j))) ≤
        Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j)) :=
      Ideal.span_le.mpr (by rintro _ ⟨j, rfl⟩; exact Ideal.subset_span ⟨σ j, rfl⟩)
    have hne : (Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j))).map
        (Ideal.Quotient.mk (Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j))))) ≠ ⊤ := by
      intro htop
      have h1 : (1 : _ ⧸ Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j)))) ∈
          (Ideal.span (Set.range fun j =>
            (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j))).map
          (Ideal.Quotient.mk _) := htop ▸ Submodule.mem_top
      obtain ⟨s, hsI, hs1⟩ :=
        (Ideal.mem_map_iff_of_surjective _ Ideal.Quotient.mk_surjective).mp h1
      have hs : s - 1 ∈ Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f (σ j))) :=
        Ideal.Quotient.eq.mp (hs1.trans (map_one _).symm)
      have h1I : (1 : (affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1) ∈
          Ideal.span (Set.range fun j =>
            (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j)) := by
        simpa using Ideal.sub_mem _ hsI (hJI hs)
      exact (IsLocalRing.maximalIdeal.isMaximal _).ne_top
        ((Ideal.eq_top_iff_one _).mpr (span_germ_le_maximalIdeal z h1I))
    have hle := IsLocalRing.le_maximalIdeal hne
    have hdimX : ringKrullDim ((localModel K n G f).toLocallyRingedSpace.presheaf.stalk z) =
        ((n - c : ℕ) : WithBot ℕ∞) :=
      WithBot.eq_natCast_sub_of_add_natCast_eq (by rwa [add_comm] at hcount)
    have hdimJ' := WithBot.eq_natCast_sub_of_add_natCast_eq hdimJ
    have hq := (ringKrullDim_eq_of_ringEquiv (DoubleQuot.quotQuotEquivQuotOfLE hJI)).trans
      (((ringKrullDim_eq_of_ringEquiv (stalkEquivQuotientF z)).symm.trans hdimX).trans hdimJ'.symm)
    have hbot := eq_bot_of_ringKrullDim_quotient_eq hle hq
    have e := (DoubleQuot.quotQuotEquivQuotOfLE hJI).symm.trans
      ((Ideal.quotEquivOfEq hbot).trans (RingEquiv.quotientBot _))
    have hregI := IsRegularLocalRing.of_ringEquiv e.symm
    exact @IsRegularLocalRing.of_ringEquiv _ _ hregI _ _ (stalkEquivQuotientF z).symm

end AnalyticSpace
