/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.Differential
import Hironaka.AnalyticSpace.ModelSupport
import Hironaka.AnalyticSpace.Propagation
import Hironaka.Manifold.AdaptedChart
import Hironaka.Manifold.Germ.StalkMap
import Hironaka.Manifold.Submanifold.Charts
import Hironaka.Manifold.Submanifold.Generators
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The adapted chart at a point of a local model

The analytic half of Hironaka's "by means of jacobian criterion and the implicit function theorem"
[Hir64, Ch. 0, §1, p. 121], set up: at a point `z` of the local model `X = V(f₁, …, f_k) ⊆ G ⊆ Kⁿ`
whose ideal `𝓘_z = (f)_z` is generated by `c` germs with independent differentials, those germs are
represented by sections `hs` on an open `U ⊆ G`, the analytic inverse function theorem
(`exists_chart_extending`, `Hironaka/Manifold/AdaptedChart.lean`) completes them to a chart `e`
of the maximal atlas at `z` with `hs i = (e ·)_{σ i}` on `e.source`, and the propagation lemma
`exists_forall_germ_mem_span` (`Hironaka/AnalyticSpace/Propagation.lean`) gives a neighbourhood `W`
of `z` on which `(f)_y = (hs)_y` for every `y`. The data is packaged as `ModelChartData`; its
consequences — on `W`, the support of `X` is the zero set `{(e ·)_σ = 0}` of the adapted
coordinates, and the `hs` have independent differentials at every point of `e.source` — feed the
`K`-isomorphism `X|V ≅ (G', 𝒜_{G'})` of `Hironaka/AnalyticSpace/ModelIso.lean`.

* `exists_chart_extending_affine` — the chart statement on `Kⁿ`;
* `ModelChartData`, `exists_modelChartData` — the data at `z` from the hypotheses;
* `ModelChartData.eval_eq_zero_iff`, `ModelChartData.hasIndependentDifferentialsAt`.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite Manifold
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace AnalyticSpace

variable (K : Type) [RCLike K] (n : ℕ)

/-- Analytic functions `z₁, …, z_c` on `Kⁿ` vanishing at `q` with independent differentials are
the coordinates `σ 1, …, σ c` of a chart `e` of the maximal atlas at `q` with `e q = 0`
(`exists_chart_extending` on `Kⁿ`). -/
theorem exists_chart_extending_affine {c : ℕ} (z : Fin c → Kn.{u} K n → K) (q : Kn.{u} K n)
    (hz : ∀ i, ContMDiffAt 𝓘(K, Kn.{u} K n) 𝓘(K) ω (z i) q) (hz0 : ∀ i, z i q = 0)
    (hind : HasIndependentDifferentialsAt (Kn.{u} K n) z q) :
    ∃ (e : OpenPartialHomeomorph (Kn.{u} K n) (Kn.{u} K n)) (σ : Fin c ↪ Fin n),
      e ∈ maximalAtlas 𝓘(K, Kn.{u} K n) ω (Kn.{u} K n) ∧ q ∈ e.source ∧ e q = 0 ∧
      ∀ y ∈ e.source, ∀ i, z i y = (e y).down (σ i) :=
  exists_chart_extending ContinuousLinearEquiv.ulift z q hz hz0 hind

variable {K n}

/-- The local data of Hironaka's implicit-function-theorem step [Hir64, Ch. 0, §1, p. 121] at a
point `z` of the
local model `V(f) ⊆ G`: sections `hs` on `U ⊆ G` generating the ideal `(f)` at every point of a
neighbourhood `W ∋ z`, and a chart `e` of the maximal atlas on `e.source ⊇ W` whose coordinates
`σ i` are the `hs i`. -/
structure ModelChartData (G : Opens (Kn.{u} K n)) {k : ℕ} (f : Fin k → AnalyticFun K n G)
    (z : localModel K n G f) (c : ℕ) where
  /-- The domain of the sections. -/
  U : Opens (Kn.{u} K n)
  hU : U ≤ G
  /-- The sections representing the generators. -/
  hs : Fin c → AnalyticFun K n U
  /-- The adapted chart. -/
  e : OpenPartialHomeomorph (Kn.{u} K n) (Kn.{u} K n)
  he : e ∈ maximalAtlas 𝓘(K, Kn.{u} K n) ω (Kn.{u} K n)
  /-- The adapted coordinates. -/
  σ : Fin c ↪ Fin n
  /-- The good neighbourhood of `z`. -/
  W : Opens (Kn.{u} K n)
  hzW : z.1.1 ∈ W
  hWU : W ≤ U
  hWe : (W : Set (Kn.{u} K n)) ⊆ e.source
  hcoord : ∀ y ∈ e.source, ∀ i, extendSection K (Kn.{u} K n) (hs i) y = (e y).down (σ i)
  hideal : ∀ y (hy : y ∈ W),
    Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ G y (hU (hWU hy)) (f j)) =
      Ideal.span (Set.range fun i =>
        (affine K n).toLocallyRingedSpace.presheaf.germ U y (hWU hy) (hs i))

variable (G : Opens (Kn.{u} K n)) {k : ℕ} (f : Fin k → AnalyticFun K n G)

/-- A point of the support of the local model has all `f j` vanishing there, so the germs of the
`f j` lie in the maximal ideal. -/
theorem germ_mem_maximalIdeal_of_mem_cosupport (z : localModel K n G f) (j : Fin k) :
    (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f j) ∈
      IsLocalRing.maximalIdeal ((affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1) := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_germ_affine_iff K n G z.1 (f j),
    not_not]
  exact (mem_cosupport_modelIdeal_iff K n G f z.1).mp z.2 j

/-- From the hypotheses of the Jacobian criterion's geometric conclusion — `𝓘_z = (h)` in
`𝒜_{Kⁿ,z}` with `h` of independent differentials — the chart data at `z`. -/
theorem exists_modelChartData (z : localModel K n G f) {c : ℕ}
    (h : Fin c → (affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1)
    (hgen : Ideal.span (Set.range fun i =>
        (affine K n).toLocallyRingedSpace.presheaf.germ G z.1.1 z.1.2 (f i)) =
      Ideal.span (Set.range h))
    (hind : LinearIndependent K (fun i => dlin K n z.1.1 (h i))) :
    Nonempty (ModelChartData G f z c) := by
  classical
  have hqG : z.1.1 ∈ G := z.1.2
  -- represent the germs by sections on a common open `U ≤ G`
  choose U' hqU' s' hs' using fun i =>
    (affine K n).toLocallyRingedSpace.presheaf.exists_germ_eq (h i)
  let U : Opens (Kn.{u} K n) := G ⊓ ⨅ i, U' i
  have hqU : z.1.1 ∈ U := Opens.mem_inf.mpr ⟨hqG, mem_iInf_opens.mpr hqU'⟩
  have hUG : U ≤ G := inf_le_left
  have hUU' : ∀ i, U ≤ U' i := fun i => inf_le_right.trans (iInf_le _ i)
  let hs : Fin c → AnalyticFun K n U := fun i =>
    (affine K n).toLocallyRingedSpace.presheaf.map (homOfLE (hUU' i)).op (s' i)
  have hhs : ∀ i, (affine K n).toLocallyRingedSpace.presheaf.germ U z.1.1 hqU (hs i) = h i :=
    fun i => (TopCat.Presheaf.germ_res_apply _ (homOfLE (hUU' i)) z.1.1 hqU (s' i)).trans (hs' i)
  let fU : Fin k → AnalyticFun K n U := fun j =>
    (affine K n).toLocallyRingedSpace.presheaf.map (homOfLE hUG).op (f j)
  have hfU : ∀ (j : Fin k) y (hy : y ∈ U),
      (affine K n).toLocallyRingedSpace.presheaf.germ U y hy (fU j) =
        (affine K n).toLocallyRingedSpace.presheaf.germ G y (hUG hy) (f j) :=
    fun j y hy => TopCat.Presheaf.germ_res_apply _ _ y hy (f j)
  -- the `h i` vanish at `z`
  have hm : ∀ i, h i ∈
      IsLocalRing.maximalIdeal ((affine K n).toLocallyRingedSpace.presheaf.stalk z.1.1) := by
    intro i
    have h1 : h i ∈ Ideal.span (Set.range h) := Ideal.subset_span ⟨i, rfl⟩
    rw [← hgen] at h1
    refine (Ideal.span_le.mpr ?_) h1
    rintro _ ⟨j, rfl⟩
    exact germ_mem_maximalIdeal_of_mem_cosupport G f z j
  have hz0 : ∀ i, extendSection K (Kn.{u} K n) (hs i) z.1.1 = 0 := fun i => by
    rw [extendSection_of_mem K (Kn.{u} K n) (hs i) hqU]
    have := (mem_maximalIdeal_iff_eval (Kn.{u} K n) (h i)).mp (hm i)
    rw [← hhs i] at this
    exact (contMDiffSheafCommRing.eval_germ 𝓘(K, Kn.{u} K n) 𝓘(K) ω (Kn.{u} K n) K U z.1.1 hqU
      (hs i)).symm.trans this
  have hz : ∀ i, ContMDiffAt 𝓘(K, Kn.{u} K n) 𝓘(K) ω (extendSection K (Kn.{u} K n) (hs i)) z.1.1 :=
    fun i => (contMDiffOn_extendSection (hs i)).contMDiffAt (U.isOpen.mem_nhds hqU)
  have hind' : HasIndependentDifferentialsAt (Kn.{u} K n)
      (fun i => extendSection K (Kn.{u} K n) (hs i)) z.1.1 := by
    rw [← linearIndependent_dlin_germ_iff_hasIndependentDifferentialsAt K n U hs z.1.1 hqU]
    simpa only [hhs] using hind
  obtain ⟨e, σ, he, hqe, -, hcoord⟩ := exists_chart_extending_affine K n _ z.1.1 hz hz0 hind'
  -- propagation of `(f) = (hs)` to a neighbourhood
  have hspan : Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ U z.1.1 hqU (fU j)) =
      Ideal.span (Set.range fun i =>
        (affine K n).toLocallyRingedSpace.presheaf.germ U z.1.1 hqU (hs i)) := by
    simp only [hfU, hhs]
    exact hgen
  have hf_mem : ∀ j, ∃ (W : Opens (Kn.{u} K n)) (_ : z.1.1 ∈ W) (hWU : W ≤ U), ∀ y (hy : y ∈ W),
      (affine K n).toLocallyRingedSpace.presheaf.germ U y (hWU hy) (fU j) ∈
        Ideal.span (Set.range fun i =>
          (affine K n).toLocallyRingedSpace.presheaf.germ U y (hWU hy) (hs i)) :=
    fun j => exists_forall_germ_mem_span (affine K n).toLocallyRingedSpace.presheaf hqU (fU j) hs
      (hspan ▸ Ideal.subset_span ⟨j, rfl⟩)
  have hs_mem : ∀ i, ∃ (W : Opens (Kn.{u} K n)) (_ : z.1.1 ∈ W) (hWU : W ≤ U), ∀ y (hy : y ∈ W),
      (affine K n).toLocallyRingedSpace.presheaf.germ U y (hWU hy) (hs i) ∈
        Ideal.span (Set.range fun j =>
          (affine K n).toLocallyRingedSpace.presheaf.germ U y (hWU hy) (fU j)) :=
    fun i => exists_forall_germ_mem_span (affine K n).toLocallyRingedSpace.presheaf hqU (hs i) fU
      (hspan ▸ Ideal.subset_span ⟨i, rfl⟩)
  choose W₁ hqW₁ hW₁U hW₁ using hf_mem
  choose W₂ hqW₂ hW₂U hW₂ using hs_mem
  let eS : Opens (Kn.{u} K n) := ⟨e.source, e.open_source⟩
  let W : Opens (Kn.{u} K n) := U ⊓ (⨅ j, W₁ j) ⊓ (⨅ i, W₂ i) ⊓ eS
  have hqW : z.1.1 ∈ W := Opens.mem_inf.mpr ⟨Opens.mem_inf.mpr ⟨Opens.mem_inf.mpr
    ⟨hqU, mem_iInf_opens.mpr hqW₁⟩, mem_iInf_opens.mpr hqW₂⟩, hqe⟩
  have hWU : W ≤ U := inf_le_left.trans (inf_le_left.trans inf_le_left)
  have hWW₁ : ∀ j, W ≤ W₁ j := fun j =>
    inf_le_left.trans (inf_le_left.trans (inf_le_right.trans (iInf_le _ j)))
  have hWW₂ : ∀ i, W ≤ W₂ i := fun i => inf_le_left.trans (inf_le_right.trans (iInf_le _ i))
  have hWe : (W : Set (Kn.{u} K n)) ⊆ e.source := fun y hy => (inf_le_right : W ≤ eS) hy
  refine ⟨⟨U, hUG, hs, e, he, σ, W, hqW, hWU, hWe, hcoord, fun y hy => ?_⟩⟩
  have hyU : y ∈ U := hWU hy
  have : Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ G y (hUG hyU) (f j)) =
      Ideal.span (Set.range fun j =>
        (affine K n).toLocallyRingedSpace.presheaf.germ U y hyU (fU j)) := by
    simp only [hfU]
  rw [this]
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨j, rfl⟩
    exact hW₁ j y (hWW₁ j hy)
  · rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact hW₂ i y (hWW₂ i hy)



namespace ModelChartData

variable {G f} {z : localModel K n G f} {c : ℕ} (D : ModelChartData G f z c)

/-- On the good neighbourhood `W`, a point lies in the support of the local model (all `f j` vanish)
iff the adapted coordinates `(e ·)_{σ i}` vanish: the support is the coordinate subspace of the
chart. -/
theorem eval_eq_zero_iff {y : Kn.{u} K n} (hy : y ∈ D.W) :
    (∀ j, (f j).eval ⟨y, D.hU (D.hWU hy)⟩ = 0) ↔ ∀ i, (D.e y).down (D.σ i) = 0 := by
  have hyU : y ∈ D.U := D.hWU hy
  have hyG : y ∈ G := D.hU hyU
  have h1 : ∀ j, (f j).eval ⟨y, hyG⟩ = 0 ↔
      (affine K n).toLocallyRingedSpace.presheaf.germ G y hyG (f j) ∈
        IsLocalRing.maximalIdeal ((affine K n).toLocallyRingedSpace.presheaf.stalk y) := fun j =>
    ((not_congr (isUnit_germ_affine_iff K n G ⟨y, hyG⟩ (f j))).trans not_not).symm.trans
      (by rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff])
  have h2 : ∀ i, (D.hs i).eval ⟨y, hyU⟩ = 0 ↔
      (affine K n).toLocallyRingedSpace.presheaf.germ D.U y hyU (D.hs i) ∈
        IsLocalRing.maximalIdeal ((affine K n).toLocallyRingedSpace.presheaf.stalk y) := fun i =>
    ((not_congr (isUnit_germ_affine_iff K n D.U ⟨y, hyU⟩ (D.hs i))).trans not_not).symm.trans
      (by rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff])
  have key : (∀ j, (f j).eval ⟨y, hyG⟩ = 0) ↔ ∀ i, (D.hs i).eval ⟨y, hyU⟩ = 0 := by
    simp only [h1, h2]
    constructor
    · intro hf i
      have : (affine K n).toLocallyRingedSpace.presheaf.germ D.U y hyU (D.hs i) ∈
          Ideal.span (Set.range fun i =>
            (affine K n).toLocallyRingedSpace.presheaf.germ D.U y hyU (D.hs i)) :=
        Ideal.subset_span ⟨i, rfl⟩
      rw [← D.hideal y hy] at this
      exact (Ideal.span_le.mpr (by rintro _ ⟨j, rfl⟩; exact hf j)) this
    · intro hh j
      have : (affine K n).toLocallyRingedSpace.presheaf.germ G y hyG (f j) ∈
          Ideal.span (Set.range fun j =>
            (affine K n).toLocallyRingedSpace.presheaf.germ G y (D.hU (D.hWU hy)) (f j)) :=
        Ideal.subset_span ⟨j, rfl⟩
      rw [D.hideal y hy] at this
      exact (Ideal.span_le.mpr (by rintro _ ⟨i, rfl⟩; exact hh i)) this
  rw [key]
  refine forall_congr' fun i => ?_
  rw [← D.hcoord y (D.hWe hy) i, extendSection_of_mem K (Kn.{u} K n) (D.hs i) hyU]
  exact Iff.rfl

/-- The adapted coordinates have independent differentials at every point of the chart domain
(`Hironaka/Manifold/Submanifold/Generators.lean`), hence so do the sections `hs`, which agree
with them on `e.source`. -/
theorem hasIndependentDifferentialsAt {y : Kn.{u} K n} (hy : y ∈ D.e.source) :
    HasIndependentDifferentialsAt (Kn.{u} K n)
      (fun i => extendSection K (Kn.{u} K n) (D.hs i)) y := by
  have h := (isAdaptedChart_zeroSet' (ψ := ContinuousLinearEquiv.ulift) D.he D.σ
    ).hasIndependentDifferentialsAt hy
  unfold HasIndependentDifferentialsAt at h ⊢
  have : (fun i => mderivFun (Kn.{u} K n) (extendSection K (Kn.{u} K n) (D.hs i)) y) =
      fun i => mderivFun (Kn.{u} K n)
        (fun x => (ContinuousLinearEquiv.ulift : Kn.{u} K n ≃L[K] (Fin n → K)) (D.e x) (D.σ i))
        y := by
    funext i
    unfold mderivFun
    apply Filter.EventuallyEq.mfderiv_eq
    filter_upwards [D.e.open_source.mem_nhds hy] with x hx
    exact D.hcoord x hx i
  rw [this]
  exact h

end ModelChartData

end AnalyticSpace
