/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.VanishingIdeal
public import Hironaka.AnalyticSpace.Model
public import Hironaka.AnalyticSpace.QuotientLift
public import Mathlib.Analysis.Complex.Basic
import Hironaka.Analytic.Rueckert.Nullstellensatz
import Hironaka.AnalyticSpace.ModelSupport
import Hironaka.AnalyticSpace.ModelTransport
import Hironaka.AnalyticSpace.OpenSubspaceLemmas
import Hironaka.AnalyticSpace.Quotient
import Hironaka.AnalyticSpace.RegDensityLemmas
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# Rückert's Nullstellensatz for the stalks of an analytic `ℂ`-space

The ideal of the germs vanishing on the support of an ideal sheaf `J` of finite type is the radical
of `J`, stalk by stalk: `𝓘_{S(J)}(y) = √(J_y)` (`vanishingStalkIdeal_cosupport_eq_radical`) — the
Nullstellensatz for analytic sets [GR84, Ch. 4, §1]. It is Rückert's Nullstellensatz for
`𝒪_n = Conv ℂ n` (`vanishingIdeal_eq_radical`,
`Hironaka/Analytic/Rueckert/Nullstellensatz.lean`), carried to the stalks of an analytic
space in three steps:

* `vanishingStalkIdeal_eq_radical_span_affine`: at a point `q ∈ ℂⁿ`, for a set `D` which near `q`
  is the common zero set of finitely many analytic functions `h_i`, the germs vanishing on `D` are
  the radical of `(h_1, …, h_k)_q` — the Taylor isomorphism `taylorAffine q : 𝒜_{ℂⁿ,q} ≃ 𝒪_n`
  (`Hironaka/AnalyticSpace/Dimension.lean`) turns the zero set into the zero-set germ `V(S)` of the
  Taylor series `S` and the vanishing condition into `VanishesOn S`, and Rückert's theorem
  finishes.
* `vanishingStalkIdeal_cosupport_eq_radical_analyticSpaceOfOpen`: the open subspace `(G, 𝒜_G)`,
  along the open immersion into `(ℂⁿ, 𝒜)` (stalk isomorphisms); the support of `J` is the common
  zero set of local generators (a local ring: a span is proper iff no generator is a unit, and a
  germ is a unit iff its value is nonzero).
* `vanishingStalkIdeal_cosupport_eq_radical_quotient`: a quotient `(S(𝒥), 𝒪_Y/𝒥)`, along its
  closed immersion (surjective stalk maps), given the statement on `Y` for the lifted ideal sheaf
  (`liftIdeal`, `Hironaka/AnalyticSpace/QuotientLift.lean`).

The general statement then follows through a chart `X|U ≅ (S(𝓘), 𝒜_G/𝓘)`
(`exists_kIso_localModel`) with the transport of ideal sheaves `restrictIdeal`
(`Hironaka/AnalyticSpace/QuotientMap.lean`) and `comap`, points being parametrized from the model
side. `isUnit_map_iff_of_bijective` and `germ_mem_maximalIdeal_affine_iff` are the two small
tools. Used by `Hironaka/Manifold/BlowUp/Transform/StrictSubspaceClosure.lean`.
-/

public section

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite Manifold
open Analytic Filter Topology
open MvPowerSeries

universe u

namespace AnalyticSpace

variable {n : ℕ}

/-- A germ of `𝒜_{Kⁿ}` lies in the maximal ideal iff the function vanishes at the point. -/
theorem germ_mem_maximalIdeal_affine_iff {K : Type} [RCLike K] (U : Opens (Kn.{u} K n)) (x : U)
    (g : AnalyticFun K n U) :
    (affine K n).toLocallyRingedSpace.presheaf.germ U x.1 x.2 g ∈
        IsLocalRing.maximalIdeal ((affine K n).toLocallyRingedSpace.presheaf.stalk x.1) ↔
      g.eval x = 0 := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_germ_affine_iff, not_not]

/-- Rückert's Nullstellensatz at a point `q` of `ℂⁿ` for the germs of `𝒜_{ℂⁿ}`: if near `q` the set
`D` is the common zero set of analytic functions `h_i` on `U ∋ q`, the germs at `q` vanishing on `D`
are exactly the radical of the ideal generated by the germs of the `h_i`
(`vanishingIdeal_eq_radical` of `Hironaka/Analytic/Rueckert/Nullstellensatz.lean`,
transported to the stalk at `q` by the Taylor isomorphism `taylorAffine`). -/
theorem vanishingStalkIdeal_eq_radical_span_affine (q : Kn.{u} ℂ n) {U : Opens (Kn.{u} ℂ n)}
    (hq : q ∈ U) {k : ℕ} (h : Fin k → AnalyticFun ℂ n U) {D : Set (Kn.{u} ℂ n)}
    (hD : ∀ b (hb : b ∈ U), b ∈ D ↔ ∀ i, (h i).eval ⟨b, hb⟩ = 0) :
    vanishingStalkIdeal (affine ℂ n).toLocallyRingedSpace D q =
      (Ideal.span (Set.range fun i =>
        (affine ℂ n).toLocallyRingedSpace.presheaf.germ U q hq (h i))).radical := by
  classical
  set θ : (affine ℂ n).toLocallyRingedSpace.presheaf.stalk q →+* Analytic.Conv ℂ n :=
    (taylorAffine.{u} ℂ n q).toRingHom with hθ
  have hθb : Function.Bijective θ := (taylorAffine.{u} ℂ n q).bijective
  set gm : Fin k → (affine ℂ n).toLocallyRingedSpace.presheaf.stalk q := fun i =>
    (affine ℂ n).toLocallyRingedSpace.presheaf.germ U q hq (h i) with hgm
  set S : Finset (Analytic.Conv ℂ n) := Finset.univ.image fun i => θ (gm i) with hS
  have hSJ : Ideal.span (S : Set (Analytic.Conv ℂ n)) = Ideal.map θ (Ideal.span (Set.range gm)) :=
      by
    rw [Ideal.map_span, hS, Finset.coe_image, Finset.coe_univ, Set.image_univ, ← Set.range_comp]
    rfl
  -- the points `q + x` near `q`
  let pt : (Fin n → ℂ) → Kn.{u} ℂ n := fun x => ULift.up (q.down + x)
  have hpt : Continuous pt :=
    (ContinuousLinearEquiv.ulift : Kn.{u} ℂ n ≃L[ℂ] (Fin n → ℂ)).symm.continuous.comp
      (continuous_const.add continuous_id)
  have hpt0 : Tendsto pt (𝓝 0) (𝓝 q) := hpt.tendsto' 0 q (ULift.ext _ _ (add_zero _))
  -- near `0`: `q + x ∈ U`, the zero set of `S` is `D - q`, and the series of the `h_i` evaluate to
  -- the functions
  have hev : ∀ᶠ x in 𝓝 (0 : Fin n → ℂ), ∃ hx : pt x ∈ U, (x ∈ zeroSet S ↔ pt x ∈ D) := by
    have h1 : ∀ᶠ x in 𝓝 (0 : Fin n → ℂ), ∀ i,
        evalSeries (θ (gm i) : MvPowerSeries (Fin n) ℂ) x =
          extendSection ℂ (Kn.{u} ℂ n) (h i) (ULift.up (q.down + x)) :=
      eventually_all.mpr fun i => eventually_evalSeries_convAt_germ q hq (h i)
    filter_upwards [h1, hpt0.eventually (U.isOpen.mem_nhds hq)] with x hx hxU
    have hval : ∀ i, evalSeries (θ (gm i) : MvPowerSeries (Fin n) ℂ) x =
        (h i).eval ⟨pt x, hxU⟩ := by
      intro i
      rw [hx i, extendSection_of_mem (M := Kn.{u} ℂ n) ℂ (Kn.{u} ℂ n) (h i) hxU]
      rfl
    refine ⟨hxU, ?_⟩
    rw [hD (pt x) hxU, mem_zeroSet_iff]
    constructor
    · intro hz i
      rw [← hval i]
      exact hz _ (Finset.mem_image_of_mem _ (Finset.mem_univ i))
    · rintro hm g hg
      obtain ⟨i, -, rfl⟩ := Finset.mem_image.mp hg
      rw [hval i]
      exact hm i
  -- the vanishing ideal is the preimage of `𝓘(V(S))` under `θ`
  have hkey : ∀ s, s ∈ vanishingStalkIdeal (affine ℂ n).toLocallyRingedSpace D q ↔
      VanishesOn S (θ s) := by
    intro s
    obtain ⟨V, hqV, g, rfl⟩ := (affine ℂ n).toLocallyRingedSpace.presheaf.exists_germ_eq s
    have h2 : ∀ᶠ x in 𝓝 (0 : Fin n → ℂ), ∃ hx : pt x ∈ V,
        evalSeries (θ ((affine ℂ n).toLocallyRingedSpace.presheaf.germ V q hqV g) :
          MvPowerSeries (Fin n) ℂ) x = AnalyticFun.eval g ⟨pt x, hx⟩ := by
      have h2' : ∀ᶠ x in 𝓝 (0 : Fin n → ℂ),
          evalSeries (θ ((affine ℂ n).toLocallyRingedSpace.presheaf.germ V q hqV g) :
            MvPowerSeries (Fin n) ℂ) x = extendSection ℂ (Kn.{u} ℂ n) g (ULift.up (q.down + x)) :=
        eventually_evalSeries_convAt_germ q hqV g
      filter_upwards [h2', hpt0.eventually (V.isOpen.mem_nhds hqV)] with x hx hxV
      refine ⟨hxV, ?_⟩
      rw [hx, extendSection_of_mem (M := Kn.{u} ℂ n) ℂ (Kn.{u} ℂ n) g hxV]
      rfl
    constructor
    · rintro ⟨V', hqV', g', hg', hvan⟩
      obtain ⟨W, hqW, iV', iV, hW⟩ :=
        (affine ℂ n).toLocallyRingedSpace.presheaf.germ_eq q hqV' hqV _ _ hg'
      change ∀ᶠ x in 𝓝 (0 : Fin n → ℂ), x ∈ zeroSet S →
        evalSeries (θ ((affine ℂ n).toLocallyRingedSpace.presheaf.germ V q hqV g) :
          MvPowerSeries (Fin n) ℂ) x = 0
      filter_upwards [hev, h2, hpt0.eventually (W.isOpen.mem_nhds hqW)] with x hx1 hx2 hxW hz
      obtain ⟨hxU, hzD⟩ := hx1
      obtain ⟨hxV, hval⟩ := hx2
      rw [hval]
      have hmem := hvan (pt x) (iV'.le hxW) (hzD.mp hz)
      have heq : (affine ℂ n).toLocallyRingedSpace.presheaf.germ V (pt x) hxV g =
          (affine ℂ n).toLocallyRingedSpace.presheaf.germ V' (pt x) (iV'.le hxW) g' := by
        rw [← (affine ℂ n).toLocallyRingedSpace.presheaf.germ_res_apply iV (pt x) hxW g, ← hW,
          (affine ℂ n).toLocallyRingedSpace.presheaf.germ_res_apply iV' (pt x) hxW g']
      rw [← heq, germ_mem_maximalIdeal_affine_iff V ⟨pt x, hxV⟩ g] at hmem
      exact hmem
    · intro hvan
      have hvan' : ∀ᶠ x in 𝓝 (0 : Fin n → ℂ), x ∈ zeroSet S →
          evalSeries (θ ((affine ℂ n).toLocallyRingedSpace.presheaf.germ V q hqV g) :
            MvPowerSeries (Fin n) ℂ) x = 0 := hvan
      obtain ⟨N, hN, hNo, h0N⟩ := eventually_nhds_iff.mp (hvan'.and (hev.and h2))
      have hsub : Continuous fun b : Kn.{u} ℂ n => b.down - q.down :=
        (ContinuousLinearEquiv.ulift : Kn.{u} ℂ n ≃L[ℂ] (Fin n → ℂ)).continuous.sub
          continuous_const
      let V₀ : Opens (Kn.{u} ℂ n) := V ⊓ ⟨(fun b : Kn.{u} ℂ n => b.down - q.down) ⁻¹' N,
        hNo.preimage hsub⟩
      have hqV₀ : q ∈ V₀ := ⟨hqV, by change q.down - q.down ∈ N; rw [sub_self]; exact h0N⟩
      refine ⟨V₀, hqV₀, (affine ℂ n).toLocallyRingedSpace.presheaf.map (homOfLE inf_le_left).op g,
        (affine ℂ n).toLocallyRingedSpace.presheaf.germ_res_apply (homOfLE inf_le_left) q hqV₀ g,
        fun b hb hbD => ?_⟩
      obtain ⟨x, hxN, rfl⟩ : ∃ x ∈ N, pt x = b :=
        ⟨b.down - q.down, hb.2, ULift.ext _ _ (add_sub_cancel _ _)⟩
      obtain ⟨hz0, ⟨hxU, hzD⟩, ⟨hxV, hval⟩⟩ := hN x hxN
      rw [(affine ℂ n).toLocallyRingedSpace.presheaf.germ_res_apply (homOfLE inf_le_left) (pt x)
        hb g, germ_mem_maximalIdeal_affine_iff V ⟨pt x, hb.1⟩ g]
      have : AnalyticFun.eval g ⟨pt x, hxV⟩ = 0 := by rw [← hval]; exact hz0 (hzD.mpr hbD)
      exact this
  -- assemble: `𝓘_D(q) = θ⁻¹ 𝓘(V(S)) = θ⁻¹ √(S) = √J`
  have hI : vanishingStalkIdeal (affine ℂ n).toLocallyRingedSpace D q =
      Ideal.comap θ (vanishingIdeal (Ideal.span (S : Set (Analytic.Conv ℂ n)))) := by
    ext s
    rw [Ideal.mem_comap, mem_vanishingIdeal_iff rfl]
    exact hkey s
  have hker : RingHom.ker θ ≤ Ideal.span (Set.range gm) := by
    rw [(RingHom.injective_iff_ker_eq_bot θ).mp hθb.1]
    exact bot_le
  rw [hI, vanishingIdeal_eq_radical, hSJ, ← Ideal.map_radical_of_surjective hθb.2 hker,
    Ideal.comap_map_of_bijective θ hθb]

/-- A bijective ring homomorphism preserves and detects units. -/
theorem isUnit_map_iff_of_bijective {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
    (hf : Function.Bijective f) (x : R) : IsUnit (f x) ↔ IsUnit x := by
  refine ⟨fun h => ?_, fun h => h.map f⟩
  obtain ⟨u, hu⟩ := h
  obtain ⟨y, hy⟩ := hf.2 (u⁻¹ : Sˣ)
  refine isUnit_iff_exists_inv.mpr ⟨y, hf.1 ?_⟩
  rw [map_mul, map_one, hy, ← hu]
  exact u.mul_inv

/-- Rückert's Nullstellensatz on `(G, 𝒜_G)`: the germs at `q` vanishing on the support of an ideal
sheaf `J` of finite type are the radical of `J_q` (transport of the affine form along the open
immersion `(G, 𝒜_G) ⟶ (ℂⁿ, 𝒜)`, whose stalk maps are isomorphisms). -/
theorem vanishingStalkIdeal_cosupport_eq_radical_analyticSpaceOfOpen (G : Opens (Kn.{u} ℂ n))
    (J : IdealSheaf (analyticSpaceOfOpen ℂ n G).toLocallyRingedSpace.𝒪)
    (q : analyticSpaceOfOpen ℂ n G) :
    vanishingStalkIdeal (analyticSpaceOfOpen ℂ n G).toLocallyRingedSpace J.support q =
      (J.stalkIdeal q).radical := by
  obtain ⟨U', hqU', k, f, -, hgen⟩ := J.exists_generators q
  have hoe := Opens.isOpenEmbedding (X := (affine ℂ n).toLocallyRingedSpace.toTopCat) G
  have hbij : ∀ b, Function.Bijective
      (((affine ℂ n).toLocallyRingedSpace.ofRestrict hoe).stalkMap b).hom := fun b =>
    haveI := LocallyRingedSpace.ofRestrict_stalkMap_isIso (affine ℂ n).toLocallyRingedSpace hoe b
    ConcreteCategory.bijective_of_isIso _
  have hind : IsInducing ((affine ℂ n).toLocallyRingedSpace.ofRestrict hoe).base := hoe.isInducing
  have hmemU : ∀ b : analyticSpaceOfOpen ℂ n G, b ∈ U' → b.1 ∈ hoe.functor.obj U' :=
    fun b hb => ⟨b, hb, rfl⟩
  have hqU : q.1 ∈ hoe.functor.obj U' := hmemU q hqU'
  -- the germs of the generators, read in `𝒜_{ℂⁿ}`
  have hgerm : ∀ (b : analyticSpaceOfOpen ℂ n G) (hb : b ∈ U')
      (s : (analyticSpaceOfOpen ℂ n G).toLocallyRingedSpace.presheaf.obj (op U')),
      ((affine ℂ n).toLocallyRingedSpace.ofRestrict hoe).stalkMap b
        ((affine ℂ n).toLocallyRingedSpace.presheaf.germ (hoe.functor.obj U') b.1 (hmemU b hb) s) =
        (analyticSpaceOfOpen ℂ n G).toLocallyRingedSpace.presheaf.germ U' b hb s := fun b hb s =>
    (congrArg (fun ψ : (affine ℂ n).toLocallyRingedSpace.presheaf.stalk b.1 ⟶
        ((affine ℂ n).toLocallyRingedSpace.restrict hoe).presheaf.stalk b =>
      ψ ((affine ℂ n).toLocallyRingedSpace.presheaf.germ (hoe.functor.obj U') b.1 (hmemU b hb) s))
      (LocallyRingedSpace.restrictStalkIso_inv_eq_ofRestrict (affine ℂ n).toLocallyRingedSpace hoe
        b)).symm.trans
      (LocallyRingedSpace.restrictStalkIso_inv_eq_germ_apply (affine ℂ n).toLocallyRingedSpace hoe
        U' b hb s)
  -- near `q`, the support of `J` is the common zero set of the generators
  have hD : ∀ b (hb : b ∈ hoe.functor.obj U'), b ∈ Subtype.val '' J.support ↔
      ∀ i, AnalyticFun.eval (f i) ⟨b, hb⟩ = 0 := by
    intro b hb
    obtain ⟨b', hb', rfl⟩ : ∃ b' : analyticSpaceOfOpen ℂ n G, b' ∈ U' ∧ b'.1 = b := hb
    have : IsLocalRing ((analyticSpaceOfOpen ℂ n G).toLocallyRingedSpace.𝒪.presheaf.stalk b') :=
      inferInstanceAs
        (IsLocalRing ((analyticSpaceOfOpen ℂ n G).toLocallyRingedSpace.presheaf.stalk b'))
    have hunit : ∀ i, IsUnit ((analyticSpaceOfOpen ℂ n G).toLocallyRingedSpace.presheaf.germ U'
        b' hb' (f i)) ↔ AnalyticFun.eval (f i) ⟨b'.1, hmemU b' hb'⟩ ≠ 0 := by
      intro i
      rw [← hgerm b' hb' (f i)]
      exact (isUnit_map_iff_of_bijective _ (hbij b') _).trans
        (isUnit_germ_affine_iff ℂ n (hoe.functor.obj U') ⟨b'.1, hmemU b' hb'⟩ (f i))
    constructor
    · rintro ⟨c, hc, hcb⟩ i
      obtain rfl : c = b' := Subtype.ext hcb
      have hne : J.stalkIdeal c ≠ ⊤ := hc
      rw [hgen c hb', ne_eq, Ideal.span_eq_top_iff_exists_isUnit] at hne
      by_contra h0
      exact hne ⟨_, ⟨i, rfl⟩, (hunit i).mpr h0⟩
    · intro h0
      refine ⟨b', ?_, rfl⟩
      change J.stalkIdeal b' ≠ ⊤
      rw [hgen b' hb', ne_eq, Ideal.span_eq_top_iff_exists_isUnit]
      rintro ⟨_, ⟨i, rfl⟩, hu⟩
      exact (hunit i).mp hu (h0 i)
  have hNS := vanishingStalkIdeal_eq_radical_span_affine q.1 hqU f hD
  have hpre : ((affine ℂ n).toLocallyRingedSpace.ofRestrict hoe).base ⁻¹'
      (Subtype.val '' J.support) = J.support := by
    ext b
    exact ⟨fun ⟨c, hc, hcb⟩ => (Subtype.ext hcb : c = b) ▸ hc, fun hb => ⟨b, hb, rfl⟩⟩
  have hV2 := vanishingStalkIdeal_preimage_eq_map ((affine ℂ n).toLocallyRingedSpace.ofRestrict hoe)
    hind (fun b => (hbij b).2) (D := Subtype.val '' J.support)
    (fun _ ⟨c, _, hcb⟩ => ⟨c, hcb⟩) q
  rw [hpre] at hV2
  have hker : RingHom.ker (((affine ℂ n).toLocallyRingedSpace.ofRestrict hoe).stalkMap q).hom ≤
      Ideal.span (Set.range fun i =>
        (affine ℂ n).toLocallyRingedSpace.presheaf.germ (hoe.functor.obj U') q.1 hqU (f i)) := by
    rw [(RingHom.injective_iff_ker_eq_bot _).mp (hbij q).1]
    exact bot_le
  refine hV2.trans ((congrArg _ hNS).trans
    ((Ideal.map_radical_of_surjective (hbij q).2 hker).trans (congrArg Ideal.radical ?_)))
  exact (Ideal.map_span _ _).trans ((congrArg Ideal.span ((Set.range_comp _ _).symm.trans
    (congrArg Set.range (funext fun i => hgerm q hqU' (f i))))).trans (hgen q hqU').symm)

/-- The Nullstellensatz descends to a quotient `(S(𝒥), 𝒪_Y/𝒥)`: for an ideal sheaf `J'` on the
quotient, given the Nullstellensatz on `Y` for its lift, the germs on the quotient vanishing on the
support of `J'` are the radical of `J'_z` (transport along the closed immersion, whose stalk maps
are the surjections `𝒪_{Y,z} → 𝒪_{Y,z}/𝒥_z`). -/
theorem vanishingStalkIdeal_cosupport_eq_radical_quotient (Y : LocallyRingedSpace.{u})
    (I : IdealSheaf Y.𝒪) (J' : IdealSheaf (QuotientSpace.quotientSpace Y I).𝒪)
    (z : QuotientSpace.quotientSpace Y I)
    (hY : vanishingStalkIdeal Y (QuotientSpace.liftIdeal Y I J').support z.1 =
      ((QuotientSpace.liftIdeal Y I J').stalkIdeal z.1).radical) :
    vanishingStalkIdeal (QuotientSpace.quotientSpace Y I) J'.support z =
      (J'.stalkIdeal z).radical := by
  have hsurj : ∀ z, Function.Surjective ((QuotientSpace.ι Y I).stalkMap z).hom := fun z =>
    QuotientSpace.stalkMap_surjective Y I z
  have hind : IsInducing (QuotientSpace.ι Y I).base := IsInducing.subtypeVal
  have hpre : (QuotientSpace.ι Y I).base ⁻¹' (Subtype.val '' J'.support) = J'.support := by
    ext b
    exact ⟨fun ⟨c, hc, hcb⟩ => (Subtype.ext hcb : c = b) ▸ hc, fun hb => ⟨b, hb, rfl⟩⟩
  have hcos : Subtype.val '' J'.support = (QuotientSpace.liftIdeal Y I J').support := by
    rw [QuotientSpace.cosupport_eq_preimage_cosupport_liftIdeal, Set.image_preimage_eq_inter_range,
      Subtype.range_coe]
    refine Set.inter_eq_left.mpr fun x hx => ?_
    by_contra hxI
    exact hx ((QuotientSpace.stalkIdeal_liftIdeal Y I J' x).trans
      (QuotientSpace.liftStalk_of_notMem Y I J' hxI))
  have hV2 := vanishingStalkIdeal_preimage_eq_map (QuotientSpace.ι Y I) hind hsurj
    (D := Subtype.val '' J'.support) (fun _ ⟨c, _, hcb⟩ => ⟨c, hcb⟩) z
  rw [hpre, hcos] at hV2
  have hlift : (QuotientSpace.liftIdeal Y I J').stalkIdeal z.1 =
      Ideal.comap ((QuotientSpace.ι Y I).stalkMap z).hom (J'.stalkIdeal z) :=
    (QuotientSpace.stalkIdeal_liftIdeal Y I J' z.1).trans
      (QuotientSpace.liftStalk_of_mem Y I J' z.2)
  refine hV2.trans ((congrArg _ (hY.trans (congrArg Ideal.radical hlift))).trans ?_)
  exact (Ideal.map_radical_of_surjective (hsurj z) (Ideal.ker_le_comap _)).trans
    (congrArg Ideal.radical (Ideal.map_comap_of_surjective _ (hsurj z) _))

/-- **Rückert's Nullstellensatz on an analytic `ℂ`-space** [GR84, Ch. 4, §1]: the germs at `y`
vanishing on the support of an ideal sheaf `J` are exactly the radical of `J_y`. Through a chart
`X|U ≅ (S(𝓘), 𝒜_G/𝓘)` and the transport of ideal sheaves (`restrictIdeal`, `comap`,
`liftIdeal`), the statement descends from `(G, 𝒜_G)`. -/
theorem vanishingStalkIdeal_cosupport_eq_radical (X : AnalyticSpace.{u} ℂ)
    (J : IdealSheaf X.toLocallyRingedSpace.𝒪) (y : X) :
    vanishingStalkIdeal X.toLocallyRingedSpace J.support y = (J.stalkIdeal y).radical := by
  obtain ⟨U, hyU, n, k, G, f, ⟨e⟩⟩ := AnalyticSpace.exists_kIso_localModel X y
  obtain ⟨φ₁, hφ₁⟩ : ∃ φ₁ : (X.toKLocallyRingedSpace.restrictOpen U).toLocallyRingedSpace ⟶
      X.toLocallyRingedSpace, φ₁ = (KLocallyRingedSpace.ofRestrict X.toKLocallyRingedSpace U).1 :=
    ⟨_, rfl⟩
  obtain ⟨φ₂, hφ₂⟩ : ∃ φ₂ : (localModel ℂ n G f).toLocallyRingedSpace ⟶
      (X.toKLocallyRingedSpace.restrictOpen U).toLocallyRingedSpace, φ₂ = e.inv.1 := ⟨_, rfl⟩
  -- parametrize the point from the model side: `y = φ₁ (φ₂ z)`
  obtain ⟨y', rfl⟩ : ∃ y' : X.toKLocallyRingedSpace.restrictOpen U, φ₁.base y' = y := by
    refine ⟨⟨y, hyU⟩, ?_⟩
    rw [hφ₁]
    rfl
  obtain ⟨z, rfl⟩ : ∃ z : localModel ℂ n G f, φ₂.base z = y' := by
    refine ⟨e.hom.1.base y', ?_⟩
    rw [hφ₂]
    exact congrArg (fun g : X.toKLocallyRingedSpace.restrictOpen U ⟶
      X.toKLocallyRingedSpace.restrictOpen U => g.1.base y') e.hom_inv_id
  obtain ⟨J₁, hJ₁⟩ : ∃ J₁ :
      IdealSheaf (X.toKLocallyRingedSpace.restrictOpen U).toLocallyRingedSpace.𝒪,
      J₁ = QuotientSpace.comap φ₁ J := ⟨_, rfl⟩
  obtain ⟨J₂, hJ₂⟩ : ∃ J₂ : IdealSheaf (localModel ℂ n G f).toLocallyRingedSpace.𝒪,
      J₂ = QuotientSpace.comap φ₂ J₁ := ⟨_, rfl⟩
  have hiso₁ : ∀ b, IsIso (φ₁.stalkMap b) := by
    rw [hφ₁]
    intro b
    exact LocallyRingedSpace.ofRestrict_stalkMap_isIso X.toLocallyRingedSpace
      (Opens.isOpenEmbedding (X := X.toLocallyRingedSpace.toTopCat) U) b
  have hb₁ : ∀ b, Function.Bijective (φ₁.stalkMap b).hom := fun b =>
    ConcreteCategory.bijective_of_isIso _
  have hiso₂ : ∀ b, IsIso (φ₂.stalkMap b) := by
    rw [hφ₂]
    intro b
    have : IsIso e.inv.1 := KLocallyRingedSpace.KIso.isIso_hom_val e.symm
    have : IsIso e.inv.1.toShHom.hom := SheafedSpace.is_presheafedSpace_iso e.inv.1.toShHom
    exact PresheafedSpace.stalkMap.isIso e.inv.1.toShHom.hom _
  have hb₂ : ∀ b, Function.Bijective (φ₂.stalkMap b).hom := fun b =>
    ConcreteCategory.bijective_of_isIso _
  have hind₁ : IsInducing φ₁.base := by
    rw [hφ₁]
    exact (Opens.isOpenEmbedding (X := X.toLocallyRingedSpace.toTopCat) U).isInducing
  have hind₂ : IsInducing φ₂.base := by
    rw [hφ₂]
    exact (KLocallyRingedSpace.KIso.homeomorph e.symm).isInducing
  have hsurj₂ : Function.Surjective φ₂.base := by
    rw [hφ₂]
    exact (KLocallyRingedSpace.KIso.homeomorph e.symm).surjective
  have hbase₁ : ∀ b, φ₁.base b = b.1 := by
    rw [hφ₁]
    intro b
    rfl
  -- (3) the local model, from `(G, 𝒜_G)`
  have hlm : vanishingStalkIdeal (localModel ℂ n G f).toLocallyRingedSpace J₂.support z =
      (J₂.stalkIdeal z).radical :=
    vanishingStalkIdeal_cosupport_eq_radical_quotient _ _ J₂ z
      (vanishingStalkIdeal_cosupport_eq_radical_analyticSpaceOfOpen G _ z.1)
  -- (2) `X | U`, along `e⁻¹`
  have hXU : vanishingStalkIdeal (X.toKLocallyRingedSpace.restrictOpen U).toLocallyRingedSpace
      J₁.support (φ₂.base z) = (J₁.stalkIdeal (φ₂.base z)).radical := by
    apply ideal_map_injective_of_bijective _ (hb₂ z)
    have hker : RingHom.ker (φ₂.stalkMap z).hom ≤ J₁.stalkIdeal (φ₂.base z) := by
      rw [(RingHom.injective_iff_ker_eq_bot _).mp (hb₂ z).1]
      exact bot_le
    have h1 : Ideal.map (φ₂.stalkMap z).hom (J₁.stalkIdeal (φ₂.base z)) = J₂.stalkIdeal z := by
      rw [hJ₂]
      exact (QuotientSpace.stalkIdeal_comap φ₂ J₁ z).symm
    have h2 : φ₂.base ⁻¹' J₁.support = J₂.support := by
      rw [hJ₂, QuotientSpace.cosupport_comap]
    refine ((vanishingStalkIdeal_preimage_eq_map φ₂ hind₂ (fun b => (hb₂ b).2)
      (D := J₁.support) (fun b _ => hsurj₂ b) z).symm.trans ?_).trans
      ((Ideal.map_radical_of_surjective (hb₂ z).2 hker).trans (congrArg Ideal.radical h1)).symm
    rw [h2]
    exact hlm
  -- (1) `X`, along the open immersion
  apply ideal_map_injective_of_bijective _ (hb₁ (φ₂.base z))
  have hker : RingHom.ker (φ₁.stalkMap (φ₂.base z)).hom ≤
      J.stalkIdeal (φ₁.base (φ₂.base z)) := by
    rw [(RingHom.injective_iff_ker_eq_bot _).mp (hb₁ _).1]
    exact bot_le
  have h1 : Ideal.map (φ₁.stalkMap (φ₂.base z)).hom (J.stalkIdeal (φ₁.base (φ₂.base z))) =
      J₁.stalkIdeal (φ₂.base z) := by
    rw [hJ₁]
    exact (QuotientSpace.stalkIdeal_comap φ₁ J (φ₂.base z)).symm
  have hU : (U : Set X) ∈ 𝓝 (φ₁.base (φ₂.base z)) := by
    rw [hbase₁]
    exact U.isOpen.mem_nhds (φ₂.base z).2
  have h2 : φ₁.base ⁻¹' (J.support ∩ (U : Set X)) = J₁.support := by
    rw [hJ₁, QuotientSpace.cosupport_comap]
    ext b
    rw [Set.mem_preimage, Set.mem_preimage, Set.mem_inter_iff, hbase₁]
    exact ⟨fun hb => hb.1, fun hb => ⟨hb, b.2⟩⟩
  have h3 := vanishingStalkIdeal_preimage_eq_map φ₁ hind₁ (fun b => (hb₁ b).2)
    (D := J.support ∩ (U : Set X)) (fun b hb => ⟨⟨b, hb.2⟩, hbase₁ _⟩) (φ₂.base z)
  rw [h2, vanishingStalkIdeal_inter_of_mem_nhds J.support hU] at h3
  exact h3.symm.trans (hXU.trans
    ((Ideal.map_radical_of_surjective (hb₁ _).2 hker).trans (congrArg Ideal.radical h1)).symm)

end AnalyticSpace

end
