/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.AnalyticSpace.QuotientMap
import Hironaka.AnalyticSpace.Quotient
import Hironaka.Manifold.IdealSheaf.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# The quotient of a quotient

A closed subspace of a closed subspace is a closed subspace: for an ideal sheaf `𝒥` on a locally
ringed space `X` and an ideal sheaf `𝒥'` on the quotient `Z = (S(𝒥), (𝒪_X/𝒥)|_{S(𝒥)})`, the
quotient of `Z` by `𝒥'` is the quotient of `X` by the **lifted** ideal sheaf `𝒥̃` whose stalk at
a point `x` of `S(𝒥)` is the preimage of `𝒥'_x` under the canonical stalk map
`𝒪_{X,x} → 𝒪_{Z,x} = 𝒪_{X,x}/𝒥_x` (and the unit ideal off `S(𝒥)`). This is what makes the local
models of a closed subspace of an analytic `K`-space the zero sets `V(f₁, …, f_k, g₁, …, g_l)`:
the `f_i` cut out the ambient model, the `g_j` are ambient lifts of local generators of `𝒥'`; it
is how a closed subspace of an analytic `K`-space is shown to be an analytic `K`-space.

**The lifted ideal sheaf.** The stalk family `liftStalk` (`Hironaka/AnalyticSpace/QuotientMap.lean`)
has local generators (`hasLocalGenerators_liftStalk`): near a point `a ∈ S(𝒥)`, local generators
`g_j` of `𝒥'` on an open of `S(𝒥)` are compatible germ families, each of which is, near `a`, the
class family of an ambient section `b_j` over an open `W_j ⊆ X`; on the common open `U` of `X` the
germs of the `b_j` together with local generators `f_i` of `𝒥` generate the preimage — the
canonical stalk map is surjective with kernel `𝒥_x` (`ker_stalkMap_ι`), and the preimage of an
ideal generated by the images of the `b_j` is the ideal they generate plus the kernel (Mathlib's
`Ideal.comap_map_of_surjective`); near a point off `S(𝒥)` the closed set `S(𝒥)` is avoided and
`1` generates. The germ of `g_j` at a point is the image of the germ of `b_j`
(`germ_eq_stalkMap_ι_germ`, by `germ_ext` on the open where the two families agree).

**The isomorphism.** The canonical morphism `ι : Z ⟶ X` is compatible with `𝒥'` and `𝒥̃`
(`compat_liftIdeal`), so the functorial `map` gives `Z/𝒥' ⟶ X/𝒥̃`. Its fibre maps
`𝒪_{X,x}/𝒥̃_x → 𝒪_{Z,x}/𝒥'_x` are bijective (`fiberMap_lift_bijective`: surjective because the
stalk map is, injective because `𝒥̃_x` is exactly the preimage), so the stalk maps are
isomorphisms; the base map identifies `S(𝒥')` with `S(𝒥̃)` — the support of `𝒥̃` is the image of
that of `𝒥'` (`cosupport_eq_preimage_cosupport_liftIdeal`, `mapBase_lift_surjective`), and the
map is an embedding as the restriction of the subtype inclusion (`isOpenEmbedding_mapBase_lift`).
Mathlib's `IsOpenImmersion.of_stalk_iso` makes `map` an open immersion onto everything, hence an
isomorphism (`isoOfRangeEq` against the identity): `KLocallyRingedSpace.quotient_quotient_iso`.
-/

@[expose] public noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite Manifold Topology

universe u

namespace AnalyticSpace.QuotientSpace

section Lift

variable (X : LocallyRingedSpace.{u}) (J : IdealSheaf X.𝒪)

/-- A compatible germ family that is, on the trace of an open `O ∋ z`, the class family of an
ambient section `b` has at `z` the germ `ι^♯_z (germ b)`. -/
theorem germ_eq_stalkMap_ι_germ {V : Opens (support X J)} (g : (presheafCommRing X J).obj (op V))
    {z : support X J} (hz : z ∈ V) {W : Opens X} (b : X.presheaf.obj (op W)) {O : Opens X}
    (hzO : z.1 ∈ O)
    (hloc : ∀ w : support X J, w.1 ∈ O → ∃ (hw : w ∈ V) (hwW : w.1 ∈ W),
      g.1 ⟨w, hw⟩ = Ideal.Quotient.mk _ (X.presheaf.germ W w.1 hwW b)) :
    ∃ hzW : z.1 ∈ W,
(presheafCommRing X J).germ V z hz g = ((ι X J).stalkMap z).hom (X.presheaf.germ W z.1 hzW b) := by
  obtain ⟨_, hzW, _⟩ := hloc z hzO
  refine ⟨hzW, ?_⟩
  rw [stalkMap_ι_germ]
  refine TopCat.Presheaf.germ_ext (presheafCommRing X J) (preimage X J (O ⊓ W) ⊓ V)
    ⟨⟨hzO, hzW⟩, hz⟩ (homOfLE inf_le_right) (homOfLE fun w hw => hw.1.2) ?_
  apply Subtype.ext
  funext w
  obtain ⟨hw, hwW, e⟩ := hloc w.1 w.2.1.1
  exact e

variable (J' : IdealSheaf (quotientSpace X J).𝒪)

/-- The lifted stalk family has local generators: near a point of the support, the generators of `𝒥`
together with ambient lifts of local generators of `𝒥'`; off the support, `1`. -/
theorem hasLocalGenerators_liftStalk :
    IdealSheaf.HasLocalGenerators (𝒪 := X.𝒪) (liftStalk X J J') := by
  intro a
  by_cases ha : a ∈ J.support
  · have hJ : ∃ (U₀ : Opens X) (_ : a ∈ U₀) (k : ℕ) (f : Fin k → X.presheaf.obj (op U₀)),
        ∀ b (hb : b ∈ U₀), stalkIdeal X J b =
          Ideal.span (Set.range fun i => X.presheaf.germ U₀ b hb (f i)) := by
      obtain ⟨U₀, haU₀, k, f, -, hf⟩ := J.exists_generators a
      exact ⟨U₀, haU₀, k, f, hf⟩
    obtain ⟨U₀, haU₀, k, f, hf⟩ := hJ
    obtain ⟨V', hyV', l, g, -, hg⟩ := J'.exists_generators ⟨a, ha⟩
    obtain ⟨O', hV'⟩ := exists_opens_eq_preimage X J V'
    have hloc : ∀ i : Fin l, ∃ (O : Opens X) (_ : a ∈ O) (W : Opens X) (b : X.presheaf.obj (op W)),
        ∀ w : support X J, w.1 ∈ O → ∃ (hw : w ∈ V') (hwW : w.1 ∈ W),
          (g i).1 ⟨w, hw⟩ = Ideal.Quotient.mk _ (X.presheaf.germ W w.1 hwW b) := by
      intro i
      obtain ⟨U₁, hy₁, i₁, W, b, hWb⟩ := (g i).2 ⟨⟨a, ha⟩, hyV'⟩
      obtain ⟨O, rfl⟩ := exists_opens_eq_preimage X J U₁
      refine ⟨O, hy₁, W, b, fun w hw => ?_⟩
      obtain ⟨hwW, e⟩ := hWb ⟨w, hw⟩
      exact ⟨i₁.le hw, hwW, e⟩
    choose O haO W b hOWb using hloc
    have haW : ∀ i, a ∈ W i := fun i => (hOWb i ⟨a, ha⟩ (haO i)).2.1
    have haO' : a ∈ O' := by
      have : (⟨a, ha⟩ : support X J) ∈ V' := hyV'
      rw [hV'] at this
      exact this
    let U : Opens X := U₀ ⊓ O' ⊓ Finset.univ.inf fun i => O i ⊓ W i
    have hUinf : U ≤ Finset.univ.inf fun i => O i ⊓ W i := inf_le_right
    have hUO : ∀ i, U ≤ O i := fun i =>
      hUinf.trans ((Finset.inf_le (Finset.mem_univ i)).trans inf_le_left)
    have hUW : ∀ i, U ≤ W i := fun i =>
      hUinf.trans ((Finset.inf_le (Finset.mem_univ i)).trans inf_le_right)
    have hUU₀ : U ≤ U₀ := inf_le_left.trans inf_le_left
    have hUO' : U ≤ O' := inf_le_left.trans inf_le_right
    have haU : a ∈ U := by
      refine ⟨⟨haU₀, haO'⟩, ?_⟩
      rw [Opens.coe_finset_inf, Finset.inf_eq_iInf]
      exact Set.mem_iInter₂.mpr fun i _ => ⟨haO i, haW i⟩
    refine ⟨U, haU, Fin l ⊕ Fin k, inferInstance,
      Sum.elim (fun i => X.presheaf.map (homOfLE (hUW i)).op (b i))
        (fun j => X.presheaf.map (homOfLE hUU₀).op (f j)), fun x hx => ?_⟩
    have hspan : Ideal.span (Set.range fun s : Fin l ⊕ Fin k => X.presheaf.germ U x hx
        (Sum.elim (fun i => X.presheaf.map (homOfLE (hUW i)).op (b i))
          (fun j => X.presheaf.map (homOfLE hUU₀).op (f j)) s)) =
        Ideal.span (Set.range fun i => X.presheaf.germ (W i) x (hUW i hx) (b i)) ⊔
          Ideal.span (Set.range fun j => X.presheaf.germ U₀ x (hUU₀ hx) (f j)) := by
      rw [← Ideal.span_union]
      congr 1
      ext σ
      constructor
      · rintro ⟨s, rfl⟩
        rcases s with i | j
        · exact Or.inl ⟨i, (TopCat.Presheaf.germ_res_apply _ _ _ _ _).symm⟩
        · exact Or.inr ⟨j, (TopCat.Presheaf.germ_res_apply _ _ _ _ _).symm⟩
      · rintro (⟨i, rfl⟩ | ⟨j, rfl⟩)
        · exact ⟨Sum.inl i, TopCat.Presheaf.germ_res_apply _ _ _ _ _⟩
        · exact ⟨Sum.inr j, TopCat.Presheaf.germ_res_apply _ _ _ _ _⟩
    change liftStalk X J J' x = Ideal.span (Set.range fun s : Fin l ⊕ Fin k =>
      X.presheaf.germ U x hx (Sum.elim (fun i => X.presheaf.map (homOfLE (hUW i)).op (b i))
        (fun j => X.presheaf.map (homOfLE hUU₀).op (f j)) s))
    rw [hspan]
    by_cases hx' : x ∈ J.support
    · rw [liftStalk_of_mem X J J' hx']
      have hyV' : (⟨x, hx'⟩ : support X J) ∈ V' := by rw [hV']; exact hUO' hx
      have hgy : stalkIdeal (quotientSpace X J) J' ⟨x, hx'⟩ =
          Ideal.span (Set.range fun i => (presheafCommRing X J).germ V' ⟨x, hx'⟩ hyV' (g i)) :=
        hg ⟨x, hx'⟩ hyV'
      have hgi : ∀ i, (presheafCommRing X J).germ V' ⟨x, hx'⟩ hyV' (g i) =
          ((ι X J).stalkMap ⟨x, hx'⟩).hom (X.presheaf.germ (W i) x (hUW i hx) (b i)) := fun i =>
        (germ_eq_stalkMap_ι_germ X J (g i) hyV' (b i) (hUO i hx) (hOWb i)).2
      have hsurj : Function.Surjective ((ι X J).stalkMap ⟨x, hx'⟩).hom :=
        stalkMap_surjective X J ⟨x, hx'⟩
      have hrange : (Set.range fun i => ((ι X J).stalkMap ⟨x, hx'⟩).hom
            (X.presheaf.germ (W i) x (hUW i hx) (b i))) =
          ((ι X J).stalkMap ⟨x, hx'⟩).hom ''
            Set.range (fun i => X.presheaf.germ (W i) x (hUW i hx) (b i)) :=
        Set.range_comp _ _
      rw [hgy]
      simp_rw [hgi]
      rw [hrange, ← Ideal.map_span, Ideal.comap_map_of_surjective _ hsurj,
        ← RingHom.ker_eq_comap_bot, ker_stalkMap_ι, hf x (hUU₀ hx)]
      rfl
    · rw [liftStalk_of_notMem X J J' hx']
      have h1 : stalkIdeal X J x = ⊤ := not_not.mp hx'
      have h2 : Ideal.span (Set.range fun j => X.presheaf.germ U₀ x (hUU₀ hx) (f j)) = ⊤ :=
        (hf x (hUU₀ hx)).symm.trans h1
      exact (eq_top_iff.mpr (h2.ge.trans le_sup_right)).symm
  · refine ⟨⟨J.supportᶜ, J.isOpen_compl_support⟩, ha, Unit, inferInstance, fun _ => 1,
      fun x hx => ?_⟩
    rw [liftStalk_of_notMem X J J' hx]
    have h1 : (1 : X.presheaf.stalk x) ∈ Set.range fun _ : Unit =>
        X.presheaf.germ ⟨J.supportᶜ, J.isOpen_compl_support⟩ x hx (1 : X.presheaf.obj _) :=
      ⟨(), map_one _⟩
    exact ((Ideal.eq_top_iff_one _).mpr (Ideal.subset_span h1)).symm


/-- The lifted ideal sheaf on `X`: the preimage of `𝒥'` under the canonical stalk maps at the
points of the support, the unit ideal elsewhere. -/
def liftIdeal : IdealSheaf X.𝒪 := IdealSheaf.ofStalks X.𝒪 _ (hasLocalGenerators_liftStalk X J J')

theorem stalkIdeal_liftIdeal (x : X) : (liftIdeal X J J').stalkIdeal x = liftStalk X J J' x :=
  IdealSheaf.stalkIdeal_ofStalks _ _ x

theorem compat_liftIdeal : Compat (ι X J) J' (liftIdeal X J J') := by
  intro z
  have h1 : stalkIdeal X (liftIdeal X J J') ((ι X J).base z) =
      (stalkIdeal (quotientSpace X J) J' z).comap ((ι X J).stalkMap z).hom :=
    (stalkIdeal_liftIdeal X J J' z.1).trans (liftStalk_of_mem X J J' z.2)
  change (stalkIdeal X (liftIdeal X J J') ((ι X J).base z)).map ((ι X J).stalkMap z).hom ≤ _
  rw [h1]
  exact Ideal.map_comap_le

theorem fiberMap_lift_bijective (z : support (quotientSpace X J) J') :
    Function.Bijective (fiberMap (ι X J) J' (liftIdeal X J J') (compat_liftIdeal X J J') z) := by
  refine ⟨Ideal.quotientMap_injective' ?_,
    Ideal.quotientMap_surjective (stalkMap_surjective X J z.1)⟩
  have h1 : stalkIdeal X (liftIdeal X J J') ((ι X J).base z.1) =
      (stalkIdeal (quotientSpace X J) J' z.1).comap ((ι X J).stalkMap z.1).hom :=
    (stalkIdeal_liftIdeal X J J' z.1.1).trans (liftStalk_of_mem X J J' z.1.2)
  exact h1.ge

/-- The support of `𝒥'` is the part of the support of `𝒥` lying over the support of the lifted
ideal sheaf. -/
theorem cosupport_eq_preimage_cosupport_liftIdeal :
    J'.support = (Subtype.val : support X J → X) ⁻¹' (liftIdeal X J J').support := by
  ext z
  rw [IdealSheaf.mem_support, Set.mem_preimage, IdealSheaf.mem_support, stalkIdeal_liftIdeal,
    liftStalk_of_mem X J J' z.2]
  exact (not_congr Ideal.comap_eq_top_iff).symm

theorem mapBase_lift_surjective :
    Function.Surjective (mapBase (ι X J) J' (liftIdeal X J J') (compat_liftIdeal X J J')) := by
  intro x
  have hx' : liftStalk X J J' x.1 ≠ ⊤ := by
    have h := x.2
    rw [IdealSheaf.mem_support, stalkIdeal_liftIdeal] at h
    exact h
  have hx : x.1 ∈ J.support := by
    by_contra hcon
    exact hx' (liftStalk_of_notMem X J J' hcon)
  rw [liftStalk_of_mem X J J' hx] at hx'
  have hz : (⟨x.1, hx⟩ : support X J) ∈ J'.support := by
    rw [IdealSheaf.mem_support]
    intro htop
    apply hx'
    have htop' : stalkIdeal (quotientSpace X J) J' ⟨x.1, hx⟩ = ⊤ := htop
    rw [htop', Ideal.comap_top]
  exact ⟨⟨⟨x.1, hx⟩, hz⟩, Subtype.ext rfl⟩

theorem isOpenEmbedding_mapBase_lift :
    IsOpenEmbedding (mapBase (ι X J) J' (liftIdeal X J J') (compat_liftIdeal X J J')) := by
  have e : (mapBase (ι X J) J' (liftIdeal X J J') (compat_liftIdeal X J J') :
      support (quotientSpace X J) J' → support X (liftIdeal X J J')) =
      (liftIdeal X J J').support.restrictPreimage (Subtype.val : support X J → X) ∘
        Homeomorph.setCongr (cosupport_eq_preimage_cosupport_liftIdeal X J J') := by
    funext z
    rfl
  refine ⟨?_, ?_⟩
  · rw [e]
    exact (Set.restrictPreimage_isEmbedding _ IsEmbedding.subtypeVal).comp
      (Homeomorph.setCongr _).isEmbedding
  · rw [Set.range_eq_univ.mpr (mapBase_lift_surjective X J J')]
    exact isOpen_univ

theorem isOpenImmersion_map_lift :
    LocallyRingedSpace.IsOpenImmersion
      (map (ι X J) J' (liftIdeal X J J') (compat_liftIdeal X J J')) :=
  have : ∀ z, IsIso ((map (ι X J) J' (liftIdeal X J J') (compat_liftIdeal X J J')).stalkMap z) :=
    fun z => isIso_map_stalkMap_of_bijective _ _ _ _ z (fiberMap_lift_bijective X J J' z)
  LocallyRingedSpace.IsOpenImmersion.of_stalk_iso _ (isOpenEmbedding_mapBase_lift X J J')

end Lift

end AnalyticSpace.QuotientSpace

namespace AnalyticSpace.KLocallyRingedSpace

variable {K : Type} [RCLike K] (X : KLocallyRingedSpace.{u} K)
  (J : IdealSheaf X.toLocallyRingedSpace.𝒪) (J' : IdealSheaf (X.quotient J).toLocallyRingedSpace.𝒪)

/-- The lifted ideal sheaf of `𝒥'` on `X / 𝒥`, as an ideal sheaf on `X`: an alias of
`QuotientSpace.liftIdeal` for the `K`-local-ringed space `X`. -/
abbrev liftIdeal : IdealSheaf X.toLocallyRingedSpace.𝒪 :=
  QuotientSpace.liftIdeal X.toLocallyRingedSpace J J'

instance isOpenImmersion_quotientMap_quotientι :
    LocallyRingedSpace.IsOpenImmersion
      (quotientMap (quotientι X J) J' (liftIdeal X J J')
        (QuotientSpace.compat_liftIdeal _ J J')).1 :=
  QuotientSpace.isOpenImmersion_map_lift _ J J'

theorem range_quotientMap_quotientι :
    Set.range (Hom.toFun (quotientMap (quotientι X J) J' (liftIdeal X J J')
        (QuotientSpace.compat_liftIdeal _ J J'))) =
      Set.range (Hom.toFun (𝟙 (X.quotient (liftIdeal X J J')))) := by
  rw [Hom.toFun_id, Set.range_id]
  exact Set.range_eq_univ.mpr (QuotientSpace.mapBase_lift_surjective _ J J')

/-- The quotient of a quotient is the quotient by the lifted ideal sheaf:
`(X / 𝒥) / 𝒥' ≅ X / 𝒥̃`. -/
def quotient_quotient_iso : (X.quotient J).quotient J' ≅ X.quotient (liftIdeal X J J') :=
  haveI : LocallyRingedSpace.IsOpenImmersion
      (𝟙 (X.quotient (liftIdeal X J J')) : Hom _ _).1 :=
    inferInstanceAs
      (LocallyRingedSpace.IsOpenImmersion (𝟙 (X.quotient (liftIdeal X J J')).toLocallyRingedSpace))
  isoOfRangeEq (quotientMap (quotientι X J) J' (liftIdeal X J J')
      (QuotientSpace.compat_liftIdeal _ J J'))
    (𝟙 _) (range_quotientMap_quotientι X J J')

end AnalyticSpace.KLocallyRingedSpace
