/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUp.Chart
public import Hironaka.Scheme.IdealSheaf.Defs
public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Hironaka.Scheme.BlowUp.AffineAlgebra
import Hironaka.Scheme.BlowUp.InverseImage
import Hironaka.Scheme.BlowUp.Invertible

/-!
# The exceptional ideal of the affine blow-up on its charts

For an ideal `I` of a commutative ring `R`, the **exceptional ideal** of the affine blow-up
`B = affineBlowUp I = Proj Rees(I)` is the ideal sheaf `I · 𝒪_B`, the inverse image
(`IdealSheafData.comap`) of the ideal sheaf of `I` on `Spec R` under the blow-up map `π`: the
ideal of the exceptional divisor `E = π⁻¹(Z)` [Hau14, Definitions 4.4 and 4.7]; [Sta, Tag 02OS];
[Kol07, Notation 19].

On the chart of `a ∈ I`, `affineBlowUp.chart a ≫ π = Spec (R → R[I/a])` (`affineBlowUp.chart_π`),
so the inverse image of `I` on the chart is the ideal sheaf of `I·R[I/a]` (the affine computation
`comap_ofIdealTop_Spec_map`), which is `a·R[I/a]`
(`affineBlowUpAlgebra.map_algebraMap_eq_span_singleton`) with `a` a nonzerodivisor of `R[I/a]`
(`affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors`).
Since the charts cover `B`, the exceptional ideal is invertible in the sense of
`IdealSheafData.IsInvertible` (locally, on an affine open, principal with a nonzerodivisor
generator): the exceptional divisor is an effective Cartier divisor [Sta, Tag 02OS].

* `affineBlowUp.exceptionalIdeal I : (affineBlowUp I).IdealSheafData` — the exceptional ideal.
* `affineBlowUp.comap_exceptionalIdeal_chart` — its inverse image on the chart of `a` is the
  ideal sheaf of `(a) ⊆ R[I/a]`.
* `affineBlowUp.ideal_comap_exceptionalIdeal_chart_top`,
  `affineBlowUp.chartGenerator_mem_nonZeroDivisors` — on `Spec R[I/a]` the exceptional ideal is
  generated by the image of `a`, a nonzerodivisor.
* `affineBlowUp.exists_generator_exceptionalIdeal_opensRange_chart` — the same on the affine open
  `U_a ⊆ B`, the image of the chart (transport along `Scheme.Hom.appIso`).
* `affineBlowUp.isInvertible_exceptionalIdeal` — the exceptional ideal is invertible.

The ideal sheaf of `I` on `Spec R` is written `ofIdealTop (I.map (Scheme.ΓSpecIso (.of R)).inv.hom)`
(sections transported by `ΓSpecIso`), as throughout `Hironaka.BlowUp`.
-/

@[expose] public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory Scheme.IdealSheafData

universe u

variable {R : Type u} [CommRing R] (I : Ideal R)

/-- **The exceptional ideal** `I · 𝒪_B` of the affine blow-up: the inverse image of the ideal
sheaf of `I` on `Spec R` under the blow-up map — the ideal of the exceptional divisor `E = π⁻¹(Z)`
[Hau14, Definition 4.4]; [Sta, Tag 02OS]; [Kol07, Notation 19]. -/
noncomputable def affineBlowUp.exceptionalIdeal : (affineBlowUp I).IdealSheafData :=
  (Scheme.IdealSheafData.ofIdealTop (I.map (Scheme.ΓSpecIso (.of R)).inv.hom)).comap
      (affineBlowUp.π I)

/-- The inverse image of the exceptional ideal on the chart of `a` is the ideal sheaf of the
principal ideal `(a)` of `R[I/a]` (the identity `I A' = a A'` on the chart `Spec A'` of
[Sta, Tag 02OS]) — from `chart ≫ π = Spec (R → R[I/a])`, the affine computation of the inverse
image (`comap_ofIdealTop_Spec_map`) and `I·R[I/a] = a·R[I/a]`. -/
theorem affineBlowUp.comap_exceptionalIdeal_chart (a : I) :
    (affineBlowUp.exceptionalIdeal I).comap (affineBlowUp.chart I a) =
      Scheme.IdealSheafData.ofIdealTop ((Ideal.span {algebraMap R (affineBlowUpAlgebra I a) a}).map
        (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra I a))).inv.hom) := by
  unfold affineBlowUp.exceptionalIdeal
  rw [← Scheme.IdealSheafData.comap_comp, affineBlowUp.chart_π,
      Scheme.IdealSheafData.comap_ofIdealTop_Spec_map, CommRingCat.hom_ofHom,
    affineBlowUpAlgebra.map_algebraMap_eq_span_singleton a.2]

/-- The generator of the exceptional ideal on the chart of `a`: the image of `a` in the global
sections of `Spec R[I/a]`. -/
noncomputable abbrev affineBlowUp.chartGenerator (a : I) :
    Γ(Spec (.of (affineBlowUpAlgebra I a)), ⊤) :=
  (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra I a))).inv.hom
    (algebraMap R (affineBlowUpAlgebra I a) a)

/-- On `Spec R[I/a]` the exceptional ideal is the principal ideal generated by the image of
`a`. -/
theorem affineBlowUp.ideal_comap_exceptionalIdeal_chart_top (a : I) :
    ((affineBlowUp.exceptionalIdeal I).comap (affineBlowUp.chart I a)).ideal
        ⟨⊤, isAffineOpen_top _⟩ =
      Ideal.span {affineBlowUp.chartGenerator I a} := by
  rw [affineBlowUp.comap_exceptionalIdeal_chart, Scheme.IdealSheafData.ofIdealTop_ideal,
    show homOfLE (le_top : (⊤ : (Spec (.of (affineBlowUpAlgebra I a))).Opens) ≤ ⊤) = 𝟙 _ from rfl,
    op_id, CategoryTheory.Functor.map_id, CommRingCat.hom_id, Ideal.map_id, Ideal.map_span,
    Set.image_singleton]

/-- The generator of the exceptional ideal on the chart of `a` is a nonzerodivisor (`a` is a
unit of `R_a ⊇ R[I/a]`; [Sta, Tag 02OS]). -/
theorem affineBlowUp.chartGenerator_mem_nonZeroDivisors (a : I) :
    affineBlowUp.chartGenerator I a ∈
      nonZeroDivisors Γ(Spec (.of (affineBlowUpAlgebra I a)), ⊤) :=
  map_mem_nonZeroDivisors_of_ringEquiv
    (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra I a))).symm.commRingCatIsoToRingEquiv
    affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors

/-- On the affine open `U_a = chart a ''ᵁ ⊤ ⊆ B`, the exceptional ideal is generated by a
nonzerodivisor (the image of `a`, transported along the isomorphism
`Γ(B, U_a) ≅ Γ(Spec R[I/a], ⊤)` of the open immersion). -/
theorem affineBlowUp.exists_generator_exceptionalIdeal_image_chart (a : I)
    (W : (affineBlowUp I).Opens) (hW : IsAffineOpen W)
    (hWeq : W = affineBlowUp.chart I a ''ᵁ ⊤) :
    ∃ f ∈ nonZeroDivisors Γ(affineBlowUp I, W),
      (affineBlowUp.exceptionalIdeal I).ideal ⟨W, hW⟩ = Ideal.span {f} := by
  subst hWeq
  set j := affineBlowUp.chart I a
  set e := (j.appIso ⊤).commRingCatIsoToRingEquiv with he
  let ψ : Γ(Spec (.of (affineBlowUpAlgebra I a)), ⊤) →+* Γ(affineBlowUp I, j ''ᵁ ⊤) := e.symm
  have hψ : (j.appIso ⊤).inv.hom = ψ := RingHom.ext fun _ => rfl
  have hψs : Function.Surjective ψ := e.symm.surjective
  have h1 : ((affineBlowUp.exceptionalIdeal I).comap j).ideal ⟨⊤, isAffineOpen_top _⟩ =
      ((affineBlowUp.exceptionalIdeal I).ideal ⟨j ''ᵁ ⊤, hW⟩).comap (j.appIso ⊤).inv.hom :=
    Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion (affineBlowUp.exceptionalIdeal I) j ⟨⊤,
        isAffineOpen_top _⟩
  rw [affineBlowUp.ideal_comap_exceptionalIdeal_chart_top, hψ] at h1
  refine ⟨ψ (affineBlowUp.chartGenerator I a),
    map_mem_nonZeroDivisors_of_ringEquiv e.symm
      (affineBlowUp.chartGenerator_mem_nonZeroDivisors I a), ?_⟩
  have h2 := congrArg (Ideal.map ψ) h1
  rw [Ideal.map_comap_of_surjective ψ hψs, Ideal.map_span, Set.image_singleton] at h2
  exact h2.symm

/-- The same on the affine open `U_a ⊆ B`, the image of the chart of `a`. -/
theorem affineBlowUp.exists_generator_exceptionalIdeal_opensRange_chart (a : I) :
    ∃ f ∈ nonZeroDivisors Γ(affineBlowUp I, (affineBlowUp.chart I a).opensRange),
      (affineBlowUp.exceptionalIdeal I).ideal
        ⟨(affineBlowUp.chart I a).opensRange, isAffineOpen_opensRange _⟩ = Ideal.span {f} :=
  affineBlowUp.exists_generator_exceptionalIdeal_image_chart I a _ _
    (Scheme.Hom.image_top_eq_opensRange _).symm

/-- **The exceptional ideal of the affine blow-up is invertible** — the exceptional divisor is an
effective Cartier divisor [Sta, Tag 02OS]; [Hau14, Definition 4.4]: every point lies in the chart
of some `a ∈ I`, an affine open on which the exceptional ideal is generated by the nonzerodivisor
`a`. -/
theorem affineBlowUp.isInvertible_exceptionalIdeal :
    (affineBlowUp.exceptionalIdeal I).IsInvertible := fun x => by
  obtain ⟨a, hx⟩ := affineBlowUp.exists_mem_opensRange_chart I x
  obtain ⟨f, hf, hJ⟩ := affineBlowUp.exists_generator_exceptionalIdeal_opensRange_chart I a
  exact ⟨⟨(affineBlowUp.chart I a).opensRange, isAffineOpen_opensRange _⟩, hx, f, hf, hJ⟩

end AlgebraicGeometry
