/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.ProjectiveBundle.Defs
public import Hironaka.Scheme.BlowUp.Defs
public import Hironaka.Scheme.Modules.IdealSheaf
public import Hironaka.Scheme.Modules.IdealSheafFinite
public import Hironaka.Algebra.SymmetricAlgebra.Lift
import Hironaka.Algebra.SymmetricAlgebra.Away
import Hironaka.Scheme.BlowUp.Rees.Basic
import Hironaka.Scheme.BlowUp.Rees.Irrelevant
import Hironaka.Scheme.BlowUp.Rees.Map
import Hironaka.Scheme.ProjectiveBundle.Affine.Properties
import Hironaka.Scheme.BlowUp.Glue.AffineBlowUpFunctor

/-!
# A blow-up is a closed subscheme of a projective bundle

For an ideal sheaf `I` on a scheme `X` whose sheaf of modules `I.toModules` is quasi-coherent, the
blow-up `Bl_I X = Proj_X (⨁ₙ Iⁿ)` is a closed subscheme of the projective bundle
`P(I) = Proj_X (Sym I)` over `X` [Sta, Tag 02NS]: the surjection `Sym I → ⨁ₙ Iⁿ`, the identity of
`I` in degree one, induces a closed immersion `Bl_I X ⟶ P(I)` over `X`
(`Scheme.IdealSheafData.blowUpToProjectiveBundle`, `isClosedImmersion_blowUpToProjectiveBundle`).
Over an affine open `U` it is `Proj` of the surjection `Sym_{Γ(X, U)} I(U) → Rees(I(U))`, a closed
immersion (`Proj.isClosedImmersion_map_of_surjective`); these charts are natural in `U`, so they
glue to a morphism of the glued schemes over `X`, and over the chart of `U` it is the chart
morphism, so it is a closed immersion, being one is local on the target.
-/

@[expose] public section

universe u

open CategoryTheory CategoryTheory.Limits SymmetricAlgebra Polynomial

namespace AlgebraicGeometry

variable {X : Scheme.{u}} (I : X.IdealSheafData)

namespace Scheme.IdealSheafData

/-- The degree-one map `I(U) → Rees(I(U))`, `a ↦ a t`, on the sections of `I.toModules` over an
affine open `U`. -/
noncomputable def toModulesToRees (U : X.affineOpens) :
    Γ(I.toModules, U) →ₗ[Γ(X, U)] reesAlgebra (I.ideal U) :=
  reesAlgebra.degreeOne (I.ideal U) ∘ₗ (I.toModulesSectionsEquiv U).toLinearMap

/-- The graded surjection `Sym_{Γ(X, U)} Γ(I.toModules, U) → Rees(I(U))`, the lift of
`toModulesToRees`. -/
noncomputable def symToRees (U : X.affineOpens) :
    grading Γ(X, U) Γ(I.toModules, U) →+*ᵍ reesAlgebra.grading (I.ideal U) :=
  gradedLift (reesAlgebra.grading (I.ideal U)) (I.toModulesToRees U)
    fun _ => reesAlgebra.degreeOne_mem _

theorem symToRees_ι (U : X.affineOpens) (s : Γ(I.toModules, U)) :
    I.symToRees U (ι _ _ s) = reesAlgebra.degreeOne (I.ideal U) (I.toModulesSectionsEquiv U s) :=
  lift_ι_apply (I.toModulesToRees U) s

theorem symToRees_algebraMap (U : X.affineOpens) (r : Γ(X, U)) :
    I.symToRees U (algebraMap _ _ r) = algebraMap Γ(X, U) (reesAlgebra (I.ideal U)) r :=
  AlgHom.commutes (lift (I.toModulesToRees U)) r

theorem degreeOne_mem_range (U : X.affineOpens) (a : I.ideal U) :
    reesAlgebra.degreeOne (I.ideal U) a ∈ (I.symToRees U).toRingHom.range :=
  ⟨ι _ _ ((I.toModulesSectionsEquiv U).symm a), by
    rw [GradedRingHom.coe_toRingHom, symToRees_ι, LinearEquiv.apply_symm_apply]⟩

/-- The graded map `Sym I(U) → Rees(I(U))` is surjective: the Rees algebra is generated by its
degree-one elements `a t`, `a ∈ I(U)`. -/
theorem symToRees_surjective (U : X.affineOpens) : Function.Surjective (I.symToRees U) := by
  -- The range contains every monomial `c tⁿ`, `c ∈ I(U)ⁿ`, by induction on the power.
  have key : ∀ (n : ℕ) (c : Γ(X, U)) (hc : c ∈ I.ideal U ^ n),
      (⟨monomial n c, reesAlgebra.monomial_mem.mpr hc⟩ : reesAlgebra (I.ideal U)) ∈
        (I.symToRees U).toRingHom.range := by
    intro n c hc
    induction hc using Submodule.pow_induction_on_left' with
    | algebraMap r =>
      refine ⟨algebraMap _ _ r, ?_⟩
      rw [GradedRingHom.coe_toRingHom, symToRees_algebraMap]
      refine Subtype.ext ?_
      change Polynomial.C r = monomial 0 r
      exact (Polynomial.monomial_zero_left (R := Γ(X, U)) (a := r)).symm
    | add x y i hx hy ihx ihy =>
      have hx' : monomial i x ∈ reesAlgebra (I.ideal U) := reesAlgebra.monomial_mem.mpr hx
      have hy' : monomial i y ∈ reesAlgebra (I.ideal U) := reesAlgebra.monomial_mem.mpr hy
      have : (⟨monomial i (x + y), reesAlgebra.monomial_mem.mpr (add_mem hx hy)⟩ :
          reesAlgebra (I.ideal U)) = ⟨monomial i x, hx'⟩ + ⟨monomial i y, hy'⟩ :=
        Subtype.ext (map_add (monomial i) x y)
      rw [this]
      exact add_mem (ihx) (ihy)
    | mem_mul m hm i x hx ih =>
      have hx' : monomial i x ∈ reesAlgebra (I.ideal U) := reesAlgebra.monomial_mem.mpr hx
      have : (⟨monomial (i + 1) (m * x), reesAlgebra.monomial_mem.mpr (by
            rw [pow_succ']; exact Submodule.mul_mem_mul hm hx)⟩ : reesAlgebra (I.ideal U)) =
          reesAlgebra.degreeOne (I.ideal U) ⟨m, hm⟩ * ⟨monomial i x, hx'⟩ :=
        Subtype.ext (by
          change monomial (i + 1) (m * x) = monomial 1 m * monomial i x
          rw [monomial_mul_monomial, add_comm])
      rw [this]
      exact mul_mem (I.degreeOne_mem_range U ⟨m, hm⟩) ih
  intro p
  have hp : p = ∑ n ∈ (p : Γ(X, U)[X]).support,
      ⟨monomial n ((p : Γ(X, U)[X]).coeff n), reesAlgebra.monomial_mem.mpr
        (reesAlgebra.coeff_mem_pow p n)⟩ := by
    refine Subtype.ext ?_
    rw [AddSubmonoidClass.coe_finsetSum]
    exact (as_sum_support (p : Γ(X, U)[X]))
  obtain ⟨q, hq⟩ : p ∈ (I.symToRees U).toRingHom.range := by
    rw [hp]
    exact Subring.sum_mem _ fun n _ => key n _ (reesAlgebra.coeff_mem_pow p n)
  exact ⟨q, hq⟩

/-- The `Proj.map` hypothesis for `symToRees`: the irrelevant ideal of `Rees(I(U))`, generated by
the degree-one elements `a t`, lies in the ideal generated by the image of that of `Sym I(U)`. -/
theorem irrelevant_le_map_symToRees (U : X.affineOpens) :
    HomogeneousIdeal.irrelevant (reesAlgebra.grading (I.ideal U)) ≤
      (HomogeneousIdeal.irrelevant (grading Γ(X, U) Γ(I.toModules, U))).map (I.symToRees U) := by
  rw [← toIdeal_le_toIdeal_iff, HomogeneousIdeal.toIdeal_map]
  refine (reesAlgebra.irrelevant_le_span_degreeOne _).trans (Ideal.span_le.mpr ?_)
  rintro _ ⟨a, rfl⟩
  rw [← LinearEquiv.apply_symm_apply (I.toModulesSectionsEquiv U) a, ← symToRees_ι]
  exact Ideal.mem_map_of_mem _
    (HomogeneousIdeal.mem_irrelevant_of_mem _ one_pos (ι_mem_grading_one _))

/-- The chart of the closed immersion of the blow-up in the projective bundle over an affine open
`U`: `Proj` of the surjection `Sym I(U) → Rees(I(U))`. -/
noncomputable def blowUpChart (U : X.affineOpens) :
    affineBlowUp (I.ideal U) ⟶ affineProjectiveBundle Γ(X, U) Γ(I.toModules, U) :=
  Proj.map (I.symToRees U) (I.irrelevant_le_map_symToRees U)

theorem isClosedImmersion_blowUpChart (U : X.affineOpens) : IsClosedImmersion (I.blowUpChart U) :=
  Proj.isClosedImmersion_map_of_surjective _ _ (I.symToRees_surjective U)

/-- Over the base: the chart lies over `Spec Γ(X, U)`. -/
theorem blowUpChart_π (U : X.affineOpens) :
    I.blowUpChart U ≫ affineProjectiveBundle.π Γ(X, U) Γ(I.toModules, U) =
      affineBlowUp.π (I.ideal U) := by
  rw [blowUpChart, affineProjectiveBundle.π, affineBlowUp.π, Proj.map_toSpecZero_assoc,
    ← Spec.map_comp]
  congr 2
  refine CommRingCat.hom_ext (RingHom.ext fun r => Subtype.ext (Subtype.ext ?_))
  change ((I.symToRees U (algebraMap _ _ r) : reesAlgebra (I.ideal U)) : Γ(X, U)[X]) = _
  rw [symToRees_algebraMap]
  rfl

variable [I.toModules.IsQuasicoherent]

/-- The charts are natural in the affine open: `Proj` of the commutative square of graded maps
`Sym I(V) → Rees(I(V)) → Rees(I(U))`, `Sym I(V) → Sym I(U) → Rees(I(U))`, checked on the generators
and the constants. -/
theorem blowUpChart_naturality {U V : X.affineOpens} (h : U ⟶ V) :
    (affineBlowUpFunctor I).map h ≫ I.blowUpChart V =
      I.blowUpChart U ≫ (projectiveBundleFunctor I.toModules).map h := by
  have key : ∀ (F : grading Γ(X, V) Γ(I.toModules, V) →+*ᵍ reesAlgebra.grading (I.ideal U))
      (hF) (F' : grading Γ(X, V) Γ(I.toModules, V) →+*ᵍ reesAlgebra.grading (I.ideal U)) (hF'),
      F = F' → Proj.map F hF = Proj.map F' hF' := by
    rintro F hF _ hF' rfl
    rfl
  rw [affineBlowUpFunctor_map]
  dsimp only [projectiveBundleFunctor, affineBlowUp.mapHom, affineBlowUp.mapOfEq,
    affineProjectiveBundle.mapHom, affineProjectiveBundle.map, blowUpChart]
  rw [← Proj.map_comp]
  refine (Proj.map_comp _ _ _ _).symm.trans (key _ _ _ _ (GradedRingHom.ext fun a =>
    RingHom.congr_fun (ringHom_ext
    (F := ((reesAlgebra.mapOfLe _ _).comp (I.symToRees V)).toRingHom)
    (G := ((I.symToRees U).comp (gradedMap _ (I.toModules.restrictionMap h.le))).toRingHom)
    (fun r => ?_) (fun x => ?_)) a))
  · simp only [GradedRingHom.coe_toRingHom, GradedRingHom.comp_apply, symToRees_algebraMap,
      gradedMap_algebraMap]
    refine Subtype.ext ?_
    change ((Polynomial.C r).map _ : Γ(X, U)[X]) = Polynomial.C _
    rw [Polynomial.map_C]
    rfl
  · simp only [GradedRingHom.coe_toRingHom, GradedRingHom.comp_apply, symToRees_ι,
      gradedMap_ι, reesAlgebra.mapOfLe_degreeOne]
    rfl

/-- The charts `blowUpChart`, as a natural transformation from the affine blow-ups to the
projective bundles of `I.toModules` over the affine opens. -/
noncomputable def blowUpNatTrans :
    (relativeGluingDataOf I (affineBlowUpNatTrans_equifibered I)).functor ⟶
      (projectiveBundleGluingData I.toModules).functor where
  app := I.blowUpChart
  naturality _ _ h := I.blowUpChart_naturality h

theorem blowUpNatTrans_app_comp (U : X.affineOpens) :
    (I.blowUpNatTrans).app U ≫ (projectiveBundleNatTrans I.toModules).app U =
      (affineBlowUpNatTrans I).app U := by
  change I.blowUpChart U ≫ affineProjectiveBundle.π _ _ ≫ _ = _
  refine (Category.assoc _ _ _).symm.trans ?_
  rw [blowUpChart_π]
  exact (affineBlowUpNatTrans_app I U).symm

/-- **The closed immersion of the blow-up into the projective bundle** `Bl_I X ⟶ P(I)` over `X`
[Sta, Tag 02NS], glued from the charts `blowUpChart`. -/
noncomputable def blowUpToProjectiveBundle : I.blowUp ⟶ I.toModules.projectiveBundle :=
  colimMap I.blowUpNatTrans

theorem blowUpToProjectiveBundle_π :
    I.blowUpToProjectiveBundle ≫ I.toModules.projectiveBundleπ = I.blowUpπ := by
  change colimMap I.blowUpNatTrans ≫ (projectiveBundleGluingData I.toModules).toBase =
    (relativeGluingDataOf I (affineBlowUpNatTrans_equifibered I)).toBase
  refine colimit.hom_ext fun U => ?_
  rw [ι_colimMap_assoc]
  erw [Scheme.Cover.RelativeGluingData.ι_toBase, Scheme.Cover.RelativeGluingData.ι_toBase]
  erw [← Category.assoc, I.blowUpNatTrans_app_comp U]
  rfl

theorem isClosedImmersion_blowUpToProjectiveBundle :
    IsClosedImmersion I.blowUpToProjectiveBundle := by
  refine IsZariskiLocalAtTarget.of_openCover
    (projectiveBundleGluingData I.toModules).cover fun (U : X.affineOpens) => ?_
  have h₁ := (relativeGluingDataOf I
    (affineBlowUpNatTrans_equifibered I)).isPullback_natTrans_ι_toBase U
  have h₂ := (projectiveBundleGluingData I.toModules).isPullback_natTrans_ι_toBase U
  have hsq : IsPullback (I.blowUpChart U)
      (colimit.ι (relativeGluingDataOf I (affineBlowUpNatTrans_equifibered I)).functor U)
      (colimit.ι (projectiveBundleGluingData I.toModules).functor U)
      I.blowUpToProjectiveBundle := by
    refine IsPullback.of_right (h₁₂ := (projectiveBundleGluingData I.toModules).natTrans.app U)
      (h₂₂ := (projectiveBundleGluingData I.toModules).toBase)
      (v₁₃ := X.directedAffineCover.f U) ?_ (by exact (ι_colimMap I.blowUpNatTrans U).symm) h₂
    have e₁ : I.blowUpChart U ≫ (projectiveBundleGluingData I.toModules).natTrans.app U =
        (relativeGluingDataOf I (affineBlowUpNatTrans_equifibered I)).natTrans.app U :=
      I.blowUpNatTrans_app_comp U
    have e₂ : I.blowUpToProjectiveBundle ≫ (projectiveBundleGluingData I.toModules).toBase =
        (relativeGluingDataOf I (affineBlowUpNatTrans_equifibered I)).toBase :=
      I.blowUpToProjectiveBundle_π
    exact h₁.of_iso (Iso.refl _) (Iso.refl _) (Iso.refl _) (Iso.refl _)
      ((Category.comp_id _).trans (e₁.symm.trans (Category.id_comp _).symm))
      ((Category.comp_id _).trans (Category.id_comp _).symm)
      ((Category.comp_id _).trans (Category.id_comp _).symm)
      ((Category.comp_id _).trans (e₂.symm.trans (Category.id_comp _).symm))
  have := I.isClosedImmersion_blowUpChart U
  exact (MorphismProperty.arrow_mk_iso_iff @IsClosedImmersion
    (Arrow.isoMk (f := Arrow.mk (I.blowUpChart U))
      (g := Arrow.mk ((projectiveBundleGluingData I.toModules).cover.pullbackHom
        I.blowUpToProjectiveBundle U)) hsq.flip.isoPullback (Iso.refl _) (by
      simp only [Scheme.Cover.pullbackHom, Iso.refl_hom]
      exact hsq.flip.isoPullback_hom_snd))).mp this

end Scheme.IdealSheafData

/-- A projective morphism composed with an isomorphism on the source is projective. -/
theorem IsProjective.isIso_comp {X X' Y : Scheme.{u}} (e : X' ⟶ X) [IsIso e] (f : X ⟶ Y)
    [hf : IsProjective f] : IsProjective (e ≫ f) := by
  obtain ⟨E, hE, hE', i, hi, hif⟩ := hf.exists_isClosedImmersion
  exact ⟨⟨E, hE, hE', e ≫ i, inferInstance, by rw [Category.assoc, hif]⟩⟩

/-- **A blow-up of a locally Noetherian scheme is projective** [Sta, Tag 02NS]: it is a closed
subscheme of the projective bundle `P(I)` of its ideal sheaf (`blowUpToProjectiveBundle`), which is
quasi-coherent of finite type (`isFinitePresentation_toModules`). -/
theorem Scheme.IdealSheafData.isProjective_blowUpπ [IsLocallyNoetherian X] :
    IsProjective I.blowUpπ := by
  obtain ⟨σ, hσ⟩ := I.isFinitePresentation_toModules.exists_quasicoherentData
  have : I.toModules.IsQuasicoherent := σ.isQuasicoherent
  have : SheafOfModules.IsFiniteType.{u} I.toModules := by
    constructor
    refine ⟨σ.localGeneratorsData, ?_⟩
    constructor
    intro i
    exact (hσ.isFinite_presentation i).isFiniteType_generators
  exact ⟨⟨I.toModules, inferInstance, inferInstance, I.blowUpToProjectiveBundle,
    I.isClosedImmersion_blowUpToProjectiveBundle, I.blowUpToProjectiveBundle_π⟩⟩

end AlgebraicGeometry
