/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.BlowUp.Transform.Basic
public import Hironaka.Manifold.IdealSheaf.Basic
import Hironaka.Analytic.Rueckert.Basic
import Hironaka.Manifold.BlowUp.Divisor
import Hironaka.Manifold.BlowUp.Transform.Division
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.Germ.CoordDerivChart
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.IdealSheaf.Pullback
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Topology.Algebra.Module.PerfectSpace

/-!
# The quotient `I_F^{-m} π⁻¹(I)` exists; the birational transform of a marked ideal

The exceptional ideal `I_F = π^*I_Y` (`hY.idealSheaf.pullback π h.contMDiff`) is the ideal sheaf of
the
exceptional divisor `F = π⁻¹(Y)`: in a blow-up chart of index `i` its stalk is generated by the
scaling coordinate `u_i`, and off `F` it is the unit ideal (`isIdealSheafOf_exceptionalIdealSheaf`,
`stalkIdeal_exceptionalIdealSheaf_eq_span_coord`, `stalkIdeal_exceptionalIdealSheaf_of_notMem`:
the results of `Hironaka.Manifold.BlowUp.Divisor` on the pullback of the ideal sheaf of the
centre, applied to `I_Y`).

If the order of `I` along the centre `Y` is at least `m`, the total transform `π⁻¹(I)` lies in
`I_F^m` (`totalTransform_le_pow_exceptional`; stalkwise, `I_a ⊆ I_{Y,a}^m` maps to
`(π^*I)_{a'} ⊆ (π^*I_Y)^m_{a'}`, and off the exceptional divisor `I_F` is the unit ideal), and the
quotient, specified stalkwise by the colon ideals `(π⁻¹(I)_{a'} : I_{F,a'}^m)`
(`IdealSheaf.IsDivExceptional`), exists as a locally finitely generated ideal sheaf
(`exists_isDivExceptional`), uniquely (`IsDivExceptional.unique`). This is the division of the
total transform by a power of the ideal of the exceptional divisor in Hironaka's weak transform
[Hir64, Ch. 0, §5, p. 142], in Bierstone–Milman's [BM97, Remark 1.8] and in Kollár's birational
transform of a marked ideal [Kol07, Definition 60, (60.1)]. The local generators are Kollár's
`u_i^{-m}(f ∘ π)` [Kol07, Definition 60, (60.3)]: on a blow-up chart `Φ` of index `i`, `f_j ∘ π`
(the pulled-back local generators `f_j` of `I`) is divisible by `u_i^m` as a germ at every point
of the exceptional divisor `{u_i = 0}`, so the iterated canonical quotient of
`Hironaka.Manifold.BlowUp.Transform.Division` gives analytic sections `g_j` on the chart with
`u_i^m g_j = f_j ∘ π`; at a point of the exceptional divisor the colon `(span(u_i^m g_j) : u_i^m)`
is `span(g_j)` because the stalk is a domain (it is isomorphic to the ring of convergent power
series) and `u_i ≠ 0`, and off it `u_i` is a unit, so the colon by the unit ideal is
`span(u_i^m g_j) = span(g_j)`. The exponent is allowed to vary with the point as long as it is
locally constant on the exceptional divisor, so that the same lemma serves the birational
transform of a marked ideal (constant `m`, here) and Hironaka's weak transform (the generic order
along each component of the centre, `Hironaka.Manifold.BlowUp.Transform.Weak`). The birational
transform `MarkedIdealSheaf.birationalTransform` has the colon stalks whenever `m ≤ ν_Y(I)`
(`isDivExceptional_birationalTransform`) and keeps the marking (`birationalTransform_m`); in a
blow-up chart the quotient's stalk is spanned by any germs `g_j` with `u_i^m g_j = f_j ∘ π`,
whatever the generators (`IsDivExceptional.stalkIdeal_eq_span`).
-/

public section

open TopologicalSpace Opposite CategoryTheory Filter Topology IsLocalRing
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

section Order

variable {X : TopCat} {𝒪 : TopCat.Sheaf CommRingCat X}

/-- `ν_{D,a}(J) ≥ p` iff `J_a ⊆ D_a^p`: the order along `D` is the largest `p` with `J_a ⊆ D_a^p`
(the set of such `p` is downward closed) [BM97, §3]. -/
theorem IdealSheaf.le_ordAlongIdeal_iff (D J : IdealSheaf 𝒪) (a : X) (p : ℕ) :
    (p : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D J a ↔ J.stalkIdeal a ≤ D.stalkIdeal a ^ p := by
  constructor
  · intro hp
    by_contra hcon
    have hlt : ∀ q : ℕ, J.stalkIdeal a ≤ D.stalkIdeal a ^ q → q < p := fun q hq => by
      by_contra hqp
      exact hcon (hq.trans (Ideal.pow_le_pow_right (not_lt.mp hqp)))
    have hp1 : 1 ≤ p := hlt 0 (by rw [pow_zero, Ideal.one_eq_top]; exact le_top)
    have h1 : IdealSheaf.ordAlongIdeal D J a ≤ ((p - 1 : ℕ) : ℕ∞) := by
      refine iSup₂_le fun q hq => ?_
      exact_mod_cast Nat.le_sub_one_of_lt (hlt q hq)
    have h2 : p ≤ p - 1 := by exact_mod_cast hp.trans h1
    omega
  · intro h
    exact le_iSup₂ (f := fun (q : ℕ) (_ : J.stalkIdeal a ≤ D.stalkIdeal a ^ q) => (q : ℕ∞)) p h

end Order

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {Y : Set M}
  {c : ℕ}

/-- A coordinate germ of a chart is nonzero: its own coordinate derivative is `1`. -/
theorem coord_ne_zero {Φ : OpenPartialHomeomorph M E} (hΦ : Φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {b : M}
    (hb : b ∈ Φ.source) (i : Fin n) : coord E ψ Φ hΦ hb i ≠ 0 := by
  intro h0
  have h1 := coordDerivStalk_coord E ψ Φ hΦ hb i i
  rw [h0, map_zero, ite_eq_left rfl, map_one] at h1
  exact zero_ne_one h1

/-- The stalk of the structure sheaf is a domain: it is isomorphic to the ring of convergent power
series. -/
theorem isDomain_stalk (ψ : E ≃L[𝕜] (Fin n → 𝕜)) {Φ : OpenPartialHomeomorph M E}
    (hΦ : Φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {b : M} (hb : b ∈ Φ.source) :
    IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk b) :=
  MulEquiv.isDomain (Analytic.Conv 𝕜 n) (taylorEquivConv E ψ Φ hb hΦ).toMulEquiv

variable {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M']
  [T2Space M'] [SecondCountableTopology M'] {π : M' → M}

/-! ### The exceptional ideal -/

/-- `I_F = π^*I_Y` is the ideal sheaf of the exceptional divisor `F = π⁻¹(Y)`. -/
theorem isIdealSheafOf_exceptionalIdealSheaf (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) :
    IsIdealSheafOf ψ (π ⁻¹' Y) 1 (hY.idealSheaf.pullback π h.contMDiff) :=
  h.isIdealSheafOf_pullback hY hY.isIdealSheafOf_idealSheaf

/-- In a blow-up chart of index `i` the stalk of `I_F` is generated by the scaling coordinate
`u_i`. -/
theorem stalkIdeal_exceptionalIdealSheaf_eq_span_coord (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} {i : Fin c}
    {Φ : OpenPartialHomeomorph M' E} (hφ : IsAdaptedChart ψ Y φ σ) (hΦ : IsBlowUpChart ψ π φ σ i Φ)
    {p : M'} (hp : p ∈ Φ.source) :
    (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal p =
      Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i)} :=
  h.stalkIdeal_pullback_eq_span_coord hY.isIdealSheafOf_idealSheaf hφ hΦ hp

/-- Off the exceptional divisor the stalk of `I_F` is the unit ideal. -/
theorem stalkIdeal_exceptionalIdealSheaf_of_notMem (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) {p : M'} (hp : π p ∉ Y) :
    (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal p = ⊤ :=
  (isIdealSheafOf_exceptionalIdealSheaf hY h).stalkIdeal_of_notMem hp

/-! ### The quotient `I_F^{-m} π⁻¹(I)` -/

/-- Stalkwise: if `ν_Y(I) ≥ m` at `π a'` then `π⁻¹(I)_{a'} ⊆ I_{F,a'}^m`. -/
theorem IsBlowUp.totalTransform_stalkIdeal_le (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) (I : IdealSheaf (structureSheaf 𝕜 E M)) {m : ℕ} {a' : M'}
    (hm : (m : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf I (π a')) :
    (I.pullback π h.contMDiff).stalkIdeal a' ≤
      (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal a' ^ m := by
  rw [IdealSheaf.stalkIdeal_pullback,
    IdealSheaf.stalkIdeal_pullback, ← Ideal.map_pow]
  exact Ideal.map_mono ((IdealSheaf.le_ordAlongIdeal_iff _ _ _ _).mp hm)

/-- If `ν_Y(I) ≥ m` along `Y` then `π⁻¹(I) ⊆ I_F^m` [Hir64, Ch. 0, §5, p. 142]. -/
theorem totalTransform_le_pow_exceptional (hY : IsClosedSubmanifold ψ Y c) (h : IsBlowUp ψ Y c π)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) {m : ℕ}
    (hm : ∀ a ∈ Y, (m : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf I a) :
    I.pullback π h.contMDiff ≤ hY.idealSheaf.pullback π h.contMDiff ^ m := by
  rw [IdealSheaf.le_def]
  intro a'
  rw [IdealSheaf.stalkIdeal_pow]
  by_cases ha : π a' ∈ Y
  · exact h.totalTransform_stalkIdeal_le hY I (hm _ ha)
  · rw [stalkIdeal_exceptionalIdealSheaf_of_notMem hY h ha, Ideal.top_pow]
    exact le_top

omit [IsManifold 𝓘(𝕜, E) ω M'] [T2Space M'] [SecondCountableTopology M'] in
/-- The scaling coordinate of a blow-up chart is a unit off the exceptional divisor. -/
theorem IsBlowUpChart.isUnit_coord_of_notMem {φ : OpenPartialHomeomorph M E}
    {σ : Fin c ↪ Fin n} {i : Fin c} {Φ : OpenPartialHomeomorph M' E} (hφ : IsAdaptedChart ψ Y φ σ)
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) {p : M'} (hp : p ∈ Φ.source) (hpY : π p ∉ Y) :
    IsUnit (coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i)) := by
  rw [← IsLocalRing.notMem_maximalIdeal, mem_maximalIdeal_iff_eval, eval_coord]
  exact fun h0 => hpY ((IsBlowUpChart.mem_preimage_iff hφ hΦ hp).mpr h0)

/-- The colon stalks `(π⁻¹(I)_{a'} : I_{F,a'}^{m a'})` have local generators, for any exponent `m`
that is locally constant on the exceptional divisor and at most the order of `I` along the
centre: the divided generators `u_i^{-m}(f_j ∘ π)` on a blow-up chart
[Kol07, Definition 60, (60.3)], the pulled-back generators off the exceptional divisor. -/
theorem hasLocalGenerators_colon (hY : IsClosedSubmanifold ψ Y c) (h : IsBlowUp ψ Y c π)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (m : M' → ℕ)
    (hm : ∀ a', π a' ∈ Y → ((m a' : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf I (π a'))
    (hloc : ∀ a', π a' ∈ Y → ∀ᶠ b in 𝓝 a', π b ∈ Y → m b = m a') :
    IdealSheaf.HasLocalGenerators (𝒪 := structureSheaf 𝕜 E M') fun a' =>
      ((I.pullback π h.contMDiff).stalkIdeal a').colon
        ↑((hY.idealSheaf.pullback π h.contMDiff).stalkIdeal a' ^ m a') := by
  intro a'
  obtain ⟨V, hV, k, f, -, hf⟩ := I.exists_generators (π a')
  have hπc : Continuous π := h.contMDiff.continuous
  by_cases ha : π a' ∈ Y
  · obtain ⟨φ, σ, haφ, hφ⟩ := hY.exists_adaptedChart (π a') ha
    obtain ⟨i, Φ, hΦ, ha'Φ⟩ := h.cover φ σ hφ a' haφ
    obtain ⟨T, hT, hTo, ha'T⟩ := mem_nhds_iff.mp (hloc a' ha)
    set W : Opens M' := ⟨Φ.source ∩ π ⁻¹' (V : Set M) ∩ T,
      (Φ.open_source.inter (V.2.preimage hπc)).inter hTo⟩ with hWdef
    have ha'W : a' ∈ W := ⟨⟨ha'Φ, hV⟩, ha'T⟩
    have hWsub : (W : Set M') ⊆ Φ.source := fun x hx => hx.1.1
    have hWV : ∀ x ∈ W, x ∈ preimageOpens π h.contMDiff V := fun x hx => hx.1.2
    set N : Set (Fin n → 𝕜) := ψ '' (Φ '' W) with hNdef
    have hNo : IsOpen N := ψ.isOpenMap _ (Φ.isOpen_image_of_subset_source W.2 hWsub)
    have hmemN : ∀ x ∈ W, ψ (Φ x) ∈ N := fun x hx => ⟨Φ x, ⟨x, hx, rfl⟩, rfl⟩
    -- the chart inverse on `N`
    have h2 : ContMDiffOn 𝓘(𝕜, Fin n → 𝕜) 𝓘(𝕜, E) ω (fun w => Φ.symm (ψ.symm w)) N := by
      refine (contMDiffOn_symm_of_mem_maximalAtlas hΦ.mem_maximalAtlas).comp
        ((ψ.symm : (Fin n → 𝕜) →L[𝕜] E).contMDiff.contMDiffOn) ?_
      rintro _ ⟨_, ⟨x, hx, rfl⟩, rfl⟩
      change ψ.symm (ψ (Φ x)) ∈ Φ.target
      rw [ψ.symm_apply_apply]
      exact Φ.map_source (hWsub hx)
    have hinv : ∀ x ∈ W, Φ.symm (ψ.symm (ψ (Φ x))) = x := fun x hx => by
      rw [ψ.symm_apply_apply, Φ.left_inv (hWsub hx)]
    -- the pulled-back generators read on the chart
    set F : Fin k → (Fin n → 𝕜) → 𝕜 := fun j w =>
      extendSection 𝕜 E (comapSection π h.contMDiff (f j)) (Φ.symm (ψ.symm w)) with hFdef
    have hFan : ∀ j, AnalyticOnNhd 𝕜 (F j) N := by
      intro j
      have h3 : ContMDiffOn 𝓘(𝕜, Fin n → 𝕜) 𝓘(𝕜) ω (F j) N := by
        refine (contMDiffOn_extendSection (comapSection π h.contMDiff (f j))).comp h2 ?_
        rintro _ ⟨_, ⟨x, hx, rfl⟩, rfl⟩
        change Φ.symm (ψ.symm (ψ (Φ x))) ∈ (preimageOpens π h.contMDiff V : Set M')
        rw [hinv x hx]
        exact hWV x hx
      exact fun w hw =>
        ((contMDiffOn_iff_contDiffOn.mp h3).contDiffAt (hNo.mem_nhds hw)).analyticAt
    -- divisibility by `u_i^m` near the points of the exceptional divisor
    have hdiv : ∀ j, ∀ v ∈ N, v (σ i) = 0 → ∃ N' : Set (Fin n → 𝕜), IsOpen N' ∧ v ∈ N' ∧
        ∃ G : (Fin n → 𝕜) → 𝕜, AnalyticOnNhd 𝕜 G N' ∧
          ∀ w ∈ N', F j w = w (σ i) ^ m a' * G w := by
      intro j v hv hvk
      obtain ⟨_, ⟨b, hbW, rfl⟩, rfl⟩ := hv
      have hbF : π b ∈ Y := (IsBlowUpChart.mem_preimage_iff hφ hΦ (hWsub hbW)).mpr hvk
      have hmb : m b = m a' := hT hbW.2 hbF
      have hmem : (structureSheaf 𝕜 E M').presheaf.germ (preimageOpens π h.contMDiff V) b
          (hWV b hbW) (comapSection π h.contMDiff (f j)) ∈
            Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas (hWsub hbW) (σ i) ^ m a'} := by
        rw [← germMap_germ π h.contMDiff (hWV b hbW) (f j), ← Ideal.span_singleton_pow,
          ← stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ (hWsub hbW), ← hmb]
        refine h.totalTransform_stalkIdeal_le hY I (hm b hbF) ?_
        rw [IdealSheaf.stalkIdeal_pullback]
        exact Ideal.mem_map_of_mem _
          (by rw [hf (π b) (hWV b hbW)]; exact Ideal.subset_span ⟨j, rfl⟩)
      exact exists_eq_pow_mul_of_mem_span_pow_coord hΦ.mem_maximalAtlas (hWsub hbW) (σ i) (m a')
        (hWV b hbW) (comapSection π h.contMDiff (f j)) hmem
    -- the divided generators as functions on the chart, then as sections over `W`
    have hQ := fun j => coordQuot_iterate_spec hNo (σ i) (m a') (F j) (hFan j) (hdiv j)
    set Q : Fin k → (Fin n → 𝕜) → 𝕜 := fun j => (coordQuot (σ i))^[m a'] (F j) with hQdef
    have hQW : ∀ j, ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜) ω (fun b => Q j (ψ (Φ b))) W := by
      intro j
      have h1 : ContMDiffOn 𝓘(𝕜, Fin n → 𝕜) 𝓘(𝕜) ω (Q j) N :=
        contMDiffOn_iff_contDiffOn.mpr ((hQ j).1.contDiffOn hNo.uniqueDiffOn)
      have h3 : ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜, Fin n → 𝕜) ω (fun b => ψ (Φ b)) W :=
        (ψ : E →L[𝕜] (Fin n → 𝕜)).contMDiff.comp_contMDiffOn
          ((contMDiffOn_of_mem_maximalAtlas hΦ.mem_maximalAtlas).mono hWsub)
      exact h1.comp h3 fun b hb => hmemN b hb
    refine ⟨W, ha'W, Fin k, inferInstance,
      fun j => sectionOfContMDiffOn (fun b => Q j (ψ (Φ b))) W (hQW j), fun b hb => ?_⟩
    change Submodule.colon ((I.pullback π h.contMDiff).stalkIdeal b)
      ↑((hY.idealSheaf.pullback π h.contMDiff).stalkIdeal b ^ m b) = _
    have hbΦ : b ∈ Φ.source := hWsub hb
    -- `u_i^m · g_j = f_j ∘ π` in the stalk at `b`
    have hkey : ∀ j, coord E ψ Φ hΦ.mem_maximalAtlas hbΦ (σ i) ^ m a' *
        (structureSheaf 𝕜 E M').presheaf.germ W b hb
          (sectionOfContMDiffOn (fun b => Q j (ψ (Φ b))) W (hQW j)) =
        germMap π h.contMDiff b
          ((structureSheaf 𝕜 E M).presheaf.germ V (π b) (hWV b hb) (f j)) := by
      intro j
      rw [germMap_germ π h.contMDiff (hWV b hb) (f j)]
      apply stalkToGerm_injective 𝓘(𝕜, E) ω M' b
      rw [map_mul, map_pow, stalkToGerm_coord, stalkToGerm_germ_sectionOfContMDiffOn,
        stalkToGerm_structureSheaf_germ, ← Germ.coe_pow, ← Germ.coe_mul, Germ.coe_eq]
      filter_upwards [W.2.mem_nhds hb] with x hx
      rw [Pi.mul_apply, Pi.pow_apply, extendSection_of_mem 𝕜 E _ (hWsub hx)]
      change (ψ (Φ x) (σ i)) ^ m a' * (coordQuot (σ i))^[m a'] (F j) (ψ (Φ x)) = _
      rw [(hQ j).2 (ψ (Φ x)) (hmemN x hx)]
      change extendSection 𝕜 E (comapSection π h.contMDiff (f j)) (Φ.symm (ψ.symm (ψ (Φ x)))) = _
      rw [hinv x hx]
    have hItot : (I.pullback π h.contMDiff).stalkIdeal b = Ideal.span (Set.range fun j =>
        coord E ψ Φ hΦ.mem_maximalAtlas hbΦ (σ i) ^ m a' *
          (structureSheaf 𝕜 E M').presheaf.germ W b hb
            (sectionOfContMDiffOn (fun b => Q j (ψ (Φ b))) W (hQW j))) := by
      rw [totalTransform_stalkIdeal_eq_span h I hf (hWV b hb)]
      exact congrArg Ideal.span (congrArg Set.range (funext fun j => (hkey j).symm))
    by_cases hbF : π b ∈ Y
    · have hmb : m b = m a' := hT hb.2 hbF
      rw [hItot, stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hbΦ,
        Ideal.span_singleton_pow, Submodule.colon_span, hmb]
      have := isDomain_stalk ψ hΦ.mem_maximalAtlas hbΦ
      exact Ideal.colon_span_range_pow_mul (coord_ne_zero hΦ.mem_maximalAtlas hbΦ (σ i)) (m a') _
    · rw [hItot, stalkIdeal_exceptionalIdealSheaf_of_notMem hY h hbF, Ideal.top_pow,
        Submodule.top_coe, Submodule.colon_univ]
      exact Ideal.span_range_unit_mul ((IsBlowUpChart.isUnit_coord_of_notMem hφ hΦ hbΦ hbF).pow _) _
  · -- off the exceptional divisor: the pulled-back generators
    set W : Opens M' := ⟨π ⁻¹' (V : Set M) ∩ π ⁻¹' Yᶜ,
      (V.2.preimage hπc).inter (hY.isClosed.isOpen_compl.preimage hπc)⟩ with hWdef
    have hWV : W ≤ preimageOpens π h.contMDiff V := fun x hx => hx.1
    refine ⟨W, ⟨hV, ha⟩, Fin k, inferInstance, fun j =>
      (structureSheaf 𝕜 E M').presheaf.map (homOfLE hWV).op (comapSection π h.contMDiff (f j)),
      fun b hb => ?_⟩
    change Submodule.colon ((I.pullback π h.contMDiff).stalkIdeal b)
      ↑((hY.idealSheaf.pullback π h.contMDiff).stalkIdeal b ^ m b) = _
    rw [stalkIdeal_exceptionalIdealSheaf_of_notMem hY h hb.2, Ideal.top_pow, Submodule.top_coe,
      Submodule.colon_univ, totalTransform_stalkIdeal_eq_span h I hf hb.1,
      IdealSheaf.range_germ_map]
    exact congrArg Ideal.span (congrArg Set.range (funext fun j =>
      germMap_germ π h.contMDiff hb.1 (f j)))

/-- The quotient `I_F^{-m} π⁻¹(I)` exists as a locally finitely generated ideal sheaf when
`ν_Y(I) ≥ m` along `Y` ([Hir64, Ch. 0, §5, p. 142]; [BM97, Remark 1.8]). -/
theorem exists_isDivExceptional (hY : IsClosedSubmanifold ψ Y c) (h : IsBlowUp ψ Y c π)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) {m : ℕ}
    (hm : ∀ a ∈ Y, (m : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf I a) :
    ∃ J' : IdealSheaf (structureSheaf 𝕜 E M'), IdealSheaf.IsDivExceptional
      (I.pullback π h.contMDiff) (hY.idealSheaf.pullback π h.contMDiff) (fun _ => m) J' :=
  ⟨IdealSheaf.ofStalks _ _ (hasLocalGenerators_colon hY h I (fun _ => m) (fun _ ha' => hm _ ha')
      fun _ _ => Eventually.of_forall fun _ _ => rfl),
    fun a' => IdealSheaf.stalkIdeal_ofStalks _ _ a'⟩

omit [IsManifold 𝓘(𝕜, E) ω M'] [T2Space M'] [SecondCountableTopology M'] in
/-- The quotient is determined by its stalks. -/
theorem IsDivExceptional.unique {Itot IF : IdealSheaf (structureSheaf 𝕜 E M')} {m : M' → ℕ}
    {J₁ J₂ : IdealSheaf (structureSheaf 𝕜 E M')} (h₁ : IdealSheaf.IsDivExceptional Itot IF m J₁)
    (h₂ : IdealSheaf.IsDivExceptional Itot IF m J₂) : J₁ = J₂ :=
  IdealSheaf.ext fun a => (h₁ a).trans (h₂ a).symm

/-- The birational transform of `(I, m)`, `m ≤ ν_Y(I)`, has the colon stalks
[Kol07, Definition 60, (60.1)]. -/
theorem isDivExceptional_birationalTransform (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) (J : MarkedIdealSheaf (structureSheaf 𝕜 E M))
    (hm : ∀ a ∈ Y, (J.m : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J.I a) :
    IdealSheaf.IsDivExceptional (J.I.pullback π h.contMDiff)
      (hY.idealSheaf.pullback π h.contMDiff) (fun _ => J.m)
      (MarkedIdealSheaf.birationalTransform hY h J).I := by
  have hex := exists_isDivExceptional hY h J.I hm
  unfold MarkedIdealSheaf.birationalTransform
  dsimp only
  rw [dite_eq_left hex]
  exact Classical.choose_spec hex

/-- The birational transform keeps the marking. -/
theorem birationalTransform_m (hY : IsClosedSubmanifold ψ Y c) (h : IsBlowUp ψ Y c π)
    (J : MarkedIdealSheaf (structureSheaf 𝕜 E M)) :
    (MarkedIdealSheaf.birationalTransform hY h J).m = J.m := rfl

/-- In a blow-up chart of index `i`, the quotient `I_F^{-m} π⁻¹(I)` is generated by germs `g_j`
with `u_i^m g_j = f_j ∘ π`, for any local generators `f_j` of `I`, whatever the generators
[Kol07, Definition 60, (60.3)]. -/
theorem IsDivExceptional.stalkIdeal_eq_span (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) (I : IdealSheaf (structureSheaf 𝕜 E M)) {m : ℕ}
    (hm : ∀ a ∈ Y, (m : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf I a)
    {J' : IdealSheaf (structureSheaf 𝕜 E M')}
    (hJ' : IdealSheaf.IsDivExceptional (I.pullback π h.contMDiff)
      (hY.idealSheaf.pullback π h.contMDiff) (fun _ => m) J')
    {U : Opens M} {k : ℕ} {f : Fin k → (structureSheaf 𝕜 E M).presheaf.obj (op U)}
    (hgen : ∀ b (hb : b ∈ U), I.stalkIdeal b =
      Ideal.span (Set.range fun j => (structureSheaf 𝕜 E M).presheaf.germ U b hb (f j)))
    {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} {i : Fin c}
    {Φ : OpenPartialHomeomorph M' E} (hφ : IsAdaptedChart ψ Y φ σ) (hΦ : IsBlowUpChart ψ π φ σ i Φ)
    {a' : M'} (ha' : a' ∈ Φ.source) (hU : π a' ∈ U) :
    ∃ g : Fin k → (structureSheaf 𝕜 E M').presheaf.stalk a',
      (∀ j, coord E ψ Φ hΦ.mem_maximalAtlas ha' (σ i) ^ m * g j =
        germMap π h.contMDiff a' ((structureSheaf 𝕜 E M).presheaf.germ U (π a') hU (f j))) ∧
      J'.stalkIdeal a' = Ideal.span (Set.range g) := by
  have hItot := totalTransform_stalkIdeal_eq_span h I hgen hU
  by_cases haF : π a' ∈ Y
  · -- every `f_j ∘ π` is a multiple of `u_i^m`
    have hmem : ∀ j, ∃ g, coord E ψ Φ hΦ.mem_maximalAtlas ha' (σ i) ^ m * g =
        germMap π h.contMDiff a' ((structureSheaf 𝕜 E M).presheaf.germ U (π a') hU (f j)) := by
      intro j
      have h1 : germMap π h.contMDiff a'
          ((structureSheaf 𝕜 E M).presheaf.germ U (π a') hU (f j)) ∈
            Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas ha' (σ i) ^ m} := by
        rw [← Ideal.span_singleton_pow,
          ← stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ ha']
        refine h.totalTransform_stalkIdeal_le hY I (hm _ haF) ?_
        rw [hItot]
        exact Ideal.subset_span ⟨j, rfl⟩
      obtain ⟨g, hg⟩ := Ideal.mem_span_singleton'.mp h1
      exact ⟨g, by rw [mul_comm]; exact hg⟩
    choose g hg using hmem
    refine ⟨g, hg, ?_⟩
    rw [hJ' a', hItot, stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ ha',
      Ideal.span_singleton_pow, Submodule.colon_span]
    have := isDomain_stalk ψ hΦ.mem_maximalAtlas ha'
    rw [← Ideal.colon_span_range_pow_mul (coord_ne_zero hΦ.mem_maximalAtlas ha' (σ i)) m g]
    exact congrArg (fun S : Ideal _ => Submodule.colon S _)
      (congrArg Ideal.span (congrArg Set.range (funext fun j => (hg j).symm)))
  · have hu := IsBlowUpChart.isUnit_coord_of_notMem hφ hΦ ha' haF
    obtain ⟨u, hu⟩ := hu
    refine ⟨fun j => (↑u⁻¹ : (structureSheaf 𝕜 E M').presheaf.stalk a') ^ m *
      germMap π h.contMDiff a' ((structureSheaf 𝕜 E M).presheaf.germ U (π a') hU (f j)),
      fun j => ?_, ?_⟩
    · rw [← hu, ← mul_assoc, ← mul_pow, Units.mul_inv, one_pow, one_mul]
    · rw [hJ' a', stalkIdeal_exceptionalIdealSheaf_of_notMem hY h haF, Ideal.top_pow,
        Submodule.top_coe, Submodule.colon_univ, hItot]
      exact (Ideal.span_range_unit_mul ((Units.isUnit u⁻¹).pow m) _).symm

end Manifold
