/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.BlowUp.Lift
public import Hironaka.Manifold.StructureSheaf
import Hironaka.Manifold.Germ.ChartTransport
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Division by a power of a coordinate, on a chart and in a stalk

The quotient `u^{-m} F` of an analytic function `F` by the `m`-th power of a coordinate `u = x_k`
is a well-defined analytic function on the whole chart when `F` is divisible by `x_k^m` near
every point of the hyperplane `{x_k = 0}`: it is the `m`-fold iterate of the canonical coordinate
quotient `coordQuot` of `Hironaka.Manifold.BlowUp.Lift` (`F/x_k` off the hyperplane, `∂_k F`
on it), and `x_k^m · (u^{-m} F) = F` (`coordQuot_iterate_spec`). The divisibility hypothesis is
read off a stalk: a germ lying in the `m`-th power of the ideal generated by a coordinate germ of
a chart is, near the point, the product of the `m`-th power of the coordinate function with an
analytic function (`exists_eq_pow_mul_of_mem_span_pow_coord`). Two facts about ideals close the
file: in a domain, the colon of the ideal spanned by the `a^m g_j` by `a^m` is the ideal spanned
by the `g_j` (`Ideal.colon_span_range_pow_mul`: the quotient is independent of the generators),
and multiplying generators by a unit does not change the ideal (`Ideal.span_range_unit_mul`).

These are the tools for dividing the total transform of an ideal by a power of the exceptional
divisor, as in Hironaka's weak transform [Hir64, Ch. 0, §5, p. 142] and Kollár's chart formula
for the birational transform [Kol07, Definition 60, (60.3)]; they are used in
`Hironaka.Manifold.BlowUp.Transform.Colon`.
-/

public section

open TopologicalSpace Opposite CategoryTheory Filter Topology
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {n : ℕ}

/-! ### Iterated coordinate division on an open set -/

/-- If `F = x_k · Q` on an open set with `Q` analytic, the canonical quotient of `F` by `x_k` is
`Q` there. -/
theorem coordQuot_eq_of_eq_mul (k : Fin n) {F Q : (Fin n → 𝕜) → 𝕜} {U : Set (Fin n → 𝕜)}
    (hU : IsOpen U) (hQ : AnalyticOnNhd 𝕜 Q U) (h : ∀ y ∈ U, F y = y k * Q y) {y : Fin n → 𝕜}
    (hy : y ∈ U) : coordQuot k F y = Q y := by
  by_cases hyk : y k = 0
  · rw [coordQuot_of_eq k F hyk]
    exact eq_fderiv_of_eq_mul k hU hQ h hy hyk
  · rw [coordQuot_of_ne k F hyk, h y hy, mul_div_cancel_left₀ _ hyk]

/-- The coordinate function `x_k` is analytic. -/
theorem analyticAt_apply_coord (k : Fin n) (w : Fin n → 𝕜) :
    AnalyticAt 𝕜 (fun v : Fin n → 𝕜 => v k) w :=
  (ContinuousLinearMap.proj (R := 𝕜) (φ := fun _ : Fin n => 𝕜) k).analyticAt w

/-- If `F` is analytic on the open set `N` and, near every point of `N` on the hyperplane
`{x_k = 0}`, `F` is `x_k^m` times an analytic function, then the `m`-fold canonical quotient
`x_k^{-m} F` is analytic on `N` and `x_k^m · (x_k^{-m} F) = F` on `N`. -/
theorem coordQuot_iterate_spec {N : Set (Fin n → 𝕜)} (hN : IsOpen N) (k : Fin n) :
    ∀ (m : ℕ) (F : (Fin n → 𝕜) → 𝕜), AnalyticOnNhd 𝕜 F N →
      (∀ v ∈ N, v k = 0 → ∃ N' : Set (Fin n → 𝕜), IsOpen N' ∧ v ∈ N' ∧
        ∃ G : (Fin n → 𝕜) → 𝕜, AnalyticOnNhd 𝕜 G N' ∧ ∀ w ∈ N', F w = w k ^ m * G w) →
      AnalyticOnNhd 𝕜 ((coordQuot k)^[m] F) N ∧
        ∀ v ∈ N, v k ^ m * (coordQuot k)^[m] F v = F v
  | 0, F, hF, _ => ⟨hF, fun v _ => by simp⟩
  | m + 1, F, hF, hdiv => by
    have h0 : ∀ v ∈ N, v k = 0 → F v = 0 := fun v hv hvk => by
      obtain ⟨N', -, hvN', G, -, hG⟩ := hdiv v hv hvk
      rw [hG v hvN', hvk, zero_pow (Nat.succ_ne_zero m), zero_mul]
    have hQ : AnalyticOnNhd 𝕜 (coordQuot k F) N := analyticOnNhd_coordQuot k F hN hF h0
    have hdivQ : ∀ v ∈ N, v k = 0 → ∃ N' : Set (Fin n → 𝕜), IsOpen N' ∧ v ∈ N' ∧
        ∃ G : (Fin n → 𝕜) → 𝕜, AnalyticOnNhd 𝕜 G N' ∧
          ∀ w ∈ N', coordQuot k F w = w k ^ m * G w := by
      intro v hv hvk
      obtain ⟨N', hN'o, hvN', G, hGan, hG⟩ := hdiv v hv hvk
      refine ⟨N', hN'o, hvN', G, hGan, fun w hw => ?_⟩
      have hQan : AnalyticOnNhd 𝕜 (fun w => w k ^ m * G w) N' := fun w hw =>
        ((analyticAt_apply_coord k w).pow m).mul (hGan w hw)
      exact coordQuot_eq_of_eq_mul k hN'o hQan (fun y hy => by rw [hG y hy]; ring) hw
    obtain ⟨hQm, hQm'⟩ := coordQuot_iterate_spec hN k m (coordQuot k F) hQ hdivQ
    refine ⟨by rw [Function.iterate_succ_apply]; exact hQm, fun v hv => ?_⟩
    rw [Function.iterate_succ_apply, pow_succ, mul_comm (v k ^ m) (v k), mul_assoc, hQm' v hv,
      mul_coordQuot k F h0 hv]

/-! ### From a stalk to a chart -/

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {ψ : E ≃L[𝕜] (Fin n → 𝕜)}
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M]

/-- Reading a stalk statement on a chart: if the germ at `b` of a section `f` lies in the `m`-th
power of the ideal generated by the coordinate germ `x_k` of a chart `Φ` at `b`, then near
`ψ (Φ b)` the function `f ∘ Φ⁻¹ ∘ ψ⁻¹` is `x_k^m` times an analytic function. -/
theorem exists_eq_pow_mul_of_mem_span_pow_coord {Φ : OpenPartialHomeomorph M E}
    (hΦ : Φ ∈ maximalAtlas 𝓘(𝕜, E) ω M) {b : M} (hb : b ∈ Φ.source) (k : Fin n) (m : ℕ)
    {W : Opens M} (hbW : b ∈ W) (f : (structureSheaf 𝕜 E M).presheaf.obj (op W))
    (hs : (structureSheaf 𝕜 E M).presheaf.germ W b hbW f ∈
      Ideal.span {coord E ψ Φ hΦ hb k ^ m}) :
    ∃ N' : Set (Fin n → 𝕜), IsOpen N' ∧ ψ (Φ b) ∈ N' ∧ ∃ G : (Fin n → 𝕜) → 𝕜,
      AnalyticOnNhd 𝕜 G N' ∧
        ∀ w ∈ N', extendSection 𝕜 E f (Φ.symm (ψ.symm w)) = w k ^ m * G w := by
  obtain ⟨q, hq⟩ := Ideal.mem_span_singleton'.mp hs
  obtain ⟨h, hh, U, hbU, hU⟩ := (mem_range_stalkToGerm_iff 𝓘(𝕜, E) ω M b _).mp ⟨q, rfl⟩
  have hgerm : ∀ᶠ x in 𝓝 b, extendSection 𝕜 E f x = h x * (ψ (Φ x) k) ^ m := by
    have h1 := congrArg (stalkToGerm 𝓘(𝕜, E) ω M b) hq
    rw [map_mul, map_pow, stalkToGerm_structureSheaf_germ, stalkToGerm_coord, hh, ← Germ.coe_pow,
      ← Germ.coe_mul, Germ.coe_eq] at h1
    filter_upwards [h1, Φ.open_source.mem_nhds hb] with x hx hxs
    rw [← hx, Pi.mul_apply, Pi.pow_apply, extendSection_of_mem 𝕜 E _ hxs]
    rfl
  obtain ⟨T, hT, hTo, hbT⟩ := mem_nhds_iff.mp hgerm
  set S : Set M := T ∩ Φ.source ∩ U with hS
  have hSo : IsOpen S := (hTo.inter Φ.open_source).inter U.2
  have hbS : b ∈ S := ⟨⟨hbT, hb⟩, hbU⟩
  have hSsub : S ⊆ Φ.source := fun x hx => hx.1.2
  refine ⟨ψ '' (Φ '' S), ψ.isOpenMap _ (Φ.isOpen_image_of_subset_source hSo hSsub),
    ⟨Φ b, ⟨b, hbS, rfl⟩, rfl⟩, fun w => h (Φ.symm (ψ.symm w)), ?_, ?_⟩
  · have h2 : ContMDiffOn 𝓘(𝕜, Fin n → 𝕜) 𝓘(𝕜, E) ω (fun w => Φ.symm (ψ.symm w))
        (ψ '' (Φ '' S)) := by
      refine (contMDiffOn_symm_of_mem_maximalAtlas hΦ).comp
        ((ψ.symm : (Fin n → 𝕜) →L[𝕜] E).contMDiff.contMDiffOn) ?_
      rintro _ ⟨_, ⟨x, hx, rfl⟩, rfl⟩
      change ψ.symm (ψ (Φ x)) ∈ Φ.target
      rw [ψ.symm_apply_apply]
      exact Φ.map_source (hSsub hx)
    have hG : ContMDiffOn 𝓘(𝕜, Fin n → 𝕜) 𝓘(𝕜) ω (fun w => h (Φ.symm (ψ.symm w)))
        (ψ '' (Φ '' S)) := by
      refine hU.comp h2 ?_
      rintro _ ⟨_, ⟨x, hx, rfl⟩, rfl⟩
      change Φ.symm (ψ.symm (ψ (Φ x))) ∈ (U : Set M)
      rw [ψ.symm_apply_apply, Φ.left_inv (hSsub hx)]
      exact hx.2
    intro w hw
    exact ((contMDiffOn_iff_contDiffOn.mp hG).contDiffAt
      ((ψ.isOpenMap _ (Φ.isOpen_image_of_subset_source hSo hSsub)).mem_nhds hw)).analyticAt
  · rintro _ ⟨_, ⟨x, hx, rfl⟩, rfl⟩
    change extendSection 𝕜 E f (Φ.symm (ψ.symm (ψ (Φ x)))) =
      ψ (Φ x) k ^ m * h (Φ.symm (ψ.symm (ψ (Φ x))))
    rw [ψ.symm_apply_apply, Φ.left_inv (hSsub hx), hT hx.1.1, mul_comm]

/-! ### Two facts about ideals -/

/-- In a domain, the colon of the ideal spanned by the `a^m · g_j` by `a^m` is the ideal spanned by
the `g_j`: the quotient is independent of the generators. -/
theorem _root_.Ideal.colon_span_range_pow_mul {R : Type*} [CommRing R] [IsDomain R] {a : R}
    (ha : a ≠ 0) (m : ℕ) {ι : Type*} [Finite ι] (g : ι → R) :
    (Ideal.span (Set.range fun j => a ^ m * g j)).colon {a ^ m} = Ideal.span (Set.range g) := by
  cases nonempty_fintype ι
  ext x
  rw [Submodule.mem_colon_singleton, smul_eq_mul, Submodule.mem_span_range_iff_exists_fun,
    Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, mul_left_cancel₀ (pow_ne_zero m ha) ?_⟩
    calc a ^ m * ∑ j, c j • g j = ∑ j, c j • (a ^ m * g j) := by
          rw [Finset.mul_sum]
          exact Finset.sum_congr rfl fun j _ => by rw [smul_eq_mul, smul_eq_mul, mul_left_comm]
      _ = x * a ^ m := hc
      _ = a ^ m * x := mul_comm _ _
  · rintro ⟨c, rfl⟩
    refine ⟨c, ?_⟩
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl fun j _ => by
      rw [smul_eq_mul, smul_eq_mul, mul_assoc, mul_comm (g j)]

/-- Multiplying generators by a unit does not change the ideal they span. -/
theorem _root_.Ideal.span_range_unit_mul {R : Type*} [CommRing R] {v : R} (hv : IsUnit v)
    {ι : Type*} (g : ι → R) :
    Ideal.span (Set.range fun j => v * g j) = Ideal.span (Set.range g) := by
  refine le_antisymm (Ideal.span_le.mpr ?_) (Ideal.span_le.mpr ?_)
  · rintro _ ⟨j, rfl⟩
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, rfl⟩)
  · rintro _ ⟨j, rfl⟩
    obtain ⟨u, rfl⟩ := hv
    have : g j = ↑u⁻¹ * (↑u * g j) := by rw [← mul_assoc, Units.inv_mul, one_mul]
    rw [this]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, rfl⟩)

end Manifold
