/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Monoid
public import Hironaka.Manifold.BlowUp.Transform.Basic
import Hironaka.Algebra.ColonPow
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.BlowUp.Transform.DerivTransform
import Hironaka.Manifold.IdealSheaf.Pullback
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The algebra of birational transforms of marked ideals under one blowing-up

Marked ideals `(I, m)` multiply with their marks adding and add for a common mark
[Kol07, Definition 59], and the birational transform `π_*^{-1}(I, m) = (I_F^{-m} π^*I, m)`
[Kol07, Definition 60] is defined when `m ≤ ord_Y I` along the centre. This file proves the rules
that the proof of the tuning theorem [Kol07, Theorem 100] uses at every step: for marked ideal
sheaves whose transforms are defined, the birational transform of a product is the product of the
birational transforms, of a power the power, of a same-mark sum the sum, and the birational
transform grows with the mark. They are the analytic counterparts of the rules for schemes in
`Hironaka.Resolution.Algebraic.Tuning.Transform` (`markedTransform_mul`,
`markedTransform_finset_prod`, `markedTransform_iSup_eq`) and
`Hironaka.Resolution.Algebraic.Kol07.Tuning` (`markedTransform_pow`), for
`MarkedIdealSheaf.birationalTransform`.

## The argument

The birational transform is the classical choice of an ideal sheaf with the colon stalks
`(π⁻¹(J)_{a'} : I_{F,a'}^k)`, characterised by `isDivExceptional_birationalTransform` under the
divisibility `k ≤ ord_Y J` along the centre, so every rule carries that hypothesis for every
marked ideal sheaf involved, and the rules are proved stalkwise:

* over the centre, in a blow-up chart of index `i`, the exceptional ideal is generated by the
  scaling coordinate `u = u_i` (`stalkIdeal_exceptionalIdealSheaf_eq_span_coord`), the stalk is a
  domain (`isDomain_stalk`) and `u ≠ 0`, and the divisibility gives `π⁻¹(J)_{a'} ⊆ (u^k)`
  (`totalTransform_stalkIdeal_le`); the colon algebra of a domain then does the rest: for
  `A ⊆ (u^a)`, `B ⊆ (u^b)`, `(A B : u^{a+b}) = (A : u^a)(B : u^b)`, `(A^s : u^{ks}) = (A : u^k)^s`,
  `(A + B : u^k) = (A : u^k) + (B : u^k)` (exact division: `A = u^a (A : u^a)` and
  `(u^k C : u^k) = C`), and `(A : u^s) ⊆ (A : u^t)` for `s ≤ t`;
* off the centre the birational transform is the total transform
  (`birationalTransform_stalkIdeal_of_notMem`) and the rules are the multiplicativity of
  `Ideal.map` (`Ideal.map_mul`, `Ideal.map_pow`, `Ideal.map_sup`).

The definedness of the products, powers and sums themselves is the order bookkeeping along the
centre (`le_ordAlongIdeal_mul`, `le_ordAlongIdeal_pow`, `le_ordAlongIdeal_finset_sum`,
`le_ordAlongIdeal_finset_prod`), the analogue along `Y` of the cosupport rules (1)–(4) of
[Kol07, Definition 59], read on the stalk containments `J_a ⊆ D_a^p` of `IdealSheaf.ordAlongIdeal`.
The colon algebra of a domain is elementary (the quotient is independent of the generators,
`Ideal.colon_span_range_pow_mul`). The rules are used by the tuning computation of
`Hironaka.Manifold.BlowUp.Transform.TuningTransform`.
-/

public noncomputable section

open TopologicalSpace Opposite CategoryTheory
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

/-! ### Orders along a centre under products, powers and sums (Kollár 59.1–59.4 along `Y`) -/

section OrderAlong

variable {X : TopCat} {𝒪 : TopCat.Sheaf CommRingCat X} (D : IdealSheaf 𝒪) {a : X}

/-- `ord_D (J K) ≥ ord_D J + ord_D K` —
`J_a ⊆ D_a^p` and `K_a ⊆ D_a^q` give `(JK)_a ⊆ D_a^{p+q}`. -/
theorem le_ordAlongIdeal_mul {J K : IdealSheaf 𝒪} {p q : ℕ}
    (hp : (p : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D J a)
    (hq : (q : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D K a) :
    ((p + q : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D (J * K) a := by
  rw [IdealSheaf.le_ordAlongIdeal_iff] at hp hq ⊢
  rw [IdealSheaf.stalkIdeal_mul, pow_add]
  exact Ideal.mul_mono hp hq

/-- `ord_D (J^s) ≥ s · ord_D J`. -/
theorem le_ordAlongIdeal_pow {J : IdealSheaf 𝒪} {p : ℕ}
    (hp : (p : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D J a) (s : ℕ) :
    ((p * s : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D (J ^ s) a := by
  rw [IdealSheaf.le_ordAlongIdeal_iff] at hp ⊢
  rw [IdealSheaf.stalkIdeal_pow, pow_mul]
  exact Ideal.pow_right_mono hp s

/-- A finite sum of ideal sheaves of
order `≥ p` along `D` has order `≥ p` along `D`. -/
theorem le_ordAlongIdeal_finset_sum {ι : Type*} (F : Finset ι) (G : ι → IdealSheaf 𝒪) {p : ℕ}
    (hG : ∀ i ∈ F, (p : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D (G i) a) :
    (p : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D (∑ i ∈ F, G i) a := by
  rw [IdealSheaf.le_ordAlongIdeal_iff, IdealSheaf.stalkIdeal_finset_sum]
  refine Finset.sum_induction _ (fun I : Ideal _ => I ≤ D.stalkIdeal a ^ p)
    (fun A B hA hB => ?_) bot_le fun i hi => (IdealSheaf.le_ordAlongIdeal_iff _ _ _ _).mp (hG i hi)
  rw [Submodule.add_eq_sup]
  exact sup_le hA hB

/-- A finite product of ideal
sheaves of orders `≥ c_i` along `D` has order `≥ ∑ c_i` along `D`. -/
theorem le_ordAlongIdeal_finset_prod {ι : Type*} (F : Finset ι) (G : ι → IdealSheaf 𝒪) (c : ι → ℕ)
    (hG : ∀ i ∈ F, (c i : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D (G i) a) :
    ((∑ i ∈ F, c i : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D (∏ i ∈ F, G i) a := by
  rw [IdealSheaf.le_ordAlongIdeal_iff, IdealSheaf.stalkIdeal_finset_prod,
    ← Finset.prod_pow_eq_pow_sum]
  exact Finset.prod_le_prod fun i hi => (IdealSheaf.le_ordAlongIdeal_iff _ _ _ _).mp (hG i hi)

end OrderAlong

/-! ### The marked transform under one blowing-up: products, powers, sums, marks -/

section OneBlowUp

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {Y : Set M}
  {c : ℕ} {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M']
  [T2Space M'] [SecondCountableTopology M'] {π : M' → M} (hY : IsClosedSubmanifold ψ Y c)
  (h : IsBlowUp ψ Y c π)

/-- At a point
`p` of a blow-up chart of index `i`, the stalk of the marked transform of `(J, k)` is the colon of
the total transform's stalk by the `k`-th power of the scaling coordinate `u_i`. -/
theorem birationalTransform_stalkIdeal_eq_colon_coord {J : IdealSheaf (structureSheaf 𝕜 E M)}
    {k : ℕ} (hk : ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J x)
    {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} {i : Fin c}
    {Φ : OpenPartialHomeomorph M' E} (hφ : IsAdaptedChart ψ Y φ σ) (hΦ : IsBlowUpChart ψ π φ σ i Φ)
    {p : M'} (hp : p ∈ Φ.source) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨J, k⟩).I.stalkIdeal p =
      ((J.pullback π h.contMDiff).stalkIdeal p).colon
        {coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i) ^ k} := by
  have hcol := isDivExceptional_birationalTransform hY h ⟨J, k⟩ hk p
  dsimp only at hcol
  rw [hcol, stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hp,
    Ideal.colon_coe_span_singleton_pow]

/-- At a point over the centre, the total transform's stalk lies in the ideal of the
`k`-th power of the scaling coordinate. -/
theorem totalTransform_stalkIdeal_le_span_coord_pow {J : IdealSheaf (structureSheaf 𝕜 E M)} {k : ℕ}
    (hk : ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J x)
    {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} {i : Fin c}
    {Φ : OpenPartialHomeomorph M' E} (hφ : IsAdaptedChart ψ Y φ σ) (hΦ : IsBlowUpChart ψ π φ σ i Φ)
    {p : M'} (hp : p ∈ Φ.source) (hpY : π p ∈ Y) :
    (J.pullback π h.contMDiff).stalkIdeal p ≤
      Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hp (σ i) ^ k} := by
  have := h.totalTransform_stalkIdeal_le hY J (hk _ hpY)
  rwa [stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hp, Ideal.span_singleton_pow]
    at this

/-- For marked ideal sheaves
`(J₁, a)`, `(J₂, b)` whose transforms are defined — `a ≤ ord_Y J₁`, `b ≤ ord_Y J₂` along `Y` —
the marked transform of `(J₁ J₂, a + b)` is the product of the marked transforms: stalkwise,
`(π⁻¹(J₁) π⁻¹(J₂) : u^{a+b}) = (π⁻¹(J₁) : u^a) · (π⁻¹(J₂) : u^b)` for the exceptional coordinate
`u` (exact division in the domain `𝒪_{M',p}`), and the identity off the centre. -/
theorem birationalTransform_mul (J₁ J₂ : IdealSheaf (structureSheaf 𝕜 E M)) (a b : ℕ)
    (h₁ : ∀ x ∈ Y, (a : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J₁ x)
    (h₂ : ∀ x ∈ Y, (b : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J₂ x) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨J₁ * J₂, a + b⟩).I =
      (MarkedIdealSheaf.birationalTransform hY h ⟨J₁, a⟩).I *
        (MarkedIdealSheaf.birationalTransform hY h ⟨J₂, b⟩).I := by
  have h₁₂ : ∀ x ∈ Y, ((a + b : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf (J₁ * J₂) x :=
    fun x hx => le_ordAlongIdeal_mul _ (h₁ x hx) (h₂ x hx)
  refine IdealSheaf.ext fun p => ?_
  rw [IdealSheaf.stalkIdeal_mul]
  by_cases hpY : π p ∈ Y
  · obtain ⟨φ, σ, hpφ, hφ⟩ := hY.exists_adaptedChart _ hpY
    obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p hpφ
    have := isDomain_stalk ψ hΦ.mem_maximalAtlas hpΦ
    rw [birationalTransform_stalkIdeal_eq_colon_coord hY h h₁₂ hφ hΦ hpΦ,
      birationalTransform_stalkIdeal_eq_colon_coord hY h h₁ hφ hΦ hpΦ,
      birationalTransform_stalkIdeal_eq_colon_coord hY h h₂ hφ hΦ hpΦ,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_mul, Ideal.map_mul]
    refine Ideal.colon_mul_pow_add _ _ (coord_ne_zero hΦ.mem_maximalAtlas hpΦ _) a b ?_ ?_
    · have := totalTransform_stalkIdeal_le_span_coord_pow hY h h₁ hφ hΦ hpΦ hpY
      rwa [IdealSheaf.stalkIdeal_pullback] at this
    · have := totalTransform_stalkIdeal_le_span_coord_pow hY h h₂ hφ hΦ hpΦ hpY
      rwa [IdealSheaf.stalkIdeal_pullback] at this
  · rw [birationalTransform_stalkIdeal_of_notMem hY h h₁₂ hpY,
      birationalTransform_stalkIdeal_of_notMem hY h h₁ hpY,
      birationalTransform_stalkIdeal_of_notMem hY h h₂ hpY, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_mul,
      Ideal.map_mul]

/-- For a marked ideal sheaf `(J, k)` whose transform is
defined, the marked transform of `(J^s, ks)` is the `s`-th power of the marked transform. -/
theorem birationalTransform_pow (J : IdealSheaf (structureSheaf 𝕜 E M)) (k s : ℕ)
    (hk : ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J x) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨J ^ s, k * s⟩).I =
      (MarkedIdealSheaf.birationalTransform hY h ⟨J, k⟩).I ^ s := by
  have hks : ∀ x ∈ Y, ((k * s : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf (J ^ s) x :=
    fun x hx => le_ordAlongIdeal_pow _ (hk x hx) s
  refine IdealSheaf.ext fun p => ?_
  rw [IdealSheaf.stalkIdeal_pow]
  by_cases hpY : π p ∈ Y
  · obtain ⟨φ, σ, hpφ, hφ⟩ := hY.exists_adaptedChart _ hpY
    obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p hpφ
    have := isDomain_stalk ψ hΦ.mem_maximalAtlas hpΦ
    rw [birationalTransform_stalkIdeal_eq_colon_coord hY h hks hφ hΦ hpΦ,
      birationalTransform_stalkIdeal_eq_colon_coord hY h hk hφ hΦ hpΦ,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_pow, Ideal.map_pow]
    refine Ideal.colon_pow_pow_mul _ (coord_ne_zero hΦ.mem_maximalAtlas hpΦ _) k s ?_
    have := totalTransform_stalkIdeal_le_span_coord_pow hY h hk hφ hΦ hpΦ hpY
    rwa [IdealSheaf.stalkIdeal_pullback] at this
  · rw [birationalTransform_stalkIdeal_of_notMem hY h hks hpY,
      birationalTransform_stalkIdeal_of_notMem hY h hk hpY, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pow, Ideal.map_pow]

/-- For marked ideal sheaves
`(J₁, k)`, `(J₂, k)` whose transforms are defined, the marked transform of `(J₁ + J₂, k)` is the sum
of the marked transforms (the sum of ideal sheaves, stalkwise `⊔`). -/
theorem birationalTransform_add (J₁ J₂ : IdealSheaf (structureSheaf 𝕜 E M)) (k : ℕ)
    (h₁ : ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J₁ x)
    (h₂ : ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J₂ x) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨J₁ + J₂, k⟩).I =
      (MarkedIdealSheaf.birationalTransform hY h ⟨J₁, k⟩).I +
        (MarkedIdealSheaf.birationalTransform hY h ⟨J₂, k⟩).I := by
  have h₁₂ : ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf (J₁ + J₂) x := by
    intro x hx
    rw [IdealSheaf.le_ordAlongIdeal_iff, IdealSheaf.stalkIdeal_add]
    exact sup_le ((IdealSheaf.le_ordAlongIdeal_iff _ _ _ _).mp (h₁ x hx))
      ((IdealSheaf.le_ordAlongIdeal_iff _ _ _ _).mp (h₂ x hx))
  refine IdealSheaf.ext fun p => ?_
  rw [IdealSheaf.stalkIdeal_add]
  by_cases hpY : π p ∈ Y
  · obtain ⟨φ, σ, hpφ, hφ⟩ := hY.exists_adaptedChart _ hpY
    obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p hpφ
    have := isDomain_stalk ψ hΦ.mem_maximalAtlas hpΦ
    rw [birationalTransform_stalkIdeal_eq_colon_coord hY h h₁₂ hφ hΦ hpΦ,
      birationalTransform_stalkIdeal_eq_colon_coord hY h h₁ hφ hΦ hpΦ,
      birationalTransform_stalkIdeal_eq_colon_coord hY h h₂ hφ hΦ hpΦ,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_add, Ideal.map_sup]
    refine Ideal.colon_sup_pow _ _ (coord_ne_zero hΦ.mem_maximalAtlas hpΦ _) k ?_ ?_
    · have := totalTransform_stalkIdeal_le_span_coord_pow hY h h₁ hφ hΦ hpΦ hpY
      rwa [IdealSheaf.stalkIdeal_pullback] at this
    · have := totalTransform_stalkIdeal_le_span_coord_pow hY h h₂ hφ hΦ hpΦ hpY
      rwa [IdealSheaf.stalkIdeal_pullback] at this
  · rw [birationalTransform_stalkIdeal_of_notMem hY h h₁₂ hpY,
      birationalTransform_stalkIdeal_of_notMem hY h h₁ hpY,
      birationalTransform_stalkIdeal_of_notMem hY h h₂ hpY, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_add,
      Ideal.map_sup]

/-- The marked transform of `(𝒪, 0)` is the
unit ideal sheaf. -/
theorem birationalTransform_one :
    (MarkedIdealSheaf.birationalTransform hY h ⟨1, 0⟩).I = 1 := by
  have h0 : ∀ x ∈ Y, ((0 : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf 1 x :=
    fun x _ => by rw [IdealSheaf.le_ordAlongIdeal_iff, pow_zero, Ideal.one_eq_top]; exact le_top
  refine IdealSheaf.ext fun p => ?_
  have hcol := isDivExceptional_birationalTransform hY h ⟨1, 0⟩ h0 p
  dsimp only at hcol
  rw [hcol, pow_zero, Ideal.one_eq_top, Submodule.top_coe, Submodule.colon_univ,
    IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_one, IdealSheaf.stalkIdeal_one,
    Ideal.map_top]

/-- For marked ideal sheaves `(G_i, c_i)` whose transforms are defined,
the marked transform of `(∏ G_i, ∑ c_i)` is the product of the marked transforms. -/
theorem birationalTransform_finset_prod {ι : Type*} (F : Finset ι)
    (G : ι → IdealSheaf (structureSheaf 𝕜 E M)) (c : ι → ℕ)
    (hG : ∀ i ∈ F, ∀ x ∈ Y, (c i : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf (G i) x) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨∏ i ∈ F, G i, ∑ i ∈ F, c i⟩).I =
      ∏ i ∈ F, (MarkedIdealSheaf.birationalTransform hY h ⟨G i, c i⟩).I := by
  classical
  induction F using Finset.induction_on with
  | empty =>
    rw [Finset.prod_empty, Finset.sum_empty, Finset.prod_empty]
    exact birationalTransform_one hY h
  | insert j F hj ih =>
    rw [Finset.prod_insert hj, Finset.sum_insert hj, Finset.prod_insert hj,
      birationalTransform_mul hY h _ _ _ _ (hG j (Finset.mem_insert_self j F))
        (fun x hx => le_ordAlongIdeal_finset_prod _ F G c
          (fun i hi => hG i (Finset.mem_insert_of_mem hi) x hx)),
      ih fun i hi => hG i (Finset.mem_insert_of_mem hi)]

/-- The marked transform of `(0, k)` is the zero
ideal sheaf. -/
theorem birationalTransform_zero (k : ℕ) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨0, k⟩).I = 0 := by
  have h0 : ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf 0 x :=
    fun x _ => by rw [IdealSheaf.le_ordAlongIdeal_iff, IdealSheaf.stalkIdeal_zero]; exact bot_le
  refine IdealSheaf.ext fun p => ?_
  rw [IdealSheaf.stalkIdeal_zero]
  by_cases hpY : π p ∈ Y
  · obtain ⟨φ, σ, hpφ, hφ⟩ := hY.exists_adaptedChart _ hpY
    obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p hpφ
    have := isDomain_stalk ψ hΦ.mem_maximalAtlas hpΦ
    rw [birationalTransform_stalkIdeal_eq_colon_coord hY h h0 hφ hΦ hpΦ,
      IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_zero, Ideal.map_bot]
    refine le_bot_iff.mp fun x hx => ?_
    rw [Submodule.mem_colon_singleton, smul_eq_mul, Ideal.mem_bot] at hx
    exact Ideal.mem_bot.mpr
      ((mul_eq_zero.mp hx).resolve_right (pow_ne_zero k (coord_ne_zero hΦ.mem_maximalAtlas hpΦ _)))
  · rw [birationalTransform_stalkIdeal_of_notMem hY h h0 hpY, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_zero, Ideal.map_bot]

/-- For marked ideal sheaves `(G_i, k)` of a common mark
whose transforms are defined, the marked transform of `(∑ G_i, k)` is the sum of the marked
transforms. -/
theorem birationalTransform_finset_sum {ι : Type*} (F : Finset ι)
    (G : ι → IdealSheaf (structureSheaf 𝕜 E M)) (k : ℕ)
    (hG : ∀ i ∈ F, ∀ x ∈ Y, (k : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf (G i) x) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨∑ i ∈ F, G i, k⟩).I =
      ∑ i ∈ F, (MarkedIdealSheaf.birationalTransform hY h ⟨G i, k⟩).I := by
  classical
  induction F using Finset.induction_on with
  | empty =>
    rw [Finset.sum_empty, Finset.sum_empty]
    exact birationalTransform_zero hY h k
  | insert j F hj ih =>
    rw [Finset.sum_insert hj, Finset.sum_insert hj,
      birationalTransform_add hY h _ _ _ (hG j (Finset.mem_insert_self j F))
        (fun x hx => le_ordAlongIdeal_finset_sum _ F G
          (fun i hi => hG i (Finset.mem_insert_of_mem hi) x hx)),
      ih fun i hi => hG i (Finset.mem_insert_of_mem hi)]

/-- For `s ≤ t ≤ ord_Y J` along `Y`, `π_*^{-1}(J, s) ⊆ π_*^{-1}(J, t)`: the colon by a smaller
power of the exceptional ideal is smaller. This is the step
`Π_*^{-1}(P, ms) ⊆ Π_*^{-1}(P, ∑ (m − j) c_j)` for `∑ (m − j) c_j ≥ ms` of the proof of
[Kol07, Theorem 100]. -/
theorem birationalTransform_le_of_le_mark (J : IdealSheaf (structureSheaf 𝕜 E M)) {s t : ℕ}
    (hst : s ≤ t) (ht : ∀ x ∈ Y, (t : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J x) :
    (MarkedIdealSheaf.birationalTransform hY h ⟨J, s⟩).I ≤
      (MarkedIdealSheaf.birationalTransform hY h ⟨J, t⟩).I := by
  have hs : ∀ x ∈ Y, (s : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf J x :=
    fun x hx => (Nat.cast_le.mpr hst).trans (ht x hx)
  rw [IdealSheaf.le_def]
  intro p
  by_cases hpY : π p ∈ Y
  · obtain ⟨φ, σ, hpφ, hφ⟩ := hY.exists_adaptedChart _ hpY
    obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p hpφ
    rw [birationalTransform_stalkIdeal_eq_colon_coord hY h hs hφ hΦ hpΦ,
      birationalTransform_stalkIdeal_eq_colon_coord hY h ht hφ hΦ hpΦ]
    exact Ideal.colon_singleton_pow_mono _ _ hst
  · rw [birationalTransform_stalkIdeal_of_notMem hY h hs hpY,
      birationalTransform_stalkIdeal_of_notMem hY h ht hpY]

end OneBlowUp

end Manifold
