/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.BlowUp.Transform.StrictSubspace
public import Hironaka.Algebra.Local.ChartSaturation
public import Hironaka.Algebra.SaturationDescent
public import Hironaka.Manifold.StructureSheaf
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.IdealSheaf.Pullback
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Bierstone–Milman's Proposition 3.13: the reduction to the chart ring

At every point `a'` of the blowing-up `π : M' → M` of `M` with centre `Y`, the saturation
`⋃_k (π⁻¹(I)_{a'} : I_{F,a'}^k)` of the total transform of a coherent ideal `I`, the stalk of the
strict transform `X'`, is the ideal generated by the strict transforms `y^{-d}(f ∘ π)` of the
elements `f ∈ I_{π(a')}` (`strictTransformElems`): [BM97, Proposition 3.13]. Bierstone–Milman
prove this with the diagram of initial exponents and Hironaka's division theorem; the proof here
takes a different route, through the flatness of the completion of the chart ring (the printed
argument's truncation step, which passes through the order of Lemma 3.22, is not reproduced):

* In a blow-up chart of index `i` at `a'` over `Y`, the chart-ring map `χ : R' → 𝒪_{M',a'}` of
  `Hironaka.Manifold.BlowUp.Transform.KollarChart` (Kollár's chart [Kol07, Definition 60,
  (60.2)]; here in the general form `IsLocalRing.exists_chartRing_hom_of_mul_eq`, for the
  coordinates shifted at `a'`; the coordinate permutation `τ` is `exists_kollarPerm`) identifies
  the total transform's stalk with `χ(I_a R')` (`IdealSheaf.stalkIdeal_pullback`) and the
  exceptional ideal with `(χ(x_r))` (`stalkIdeal_exceptionalIdealSheaf_eq_span_coord`), so the
  saturation is `⋃_k (χ(I_a R') : χ(x_r)^k)`.
* Given a **flat descent datum** for `χ` (`Algebra.HasFlatDescentDatum`: a ring `T` with
  `𝒪_{M',a'} → T` along which ideals descend and `R' → T` flat; the completion `T = 𝒪̂_{M',a'}`,
  `Hironaka.Manifold.BlowUp.Transform.StrictSubspaceCompletion`), this is
  `χ(⋃_k (I_a R' : x_r^k))` (`Algebra.iSup_colon_pow_map_eq_map_iSup_colon_pow`), and the
  chart-ring saturation is the ideal of the transforms `x_r^{-M} φ(f)`, `f ∈ I_a`
  (`Hironaka.Algebra.Local.ChartSaturation`).
* A transform `g` with `x_r^M g = φ(f)` maps to `χ(g)` with `χ(x_r)^M χ(g) = f ∘ π`: a strict
  transform of `f` (`map_transformsIdeal_le_span_strictTransformElems`); conversely every strict
  transform lies in the saturation (`span_strictTransformElems_le_saturationStalk`).
* Off the centre (`π(a') ∉ Y`) the exceptional ideal is the unit ideal, the saturation is the
  total transform (`saturationStalk_of_notMem_cosupport`) and `f ∘ π = 1^0 · (f ∘ π)` is a strict
  transform (`saturationStalk_eq_span_strictTransformElems_of_notMem`).

`Hironaka.Manifold.BlowUp.Transform.StrictSubspaceCompletion` supplies the flat descent datum
(the completion identification `𝒪̂_{M',a'} ≅ (R'_{𝔪'})^` through Cohen's structure theorem) and
assembles the proposition at every `a'` (`saturationStalk_eq_span_strictTransformElems`). Nothing
is assumed of `I`: `I = ⊤` and `I = ⊥` are covered (`⊤`: every element is a strict transform of
itself with `d = 0`; `⊥`: both sides are `⊥`). Hironaka describes the strict transform as the
union of the kernels `⋃_n (g⁻¹I : (g^*J)^n)` [Hir64, Ch. 0, §2, pp. 129–130].
-/

@[expose] public section

open TopologicalSpace Opposite CategoryTheory IsLocalRing
open scoped Manifold ContDiff

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {Y : Set M}
  {c : ℕ} {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M']
  [T2Space M'] [SecondCountableTopology M'] {π : M' → M} {φ : OpenPartialHomeomorph M E}
  {σ : Fin c ↪ Fin n} {i : Fin c} {Φ : OpenPartialHomeomorph M' E}

/-- **`χ` is a chart-ring map at `a'`** for the blow-up chart `Φ` of index `i` over the adapted
chart `φ`, at a point over the centre, with the coordinates `x` indexed through the permutation
`τ` (Kollár's convention: `τ r = σ i` is the scaling coordinate and the `τ j`, `j < r`, are the
other centre coordinates): `χ ∘ φ_R = germMap π`, `x_j / x_r ↦ u_{τ j} − u_{τ j}(a')` (`j < r`:
the ratio coordinates centred at `a'`, so that `χ⁻¹(𝔪_{a'})` is the chart origin of `x` — the
form `exists_chartRing_hom` takes when the coordinates `x` are Kollár's coordinates
`kollarCoords` shifted at `a'`) and `x_r ↦ u_{σ i}`. -/
structure IsChartRingHom (h : IsBlowUp ψ Y c π) (hΦ : IsBlowUpChart ψ π φ σ i Φ) {a' : M'}
    (ha' : a' ∈ Φ.source) (x : Fin n → (structureSheaf 𝕜 E M).presheaf.stalk (π a')) (r : Fin n)
    (τ : Fin n ≃ Fin n)
    (χ : chartRing x r →+* (structureSheaf 𝕜 E M').presheaf.stalk a') : Prop where
  mem_center : π a' ∈ Y
  apply_eq : τ r = σ i
  lt_iff : ∀ j, j < r ↔ ∃ k, k ≠ i ∧ τ j = σ k
  algebraMap_eq : ∀ s, χ (algebraMap _ _ s) = germMap π h.contMDiff a' s
  chartYR_eq : ∀ j, j < r →
    χ (chartYR x r j) = coord E ψ Φ hΦ.mem_maximalAtlas ha' (τ j) -
      const 𝕜 E M' a' (eval 𝕜 E M' a' (coord E ψ Φ hΦ.mem_maximalAtlas ha' (τ j)))
  xr_eq : χ (algebraMap _ _ (x r)) = coord E ψ Φ hΦ.mem_maximalAtlas ha' (σ i)

variable (hY : IsClosedSubmanifold ψ Y c) (h : IsBlowUp ψ Y c π)
  (I : IdealSheaf (structureSheaf 𝕜 E M))

/-- Through a chart-ring map `χ` compatible with the germ map, the total transform's stalk is the
image of the extension `I_a R'` (`IdealSheaf.stalkIdeal_pullback`, rewritten through
`χ ∘ φ_R = germMap π`). -/
theorem totalTransform_stalkIdeal_eq_map_map_chartRing {a' : M'}
    (x : Fin n → (structureSheaf 𝕜 E M).presheaf.stalk (π a')) (r : Fin n)
    (χ : chartRing x r →+* (structureSheaf 𝕜 E M').presheaf.stalk a')
    (hχ : ∀ s, χ (algebraMap _ _ s) = germMap π h.contMDiff a' s) :
    (I.pullback π h.contMDiff).stalkIdeal a' =
      Ideal.map χ ((I.stalkIdeal (π a')).map (algebraMap _ (chartRing x r))) := by
  rw [IdealSheaf.stalkIdeal_pullback, Ideal.map_map]
  congr 1
  exact (RingHom.ext hχ).symm

/-- BM97 Prop 3.13, the transport (flatness route): in a blow-up chart at `a'` over
`Y`, given a flat descent datum for the chart-ring map `χ`, the saturation of the total transform
is the image under `χ` of the ideal of the transforms `x_r^{-M} φ(f)`, `f ∈ I_{π(a')}`, of the chart
ring. -/
theorem saturationStalk_eq_map_transformsIdeal (hφ : IsAdaptedChart ψ Y φ σ)
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) {a' : M'} (ha' : a' ∈ Φ.source)
    (x : Fin n → (structureSheaf 𝕜 E M).presheaf.stalk (π a')) (r : Fin n) (τ : Fin n ≃ Fin n)
    (χ : chartRing x r →+* (structureSheaf 𝕜 E M').presheaf.stalk a')
    (hχ : IsChartRingHom h hΦ ha' x r τ χ) (hdat : Algebra.HasFlatDescentDatum χ) :
    saturationStalk hY h I a' =
      Ideal.map χ (transformsIdeal x r (I.stalkIdeal (π a'))) := by
  rw [saturationStalk, stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ ha', ← hχ.xr_eq,
    totalTransform_stalkIdeal_eq_map_map_chartRing h I x r χ hχ.algebraMap_eq]
  simp_rw [Ideal.span_singleton_pow, Submodule.colon_span]
  rw [hdat.iSup_colon_pow_map_eq, iSup_colon_pow_singleton_map_eq_transformsIdeal]

/-- BM97 Prop 3.13, the easy inclusion in the chart: the image under `χ` of a transform `g`,
`x_r^M g = φ(f)` with `f ∈ I_{π(a')}`, is a strict transform of `f` —
`u_{σ i}^M χ(g) = f ∘ π` with `(u_{σ i}) = I_{F,a'}`. -/
theorem map_transformsIdeal_le_span_strictTransformElems (hφ : IsAdaptedChart ψ Y φ σ)
    (hΦ : IsBlowUpChart ψ π φ σ i Φ) {a' : M'} (ha' : a' ∈ Φ.source)
    (x : Fin n → (structureSheaf 𝕜 E M).presheaf.stalk (π a')) (r : Fin n) (τ : Fin n ≃ Fin n)
    (χ : chartRing x r →+* (structureSheaf 𝕜 E M').presheaf.stalk a')
    (hχ : IsChartRingHom h hΦ ha' x r τ χ) :
    Ideal.map χ (transformsIdeal x r (I.stalkIdeal (π a'))) ≤
      Ideal.span (strictTransformElems hY h I a') := by
  rw [Ideal.map_le_iff_le_comap]
  intro g hg
  obtain ⟨d, f, hf, hfg⟩ := (mem_transformsIdeal x r _).mp hg
  rw [Ideal.mem_comap]
  refine Ideal.subset_span ⟨f, hf, coord E ψ Φ hΦ.mem_maximalAtlas ha' (σ i), d,
    (stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ ha').symm, ?_⟩
  rw [← hχ.xr_eq, ← map_pow, ← map_mul, hfg, hχ.algebraMap_eq]

/-- BM97 Prop 3.13 at a point over the centre (flatness route), given a flat descent
datum for the chart-ring map: the saturation is generated by the strict transforms of the
elements of `I_{π(a')}`. -/
theorem saturationStalk_eq_span_strictTransformElems_of_hasFlatDescentDatum
    (hφ : IsAdaptedChart ψ Y φ σ) (hΦ : IsBlowUpChart ψ π φ σ i Φ) {a' : M'} (ha' : a' ∈ Φ.source)
    (x : Fin n → (structureSheaf 𝕜 E M).presheaf.stalk (π a')) (r : Fin n) (τ : Fin n ≃ Fin n)
    (χ : chartRing x r →+* (structureSheaf 𝕜 E M').presheaf.stalk a')
    (hχ : IsChartRingHom h hΦ ha' x r τ χ) (hdat : Algebra.HasFlatDescentDatum χ) :
    saturationStalk hY h I a' = Ideal.span (strictTransformElems hY h I a') := by
  refine le_antisymm ?_ (span_strictTransformElems_le_saturationStalk hY h I a')
  rw [saturationStalk_eq_map_transformsIdeal hY h I hφ hΦ ha' x r τ χ hχ hdat]
  exact map_transformsIdeal_le_span_strictTransformElems hY h I hφ hΦ ha' x r τ χ hχ

/-- BM97 Prop 3.13 off the centre: at `a'` with `π(a') ∉ Y` the exceptional ideal is the unit
ideal, the saturation is the total transform's stalk, and every `f ∘ π` is the strict transform
`1^0 · (f ∘ π)` of `f`. -/
theorem saturationStalk_eq_span_strictTransformElems_of_notMem {a' : M'} (ha' : π a' ∉ Y) :
    saturationStalk hY h I a' = Ideal.span (strictTransformElems hY h I a') := by
  have htop := stalkIdeal_exceptionalIdealSheaf_of_notMem hY h ha'
  have hnot : a' ∉ (hY.idealSheaf.pullback π h.contMDiff).support := by
    rw [(isIdealSheafOf_exceptionalIdealSheaf hY h).1]
    exact ha'
  refine le_antisymm ?_ (span_strictTransformElems_le_saturationStalk hY h I a')
  rw [saturationStalk_of_notMem_cosupport hY h I hnot, IdealSheaf.stalkIdeal_pullback,
    Ideal.map_le_iff_le_comap]
  intro f hf
  rw [Ideal.mem_comap]
  exact Ideal.subset_span ⟨f, hf, 1, 0, by rw [Ideal.span_singleton_one, htop], by
    rw [pow_zero, one_mul]⟩

/-- The centred adapted coordinates at `π(a')`, permuted by `τ`: `x_j = u_{τ j} - u_{τ j}(π a')`,
the coordinate family `exists_chartRing_hom` takes. -/
noncomputable def centredCoords (hφ : IsAdaptedChart ψ Y φ σ) (hΦ : IsBlowUpChart ψ π φ σ i Φ)
    {a' : M'} (ha' : a' ∈ Φ.source) (τ : Fin n ≃ Fin n) :
    Fin n → (structureSheaf 𝕜 E M).presheaf.stalk (π a') :=
  fun j => coord E ψ φ hφ.1 (hΦ.source_subset ha') (τ j) -
    const 𝕜 E M (π a') (eval 𝕜 E M (π a') (coord E ψ φ hφ.1 (hΦ.source_subset ha') (τ j)))

end Manifold
