/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.BlowUp.Divisor
public import Hironaka.Manifold.BlowUp.Transform.Basic
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.BlowUp.Transform.Division
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.BlowUp.Transform.OrderAlong
import Hironaka.Manifold.BlowUp.Transform.Strict
import Hironaka.Manifold.BlowUp.Transform.StrictCharts
import Hironaka.Manifold.IdealSheaf.Pullback
import Hironaka.Manifold.Submanifold.Ideal
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The ideal sheaf of the strict transform of a hypersurface

For a smooth hypersurface `H ⊇ Y`, the birational transform `π_*^{-1}(I_H, 1) = I_F^{-1} π⁻¹(I_H)`
is the ideal sheaf of the strict transform `H'` (`isIdealSheafOf_strictTransform`): this is
Bierstone–Milman's `f' = y_exc^{-d} f ∘ σ` with `d = 1` [BM97, §3, "The strict transform"]. Both
are ideal sheaves with the stalks of a closed submanifold, so it suffices to compare stalks. Over
the centre, in the pair chart of `Hironaka.Manifold.BlowUp.Transform.StrictCharts`
(`H = {z_{σ k₀} = 0}`) and a blow-up chart of index `i`, `π⁻¹(I_H)` is generated by
`z_{σ k₀} ∘ π = u_i u_{k₀}` (or by `u_i` when `k₀ = i`), so the colon by `u_i` is `(u_{k₀})`, the
ideal of `H' = {u_{k₀} = 0}` in that chart, or the unit ideal where `H'` is absent (`k₀ = i`, or
`u_{k₀}` a unit at the point); the stalk is a domain. Off the exceptional divisor `I_F` is the
unit ideal, `π⁻¹(I_H)` is generated by `h ∘ π` for the coordinate `h` of an adapted chart of `H`,
and `h ∘ π` is the coordinate of the transported chart adapted to `H'`. The comparison of the
orders along the centre needs `I_H ⊆ I_Y` at the points of `Y`
(`stalkIdeal_idealSheaf_le_of_subset`: germs vanishing on `H` vanish on `Y ⊆ H`).
-/

public section

open TopologicalSpace Opposite CategoryTheory Filter Topology IsLocalRing Set
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {Y : Set M}
  {c : ℕ} {H : Set M}

/-- For `Y ⊆ H`, the ideal of `H` is contained in the ideal of `Y` at the points of
`Y` (germs vanishing on `H` vanish on `Y`). -/
theorem IsClosedSubmanifold.stalkIdeal_idealSheaf_le_of_subset (hY : IsClosedSubmanifold ψ Y c)
    (hH : IsClosedSubmanifold ψ H 1) (hYH : Y ⊆ H) {a : M} (ha : a ∈ Y) :
    hH.idealSheaf.stalkIdeal a ≤ hY.idealSheaf.stalkIdeal a := by
  intro s hs
  obtain ⟨V, haV, g, rfl⟩ := (structureSheaf 𝕜 E M).presheaf.exists_germ_eq s
  rw [hH.germ_mem_stalkIdeal_idealSheaf_iff V (hYH ha) haV] at hs
  rw [hY.germ_mem_stalkIdeal_idealSheaf_iff V ha haV]
  obtain ⟨O, hO, hOH⟩ := (mem_nhds_subtype H ⟨a, hYH ha⟩ _).mp hs
  refine (mem_nhds_subtype Y ⟨a, ha⟩ _).mpr ⟨O, hO, fun y hy => ?_⟩
  exact hOH (show (⟨(y : M), hYH y.2⟩ : H) ∈ Subtype.val ⁻¹' O from hy)

/-- The range of the single coordinate of a hypersurface chart. -/
theorem range_singleIdx_coord {N : Type u} [TopologicalSpace N] [ChartedSpace E N]
    {e : OpenPartialHomeomorph N E} (he : e ∈ maximalAtlas 𝓘(𝕜, E) ω N) {p : N} (hp : p ∈ e.source)
    (k : Fin n) :
    (Set.range fun j : Fin 1 => coord E ψ e he hp (singleEmb k j)) = {coord E ψ e he hp k} := by
  ext s
  simp only [Set.mem_range, singleEmb_apply, Set.mem_singleton_iff, exists_const, eq_comm]

variable {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M']
  [T2Space M'] [SecondCountableTopology M'] {π : M' → M}

/-- The ideal sheaf of the strict transform of a smooth hypersurface `H ⊇ Y` is the birational
transform of `(I_H, 1)` (`f' = y_exc^{-d} f ∘ σ` with `d = 1`, [BM97, §3, "The strict transform"]).
-/
theorem isIdealSheafOf_strictTransform [IsManifold 𝓘(𝕜, E) ω M] (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) (hH : IsClosedSubmanifold ψ H 1) (hYH : Y ⊆ H) :
    IsIdealSheafOf ψ (strictTransformSet π Y H) 1
      (MarkedIdealSheaf.birationalTransform hY h ⟨hH.idealSheaf, 1⟩).I := by
  have hH' := isClosedSubmanifold_strictTransform hY h hH hYH
  have hπc : Continuous π := h.contMDiff.continuous
  have hm : ∀ a ∈ Y, ((1 : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf hH.idealSheaf a := by
    intro a ha
    rw [IdealSheaf.le_ordAlongIdeal_iff, pow_one]
    exact hY.stalkIdeal_idealSheaf_le_of_subset hH hYH ha
  have hcol := isDivExceptional_birationalTransform hY h ⟨hH.idealSheaf, 1⟩ hm
  suffices heq : (MarkedIdealSheaf.birationalTransform hY h ⟨hH.idealSheaf, 1⟩).I = hH'.idealSheaf
  by
    rw [heq]
    exact hH'.isIdealSheafOf_idealSheaf
  refine IdealSheaf.ext fun p => ?_
  rw [hcol p]
  dsimp only
  rw [pow_one, IdealSheaf.stalkIdeal_pullback]
  by_cases hpY : π p ∈ Y
  · obtain ⟨φ, σ, k₀, hpφ, hφ, hHk⟩ := exists_adaptedChart_pair hY hH hYH hpY
    obtain ⟨i, Φ, hΦ, hpΦ⟩ := h.cover φ σ hφ p hpφ
    have hφH : IsAdaptedChart ψ H φ (singleEmb (σ k₀)) := isAdaptedChart_singleIdx hφ.1 hHk
    have hpH : π p ∈ H := hYH hpY
    have hIH : hH.idealSheaf.stalkIdeal (π p) = Ideal.span {coord E ψ φ hφ.1 hpφ (σ k₀)} := by
      rw [hH.stalkIdeal_idealSheaf_eq_span hpH hφH hpφ, range_singleIdx_coord]
    rw [hIH, Ideal.map_span, Set.image_singleton,
      stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hpΦ, Submodule.colon_span]
    have hdom := isDomain_stalk ψ hΦ.mem_maximalAtlas hpΦ
    by_cases hki : k₀ = i
    · subst hki
      rw [IsBlowUpChart.germMap_coord_self h.contMDiff hφ.1 hΦ hpΦ]
      have hp' : p ∉ strictTransformSet π Y H := by
        intro hp
        have hE := strictTransform_inter_source_self hφ hΦ hHk
        exact Set.eq_empty_iff_forall_notMem.mp hE p ⟨hp, hpΦ⟩
      rw [hH'.stalkIdeal_idealSheaf_of_notMem hp', Ideal.eq_top_iff_one,
        Submodule.mem_colon_singleton, one_smul]
      exact Ideal.mem_span_singleton_self _
    · rw [IsBlowUpChart.germMap_coord_of_ne h.contMDiff hφ.1 hΦ hpΦ hki]
      have hcol' : (Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hpΦ (σ i) *
          coord E ψ Φ hΦ.mem_maximalAtlas hpΦ (σ k₀)}).colon
            {coord E ψ Φ hΦ.mem_maximalAtlas hpΦ (σ i)} =
          Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hpΦ (σ k₀)} := by
        have := Ideal.colon_span_range_pow_mul
          (coord_ne_zero (ψ := ψ) hΦ.mem_maximalAtlas hpΦ (σ i)) 1
          (fun _ : Fin 1 => coord E ψ Φ hΦ.mem_maximalAtlas hpΦ (σ k₀))
        simpa only [pow_one, Set.range_const] using this
      rw [hcol']
      have hE := strictTransform_inter_source_of_ne hφ hΦ hHk (Ne.symm hki)
      by_cases hp' : p ∈ strictTransformSet π Y H
      · have hΦH' : IsAdaptedChart ψ (strictTransformSet π Y H) Φ (singleEmb (σ k₀)) := by
          refine isAdaptedChart_singleIdx hΦ.mem_maximalAtlas fun x hx => ?_
          exact ⟨fun hxH => ((Set.ext_iff.mp hE x).mp ⟨hxH, hx⟩).2,
            fun h0 => ((Set.ext_iff.mp hE x).mpr ⟨hx, h0⟩).1⟩
        rw [hH'.stalkIdeal_idealSheaf_eq_span hp' hΦH' hpΦ, range_singleIdx_coord]
      · rw [hH'.stalkIdeal_idealSheaf_of_notMem hp']
        have hne : ψ (Φ p) (σ k₀) ≠ 0 := fun h0 => hp' ((Set.ext_iff.mp hE p).mpr ⟨hpΦ, h0⟩).1
        have hu : IsUnit (coord E ψ Φ hΦ.mem_maximalAtlas hpΦ (σ k₀)) := by
          rw [← IsLocalRing.notMem_maximalIdeal, mem_maximalIdeal_iff_eval, eval_coord]
          exact hne
        exact Ideal.eq_top_of_isUnit_mem _ (Ideal.mem_span_singleton_self _) hu
  · rw [stalkIdeal_exceptionalIdealSheaf_of_notMem hY h hpY, Submodule.top_coe,
      Submodule.colon_univ]
    by_cases hpH : π p ∈ H
    · obtain ⟨φ, σ₁, e, hpφ, hφ, hpe, he, hcoord⟩ :=
        exists_adaptedChart_strictTransform_off hY h hH hpH hpY
      have hp' : p ∈ strictTransformSet π Y H :=
        (preimage_subset_strictTransform_union (π := π) (Y := Y)
          (show p ∈ π ⁻¹' H from hpH)).resolve_right hpY
      rw [hH.stalkIdeal_idealSheaf_eq_span hpH hφ hpφ, hH'.stalkIdeal_idealSheaf_eq_span hp' he hpe,
        Ideal.map_span, ← Set.range_comp]
      refine congrArg Ideal.span (congrArg Set.range (funext fun j => ?_))
      rw [Subsingleton.elim j 0]
      apply stalkToGerm_injective 𝓘(𝕜, E) ω M' p
      rw [Function.comp_apply, stalkToGerm_germMap, stalkToGerm_coord, stalkToGerm_coord,
        Germ.coe_compTendsto, Germ.coe_eq]
      filter_upwards [e.open_source.mem_nhds hpe,
        (φ.open_source.preimage hπc).mem_nhds (show p ∈ π ⁻¹' φ.source from hpφ)] with x hx hxφ
      rw [Function.comp_apply, extendSection_of_mem 𝕜 E _ hxφ, extendSection_of_mem 𝕜 E _ hx]
      exact (hcoord x hx).symm
    · rw [hH.stalkIdeal_idealSheaf_of_notMem hpH, Ideal.map_top]
      have hp' : p ∉ strictTransformSet π Y H := fun hp =>
        hpH (strictTransform_subset_preimage hπc hH.isClosed hp)
      rw [hH'.stalkIdeal_idealSheaf_of_notMem hp']

end Manifold
