/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUp.Chart
public import Hironaka.Scheme.IdealSheaf.Defs
public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Hironaka.Scheme.BlowUp.AffineAlgebra

/-!
# The trivial blow-up: blowing up an invertible ideal is an isomorphism

When the centre is already an effective Cartier divisor, the blow-up map is an isomorphism
[Kol07, Warning 20]; [Hau14, Remark 4.5]; [Sta, Tag 0807].

## The argument

A morphism `π : B ⟶ X` is a blow-up of `X` along the ideal sheaf `I` [Hau14, Definition 4.4] if
`π` is *admissible* — the inverse image ideal `I·𝒪_B = I.comap π` is invertible — and
*universal*: every admissible `f : Y ⟶ X` factors through `π` by a unique `g : Y ⟶ B`.  Suppose
`I` itself is invertible.  Then the identity of `X` is admissible (its inverse image of `I` is `I`),
so it factors as `σ ≫ π = 𝟙 X` for a unique `σ : X ⟶ B`.  The morphism `π` is admissible by
hypothesis, and both `π ≫ σ` and `𝟙 B` are factorizations of `π` through `π`
(`(π ≫ σ) ≫ π = π ≫ 𝟙 X = π`); by uniqueness they coincide, `π ≫ σ = 𝟙 B`.  So `σ` is a two-sided
inverse of `π`.  This is `isIso_of_isInvertible_of_universal`, stated for any morphism with the
universal property; `Hironaka.Scheme.BlowUp.Glue.Trivial` applies it to the blow-up.

## The affine model of a principal centre

For `Spec R` and the centre `(g)`, the affine blow-up is covered by the single chart of `g` (the
generating set `{g}`), whose ring `R[(g)/g] ⊆ R_g` consists of the constants: an element `y` has
`y·gⁿ = x` with `x ∈ (g)ⁿ = (gⁿ)`, say `x = r·gⁿ`, and `gⁿ` is a unit of `R_g`, so `y = r`
(`affineBlowUpAlgebra.surjective_algebraMap_span_singleton`).  Hence `R[(g)/g]` is the image of
`R` in `R_g`, i.e. `R/T_g` with `T_g = ker (R → R_g) = ⋃ₖ Ann(gᵏ)` the `g`-power torsion
(`affineBlowUpAlgebra.ker_algebraMap_span_singleton`,
`affineBlowUpAlgebra.mem_ker_algebraMap_span_singleton_iff`), and `B_{(g)} Spec R = Spec (R/T_g)`.
Hauser's Example 4.31 describes the blow-up along a zero divisor `g` with `hg = 0` as the
subscheme `V(h)`: it lies in `V(h)`
(`affineBlowUpAlgebra.algebraMap_span_singleton_eq_zero_of_mul_eq_zero`) and equals it exactly
when `T_g = (h)`.  When `g` is a nonzerodivisor, `R → R_g` is injective, so `R → R[(g)/g]` is
bijective (`affineBlowUpAlgebra.bijective_algebraMap_span_singleton`) and the blow-up map — the
inverse of the chart followed by `Spec (R ≅ R[(g)/g])` — is an isomorphism
(`affineBlowUp.isIso_π_span_singleton`): `B_{(g)} Spec R = Spec R` [Hau14, Example 4.29].  The
same example's first assertion, that the Rees algebra `R[gt] ⊂ R[t]` is isomorphic as a graded
`R`-algebra to the polynomial ring `R[v]` with `deg v = 1`, is `reesAlgebra.polynomialEquiv`:
`v ↦ gt` is surjective because the Rees algebra of `(g)` is generated by `gt` (Mathlib's
`adjoin_monomial_eq_reesAlgebra`), injective because the `n`-th coefficient of the image of `p` is
`pₙ·gⁿ` (Mathlib's `comp_C_mul_X_coeff`) and `gⁿ` is a nonzerodivisor, and graded because it
sends the monomial `r vⁿ` to `r gⁿ tⁿ` (`reesAlgebra.ofPolynomial_monomial_mem_grading`).
-/

@[expose] public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory Polynomial

universe u

section Universal

variable {X B : Scheme.{u}} (I : X.IdealSheafData) (π : B ⟶ X)

/-- **A blow-up along an invertible ideal is an isomorphism** [Sta, Tag 0807];
[Hau14, Remark 4.5 and Definition 4.4]; [Kol07, Warning 20].  If `π : B ⟶ X` is admissible for
`I` (`I.comap π` invertible) and universal among
admissible morphisms (every `f : Y ⟶ X` with `I.comap f` invertible factors uniquely through `π`),
and `I` is invertible, then `π` is an isomorphism: its inverse is the unique lift of `𝟙 X`, and
`π ≫ σ = 𝟙 B` because both are lifts of the admissible morphism `π`. -/
theorem _root_.Hironaka.BlowUp.isIso_of_isInvertible_of_universal (hπ : (I.comap π).IsInvertible)
    (hu : ∀ {Y : Scheme.{u}} (f : Y ⟶ X), (I.comap f).IsInvertible → ∃! g : Y ⟶ B, g ≫ π = f)
    (hI : I.IsInvertible) : IsIso π := by
  obtain ⟨σ, hσ, -⟩ := hu (𝟙 X) (by rwa [Scheme.IdealSheafData.comap_id])
  obtain ⟨g₀, -, hg₀⟩ := hu π hπ
  refine ⟨⟨σ, ?_, hσ⟩⟩
  calc π ≫ σ = g₀ := hg₀ _ (show (π ≫ σ) ≫ π = π by rw [Category.assoc, hσ, Category.comp_id])
    _ = 𝟙 B := (hg₀ _ (Category.id_comp π)).symm

end Universal

section Principal

variable {R : Type u} [CommRing R] (g : R)

/-- The chart ring `R[(g)/g] ⊆ R_g` of the principal centre `(g)` at its generator consists of the
constants: `y·gⁿ = r·gⁿ` in `R_g` forces `y = r` [Hau14, Examples 4.29 and 4.31]. -/
theorem affineBlowUpAlgebra.surjective_algebraMap_span_singleton :
    Function.Surjective (algebraMap R (affineBlowUpAlgebra (Ideal.span {g}) g)) := by
  rintro ⟨y, hy⟩
  obtain ⟨n, x, hx, hxy⟩ :=
    (affineBlowUpAlgebra.mem_iff (Ideal.mem_span_singleton_self g) y).mp hy
  rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton'] at hx
  obtain ⟨r, rfl⟩ := hx
  refine ⟨r, Subtype.ext ?_⟩
  have hu : IsUnit (algebraMap R (Localization.Away g) g ^ n) :=
    (IsLocalization.Away.algebraMap_isUnit (S := Localization.Away g) g).pow n
  refine hu.mul_left_injective ?_
  change algebraMap R (Localization.Away g) r * algebraMap R (Localization.Away g) g ^ n =
    y * algebraMap R (Localization.Away g) g ^ n
  rw [hxy, map_mul, map_pow]

/-- The kernel of `R → R[(g)/g]` is the kernel of `R → R_g` (the values agree, `R[(g)/g]` being a
subring of `R_g`). -/
theorem affineBlowUpAlgebra.ker_algebraMap_span_singleton :
    RingHom.ker (algebraMap R (affineBlowUpAlgebra (Ideal.span {g}) g)) =
      RingHom.ker (algebraMap R (Localization.Away g)) := by
  ext r
  simp only [RingHom.mem_ker, Subtype.ext_iff, Subalgebra.coe_algebraMap, Subalgebra.coe_zero]

/-- The kernel of `R → R[(g)/g]` is the `g`-power torsion `T_g = ⋃ₖ Ann(gᵏ)`, so
`R[(g)/g] ≅ R/T_g` and `B_{(g)} Spec R = Spec (R/T_g)` (compare [Hau14, Example 4.31]). -/
theorem affineBlowUpAlgebra.mem_ker_algebraMap_span_singleton_iff (r : R) :
    r ∈ RingHom.ker (algebraMap R (affineBlowUpAlgebra (Ideal.span {g}) g)) ↔
      ∃ n : ℕ, g ^ n * r = 0 := by
  rw [affineBlowUpAlgebra.ker_algebraMap_span_singleton, RingHom.mem_ker,
    IsLocalization.map_eq_zero_iff (Submonoid.powers g)]
  constructor
  · rintro ⟨⟨_, n, rfl⟩, h⟩
    exact ⟨n, h⟩
  · rintro ⟨n, h⟩
    exact ⟨⟨g ^ n, n, rfl⟩, h⟩

/-- For `h·g = 0` the element `h` dies in the chart ring `R[(g)/g]`, so the blow-up
`B_{(g)} Spec R` lies in `V(h)` [Hau14, Example 4.31] (it equals `V(h)` exactly when `T_g = (h)`,
as in [Hau14, Example 4.32]). -/
theorem affineBlowUpAlgebra.algebraMap_span_singleton_eq_zero_of_mul_eq_zero {h : R}
    (hgh : h * g = 0) : algebraMap R (affineBlowUpAlgebra (Ideal.span {g}) g) h = 0 :=
  (affineBlowUpAlgebra.mem_ker_algebraMap_span_singleton_iff g h).mpr
    ⟨1, by rw [pow_one, mul_comm]; exact hgh⟩

/-- For a nonzerodivisor `g`, `R[(g)/g] = R` [Hau14, Example 4.29]: the structure map is
bijective (injective because `R → R_g` is, surjective by
`affineBlowUpAlgebra.surjective_algebraMap_span_singleton`). -/
theorem affineBlowUpAlgebra.bijective_algebraMap_span_singleton (hg : g ∈ nonZeroDivisors R) :
    Function.Bijective (algebraMap R (affineBlowUpAlgebra (Ideal.span {g}) g)) := by
  refine ⟨fun x y hxy => ?_, affineBlowUpAlgebra.surjective_algebraMap_span_singleton g⟩
  have hle : Submonoid.powers g ≤ nonZeroDivisors R := by
    rintro _ ⟨n, rfl⟩
    exact pow_mem hg n
  exact IsLocalization.injective (Localization.Away g) hle (congrArg Subtype.val hxy)

/-- The chart of `g` is all of the affine blow-up along `(g)`: the generating set `{g}`. -/
theorem affineBlowUp.opensRange_chart_self :
    (affineBlowUp.chart (Ideal.span {g}) ⟨g, Ideal.mem_span_singleton_self g⟩).opensRange = ⊤ := by
  have h := affineBlowUp.iSup_opensRange_chart_of_span_eq (Ideal.span {g}) {g} rfl
  rwa [iSup_unique] at h

/-- The chart of `g` is a surjective open immersion, hence an isomorphism. -/
instance affineBlowUp.isIso_chart_self :
    IsIso (affineBlowUp.chart (Ideal.span {g}) ⟨g, Ideal.mem_span_singleton_self g⟩) := by
  rw [isIso_iff_isOpenImmersion_and_epi_base]
  refine ⟨inferInstance, ?_⟩
  rw [TopCat.epi_iff_surjective]
  intro x
  have hx : x ∈ (affineBlowUp.chart (Ideal.span {g})
      ⟨g, Ideal.mem_span_singleton_self g⟩).opensRange := by
    rw [affineBlowUp.opensRange_chart_self]
    trivial
  exact Scheme.Hom.mem_opensRange.mp hx

/-- **`B_{(g)} Spec R = Spec R` for a nonzerodivisor `g`** [Hau14, Example 4.29]; the trivial
blow-up of [Kol07, Warning 20] in the affine model: the blow-up map is an isomorphism, being the
inverse of the chart of `g` followed by `Spec (R ≅ R[(g)/g])`. -/
theorem affineBlowUp.isIso_π_span_singleton (hg : g ∈ nonZeroDivisors R) :
    IsIso (affineBlowUp.π (Ideal.span {g})) := by
  have : IsIso (CommRingCat.ofHom (algebraMap R (affineBlowUpAlgebra (Ideal.span {g}) g))) :=
    (ConcreteCategory.isIso_iff_bijective _).mpr
      (affineBlowUpAlgebra.bijective_algebraMap_span_singleton g hg)
  have : IsIso (affineBlowUp.chart (Ideal.span {g}) ⟨g, Ideal.mem_span_singleton_self g⟩ ≫
      affineBlowUp.π (Ideal.span {g})) := by
    rw [affineBlowUp.chart_π]
    infer_instance
  exact IsIso.of_isIso_comp_left
    (affineBlowUp.chart (Ideal.span {g}) ⟨g, Ideal.mem_span_singleton_self g⟩) _

end Principal

section Rees

variable {R : Type u} [CommRing R] (g : R)

/-- `v ↦ g t`: the `R`-algebra map from the polynomial ring `R[v]` to the Rees algebra of the
principal ideal `(g)` [Hau14, Example 4.29]. -/
noncomputable def _root_.Hironaka.BlowUp.reesAlgebra.ofPolynomial : R[X] →ₐ[R] reesAlgebra
    (Ideal.span {g}) :=
  aeval (reesAlgebra.degreeOne (Ideal.span {g}) ⟨g, Ideal.mem_span_singleton_self g⟩)

/-- In `R[t]`, the image of `p(v)` is `p(g t)`, the substitution `v ↦ g t`. -/
theorem _root_.Hironaka.BlowUp.reesAlgebra.coe_ofPolynomial (p : R[X]) :
    (Hironaka.BlowUp.reesAlgebra.ofPolynomial g p : R[X]) = p.comp (C g * X) := by
  rw [comp_eq_aeval, C_mul_X_eq_monomial, Hironaka.BlowUp.reesAlgebra.ofPolynomial,
    ← reesAlgebra.coe_degreeOne (I := Ideal.span {g}) ⟨g, Ideal.mem_span_singleton_self g⟩]
  exact (aeval_algHom_apply (reesAlgebra (Ideal.span {g})).val _ p).symm

/-- `v ↦ g t` is injective for a nonzerodivisor `g`: the `n`-th coefficient of `p(g t)` is
`pₙ gⁿ`. -/
theorem _root_.Hironaka.BlowUp.reesAlgebra.ofPolynomial_injective (hg : g ∈ nonZeroDivisors R) :
    Function.Injective (Hironaka.BlowUp.reesAlgebra.ofPolynomial g) := by
  refine (injective_iff_map_eq_zero _).mpr fun p hp => (comp_C_mul_X_eq_zero_iff hg).mp ?_
  rw [← Hironaka.BlowUp.reesAlgebra.coe_ofPolynomial, hp, Subalgebra.coe_zero]

/-- `v ↦ g t` is surjective: the Rees algebra of `(g)` is generated over `R` by `g t`
(Mathlib's `adjoin_monomial_eq_reesAlgebra`, with `monomial 1 (r g) = C r * monomial 1 g`). -/
theorem _root_.Hironaka.BlowUp.reesAlgebra.ofPolynomial_surjective :
    Function.Surjective (Hironaka.BlowUp.reesAlgebra.ofPolynomial g) := by
  rintro ⟨q, hq⟩
  have hadj : reesAlgebra (Ideal.span {g}) ≤ Algebra.adjoin R {monomial 1 g} := by
    rw [← adjoin_monomial_eq_reesAlgebra]
    refine Algebra.adjoin_le ?_
    rintro _ ⟨r, hr, rfl⟩
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hr
    change monomial 1 (c * g) ∈ Algebra.adjoin R {monomial 1 g}
    rw [← C_mul_monomial]
    exact Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ c)
      (Algebra.subset_adjoin (Set.mem_singleton _))
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hadj
  obtain ⟨p, hp⟩ := hadj hq
  refine ⟨p, Subtype.ext ?_⟩
  rw [Hironaka.BlowUp.reesAlgebra.coe_ofPolynomial, comp_eq_aeval, C_mul_X_eq_monomial]
  exact hp

/-- For a nonzerodivisor `g`, **the Rees algebra `R[gt]` is isomorphic to the polynomial ring
`R[v]`**, by `v ↦ g t` [Hau14, Example 4.29]. -/
noncomputable def _root_.Hironaka.BlowUp.reesAlgebra.polynomialEquiv (hg : g ∈ nonZeroDivisors R) :
    R[X] ≃ₐ[R] reesAlgebra (Ideal.span {g}) :=
  AlgEquiv.ofBijective (Hironaka.BlowUp.reesAlgebra.ofPolynomial g)
    ⟨Hironaka.BlowUp.reesAlgebra.ofPolynomial_injective g hg,
        Hironaka.BlowUp.reesAlgebra.ofPolynomial_surjective g⟩

/-- The isomorphism is graded ("`deg r = 0` for `r ∈ R` and `deg v = 1`"): the monomial `r vⁿ`
goes to `r gⁿ tⁿ`, an element of degree `n` of the Rees algebra. -/
theorem _root_.Hironaka.BlowUp.reesAlgebra.ofPolynomial_monomial_mem_grading (n : ℕ) (r : R) :
    Hironaka.BlowUp.reesAlgebra.ofPolynomial g (monomial n r) ∈ reesAlgebra.grading (Ideal.span
        {g}) n := by
  refine reesAlgebra.mem_grading_of_coe_eq_monomial (c := r * g ^ n) ?_
  rw [Hironaka.BlowUp.reesAlgebra.coe_ofPolynomial]
  ext m
  rw [comp_C_mul_X_coeff, coeff_monomial, coeff_monomial]
  split_ifs with h
  · subst h
    rfl
  · rw [zero_mul]

end Rees

end AlgebraicGeometry
