/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.AlgebraicGeometry.IdealSheaf.Basic
public import Mathlib.AlgebraicGeometry.IdealSheaf.Subscheme
public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial

/-!
# Ideal sheaves on a scheme: stalks, order, invertibility, colon

The operations on and predicates of Mathlib's ideal sheaves `X.IdealSheafData` of a scheme `X`
that the library adds.

* The **stalk** `J_x ⊆ 𝒪_{X,x}` of an ideal sheaf at a point: the ideal generated by the germs at
  `x` of the sections of `J` over the affine opens containing `x` (Hironaka's `J_x`
  [Hir64, Ch. 0, §5, p. 142]). Every such open gives the same ideal, and the supremum over all of
  them makes the definition choice-free.
* `IsNonzeroEverywhere J`: Hironaka's "coherent sheaf of non-zero ideals" [Hir64, Main Theorem II],
  read stalkwise.
* The **order** of `J` at `x`: Hironaka's `ν(J_x)`, the largest `ν` with `J_x ⊆ 𝔪_x^ν`
  [Hir64, Ch. 0, §4]; Kollár's `ord_x J` [Kol07, Definition 47]; valued in `ℕ∞`, so that the zero
  ideal has order `⊤`.
* `IsInvertible J`: the closed subscheme of `J` is an effective Cartier divisor, `J` being
  generated on an affine neighbourhood of every point by a nonzerodivisor [Sta, Tag 01WS]. Mathlib
  has no invertible ideal sheaves on schemes, so this local characterisation is the definition. On
  a locally Noetherian scheme it is equivalent to its stalkwise reading, every `J_x` generated by
  a nonzerodivisor of `𝒪_{X,x}` (the standing assumption of Hironaka's Definition 2
  [Hir64, Ch. 0, §5, Definition 2]): `isInvertible_iff_forall_stalkIdeal_eq_span` of
  `Hironaka/Scheme/IdealSheaf/Invertible.lean`.
* The **colon** ideal sheaf `(I : K)`, the largest ideal sheaf whose sections over every affine open
  lie in the colon ideal `(I(U) : K(U))`, and the `K`-power torsion **saturation**
  `⋃ᵢ (I : Kⁱ)` of `I` [Hau14, Definition 6.2]; [Sta, Tag 080D]. The transforms of an ideal sheaf
  under a blow-up are built from them.
-/

@[expose] public section

universe u

open CategoryTheory TopologicalSpace

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : Scheme.{u}}

/-- The stalk `J_x ⊆ 𝒪_{X,x}` of an ideal sheaf: the ideal generated by the germs at `x` of the
sections of `J` over the affine opens containing `x` (every such open gives the same ideal,
`stalkIdeal_eq_map_germ`; the supremum makes the definition choice-free)
[Hir64, Ch. 0, §5, p. 142]. -/
noncomputable def stalkIdeal (J : X.IdealSheafData) (x : X) : Ideal (X.presheaf.stalk x) :=
  ⨆ (U : X.affineOpens) (hx : x ∈ U.1), (J.ideal U).map (X.presheaf.germ U.1 x hx).hom

/-- Hironaka's "coherent sheaf of non-zero ideals" [Hir64, Main Theorem II; Corollary 1], read
stalkwise: `J_x ≠ 0` at every point. On a non-singular scheme this is Kollár's "not zero on any
irreducible component" [Kol07, Theorem 35]. -/
def IsNonzeroEverywhere (J : X.IdealSheafData) : Prop :=
  ∀ x : X, J.stalkIdeal x ≠ ⊥

/-- [Kol07, Definition 47]: **the order of the ideal sheaf `I` at the point `x`**, the largest `m`
with `I_x ⊆ 𝔪_xᵐ` in `𝒪_{X,x}`, as an element of `ℕ∞` (`⊤` exactly when `I_x = 0`); Hironaka's
`ν(J_x)` [Hir64, Ch. 0, §4]. -/
noncomputable def ord (I : X.IdealSheafData) (x : X) : ℕ∞ :=
  sSup {n : ℕ∞ | ∃ m : ℕ, n = m ∧
    stalkIdeal I x ≤ IsLocalRing.maximalIdeal (X.presheaf.stalk x) ^ m}

/-- An ideal sheaf `J` on `X` is *invertible* (its closed subscheme is an effective Cartier divisor
[Sta, Tag 01WS]; [Kol07, Warning 20]) if every point `x` has an affine open neighbourhood `U` and
a nonzerodivisor `f ∈ Γ(X, U)` with `J(U) = (f)`. -/
def IsInvertible (J : X.IdealSheafData) : Prop :=
  ∀ x : X, ∃ U : X.affineOpens, x ∈ U.1 ∧
    ∃ f ∈ nonZeroDivisors Γ(X, U), J.ideal U = Ideal.span {f}

/-- The colon ideal sheaf `(I : K)`: the largest ideal sheaf whose sections over every affine open
lie in the colon ideal `(I(U) : K(U))`; equivalently (`le_colon_iff_mul_le`) the largest `J` with
`J * K ≤ I`. -/
def colon (I K : X.IdealSheafData) : X.IdealSheafData :=
  ofIdeals fun U => (I.ideal U).colon (K.ideal U : Set Γ(X, U))

/-- The `K`-power torsion saturation `⋃ᵢ (I : Kⁱ)` of `I` [Hau14, Definition 6.2];
[Sta, Tag 080D] (the sections supported on the divisor). -/
def saturate (I K : X.IdealSheafData) : X.IdealSheafData := ⨆ i : ℕ, I.colon (K ^ i)

end AlgebraicGeometry.Scheme.IdealSheafData
