/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.IdealSheaf.Defs
public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Hironaka.Scheme.BlowUp.InverseImage
import Hironaka.Scheme.BlowUp.InvertibleSheaf

/-!
# The stalk of an ideal sheaf

For an ideal sheaf `J` on a scheme `X` and a point `x`, the **stalk ideal**
`J.stalkIdeal x ⊆ 𝒪_{X,x}` is the ideal generated by the germs at `x` of the sections of `J` over
the affine opens containing `x` (Hironaka's `J_x` [Hir64, Ch. 0, §5, p. 142]).  Every such open
gives the same ideal (`stalkIdeal_eq_map_germ`), so the supremum over all of them is a choice-free
definition. It is the stalk used in the statements of the main theorems.

The stalk of an inverse image ideal sheaf: `stalkIdeal_comap` says that the stalk of `I.comap f`
at `y` is the image of the stalk of `I` at `f y` under `f.stalkMap y` (the affine computation
`map_germ_ideal_comap`, read through the stalks; compare the proof of [Sta, Tag 0805]).
`stalkIdeal_eq_span_iff_of_isOpenImmersion` is the corresponding statement for generators along an
open immersion.  These are the forms in which the universal property of the affine blow-up handles
stalks.

The stalk of an invertible ideal sheaf is generated by a nonzerodivisor
(`IsInvertible.exists_mem_nonZeroDivisors_stalkIdeal_eq_span`); on a locally Noetherian scheme this
stalkwise condition is equivalent to invertibility (`Hironaka/Scheme/IdealSheaf/Invertible.lean`).
-/

public section

namespace AlgebraicGeometry.Scheme.IdealSheafData

open CategoryTheory TopologicalSpace

universe u

variable {X Y : Scheme.{u}}

theorem map_germ_le_stalkIdeal (J : X.IdealSheafData) (U : X.affineOpens) {x : X}
    (hx : x ∈ U.1) : (J.ideal U).map (X.presheaf.germ U.1 x hx).hom ≤ J.stalkIdeal x :=
  le_iSup₂ (f := fun (U : X.affineOpens) (hx : x ∈ U.1) =>
    (J.ideal U).map (X.presheaf.germ U.1 x hx).hom) U hx

/-- Germs of sections over a smaller affine open give the same ideal: `J(W) = J(V) Γ(W)` for
affine `W ≤ V` (Mathlib's `map_ideal`) and `germ ∘ res = germ`. -/
theorem map_germ_eq_of_le (J : X.IdealSheafData) {V W : X.affineOpens} (h : W ≤ V) {x : X}
    (hx : x ∈ W.1) :
    (J.ideal W).map (X.presheaf.germ W.1 x hx).hom =
      (J.ideal V).map (X.presheaf.germ V.1 x (h hx)).hom := by
  rw [← J.map_ideal h, Ideal.map_map, ← CommRingCat.hom_comp,
    show X.presheaf.map (homOfLE h).op ≫ X.presheaf.germ W.1 x hx =
      X.presheaf.germ V.1 x (h hx) from X.presheaf.germ_res (homOfLE h) x hx]

/-- Every affine open `U ∋ x` computes the stalk ideal: `J_x` is the image of `J(U)` under the
germ map. -/
theorem stalkIdeal_eq_map_germ (J : X.IdealSheafData) (U : X.affineOpens) {x : X} (hx : x ∈ U.1) :
    J.stalkIdeal x = (J.ideal U).map (X.presheaf.germ U.1 x hx).hom := by
  refine le_antisymm (iSup₂_le fun V hxV => ?_) (map_germ_le_stalkIdeal J U hx)
  obtain ⟨s, t, hst, hxs⟩ := exists_basicOpen_le_affine_inter U.2 V.2 x ⟨hx, hxV⟩
  have hWU : X.affineBasicOpen s ≤ U := X.basicOpen_le s
  have hWV : X.affineBasicOpen s ≤ V := by
    change X.basicOpen s ≤ V.1
    rw [hst]
    exact X.basicOpen_le t
  exact ((map_germ_eq_of_le J hWV hxs).symm.trans (map_germ_eq_of_le J hWU hxs)).le

/-- The stalk of the inverse image `I.comap f` at `y` is generated by the image under
`f.stalkMap y` of the stalk of `I` at `f y` (compare the proof of [Sta, Tag 0805]). -/
theorem stalkIdeal_comap (I : X.IdealSheafData) (f : Y ⟶ X) (y : Y) :
    (I.comap f).stalkIdeal y = (I.stalkIdeal (f y)).map (f.stalkMap y).hom := by
  obtain ⟨U, hU⟩ := exists_affineOpens_mem (f y)
  obtain ⟨V, hV, e⟩ : ∃ V : Y.affineOpens, y ∈ V.1 ∧ V.1 ≤ f ⁻¹ᵁ U.1 := by
    obtain ⟨V₀, hV₀⟩ := exists_affineOpens_mem y
    obtain ⟨s, hs_le, hys⟩ := V₀.2.exists_basicOpen_le (V := f ⁻¹ᵁ U.1) ⟨y, hU⟩ hV₀
    exact ⟨Y.affineBasicOpen s, hys, hs_le⟩
  rw [stalkIdeal_eq_map_germ _ V hV, stalkIdeal_eq_map_germ _ U hU,
    map_germ_ideal_comap I f y U V hV e]

/-- The germ of `f♯s` (`s` a section over `U ⊆ X`, restricted along `f` to `V ⊆ f⁻¹U`) at `z ∈ V` is
the stalk map applied to the germ of `s` at `f z`. -/
theorem _root_.AlgebraicGeometry.Scheme.Hom.germ_appLE_apply {X Y : Scheme.{u}} (f : Y ⟶ X)
    (U : X.Opens) (V : Y.Opens) (e : V ≤ f ⁻¹ᵁ U) {z : Y} (hz : z ∈ V) (hfz : f z ∈ U)
    (s : Γ(X, U)) :
    Y.presheaf.germ V z hz (f.appLE U V e s) = f.stalkMap z (X.presheaf.germ U (f z) hfz s) := by
  rw [Scheme.Hom.germ_stalkMap_apply, Scheme.Hom.appLE, CommRingCat.comp_apply,
    TopCat.Presheaf.germ_res_apply]

/-- A nonzerodivisor of `Γ(X, V)`, `V` affine, has a nonzerodivisor germ at every point of `V`: the
stalk is a localization of `Γ(X, V)` (Mathlib's `IsAffineOpen.isLocalization_stalk`). -/
theorem germ_mem_nonZeroDivisors (V : X.affineOpens) {x : X} (hx : x ∈ V.1) {s : Γ(X, V)}
    (hs : s ∈ nonZeroDivisors Γ(X, V)) :
    X.presheaf.germ V.1 x hx s ∈ nonZeroDivisors (X.presheaf.stalk x) := by
  have hloc := V.2.isLocalization_stalk ⟨x, hx⟩
  have hle := @IsLocalization.map_nonZeroDivisors_le Γ(X, V) _
    (V.2.primeIdealOf ⟨x, hx⟩).asIdeal.primeCompl (X.presheaf.stalk x) _
    (TopCat.Presheaf.algebra_section_stalk X.presheaf ⟨x, hx⟩) hloc
  exact hle ⟨_, hs, rfl⟩

/-- The stalk of an invertible ideal sheaf at any point is generated by a nonzerodivisor. -/
theorem IsInvertible.exists_mem_nonZeroDivisors_stalkIdeal_eq_span {J : X.IdealSheafData}
    (hJ : J.IsInvertible) (x : X) :
    ∃ h ∈ nonZeroDivisors (X.presheaf.stalk x), J.stalkIdeal x = Ideal.span {h} := by
  obtain ⟨V, hxV, s, hs, hJV⟩ := hJ x
  refine ⟨X.presheaf.germ V.1 x hxV s, germ_mem_nonZeroDivisors V hxV hs, ?_⟩
  rw [stalkIdeal_eq_map_germ J V hxV, hJV, Ideal.map_span, Set.image_singleton]

/-- The stalk of the vanishing ideal of a closed set depends only on the trace of the set on an
affine neighbourhood of the point. -/
theorem _root_.AlgebraicGeometry.stalkIdeal_vanishingIdeal_congr {Z Z' : Closeds X}
    (U : X.affineOpens) {x : X}
    (hx : x ∈ U.1) (h : ∀ y ∈ U.1, y ∈ Z ↔ y ∈ Z') :
    (vanishingIdeal Z).stalkIdeal x = (vanishingIdeal Z').stalkIdeal x := by
  have hideal : (vanishingIdeal Z).ideal U = (vanishingIdeal Z').ideal U := by
    simp only [vanishingIdeal_ideal]
    congr 1
    ext p
    have hp : U.2.fromSpec p ∈ U.1 := by
      rw [← SetLike.mem_coe, ← U.2.range_fromSpec]
      exact Set.mem_range_self p
    exact h _ hp
  rw [stalkIdeal_eq_map_germ _ U hx, stalkIdeal_eq_map_germ _ U hx, hideal]

end AlgebraicGeometry.Scheme.IdealSheafData
