/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.Smooth.Basic
public import Mathlib.RingTheory.Localization.AtPrime.Basic
import Hironaka.Algebra.RegularSmooth.Polynomial

/-!
# The localized presentation `k[x]_Q → S_𝔮` of a local ring of a finite type algebra

Mathlib's Jacobian criterion, applied in `Hironaka/Algebra/RegularSmooth/RegularImpliesSmooth.lean`
to show that a regular local ring of a finite type algebra over a field is smooth, is used on the
presentation of `R = S_𝔮` by `P = k[x_1, …, x_N]_Q`, `Q` the preimage of `𝔮` under a surjection
`φ : k[x] → S`, as in the proof of [Sta, Tag 00TS]. This file records what the criterion needs of
the presentation: the localized map `P → S_𝔮` (Mathlib's `Localization.localRingHom`) is
surjective, its kernel is the ideal generated by `ker φ` (an element of `P` maps to zero iff a
denominator outside `Q` clears it into `ker φ`) and finitely generated since `P` is Noetherian;
`P` is formally smooth over `k` (a polynomial ring, then a localization) with `Ω[P⁄k]` finite free
on the `d x_i`; and the localized map is a local homomorphism inducing an isomorphism of residue
fields. The surjectivity and kernel statements hold for any surjection of commutative rings.
-/

public section

universe u v

open IsLocalRing

namespace Localization

variable {A S : Type*} [CommRing A] [CommRing S] (φ : A →+* S) (𝔮 : Ideal S) [𝔮.IsPrime]

/-- The localization at `Q = φ⁻¹(𝔮)` of a surjection `φ : A → S` is a surjection `A_Q → S_𝔮` (as in
the proof of [Sta, Tag 00TS]). -/
theorem localRingHom_surjective_of_surjective (hφ : Function.Surjective φ) :
    Function.Surjective (localRingHom (𝔮.comap φ) 𝔮 φ rfl) := by
  intro z
  obtain ⟨⟨y, s⟩, rfl⟩ := IsLocalization.mk'_surjective 𝔮.primeCompl z
  dsimp only
  obtain ⟨y', rfl⟩ := hφ y
  obtain ⟨s', hs'⟩ := hφ (s : S)
  have hs'Q : s' ∈ (𝔮.comap φ).primeCompl := by
    change s' ∉ 𝔮.comap φ
    rw [Ideal.mem_comap, hs']
    exact s.2
  refine ⟨IsLocalization.mk' (Localization.AtPrime (𝔮.comap φ)) y' ⟨s', hs'Q⟩, ?_⟩
  rw [localRingHom_mk']
  congr 1
  exact Subtype.ext hs'

/-- The kernel of the localized surjection `A_Q → S_𝔮` is the ideal generated by `ker φ`: a fraction
maps to zero iff a denominator outside `Q` clears its numerator into `ker φ`. -/
theorem ker_localRingHom_of_surjective (hφ : Function.Surjective φ) :
    RingHom.ker (localRingHom (𝔮.comap φ) 𝔮 φ rfl) =
      (RingHom.ker φ).map (algebraMap A (Localization.AtPrime (𝔮.comap φ))) := by
  apply le_antisymm
  · intro x hx
    obtain ⟨⟨a, s⟩, rfl⟩ := IsLocalization.mk'_surjective (𝔮.comap φ).primeCompl x
    dsimp only at hx ⊢
    rw [RingHom.mem_ker, localRingHom_mk', IsLocalization.mk'_eq_zero_iff] at hx
    obtain ⟨⟨t, ht⟩, ht0⟩ := hx
    obtain ⟨t', rfl⟩ := hφ t
    have ht' : t' ∈ (𝔮.comap φ).primeCompl := by
      change t' ∉ 𝔮.comap φ
      rw [Ideal.mem_comap]
      exact ht
    have hmem : t' * a ∈ RingHom.ker φ := by
      rw [RingHom.mem_ker, map_mul]
      exact ht0
    have hx' : IsLocalization.mk' (Localization.AtPrime (𝔮.comap φ)) a s =
        algebraMap A (Localization.AtPrime (𝔮.comap φ)) (t' * a) *
          IsLocalization.mk' (Localization.AtPrime (𝔮.comap φ)) (1 : A) (⟨t', ht'⟩ * s) := by
      rw [← IsLocalization.mk'_eq_mul_mk'_one, IsLocalization.mk'_eq_iff_eq]
      simp only [Submonoid.coe_mul]
      congr 1
      ring
    rw [hx']
    exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ hmem)
  · rw [Ideal.map_le_iff_le_comap]
    intro a ha
    rw [Ideal.mem_comap, RingHom.mem_ker, localRingHom_to_map, RingHom.mem_ker.mp ha, map_zero]

/-- The localized surjection `A_Q → S_𝔮` induces an isomorphism of residue fields. -/
theorem bijective_residueField_map_localRingHom_of_surjective (hφ : Function.Surjective φ) :
    letI := isLocalHom_localRingHom (I := 𝔮.comap φ) 𝔮 φ rfl
    Function.Bijective (ResidueField.map (localRingHom (𝔮.comap φ) 𝔮 φ rfl)) := by
  have := isLocalHom_localRingHom (I := 𝔮.comap φ) 𝔮 φ rfl
  refine ⟨(ResidueField.map _).injective, fun z => ?_⟩
  obtain ⟨w, rfl⟩ := residue_surjective z
  obtain ⟨v, rfl⟩ := localRingHom_surjective_of_surjective φ 𝔮 hφ w
  exact ⟨residue _ v, ResidueField.map_residue _ v⟩

end Localization

namespace MvPolynomial

variable {k : Type u} [Field k] {ι : Type v} [Finite ι] (Q : Ideal (MvPolynomial ι k)) [Q.IsPrime]

omit [Finite ι] in
/-- `k[x]_Q` is formally smooth over `k` (a polynomial ring, then a localization). -/
theorem formallySmooth_localization_atPrime : Algebra.FormallySmooth k (Localization.AtPrime Q) :=
  have : Algebra.FormallySmooth (MvPolynomial ι k) (Localization.AtPrime Q) :=
    Algebra.FormallySmooth.of_isLocalization (Rₘ := Localization.AtPrime Q) Q.primeCompl
  Algebra.FormallySmooth.comp k (MvPolynomial ι k) (Localization.AtPrime Q)

omit [Finite ι] in
/-- `Ω[k[x]_Q ⁄ k]` is free, on the `d x_i` [Sta, Tags 00RX, 00RT]. -/
theorem free_kaehlerDifferential_localization_atPrime :
    Module.Free (Localization.AtPrime Q) Ω[Localization.AtPrime Q⁄k] :=
  Module.Free.of_basis (KaehlerDifferential.mvPolynomialLocalizationBasis Q)

/-- `Ω[k[x]_Q ⁄ k]` is a finite module (finitely many variables). -/
theorem finite_kaehlerDifferential_localization_atPrime :
    Module.Finite (Localization.AtPrime Q) Ω[Localization.AtPrime Q⁄k] :=
  Module.Finite.of_basis (KaehlerDifferential.mvPolynomialLocalizationBasis Q)

/-- Every ideal of `k[x]_Q` is finitely generated (`k[x]_Q` is Noetherian). -/
theorem fg_of_localization_atPrime (I : Ideal (Localization.AtPrime Q)) : I.FG :=
  have : IsNoetherianRing (Localization.AtPrime Q) :=
    IsLocalization.isNoetherianRing Q.primeCompl (Localization.AtPrime Q) inferInstance
  IsNoetherian.noetherian I

end MvPolynomial
