/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.RegularLocalRing.Defs

/-!
# Quotients of a regular local ring by part of a regular system of parameters

The dimension part of [Sta, Tag 00NQ]: if `R` is a regular local ring and `f_1, …, f_c ∈ 𝔪` have
linearly independent classes in `𝔪/𝔪²`, then `R/(f_1, …, f_c)` is a regular local ring of
dimension `dim R - c`. This is the form used to show that a smooth algebra has regular local
rings (`Hironaka/Algebra/RegularSmooth/SmoothImpliesRegular.lean`) and to count regular systems of
parameters (`Hironaka/Algebra/RegularSmooth/ParameterCount.lean`). The proof is a count.
*Generators.* The classes of the `f_j` extend to a basis of `𝔪/𝔪²` (`Basis.sumExtend`); lifting the
new basis vectors to `y_1, …, y_e ∈ 𝔪`, the family `f_1, …, f_c, y_1, …, y_e` spans `𝔪/𝔪²`, hence
generates `𝔪` by Nakayama (Mathlib's `CotangentSpace.span_image_eq_top_iff`), so the maximal
ideal of the quotient is generated by the images of the `y_i` alone: its span rank is at most
`e = dim 𝔪/𝔪² - c = dim R - c`, the last equality being the definition of regularity together
with `spanFinrank_maximalIdeal_eq_finrank_cotangentSpace`. *Dimension.* Krull's height theorem
in the form `dim R ≤ dim R/(f_1, …, f_c) + c` (`ringKrullDim_le_ringKrullDim_quotient_add_card`).
Together: the span rank of the quotient's maximal ideal is at most its dimension, which is
regularity (`IsRegularLocalRing.of_spanFinrank_maximalIdeal_le`), and then the two inequalities
pinch the dimension to `dim R - c`. No "regular implies domain" is needed; the case `c = 1` is
`IsRegularLocalRing.quotient_span_singleton` of `Hironaka/Algebra/Local/Regular.lean`, not used
here. The dimension arithmetic lives in `WithBot ℕ∞` and is done by extracting natural numbers.
-/

public section

universe u

open IsLocalRing

namespace IsRegularLocalRing

variable {R : Type u} [CommRing R] [IsRegularLocalRing R]

/-- The dimension part of [Sta, Tag 00NQ]: if `f : ι → R` takes values in `𝔪` with linearly
independent classes in `𝔪/𝔪²`, then `R ⧸ (f i)` is a regular local ring and
`dim R ⧸ (f i) + |ι| = dim R`. -/
theorem quotient_span_range_of_linearIndependent {ι : Type*} [Fintype ι] (f : ι → R)
    (hf : ∀ i, f i ∈ maximalIdeal R)
    (hli : LinearIndependent (ResidueField R) fun i => (maximalIdeal R).toCotangent ⟨f i, hf i⟩) :
    IsRegularLocalRing (R ⧸ Ideal.span (Set.range f)) ∧
      ringKrullDim (R ⧸ Ideal.span (Set.range f)) + Fintype.card ι = ringKrullDim R := by
  classical
  set I := Ideal.span (Set.range f) with hI
  have hIle : I ≤ maximalIdeal R := Ideal.span_le.mpr (by rintro _ ⟨i, rfl⟩; exact hf i)
  have hIne : I ≠ ⊤ := ne_top_of_le_ne_top (maximalIdeal.isMaximal R).ne_top hIle
  have : Nontrivial (R ⧸ I) := Ideal.Quotient.nontrivial_iff.mpr hIne
  have : IsLocalRing (R ⧸ I) :=
    IsLocalRing.of_surjective' (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  -- the maximal ideal of the quotient is the image of `𝔪`
  have hmax : maximalIdeal (R ⧸ I) = (maximalIdeal R).map (Ideal.Quotient.mk I) := by
    refine (IsLocalRing.eq_maximalIdeal ?_).symm
    refine (Ideal.map_eq_top_or_isMaximal_of_surjective _ Ideal.Quotient.mk_surjective
      (maximalIdeal.isMaximal R)).resolve_left fun h => ?_
    have := Ideal.comap_map_of_surjective (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
      (maximalIdeal R)
    rw [h, Ideal.comap_top, ← RingHom.ker_eq_comap_bot, Ideal.mk_ker, sup_eq_left.mpr hIle] at this
    exact (maximalIdeal.isMaximal R).ne_top this.symm
  -- a basis of `𝔪/𝔪²` extending the classes of the `f i`, and lifts of the new vectors to `𝔪`
  set b := Module.Basis.sumExtend hli with hb
  have hfin := Module.Finite.finite_basis b
  have : Finite (Module.Basis.sumExtendIndex hli) :=
    Finite.of_injective (Sum.inr : Module.Basis.sumExtendIndex hli → ι ⊕ _) Sum.inr_injective
  have hb_inl : ∀ i, b (Sum.inl i) = (maximalIdeal R).toCotangent ⟨f i, hf i⟩ := fun i => by
    rw [hb]
    unfold Module.Basis.sumExtend
    rw [Module.Basis.reindex_apply, Module.Basis.extend_apply_self]
    rfl
  choose y hy using fun j : Module.Basis.sumExtendIndex hli =>
    (maximalIdeal R).toCotangent_surjective (b (Sum.inr j))
  let g : ι ⊕ Module.Basis.sumExtendIndex hli → maximalIdeal R := Sum.elim (fun i => ⟨f i, hf i⟩) y
  have hg : ((maximalIdeal R).toCotangent ∘ g) = b := by
    funext s
    rcases s with i | j
    · exact (hb_inl i).symm
    · exact hy j
  -- Nakayama: the family `g` generates `𝔪`
  have hspan : Submodule.span R (Set.range g) = ⊤ := by
    rw [← CotangentSpace.span_image_eq_top_iff, ← Set.range_comp, hg]
    exact b.span_eq
  have hm : maximalIdeal R = Ideal.span (Set.range fun s => ((g s : maximalIdeal R) : R)) := by
    have := congrArg (Submodule.map (maximalIdeal R).subtype) hspan
    rw [Submodule.map_span, Submodule.map_top, Submodule.range_subtype, ← Set.range_comp] at this
    exact this.symm
  -- in the quotient the `f i` vanish: the maximal ideal is generated by the images of the `y j`
  have hmbar : maximalIdeal (R ⧸ I) =
      Ideal.span (Set.range fun j => Ideal.Quotient.mk I (y j : R)) := by
    have hm' := congrArg (Ideal.map (Ideal.Quotient.mk I)) hm
    rw [hmax, hm', Ideal.map_span, ← Set.range_comp]
    apply le_antisymm
    · rw [Ideal.span_le]
      rintro _ ⟨s, rfl⟩
      rcases s with i | j
      · have hfi : f i ∈ I := Ideal.subset_span (Set.mem_range_self i)
        change Ideal.Quotient.mk I (f i) ∈ _
        rw [Ideal.Quotient.eq_zero_iff_mem.mpr hfi]
        exact zero_mem _
      · change Ideal.Quotient.mk I (y j : R) ∈ _
        exact Ideal.subset_span (Set.mem_range_self j)
    · refine Ideal.span_mono ?_
      rintro _ ⟨j, rfl⟩
      exact ⟨Sum.inr j, rfl⟩
  -- generators: the span rank of the quotient's maximal ideal is at most `|J|`
  have h1 : (maximalIdeal (R ⧸ I)).spanFinrank ≤ Nat.card (Module.Basis.sumExtendIndex hli) := by
    rw [hmbar]
    refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)).trans ?_
    rw [← Set.image_univ]
    exact (Set.ncard_image_le Set.finite_univ).trans (by rw [Set.ncard_univ])
  -- `dim R = |ι| + |J|`
  have hdimR : ringKrullDim R =
      ((Fintype.card ι + Nat.card (Module.Basis.sumExtendIndex hli) : ℕ) : WithBot ℕ∞) := by
    rw [← IsRegularLocalRing.spanFinrank_maximalIdeal,
      spanFinrank_maximalIdeal_eq_finrank_cotangentSpace, Module.finrank_eq_nat_card_basis b,
      Nat.card_sum, Nat.card_eq_fintype_card]
  -- Krull: `dim R ≤ dim R/I + |ι|`
  have h2 : ringKrullDim R ≤ ringKrullDim (R ⧸ I) + Fintype.card ι := by
    have hs : ((Finset.univ.image f : Finset R) : Set R) ⊆ Ring.jacobson R := by
      rw [Finset.coe_image, Finset.coe_univ, Set.image_univ, ← Ideal.jacobson_bot,
        IsLocalRing.jacobson_eq_maximalIdeal ⊥ bot_ne_top]
      rintro _ ⟨i, rfl⟩
      exact hf i
    have := ringKrullDim_le_ringKrullDim_quotient_add_card (Finset.univ.image f) hs
    rw [Finset.coe_image, Finset.coe_univ, Set.image_univ, ← hI] at this
    refine this.trans ?_
    gcongr
    exact_mod_cast Finset.card_image_le.trans Finset.card_univ.le
  -- the dimension of the quotient is a natural number
  obtain ⟨d, hd⟩ : ∃ d : ℕ, ringKrullDim (R ⧸ I) = d := by
    have hne_top : ringKrullDim (R ⧸ I) ≠ ⊤ := ringKrullDim_ne_top
    have hne_bot : ringKrullDim (R ⧸ I) ≠ ⊥ :=
      ((WithBot.bot_lt_coe (0 : ℕ∞)).trans_le ringKrullDim_nonneg_of_nontrivial).ne'
    obtain ⟨e, he⟩ := WithBot.ne_bot_iff_exists.mp hne_bot
    have he_top : e ≠ ⊤ := fun h => hne_top (by rw [← he, h]; rfl)
    obtain ⟨d, rfl⟩ := ENat.ne_top_iff_exists.mp he_top
    exact ⟨d, by rw [← he]; rfl⟩
  have hcardJ : Nat.card (Module.Basis.sumExtendIndex hli) ≤ d := by
    have := h2
    rw [hdimR, hd] at this
    have : Fintype.card ι + Nat.card (Module.Basis.sumExtendIndex hli) ≤ d + Fintype.card ι := by
      exact_mod_cast this
    omega
  have hreg : IsRegularLocalRing (R ⧸ I) :=
    IsRegularLocalRing.of_spanFinrank_maximalIdeal_le (R ⧸ I)
      (by rw [hd]; exact_mod_cast h1.trans hcardJ)
  refine ⟨hreg, ?_⟩
  have hsp : ((maximalIdeal (R ⧸ I)).spanFinrank : WithBot ℕ∞) = d := by
    rw [hreg.spanFinrank_maximalIdeal, hd]
  have hsp' : (maximalIdeal (R ⧸ I)).spanFinrank = d := by exact_mod_cast hsp
  have hdJ : d = Nat.card (Module.Basis.sumExtendIndex hli) := le_antisymm (hsp' ▸ h1) hcardJ
  rw [hd, hdimR, hdJ]
  norm_cast
  omega

end IsRegularLocalRing
