/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.Smooth.Locus
public import Mathlib.FieldTheory.Perfect
public import Mathlib.RingTheory.RegularLocalRing.Defs
import Hironaka.Algebra.Local.QuotientParameters
import Hironaka.Algebra.Local.RegularSystem
import Hironaka.Algebra.RegularSmooth.Cotangent
import Hironaka.Algebra.RegularSmooth.Polynomial
import Hironaka.Algebra.RegularSmooth.Presentation
import Mathlib.RingTheory.Smooth.Field
import Mathlib.RingTheory.Smooth.Local

/-!
# Regular implies smooth

The implication (2) ⇒ (1) of [Sta, Tag 00TV]: if `S` is a finite type algebra over the field `k`
and `𝔮 ⊆ S` a prime with `S_𝔮` a regular local ring and residue field `κ` formally smooth over
`k`, then `S` is smooth at `𝔮`. The proof goes through Mathlib's Jacobian criterion as follows.

*The presentation.* Choose a surjection `φ : k[x_1, …, x_N] → S`, put `Q = φ⁻¹(𝔮)`, `P = k[x]_Q`,
`R = S_𝔮`; the localized map `g : P → R` is a local surjection with finitely generated kernel `I`,
`P` is formally smooth over `k` with `Ω[P⁄k]` finite free (`Presentation.lean`), so
Mathlib's Jacobian criterion
(`FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField`) reduces smoothness of
`R` over `k` to the injectivity of `κ ⊗_P I → κ ⊗_P Ω[P⁄k]`,
`a ⊗ y ↦ a · (1 ⊗ d y)`, where `κ = κ(R)`.

*The kernel is generated by parameters.* `P` is regular local (`Polynomial.lean`) and `P/I ≅ R` is
regular local, so by [Sta, Tag 00NR] (`Hironaka/Algebra/Local/QuotientParameters.lean`) `I` is
generated by an initial segment `x_1, …, x_c` of a regular system of parameters of `P`. Hence
`κ ⊗_P I` is spanned by the `1 ⊗ x_j`, `j ≤ c`, whose images are the `1 ⊗ d x_j`.

*The images are independent.* The classes of `x_1, …, x_c` are linearly independent in
`𝔪_P/𝔪_P²` (`Hironaka/Algebra/Local/RegularSystem.lean`), and the conormal map
`𝔪_P/𝔪_P² → κ(P) ⊗_P Ω[P⁄k]` is injective because `κ(P)` is formally smooth over `k`
([Sta, Tag 00TU], `Cotangent.lean`): `κ(P) ≅ κ(R)` along `g`, and formal smoothness transports
along this `k`-algebra isomorphism. So the `1 ⊗ d x_j` are independent over `κ(P)` in
`κ(P) ⊗_P Ω[P⁄k]`, and then over `κ(R)` in `κ(R) ⊗_P Ω[P⁄k]`, the two tensor products being
identified semilinearly (`linearIndependent_tmul_of_bijective_residueField_map`).

*Conclusion.* A linear map that sends a spanning family to a linearly independent family is
injective: writing an element of the kernel as `∑ a_j (1 ⊗ x_j)`, its image `∑ a_j (1 ⊗ d x_j)`
vanishes only if all `a_j = 0`. Over a perfect field every essentially finite type field
extension is formally smooth (Mathlib's `FormallySmooth.of_perfectField`), which gives the form
used for schemes in `Hironaka/Algebra/RegularSmooth/RegularSmoothEquiv.lean`.
-/

@[expose] public section

universe u v

open IsLocalRing KaehlerDifferential
open scoped TensorProduct

namespace Algebra

section Transport

variable {k : Type*} [CommRing k] {P L : Type*} [CommRing P] [CommRing L] [IsLocalRing P]
  [IsLocalRing L] [Algebra k P] [Algebra k L] [Algebra P L] [IsScalarTower k P L]
  [IsLocalHom (algebraMap P L)]

/-- A local `k`-algebra map `P → L` inducing a bijection of residue fields gives a `k`-algebra
isomorphism `κ(P) ≃ κ(L)`. -/
noncomputable def residueFieldAlgEquivOfBijective
    (hbij : Function.Bijective (ResidueField.map (algebraMap P L))) :
    ResidueField P ≃ₐ[k] ResidueField L :=
  AlgEquiv.ofRingEquiv (f := RingEquiv.ofBijective (ResidueField.map (algebraMap P L)) hbij)
    fun c => by
      change ResidueField.map (algebraMap P L) (algebraMap k (ResidueField P) c) =
        algebraMap k (ResidueField L) c
      rw [IsScalarTower.algebraMap_apply k P (ResidueField P), ResidueField.algebraMap_eq,
        ResidueField.map_residue, ← IsScalarTower.algebraMap_apply,
        IsScalarTower.algebraMap_apply k L (ResidueField L), ResidueField.algebraMap_eq]

/-- Formal smoothness of `κ(L)` over `k` transports to `κ(P)` along the residue field bijection. -/
theorem FormallySmooth.residueField_of_bijective
    (hbij : Function.Bijective (ResidueField.map (algebraMap P L)))
    [Algebra.FormallySmooth k (ResidueField L)] : Algebra.FormallySmooth k (ResidueField P) :=
  Algebra.FormallySmooth.of_equiv (residueFieldAlgEquivOfBijective hbij).symm

omit [Algebra k L] [IsScalarTower k P L] in
/-- A family `1 ⊗ v_i` linearly independent over `κ(P)` in `κ(P) ⊗[P] Ω[P⁄k]` is linearly
independent over `κ(L)` in `κ(L) ⊗[P] Ω[P⁄k]` when `P → L` induces a bijection of residue fields:
the two tensor products are identified along the residue field isomorphism, semilinearly. -/
theorem linearIndependent_tmul_of_bijective_residueField_map
    (hbij : Function.Bijective (ResidueField.map (algebraMap P L))) {ι : Type*} (v : ι → Ω[P⁄k])
    (hv : LinearIndependent (ResidueField P) fun i => (1 : ResidueField P) ⊗ₜ[P] v i) :
    LinearIndependent (ResidueField L) fun i => (1 : ResidueField L) ⊗ₜ[P] v i := by
  set e := RingEquiv.ofBijective (ResidueField.map (algebraMap P L)) hbij with he
  have hemap : ∀ p : P, e (algebraMap P (ResidueField P) p) = algebraMap P (ResidueField L) p :=
    fun p => by
      change ResidueField.map (algebraMap P L) (algebraMap P (ResidueField P) p) =
        algebraMap P (ResidueField L) p
      rw [ResidueField.algebraMap_eq, ResidueField.map_residue,
        IsScalarTower.algebraMap_apply P L (ResidueField L), ResidueField.algebraMap_eq]
  let eₗ : ResidueField P →ₗ[P] ResidueField L :=
    { toFun := e
      map_add' := map_add e
      map_smul' := fun p a => by
        simp only [RingHom.id_apply]
        rw [Algebra.smul_def, Algebra.smul_def, map_mul, hemap] }
  let E : ResidueField P ≃ₗ[P] ResidueField L := LinearEquiv.ofBijective eₗ hbij
  let Φ : ResidueField P ⊗[P] Ω[P⁄k] ≃ₗ[P] ResidueField L ⊗[P] Ω[P⁄k] := E.rTensor Ω[P⁄k]
  have hΦ : ∀ (r : ResidueField L) (m : ResidueField P ⊗[P] Ω[P⁄k]),
      Φ (e.symm r • m) = r • Φ m := by
    intro r m
    induction m using TensorProduct.induction_on with
    | zero => simp only [smul_zero, map_zero]
    | tmul a w =>
      rw [TensorProduct.smul_tmul']
      change E (e.symm r • a) ⊗ₜ[P] w = r • (E a ⊗ₜ[P] w)
      rw [TensorProduct.smul_tmul']
      congr 1
      change e (e.symm r * a) = r * e a
      rw [map_mul, RingEquiv.apply_symm_apply]
    | add m₁ m₂ h₁ h₂ => rw [smul_add, map_add, h₁, h₂, map_add, smul_add]
  have this : LinearIndependent (ResidueField L)
      (Φ.toLinearMap.toAddMonoidHom ∘ fun i => (1 : ResidueField P) ⊗ₜ[P] v i) :=
    hv.map_of_injective_injective (fun r => e.symm r) Φ.toLinearMap.toAddMonoidHom
      (fun r hr => e.symm.injective (hr.trans (map_zero _).symm))
      (fun m hm => Φ.injective (hm.trans (map_zero _).symm)) hΦ
  have hfun : (Φ.toLinearMap.toAddMonoidHom ∘ fun i => (1 : ResidueField P) ⊗ₜ[P] v i) =
      fun i => (1 : ResidueField L) ⊗ₜ[P] v i := by
    funext i
    change E 1 ⊗ₜ[P] v i = (1 : ResidueField L) ⊗ₜ[P] v i
    congr 1
    exact map_one e
  rwa [hfun] at this

end Transport

section Kernel

variable {k : Type u} [Field k] {S : Type u} [CommRing S] [Algebra k S]

/-- If `S_𝔮` is a regular local ring and its residue field is formally smooth over `k`, then the
finite type `k`-algebra `S` is smooth at `𝔮`: the implication (2) ⇒ (1) of [Sta, Tag 00TV],
proved through Mathlib's Jacobian criterion, [Sta, Tag 00NR] and [Sta, Tag 00TU] as in the
module docstring. -/
theorem IsSmoothAt.of_isRegularLocalRing [Algebra.FiniteType k S] (𝔮 : Ideal S) [𝔮.IsPrime]
    [IsRegularLocalRing (Localization.AtPrime 𝔮)] [Algebra.FormallySmooth k 𝔮.ResidueField] :
    Algebra.IsSmoothAt k 𝔮 := by
  classical
  obtain ⟨N, φ, hφ⟩ := Algebra.FiniteType.iff_quotient_mvPolynomial''.mp ‹Algebra.FiniteType k S›
  set Q : Ideal (MvPolynomial (Fin N) k) := 𝔮.comap φ.toRingHom with hQ
  set P := Localization.AtPrime Q with hP
  set L := Localization.AtPrime 𝔮 with hL
  set g : P →+* L := Localization.localRingHom Q 𝔮 φ.toRingHom rfl with hg
  let _ : Algebra P L := g.toAlgebra
  have hgalg : algebraMap P L = g := RingHom.algebraMap_toAlgebra g
  have hcomm : ∀ c : k, g (algebraMap k P c) = algebraMap k L c := fun c => by
    rw [IsScalarTower.algebraMap_apply k (MvPolynomial (Fin N) k) P, hg,
      Localization.localRingHom_to_map, IsScalarTower.algebraMap_apply k S L]
    congr 1
    exact φ.commutes c
  have : IsScalarTower k P L := IsScalarTower.of_algebraMap_eq fun c => by rw [hgalg, hcomm]
  have hloc : IsLocalHom (algebraMap P L) := by
    rw [hgalg]
    exact Localization.isLocalHom_localRingHom (I := Q) 𝔮 φ.toRingHom rfl
  have hsurj : Function.Surjective (algebraMap P L) := by
    rw [hgalg]
    exact Localization.localRingHom_surjective_of_surjective φ.toRingHom 𝔮 hφ
  have hbij : Function.Bijective (ResidueField.map (algebraMap P L)) :=
    Localization.bijective_residueField_map_localRingHom_of_surjective φ.toRingHom 𝔮 hφ
  have hker : (RingHom.ker (algebraMap P L)).FG := MvPolynomial.fg_of_localization_atPrime Q _
  have : Algebra.FormallySmooth k P := MvPolynomial.formallySmooth_localization_atPrime Q
  have : Module.Free P Ω[P⁄k] := MvPolynomial.free_kaehlerDifferential_localization_atPrime Q
  have : Module.Finite P Ω[P⁄k] := MvPolynomial.finite_kaehlerDifferential_localization_atPrime Q
  change Algebra.FormallySmooth k L
  rw [Algebra.FormallySmooth.iff_injective_cotangentComplexBaseChange_residueField P hsurj hker]
  -- the kernel `K` of `P → L` is generated by an initial segment of a regular system of parameters
  set K := RingHom.ker (algebraMap P L) with hKdef
  have : IsRegularLocalRing P := MvPolynomial.isRegularLocalRing_localization_atPrime Q
  have : IsRegularLocalRing (P ⧸ K) :=
    IsRegularLocalRing.of_ringEquiv (RingHom.quotientKerEquivOfSurjective hsurj).symm
  obtain ⟨n, c, x, hcn, hnP, hx, hK⟩ :=
    IsRegularLocalRing.exists_span_eq_maximalIdeal_and_eq_span_image_lt K
  have hxK : ∀ j : Fin c, x (Fin.castLE hcn j) ∈ K := fun j => by
    rw [hK]
    exact Ideal.subset_span ⟨Fin.castLE hcn j, j.isLt, rfl⟩
  let v : Fin c → K := fun j => ⟨x (Fin.castLE hcn j), hxK j⟩
  have hrange :
      Set.range (fun j : Fin c => x (Fin.castLE hcn j)) = x '' {j : Fin n | j.val < c} := by
    ext z
    constructor
    · rintro ⟨j, rfl⟩
      exact ⟨Fin.castLE hcn j, j.isLt, rfl⟩
    · rintro ⟨j, hj, rfl⟩
      exact ⟨⟨j.val, hj⟩, congrArg x (Fin.ext rfl)⟩
  -- the `v_j` generate `K`, so the `1 ⊗ v_j` span `κ ⊗[P] K`
  have hvspan : Submodule.span P (Set.range v) = ⊤ := by
    apply Submodule.map_injective_of_injective K.injective_subtype
    rw [Submodule.map_span, Submodule.map_top, Submodule.range_subtype, ← Set.range_comp]
    have hcomp : Set.range (K.subtype ∘ v) = Set.range fun j : Fin c => x (Fin.castLE hcn j) := rfl
    rw [hcomp, hrange]
    exact hK.symm
  have hTspan : Submodule.span (ResidueField L)
      (Set.range fun j => (1 : ResidueField L) ⊗ₜ[P] v j) = ⊤ := by
    have := congrArg (Submodule.baseChange (ResidueField L)) hvspan
    rw [Submodule.baseChange_span, Submodule.baseChange_top, ← Set.range_comp] at this
    exact this
  -- the criterion's map sends `1 ⊗ v_j` to `1 ⊗ d x_j`
  set F := cotangentComplexBaseChange k L P (ResidueField L) with hF
  have hFv : ∀ j, F ((1 : ResidueField L) ⊗ₜ[P] v j) =
      (1 : ResidueField L) ⊗ₜ[P] D k P (x (Fin.castLE hcn j)) := fun j => by
    rw [hF, cotangentComplexBaseChange_tmul, one_smul, kerToTensor_apply]
  -- the classes of the `x_j`, `j < c`, are independent in `𝔪_P/𝔪_P²`, hence the `1 ⊗ d x_j` are
  obtain ⟨b, hb⟩ := exists_basis_cotangentSpace_of_span_eq x hx hnP
  have hliP : LinearIndependent (ResidueField P) fun j : Fin c =>
      (maximalIdeal P).toCotangent
        ⟨x (Fin.castLE hcn j), x_mem_maximalIdeal_of_span_eq x hx _⟩ := by
    have := b.linearIndependent.comp (Fin.castLE hcn) (Fin.castLE_injective hcn)
    convert this using 1
    funext j
    rw [Function.comp_apply, hb]
  have : Algebra.FormallySmooth k (ResidueField P) := FormallySmooth.residueField_of_bijective hbij
  have hliP' : LinearIndependent (ResidueField P) fun j : Fin c =>
      (1 : ResidueField P) ⊗ₜ[P] D k P (x (Fin.castLE hcn j)) := by
    have this : LinearIndependent (ResidueField P) (cotangentSpaceToTensor k P ∘ fun j : Fin c =>
        (maximalIdeal P).toCotangent
          ⟨x (Fin.castLE hcn j), x_mem_maximalIdeal_of_span_eq x hx _⟩) :=
      hliP.map' (cotangentSpaceToTensor k P)
        (LinearMap.ker_eq_bot.mpr (injective_cotangentSpaceToTensor k P))
    have hfun : (cotangentSpaceToTensor k P ∘ fun j : Fin c =>
        (maximalIdeal P).toCotangent
          ⟨x (Fin.castLE hcn j), x_mem_maximalIdeal_of_span_eq x hx _⟩) =
        fun j : Fin c => (1 : ResidueField P) ⊗ₜ[P] D k P (x (Fin.castLE hcn j)) := by
      funext j
      rw [Function.comp_apply, cotangentSpaceToTensor_toCotangent]
    rwa [hfun] at this
  have hliL := linearIndependent_tmul_of_bijective_residueField_map hbij _ hliP'
  -- a linear map sending a spanning family to an independent family is injective
  refine (injective_iff_map_eq_zero F).mpr fun w hw => ?_
  have hwT : w ∈ Submodule.span (ResidueField L)
      (Set.range fun j => (1 : ResidueField L) ⊗ₜ[P] v j) := by
    rw [hTspan]
    exact Submodule.mem_top
  obtain ⟨a, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun (ResidueField L)).mp hwT
  have h0 : ∑ j, a j • ((1 : ResidueField L) ⊗ₜ[P] D k P (x (Fin.castLE hcn j))) = 0 := by
    rw [← hw, map_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [map_smul, hFv]
  have ha : ∀ j, a j = 0 := Fintype.linearIndependent_iff.mp hliL a h0
  exact Finset.sum_eq_zero fun j _ => by rw [ha j, zero_smul]

/-- For `k` perfect, `S_𝔮` regular implies `S` smooth at `𝔮` over `k` ([Sta, Tag 00TV], (2) ⇒ (1)):
the residue field of `S_𝔮` is essentially of finite type over `k`, hence formally smooth over
the perfect field `k`. -/
theorem IsSmoothAt.of_isRegularLocalRing_of_perfectField [PerfectField k] [Algebra.FiniteType k S]
    (𝔮 : Ideal S) [𝔮.IsPrime] [IsRegularLocalRing (Localization.AtPrime 𝔮)] :
    Algebra.IsSmoothAt k 𝔮 :=
  have : Algebra.EssFiniteType k 𝔮.ResidueField := Algebra.EssFiniteType.comp k S _
  IsSmoothAt.of_isRegularLocalRing 𝔮

end Kernel

end Algebra
