/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.MaximalContact.EtaleEquiv
import Hironaka.Resolution.Algebraic.MaximalContact.EtaleToFormal
import Hironaka.Resolution.Algebraic.MaximalContact.Theorem97Setup
import Hironaka.Scheme.BlowUp.BlowUpMap
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.BlowUp.Transform.WeakTransform
import Hironaka.Scheme.BlowUpSequence.InducedData
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The inductive step of Theorem 97: the defects, and the pieces of the one-step descent

In the proof of [Kol07, Theorem 97], Kollár picks local coordinates `x_1, …, x_n` on `X_i = X'_i`
with `Z_i = Z'_i = (x_1 = ⋯ = x_k = 0)` and writes, by induction,
`ψ'^*_i(x_j) = ψ^*_i(x_j) − b(i, j)` with `b(i, j) ∈ (Π^U_i)^{-1}_*(MC(I^U), 1)`. This file
defines the defects `b(i, j)` and proves the ingredients of the one-step descent of agreement
through a blow-up, which is assembled in
`Hironaka/Resolution/Algebraic/MaximalContact/AgreeOnBlowUpKernel.lean`. Everything here is stated
for arbitrary schemes and arbitrary morphisms; flatness enters only the descent of the centres
(`eq_of_comap_eq_of_agreeOn_of_le`).

* `defect ψ ψ' V a`: the defect `ψ^* a − ψ'^* a` of a section `a ∈ Γ(X, V)` under two maps
  `ψ, ψ' : U ⟶ X`, a section over `ψ^{-1} V ⊓ ψ'^{-1} V` (the open on which both pull-backs are
  defined; Kollár's `b(i, j)` for `a = x_j`); `germ_defect_mem`: at the points of `V(M)` the
  defects lie in the stalks of `M` when `ψ, ψ'` agree on `V(M)`, the stalkwise content of "`ψ_i`
  and `ψ'_i` agree on `V(M_i)`" (`AgreeOn`).
* `eq_of_comap_eq_of_agreeOn_of_le`: `Z_i = ψ_i(Z^U_i) = ψ'_i(Z^U_i) = Z'_i` by descent of closed
  subschemes along flat maps agreeing on the common preimage, the agreement on the common
  pulled-back centre coming from `M ≤ Z^U` by `AgreeOn.mono`.
* `comap_blowUpπ_le_markedTransform_one`, `support_markedTransform_one_subset`:
  `π^* M ≤ π^{-1}_*(M, 1)` and `V(π^{-1}_*(M, 1)) ⊆ π^{-1} V(M)`, formal properties of the colon.
* `AgreeOn.comp_left`, `agreeOn_blowUpMap_comp_π`: agreement pulls back along any morphism, and
  the lifts to the blow-ups, composed with the projection of the target blow-up, agree on
  `V(π^{-1}_*(M, 1))`: Kollár's "clear if `y_j = x_j`", for every function of the base.
* `exceptionalDivisor_mul_markedTransform_one`: `𝒪(F) · π^{-1}_*(M, 1) = π^* M` for `M ≤ J`, the
  formula (60.1) of [Kol07, Definition 60] at mark `1`: the division of the defects by the
  exceptional equation.
* `isUnit_one_sub_of_mem_stalkIdeal`, `ratio_identity`: the unit `1 − d` at a point of the support
  (the step that shows the two lifts land in a common chart) and Kollár's displayed quotient after
  cancelling the nonzerodivisor `e`.
* `sub_mem_of_forall_mem_closure`, `agreeOn_iff_forall_gen`: the equalizer ideal of two ring
  homomorphisms is generated by the defects of ring generators; for morphisms from an affine
  scheme into `Spec B`, agreement on `V(M)` is the membership of the generators' defects in `M`.
-/

@[expose] public section

namespace AlgebraicGeometry.Scheme.IdealSheafData

open CategoryTheory IdealSheafData

universe u

variable {U X : Scheme.{u}}

/-! ### The defects -/

/-- Kollár's "`ψ'^*_i(x_j) = ψ^*_i(x_j) − b(i, j)`" (the proof of [Kol07, Theorem 97]): the
**defect** `ψ^* a − ψ'^* a` of a section `a ∈ Γ(X, V)` under the two maps `ψ, ψ' : U ⟶ X`, a
section of `𝒪_U` over `ψ^{-1} V ⊓ ψ'^{-1} V`.
-/
noncomputable def defect (ψ ψ' : U ⟶ X) (V : X.Opens) (a : Γ(X, V)) :
    Γ(U, ψ ⁻¹ᵁ V ⊓ ψ' ⁻¹ᵁ V) :=
  U.presheaf.map (homOfLE inf_le_left).op (ψ.app V a) -
    U.presheaf.map (homOfLE inf_le_right).op (ψ'.app V a)

/-- The defect unfolded. -/
theorem defect_eq (ψ ψ' : U ⟶ X) (V : X.Opens) (a : Γ(X, V)) :
    defect ψ ψ' V a = U.presheaf.map (homOfLE inf_le_left).op (ψ.app V a) -
      U.presheaf.map (homOfLE inf_le_right).op (ψ'.app V a) :=
  rfl

/-- Kollár's "`b(i, j) ∈ (Π^U_i)^{-1}_*(MC(I^U), 1)`": at a point `w ∈ V(M)` in the common domain,
the germ of the defect `ψ^* a − ψ'^* a` lies in the stalk `M_w`, when `ψ, ψ'` agree on `V(M)`;
the restrictions to the common open do not change the germs, and
`germ_app_sub_germ_app_mem_stalkIdeal` applies.
-/
theorem germ_defect_mem (ψ ψ' : U ⟶ X) (M : U.IdealSheafData)
    (h : AgreeOn ψ ψ' M) (V : X.Opens) (a : Γ(X, V)) {w : U} (hw : w ∈ M.support)
    (hw' : w ∈ ψ ⁻¹ᵁ V ⊓ ψ' ⁻¹ᵁ V) :
    U.presheaf.germ (ψ ⁻¹ᵁ V ⊓ ψ' ⁻¹ᵁ V) w hw' (defect ψ ψ' V a) ∈ M.stalkIdeal w := by
  rw [defect_eq, map_sub, TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply]
  exact germ_app_sub_germ_app_mem_stalkIdeal ψ ψ' M h hw V a hw'.1 hw'.2

/-! ### Equality of the centres by descent -/

/-- Kollár's "`Z_i = ψ_i(Z^U_i) = ψ'_i(Z^U_i) = Z'_i`" (the proof of [Kol07, Theorem 97]): for
flat `ψ, ψ' : U ⟶ X`, centres `Z, Z'` with equal inverse images, supports in the images of `ψ`,
`ψ'`, and an ideal sheaf `M ≤ ψ^{-1} Z` on which `ψ, ψ'` agree, `Z = Z'`; this is the descent
`eq_of_comap_eq_of_agreeOn` of closed subschemes along flat maps, the agreement on the common
pulled-back centre `V(ψ^{-1} Z)` inherited from `V(M)` by `AgreeOn.mono`.
-/
theorem eq_of_comap_eq_of_agreeOn_of_le (ψ ψ' : U ⟶ X) [Flat ψ] [Flat ψ']
    (Z Z' : X.IdealSheafData) (M : U.IdealSheafData) (hZ : Z.comap ψ = Z'.comap ψ')
    (hsup : (Z.support : Set X) ⊆ Set.range ψ) (hsup' : (Z'.support : Set X) ⊆ Set.range ψ')
    (hM : M ≤ Z.comap ψ) (hfg : AgreeOn ψ ψ' M) : Z = Z' :=
  eq_of_comap_eq_of_agreeOn ψ ψ' Z Z' hsup hsup' hZ (AgreeOn.mono hM hfg)

/-! ### The marked transform contains the pull-back -/

/-- `π^* M ≤ π^{-1}_*(M, 1)`: the marked transform is the colon `(π^* M : 𝒪(F))`
(`markedTransform_eq_colon`), which contains `π^* M`.
-/
theorem comap_blowUpπ_le_markedTransform_one (J M : U.IdealSheafData) :
    M.comap J.blowUpπ ≤ M.markedTransform J 1 := by
  rw [markedTransform_eq_colon]
  exact le_colon_self _ _

/-- `V(π^{-1}_*(M, 1)) ⊆ π^{-1}(V(M))`, so the base maps agree at `π(u)` for every `u ∈ V(M')`:
supports are antitone and `V(π^* M) = π^{-1} V(M)` (Mathlib's `support_comap`).
-/
theorem support_markedTransform_one_subset (J M : U.IdealSheafData) :
    ((M.markedTransform J 1).support : Set J.blowUp) ⊆
      J.blowUpπ.base ⁻¹' (M.support : Set U) := by
  intro u hu
  have h := support_antitone (comap_blowUpπ_le_markedTransform_one J M) hu
  rw [support_comap] at h
  exact h

/-! ### The defects of the base functions -/

/-- Kollár's "this is clear if `y_j = x_j`", for every function of the base: agreement on `V(M)`
pulls back along any `π : T ⟶ U` to agreement on `V(π^* M)`; the closed immersion of `V(π^* M)`
composed with `π` factors through the closed immersion of `V(M)` (Mathlib's `subschemeMap`).
-/
theorem AgreeOn.comp_left {T : Scheme.{u}} (π : T ⟶ U) {f g : U ⟶ X} {M : U.IdealSheafData}
    (hfg : AgreeOn f g M) : AgreeOn (π ≫ f) (π ≫ g) (M.comap π) := by
  unfold AgreeOn at hfg ⊢
  calc (M.comap π).subschemeι ≫ π ≫ f
      = subschemeMap (M.comap π) M π (le_map_comap M π) ≫ M.subschemeι ≫ f := by
        rw [subschemeMap_subschemeι_assoc]
    _ = subschemeMap (M.comap π) M π (le_map_comap M π) ≫ M.subschemeι ≫ g := by rw [hfg]
    _ = (M.comap π).subschemeι ≫ π ≫ g := by rw [subschemeMap_subschemeι_assoc]

/-- The lifts composed with the blow-up projection `π_X : B_C X ⟶ X` agree on `V(π^{-1}_*(M, 1))`:
`f̃ ≫ π_X = π ≫ f` and `g̃ ≫ π_X = π ≫ g` (`blowUpMap_π`, with the transport
`AlgebraicGeometry.eqToHom_comp_blowUpπ`), agreement on `V(M)` pulls back to `V(π^* M)`
(`AgreeOn.comp_left`), and `π^* M ≤ M'` (`AgreeOn.mono`).
-/
theorem agreeOn_blowUpMap_comp_π (f g : U ⟶ X) (C : X.IdealSheafData)
    (M : U.IdealSheafData) (hJ : C.comap f = C.comap g) (hfg : AgreeOn f g M) :
    AgreeOn (Scheme.Hom.blowUpMap f C ≫ C.blowUpπ)
      ((eqToHom (congrArg Scheme.IdealSheafData.blowUp hJ) ≫ Scheme.Hom.blowUpMap g C) ≫
          C.blowUpπ)
      (M.markedTransform (C.comap f) 1) := by
  have h1 : Scheme.Hom.blowUpMap f C ≫ C.blowUpπ = (C.comap f).blowUpπ ≫ f :=
    blowUpMap_π f C
  have h1' : Scheme.Hom.blowUpMap g C ≫ C.blowUpπ = (C.comap g).blowUpπ ≫ g :=
    blowUpMap_π g C
  have h2 : (eqToHom (congrArg Scheme.IdealSheafData.blowUp hJ) ≫ Scheme.Hom.blowUpMap g C) ≫
      C.blowUpπ =
      (C.comap f).blowUpπ ≫ g := by
    rw [Category.assoc, h1', ← Category.assoc]
    congr 1
    exact eqToHom_comp_blowUpπ hJ
  rw [h1, h2]
  exact AgreeOn.mono (comap_blowUpπ_le_markedTransform_one _ _) (AgreeOn.comp_left _ hfg)

/-! ### Division by the exceptional equation -/

/-- Kollár's "the `b(i, j)` vanish along `Z^U_i` and so
`(π^U_i)^* b(i, j) = ψ^*_{i+1}(x_r) b(i+1, j)`" (the formula (60.1) of [Kol07, Definition 60] at
mark `1`): for `M ≤ J`,
`𝒪(F) · π^{-1}_*(M, 1) = π^* M` on `B_J U`, because `π^* M ≤ π^* J = 𝒪(F)` and `𝒪(F)` is
invertible, so `𝒪(F) ∣ π^* M` and `pow_mul_markedTransform` applies.
-/
theorem exceptionalDivisor_mul_markedTransform_one {J M : U.IdealSheafData}
    (hM : M ≤ J) : J.exceptionalDivisor * M.markedTransform J 1 = M.comap
        J.blowUpπ := by
  have hdvd : J.exceptionalDivisor ^ 1 ∣ M.comap J.blowUpπ :=
    pow_dvd_of_le_pow_of_isInvertible
      (blowUp.isInvertible_comap_π J)
      (by rw [pow_one]; exact comap_mono J.blowUpπ hM)
  have h := pow_mul_markedTransform J M 1 hdvd
  rwa [pow_one] at h

/-! ### The common chart and the ratio identity -/

/-- At a point `w ∈ V(M)`, `1 − d` is a unit of the stalk for every `d ∈ M_w`: the stalk of `M` at
a point of its support lies in the maximal ideal (`mem_support_iff_stalkIdeal_le_maximalIdeal`).
This is what puts the two lifts into a common chart of the blow-up.
-/
theorem isUnit_one_sub_of_mem_stalkIdeal (M : U.IdealSheafData) {w : U}
    (hw : w ∈ M.support) {d : U.presheaf.stalk w} (hd : d ∈ M.stalkIdeal w) : IsUnit (1 - d) :=
  IsLocalRing.isUnit_one_sub_self_of_mem_nonunits d
    ((IsLocalRing.mem_maximalIdeal d).mp
      ((M.mem_support_iff_stalkIdeal_le_maximalIdeal w).mp hw hd))

/-- Kollár's displayed identity
`ψ^*_{i+1}(y_j) − ψ'^*_{i+1}(y_j) = (b(i+1, j) − b(i+1, r) ψ^*_{i+1}(y_j)) / (1 − b(i+1, r))`, after
cancelling the nonzerodivisor: in a commutative ring, if `e` is a nonzerodivisor, `e · a = x` and
`e · ((1 − d) · a') = x − e · dj`, then `(1 − d) · (a − a') = dj − d · a`.
-/
theorem ratio_identity {R : Type*} [CommRing R] {e a a' x d dj : R} (he : e ∈ nonZeroDivisors R)
    (h1 : e * a = x) (h2 : e * ((1 - d) * a') = x - e * dj) : (1 - d) * (a - a') = dj - d * a := by
  rw [← mul_cancel_left_mem_nonZeroDivisors he]
  linear_combination h1 - h2

/-! ### Generation of the equalizer ideal by the defects of generators -/

/-- For ring homomorphisms `φ, φ' : R → S` and an ideal `N` of `S`, if the defects `φ s − φ' s` of
the elements of a set `T` generating `R` as a ring lie in `N`, so does every defect `φ r − φ' r`:
induction over `Subring.closure`, the product case being
`φ(r₁ r₂) − φ'(r₁ r₂) = φ r₁ (φ r₂ − φ' r₂) + φ' r₂ (φ r₁ − φ' r₁)`.
-/
theorem sub_mem_of_forall_mem_closure {R S : Type*} [CommRing R] [CommRing S] (φ φ' : R →+* S)
    (N : Ideal S) {T : Set R} (hT : Subring.closure T = ⊤) (h : ∀ s ∈ T, φ s - φ' s ∈ N) (r : R) :
    φ r - φ' r ∈ N := by
  have hr : r ∈ Subring.closure T := hT ▸ Subring.mem_top r
  induction hr using Subring.closure_induction with
  | mem x hx => exact h x hx
  | zero => simp
  | one => simp
  | add x y _ _ hx hy =>
    have e : φ (x + y) - φ' (x + y) = (φ x - φ' x) + (φ y - φ' y) := by
      simp only [map_add]; ring
    rw [e]; exact N.add_mem hx hy
  | neg x _ hx =>
    have e : φ (-x) - φ' (-x) = -(φ x - φ' x) := by simp only [map_neg]; ring
    rw [e]; exact N.neg_mem hx
  | mul x y _ _ hx hy =>
    have e : φ (x * y) - φ' (x * y) = φ x * (φ y - φ' y) + φ' y * (φ x - φ' x) := by
      simp only [map_mul]; ring
    rw [e]; exact N.add_mem (N.mul_mem_left _ hy) (N.mul_mem_left _ hx)

/-- The scheme form on an affine source: two morphisms `a, a'` from an affine scheme `W` to
`Spec B` agree on `V(M)` iff the defects of the elements of a set `T` generating `B` as a ring lie
in `M(W)`. Indeed `M(W)` is the kernel of the closed immersion of `V(M)` on global sections
(Mathlib's `ker_subschemeι_app`), morphisms into the affine `Spec B` are determined by their maps
on global sections (`ext_of_isAffine`), and the ring-level generation lemma finishes.
-/
theorem agreeOn_iff_forall_gen {W : Scheme.{u}} [IsAffine W] {B : CommRingCat.{u}}
    (a a' : W ⟶ Spec B) (M : W.IdealSheafData) {T : Set B} (hT : Subring.closure T = ⊤) :
    AgreeOn a a' M ↔ ∀ s ∈ T,
      a.appTop ((Scheme.ΓSpecIso B).inv s) - a'.appTop ((Scheme.ΓSpecIso B).inv s) ∈
        M.ideal ⟨⊤, isAffineOpen_top W⟩ := by
  have hker : ∀ x : Γ(W, ⊤), x ∈ M.ideal ⟨⊤, isAffineOpen_top W⟩ ↔
      M.subschemeι.appTop x = 0 := by
    intro x
    rw [← ker_subschemeι_app M ⟨⊤, isAffineOpen_top W⟩, RingHom.mem_ker]
    rfl
  constructor
  · intro h s _
    rw [hker, map_sub, sub_eq_zero]
    have e := congrArg (fun φ : M.subscheme ⟶ Spec B => φ.appTop ((Scheme.ΓSpecIso B).inv s)) h
    simp only [Scheme.Hom.comp_appTop, CommRingCat.comp_apply] at e
    exact e
  · intro h
    unfold AgreeOn
    apply AlgebraicGeometry.ext_of_isAffine
    rw [Scheme.Hom.comp_appTop, Scheme.Hom.comp_appTop]
    ext x
    rw [CommRingCat.comp_apply, CommRingCat.comp_apply]
    have key := sub_mem_of_forall_mem_closure
      (M.subschemeι.appTop.hom.comp (a.appTop.hom.comp (Scheme.ΓSpecIso B).inv.hom))
      (M.subschemeι.appTop.hom.comp (a'.appTop.hom.comp (Scheme.ΓSpecIso B).inv.hom)) ⊥ hT
      (fun s hs => by
        rw [Ideal.mem_bot, RingHom.comp_apply, RingHom.comp_apply, RingHom.comp_apply,
          RingHom.comp_apply, ← map_sub]
        exact (hker _).mp (h s hs))
      ((Scheme.ΓSpecIso B).hom x)
    rw [Ideal.mem_bot, sub_eq_zero] at key
    simpa [RingHom.comp_apply] using key

end AlgebraicGeometry.Scheme.IdealSheafData
