/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.Composite.Descend
public import Hironaka.Resolution.Algebraic.MaximalContact.EtaleEquiv
import Hironaka.Resolution.Algebraic.MaximalContact.AgreeOnBlowUp
import Hironaka.Resolution.Algebraic.MaximalContact.EtaleToFormal
import Hironaka.Scheme.BlowUp.BlowUpMap
import Hironaka.Scheme.BlowUp.Composite.Transition
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.BlowUp.InvertibleSheaf
import Hironaka.Scheme.BlowUp.Transform.WeakTransform
import Hironaka.Scheme.IdealSheaf.Order.AffineSpace
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.IdealSheaf.StalkLe
import Hironaka.Scheme.Smooth.SubschemeStalk
import Hironaka.Scheme.Snc.HasSncWith
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The one-step descent of agreement through a blow-up

The inductive step in the proof of [Kol07, Theorem 97] (compare the proof of the gluing lemma
[Wlo05, Lemma 2.9.5]). This file proves `agreeOn_blowUpMap`: for morphisms `f, g : U ⟶ X`, a
centre `C ⊆ X` with `f^{-1} C = g^{-1} C =: J` and an ideal sheaf `M ≤ J` on which `f, g` agree,
the lifts `f̃, g̃ : B_J U ⟶ B_C X` agree on `V(π^{-1}_*(M, 1))`; this is the step that the
induction of `Hironaka/Resolution/Algebraic/MaximalContact/Theorem97Induction.lean` takes as a
hypothesis, in the same spelling. Its corollary `step_agreeOn` adds the equality of the centres. No
smoothness, étaleness or flatness enters the descent itself; flatness appears only in
`step_agreeOn`, through the descent of the centres.

## The proof

Kollár's computation is written in local coordinates on a chart of the blow-up. Fix a point `u`
of `V(M')`, `M' := π^{-1}_*(M, 1)`; its image `π u` lies in `V(M)`, so `f (π u) = g (π u)`.

1. **The chart.** Take an affine `V ∋ f (π u)`; the charts `Spec A[C(V)/c]`, `c ∈ C(V)`, cover
   `π_X^{-1} V`, so `f̃ u` lies in the chart of some `c`. On that chart the exceptional ideal of
   `B_C X` is generated by `π_X^* c`, hence `𝒪(F)` is generated at `u` by `e := π^* f^* c`
   (`stalkIdeal_exceptionalDivisor_eq_span`).
2. **The defects divided.** For `b ∈ C(V)` the defect `π^*(f^* b − g^* b)` lies in `π^* M`, and
   `π^* M = 𝒪(F) · M'`, so `π^* g^* b = π^* f^* b − e · d_b` with `d_b ∈ M'_u`
   (`exists_mem_markedTransform_mul_eq`).
3. **The common chart** (a step absent from the printed proof). In particular
   `π^* g^* c = e (1 − d_c)` with `1 − d_c` a unit at `u`, so `π^* g^* c` generates `𝒪(F)` at `u`
   as well; reading this on whichever chart `c'` contains `g̃ u`, the ratio `c / c'` is a unit
   there (two nonzerodivisor generators of a principal ideal differ by a unit), so `g̃ u` lies in
   the chart of `c` too (`mem_chartOpen_of_stalkIdeal_eq_span`, via `chart_preimage_chart`).
4. **Generators.** Choose an affine `W ∋ u` inside both chart preimages. The chart algebra is
   generated as a ring by the image of `A = Γ(X, V)` and the ratios `b / c`
   (`subring_closure_chart_generators_eq_top`). The pulled-back sections of the base functions
   are `π^* f^* r` and `π^* g^* r`, whose difference lies in `π^* M ≤ M'`. For the ratios,
   `a_b · e = π^* f^* b` and `a'_b · π^* g^* c = π^* g^* b`, so at every point `w` of `W ∩ V(M')`
   (where `e` is a nonzerodivisor generating `𝒪(F)`) Kollár's identity
   `(1 − d_c)(a_b − a'_b) = d_b − d_c a_b` holds (`ratio_identity`) and `a_b − a'_b ∈ M'_w`. Off
   `V(M')` the stalk of `M'` is the unit ideal. Hence the defects of all generators lie in `M'(W)`
   (`mem_ideal_of_forall_germ_mem`, the local-global principle for ideal membership).
5. **From generators to morphisms.** The two lifts of `W ∩ V(M')` into the affine chart are equal
   (`ext_of_isAffine` and the ring-level generation lemma), so `f̃` and `g̃` agree on the affine
   piece `W ∩ V(M')` (`eq_comp_of_forall_gen`); equality of morphisms is local on the source
   (`hom_ext_of_forall`).

Points of the blow-ups are written in Mathlib's coercion spelling `φ w`; the stalk of `Spec A` at
`q` receives `A` through `chartGerm` (Mathlib's `StructureSheaf.toStalk`; the same map as
`AlgebraicGeometry.specGerm` of `Hironaka/Scheme/BlowUp/AffineBlowUp/Universal/Membership.lean`),
and every identity between stalk elements is proved by explicit congruences and `Eq.trans` chains
rather than by rewriting, which would unfold the glued blow-up.
-/

@[expose] public section

universe u

open CategoryTheory AlgebraicGeometry Scheme.IdealSheafData

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {U X : Scheme.{u}}

/-! ### Base points -/
/-- Two morphisms agreeing on `V(M)` take the same value at every point of `V(M)`. -/
theorem AgreeOn.base_eq {f g : U ⟶ X} {M : U.IdealSheafData} (h : AgreeOn f g M) {w : U}
    (hw : w ∈ M.support) : f w = g w := by
  obtain ⟨z, rfl⟩ := M.exists_subschemeι_eq hw
  have e := congrArg (fun φ : M.subscheme ⟶ X => φ z) h
  simpa using e

/-! ### Sections from germs on an affine open -/
/-- The local-global principle for ideal membership: a section over an affine open whose germ at
every point lies in the stalk of `I` lies in `I` (Mathlib's `Ideal.mem_of_localization_maximal`,
the stalks at the points of an affine open being its localizations at maximal ideals). -/
theorem mem_ideal_of_forall_germ_mem (I : X.IdealSheafData) (W : X.affineOpens) (s : Γ(X, W))
    (h : ∀ x (hx : x ∈ W.1), X.presheaf.germ W.1 x hx s ∈ I.stalkIdeal x) : s ∈ I.ideal W := by
  refine Ideal.mem_of_localization_maximal fun P hP => ?_
  have hU : IsAffineOpen W.1 := W.2
  have hx : hU.fromSpec ⟨P, hP.isPrime⟩ ∈ W.1 := by
    have : hU.fromSpec ⟨P, hP.isPrime⟩ ∈ Set.range hU.fromSpec := Set.mem_range_self _
    rwa [hU.range_fromSpec] at this
  let _ := X.presheaf.algebra_section_stalk ⟨hU.fromSpec ⟨P, hP.isPrime⟩, hx⟩
  have hloc : IsLocalization P.primeCompl (X.presheaf.stalk (hU.fromSpec ⟨P, hP.isPrime⟩)) :=
    hU.isLocalization_stalk' ⟨P, hP.isPrime⟩ hx
  let e := IsLocalization.algEquiv P.primeCompl
    (X.presheaf.stalk (hU.fromSpec ⟨P, hP.isPrime⟩)) (Localization.AtPrime P)
  have hmap : (I.ideal W).map (algebraMap Γ(X, W) (Localization.AtPrime P)) =
      (I.stalkIdeal (hU.fromSpec ⟨P, hP.isPrime⟩)).map
        (e : X.presheaf.stalk (hU.fromSpec ⟨P, hP.isPrime⟩) →+* Localization.AtPrime P) := by
    rw [stalkIdeal_eq_map_germ I W hx, Ideal.map_map]
    congr 1
    exact RingHom.ext fun r => (e.commutes r).symm
  have hs : algebraMap Γ(X, W) (Localization.AtPrime P) s =
      e (X.presheaf.germ W.1 _ hx s) := (e.commutes s).symm
  rw [hmap, hs]
  exact Ideal.mem_map_of_mem _ (h _ hx)

/-! ### Two generators of a principal ideal -/
/-- Two generators of one principal ideal differ by a unit when one of them is a nonzerodivisor. -/
theorem exists_isUnit_mul_of_span_singleton_eq {R : Type*} [CommRing R] {e k : R}
    (hk : k ∈ nonZeroDivisors R) (h : Ideal.span {e} = Ideal.span {k}) :
    ∃ v : R, IsUnit v ∧ e = v * k := by
  have he : e ∈ Ideal.span {k} := h ▸ Ideal.mem_span_singleton_self e
  have hk' : k ∈ Ideal.span {e} := h ▸ Ideal.mem_span_singleton_self k
  obtain ⟨v, rfl⟩ := Ideal.mem_span_singleton'.mp he
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hk'
  refine ⟨v, ?_, rfl⟩
  have h1 : k * (b * v) = k * 1 := by rw [mul_one]; linear_combination hb
  exact isUnit_iff_exists_inv.mpr
    ⟨b, by rw [mul_comm]; exact (mul_cancel_left_mem_nonZeroDivisors hk).mp h1⟩

/-- At a point where `𝒪(F)` is generated by `e`, every element of the stalk of `π^* M` is `e · d`
with `d` in the stalk of `π^{-1}_*(M, 1)`: the identity `𝒪(F) · π^{-1}_*(M, 1) = π^* M` read at
the stalk (`stalkIdeal_mul`).
-/
theorem exists_mem_markedTransform_mul_eq {J M : U.IdealSheafData} (hM : M ≤ J)
    {w : J.blowUp} {e : J.blowUp.presheaf.stalk w}
    (he : J.exceptionalDivisor.stalkIdeal w = Ideal.span {e})
    {x : J.blowUp.presheaf.stalk w} (hx : x ∈ (M.comap
        J.blowUpπ).stalkIdeal w) :
    ∃ d ∈ (M.markedTransform J 1).stalkIdeal w, e * d = x := by
  rw [← exceptionalDivisor_mul_markedTransform_one hM, stalkIdeal_mul, he] at hx
  exact Ideal.mem_span_singleton_mul.mp hx

/-- The pull-back along `π` of the defect `f^* s − g^* s` lies in the stalk of `π^* M` at every
point over `V(M)`: `germ_app_sub_germ_app_mem_stalkIdeal` transported by `stalkIdeal_comap`.
-/
theorem stalkMap_sub_stalkMap_mem_comap {T : Scheme.{u}} (π : T ⟶ U) (f g : U ⟶ X)
    (M : U.IdealSheafData) (hfg : AgreeOn f g M) (V : X.Opens) (s : Γ(X, V)) {w : T}
    (hw : π w ∈ M.support) (h1 : f (π w) ∈ V) (h2 : g (π w) ∈ V) :
    π.stalkMap w (f.stalkMap (π w) (X.presheaf.germ V _ h1 s)) -
      π.stalkMap w (g.stalkMap (π w) (X.presheaf.germ V _ h2 s)) ∈ (M.comap π).stalkIdeal w := by
  rw [stalkIdeal_comap, ← map_sub]
  refine Ideal.mem_map_of_mem _ ?_
  rw [Scheme.Hom.germ_stalkMap_apply, Scheme.Hom.germ_stalkMap_apply]
  exact germ_app_sub_germ_app_mem_stalkIdeal f g M hfg hw V s h1 h2

/-! ### The exceptional ideal on a chart is principal, generated by the chart function -/
/-- On the chart of `c`, the exceptional ideal `π_X^* C` is generated by `π_X^* c`. -/
theorem ideal_comap_π_chartOpen (C : X.IdealSheafData) (V : X.affineOpens) (c : C.ideal V) :
    (C.comap C.blowUpπ).ideal (chartOpen C V c) =
      Ideal.span {C.blowUpπ.appLE V.1 (chartOpen C V c).1
        (chart_image_top_le C V c) c} := by
  set A := affineBlowUpAlgebra (C.ideal V) c with hA
  let θ : A ≃+* Γ(C.blowUp, (chartOpen C V c).1) :=
    ((Scheme.ΓSpecIso (.of A)).symm ≪≫
      ((blowUp.chart C V c).appIso ⊤).symm).commRingCatIsoToRingEquiv
  have hE : chartIdeal C (C.comap C.blowUpπ) V c =
      Ideal.span {algebraMap Γ(X, V) A c} := by
    apply specIdealSheaf_inj
    rw [← comap_chart_eq_specIdealSheaf]
    exact blowUp.comap_exceptionalDivisor_chart C V c
  have hmem : ∀ z : A, z ∈ chartIdeal C (C.comap C.blowUpπ) V c ↔
      θ z ∈ (C.comap C.blowUpπ).ideal (chartOpen C V c) :=
    fun z => mem_chartIdeal_iff C _ V c z
  have hideal : (C.comap C.blowUpπ).ideal (chartOpen C V c) =
      (chartIdeal C (C.comap C.blowUpπ) V c).map (θ : A →+* _) := by
    have hsurj : Function.Surjective (θ : A →+* _) := fun y => θ.surjective y
    ext w
    rw [Ideal.mem_map_iff_of_surjective _ hsurj]
    constructor
    · intro hw
      exact ⟨θ.symm w, (hmem _).mpr (by simpa using hw), θ.apply_symm_apply w⟩
    · rintro ⟨z, hz, rfl⟩
      exact (hmem z).mp hz
  rw [hideal, hE, Ideal.map_span, Set.image_singleton]
  congr 2
  exact (appLE_chart_eq C V c c).symm

/-! ### The generator pulled back along a morphism into the blow-up -/
/-- Along any morphism `φ` into the blow-up, at a point mapped into the chart of `c`, the stalk of
`φ^* π_X^* C` is generated by the pull-back of `π_X^* c`. -/
theorem stalkIdeal_comap_comap_eq_span (C : X.IdealSheafData) (V : X.affineOpens) (c : C.ideal V)
    {B : Scheme.{u}} (φ : B ⟶ C.blowUp) {w : B}
    (hw : φ w ∈ (chartOpen C V c).1) :
    ((C.comap C.blowUpπ).comap φ).stalkIdeal w =
      Ideal.span {φ.stalkMap w (C.blowUp.presheaf.germ (chartOpen C V c).1
        (φ w) hw (C.blowUpπ.appLE V.1 (chartOpen C V c).1
          (chart_image_top_le C V c) c))} := by
  rw [stalkIdeal_comap, stalkIdeal_eq_map_germ _ (chartOpen C V c) hw,
    ideal_comap_π_chartOpen, Ideal.map_span, Set.image_singleton, Ideal.map_span,
    Set.image_singleton]

/-- The chart of `c` lies over `V` (`chart_image_top_le`, in the form of a bound on the preimage).
-/
theorem chart_le_preimage (C : X.IdealSheafData) (V : X.affineOpens) (c : C.ideal V) :
    (⊤ : (Spec (.of (affineBlowUpAlgebra (C.ideal V) c))).Opens) ≤
      blowUp.chart C V c ⁻¹ᵁ (C.blowUpπ ⁻¹ᵁ V.1) := fun z _ =>
  chart_image_top_le C V c
    (by rw [Scheme.Hom.image_top_eq_opensRange]; exact ⟨z, rfl⟩)

/-! ### The stalk of `Spec A` at `q` receives `A` through the germ of global sections -/
/-- The ring map `A → 𝒪_{Spec A, q}`, `a ↦ germ_q (a)`, spelled through the germ of global sections
(the same map as `StructureSheaf.toStalk`, in the spelling of the stalk of the scheme `Spec A`).
A duplicate of `AlgebraicGeometry.specGerm`
(`Hironaka/Scheme/BlowUp/AffineBlowUp/Universal/Membership.lean`), kept under a local name so that
every stalk identity of this file is spelled through it. -/
noncomputable def chartGerm (A : CommRingCat.{u}) (q : Spec A) : A →+* (Spec A).presheaf.stalk q :=
  (StructureSheaf.toStalk A q).hom

/-- `chartGerm` is the germ of the global section (the `specGerm_apply` of
`AlgebraicGeometry.specGerm`). -/
theorem chartGerm_apply (A : CommRingCat.{u}) (q : Spec A) (a : A) :
    chartGerm A q a =
      (Spec A).presheaf.germ ⊤ q (TopologicalSpace.Opens.mem_top q) ((Scheme.ΓSpecIso A).inv a) :=
  rfl

/-- `a` is a unit at `q ∈ Spec A` iff `a ∉ q`: Mathlib's `IsLocalization.AtPrime.isUnit_to_map_iff`
on the stalk.
-/
theorem isUnit_chartGerm_iff (R : Type u) [CommRing R] (q : PrimeSpectrum R) (r : R) :
    IsUnit (chartGerm (.of R) q r) ↔ r ∉ q.asIdeal :=
  IsLocalization.AtPrime.isUnit_to_map_iff ((Spec.structureSheaf R).presheaf.stalk q) q.asIdeal r

/-- The chart generator `c ∈ A[C(V)/c]` is a nonzerodivisor at every point of the chart.
-/
theorem chartGerm_algebraMap_mem_nonZeroDivisors (C : X.IdealSheafData) (V : X.affineOpens)
    (c : C.ideal V) (q : Spec (.of (affineBlowUpAlgebra (C.ideal V) c))) :
    chartGerm _ q (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c) c) ∈
      nonZeroDivisors _ := by
  have hs : (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
      (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c) c) ∈
      nonZeroDivisors Γ(Spec (.of (affineBlowUpAlgebra (C.ideal V) c)), ⊤) :=
    map_mem_nonZeroDivisors_of_ringEquiv
      (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V)
          c))).symm.commRingCatIsoToRingEquiv
      affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors
  rw [chartGerm_apply]
  exact germ_mem_nonZeroDivisors ⟨⊤, isAffineOpen_top _⟩ (TopologicalSpace.Opens.mem_top q) hs

/-- The exceptional ideal pulled back to the chart of `c` is generated at every point by `c`
(`comap_exceptionalDivisor_chart`).
-/
theorem stalkIdeal_comap_chart (C : X.IdealSheafData) (V : X.affineOpens) (c : C.ideal V)
    (q : Spec (.of (affineBlowUpAlgebra (C.ideal V) c))) :
    ((C.comap C.blowUpπ).comap (blowUp.chart C V c)).stalkIdeal q =
      Ideal.span {chartGerm _ q
        (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c) c)} := by
  change (C.exceptionalDivisor.comap _).stalkIdeal q = _
  rw [blowUp.comap_exceptionalDivisor_chart, stalkIdeal_specIdealSheaf,
    Ideal.map_span, Set.image_singleton]
  rfl

/-- The germ of `π_X^* s` at a point of the chart of `c'`, read on the chart, is the image of
`algebraMap s` (`appLE_chart_comp_π`).
-/
theorem chart_stalkMap_π_stalkMap_germ (C : X.IdealSheafData) (V : X.affineOpens)
    (c' c : C.ideal V) (q : Spec (.of (affineBlowUpAlgebra (C.ideal V) c')))
    (hp : C.blowUpπ ((blowUp.chart C V c') q) ∈ V.1) :
    (blowUp.chart C V c').stalkMap q (C.blowUpπ.stalkMap
        ((blowUp.chart C V c') q) (X.presheaf.germ V.1 _ hp c)) =
      chartGerm _ q (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c') c) :=
          by
  have e1 : C.blowUpπ.stalkMap ((blowUp.chart C V c') q)
      (X.presheaf.germ V.1 _ hp c) =
      C.blowUp.presheaf.germ (C.blowUpπ ⁻¹ᵁ V.1)
          ((blowUp.chart C V c') q) hp
        (C.blowUpπ.appLE V.1 (C.blowUpπ ⁻¹ᵁ V.1) le_rfl
            c) :=
    (Scheme.Hom.germ_appLE_apply C.blowUpπ V.1
        (C.blowUpπ ⁻¹ᵁ V.1) le_rfl hp hp c).symm
  have e2 : (blowUp.chart C V c').stalkMap q
      (C.blowUp.presheaf.germ (C.blowUpπ ⁻¹ᵁ V.1)
          ((blowUp.chart C V c') q) hp
        (C.blowUpπ.appLE V.1 (C.blowUpπ ⁻¹ᵁ V.1) le_rfl
            c)) =
      (Spec (.of (affineBlowUpAlgebra (C.ideal V) c'))).presheaf.germ ⊤ q
        (TopologicalSpace.Opens.mem_top q) ((blowUp.chart C V c').appLE
          (C.blowUpπ ⁻¹ᵁ V.1) ⊤ (chart_le_preimage C V c')
          (C.blowUpπ.appLE V.1 (C.blowUpπ ⁻¹ᵁ V.1) le_rfl
              c)) :=
    (Scheme.Hom.germ_appLE_apply (blowUp.chart C V c') (C.blowUpπ ⁻¹ᵁ V.1) ⊤
      (chart_le_preimage C V c') (TopologicalSpace.Opens.mem_top q) hp _).symm
  have e3 : (blowUp.chart C V c').appLE (C.blowUpπ ⁻¹ᵁ V.1) ⊤
      (chart_le_preimage C V c') (C.blowUpπ.appLE V.1
          (C.blowUpπ ⁻¹ᵁ V.1) le_rfl c) =
      (blowUp.chart C V c' ≫ C.blowUpπ).appLE V.1 ⊤
        (chart_comp_le C V c') c :=
    congrArg (fun φ : Γ(X, V) ⟶ Γ(Spec (.of (affineBlowUpAlgebra (C.ideal V) c')),
        ⊤)
      => φ c) (Scheme.Hom.appLE_comp_appLE (blowUp.chart C V c') C.blowUpπ V.1
        (C.blowUpπ ⁻¹ᵁ V.1) ⊤ le_rfl (chart_le_preimage C V c'))
  have e5 : (Spec (.of (affineBlowUpAlgebra (C.ideal V) c'))).presheaf.germ ⊤ q
        (TopologicalSpace.Opens.mem_top q) ((blowUp.chart C V c' ≫ C.blowUpπ).appLE
          V.1 ⊤ (chart_comp_le C V c') c) =
      chartGerm _ q (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c') c) :=
    (congrArg (fun s => (Spec (.of (affineBlowUpAlgebra (C.ideal V)
        c'))).presheaf.germ
      ⊤ q (TopologicalSpace.Opens.mem_top q) s) (appLE_chart_comp_π C V c' c)).trans
      (chartGerm_apply _ q _).symm
  exact (congrArg (fun y => (blowUp.chart C V c').stalkMap q y) e1).trans
    (e2.trans ((congrArg (fun s => (Spec (.of (affineBlowUpAlgebra (C.ideal V) c'))
      ).presheaf.germ ⊤ q (TopologicalSpace.Opens.mem_top q) s) e3).trans e5))

/-- If the exceptional ideal at a point `p` of the chart of `c'` is generated by `π_X^* c`, then on
the chart it is generated by the image of `algebraMap c`.
-/
theorem stalkIdeal_comap_chart_of_span (C : X.IdealSheafData) (V : X.affineOpens)
    (c' c : C.ideal V) (q : Spec (.of (affineBlowUpAlgebra (C.ideal V) c')))
    (hp : C.blowUpπ ((blowUp.chart C V c') q) ∈ V.1)
    (hgen : (C.comap C.blowUpπ).stalkIdeal ((blowUp.chart C V c') q) =
      Ideal.span {C.blowUpπ.stalkMap ((blowUp.chart C V c') q)
        (X.presheaf.germ V.1 _ hp c)}) :
    ((C.comap C.blowUpπ).comap (blowUp.chart C V c')).stalkIdeal q =
      Ideal.span {chartGerm _ q
        (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c') c)} := by
  rw [stalkIdeal_comap]
  refine (congrArg (Ideal.map ((blowUp.chart C V c').stalkMap q).hom)
    hgen).trans ?_
  rw [Ideal.map_span, Set.image_singleton]
  exact congrArg (fun x => Ideal.span {x}) (chart_stalkMap_π_stalkMap_germ C V c' c q hp)

/-! ### Generators of the chart algebra as a ring -/
/-- The chart algebra `R[I/a]` is generated as a ring by the image of `R` and the ratios `b / a`,
`b ∈ I`. -/
theorem subring_closure_chart_generators_eq_top {R : Type*} [CommRing R] (I : Ideal R) (a : I) :
    Subring.closure (Set.range (algebraMap R (affineBlowUpAlgebra I (a : R))) ∪
      Set.range (affineBlowUpAlgebra.ratio I a)) = ⊤ := by
  set S := affineBlowUpAlgebra I (a : R) with hS
  set T := Set.range (algebraMap R S) ∪ Set.range (affineBlowUpAlgebra.ratio I a)
    with hT
  rw [Subring.eq_top_iff']
  intro y
  have hy : (y : Localization.Away (a : R)) ∈ (Algebra.adjoin R
      ((fun x => Localization.mk x ⟨(a : R), Submonoid.mem_powers _⟩) '' (I : Set R))).toSubring :=
    y.2
  rw [Algebra.adjoin_eq_ring_closure] at hy
  have himg : (SubringClass.subtype S) '' T = Set.range (algebraMap R (Localization.Away (a : R))) ∪
      (fun x => Localization.mk x ⟨(a : R), Submonoid.mem_powers _⟩) '' (I : Set R) := by
    rw [hT, Set.image_union]
    congr 1
    · ext z
      constructor
      · rintro ⟨_, ⟨r, rfl⟩, rfl⟩
        exact ⟨r, (Subalgebra.coe_algebraMap S r).symm⟩
      · rintro ⟨r, rfl⟩
        exact ⟨algebraMap R S r, ⟨r, rfl⟩, Subalgebra.coe_algebraMap S r⟩
    · ext z
      constructor
      · rintro ⟨_, ⟨b, rfl⟩, rfl⟩
        exact ⟨b, b.2, (awayFrac_one (a := (a : R)) (b : R)).symm⟩
      · rintro ⟨x, hx, rfl⟩
        exact ⟨affineBlowUpAlgebra.ratio I a ⟨x, hx⟩, ⟨⟨x, hx⟩, rfl⟩,
          awayFrac_one (a := (a : R)) x⟩
  rw [← himg, ← RingHom.map_closure, Subring.mem_map] at hy
  obtain ⟨y', hy', hyy⟩ := hy
  exact (Subtype.ext hyy : y' = y) ▸ hy'

/-- Kollár's `y_j x_r = x_j`: the ratio identity `(b / c) · c = b` in the chart algebra
(`awayFrac_mul_algebraMap_pow`).
-/
theorem ratio_mul_algebraMap {R : Type*} [CommRing R] (I : Ideal R) (a b : I) :
    affineBlowUpAlgebra.ratio I a b * algebraMap R
        (affineBlowUpAlgebra I (a : R)) a =
      algebraMap R (affineBlowUpAlgebra I (a : R)) b := by
  apply Subtype.ext
  rw [Subalgebra.coe_mul, Subalgebra.coe_algebraMap, Subalgebra.coe_algebraMap]
  change awayFrac (a : R) 1 (b : R) * algebraMap R (Localization.Away (a : R)) a =
    algebraMap R _ b
  have := affineBlowUpAlgebra.awayFrac_mul_algebraMap_pow (a := (a : R)) 1 (b : R)
  rwa [pow_one] at this

/-- The ratio identity transported to the sections of the chart of `a` in the blow-up: with `θ z :=
(chart.appIso ⊤).inv ((ΓSpecIso _).inv z)`, `θ (b / a) · θ a = θ b`.
-/
theorem appIso_inv_ΓSpecIso_inv_ratio_mul (C : X.IdealSheafData) (V : X.affineOpens)
    (a b : C.ideal V) :
    ((blowUp.chart C V a).appIso ⊤).inv
        ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) a))).inv
          (affineBlowUpAlgebra.ratio (C.ideal V) a b)) *
      ((blowUp.chart C V a).appIso ⊤).inv
        ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) a))).inv
          (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) a) a)) =
      ((blowUp.chart C V a).appIso ⊤).inv
        ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) a))).inv
          (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) a) b)) :=
  (map_mul ((blowUp.chart C V a).appIso ⊤).inv.hom _ _).symm.trans
    ((congrArg (fun t => ((blowUp.chart C V a).appIso ⊤).inv t)
      (map_mul (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) a))).inv.hom
        _ _).symm).trans
      (congrArg (fun z => ((blowUp.chart C V a).appIso ⊤).inv
        ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) a))).inv z))
        (ratio_mul_algebraMap (C.ideal V) a b)))

/-! ### The converse: a point where the chart function generates lies in the chart -/
/-- A point of the blow-up over `V` at which the exceptional ideal is generated by `π_X^* c` lies
in the chart of `c`: on whichever chart `c'` contains it, the ratio `c / c'` is a unit there, and
the chart of `c` meets the chart of `c'` in the basic open of that ratio. -/
theorem mem_chartOpen_of_stalkIdeal_eq_span (C : X.IdealSheafData) (V : X.affineOpens)
    (c : C.ideal V) {p : C.blowUp} (hp : C.blowUpπ p ∈
        V.1)
    (hgen : (C.comap C.blowUpπ).stalkIdeal p =
      Ideal.span {C.blowUpπ.stalkMap p (X.presheaf.germ V.1 _ hp c)}) :
    p ∈ (chartOpen C V c).1 := by
  have hp' : p ∈ C.blowUpπ ⁻¹ᵁ V.1 := hp
  rw [← blowUp.iSup_opensRange_chart C V, TopologicalSpace.Opens.mem_iSup] at hp'
  obtain ⟨c', hc'⟩ := hp'
  obtain ⟨q', rfl⟩ := Scheme.Hom.mem_opensRange.mp hc'
  have h2 := stalkIdeal_comap_chart_of_span C V c' c q' hp hgen
  have hnzd := chartGerm_algebraMap_mem_nonZeroDivisors C V c' q'
  obtain ⟨v, hv, hvc⟩ := exists_isUnit_mul_of_span_singleton_eq hnzd
    (h2.symm.trans (stalkIdeal_comap_chart C V c' q'))
  have h3 := congrArg (chartGerm (.of (affineBlowUpAlgebra (C.ideal V) c')) q')
    (ratio_mul_algebraMap (C.ideal V) c' c)
  rw [map_mul, hvc] at h3
  have h4 : chartGerm _ q' (algebraMap Γ(X, V) _ c') *
      chartGerm _ q' (affineBlowUpAlgebra.ratio (C.ideal V) c' c) =
      chartGerm _ q' (algebraMap Γ(X, V) _ c') * v :=
    (mul_comm _ _).trans (h3.trans (mul_comm _ _))
  have hr := (mul_cancel_left_mem_nonZeroDivisors hnzd).mp h4
  have hunit : IsUnit (chartGerm (.of (affineBlowUpAlgebra (C.ideal V) c')) q'
      (affineBlowUpAlgebra.ratio (C.ideal V) c' c)) :=
    (congrArg (fun x => IsUnit x) hr).mpr hv
  have hq : q' ∈ PrimeSpectrum.basicOpen (affineBlowUpAlgebra.ratio
      (C.ideal V) c' c) :=
    (PrimeSpectrum.mem_basicOpen _ q').mpr ((isUnit_chartGerm_iff _ q' _).mp hunit)
  rw [← blowUp.chart_preimage_chart C V c' c] at hq
  change (blowUp.chart C V c') q' ∈ blowUp.chart C V c ''ᵁ ⊤
  rw [Scheme.Hom.image_top_eq_opensRange]
  exact hq

/-- `appLE` respects an equality of morphisms. -/
theorem appLE_eq_of_eq {B : Scheme.{u}} (h h' : B ⟶ X) (hh : h = h') (V : X.Opens) (W : B.Opens)
    (e : W ≤ h ⁻¹ᵁ V) (s : Γ(X, V)) : h.appLE V W e s = h'.appLE V W (hh ▸ e) s := by
  subst hh; rfl

/-- The germ of a section pulled back along `π ≫ f` is the composite of the stalk maps applied to
the germ (`appLE_comp_appLE`, `germ_appLE_apply`, `germ_stalkMap_apply`).
-/
theorem germ_appLE_comp_eq {T : Scheme.{u}} (π : T ⟶ U) (f : U ⟶ X) (V : X.Opens) (W : T.Opens)
    (e : W ≤ (π ≫ f) ⁻¹ᵁ V) {w : T} (hw : w ∈ W) (hfw : f (π w) ∈ V) (s : Γ(X, V)) :
    T.presheaf.germ W w hw ((π ≫ f).appLE V W e s) =
      π.stalkMap w (f.stalkMap (π w) (X.presheaf.germ V _ hfw s)) := by
  have hf := Scheme.Hom.appLE_comp_appLE π f V (f ⁻¹ᵁ V) W le_rfl e
  rw [← hf, CommRingCat.comp_apply, ← Scheme.Hom.app_eq_appLE,
    Scheme.Hom.germ_appLE_apply π (f ⁻¹ᵁ V) W e hw hfw, Scheme.Hom.germ_stalkMap_apply]

/-! ### Equality of two morphisms into an affine chart on an affine piece of `V(N)` -/
/-- Two morphisms `φ, φ'` that map an affine open `W` into the affine chart `ch : Spec A ⟶ Y` agree
on `V(N) ∩ W` as soon as the defects of a set of ring generators of `A` lie in `N(W)`: the
restrictions to `V(N) ∩ W` factor through the chart, and morphisms into an affine scheme are
determined by their maps on global sections. -/
theorem eq_comp_of_forall_gen {B Y : Scheme.{u}} (φ φ' : B ⟶ Y) {A : CommRingCat.{u}}
    (ch : Spec A ⟶ Y) [IsOpenImmersion ch] (W : B.affineOpens)
    (hW : W.1 ≤ φ ⁻¹ᵁ (ch ''ᵁ ⊤)) (hW' : W.1 ≤ φ' ⁻¹ᵁ (ch ''ᵁ ⊤)) (N : B.IdealSheafData)
    {T : Set A} (hT : Subring.closure T = ⊤)
    (h : ∀ s ∈ T, φ.appLE (ch ''ᵁ ⊤) W.1 hW ((ch.appIso ⊤).inv ((Scheme.ΓSpecIso A).inv s)) -
      φ'.appLE (ch ''ᵁ ⊤) W.1 hW' ((ch.appIso ⊤).inv ((Scheme.ΓSpecIso A).inv s)) ∈ N.ideal W) :
    (N.subschemeι ⁻¹ᵁ W.1).ι ≫ N.subschemeι ≫ φ =
      (N.subschemeι ⁻¹ᵁ W.1).ι ≫ N.subschemeι ≫ φ' := by
  have hr : ∀ ψ : B ⟶ Y, W.1 ≤ ψ ⁻¹ᵁ (ch ''ᵁ ⊤) →
      Set.range ((N.subschemeι ⁻¹ᵁ W.1).ι ≫ N.subschemeι ≫ ψ) ⊆ Set.range ch := by
    intro ψ hψ
    rintro _ ⟨z, rfl⟩
    have hz : N.subschemeι ((N.subschemeι ⁻¹ᵁ W.1).ι z) ∈ W.1 := z.2
    have hmem := hψ hz
    rw [Scheme.Hom.image_top_eq_opensRange] at hmem
    obtain ⟨y, hy⟩ := Scheme.Hom.mem_opensRange.mp hmem
    exact ⟨y, by rw [hy]; rfl⟩
  have hfa := IsOpenImmersion.lift_fac ch _ (hr φ hW)
  have hfa' := IsOpenImmersion.lift_fac ch _ (hr φ' hW')
  rw [← hfa, ← hfa']
  congr 1
  apply AlgebraicGeometry.ext_of_isAffine
  have key : ∀ (ψ : B ⟶ Y) (hψ : W.1 ≤ ψ ⁻¹ᵁ (ch ''ᵁ ⊤)) (y : Γ(Spec A, ⊤)),
      (IsOpenImmersion.lift ch _ (hr ψ hψ)).appTop y =
        (N.subschemeι ⁻¹ᵁ W.1).ι.appLE (N.subschemeι ⁻¹ᵁ W.1) ⊤ (fun x _ => x.2)
          (N.subschemeι.app W.1 (ψ.appLE (ch ''ᵁ ⊤) W.1 hψ ((ch.appIso ⊤).inv y))) := by
    intro ψ hψ y
    set l := IsOpenImmersion.lift ch _ (hr ψ hψ) with hl
    have hlf : l ≫ ch = (N.subschemeι ⁻¹ᵁ W.1).ι ≫ N.subschemeι ≫ ψ :=
      IsOpenImmersion.lift_fac ch _ (hr ψ hψ)
    have e₁ : (⊤ : (Spec A).Opens) ≤ ch ⁻¹ᵁ (ch ''ᵁ ⊤) := (Scheme.Hom.preimage_image_eq ch ⊤).ge
    have e₂ : (⊤ : (N.subschemeι ⁻¹ᵁ W.1 : Scheme).Opens) ≤ l ⁻¹ᵁ ⊤ := fun _ _ => trivial
    have hc := Scheme.Hom.appLE_comp_appLE l ch (ch ''ᵁ ⊤) ⊤ ⊤ e₁ e₂
    have hy : ch.appLE (ch ''ᵁ ⊤) ⊤ e₁ ((ch.appIso ⊤).inv y) = y := by
      rw [← Scheme.Hom.appIso_hom']; simp
    have e₁' : N.subschemeι ⁻¹ᵁ W.1 ≤ (N.subschemeι ≫ ψ) ⁻¹ᵁ (ch ''ᵁ ⊤) := fun x hx => hψ hx
    have e₂' : (⊤ : (N.subschemeι ⁻¹ᵁ W.1 : Scheme).Opens) ≤
        (N.subschemeι ⁻¹ᵁ W.1).ι ⁻¹ᵁ (N.subschemeι ⁻¹ᵁ W.1) := fun x _ => x.2
    have h0 : l.appTop y = l.appLE ⊤ ⊤ e₂ y := by
      change l.app ⊤ y = _
      rw [Scheme.Hom.app_eq_appLE]
      rfl
    calc l.appTop y = l.appLE ⊤ ⊤ e₂ y := h0
      _ = l.appLE ⊤ ⊤ e₂ (ch.appLE (ch ''ᵁ ⊤) ⊤ e₁ ((ch.appIso ⊤).inv y)) := by rw [hy]
      _ = (l ≫ ch).appLE (ch ''ᵁ ⊤) ⊤ _ ((ch.appIso ⊤).inv y) := by
          rw [← hc, CommRingCat.comp_apply]
      _ = ((N.subschemeι ⁻¹ᵁ W.1).ι ≫ N.subschemeι ≫ ψ).appLE (ch ''ᵁ ⊤) ⊤ _
            ((ch.appIso ⊤).inv y) := appLE_eq_of_eq _ _ hlf _ _ _ _
      _ = (N.subschemeι ⁻¹ᵁ W.1).ι.appLE (N.subschemeι ⁻¹ᵁ W.1) ⊤ e₂'
            ((N.subschemeι ≫ ψ).appLE (ch ''ᵁ ⊤) (N.subschemeι ⁻¹ᵁ W.1) e₁'
              ((ch.appIso ⊤).inv y)) := by
          rw [← Scheme.Hom.appLE_comp_appLE (N.subschemeι ⁻¹ᵁ W.1).ι (N.subschemeι ≫ ψ) (ch ''ᵁ ⊤)
            (N.subschemeι ⁻¹ᵁ W.1) ⊤ e₁' e₂', CommRingCat.comp_apply]
      _ = (N.subschemeι ⁻¹ᵁ W.1).ι.appLE (N.subschemeι ⁻¹ᵁ W.1) ⊤ e₂'
            (N.subschemeι.appLE W.1 (N.subschemeι ⁻¹ᵁ W.1) le_rfl
              (ψ.appLE (ch ''ᵁ ⊤) W.1 hψ ((ch.appIso ⊤).inv y))) := by
          rw [← Scheme.Hom.appLE_comp_appLE N.subschemeι ψ (ch ''ᵁ ⊤) W.1 (N.subschemeι ⁻¹ᵁ W.1)
            hψ le_rfl, CommRingCat.comp_apply]
      _ = _ := by rw [← Scheme.Hom.app_eq_appLE]
  ext x
  have hx : x = (Scheme.ΓSpecIso A).inv ((Scheme.ΓSpecIso A).hom x) := by simp
  rw [hx, key φ hW, key φ' hW']
  congr 1
  let ρ : A →+* Γ(N.subscheme, N.subschemeι ⁻¹ᵁ W.1) :=
    (N.subschemeι.app W.1).hom.comp ((φ.appLE (ch ''ᵁ ⊤) W.1 hW).hom.comp
      ((ch.appIso ⊤).inv.hom.comp (Scheme.ΓSpecIso A).inv.hom))
  let ρ' : A →+* Γ(N.subscheme, N.subschemeι ⁻¹ᵁ W.1) :=
    (N.subschemeι.app W.1).hom.comp ((φ'.appLE (ch ''ᵁ ⊤) W.1 hW').hom.comp
      ((ch.appIso ⊤).inv.hom.comp (Scheme.ΓSpecIso A).inv.hom))
  have hgen := sub_mem_of_forall_mem_closure ρ ρ' ⊥ hT (fun s hs => by
    have hker := h s hs
    rw [← ker_subschemeι_app N W, RingHom.mem_ker] at hker
    rw [Ideal.mem_bot]
    simpa [ρ, ρ', RingHom.comp_apply, map_sub] using hker) ((Scheme.ΓSpecIso A).hom x)
  rw [Ideal.mem_bot, sub_eq_zero] at hgen
  simpa [ρ, ρ', RingHom.comp_apply] using hgen


/-! ### The exceptional ideal as the pull-back of the target's exceptional ideal along a lift
-/
/-- For a lift `φ : B_J U ⟶ B_C X` over `f₀` with `f₀^* C = J`, the pull-back of the exceptional
ideal of `B_C X` is the exceptional ideal of `B_J U`. -/
theorem comap_comap_eq_exceptionalDivisor (f₀ : U ⟶ X) (C : X.IdealSheafData) (J : U.IdealSheafData)
    (hJ₀ : C.comap f₀ = J) (φ : J.blowUp ⟶ C.blowUp)
    (hφ : φ ≫ C.blowUpπ = J.blowUpπ ≫ f₀) :
    (C.comap C.blowUpπ).comap φ = J.exceptionalDivisor := by
  change _ = J.comap J.blowUpπ
  rw [← comap_comp, hφ, comap_comp, hJ₀]

/-! ### The chart function pulled back along a lift, at the stalk -/
/-- Along a lift `φ` over `f₀`, the germ of `π_X^* s` on the chart pulls back to the germ of
`π^* f₀^* s`. -/
theorem stalkMap_germ_appLE_chart_eq (f₀ : U ⟶ X) (C : X.IdealSheafData) (J : U.IdealSheafData)
    (φ : J.blowUp ⟶ C.blowUp)
        (hφ : φ ≫ C.blowUpπ = J.blowUpπ ≫ f₀)
        (V : X.affineOpens)
    (c : C.ideal V) {w : J.blowUp} (hw : φ w ∈ (chartOpen C V c).1)
    (hfw : f₀ (J.blowUpπ w) ∈ V.1) (s : Γ(X, V)) :
    φ.stalkMap w (C.blowUp.presheaf.germ (chartOpen C V c).1 (φ w) hw
        (C.blowUpπ.appLE V.1 (chartOpen C V c).1
          (chart_image_top_le C V c) s)) =
      J.blowUpπ.stalkMap w (f₀.stalkMap _ (X.presheaf.germ V.1 _ hfw s)) := by
  have e1 := Scheme.Hom.germ_appLE_apply φ (chartOpen C V c).1
    (φ ⁻¹ᵁ (chartOpen C V c).1) le_rfl hw hw
    (C.blowUpπ.appLE V.1 (chartOpen C V c).1
      (chart_image_top_le C V c) s)
  have e2 : φ.appLE (chartOpen C V c).1 (φ ⁻¹ᵁ (chartOpen C V c).1)
      le_rfl (C.blowUpπ.appLE V.1 (chartOpen C V c).1
        (chart_image_top_le C V c) s) =
      (φ ≫ C.blowUpπ).appLE V.1 (φ ⁻¹ᵁ (chartOpen C V c).1)
        (fun x hx => chart_image_top_le C V c hx) s :=
    congrArg (fun ψ : Γ(X, V) ⟶ Γ(J.blowUp, φ ⁻¹ᵁ (chartOpen C V c).1)
      => ψ s) (Scheme.Hom.appLE_comp_appLE φ C.blowUpπ V.1
        (chartOpen C V c).1 _ (chart_image_top_le C V c) le_rfl)
  have e3 := appLE_eq_of_eq (φ ≫ C.blowUpπ)
      (J.blowUpπ ≫ f₀) hφ V.1
    (φ ⁻¹ᵁ (chartOpen C V c).1)
    (fun x hx => chart_image_top_le C V c hx) s
  rw [← e1, e2, e3, germ_appLE_comp_eq J.blowUpπ f₀ V.1 (φ ⁻¹ᵁ (chartOpen C V
      c).1)
    _ (w := w) hw hfw]

/-! ### The exceptional ideal at a point of a chart preimage is generated by the chart function
-/
/-- At a point `w` of `B_J U` whose image under the lift lies in the chart of `c`, the exceptional
ideal of `B_J U` is generated by `π^* f₀^* c`. -/
theorem stalkIdeal_exceptionalDivisor_eq_span (f₀ : U ⟶ X) (C : X.IdealSheafData)
    (J : U.IdealSheafData) (hJ₀ : C.comap f₀ = J) (φ : J.blowUp ⟶
        C.blowUp)
    (hφ : φ ≫ C.blowUpπ = J.blowUpπ ≫ f₀)
        (V : X.affineOpens) (c : C.ideal V)
    {w : J.blowUp} (hw : φ w ∈ (chartOpen C V c).1)
    (hfw : f₀ (J.blowUpπ w) ∈ V.1) :
    J.exceptionalDivisor.stalkIdeal w =
      Ideal.span {J.blowUpπ.stalkMap w (f₀.stalkMap _
          (X.presheaf.germ V.1 _ hfw c))} := by
  rw [← comap_comap_eq_exceptionalDivisor f₀ C J hJ₀ φ hφ, stalkIdeal_comap_comap_eq_span C V c φ
      hw,
    stalkMap_germ_appLE_chart_eq f₀ C J φ hφ V c hw hfw]

/-! ### The transported second lift over the projection -/
/-- The second lift, transported to `B_{f^{-1} C} U` along `f^{-1} C = g^{-1} C`, lies over `g`. -/
theorem eqToHom_comp_blowUpMap_comp_π (f g : U ⟶ X) (C : X.IdealSheafData)
    (hJ : C.comap f = C.comap g) :
    (eqToHom (congrArg Scheme.IdealSheafData.blowUp hJ) ≫ Scheme.Hom.blowUpMap g C) ≫
        C.blowUpπ =
      (C.comap f).blowUpπ ≫ g := by
  have h1' : Scheme.Hom.blowUpMap g C ≫ C.blowUpπ = (C.comap g).blowUpπ ≫ g :=
    blowUpMap_π g C
  rw [Category.assoc, h1', ← Category.assoc]
  congr 1
  exact eqToHom_comp_blowUpπ hJ


/-! ### The sections of the chart generators pulled back along a lift -/
/-- An open of `B_J U` mapped into the chart of `c` by a lift over `f₀` lies over `V`. -/
theorem le_preimage_comp (f₀ : U ⟶ X) (C : X.IdealSheafData) (J : U.IdealSheafData)
    (φ : J.blowUp ⟶ C.blowUp)
        (hφ : φ ≫ C.blowUpπ = J.blowUpπ ≫ f₀)
        (V : X.affineOpens)
    (c : C.ideal V) (W : J.blowUp.Opens) (hW : W ≤ φ ⁻¹ᵁ
        (chartOpen C V c).1) :
    W ≤ (J.blowUpπ ≫ f₀) ⁻¹ᵁ V.1 := by
  intro x hx
  have h1 : C.blowUpπ (φ x) ∈ V.1 := chart_image_top_le C V c (hW hx)
  have h2 : (φ ≫ C.blowUpπ) x = (J.blowUpπ ≫ f₀) x :=
    congrArg (fun h : J.blowUp ⟶ X => h x) hφ
  change (J.blowUpπ ≫ f₀) x ∈ V.1
  rw [← h2, Scheme.Hom.comp_apply]
  exact h1

/-- Kollár's "this is clear if `y_j = x_j`": the pull-back along a lift of the chart section
`θ (algebraMap r)` is the section `π^* f₀^* r` (`appLE_chart_eq`, `appLE_comp_appLE`).
-/
theorem appLE_chart_algebraMap_eq (f₀ : U ⟶ X) (C : X.IdealSheafData) (J : U.IdealSheafData)
    (φ : J.blowUp ⟶ C.blowUp)
        (hφ : φ ≫ C.blowUpπ = J.blowUpπ ≫ f₀)
        (V : X.affineOpens)
    (c : C.ideal V) (W : J.blowUp.Opens) (hW : W ≤ φ ⁻¹ᵁ (chartOpen C V c).1)
    (r : Γ(X, V)) :
    φ.appLE (chartOpen C V c).1 W hW
        (((blowUp.chart C V c).appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
            (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c) r))) =
      (J.blowUpπ ≫ f₀).appLE V.1 W (le_preimage_comp f₀ C J φ hφ V c W hW) r :=
          by
  rw [← appLE_chart_eq C V c r]
  have e2 := congrArg (fun ψ : Γ(X, V) ⟶ Γ(J.blowUp, W) => ψ r)
    (Scheme.Hom.appLE_comp_appLE φ C.blowUpπ V.1 (chartOpen C V c).1 W
      (chart_image_top_le C V c) hW)
  simp only [CommRingCat.comp_apply] at e2
  rw [e2]
  exact appLE_eq_of_eq _ _ hφ V.1 W _ r

/-- Kollár's `ψ^*_{i+1}(y_j) · ψ^*_{i+1}(x_r) = ψ^*_{i+1}(x_j)`: the pull-back along a lift of the
chart section `θ (b / c)` times `π^* f₀^* c` is `π^* f₀^* b`.
-/
theorem appLE_chart_ratio_mul (f₀ : U ⟶ X) (C : X.IdealSheafData) (J : U.IdealSheafData)
    (φ : J.blowUp ⟶ C.blowUp)
        (hφ : φ ≫ C.blowUpπ = J.blowUpπ ≫ f₀)
        (V : X.affineOpens)
    (c : C.ideal V) (W : J.blowUp.Opens) (hW : W ≤ φ ⁻¹ᵁ (chartOpen C V c).1)
    (b : C.ideal V) :
    φ.appLE (chartOpen C V c).1 W hW
        (((blowUp.chart C V c).appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
            (affineBlowUpAlgebra.ratio (C.ideal V) c b))) *
      (J.blowUpπ ≫ f₀).appLE V.1 W (le_preimage_comp f₀ C J φ hφ V c W hW) c =
      (J.blowUpπ ≫ f₀).appLE V.1 W (le_preimage_comp f₀ C J φ hφ V c W hW) b :=
          by
  have h1 := appLE_chart_algebraMap_eq f₀ C J φ hφ V c W hW c
  have h2 := appLE_chart_algebraMap_eq f₀ C J φ hφ V c W hW b
  have h3 := appIso_inv_ΓSpecIso_inv_ratio_mul C V c b
  calc _ = φ.appLE (chartOpen C V c).1 W hW
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c b))) *
        φ.appLE (chartOpen C V c).1 W hW
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c) c))) :=
        congrArg (fun t => φ.appLE (chartOpen C V c).1 W hW
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c b))) * t) h1.symm
    _ = _ := (map_mul (φ.appLE (chartOpen C V c).1 W hW).hom _ _).symm
    _ = _ := congrArg (fun t => φ.appLE (chartOpen C V c).1 W hW t) h3
    _ = _ := h2

/-! ### The local step: an affine neighbourhood of a point of `V(M')` on which the lifts agree -/
/-- The local step of the descent: every point `u` of `V(M')`, `M' = π^{-1}_*(M, 1)`, has an affine
neighbourhood `W` such that the two lifts `f', g'` agree on `V(M') ∩ W`. This is steps 1–5 of the
proof described in the module docstring. -/
theorem exists_affineOpens_eq_comp (f g : U ⟶ X) (C : X.IdealSheafData) (J M : U.IdealSheafData)
    (hJf : C.comap f = J) (hJg : C.comap g = J) (hM : M ≤ J) (hfg : AgreeOn f g M)
    (f' g' : J.blowUp ⟶ C.blowUp)
        (hf' : f' ≫ C.blowUpπ = J.blowUpπ ≫ f)
    (hg' : g' ≫ C.blowUpπ = J.blowUpπ ≫ g)
        (u : J.blowUp)
    (hu : u ∈ (M.markedTransform J 1).support) :
    ∃ W : J.blowUp.affineOpens, u ∈ W.1 ∧
      ((M.markedTransform J 1).subschemeι ⁻¹ᵁ W.1).ι ≫ (M.markedTransform J 1).subschemeι ≫ f' =
      ((M.markedTransform J 1).subschemeι ⁻¹ᵁ W.1).ι ≫ (M.markedTransform J 1).subschemeι ≫ g' := by
  have hinv : J.exceptionalDivisor.IsInvertible :=
    blowUp.isInvertible_comap_π J
  have hπu : J.blowUpπ u ∈ M.support :=
      support_markedTransform_one_subset J M hu
  have hfgu : f (J.blowUpπ u) = g (J.blowUpπ u) :=
      hfg.base_eq hπu
  have hpt : ∀ (f₀ : U ⟶ X) (φ : J.blowUp ⟶ C.blowUp)
      (hφ : φ ≫ C.blowUpπ = J.blowUpπ ≫ f₀)
          (w : J.blowUp),
      C.blowUpπ (φ w) = f₀ (J.blowUpπ w) := by
    intro f₀ φ hφ w
    rw [← Scheme.Hom.comp_apply φ C.blowUpπ w, hφ, Scheme.Hom.comp_apply]
  obtain ⟨V, hV⟩ := exists_affineOpens_mem (f (J.blowUpπ u))
  have hVg : g (J.blowUpπ u) ∈ V.1 := hfgu ▸ hV
  -- (1) a chart `c` containing `f' u`
  have hfu : f' u ∈ C.blowUpπ ⁻¹ᵁ V.1 := by
    change C.blowUpπ (f' u) ∈ V.1
    exact (hpt f f' hf' u).symm ▸ hV
  rw [← blowUp.iSup_opensRange_chart C V, TopologicalSpace.Opens.mem_iSup] at hfu
  obtain ⟨c, hc⟩ := hfu
  have hfc : f' u ∈ (chartOpen C V c).1 := by
    change _ ∈ blowUp.chart C V c ''ᵁ ⊤
    rw [Scheme.Hom.image_top_eq_opensRange]; exact hc
  -- (2) the exceptional ideal at `u` is generated by `π^* f^* c`
  have hgenF := stalkIdeal_exceptionalDivisor_eq_span f C J hJf f' hf' V c hfc hV
  -- (3) the common chart: `g' u` lies in the chart of `c`
  have hgu : C.blowUpπ (g' u) ∈ V.1 := (hpt g g' hg' u).symm ▸ hVg
  have hgu' : g' u ∈ C.blowUpπ ⁻¹ᵁ V.1 := hgu
  rw [← blowUp.iSup_opensRange_chart C V, TopologicalSpace.Opens.mem_iSup] at hgu'
  obtain ⟨c', hc'⟩ := hgu'
  have hgc' : g' u ∈ (chartOpen C V c').1 := by
    change _ ∈ blowUp.chart C V c' ''ᵁ ⊤
    rw [Scheme.Hom.image_top_eq_opensRange]; exact hc'
  have hgenG := stalkIdeal_exceptionalDivisor_eq_span g C J hJg g' hg' V c' hgc' hVg
  have hdef := stalkMap_sub_stalkMap_mem_comap J.blowUpπ f g M hfg V.1 c hπu
      hV hVg
  obtain ⟨d, hd, hed⟩ := exists_mem_markedTransform_mul_eq hM hgenF hdef
  have hΨ : J.blowUpπ.stalkMap u (g.stalkMap _
      (X.presheaf.germ V.1 _ hVg c)) =
      J.blowUpπ.stalkMap u (f.stalkMap _ (X.presheaf.germ V.1 _ hV c)) *
          (1 - d) := by
    linear_combination hed
  have hunit : IsUnit (1 - d) := isUnit_one_sub_of_mem_stalkIdeal _ hu hd
  have hspanΨ : Ideal.span {J.blowUpπ.stalkMap u (g.stalkMap _
      (X.presheaf.germ V.1 _ hVg c))} =
      J.exceptionalDivisor.stalkIdeal u :=
    (congrArg (fun x => Ideal.span {x}) hΨ).trans
      ((Ideal.span_singleton_mul_right_unit hunit _).trans hgenF.symm)
  have hθ := appIso_inv_ΓSpecIso_inv_ratio_mul C V c' c
  have hsec : C.blowUpπ.appLE V.1 (chartOpen C V c').1
      (chart_image_top_le C V c') c =
      ((blowUp.chart C V c').appIso ⊤).inv
        ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c'))).inv
          (affineBlowUpAlgebra.ratio (C.ideal V) c' c)) *
      C.blowUpπ.appLE V.1 (chartOpen C V c').1
        (chart_image_top_le C V c') c' :=
    (appLE_chart_eq C V c' c).trans (hθ.symm.trans
      (congrArg (fun t => ((blowUp.chart C V c').appIso ⊤).inv
        ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c'))).inv
          (affineBlowUpAlgebra.ratio (C.ideal V) c' c)) * t)
        (appLE_chart_eq C V c' c').symm))
  have hγ : C.blowUp.presheaf.germ (chartOpen C V c').1 (g' u) hgc'
      (C.blowUpπ.appLE V.1 _ (chart_image_top_le C V c') c) =
      C.blowUp.presheaf.germ (chartOpen C V c').1 (g' u) hgc'
        (((blowUp.chart C V c').appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c'))).inv
            (affineBlowUpAlgebra.ratio (C.ideal V) c' c))) *
      C.blowUp.presheaf.germ (chartOpen C V c').1 (g' u) hgc'
        (C.blowUpπ.appLE V.1 _ (chart_image_top_le C V c') c') :=
    (congrArg (fun t => C.blowUp.presheaf.germ (chartOpen C V c').1
        (g' u) hgc'
        t)
      hsec).trans (map_mul (C.blowUp.presheaf.germ (chartOpen C V c').1 (g' u)
        hgc').hom _ _)
  have hΨc := stalkMap_germ_appLE_chart_eq g C J g' hg' V c' hgc' hVg c
  have hΨc' := stalkMap_germ_appLE_chart_eq g C J g' hg' V c' hgc' hVg c'
  obtain ⟨k, hk, hkspan⟩ := hinv.exists_mem_nonZeroDivisors_stalkIdeal_eq_span u
  have hnzd := mem_nonZeroDivisors_of_span_singleton_eq hk
    (hgenG.symm.trans hkspan).symm
  obtain ⟨v, hv, hvΨ⟩ := exists_isUnit_mul_of_span_singleton_eq hnzd (hspanΨ.trans hgenG)
  have hρunit : IsUnit (C.blowUp.presheaf.germ (chartOpen C V c').1
      (g' u) hgc'
      (((blowUp.chart C V c').appIso ⊤).inv
        ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c'))).inv
          (affineBlowUpAlgebra.ratio (C.ideal V) c' c)))) := by
    refine (isUnit_map_iff (g'.stalkMap u).hom _).mp ?_
    have h5 : g'.stalkMap u (C.blowUp.presheaf.germ (chartOpen C V c').1
        (g' u)
        hgc' (((blowUp.chart C V c').appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c'))).inv
            (affineBlowUpAlgebra.ratio (C.ideal V) c' c)))) *
        J.blowUpπ.stalkMap u (g.stalkMap _ (X.presheaf.germ V.1 _ hVg c')) =
        v * J.blowUpπ.stalkMap u (g.stalkMap _
            (X.presheaf.germ V.1 _ hVg c')) :=
      (congrArg (fun t => g'.stalkMap u (C.blowUp.presheaf.germ (chartOpen C V
          c').1
        (g' u) hgc' (((blowUp.chart C V c').appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c'))).inv
            (affineBlowUpAlgebra.ratio (C.ideal V) c' c)))) * t) hΨc'.symm).trans
        ((map_mul (g'.stalkMap u).hom _ _).symm.trans ((congrArg (fun t => g'.stalkMap u t)
            hγ.symm).trans
          (hΨc.trans hvΨ)))
    have h6 := (mul_cancel_left_mem_nonZeroDivisors hnzd).mp
      ((mul_comm _ _).trans (h5.trans (mul_comm _ _)))
    exact (congrArg (fun x => IsUnit x) h6).mpr hv
  have hgenp : (C.comap C.blowUpπ).stalkIdeal (g' u) =
      Ideal.span {C.blowUpπ.stalkMap (g' u) (X.presheaf.germ V.1 _ hgu c)} :=
    (stalkIdeal_eq_map_germ _ (chartOpen C V c') hgc').trans
      ((congrArg (Ideal.map _) (ideal_comap_π_chartOpen C V c')).trans
        ((Ideal.map_span _ _).trans ((congrArg Ideal.span Set.image_singleton).trans
          ((Ideal.span_singleton_mul_left_unit hρunit _).symm.trans
            ((congrArg (fun x => Ideal.span {x}) hγ.symm).trans
              (congrArg (fun x => Ideal.span {x})
                (Scheme.Hom.germ_appLE_apply C.blowUpπ V.1 _
                  (chart_image_top_le C V c') hgc' hgu c)))))))
  have hgc : g' u ∈ (chartOpen C V c).1 :=
    mem_chartOpen_of_stalkIdeal_eq_span C V c hgu hgenp
  -- (4) an affine neighbourhood inside both chart preimages
  have hu2 : u ∈ f' ⁻¹ᵁ (chartOpen C V c).1 ⊓
      g' ⁻¹ᵁ (chartOpen C V c).1 := ⟨hfc, hgc⟩
  obtain ⟨W₀, hW₀, huW, hWle⟩ :=
    TopologicalSpace.Opens.isBasis_iff_nbhd.mp (Scheme.isBasis_affineOpens
        J.blowUp) hu2
  refine ⟨⟨W₀, hW₀⟩, huW, ?_⟩
  have hWf : W₀ ≤ f' ⁻¹ᵁ (chartOpen C V c).1 := hWle.trans inf_le_left
  have hWg : W₀ ≤ g' ⁻¹ᵁ (chartOpen C V c).1 := hWle.trans inf_le_right
  have hfV : ∀ w ∈ W₀, f (J.blowUpπ w) ∈ V.1 := fun w hw => by
    rw [← hpt f f' hf' w]; exact chart_image_top_le C V c (hWf hw)
  have hgV : ∀ w ∈ W₀, g (J.blowUpπ w) ∈ V.1 := fun w hw => by
    rw [← hpt g g' hg' w]; exact chart_image_top_le C V c (hWg hw)
  apply eq_comp_of_forall_gen f' g' (blowUp.chart C V c) ⟨W₀, hW₀⟩ hWf hWg
    (M.markedTransform J 1) (subring_closure_chart_generators_eq_top (C.ideal V) c)
  rintro s (⟨r, rfl⟩ | ⟨b, rfl⟩)
  · -- the defect of a base function
    change f'.appLE (chartOpen C V c).1 W₀ hWf
        (((blowUp.chart C V c).appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
            (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c) r))) -
      g'.appLE (chartOpen C V c).1 W₀ hWg
        (((blowUp.chart C V c).appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
            (algebraMap Γ(X, V) (affineBlowUpAlgebra (C.ideal V) c) r))) ∈
      (M.markedTransform J 1).ideal ⟨W₀, hW₀⟩
    refine (congrArg₂ (fun x y => x - y ∈ (M.markedTransform J 1).ideal ⟨W₀, hW₀⟩)
      (appLE_chart_algebraMap_eq f C J f' hf' V c W₀ hWf r)
      (appLE_chart_algebraMap_eq g C J g' hg' V c W₀ hWg r)).mpr ?_
    apply mem_ideal_of_forall_germ_mem
    intro w hw
    by_cases hws : w ∈ (M.markedTransform J 1).support
    · have hπw : J.blowUpπ w ∈ M.support :=
        support_markedTransform_one_subset J M hws
      have g1 := germ_appLE_comp_eq J.blowUpπ f V.1 W₀
          (le_preimage_comp f C J f' hf' V c W₀
          hWf)
        hw (hfV w hw) r
      have g2 := germ_appLE_comp_eq J.blowUpπ g V.1 W₀
          (le_preimage_comp g C J g' hg' V c W₀
          hWg)
        hw (hgV w hw) r
      rw [map_sub]
      refine (congrArg₂ (fun x y => x - y ∈ (M.markedTransform J 1).stalkIdeal w) g1 g2).mpr ?_
      exact stalkIdeal_mono (comap_blowUpπ_le_markedTransform_one J M) w
        (stalkMap_sub_stalkMap_mem_comap J.blowUpπ f g M hfg V.1 r hπw
            (hfV w hw) (hgV w hw))
    · rw [stalkIdeal_eq_top_of_notMem_support _ hws]; exact Submodule.mem_top
  · -- the defect of a ratio
    change f'.appLE (chartOpen C V c).1 W₀ hWf
        (((blowUp.chart C V c).appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
            (affineBlowUpAlgebra.ratio (C.ideal V) c b))) -
      g'.appLE (chartOpen C V c).1 W₀ hWg
        (((blowUp.chart C V c).appIso ⊤).inv
          ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
            (affineBlowUpAlgebra.ratio (C.ideal V) c b))) ∈
      (M.markedTransform J 1).ideal ⟨W₀, hW₀⟩
    apply mem_ideal_of_forall_germ_mem
    intro w hw
    by_cases hws : w ∈ (M.markedTransform J 1).support
    · have hπw : J.blowUpπ w ∈ M.support :=
        support_markedTransform_one_subset J M hws
      rw [map_sub]
      have hfwc : f' w ∈ (chartOpen C V c).1 := hWf hw
      have hgenw := stalkIdeal_exceptionalDivisor_eq_span f C J hJf f' hf' V c hfwc (hfV w hw)
      have hk0 := hinv.exists_mem_nonZeroDivisors_stalkIdeal_eq_span (X :=
          J.blowUp) w
      obtain ⟨k, hk, hkspan⟩ := hk0
      have he := mem_nonZeroDivisors_of_span_singleton_eq hk
        (hgenw.symm.trans hkspan).symm
      have hf1 := congrArg (J.blowUp.presheaf.germ W₀ w hw)
        (appLE_chart_ratio_mul f C J f' hf' V c W₀ hWf b)
      have hg1 := congrArg (J.blowUp.presheaf.germ W₀ w hw)
        (appLE_chart_ratio_mul g C J g' hg' V c W₀ hWg b)
      simp only [map_mul] at hf1 hg1
      have g1c := germ_appLE_comp_eq J.blowUpπ f V.1 W₀
          (le_preimage_comp f C J f' hf' V c W₀
          hWf)
        hw (hfV w hw) c
      have g1b := germ_appLE_comp_eq J.blowUpπ f V.1 W₀
          (le_preimage_comp f C J f' hf' V c W₀
          hWf)
        hw (hfV w hw) b
      have g2c := germ_appLE_comp_eq J.blowUpπ g V.1 W₀
          (le_preimage_comp g C J g' hg' V c W₀
          hWg)
        hw (hgV w hw) c
      have g2b := germ_appLE_comp_eq J.blowUpπ g V.1 W₀
          (le_preimage_comp g C J g' hg' V c W₀
          hWg)
        hw (hgV w hw) b
      have hdc0 := exists_mem_markedTransform_mul_eq hM hgenw
        (stalkMap_sub_stalkMap_mem_comap J.blowUpπ f g M hfg V.1 c hπw
            (hfV w hw) (hgV w hw))
      have hdb0 := exists_mem_markedTransform_mul_eq hM hgenw
        (stalkMap_sub_stalkMap_mem_comap J.blowUpπ f g M hfg V.1 b hπw
            (hfV w hw) (hgV w hw))
      obtain ⟨dc, hdc, hedc⟩ := hdc0
      obtain ⟨db, hdb, hedb⟩ := hdb0
      have hunitc : IsUnit (1 - dc) := isUnit_one_sub_of_mem_stalkIdeal _ hws hdc
      have h1 : J.blowUpπ.stalkMap w (f.stalkMap _ (X.presheaf.germ V.1 _
          (hfV w hw) c)) *
          (J.blowUp.presheaf.germ W₀ w hw (f'.appLE (chartOpen C V c).1 W₀ hWf
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c
                  b))))) = J.blowUpπ.stalkMap w (f.stalkMap _ (X.presheaf.germ V.1 _ (hfV w hw) b))
                  :=
        (congrArg (fun t => t * (J.blowUp.presheaf.germ W₀ w hw (f'.appLE
            (chartOpen C V c).1 W₀ hWf
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c b)))))) g1c.symm).trans
                  ((mul_comm _ _).trans (hf1.trans g1b))
      have hg1' : (J.blowUp.presheaf.germ W₀ w hw (g'.appLE
          (chartOpen C V c).1
          W₀ hWg
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c
                  b))))) * J.blowUpπ.stalkMap w (g.stalkMap _ (X.presheaf.germ V.1 _ (hgV w hw) c))
                  =
                      (Scheme.IdealSheafData.blowUpπ
                  J).stalkMap w (g.stalkMap _ (X.presheaf.germ V.1 _ (hgV w hw) b)) :=
        (congrArg (fun t => (J.blowUp.presheaf.germ W₀ w hw (g'.appLE
            (chartOpen C V c).1 W₀ hWg
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c b))))) * t) g2c.symm).trans
                  (hg1.trans g2b)
      have h2 : J.blowUpπ.stalkMap w (f.stalkMap _ (X.presheaf.germ V.1 _
          (hfV w hw) c)) * ((1
          - dc) * (J.blowUp.presheaf.germ W₀ w hw (g'.appLE
              (chartOpen C V c).1
          W₀ hWg
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c
                  b)))))) = J.blowUpπ.stalkMap w (f.stalkMap _ (X.presheaf.germ V.1 _ (hfV w hw) b))
                  -
                      (Scheme.IdealSheafData.blowUpπ
                  J).stalkMap w (f.stalkMap _ (X.presheaf.germ V.1 _ (hfV w hw) c)) * db := by
        linear_combination hg1' + hedb - (J.blowUp.presheaf.germ W₀ w hw
            (g'.appLE
            (chartOpen C V c).1 W₀ hWg
          (((blowUp.chart C V c).appIso ⊤).inv
            ((Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (C.ideal V) c))).inv
              (affineBlowUpAlgebra.ratio (C.ideal V) c b))))) * hedc
      have hid := ratio_identity he h1 h2
      have hmem := (congrArg (fun x => x ∈ (M.markedTransform J 1).stalkIdeal w) hid).mpr
        (sub_mem hdb (Ideal.mul_mem_right _ _ hdc))
      exact (Ideal.unit_mul_mem_iff_mem _ hunitc).mp hmem
    · exact (stalkIdeal_eq_top_of_notMem_support _ hws).ge Submodule.mem_top

/-! ### The descent -/
/-- **One-step descent of agreement through a blow-up.** For morphisms `f, g : U ⟶ X`, a centre
`C ⊆ X` with `f^{-1} C = g^{-1} C`, and an ideal sheaf `M ≤ f^{-1} C` on which `f` and `g` agree,
the lifts `f̃, g̃ : B_{f^{-1} C} U ⟶ B_C X` (the second transported along `f^{-1} C = g^{-1} C`)
agree on `V(π^{-1}_*(M, 1))`. The inductive step of the proof of [Kol07, Theorem 97]; equality of
morphisms is local on the source, and `exists_affineOpens_eq_comp` gives it locally. -/
theorem agreeOn_blowUpMap (f g : U ⟶ X) (C : X.IdealSheafData) (M : U.IdealSheafData)
    (hJ : C.comap f = C.comap g) (hM : M ≤ C.comap f) (hfg : AgreeOn f g M) :
    AgreeOn (Scheme.Hom.blowUpMap f C) (eqToHom (congrArg Scheme.IdealSheafData.blowUp hJ) ≫
        Scheme.Hom.blowUpMap g C)
      (M.markedTransform (C.comap f) 1) := by
  unfold AgreeOn
  apply hom_ext_of_forall
  intro z
  obtain ⟨W, huW, hW⟩ := exists_affineOpens_eq_comp f g C (C.comap f) M rfl hJ.symm hM hfg
    (Scheme.Hom.blowUpMap f C) (eqToHom (congrArg Scheme.IdealSheafData.blowUp hJ) ≫
        Scheme.Hom.blowUpMap g C)
    (blowUpMap_π f C) (eqToHom_comp_blowUpMap_comp_π f g C hJ) _
    (subschemeι_mem_support _ z)
  exact ⟨_, huW, hW⟩


/-! ### The step assembled -/

/-- The three assertions of the induction in the proof of [Kol07, Theorem 97] at stage `i + 1`:
with flat `ψ, ψ'`, equal pulled-back centres, centres in the images and `M ≤ ψ^{-1} Z` on which
`ψ, ψ'` agree, the centres are equal (assertion (3)) and, `Z'` substituted by `Z` (assertion (1)),
the lifts agree on `V(π^{-1}_*(M, 1))` (assertion (2), `agreeOn_blowUpMap`), the second lift
transported along the equality of the pulled-back centres.
-/
theorem step_agreeOn (ψ ψ' : U ⟶ X) [Flat ψ] [Flat ψ'] (Z Z' : X.IdealSheafData)
    (M : U.IdealSheafData) (hZ : Z.comap ψ = Z'.comap ψ')
    (hsup : (Z.support : Set X) ⊆ Set.range ψ) (hsup' : (Z'.support : Set X) ⊆ Set.range ψ')
    (hM : M ≤ Z.comap ψ) (hfg : AgreeOn ψ ψ' M) :
    ∃ e : Z = Z', AgreeOn (Scheme.Hom.blowUpMap ψ Z)
      (eqToHom (congrArg Scheme.IdealSheafData.blowUp
        (hZ.trans (congrArg (fun W : X.IdealSheafData => W.comap ψ')
            e.symm))) ≫ Scheme.Hom.blowUpMap ψ' Z)
      (M.markedTransform (Z.comap ψ) 1) := by
  have e := eq_of_comap_eq_of_agreeOn_of_le ψ ψ' Z Z' M hZ hsup hsup' hM hfg
  exact ⟨e, agreeOn_blowUpMap ψ ψ' Z M
    (hZ.trans (congrArg (fun W : X.IdealSheafData => W.comap ψ') e.symm)) hM hfg⟩

end AlgebraicGeometry.Scheme.IdealSheafData
