/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.MaximalContact.FormalEquiv
import Hironaka.Scheme.BlowUp.Descent

/-!
# Completed ideals of principal stalks under automorphisms of the completion

In the proof of Theorem 92 ([Kol07, 95]) Kollár notes: "By construction `φ(Ĥ) = Ĥ'`,
`φ(Êⁱ) = Êⁱ`". With `H_p = (x₁)`, `H'_p = (x₁')` and `φ^*(x₁') = x₁`, the completed ideal
`Ĥ' = (ι x₁')` is carried to `(ι x₁) = Ĥ` (`map_completionIdeal_eq_of_stalkIdeal_eq_span`); with
`Eⁱ_p = (y_{c(i)})` and `φ^*(y_{c(i)}) = y_{c(i)}` the completed ideal of a component through `p`
is fixed (the same lemma with `a = b`); and for a component not through `p` the stalk, hence the
completed ideal, is the unit ideal (`completionIdeal_eq_top_of_notMem_support`), fixed by every
ring map. Everything is the behaviour of `Ideal.map` on a principal ideal: `(a).map φ = (φ a)`.
-/

public section

namespace AlgebraicGeometry.Scheme.IdealSheafData

open CategoryTheory IsLocalRing

universe u

variable {X : Scheme.{u}}

/-- The maximal-adic completion of a local ring ([Kol07, Definition 55]). -/
local notation "Ô(" R ")" => AdicCompletion (maximalIdeal R) R

/-- For a component not through `p` the completed ideal is the unit ideal. -/
theorem completionIdeal_eq_top_of_notMem_support (J : X.IdealSheafData) {p : X}
    (hp : p ∉ J.support) : J.completionIdeal p = ⊤ := by
  rw [completionIdeal_eq, stalkIdeal_eq_top_of_notMem_support J hp, Ideal.map_top]

/-- The completion of an ideal sheaf whose stalk is principal is principal, generated by the image
of
the generator. -/
theorem completionIdeal_eq_span_of_stalkIdeal_eq_span {J : X.IdealSheafData} {p : X}
    {a : X.presheaf.stalk p} (h : J.stalkIdeal p = Ideal.span {a}) :
    J.completionIdeal p =
      Ideal.span {algebraMap (X.presheaf.stalk p) Ô(X.presheaf.stalk p) a} := by
  rw [completionIdeal_eq, h, Ideal.map_span, Set.image_singleton]

/-- Kollár's "By construction `φ(Ĥ) = Ĥ'`, `φ(Êⁱ) = Êⁱ`" ([Kol07, 95]): if `J_p = (a)`, `J'_p = (b)`
and a ring map `φ` of the completion sends `ι a` to `ι b`, then `φ(Ĵ) = Ĵ'`. -/
theorem map_completionIdeal_eq_of_stalkIdeal_eq_span {p : X} (J J' : X.IdealSheafData)
    {a b : X.presheaf.stalk p} (hJ : J.stalkIdeal p = Ideal.span {a})
    (hJ' : J'.stalkIdeal p = Ideal.span {b}) {F : Type*}
    [FunLike F Ô(X.presheaf.stalk p) Ô(X.presheaf.stalk p)]
    [RingHomClass F Ô(X.presheaf.stalk p) Ô(X.presheaf.stalk p)] (φ : F)
    (hφ : φ (algebraMap (X.presheaf.stalk p) Ô(X.presheaf.stalk p) a) =
      algebraMap (X.presheaf.stalk p) Ô(X.presheaf.stalk p) b) :
    (J.completionIdeal p).map φ = J'.completionIdeal p := by
  rw [completionIdeal_eq_span_of_stalkIdeal_eq_span hJ,
    completionIdeal_eq_span_of_stalkIdeal_eq_span hJ', Ideal.map_span, Set.image_singleton, hφ]

end AlgebraicGeometry.Scheme.IdealSheafData
