/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.MaximalContact.Basic
public import Hironaka.Algebra.Local.CohenIso
public import Hironaka.Algebra.Local.CompletionCoords
public import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Algebra.Local.DerivativeCompletion
/-!
# Formal equivalence of hypersurfaces of maximal contact at a point

The first half of [Kol07, Definition 91]. Let `X` be a smooth variety, `p ∈ X` a point, `I` an
ideal sheaf with `max-ord I = ord_p I = m`, `E = E¹ + ⋯ + Eˢ` a simple normal crossing divisor and
`H, H' ⊂ X` two hypersurfaces of maximal contact. Write `X̂ := Spec_k Ô_{p,X}` for the completion
of `X` at `p` ([Kol07, Definition 55]) and `Î, Ĥ, Ĥ', Êⁱ` for the completions of the ideal
sheaves. Then `H` and `H'` are **formally equivalent at `p` with respect to `(X, I, E)`** if there
is an automorphism `φ : X̂ → X̂` carrying `(X, I, H + E)` to `(X, I, H' + E)` and close to the
identity: (1) `φ(Ĥ) = Ĥ'`, (2) `φ^*(Î) = Î`, (3) `φ(Êⁱ) = Êⁱ` for `i = 1, …, s`, and
(4) `h − φ^*(h) ∈ \widehat{MC(I)}` for every `h ∈ Ô_{p,X}`.

* **The completed ideal** ([Kol07, Definition 55]): `Ô_{X,p}` is the maximal-adic completion
  `AdicCompletion (maximalIdeal 𝒪_{X,p}) 𝒪_{X,p}` of the stalk, and Kollár's `Ĵ` is the extension
  `J_p Ô_{X,p}` of the stalk `J_p` (`stalkIdeal`) along `𝒪_{X,p} → Ô_{X,p}` (`completionIdeal`);
  it is the completion of the module `J_p` (`range_adicCompletion_map_subtype`), and the extension
  reflects inclusions (`map_adicCompletion_le_iff`; here `completionIdeal_le_iff`, the
  Krull-intersection remark of Definition 55).
* **Formal equivalence** (the conditions (91.1)–(91.4); throughout
  `Hironaka/Resolution/Algebraic/MaximalContact/`, (91.k) abbreviates condition (k) of [Kol07,
  Definition 91] and (91.k′) its étale counterpart (k′), the shorthand Kollár himself uses once, in
  [Kol07, 95]): the automorphism `φ` of `X̂ = Spec_k Ô_{p,X}` is a `k`-algebra automorphism `φ^*` of
  `Ô_{p,X}`, for the `k`-structure `f.stalkAlgebra p` of the stalk extended to the completion. Read
  on functions, (1) is `φ^*(Ĥ') = Ĥ`: the closed subscheme `Ĥ = V(Ĥ)` is carried onto `Ĥ' = V(Ĥ')`
  exactly when the pull-back of the equations of `Ĥ'` generates the ideal of `Ĥ` (with `x₁' ↦ x₁` in
  the proof of Theorem 92: `φ^*(x₁') = x₁`); (2) and (3) are `φ^*(Î) = Î` and `φ^*(Êⁱ) = Êⁱ`; (4) is
  the displayed membership, for the maximal contact ideal `MC f I m` completed at `p`
  (`FormallyEquivalentAt`).
* **`MC` commutes with completion** (Kollár's remark after Definition 91 that
  `\widehat{MC(I)} = MC(Î)` because derivatives commute with completion, [Kol07, Lemma 74 (5)]):
  for coordinates `c` on the stalk that are `k`-linear and span the `k`-derivations, the maximal
  contact ideal of `Î` computed with the completed coordinate derivations `∂̂ᵢ` (Kollár's `D` on
  `Ô_{p,X} ≅ K⟦x₁, …, xₙ⟧` is the ideal generated by the `∂/∂xᵢ`-derivatives,
  [Kol07, Definition 73]) is the completion of the stalk of the sheaf `MC(I)`
  (`adicCompletion_MC_completionIdeal`). Proof: the stalk of `Dʳ(I)` is the coordinate `Dʳ` of the
  stalk (`stalkIdeal_derivativeIter`, `derivativeIter_eq_Dpow`; here the stalk bridge
  `stalkIdeal_MC`), and `Dʳ` passes across the extension of ideals to `R̂`
  (`Dpow_adicCompletion`). So condition (4) may be read with either side.

Kollár's standing hypotheses of Definition 91 (`X` smooth over `k`, `p` a closed point with
`max-ord I = ord_p I = m`, `E` simple normal crossing, `H, H'` hypersurfaces of maximal contact in
the static form with `AlgebraicGeometry.IsSmoothDivisor`) are not clauses of the predicate: as for
`MC` and `IsMaximalContact` they are hypotheses of the theorems that use it (the formal half of
Theorem 92, `Hironaka/Resolution/Algebraic/MaximalContact/FormalEquivExists.lean`; the passage from
étale to formal equivalence, `Hironaka/Resolution/Algebraic/MaximalContact/EtaleToFormal.lean`). The
mark `m` is an explicit parameter.
-/

@[expose] public section

namespace AlgebraicGeometry.Scheme.IdealSheafData

open CategoryTheory IsLocalRing Scheme

universe u

variable {k : Type u} [Field k] {X : Scheme.{u}} (f : X ⟶ Spec (.of k))

/-- The maximal-adic completion of a local ring ([Kol07, Definition 55]). -/
local notation "Ô(" R ")" => AdicCompletion (maximalIdeal R) R

/-! ### The completed ideal `Ĵ ⊆ Ô_{X,p}` -/

/-- **The completion of an ideal sheaf at a point** (the `Î, Ĥ, Êⁱ` of [Kol07, Definition 91],
with the completion of [Kol07, Definition 55]): the extension `J_p Ô_{X,p}` of the stalk `J_p`
along the canonical map `𝒪_{X,p} → Ô_{X,p}` into the maximal-adic completion of the stalk. It is
also the completion of the module `J_p`. -/
noncomputable def completionIdeal (J : X.IdealSheafData) (p : X) : Ideal Ô(X.presheaf.stalk p) :=
  (J.stalkIdeal p).map (algebraMap (X.presheaf.stalk p) Ô(X.presheaf.stalk p))

/-- `completionIdeal` unfolded. -/
theorem completionIdeal_eq (J : X.IdealSheafData) (p : X) :
    J.completionIdeal p =
      (J.stalkIdeal p).map (algebraMap (X.presheaf.stalk p) Ô(X.presheaf.stalk p)) :=
  rfl

/-- Krull's intersection theorem in the form of [Kol07, Definition 55] (equal completions of two
subschemes at a point give equal subschemes near it): on a locally Noetherian scheme the
completed ideals compare exactly as the stalks do. -/
theorem completionIdeal_le_iff [IsLocallyNoetherian X] (J J' : X.IdealSheafData) (p : X) :
    J.completionIdeal p ≤ J'.completionIdeal p ↔ J.stalkIdeal p ≤ J'.stalkIdeal p :=
  map_adicCompletion_le_iff

/-! ### Formal equivalence at a point -/

/-- The conditions (91.1)–(91.4) of [Kol07, Definition 91]: `H` and `H'` are **formally equivalent
at `p` with respect to `(X, I, E)`**, for the mark `m`, if there is a `k`-algebra automorphism
`φ^*` of `Ô_{p,X}` (an automorphism `φ` of `X̂ = Spec_k Ô_{p,X}`) with
(1) `φ(Ĥ) = Ĥ'`, i.e. `φ^*(Ĥ') = Ĥ`; (2) `φ^*(Î) = Î`; (3) `φ^*(Êⁱ) = Êⁱ` for every component
`Eⁱ` of `E`; (4) `h − φ^*(h) ∈ \widehat{MC(I)}` for every `h ∈ Ô_{p,X}` ("`φ` is close to the
identity": it is the identity on the closed subscheme `V(\widehat{MC(I)})`). The `k`-structure of
`Ô_{p,X}` is the one induced by `f` on the stalk (`Scheme.Hom.stalkAlgebra`) and extended to the
completion. Kollár's standing hypotheses (`p` closed, `max-ord I = ord_p I = m`, `E` snc, `H, H'`
of maximal contact) are hypotheses of the theorems that use the predicate. -/
def FormallyEquivalentAt (I : X.IdealSheafData) (m : ℕ) (E : DivisorFamily X)
    (H H' : X.IdealSheafData) (p : X) : Prop :=
  letI := f.stalkAlgebra p
  ∃ φ : Ô(X.presheaf.stalk p) ≃ₐ[k] Ô(X.presheaf.stalk p),
    (H'.completionIdeal p).map φ = H.completionIdeal p ∧
    (I.completionIdeal p).map φ = I.completionIdeal p ∧
    (∀ i, ((E.component i).completionIdeal p).map φ = (E.component i).completionIdeal p) ∧
    ∀ h, h - φ h ∈ (MC f I m).completionIdeal p

/-- The definition unfolded. -/
theorem formallyEquivalentAt_iff (I : X.IdealSheafData) (m : ℕ) (E : DivisorFamily X)
    (H H' : X.IdealSheafData) (p : X) :
    FormallyEquivalentAt f I m E H H' p ↔
      letI := f.stalkAlgebra p
      ∃ φ : Ô(X.presheaf.stalk p) ≃ₐ[k] Ô(X.presheaf.stalk p),
        (H'.completionIdeal p).map φ = H.completionIdeal p ∧
        (I.completionIdeal p).map φ = I.completionIdeal p ∧
        (∀ i, ((E.component i).completionIdeal p).map φ = (E.component i).completionIdeal p) ∧
        ∀ h, h - φ h ∈ (MC f I m).completionIdeal p :=
  Iff.rfl

/-! ### `MC` commutes with completion ([Kol07, Lemma 74 (5)] iterated) -/

section Smooth

variable [CharZero k] (n : ℕ) [SmoothOfRelativeDimension n f]

include n in
/-- The stalk bridge for the maximal contact ideal: the sheaf `MC f I m` and `RegularCoords.MC`
are the same [Kol07, Definition 79] read at a stalk. For coordinates `c` on `𝒪_{X,p}` that are
`k`-linear and span the `k`-derivations, `(MC f I m)_p = MC_c((I_p), m)`, through
`stalkIdeal_derivativeIter` and `derivativeIter_eq_Dpow`. -/
theorem stalkIdeal_MC (I : X.IdealSheafData) (m : ℕ) (p : X) {n' : ℕ}
    (c : letI := f.stalkAlgebraRat p
      haveI := @isRegularLocalRing_stalk k _ X f
        (SmoothOfRelativeDimension.smooth n f) p
      RegularCoords (X.presheaf.stalk p) n')
    (hk : letI := f.stalkAlgebra p; letI := f.stalkAlgebraRat p
      haveI := @isRegularLocalRing_stalk k _ X f
        (SmoothOfRelativeDimension.smooth n f) p
      c.IsLinearOver k)
    (hs : letI := f.stalkAlgebra p; letI := f.stalkAlgebraRat p
      haveI := @isRegularLocalRing_stalk k _ X f
        (SmoothOfRelativeDimension.smooth n f) p
      c.SpansDerivations k) :
    (MC f I m).stalkIdeal p =
      letI := f.stalkAlgebraRat p
      haveI := @isRegularLocalRing_stalk k _ X f
        (SmoothOfRelativeDimension.smooth n f) p
      c.MC (I.stalkIdeal p) m := by
  have hsm : Smooth f := SmoothOfRelativeDimension.smooth n f
  let _ := f.stalkAlgebra p
  let _ := f.stalkAlgebraRat p
  have := isRegularLocalRing_stalk f p
  rw [MC_eq, stalkIdeal_derivativeIter f (m - 1) I p, Ideal.derivativeIter_eq_Dpow c hk hs (m - 1)]
  rfl

include n in
/-- Kollár's remark after [Kol07, Definition 91] that `\widehat{MC(I)} = MC(Î)`, since derivatives
commute with completion ([Kol07, Lemma 74 (5)] iterated): for coordinates `c` on the stalk
`𝒪_{X,p}` that are `k`-linear and span the `k`-derivations, the maximal contact ideal of `Î`
computed with the completed coordinate derivations `∂̂ᵢ` (Kollár's `D` on `Ô_{p,X} ≅ K⟦x⟧`,
[Kol07, Definition 73]) is the completion of the stalk of `MC(I)`. Condition (91.4) may therefore
be read with either side. -/
theorem adicCompletion_MC_completionIdeal (I : X.IdealSheafData) (m : ℕ) (p : X) {n' : ℕ}
    (c : letI := f.stalkAlgebraRat p
      haveI := @isRegularLocalRing_stalk k _ X f
        (SmoothOfRelativeDimension.smooth n f) p
      RegularCoords (X.presheaf.stalk p) n')
    (hk : letI := f.stalkAlgebra p; letI := f.stalkAlgebraRat p
      haveI := @isRegularLocalRing_stalk k _ X f
        (SmoothOfRelativeDimension.smooth n f) p
      c.IsLinearOver k)
    (hs : letI := f.stalkAlgebra p; letI := f.stalkAlgebraRat p
      haveI := @isRegularLocalRing_stalk k _ X f
        (SmoothOfRelativeDimension.smooth n f) p
      c.SpansDerivations k) :
    letI := f.stalkAlgebraRat p
    haveI := @isRegularLocalRing_stalk k _ X f
      (SmoothOfRelativeDimension.smooth n f) p
    c.adicCompletion.MC (I.completionIdeal p) m = (MC f I m).completionIdeal p := by
  have hsm : Smooth f := SmoothOfRelativeDimension.smooth n f
  let _ := f.stalkAlgebra p
  let _ := f.stalkAlgebraRat p
  have := isRegularLocalRing_stalk f p
  rw [completionIdeal_eq, completionIdeal_eq, c.MC_adicCompletion, stalkIdeal_MC f n I m p c hk hs]

end Smooth

end AlgebraicGeometry.Scheme.IdealSheafData
