/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.StructureSheaf
public import Mathlib.Topology.Germ
import Hironaka.Manifold.Germ.ChartTransport
import Hironaka.Manifold.Sheaf.LocalRing
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# The stalk map of an analytic map on germs of sections

The stalk map `germMapOn φ hφ hb hc : 𝒪_{M,c} →+* 𝒪_{N,b}` of an analytic map `φ` (with
`φ b = c`), `s ↦ s ∘ φ`, is characterized by composition of function germs through the embedding
`stalkToGerm` (`stalkToGerm_germMapOn`, `stalkToGerm_germMap` for a global analytic map
`germMap`). This module reads it on sections:

* a function `C^ω` on an open set `W` is a section of `𝒪_N` over `W` (`sectionOfContMDiffOn`), and
  the stalk map sends the germ of a section `f` to the germ of the section `f ∘ φ`
  (`germMapOn_germ`); for a global analytic map, `f ∘ φ` is the section `comapSection φ hφ f` over
  the preimage `preimageOpens φ hφ U` (`germMap_germ`);
* the stalk map is local, `ev_b (s ∘ φ) = ev_{φ b} s` (`eval_germMapOn`, through
  `eval_eq_value`), hence a local homomorphism (`isLocalHom_germMapOn`, `isLocalHom_germMap`);
* the stalk map of the identity is the identity (`germMap_id`).

These are the facts behind the pullback of ideal sheaves (`IdealSheaf.pullback`, whose stalks are
generated by the germs of the `f ∘ φ`).
-/

@[expose] public section

open TopologicalSpace Opposite CategoryTheory Filter
open scoped Manifold ContDiff Topology

universe u v

noncomputable section

namespace Manifold

variable {𝕜 : Type} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  {E' : Type*} [NormedAddCommGroup E'] [NormedSpace 𝕜 E']
  {N : Type v} [TopologicalSpace N] [ChartedSpace E' N]

/-- A `C^ω` function on an open set `W`, as a section of `𝒪_N` over `W`. -/
def sectionOfContMDiffOn (h : N → 𝕜) (W : Opens N) (hW : ContMDiffOn 𝓘(𝕜, E') 𝓘(𝕜) ω h W) :
    (structureSheaf 𝕜 E' N).presheaf.obj (op W) :=
  ⟨h ∘ Subtype.val, fun x =>
    ((contDiffWithinAt_localInvariantProp (I := 𝓘(𝕜, E')) (I' := 𝓘(𝕜))
      ω).liftPropAt_iff_comp_subtype_val (U := W) h x).mp (hW.contMDiffAt (W.2.mem_nhds x.2))⟩

theorem sectionOfContMDiffOn_apply (h : N → 𝕜) (W : Opens N)
    (hW : ContMDiffOn 𝓘(𝕜, E') 𝓘(𝕜) ω h W) (x : W) :
    sectionOfContMDiffOn h W hW x = h x := rfl

theorem stalkToGerm_germ_sectionOfContMDiffOn (h : N → 𝕜) (W : Opens N)
    (hW : ContMDiffOn 𝓘(𝕜, E') 𝓘(𝕜) ω h W) {b : N} (hb : b ∈ W) :
    stalkToGerm 𝓘(𝕜, E') ω N b
      ((structureSheaf 𝕜 E' N).presheaf.germ W b hb (sectionOfContMDiffOn h W hW)) = ↑h := by
  rw [stalkToGerm_structureSheaf_germ]
  refine Germ.coe_eq.mpr ?_
  filter_upwards [W.2.mem_nhds hb] with x hx
  exact extendSection_of_mem 𝕜 E' _ hx

/-- The evaluation at `a` is the value of the germ. -/
theorem eval_eq_value (a : M) (s : (structureSheaf 𝕜 E M).presheaf.stalk a) :
    eval 𝕜 E M a s = (stalkToGerm 𝓘(𝕜, E) ω M a s).value := by
  obtain ⟨U, ha, f, rfl⟩ := (structureSheaf 𝕜 E M).presheaf.exists_germ_eq s
  rw [stalkToGerm_structureSheaf_germ, Germ.value_ofFun, extendSection_of_mem 𝕜 E f ha]
  exact contMDiffSheafCommRing.eval_germ 𝓘(𝕜, E) 𝓘(𝕜) ω M 𝕜 U a ha f

section GermMap

variable (φ : N → M) {V : Opens N} (hφ : ContMDiffOn 𝓘(𝕜, E') 𝓘(𝕜, E) ω φ V) {b : N} (hb : b ∈ V)
  {c : M} (hc : φ b = c)

theorem stalkToGerm_stalkEquivRange_symm (b : N) (g : (stalkToGerm 𝓘(𝕜, E') ω N b).range) :
    stalkToGerm 𝓘(𝕜, E') ω N b ((stalkEquivRange b).symm g) = g :=
  congrArg Subtype.val ((stalkEquivRange b).apply_symm_apply g)

/-- The stalk map is characterized by composition of germs. -/
theorem stalkToGerm_germMapOn (s : (structureSheaf 𝕜 E M).presheaf.stalk c) :
    stalkToGerm 𝓘(𝕜, E') ω N b (germMapOn φ hφ hb hc s) =
      (stalkToGerm 𝓘(𝕜, E) ω M c s).compTendsto φ (tendsto_of_contMDiffOn_of_eq φ hφ hb hc) :=
  stalkToGerm_stalkEquivRange_symm b _

/-- The stalk map sends the germ of a section `f` to the germ of `f ∘ φ`. -/
theorem germMapOn_germ {U : Opens M} (hcU : c ∈ U) (f : (structureSheaf 𝕜 E M).presheaf.obj (op U))
    {W : Opens N} (hbW : b ∈ W) (hW : ContMDiffOn 𝓘(𝕜, E') 𝓘(𝕜) ω (extendSection 𝕜 E f ∘ φ) W) :
    germMapOn φ hφ hb hc ((structureSheaf 𝕜 E M).presheaf.germ U c hcU f) =
      (structureSheaf 𝕜 E' N).presheaf.germ W b hbW (sectionOfContMDiffOn _ W hW) := by
  apply stalkToGerm_injective 𝓘(𝕜, E') ω N b
  rw [stalkToGerm_germMapOn, stalkToGerm_structureSheaf_germ, Germ.coe_compTendsto,
    stalkToGerm_germ_sectionOfContMDiffOn]

/-- The stalk map is local: `ev_b (s ∘ φ) = ev_{φ b} s`. -/
theorem eval_germMapOn (s : (structureSheaf 𝕜 E M).presheaf.stalk c) :
    eval 𝕜 E' N b (germMapOn φ hφ hb hc s) = eval 𝕜 E M c s := by
  rw [eval_eq_value, eval_eq_value, stalkToGerm_germMapOn]
  induction stalkToGerm 𝓘(𝕜, E) ω M c s using Germ.inductionOn with
  | h g => rw [Germ.coe_compTendsto, Germ.value_ofFun, Germ.value_ofFun, Function.comp_apply, hc]

instance isLocalHom_germMapOn : IsLocalHom (germMapOn φ hφ hb hc) where
  map_nonunit s hs := by
    rw [contMDiffSheafCommRing.isUnit_stalk_iff] at hs ⊢
    exact fun h0 => hs ((eval_germMapOn φ hφ hb hc s).trans h0)

end GermMap

section GlobalMap

variable (φ : N → M) (hφ : ContMDiff 𝓘(𝕜, E') 𝓘(𝕜, E) ω φ)

theorem stalkToGerm_germMap (b : N)
    (s : (structureSheaf 𝕜 E M).presheaf.stalk (φ b)) :
    stalkToGerm 𝓘(𝕜, E') ω N b (germMap φ hφ b s) =
      (stalkToGerm 𝓘(𝕜, E) ω M (φ b) s).compTendsto φ
        (hφ.continuous.tendsto b) :=
  stalkToGerm_germMapOn φ (V := ⊤) hφ.contMDiffOn (Opens.mem_top b) rfl s

instance isLocalHom_germMap (b : N) : IsLocalHom (germMap φ hφ b) :=
  isLocalHom_germMapOn φ (V := ⊤) hφ.contMDiffOn (Opens.mem_top b) rfl

/-- The preimage of an open set under `φ`. -/
def preimageOpens (U : Opens M) : Opens N := ⟨φ ⁻¹' U, U.2.preimage hφ.continuous⟩

theorem mem_preimageOpens {U : Opens M} {x : N} : x ∈ preimageOpens φ hφ U ↔ φ x ∈ U := Iff.rfl

omit hφ in
/-- The extension by zero of a section is `C^ω` on its domain. -/
theorem contMDiffOn_extendSection {U : Opens M} (f : (structureSheaf 𝕜 E M).presheaf.obj (op U)) :
    ContMDiffOn 𝓘(𝕜, E) 𝓘(𝕜) ω (extendSection 𝕜 E f) U := by
  intro x hx
  refine ContMDiffAt.contMDiffWithinAt ?_
  have hf : ContMDiffAt 𝓘(𝕜, E) 𝓘(𝕜) ω (extendSection 𝕜 E f ∘ Subtype.val) (⟨x, hx⟩ : U) := by
    rw [extendSection, extendBy0_comp_val]
    exact f.2 ⟨x, hx⟩
  exact ((contDiffWithinAt_localInvariantProp (I := 𝓘(𝕜, E)) (I' := 𝓘(𝕜))
    ω).liftPropAt_iff_comp_subtype_val (U := U) (extendSection 𝕜 E f) ⟨x, hx⟩).mpr hf

/-- `f ∘ φ` as a section of `𝒪_N` over `φ⁻¹ U`. -/
def comapSection {U : Opens M} (f : (structureSheaf 𝕜 E M).presheaf.obj (op U)) :
    (structureSheaf 𝕜 E' N).presheaf.obj (op (preimageOpens φ hφ U)) :=
  sectionOfContMDiffOn (extendSection 𝕜 E f ∘ φ) _
    ((contMDiffOn_extendSection f).comp hφ.contMDiffOn (Set.mapsTo_preimage φ U))

theorem comapSection_apply {U : Opens M} (f : (structureSheaf 𝕜 E M).presheaf.obj (op U))
    (x : preimageOpens φ hφ U) : comapSection φ hφ f x = f ⟨φ x, x.2⟩ :=
  extendSection_of_mem 𝕜 E f x.2

/-- The stalk map sends the germ of `f` to the germ of `f ∘ φ`. -/
theorem germMap_germ {U : Opens M} {b : N} (hU : φ b ∈ U)
    (f : (structureSheaf 𝕜 E M).presheaf.obj (op U)) :
    germMap φ hφ b ((structureSheaf 𝕜 E M).presheaf.germ U (φ b) hU f) =
      (structureSheaf 𝕜 E' N).presheaf.germ (preimageOpens φ hφ U) b
        ((mem_preimageOpens φ hφ).mpr hU) (comapSection φ hφ f) :=
  germMapOn_germ φ (V := ⊤) hφ.contMDiffOn (Opens.mem_top b) rfl hU f
    ((mem_preimageOpens φ hφ).mpr hU) _

/-- The germ map of the identity is the identity of the stalk. -/
theorem germMap_id (x : M) (s : (structureSheaf 𝕜 E M).presheaf.stalk x) :
    germMap (𝕜 := 𝕜) (E' := E) (id : M → M) contMDiff_id x s = s := by
  refine stalkToGerm_injective 𝓘(𝕜, E) ω M x ?_
  rw [stalkToGerm_germMap]
  change (stalkToGerm 𝓘(𝕜, E) ω M x s).compTendsto id (continuous_id.tendsto x) =
    stalkToGerm 𝓘(𝕜, E) ω M x s
  induction stalkToGerm 𝓘(𝕜, E) ω M x s using Germ.inductionOn with
  | h f => rw [Germ.coe_compTendsto]; rfl

end GlobalMap

end Manifold

end
