/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Germ.TaylorHom
public import Mathlib.RingTheory.RegularLocalRing.Defs
import Hironaka.Algebra.Local.CohenIso
import Hironaka.Algebra.Local.PowerSeriesRegular
import Hironaka.Analytic.Rueckert.Noetherian
import Hironaka.Manifold.Germ.CoordDerivCoords
import Hironaka.Manifold.Germ.TaylorCompletion
import Hironaka.Manifold.Germ.TaylorIdeal
import Hironaka.Manifold.IdealSheaf.Order
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init

/-!
# The analytic stalk is a Noetherian regular local ring of dimension `n`

Bierstone–Milman require of their category of spaces that "`𝒪_X` is a coherent sheaf of rings and
`X` is locally Noetherian" [BM97, (3.8)(3)] and call `X` smooth "if, for all `x ∈ |X|`, `𝒪_{X,x}`
is a regular local ring" [BM97, §3]; Hironaka calls a point simple if its local ring is regular,
the simple points being, by the Jacobian criterion and the implicit function theorem, those with
a neighbourhood isomorphic to an open subset of `K^n` [Hir64, p. 121]. For the stalk `𝒪_{M,a}` of
the structure sheaf of an analytic manifold:

* **Noetherian** (Rückert's basis theorem): the Taylor homomorphism `T_a` of a chart is injective
  with range the convergent power series (`Hironaka/Manifold/Germ/TaylorIdeal.lean`), so
  `𝒪_{M,a} ≃+* Conv 𝕜 n` (`taylorEquivConv`), and `Conv 𝕜 n` is Noetherian
  (`Hironaka/Analytic/Rueckert/Noetherian.lean`);
* **dimension `n`**: `𝒪̂_{M,a} ≅ 𝕜[[X_1, …, X_n]]`
  (`Hironaka/Manifold/Germ/TaylorCompletion.lean`), the completion of a Noetherian local ring
  has the same Krull dimension (`IsLocalRing.ringKrullDim_adicCompletion_eq`; `𝒪̂` is
  Noetherian by `IsLocalRing.isNoetherianRing_adicCompletion`), and `dim 𝕜[[X_1, …, X_n]] = n`
  (`IsLocalRing.ringKrullDim_mvPowerSeries`);
* **regular**: `𝔪_a` is generated by the `n` centred coordinates, so
  `spanFinrank 𝔪_a ≤ n = ringKrullDim 𝒪_{M,a}`, which is Mathlib's criterion
  `IsRegularLocalRing.of_spanFinrank_maximalIdeal_le`; the embedding dimension is then `n`
  (`spanFinrank_maximalIdeal_stalk`).

The chart-parametrised statements take a chart `(φ, ψ)` at `a`; the instances take
`[IsManifold 𝓘(𝕜, E) ω M]` and `[FiniteDimensional 𝕜 E]` and use the chart at `a` with the
coordinates `modelCoord` of the finite-dimensional model space (`n = finrank 𝕜 E`). The Noetherian
instance is used throughout the `Hironaka` library wherever an ideal of a stalk has to be
finitely generated, and the regularity and dimension wherever a centre or a hypersurface is compared
with the ambient stalk.
-/

@[expose] public section

noncomputable section

open TopologicalSpace Opposite CategoryTheory IsLocalRing Analytic
open scoped Manifold ContDiff Topology
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] (E : Type*) [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {n : ℕ} (ψ : E ≃L[𝕜] (Fin n → 𝕜))
  (φ : OpenPartialHomeomorph M E) {a : M} (ha : a ∈ φ.source) (hφ : φ ∈ maximalAtlas 𝓘(𝕜, E) ω M)

/-- The Taylor homomorphism of a chart as a ring isomorphism `𝒪_{M,a} ≃+* Conv 𝕜 n` onto the
convergent power series: injective (`IsTaylorHom.injective'`) with range `Conv 𝕜 n`
(`range_taylorHom`). -/
def taylorEquivConv : (structureSheaf 𝕜 E M).presheaf.stalk a ≃+* Analytic.Conv 𝕜 n :=
  RingEquiv.ofBijective ((taylorHom E ψ φ ha hφ).codRestrict (Analytic.Conv 𝕜 n)
    (taylorHom_mem_conv E ψ φ ha hφ))
    ⟨fun s t hst => IsTaylorHom.injective' E ψ φ ha (isTaylorHom_taylorHom E ψ φ ha hφ)
        (congrArg Subtype.val hst),
      fun c => by
        obtain ⟨s, hs⟩ := (range_taylorHom E ψ φ ha hφ).ge c.2
        exact ⟨s, Subtype.ext hs⟩⟩

theorem taylorEquivConv_apply_coe (s : (structureSheaf 𝕜 E M).presheaf.stalk a) :
    (taylorEquivConv E ψ φ ha hφ s : MvPowerSeries (Fin n) 𝕜) = taylorHom E ψ φ ha hφ s := rfl

include ψ φ ha hφ in
/-- Rückert's basis theorem for the stalk [BM97, (3.8)(3)]: `𝒪_{M,a}` is Noetherian, being
isomorphic to the ring `Conv 𝕜 n` of convergent power series. -/
theorem isNoetherianRing_stalk_of_chart :
    IsNoetherianRing ((structureSheaf 𝕜 E M).presheaf.stalk a) :=
  isNoetherianRing_of_ringEquiv (Analytic.Conv 𝕜 n) (taylorEquivConv E ψ φ ha hφ).symm

include ψ φ ha hφ in
/-- `ringKrullDim 𝒪_{M,a} = n`: the completion `𝒪̂_{M,a} ≅ 𝕜[[X_1, …, X_n]]` has the same dimension
as `𝒪_{M,a}`, and `dim 𝕜[[X]] = n`. -/
theorem ringKrullDim_stalk_of_chart :
    ringKrullDim ((structureSheaf 𝕜 E M).presheaf.stalk a) = n := by
  have h1 := isNoetherianRing_stalk_of_chart E ψ φ ha hφ
  have h2 : IsNoetherianRing (AdicCompletion
      (maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk a))
      ((structureSheaf 𝕜 E M).presheaf.stalk a)) :=
    isNoetherianRing_adicCompletion ((structureSheaf 𝕜 E M).presheaf.stalk a)
      (centredCoord E ψ φ hφ ha) (maximalIdeal_eq_span_coord' E ψ φ ha hφ)
  have h3 := ringKrullDim_adicCompletion_eq ((structureSheaf 𝕜 E M).presheaf.stalk a)
  have h4 := ringKrullDim_eq_of_ringEquiv (taylorCompletionEquiv E ψ φ ha hφ)
  rw [← h3, h4, ringKrullDim_mvPowerSeries]

include ψ φ ha hφ in
/-- The maximal ideal of the stalk is generated by the `n` centred coordinates, so its minimal
number of generators is at most `n`. -/
theorem spanFinrank_maximalIdeal_stalk_le :
    (maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk a)).spanFinrank ≤ n := by
  rw [maximalIdeal_eq_span_coord' E ψ φ ha hφ]
  refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)).trans ?_
  calc (Set.range fun i => coord E ψ φ hφ ha i -
          const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ hφ ha i))).ncard
      = ((fun i => coord E ψ φ hφ ha i - const 𝕜 E M a (eval 𝕜 E M a (coord E ψ φ hφ ha i))) ''
          Set.univ).ncard := by rw [Set.image_univ]
    _ ≤ (Set.univ : Set (Fin n)).ncard := Set.ncard_image_le Set.finite_univ
    _ = n := by rw [Set.ncard_univ, Nat.card_eq_fintype_card, Fintype.card_fin]

include ψ φ ha hφ in
/-- The stalk `𝒪_{M,a}` is a regular local ring ("smooth if … `𝒪_{X,x}` is a regular local ring"
[BM97, §3]; Hironaka's simple points [Hir64, p. 121]): `𝔪_a` has `n` generators and
`ringKrullDim 𝒪_{M,a} = n` (Mathlib's `IsRegularLocalRing.of_spanFinrank_maximalIdeal_le`). -/
theorem isRegularLocalRing_stalk_of_chart :
    IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk a) := by
  have h1 := isNoetherianRing_stalk_of_chart E ψ φ ha hφ
  refine IsRegularLocalRing.of_spanFinrank_maximalIdeal_le _ ?_
  rw [ringKrullDim_stalk_of_chart E ψ φ ha hφ]
  exact_mod_cast spanFinrank_maximalIdeal_stalk_le E ψ φ ha hφ

include ψ φ ha hφ in
/-- The embedding dimension `dim_𝕜 𝔪_a/𝔪_a²` (the minimal number of generators of `𝔪_a`) is `n`. -/
theorem spanFinrank_maximalIdeal_stalk_of_chart :
    (maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk a)).spanFinrank = n := by
  have h1 := isRegularLocalRing_stalk_of_chart E ψ φ ha hφ
  have h := IsRegularLocalRing.spanFinrank_maximalIdeal
    (R := (structureSheaf 𝕜 E M).presheaf.stalk a)
  rw [ringKrullDim_stalk_of_chart E ψ φ ha hφ] at h
  exact_mod_cast h

section Instances

variable [IsManifold 𝓘(𝕜, E) ω M] [FiniteDimensional 𝕜 E]

omit ψ φ ha hφ in
/-- **The analytic stalks are Noetherian** [BM97, (3.8)(3)]. -/
instance isNoetherianRing_stalk (a : M) :
    IsNoetherianRing ((structureSheaf 𝕜 E M).presheaf.stalk a) :=
  isNoetherianRing_stalk_of_chart E (IdealSheaf.modelCoord (𝕜 := 𝕜) (E := E)) (chartAt E a)
    (mem_chart_source E a) (IsManifold.chart_mem_maximalAtlas a)

omit ψ φ ha hφ in
/-- `ringKrullDim 𝒪_{M,a} = n`, the dimension of the manifold. -/
theorem ringKrullDim_stalk (a : M) :
    ringKrullDim ((structureSheaf 𝕜 E M).presheaf.stalk a) = Module.finrank 𝕜 E :=
  ringKrullDim_stalk_of_chart E (IdealSheaf.modelCoord (𝕜 := 𝕜) (E := E)) (chartAt E a)
    (mem_chart_source E a) (IsManifold.chart_mem_maximalAtlas a)

omit ψ φ ha hφ in
/-- **The analytic stalks are regular local rings** ([BM97, §3]; [Hir64, p. 121]). -/
instance isRegularLocalRing_stalk (a : M) :
    IsRegularLocalRing ((structureSheaf 𝕜 E M).presheaf.stalk a) :=
  isRegularLocalRing_stalk_of_chart E (IdealSheaf.modelCoord (𝕜 := 𝕜) (E := E)) (chartAt E a)
    (mem_chart_source E a) (IsManifold.chart_mem_maximalAtlas a)

omit ψ φ ha hφ in
/-- The embedding dimension of the stalk is `n`. -/
theorem spanFinrank_maximalIdeal_stalk (a : M) :
    (maximalIdeal ((structureSheaf 𝕜 E M).presheaf.stalk a)).spanFinrank = Module.finrank 𝕜 E :=
  spanFinrank_maximalIdeal_stalk_of_chart E (IdealSheaf.modelCoord (𝕜 := 𝕜) (E := E)) (chartAt E a)
    (mem_chart_source E a) (IsManifold.chart_mem_maximalAtlas a)

end Instances

end Manifold

end
