/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Analytic.Rueckert.PermConv
public import Hironaka.Analytic.Rueckert.Basic
public import Mathlib.Analysis.Complex.Basic
import Hironaka.Analytic.Rueckert.MonicDivision
import Hironaka.Analytic.Rueckert.ParametrizationPrimitive
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Tactic.Positivity.Finset

/-!
# Iterated Weierstrass division by monic relations of the fibre coordinates

The division argument of [Fre17, Ch. I, 8.3], done simultaneously in all fibre coordinates (see
also [GR84, Chapter 3]): let `e : Fin d ↪ Fin m` embed the base coordinates and let every fibre
coordinate `x_i` (`i ∉ range e`) satisfy a monic relation `Qf_i(x_i)`, `Qf_i ∈ 𝒪_d[T]`. Then
every `F ∈ 𝒪_m` is, modulo the ideal generated by the relations, a polynomial in the fibre
coordinates over the base: `F ≡ ∑_μ a_μ(x_base) x_fibre^μ` with `μ_i < deg Qf_i`. The textbooks
divide one variable at a time; here the induction is on the number `m` of variables: a fibre
coordinate is moved to the first position by the permutation `permConv (swap 0 i)`
(`PermConv.lean`), the monic relation in `x_0` is `x_0`-regular of some order `≤ deg Qf_i`
(`exists_isRegularIn_convPolyEval_of_monic`), Weierstrass division
(`exists_eq_mul_add_sum_convTail_mul_convX_pow`, `MonicDivision.lean`) yields a polynomial
remainder in `x_0` whose coefficients live in the tail ring `𝒪_{m-1}`, and the induction
hypothesis reduces those coefficients modulo the remaining relations (now relations in
`𝒪_{m-1}`). The base of the induction is the case of no fibre coordinate (`e` onto), where `F`
itself is a base series.

`fibreBox e Qf` is the additive monoid of such polynomials (exponents `0` on the base indices,
`< deg Qf_i` on the fibre indices); `fibreRelIdeal e Qf` is the ideal of the relations. This is
the finiteness step of the parametrization of a prime germ (`ParametrizationDivision.lean`).
-/

@[expose] public section

open MvPowerSeries Polynomial

namespace Analytic

variable {m d : ℕ}

/-- The tail embedding of a coordinate series is the next coordinate series (`liftTail` is the
renaming along `Fin.succ`). -/
theorem convTail_convX (j : Fin m) : convTail ℂ (convX ℂ j) = convX ℂ j.succ := by
  apply Subtype.ext
  rw [coe_convTail, coe_convX, coe_convX]
  exact MvPowerSeries.rename_X _ _

open Classical in
/-- The additive monoid of polynomials in the fibre coordinates over the base: sums of
`a(x_base) · ∏ x_i^{μ_i}` with `μ_i = 0` on the base indices and `μ_i < deg Qf_i` on the fibre
indices. -/
noncomputable def fibreBox (e : Fin d ↪ Fin m) (Qf : Fin m → Polynomial (Conv ℂ d)) :
    AddSubmonoid (Conv ℂ m) :=
  AddSubmonoid.closure {g | ∃ (a : Conv ℂ d) (μ : Fin m → ℕ), (∀ i, i ∈ Set.range e → μ i = 0) ∧
    (∀ i, i ∉ Set.range e → μ i < (Qf i).natDegree) ∧ g = convEmbed ℂ e a * ∏ i, convX ℂ i ^ μ i}

/-- The ideal generated by the monic relations `Qf_i(x_i)` of the fibre coordinates. -/
noncomputable def fibreRelIdeal (e : Fin d ↪ Fin m) (Qf : Fin m → Polynomial (Conv ℂ d)) :
    Ideal (Conv ℂ m) :=
  Ideal.span (Set.range fun i : {i : Fin m // i ∉ Set.range e} =>
    ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i))

theorem mem_fibreBox_of {e : Fin d ↪ Fin m} {Qf : Fin m → Polynomial (Conv ℂ d)} (a : Conv ℂ d)
    (μ : Fin m → ℕ) (h0 : ∀ i, i ∈ Set.range e → μ i = 0)
    (hlt : ∀ i, i ∉ Set.range e → μ i < (Qf i).natDegree) :
    convEmbed ℂ e a * ∏ i, convX ℂ i ^ μ i ∈ fibreBox e Qf :=
  AddSubmonoid.subset_closure ⟨a, μ, h0, hlt, rfl⟩

theorem rel_mem_fibreRelIdeal {e : Fin d ↪ Fin m} {Qf : Fin m → Polynomial (Conv ℂ d)} {i : Fin m}
    (hi : i ∉ Set.range e) :
    ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i) ∈ fibreRelIdeal e Qf :=
  Ideal.subset_span ⟨⟨i, hi⟩, rfl⟩

/-- No fibre coordinate (`e` onto): every series is a base series, the box itself. -/
theorem exists_mem_fibreBox_sub_mem_of_surjective {e : Fin d ↪ Fin m}
    (Qf : Fin m → Polynomial (Conv ℂ d)) (hsurj : Function.Surjective e) (F : Conv ℂ m) :
    ∃ G ∈ fibreBox e Qf, F - G ∈ fibreRelIdeal e Qf := by
  obtain ⟨a, ha⟩ := convEmbed_surjective_of_surjective e hsurj F
  refine ⟨F, ?_, by rw [sub_self]; exact Ideal.zero_mem _⟩
  have : F = convEmbed ℂ e a * ∏ i : Fin m, convX ℂ i ^ (0 : ℕ) := by
    rw [ha]
    simp
  rw [this]
  exact mem_fibreBox_of a (fun _ => 0) (fun _ _ => rfl)
    (fun i hi => (hsurj i).elim fun k hk => (hi ⟨k, hk⟩).elim)

section Step

/-- After the swap `0 ↔ i`, a base index is never `0`. -/
theorem swap_apply_ne_zero_of_mem_range (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)}
    (hi : i ∉ Set.range e) {x : Fin (m + 1)} (hx : x ∈ Set.range e) :
    Equiv.swap (0 : Fin (m + 1)) i x ≠ 0 := by
  intro h
  have : x = i := by
    have h' := congrArg (Equiv.swap (0 : Fin (m + 1)) i) h
    rwa [Equiv.swap_apply_self, Equiv.swap_apply_left] at h'
  exact hi (this ▸ hx)

/-- The base embedding after removing the fibre coordinate `i` (moved to position `0` by the
swap): `k ↦ pred (swap 0 i (e k))`. -/
noncomputable def predEmb (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)} (hi : i ∉ Set.range e) :
    Fin d ↪ Fin m where
  toFun k := (Equiv.swap (0 : Fin (m + 1)) i (e k)).pred
    (swap_apply_ne_zero_of_mem_range e hi ⟨k, rfl⟩)
  inj' k k' h := by
    have h' := congrArg Fin.succ h
    rw [Fin.succ_pred, Fin.succ_pred] at h'
    exact e.injective ((Equiv.swap _ _).injective h')

theorem predEmb_succ (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)} (hi : i ∉ Set.range e)
    (k : Fin d) : ((predEmb e hi) k).succ = Equiv.swap (0 : Fin (m + 1)) i (e k) :=
  Fin.succ_pred _ (swap_apply_ne_zero_of_mem_range e hi ⟨k, rfl⟩)

theorem predEmb_trans_succ (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)} (hi : i ∉ Set.range e) :
    (predEmb e hi).trans ⟨Fin.succ, Fin.succ_injective m⟩ =
      e.trans (Equiv.swap 0 i).toEmbedding :=
  Function.Embedding.ext fun k => predEmb_succ e hi k

theorem notMem_range_predEmb_iff (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)}
    (hi : i ∉ Set.range e) (j : Fin m) :
    j ∉ Set.range (predEmb e hi) ↔ Equiv.swap (0 : Fin (m + 1)) i j.succ ∉ Set.range e := by
  constructor
  · rintro hj ⟨k, hk⟩
    apply hj
    refine ⟨k, ?_⟩
    apply Fin.succ_injective
    rw [predEmb_succ, hk, Equiv.swap_apply_self]
  · rintro hj ⟨k, hk⟩
    apply hj
    refine ⟨k, ?_⟩
    rw [← hk, predEmb_succ e hi k, Equiv.swap_apply_self]

/-- The transport `𝒪_m → 𝒪_{m+1}`, tail embedding followed by the inverse swap: it puts the
remaining variables back in their places. -/
noncomputable def tailSwap (i : Fin (m + 1)) : Conv ℂ m →ₐ[ℂ] Conv ℂ (m + 1) :=
  ((permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i)).symm :
    Conv ℂ (m + 1) ≃ₐ[ℂ] Conv ℂ (m + 1)).toAlgHom.comp (convTail ℂ)

theorem tailSwap_apply (i : Fin (m + 1)) (x : Conv ℂ m) :
    tailSwap i x = (permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i)).symm (convTail ℂ x) := rfl

theorem tailSwap_convX (i : Fin (m + 1)) (j : Fin m) :
    tailSwap i (convX ℂ j) = convX ℂ (Equiv.swap (0 : Fin (m + 1)) i j.succ) := by
  rw [tailSwap_apply, convTail_convX, permConv_symm, permConv_convX, Equiv.symm_swap]

theorem tailSwap_convEmbed (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)} (hi : i ∉ Set.range e)
    (a : Conv ℂ d) :
    tailSwap i (convEmbed ℂ (predEmb e hi) a) = convEmbed ℂ e a := by
  rw [tailSwap_apply, convTail_convEmbed, predEmb_trans_succ, permConv_symm, Equiv.symm_swap,
    permConv_convEmbed]
  have : (e.trans (Equiv.swap (0 : Fin (m + 1)) i).toEmbedding).trans
      (Equiv.swap (0 : Fin (m + 1)) i).toEmbedding = e :=
    Function.Embedding.ext fun k => by simp [Equiv.swap_apply_self]
  rw [this]

theorem tailSwap_rel (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)} (hi : i ∉ Set.range e)
    (Qf : Fin (m + 1) → Polynomial (Conv ℂ d)) (j : Fin m) :
    tailSwap i (((Qf (Equiv.swap (0 : Fin (m + 1)) i j.succ)).map
      (convEmbed ℂ (predEmb e hi)).toRingHom).eval (convX ℂ j)) =
    ((Qf (Equiv.swap (0 : Fin (m + 1)) i j.succ)).map (convEmbed ℂ e).toRingHom).eval
      (convX ℂ (Equiv.swap (0 : Fin (m + 1)) i j.succ)) := by
  rw [eval_map, eval_map]
  have h : tailSwap i (eval₂ (convEmbed ℂ (predEmb e hi)).toRingHom (convX ℂ j)
      (Qf (Equiv.swap (0 : Fin (m + 1)) i j.succ))) =
      eval₂ ((tailSwap i : Conv ℂ m →+* Conv ℂ (m + 1)).comp
        (convEmbed ℂ (predEmb e hi)).toRingHom) (tailSwap i (convX ℂ j))
        (Qf (Equiv.swap (0 : Fin (m + 1)) i j.succ)) :=
    hom_eval₂ _ _ (tailSwap i : Conv ℂ m →+* Conv ℂ (m + 1)) _
  rw [h]
  have hcomp : ((tailSwap i : Conv ℂ m →+* Conv ℂ (m + 1)).comp
      (convEmbed ℂ (predEmb e hi)).toRingHom) = (convEmbed ℂ e).toRingHom :=
    RingHom.ext fun a => tailSwap_convEmbed e hi a
  rw [hcomp]
  congr 1
  exact tailSwap_convX i j

/-- The relation of the fibre coordinate `i`, after the swap, is the monic polynomial `Qf_i` in
`x_0` with coefficients embedded from the tail ring. -/
theorem permConv_swap_rel (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)} (hi : i ∉ Set.range e)
    (Qf : Fin (m + 1) → Polynomial (Conv ℂ d)) :
    permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i)
        (((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i)) =
      convPolyEval ℂ ((Qf i).map (convEmbed ℂ (predEmb e hi)).toRingHom) := by
  rw [eval_map]
  have h : permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i)
      (eval₂ (convEmbed ℂ e).toRingHom (convX ℂ i) (Qf i)) =
      eval₂ ((permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i) :
        Conv ℂ (m + 1) →+* Conv ℂ (m + 1)).comp (convEmbed ℂ e).toRingHom)
        (permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i) (convX ℂ i)) (Qf i) :=
    hom_eval₂ _ _ (permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i) :
      Conv ℂ (m + 1) →+* Conv ℂ (m + 1)) _
  rw [h]
  have hcomp : ((permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i) :
      Conv ℂ (m + 1) →+* Conv ℂ (m + 1)).comp (convEmbed ℂ e).toRingHom) =
      (convTail ℂ).toRingHom.comp (convEmbed ℂ (predEmb e hi)).toRingHom :=
    RingHom.ext fun a => by
      change permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i) (convEmbed ℂ e a) =
        convTail ℂ (convEmbed ℂ (predEmb e hi) a)
      rw [permConv_convEmbed, convTail_convEmbed, predEmb_trans_succ]
  have hX : permConv ℂ (Equiv.swap (0 : Fin (m + 1)) i) (convX ℂ i) = convX ℂ 0 := by
    rw [permConv_convX, Equiv.swap_apply_right]
  rw [hcomp, hX, ← eval₂_map]
  rfl

/-- The transport of a box element of the smaller ring, times a power `x_i^k` with
`k < deg Qf_i`, is a box element of the larger ring. -/
theorem tailSwap_mem_fibreBox (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)} (hi : i ∉ Set.range e)
    (Qf : Fin (m + 1) → Polynomial (Conv ℂ d)) {g : Conv ℂ m}
    (hg : g ∈ fibreBox (predEmb e hi) fun j => Qf (Equiv.swap (0 : Fin (m + 1)) i j.succ))
    {k : ℕ} (hk : k < (Qf i).natDegree) :
    tailSwap i g * convX ℂ i ^ k ∈ fibreBox e Qf := by
  classical
  induction hg using AddSubmonoid.closure_induction with
  | mem g hgen =>
    obtain ⟨a, μ, h0, hlt, rfl⟩ := hgen
    set τ := Equiv.swap (0 : Fin (m + 1)) i with hτ
    -- the exponent function on the larger index set
    let μ' : Fin (m + 1) → ℕ := fun i' => Fin.cases k (fun j => μ j) (τ i')
    have hτi : τ i = 0 := by rw [hτ]; exact Equiv.swap_apply_right 0 i
    have hττ : ∀ x, τ (τ x) = x := fun x => by rw [hτ]; exact Equiv.swap_apply_self _ _ _
    have hμ'i : μ' i = k := by
      simp only [μ', hτi, Fin.cases_zero]
    have hμ'succ : ∀ j : Fin m, μ' (τ j.succ) = μ j := fun j => by
      simp only [μ', hττ, Fin.cases_succ]
    have hprod : tailSwap i (convEmbed ℂ (predEmb e hi) a * ∏ j, convX ℂ j ^ μ j) *
        convX ℂ i ^ k = convEmbed ℂ e a * ∏ i', convX ℂ i' ^ μ' i' := by
      rw [map_mul, map_prod, tailSwap_convEmbed]
      simp_rw [map_pow, tailSwap_convX]
      rw [mul_assoc]
      congr 1
      rw [← Equiv.prod_comp τ (fun i' => convX ℂ i' ^ μ' i'), Fin.prod_univ_succ, hτ,
        Equiv.swap_apply_left, ← hτ, hμ'i, mul_comm]
      congr 1
      refine Finset.prod_congr rfl fun j _ => ?_
      rw [hμ'succ]
    rw [hprod]
    refine mem_fibreBox_of a μ' (fun i' hi' => ?_) (fun i' hi' => ?_)
    · -- a base index: `τ i'` is a successor, its predecessor is a base index of the smaller ring
      have hne : τ i' ≠ 0 := swap_apply_ne_zero_of_mem_range e hi hi'
      obtain ⟨j, hj⟩ : ∃ j : Fin m, τ i' = j.succ := ⟨(τ i').pred hne, (Fin.succ_pred _ _).symm⟩
      have hi'j : i' = τ j.succ := by rw [← hj, hτ, Equiv.swap_apply_self]
      rw [hi'j, hμ'succ]
      apply h0
      rw [← not_not (a := j ∈ Set.range (predEmb e hi)), notMem_range_predEmb_iff, not_not, ← hτ,
        ← hi'j]
      exact hi'
    · by_cases hii : i' = i
      · subst hii; rw [hμ'i]; exact hk
      · have hne : τ i' ≠ 0 := by
          intro h
          apply hii
          have h' := congrArg τ h
          rwa [hτ, Equiv.swap_apply_self, Equiv.swap_apply_left] at h'
        obtain ⟨j, hj⟩ : ∃ j : Fin m, τ i' = j.succ := ⟨(τ i').pred hne, (Fin.succ_pred _ _).symm⟩
        have hi'j : i' = τ j.succ := by rw [← hj, hτ, Equiv.swap_apply_self]
        rw [hi'j, hμ'succ]
        have hj' : j ∉ Set.range (predEmb e hi) := by
          rw [notMem_range_predEmb_iff, ← hτ, ← hi'j]; exact hi'
        exact hlt j hj'
  | zero => rw [map_zero, zero_mul]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add, add_mul]; exact add_mem hx hy

/-- The transport of the relation ideal of the smaller ring lies in the relation ideal of the
larger ring. -/
theorem tailSwap_mem_fibreRelIdeal (e : Fin d ↪ Fin (m + 1)) {i : Fin (m + 1)}
    (hi : i ∉ Set.range e) (Qf : Fin (m + 1) → Polynomial (Conv ℂ d)) {r : Conv ℂ m}
    (hr : r ∈ fibreRelIdeal (predEmb e hi) fun j => Qf (Equiv.swap (0 : Fin (m + 1)) i j.succ)) :
    tailSwap i r ∈ fibreRelIdeal e Qf := by
  have h1 := Ideal.mem_map_of_mem (tailSwap i : Conv ℂ m →+* Conv ℂ (m + 1)) hr
  refine (show Ideal.map (tailSwap i : Conv ℂ m →+* Conv ℂ (m + 1))
      (fibreRelIdeal (predEmb e hi) fun j => Qf (Equiv.swap (0 : Fin (m + 1)) i j.succ)) ≤
        fibreRelIdeal e Qf from ?_) h1
  rw [fibreRelIdeal, Ideal.map_span, Ideal.span_le]
  rintro x ⟨y, ⟨⟨j, hj⟩, rfl⟩, rfl⟩
  change tailSwap i _ ∈ _
  rw [tailSwap_rel]
  exact rel_mem_fibreRelIdeal ((notMem_range_predEmb_iff e hi j).mp hj)

end Step

/-- Iterated Weierstrass division (the division argument of [Fre17, Ch. I, 8.3], simultaneous in
the fibre coordinates): with monic relations `Qf_i(x_i)` for every fibre coordinate, every
`F ∈ 𝒪_m` is, modulo the ideal of the relations, a polynomial in the fibre coordinates over the
base with exponents below the degrees, by induction on the number of variables, dividing by one
relation at a time. -/
theorem exists_mem_fibreBox_sub_mem :
    ∀ {m : ℕ} (e : Fin d ↪ Fin m) (Qf : Fin m → Polynomial (Conv ℂ d)),
      (∀ i, i ∉ Set.range e → (Qf i).Monic) → ∀ F : Conv ℂ m,
        ∃ G ∈ fibreBox e Qf, F - G ∈ fibreRelIdeal e Qf := by
  intro m
  induction m with
  | zero =>
    intro e Qf _ F
    exact exists_mem_fibreBox_sub_mem_of_surjective Qf (fun i => i.elim0) F
  | succ m ih =>
    intro e Qf hmonic F
    by_cases hsurj : Function.Surjective e
    · exact exists_mem_fibreBox_sub_mem_of_surjective Qf hsurj F
    obtain ⟨i, hi⟩ : ∃ i, i ∉ Set.range e := by
      by_contra hall
      exact hsurj fun i => by
        by_contra hi
        exact hall ⟨i, hi⟩
    set τ := Equiv.swap (0 : Fin (m + 1)) i with hτ
    set σ := permConv ℂ τ with hσ
    set e' := predEmb e hi with he'
    set Qf' : Fin m → Polynomial (Conv ℂ d) := fun j => Qf (τ j.succ) with hQf'
    have hmonic' : ∀ j, j ∉ Set.range e' → (Qf' j).Monic := fun j hj =>
      hmonic _ ((notMem_range_predEmb_iff e hi j).mp hj)
    -- the relation of `x_i`, after the swap: a monic polynomial in `x_0`
    have hW := permConv_swap_rel e hi Qf
    obtain ⟨d', hd'le, hreg⟩ :=
      exists_isRegularIn_convPolyEval_of_monic ((Qf i).map (convEmbed ℂ e').toRingHom)
        ((hmonic i hi).map _)
    have hd' : d' ≤ (Qf i).natDegree := hd'le.trans_eq ((hmonic i hi).natDegree_map _)
    -- Weierstrass division of `σ F`
    obtain ⟨q, b, k, hk, hσF⟩ := exists_eq_mul_add_sum_convTail_mul_convX_pow hreg (σ F)
    -- the induction hypothesis on the coefficients
    choose G' hG' hr' using fun j => ih e' Qf' hmonic' (b j)
    refine ⟨∑ j, tailSwap i (G' j) * convX ℂ i ^ k j, ?_, ?_⟩
    · exact AddSubmonoid.sum_mem _ fun j _ =>
        tailSwap_mem_fibreBox e hi Qf (hG' j) ((hk j).trans_le hd')
    · -- `F = σ⁻¹ (σ F)`, expanded
      have hF : F = σ.symm q * ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i) +
          ∑ j, tailSwap i (b j) * convX ℂ i ^ k j := by
        have h1 := congrArg σ.symm hσF
        rw [AlgEquiv.symm_apply_apply, map_add, map_mul, map_sum] at h1
        rw [h1, ← hW, AlgEquiv.symm_apply_apply]
        congr 1
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [map_mul, map_pow, tailSwap_apply, hσ, permConv_symm, permConv_convX, Equiv.symm_swap,
          Equiv.swap_apply_left]
      rw [hF]
      have hsplit : ∑ j, tailSwap i (b j) * convX ℂ i ^ k j -
          ∑ j, tailSwap i (G' j) * convX ℂ i ^ k j =
          ∑ j, tailSwap i (b j - G' j) * convX ℂ i ^ k j := by
        rw [← Finset.sum_sub_distrib]
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [map_sub, sub_mul]
      rw [add_sub_assoc, hsplit]
      refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ (rel_mem_fibreRelIdeal hi))
        (Ideal.sum_mem _ fun j _ => Ideal.mul_mem_right _ _ ?_)
      exact tailSwap_mem_fibreRelIdeal e hi Qf (hr' j)

end Analytic
