/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Analytic.ConvSeries.ConvNorm
public import Mathlib.RingTheory.Noetherian.Defs
import Hironaka.Analytic.ConvSeries.Units
import Hironaka.Analytic.Rueckert.Slices
import Hironaka.Analytic.Rueckert.Subst
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Tactic.Positivity.Finset

/-!
# Rückert's basis theorem: `Conv K m` is Noetherian

Rückert's basis theorem [GR65, Chapter II, §B], by induction on `m`. `Conv K 0 ≅ K` is a field
(every nonzero element is a unit). For `m + 1`: let `I` be a nonzero ideal, `f ∈ I` nonzero; a
linear change `L` (`exists_substEquiv_isRegularIn`, `Subst.lean`) makes `g = f ∘ L` `x_0`-regular
of order `d`, and it suffices to show that `J = I ∘ L` is finitely generated (finite generation
transports along the automorphism). The Weierstrass division by `g` writes every element as
`q g + r` with `r` of `x_0`-degree `< d`, and `r = ∑_{j<d} convTail (slice_j) x_0^j`, so
`Conv K (m+1) ⧸ (g)` is a `Conv K m`-module generated by the classes of `1, x_0, …, x_0^{d-1}`;
over the Noetherian `Conv K m` (induction hypothesis) it is a Noetherian module, hence Noetherian
as a `Conv K (m+1)`-module (`isNoetherian_of_tower`). The image of `J` in the quotient is
therefore finitely generated, and so is `J ∩ (g) = (g)`; hence `J` is finitely generated
(`Submodule.fg_of_fg_map_of_fg_inf_ker`).

The `Conv K m`-module structures are local instances (a global
`Algebra (Conv K m) (Conv K (m+1))` instance makes instance search run very long).
Noetherianity is what gives every ideal of germs a finite generating system
(`ZeroSet.lean`) and the stalks of the structure sheaf of an analytic manifold their Noetherian
structure (`Hironaka/Manifold/Germ/StalkNoetherian.lean`).

The coefficient field `K` is `ℝ` or `ℂ` (`[RCLike K]`).
-/

@[expose] public section

open MvPowerSeries

namespace Analytic

variable {K : Type*} [RCLike K]

section Zero

/-- Every nonzero element of `Conv K 0` is a unit. -/
theorem isUnit_of_ne_zero_conv_zero {f : Conv K 0} (hf : f ≠ 0) : IsUnit f := by
  rw [← Subtype.coe_eta f f.2, isUnit_iff_constantCoeff_ne_zero]
  intro h0
  apply hf
  apply Subtype.ext
  apply MvPowerSeries.ext
  intro ν
  rw [Subsingleton.elim ν 0, coeff_zero_eq_constantCoeff_apply, h0]
  simp

/-- `Conv K 0` is Noetherian. -/
theorem isNoetherianRing_conv_zero : IsNoetherianRing (Conv K 0) := by
  rw [isNoetherianRing_iff_ideal_fg]
  intro I
  by_cases hI : I = ⊥
  · rw [hI]
    exact Submodule.fg_bot
  · obtain ⟨f, hfI, hf0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hI
    rw [Ideal.eq_top_of_isUnit_mem I hfI (isUnit_of_ne_zero_conv_zero hf0)]
    exact ⟨{1}, by simp⟩

end Zero

section Succ

variable {m : ℕ}

/-- The inductive step: if `Conv K m` is Noetherian, so is `Conv K (m+1)` (Weierstrass division
by a regular element makes the quotient a finite `Conv K m`-module) [GR65, Chapter II, §B]. -/
theorem isNoetherianRing_conv_succ [IsNoetherianRing (Conv K m)] :
    IsNoetherianRing (Conv K (m + 1)) := by
  classical
  rw [isNoetherianRing_iff_ideal_fg]
  intro I
  by_cases hI : I = ⊥
  · rw [hI]
    exact Submodule.fg_bot
  obtain ⟨f, hfI, hf0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hI
  obtain ⟨L, hreg⟩ := exists_substEquiv_isRegularIn hf0
  set e : Conv K (m + 1) ≃+* Conv K (m + 1) := (substEquiv L).toRingEquiv with he
  set g : Conv K (m + 1) := substEquiv L f with hg
  set J : Ideal (Conv K (m + 1)) := I.map (e : Conv K (m + 1) →+* Conv K (m + 1)) with hJ
  have hgJ : g ∈ J := Ideal.mem_map_of_mem _ hfI
  suffices hJfg : J.FG by
    obtain ⟨S, hS⟩ := hJfg
    have hIJ : I = Ideal.map (e.symm : Conv K (m + 1) →+* Conv K (m + 1)) J := by
      have hcomp : (e.symm : Conv K (m + 1) →+* Conv K (m + 1)).comp
          (e : Conv K (m + 1) →+* Conv K (m + 1)) = RingHom.id _ :=
        RingHom.ext fun x => e.symm_apply_apply x
      rw [hJ, Ideal.map_map, hcomp, Ideal.map_id]
    rw [hIJ, ← hS, Ideal.map_span]
    exact Submodule.fg_span (S.finite_toSet.image _)
  set d := (f : MvPowerSeries (Fin (m + 1)) K).order.toNat with hd
  set P : Ideal (Conv K (m + 1)) := Ideal.span {g} with hP
  have hPJ : P ≤ J := (Submodule.span_singleton_le_iff_mem g J).mpr hgJ
  -- `Conv K (m+1)` and its quotient by `P` as `Conv K m`-modules through the tail embedding
  let sm : SMul (Conv K m) (Conv K (m + 1)) := ⟨fun a b => convTail K a * b⟩
  let mod : Module (Conv K m) (Conv K (m + 1)) :=
    { sm with
      one_smul := fun b => by
        change convTail K 1 * b = b
        rw [map_one, one_mul]
      mul_smul := fun a a' b => by
        change convTail K (a * a') * b = convTail K a * (convTail K a' * b)
        rw [map_mul, mul_assoc]
      smul_zero := fun a => by
        change convTail K a * 0 = 0
        rw [mul_zero]
      smul_add := fun a b b' => by
        change convTail K a * (b + b') = convTail K a * b + convTail K a * b'
        rw [mul_add]
      add_smul := fun a a' b => by
        change convTail K (a + a') * b = convTail K a * b + convTail K a' * b
        rw [map_add, add_mul]
      zero_smul := fun b => by
        change convTail K 0 * b = 0
        rw [map_zero, zero_mul] }
  have tower : IsScalarTower (Conv K m) (Conv K (m + 1)) (Conv K (m + 1)) :=
    ⟨fun a b c => mul_assoc (convTail K a) b c⟩
  have hsmul : ∀ (a : Conv K m) (b : Conv K (m + 1)), a • b = convTail K a * b := fun _ _ => rfl
  let smR : SMul (Conv K (m + 1)) (Conv K (m + 1) ⧸ P) :=
    (Submodule.Quotient.module P).toDistribMulAction.toMulAction.toSMul
  let modQ : Module (Conv K m) (Conv K (m + 1) ⧸ P) := Submodule.Quotient.module' P
  let smQ : SMul (Conv K m) (Conv K (m + 1) ⧸ P) :=
    modQ.toDistribMulAction.toMulAction.toSMul
  have towerQ : IsScalarTower (Conv K m) (Conv K (m + 1)) (Conv K (m + 1) ⧸ P) :=
    Submodule.Quotient.isScalarTower P (Conv K (m + 1))
  -- the quotient is generated over `Conv K m` by the classes of `x_0^k`, `k < d`
  have fin : Module.Finite (Conv K m) (Conv K (m + 1) ⧸ P) := by
    rw [Module.finite_def]
    refine ⟨Finset.image (fun j : Fin d => P.mkQ (convX K 0 ^ (d - 1 - (j : ℕ)))) Finset.univ, ?_⟩
    rw [Submodule.eq_top_iff']
    intro x
    obtain ⟨y, rfl⟩ := P.mkQ_surjective x
    obtain ⟨q, r, hdeg, hy⟩ := exists_division_conv (f := y) (g := g) hreg
    have hyr : P.mkQ y = P.mkQ r := by
      rw [hy, map_add, add_eq_right, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
      exact Ideal.mul_mem_left P q (Ideal.mem_span_singleton_self g)
    rw [hyr, eq_sum_convTail_sliceConv hdeg, map_sum]
    refine Submodule.sum_mem _ fun j _ => ?_
    rw [← hsmul, Submodule.mkQ_apply, Submodule.Quotient.mk_smul]
    refine Submodule.smul_mem _ _ (Submodule.subset_span ?_)
    rw [Finset.coe_image]
    exact ⟨j, Finset.mem_coe.mpr (Finset.mem_univ j), rfl⟩
  have noethQ : IsNoetherian (Conv K m) (Conv K (m + 1) ⧸ P) :=
    isNoetherian_of_isNoetherianRing_of_finite (Conv K m) _
  have noethQ' : IsNoetherian (Conv K (m + 1)) (Conv K (m + 1) ⧸ P) :=
    isNoetherian_of_tower (Conv K m) noethQ
  refine Submodule.fg_of_fg_map_of_fg_inf_ker P.mkQ (IsNoetherian.noetherian _) ?_
  rw [Submodule.ker_mkQ, inf_eq_right.mpr hPJ]
  exact Submodule.fg_span_singleton g

end Succ

variable (K) in
/-- Rückert's basis theorem: `Conv K m` is Noetherian [GR65, Chapter II, §B], by induction on
`m`. -/
theorem isNoetherianRing_conv {m : ℕ} : IsNoetherianRing (Conv K m) := by
  induction m with
  | zero => exact isNoetherianRing_conv_zero
  | succ m ih => exact @isNoetherianRing_conv_succ K _ m ih

variable (K) in
/-- Rückert's basis theorem as an instance (the theorem `isNoetherianRing_conv` registered for
instance search). -/
instance instIsNoetherianRingConv {m : ℕ} : IsNoetherianRing (Conv K m) :=
  isNoetherianRing_conv K

end Analytic
