/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Analytic.Rueckert.NoetherNormalization
public import Mathlib.Analysis.Complex.Basic
import Hironaka.Analytic.Rueckert.FibreDivision
import Hironaka.Analytic.Rueckert.MinpolyDvd
import Hironaka.Analytic.Rueckert.UFD
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.RingTheory.Polynomial.RationalRoot

/-!
# The division argument of the parametrization theorem

The division argument of [Fre17, Ch. I, 8.3], simultaneous in the fibre coordinates (see also
[GR84, Chapter 3]): with the data of the primitive normalization
(`ParametrizationPrimitive.lean`) in the coordinates of `σ = substEquiv L`, namely
`P' = comap σ P`, the primitive fibre coordinate `X_{i₀}` with its monic irreducible `Q`,
`Q(X_{i₀}) ∈ P'`, the denominators `A ≠ 0`, `B_i` with `A X_i − B_i(X_{i₀}) ∈ P'`, and monic
relations `Qf_i(X_i) ∈ P'` for every fibre coordinate, a power of `A` multiplies `P'` into the
ideal `J` generated by `Q(X_{i₀})`, the `Qf_i(X_i)` and the `A X_i − B_i(X_{i₀})`.

Proof. Let `F ∈ P'`. By the iterated Weierstrass division (`FibreDivision.lean`), `F ≡ G` modulo
the relations `Qf_i(X_i)` (all in `J`), with `G = ∑ a_μ(x_base) x_fibre^μ`, `μ_i < deg Qf_i`.
Modulo `J`, `A X_i = B_i(X_{i₀})`, so for `N := ∑_i deg Qf_i ≥ |μ|`,
`A^N x^μ ≡ A^{N-|μ|} ∏ B_i(X_{i₀})^{μ_i}`, and `A^N G ≡ H(X_{i₀})` for a polynomial `H ∈ 𝒪_d[T]`.
Since `J ⊆ P'`, `H(X_{i₀}) ∈ P'`, i.e. `H` vanishes at the class `ξ` of `X_{i₀}` in the domain
`𝒪_n/P'`; the base `𝒪_d` is a unique factorization domain (`UFD.lean`), hence integrally closed,
and embeds in `𝒪_n/P'` (the Noether normalization is injective), so `Q ∣ H` (`MinpolyDvd.lean`)
and `H(X_{i₀}) ∈ (Q(X_{i₀})) ⊆ J`. Hence `A^N F ∈ J`, with `N` independent of `F`.

The reduction `A^N F ≡ H(X_{i₀}) mod J` holds for every `F` (not only `F ∈ P'`) and is stated
separately as `exists_pow_mul_sub_eval_map_mem_span`.
-/

public section

open Polynomial

namespace Analytic

variable {n d : ℕ}

/-- The reduction of an arbitrary series: for any `F ∈ 𝒪_n`, `A^N F ≡ H(X_{i₀})` modulo the ideal
`J` generated by `Q(X_{i₀})`, the monic relations `Qf_i(X_i)` and the relations
`A X_i − B_i(X_{i₀})`, with `H ∈ 𝒪_d[X]` and `N = ∑_i deg Qf_i` independent of `F`: `F` is reduced
modulo the relations to a polynomial in the fibre coordinates (`exists_mem_fibreBox_sub_mem`),
and there `A X_i = B_i(X_{i₀})` clears the fibre coordinates. No ideal `P` enters. -/
theorem exists_pow_mul_sub_eval_map_mem_span (e : Fin d ↪ Fin n) (i₀ : Fin n)
    (Q : Polynomial (Conv ℂ d)) (A : Conv ℂ d) (B Qf : Fin n → Polynomial (Conv ℂ d))
    (hQf : ∀ i, i ∉ Set.range e → (Qf i).Monic) :
    ∃ N : ℕ, ∀ F : Conv ℂ n, ∃ H : Polynomial (Conv ℂ d),
      convEmbed ℂ e A ^ N * F - (H.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀) ∈
        Ideal.span ({(Q.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)} ∪
          Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
            ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i)) ∪
          Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
            convEmbed ℂ e A * convX ℂ i -
              ((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀))) := by
  classical
  set J : Ideal (Conv ℂ n) := Ideal.span ({(Q.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)} ∪
    Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
      ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i)) ∪
    Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
      convEmbed ℂ e A * convX ℂ i -
        ((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)))
  -- the three kinds of generators of `J`
  have hQfJ : ∀ i (hi : i ∉ Set.range e),
      ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i) ∈ J := fun i hi =>
    Ideal.subset_span (Or.inl (Or.inr ⟨⟨i, hi⟩, rfl⟩))
  have hBJ : ∀ i (hi : i ∉ Set.range e), convEmbed ℂ e A * convX ℂ i -
      ((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀) ∈ J := fun i hi =>
    Ideal.subset_span (Or.inr ⟨⟨i, hi⟩, rfl⟩)
  -- the relation ideal lies in `J`
  have hrel : fibreRelIdeal e Qf ≤ J := by
    rw [fibreRelIdeal, Ideal.span_le]
    rintro x ⟨⟨i, hi⟩, rfl⟩
    exact hQfJ i hi
  -- modulo `J`: `A X_i = B_i(X_{i₀})`
  have hAX : ∀ i (hi : i ∉ Set.range e), Ideal.Quotient.mk J (convEmbed ℂ e A * convX ℂ i) =
      Ideal.Quotient.mk J (((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)) := fun i hi =>
    Ideal.Quotient.eq.mpr (hBJ i hi)
  -- evaluation of base polynomials at `X_{i₀}`, in `𝒪_n / J`
  set ev : Polynomial (Conv ℂ d) →+* Conv ℂ n ⧸ J :=
    (Ideal.Quotient.mk J).comp (Polynomial.eval₂RingHom (convEmbed ℂ e).toRingHom (convX ℂ i₀))
    with hev_def
  have hev : ∀ H : Polynomial (Conv ℂ d),
      ev H = Ideal.Quotient.mk J ((H.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)) :=
    fun H => by rw [hev_def, RingHom.comp_apply, coe_eval₂RingHom, eval_map]
  have hevC : ∀ c : Conv ℂ d, ev (Polynomial.C c) = Ideal.Quotient.mk J (convEmbed ℂ e c) :=
    fun c => by rw [hev_def, RingHom.comp_apply, coe_eval₂RingHom, eval₂_C]; rfl
  -- the fibre indices and the exponent `N`
  set fib : Finset (Fin n) := Finset.univ.filter (fun i => i ∉ Set.range e) with hfib
  have hmem_fib : ∀ i, i ∈ fib ↔ i ∉ Set.range e := fun i =>
    Finset.mem_filter.trans (and_iff_right (Finset.mem_univ i))
  set N : ℕ := ∑ i ∈ fib, (Qf i).natDegree with hN
  -- every box element `G` has `A^N G ≡ H(X_{i₀})` modulo `J`
  have hbox : ∀ G ∈ fibreBox e Qf, ∃ H : Polynomial (Conv ℂ d),
      Ideal.Quotient.mk J (convEmbed ℂ e A ^ N * G) = ev H := by
    intro G hG
    induction hG using AddSubmonoid.closure_induction with
    | mem g hg =>
      obtain ⟨a, μ, h0, hlt, rfl⟩ := hg
      set s : ℕ := ∑ i ∈ fib, μ i with hs
      have hsN : s ≤ N := Finset.sum_le_sum fun i hi => (hlt i ((hmem_fib i).mp hi)).le
      refine ⟨Polynomial.C (a * A ^ (N - s)) * ∏ i ∈ fib, (B i) ^ μ i, ?_⟩
      -- the monomial only involves the fibre coordinates
      have hprod : ∏ i, convX ℂ i ^ μ i = ∏ i ∈ fib, convX ℂ i ^ μ i := by
        rw [← Finset.prod_filter_mul_prod_filter_not Finset.univ (fun i => i ∉ Set.range e)]
        rw [hfib]
        have : ∏ i ∈ Finset.univ.filter (fun i => ¬ i ∉ Set.range e), convX ℂ i ^ μ i = 1 :=
          Finset.prod_eq_one fun i hi => by
            rw [h0 i (not_not.mp (Finset.mem_filter.mp hi).2), pow_zero]
        rw [this, mul_one]
      -- `A^N = A^{N-s} ∏_{i ∈ fib} A^{μ i}`
      have hpow : convEmbed ℂ e A ^ N =
          convEmbed ℂ e A ^ (N - s) * ∏ i ∈ fib, convEmbed ℂ e A ^ μ i := by
        rw [Finset.prod_pow_eq_pow_sum, ← pow_add, Nat.sub_add_cancel hsN]
      have hR : ev (Polynomial.C (a * A ^ (N - s)) * ∏ i ∈ fib, (B i) ^ μ i) =
          Ideal.Quotient.mk J (convEmbed ℂ e (a * A ^ (N - s))) *
            ∏ i ∈ fib, (Ideal.Quotient.mk J
              (((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀))) ^ μ i := by
        rw [map_mul, hevC, map_prod]
        congr 1
        exact Finset.prod_congr rfl fun i _ => by rw [map_pow, hev]
      have hL : convEmbed ℂ e A ^ N * (convEmbed ℂ e a * ∏ i, convX ℂ i ^ μ i) =
          convEmbed ℂ e (a * A ^ (N - s)) * ∏ i ∈ fib, (convEmbed ℂ e A * convX ℂ i) ^ μ i := by
        rw [hprod, hpow, map_mul, map_pow]
        simp_rw [mul_pow]
        rw [Finset.prod_mul_distrib]
        ring
      rw [hR, hL, map_mul, map_prod]
      congr 1
      refine Finset.prod_congr rfl fun i hi => ?_
      rw [map_pow, hAX i ((hmem_fib i).mp hi)]
    | zero => exact ⟨0, by rw [mul_zero, map_zero, map_zero]⟩
    | add x y _ _ hx hy =>
      obtain ⟨H₁, h₁⟩ := hx
      obtain ⟨H₂, h₂⟩ := hy
      exact ⟨H₁ + H₂, by rw [mul_add, map_add, h₁, h₂, map_add]⟩
  refine ⟨N, fun F => ?_⟩
  -- the division: `F ≡ G` modulo the relations
  obtain ⟨G, hG, hFG⟩ := exists_mem_fibreBox_sub_mem e Qf hQf F
  obtain ⟨H, hH⟩ := hbox G hG
  have h1 : Ideal.Quotient.mk J (convEmbed ℂ e A ^ N * F) = ev H := by
    rw [← hH]
    apply Ideal.Quotient.eq.mpr
    rw [← mul_sub]
    exact Ideal.mul_mem_left _ _ (hrel hFG)
  exact ⟨H, Ideal.Quotient.eq.mp (h1.trans (hev H))⟩

/-- The division argument of the parametrization theorem ([Fre17, Ch. I, 8.3], simultaneous in
the fibre coordinates): for a prime `P` with the data of the primitive normalization and monic
relations for every fibre coordinate, some power of `A` multiplies `comap σ P` into the ideal
generated by `Q(X_{i₀})`, the monic relations and the relations `A X_i − B_i(X_{i₀})`. -/
theorem exists_pow_mul_mem_span_of_isPrime (P : Ideal (Conv ℂ n)) [P.IsPrime] {d : ℕ}
    (e : Fin d ↪ Fin n) (L : (Fin n → ℂ) ≃L[ℂ] (Fin n → ℂ))
    (hinj : Function.Injective (normMap ℂ P e L)) (i₀ : Fin n) (_hi₀ : i₀ ∉ Set.range e)
    (Q : Polynomial (Conv ℂ d)) (hQ : Q.Monic) (hQirr : Irreducible Q)
    (hQP : (Q.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀) ∈ Ideal.comap (substEquiv L) P)
    (A : Conv ℂ d) (_hA : A ≠ 0) (B : Fin n → Polynomial (Conv ℂ d))
    (hB : ∀ i, i ∉ Set.range e → convEmbed ℂ e A * convX ℂ i -
      ((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀) ∈ Ideal.comap (substEquiv L) P)
    (Qf : Fin n → Polynomial (Conv ℂ d)) (hQf : ∀ i, i ∉ Set.range e → (Qf i).Monic)
    (hQfP : ∀ i, i ∉ Set.range e →
      ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i) ∈ Ideal.comap (substEquiv L) P) :
    ∃ N : ℕ, ∀ F ∈ Ideal.comap (substEquiv L) P, convEmbed ℂ e A ^ N * F ∈
      Ideal.span ({(Q.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)} ∪
        Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
          ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i)) ∪
        Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
          convEmbed ℂ e A * convX ℂ i -
            ((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀))) := by
  classical
  -- `_hi₀` and `_hA` are part of the data of the primitive normalization
  -- (`exists_primitive_normalization`) and are kept so that the theorem applies to that output as
  -- it stands; the argument does not need them, because the fibre condition on `i₀` and the
  -- nonvanishing of `A` enter only through the relations `hQP`, `hB` and the monic irreducible
  -- `Q`, which are hypotheses in their own right
  set P' : Ideal (Conv ℂ n) := Ideal.comap (substEquiv L) P with hP'
  set J : Ideal (Conv ℂ n) := Ideal.span ({(Q.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)} ∪
    Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
      ((Qf i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i)) ∪
    Set.range (fun i : {i : Fin n // i ∉ Set.range e} =>
      convEmbed ℂ e A * convX ℂ i -
        ((B i).map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀))) with hJ
  -- the three kinds of generators of `J`
  have hQJ : (Q.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀) ∈ J :=
    Ideal.subset_span (Or.inl (Or.inl rfl))
  -- `J ⊆ P'`
  have hJP : J ≤ P' := by
    rw [hJ, Ideal.span_le]
    rintro x ((rfl | ⟨⟨i, hi⟩, rfl⟩) | ⟨⟨i, hi⟩, rfl⟩)
    · exact hQP
    · exact hQfP i hi
    · exact hB i hi
  obtain ⟨N, hN⟩ := exists_pow_mul_sub_eval_map_mem_span e i₀ Q A B Qf hQf
  refine ⟨N, fun F hF => ?_⟩
  obtain ⟨H, hdiff⟩ := hN F
  have hHP : (H.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀) ∈ P' := by
    have hAF : convEmbed ℂ e A ^ N * F ∈ P' := Ideal.mul_mem_left _ _ hF
    have := Ideal.sub_mem P' hAF (hJP hdiff)
    rwa [sub_sub_cancel] at this
  -- in the domain `𝒪_n / P'`, `Q ∣ H` by the minimal-polynomial argument
  have hdom : IsDomain (Conv ℂ n ⧸ P') := Ideal.Quotient.isDomain P'
  set f : Conv ℂ d →+* Conv ℂ n ⧸ P' := (Ideal.Quotient.mk P').comp (convEmbed ℂ e).toRingHom
    with hf
  have hfinj : Function.Injective f := by
    intro a b hab
    rw [hf, RingHom.comp_apply, RingHom.comp_apply, Ideal.Quotient.eq] at hab
    apply hinj
    rw [normMap_apply, normMap_apply, Ideal.Quotient.eq, ← map_sub, ← map_sub]
    have hmem : convEmbed ℂ e (a - b) ∈ P' := by rw [map_sub]; exact hab
    exact Ideal.mem_comap.mp hmem
  have hmkev : ∀ H' : Polynomial (Conv ℂ d),
      Ideal.Quotient.mk P' ((H'.map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀)) =
        eval₂ f (Ideal.Quotient.mk P' (convX ℂ i₀)) H' := fun H' => by
    rw [eval_map]
    exact hom_eval₂ H' (convEmbed ℂ e).toRingHom (Ideal.Quotient.mk P') (convX ℂ i₀)
  have hQξ : eval₂ f (Ideal.Quotient.mk P' (convX ℂ i₀)) Q = 0 := by
    rw [← hmkev]; exact Ideal.Quotient.eq_zero_iff_mem.mpr hQP
  have hHξ : eval₂ f (Ideal.Quotient.mk P' (convX ℂ i₀)) H = 0 := by
    rw [← hmkev]; exact Ideal.Quotient.eq_zero_iff_mem.mpr hHP
  obtain ⟨H', rfl⟩ := dvd_of_eval₂_eq_zero_of_monic_irreducible f hfinj hQ hQirr hQξ hHξ
  -- `H(X_{i₀}) = Q(X_{i₀}) H'(X_{i₀}) ∈ J`, so `A^N F ∈ J`
  have hHJ : ((Q * H').map (convEmbed ℂ e).toRingHom).eval (convX ℂ i₀) ∈ J := by
    rw [Polynomial.map_mul, eval_mul]
    exact Ideal.mul_mem_right _ _ hQJ
  have := Ideal.add_mem J hdiff hHJ
  rwa [sub_add_cancel] at this

end Analytic
