/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Analytic.Rueckert.Embed
public import Hironaka.Analytic.Rueckert.Basic
public import Mathlib.RingTheory.KrullDimension.Basic
import Hironaka.Algebra.Local.IntegralKrullDim
import Hironaka.Analytic.ConvSeries.CoordDivision
import Hironaka.Analytic.ConvSeries.Units
import Hironaka.Analytic.Rueckert.Noetherian
import Mathlib.Algebra.Order.Algebra
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Tactic.Positivity.Finset

/-!
# Systems of parameters in the germ ring `𝒪_n`

The algebra behind the upper semicontinuity of the dimension of an analytic germ
[Fre17, Ch. II, 5.4], on `Conv K n`. After a linear change of coordinates `σ = substEquiv L` and
a choice `e : Fin d ↪ Fin n` of base coordinates, suppose every fibre coordinate `σ (X i)`,
`i ∉ range e`, satisfies a monic polynomial with constant coefficients modulo
`I ⊔ (σ X (e j))_j`. Then the maximal ideal `𝔪`, generated by the `σ (X i)`
(`maximalIdeal_conv_eq_span_algEquiv_convX`: Hadamard's lemma for series `sum_X_mul_divPart`
transported by the automorphism), lies in the radical of `I ⊔ (σ X (e j))_j`
(`mem_radical_of_monic_aeval_mem`: factor the monic polynomial as `X^s · u` with `u(0) ≠ 0`, so
`u(σ X i)` is a unit), and Krull's height theorem
(`IsLocalRing.ringKrullDim_quotient_le_of_maximalIdeal_le_radical_sup`) gives
`dim 𝒪_n / I ≤ d` (`ringKrullDim_quotient_le_of_parameters`). The lemma
`convEmbed_sub_algebraMap_mem` (a series in the base coordinates is its constant term modulo the
base coordinates) is what reduces the relations coming from a Noether normalization to relations
with constant coefficients. The dimension theory itself is [Fre17, Ch. VII, 5.6] read on the
germ ring.
-/

@[expose] public section

open MvPowerSeries IsLocalRing

namespace Analytic

variable {K : Type*} [RCLike K] {n d : ℕ}

/-- The constant coefficient of a convergent series, as a ring homomorphism `Conv K n →+* K`. -/
noncomputable def constantCoeffConv : Conv K n →+* K :=
  (constantCoeff : MvPowerSeries (Fin n) K →+* K).comp (Conv K n).val.toRingHom

theorem constantCoeffConv_apply (f : Conv K n) :
    constantCoeffConv f = constantCoeff (f : MvPowerSeries (Fin n) K) := rfl

/-- The constant coefficient of a constant series. -/
theorem constantCoeffConv_algebraMap (r : K) :
    constantCoeffConv (algebraMap K (Conv K n) r) = r := by
  rw [constantCoeffConv_apply, Subalgebra.coe_algebraMap, MvPowerSeries.algebraMap_apply,
    constantCoeff_C]
  simp

/-- `f ∈ 𝔪` iff its constant coefficient vanishes (the unit criterion
`isUnit_iff_constantCoeff_ne_zero`). -/
theorem mem_maximalIdeal_conv_iff (f : Conv K n) :
    f ∈ maximalIdeal (Conv K n) ↔ constantCoeff (f : MvPowerSeries (Fin n) K) = 0 := by
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
  obtain ⟨f, hf⟩ := f
  rw [isUnit_iff_constantCoeff_ne_zero hf, not_not]

/-- The maximal ideal of `Conv K n` is generated by the coordinates (series-level Hadamard,
`sum_X_mul_divPart`). -/
theorem maximalIdeal_conv_eq_span_convX :
    maximalIdeal (Conv K n) = Ideal.span (Set.range (convX K (n := n))) := by
  apply le_antisymm
  · intro f hf
    rw [mem_maximalIdeal_conv_iff] at hf
    have h := sum_X_mul_divPart hf
    have : f = ∑ i, convX K i *
        ⟨divPart i (f : MvPowerSeries (Fin n) K), divPart_mem_conv f.2 i⟩ := by
      apply Subtype.ext
      simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_mul, coe_convX]
      exact h.symm
    rw [this]
    exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)
  · rw [Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    rw [SetLike.mem_coe, mem_maximalIdeal_conv_iff, coe_convX, constantCoeff_X]

/-- An algebra automorphism of `Conv K n` preserves the maximal ideal. -/
theorem mem_maximalIdeal_algEquiv_iff (σ : Conv K n ≃ₐ[K] Conv K n) (f : Conv K n) :
    σ f ∈ maximalIdeal (Conv K n) ↔ f ∈ maximalIdeal (Conv K n) := by
  simp only [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
  constructor
  · intro h hf
    exact h (hf.map σ)
  · intro h hf
    have := hf.map σ.symm
    rw [AlgEquiv.symm_apply_apply] at this
    exact h this

/-- The maximal ideal is generated by the images of the coordinates under an automorphism. -/
theorem maximalIdeal_conv_eq_span_algEquiv_convX (σ : Conv K n ≃ₐ[K] Conv K n) :
    maximalIdeal (Conv K n) = Ideal.span (Set.range fun i => σ (convX K i)) := by
  have h : Ideal.span (Set.range fun i => σ (convX K i)) =
      Ideal.map σ (Ideal.span (Set.range (convX K (n := n)))) := by
    rw [Ideal.map_span, ← Set.range_comp]
    rfl
  rw [h, ← maximalIdeal_conv_eq_span_convX]
  apply le_antisymm
  · intro f hf
    have : f = σ (σ.symm f) := (AlgEquiv.apply_symm_apply σ f).symm
    rw [this]
    exact Ideal.mem_map_of_mem _ ((mem_maximalIdeal_algEquiv_iff σ.symm f).mpr hf)
  · rw [Ideal.map_le_iff_le_comap]
    intro f hf
    exact Ideal.mem_comap.mpr ((mem_maximalIdeal_algEquiv_iff σ f).mpr hf)

/-- A series in the coordinates `e i` differs from its constant coefficient by an element of the
ideal generated by the coordinates `X (e j)` (series-level Hadamard, transported by `rename`). -/
theorem convEmbed_sub_algebraMap_mem (e : Fin d ↪ Fin n) (c : Conv K d) :
    convEmbed K e c - algebraMap K (Conv K n) (constantCoeff (c : MvPowerSeries (Fin d) K)) ∈
      Ideal.span (Set.range fun j => convX K (e j)) := by
  obtain ⟨c₀, hc₀⟩ : ∃ c₀ : Conv K d,
      c₀ = c - algebraMap K (Conv K d) (constantCoeff (c : MvPowerSeries (Fin d) K)) := ⟨_, rfl⟩
  have hc₀' : (c₀ : MvPowerSeries (Fin d) K) =
      (c : MvPowerSeries (Fin d) K) - C (constantCoeff (c : MvPowerSeries (Fin d) K)) := by
    rw [hc₀, Subalgebra.coe_sub, Subalgebra.coe_algebraMap, MvPowerSeries.algebraMap_apply]
    simp
  have h0 : constantCoeff (c₀ : MvPowerSeries (Fin d) K) = 0 := by
    rw [hc₀', map_sub, constantCoeff_C, sub_self]
  have h := sum_X_mul_divPart h0
  have h1 : convEmbed K e c -
      algebraMap K (Conv K n) (constantCoeff (c : MvPowerSeries (Fin d) K)) = convEmbed K e c₀ := by
    rw [hc₀, map_sub, AlgHom.commutes]
  have h2 : convEmbed K e c₀ = ∑ j, convX K (e j) *
      convEmbed K e ⟨divPart j (c₀ : MvPowerSeries (Fin d) K), divPart_mem_conv c₀.2 j⟩ := by
    apply Subtype.ext
    simp only [AddSubmonoidClass.coe_finsetSum, Subalgebra.coe_mul, coe_convX, coe_convEmbed]
    conv_lhs => rw [← h]
    rw [map_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [map_mul, rename_X]
  rw [h1, h2]
  exact Ideal.sum_mem _ fun j _ => Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨j, rfl⟩)

/-- A polynomial with constant coefficients evaluated at an element of `𝔪` has constant coefficient
`p(0)`. -/
theorem constantCoeffConv_aeval (p : Polynomial K) {x : Conv K n}
    (hx : x ∈ maximalIdeal (Conv K n)) :
    constantCoeffConv (Polynomial.aeval x p) = p.eval 0 := by
  rw [Polynomial.aeval_def, Polynomial.hom_eval₂]
  have hx0 : constantCoeffConv x = 0 := (mem_maximalIdeal_conv_iff x).mp hx
  rw [hx0]
  have : constantCoeffConv.comp (algebraMap K (Conv K n)) = RingHom.id K := by
    ext r
    simp only [RingHom.comp_apply, RingHom.id_apply, constantCoeffConv_algebraMap]
  rw [this, Polynomial.eval₂_id]

/-- A convergent series is a unit iff its constant coefficient is nonzero
(`isUnit_iff_constantCoeff_ne_zero`, on `Conv`). -/
theorem isUnit_conv_iff (f : Conv K n) :
    IsUnit f ↔ constantCoeff (f : MvPowerSeries (Fin n) K) ≠ 0 := by
  obtain ⟨f, hf⟩ := f
  exact isUnit_iff_constantCoeff_ne_zero hf

/-- If a monic polynomial with constant coefficients vanishes at `x ∈ 𝔪` modulo `I`, then `x` is in
the radical of `I` — factor `p = X^s · u` with `u(0) ≠ 0`, so `u(x)` is a unit. -/
theorem mem_radical_of_monic_aeval_mem {I : Ideal (Conv K n)} {x : Conv K n}
    (hx : x ∈ maximalIdeal (Conv K n)) {p : Polynomial K} (hp : p.Monic)
    (hmem : Polynomial.aeval x p ∈ I) : x ∈ I.radical := by
  obtain ⟨q, hpq, hq⟩ := Polynomial.exists_eq_pow_rootMultiplicity_mul_and_not_dvd p hp.ne_zero 0
  rw [Polynomial.dvd_iff_isRoot, Polynomial.IsRoot.def] at hq
  have hunit : IsUnit (Polynomial.aeval x q) := by
    rw [isUnit_conv_iff, ← constantCoeffConv_apply, constantCoeffConv_aeval q hx]
    exact hq
  rw [hpq, map_mul, map_pow, map_sub, Polynomial.aeval_X, Polynomial.aeval_C, map_zero, sub_zero,
    Ideal.mul_unit_mem_iff_mem I hunit] at hmem
  exact Ideal.mem_radical_iff.mpr ⟨_, hmem⟩

/-- The base coordinates lie in the maximal ideal. -/
theorem span_algEquiv_convX_le_maximalIdeal (σ : Conv K n ≃ₐ[K] Conv K n) (e : Fin d ↪ Fin n) :
    Ideal.span (Set.range fun j => σ (convX K (e j))) ≤ maximalIdeal (Conv K n) := by
  rw [Ideal.span_le]
  rintro _ ⟨j, rfl⟩
  rw [SetLike.mem_coe, mem_maximalIdeal_algEquiv_iff, mem_maximalIdeal_conv_iff, coe_convX,
    constantCoeff_X]

/-- The maximal ideal lies in the radical of `I ⊔ (σ X (e j))_j` when every fibre coordinate
satisfies a monic relation with constant coefficients modulo that ideal. -/
theorem maximalIdeal_le_radical_sup_of_parameters (I : Ideal (Conv K n))
    (σ : Conv K n ≃ₐ[K] Conv K n) (e : Fin d ↪ Fin n)
    (hrel : ∀ i, i ∉ Set.range e → ∃ p : Polynomial K, p.Monic ∧
      Polynomial.aeval (σ (convX K i)) p ∈ I ⊔ Ideal.span (Set.range fun j => σ (convX K (e j)))) :
    maximalIdeal (Conv K n) ≤ (I ⊔ Ideal.span (Set.range fun j => σ (convX K (e j)))).radical := by
  rw [maximalIdeal_conv_eq_span_algEquiv_convX σ, Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  by_cases hi : i ∈ Set.range e
  · obtain ⟨j, rfl⟩ := hi
    exact Ideal.le_radical (Ideal.mem_sup_right (Ideal.subset_span ⟨j, rfl⟩))
  · obtain ⟨p, hp, hmem⟩ := hrel i hi
    refine mem_radical_of_monic_aeval_mem ?_ hp hmem
    rw [mem_maximalIdeal_algEquiv_iff, mem_maximalIdeal_conv_iff, coe_convX, constantCoeff_X]

/-- Krull's height theorem in the germ ring: if for every coordinate `X i` outside the base
coordinates `X (e j)` a monic polynomial with constant coefficients in `σ (X i)` lies in
`I ⊔ (σ X (e j))_j`, then `dim (𝒪_n / I) ≤ d`, the `d` base coordinates being a system of
parameters of `𝒪_n / I` [Fre17, Ch. VII, 5.6]. The general form for any Noetherian local ring
(`𝔪 ≤ √(I ⊔ (s₁, …, s_d))` gives `dim R/I ≤ d`) is
`IsLocalRing.ringKrullDim_quotient_le_of_maximalIdeal_le_radical_sup`. -/
theorem ringKrullDim_quotient_le_of_parameters (I : Ideal (Conv K n))
    (σ : Conv K n ≃ₐ[K] Conv K n) (e : Fin d ↪ Fin n)
    (hrel : ∀ i, i ∉ Set.range e → ∃ p : Polynomial K, p.Monic ∧
      Polynomial.aeval (σ (convX K i)) p ∈ I ⊔ Ideal.span (Set.range fun j => σ (convX K (e j)))) :
    ringKrullDim (Conv K n ⧸ I) ≤ (d : WithBot ℕ∞) :=
  ringKrullDim_quotient_le_of_maximalIdeal_le_radical_sup I
    (fun j => σ (convX K (e j)))
    (fun j => by rw [mem_maximalIdeal_algEquiv_iff, mem_maximalIdeal_conv_iff, coe_convX,
      constantCoeff_X])
    (maximalIdeal_le_radical_sup_of_parameters I σ e hrel)

/-- The relation `(x + a)^D + ∑_{k<D} c_k (x + a)^k ∈ J` with constant coefficients `c_k` is a monic
polynomial relation in `x` (the shape produced at a point near a Noether normalization). -/
theorem exists_monic_aeval_mem_of_pow_add_sum {J : Ideal (Conv K n)} {x : Conv K n} {D : ℕ}
    (c : Fin D → K) (a : K)
    (hmem : (x + algebraMap K (Conv K n) a) ^ D + ∑ k : Fin D,
      algebraMap K (Conv K n) (c k) * (x + algebraMap K (Conv K n) a) ^ (k : ℕ) ∈ J) :
    ∃ p : Polynomial K, p.Monic ∧ Polynomial.aeval x p ∈ J := by
  refine ⟨(Polynomial.X ^ D + ∑ k : Fin D, Polynomial.C (c k) * Polynomial.X ^ (k : ℕ)).comp
    (Polynomial.X + Polynomial.C a), ?_, ?_⟩
  · refine (Polynomial.monic_X_pow_add (Polynomial.degree_sum_fin_lt c)).comp
      (Polynomial.monic_X_add_C a) ?_
    rw [Polynomial.natDegree_X_add_C]
    exact one_ne_zero
  · rw [Polynomial.aeval_comp]
    simpa [map_add, map_sum, map_mul, map_pow, Polynomial.aeval_X, Polynomial.aeval_C] using hmem

end Analytic
