/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Analytic.Rueckert.Specialize
public import Hironaka.Analytic.Rueckert.ZeroSet
public import Hironaka.Analytic.Weierstrass.Exponents
public import Mathlib.Analysis.Complex.Basic
import Hironaka.Analytic.ConvSeries.Mul
import Hironaka.Analytic.Germ.CoordDiv
import Hironaka.Analytic.Rueckert.Hypersurface
import Hironaka.Analytic.Rueckert.Quotient
import Hironaka.Analytic.Rueckert.Slices
import Hironaka.Analytic.Rueckert.Subst
import Mathlib.Analysis.Complex.Polynomial.Basic

/-!
# Points of `V(P)` over the generic points of `V(P ∩ 𝒪_m)`

The parametrization lemma used in the second alternative of Rückert's Nullstellensatz
(`Nullstellensatz.lean`), in place of [Fre17, Ch. I, 7.3–7.4 and 8.2]. What the proof of the
Nullstellensatz uses of the second alternative is only this: for a prime `P ⊆ 𝒪_{m+1}`
containing the series of a Weierstrass polynomial in `x_0`, with `𝔭 = P ∩ 𝒪_m`, over every point
`y ∈ V(𝔭)` near `0` off the zero set of a fixed `A ∉ 𝔭` there is a point `(t, y) ∈ V(P)` with `t`
as small as prescribed (`exists_eventually_exists_cons_mem_zeroSet`).

The argument. Reduce the finitely many generators of `P` modulo the Weierstrass series to
polynomials `B ∈ 𝒪_m[x_0]` whose series lie in `P` (Weierstrass division,
`exists_division_conv`); let `𝔅` be the family of these remainders together with the Weierstrass
polynomial. Over the domain `R̄ = 𝒪_m/𝔭` and its fraction field `K'`, the ideal of `K'[T]`
generated by the classes of `𝔅` is principal (`K'[T]` is a principal ideal domain); its generator
`g` is nonzero (the Weierstrass polynomial is monic) and not a unit: a nonzero constant in the
ideal would, after clearing denominators (`exists_C_mul_eq_map_of_mem_span_image`), give a
nonzero element of `R̄` in the ideal generated by `𝔅` in `R̄[T]`, hence an element of `𝒪_m ∖ 𝔭` in
`P` (the mechanism "`P_0 ∈ 𝒫 ∩ 𝒪_{n−1} = 𝔭`" of [Fre17, Ch. I, 8.3],
`convPolyEval_mem_of_coeff_mem`). Clearing denominators (`IsLocalization.integerNormalization`)
gives `ω ∈ R̄[T]` of positive degree with `C c_B · B̄ = ω · H_B` for every `B ∈ 𝔅`
(`exists_common_factor_of_span`); lifted to `𝒪_m[T]`, these identities hold modulo `𝔭[T]`, so
they specialize exactly at the points of `V(𝔭)` near `0`
(`eventually_specialize_eq_zero_of_coeff_mem`). Put `A = lead(ω) · ∏ c_B ∉ 𝔭`. At `y ∈ V(𝔭)` with
`A(y) ≠ 0` the specialized `ω(y, ·)` has positive degree and a root `t` (`ℂ` is algebraically
closed), which is a root of every `B(y, ·)`, in particular of the Weierstrass polynomial, so `t`
is small (`eventually_forall_root_norm_lt`), and `(t, y)` is a common zero of the generators of
`P`.
-/

public section

open Polynomial

namespace Analytic

section Abstract

variable {R : Type*} [CommRing R] [IsDomain R]

omit [IsDomain R] in
/-- The action of `R` on polynomials over the fraction field is multiplication by the constant. -/
theorem smul_eq_C_algebraMap_mul (b : R) (c : (FractionRing R)[X]) :
    b • c = C (algebraMap R (FractionRing R) b) * c := by
  rw [← algebraMap_smul (FractionRing R) b c, Polynomial.smul_eq_C_mul]

/-- Every element of the ideal generated by the images of a finite family of polynomials over `R` in
`K[T]` (`K` the fraction field) becomes, after clearing a denominator, the image of an element of
the ideal generated by the family in `R[T]`. -/
theorem exists_C_mul_eq_map_of_mem_span_image (𝔅 : Finset R[X]) {z : (FractionRing R)[X]}
    (hz : z ∈ Ideal.span ((𝔅 : Set R[X]).image (map (algebraMap R (FractionRing R))))) :
    ∃ r : R, r ≠ 0 ∧ ∃ q ∈ Ideal.span (𝔅 : Set R[X]),
      C (algebraMap R (FractionRing R) r) * z = map (algebraMap R (FractionRing R)) q := by
  refine Submodule.span_induction (p := fun z _ => ∃ r : R, r ≠ 0 ∧ ∃ q ∈ Ideal.span (𝔅 : Set R[X]),
    C (algebraMap R (FractionRing R) r) * z = map (algebraMap R (FractionRing R)) q) ?_ ?_ ?_ ?_ hz
  · rintro _ ⟨B, hB, rfl⟩
    exact ⟨1, one_ne_zero, B, Ideal.subset_span hB, by rw [map_one, C_1, one_mul]⟩
  · exact ⟨1, one_ne_zero, 0, Ideal.zero_mem _, by rw [mul_zero, Polynomial.map_zero]⟩
  · rintro z₁ z₂ - - ⟨r₁, hr₁, q₁, hq₁, h₁⟩ ⟨r₂, hr₂, q₂, hq₂, h₂⟩
    refine ⟨r₁ * r₂, mul_ne_zero hr₁ hr₂, C r₂ * q₁ + C r₁ * q₂,
      Ideal.add_mem _ (Ideal.mul_mem_left _ _ hq₁) (Ideal.mul_mem_left _ _ hq₂), ?_⟩
    rw [Polynomial.map_add, Polynomial.map_mul, Polynomial.map_mul, map_C, map_C, ← h₁, ← h₂,
      map_mul, C_mul]
    ring
  · rintro c z - ⟨r, hr, q, hq, h⟩
    obtain ⟨b, hb, hbc⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors R) c
    refine ⟨b * r, mul_ne_zero (nonZeroDivisors.ne_zero hb) hr,
      IsLocalization.integerNormalization (nonZeroDivisors R) c * q, Ideal.mul_mem_left _ _ hq, ?_⟩
    rw [smul_eq_mul, Polynomial.map_mul, hbc, ← h, smul_eq_C_algebraMap_mul, map_mul, C_mul]
    ring

/-- The algebraic core of the parametrization: a finite family `𝔅` of polynomials over the domain
`R`, containing a nonzero polynomial and generating an ideal of `R[T]` without nonzero constants,
has a common "root polynomial" `ω ∈ R[T]` of positive degree: every `B ∈ 𝔅` satisfies
`C c * B = ω * H` for some `c ≠ 0` and `H`. -/
theorem exists_common_factor_of_span (𝔅 : Finset R[X]) (hne : ∃ W ∈ 𝔅, W ≠ 0)
    (hprop : ∀ r : R, C r ∈ Ideal.span (𝔅 : Set R[X]) → r = 0) :
    ∃ ω : R[X], 0 < ω.natDegree ∧
      ∀ B ∈ 𝔅, ∃ c : R, c ≠ 0 ∧ ∃ H : R[X], C c * B = ω * H := by
  classical
  set φ := algebraMap R (FractionRing R) with hφ
  have hinj : Function.Injective (map φ) := map_injective φ (IsFractionRing.injective R _)
  set J : Ideal (FractionRing R)[X] := Ideal.span ((𝔅 : Set R[X]).image (map φ)) with hJ
  obtain ⟨g, hg⟩ := (IsPrincipalIdealRing.principal J).principal
  -- `g ≠ 0`
  have hg0 : g ≠ 0 := by
    rintro rfl
    obtain ⟨W, hW, hW0⟩ := hne
    have : map φ W ∈ J := Ideal.subset_span ⟨W, hW, rfl⟩
    rw [hg, Submodule.span_singleton_eq_bot.mpr rfl, Submodule.mem_bot] at this
    exact hW0 (hinj (by rw [this, Polynomial.map_zero]))
  -- `g` is not a unit: otherwise `1 ∈ J`, and clearing denominators gives a nonzero constant in
  -- the span of `𝔅`
  have hgu : ¬ IsUnit g := by
    intro hu
    have h1 : (1 : (FractionRing R)[X]) ∈ J := by
      rw [hg]
      exact Ideal.mem_span_singleton.mpr hu.dvd
    obtain ⟨r, hr, q, hq, hrq⟩ := exists_C_mul_eq_map_of_mem_span_image 𝔅 h1
    rw [mul_one, ← map_C] at hrq
    exact hr (hprop r (hinj hrq ▸ hq))
  have hdeg : 0 < g.degree := degree_pos_of_ne_zero_of_nonunit hg0 hgu
  -- clear the denominators of `g`
  obtain ⟨a, ha, hag⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors R) g
  refine ⟨IsLocalization.integerNormalization (nonZeroDivisors R) g, ?_, fun B hB => ?_⟩
  · have ha0 : φ a ≠ 0 :=
      (map_ne_zero_iff φ (IsFractionRing.injective R (FractionRing R))).mpr
        (nonZeroDivisors.ne_zero ha)
    rw [← natDegree_map_eq_of_injective (IsFractionRing.injective R (FractionRing R)), hag,
      smul_eq_C_algebraMap_mul, natDegree_C_mul ha0, natDegree_pos_iff_degree_pos]
    exact hdeg
  · have hBJ : map φ B ∈ J := Ideal.subset_span ⟨B, hB, rfl⟩
    rw [hg, Ideal.mem_span_singleton] at hBJ
    obtain ⟨h, hh⟩ := hBJ
    obtain ⟨b, hb, hbh⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors R) h
    refine ⟨a * b, mul_ne_zero (nonZeroDivisors.ne_zero ha) (nonZeroDivisors.ne_zero hb),
      IsLocalization.integerNormalization (nonZeroDivisors R) h, hinj ?_⟩
    rw [Polynomial.map_mul, map_C, Polynomial.map_mul, hag, hbh, hh, map_mul, C_mul,
      smul_eq_C_algebraMap_mul, smul_eq_C_algebraMap_mul]
    ring

end Abstract

section Analytic

open Filter Topology

variable {K : Type*} [RCLike K] {m n : ℕ}

/-- Near `0`, the value of a finite product of convergent series is the product of the values. -/
theorem evalSeries_finsetProd_eventually {ι : Type*} (s : Finset ι) (F : ι → Conv K n) :
    evalSeries (∏ i ∈ s, (F i : MvPowerSeries (Fin n) K)) =ᶠ[𝓝 (0 : Fin n → K)]
      fun x => ∏ i ∈ s, evalSeries (F i : MvPowerSeries (Fin n) K) x := by
  classical
  induction s using Finset.induction_on with
  | empty => exact Eventually.of_forall fun x => by simp [evalSeries_one]
  | insert a s ha ih =>
    rw [Finset.prod_insert ha]
    have hmem : (∏ i ∈ s, (F i : MvPowerSeries (Fin n) K)) ∈ Conv K n :=
      Subalgebra.prod_mem _ fun i _ => (F i).2
    filter_upwards [ih, evalSeries_mul_eventually (F a).2 hmem] with x ih h
    rw [h, ih, Finset.prod_insert ha]

/-- A polynomial over `𝒪_m` whose coefficients lie in `P ∩ 𝒪_m` has its series in `P`. -/
theorem convPolyEval_mem_of_coeff_mem {P : Ideal (Conv K (m + 1))} {Q : Polynomial (Conv K m)}
    (hQ : ∀ i, Q.coeff i ∈ P.comap (convTail K).toRingHom) : convPolyEval K Q ∈ P := by
  change Q.eval₂ (convTail K).toRingHom (convX K 0) ∈ P
  rw [eval₂_eq_sum_range]
  exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_right _ _ (Ideal.mem_comap.mp (hQ i))

/-- Near `0`, a polynomial with coefficients in `p` specializes to `0` at the points of `V(p)`. -/
theorem eventually_specialize_eq_zero_of_coeff_mem {p : Ideal (Conv K m)} {Sp : Finset (Conv K m)}
    (hSp : Ideal.span (Sp : Set (Conv K m)) = p) {D : Polynomial (Conv K m)}
    (hD : ∀ i, D.coeff i ∈ p) :
    ∀ᶠ y in 𝓝 (0 : Fin m → K), y ∈ zeroSet Sp → specialize D y = 0 := by
  have hv : ∀ i ∈ Finset.range (D.natDegree + 1), VanishesOn Sp (D.coeff i) := fun i _ =>
    (mem_vanishingIdeal_iff hSp).mp (le_vanishingIdeal p (hD i))
  filter_upwards [(eventually_all_finset _).mpr hv] with y hy hyS
  ext k
  rw [coeff_specialize, coeff_zero]
  by_cases hk : k ∈ Finset.range (D.natDegree + 1)
  · exact hy k hk hyS
  · rw [coeff_eq_zero_of_natDegree_lt (by simpa using hk), Subalgebra.coe_zero, evalSeries_zero]

/-- Weierstrass division with the remainder as the series of a polynomial. -/
theorem exists_eq_mul_add_convPolyEval {W : Conv K (m + 1)} {d : ℕ}
    (hreg : IsRegularIn (W : MvPowerSeries (Fin (m + 1)) K) d) (G : Conv K (m + 1)) :
    ∃ (q : Conv K (m + 1)) (B : Polynomial (Conv K m)), G = q * W + convPolyEval K B := by
  obtain ⟨q, r, hrd, hG⟩ := exists_division_conv (f := G) hreg
  refine ⟨q, ∑ j : Fin d, C (sliceConv r (d - 1 - j)) * X ^ (d - 1 - (j : ℕ)), ?_⟩
  rw [hG, map_sum]
  congr 1
  conv_lhs => rw [eq_sum_convTail_sliceConv hrd]
  refine Finset.sum_congr rfl fun j _ => ?_
  rw [map_mul, map_pow, convPolyEval_C, convPolyEval_X]

/-- The parametrization lemma (in place of [Fre17, Ch. I, 7.4 and 8.2]): for a prime `P ⊆ 𝒪_{m+1}`
containing the series of a Weierstrass polynomial in `x_0`, with `p = P ∩ 𝒪_m`, there is `A ∉ p`
such that over every point `y ∈ V(p)` near `0` with `A(y) ≠ 0` there is a point `(t, y) ∈ V(P)`
with `t` as small as prescribed. -/
theorem exists_eventually_exists_cons_mem_zeroSet {P : Ideal (Conv ℂ (m + 1))} [hP : P.IsPrime]
    {d : ℕ} {c : Fin d → Conv ℂ m}
    (hc : ∀ j, MvPowerSeries.constantCoeff (c j : MvPowerSeries (Fin m) ℂ) = 0)
    (hW : convPolyEval ℂ (weierstrassPolynomial d c) ∈ P)
    {S : Finset (Conv ℂ (m + 1))} (hS : Ideal.span (S : Set (Conv ℂ (m + 1))) = P)
    {Sp : Finset (Conv ℂ m)}
    (hSp : Ideal.span (Sp : Set (Conv ℂ m)) = P.comap (convTail ℂ).toRingHom)
    {δ : ℝ} (hδ : 0 < δ) :
    ∃ A : Conv ℂ m, A ∉ P.comap (convTail ℂ).toRingHom ∧
      ∀ᶠ y in 𝓝 (0 : Fin m → ℂ), y ∈ zeroSet Sp →
        evalSeries (A : MvPowerSeries (Fin m) ℂ) y ≠ 0 →
          ∃ t : ℂ, ‖t‖ < δ ∧ Fin.cons t y ∈ zeroSet S := by
  classical
  obtain ⟨p, hpdef⟩ : ∃ p : Ideal (Conv ℂ m), p = P.comap (convTail ℂ).toRingHom := ⟨_, rfl⟩
  rw [← hpdef] at hSp ⊢
  have hp : p.IsPrime := by rw [hpdef]; exact Ideal.comap_isPrime _ _
  have : IsDomain (Conv ℂ m ⧸ p) := Ideal.Quotient.isDomain p
  have : Nontrivial (Conv ℂ m ⧸ p) := Ideal.Quotient.nontrivial_iff.mpr hp.ne_top
  obtain ⟨π, hπ⟩ : ∃ π : Conv ℂ m →+* Conv ℂ m ⧸ p, π = Ideal.Quotient.mk p := ⟨_, rfl⟩
  have hπsurj : Function.Surjective π := by rw [hπ]; exact Ideal.Quotient.mk_surjective
  have hπker : ∀ a, π a = 0 ↔ a ∈ p := fun a => by rw [hπ]; exact Ideal.Quotient.eq_zero_iff_mem
  obtain ⟨Wp, hWp⟩ : ∃ Wp : Polynomial (Conv ℂ m), Wp = weierstrassPolynomial d c := ⟨_, rfl⟩
  rw [← hWp] at hW
  have hWmonic : Wp.Monic := by rw [hWp]; exact monic_weierstrassPolynomial d c
  have hd : 0 < d := by
    rcases Nat.eq_zero_or_pos d with h0 | h
    · exfalso
      have h1 : Wp = 1 := eq_one_of_monic_natDegree_zero hWmonic
        (by rw [hWp, natDegree_weierstrassPolynomial, h0])
      rw [h1, map_one] at hW
      exact hP.ne_top ((Ideal.eq_top_iff_one _).mpr hW)
    · exact h
  have hreg : IsRegularIn (convPolyEval ℂ Wp : MvPowerSeries (Fin (m + 1)) ℂ) d := by
    rw [hWp]; exact isRegularIn_convPolyEval_weierstrassPolynomial hc
  -- remainders of the generators modulo the Weierstrass series
  choose qf Bf hqB using fun G : Conv ℂ (m + 1) => exists_eq_mul_add_convPolyEval hreg G
  obtain ⟨𝔅, h𝔅⟩ : ∃ 𝔅 : Finset (Polynomial (Conv ℂ m)), 𝔅 = insert Wp (S.image Bf) := ⟨_, rfl⟩
  have hWp𝔅 : Wp ∈ 𝔅 := by rw [h𝔅]; exact Finset.mem_insert_self _ _
  have hBf𝔅 : ∀ G ∈ S, Bf G ∈ 𝔅 := fun G hG => by
    rw [h𝔅]; exact Finset.mem_insert_of_mem (Finset.mem_image_of_mem _ hG)
  have h𝔅P : ∀ B ∈ 𝔅, convPolyEval ℂ B ∈ P := by
    intro B hB
    rw [h𝔅, Finset.mem_insert, Finset.mem_image] at hB
    rcases hB with rfl | ⟨G, hG, rfl⟩
    · exact hW
    · have hGP : G ∈ P := hS ▸ Ideal.subset_span hG
      have h2 : convPolyEval ℂ (Bf G) = G - qf G * convPolyEval ℂ Wp :=
        eq_sub_of_add_eq' (hqB G).symm
      rw [h2]
      exact P.sub_mem hGP (P.mul_mem_left _ hW)
  -- the abstract lemma over `𝒪_m / p`
  obtain ⟨𝔅', h𝔅'⟩ : ∃ 𝔅' : Finset (Polynomial (Conv ℂ m ⧸ p)), 𝔅' = 𝔅.image (Polynomial.map π) :=
    ⟨_, rfl⟩
  have hne : ∃ W' ∈ 𝔅', W' ≠ 0 :=
    ⟨Wp.map π, by rw [h𝔅']; exact Finset.mem_image_of_mem _ hWp𝔅, (hWmonic.map π).ne_zero⟩
  have hprop : ∀ r : Conv ℂ m ⧸ p,
      C r ∈ Ideal.span (𝔅' : Set (Polynomial (Conv ℂ m ⧸ p))) → r = 0 := by
    intro r hr
    obtain ⟨r', rfl⟩ := hπsurj r
    rw [h𝔅', Finset.coe_image, ← coe_mapRingHom, ← Ideal.map_span,
      Ideal.mem_map_iff_of_surjective _ (map_surjective π hπsurj)] at hr
    obtain ⟨q, hq, hqr⟩ := hr
    have hcoef : ∀ i, (q - C r').coeff i ∈ p := by
      intro i
      have : ((q - C r').map π).coeff i = 0 := by
        rw [Polynomial.map_sub, map_C, ← coe_mapRingHom, hqr, sub_self, coeff_zero]
      rwa [coeff_map, hπker] at this
    have h1 : convPolyEval ℂ (q - C r') ∈ P :=
      convPolyEval_mem_of_coeff_mem fun i => by rw [← hpdef]; exact hcoef i
    have h2 : convPolyEval ℂ q ∈ P := by
      have : Ideal.span (𝔅 : Set (Polynomial (Conv ℂ m))) ≤ P.comap (convPolyEval ℂ) :=
        Ideal.span_le.mpr fun B hB => h𝔅P B hB
      exact this hq
    have h3 : convTail ℂ r' ∈ P := by
      have h4 : convPolyEval ℂ (C r') ∈ P := by
        have h6 := P.sub_mem h2 h1
        have h7 : convPolyEval ℂ q - convPolyEval ℂ (q - C r') = convPolyEval ℂ (C r') := by
          rw [show convPolyEval ℂ (q - C r') = convPolyEval ℂ q - convPolyEval ℂ (C r') from
            Polynomial.eval₂_sub _, sub_sub_cancel]
        rwa [h7] at h6
      rwa [convPolyEval_C] at h4
    exact (hπker r').mpr (by rw [hpdef]; exact h3)
  obtain ⟨ω', hω'deg, hω'⟩ := exists_common_factor_of_span (R := Conv ℂ m ⧸ p) 𝔅' hne hprop
  obtain ⟨ω, hω⟩ := map_surjective π hπsurj ω'
  have hω'0 : ω' ≠ 0 := ne_zero_of_natDegree_gt hω'deg
  obtain ⟨ℓ, hℓdef⟩ : ∃ ℓ : Conv ℂ m, ℓ = ω.coeff ω'.natDegree := ⟨_, rfl⟩
  have hℓ : ℓ ∉ p := by
    intro h
    have h1 : π ℓ = ω'.leadingCoeff := by rw [hℓdef, ← coeff_map, hω, leadingCoeff]
    rw [(hπker ℓ).mpr h] at h1
    exact leadingCoeff_ne_zero.mpr hω'0 h1.symm
  have hrel : ∀ B ∈ 𝔅, ∃ (cB : Conv ℂ m) (H : Polynomial (Conv ℂ m)), cB ∉ p ∧
      ∀ i, (C cB * B - ω * H).coeff i ∈ p := by
    intro B hB
    obtain ⟨c', hc', H', hH'⟩ := hω' (B.map π) (by rw [h𝔅']; exact Finset.mem_image_of_mem _ hB)
    obtain ⟨cB, rfl⟩ := hπsurj c'
    obtain ⟨H, rfl⟩ := map_surjective π hπsurj H'
    refine ⟨cB, H, fun h => hc' ((hπker cB).mpr h), fun i => ?_⟩
    have : ((C cB * B - ω * H).map π).coeff i = 0 := by
      rw [Polynomial.map_sub, Polynomial.map_mul, Polynomial.map_mul, map_C, hω, hH', sub_self,
        coeff_zero]
    rwa [coeff_map, hπker] at this
  choose! cf Hf hcf using hrel
  refine ⟨ℓ * ∏ B ∈ 𝔅, cf B, ?_, ?_⟩
  · intro h
    rcases hp.mem_or_mem h with h | h
    · exact hℓ h
    · rw [Finset.prod_eq_multiset_prod, hp.multiset_prod_mem_iff_exists_mem] at h
      obtain ⟨x, hx, hxp⟩ := h
      obtain ⟨B, hB, rfl⟩ := Multiset.mem_map.mp hx
      exact (hcf B (Multiset.mem_toFinset.mp (by simpa using hB))).1 hxp
  -- the analytic part
  have hball : ∀ᶠ z in 𝓝 (0 : Fin (m + 1) → ℂ),
      (∀ B ∈ 𝔅, evalSeries (convPolyEval ℂ B : MvPowerSeries (Fin (m + 1)) ℂ) z =
        (specialize B (Fin.tail z)).eval (z 0)) ∧
      ∀ G ∈ S, evalSeries (G : MvPowerSeries (Fin (m + 1)) ℂ) z =
        evalSeries (qf G : MvPowerSeries (Fin (m + 1)) ℂ) z *
          evalSeries (convPolyEval ℂ Wp : MvPowerSeries (Fin (m + 1)) ℂ) z +
        evalSeries (convPolyEval ℂ (Bf G) : MvPowerSeries (Fin (m + 1)) ℂ) z := by
    refine ((eventually_all_finset 𝔅).mpr fun B _ =>
      evalSeries_convPolyEval_eq_eval_specialize B).and
      ((eventually_all_finset S).mpr fun G _ => ?_)
    filter_upwards [evalSeries_add_eventually (qf G * convPolyEval ℂ Wp).2
      (convPolyEval ℂ (Bf G)).2, evalSeries_mul_eventually (qf G).2 (convPolyEval ℂ Wp).2]
      with z h1 h2
    have hG := hqB G
    calc evalSeries (G : MvPowerSeries (Fin (m + 1)) ℂ) z
        = evalSeries ((qf G * convPolyEval ℂ Wp + convPolyEval ℂ (Bf G) : Conv ℂ (m + 1)) :
            MvPowerSeries (Fin (m + 1)) ℂ) z := by rw [← hG]
      _ = _ := by rw [Subalgebra.coe_add, h1, Subalgebra.coe_mul, h2]
  obtain ⟨δ₀, hδ₀, hball'⟩ := Metric.eventually_nhds_iff.mp hball
  have hδ₀2 : 0 < δ₀ / 2 := by positivity
  obtain ⟨ε, hε, hε1, hεδ, hεδ₀⟩ : ∃ ε : ℝ, 0 < ε ∧ ε ≤ 1 ∧ ε ≤ δ ∧ ε ≤ δ₀ / 2 :=
    ⟨min (min δ (δ₀ / 2)) 1, lt_min (lt_min hδ hδ₀2) one_pos, min_le_right _ _,
      (min_le_left _ _).trans (min_le_left _ _), (min_le_left _ _).trans (min_le_right _ _)⟩
  have hroots := eventually_forall_root_norm_lt hc hε hε1
  rw [← hWp] at hroots
  have hspec : ∀ᶠ y in 𝓝 (0 : Fin m → ℂ), ∀ B ∈ 𝔅,
      (y ∈ zeroSet Sp → specialize (C (cf B) * B - ω * Hf B) y = 0) ∧
      specialize (C (cf B) * B) y =
        C (evalSeries (cf B : MvPowerSeries (Fin m) ℂ) y) * specialize B y ∧
      specialize (ω * Hf B + (C (cf B) * B - ω * Hf B)) y =
        specialize ω y * specialize (Hf B) y + specialize (C (cf B) * B - ω * Hf B) y := by
    refine (eventually_all_finset 𝔅).mpr fun B hB => ?_
    filter_upwards [eventually_specialize_eq_zero_of_coeff_mem hSp (hcf B hB).2,
      specialize_mul_eventually (C (cf B)) B,
      specialize_add_eventually (ω * Hf B) (C (cf B) * B - ω * Hf B),
      specialize_mul_eventually ω (Hf B)] with y h1 h2 h3 h4
    exact ⟨h1, by rw [h2, specialize_C], by rw [h3, h4]⟩
  have hAeval := evalSeries_mul_eventually ℓ.2 (∏ B ∈ 𝔅, cf B).2
  have hprod := evalSeries_finsetProd_eventually 𝔅 cf
  filter_upwards [hroots, hspec, hAeval, hprod,
    Metric.eventually_nhds_iff.mpr ⟨δ₀ / 2, hδ₀2, fun y hy => hy⟩]
    with y hroots hspec hAeval hprod hyδ hySp hAy
  rw [Subalgebra.coe_mul, hAeval, SubmonoidClass.coe_finsetProd, hprod] at hAy
  have hℓy : evalSeries (ℓ : MvPowerSeries (Fin m) ℂ) y ≠ 0 := left_ne_zero_of_mul hAy
  have hcfy : ∀ B ∈ 𝔅, evalSeries (cf B : MvPowerSeries (Fin m) ℂ) y ≠ 0 := fun B hB =>
    Finset.prod_ne_zero_iff.mp (right_ne_zero_of_mul hAy) B hB
  have hωdeg : (specialize ω y).degree ≠ 0 := by
    have h1 : (specialize ω y).coeff ω'.natDegree ≠ 0 := by
      rw [coeff_specialize, ← hℓdef]; exact hℓy
    have h2 := le_degree_of_ne_zero h1
    intro h0
    rw [h0] at h2
    exact hω'deg.ne' (Nat.le_zero.mp (by exact_mod_cast h2))
  obtain ⟨t, ht⟩ := IsAlgClosed.exists_root (specialize ω y) hωdeg
  rw [IsRoot.def] at ht
  have hBt : ∀ B ∈ 𝔅, (specialize B y).eval t = 0 := by
    intro B hB
    obtain ⟨h1, h2, h3⟩ := hspec B hB
    have hrel : specialize (C (cf B) * B) y =
        specialize (ω * Hf B + (C (cf B) * B - ω * Hf B)) y := by
      congr 1
      ring
    rw [h2, h3, h1 hySp, add_zero] at hrel
    have := congrArg (Polynomial.eval t) hrel
    rw [eval_mul, eval_C, eval_mul, ht, zero_mul] at this
    exact (mul_eq_zero.mp this).resolve_left (hcfy B hB)
  have htε : ‖t‖ < ε := hroots t (hBt Wp hWp𝔅)
  obtain ⟨z, hz⟩ : ∃ z : Fin (m + 1) → ℂ, z = Fin.cons t y := ⟨_, rfl⟩
  have hzball : dist z 0 < δ₀ := by
    rw [dist_zero_right, pi_norm_lt_iff hδ₀]
    intro i
    refine Fin.cases ?_ (fun j => ?_) i
    · rw [hz, Fin.cons_zero]
      exact htε.trans_le (hεδ₀.trans (by linarith))
    · rw [hz, Fin.cons_succ]
      have hy' : ‖y‖ < δ₀ / 2 := by rwa [dist_zero_right] at hyδ
      exact ((pi_norm_lt_iff hδ₀2).mp hy' j).trans (by linarith)
  obtain ⟨hzB, hzG⟩ := hball' hzball
  refine ⟨t, htε.trans_le hεδ, fun G hG => ?_⟩
  rw [← hz, hzG G hG, hzB Wp hWp𝔅, hzB (Bf G) (hBf𝔅 G hG), hz, Fin.tail_cons, Fin.cons_zero,
    hBt Wp hWp𝔅, hBt (Bf G) (hBf𝔅 G hG), mul_zero, add_zero]

end Analytic

end Analytic
