/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Analytic.Rueckert.Basic
import Hironaka.Analytic.Weierstrass.Division
import Hironaka.Analytic.Weierstrass.Poly
import Hironaka.Analytic.Weierstrass.Tail
import Mathlib.Algebra.Order.Algebra
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

/-!
# Series of bounded `x_0`-degree as polynomials over the tail ring; division in `Conv K (m+1)`

A series `r` with `coeff ν r = 0` whenever `ν 0 ≥ d` is `∑_{j<d} (x_0-slice j of r) · x_0^j`, the
slices being the coefficients of `splitFirst m r` (convergent when `r` is,
`coeff_splitFirst_mem_conv`); in `Conv K (m+1)` this reads
`r = ∑_j convTail (sliceConv r j) * convX 0 ^ j` (`eq_sum_convTail_sliceConv`). The convergent
Weierstrass division is restated for elements of `Conv K (m+1)` (`exists_division_conv`): for `g`
`x_0`-regular of order `d`, every `f` is `q g + r` with `r` of `x_0`-degree `< d`. These two facts
make `Conv K (m+1) ⧸ (g)` a module generated by `1, x_0, …, x_0^{d-1}` over `Conv K m`, the step
of Rückert's basis theorem (`Noetherian.lean`) [GR65, Chapter II, §B].

The coefficient field `K` is `ℝ` or `ℂ` (`[RCLike K]`).
-/

@[expose] public section

open MvPowerSeries

namespace Analytic

variable {K : Type*} [RCLike K]

variable {m : ℕ}

/-- A series of `x_0`-degree `< d` is the sum of its `x_0`-slices times powers of `x_0`. -/
theorem eq_sum_liftTail_coeff_splitFirst {r : MvPowerSeries (Fin (m + 1)) K} {d : ℕ}
    (hr : ∀ ν : Fin (m + 1) →₀ ℕ, d ≤ ν 0 → coeff ν r = 0) :
    r = ∑ j : Fin d, liftTail (PowerSeries.coeff (d - 1 - j) (splitFirst K m r)) *
      X 0 ^ (d - 1 - (j : ℕ)) := by
  apply (splitFirst K m).injective
  rw [map_sum]
  simp only [splitFirst_liftTail_mul_X_pow]
  exact (splitFirst_eq_trunc hr).trans (coe_trunc_eq_sum _ d)

/-- The `x_0`-slices of a convergent series, as elements of `Conv K m`
(`coeff_splitFirst_mem_conv`). -/
noncomputable def sliceConv (r : Conv K (m + 1)) (k : ℕ) : Conv K m :=
  ⟨PowerSeries.coeff k (splitFirst K m (r : MvPowerSeries (Fin (m + 1)) K)),
    coeff_splitFirst_mem_conv r.2 k⟩

@[simp] theorem coe_sliceConv (r : Conv K (m + 1)) (k : ℕ) :
    (sliceConv r k : MvPowerSeries (Fin m) K) =
      PowerSeries.coeff k (splitFirst K m (r : MvPowerSeries (Fin (m + 1)) K)) := rfl

/-- In `Conv K (m+1)`, a series of `x_0`-degree `< d` is `∑_j convTail (slice_j) * x_0^j`. -/
theorem eq_sum_convTail_sliceConv {r : Conv K (m + 1)} {d : ℕ}
    (hr : ∀ ν : Fin (m + 1) →₀ ℕ, d ≤ ν 0 → coeff ν (r : MvPowerSeries (Fin (m + 1)) K) = 0) :
    r = ∑ j : Fin d, convTail K (sliceConv r (d - 1 - j)) * convX K 0 ^ (d - 1 - (j : ℕ)) := by
  apply Subtype.ext
  push_cast
  simp only [coe_convTail, coe_sliceConv]
  exact eq_sum_liftTail_coeff_splitFirst hr

/-- The convergent Weierstrass division for elements of `Conv K (m+1)`. -/
theorem exists_division_conv {f g : Conv K (m + 1)} {d : ℕ}
    (hreg : IsRegularIn (g : MvPowerSeries (Fin (m + 1)) K) d) :
    ∃ q r : Conv K (m + 1),
      (∀ ν : Fin (m + 1) →₀ ℕ, d ≤ ν 0 → coeff ν (r : MvPowerSeries (Fin (m + 1)) K) = 0) ∧
      f = q * g + r := by
  obtain ⟨q, r, hq, hr, hdeg, hfq, -⟩ := exists_unique_weierstrassDivision f.2 g.2 hreg
  exact ⟨⟨q, hq⟩, ⟨r, hr⟩, hdeg, Subtype.ext hfq⟩

end Analytic
