/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Analytic.ConvSeries.Eval
import Hironaka.Analytic.ConvSeries.Mul
import Hironaka.Analytic.Germ.CoordDiv
import Hironaka.Analytic.Rueckert.Noetherian
import Hironaka.Analytic.Rueckert.Subst
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Tactic.Positivity.Finset

/-!
# Zero-set germs and vanishing ideals in the germ ring `𝒪_n = Conv K n`

The definitions of Rückert's Nullstellensatz, stated over any `K` with `[RCLike K]`; the theorem
itself (`Nullstellensatz.lean`) is over `ℂ`. Following [Fre17, Ch. I, §8–§9]: an ideal `I ⊆ 𝒪_n` is
finitely generated (Rückert's basis theorem, `isNoetherianRing_conv`); the generators converge on
a common polydisc around `0`, and their common zero set there is the *geometric realization*
`V(I)` of `I`, well defined up to shrinking the neighbourhood; the *vanishing ideal* (Freitag's
*saturation*) of `I` is the ideal of the series vanishing on `V(I)` near `0`.

* `zeroSet S`: the common zero set `{x | ∀ g ∈ S, g(x) = 0}` of a finite family `S` of convergent
  series, as a set of points of `K^n`; only its germ at `0` matters (outside the common polydisc
  of `S` the values `evalSeries g x` are the junk values of a non-summable `tsum`, and every
  statement below is an `∀ᶠ x in 𝓝 0` statement, which sees only a neighbourhood of `0` where the
  finitely many series converge).
* `VanishesOn S f`: `f` vanishes on `V(S)` near `0`: `∀ᶠ x in 𝓝 0, x ∈ zeroSet S → f(x) = 0`.
* `vanishingIdeal I`: the series vanishing on `V(I)` near `0`, quantified over every finite
  system of generators of `I` (`vanishesOn_congr`: two systems of generators of the same ideal
  have the same zero-set germ, so `mem_vanishingIdeal_iff` reads it off any one of them).

The germs on a manifold vanishing on a set near a point (`vanishingStalk`) are the same notion on
the stalks of an analytic manifold; the two are related where the stalks of an analytic space are
identified with convergent series (`Hironaka/AnalyticSpace/Nullstellensatz.lean`), not here.

Elementary consequences (the trivial inclusions of the proof of [Fre17, Ch. I, 9.1]):
`I ≤ I.radical ≤ vanishingIdeal I`, `vanishingIdeal` is monotone (`V` and `𝓘` are both antitone),
`vanishingIdeal ⊤ = ⊤`, and `vanishingIdeal ⊥ = ⊥` by the identity theorem
(`Conv.ext_of_evalSeries_eventuallyEq`).
-/

@[expose] public section

open Filter Topology MvPowerSeries

namespace Analytic

variable {K : Type*} [RCLike K] {n : ℕ}

/-- The common zero set of a finite family `S` of convergent series, as a set of points of `K^n`
(only its germ at `0` is meaningful): the geometric realization of an ideal of
[Fre17, Ch. I, §8]. -/
def zeroSet (S : Finset (Conv K n)) : Set (Fin n → K) :=
  {x | ∀ g ∈ S, evalSeries (g : MvPowerSeries (Fin n) K) x = 0}

@[simp]
theorem mem_zeroSet_iff {S : Finset (Conv K n)} {x : Fin n → K} :
    x ∈ zeroSet S ↔ ∀ g ∈ S, evalSeries (g : MvPowerSeries (Fin n) K) x = 0 := Iff.rfl

/-- The series `f` vanishes on the zero-set germ `V(S)` near `0`. -/
def VanishesOn (S : Finset (Conv K n)) (f : Conv K n) : Prop :=
  ∀ᶠ x in 𝓝 (0 : Fin n → K), x ∈ zeroSet S → evalSeries (f : MvPowerSeries (Fin n) K) x = 0

theorem VanishesOn.zero (S : Finset (Conv K n)) : VanishesOn S (0 : Conv K n) :=
  Eventually.of_forall fun x _ => by rw [Subalgebra.coe_zero, evalSeries_zero]

theorem VanishesOn.add {S : Finset (Conv K n)} {f g : Conv K n} (hf : VanishesOn S f)
    (hg : VanishesOn S g) : VanishesOn S (f + g) := by
  filter_upwards [hf, hg, evalSeries_add_eventually f.2 g.2] with x hf hg h hx
  rw [Subalgebra.coe_add, h, hf hx, hg hx, add_zero]

theorem VanishesOn.mul_left {S : Finset (Conv K n)} (c : Conv K n) {f : Conv K n}
    (hf : VanishesOn S f) : VanishesOn S (c * f) := by
  filter_upwards [hf, evalSeries_mul_eventually c.2 f.2] with x hf h hx
  rw [Subalgebra.coe_mul, h, hf hx, mul_zero]

theorem VanishesOn.of_mem {S : Finset (Conv K n)} {g : Conv K n} (hg : g ∈ S) : VanishesOn S g :=
  Eventually.of_forall fun _ hx => hx g hg

/-- Every element of the ideal generated by `S` vanishes on `V(S)` near `0`. -/
theorem VanishesOn.of_mem_span {S : Finset (Conv K n)} {g : Conv K n}
    (hg : g ∈ Ideal.span (S : Set (Conv K n))) : VanishesOn S g := by
  refine Submodule.span_induction (p := fun g _ => VanishesOn S g) (fun g hg => .of_mem hg)
    (.zero S) (fun _ _ _ _ hf hg => hf.add hg) (fun c _ _ hf => ?_) hg
  rw [smul_eq_mul]
  exact hf.mul_left c

theorem evalSeries_pow_eventually {f : MvPowerSeries (Fin n) K} (hf : f ∈ Conv K n) (k : ℕ) :
    evalSeries (f ^ k) =ᶠ[𝓝 (0 : Fin n → K)] fun x => evalSeries f x ^ k := by
  induction k with
  | zero =>
    exact Eventually.of_forall fun x => by
      change evalSeries (f ^ 0) x = evalSeries f x ^ 0
      rw [pow_zero, pow_zero, evalSeries_one]
  | succ k ih =>
    filter_upwards [ih, evalSeries_mul_eventually (pow_mem hf k) hf] with x ih h
    rw [pow_succ, h, ih, pow_succ]

/-- If a power of `f` vanishes on `V(S)` near `0`, so does `f`. -/
theorem VanishesOn.of_pow {S : Finset (Conv K n)} {f : Conv K n} {k : ℕ}
    (hf : VanishesOn S (f ^ k)) : VanishesOn S f := by
  filter_upwards [hf, evalSeries_pow_eventually f.2 k] with x hf h hx
  have hk := hf hx
  rw [Subalgebra.coe_pow, h] at hk
  rcases Nat.eq_zero_or_pos k with rfl | hk0
  · exact absurd hk (by rw [pow_zero]; exact one_ne_zero)
  · exact (pow_eq_zero_iff hk0.ne').mp hk

/-- If `span S ≤ span S'`, then near `0` the zero set of `S'` lies in the zero set of `S` (two
geometric realizations of the same ideal agree near `0`, [Fre17, Ch. I, §8]). -/
theorem eventually_mem_zeroSet_of_span_le {S S' : Finset (Conv K n)}
    (h : Ideal.span (S : Set (Conv K n)) ≤ Ideal.span (S' : Set (Conv K n))) :
    ∀ᶠ x in 𝓝 (0 : Fin n → K), x ∈ zeroSet S' → x ∈ zeroSet S := by
  have hS : ∀ g ∈ S, VanishesOn S' g := fun g hg =>
    VanishesOn.of_mem_span (h (Ideal.subset_span hg))
  filter_upwards [(eventually_all_finset S).mpr hS] with x hx hx' g hg
  exact hx g hg hx'

theorem vanishesOn_of_span_le {S S' : Finset (Conv K n)}
    (h : Ideal.span (S : Set (Conv K n)) ≤ Ideal.span (S' : Set (Conv K n))) {f : Conv K n}
    (hf : VanishesOn S f) : VanishesOn S' f := by
  filter_upwards [hf, eventually_mem_zeroSet_of_span_le h] with x hf h hx
  exact hf (h hx)

/-- The zero-set germ depends only on the ideal generated: vanishing on `V(S)` near `0` is the
same for two finite systems of generators of the same ideal. -/
theorem vanishesOn_congr {S S' : Finset (Conv K n)}
    (h : Ideal.span (S : Set (Conv K n)) = Ideal.span (S' : Set (Conv K n))) (f : Conv K n) :
    VanishesOn S f ↔ VanishesOn S' f :=
  ⟨vanishesOn_of_span_le h.le, vanishesOn_of_span_le h.ge⟩

/-- The ideal of the series vanishing on the zero-set germ `V(I)` near `0`, read through every
finite system of generators of `I` (they all give the same germ, `vanishesOn_congr`): the
vanishing ideal, Freitag's *saturation* of `I` [Fre17, Ch. I, §9]. -/
def vanishingIdeal (I : Ideal (Conv K n)) : Ideal (Conv K n) where
  carrier := {f | ∀ S : Finset (Conv K n), Ideal.span (S : Set (Conv K n)) = I → VanishesOn S f}
  zero_mem' := fun S _ => VanishesOn.zero S
  add_mem' := fun hf hg S hS => (hf S hS).add (hg S hS)
  smul_mem' := fun c _ hf S hS => by
    rw [smul_eq_mul]
    exact (hf S hS).mul_left c

theorem mem_vanishingIdeal_iff {I : Ideal (Conv K n)} {S : Finset (Conv K n)}
    (hS : Ideal.span (S : Set (Conv K n)) = I) {f : Conv K n} :
    f ∈ vanishingIdeal I ↔ VanishesOn S f :=
  ⟨fun h => h S hS, fun h _S' hS' => (vanishesOn_congr (hS.trans hS'.symm) f).mp h⟩

/-- Rückert's basis theorem (`isNoetherianRing_conv`): every ideal of `𝒪_n` has a finite system of
generators, so every ideal has a zero-set germ. -/
theorem exists_finset_span_eq (I : Ideal (Conv K n)) :
    ∃ S : Finset (Conv K n), Ideal.span (S : Set (Conv K n)) = I :=
  IsNoetherian.noetherian I

/-- `√I ⊆ 𝓘(V(I))` (the trivial inclusion of the proof of [Fre17, Ch. I, 9.1]). -/
theorem radical_le_vanishingIdeal (I : Ideal (Conv K n)) : I.radical ≤ vanishingIdeal I :=
  fun _ hf S hS => by
    obtain ⟨k, hk⟩ := Ideal.mem_radical_iff.mp hf
    rw [← hS] at hk
    exact (VanishesOn.of_mem_span hk).of_pow

/-- `I ⊆ 𝓘(V(I))`. -/
theorem le_vanishingIdeal (I : Ideal (Conv K n)) : I ≤ vanishingIdeal I :=
  Ideal.le_radical.trans (radical_le_vanishingIdeal I)

/-- `V(J) ⊆ V(I)` for `I ≤ J`, so a series vanishing on `V(I)` vanishes on `V(J)`: the vanishing
ideal is monotone. -/
theorem vanishingIdeal_mono {I J : Ideal (Conv K n)} (h : I ≤ J) :
    vanishingIdeal I ≤ vanishingIdeal J := fun f hf S' hS' => by
  obtain ⟨S, hS⟩ := exists_finset_span_eq I
  exact vanishesOn_of_span_le (by rw [hS, hS']; exact h) (hf S hS)

theorem vanishingIdeal_top : vanishingIdeal (⊤ : Ideal (Conv K n)) = ⊤ :=
  top_le_iff.mp (le_vanishingIdeal ⊤)

/-- The identity theorem (`Conv.ext_of_evalSeries_eventuallyEq`): a series vanishing near `0` is
zero, so `𝓘(V(0)) = 0`. -/
theorem vanishingIdeal_bot : vanishingIdeal (⊥ : Ideal (Conv K n)) = ⊥ := by
  refine (eq_bot_iff.mpr fun f hf => ?_)
  have h := hf ∅ (by simp)
  refine Conv.ext_of_evalSeries_eventuallyEq (g := 0) ?_
  filter_upwards [h] with x hx
  rw [hx fun g hg => absurd hg (Finset.notMem_empty g), Subalgebra.coe_zero, evalSeries_zero]

end Analytic
