/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.CoordinateSubspace.Exceptional
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# The coordinate ring of `𝔸ⁿ` as a polynomial ring over `𝒪(L)`

For the coordinate subspace `L = V(x_0, …, x_{r-1}) ⊆ 𝔸ⁿ_A` (`r ≤ n`),
`A[x] ≅ 𝒪(L)[u_0, …, u_{r-1}]` with `𝒪(L) = A[x]/I ≅ A[x_r, …, x_{n-1}]` (`quotientCenterAlgEquiv`
of `Hironaka.Scheme.BlowUp.CoordinateSubspace.Exceptional`), `x_i ↦ u_i` for `i < r` and `x_i ↦
x̄_i` for `i ≥ r` (`centerSplitEquiv`).  Under it the centre ideal `I` is the ideal `(u_0, …,
u_{r-1})` of the polynomial ring, and `I^k` is the ideal of polynomials all of whose monomials have
degree `≥ k` (`mem_span_range_X_pow_iff`); the degree-`k` homogeneous component of such a polynomial
is its *initial form*, and initial forms multiply (`homogeneousComponent_mul_of_mem`).  This is
[Mat89, Theorem 16.2] (the associated graded ring of an ideal generated by a regular sequence is
the polynomial ring) for the coordinate ideal, by degree counting — the algebraic input for the
identification of the exceptional divisor with `ℙ^{r-1}_L`
(`Hironaka.Scheme.BlowUp.CoordinateSubspace.ReesInitial`).
-/

@[expose] public section

universe u

open MvPolynomial

namespace AlgebraicGeometry.CoordinateSubspace

section Degree

variable {σ S : Type*} [CommRing S]

/-- Products of powers of elements of an ideal lie in the corresponding power of the ideal. -/
theorem prod_pow_mem_pow (J : Ideal S) (s : Finset σ) (e : σ → ℕ) (x : σ → S)
    (hx : ∀ i, x i ∈ J) : ∏ i ∈ s, x i ^ e i ∈ J ^ (∑ i ∈ s, e i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
    rw [Finset.prod_insert ha, Finset.sum_insert ha, pow_add]
    exact Ideal.mul_mem_mul (Ideal.pow_mem_pow (hx a) _) ih

/-- A polynomial all of whose monomials have degree `≥ k` lies in `(X_i)^k`. -/
theorem mem_span_range_X_pow_of_forall {k : ℕ} {p : MvPolynomial σ S}
    (h : ∀ d ∈ p.support, k ≤ d.degree) :
    p ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ k := by
  rw [p.as_sum]
  refine Ideal.sum_mem _ fun d hd => ?_
  rw [monomial_eq]
  refine Ideal.mul_mem_left _ _ ?_
  have := prod_pow_mem_pow (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) d.support d X
    fun i => Ideal.subset_span ⟨i, rfl⟩
  rw [← Finsupp.degree_apply] at this
  exact Ideal.pow_le_pow_right (h d hd) this

/-- Every monomial of an element of `(X_i)^k` has degree `≥ k`. -/
theorem forall_degree_of_mem_span_range_X_pow {k : ℕ} {p : MvPolynomial σ S}
    (hp : p ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ k) :
    ∀ d ∈ p.support, k ≤ d.degree := by
  classical
  induction k generalizing p with
  | zero => exact fun _ _ => Nat.zero_le _
  | succ k ih =>
    rw [pow_succ] at hp
    refine Submodule.mul_induction_on hp ?_ ?_
    · intro a ha b hb d hd
      obtain ⟨da, hda, db, hdb, rfl⟩ := Finset.mem_add.mp (support_mul a b hd)
      have h1 := ih ha da hda
      have h2 : 1 ≤ db.degree := by
        rw [← Set.image_univ] at hb
        obtain ⟨i, -, hi⟩ := mem_ideal_span_X_image.mp hb db hdb
        exact (Nat.one_le_iff_ne_zero.mpr hi).trans (Finsupp.le_degree i db)
      rw [map_add]
      omega
    · intro a b ha hb d hd
      rcases Finset.mem_union.mp (support_add hd) with h | h
      · exact ha d h
      · exact hb d h

/-- `(X_i)^k` is the ideal of polynomials all of whose monomials have degree `≥ k`. -/
theorem mem_span_range_X_pow_iff {k : ℕ} {p : MvPolynomial σ S} :
    p ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ k ↔
      ∀ d ∈ p.support, k ≤ d.degree :=
  ⟨forall_degree_of_mem_span_range_X_pow, mem_span_range_X_pow_of_forall⟩

variable (J : Ideal (MvPolynomial σ S))

/-- The homogeneous component of degree `k` lies in `(X_i)^k`. -/
theorem homogeneousComponent_mem_span_range_X_pow (k : ℕ) (p : MvPolynomial σ S) :
    homogeneousComponent k p ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ k :=
  mem_span_range_X_pow_of_forall fun d hd => by
    rw [support_homogeneousComponent, Finset.mem_filter] at hd
    exact hd.2.ge

/-- For `p ∈ (X_i)^k`, `p` minus its initial form lies in `(X_i)^(k+1)`. -/
theorem sub_homogeneousComponent_mem {k : ℕ} {p : MvPolynomial σ S}
    (hp : p ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ k) :
    p - homogeneousComponent k p ∈
      (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ (k + 1) := by
  refine mem_span_range_X_pow_of_forall fun d hd => ?_
  have hd' := mem_support_iff.mp hd
  rw [coeff_sub, coeff_homogeneousComponent] at hd'
  by_cases hdk : d.degree = k
  · rw [ite_eq_left hdk, sub_self] at hd'
    exact absurd rfl hd'
  · rw [ite_eq_right hdk, sub_zero] at hd'
    have := forall_degree_of_mem_span_range_X_pow hp d (mem_support_iff.mpr hd')
    omega

/-- For `p ∈ (X_i)^k`, the initial form vanishes iff `p ∈ (X_i)^(k+1)`. -/
theorem homogeneousComponent_eq_zero_iff_mem_succ {k : ℕ} {p : MvPolynomial σ S}
    (hp : p ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ k) :
    homogeneousComponent k p = 0 ↔
      p ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ (k + 1) := by
  constructor
  · intro h
    have := sub_homogeneousComponent_mem hp
    rwa [h, sub_zero] at this
  · intro h
    refine homogeneousComponent_eq_zero' _ _ fun d hd hdk => ?_
    have := forall_degree_of_mem_span_range_X_pow h d hd
    omega

/-- Initial forms multiply: for `a ∈ (X_i)^k`, `b ∈ (X_i)^l`, the degree-`(k + l)` component of
`a * b` is the product of the degree-`k` component of `a` and the degree-`l` component of `b`. -/
theorem homogeneousComponent_mul_of_mem {k l : ℕ} {a b : MvPolynomial σ S}
    (ha : a ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ k)
    (hb : b ∈ (Ideal.span (Set.range (X : σ → MvPolynomial σ S))) ^ l) :
    homogeneousComponent (k + l) (a * b) =
      homogeneousComponent k a * homogeneousComponent l b := by
  set J := Ideal.span (Set.range (X : σ → MvPolynomial σ S)) with hJ
  have ha' := sub_homogeneousComponent_mem ha
  have hb' := sub_homogeneousComponent_mem hb
  have hak := homogeneousComponent_mem_span_range_X_pow k a
  have hbl := homogeneousComponent_mem_span_range_X_pow l b
  have hab : a * b = homogeneousComponent k a * homogeneousComponent l b +
      (homogeneousComponent k a * (b - homogeneousComponent l b) +
        (a - homogeneousComponent k a) * homogeneousComponent l b +
        (a - homogeneousComponent k a) * (b - homogeneousComponent l b)) := by ring
  have hrest : homogeneousComponent k a * (b - homogeneousComponent l b) +
      (a - homogeneousComponent k a) * homogeneousComponent l b +
      (a - homogeneousComponent k a) * (b - homogeneousComponent l b) ∈ J ^ (k + l + 1) := by
    refine Ideal.add_mem _ (Ideal.add_mem _ ?_ ?_) ?_
    · have := Ideal.mul_mem_mul hak hb'
      rwa [← pow_add, show k + (l + 1) = k + l + 1 by omega] at this
    · have := Ideal.mul_mem_mul ha' hbl
      rwa [← pow_add, show k + 1 + l = k + l + 1 by omega] at this
    · have := Ideal.mul_mem_mul ha' hb'
      rw [← pow_add] at this
      exact Ideal.pow_le_pow_right (by omega) this
  have hz : homogeneousComponent (k + l)
      (homogeneousComponent k a * (b - homogeneousComponent l b) +
        (a - homogeneousComponent k a) * homogeneousComponent l b +
        (a - homogeneousComponent k a) * (b - homogeneousComponent l b)) = 0 :=
    homogeneousComponent_eq_zero' _ _ fun d hd hdk => by
      have := forall_degree_of_mem_span_range_X_pow hrest d hd
      omega
  rw [hab, map_add, hz, add_zero, homogeneousComponent_eq_self
    ((homogeneousComponent_isHomogeneous k a).mul (homogeneousComponent_isHomogeneous l b))]

end Degree

section Split

variable (A : Type u) [CommRing A] (n r : ℕ) (hrn : r ≤ n)

/-- The variables of `𝔸ⁿ` split into the `r` center variables (`Fin r`) and the rest. -/
def splitFin : Fin n ≃ Fin r ⊕ {i : Fin n // ¬ i.val < r} where
  toFun i := if h : i.val < r then Sum.inl ⟨i.val, h⟩ else Sum.inr ⟨i, h⟩
  invFun := Sum.elim (fun j => ⟨j.val, lt_of_lt_of_le j.2 hrn⟩) Subtype.val
  left_inv i := by
    by_cases h : i.val < r
    · dsimp only
      rw [dite_eq_left h]
      rfl
    · dsimp only
      rw [dite_eq_right h]
      rfl
  right_inv := by
    rintro (j | i)
    · exact dite_eq_left j.2
    · exact dite_eq_right i.2

theorem splitFin_apply_of_lt {i : Fin n} (h : i.val < r) :
    splitFin n r hrn i = Sum.inl ⟨i.val, h⟩ := dite_eq_left h

theorem splitFin_apply_of_not_lt {i : Fin n} (h : ¬ i.val < r) :
    splitFin n r hrn i = Sum.inr ⟨i, h⟩ := dite_eq_right h

/-- `A[x_0, …, x_{n-1}] ≃ₐ[A] (A[x]/I)[u_0, …, u_{r-1}]`, `x_i ↦ u_i` for `i < r` and `x_i ↦ x̄_i`
for `i ≥ r`, through `A[x]/I ≃ A[x_i : r ≤ i]` (`quotientCenterAlgEquiv`). -/
noncomputable def centerSplitEquiv : MvPolynomial (Fin n) A ≃ₐ[A]
    MvPolynomial (Fin r) (MvPolynomial (Fin n) A ⧸ centerIdeal A n r) :=
  (renameEquiv A (splitFin n r hrn)).trans <|
    (sumAlgEquiv A (Fin r) {i : Fin n // ¬ i.val < r}).trans <|
      mapAlgEquiv (Fin r) (quotientCenterAlgEquiv A n r).symm

theorem centerSplitEquiv_X_of_lt {i : Fin n} (h : i.val < r) :
    centerSplitEquiv A n r hrn (X i) = X ⟨i.val, h⟩ := by
  rw [centerSplitEquiv, AlgEquiv.trans_apply, AlgEquiv.trans_apply]
  change mapAlgEquiv _ _ (sumAlgEquiv A _ _ (rename _ (X i))) = _
  rw [rename_X, splitFin_apply_of_lt n r hrn h, sumAlgEquiv_X_inl, mapAlgEquiv_apply, map_X]

theorem centerSplitEquiv_X_of_not_lt {i : Fin n} (h : ¬ i.val < r) :
    centerSplitEquiv A n r hrn (X i) = C (Ideal.Quotient.mk _ (X i)) := by
  rw [centerSplitEquiv, AlgEquiv.trans_apply, AlgEquiv.trans_apply]
  change mapAlgEquiv _ _ (sumAlgEquiv A _ _ (rename _ (X i))) = _
  rw [rename_X, splitFin_apply_of_not_lt n r hrn h, sumAlgEquiv_X_inr, mapAlgEquiv_apply, map_C]
  congr 1
  rw [RingHom.coe_coe, AlgEquiv.symm_apply_eq, quotientCenterAlgEquiv_mk_X]

/-- The constant term of `centerSplitEquiv p` is the class of `p` in `A[x]/I`. -/
theorem constantCoeff_comp_centerSplitEquiv :
    (constantCoeff (σ := Fin r)).comp
        (centerSplitEquiv A n r hrn : MvPolynomial (Fin n) A →+* _) =
      Ideal.Quotient.mk (centerIdeal A n r) := by
  refine MvPolynomial.ringHom_ext (fun a => ?_) (fun i => ?_)
  · rw [RingHom.comp_apply, RingHom.coe_coe, ← MvPolynomial.algebraMap_eq, AlgEquiv.commutes,
      MvPolynomial.algebraMap_apply, constantCoeff_C]
    rfl
  · by_cases h : i.val < r
    · rw [RingHom.comp_apply, RingHom.coe_coe, centerSplitEquiv_X_of_lt A n r hrn h,
        constantCoeff_X, Ideal.Quotient.eq_zero_iff_mem.mpr (X_mem_centerIdeal A n r h)]
    · rw [RingHom.comp_apply, RingHom.coe_coe, centerSplitEquiv_X_of_not_lt A n r hrn h,
        constantCoeff_C]

/-- Under `centerSplitEquiv` the center ideal is the ideal `(u_0, …, u_{r-1})`. -/
theorem map_centerIdeal_centerSplitEquiv :
    (centerIdeal A n r).map (centerSplitEquiv A n r hrn : MvPolynomial (Fin n) A →+* _) =
      Ideal.span (Set.range (X : Fin r →
        MvPolynomial (Fin r) (MvPolynomial (Fin n) A ⧸ centerIdeal A n r))) := by
  change (Ideal.span (X '' center n r)).map _ = _
  rw [Ideal.map_span]
  congr 1
  ext F
  simp only [Set.mem_image, Set.mem_range]
  constructor
  · rintro ⟨_, ⟨i, hi, rfl⟩, rfl⟩
    exact ⟨⟨i.val, hi⟩, by rw [RingHom.coe_coe, centerSplitEquiv_X_of_lt A n r hrn hi]⟩
  · rintro ⟨j, rfl⟩
    refine ⟨X ⟨j.val, lt_of_lt_of_le j.2 hrn⟩, ⟨⟨j.val, lt_of_lt_of_le j.2 hrn⟩, j.2, rfl⟩, ?_⟩
    rw [RingHom.coe_coe, centerSplitEquiv_X_of_lt A n r hrn j.2]

/-- `p ∈ I^k` iff its image under `centerSplitEquiv` lies in `(u_0, …, u_{r-1})^k`. -/
theorem mem_pow_iff_centerSplitEquiv_mem {k : ℕ} {c : MvPolynomial (Fin n) A} :
    c ∈ centerIdeal A n r ^ k ↔
      centerSplitEquiv A n r hrn c ∈ (Ideal.span (Set.range (X : Fin r →
        MvPolynomial (Fin r) (MvPolynomial (Fin n) A ⧸ centerIdeal A n r)))) ^ k := by
  have hbij : Function.Bijective ⇑(centerSplitEquiv A n r hrn : MvPolynomial (Fin n) A →+*
      MvPolynomial (Fin r) (MvPolynomial (Fin n) A ⧸ centerIdeal A n r)) := by
    rw [RingHom.coe_coe]
    exact (centerSplitEquiv A n r hrn).bijective
  rw [← map_centerIdeal_centerSplitEquiv A n r hrn, ← Ideal.map_pow]
  conv_lhs => rw [← Ideal.comap_map_of_bijective _ hbij (I := centerIdeal A n r ^ k)]
  exact Ideal.mem_comap

end Split

end AlgebraicGeometry.CoordinateSubspace
