/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.ChartRing
public import Hironaka.Scheme.BlowUp.Defs
public import Hironaka.Scheme.IdealSheaf.Defs
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
import Hironaka.Algebra.Local.Chart
import Hironaka.Algebra.Local.ChartLocal
import Hironaka.Algebra.Local.ChartShift
import Hironaka.Algebra.Local.RegularSystem
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Smooth.ChartRing
import Hironaka.Scheme.Snc.ChartDerivations
import Hironaka.Scheme.Snc.EtaleParameters
import Hironaka.Scheme.Snc.InducedCoordinates
import Hironaka.Scheme.Snc.StalkDerivations
import Hironaka.Scheme.Snc.TotalTransformData
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The origin of the chart after a linear change of coordinates

[Hau14, Proposition 5.4 (8)–(9)] ([Hau03, Appendix C (8)–(9)]; the proof of [Kol07, Lemma 61]): for
a point `a'` of the exceptional divisor over `a`, in the chart of `x_j` and **rational over
`κ(a)`**, the coordinate change `x_i ↦ x_i − α_i x_j` on the other centre coordinates
(`α_i ∈ 𝒪_{X,a}` lifting the entries of `a'`) makes `a'` the origin of the chart and the local
blow-up monomial: the induced coordinates of the new system form a regular system of parameters at
`a'`, with `π^* x'_i = w'_i · w'_j` (`exists_shiftCoords_chartOrigin`). The change preserves `I_Z`
and the coordinate `x_p` of any hypersurface `V = (x_p = 0)` through `a'`'s strict transform (its
entry vanishes, so the lift `α_p` may be taken `0`).

The proof lives in Kollár's chart ring (`Hironaka.Scheme.Snc.InducedCoordinates`): `𝒪_{B,a'} ≅ R'_𝔮`
with `𝔮` over `𝔪_a`; rationality of `a'` — the residue map `κ(a) → κ(a')` bijective — is the
bijectivity of `R/𝔪 → R'/𝔮` (`bijective_quotientMap_of_residueField`), so `𝔮 = 𝔪'_α = chartOriginAt
y ρ α` for lifts `α` (`exists_eq_chartOriginAt`), which can be changed modulo `𝔪`
(`chartOriginAt_eq_of_sub_mem`); `chartRingEquivShift` and `localizationEquivShift` of
`Hironaka.Algebra.Local.ChartShift` identify `R'_{𝔪'_α}` with the localization of the chart ring of
the shifted coordinates at its origin, whose maximal ideal is generated by the chart functions
(`maximalIdeal_localization_chartOrigin`), and the chart derivations
(`Hironaka.Scheme.Snc.ChartDerivations`) show these `n` generators are a regular system of
parameters (`ringKrullDim_eq_of_span_eq_of_derivations`).

Hauser's (9) (`exists_coordinates_chartOrigin'`): if `a'` lies on the strict transform of
`V = (x_{n-k+1} = 0)` the chart index is not `n − k + 1` and (8) applies, after which the
transposition of the positions `j` and `n` makes `a'` the origin of the `x_n`-chart; otherwise `a'`
lies in the chart of `x_{n-k+1}` itself (the entry of `V`'s coordinate is a unit) and (8) applies
with `j = n − k + 1`.
-/

public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal Scheme.IdealSheafData

namespace AlgebraicGeometry

section Rational

variable {R S R' : Type u} [CommRing R] [IsLocalRing R] [CommRing S] [IsLocalRing S] [CommRing R']
  [Algebra R R']

/-- Rationality transported to the chart ring: if the residue map of a local homomorphism
`π : R → S` is bijective and `S ≃ R'_𝔮` compatibly with `π` and `R → R' → R'_𝔮`, then
`R/𝔪 → R'/𝔮` is bijective. -/
theorem bijective_quotientMap_of_residueField (π : R →+* S) [IsLocalHom π]
    (hrat : Function.Bijective (IsLocalRing.ResidueField.map π)) (𝔮 : Ideal R') [𝔮.IsPrime]
    (e : S ≃+* Localization.AtPrime 𝔮)
    (hcompat : ∀ c, e (π c) = algebraMap R' (Localization.AtPrime 𝔮) (algebraMap R R' c))
    (h : maximalIdeal R ≤ 𝔮.comap (algebraMap R R')) :
    Function.Bijective (Ideal.quotientMap 𝔮 (algebraMap R R') h) := by
  -- the composite `κ(R) → κ(S) → κ(R'_𝔮)` is bijective and factors through `R'/𝔮`
  have hφbij : Function.Bijective (fun t => IsLocalRing.ResidueField.mapEquiv e
      (IsLocalRing.ResidueField.map π t)) :=
    (IsLocalRing.ResidueField.mapEquiv e).bijective.comp hrat
  have hfac : ∀ t : IsLocalRing.ResidueField R,
      algebraMap (R' ⧸ 𝔮) 𝔮.ResidueField (Ideal.quotientMap 𝔮 (algebraMap R R') h t) =
        IsLocalRing.ResidueField.mapEquiv e (IsLocalRing.ResidueField.map π t) := by
    intro t
    obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective t
    change algebraMap (R' ⧸ 𝔮) 𝔮.ResidueField (Ideal.quotientMap 𝔮 (algebraMap R R') h
      (Ideal.Quotient.mk _ x)) = IsLocalRing.ResidueField.mapEquiv e
        (IsLocalRing.ResidueField.map π (residue R x))
    rw [Ideal.quotientMap_mk, Ideal.algebraMap_quotient_residueField_mk,
      IsLocalRing.ResidueField.mapEquiv_apply, IsLocalRing.ResidueField.map_residue,
      IsLocalRing.ResidueField.map_residue, RingEquiv.coe_toRingHom, hcompat,
      IsScalarTower.algebraMap_apply R' (Localization.AtPrime 𝔮) 𝔮.ResidueField]
    rfl
  have hinj := Ideal.injective_algebraMap_quotient_residueField (I := 𝔮)
  refine ⟨?_, ?_⟩
  · intro a b hab
    apply hφbij.1
    exact (hfac a).symm.trans ((congrArg (algebraMap (R' ⧸ 𝔮) 𝔮.ResidueField) hab).trans (hfac b))
  · intro y
    obtain ⟨x, hx⟩ := hφbij.2 (algebraMap (R' ⧸ 𝔮) 𝔮.ResidueField y)
    refine ⟨x, hinj ?_⟩
    rw [hfac]
    exact hx

end Rational

section Lifts

variable {R : Type u} [CommRing R] [IsRegularLocalRing R] {n : ℕ} (x : Fin n → R) (r : Fin n)
  (hx : maximalIdeal R = span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)

include hx hn

/-- The origin `𝔪'_a` of the shifted chart depends only on the lifts `a` modulo `𝔪`. -/
theorem chartOriginAt_eq_of_sub_mem (a b : Fin n → R) (hab : ∀ i, a i - b i ∈ maximalIdeal R) :
    chartOriginAt x r a = chartOriginAt x r b := by
  have key : ∀ (a b : Fin n → R), (∀ i, a i - b i ∈ maximalIdeal R) →
      chartOriginAt x r a ≤ chartOriginAt x r b := by
    intro a b hab
    have hm : (maximalIdeal R).map (algebraMap R (chartRing x r)) ≤ chartOriginAt x r b :=
      Ideal.map_le_iff_le_comap.mpr (comap_chartOriginAt x r b hx hn).ge
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨i, rfl⟩
    by_cases hi : i < r
    · simp only [if_pos hi]
      have h1 : chartYR x r i - algebraMap R _ (b i) ∈ chartOriginAt x r b :=
        Ideal.subset_span ⟨i, by simp only [if_pos hi]⟩
      have h2 : algebraMap R (chartRing x r) (a i - b i) ∈ chartOriginAt x r b :=
        hm (Ideal.mem_map_of_mem _ (hab i))
      have : chartYR x r i - algebraMap R (chartRing x r) (a i) =
          (chartYR x r i - algebraMap R _ (b i)) - algebraMap R _ (a i - b i) := by
        rw [map_sub]; ring
      rw [this]
      exact Ideal.sub_mem _ h1 h2
    · simp only [if_neg hi]
      exact Ideal.subset_span ⟨i, by simp only [if_neg hi]⟩
  exact le_antisymm (key a b hab) (key b a fun i => by
    have := (maximalIdeal R).neg_mem (hab i)
    rwa [neg_sub] at this)

end Lifts

section Count

variable {k S : Type*} [CommRing k] [CommRing S] [IsRegularLocalRing S] [Algebra k S]

/-- A family of `n` generators of the maximal ideal of a regular local ring with dual derivations
is a regular system of parameters: `n = dim S`. -/
theorem ringKrullDim_eq_of_span_eq_of_derivations {n : ℕ} (g : Fin n → S)
    (hspan : span (Set.range g) = maximalIdeal S) (D : Fin n → Derivation k S S)
    (hD : ∀ i j, D i (g j) = if i = j then 1 else 0) : (n : WithBot ℕ∞) = ringKrullDim S := by
  classical
  have hg : ∀ i, g i ∈ maximalIdeal S := fun i => hspan ▸ Ideal.subset_span ⟨i, rfl⟩
  have hli := linearIndependent_toCotangent_of_derivations g hg D hD
  have htop : ⊤ ≤ Submodule.span (IsLocalRing.ResidueField S)
      (Set.range fun i => (maximalIdeal S).toCotangent ⟨g i, hg i⟩) :=
    ((span_eq_maximalIdeal_iff_span_toCotangent_eq_top g hg).mp hspan.symm).ge
  have hcard := ((span_eq_maximalIdeal_and_card_eq_spanFinrank_iff g hg).mpr
    ⟨Module.Basis.mk hli htop, fun i => by rw [Module.Basis.mk_apply]⟩).2
  rw [Fintype.card_fin] at hcard
  rw [hcard]
  exact IsRegularLocalRing.spanFinrank_maximalIdeal

end Count

section Generic

variable {R S R' L : Type*} [CommRing R] [CommRing S] [CommRing R'] [CommRing L]

theorem ringEquiv_symm_apply_eq_of_compat (E : S ≃+* L) (π : R →+* S) (g : R →+* R')
    (h : R' →+* L) (hc : ∀ c, E (π c) = h (g c)) {u : R'} {c : R} (hu : u = g c) :
    E.symm (h u) = π c := by
  subst hu
  rw [← hc, E.symm_apply_apply]

theorem span_range_symm_eq_maximalIdeal [IsLocalRing S] [IsLocalRing L] (E : S ≃+* L)
    {ι : Type*} (g : ι → L) (hspan : span (Set.range g) = maximalIdeal L) :
    span (Set.range fun i => E.symm (g i)) = maximalIdeal S := by
  rw [Set.range_comp', ← Ideal.map_span, hspan]
  exact map_maximalIdeal_ringEquiv E

theorem ringEquiv_trans_symm_compat {L' : Type*} [CommRing L'] (e : S ≃+* L) (Lq : L' ≃+* L)
    (π : R →+* S) (g : R →+* R') (h : R' →+* L) (h' : R →+* L') (hc : ∀ c, e (π c) = h (g c))
    (hL : ∀ c, Lq (h' c) = h (g c)) (c : R) : (e.trans Lq.symm) (π c) = h' c := by
  rw [RingEquiv.trans_apply, hc, RingEquiv.symm_apply_eq, hL]

theorem ringEquiv_symm_mul_eq_of_compat (E : S ≃+* L) (π : R →+* S) (g : R →+* R') (h : R' →+* L)
    (hc : ∀ c, E (π c) = h (g c)) (ci cj : R) {u v : R'} (hv : v = g cj) (huv : u * g cj = g ci) :
    E.symm (h u) * E.symm (h v) = π ci := by
  subst hv
  rw [← map_mul, ← map_mul, huv, ← hc, E.symm_apply_apply]

end Generic

section InducedAbstract

variable {k R S : Type*} [CommRing k] [CommRing R] [IsRegularLocalRing R] [Algebra k R]
  [CommRing S] [IsRegularLocalRing S]

omit [IsRegularLocalRing R] in
/-- The induced coordinates at the origin of a chart, abstractly: for `y'` a regular system of
parameters of `R` with dual derivations, and `S ≃ R'_{𝔪'}` (the localization of the chart ring of
`y'` at the origin of the chart of `y'_ρ`) compatibly with `π : R → S`, the chart functions
`y'_{σ i}` pulled back to `S` form a regular system of parameters of `S`, with `w'_i = π(y'_{σ i})`
for the non-fibre positions and `π(y'_{σ i}) = w'_i · w'_{σ⁻¹ ρ}` for the fibre positions. -/
theorem exists_induced_of_equiv_chartOrigin {n : ℕ} (y' : Fin n → R) (ρ : Fin n)
    (D' : Fin n → Derivation k R R) (hD' : ∀ i j, D' i (y' j) = if i = j then 1 else 0)
    [(chartOrigin y' ρ).IsPrime] (E : S ≃+* Localization.AtPrime (chartOrigin y' ρ))
    (π : R →+* S) (hEc : ∀ c, E (π c) = algebraMap R (Localization.AtPrime (chartOrigin y' ρ)) c)
    (σ : Fin n ≃ Fin n) :
    ∃ w' : Fin n → S,
      (span (Set.range w') = maximalIdeal S ∧ (n : WithBot ℕ∞) = ringKrullDim S) ∧
      (∀ i, ¬ σ i < ρ → w' i = π (y' (σ i))) ∧
      (∀ i, σ i < ρ → π (y' (σ i)) = w' i * w' (σ.symm ρ)) := by
  classical
  have hEc' : ∀ c, E (π c) = algebraMap (chartRing y' ρ) (Localization.AtPrime (chartOrigin y' ρ))
      (algebraMap R (chartRing y' ρ) c) :=
    fun c => (hEc c).trans (IsScalarTower.algebraMap_apply _ (chartRing y' ρ) _ c)
  have hregL : IsRegularLocalRing (Localization.AtPrime (chartOrigin y' ρ)) :=
    IsRegularLocalRing.of_ringEquiv E
  have hspan' : span (Set.range fun l => algebraMap (chartRing y' ρ)
      (Localization.AtPrime (chartOrigin y' ρ)) (chartYR y' ρ l)) =
      maximalIdeal (Localization.AtPrime (chartOrigin y' ρ)) :=
    (maximalIdeal_localization_chartOrigin y' ρ).symm
  refine ⟨fun i => E.symm (algebraMap (chartRing y' ρ) _ (chartYR y' ρ (σ i))), ⟨?_, ?_⟩, ?_, ?_⟩
  · refine span_range_symm_eq_maximalIdeal E _ ?_
    have hr : (Set.range fun i => algebraMap (chartRing y' ρ)
        (Localization.AtPrime (chartOrigin y' ρ)) (chartYR y' ρ (σ i))) =
        Set.range fun l => algebraMap (chartRing y' ρ)
          (Localization.AtPrime (chartOrigin y' ρ)) (chartYR y' ρ l) := by
      rw [← σ.surjective.range_comp (fun l => algebraMap (chartRing y' ρ)
        (Localization.AtPrime (chartOrigin y' ρ)) (chartYR y' ρ l))]
      rfl
    rw [hr]
    exact hspan'
  · rw [ringKrullDim_eq_of_ringEquiv E]
    exact ringKrullDim_eq_of_span_eq_of_derivations _ hspan'
      (fun l => (chartRingDer y' ρ D' hD' l).localization (chartOrigin y' ρ).primeCompl)
      (fun i l => by
        change (chartRingDer y' ρ D' hD' i).localization (chartOrigin y' ρ).primeCompl
          (algebraMap (chartRing y' ρ) (Localization (chartOrigin y' ρ).primeCompl)
            (chartYR y' ρ l)) = _
        rw [Derivation.localization_algebraMap, chartRingDer_chartYR]
        split_ifs <;> simp)
  · intro i hi
    exact ringEquiv_symm_apply_eq_of_compat E π _ _ hEc' (chartYR_of_not_lt y' ρ hi)
  · intro i hi
    have hv : chartYR y' ρ (σ (σ.symm ρ)) = algebraMap R (chartRing y' ρ) (y' ρ) := by
      rw [Equiv.apply_symm_apply]
      exact chartYR_of_not_lt y' ρ (lt_irrefl ρ)
    exact (ringEquiv_symm_mul_eq_of_compat E π _ _ hEc' (y' (σ i)) (y' ρ) hv
      (chartYR_mul_algebraMap y' ρ hi)).symm

end InducedAbstract

variable {X : Scheme.{u}}

section Shift

variable {k : Type u} [Field k] [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]
  (Z : X.IdealSheafData) (a' : blowUp Z) [IsRegularLocalRing ((blowUp Z).presheaf.stalk a')]
  {n kk : ℕ} (hk : 1 ≤ kk) (hkn : kk ≤ n) {z : Fin n → X.presheaf.stalk (blowUpπ Z a')}
  (hz : span (Set.range z) = maximalIdeal (X.presheaf.stalk (blowUpπ Z a')) ∧
    (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk (blowUpπ Z a')))
  (hZa : Z.stalkIdeal (blowUpπ Z a') = span (z '' {i | n - kk ≤ i.val}))
  (hrat : Function.Bijective (IsLocalRing.ResidueField.map ((blowUpπ Z).stalkMap a').hom))

include f hk hkn hz hZa hrat

/-- [Hau14, Proposition 5.4 (8)] ([Hau03, Appendix C (8)]; the proof of [Kol07, Lemma 61]): for `a'`
in the chart of `z_j` and rational over `κ(a)`, the coordinates `z'_i = z_i − α_i z_j` (`n − k ≤ i`,
`i ≠ j`; `z'_i = z_i` otherwise) make `a'` the origin of the chart and the local blow-up monomial:
`Z` is still cut out by the last `k` of them, the coordinate `z_p` of a hypersurface whose induced
entry at `a'` vanishes is unchanged, and the induced coordinates `w'` form a regular system of
parameters at `a'` with `π^* z'_i = w'_i w'_j`. -/
theorem exists_shiftCoords_chartOrigin {j : Fin n} (hj : n - kk ≤ j.val)
    (hF : (Z.comap (blowUpπ Z)).stalkIdeal a' = span {(blowUpπ Z).stalkMap a' (z j)})
    (hne : (blowUpπ Z).stalkMap a' (z j) ≠ 0) (p : Fin n) (hp : n - kk ≤ p.val) :
    ∃ z' : Fin n → X.presheaf.stalk (blowUpπ Z a'),
      (span (Set.range z') = maximalIdeal (X.presheaf.stalk (blowUpπ Z a')) ∧
        (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk (blowUpπ Z a'))) ∧
      (∀ i : Fin n, i.val < n - kk ∨ i = j → z' i = z i) ∧
      (∀ i : Fin n, n - kk ≤ i.val → ∃ α : X.presheaf.stalk (blowUpπ Z a'),
        z' i = z i - α * z j) ∧
      Z.stalkIdeal (blowUpπ Z a') = span (z' '' {i | n - kk ≤ i.val}) ∧
      ((p = j ∨ ∀ y : (blowUp Z).presheaf.stalk a',
        (blowUpπ Z).stalkMap a' (z p) = y * (blowUpπ Z).stalkMap a' (z j) →
          y ∈ maximalIdeal ((blowUp Z).presheaf.stalk a')) → z' p = z p) ∧
      ∃ w' : Fin n → (blowUp Z).presheaf.stalk a',
        (span (Set.range w') = maximalIdeal ((blowUp Z).presheaf.stalk a') ∧
          (n : WithBot ℕ∞) = ringKrullDim ((blowUp Z).presheaf.stalk a')) ∧
        (∀ i : Fin n, i.val < n - kk ∨ i = j → w' i = (blowUpπ Z).stalkMap a' (z' i)) ∧
        (∀ i : Fin n, n - kk ≤ i.val → i ≠ j →
          (blowUpπ Z).stalkMap a' (z' i) = w' i * w' j) := by
  classical
  -- the induced coordinates `w` of the chart of `z_j`
  have hex : ∀ i : Fin n, n - kk ≤ i.val → ∃ y : (blowUp Z).presheaf.stalk a',
      (blowUpπ Z).stalkMap a' (z i) = y * (blowUpπ Z).stalkMap a' (z j) := by
    intro i hi
    have hmem : (blowUpπ Z).stalkMap a' (z i) ∈ (Z.comap (blowUpπ Z)).stalkIdeal a' := by
      rw [Scheme.IdealSheafData.stalkIdeal_comap, hZa]
      exact Ideal.mem_map_of_mem _ (Ideal.subset_span ⟨i, hi, rfl⟩)
    rw [hF] at hmem
    obtain ⟨y, hy⟩ := Ideal.mem_span_singleton'.mp hmem
    exact ⟨y, hy.symm⟩
  choose! yy hyy using hex
  set w : Fin n → (blowUp Z).presheaf.stalk a' := fun i =>
    if i.val < n - kk ∨ i = j then (blowUpπ Z).stalkMap a' (z i) else yy i with hw_def
  have hw : ∀ i : Fin n, i.val < n - kk ∨ i = j → w i = (blowUpπ Z).stalkMap a' (z i) :=
    fun i hi => if_pos hi
  have hw' : ∀ i : Fin n, n - kk ≤ i.val → i ≠ j →
      (blowUpπ Z).stalkMap a' (z i) = w i * (blowUpπ Z).stalkMap a' (z j) := by
    intro i h1 h2
    have : w i = yy i := if_neg (by omega)
    rw [this]
    exact hyy i h1
  -- Kollár's indexing, made opaque
  have hσ1 := lt_kollarReindex_iff hk hkn j hj
  have hσ2 := kollarReindex_apply_self hk hkn j
  have hρ1 := kollarIdx_val hk hkn
  generalize kollarReindex hk hkn j = σ at hσ1 hσ2
  generalize kollarIdx hk hkn = ρ at hσ2 hρ1
  have hyσ : ∀ i, (z ∘ σ.symm) (σ i) = z i :=
    fun i => by simp only [Function.comp_apply, Equiv.symm_apply_apply]
  have hyρ : (z ∘ σ.symm) ρ = z j := by rw [← hσ2, hyσ]
  have hyspan : maximalIdeal (X.presheaf.stalk (blowUpπ Z a')) =
      span (Set.range (z ∘ σ.symm)) := by
    rw [← hz.1, Set.range_comp, Equiv.range_eq_univ, Set.image_univ]
  have hZ' : Z.stalkIdeal (blowUpπ Z a') = span ((z ∘ σ.symm) '' {i | i.val < kk}) := by
    rw [hZa, ← image_eq_of_lt_iff σ hσ1, Set.image_image]
    simp only [Function.comp_apply, Equiv.symm_apply_apply]
  have hregR : IsRegularLocalRing (X.presheaf.stalk (blowUpπ Z a')) :=
    isRegularLocalRing_stalk f _
  -- the chart-ring model
  obtain ⟨𝔮, h𝔮, e, hcomap, hcompat, hE⟩ :=
    exists_chartRing_model Z a' hk hZa hF hne σ hσ1 ρ hρ1 hσ2 w hw hw'
  have hreg : IsRegularLocalRing (Localization.AtPrime 𝔮) := IsRegularLocalRing.of_ringEquiv e
  -- rationality: `𝔮` is the origin of the chart after a shift by lifts `α`
  have hle : maximalIdeal (X.presheaf.stalk (blowUpπ Z a')) ≤ 𝔮.comap (algebraMap _ _) :=
    hcomap.ge
  have hrat' := bijective_quotientMap_of_residueField ((blowUpπ Z).stalkMap a').hom hrat 𝔮 e
    hcompat hle
  obtain ⟨α, hα⟩ :=
    exists_eq_chartOriginAt (z ∘ σ.symm) ρ hyspan hz.2 𝔮 hle hrat'
  -- the lift at the position of `p` may be taken `0` when `p`'s entry vanishes
  have hσp : n - kk ≤ p.val := hp
  have hlift : ∃ β : Fin n → X.presheaf.stalk (blowUpπ Z a'),
      𝔮 = chartOriginAt (z ∘ σ.symm) ρ β ∧
        ((p = j ∨ ∀ y : (blowUp Z).presheaf.stalk a',
          (blowUpπ Z).stalkMap a' (z p) = y * (blowUpπ Z).stalkMap a' (z j) →
            y ∈ maximalIdeal ((blowUp Z).presheaf.stalk a')) → p ≠ j → β (σ p) = 0) := by
    by_cases hV : p = j ∨ ∀ y : (blowUp Z).presheaf.stalk a',
        (blowUpπ Z).stalkMap a' (z p) = y * (blowUpπ Z).stalkMap a' (z j) →
          y ∈ maximalIdeal ((blowUp Z).presheaf.stalk a')
    swap
    · exact ⟨α, hα, fun h => (hV h).elim⟩
    rcases hV with hpj | hpy
    · exact ⟨α, hα, fun _ h => (h hpj).elim⟩
    · by_cases hpj : p = j
      · exact ⟨α, hα, fun _ h => (h hpj).elim⟩
      · -- the entry `w p` vanishes, so `α (σ p) ∈ 𝔪`
        have hwp : w p ∈ maximalIdeal ((blowUp Z).presheaf.stalk a') := hpy (w p) (hw' p hp hpj)
        have hlt : σ p < ρ := by
          have h1 := (hσ1 p).mpr hp
          have h2 : σ p ≠ ρ := fun h => hpj (σ.injective (h.trans hσ2.symm))
          rw [Fin.lt_def]
          have h3 := Fin.val_ne_of_ne h2
          omega
        have hmem : chartYR (z ∘ σ.symm) ρ (σ p) ∈ 𝔮 := by
          rw [← map_maximalIdeal_ringEquiv e, Ideal.map_symm, Ideal.mem_comap, hE p] at hwp
          exact (IsLocalization.AtPrime.to_map_mem_maximal_iff (Localization.AtPrime 𝔮) 𝔮 _).mp
            hwp
        have hgen : chartYR (z ∘ σ.symm) ρ (σ p) -
            algebraMap _ (chartRing (z ∘ σ.symm) ρ) (α (σ p)) ∈ 𝔮 := by
          rw [hα]
          exact Ideal.subset_span ⟨σ p, by simp only [if_pos hlt]⟩
        have hαp : α (σ p) ∈ maximalIdeal (X.presheaf.stalk (blowUpπ Z a')) := by
          rw [← hcomap, Ideal.mem_comap]
          have := 𝔮.sub_mem hmem hgen
          rwa [sub_sub_cancel] at this
        refine ⟨Function.update α (σ p) 0, ?_, fun _ _ => Function.update_self _ _ _⟩
        rw [hα]
        refine chartOriginAt_eq_of_sub_mem (z ∘ σ.symm) ρ hyspan hz.2 α _ fun i => ?_
        by_cases hi : i = σ p
        · subst hi
          rw [Function.update_self, sub_zero]
          exact hαp
        · rw [Function.update_of_ne hi, sub_self]
          exact Ideal.zero_mem _
  obtain ⟨β, hβ, hβp⟩ := hlift
  clear hα α
  subst hβ
  -- the shifted coordinates and their chart ring at the origin
  set y' : Fin n → X.presheaf.stalk (blowUpπ Z a') := shiftCoords (z ∘ σ.symm) ρ β with hy'
  have hy'span : maximalIdeal (X.presheaf.stalk (blowUpπ Z a')) = span (Set.range y') :=
    span_range_shiftCoords (z ∘ σ.symm) ρ β hyspan
  have hy'lt : ∀ i, i < ρ → y' i = (z ∘ σ.symm) i - β i * (z ∘ σ.symm) ρ := fun i hi =>
    shiftCoords_of_lt _ _ _ hi
  have hy'ge : ∀ i, ¬ i < ρ → y' i = (z ∘ σ.symm) i := fun i hi => shiftCoords_of_not_lt _ _ _ hi
  have hprime : (chartOrigin y' ρ).IsPrime := (chartOrigin_isMaximal y' ρ hy'span hz.2).isPrime
  let L := localizationEquivShift (z ∘ σ.symm) ρ β
  let E : (blowUp Z).presheaf.stalk a' ≃+* Localization.AtPrime (chartOrigin y' ρ) :=
    e.trans L.symm
  have hEc : ∀ c, E ((blowUpπ Z).stalkMap a' c) =
      algebraMap _ (Localization.AtPrime (chartOrigin y' ρ)) c :=
    ringEquiv_trans_symm_compat e L ((blowUpπ Z).stalkMap a').hom _ _ _ hcompat
      (fun c => (localizationEquivShift_algebraMap_R (z ∘ σ.symm) ρ β c).trans
        (IsScalarTower.algebraMap_apply _ (chartRing (z ∘ σ.symm) ρ) _ c))
  -- the classification of positions
  have hlt_of : ∀ i : Fin n, n - kk ≤ i.val → i ≠ j → σ i < ρ := by
    intro i h1 h2
    have h3 := (hσ1 i).mpr h1
    have h4 : σ i ≠ ρ := fun h => h2 (σ.injective (h.trans hσ2.symm))
    rw [Fin.lt_def]
    have h5 := Fin.val_ne_of_ne h4
    omega
  have hnlt_of : ∀ i : Fin n, i.val < n - kk ∨ i = j → ¬ σ i < ρ := by
    intro i hi
    rcases hi with hi | rfl
    · intro hlt
      have h1 := (hσ1 i).mp (lt_of_lt_of_le hlt (by omega))
      omega
    · rw [hσ2]
      exact lt_irrefl _
  -- the new coordinates at `a` and the induced coordinates at `a'`
  refine ⟨fun i => y' (σ i), ⟨?_, hz.2⟩, ?_, ?_, ?_, ?_, ?_⟩
  · change span (Set.range (y' ∘ σ)) = _
    rw [Set.range_comp, Equiv.range_eq_univ, Set.image_univ, ← hy'span]
  · intro i hi
    change y' (σ i) = z i
    rw [hy'ge _ (hnlt_of i hi), hyσ]
  · intro i hi
    by_cases hij : i = j
    · refine ⟨0, ?_⟩
      change y' (σ i) = z i - 0 * z j
      rw [hy'ge _ (hnlt_of i (Or.inr hij)), hyσ, zero_mul, sub_zero]
    · refine ⟨β (σ i), ?_⟩
      change y' (σ i) = z i - β (σ i) * z j
      rw [hy'lt _ (hlt_of i hi hij), hyσ, hyρ]
  · -- `Z` is cut out by the last `k` coordinates
    have hset : {i : Fin n | i ≤ ρ} = {i | i.val < kk} := by
      ext i
      change i.val ≤ ρ.val ↔ i.val < kk
      omega
    have h1 : (fun i => y' (σ i)) '' {i : Fin n | n - kk ≤ i.val} = y' '' {i | i.val < kk} := by
      rw [← image_eq_of_lt_iff σ hσ1, Set.image_image]
    have hcc := chartCenter_shiftCoords (z ∘ σ.symm) ρ β
    rw [chartCenter, chartCenter, hset] at hcc
    rw [h1, hZ']
    exact hcc.symm
  · -- the coordinate of `V`
    intro hV
    change y' (σ p) = z p
    by_cases hpj : p = j
    · rw [hy'ge _ (hnlt_of p (Or.inr hpj)), hyσ]
    · rw [hy'lt _ (hlt_of p hp hpj), hyσ, hyρ, hβp hV hpj, zero_mul, sub_zero]
  · -- the induced coordinates form a regular system of parameters at `a'`
    let _ := f.stalkAlgebra (blowUpπ Z a')
    obtain ⟨D', hD'⟩ := exists_derivation_dual f (blowUpπ Z a') y' hy'span hz.2
    obtain ⟨w', hw'r, hw'1, hw'2⟩ := exists_induced_of_equiv_chartOrigin y' ρ D' hD'
      E ((blowUpπ Z).stalkMap a').hom hEc σ
    have hσj' : σ.symm ρ = j := by rw [← hσ2, Equiv.symm_apply_apply]
    refine ⟨w', hw'r, fun i hi => ?_, fun i hi hij => ?_⟩
    · exact hw'1 i (hnlt_of i hi)
    · have := hw'2 i (hlt_of i hi hij)
      rwa [hσj'] at this


/-- [Hau14, Proposition 5.4 (9)] ([Hau03, Appendix C (9)]), with `P` standing for "`a'` lies on the
strict transform of `V = (z_p = 0)`", `p = n − k` the position of `V`'s coordinate: `P` excludes the
chart of `z_p` and the entry of `V`'s coordinate at `a'` vanishes exactly when `P` (Hauser's (6)).
For `a'` rational over `κ(a)` there are coordinates `z''` at `a` with (1)–(3) in which `a'` is the
origin of the chart of `z''_{j'}`, `j' = n − 1` when `P` and `j' = p` when `¬P`, and the local
blow-up is monomial. -/
theorem exists_coordinates_chartOrigin' {j : Fin n} (hj : n - kk ≤ j.val)
    (hF : (Z.comap (blowUpπ Z)).stalkIdeal a' = span {(blowUpπ Z).stalkMap a' (z j)})
    (hne : (blowUpπ Z).stalkMap a' (z j) ≠ 0) {IV : Ideal (X.presheaf.stalk (blowUpπ Z a'))}
    (p : Fin n) (hp : p.val = n - kk) (hV : IV = span {z p}) (P : Prop) (hP : P → j ≠ p)
    (hPy : ∀ y : (blowUp Z).presheaf.stalk a',
      (blowUpπ Z).stalkMap a' (z p) = y * (blowUpπ Z).stalkMap a' (z j) →
        (y ∈ maximalIdeal ((blowUp Z).presheaf.stalk a') ↔ P)) :
    ∃ (z'' : Fin n → X.presheaf.stalk (blowUpπ Z a')) (j' : Fin n),
      (span (Set.range z'') = maximalIdeal (X.presheaf.stalk (blowUpπ Z a')) ∧
        (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk (blowUpπ Z a'))) ∧
      IV = span {z'' p} ∧
      Z.stalkIdeal (blowUpπ Z a') = span (z'' '' {i | n - kk ≤ i.val}) ∧
      n - kk ≤ j'.val ∧ (P → j'.val = n - 1) ∧ (¬ P → j'.val = n - kk) ∧
      (Z.comap (blowUpπ Z)).stalkIdeal a' = span {(blowUpπ Z).stalkMap a' (z'' j')} ∧
      ∃ w'' : Fin n → (blowUp Z).presheaf.stalk a',
        (span (Set.range w'') = maximalIdeal ((blowUp Z).presheaf.stalk a') ∧
          (n : WithBot ℕ∞) = ringKrullDim ((blowUp Z).presheaf.stalk a')) ∧
        (∀ i : Fin n, i.val < n - kk ∨ i = j' → w'' i = (blowUpπ Z).stalkMap a' (z'' i)) ∧
        (∀ i : Fin n, n - kk ≤ i.val → i ≠ j' →
          (blowUpπ Z).stalkMap a' (z'' i) = w'' i * w'' j') := by
  classical
  have hpk : n - kk ≤ p.val := hp.ge
  by_cases hPc : P
  · -- `a'` on the strict transform of `V`: shift in the chart of `z_j`, then move `j` to the end
    have hjp : j ≠ p := hP hPc
    obtain ⟨z', hz', hz'1, -, hz'Z, hz'p', w', hw'r, hw'1, hw'2⟩ :=
      exists_shiftCoords_chartOrigin f Z a' hk hkn hz hZa hrat hj hF hne p hpk
    have hz'p : z' p = z p := hz'p' (Or.inr fun y hy => (hPy y hy).mpr hPc)
    have hn1 : n - 1 < n := by have := j.2; omega
    set τ : Fin n ≃ Fin n := Equiv.swap j ⟨n - 1, hn1⟩ with hτ
    have hpn : p ≠ ⟨n - 1, hn1⟩ := by
      intro h
      have h1 := congrArg Fin.val h
      simp only at h1
      have h2 := j.2
      have h3 : j.val = p.val := by omega
      exact hjp (Fin.ext h3)
    have hτp : τ p = p := Equiv.swap_apply_of_ne_of_ne hjp.symm hpn
    have hτj : τ j = ⟨n - 1, hn1⟩ := Equiv.swap_apply_left _ _
    have hτn : τ ⟨n - 1, hn1⟩ = j := Equiv.swap_apply_right _ _
    have hτlow : ∀ i : Fin n, i.val < n - kk → τ i = i := by
      intro i hi
      refine Equiv.swap_apply_of_ne_of_ne ?_ ?_
      · intro h; subst h; omega
      · intro h; have := congrArg Fin.val h; simp only at this; omega
    have hτge : ∀ i : Fin n, n - kk ≤ i.val → n - kk ≤ (τ i).val := by
      intro i hi
      rw [hτ, Equiv.swap_apply_def]
      split_ifs <;> first | exact hj | exact hi | (change n - kk ≤ n - 1; omega)
    have hτimage : τ '' {i : Fin n | n - kk ≤ i.val} = {i | n - kk ≤ i.val} := by
      ext i
      constructor
      · rintro ⟨i', hi', rfl⟩
        exact hτge i' hi'
      · intro hi
        refine ⟨τ.symm i, ?_, Equiv.apply_symm_apply _ _⟩
        have : τ.symm i = τ i := by rw [hτ, Equiv.symm_swap]
        change n - kk ≤ (τ.symm i).val
        rw [this]
        exact hτge i hi
    refine ⟨fun i => z' (τ i), ⟨n - 1, hn1⟩, ⟨?_, hz'.2⟩, ?_, ?_, show n - kk ≤ n - 1 by omega,
      fun _ => rfl, fun h => (h hPc).elim, ?_, fun i => w' (τ i), ⟨?_, hw'r.2⟩, ?_, ?_⟩
    · change span (Set.range (z' ∘ τ)) = _
      rw [Set.range_comp, Equiv.range_eq_univ, Set.image_univ, hz'.1]
    · change IV = span {z' (τ p)}
      rw [hτp, hz'p, hV]
    · rw [← Set.image_image, hτimage, hz'Z]
    · change _ = span {(blowUpπ Z).stalkMap a' (z' (τ ⟨n - 1, hn1⟩))}
      rw [hτn, hz'1 j (Or.inr rfl)]
      exact hF
    · change span (Set.range (w' ∘ τ)) = _
      rw [Set.range_comp, Equiv.range_eq_univ, Set.image_univ, hw'r.1]
    · intro i hi
      change w' (τ i) = (blowUpπ Z).stalkMap a' (z' (τ i))
      rcases hi with hi | rfl
      · rw [hτlow i hi]
        exact hw'1 i (Or.inl hi)
      · rw [hτn]
        exact hw'1 j (Or.inr rfl)
    · intro i hi hin
      change (blowUpπ Z).stalkMap a' (z' (τ i)) = w' (τ i) * w' (τ ⟨n - 1, hn1⟩)
      rw [hτn]
      refine hw'2 (τ i) (hτge i hi) fun h => hin ?_
      exact (Equiv.swap_apply_self _ _ i).symm.trans ((congrArg τ h).trans hτj)
  · -- `a'` off the strict transform of `V`: `V`'s coordinate generates the exceptional ideal
    have hmem : (blowUpπ Z).stalkMap a' (z p) ∈ (Z.comap (blowUpπ Z)).stalkIdeal a' := by
      rw [Scheme.IdealSheafData.stalkIdeal_comap, hZa]
      exact Ideal.mem_map_of_mem _ (Ideal.subset_span ⟨p, hpk, rfl⟩)
    rw [hF] at hmem
    obtain ⟨y, hy⟩ := Ideal.mem_span_singleton'.mp hmem
    have hyu : IsUnit y := by
      by_contra hu
      exact hPc ((hPy y hy.symm).mp ((IsLocalRing.mem_maximalIdeal y).mpr hu))
    have hFp : (Z.comap (blowUpπ Z)).stalkIdeal a' = span {(blowUpπ Z).stalkMap a' (z p)} := by
      rw [hF, ← hy, Ideal.span_singleton_mul_left_unit hyu]
    have hnep : (blowUpπ Z).stalkMap a' (z p) ≠ 0 := by
      intro h0
      apply hne
      have := hy
      rw [h0] at this
      exact hyu.mul_right_eq_zero.mp this
    obtain ⟨z', hz', hz'1, -, hz'Z, hz'p', w', hw'r, hw'1, hw'2⟩ :=
      exists_shiftCoords_chartOrigin f Z a' hk hkn hz hZa hrat hpk hFp hnep p hpk
    have hz'p : z' p = z p := hz'p' (Or.inl rfl)
    refine ⟨z', p, hz', ?_, hz'Z, hpk, fun h => (hPc h).elim, fun _ => hp, ?_, w', hw'r, hw'1,
      hw'2⟩
    · rw [hz'p, hV]
    · rw [hz'p]
      exact hFp

end Shift

end AlgebraicGeometry
