/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.Snc.SpreadSnc
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.IdealSheaf.Order.Basic

/-!
# Hauser's coordinates (1)–(4) at a point of the centre

[Hau14, Proposition 5.4 (1)–(4)]: a smooth `X` over a perfect field, an snc family `E` of divisors
one of whose members `V = E v` contains the centre `Z` (`E v ≤ Z` in the ideal-sheaf order,
`I_V ⊆ I_Z`), `Z` having simple normal crossings with `E`, and a point `a` of `Z`. Kollár's snc data
at `a` [Kol07, Definition 24 (1)–(4)] are a regular system of parameters `z_1, …, z_n` of `𝒪_{X,a}`,
an injective assignment `c` of a coordinate to every component through `a` with
`I_{E^i,a} = (z_{c(i)})`, and a set `s` of indices with `I_{Z,a} = (z_l : l ∈ s)`.

**(1)–(3).** Since `I_{V,a} ⊆ I_{Z,a}`, the coordinate `z_{c(v)}` of `V` lies in `(z_l : l ∈ s)`, so
`c(v) ∈ s` (`mem_span_image_iff` of `Hironaka.Scheme.Snc.ParameterSubset`: a parameter lies in the
ideal generated by a subset of the parameters only if it is one of them). Hauser's positions are
reached by reindexing: `hauserReindex s j` is the permutation of `Fin n` sending `s` onto the last
`k = |s|` positions `n − k, …, n − 1` with `j = c(v) ↦ n − k` — the composite of `sncReindex s`
(which puts `s` first), the reversal `Fin.rev`, and a transposition inside the last `k` positions.
The reindexed parameters `z' = z ∘ σ⁻¹` are again a regular system of parameters (same range), the
snc assignment becomes `σ ∘ c`, `I_{V,a} = (z'_{n-k})` and `I_{Z,a} = (z'_l : l ≥ n − k)`
(`exists_hauser_coordinates`). Condition (1), `a = (0, …, 0)`, is that the `z'_i` lie in the maximal
ideal, part of being a regular system of parameters.

**(4).** The ideal of the (not necessarily reduced) divisor `D = ∑_{i ≠ v} m_i E^i` at `a` is the
product `∏_{i ≠ v} I_{E^i,a}^{m_i}` ([Hau14, Remark 3.16, Remark 3.20]: unions of schemes are
products of ideals). A component through `a` contributes `(z_{c(i)})^{m_i} = (z_{c(i)}^{m_i})`, a
component missing `a` contributes `⊤ = (1)`; the product of principal ideals is the principal ideal
of the product (Mathlib's `Ideal.prod_span_singleton`), and regrouping the factors by their
coordinate (`Finset.prod_fiberwise_of_maps_to`) writes the generator as the monomial `∏_j z_j^{q_j}`
with `q_j = ∑_{c(i) = j, i ≠ v} m_i`. The exponent of `V`'s coordinate is `q_{c(v)} = 0`: by
injectivity of `c` the only component with coordinate `c(v)` is `V` itself, which is excluded
(`exists_prod_stalkIdeal_pow_eq_span_monomial`). Hauser states (4) in `V`: the ideal of `D ∩ V` in
`𝒪_{V,a} = 𝒪_{X,a}/I_{V,a}` is the image of `I_{D,a}`, generated by the image of the monomial
(`exists_map_prod_stalkIdeal_pow_eq_span_monomial`).

The transversality of `Z` and `D` enters through the snc data at `a` (the hypothesis
`E.HasSncWith Z`). The forms of these statements on the predicates `IsSncAt` and `HasSncWith` are in
`Hironaka.Scheme.Snc.MonomialCoordinates`.

Sources: [Hau14, Proposition 5.4 (1)–(4); Remark 3.16; Remark 3.20]; [Hau03, Appendix C] (the proof,
"(1) to (3) … and (4) follows immediately from the fact that `D` and `Z` are transversal");
[Kol07, Definition 24].
-/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal Scheme.IdealSheafData

namespace AlgebraicGeometry

section Reindex

variable {n : ℕ} (s : Finset (Fin n)) {j : Fin n} (hj : j ∈ s)

/-- The last `s.card` positions of `Fin n` begin at `n - s.card`, a valid index once `s` is
nonempty. -/
theorem sub_card_lt (hj : j ∈ s) : n - s.card < n := by
  have h1 : 0 < s.card := Finset.card_pos.mpr ⟨j, hj⟩
  have h2 : s.card ≤ n := (Finset.card_le_univ s).trans (Fintype.card_fin n).le
  have h3 := j.2
  omega

/-- The reindexing of `Fin n` sending `s` onto the last `s.card` positions, the members of the
complement onto the first `n - s.card` ones: `sncReindex s` inverted, then `Fin.rev`. -/
noncomputable def lastReindex : Fin n ≃ Fin n := (sncReindex s).symm.trans Fin.revPerm

theorem mem_iff_sub_card_le_lastReindex (i : Fin n) :
    i ∈ s ↔ n - s.card ≤ (lastReindex s i).val := by
  have h := sncReindex_mem_iff s ((sncReindex s).symm i)
  rw [Equiv.apply_symm_apply] at h
  rw [h]
  change _ ↔ n - s.card ≤ (Fin.rev ((sncReindex s).symm i)).val
  rw [Fin.val_rev]
  have h2 : s.card ≤ n := (Finset.card_le_univ s).trans (Fintype.card_fin n).le
  have h3 := ((sncReindex s).symm i).2
  omega

/-- Hauser's reindexing: `s` goes onto the last `s.card` positions and the distinguished member
`j ∈ s` (the coordinate of the hypersurface `V`) onto position `n - s.card`, Hauser's
`x_{n-k+1}`. -/
noncomputable def hauserReindex : Fin n ≃ Fin n :=
  (lastReindex s).trans (Equiv.swap (lastReindex s j) ⟨n - s.card, sub_card_lt s hj⟩)

theorem mem_iff_sub_card_le_hauserReindex (i : Fin n) :
    i ∈ s ↔ n - s.card ≤ (hauserReindex s hj i).val := by
  rw [mem_iff_sub_card_le_lastReindex]
  change _ ↔ n - s.card ≤ (Equiv.swap (lastReindex s j) ⟨n - s.card, sub_card_lt s hj⟩
    (lastReindex s i)).val
  have hjs : n - s.card ≤ (lastReindex s j).val := (mem_iff_sub_card_le_lastReindex s j).mp hj
  rw [Equiv.swap_apply_def]
  split_ifs with h1 h2
  · exact ⟨fun _ => le_rfl, fun _ => h1 ▸ hjs⟩
  · rw [h2]; exact ⟨fun _ => hjs, fun _ => le_rfl⟩
  · rfl

theorem hauserReindex_apply_self : hauserReindex s hj j = ⟨n - s.card, sub_card_lt s hj⟩ := by
  change Equiv.swap (lastReindex s j) ⟨n - s.card, sub_card_lt s hj⟩ (lastReindex s j) = _
  exact Equiv.swap_apply_left _ _

theorem image_hauserReindex :
    hauserReindex s hj '' ↑s = {i : Fin n | n - s.card ≤ i.val} := by
  ext i
  constructor
  · rintro ⟨i', hi', rfl⟩
    exact (mem_iff_sub_card_le_hauserReindex s hj i').mp hi'
  · intro hi
    refine ⟨(hauserReindex s hj).symm i, ?_, Equiv.apply_symm_apply _ _⟩
    rw [Finset.mem_coe, mem_iff_sub_card_le_hauserReindex s hj, Equiv.apply_symm_apply]
    exact hi

end Reindex

variable {X : Scheme.{u}} {ι : Type*} (E : ι → X.IdealSheafData) (Z : X.IdealSheafData) (v : ι)
  {a : X} {n : ℕ} {z : Fin n → X.presheaf.stalk a}

/-- [Hau14, Proposition 5.4 (1)–(3)] ([Hau03, Appendix C]): Kollár's snc data at a point `a` of the
centre `Z` for a family `E` whose member `v` contains `Z`, reindexed to Hauser's positions — a
regular system of parameters `z'` at `a`, snc coordinates for `E`, with `I_{V,a} = (z'_{n-k})` and
`I_{Z,a} = (z'_l : l ≥ n − k)`, `k = |s|` the codimension of `Z` at `a`. -/
theorem exists_hauser_coordinates [IsRegularLocalRing (X.presheaf.stalk a)] (hv : E v ≤ Z)
    (ha : a ∈ Z.support)
    (hz : span (Set.range z) = maximalIdeal (X.presheaf.stalk a) ∧
      (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk a))
    (c : {i : ι // a ∈ (E i).support} → Fin n) (hcinj : Function.Injective c)
    (hc : ∀ i, (E i.1).stalkIdeal a = span {z (c i)}) (s : Finset (Fin n))
    (hs : Z.stalkIdeal a = span (z '' ↑s)) :
    ∃ (k : ℕ) (hk : 1 ≤ k) (hkn : k ≤ n) (z' : Fin n → X.presheaf.stalk a),
      (span (Set.range z') = maximalIdeal (X.presheaf.stalk a) ∧
        (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk a)) ∧
      (∃ c' : {i : ι // a ∈ (E i).support} → Fin n, Function.Injective c' ∧
        ∀ i, (E i.1).stalkIdeal a = span {z' (c' i)}) ∧
      (E v).stalkIdeal a = span {z' ⟨n - k, by omega⟩} ∧
      Z.stalkIdeal a = span (z' '' {i | n - k ≤ i.val}) := by
  have hva : a ∈ (E v).support := Scheme.IdealSheafData.support_antitone hv ha
  -- the coordinate of `V` is one of the coordinates of `Z`
  have hcv : c ⟨v, hva⟩ ∈ s := by
    have hle := Scheme.IdealSheafData.stalkIdeal_mono hv a
    rw [hc ⟨v, hva⟩, hs] at hle
    exact (span_singleton_le_span_image_iff hz.1.symm hz.2 s _).mp hle
  have hk : 1 ≤ s.card := Finset.card_pos.mpr ⟨_, hcv⟩
  have hkn : s.card ≤ n := (Finset.card_le_univ s).trans (Fintype.card_fin n).le
  refine ⟨s.card, hk, hkn, z ∘ (hauserReindex s hcv).symm, ⟨?_, hz.2⟩,
    ⟨hauserReindex s hcv ∘ c, (hauserReindex s hcv).injective.comp hcinj, fun i => ?_⟩, ?_, ?_⟩
  · rw [Set.range_comp, Equiv.range_eq_univ, Set.image_univ, hz.1]
  · change _ = span {z ((hauserReindex s hcv).symm (hauserReindex s hcv (c i)))}
    rw [Equiv.symm_apply_apply]
    exact hc i
  · change _ = span {z ((hauserReindex s hcv).symm ⟨n - s.card, sub_card_lt s hcv⟩)}
    rw [← hauserReindex_apply_self s hcv, Equiv.symm_apply_apply]
    exact hc ⟨v, hva⟩
  · rw [hs, ← image_hauserReindex s hcv, Set.image_image]
    simp only [Function.comp_apply, Equiv.symm_apply_apply]

/-- [Hau14, Proposition 5.4 (4)] in `𝒪_{X,a}` ([Hau14, Remark 3.16, Remark 3.20]): for snc
coordinates `z` at `a` with `I_{V,a} = (z_p)`, the ideal `∏_{i ≠ v} I_{E^i,a}^{m_i}` of the divisor
`D = ∑_{i ≠ v} m_i E^i` is generated by a monomial `∏_j z_j^{q_j}` with `q_p = 0`. -/
theorem exists_prod_stalkIdeal_pow_eq_span_monomial [Fintype ι] [DecidableEq ι]
    [IsRegularLocalRing (X.presheaf.stalk a)]
    (hz : span (Set.range z) = maximalIdeal (X.presheaf.stalk a) ∧
      (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk a))
    (c : {i : ι // a ∈ (E i).support} → Fin n) (hcinj : Function.Injective c)
    (hc : ∀ i, (E i.1).stalkIdeal a = span {z (c i)}) {p : Fin n}
    (hV : (E v).stalkIdeal a = span {z p}) (m : ι → ℕ) :
    ∃ q : Fin n → ℕ, q p = 0 ∧
      ∏ i ∈ Finset.univ.filter (· ≠ v), (E i).stalkIdeal a ^ m i = span {∏ j, z j ^ q j} := by
  classical
  have hva : a ∈ (E v).support := by
    rw [Scheme.IdealSheafData.mem_support_iff_stalkIdeal_le_maximalIdeal, hV,
        Ideal.span_singleton_le_iff_mem]
    exact hz.1 ▸ subset_span ⟨p, rfl⟩
  have hp : c ⟨v, hva⟩ = p := by
    by_contra hne
    have h1 : z (c ⟨v, hva⟩) ∈ span {z p} := by
      rw [← hV, hc ⟨v, hva⟩]
      exact subset_span rfl
    have h2 := notMem_span_image_of_notMem hz.1.symm hz.2 (s := {p}) (j := c ⟨v, hva⟩)
      (by simpa using hne)
    rw [Finset.coe_singleton, Set.image_singleton] at h2
    exact h2 h1
  -- the generator of each factor
  let w : ι → X.presheaf.stalk a := fun i =>
    if h : a ∈ (E i).support then z (c ⟨i, h⟩) ^ m i else 1
  have hw : ∀ i, (E i).stalkIdeal a ^ m i = span {w i} := by
    intro i
    by_cases h : a ∈ (E i).support
    · simp only [w, dite_eq_left h]
      rw [hc ⟨i, h⟩, Ideal.span_singleton_pow]
    · simp only [w, dite_eq_right h]
      rw [Scheme.IdealSheafData.stalkIdeal_eq_top_of_notMem_support _ h, Ideal.top_pow,
          Ideal.span_singleton_one]
  -- the coordinate of a component (junk for a component missing `a`) and its multiplicity
  let g : ι → Fin n := fun i => if h : a ∈ (E i).support then c ⟨i, h⟩ else p
  let m' : ι → ℕ := fun i => if a ∈ (E i).support then m i else 0
  set F := Finset.univ.filter (· ≠ v) with hF
  refine ⟨fun j => ∑ i ∈ F.filter (fun i => g i = j), m' i, ?_, ?_⟩
  · refine Finset.sum_eq_zero fun i hi => ?_
    rw [Finset.mem_filter, hF, Finset.mem_filter] at hi
    obtain ⟨⟨-, hiv⟩, hgi⟩ := hi
    simp only [m']
    split_ifs with h
    · exfalso
      simp only [g, dite_eq_left h] at hgi
      exact hiv (congrArg Subtype.val (hcinj (hgi.trans hp.symm)))
    · rfl
  · rw [Finset.prod_congr rfl fun i _ => hw i, Ideal.prod_span_singleton]
    congr 2
    symm
    calc ∏ j, z j ^ (∑ i ∈ F.filter (fun i => g i = j), m' i)
        = ∏ j, ∏ i ∈ F.filter (fun i => g i = j), z j ^ m' i :=
          Finset.prod_congr rfl fun j _ => (Finset.prod_pow_eq_pow_sum _ _ _).symm
      _ = ∏ j, ∏ i ∈ F.filter (fun i => g i = j), w i := by
          refine Finset.prod_congr rfl fun j _ => Finset.prod_congr rfl fun i hi => ?_
          rw [Finset.mem_filter] at hi
          obtain ⟨-, hgi⟩ := hi
          simp only [w, m']
          split_ifs with h
          · simp only [g, dite_eq_left h] at hgi
            rw [hgi]
          · exact pow_zero _
      _ = ∏ i ∈ F, w i := Finset.prod_fiberwise_of_maps_to (fun i _ => Finset.mem_univ (g i)) w

/-- [Hau14, Proposition 5.4 (4)] as printed: `D ∩ V` is defined in `V` locally at `a` — in
`𝒪_{V,a} = 𝒪_{X,a} ⧸ I_{V,a}` — by the image of the monomial `∏_j z_j^{q_j}`, `q_p = 0`. -/
theorem exists_map_prod_stalkIdeal_pow_eq_span_monomial [Fintype ι] [DecidableEq ι]
    [IsRegularLocalRing (X.presheaf.stalk a)]
    (hz : span (Set.range z) = maximalIdeal (X.presheaf.stalk a) ∧
      (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk a))
    (c : {i : ι // a ∈ (E i).support} → Fin n) (hcinj : Function.Injective c)
    (hc : ∀ i, (E i.1).stalkIdeal a = span {z (c i)}) {p : Fin n}
    (hV : (E v).stalkIdeal a = span {z p}) (m : ι → ℕ) :
    ∃ q : Fin n → ℕ, q p = 0 ∧
      (∏ i ∈ Finset.univ.filter (· ≠ v), (E i).stalkIdeal a ^ m i).map
          (Ideal.Quotient.mk ((E v).stalkIdeal a)) =
        span {∏ j, Ideal.Quotient.mk ((E v).stalkIdeal a) (z j) ^ q j} := by
  obtain ⟨q, hq, hprod⟩ := exists_prod_stalkIdeal_pow_eq_span_monomial E v hz c hcinj hc hV m
  refine ⟨q, hq, ?_⟩
  rw [hprod, Ideal.map_span, Set.image_singleton, map_prod]
  simp only [map_pow]

end AlgebraicGeometry
