/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.ChartRing
public import Hironaka.Scheme.BlowUp.AffineBlowUp.Exceptional
public import Hironaka.Scheme.BlowUp.Defs
import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Membership
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.ChartRing
import Hironaka.Scheme.Smooth.LocalBlowUp
import Hironaka.Scheme.Smooth.LocalBlowUpStalk
import Mathlib.Algebra.Order.BigOperators.Ring.Finset

/-!
# The local blow-up at an arbitrary point of a chart

[Kol07, Definition 60] and [Hau14, Definitions 4.15–4.16]: for a point `x'` of `B_Z X` over `x`
lying in the chart of the coordinate `y_ρ` — the exceptional ideal at `x'` is generated by `π^* y_ρ`
— with `y` a regular system of parameters at `x` adapted to `Z` (`I_x = (y_0, …, y_{r-1})`,
`ρ = r − 1`), the stalk `𝒪_{B,x'}` is the localization of the chart ring
`R' = 𝒪_{X,x}[I_x/y_ρ] = chartRing y ρ` at a prime `𝔮` over `𝔪_x`, compatibly with `π^*`
(`exists_stalk_equiv_localization_atPrime`). `Hironaka.Scheme.Smooth.LocalBlowUp` proves this at the
origin of the chart (`exists_stalk_equiv_localization_chartOrigin_of_isIso`); the same assembly
works at every point once the point is located in the chart:

* the blow-up of `Spec 𝒪_{X,x}` along `I_x` is the base change of `B_Z X` along `Spec 𝒪_{X,x} → X`
  (`exists_isPullback_fromSpecStalk`), so `x'` — which lies over `x`, the image of the closed point
  — lifts to a point `t` of the local blow-up (Mathlib's `exists_preimage_of_isPullback`), and the
  stalks agree (`isIso_stalkMap_of_isPullback_fromSpecStalk`);
* the exceptional ideal of the local blow-up is the pullback of the exceptional ideal of `B_Z X`, so
  at `t` it is generated by the image of `y_ρ`, and `t` lies in the chart of `y_ρ` by the chart
  membership criterion (`affineBlowUp.mem_chart_iff`): `t = chart_{y_ρ}(q)` for a prime `q` of
  `𝒪_{X,x}[I_x/y_ρ]`, and that algebra is `chartRing y ρ`
  (`affineBlowUpAlgebra_stalkIdeal_eq_chartRing`);
* the stalk of the affine blow-up at `chart_{y_ρ}(q)` is the localization at `q`
  (`exists_ringEquiv_stalk_chart`), compatibly with germs; `q` lies over `𝔪_x` because `t` lies over
  the closed point (`chart_π`).

This is the chart model of a point that `Hironaka.Scheme.Snc.InducedCoordinates` and
`Hironaka.Scheme.Snc.ChartOrigin` read Hauser's (6)–(9) in.

Sources: [Kol07, Definition 60]; [Hau14, Definition 4.13; Definitions 4.15–4.16]; [Sta, Tag 0BFL].
-/

public section

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal Scheme.IdealSheafData

universe u

namespace AlgebraicGeometry

variable {X : Scheme.{u}}

/-- The stalk of the exceptional ideal of the local blow-up at a point `t` over `x'`, as the image
of the stalk of the exceptional ideal of `B_Z X` at `x'` under the (iso) stalk map of the base
change. -/
theorem stalkIdeal_exceptionalIdeal_eq_map_of_isPullback (Z : X.IdealSheafData) (x : X)
    {φ : affineBlowUp (Z.stalkIdeal x) ⟶ blowUp Z}
    (H : IsPullback φ (affineBlowUp.π (Z.stalkIdeal x)) (blowUpπ Z) (X.fromSpecStalk x))
    (t : affineBlowUp (Z.stalkIdeal x)) :
    (affineBlowUp.exceptionalIdeal (Z.stalkIdeal x)).stalkIdeal t =
      ((Z.comap (blowUpπ Z)).stalkIdeal (φ t)).map (φ.stalkMap t).hom := by
  rw [← Scheme.IdealSheafData.stalkIdeal_comap, ← Scheme.IdealSheafData.comap_comp, H.w,
    Scheme.IdealSheafData.comap_comp, comap_fromSpecStalk_eq_specIdealSheaf]
  rfl

section Generic

variable {Y B : Scheme.{u}} {x : X} (φ : Y ⟶ B) (ψ : Y ⟶ Spec (X.presheaf.stalk x)) (π : B ⟶ X)
  (hw : φ ≫ π = ψ ≫ X.fromSpecStalk x) (T : Y) (hx' : π (φ T) = x)

include hw hx'

/-- Along a base change of `Spec 𝒪_{X,x} → X`: `φ^♯` sends `π^*` of a germ at `π(φ T) = x` to
`ψ^♯` of the germ of the "constant" (`stalkMap_germ_eq_of_eq_comp_fromSpecStalk`, with the point
of the germ rewritten to `π (φ T)`). -/
theorem stalkMap_stalkMap_germ_eq (V : X.Opens) (hxV : x ∈ V) (s : Γ(X, V)) :
    φ.stalkMap T (π.stalkMap (φ T) (X.presheaf.germ V (π (φ T)) (hx' ▸ hxV) s)) =
      ψ.stalkMap T ((Spec (X.presheaf.stalk x)).presheaf.germ ⊤ (ψ T) trivial
        ((Scheme.ΓSpecIso (X.presheaf.stalk x)).inv (X.presheaf.germ V x hxV s))) := by
  have hV : (φ ≫ π) T ∈ V := hx' ▸ hxV
  have h := stalkMap_germ_eq_of_eq_comp_fromSpecStalk x (φ ≫ π) hw T V hxV hV s
  have h1 : φ.stalkMap T (π.stalkMap (φ T) (X.presheaf.germ V (π (φ T)) (hx' ▸ hxV) s)) =
      (φ ≫ π).stalkMap T (X.presheaf.germ V ((φ ≫ π) T) hV s) := by
    rw [Scheme.Hom.stalkMap_comp]
    rfl
  exact h1.trans h

/-- The image under `φ^♯` of a principal stalk ideal generated by `π^*` of a germ. -/
theorem map_stalkIdeal_eq_span_of_eq_span (Z : X.IdealSheafData) (V : X.Opens) (hxV : x ∈ V)
    (s : Γ(X, V))
    (hF : (Z.comap π).stalkIdeal (φ T) =
      span {π.stalkMap (φ T) (X.presheaf.germ V (π (φ T)) (hx' ▸ hxV) s)}) :
    ((Z.comap π).stalkIdeal (φ T)).map (φ.stalkMap T).hom =
      span {ψ.stalkMap T ((Spec (X.presheaf.stalk x)).presheaf.germ ⊤ (ψ T) trivial
        ((Scheme.ΓSpecIso (X.presheaf.stalk x)).inv (X.presheaf.germ V x hxV s)))} := by
  rw [hF, Ideal.map_span, Set.image_singleton, stalkMap_stalkMap_germ_eq φ ψ π hw T hx']

/-- The stalk isomorphism of a base change of `Spec 𝒪_{X,x} → X`, composed with an isomorphism
`e₁` of the stalk of `Y` with a ring `L` under which the germs of constants go to `g`, sends `π^*`
to `g`. -/
theorem ringEquiv_trans_stalkMap_eq [IsIso (φ.stalkMap T)] {L : Type u} [CommRing L]
    (e₁ : Y.presheaf.stalk T ≃+* L) (g : X.presheaf.stalk x →+* L)
    (h4 : ∀ (V : X.Opens) (hxV : x ∈ V) (s : Γ(X, V)),
      ψ.stalkMap T ((Spec (X.presheaf.stalk x)).presheaf.germ ⊤ (ψ T) trivial
        ((Scheme.ΓSpecIso (X.presheaf.stalk x)).inv (X.presheaf.germ V x hxV s))) =
      e₁.symm (g (X.presheaf.germ V x hxV s)))
    (c : X.presheaf.stalk (π (φ T))) :
    ((RingEquiv.ofBijective (φ.stalkMap T).hom (ConcreteCategory.bijective_of_isIso _)).trans e₁)
      (π.stalkMap (φ T) c) = g (hx' ▸ c) := by
  subst hx'
  obtain ⟨V, hxV, s, rfl⟩ := X.presheaf.exists_germ_eq c
  have hE : ∀ a, ((RingEquiv.ofBijective (φ.stalkMap T).hom
      (ConcreteCategory.bijective_of_isIso _)).trans e₁) a = e₁ (φ.stalkMap T a) := fun a => rfl
  rw [hE, stalkMap_stalkMap_germ_eq φ ψ π hw T rfl V hxV s, h4, RingEquiv.apply_symm_apply]

end Generic

/-- The lift of a point `x'` of `B_Z X` in the chart of `b` to the local blow-up: a prime `q` of
the chart algebra `𝒪_{X,x}[I_x/b]` with `φ (chart q) = x'`, lying over the maximal ideal. -/
theorem exists_chart_point_of_isPullback (Z : X.IdealSheafData) (x : X) (x' : blowUp Z)
    (hx' : blowUpπ Z x' = x) {b : X.presheaf.stalk x} (hmem : b ∈ Z.stalkIdeal x)
    {φ : affineBlowUp (Z.stalkIdeal x) ⟶ blowUp Z}
    (H : IsPullback φ (affineBlowUp.π (Z.stalkIdeal x)) (blowUpπ Z) (X.fromSpecStalk x))
    (V₀ : X.Opens) (hxV₀ : x ∈ V₀) (s₀ : Γ(X, V₀)) (hs₀ : X.presheaf.germ V₀ x hxV₀ s₀ = b)
    (hF : (Z.comap (blowUpπ Z)).stalkIdeal x' =
      span {(blowUpπ Z).stalkMap x' (X.presheaf.germ V₀ (blowUpπ Z x') (hx' ▸ hxV₀) s₀)}) :
    ∃ q : Spec (.of (affineBlowUpAlgebra (Z.stalkIdeal x) b)),
      φ (affineBlowUp.chart (Z.stalkIdeal x) ⟨b, hmem⟩ q) = x' ∧
      (PrimeSpectrum.asIdeal q).comap
          (algebraMap (X.presheaf.stalk x) (affineBlowUpAlgebra (Z.stalkIdeal x) b)) =
        maximalIdeal (X.presheaf.stalk x) := by
  have hxc : (blowUpπ Z).base x' =
      (X.fromSpecStalk x).base (closedPoint (X.presheaf.stalk x)) := by
    rw [Scheme.fromSpecStalk_closedPoint, hx']
  obtain ⟨t, hφt, hπt⟩ := Scheme.exists_preimage_of_isPullback H x' _ hxc
  change φ t = x' at hφt
  subst hφt
  have hchart : t ∈ (affineBlowUp.chart (Z.stalkIdeal x) ⟨b, hmem⟩).opensRange := by
    rw [affineBlowUp.mem_chart_iff, stalkIdeal_exceptionalIdeal_eq_map_of_isPullback Z x H t,
      map_stalkIdeal_eq_span_of_eq_span φ (affineBlowUp.π (Z.stalkIdeal x)) (blowUpπ Z) H.w t
        hx' Z V₀ hxV₀ s₀ hF, hs₀]
    rfl
  obtain ⟨q, hq⟩ := Scheme.Hom.mem_opensRange.mp hchart
  subst hq
  refine ⟨q, rfl, ?_⟩
  change (affineBlowUp.chart (Z.stalkIdeal x) ⟨b, hmem⟩ ≫ affineBlowUp.π (Z.stalkIdeal x)) q =
    closedPoint _ at hπt
  rw [affineBlowUp.chart_π, Spec.map_apply] at hπt
  exact congrArg PrimeSpectrum.asIdeal hπt

/-- The chart model at an arbitrary point of the chart, in the chart algebra `𝒪_{X,x}[I_x/y_ρ]` (the
form before the identification with `chartRing y ρ`), over an abstract base point `x` with `x' ↦ x`.
-/
theorem exists_stalk_equiv_localization_atPrime_aux (Z : X.IdealSheafData) (x : X)
    (x' : blowUp Z) (hx' : blowUpπ Z x' = x) {n r : ℕ} (y : Fin n → X.presheaf.stalk x)
    (hZ : Z.stalkIdeal x = span (y '' {i | i.val < r})) (ρ : Fin n) (hρ : ρ.val + 1 = r)
    (V₀ : X.Opens) (hxV₀ : x ∈ V₀) (s₀ : Γ(X, V₀)) (hs₀ : X.presheaf.germ V₀ x hxV₀ s₀ = y ρ)
    (hF : (Z.comap (blowUpπ Z)).stalkIdeal x' =
      span {(blowUpπ Z).stalkMap x' (X.presheaf.germ V₀ (blowUpπ Z x') (hx' ▸ hxV₀) s₀)}) :
    ∃ (𝔮 : Ideal (affineBlowUpAlgebra (Z.stalkIdeal x) (y ρ))) (_ : 𝔮.IsPrime)
      (e : (blowUp Z).presheaf.stalk x' ≃+* Localization.AtPrime 𝔮),
      𝔮.comap (algebraMap (X.presheaf.stalk x) (affineBlowUpAlgebra (Z.stalkIdeal x) (y ρ))) =
        maximalIdeal (X.presheaf.stalk x) ∧
      ∀ c : X.presheaf.stalk (blowUpπ Z x'),
        e ((blowUpπ Z).stalkMap x' c) =
          algebraMap (affineBlowUpAlgebra (Z.stalkIdeal x) (y ρ)) _ (algebraMap _ _ (hx' ▸ c)) := by
  classical
  obtain ⟨φ, H⟩ := exists_isPullback_fromSpecStalk Z x
  have hmem : y ρ ∈ Z.stalkIdeal x :=
    hZ ▸ Ideal.subset_span ⟨ρ, show ρ.val < r by omega, rfl⟩
  obtain ⟨q, hφq, hqm⟩ :=
    exists_chart_point_of_isPullback Z x x' hx' hmem H V₀ hxV₀ s₀ hs₀ hF
  -- the stalk at the chart point is the localization of the chart algebra at `q`
  obtain ⟨e₁, he₁⟩ := exists_ringEquiv_stalk_chart (Z.stalkIdeal x) ⟨y ρ, hmem⟩ q
  have hi := (ConcreteCategory.bijective_of_isIso
    ((affineBlowUp.chart (Z.stalkIdeal x) ⟨y ρ, hmem⟩).stalkMap q)).1
  have h2 := stalkMap_chart_stalkMap_π (Z.stalkIdeal x) ⟨y ρ, hmem⟩ q
  let g : X.presheaf.stalk x →+*
      Localization.AtPrime (PrimeSpectrum.asIdeal q) (hp := PrimeSpectrum.isPrime q) :=
    (algebraMap (affineBlowUpAlgebra (Z.stalkIdeal x) (y ρ)) _).comp
      (algebraMap _ (affineBlowUpAlgebra (Z.stalkIdeal x) (y ρ)))
  have h4 : ∀ (V : X.Opens) (hxV : x ∈ V) (s : Γ(X, V)),
      (affineBlowUp.π (Z.stalkIdeal x)).stalkMap
          (affineBlowUp.chart (Z.stalkIdeal x) ⟨y ρ, hmem⟩ q)
          ((Spec (X.presheaf.stalk x)).presheaf.germ ⊤
            (affineBlowUp.π (Z.stalkIdeal x) (affineBlowUp.chart (Z.stalkIdeal x) ⟨y ρ, hmem⟩ q))
            trivial ((Scheme.ΓSpecIso (X.presheaf.stalk x)).inv (X.presheaf.germ V x hxV s))) =
        e₁.symm (g (X.presheaf.germ V x hxV s)) := fun V hxV s =>
    hi ((h2 (X.presheaf.germ V x hxV s)).trans (he₁ _).symm)
  have hiso := isIso_stalkMap_of_isPullback_fromSpecStalk H
    (affineBlowUp.chart (Z.stalkIdeal x) ⟨y ρ, hmem⟩ q)
  subst hφq
  have key := ringEquiv_trans_stalkMap_eq φ (affineBlowUp.π (Z.stalkIdeal x)) (blowUpπ Z) H.w
    (affineBlowUp.chart (Z.stalkIdeal x) ⟨y ρ, hmem⟩ q) hx' e₁ g h4
  exact ⟨PrimeSpectrum.asIdeal q, PrimeSpectrum.isPrime q, _, hqm, key⟩

/-- The chart model at an arbitrary point of the chart ([Kol07, Definition 60];
[Hau14, Definitions 4.15–4.16]): for `x'` a point of `B_Z X` over `x` in the chart of `y_ρ` —
`F_{x'} = (π^* y_ρ)` — with `y` a regular system of parameters at `x` adapted to `Z`
(`I_x = (y_0, …, y_{r-1})`, `ρ + 1 = r`), the stalk `𝒪_{B,x'}` is the localization of the chart ring
`chartRing y ρ` at a prime `𝔮` lying over `𝔪_x`, compatibly with `π^*`. -/
theorem exists_stalk_equiv_localization_atPrime (Z : X.IdealSheafData) (x' : blowUp Z)
    {n r : ℕ} (y : Fin n → X.presheaf.stalk (blowUpπ Z x'))
    (hZ : Z.stalkIdeal (blowUpπ Z x') = span (y '' {i | i.val < r})) (ρ : Fin n)
    (hρ : ρ.val + 1 = r)
    (hF : (Z.comap (blowUpπ Z)).stalkIdeal x' = span {(blowUpπ Z).stalkMap x' (y ρ)}) :
    ∃ (𝔮 : Ideal (chartRing y ρ)) (_ : 𝔮.IsPrime)
      (e : (blowUp Z).presheaf.stalk x' ≃+* Localization.AtPrime 𝔮),
      𝔮.comap (algebraMap (X.presheaf.stalk (blowUpπ Z x')) (chartRing y ρ)) =
        maximalIdeal (X.presheaf.stalk (blowUpπ Z x')) ∧
      ∀ c : X.presheaf.stalk (blowUpπ Z x'),
        e ((blowUpπ Z).stalkMap x' c) = algebraMap (chartRing y ρ) _ (algebraMap _ _ c) := by
  obtain ⟨V₀, hxV₀, s₀, hs₀⟩ := X.presheaf.exists_germ_eq (y ρ)
  have hF₀ : (Z.comap (blowUpπ Z)).stalkIdeal x' =
      span {(blowUpπ Z).stalkMap x' (X.presheaf.germ V₀ (blowUpπ Z x') hxV₀ s₀)} := by
    rw [hs₀]
    exact hF
  have h := exists_stalk_equiv_localization_atPrime_aux Z (blowUpπ Z x') x' rfl y hZ ρ hρ V₀ hxV₀
    s₀ hs₀ hF₀
  have hC := affineBlowUpAlgebra_stalkIdeal_eq_chartRing Z _ hZ ρ hρ
  generalize affineBlowUpAlgebra (Z.stalkIdeal (blowUpπ Z x')) (y ρ) = C at hC h
  subst hC
  exact h

end AlgebraicGeometry
