/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
public import Hironaka.Scheme.Snc.Defs
import Hironaka.Algebra.Local.Regular
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Snc.ChartIndex
import Hironaka.Scheme.Snc.ChartOrigin
import Hironaka.Scheme.Snc.HypersurfaceCoordinates
import Hironaka.Scheme.Snc.InducedCoordinates
import Hironaka.Scheme.Snc.TotalTransformChartComputation
import Hironaka.Scheme.Snc.TotalTransformOnCentre
import Hironaka.Scheme.Snc.TotalTransformSnc
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded
import Hironaka.Scheme.BlowUp.CoordinateSubspace.Smooth
import Hironaka.Scheme.Snc.TotalTransformSmoothBlowUp
import Hironaka.Scheme.Smooth.Graph
/-!
# Adapted coordinates in which the blow-up is monomial

[Hau14, Proposition 5.4 (1)–(9)] stated on the predicates `IsSncAt`, `HasSncWith`,
`IsRegularSystemOfParameters` and `stalkIdeal` and on `Z.blowUp`, `Z.exceptionalDivisor` and
`strictTransform Z D` (`Z.exceptionalDivisor` is `Z.comap (IdealSheafData.blowUpπ Z)` and
`strictTransform Z D` is `strictTransformAlong (IdealSheafData.blowUpπ Z) (Z.comap π) D` by
definition): a smooth `X` over a perfect field `k`, an snc family `E` having simple normal crossings
with the centre `Z`, a member `V = E v` containing `Z`, a point `a` of `Z` and a point `a'` of the
exceptional divisor over `a`. The proofs are those of the modules of `Hironaka.Snc` on the unfolded
data, which `hasSncWith_data` extracts from `E.HasSncWith Z`:

* (1)–(4): `exists_coordinates_hypersurface_center`, `exists_sncAt_coordinates_hypersurface_center`
  (Hauser's positions by reindexing the snc data at `a`,
  `Hironaka.Scheme.Snc.HypersurfaceCoordinates`), `exists_prod_stalkIdeal_pow_eq_span_monomial'`,
  `exists_map_prod_stalkIdeal_pow_eq_span_monomial'`;
* (5)–(7): `exists_chart_index'`, `mem_maximalIdeal_iff_mem_support_strictTransform`,
  `stalkIdeal_strictTransform_hypersurface` (`Hironaka.Scheme.Snc.ChartIndex`), with the centre's
  index set `s = {i | n − k ≤ i}` as a `Finset`;
* (6), the coordinate content: `exists_isRegularSystemOfParameters_induced'`
  (`Hironaka.Scheme.Snc.InducedCoordinates`), with the regularity of `𝒪_{B,a'}` and `π^* z_j ≠ 0`
  from the chart shape of the total transform (`Hironaka.Scheme.Snc.TotalTransformSnc`);
* (8)–(9): `exists_shiftCoords_chartOrigin'`, `exists_coordinates_chartOrigin`
  (`Hironaka.Scheme.Snc.ChartOrigin`), the rationality hypothesis read as the bijectivity of the
  residue field map (`bijective_of_isIso_residueFieldMap`) and the clause on the strict transform of
  `V` through (6);
* Hauser's setting of closed points over an algebraically closed field:
  `isIso_residueFieldMap_of_isClosed` of `Hironaka.Scheme.Snc.ClosedPointRational` discharges the
  rationality hypothesis.

The primed names are the forms on the predicates of the correspondingly named lemmas of those
modules; each docstring names its original. [Hau14, Example 4.53] (the positive half) is the
`example` at the end. This module is the statement of Hauser's proposition in the library's
vocabulary and is not used further.

Sources: [Hau14, Proposition 5.4; Example 4.53]; [Hau03, Appendix C];
[Kol07, Definition 24; Definition 60; Lemma 61].
-/

public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal Scheme.IdealSheafData
  Scheme DivisorFamily
open AlgebraicGeometry

namespace AlgebraicGeometry


variable {k : Type u} [Field k] {X : Scheme.{u}}

/-- The centre's index set `{i | n − k ≤ i}` as a `Finset`, with its coercion. -/
theorem coe_centreFinset (n k : ℕ) :
    ((Finset.univ.filter fun i : Fin n => n - k ≤ i.val : Finset (Fin n)) : Set (Fin n)) =
      {i | n - k ≤ i.val} := by
  ext i
  simp

section

/-- The centre's ideal at `π a'` in the `Finset` form of `Hironaka.Scheme.Snc.ChartIndex`. -/
theorem hs_finset (Z : X.IdealSheafData) (a' : Z.blowUp) {n k : ℕ}
    {z : Fin n → X.presheaf.stalk (Z.blowUpπ a')}
    (hZa : Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z '' {i | n - k ≤ i.val})) :
    Z.stalkIdeal (Z.blowUpπ a') =
      span (z '' ↑(Finset.univ.filter fun i : Fin n => n - k ≤ i.val)) := by
  rw [coe_centreFinset]
  exact hZa

/-- `π^* z_j ≠ 0`: the exceptional ideal at `a'` is nonzero, being generated by a member of a
regular system of parameters (`TotalTransformData`). -/
theorem stalkMap_ne_zero [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f] (E : DivisorFamily X)
    (Z : X.IdealSheafData) (hZ : E.HasSncWith Z) (a' : Z.blowUp)
    (ha' : a' ∈ Z.exceptionalDivisor.support) {n : ℕ}
    {z : Fin n → X.presheaf.stalk (Z.blowUpπ a')} {j : Fin n}
    (hF : Z.exceptionalDivisor.stalkIdeal a' = Ideal.span {Z.blowUpπ.stalkMap a'
        (z j)}) :
    Z.blowUpπ.stalkMap a' (z j) ≠ 0 := by
  intro h0
  apply stalkIdeal_comap_π_ne_bot f E.component Z (hasSncWith_data E Z hZ) a' ha'
  rw [show (Z.comap (IdealSheafData.blowUpπ Z)).stalkIdeal a' = Ideal.span
      {Z.blowUpπ.stalkMap a' (z j)}
    from hF, h0, Ideal.span_singleton_eq_bot]

/-- The rationality hypothesis — `a'` rational over `κ(a)` — in the form the chart-origin lemmas
take: the residue field map is bijective. -/
theorem bijective_of_isIso_residueFieldMap (Z : X.IdealSheafData) (a' : Z.blowUp)
    (hrat : IsIso (Z.blowUpπ.residueFieldMap a')) :
    Function.Bijective (IsLocalRing.ResidueField.map ((IdealSheafData.blowUpπ Z).stalkMap a').hom)
        :=
  ConcreteCategory.bijective_of_isIso (Z.blowUpπ.residueFieldMap a')

/-- [Hau14, Proposition 5.4 (1)–(3)] on the predicates: for an snc family `E` having simple normal
crossings with `Z` and a member `E v` containing `Z`, at every point `a` of `Z` there is a regular
system of parameters `z` with `I_{V,a} = (z_{n-k})` and `I_{Z,a} = (z_l : l ≥ n − k)`, `1 ≤ k ≤ n` —
`exists_hauser_coordinates` of `Hironaka.Scheme.Snc.HypersurfaceCoordinates` on the data of
`hasSncWith_data`. The hypothesis `E.IsSnc` is part of Hauser's setting (`D` a normal crossings
divisor) and is kept so that the statements of this module share his hypotheses; the proof does not
need it, because clauses (1)–(3) use only the snc data of `E.HasSncWith Z` at `a`. -/
theorem exists_coordinates_hypersurface_center (f : X ⟶ Spec (.of k))
    [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (hv : E.component v ≤ Z) (a : X) (ha : a ∈ Z.support) :
    ∃ (n k : ℕ) (hk : 1 ≤ k) (hkn : k ≤ n) (z : Fin n → X.presheaf.stalk a),
      IsRegularSystemOfParameters z ∧
      (E.component v).stalkIdeal a = Ideal.span {z ⟨n - k, by omega⟩} ∧
      Z.stalkIdeal a = Ideal.span (z '' {i | n - k ≤ i.val}) := by
  have hreg : IsRegularLocalRing (X.presheaf.stalk a) :=
    isRegularLocalRing_stalk f a
  obtain ⟨n, z, hrs, ⟨c, hcinj, hc⟩, s, hs⟩ := hasSncWith_data E Z hZ a ha
  obtain ⟨kk, hk, hkn, z', hrs', -, hV, hZ'⟩ :=
    exists_hauser_coordinates E.component Z v hv ha hrs c hcinj hc s hs
  exact ⟨n, kk, hk, hkn, z', hrs', hV, hZ'⟩

/-- `exists_coordinates_hypersurface_center` keeping the snc coordinates for `E`: the regular system
of parameters `z` at `a` satisfies `E.IsSncAt a z` as well as `I_{V,a} = (z_{n-k})` and
`I_{Z,a} = (z_l : l ≥ n − k)`. The hypothesis `E.IsSnc` is part of Hauser's setting and is kept so
that the statements of this module share his hypotheses; the proof does not need it, because only
the snc data of `E.HasSncWith Z` at `a` enter. -/
theorem exists_sncAt_coordinates_hypersurface_center (f : X ⟶ Spec (.of k))
    [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (hv : E.component v ≤ Z) (a : X) (ha : a ∈ Z.support) :
    ∃ (n k : ℕ) (hk : 1 ≤ k) (hkn : k ≤ n) (z : Fin n → X.presheaf.stalk a),
      E.IsSncAt a z ∧
      (E.component v).stalkIdeal a = Ideal.span {z ⟨n - k, by omega⟩} ∧
      Z.stalkIdeal a = Ideal.span (z '' {i | n - k ≤ i.val}) := by
  have hreg : IsRegularLocalRing (X.presheaf.stalk a) :=
    isRegularLocalRing_stalk f a
  obtain ⟨n, z, hrs, ⟨c, hcinj, hc⟩, s, hs⟩ := hasSncWith_data E Z hZ a ha
  obtain ⟨kk, hk, hkn, z', hrs', ⟨c', hc'inj, hc'⟩, hV, hZ'⟩ :=
    exists_hauser_coordinates E.component Z v hv ha hrs c hcinj hc s hs
  exact ⟨n, kk, hk, hkn, z', ⟨hrs', c', hc'inj, hc'⟩, hV, hZ'⟩

/-- [Hau14, Proposition 5.4 (4)] in `𝒪_{X,a}`, on the predicate `IsSncAt`: the ideal
`∏_{i ≠ v} I_{E^i,a}^{m_i}` of the divisor `D = ∑_{i ≠ v} m_i E^i` is generated by a monomial
`∏_j z_j^{q_j}` with `q_{n-k} = 0`. This is `exists_prod_stalkIdeal_pow_eq_span_monomial` of
`Hironaka.Scheme.Snc.HypersurfaceCoordinates` with the snc data packed into `E.IsSncAt a z`; the
hypotheses of Hauser's setting (`E` snc, `E.HasSncWith Z`, `E v ≤ Z`, `a ∈ Z`) are kept so that the
statement reads as clause (4) of his proposition; the proof does not need them, because the clause
is a statement about the stalk at `a` given `E.IsSncAt a z` and `I_{V,a} = (z_{n-k})`. -/
theorem exists_prod_stalkIdeal_pow_eq_span_monomial' (f : X ⟶ Spec (.of k))
    [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (_hZ : E.HasSncWith Z) (v : E.ι)
    (_hv : E.component v ≤ Z) (a : X) (_ha : a ∈ Z.support) {n k : ℕ} (hk : 1 ≤ k) (hkn : k ≤ n)
    {z : Fin n → X.presheaf.stalk a} (hz : E.IsSncAt a z)
    (hV : (E.component v).stalkIdeal a = Ideal.span {z ⟨n - k, by omega⟩}) (m : E.ι → ℕ) :
    ∃ q : Fin n → ℕ, q ⟨n - k, by omega⟩ = 0 ∧
      ∏ i ∈ Finset.univ.filter (· ≠ v), (E.component i).stalkIdeal a ^ m i =
        Ideal.span {∏ j, z j ^ q j} := by
  have hreg : IsRegularLocalRing (X.presheaf.stalk a) :=
    isRegularLocalRing_stalk f a
  obtain ⟨hrs, c, hcinj, hc⟩ := hz
  exact exists_prod_stalkIdeal_pow_eq_span_monomial E.component v hrs c hcinj hc hV m

/-- [Hau14, Proposition 5.4 (4)] as printed, on the predicate `IsSncAt`: `D ∩ V` is defined in `V`
locally at `a` — in `𝒪_{V,a} = 𝒪_{X,a} ⧸ I_{V,a}` — by the image of a monomial `∏_j z_j^{q_j}` with
`q_{n-k} = 0`. This is `exists_map_prod_stalkIdeal_pow_eq_span_monomial` of
`Hironaka.Scheme.Snc.HypersurfaceCoordinates` with the snc data packed into `E.IsSncAt a z`; the
hypotheses of Hauser's setting (`E` snc, `E.HasSncWith Z`, `E v ≤ Z`, `a ∈ Z`) are kept so that the
statement reads as clause (4) of his proposition; the proof does not need them, because the clause
is a statement about the stalk at `a` given `E.IsSncAt a z` and `I_{V,a} = (z_{n-k})`. -/
theorem exists_map_prod_stalkIdeal_pow_eq_span_monomial' (f : X ⟶ Spec (.of k))
    [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (_hZ : E.HasSncWith Z) (v : E.ι)
    (_hv : E.component v ≤ Z) (a : X) (_ha : a ∈ Z.support) {n k : ℕ} (hk : 1 ≤ k) (hkn : k ≤ n)
    {z : Fin n → X.presheaf.stalk a} (hz : E.IsSncAt a z)
    (hV : (E.component v).stalkIdeal a = Ideal.span {z ⟨n - k, by omega⟩}) (m : E.ι → ℕ) :
    ∃ q : Fin n → ℕ, q ⟨n - k, by omega⟩ = 0 ∧
      (∏ i ∈ Finset.univ.filter (· ≠ v), (E.component i).stalkIdeal a ^ m i).map
          (Ideal.Quotient.mk ((E.component v).stalkIdeal a)) =
        Ideal.span {∏ j, Ideal.Quotient.mk ((E.component v).stalkIdeal a) (z j) ^ q j} := by
  have hreg : IsRegularLocalRing (X.presheaf.stalk a) :=
    isRegularLocalRing_stalk f a
  obtain ⟨hrs, c, hcinj, hc⟩ := hz
  exact exists_map_prod_stalkIdeal_pow_eq_span_monomial E.component v hrs c hcinj hc
    hV m

/-- [Hau14, Proposition 5.4 (5)], with the clause on the strict transform of `V` from (9), on the
predicates and `Z.blowUp`: a point `a'` of the exceptional divisor lies in the chart of
some centre coordinate `z_j` (`F_{a'} = (π^* z_j)`), every centre coordinate is a multiple of
`π^* z_j` there, and `j ≠ n − k` where `a'` lies on the strict transform of `V`. This is
`exists_chart_index` with `ne_of_mem_support_strictTransformAlong` of
`Hironaka.Scheme.Snc.ChartIndex`, the centre's index set being `{i | n − k ≤ i}`. -/
theorem exists_chart_index' [PerfectField k] (f : X ⟶ Spec (.of k))
    [Smooth f] (E : DivisorFamily X)
    (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (_hv : E.component v ≤ Z) (a' : Z.blowUp) (ha' : a' ∈
        Z.exceptionalDivisor.support)
    {n k : ℕ} (hk : 1 ≤ k) (hkn : k ≤ n) {z : Fin n → X.presheaf.stalk (Z.blowUpπ a')}
    (_hz : E.IsSncAt (Z.blowUpπ a') z)
    (hV : (E.component v).stalkIdeal (Z.blowUpπ a') = Ideal.span {z ⟨n - k, by omega⟩})
    (hZa : Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z '' {i | n - k ≤ i.val})) :
    ∃ j : Fin n, n - k ≤ j.val ∧
      Z.exceptionalDivisor.stalkIdeal a' = Ideal.span {Z.blowUpπ.stalkMap a'
          (z j)} ∧
      (∀ i : Fin n, n - k ≤ i.val → ∃ y : Z.blowUp.presheaf.stalk a',
        Z.blowUpπ.stalkMap a' (z i) = y * Z.blowUpπ.stalkMap a' (z j)) ∧
      (a' ∈ ((E.component v).strictTransform Z).support → j.val ≠ n - k) := by
  obtain ⟨j, hj, hF, hy⟩ := exists_chart_index f E.component Z
    (hasSncWith_data E Z hZ) a' ha' (hs_finset Z a' hZa)
  rw [Finset.mem_filter] at hj
  refine ⟨j, hj.2, hF, fun i hi => hy i (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hi⟩),
    fun hmem hjv => ?_⟩
  exact ne_of_mem_support_strictTransformAlong E.component Z a' hV hF hmem (Fin.ext hjv)

/-- [Hau14, Proposition 5.4 (6)] on the predicates: the entry `y` of `a'` at the coordinate of a
component `E^i = (z_c = 0)` containing `Z` (`π^* z_c = y · π^* z_j`) lies in `𝔪_{a'}` exactly when
the strict transform of `E^i` passes through `a'` —
`mem_maximalIdeal_iff_mem_support_strictTransformAlong` of `Hironaka.Scheme.Snc.ChartIndex`. -/
theorem mem_maximalIdeal_iff_mem_support_strictTransform [PerfectField k] (f : X ⟶ Spec (.of k))
    [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (_hv : E.component v ≤ Z) (a' : Z.blowUp)
        (ha' : a' ∈ Z.exceptionalDivisor.support)
    {n k : ℕ} (hk : 1 ≤ k) (hkn : k ≤ n) {z : Fin n → X.presheaf.stalk (Z.blowUpπ a')}
    (hz : E.IsSncAt (Z.blowUpπ a') z)
    (_hV : (E.component v).stalkIdeal (Z.blowUpπ a') = Ideal.span {z ⟨n - k, by omega⟩})
    (hZa : Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z '' {i | n - k ≤ i.val}))
        {j : Fin n}
    (_hj : n - k ≤ j.val)
    (hF : Z.exceptionalDivisor.stalkIdeal a' = Ideal.span {Z.blowUpπ.stalkMap a'
        (z j)})
    {i : E.ι} {c : Fin n}
    (hc : (E.component i).stalkIdeal (Z.blowUpπ a') = Ideal.span {z c})
        (hcs : n - k ≤ c.val)
    (_hcj : c ≠ j) {y : Z.blowUp.presheaf.stalk a'}
    (hy : Z.blowUpπ.stalkMap a' (z c) = y * Z.blowUpπ.stalkMap a' (z j)) :
    y ∈ IsLocalRing.maximalIdeal (Z.blowUp.presheaf.stalk a') ↔
      a' ∈ ((E.component i).strictTransform Z).support :=
  mem_maximalIdeal_iff_mem_support_strictTransformAlong f E.component Z (hasSncWith_data E Z hZ)
    a' ha' hz.1 (hs_finset Z a' hZa) hc (Finset.mem_filter.mpr ⟨Finset.mem_univ _, hcs⟩) hF hy

/-- [Hau14, Proposition 5.4 (6)], the coordinate content, on the predicates and
`Z.blowUp`: the induced coordinates `w` of the `z_j`-chart vanishing at `a'` extend to a
regular system of parameters of `𝒪_{B,a'}`. This is `exists_isRegularSystemOfParameters_induced` of
`Hironaka.Scheme.Snc.InducedCoordinates`, the regularity of `𝒪_{B,a'}` and `π^* z_j ≠ 0` supplied
from the snc data (`isRegularLocalRing_stalk_blowUp'`, `stalkMap_ne_zero`). -/
theorem exists_isRegularSystemOfParameters_induced' [PerfectField k] (f : X ⟶ Spec (.of k))
    [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (_hv : E.component v ≤ Z) (a' : Z.blowUp)
        (ha' : a' ∈ Z.exceptionalDivisor.support)
    {n k : ℕ} (hk : 1 ≤ k) (hkn : k ≤ n) {z : Fin n → X.presheaf.stalk (Z.blowUpπ a')}
    (hz : E.IsSncAt (Z.blowUpπ a') z)
    (_hV : (E.component v).stalkIdeal (Z.blowUpπ a') = Ideal.span {z ⟨n - k, by omega⟩})
    (hZa : Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z '' {i | n - k ≤ i.val}))
        {j : Fin n}
    (hj : n - k ≤ j.val)
    (hF : Z.exceptionalDivisor.stalkIdeal a' = Ideal.span {Z.blowUpπ.stalkMap a'
        (z j)})
    (w : Fin n → Z.blowUp.presheaf.stalk a')
    (hw : ∀ i : Fin n, i.val < n - k ∨ i = j → w i = Z.blowUpπ.stalkMap a' (z i))
    (hw' : ∀ i : Fin n, n - k ≤ i.val → i ≠ j →
      Z.blowUpπ.stalkMap a' (z i) = w i * Z.blowUpπ.stalkMap a' (z j)) :
    ∃ (m : ℕ) (z' : Fin m → Z.blowUp.presheaf.stalk a'), IsRegularSystemOfParameters
        z' ∧
      ∃ σ :
          {i : Fin n // w i ∈ IsLocalRing.maximalIdeal (Z.blowUp.presheaf.stalk a')} →
              Fin m,
        Function.Injective σ ∧ ∀ i, z' (σ i) = w i.1 := by
  have hreg : IsRegularLocalRing (Z.blowUp.presheaf.stalk a') :=
    isRegularLocalRing_stalk_blowUp' f E.component Z (hasSncWith_data E Z hZ) a'
  exact exists_isRegularSystemOfParameters_induced f Z a' hk hkn hz.1 hZa hj hF
    (stalkMap_ne_zero f E Z hZ a' ha' hF) w hw hw'

/-- [Hau14, Proposition 5.4 (7)] on the predicates: in the chart of `z_j`, `j ≠ n − k`, with
`π^* z_{n-k} = y · π^* z_j`, the strict transform of `V = E v` at `a'` is `(y)` —
`stalkIdeal_strictTransformAlong_eq_span_of_eq_mul` of `Hironaka.Scheme.Snc.ChartIndex`. -/
theorem stalkIdeal_strictTransform_hypersurface [PerfectField k] (f : X ⟶ Spec (.of k))
    [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (_hv : E.component v ≤ Z) (a' : Z.blowUp)
        (ha' : a' ∈ Z.exceptionalDivisor.support)
    {n k : ℕ} (hk : 1 ≤ k) (hkn : k ≤ n) {z : Fin n → X.presheaf.stalk (Z.blowUpπ a')}
    (hz : E.IsSncAt (Z.blowUpπ a') z)
    (hV : (E.component v).stalkIdeal (Z.blowUpπ a') = Ideal.span {z ⟨n - k, by omega⟩})
    (hZa : Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z '' {i | n - k ≤ i.val}))
        {j : Fin n}
    (_hj : n - k ≤ j.val)
    (hF : Z.exceptionalDivisor.stalkIdeal a' = Ideal.span {Z.blowUpπ.stalkMap a'
        (z j)})
    (_hjV : j.val ≠ n - k) {y : Z.blowUp.presheaf.stalk a'}
    (hy : Z.blowUpπ.stalkMap a' (z ⟨n - k,
        by omega⟩) = y * Z.blowUpπ.stalkMap a' (z j)) :
    ((E.component v).strictTransform Z).stalkIdeal a' = Ideal.span {y} :=
  stalkIdeal_strictTransformAlong_eq_span_of_eq_mul f E.component Z (hasSncWith_data E Z hZ) a'
    ha' hz.1 (hs_finset Z a' hZa) hV (Finset.mem_filter.mpr ⟨Finset.mem_univ _, le_rfl⟩) hF hy

/-- [Hau14, Proposition 5.4 (8)] on the predicates and `Z.blowUp`: for `a'` rational over
`κ(a)` (`IsIso` of the residue field map) in the chart of `z_j`, the coordinates
`z'_i = z_i − α_i z_j` on the other centre coordinates make `a'` the origin of the chart and the
local blow-up monomial, preserve `I_Z`, and leave the coordinate of `V` unchanged where `a'` lies on
the strict transform of `V`. This is `exists_shiftCoords_chartOrigin` of
`Hironaka.Scheme.Snc.ChartOrigin`, the last clause obtained through (6). -/
theorem exists_shiftCoords_chartOrigin' [PerfectField k] (f : X ⟶ Spec (.of k))
    [Smooth f] (E : DivisorFamily X)
    (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (_hv : E.component v ≤ Z) (a' : Z.blowUp) (ha' : a' ∈
        Z.exceptionalDivisor.support)
    {n k : ℕ} (hk : 1 ≤ k) (hkn : k ≤ n) {z : Fin n → X.presheaf.stalk (Z.blowUpπ a')}
    (hz : E.IsSncAt (Z.blowUpπ a') z)
    (hV : (E.component v).stalkIdeal (Z.blowUpπ a') = Ideal.span {z ⟨n - k, by omega⟩})
    (hZa : Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z '' {i | n - k ≤ i.val}))
        {j : Fin n}
    (hj : n - k ≤ j.val)
    (hF : Z.exceptionalDivisor.stalkIdeal a' = Ideal.span {Z.blowUpπ.stalkMap a'
        (z j)})
    (hrat : IsIso (Z.blowUpπ.residueFieldMap a')) :
    ∃ z' : Fin n → X.presheaf.stalk (Z.blowUpπ a'),
      IsRegularSystemOfParameters z' ∧
      (∀ i : Fin n, i.val < n - k ∨ i = j → z' i = z i) ∧
      (∀ i : Fin n, n - k ≤ i.val → ∃ α : X.presheaf.stalk (Z.blowUpπ a'),
        z' i = z i - α * z j) ∧
      Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z' '' {i | n - k ≤ i.val}) ∧
      (a' ∈ ((E.component v).strictTransform Z).support →
        z' ⟨n - k, by omega⟩ = z ⟨n - k, by omega⟩) ∧
      ∃ w' : Fin n → Z.blowUp.presheaf.stalk a', IsRegularSystemOfParameters w' ∧
        (∀ i : Fin n, i.val < n - k ∨ i = j → w' i = Z.blowUpπ.stalkMap a' (z' i)) ∧
        (∀ i : Fin n, n - k ≤ i.val → i ≠ j →
          Z.blowUpπ.stalkMap a' (z' i) = w' i * w' j) := by
  have hreg : IsRegularLocalRing (Z.blowUp.presheaf.stalk a') :=
    isRegularLocalRing_stalk_blowUp' f E.component Z (hasSncWith_data E Z hZ) a'
  obtain ⟨z', hz', h1, h2, h3, h4, w', hw'⟩ := exists_shiftCoords_chartOrigin f Z a'
    hk hkn hz.1 hZa (bijective_of_isIso_residueFieldMap Z a' hrat) hj hF
    (stalkMap_ne_zero f E Z hZ a' ha' hF) ⟨n - k, by omega⟩ le_rfl
  refine ⟨z', hz', h1, h2, h3, fun hmem => h4 ?_, w', hw'⟩
  by_cases hpj : (⟨n - k, by omega⟩ : Fin n) = j
  · exact Or.inl hpj
  · exact Or.inr fun y hy => (mem_maximalIdeal_iff_mem_support_strictTransformAlong f E.component
      Z (hasSncWith_data E Z hZ) a' ha' hz.1 (hs_finset Z a' hZa) hV
      (Finset.mem_filter.mpr ⟨Finset.mem_univ _, le_rfl⟩) hF hy).mpr hmem

/-- [Hau14, Proposition 5.4 (9)] on the predicates: for `a'` rational over `κ(a)` there are
coordinates `z` at `a` with (1)–(3) in which `a'` is the origin of the chart of `z_j` — `j = n − 1`
when `a'` lies on the strict transform of `V`, `j = n − k` otherwise — and the local blow-up is
monomial: the induced coordinates `w` form a regular system of parameters at `a'` with
`π^* z_i = w_i w_j` for the other centre coordinates. This assembles (1)–(3) with
`exists_coordinates_chartOrigin'` of `Hironaka.Scheme.Snc.ChartOrigin`. -/
theorem exists_coordinates_chartOrigin [PerfectField k] (f : X ⟶ Spec (.of k))
    [Smooth f] (E : DivisorFamily X)
    (Z : X.IdealSheafData) (hE : E.IsSnc) (hZ : E.HasSncWith Z) (v : E.ι)
    (hv : E.component v ≤ Z) (a' : Z.blowUp) (ha' : a' ∈
        Z.exceptionalDivisor.support)
    (hrat : IsIso (Z.blowUpπ.residueFieldMap a')) :
    ∃ (n k : ℕ) (hk : 1 ≤ k) (hkn : k ≤ n) (z : Fin n → X.presheaf.stalk (Z.blowUpπ a'))
      (j : Fin n),
      IsRegularSystemOfParameters z ∧
      (E.component v).stalkIdeal (Z.blowUpπ a') = Ideal.span {z ⟨n - k, by omega⟩} ∧
      Z.stalkIdeal (Z.blowUpπ a') = Ideal.span (z '' {i | n - k ≤ i.val}) ∧
      n - k ≤ j.val ∧
      (a' ∈ ((E.component v).strictTransform Z).support → j.val = n - 1) ∧
      (a' ∉ ((E.component v).strictTransform Z).support → j.val = n - k) ∧
      Z.exceptionalDivisor.stalkIdeal a' = Ideal.span {Z.blowUpπ.stalkMap a'
          (z j)} ∧
      ∃ w : Fin n → Z.blowUp.presheaf.stalk a', IsRegularSystemOfParameters w ∧
        (∀ i : Fin n, i.val < n - k ∨ i = j → w i = Z.blowUpπ.stalkMap a' (z i)) ∧
        (∀ i : Fin n, n - k ≤ i.val → i ≠ j →
          Z.blowUpπ.stalkMap a' (z i) = w i * w j) := by
  have ha : Z.blowUpπ a' ∈ Z.support := (mem_support_comap_iff' Z
      (IdealSheafData.blowUpπ Z) a').mp ha'
  obtain ⟨n, kk, hk, hkn, z, hz, hV, hZa⟩ :=
    exists_sncAt_coordinates_hypersurface_center f E Z hE hZ v hv (Z.blowUpπ a') ha
  obtain ⟨j, hj, hF, -, hjV⟩ := exists_chart_index' f E Z hE hZ v hv a' ha' hk hkn hz hV hZa
  have hreg : IsRegularLocalRing (Z.blowUp.presheaf.stalk a') :=
    isRegularLocalRing_stalk_blowUp' f E.component Z (hasSncWith_data E Z hZ) a'
  have hne := stalkMap_ne_zero f E Z hZ a' ha' hF
  have hPy : ∀ y : Z.blowUp.presheaf.stalk a',
      Z.blowUpπ.stalkMap a' (z ⟨n - kk,
          by omega⟩) = y * Z.blowUpπ.stalkMap a' (z j) →
        (y ∈ IsLocalRing.maximalIdeal (Z.blowUp.presheaf.stalk a') ↔
          a' ∈ ((E.component v).strictTransform Z).support) := by
    intro y hy
    by_cases hpj : (⟨n - kk, by omega⟩ : Fin n) = j
    · -- in the chart of `V`'s own coordinate: `y = 1` and `a'` misses `V^s`
      have h1 : y = 1 := by
        rw [hpj] at hy
        exact mul_right_cancel₀ hne (hy.symm.trans (one_mul _).symm)
      subst h1
      have hnot : a' ∉ ((E.component v).strictTransform Z).support :=
        notMem_support_strictTransformAlong_of_stalkIdeal_eq Z (E.component v) a' hV (hpj ▸ hF)
      exact ⟨fun h => absurd isUnit_one ((IsLocalRing.mem_maximalIdeal _).mp h),
        fun h => (hnot h).elim⟩
    · exact mem_maximalIdeal_iff_mem_support_strictTransformAlong f E.component Z
        (hasSncWith_data E Z hZ) a' ha' hz.1 (hs_finset Z a' hZa) hV
        (Finset.mem_filter.mpr ⟨Finset.mem_univ _, le_rfl⟩) hF hy
  obtain ⟨z'', j', hz'', hV'', hZ'', hj', hP1, hP2, hF'', w'', hw''⟩ :=
    exists_coordinates_chartOrigin' f Z a' hk hkn hz.1 hZa
      (bijective_of_isIso_residueFieldMap Z a' hrat) hj hF hne ⟨n - kk, by omega⟩ rfl hV
      (a' ∈ ((E.component v).strictTransform Z).support)
      (fun hmem h => hjV hmem (congrArg Fin.val h)) hPy
  exact ⟨n, kk, hk, hkn, z'', j', hz'', hV'', hZ'', hj', hP1, hP2, hF'', w'', hw''⟩

end

/-- [Hau14, Example 4.53], the positive half: the inverse image of a normal crossings `E ⊂ 𝔸ⁿ` under
the blow-up along a `Z` with `E ∪ Z` normal crossings is normal crossings — the instance for `𝔸ⁿ_k`
of `totalTransform_isSnc`. The negative half of the example (`V(xy) ⊂ 𝔸³` blown up along
`V(x − y, z)`, where the inverse image is not normal crossings) is not formalised. -/
example [PerfectField k] (n : ℕ) (E : DivisorFamily (Spec (.of (MvPolynomial (Fin n) k))))
    (Z : (Spec (.of (MvPolynomial (Fin n) k))).IdealSheafData) (hE : E.IsSnc)
    (hZ : E.HasSncWith Z) : (E.totalTransform Z).IsSnc :=
  haveI : SmoothOfRelativeDimension n (affineSpaceToSpec k n) :=
    CoordinateSubspace.smoothOfRelativeDimension_Spec_map_algebraMap_mvPolynomial
      k n
  haveI : Smooth (affineSpaceToSpec k n) :=
    SmoothOfRelativeDimension.smooth n _
  totalTransform_isSnc (affineSpaceToSpec k n) E Z
    hE hZ

end AlgebraicGeometry

