/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.RegularSmooth.Defs
public import Hironaka.Scheme.IdealSheaf.Defs
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
import Hironaka.Algebra.Local.Regular
import Hironaka.Algebra.Local.RegularSystem
import Hironaka.Scheme.Smooth.AdaptedCoordinates

/-!
# Smooth divisors

[Kol07, Definition 24] ("each `E^i` is smooth") and [Hau14, Definition 4.1] (a hypersurface): a
*smooth divisor* of a scheme `X` smooth over `k` is a closed subscheme `D ⊆ X`, smooth over `k`,
whose ideal is generated at every point `x ∈ D` by one element of `𝔪_x ∖ 𝔪_x²`. "Smooth over `k`" is
taken as regularity of the closed subscheme (`IsRegular`; the two agree over a perfect field,
`Hironaka.Algebra.RegularSmooth.RegularSmoothEquiv`), and the ideal of `D` at `x` is the stalk
`D.stalkIdeal x` of the ideal sheaf. The equivalence with "`V(D)` is smooth of relative dimension
`n − 1`" is `isSmoothDivisor_of_smoothOfRelativeDimension` here and
`smoothOfRelativeDimension_of_isSmoothDivisor` of `Hironaka.Scheme.Snc.RelativeDimension`. The
members of a simple normal crossing family are smooth divisors (`Hironaka.Scheme.Snc.Family`), and a
hypersurface of maximal contact is required to be one
(`Hironaka.Resolution.Algebraic.MaximalContact.Basic`). -/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal

namespace AlgebraicGeometry

variable {X : Scheme.{u}}

/-- `D` is a smooth divisor of `X` ([Kol07, Definition 24], "each `E^i` is smooth";
[Hau14, Definition 4.1]): the closed subscheme `V(D)` is regular (smooth over the perfect ground
field) and at every point `x` of `V(D)` the stalk `D_x ⊆ 𝒪_{X,x}` is generated by one element of
`𝔪_x ∖ 𝔪_x²`. -/
def IsSmoothDivisor (D : X.IdealSheafData) : Prop :=
  IsRegular D.subscheme ∧ ∀ x ∈ D.support, ∃ a : X.presheaf.stalk x,
    a ∈ maximalIdeal (X.presheaf.stalk x) ∧ a ∉ maximalIdeal (X.presheaf.stalk x) ^ 2 ∧
      D.stalkIdeal x = Ideal.span {a}

variable {k : Type u} [Field k]

/-- If `V(D)` is smooth of relative dimension `n − 1` over the perfect field `k`, `X` being smooth
of relative dimension `n ≥ 1`, then `D` is a smooth divisor: `V(D)` is regular, and at `x ∈ V(D)`
the adapted parameters of `Hironaka.Scheme.Smooth.AdaptedCoordinates` give `D_x = (y_0)` with `y_0`
a member of a regular system of parameters, hence in `𝔪_x ∖ 𝔪_x²` ([Sta, Tag 00NR]). -/
theorem isSmoothDivisor_of_smoothOfRelativeDimension [PerfectField k] (f : X ⟶ Spec (.of k))
    (n : ℕ) [SmoothOfRelativeDimension n f] (hn : 1 ≤ n) (D : X.IdealSheafData)
    [SmoothOfRelativeDimension (n - 1) (D.subschemeι ≫ f)] : IsSmoothDivisor D := by
  have hsX : Smooth f := SmoothOfRelativeDimension.smooth n f
  have hsD : Smooth (D.subschemeι ≫ f) := SmoothOfRelativeDimension.smooth (n - 1) _
  refine ⟨⟨fun z => isRegularLocalRing_stalk (D.subschemeι ≫ f) z⟩, fun x hx => ?_⟩
  obtain ⟨m, y, hm, hspan, hI⟩ := exists_adaptedParameters D f n 1 hn hx
  have := isRegularLocalRing_quotient_stalkIdeal D f hx
  obtain ⟨q, hq⟩ :=
    exists_ringKrullDim_eq_natCast (X.presheaf.stalk x ⧸ D.stalkIdeal x)
  have hdim := ringKrullDim_quotient_stalkIdeal_add D f n 1 hn hx
  rw [hq, ← hm] at hdim
  have hqm : q + 1 = m := by exact_mod_cast hdim
  have h0 : 0 < m := by omega
  have himg : y '' {j : Fin m | j.val < 1} = {y ⟨0, h0⟩} := by
    ext a
    simp only [Set.mem_image, Set.mem_ofPred_eq, Set.mem_singleton_iff]
    constructor
    · rintro ⟨j, hj, rfl⟩
      congr 1
      exact Fin.ext (Nat.lt_one_iff.mp hj)
    · rintro rfl
      exact ⟨⟨0, h0⟩, Nat.zero_lt_one, rfl⟩
  rw [himg] at hI
  have := isRegularLocalRing_stalk f x
  exact ⟨y ⟨0, h0⟩, x_mem_maximalIdeal_of_span_eq y hspan _,
    notMem_sq_of_span_eq y hspan hm _, hI⟩

end AlgebraicGeometry
