/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.Snc.ParameterSubset
public import Hironaka.Scheme.IdealSheaf.Defs
public import Hironaka.Scheme.Smooth.EtaleCoordinatesDefs
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.Adapted
import Hironaka.Scheme.Smooth.DifferentialBasis
import Hironaka.Scheme.Smooth.EtaleCoordinates
import Hironaka.Scheme.Smooth.EtaleLocal

/-!
# Snc coordinates at a closed point spread to an étale chart

Hauser's proofs of [Hau14, Proposition 5.3] and [Hau14, Proposition 5.4] read the total transform of
an snc divisor "in local coordinates for which the blow-up is monomial": coordinates `x_1, …, x_n`
at
a point `x₀ ∈ Z` in which the centre is `Z = (x_1 = ⋯ = x_r = 0)` and each component of the divisor
through `x₀` is a coordinate hyperplane `(x_c = 0)`. [Kol07, Definition 24 (4)] provides such
coordinates on the stalk `𝒪_{X,x₀}` (a regular system of parameters);
`Hironaka.Scheme.Smooth.ChartIso` computes the charts of the blow-up from a chart `U ∋ x₀` of
**étale coordinates adapted to `Z`** (`EtaleCoordinatesAdapted` of
`Hironaka.Scheme.Smooth.EtaleCoordinatesAdapted`). This module spreads the snc data at a *closed*
point `x₀` to such a chart on which, in addition, every component through `x₀` is the coordinate
hyperplane of one of the étale coordinates and every other component misses the chart;
`Hironaka.Scheme.Snc.TotalTransformOnCentre` and `Hironaka.Scheme.Snc.HypersurfaceCoordinates` use
it.

**Why the lemmas hold.** The regular system of parameters `z` at `x₀` lifts to sections `w` of an
affine open (`exists_affineOpen_germ_eq`); at a closed point of a scheme smooth of relative
dimension `n` their differentials form a basis of `κ(x₀) ⊗ Ω`, so on a smaller affine open the `w`
are étale coordinates. An equality of a stalk ideal with the ideal generated by the germs of
finitely many sections spreads to a basic open around `x₀` because two finitely generated ideals
with the same localization at a prime agree after inverting a single element outside the prime
(`exists_mem_map_eq_map_of_localization`); finitely many such equalities hold simultaneously on the
basic open of the product. A component not through `x₀` has closed support, so a basic open around
`x₀` misses it. Adaptedness to `Z` on a further basic open is
`exists_comap_eq_comap_coordinateSubspace` after reindexing the parameters so that those of `Z` come
first (`finsetEquiv` of `Hironaka.Scheme.Snc.ParameterSubset`).

Sources: [Hau14, Proposition 5.3] (the proof); [Hau14, Proposition 5.4]; [Kol07, Definition 24 (4)].
-/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal TopologicalSpace KaehlerDifferential
open scoped TensorProduct

namespace AlgebraicGeometry

variable {X : Scheme.{u}}

section Spread

/-- An equality of a stalk ideal with the ideal generated by the germs of finitely many sections of
an affine open `V ∋ x` spreads to a basic open `D(s) ∋ x` of `V`: finitely generated ideals with the
same localization at the prime of `x` agree after inverting one element `s` outside it. -/
theorem exists_basicOpen_ideal_eq_span (D : X.IdealSheafData) {x : X} (V : X.affineOpens)
    (hxV : x ∈ V.1) [IsNoetherianRing Γ(X, V.1)] (S : Set Γ(X, V.1)) (hS : S.Finite)
    (hD : D.stalkIdeal x = span ((X.presheaf.germ V.1 x hxV).hom '' S)) :
    ∃ s : Γ(X, V.1), x ∈ X.basicOpen s ∧
      D.ideal ⟨X.basicOpen s, V.2.basicOpen s⟩ =
        span ((X.presheaf.map (homOfLE (X.basicOpen_le s)).op).hom '' S) := by
  classical
  let _ := X.presheaf.algebra_section_stalk ⟨x, hxV⟩
  have hloc := V.2.isLocalization_stalk ⟨x, hxV⟩
  set p := (V.2.primeIdealOf ⟨x, hxV⟩).asIdeal with hpdef
  have hI : (D.ideal V).map (algebraMap Γ(X, V.1) (X.presheaf.stalk x)) =
      (span S).map (algebraMap Γ(X, V.1) (X.presheaf.stalk x)) := by
    change (D.ideal V).map (X.presheaf.germ V.1 x hxV).hom =
      (span S).map (X.presheaf.germ V.1 x hxV).hom
    rw [← Scheme.IdealSheafData.stalkIdeal_eq_map_germ D V hxV, hD, Ideal.map_span]
  obtain ⟨s, hsp, hs⟩ := exists_mem_map_eq_map_of_localization p.primeCompl (D.ideal V) (span S)
    (IsNoetherian.noetherian _) (Submodule.fg_span hS) hI
  have hUV : X.basicOpen s ≤ V.1 := X.basicOpen_le s
  have hxU : x ∈ X.basicOpen s := (mem_basicOpen_iff_notMem_primeIdealOf V.2 hxV s).mpr hsp
  let _ := restrictAlgebra (X := X) hUV
  have hloc' : IsLocalization.Away s Γ(X, X.basicOpen s) :=
    V.2.isLocalization_of_eq_basicOpen s (homOfLE hUV) rfl
  refine ⟨s, hxU, ?_⟩
  rw [← Scheme.IdealSheafData.map_ideal D (U := ⟨X.basicOpen s, V.2.basicOpen s⟩) (V := V) hUV]
  change (D.ideal V).map (algebraMap Γ(X, V.1) Γ(X, X.basicOpen s)) = _
  rw [hs Γ(X, X.basicOpen s), Ideal.map_span]
  rfl

/-- Finitely many such equalities hold simultaneously on the basic open of the product of the
elements inverted for each of them. -/
theorem exists_basicOpen_forall_ideal_eq_span {ι : Type*} [Finite ι] (D : ι → X.IdealSheafData)
    {x : X} (V : X.affineOpens) (hxV : x ∈ V.1) [IsNoetherianRing Γ(X, V.1)]
    (S : ι → Set Γ(X, V.1)) (hS : ∀ i, (S i).Finite)
    (hD : ∀ i, (D i).stalkIdeal x = span ((X.presheaf.germ V.1 x hxV).hom '' S i)) :
    ∃ s : Γ(X, V.1), x ∈ X.basicOpen s ∧ ∀ i,
      (D i).ideal ⟨X.basicOpen s, V.2.basicOpen s⟩ =
        span ((X.presheaf.map (homOfLE (X.basicOpen_le s)).op).hom '' S i) := by
  classical
  cases nonempty_fintype ι
  choose t ht using fun i => exists_basicOpen_ideal_eq_span (D i) V hxV (S i) (hS i) (hD i)
  refine ⟨∏ i, t i, ?_, fun i => ?_⟩
  · refine Finset.prod_induction t (fun a => x ∈ X.basicOpen a) (fun a b ha hb => ?_) ?_
      (fun i _ => (ht i).1)
    · rw [X.basicOpen_mul]
      exact ⟨ha, hb⟩
    · rw [X.basicOpen_one]
      exact hxV
  · have hle : X.basicOpen (∏ i, t i) ≤ X.basicOpen (t i) := by
      rw [← Finset.mul_prod_erase Finset.univ t (Finset.mem_univ i), X.basicOpen_mul]
      exact inf_le_left
    rw [← Scheme.IdealSheafData.map_ideal (D i) (U := ⟨X.basicOpen (∏ i, t i), V.2.basicOpen _⟩)
      (V := ⟨X.basicOpen (t i), V.2.basicOpen _⟩) hle, (ht i).2, Ideal.map_span, Set.image_image]
    refine congrArg span (Set.image_congr fun a _ => ?_)
    change (X.presheaf.map _ ≫ X.presheaf.map _) a = X.presheaf.map _ a
    rw [← Functor.map_comp]
    rfl

/-- A point outside finitely many closed sets has an affine neighbourhood inside a given affine
open missing all of them. -/
theorem exists_affineOpen_le_disjoint {ι : Type*} [Finite ι] (C : ι → Set X)
    (hC : ∀ i, IsClosed (C i)) {x : X} (hx : ∀ i, x ∉ C i) (V : X.affineOpens) (hxV : x ∈ V.1) :
    ∃ (U : X.affineOpens) (_ : x ∈ U.1) (_ : U.1 ≤ V.1), ∀ i, Disjoint (U.1 : Set X) (C i) := by
  classical
  have hcl : IsClosed (⋃ i, C i) := isClosed_iUnion_of_finite hC
  let W : X.Opens := V.1 ⊓ ⟨(⋃ i, C i)ᶜ, hcl.isOpen_compl⟩
  have hxW : x ∈ W := ⟨hxV, fun h => by
    obtain ⟨i, hi⟩ := Set.mem_iUnion.mp h
    exact hx i hi⟩
  obtain ⟨t, htW, hxt⟩ := V.2.exists_basicOpen_le (⟨x, hxW⟩ : W) hxV
  refine ⟨⟨X.basicOpen t, V.2.basicOpen t⟩, hxt, X.basicOpen_le t, fun i => ?_⟩
  rw [Set.disjoint_left]
  intro y hy hyC
  exact (htW hy).2 (Set.mem_iUnion.mpr ⟨i, hyC⟩)

/-- An ideal sheaf whose support misses an open `U` restricts to the unit ideal sheaf on `U`. -/
theorem comap_eq_top_of_disjoint (D : X.IdealSheafData) (U : X.Opens)
    (h : Disjoint (U : Set X) (D.support : Set X)) : D.comap U.ι = ⊤ := by
  rw [← Scheme.IdealSheafData.support_eq_bot_iff]
  ext y
  simp only [Scheme.IdealSheafData.support_comap, Closeds.coe_preimage, Set.mem_preimage,
    Closeds.coe_bot, Set.mem_empty_iff_false, iff_false]
  intro hy
  exact Set.disjoint_left.mp h (Scheme.Opens.ι_apply U y ▸ y.2) hy

end Spread

section Restrict

/-- Restriction of sections along `U ≤ U' ≤ V` composes. -/
theorem res_res {U U' V : X.Opens} (h₁ : U' ≤ V) (h₂ : U ≤ U') (a : Γ(X, V)) :
    X.presheaf.map (homOfLE h₂).op (X.presheaf.map (homOfLE h₁).op a) =
      X.presheaf.map (homOfLE (h₂.trans h₁)).op a := by
  change (X.presheaf.map _ ≫ X.presheaf.map _) a = _
  rw [← Functor.map_comp]
  rfl

/-- An equality `D(V) = ⟨S⟩` of ideals of an affine open restricts to a smaller affine open. -/
theorem ideal_eq_span_of_le (D : X.IdealSheafData) {U V : X.affineOpens} (h : U ≤ V)
    (S : Set Γ(X, V.1)) (hD : D.ideal V = span S) :
    D.ideal U = span ((X.presheaf.map (homOfLE h).op).hom '' S) := by
  rw [← Scheme.IdealSheafData.map_ideal D h, hD, Ideal.map_span]

end Restrict

section Reindex

variable {n : ℕ}

/-- The reindexing of `Fin n` putting the members of `s` first. -/
noncomputable def sncReindex (s : Finset (Fin n)) : Fin n ≃ Fin n :=
  (finCongr (card_add_card_compl_eq s).symm).trans (finsetEquiv s)

theorem sncReindex_mem_iff (s : Finset (Fin n)) (i : Fin n) :
    sncReindex s i ∈ s ↔ i.val < s.card := by
  constructor
  · intro h
    obtain ⟨j, hj, hji⟩ : sncReindex s i ∈ finsetEquiv s '' {j | j.val < s.card} := by
      rw [finsetEquiv_image_lt]; exact h
    have : (sncReindex s).symm (finsetEquiv s j) = (sncReindex s).symm (sncReindex s i) :=
      congrArg _ hji
    rw [Equiv.symm_apply_apply] at this
    have hval : ((sncReindex s).symm (finsetEquiv s j)).val = j.val := by
      simp [sncReindex]
    rw [← this, hval]
    exact hj
  · intro h
    have : sncReindex s i ∈ finsetEquiv s '' {j | j.val < s.card} :=
      ⟨finCongr (card_add_card_compl_eq s).symm i, by simpa using h, rfl⟩
    rwa [finsetEquiv_image_lt] at this

end Reindex

section Chart

variable {k : Type u} [Field k] [PerfectField k] (f : X ⟶ Spec (.of k)) (n : ℕ)
  [SmoothOfRelativeDimension n f]

/-- The chart of the proof of [Hau14, Proposition 5.3] ([Kol07, Definition 24 (4)]): snc data at a
**closed** point `x₀ ∈ Z` — a regular system of parameters `z` of `𝒪_{X,x₀}` with
`Z_{x₀} = (z_l : l ∈ s)` and each component `D i` through `x₀` equal to `(z_{c i})` — spread to a
chart of étale coordinates adapted to `Z` on which every component through `x₀` is the coordinate
hyperplane of the coordinate `c' i` (`c' i < |s|` exactly when `c i ∈ s`, i.e. when the component
contains `Z` near `x₀`) and every other component misses the chart. -/
theorem exists_etaleCoordinatesAdapted_of_snc {Z : X.IdealSheafData} {ι : Type*} [Finite ι]
    (D : ι → X.IdealSheafData) {x₀ : X} (hx₀ : IsClosed ({x₀} : Set X))
    {z : Fin n → X.presheaf.stalk x₀}
    (hz : maximalIdeal (X.presheaf.stalk x₀) = span (Set.range z)) (s : Finset (Fin n))
    (hZ : Z.stalkIdeal x₀ = span (z '' ↑s)) (c : {i : ι // x₀ ∈ (D i).support} → Fin n)
    (hcinj : Function.Injective c) (hc : ∀ i, (D i.1).stalkIdeal x₀ = span {z (c i)}) :
    ∃ (E : EtaleCoordinatesAdapted f n s.card Z x₀) (c' : {i : ι // x₀ ∈ (D i).support} → Fin n),
      Function.Injective c' ∧ (∀ i, (c' i).val < s.card ↔ c i ∈ s) ∧
      (∀ i, (D i.1).ideal E.U = span {E.v (c' i)}) ∧
      (∀ i, x₀ ∉ (D i).support → (D i).comap E.U.1.ι = ⊤) := by
  classical
  let _ := f.stalkAlgebra x₀
  have hs : Smooth f := SmoothOfRelativeDimension.smooth n f
  -- reindex the parameters so that those of `Z` come first
  set e := sncReindex s with hedef
  set z' : Fin n → X.presheaf.stalk x₀ := z ∘ e with hz'def
  have hz' : maximalIdeal (X.presheaf.stalk x₀) = span (Set.range z') := by
    rw [hz, hz'def, e.surjective.range_comp]
  have himg : z' '' {i : Fin n | i.val < s.card} = z '' ↑s := by
    ext a
    constructor
    · rintro ⟨i, hi, rfl⟩
      exact ⟨e i, (sncReindex_mem_iff s i).mpr hi, rfl⟩
    · rintro ⟨j, hj, rfl⟩
      refine ⟨e.symm j, ?_, by simp [hz'def]⟩
      have := (sncReindex_mem_iff s (e.symm j)).mp (by rwa [Equiv.apply_symm_apply])
      exact this
  have hZ' : Z.stalkIdeal x₀ = span (z' '' {i : Fin n | i.val < s.card}) := by rw [hZ, himg]
  set c' : {i : ι // x₀ ∈ (D i).support} → Fin n := fun i => e.symm (c i) with hc'def
  have hc'inj : Function.Injective c' := e.symm.injective.comp hcinj
  have hc'lt : ∀ i, (c' i).val < s.card ↔ c i ∈ s := fun i => by
    rw [← sncReindex_mem_iff s (c' i)]
    change e (e.symm (c i)) ∈ s ↔ c i ∈ s
    rw [Equiv.apply_symm_apply]
  have hc' : ∀ i, (D i.1).stalkIdeal x₀ = span {z' (c' i)} := fun i => by
    rw [hc i, hz'def, Function.comp_apply, hc'def, Equiv.apply_symm_apply]
  -- lift the parameters to sections of an affine open `V ∋ x₀`
  obtain ⟨_, ⟨V₀, hV₀, rfl⟩, hxV₀, -⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x₀) isOpen_univ
  obtain ⟨V, hxV, -, w, hw⟩ := exists_affineOpen_germ_eq ⟨V₀, hV₀⟩ hxV₀ z'
  -- their differentials form a basis at `x₀`, hence étale coordinates
  obtain ⟨b, hb⟩ := exists_basis_tensor_kaehlerDifferential_of_span_eq_maximalIdeal f n hx₀ z' hz'
  have hb' : ∃ b' : Module.Basis (Fin n) (ResidueField (X.presheaf.stalk x₀))
      (ResidueField (X.presheaf.stalk x₀) ⊗[X.presheaf.stalk x₀] Ω[X.presheaf.stalk x₀⁄k]),
      ∀ i, b' i = 1 ⊗ₜ KaehlerDifferential.D k (X.presheaf.stalk x₀)
        (X.presheaf.germ V.1 x₀ hxV (w i)) :=
    ⟨b, fun i => by rw [hb i, hw i]⟩
  obtain ⟨U₁, hxU₁, hU₁V, hE₁⟩ := exists_etale_toAffineSpace_of_basis f n V hxV w hb'
  set w₁ : Fin n → Γ(X, U₁.1) := fun i => X.presheaf.map (homOfLE hU₁V).op (w i) with hw₁def
  have hw₁ : ∀ i, X.presheaf.germ U₁.1 x₀ hxU₁ (w₁ i) = z' i := fun i => by
    rw [hw₁def]
    change X.presheaf.germ U₁.1 x₀ hxU₁ (X.presheaf.map (homOfLE hU₁V).op (w i)) = z' i
    rw [X.presheaf.germ_res_apply, hw i]
  -- avoid the components not through `x₀`
  obtain ⟨U₂, hxU₂, hU₂U₁, hdisj⟩ := exists_affineOpen_le_disjoint
    (fun i : {i : ι // x₀ ∉ (D i).support} => ((D i.1).support : Set X))
    (fun i => (D i.1).support.isClosed) (fun i => i.2) U₁ hxU₁
  set w₂ : Fin n → Γ(X, U₂.1) := fun i => X.presheaf.map (homOfLE hU₂U₁).op (w₁ i) with hw₂def
  have hw₂ : ∀ i, X.presheaf.germ U₂.1 x₀ hxU₂ (w₂ i) = z' i := fun i => by
    rw [hw₂def]
    change X.presheaf.germ U₂.1 x₀ hxU₂ (X.presheaf.map (homOfLE hU₂U₁).op (w₁ i)) = z' i
    rw [X.presheaf.germ_res_apply, hw₁ i]
  -- spread the ideal equalities of `Z` and of the components through `x₀` to a basic open
  have hnoeth : IsNoetherianRing Γ(X, U₂.1) := by
    let _ := f.sectionsAlgebra U₂.1
    have : Algebra.FiniteType k Γ(X, U₂.1) := f.finiteType_sectionsAlgebra U₂.2
    exact Algebra.FiniteType.isNoetherianRing k Γ(X, U₂.1)
  let D' : {i : ι // x₀ ∈ (D i).support} ⊕ Unit → X.IdealSheafData :=
    Sum.elim (fun i => D i.1) fun _ => Z
  let S' : {i : ι // x₀ ∈ (D i).support} ⊕ Unit → Set Γ(X, U₂.1) :=
    Sum.elim (fun i => {w₂ (c' i)}) fun _ => w₂ '' {i : Fin n | i.val < s.card}
  have hS' : ∀ j, (S' j).Finite := by
    rintro (i | u)
    · exact Set.finite_singleton _
    · exact (Set.toFinite _).image w₂
  have hD' : ∀ j, (D' j).stalkIdeal x₀ = span ((X.presheaf.germ U₂.1 x₀ hxU₂).hom '' S' j) := by
    rintro (i | u)
    · change (D i.1).stalkIdeal x₀ = span ((X.presheaf.germ U₂.1 x₀ hxU₂).hom '' {w₂ (c' i)})
      rw [hc' i, Set.image_singleton]
      change span {z' (c' i)} = span {X.presheaf.germ U₂.1 x₀ hxU₂ (w₂ (c' i))}
      rw [hw₂]
    · change Z.stalkIdeal x₀ =
        span ((X.presheaf.germ U₂.1 x₀ hxU₂).hom '' (w₂ '' {i : Fin n | i.val < s.card}))
      rw [hZ', Set.image_image]
      refine congrArg span (Set.image_congr fun i _ => ?_)
      exact (hw₂ i).symm
  obtain ⟨t, hxt, ht⟩ := exists_basicOpen_forall_ideal_eq_span D' U₂ hxU₂ S' hS' hD'
  set U₃ : X.affineOpens := ⟨X.basicOpen t, U₂.2.basicOpen t⟩ with hU₃def
  have hU₃U₂ : U₃.1 ≤ U₂.1 := X.basicOpen_le t
  set w₃ : Fin n → Γ(X, U₃.1) := fun i => X.presheaf.map (homOfLE hU₃U₂).op (w₂ i) with hw₃def
  have hw₃ : ∀ i, X.presheaf.germ U₃.1 x₀ hxt (w₃ i) = z' i := fun i => by
    rw [hw₃def]
    change X.presheaf.germ U₃.1 x₀ hxt (X.presheaf.map (homOfLE hU₃U₂).op (w₂ i)) = z' i
    rw [X.presheaf.germ_res_apply, hw₂ i]
  -- adaptedness to `Z` on a further basic open
  have hZ₃ : Z.stalkIdeal x₀ =
      span ((fun i => X.presheaf.germ U₃.1 x₀ hxt (w₃ i)) '' {i : Fin n | i.val < s.card}) := by
    rw [hZ']
    exact congrArg span (Set.image_congr fun i _ => (hw₃ i).symm)
  obtain ⟨U₄, hxU₄, hU₄U₃, hAd⟩ :=
    exists_comap_eq_comap_coordinateSubspace f n s.card Z U₃ hxt w₃ hZ₃
  have hU₄U₁ : U₄.1 ≤ U₁.1 := hU₄U₃.trans (hU₃U₂.trans hU₂U₁)
  set w₄ : Fin n → Γ(X, U₄.1) := fun i => X.presheaf.map (homOfLE hU₄U₁).op (w₁ i) with hw₄def
  have hw₄eq : (fun i => X.presheaf.map (homOfLE hU₄U₃).op (w₃ i)) = w₄ := by
    funext i
    rw [hw₄def, hw₃def, hw₂def]
    change X.presheaf.map (homOfLE hU₄U₃).op (X.presheaf.map (homOfLE hU₃U₂).op
      (X.presheaf.map (homOfLE hU₂U₁).op (w₁ i))) = X.presheaf.map (homOfLE hU₄U₁).op (w₁ i)
    rw [res_res, res_res]
  have hE₄ : Etale (toAffineSpace f U₄.1 w₄) := by
    have : Etale (toAffineSpace f U₁.1 w₁) := hE₁
    exact etale_toAffineSpace_restrict f hU₄U₁ w₁
  rw [hw₄eq] at hAd
  refine ⟨⟨U₄, hxU₄, w₄, hE₄, hAd⟩, c', hc'inj, hc'lt, fun i => ?_, fun i hi => ?_⟩
  · -- the component `D i` is the coordinate hyperplane of `w₄ (c' i)` on `U₄`
    have h₃ := ht (Sum.inl i)
    change (D i.1).ideal U₃ = span ((X.presheaf.map (homOfLE hU₃U₂).op).hom '' {w₂ (c' i)}) at h₃
    rw [Set.image_singleton] at h₃
    have h₄ := ideal_eq_span_of_le (D i.1) hU₄U₃ _ h₃
    rw [Set.image_singleton] at h₄
    change (D i.1).ideal U₄ = span {w₄ (c' i)}
    rw [h₄, ← congrFun hw₄eq (c' i)]
    rfl
  · -- a component not through `x₀` misses `U₄ ⊆ U₂`
    exact comap_eq_top_of_disjoint (D i) U₄.1
      (Set.disjoint_of_subset_left (hU₄U₃.trans hU₃U₂) (hdisj ⟨i, hi⟩))

end Chart

end AlgebraicGeometry
