/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.Snc.SmoothDivisor
public import Hironaka.Scheme.Snc.Defs
public import Hironaka.Scheme.Snc.TrivialTotalTransform
import Hironaka.Scheme.BlowUp.Glue.Trivial
import Hironaka.Scheme.BlowUp.Transform.TransformIso
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Smooth.ExceptionalModel
import Hironaka.Scheme.Snc.HasSncWith
import Hironaka.Scheme.Snc.TotalTransformChartComputation
import Hironaka.Scheme.Snc.TrivialSncData
import Mathlib.Data.Nat.Choose.Multinomial
/-!
# The total transform of an snc divisor under a smooth blow-up

[Hau14, Proposition 5.3]: the total transform `π^{-1}_{tot}(E) = (π_*^{-1} E^i, F)`
[Kol07, Definition 25] of a simple normal crossing family `E` under the blow-up `π : B_Z X → X`
along a centre `Z` having simple normal crossings with `E` is again a simple normal crossing family
(`totalTransform_isSnc`), and each of its members — the strict transform of a component, the
exceptional divisor — is a smooth divisor (`isSmoothDivisor_strictTransform`,
`isSmoothDivisor_exceptionalDivisor`). The proof assembles the three statements of
`Hironaka.Scheme.Snc.TotalTransformChartComputation`: `IsSnc` is the regularity of every member (the
regular half of the smooth-divisor statement) together with the pointwise conditions of
[Kol07, Definition 24], obtained by cases on `x' ∈ F` — Hauser's "computation in local coordinates
for which the blow-up is monomial" at the points of `F`, and the local isomorphism off `F`. This is
the theorem that keeps the boundary of a blow-up sequence snc (`Hironaka.Sequence`;
`Hironaka.Resolution.Algebraic.Monomial.Geometric.Realize`).

The first section records what is definitional: the members and the order of `E.totalTransform Z`
(`totalTransform_component_inl`, `totalTransform_component_inr`, `totalTransform_linearOrder`).

**The trivial blow-up** ([Kol07, Definition 65]: "If `π` is a trivial blow-up, then
`π⁻¹_{tot}(E) = E + Z`"). For a trivial blow-up the centre `Z` is a Cartier divisor and
`π : B_Z X ⟶ X` is an isomorphism (the universal property applied to `𝟙_X`), so the strict transform
of a component `D = E^i` is the inverse image along `π` of the saturation `D.saturate Z` computed on
`X`, and everything is read on stalks (`Hironaka.Scheme.Snc.TrivialTotalTransform`). At a point `x ∈
Z ∩ D` the snc data ([Kol07, Definition 24 (4)]) give a regular system of parameters `z` with `D_x =
(z_c)` and `Z_x = (z_l : l ∈ s)`; since `Z_x` is principal, generated by a nonzerodivisor, `s =
{j}`. If `c ≠ j` — the component is transversal to `Z` — the prime `(z_c)` is unchanged by the colon
with powers of `(z_j)`, so the saturation is `D` and the strict transform is `D` carried along `π`
(`strictTransform_eq_comap_of_isInvertible`). If `c = j` the component coincides with `Z` near `x`
and its saturation has stalk `(1)` there: it dies, as [Hau14, Definition 6.2] says of the centre
itself. The total transform is snc: every member is regular (a transversal component keeps its
stalks, the exceptional divisor is `Z` carried along `π`, and regularity transports along `π`), and
at `x' = π⁻¹(x)` the coordinates `π♯ z` are a regular system of parameters for which the surviving
old components keep their coordinates `z_{c(i)}` and `F` takes `z_j`, a coordinate no surviving
component uses (`totalTransform_isSnc_of_isInvertible`; `Hironaka.Scheme.Snc.TrivialSncData`).
-/

public section

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal Scheme IdealSheafData
  DivisorFamily
open AlgebraicGeometry

namespace AlgebraicGeometry

universe u

variable {k : Type u} [Field k] {X : Scheme.{u}}

/-! ### The members of the total transform -/

/-- The member of the total transform at an old index is the strict transform of that component. -/
theorem totalTransform_component_inl (E : DivisorFamily X) (Z : X.IdealSheafData) (i : E.ι) :
    (E.totalTransform Z).component (toLex (Sum.inl i)) = (E.component i).strictTransform Z :=
  rfl

/-- The last member of the total transform is the exceptional divisor [Kol07, Definition 25]. -/
theorem totalTransform_component_inr (E : DivisorFamily X) (Z : X.IdealSheafData) :
    (E.totalTransform Z).component (toLex (Sum.inr PUnit.unit)) = Z.exceptionalDivisor :=
  rfl

/-- The order of the total transform: the old members in their order, the exceptional divisor last.
-/
theorem totalTransform_linearOrder (E : DivisorFamily X) (Z : X.IdealSheafData) :
    (E.totalTransform Z).linearOrder = Sum.Lex.linearOrder :=
  rfl

/-! ### The total transform is snc -/

/-- [Hau14, Proposition 5.3]: the total transform of a simple normal crossing family `E` under the
blow-up along a centre `Z` having simple normal crossings with `E` is a simple normal crossing
family — Kollár's conditions (1)–(3) at the points of the exceptional divisor
(`exists_isSncAt_totalTransform_of_mem_support`) and off it
(`exists_isSncAt_totalTransform_of_notMem_support`), and every member a smooth divisor, hence
regular (`isSmoothDivisor_totalTransform_component`), all of
`Hironaka.Scheme.Snc.TotalTransformChartComputation`. -/
theorem totalTransform_isSnc [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (hE : E.IsSnc) (hZ : E.HasSncWith Z) :
    (E.totalTransform Z).IsSnc :=
  ⟨fun i =>
    (isSmoothDivisor_totalTransform_component f E Z hE hZ i).1,
    fun x' => by
      by_cases h : x' ∈ Z.exceptionalDivisor.support
      · exact exists_isSncAt_totalTransform_of_mem_support
          f E Z hE hZ x' h
      · exact exists_isSncAt_totalTransform_of_notMem_support
          f E Z hE hZ x' h⟩

/-- The strict transform of a component of a simple normal crossing family under a blow-up along a
centre having simple normal crossings with it is a smooth divisor
(`isSmoothDivisor_totalTransform_component` at an old index). -/
theorem isSmoothDivisor_strictTransform [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (hE : E.IsSnc) (hZ : E.HasSncWith Z) (i : E.ι) :
    IsSmoothDivisor ((E.component i).strictTransform Z) :=
  isSmoothDivisor_totalTransform_component f E Z hE hZ
    (toLex (Sum.inl i))

/-- The exceptional divisor of the blow-up along a centre having simple normal crossings with a
simple normal crossing family is a smooth divisor (`isSmoothDivisor_totalTransform_component` at the
index of `F`). -/
theorem isSmoothDivisor_exceptionalDivisor [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (hE : E.IsSnc) (hZ : E.HasSncWith Z) :
    IsSmoothDivisor Z.exceptionalDivisor :=
  isSmoothDivisor_totalTransform_component f E Z hE hZ
    (toLex (Sum.inr PUnit.unit))

/-! ### The trivial blow-up -/

/-- The snc data of a component and the centre at a point of both ([Kol07, Definition 24 (4)]), in
the form of `AlgebraicGeometry.SncDataAt`. -/
theorem sncDataAt_of_hasSncWith (E : DivisorFamily X) (Z : X.IdealSheafData)
    (hZ : E.HasSncWith Z) (i : E.ι) :
    ∀ x ∈ (E.component i).support, x ∈ Z.support → SncDataAt (E.component i) Z x := by
  intro x hxD hxZ
  obtain ⟨n, z, hsnc, s, hZs⟩ := hZ x hxZ
  obtain ⟨c, -, hc⟩ := hsnc.2
  exact ⟨n, z, c ⟨i, hxD⟩, s, hsnc.1.1.symm, hsnc.1.2, hc ⟨i, hxD⟩, hZs⟩

/-- Under a trivial blow-up, the strict transform of a component `E^i` that contains the centre near
no point of `Z ∩ E^i` is `E^i` carried along the isomorphism `π`: its saturation along `Z` is
itself. -/
theorem strictTransform_eq_comap_of_isInvertible (f : X ⟶ Spec (.of k)) [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (_hE : E.IsSnc) (hZ : E.HasSncWith Z)
    (hZ' : Z.IsInvertible) (i : E.ι)
    (hi : ∀ x ∈ Z.support, x ∈ (E.component i).support →
      ¬ (E.component i).stalkIdeal x ≤ Z.stalkIdeal x) :
    (E.component i).strictTransform Z = (E.component i).comap Z.blowUpπ := by
  have hreg : ∀ x : X, IsRegularLocalRing (X.presheaf.stalk x) := fun x =>
    isRegularLocalRing_stalk f x
  have := blowUp.isIso_π_of_isInvertible Z hZ'
  have hsat : (E.component i).saturate Z = E.component i := by
    refine saturate_eq_self_of_snc_transversal hreg (E.component i) Z hZ' fun x hxD hxZ => ?_
    obtain ⟨n, z, hsnc, s, hZs⟩ := hZ x hxZ
    obtain ⟨c, -, hc⟩ := hsnc.2
    exact ⟨n, z, c ⟨i, hxD⟩, s, hsnc.1.1.symm, hsnc.1.2, hc ⟨i, hxD⟩, hZs,
      notMem_of_not_stalkIdeal_le hsnc.1 hZs (hc ⟨i, hxD⟩) (hi x hxZ hxD)⟩
  exact strictTransformAlong_eq_comap_of_saturate_eq (IdealSheafData.blowUpπ Z) Z
      (E.component i) hsat

/-- The total transform of a simple normal crossing family under a trivial blow-up along a centre
having simple normal crossings with it is a simple normal crossing family — Kollár's
`π⁻¹_{tot}(E) = E + Z` [Kol07, Definition 65]; see the module docstring for the argument. -/
theorem totalTransform_isSnc_of_isInvertible (f : X ⟶ Spec (.of k)) [Smooth f]
    (E : DivisorFamily X) (Z : X.IdealSheafData) (hE : E.IsSnc) (hZ : E.HasSncWith Z)
    (hZ' : Z.IsInvertible) : (E.totalTransform Z).IsSnc := by
  have hreg : ∀ x : X, IsRegularLocalRing (X.presheaf.stalk x) := fun x =>
    isRegularLocalRing_stalk f x
  have hiso := blowUp.isIso_π_of_isInvertible Z hZ'
  have hdata := sncDataAt_of_hasSncWith E Z hZ
  refine ⟨fun k => ?_, fun x' => ?_⟩
  · -- regularity of every member
    rcases k with i | u
    · change IsRegular ((E.component i).strictTransform Z).subscheme
      rw [show (E.component i).strictTransform Z =
          ((E.component i).saturate Z).comap (IdealSheafData.blowUpπ Z) from
        strictTransformAlong_of_isIso (IdealSheafData.blowUpπ Z) Z (E.component i)]
      have := isIso_subschemeMap_comap_of_isIso (IdealSheafData.blowUpπ Z)
          ((E.component i).saturate Z)
      exact IsRegular.of_isIso
        (inv (Scheme.IdealSheafData.subschemeMap _ _ (IdealSheafData.blowUpπ Z)
          (Scheme.IdealSheafData.le_map_comap _ _)))
        (isRegular_subscheme_saturate hreg (E.component i) Z hZ' (hdata i) (hE.1 i))
    · change IsRegular (Z.comap (IdealSheafData.blowUpπ Z)).subscheme
      have hZreg : IsRegular Z.subscheme :=
        isRegular_subscheme_of_isRegularLocalRing_quotient Z fun w hw => by
          have := hreg w
          obtain ⟨n, z, hsnc, s, hZs⟩ := hZ w hw
          exact isRegularLocalRing_quotient_stalkIdeal_of_eq_span hsnc.1 hZs
      have := isIso_subschemeMap_comap_of_isIso (IdealSheafData.blowUpπ Z) Z
      exact IsRegular.of_isIso
        (inv (Scheme.IdealSheafData.subschemeMap _ _ (IdealSheafData.blowUpπ Z)
          (Scheme.IdealSheafData.le_map_comap _ _))) hZreg
  · -- Kollár's (1)–(3) at `x'`, from the data at `π x'`
    by_cases hxZ : IdealSheafData.blowUpπ Z x' ∈ Z.support
    · obtain ⟨n, z, hsnc, s, hZs⟩ := hZ _ hxZ
      obtain ⟨c, hcinj, hc⟩ := hsnc.2
      have := hreg (IdealSheafData.blowUpπ Z x')
      obtain ⟨g, hg, hgZ⟩ := hZ'.exists_mem_nonZeroDivisors_stalkIdeal_eq_span
          (IdealSheafData.blowUpπ Z x')
      obtain ⟨j, hsj⟩ := exists_eq_singleton_of_span_image_eq_span_singleton hsnc.1.1.symm
        hsnc.1.2 hg (hZs.symm.trans hgZ)
      have hZj : Z.stalkIdeal (IdealSheafData.blowUpπ Z x') = span {z j} := by
        have h := hZs
        rw [hsj, Finset.coe_singleton, Set.image_singleton] at h
        exact h
      obtain ⟨c', hc'inj, hc'⟩ := exists_snc_data_trivialTotalTransform
          (IdealSheafData.blowUpπ Z) hreg Z hZ'
        E.component hdata x' c hcinj hc fun _ => ⟨j, hZj⟩
      refine ⟨n, fun l => (IdealSheafData.blowUpπ Z).stalkMap x' (z l),
        ⟨(maximalIdeal_eq_span_range_stalkMap (IdealSheafData.blowUpπ Z) x' hsnc.1.1.symm).symm,
          natCast_eq_ringKrullDim_stalk_of_isIso (IdealSheafData.blowUpπ Z) x' hsnc.1.2⟩,
        fun kk => c' ⟨ofLex kk.1, kk.2⟩, fun k₁ k₂ h => ?_, fun kk => hc' ⟨ofLex kk.1, kk.2⟩⟩
      exact Subtype.ext (ofLex.injective (Subtype.mk.inj (hc'inj h)))
    · obtain ⟨n, z, hsnc⟩ := hE.2 (IdealSheafData.blowUpπ Z x')
      obtain ⟨c, hcinj, hc⟩ := hsnc.2
      obtain ⟨c', hc'inj, hc'⟩ := exists_snc_data_trivialTotalTransform
          (IdealSheafData.blowUpπ Z) hreg Z hZ'
        E.component hdata x' c hcinj hc fun h => absurd h hxZ
      refine ⟨n, fun l => (IdealSheafData.blowUpπ Z).stalkMap x' (z l),
        ⟨(maximalIdeal_eq_span_range_stalkMap (IdealSheafData.blowUpπ Z) x' hsnc.1.1.symm).symm,
          natCast_eq_ringKrullDim_stalk_of_isIso (IdealSheafData.blowUpπ Z) x' hsnc.1.2⟩,
        fun kk => c' ⟨ofLex kk.1, kk.2⟩, fun k₁ k₂ h => ?_, fun kk => hc' ⟨ofLex kk.1, kk.2⟩⟩
      exact Subtype.ext (ofLex.injective (Subtype.mk.inj (hc'inj h)))

end AlgebraicGeometry
