/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.RegularSmooth.Defs
public import Hironaka.Scheme.BlowUp.Transform.Defs
import Hironaka.Algebra.Local.Regular
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.BlowUp.Transform
import Hironaka.Scheme.BlowUp.Transform.TransformIso
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.IdealSheaf.StalkLe
import Hironaka.Scheme.Smooth.SubschemeStalk
import Hironaka.Scheme.Snc.Coordinates
import Hironaka.Scheme.Snc.HasSncWith

/-!
# The total transform under a trivial blow-up

[Kol07, Definition 65]: "If `π` is a trivial blow-up, then `π⁻¹_{tot}(E) = E + Z`";
[Kol07, Warning 20 (2)]: its exceptional divisor is `F = Z`. A trivial blow-up has an invertible
centre `Z` (a Cartier divisor) and `π : B_Z X ⟶ X` is an isomorphism (the universal property of the
blow-up applied to the identity), so the strict transform of a component `D` of `E` is the inverse
image along `π` of the saturation `D.saturate Z` computed on `X` (`strictTransformAlong_of_isIso`),
and everything reduces to stalks.

**Why the lemmas hold.** At a point `x ∈ Z` the snc data ([Kol07, Definition 24 (4)]) give a regular
system of parameters `z` of `𝒪_{X,x}` with `Z_x = (z_l : l ∈ s)` and, for a component `D` through
`x`, `D_x = (z_c)`. Since `Z_x` is principal, generated by a nonzerodivisor, `s` is a single index
`{j}`: two distinct parameters `z_j, z_{j'}` cannot both be multiples of one generator `g ∈ 𝔪` — if
`z_j = g b` with `b` a unit then `z_{j'} ∈ (z_j)`, and if `b ∈ 𝔪` then `z_j ∈ 𝔪²`, both impossible
for a regular system of parameters (`exists_eq_singleton_of_span_image_eq_span_singleton`). If
`c ≠ j` the ideal `(z_c)` is prime (the quotient is regular, hence a domain) and `z_j ∉ (z_c)`, so
`(z_c) : (z_j)^i = (z_c)`: the component is unchanged by the saturation. If `c = j` then `D_x = Z_x`
and `(z_j) : (z_j) = (1)`: the component dies near `x`. On its support the saturation therefore has
the stalks of `D` (`stalkIdeal_saturate_eq_of_mem_support`), so its subscheme is regular when `V(D)`
is (`isRegular_subscheme_saturate`), and for a component transversal to `Z` at every point the
saturation is `D` itself (`saturate_eq_self_of_snc_transversal`).

The assembly into Kollár's conditions (1)–(3) for `DivisorFamily.totalTransform` is
`Hironaka.Scheme.Snc.TrivialSncData` and `totalTransform_isSnc_of_isInvertible` of
`Hironaka.Scheme.Snc.TotalTransformSmoothBlowUp`; as in `Hironaka.Scheme.Snc.Family` the snc data
are explicit hypotheses here.

## Main declarations

* `Ideal.colon_pow_eq_self_of_isPrime` — `(p : J^i) = p` for a prime `p` and `J ⊄ p`.
* `AlgebraicGeometry.isPrime_span_singleton_of_parameters`, `colon_pow_span_image_eq_of_notMem`,
  `exists_eq_singleton_of_span_image_eq_span_singleton` — the algebra in a regular local ring.
* `AlgebraicGeometry.saturate_eq_self_of_forall_stalk`, `stalkIdeal_saturate_eq_of_mem_support`,
  `saturate_eq_self_of_snc_transversal`, `isRegular_subscheme_saturate`,
  `strictTransformAlong_eq_comap_of_saturate_eq` — the sheaf-level statements.
-/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing Ideal Scheme.IdealSheafData

/-- `(I : I) = ⊤` for an ideal `I` of a commutative ring. -/
theorem Ideal.colon_coe_self {R : Type*} [CommRing R] (I : Ideal R) : I.colon (↑I : Set R) = ⊤ :=
  top_le_iff.mp fun r _ => Submodule.mem_colon.mpr fun s hs => by
    rw [smul_eq_mul]; exact I.mul_mem_left r hs

/-- In any commutative ring, a prime ideal is unchanged by the colon with a power of an ideal not
contained in it. -/
theorem Ideal.colon_pow_eq_self_of_isPrime {R : Type*} [CommRing R] {p J : Ideal R} (hp : p.IsPrime)
    (hJ : ¬ J ≤ p) (i : ℕ) : p.colon (↑(J ^ i) : Set R) = p := by
  have := hp
  refine le_antisymm (fun r hr => ?_) fun r hr =>
    Submodule.mem_colon.mpr fun s _ => by rw [smul_eq_mul]; exact p.mul_mem_right s hr
  rw [Submodule.mem_colon] at hr
  have hJi : ¬ J ^ i ≤ p := fun h => hJ (Ideal.IsPrime.le_of_pow_le h)
  obtain ⟨y, hyJ, hyp⟩ := SetLike.not_le_iff_exists.mp hJi
  have h := hr y hyJ
  rw [smul_eq_mul] at h
  exact (hp.mem_or_mem h).resolve_right hyp

namespace AlgebraicGeometry

/-! ### Algebra in a regular local ring -/

section RegularLocalRing

variable {R : Type u} [CommRing R] [IsRegularLocalRing R] {n : ℕ} {z : Fin n → R}
  (hz : maximalIdeal R = span (Set.range z)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
include hz hn

/-- A single member of a regular system of parameters generates a prime ideal (the quotient is a
regular local ring, hence a domain; `isRegularLocalRing_quotient_span_image_finset` of
`Hironaka.Scheme.Snc.ParameterSubset`). -/
theorem isPrime_span_singleton_of_parameters (c : Fin n) : (span {z c}).IsPrime := by
  have h := isRegularLocalRing_quotient_span_image_finset hz hn {c}
  rw [Finset.coe_singleton, Set.image_singleton] at h
  exact (Ideal.Quotient.isDomain_iff_prime _).mp inferInstance

/-- `(z_c) : (z_l : l ∈ s)^i = (z_c)` for `c ∉ s` and `s` nonempty. -/
theorem colon_pow_span_image_eq_of_notMem {s : Finset (Fin n)} (hs : s.Nonempty) {c : Fin n}
    (hc : c ∉ s) (i : ℕ) : (span {z c}).colon (↑(span (z '' ↑s) ^ i) : Set R) = span {z c} := by
  obtain ⟨j, hj⟩ := hs
  have hjc : j ∉ ({c} : Finset (Fin n)) := by
    rw [Finset.mem_singleton]
    rintro rfl
    exact hc hj
  have hnot : ¬ span (z '' ↑s) ≤ span {z c} := by
    intro hle
    have h1 : z j ∈ span (z '' ↑s) := subset_span (Set.mem_image_of_mem z (Finset.mem_coe.mpr hj))
    have h2 := notMem_span_image_of_notMem hz hn hjc
    rw [Finset.coe_singleton, Set.image_singleton] at h2
    exact h2 (hle h1)
  exact Ideal.colon_pow_eq_self_of_isPrime (isPrime_span_singleton_of_parameters hz hn c) hnot i

/-- If the ideal `(z_l : l ∈ s)` of a subset of the parameters is principal, generated by a
nonzerodivisor, then `s` is a single index: two parameters cannot both be multiples of one
generator `g ∈ 𝔪` (a unit multiplier puts one in the ideal of the other, a non-unit multiplier
puts one in `𝔪²`), and `s = ∅` would make `g = 0`. -/
theorem exists_eq_singleton_of_span_image_eq_span_singleton {s : Finset (Fin n)} {g : R}
    (hg : g ∈ nonZeroDivisors R) (h : span (z '' ↑s) = span {g}) : ∃ j, s = {j} := by
  classical
  have hs : s.Nonempty := by
    by_contra hs
    rw [Finset.not_nonempty_iff_eq_empty] at hs
    rw [hs, Finset.coe_empty, Set.image_empty, span_empty] at h
    have hg0 : g = 0 := (Submodule.mem_bot R).mp (h ▸ mem_span_singleton_self g)
    exact nonZeroDivisors.ne_zero hg hg0
  obtain ⟨j, hj⟩ := hs
  have hgm : g ∈ maximalIdeal R := by
    have : g ∈ span (z '' ↑s) := h ▸ mem_span_singleton_self g
    rw [hz]
    exact span_mono (Set.image_subset_range z ↑s) this
  refine ⟨j, Finset.eq_singleton_iff_unique_mem.mpr ⟨hj, fun j' hj' => ?_⟩⟩
  by_contra hne
  obtain ⟨b, hb⟩ :=
    mem_span_singleton.mp (h ▸ subset_span (Set.mem_image_of_mem z hj) : z j ∈ span {g})
  obtain ⟨b', hb'⟩ :=
    mem_span_singleton.mp (h ▸ subset_span (Set.mem_image_of_mem z hj') : z j' ∈ span {g})
  by_cases hu : IsUnit b
  · have hgz : g = z j * ↑hu.unit⁻¹ := by
      rw [hb, mul_assoc, IsUnit.mul_val_inv, mul_one]
    have hmem : z j' ∈ span (z '' ↑({j} : Finset (Fin n))) := by
      rw [Finset.coe_singleton, Set.image_singleton, mem_span_singleton]
      exact ⟨↑hu.unit⁻¹ * b', by rw [hb', hgz, mul_assoc]⟩
    have hj'j : j' ∉ ({j} : Finset (Fin n)) := by simpa using hne
    exact notMem_span_image_of_notMem hz hn hj'j hmem
  · have hbm : b ∈ maximalIdeal R :=
      (IsLocalRing.mem_maximalIdeal b).mpr (mem_nonunits_iff.mpr hu)
    have : z j ∈ maximalIdeal R ^ 2 := by
      rw [hb, pow_two]
      exact Ideal.mul_mem_mul hgm hbm
    exact (mem_maximalIdeal_and_notMem_sq_of_span_eq ⟨hz.symm, hn⟩ j).2 this

end RegularLocalRing

/-! ### The saturation along the centre of a trivial blow-up -/

section Sheaf

variable {X : Scheme.{u}}

/-- If at every point of `D ∩ Z` the colon of the stalks is contained in the stalk of `D`, the
saturation of `D` along the invertible `Z` is `D`. -/
theorem saturate_eq_self_of_forall_stalk (D Z : X.IdealSheafData) (hZ : Z.IsInvertible)
    (h : ∀ x ∈ D.support, x ∈ Z.support → ∀ i : ℕ,
      (D.stalkIdeal x).colon (↑(Z.stalkIdeal x ^ i) : Set (X.presheaf.stalk x)) ≤ D.stalkIdeal x) :
    D.saturate Z = D := by
  refine le_antisymm (Scheme.IdealSheafData.le_of_stalkIdeal_le fun x => ?_)
      (Scheme.IdealSheafData.le_saturate D Z)
  rw [Scheme.IdealSheafData.stalkIdeal_saturate_of_isInvertible D hZ x]
  refine iSup_le fun i => ?_
  by_cases hxD : x ∈ D.support
  · by_cases hxZ : x ∈ Z.support
    · exact h x hxD hxZ i
    · rw [Scheme.IdealSheafData.stalkIdeal_eq_top_of_notMem_support Z hxZ, Ideal.top_pow]
      intro r hr
      have := Submodule.mem_colon.mp hr 1 Submodule.mem_top
      rwa [smul_eq_mul, mul_one] at this
  · rw [Scheme.IdealSheafData.stalkIdeal_eq_top_of_notMem_support D hxD]
    exact le_top

/-- The snc data of the centre `Z` and of a component `D` at a point: a regular system of parameters
`z` with `D_x = (z_c)` and `Z_x = (z_l : l ∈ s)`. -/
def SncDataAt (D Z : X.IdealSheafData) (x : X) : Prop :=
  ∃ (n : ℕ) (z : Fin n → X.presheaf.stalk x) (c : Fin n) (s : Finset (Fin n)),
    maximalIdeal (X.presheaf.stalk x) = span (Set.range z) ∧
    (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk x) ∧
    D.stalkIdeal x = span {z c} ∧ Z.stalkIdeal x = span (z '' ↑s)

variable (hreg : ∀ x : X, IsRegularLocalRing (X.presheaf.stalk x))
include hreg

/-- On the support of the saturation, the saturation of `D` along the invertible centre `Z` has the
stalks of `D`: at a point of `Z` on `D` with `D_x = (z_c)`, `Z_x = (z_j)`, either `c ≠ j` and the
colon computation gives `(z_c)`, or `c = j`, the stalk of the saturation is `(1)` and the point is
not on the support. -/
theorem stalkIdeal_saturate_eq_of_mem_support (D Z : X.IdealSheafData) (hZ : Z.IsInvertible)
    (hdata : ∀ x ∈ D.support, x ∈ Z.support → SncDataAt D Z x) {w : X}
    (hw : w ∈ (D.saturate Z).support) : (D.saturate Z).stalkIdeal w = D.stalkIdeal w := by
  have hwD : w ∈ D.support := Scheme.IdealSheafData.support_antitone
      (Scheme.IdealSheafData.le_saturate D Z) hw
  have hne : (D.saturate Z).stalkIdeal w ≠ ⊤ := fun htop =>
    (maximalIdeal.isMaximal (X.presheaf.stalk w)).ne_top
      (top_le_iff.mp (htop ▸ (Scheme.IdealSheafData.mem_support_iff_stalkIdeal_le_maximalIdeal _
          _).mp hw))
  rw [Scheme.IdealSheafData.stalkIdeal_saturate_of_isInvertible D hZ w]
  refine le_antisymm (iSup_le fun i => ?_) ?_
  · by_cases hwZ : w ∈ Z.support
    · have := hreg w
      obtain ⟨n, z, c, s, hz, hn, hD, hZw⟩ := hdata w hwD hwZ
      obtain ⟨g, hg, hgZ⟩ := hZ.exists_mem_nonZeroDivisors_stalkIdeal_eq_span w
      obtain ⟨j, rfl⟩ :=
        exists_eq_singleton_of_span_image_eq_span_singleton hz hn hg (hZw.symm.trans hgZ)
      by_cases hcj : c = j
      · exfalso
        apply hne
        rw [Scheme.IdealSheafData.stalkIdeal_saturate_of_isInvertible D hZ w]
        refine top_le_iff.mp (le_iSup_of_le 1 ?_)
        rw [hD, hZw, pow_one, Finset.coe_singleton, Set.image_singleton, hcj]
        exact (Ideal.colon_coe_self _).ge
      · rw [hD, hZw, colon_pow_span_image_eq_of_notMem hz hn (Finset.singleton_nonempty j)
          (by simpa using hcj) i]
    · rw [Scheme.IdealSheafData.stalkIdeal_eq_top_of_notMem_support Z hwZ, Ideal.top_pow]
      intro r hr
      have := Submodule.mem_colon.mp hr 1 Submodule.mem_top
      rwa [smul_eq_mul, mul_one] at this
  · have h0 : D.stalkIdeal w ≤
        (D.stalkIdeal w).colon (↑(Z.stalkIdeal w ^ 0) : Set (X.presheaf.stalk w)) := by
      rw [pow_zero]
      intro r hr
      rw [Submodule.mem_colon]
      intro s _
      rw [smul_eq_mul]
      exact Ideal.mul_mem_right s _ hr
    exact le_iSup_of_le 0 h0

/-- For a component `D` transversal to the invertible centre `Z` at every point (`c ∉ s` in the snc
data), the saturation of `D` along `Z` is `D`. -/
theorem saturate_eq_self_of_snc_transversal (D Z : X.IdealSheafData) (hZ : Z.IsInvertible)
    (hdata : ∀ x ∈ D.support, x ∈ Z.support →
      ∃ (n : ℕ) (z : Fin n → X.presheaf.stalk x) (c : Fin n) (s : Finset (Fin n)),
        maximalIdeal (X.presheaf.stalk x) = span (Set.range z) ∧
        (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk x) ∧
        D.stalkIdeal x = span {z c} ∧ Z.stalkIdeal x = span (z '' ↑s) ∧ c ∉ s) :
    D.saturate Z = D := by
  refine saturate_eq_self_of_forall_stalk D Z hZ fun x hxD hxZ i => ?_
  have := hreg x
  obtain ⟨n, z, c, s, hz, hn, hD, hZx, hcs⟩ := hdata x hxD hxZ
  obtain ⟨g, hg, hgZ⟩ := hZ.exists_mem_nonZeroDivisors_stalkIdeal_eq_span x
  obtain ⟨j, rfl⟩ :=
    exists_eq_singleton_of_span_image_eq_span_singleton hz hn hg (hZx.symm.trans hgZ)
  rw [hD, hZx, colon_pow_span_image_eq_of_notMem hz hn (Finset.singleton_nonempty j) hcs i]

/-- The subscheme of the saturation of `D` along the invertible centre `Z` is regular when `V(D)`
is: on its support the saturation has the stalks of `D`. -/
theorem isRegular_subscheme_saturate (D Z : X.IdealSheafData) (hZ : Z.IsInvertible)
    (hdata : ∀ x ∈ D.support, x ∈ Z.support → SncDataAt D Z x) (hD : IsRegular D.subscheme) :
    IsRegular (D.saturate Z).subscheme := by
  refine isRegular_subscheme_of_isRegularLocalRing_quotient _ fun w hw => ?_
  rw [stalkIdeal_saturate_eq_of_mem_support hreg D Z hZ hdata hw]
  have hwD : w ∈ D.support := Scheme.IdealSheafData.support_antitone
      (Scheme.IdealSheafData.le_saturate D Z) hw
  obtain ⟨v, rfl⟩ : w ∈ Set.range D.subschemeι := by rwa [Scheme.IdealSheafData.range_subschemeι]
  have : IsRegularLocalRing (D.subscheme.presheaf.stalk v) := hD.isRegularAt v
  exact IsRegularLocalRing.of_ringEquiv (D.stalkQuotientEquiv v).symm

end Sheaf

/-- For an isomorphism `π` (a trivial blow-up) and a closed subscheme `D` whose saturation along the
centre is `D`, the strict transform of `D` is `D` carried along `π`. -/
theorem strictTransformAlong_eq_comap_of_saturate_eq {B X : Scheme.{u}} (π : B ⟶ X) [IsIso π]
    (Z D : X.IdealSheafData) (h : D.saturate Z = D) :
    D.strictTransformAlong π (Z.comap π) = D.comap π := by
  rw [strictTransformAlong_of_isIso, h]

end AlgebraicGeometry
