/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Defs
import Hironaka.Manifold.IdealSheaf.Basic
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal

@[expose] public section

open TopCat Opposite TopologicalSpace CategoryTheory

/-!
# Colon of an ideal sheaf by a locally principal ideal sheaf

The nonmonomial part `N(I) = I : M(I)` of an ideal sheaf `I` (Kollár's Definition–Lemma 110 in the
form used by this library, `BMO/NonmonomialPart.lean`) is the colon of `I` by its monomial part
`M(I)`, and `M(I)` is locally principal, generated near every point by a section whose germs are
non-zero-divisors. This file provides the sheaf-theoretic tool that makes such a colon an ideal
sheaf: when `J` is locally generated by a non-zero-divisor section `s` and `I ⊆ J` stalkwise, the
quotients of finitely many local generators of `I` by `s` generate the stalks of the colon `I : J`
near the point, so the colon has local generators. No coordinates enter; the statements are about
an arbitrary sheaf of commutative rings on a topological space.

The two ring-theoretic lemmas at the top are elementary facts about colon ideals in a commutative
ring; the sheaf-level statements follow. Not in the sources; auxiliary for the fine split
`I = M(I) · N(I)` of [Kol07, Definition–Lemma 110].
-/

namespace Manifold

/-- The colon of `K` by the principal ideal `span {s}`, taken as a set, equals the colon by the
singleton `{s}`: testing multiplication by every multiple of `s` is testing multiplication by `s`.
An elementary fact about colon ideals, not in the sources. -/
theorem _root_.Ideal.colon_span_singleton_eq_colon_singleton {R : Type*} [CommRing R] (K : Ideal R)
    (s : R) : K.colon (↑(Ideal.span {s}) : Set R) = K.colon {s} := by
  ext r
  rw [Submodule.mem_colon, Submodule.mem_colon_singleton]
  constructor
  · intro h
    exact h s (Ideal.subset_span rfl)
  · intro h y hy
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton'.mp hy
    have hrw : r • (c * s) = c * (r • s) := by rw [smul_eq_mul, smul_eq_mul]; ring
    rw [hrw]
    exact K.mul_mem_left c h

/-- Dividing the generators of `span (range fun j => s * g j)` by the non-zero-divisor `s` (as the
colon by `{s}`) recovers `span (range g)`. The non-zero-divisor form of
`Ideal.colon_span_range_pow_mul`, used with a single factor `s` for the local generators of the
colon. Not in the sources. -/
theorem _root_.Ideal.colon_span_range_mul_of_mem_nonZeroDivisors {R : Type*} [CommRing R] {s : R}
    (hs : s ∈ nonZeroDivisors R) {ι : Type*} [Finite ι] (g : ι → R) :
    (Ideal.span (Set.range fun j => s * g j)).colon {s} = Ideal.span (Set.range g) := by
  cases nonempty_fintype ι
  ext x
  rw [Submodule.mem_colon_singleton, smul_eq_mul, Submodule.mem_span_range_iff_exists_fun,
    Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨c, ?_⟩
    have hAB : s * ∑ j, c j • g j = s * x := by
      rw [Finset.mul_sum]
      calc ∑ j, s * (c j • g j) = ∑ j, c j • (s * g j) :=
            Finset.sum_congr rfl fun j _ => by rw [smul_eq_mul, smul_eq_mul]; ring
        _ = x * s := hc
        _ = s * x := mul_comm _ _
    have hz : (∑ j, c j • g j - x) * s = 0 := by
      rw [sub_mul, mul_comm _ s, mul_comm x s, hAB, sub_self]
    exact sub_eq_zero.mp ((mem_nonZeroDivisors_iff.mp hs).2 _ hz)
  · rintro ⟨c, rfl⟩
    refine ⟨c, ?_⟩
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl fun j _ => by rw [smul_eq_mul, smul_eq_mul]; ring

universe u

variable {X : Type u} [TopologicalSpace X] {𝒪 : TopCat.Sheaf CommRingCat (TopCat.of X)}

/-- A relation `germ t = germ s · germ r` between germs at `x` extends to a neighbourhood: the
sections satisfy the same relation, germ by germ, at every point of some open neighbourhood of `x`.
This is the germ-shrinking step behind the local generators of a colon. -/
theorem _root_.Hironaka.Manifold.exists_nhds_forall_germ_mul_eq {U V W : Opens X} {x : X}
    (hxU : x ∈ U) (hxV : x ∈ V) (hxW : x ∈ W) (s : 𝒪.presheaf.obj (op U))
    (t : 𝒪.presheaf.obj (op V)) (r : 𝒪.presheaf.obj (op W))
    (heq : 𝒪.presheaf.germ V x hxV t =
      𝒪.presheaf.germ U x hxU s * 𝒪.presheaf.germ W x hxW r) :
    ∃ (O : Opens X) (_ : x ∈ O) (hOU : O ≤ U) (hOV : O ≤ V) (hOW : O ≤ W),
      ∀ y (hy : y ∈ O), 𝒪.presheaf.germ V y (hOV hy) t =
        𝒪.presheaf.germ U y (hOU hy) s * 𝒪.presheaf.germ W y (hOW hy) r := by
  have hxUW : x ∈ U ⊓ W := Opens.mem_inf.mpr ⟨hxU, hxW⟩
  set sr : 𝒪.presheaf.obj (op (U ⊓ W)) :=
    𝒪.presheaf.map (homOfLE inf_le_left).op s * 𝒪.presheaf.map (homOfLE inf_le_right).op r with hsr
  have hgerm : 𝒪.presheaf.germ V x hxV t = 𝒪.presheaf.germ (U ⊓ W) x hxUW sr := by
    rw [hsr, map_mul, TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply]; exact heq
  obtain ⟨O, hxO, iOV, iOUW, hres⟩ := 𝒪.presheaf.germ_eq x hxV hxUW t sr hgerm
  refine ⟨O, hxO, fun y hy => (iOUW.le hy).1, iOV.le, fun y hy => (iOUW.le hy).2, fun y hy => ?_⟩
  rw [← TopCat.Presheaf.germ_res_apply 𝒪.presheaf iOV y hy t, hres,
    TopCat.Presheaf.germ_res_apply 𝒪.presheaf iOUW y hy sr, hsr, map_mul,
    TopCat.Presheaf.germ_res_apply, TopCat.Presheaf.germ_res_apply]

/-- An ideal sheaf is **locally regularly principal** when, near every point, it is generated by a
single section whose germs are non-zero-divisors — the section-level form of stalkwise principality
by a non-zero-divisor. The colon of an ideal sheaf `I` by such a sheaf is generated by dividing the
generators of `I` by that section (`HasLocalRegularGenerator.hasLocalGenerators_colon`). -/
def IdealSheaf.HasLocalRegularGenerator (J : IdealSheaf 𝒪) : Prop :=
  ∀ x : X, ∃ (U : Opens X) (_ : x ∈ U) (s : 𝒪.presheaf.obj (op U)),
    ∀ (y : X) (hy : y ∈ U),
      𝒪.presheaf.germ U y hy s ∈ nonZeroDivisors (𝒪.presheaf.stalk y) ∧
      J.stalkIdeal y = Ideal.span {𝒪.presheaf.germ U y hy s}

/-- An ideal sheaf whose stalks are principal, each generated by a non-zero-divisor, is locally
regularly principal: near every point it is generated by a single section whose germs are
non-zero-divisors. The stalkwise hypothesis is upgraded to a section-level one by shrinking the
neighbourhood finitely many times. Not in the sources. -/
theorem IdealSheaf.hasLocalRegularGenerator_of_stalks (J : IdealSheaf 𝒪)
    (hJ : ∀ x : X, ∃ g ∈ nonZeroDivisors (𝒪.presheaf.stalk x),
      J.stalkIdeal x = Ideal.span {g}) : J.HasLocalRegularGenerator := by
  intro x
  obtain ⟨g, hg_nzd, hg_span⟩ := hJ x
  obtain ⟨U0, hxU0, s, hs⟩ := 𝒪.presheaf.exists_germ_eq g
  obtain ⟨V, hxV, k, f, hfmem, hfspan⟩ := J.exists_generators x
  have hJx : J.stalkIdeal x = Ideal.span {𝒪.presheaf.germ U0 x hxU0 s} := by rw [hg_span, hs]
  -- (≤) each generator of `J` is locally a multiple of `s`
  have hdiv : ∀ i : Fin k, ∃ (O : Opens X) (hxO : x ∈ O) (hOU0 : O ≤ U0) (hOV : O ≤ V),
      ∀ y (hy : y ∈ O), 𝒪.presheaf.germ V y (hOV hy) (f i) ∈
        Ideal.span {𝒪.presheaf.germ U0 y (hOU0 hy) s} := by
    intro i
    have hmem : 𝒪.presheaf.germ V x hxV (f i) ∈ Ideal.span {𝒪.presheaf.germ U0 x hxU0 s} := by
      rw [← hJx]; exact J.germ_mem_stalkIdeal hxV (hfmem i)
    obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp hmem
    obtain ⟨Ua, hxUa, ra, hra⟩ := 𝒪.presheaf.exists_germ_eq a
    obtain ⟨O, hxO, hOU0, hOV, _, hprop⟩ :=
      Hironaka.Manifold.exists_nhds_forall_germ_mul_eq hxU0 hxV hxUa s (f i) ra
        (by rw [← ha, ← hra]; exact mul_comm _ _)
    exact ⟨O, hxO, hOU0, hOV, fun y hy => by
      rw [hprop y hy]; exact Ideal.mem_span_singleton'.mpr ⟨_, mul_comm _ _⟩⟩
  choose O hxO hOU0 hOV hOle using hdiv
  have hiInf : ∀ z : X, z ∈ (⨅ i, O i : Opens X) ↔ ∀ i, z ∈ O i := fun z => by
    rw [← SetLike.mem_coe, TopologicalSpace.Opens.coe_iInf, Set.mem_iInter]
    exact ⟨fun h i => h i, fun h i => h i⟩
  -- (≥) `s` agrees near `x` with a section `g'` of `J`, so its germ lies in `J` nearby
  have hgJ : g ∈ J.stalkIdeal x := hg_span ▸ Ideal.mem_span_singleton_self g
  obtain ⟨V', hxV', g', hg'mem, hg'germ⟩ := J.mem_stalkIdeal_iff.mp hgJ
  obtain ⟨O', hxO', iO'U0, iO'V', hres'⟩ :=
    𝒪.presheaf.germ_eq x hxU0 hxV' s g' (by rw [hs, hg'germ])
  -- the neighborhood and the (restricted) generating section
  refine ⟨U0 ⊓ V ⊓ (⨅ i, O i) ⊓ O', ⟨⟨⟨hxU0, hxV⟩, (hiInf x).mpr hxO⟩, hxO'⟩,
    𝒪.presheaf.map (homOfLE (le_trans inf_le_left (le_trans inf_le_left inf_le_left))).op s,
    fun y hy => ?_⟩
  have hyU0 : y ∈ U0 := (Opens.mem_inf.mp (Opens.mem_inf.mp (Opens.mem_inf.mp hy).1).1).1
  have hyV : y ∈ V := (Opens.mem_inf.mp (Opens.mem_inf.mp (Opens.mem_inf.mp hy).1).1).2
  have hyiInf : y ∈ (⨅ i, O i : Opens X) := (Opens.mem_inf.mp (Opens.mem_inf.mp hy).1).2
  have hyO' : y ∈ O' := (Opens.mem_inf.mp hy).2
  have hyO : ∀ i, y ∈ O i := (hiInf y).mp hyiInf
  have hsy : 𝒪.presheaf.germ _ y hy
      (𝒪.presheaf.map (homOfLE (le_trans inf_le_left (le_trans inf_le_left inf_le_left))).op s) =
        𝒪.presheaf.germ U0 y hyU0 s := TopCat.Presheaf.germ_res_apply _ _ _ _ _
  -- `J.stalkIdeal y = span {germ_y s}`
  have hle : J.stalkIdeal y ≤ Ideal.span {𝒪.presheaf.germ U0 y hyU0 s} := by
    rw [hfspan y hyV, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    have := hOle i y (hyO i)
    rwa [show 𝒪.presheaf.germ V y (hOV i (hyO i)) (f i) = 𝒪.presheaf.germ V y hyV (f i) from rfl,
      show 𝒪.presheaf.germ U0 y (hOU0 i (hyO i)) s = 𝒪.presheaf.germ U0 y hyU0 s from rfl] at this
  have hge : Ideal.span {𝒪.presheaf.germ U0 y hyU0 s} ≤ J.stalkIdeal y := by
    rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe]
    have hsg' : 𝒪.presheaf.germ U0 y hyU0 s = 𝒪.presheaf.germ V' y (iO'V'.le hyO') g' := by
      rw [← TopCat.Presheaf.germ_res_apply 𝒪.presheaf iO'U0 y hyO' s, hres',
        TopCat.Presheaf.germ_res_apply]
    rw [hsg']; exact J.germ_mem_stalkIdeal _ hg'mem
  have hJy : J.stalkIdeal y = Ideal.span {𝒪.presheaf.germ U0 y hyU0 s} := le_antisymm hle hge
  refine ⟨?_, by rw [hsy, hJy]⟩
  -- the germ of `s` at `y` is a non-zero-divisor: it divides the non-zero-divisor generator `g_y`
  rw [hsy]
  obtain ⟨gy, hgy_nzd, hgy_span⟩ := hJ y
  have hgy_mem : gy ∈ Ideal.span {𝒪.presheaf.germ U0 y hyU0 s} := by
    rw [← hJy, hgy_span]; exact Ideal.mem_span_singleton_self gy
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp hgy_mem
  rw [mem_nonZeroDivisors_iff]
  refine ⟨fun z hz => (mem_nonZeroDivisors_iff.mp hgy_nzd).1 z ?_,
    fun z hz => (mem_nonZeroDivisors_iff.mp hgy_nzd).2 z ?_⟩
  · rw [← hc, mul_assoc, hz, mul_zero]
  · have : z * gy = c * (z * 𝒪.presheaf.germ U0 y hyU0 s) := by rw [← hc]; ring
    rw [this, hz, mul_zero]

/-- If `I ≤ J` stalkwise and `J` is locally regularly principal, then the colon `x ↦ (I_x : J_x)`
has local generators: near a point where `J` is generated by the non-zero-divisor section `s`, each
generator of `I` is `s` times a section, and these quotients generate the colon
(`Ideal.colon_span_range_mul_of_mem_nonZeroDivisors`). Applied to `J = M(I)`, this is what makes the
nonmonomial part `N(I) = I : M(I)` of [Kol07, Definition–Lemma 110] an ideal sheaf. -/
theorem IdealSheaf.HasLocalRegularGenerator.hasLocalGenerators_colon {I J : IdealSheaf 𝒪}
    (hJ : J.HasLocalRegularGenerator) (hIJ : ∀ x, I.stalkIdeal x ≤ J.stalkIdeal x) :
    IdealSheaf.HasLocalGenerators
      (fun x => Submodule.colon (I.stalkIdeal x) (↑(J.stalkIdeal x))) := by
  intro x
  obtain ⟨U, hxU, s, hsprop⟩ := hJ x
  obtain ⟨V, hxV, k, f, hfmem, hfspan⟩ := I.exists_generators x
  have hdiv : ∀ i : Fin k, ∃ (O : Opens X) (hxO : x ∈ O) (hOU : O ≤ U) (hOV : O ≤ V)
      (Ur : Opens X) (ri : 𝒪.presheaf.obj (op Ur)) (hOUr : O ≤ Ur),
      ∀ y (hy : y ∈ O), 𝒪.presheaf.germ V y (hOV hy) (f i) =
        𝒪.presheaf.germ U y (hOU hy) s * 𝒪.presheaf.germ Ur y (hOUr hy) ri := by
    intro i
    have hmem : 𝒪.presheaf.germ V x hxV (f i) ∈ Ideal.span {𝒪.presheaf.germ U x hxU s} := by
      rw [← (hsprop x hxU).2]; exact hIJ x (I.germ_mem_stalkIdeal hxV (hfmem i))
    obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp hmem
    obtain ⟨Ur, hxUr, ri, hri⟩ := 𝒪.presheaf.exists_germ_eq a
    obtain ⟨O, hxO, hOU, hOV, hOUr, hprop⟩ :=
      Hironaka.Manifold.exists_nhds_forall_germ_mul_eq hxU hxV hxUr s (f i) ri
        (by rw [← ha, ← hri]; exact mul_comm _ _)
    exact ⟨O, hxO, hOU, hOV, Ur, ri, hOUr, hprop⟩
  choose O hxO hOU hOV Ur ri hOUr hprop using hdiv
  have hiInf : ∀ z : X, z ∈ (⨅ i, O i : Opens X) ↔ ∀ i, z ∈ O i := fun z => by
    rw [← SetLike.mem_coe, TopologicalSpace.Opens.coe_iInf, Set.mem_iInter]
    exact ⟨fun h i => h i, fun h i => h i⟩
  refine ⟨U ⊓ V ⊓ (⨅ i, O i), ⟨⟨hxU, hxV⟩, (hiInf x).mpr hxO⟩, Fin k, inferInstance,
    fun i => 𝒪.presheaf.map
      (homOfLE (le_trans inf_le_right (le_trans (iInf_le O i) (hOUr i)))).op (ri i),
    fun y hy => ?_⟩
  have hyU : y ∈ U := (Opens.mem_inf.mp (Opens.mem_inf.mp hy).1).1
  have hyV : y ∈ V := (Opens.mem_inf.mp (Opens.mem_inf.mp hy).1).2
  have hyO : ∀ i, y ∈ O i := (hiInf y).mp (Opens.mem_inf.mp hy).2
  obtain ⟨hs_nzd, hJy⟩ := hsprop y hyU
  have hIy : I.stalkIdeal y = Ideal.span (Set.range fun i =>
      𝒪.presheaf.germ U y hyU s * 𝒪.presheaf.germ (Ur i) y (hOUr i (hyO i)) (ri i)) := by
    rw [hfspan y hyV]
    exact congrArg Ideal.span (congrArg Set.range (funext fun i => hprop i y (hyO i)))
  change Submodule.colon (I.stalkIdeal y) (↑(J.stalkIdeal y)) = _
  rw [hJy, hIy, Ideal.colon_span_singleton_eq_colon_singleton,
    Ideal.colon_span_range_mul_of_mem_nonZeroDivisors hs_nzd]
  exact congrArg Ideal.span (congrArg Set.range (funext fun i =>
    (TopCat.Presheaf.germ_res_apply _ _ _ _ _).symm))

end Manifold
