/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Analytic.OrderReduction.BMO.MonomialPart
public import Hironaka.Resolution.Analytic.OrderReduction.BMO.ColonLocalPrincipal
public import Hironaka.Resolution.Analytic.OrderReduction.BMO.Split
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The nonmonomial part of an ideal sheaf

The decomposition `I = M(I) · N(I)` of [Kol07, Definition–Lemma 110] defines the **nonmonomial
part** `N(I)` of an ideal sheaf `I` with respect to a boundary family: the part of `I` left after
the monomial part `M(I)` (`BMO/MonomialPart.lean`) has been divided out, that is, the ideal colon
`N(I) = I : M(I)`. This file assembles `N(I)` as an ideal sheaf on an analytic manifold.

The stalk of `N(I)` at `x` is the colon `I_x : M(I)_x`. It has local generators because `M(I)` is
locally generated by a single non-zero-divisor (`exists_nonZeroDivisor_stalkIdeal_monomialPart`,
`BMO/Split.lean`) and `I ⊆ M(I)` stalkwise (`stalkIdeal_le_monomialPart`): the general colon lemma
`HasLocalRegularGenerator.hasLocalGenerators_colon` of `BMO/ColonLocalPrincipal.lean` then divides
the local generators of `I` by the generator of `M(I)`. The analytic counterpart of
`Hironaka.BMO.nonmonomialPart`.
-/

@[expose] public section

open Set
open scoped Manifold ContDiff Topology

universe u

namespace Hironaka.Manifold.BMO

open _root_.Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  [IsManifold 𝓘(𝕜, E) ω M]

variable (F : HypersurfaceFamily M)

/-- The **nonmonomial part** `N(I) = I : M(I)` of `I` with respect to the boundary family `F`: the
ideal sheaf whose stalk at `x` is the colon of `I_x` by the stalk of the monomial part
([Kol07, Definition–Lemma 110]). Its local generators come from dividing those of `I` by the local
non-zero-divisor generator of `M(I)`. The analytic counterpart of `Hironaka.BMO.nonmonomialPart`. -/
noncomputable def nonmonomialPart (hF : F.IsSnc ψ) (I : IdealSheaf (structureSheaf 𝕜 E M)) :
    IdealSheaf (structureSheaf 𝕜 E M) :=
  IdealSheaf.ofStalks (structureSheaf 𝕜 E M)
    (fun x => Submodule.colon (I.stalkIdeal x) (↑((monomialPart F hF I).stalkIdeal x)))
    ((IdealSheaf.hasLocalRegularGenerator_of_stalks (monomialPart F hF I)
        (exists_nonZeroDivisor_stalkIdeal_monomialPart F hF I)).hasLocalGenerators_colon
      (stalkIdeal_le_monomialPart F hF I))

/-- The stalk of the nonmonomial part `N(I)` at `x` is the colon `I_x : M(I)_x`. -/
@[simp] theorem stalkIdeal_nonmonomialPart (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (x : M) :
    (nonmonomialPart F hF I).stalkIdeal x =
      Submodule.colon (I.stalkIdeal x) (↑((monomialPart F hF I).stalkIdeal x)) := by
  rw [nonmonomialPart, IdealSheaf.stalkIdeal_ofStalks]

end Hironaka.Manifold.BMO
