/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Analytic.OrderReduction.BMO.MonomialPart
public import Hironaka.Manifold.Snc.Basic
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.BlowUp.Transform.OrderAlong
import Hironaka.Manifold.BlowUp.Transform.StrictCharts
import Hironaka.Manifold.BlowUp.Transform.StrictIdeal
import Hironaka.Manifold.Snc.Dictionary
import Hironaka.Manifold.Submanifold.Components
import Mathlib.Algebra.Category.Ring.FilteredColimits
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The monomial part is locally principal

The decomposition `I = M(I) · N(I)` of [Kol07, Definition–Lemma 110] rests on the monomial part
`M(I)` being an invertible ideal sheaf. This file proves the local form of that statement on an
analytic manifold: at every point `x` the stalk `M(I)_x` is the principal ideal generated by a
nonzero element of the domain `𝒪_{M,x}`, namely the monomial `∏_D z_D^{ord_D I}` over the
components `D` through `x`, where `z_D` is the coordinate cutting out `D` in a chart adapted to the
boundary family. The file also proves the containment `I_x ⊆ M(I)_x`, which the colon
`N(I) = I : M(I)` needs: `I` vanishes to order `≥ ord_D I` along each component `D` through `x`, the
coordinates of distinct components are pairwise non-associated primes of the stalk, and so their
product of powers divides every element of `I_x`.

Two general facts sit beside their use here: `prod_pow_dvd_of_prime_of_not_dvd` (divisibility by a
product of powers of pairwise non-dividing primes in a domain) and `nhds_subtype_map_eq`. The
analytic counterpart of `Hironaka.BMO.isInvertible_monomialPart`.
-/

public section

open Set
open scoped Manifold ContDiff Topology

universe u

namespace Hironaka.Manifold.BMO

open _root_.Manifold

/-- In a domain, if `z` is divisible by each `p i ^ e i` over a finite set of pairwise non-dividing
primes `p i`, then it is divisible by their product. The prime-power form of
`IsLocalRing.prod_dvd_of_prime_of_not_dvd`; not in the sources. -/
theorem _root_.prod_pow_dvd_of_prime_of_not_dvd {R : Type*} [CommRing R] [IsDomain R] {ι : Type*}
    (s : Finset ι) (p : ι → R) (e : ι → ℕ) (hp : ∀ i ∈ s, Prime (p i))
    (hnd : ∀ i ∈ s, ∀ j ∈ s, i ≠ j → ¬ p i ∣ p j) {z : R} (hz : ∀ i ∈ s, p i ^ e i ∣ z) :
    ∏ i ∈ s, p i ^ e i ∣ z := by
  classical
  induction s using Finset.induction_on generalizing z with
  | empty => simp
  | insert a s has ih =>
    rw [Finset.prod_insert has]
    obtain ⟨t, rfl⟩ := ih (fun i hi => hp i (Finset.mem_insert_of_mem hi))
      (fun i hi j hj hij => hnd i (Finset.mem_insert_of_mem hi) j (Finset.mem_insert_of_mem hj) hij)
      (fun i hi => hz i (Finset.mem_insert_of_mem hi))
    have hpa : Prime (p a) := hp a (Finset.mem_insert_self a s)
    have hpa_ndvd : ¬ p a ∣ ∏ i ∈ s, p i ^ e i := by
      rw [hpa.dvd_finsetProd_iff]
      rintro ⟨i, hi, hdvd⟩
      exact hnd a (Finset.mem_insert_self a s) i (Finset.mem_insert_of_mem hi)
        (fun h => has (h ▸ hi)) (hpa.dvd_of_dvd_pow hdvd)
    have hpat : p a ^ e a ∣ t :=
      hpa.pow_dvd_of_dvd_mul_left (e a) hpa_ndvd (hz a (Finset.mem_insert_self a s))
    rw [mul_comm (∏ i ∈ s, p i ^ e i) t]
    exact mul_dvd_mul_right hpat _

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  [IsManifold 𝓘(𝕜, E) ω M]

variable (F : HypersurfaceFamily M)

/-- The stalk of the monomial part `M(I)` at `x` is the principal ideal of a nonzero element of the
domain `𝒪_{M,x}`, namely the monomial `∏_D z_D^{ord_D I}` over the components `D` through `x`, `z_D`
the adapted coordinate of `D`. This is the local content of "`M(I)` is invertible" in
[Kol07, Definition–Lemma 110]. -/
theorem stalkIdeal_monomialPart_eq_span (hF : F.IsSnc ψ) (I : IdealSheaf (structureSheaf 𝕜 E M))
    (x : M) :
    ∃ g : (structureSheaf 𝕜 E M).presheaf.stalk x, g ≠ 0 ∧
      (monomialPart F hF I).stalkIdeal x = Ideal.span {g} := by
  classical
  have _hdom : IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk x) :=
    isDomain_stalk ψ (IsManifold.chart_mem_maximalAtlas x) (mem_chart_source E x)
  rw [stalkIdeal_monomialPart]
  refine Finset.prod_induction _
    (fun J => ∃ g : (structureSheaf 𝕜 E M).presheaf.stalk x, g ≠ 0 ∧ J = Ideal.span {g})
    (fun J J' hJ hJ' => ?_) ⟨1, one_ne_zero, by rw [Ideal.span_singleton_one]; exact
      Ideal.one_eq_top⟩ fun i hi => ?_
  · obtain ⟨g, hg, rfl⟩ := hJ
    obtain ⟨g', hg', rfl⟩ := hJ'
    exact ⟨g * g', mul_ne_zero hg hg', Ideal.span_singleton_mul_span_singleton g g'⟩
  · rw [IdealSheaf.mem_activeFinset] at hi
    obtain ⟨φ, σ, haφ, hφ⟩ := (componentSubmanifold F hF i).exists_adaptedChart x hi
    refine ⟨coord E ψ φ hφ.1 haφ (σ default) ^ componentExponent F hF I i,
      pow_ne_zero _ (coord_ne_zero hφ.1 haφ (σ default)), ?_⟩
    change ((componentSubmanifold F hF i).idealSheaf ^ componentExponent F hF I i).stalkIdeal x = _
    rw [IdealSheaf.stalkIdeal_pow,
      (componentSubmanifold F hF i).stalkIdeal_idealSheaf_eq_span hi hφ haφ, Set.range_unique,
      Ideal.span_singleton_pow]

/-- The stalk of the monomial part `M(I)` at `x` is generated by a single non-zero-divisor (a
nonzero element of the domain `𝒪_{M,x}`). This is the hypothesis under which the colon `I : M(I)`
has local generators (`BMO/ColonLocalPrincipal.lean`). -/
theorem exists_nonZeroDivisor_stalkIdeal_monomialPart (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (x : M) :
    ∃ g ∈ nonZeroDivisors ((structureSheaf 𝕜 E M).presheaf.stalk x),
      (monomialPart F hF I).stalkIdeal x = Ideal.span {g} := by
  have _hdom : IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk x) :=
    isDomain_stalk ψ (IsManifold.chart_mem_maximalAtlas x) (mem_chart_source E x)
  obtain ⟨g, hg, heq⟩ := stalkIdeal_monomialPart_eq_span F hF I x
  exact ⟨g, mem_nonZeroDivisors_of_ne_zero hg, heq⟩

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- At a point `x` of the component `D = i`, the ideal `I` vanishes to order at least `ord_D I`
along `D`, so `I_x ⊆ 𝓘_D^{ord_D I}`: the order of `I` along `D` is constant on the connected
component and bounded by its value at `x`. One factor of the containment `I ⊆ M(I)`. -/
theorem stalkIdeal_le_componentFactor (hF : F.IsSnc ψ) (I : IdealSheaf (structureSheaf 𝕜 E M))
    (i : ComponentIndex F) {x : M} (hx : x ∈ componentSet F i) :
    I.stalkIdeal x ≤ (componentFactor F hF I i).stalkIdeal x := by
  have hset : (ConnectedComponents.mk ⁻¹' {i.2} : Set (F.hyp i.1)) =
      connectedComponent i.2.out := by
    conv_lhs => rw [← Quotient.out_eq' i.2]
    exact connectedComponents_preimage_singleton
  have hpre : IsPreconnected (componentSet F i) := by
    rw [componentSet, hset]
    exact isPreconnected_connectedComponent.image _ continuous_subtype_val.continuousOn
  have hrepr : (i.2.out : F.hyp i.1).val ∈ componentSet F i :=
    ⟨i.2.out, by rw [Set.mem_preimage, Set.mem_singleton_iff]; exact Quotient.out_eq' i.2, rfl⟩
  have hxin : x ∈ connectedComponentIn (componentIdeal F hF i).support
      (i.2.out : F.hyp i.1).val := by
    rw [componentIdeal, (componentSubmanifold F hF i).cosupport_idealSheaf]
    exact hpre.subset_connectedComponentIn hrepr subset_rfl hx
  change I.stalkIdeal x ≤ (componentIdeal F hF i ^ componentExponent F hF I i).stalkIdeal x
  rw [IdealSheaf.stalkIdeal_pow]
  refine (IdealSheaf.le_ordAlongIdeal_iff _ _ _ _).mp ?_
  calc (componentExponent F hF I i : ℕ∞)
      ≤ IdealSheaf.genericOrdAlong (componentIdeal F hF i) I (i.2.out : F.hyp i.1).val :=
        ENat.natCast_toNat_le_self _
    _ ≤ IdealSheaf.ordAlongIdeal (componentIdeal F hF i) I x := by
        rw [IdealSheaf.genericOrdAlong]
        exact biInf_le _ hxin

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- A point of a member `E^j` lies in exactly one connected component of `E^j`: two components of
the same member through a common point coincide. This transfers the pairwise coprimality of the
coordinates of distinct members to the components through a point. -/
theorem active_component_injective_fst {i i' : ComponentIndex F} {x : M}
    (hi : x ∈ componentSet F i) (hi' : x ∈ componentSet F i') (hfst : i.1 = i'.1) : i = i' := by
  obtain ⟨j, C⟩ := i
  obtain ⟨j', C'⟩ := i'
  obtain rfl : j = j' := hfst
  simp only [componentSet, Set.mem_image, Set.mem_preimage, Set.mem_singleton_iff] at hi hi'
  obtain ⟨x1, hx1, hx1v⟩ := hi
  obtain ⟨x2, hx2, hx2v⟩ := hi'
  have hx12 : x1 = x2 := Subtype.ext (hx1v.trans hx2v.symm)
  exact Sigma.ext rfl (heq_of_eq (by rw [← hx1, ← hx2, hx12]))

/-- The neighbourhood filter within a set `s` at `x ∈ s` is the image of the neighbourhood filter of
the subtype at `⟨x, hx⟩`, stated with the base point spelled as `x : X` so that it rewrites
directly. -/
theorem nhds_subtype_map_eq {X : Type*} [TopologicalSpace X] {s : Set X} {x : X} (hx : x ∈ s) :
    Filter.map (Subtype.val : s → X) (𝓝 (⟨x, hx⟩ : s)) = 𝓝[s] x :=
  map_nhds_subtype_val _

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- Near a point `x` of the component `D = i`, the reduced ideal sheaf of `D` and the reduced ideal
sheaf of the whole member `E^{i.1}` have the same stalk: the component is a connected component of
the member, hence open in it (a closed submanifold is locally connected), so the two sets have the
same neighbourhood filter at `x`, and a germ lies in either stalk ideal exactly when its section
vanishes on the set near `x`. This carries the member-indexed coordinates of a chart adapted to the
boundary to the component-indexed factors of `M(I)`. -/
theorem componentIdeal_stalkIdeal_eq (hF : F.IsSnc ψ) (i : ComponentIndex F) {x : M}
    (hx : x ∈ componentSet F i) :
    (componentIdeal F hF i).stalkIdeal x =
      (hF.isClosedSubmanifold i.1).idealSheaf.stalkIdeal x := by
  have hsub : componentSet F i ⊆ F.hyp i.1 := Subtype.coe_image_subset _ _
  have hxmem : x ∈ F.hyp i.1 := hsub hx
  have hnhds : 𝓝[componentSet F i] x = 𝓝[F.hyp i.1] x := by
    have hmem : componentSet F i ∈ 𝓝[F.hyp i.1] x := by
      have _hlc : LocallyConnectedSpace (F.hyp i.1) :=
        (hF.isClosedSubmanifold i.1).locallyConnectedSpace'
      have hpre : (Subtype.val : F.hyp i.1 → M) ⁻¹' componentSet F i =
          connectedComponent i.2.out := by
        rw [componentSet, Set.preimage_image_eq _ Subtype.val_injective]
        conv_lhs => rw [← Quotient.out_eq' i.2]
        exact connectedComponents_preimage_singleton
      have hxc : (⟨x, hxmem⟩ : F.hyp i.1) ∈
          (Subtype.val : F.hyp i.1 → M) ⁻¹' componentSet F i := Set.mem_preimage.mpr hx
      have hpremem : (Subtype.val : F.hyp i.1 → M) ⁻¹' componentSet F i ∈
          𝓝 (⟨x, hxmem⟩ : F.hyp i.1) := by
        rw [hpre] at hxc ⊢
        exact isOpen_connectedComponent.mem_nhds hxc
      rw [← nhds_subtype_map_eq hxmem]
      exact Filter.mem_map.mpr hpremem
    have hint := nhdsWithin_inter_of_mem' hmem
    rwa [Set.inter_eq_self_of_subset_right hsub] at hint
  ext s
  obtain ⟨V, haV, g, rfl⟩ := (structureSheaf 𝕜 E M).presheaf.exists_germ_eq s
  rw [componentIdeal, (componentSubmanifold F hF i).germ_mem_stalkIdeal_idealSheaf_iff V hx haV,
    (hF.isClosedSubmanifold i.1).germ_mem_stalkIdeal_idealSheaf_iff V hxmem haV]
  have hL : Filter.map (Subtype.val : componentSet F i → M) (𝓝 (⟨x, hx⟩ : componentSet F i)) =
      𝓝[componentSet F i] x := nhds_subtype_map_eq hx
  have hR : Filter.map (Subtype.val : F.hyp i.1 → M) (𝓝 (⟨x, hxmem⟩ : F.hyp i.1)) =
      𝓝[F.hyp i.1] x := nhds_subtype_map_eq hxmem
  have hLiff : (∀ᶠ y : componentSet F i in 𝓝 (⟨x, hx⟩ : componentSet F i),
        extendSection 𝕜 E g (y : M) = 0) ↔
      ∀ᶠ z in 𝓝[componentSet F i] x, extendSection 𝕜 E g z = 0 := by
    rw [← hL]; exact Iff.rfl
  have hRiff : (∀ᶠ y : F.hyp i.1 in 𝓝 (⟨x, hxmem⟩ : F.hyp i.1),
        extendSection 𝕜 E g (y : M) = 0) ↔
      ∀ᶠ z in 𝓝[F.hyp i.1] x, extendSection 𝕜 E g z = 0 := by
    rw [← hR]; exact Iff.rfl
  rw [hLiff, hRiff, hnhds]

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The stalk containment `I_x ⊆ M(I)_x`, the hypothesis of the colon `N(I) = I : M(I)` in
[Kol07, Definition–Lemma 110]. In a chart adapted to the boundary at `x`, each component `D` through
`x` has `𝓘_D` generated by the coordinate `z_D` of its member (`componentIdeal_stalkIdeal_eq`), so
`M(I)_x` is generated by `∏_D z_D^{ord_D I}`; each factor `z_D^{ord_D I}` divides every element of
`I_x` (`stalkIdeal_le_componentFactor`), and the coordinates of distinct components are pairwise
non-dividing primes, so the product divides as well (`prod_pow_dvd_of_prime_of_not_dvd`). -/
theorem stalkIdeal_le_monomialPart (hF : F.IsSnc ψ) (I : IdealSheaf (structureSheaf 𝕜 E M))
    (x : M) : I.stalkIdeal x ≤ (monomialPart F hF I).stalkIdeal x := by
  classical
  obtain ⟨φ, c, hc⟩ := hF.exists_isSncChartAt x
  have _hdom : IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk x) :=
    isDomain_stalk ψ hc.1 hc.2.1
  intro s hs
  rw [stalkIdeal_monomialPart]
  set T : Finset (ComponentIndex F) :=
    IdealSheaf.activeFinset (componentSet F) (componentSet_locallyFinite F hF) x with hTdef
  have hmemC : ∀ i ∈ T, x ∈ componentSet F i := fun i hi =>
    IdealSheaf.mem_activeFinset.mp (hTdef ▸ hi)
  have hmemx : ∀ i ∈ T, x ∈ F.hyp i.1 := fun i hi =>
    Subtype.coe_image_subset _ _ (hmemC i hi)
  set g : ComponentIndex F → (structureSheaf 𝕜 E M).presheaf.stalk x :=
    fun i => if h : x ∈ F.hyp i.1 then coord E ψ φ hc.1 hc.2.1 (c ⟨i.1, h⟩) else 1 with hgdef
  have hg : ∀ (i : ComponentIndex F) (hi : i ∈ T),
      g i = coord E ψ φ hc.1 hc.2.1 (c ⟨i.1, hmemx i hi⟩) := by
    intro i hi
    simp only [hgdef]
    exact dif_pos (hmemx i hi)
  have hCF : ∀ i ∈ T, (componentFactor F hF I i).stalkIdeal x =
      Ideal.span {g i ^ componentExponent F hF I i} := by
    intro i hi
    have hadapt : IsAdaptedChart ψ (F.hyp i.1) φ (singleEmb (c ⟨i.1, hmemx i hi⟩)) :=
      isAdaptedChart_singleIdx hc.1 fun y hy => hc.mem_iff ⟨i.1, hmemx i hi⟩ hy
    rw [componentFactor, IdealSheaf.stalkIdeal_pow,
      componentIdeal_stalkIdeal_eq F hF i (hmemC i hi),
      (hF.isClosedSubmanifold i.1).stalkIdeal_idealSheaf_eq_span (hmemx i hi) hadapt hc.2.1,
      range_singleIdx_coord, hg i hi, Ideal.span_singleton_pow]
  have hMeq : (∏ i ∈ T, (componentFactor F hF I i).stalkIdeal x) =
      Ideal.span {∏ i ∈ T, g i ^ componentExponent F hF I i} := by
    rw [Finset.prod_congr rfl hCF, Ideal.prod_span_singleton]
  rw [hMeq, Ideal.mem_span_singleton]
  refine prod_pow_dvd_of_prime_of_not_dvd T g (fun i => componentExponent F hF I i)
    (fun i hi => ?_) (fun i hi j hj hij => ?_) (fun i hi => ?_)
  · rw [hg i hi]; exact hc.prime_coord _
  · rw [hg i hi, hg j hj]
    refine hc.not_coord_dvd fun h => hij ?_
    exact active_component_injective_fst F (hmemC i hi)
      (hmemC j hj) (congrArg Subtype.val h)
  · rw [← Ideal.mem_span_singleton, ← hCF i hi]
    exact stalkIdeal_le_componentFactor F hF I i (hmemC i hi) hs

end Hironaka.Manifold.BMO
