/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.Snc.TotalTransform
public import Hironaka.Manifold.BlowUp.Divisor
public import Hironaka.Manifold.IdealSheaf.Monoid
public import Hironaka.Resolution.Analytic.OrderReduction.BMO.NonmonomialPart
import Hironaka.Manifold.BlowUp.CoordGerm
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.BlowUp.Transform.StrictCharts
import Hironaka.Manifold.BlowUp.Transform.StrictIdeal
import Hironaka.Manifold.IdealSheaf.Pullback
import Hironaka.Manifold.Sheaf.LocalRing
import Hironaka.Manifold.Submanifold.Ideal
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Split
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Step1Comap
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Step1IdealDecomp
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Step1Measure
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Step1MeasureOrder
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Step1Transform
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The total transform of the monomial part is a monomial in the transformed boundary

Let `π : M' → M` be the blow-up of a centre `Y` having simple normal crossings with the boundary
family `F`, and let `F' = F.totalTransform π Y` be the transformed family (the strict transforms of
the members followed by the exceptional divisor). This file proves that the total transform
`π^* M(𝓘)` of the monomial part of an ideal sheaf `𝓘` (`BMO/MonomialPart.lean`) is a locally finite
product of powers of the component ideals of `F'` (`exists_comap_monomialPart_eq_monomial`), so that
its nonmonomial part with respect to `F'` is the unit ideal
(`nonmonomialPart_totalTransform_monomialPart_eq_top`) and it is its own monomial part
(`monomialPart_totalTransform_monomialPart_eq_self`). This is the content, for the monomial part
over connected components, of the remark in [Kol07, 111, Step 1] that tensoring with an ideal sheaf
of exceptional divisors changes only the monomial part.

The proof is stalkwise and has three parts.

* **The general engine.** The stalk of `M(K)` at `x` depends only on the stalk of `K` at `x`, since
  every exponent is the order of `K` along a component at `x` (`monomialPart_stalkIdeal_congr`,
  `nonmonomialPart_stalkIdeal_congr`). Hence the nonmonomial part ignores a locally finite product
  of powers of component ideals (`nonmonomialPart_locallyFiniteProduct_pow_mul`), and an ideal sheaf
  whose stalks are all monomials in the active component ideals has trivial nonmonomial part
  (`nonmonomialPart_eq_top_of_forall_stalkIdeal_eq_prod`), hence equals its own monomial part.
* **The exceptional divisor.** The exceptional ideal sheaf is the ideal sheaf of the closed
  submanifold `π⁻¹(Y)`; at a point of one of its connected components it has the stalk of that
  component's ideal (`stalkIdeal_componentIdeal_totalTransform_inr`), so the nonmonomial part for
  `F'` ignores powers of the exceptional ideal (`nonmonomialPart_exceptionalIdealSheaf_pow_mul`).
* **The chart computation.** Off the centre the blow-up is a local analytic isomorphism, and the
  total transform of the ideal of a component `D` of `F` has the stalk of the component of the
  strict transform of `D` through the point. Over the centre, in a chart adapted to `Y` and to `F`
  at `a ∈ Y` and a blow-up chart of index `i₀` at `x` over `a`, the total transform of the ideal of
  a component `D` through `a` is generated by the pull-back of the coordinate `z_D` of `D`, which
  is: the coordinate of the exceptional divisor, if `z_D` is the scaling coordinate `σ i₀`; that
  coordinate times the ratio coordinate `u_{σ k}`, if `z_D = z_{σ k}` with `k ≠ i₀`, the ratio
  coordinate being the coordinate of the strict transform of `D` when `x` lies on it and a unit
  otherwise; the same coordinate of the blow-up chart, if `z_D` is off the block of the centre,
  again the coordinate of the strict transform of `D` or a unit. In every case the stalk is a
  monomial in the stalks of the component ideals of `F'` through `x`.

The assembly (`stalkIdeal_totalTransform_monomialPart_eq_prod`) writes the stalk of `π^* M(𝓘)` at
`x` as a product of such factors, with exponents depending on `x` (the bookkeeping of finite
monomials is `IsFinsetMonomial`), and the engine concludes. Blow-up charts are those of
[BM88, Definition 4.1]; the exponents are Kollár's `cᵢ` of [Kol07, Definition–Lemma 110], read at
one stalk.
-/

@[expose] public section

noncomputable section

open Set Topology TopologicalSpace
open scoped Manifold ContDiff

universe u

namespace Hironaka.Manifold.BMO

open _root_.Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)}

/-! ### The general engine: stalkwise monomials have trivial non-monomial part -/

section Engine

variable {X : Type u} [TopologicalSpace X] [ChartedSpace E X] [IsManifold 𝓘(𝕜, E) ω X]
  (G : HypersurfaceFamily X) (hG : G.IsSnc ψ)

omit [IsManifold 𝓘(𝕜, E) ω X] in
/-- Off its component, any power of the component ideal is the unit ideal: the controlling-set
hypothesis of the locally finite product `∏ᵢ 𝓘ᵢ ^ aᵢ` for an arbitrary exponent function `a`. -/
theorem componentIdeal_pow_stalkIdeal_top_of_notMem (a : ComponentIndex G → ℕ)
    (i : ComponentIndex G) (x : X) (hx : x ∉ componentSet G i) :
    (componentIdeal G hG i ^ a i).stalkIdeal x = ⊤ := by
  change ((componentSubmanifold G hG i).idealSheaf ^ a i).stalkIdeal x = ⊤
  rw [IdealSheaf.stalkIdeal_pow, (componentSubmanifold G hG i).stalkIdeal_idealSheaf_of_notMem hx,
    ← Ideal.one_eq_top, one_pow]

/-- The ideal sheaf of a component is nonzero at every point: on the component its stalk is
generated by a prime element, off it the stalk is the unit ideal. -/
theorem componentIdeal_isNonzeroEverywhere (i : ComponentIndex G) :
    (componentIdeal G hG i).IsNonzeroEverywhere := by
  intro x
  have _hdom : IsDomain ((structureSheaf 𝕜 E X).presheaf.stalk x) :=
    isDomain_stalk ψ (IsManifold.chart_mem_maximalAtlas x) (mem_chart_source E x)
  change (componentSubmanifold G hG i).idealSheaf.stalkIdeal x ≠ ⊥
  by_cases hx : x ∈ componentSet G i
  · obtain ⟨p, hp, hspan⟩ :=
      (componentSubmanifold G hG i).exists_stalkIdeal_idealSheaf_eq_span_prime hx
    rw [hspan, Ne, Ideal.span_singleton_eq_bot]
    exact hp.ne_zero
  · rw [(componentSubmanifold G hG i).stalkIdeal_idealSheaf_of_notMem hx]
    exact top_ne_bot

/-- A finite product of powers of component ideals is nonzero at every point, each factor being so
and the stalks being domains. -/
theorem isNonzeroEverywhere_finset_prod_componentIdeal_pow (s : Finset (ComponentIndex G))
    (a : ComponentIndex G → ℕ) : (∏ i ∈ s, componentIdeal G hG i ^ a i).IsNonzeroEverywhere := by
  classical
  refine Finset.prod_induction (fun i => componentIdeal G hG i ^ a i) IdealSheaf.IsNonzeroEverywhere
    (fun I J hI hJ => isNonzeroEverywhere_mul (ψ := ψ) I J hI hJ) ?_
    (fun i _ =>
      isNonzeroEverywhere_pow (ψ := ψ) _ (componentIdeal_isNonzeroEverywhere G hG i) (a i))
  intro x hx
  have _hdom : IsDomain ((structureSheaf 𝕜 E X).presheaf.stalk x) :=
    isDomain_stalk ψ (IsManifold.chart_mem_maximalAtlas x) (mem_chart_source E x)
  rw [IdealSheaf.stalkIdeal_one] at hx
  exact absurd hx top_ne_bot

omit [IsManifold 𝓘(𝕜, E) ω X] in
/-- The stalk of the monomial part at `x` depends only on the stalk of the ideal sheaf at `x`: every
exponent of an active component is the order along that component at `x`
(`componentExponent_eq_toNat_ordAlongIdeal`), which sees only the stalk at `x`. -/
theorem monomialPart_stalkIdeal_congr (K K' : IdealSheaf (structureSheaf 𝕜 E X)) (x : X)
    (hKK' : K.stalkIdeal x = K'.stalkIdeal x) :
    (monomialPart G hG K).stalkIdeal x = (monomialPart G hG K').stalkIdeal x := by
  rw [stalkIdeal_monomialPart, stalkIdeal_monomialPart]
  refine Finset.prod_congr rfl fun i hi => ?_
  have hxi : x ∈ componentSet G i := IdealSheaf.mem_activeFinset.mp hi
  change (componentIdeal G hG i ^ componentExponent G hG K i).stalkIdeal x =
    (componentIdeal G hG i ^ componentExponent G hG K' i).stalkIdeal x
  rw [componentExponent_eq_toNat_ordAlongIdeal G hG K i hxi,
    componentExponent_eq_toNat_ordAlongIdeal G hG K' i hxi,
    IdealSheaf.ordAlongIdeal_congr_stalk (componentIdeal G hG i) K K' x hKK']

/-- The stalk of the nonmonomial part at `x` depends only on the stalk of the ideal sheaf at `x`: it
is the colon of that stalk by the stalk of the monomial part, which depends only on it as well. -/
theorem nonmonomialPart_stalkIdeal_congr (K K' : IdealSheaf (structureSheaf 𝕜 E X)) (x : X)
    (hKK' : K.stalkIdeal x = K'.stalkIdeal x) :
    (nonmonomialPart G hG K).stalkIdeal x = (nonmonomialPart G hG K').stalkIdeal x := by
  rw [stalkIdeal_nonmonomialPart, stalkIdeal_nonmonomialPart, hKK',
    monomialPart_stalkIdeal_congr G hG K K' x hKK']

/-- The nonmonomial part ignores a locally finite product of powers of component ideals:
`N((∏'ᵢ 𝓘ᵢ ^ aᵢ) · J) = N(J)` for `J` nonzero at every point. Stalkwise the locally finite product
is the finite product over the active components, for which
`nonmonomialPart_finprod_componentIdeal_pow_mul` applies ([Kol07, 111, Step 1]: an ideal of boundary
divisors changes only the monomial part). -/
theorem nonmonomialPart_locallyFiniteProduct_pow_mul (a : ComponentIndex G → ℕ)
    (J : IdealSheaf (structureSheaf 𝕜 E X)) (hJ : J.IsNonzeroEverywhere) :
    nonmonomialPart G hG
        (IdealSheaf.locallyFiniteProduct (structureSheaf 𝕜 E X)
          (fun i => componentIdeal G hG i ^ a i) (componentSet G) (componentSet_locallyFinite G hG)
          (componentIdeal_pow_stalkIdeal_top_of_notMem G hG a) * J) =
      nonmonomialPart G hG J := by
  refine IdealSheaf.ext fun x => ?_
  have hst : (IdealSheaf.locallyFiniteProduct (structureSheaf 𝕜 E X)
        (fun i => componentIdeal G hG i ^ a i) (componentSet G) (componentSet_locallyFinite G hG)
        (componentIdeal_pow_stalkIdeal_top_of_notMem G hG a) * J).stalkIdeal x =
      ((∏ i ∈ IdealSheaf.activeFinset (componentSet G) (componentSet_locallyFinite G hG) x,
        componentIdeal G hG i ^ a i) * J).stalkIdeal x := by
    rw [IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_mul,
      IdealSheaf.stalkIdeal_locallyFiniteProduct, IdealSheaf.stalkIdeal_finset_prod]
  rw [nonmonomialPart_stalkIdeal_congr G hG _ _ x hst,
    nonmonomialPart_finprod_componentIdeal_pow_mul G hG J a _
      (isNonzeroEverywhere_mul (ψ := ψ) _ _
        (isNonzeroEverywhere_finset_prod_componentIdeal_pow G hG _ a) hJ)]

include ψ in
/-- The unit ideal sheaf is nonzero at every point (the stalks are domains). -/
theorem isNonzeroEverywhere_top : (⊤ : IdealSheaf (structureSheaf 𝕜 E X)).IsNonzeroEverywhere := by
  intro x hx
  have _hdom : IsDomain ((structureSheaf 𝕜 E X).presheaf.stalk x) :=
    isDomain_stalk ψ (IsManifold.chart_mem_maximalAtlas x) (mem_chart_source E x)
  rw [IdealSheaf.stalkIdeal_top] at hx
  exact absurd hx top_ne_bot

/-- An ideal sheaf whose stalks are monomials in the component ideals has trivial nonmonomial part:
if at every `x` the stalk of `K` is a product of powers of the stalks of the active component ideals
(with exponents that may depend on `x`), then `N(K) = ⊤`. -/
theorem nonmonomialPart_eq_top_of_forall_stalkIdeal_eq_prod
    (K : IdealSheaf (structureSheaf 𝕜 E X))
    (hK : ∀ x, ∃ b : ComponentIndex G → ℕ, K.stalkIdeal x =
      ∏ i ∈ IdealSheaf.activeFinset (componentSet G) (componentSet_locallyFinite G hG) x,
        (componentIdeal G hG i).stalkIdeal x ^ b i) :
    nonmonomialPart G hG K = ⊤ := by
  refine IdealSheaf.ext fun x => ?_
  obtain ⟨b, hb⟩ := hK x
  have hst : K.stalkIdeal x =
      ((∏ i ∈ IdealSheaf.activeFinset (componentSet G) (componentSet_locallyFinite G hG) x,
        componentIdeal G hG i ^ b i) * ⊤).stalkIdeal x := by
    rw [hb, IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_top, Ideal.mul_top,
      IdealSheaf.stalkIdeal_finset_prod]
    exact Finset.prod_congr rfl fun i _ => (IdealSheaf.stalkIdeal_pow _ _ _).symm
  rw [IdealSheaf.stalkIdeal_top, nonmonomialPart_stalkIdeal_congr G hG K _ x hst,
    nonmonomialPart_finprod_componentIdeal_pow_mul G hG ⊤ b _
      (isNonzeroEverywhere_mul (ψ := ψ) _ _
        (isNonzeroEverywhere_finset_prod_componentIdeal_pow G hG _ b)
        (isNonzeroEverywhere_top (ψ := ψ))),
    stalkIdeal_nonmonomialPart, IdealSheaf.stalkIdeal_top]
  exact eq_top_iff.mpr fun r _ => Submodule.mem_colon.mpr fun p _ => Submodule.mem_top

/-- If `N(K) = ⊤` then `K = M(K)`, by the decomposition `K = M(K) · N(K)`. -/
theorem monomialPart_eq_self_of_nonmonomialPart_eq_top (K : IdealSheaf (structureSheaf 𝕜 E X))
    (hN : nonmonomialPart G hG K = ⊤) : monomialPart G hG K = K := by
  refine IdealSheaf.ext fun x => ?_
  have h := congrArg (fun J : IdealSheaf (structureSheaf 𝕜 E X) => J.stalkIdeal x)
    (monomialPart_mul_nonmonomialPart G hG K)
  simp only [IdealSheaf.stalkIdeal_mul, hN, IdealSheaf.stalkIdeal_top, Ideal.mul_top] at h
  exact h

end Engine

/-! ### The blow-up: the exceptional divisor's ideal and its component -/

section BlowUp

variable {M : Type u} [TopologicalSpace M] [ChartedSpace E M] [IsManifold 𝓘(𝕜, E) ω M] {Y : Set M}
  {c : ℕ} {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M']
  [T2Space M'] [SecondCountableTopology M'] {π : M' → M} (hY : IsClosedSubmanifold ψ Y c)
  (h : IsBlowUp ψ Y c π) (F : HypersurfaceFamily M) (hF : F.IsSnc ψ) (hsnc : F.HasSncWith ψ Y c)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The exceptional ideal sheaf of a blow-up is the ideal sheaf of the exceptional divisor `π⁻¹(Y)`
as a closed submanifold. -/
theorem exceptionalIdealSheaf_eq_idealSheaf_preimage :
    hY.idealSheaf.pullback π h.contMDiff = (h.isClosedSubmanifold_preimage hY).idealSheaf :=
  IsIdealSheafOf.eq_idealSheaf (h.isClosedSubmanifold_preimage hY)
    (isIdealSheafOf_exceptionalIdealSheaf hY h)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- At a point of a connected component `α` of the exceptional divisor, the ideal of that component
of the transformed boundary family has the stalk of the exceptional ideal sheaf: the component is
cut out of the exceptional divisor by an open set, and the ideal sheaf of a closed submanifold is
germ-local. -/
theorem stalkIdeal_componentIdeal_totalTransform_inr
    (α : ConnectedComponents ((F.totalTransform π Y).hyp (toLex (Sum.inr PUnit.unit)))) {x : M'}
    (hx : x ∈ componentSet (F.totalTransform π Y) ⟨toLex (Sum.inr PUnit.unit), α⟩) :
    (componentIdeal (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        ⟨toLex (Sum.inr PUnit.unit), α⟩).stalkIdeal x =
      (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal x := by
  have hF' := HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc
  obtain ⟨W, hWo, hW⟩ := exists_isOpen_componentSet_eq (M := (⟨M'⟩ : AnalyticManifold.{u} 𝕜 E))
    (F.totalTransform π Y) hF' ⟨toLex (Sum.inr PUnit.unit), α⟩
  rw [exceptionalIdealSheaf_eq_idealSheaf_preimage hY h, componentIdeal]
  exact ((h.isClosedSubmanifold_preimage hY).stalkIdeal_idealSheaf_eq_of_inter_eq_left
    (componentSubmanifold _ hF' _) hWo hW.symm hx).symm

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The nonmonomial part with respect to the transformed boundary family ignores powers of the
exceptional ideal: `N_{F'}(𝓘_F^m · J) = N_{F'}(J)` for `J` nonzero at every point. At a point of the
exceptional divisor the exceptional ideal has the stalk of the component ideal of the exceptional
component through the point (`stalkIdeal_componentIdeal_totalTransform_inr`), and off it the stalk
is the unit ideal ([Kol07, 111, Step 1]). -/
theorem nonmonomialPart_exceptionalIdealSheaf_pow_mul (m : ℕ)
    (J : IdealSheaf (structureSheaf 𝕜 E M')) (hJ : J.IsNonzeroEverywhere) :
    nonmonomialPart (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        (hY.idealSheaf.pullback π h.contMDiff ^ m * J) =
      nonmonomialPart (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        J := by
  have hF' := HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc
  refine IdealSheaf.ext fun x => ?_
  by_cases hxY : π x ∈ Y
  · have hmem : x ∈ (F.totalTransform π Y).hyp (toLex (Sum.inr PUnit.unit)) := hxY
    have hcs : x ∈ componentSet (F.totalTransform π Y)
        ⟨toLex (Sum.inr PUnit.unit), ConnectedComponents.mk ⟨x, hmem⟩⟩ := ⟨⟨x, hmem⟩, rfl, rfl⟩
    have hS2 := stalkIdeal_componentIdeal_totalTransform_inr hY h F hF hsnc _ hcs
    have hst : (hY.idealSheaf.pullback π h.contMDiff ^ m * J).stalkIdeal x =
        ((∏ i ∈ ({⟨toLex (Sum.inr PUnit.unit), ConnectedComponents.mk ⟨x, hmem⟩⟩} :
            Finset (ComponentIndex (F.totalTransform π Y))),
          componentIdeal (F.totalTransform π Y) hF' i ^ m) * J).stalkIdeal x := by
      rw [IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_pow,
        Finset.prod_singleton, IdealSheaf.stalkIdeal_pow, hS2]
    rw [nonmonomialPart_stalkIdeal_congr _ hF' _ _ x hst,
      nonmonomialPart_finprod_componentIdeal_pow_mul _ hF' J (fun _ => m) _
        (isNonzeroEverywhere_mul (ψ := ψ) _ _
          (isNonzeroEverywhere_finset_prod_componentIdeal_pow _ hF' _ _) hJ)]
  · have hst : (hY.idealSheaf.pullback π h.contMDiff ^ m * J).stalkIdeal x = J.stalkIdeal x := by
      rw [IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_pow,
        stalkIdeal_exceptionalIdealSheaf_of_notMem hY h hxY, Ideal.top_pow, Ideal.top_mul]
    exact nonmonomialPart_stalkIdeal_congr _ hF' _ _ x hst

end BlowUp

section BlowUpChart

variable {M : Type u} [TopologicalSpace M] [ChartedSpace E M] [IsManifold 𝓘(𝕜, E) ω M] {Y : Set M}
  {c : ℕ} {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M']
  [T2Space M'] [SecondCountableTopology M'] {π : M' → M} (hY : IsClosedSubmanifold ψ Y c)
  (h : IsBlowUp ψ Y c π) (F : HypersurfaceFamily M) (hF : F.IsSnc ψ) (hsnc : F.HasSncWith ψ Y c)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- Off the centre, at `x` with `π x ∉ Y`, the total transform of the ideal of a component `D` of
`F` through `π x` has the stalk of the ideal of the component of the strict transform of `D` through
`x`: the blow-up is a local analytic isomorphism at `x`, the strict transform is the preimage of `D`
there, and a chart adapted to `D` at `π x` transports along the local inverse to a chart adapted to
the strict transform at `x`, so the two stalks are generated by a coordinate germ and by its
pull-back. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_notMem {x : M'} (hxY : π x ∉ Y)
    (i : ComponentIndex F) (hxi : π x ∈ componentSet F i)
    (hxj : x ∈ strictTransformSet π Y (F.hyp i.1)) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      (componentIdeal (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩).stalkIdeal x := by
  have hF' := HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc
  have hπc : Continuous π := h.contMDiff.continuous
  have hmem : π x ∈ F.hyp i.1 := Subtype.coe_image_subset _ _ hxi
  have hcs : x ∈ componentSet (F.totalTransform π Y)
      ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩ := ⟨⟨x, hxj⟩, rfl, rfl⟩
  obtain ⟨φ, σ₁, e, hpφ, hφ, hpe, he, h5⟩ :=
    exists_adaptedChart_strictTransform_off hY h (hF.isClosedSubmanifold i.1) hmem hxY
  have hgerm : germMap π h.contMDiff x (coord E ψ φ hφ.1 hpφ (σ₁ 0)) =
      coord E ψ e he.1 hpe (σ₁ 0) := by
    apply stalkToGerm_injective 𝓘(𝕜, E) ω M' x
    rw [stalkToGerm_germMap, stalkToGerm_coord, stalkToGerm_coord, Filter.Germ.coe_compTendsto,
      Filter.Germ.coe_eq]
    filter_upwards [e.open_source.mem_nhds hpe, (φ.open_source.preimage hπc).mem_nhds hpφ]
      with y hy hy'
    rw [Function.comp_apply, extendSection_of_mem 𝕜 E _ hy', extendSection_of_mem 𝕜 E _ hy]
    exact (h5 y hy).symm
  rw [IdealSheaf.stalkIdeal_pullback, componentIdeal_stalkIdeal_eq (F := F) hF i hxi,
    componentIdeal_stalkIdeal_eq (F := F.totalTransform π Y) hF' _ hcs,
    (hF.isClosedSubmanifold i.1).stalkIdeal_idealSheaf_eq_span hmem hφ hpφ,
    (hF'.isClosedSubmanifold (toLex (Sum.inl i.1))).stalkIdeal_idealSheaf_eq_span hxj he hpe,
    Set.range_unique, Set.range_unique, Fin.default_eq_zero, Ideal.map_span, Set.image_singleton,
    hgerm]

variable {φ : OpenPartialHomeomorph M E} {σ : Fin c ↪ Fin n} (hφ : IsAdaptedChart ψ Y φ σ) {a : M}
  {cidx : {j // a ∈ F.hyp j} → Fin n} (hc : F.IsSncChartAt ψ φ a cidx) {i₀ : Fin c}
  {Φ : OpenPartialHomeomorph M' E} (hΦ : IsBlowUpChart ψ π φ σ i₀ Φ) {x : M'} (hx : x ∈ Φ.source)
  (hxa : π x = a)

omit [IsManifold 𝓘(𝕜, E) ω M] in
include hφ hc hΦ hx hxa in
/-- Over the centre, in a chart `φ` adapted to `Y` and to `F` at `a ∈ Y` and a blow-up chart `Φ` at
`x` over `a`, the total transform of the ideal of a component `D` of `F` through `a` is the
principal ideal generated by the pull-back along `π` of the coordinate of `D`. -/
theorem stalkIdeal_totalTransform_componentIdeal_eq_span_germMap (i : ComponentIndex F)
    (hai : a ∈ componentSet F i) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      Ideal.span {germMap π h.contMDiff x (coord E ψ φ hφ.1 (hΦ.source_subset hx)
        (cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩))} := by
  subst hxa
  have hmem : π x ∈ F.hyp i.1 := Subtype.coe_image_subset _ _ hai
  rw [IdealSheaf.stalkIdeal_pullback, componentIdeal_stalkIdeal_eq (F := F) hF i hai,
    (hF.isClosedSubmanifold i.1).stalkIdeal_idealSheaf_eq_span hmem
      (isAdaptedChart_singleIdx hc.1 fun y hy => hc.mem_iff ⟨i.1, hmem⟩ hy) hc.2.1,
    range_singleIdx_coord hc.1 hc.2.1, Ideal.map_span, Set.image_singleton]

omit [IsManifold 𝓘(𝕜, E) ω M] in
include hφ hc hΦ hx hxa in
/-- The case in which the coordinate of the component `D` is the scaling coordinate `σ i₀` of the
blow-up chart: the pulled-back coordinate is the coordinate of the exceptional divisor, so the total
transform of the ideal of `D` has the stalk of the exceptional ideal at `x`. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_eq_scaling (i : ComponentIndex F)
    (hai : a ∈ componentSet F i) (hidx : cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩ = σ i₀) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal x := by
  rw [stalkIdeal_totalTransform_componentIdeal_eq_span_germMap h F hF hφ hc hΦ hx hxa i hai,
    hidx, hΦ.germMap_coord_self h.contMDiff hφ.1 hx,
    stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hx]

omit [IsManifold 𝓘(𝕜, E) ω M] in
include hφ hc hΦ hx hxa in
/-- The case in which the coordinate of the component `D` is a coordinate `σ k`, `k ≠ i₀`, of the
centre: the pulled-back coordinate is the coordinate of the exceptional divisor times the ratio
coordinate `u_{σ k}`, so the total transform of the ideal of `D` is the exceptional ideal times the
ideal generated by the ratio coordinate at `x`. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_eq_ratio (i : ComponentIndex F)
    (hai : a ∈ componentSet F i) {k : Fin c} (hk : k ≠ i₀)
    (hidx : cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩ = σ k) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal x *
        Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hx (σ k)} := by
  rw [stalkIdeal_totalTransform_componentIdeal_eq_span_germMap h F hF hφ hc hΦ hx hxa i hai,
    hidx, hΦ.germMap_coord_of_ne h.contMDiff hφ.1 hx hk,
    stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hx,
    Ideal.span_singleton_mul_span_singleton]

include hφ hc hΦ hx hxa in
omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- In the same chart, the ideal of the component `⟨inl j, C'⟩` of the strict transform of `E^j`
through `x` is generated by the coordinate `u_{cidx j}` of the blow-up chart: the blow-up chart is a
chart of simple normal crossings for the transformed family at `x`, with the strict transform of
`E^j` cut out by the coordinate of `E^j`. -/
theorem stalkIdeal_componentIdeal_totalTransform_inl {j : F.ι} (haj : a ∈ F.hyp j)
    (C' : ConnectedComponents ((F.totalTransform π Y).hyp (toLex (Sum.inl j))))
    (hxC : x ∈ componentSet (F.totalTransform π Y) ⟨toLex (Sum.inl j), C'⟩) :
    (componentIdeal (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        ⟨toLex (Sum.inl j), C'⟩).stalkIdeal x =
      Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hx (cidx ⟨j, haj⟩)} := by
  have hF' := HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc
  have hsnc' := HypersurfaceFamily.totalTransform_isSncChartAt h hF hφ hc hΦ hx hxa
  have hxmem : x ∈ (F.totalTransform π Y).hyp (toLex (Sum.inl j)) :=
    Subtype.coe_image_subset _ _ hxC
  rw [componentIdeal_stalkIdeal_eq (F := F.totalTransform π Y) hF' _ hxC,
    (hF'.isClosedSubmanifold (toLex (Sum.inl j))).stalkIdeal_idealSheaf_eq_span hxmem
      (isAdaptedChart_singleIdx hsnc'.1 fun y hy => hsnc'.mem_iff ⟨toLex (Sum.inl j), hxmem⟩ hy)
      hsnc'.2.1,
    range_singleIdx_coord hsnc'.1 hsnc'.2.1,
    HypersurfaceFamily.totalTransformIdx_inl h hF hxa cidx σ i₀ hxmem]

include hφ hc hΦ hx hxa in
omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The ratio case when `x` lies on the strict transform of the member of `D`: the ratio coordinate
generates the ideal of the component of the strict transform through `x`, so the total transform of
the ideal of `D` is the exceptional ideal times that component ideal at `x`. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_eq_ratio_of_mem (i : ComponentIndex F)
    (hai : a ∈ componentSet F i) {k : Fin c} (hk : k ≠ i₀)
    (hidx : cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩ = σ k)
    (hxj : x ∈ strictTransformSet π Y (F.hyp i.1)) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal x *
        (componentIdeal (F.totalTransform π Y)
          (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
          ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩).stalkIdeal x := by
  have hcs : x ∈ componentSet (F.totalTransform π Y)
      ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩ := ⟨⟨x, hxj⟩, rfl, rfl⟩
  rw [stalkIdeal_totalTransform_componentIdeal_of_eq_ratio hY h F hF hφ hc hΦ hx hxa i hai hk hidx,
    stalkIdeal_componentIdeal_totalTransform_inl hY h F hF hsnc hφ hc hΦ hx hxa
      (Subtype.coe_image_subset _ _ hai) _ hcs, hidx]

omit [IsManifold 𝓘(𝕜, E) ω M] in
include hφ hc hΦ hx hxa in
/-- The ratio case when `x` does not lie on the strict transform of the member of `D`: the ratio
coordinate is a unit at `x` (on the chart the strict transform is its zero set), so the total
transform of the ideal of `D` has the stalk of the exceptional ideal alone. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_eq_ratio_of_notMem (i : ComponentIndex F)
    (hai : a ∈ componentSet F i) {k : Fin c} (hk : k ≠ i₀)
    (hidx : cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩ = σ k)
    (hxj : x ∉ strictTransformSet π Y (F.hyp i.1)) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal x := by
  have hmem : a ∈ F.hyp i.1 := Subtype.coe_image_subset _ _ hai
  have hH : ∀ y ∈ φ.source, y ∈ F.hyp i.1 ↔ ψ (φ y) (σ k) = 0 := fun y hy => by
    rw [← hidx]; exact hc.mem_iff ⟨i.1, hmem⟩ hy
  have hcut := strictTransform_inter_source_of_ne hφ hΦ hH hk.symm
  have hunit : Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hx (σ k)} = ⊤ := by
    rw [Ideal.span_singleton_eq_top, contMDiffSheafCommRing.isUnit_stalk_iff]
    change eval 𝕜 E M' x (coord E ψ Φ hΦ.mem_maximalAtlas hx (σ k)) ≠ 0
    rw [eval_coord]
    exact fun h0 => hxj ((Set.ext_iff.mp hcut x).mpr ⟨hx, h0⟩).1
  rw [stalkIdeal_totalTransform_componentIdeal_of_eq_ratio hY h F hF hφ hc hΦ hx hxa i hai hk hidx,
    hunit, Ideal.mul_top]

omit [IsManifold 𝓘(𝕜, E) ω M] in
include hφ hc hΦ hx hxa in
/-- The case in which the coordinate of the component `D` is off the block of the centre (`D` is
transversal to `Y`): the pulled-back coordinate is the same coordinate of the blow-up chart, with no
exceptional factor. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_notMem_range (i : ComponentIndex F)
    (hai : a ∈ componentSet F i)
    (hidx : ∀ k, σ k ≠ cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hx
        (cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩)} := by
  rw [stalkIdeal_totalTransform_componentIdeal_eq_span_germMap h F hF hφ hc hΦ hx hxa i hai,
    hΦ.germMap_coord_off h.contMDiff hφ.1 hx hidx]

include hφ hc hΦ hx hxa in
omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The transversal case when `x` lies on the strict transform of the member of `D`: the total
transform of the ideal of `D` has the stalk of the ideal of the component of the strict transform
through `x`. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_notMem_range_of_mem (i : ComponentIndex F)
    (hai : a ∈ componentSet F i)
    (hidx : ∀ k, σ k ≠ cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩)
    (hxj : x ∈ strictTransformSet π Y (F.hyp i.1)) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x =
      (componentIdeal (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩).stalkIdeal x := by
  have hcs : x ∈ componentSet (F.totalTransform π Y)
      ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩ := ⟨⟨x, hxj⟩, rfl, rfl⟩
  rw [stalkIdeal_totalTransform_componentIdeal_of_notMem_range h F hF hφ hc hΦ hx hxa i hai hidx,
    stalkIdeal_componentIdeal_totalTransform_inl hY h F hF hsnc hφ hc hΦ hx hxa
      (Subtype.coe_image_subset _ _ hai) _ hcs]

omit [IsManifold 𝓘(𝕜, E) ω M] in
include hφ hc hΦ hx hxa in
/-- The transversal case when `x` does not lie on the strict transform of the member of `D`: the
coordinate is a unit at `x`, so the total transform of the ideal of `D` has unit stalk. -/
theorem stalkIdeal_totalTransform_componentIdeal_of_notMem_range_of_notMem (i : ComponentIndex F)
    (hai : a ∈ componentSet F i)
    (hidx : ∀ k, σ k ≠ cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩)
    (hxj : x ∉ strictTransformSet π Y (F.hyp i.1)) :
    ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x = ⊤ := by
  have hmem : a ∈ F.hyp i.1 := Subtype.coe_image_subset _ _ hai
  have hH : ∀ y ∈ φ.source,
      y ∈ F.hyp i.1 ↔ ψ (φ y) (cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩) = 0 :=
    fun y hy => hc.mem_iff ⟨i.1, hmem⟩ hy
  have hcut := strictTransform_inter_source_off hφ hΦ hidx hH
  rw [stalkIdeal_totalTransform_componentIdeal_of_notMem_range h F hF hφ hc hΦ hx hxa i hai hidx,
    Ideal.span_singleton_eq_top, contMDiffSheafCommRing.isUnit_stalk_iff]
  change eval 𝕜 E M' x (coord E ψ Φ hΦ.mem_maximalAtlas hx
    (cidx ⟨i.1, Subtype.coe_image_subset _ _ hai⟩)) ≠ 0
  rw [eval_coord]
  exact fun h0 => hxj ((Set.ext_iff.mp hcut x).mpr ⟨hx, h0⟩).1

include hφ hΦ hx in
omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- In a blow-up chart of index `i₀`, the ideal of the exceptional component through `x` is
generated by the scaling coordinate `u_{σ i₀}`. -/
theorem stalkIdeal_componentIdeal_totalTransform_inr_eq_span_coord
    (α : ConnectedComponents ((F.totalTransform π Y).hyp (toLex (Sum.inr PUnit.unit))))
    (hxα : x ∈ componentSet (F.totalTransform π Y) ⟨toLex (Sum.inr PUnit.unit), α⟩) :
    (componentIdeal (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        ⟨toLex (Sum.inr PUnit.unit), α⟩).stalkIdeal x =
      Ideal.span {coord E ψ Φ hΦ.mem_maximalAtlas hx (σ i₀)} := by
  rw [stalkIdeal_componentIdeal_totalTransform_inr hY h F hF hsnc α hxα,
    stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ hx]

end BlowUpChart

/-! ### The finset-monomial bookkeeping -/

section FinsetMonomial

variable {ι R : Type*} [CommMonoid R]

/-- `m` is a **monomial in the `f k`, `k ∈ A`**: `m = ∏ k ∈ A, f k ^ g k` for some exponents `g`.
The bookkeeping for the stalkwise computation of the total transform of a monomial part: at each
point the stalk is a monomial in the stalks of the component ideals through it. -/
def IsFinsetMonomial (A : Finset ι) (f : ι → R) (m : R) : Prop :=
  ∃ g : ι → ℕ, m = ∏ k ∈ A, f k ^ g k

/-- `1` is the monomial with all exponents `0`. -/
theorem IsFinsetMonomial.one (A : Finset ι) (f : ι → R) : IsFinsetMonomial A f 1 :=
  ⟨fun _ => 0, by simp only [pow_zero, Finset.prod_const_one]⟩

/-- A generator `f k₀`, `k₀ ∈ A`, is a monomial (exponent `1` at `k₀`, `0` elsewhere). -/
theorem IsFinsetMonomial.of_mem {A : Finset ι} (f : ι → R) {k₀ : ι} (hk : k₀ ∈ A) :
    IsFinsetMonomial A f (f k₀) := by
  classical
  refine ⟨fun k => if k = k₀ then 1 else 0, ?_⟩
  rw [Finset.prod_eq_single k₀ (fun b _ hb => by simp [hb]) fun h => absurd hk h]
  simp

/-- Monomials are closed under products (the exponents add). -/
theorem IsFinsetMonomial.mul {A : Finset ι} {f : ι → R} {m₁ m₂ : R} (h₁ : IsFinsetMonomial A f m₁)
    (h₂ : IsFinsetMonomial A f m₂) : IsFinsetMonomial A f (m₁ * m₂) := by
  obtain ⟨g₁, rfl⟩ := h₁
  obtain ⟨g₂, rfl⟩ := h₂
  refine ⟨fun k => g₁ k + g₂ k, ?_⟩
  rw [← Finset.prod_mul_distrib]
  exact Finset.prod_congr rfl fun k _ => (pow_add _ _ _).symm

/-- Monomials are closed under powers (the exponents are multiplied). -/
theorem IsFinsetMonomial.pow {A : Finset ι} {f : ι → R} {m : R} (h : IsFinsetMonomial A f m)
    (e : ℕ) : IsFinsetMonomial A f (m ^ e) := by
  obtain ⟨g, rfl⟩ := h
  refine ⟨fun k => g k * e, ?_⟩
  rw [← Finset.prod_pow]
  exact Finset.prod_congr rfl fun k _ => (pow_mul _ _ _).symm

/-- A finite product of monomials is a monomial (the exponents are summed). -/
theorem IsFinsetMonomial.prod {A : Finset ι} {f : ι → R} {κ : Type*} (T : Finset κ) (P : κ → R)
    (hP : ∀ i ∈ T, IsFinsetMonomial A f (P i)) : IsFinsetMonomial A f (∏ i ∈ T, P i) := by
  classical
  choose! g hg using hP
  refine ⟨fun k => ∑ i ∈ T, g i k, ?_⟩
  rw [Finset.prod_congr rfl hg, Finset.prod_comm]
  exact Finset.prod_congr rfl fun k _ => Finset.prod_pow_eq_pow_sum T (fun i => g i k) (f k)

/-- For ideals, the unit ideal `⊤ = 1` is a monomial (the case of a unit factor). -/
theorem IsFinsetMonomial.top {S : Type*} [CommSemiring S] (A : Finset ι) (f : ι → Ideal S) :
    IsFinsetMonomial A f ⊤ := by
  rw [← Ideal.one_eq_top]
  exact IsFinsetMonomial.one A f

end FinsetMonomial

/-! ### The assembly: the total transform of the monomial part is a monomial -/

section Assembly

variable {M : Type u} [TopologicalSpace M] [ChartedSpace E M] [IsManifold 𝓘(𝕜, E) ω M] {Y : Set M}
  {c : ℕ} {M' : Type u} [TopologicalSpace M'] [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M']
  [T2Space M'] [SecondCountableTopology M'] {π : M' → M} (hY : IsClosedSubmanifold ψ Y c)
  (h : IsBlowUp ψ Y c π) (F : HypersurfaceFamily M) (hF : F.IsSnc ψ) (hsnc : F.HasSncWith ψ Y c)
  (I : IdealSheaf (structureSheaf 𝕜 E M))

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- At every point `x` of the blow-up, the stalk of the total transform of the monomial part `M(𝓘)`
is a product of powers of the stalks of the component ideals of the transformed family through `x`,
with exponents depending on `x`. The stalk of `π^* M(𝓘)` is the product over the components of `F`
through `π x` of the powers of the total transforms of their ideals
(`stalkIdeal_totalTransform_locallyFiniteProduct`), and each of those is a monomial in the stalks of
the component ideals of `F'` at `x` by the chart computation (off the centre
`stalkIdeal_totalTransform_componentIdeal_of_notMem`; over the centre the case distinction on the
coordinate of the component). -/
theorem stalkIdeal_totalTransform_monomialPart_eq_prod (x : M') :
    ∃ b : ComponentIndex (F.totalTransform π Y) → ℕ,
      ((monomialPart F hF I).pullback π h.contMDiff).stalkIdeal x =
        ∏ i ∈ IdealSheaf.activeFinset (componentSet (F.totalTransform π Y))
          (componentSet_locallyFinite (F.totalTransform π Y)
            (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)) x,
          (componentIdeal (F.totalTransform π Y)
            (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc) i).stalkIdeal x
            ^ b i := by
  classical
  have hF' := HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc
  -- the total transform of `M(I)` at `x`: a product over the `F`-components through `π x`
  have hL : ((monomialPart F hF I).pullback π h.contMDiff).stalkIdeal x =
      ∏ i ∈ IdealSheaf.activeFinset (componentSet F) (componentSet_locallyFinite F hF) (π x),
        ((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x ^
          componentExponent F hF I i := by
    rw [monomialPart, stalkIdeal_totalTransform_locallyFiniteProduct h]
    refine Finset.prod_congr rfl fun i _ => ?_
    rw [componentFactor, IdealSheaf.stalkIdeal_pullback, IdealSheaf.stalkIdeal_pullback,
      IdealSheaf.stalkIdeal_pow, Ideal.map_pow]
  -- each factor is a monomial in the active `F'`-component-ideal stalks at `x`
  suffices hfac : ∀ i ∈ IdealSheaf.activeFinset (componentSet F) (componentSet_locallyFinite F hF)
      (π x), IsFinsetMonomial
        (IdealSheaf.activeFinset (componentSet (F.totalTransform π Y))
          (componentSet_locallyFinite (F.totalTransform π Y) hF') x)
        (fun k => (componentIdeal (F.totalTransform π Y) hF' k).stalkIdeal x)
        (((componentIdeal F hF i).pullback π h.contMDiff).stalkIdeal x) by
    obtain ⟨b, hb⟩ :=
      IsFinsetMonomial.prod _ _ fun i hi => (hfac i hi).pow (componentExponent F hF I i)
    exact ⟨b, hL.trans hb⟩
  intro i hi
  have hxi : π x ∈ componentSet F i := IdealSheaf.mem_activeFinset.mp hi
  have hmem : π x ∈ F.hyp i.1 := Subtype.coe_image_subset _ _ hxi
  by_cases hxY : π x ∈ Y
  · -- over the centre: the adapted snc chart at `π x` and a blow-up chart at `x`
    obtain ⟨φ, σ, cidx, hφ, hc⟩ := hsnc (π x) hxY
    obtain ⟨i₀, Φ, hΦ, hx⟩ := h.cover φ σ hφ x hc.2.1
    have hexc : x ∈ componentSet (F.totalTransform π Y)
        ⟨toLex (Sum.inr PUnit.unit), ConnectedComponents.mk ⟨x, hxY⟩⟩ := ⟨⟨x, hxY⟩, rfl, rfl⟩
    have hexcA : (⟨toLex (Sum.inr PUnit.unit), ConnectedComponents.mk ⟨x, hxY⟩⟩ :
        ComponentIndex (F.totalTransform π Y)) ∈ IdealSheaf.activeFinset
          (componentSet (F.totalTransform π Y))
          (componentSet_locallyFinite (F.totalTransform π Y) hF') x :=
      IdealSheaf.mem_activeFinset.mpr hexc
    have hexcf : (hY.idealSheaf.pullback π h.contMDiff).stalkIdeal x =
        (componentIdeal (F.totalTransform π Y) hF'
          ⟨toLex (Sum.inr PUnit.unit), ConnectedComponents.mk ⟨x, hxY⟩⟩).stalkIdeal x :=
      (stalkIdeal_componentIdeal_totalTransform_inr hY h F hF hsnc _ hexc).symm
    by_cases hin : ∃ k, σ k = cidx ⟨i.1, Subtype.coe_image_subset _ _ hxi⟩
    · obtain ⟨k, hk⟩ := hin
      by_cases hki : k = i₀
      · subst hki
        rw [stalkIdeal_totalTransform_componentIdeal_of_eq_scaling hY h F hF hφ hc hΦ hx rfl i hxi
          hk.symm, hexcf]
        exact IsFinsetMonomial.of_mem _ hexcA
      · by_cases hxj : x ∈ strictTransformSet π Y (F.hyp i.1)
        · have hcs : x ∈ componentSet (F.totalTransform π Y)
              ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩ := ⟨⟨x, hxj⟩, rfl, rfl⟩
          rw [stalkIdeal_totalTransform_componentIdeal_of_eq_ratio_of_mem hY h F hF hsnc hφ hc hΦ hx
            rfl i hxi hki hk.symm hxj, hexcf]
          exact (IsFinsetMonomial.of_mem _ hexcA).mul
            (IsFinsetMonomial.of_mem _ (IdealSheaf.mem_activeFinset.mpr hcs))
        · rw [stalkIdeal_totalTransform_componentIdeal_of_eq_ratio_of_notMem hY h F hF hφ hc hΦ hx
            rfl i hxi hki hk.symm hxj, hexcf]
          exact IsFinsetMonomial.of_mem _ hexcA
    · have hj : ∀ k, σ k ≠ cidx ⟨i.1, Subtype.coe_image_subset _ _ hxi⟩ := fun k hk => hin ⟨k, hk⟩
      by_cases hxj : x ∈ strictTransformSet π Y (F.hyp i.1)
      · have hcs : x ∈ componentSet (F.totalTransform π Y)
            ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩ := ⟨⟨x, hxj⟩, rfl, rfl⟩
        rw [stalkIdeal_totalTransform_componentIdeal_of_notMem_range_of_mem hY h F hF hsnc hφ hc hΦ
          hx rfl i hxi hj hxj]
        exact IsFinsetMonomial.of_mem _ (IdealSheaf.mem_activeFinset.mpr hcs)
      · rw [stalkIdeal_totalTransform_componentIdeal_of_notMem_range_of_notMem h F hF hφ hc hΦ hx
          rfl i hxi hj hxj]
        exact IsFinsetMonomial.top _ _
  · -- off the centre: the strict-transform component through `x`
    have hxj : x ∈ strictTransformSet π Y (F.hyp i.1) :=
      (HypersurfaceFamily.mem_strictTransform_iff_of_notMem h hF hxY i.1).mpr hmem
    have hcs : x ∈ componentSet (F.totalTransform π Y)
        ⟨toLex (Sum.inl i.1), ConnectedComponents.mk ⟨x, hxj⟩⟩ := ⟨⟨x, hxj⟩, rfl, rfl⟩
    rw [stalkIdeal_totalTransform_componentIdeal_of_notMem hY h F hF hsnc hxY i hxi hxj]
    exact IsFinsetMonomial.of_mem _ (IdealSheaf.mem_activeFinset.mpr hcs)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The nonmonomial part, with respect to the transformed boundary family, of the total transform of
the monomial part is the unit ideal: the total transform of a monomial in the components of `F` is a
monomial in the components of `F'` ([Kol07, 111, Step 1]). -/
theorem nonmonomialPart_totalTransform_monomialPart_eq_top :
    nonmonomialPart (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
      ((monomialPart F hF I).pullback π h.contMDiff) = ⊤ :=
  nonmonomialPart_eq_top_of_forall_stalkIdeal_eq_prod _ _ _
    (stalkIdeal_totalTransform_monomialPart_eq_prod hY h F hF hsnc I)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The total transform of the monomial part is its own monomial part with respect to the
transformed boundary family. -/
theorem monomialPart_totalTransform_monomialPart_eq_self :
    monomialPart (F.totalTransform π Y) (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
        ((monomialPart F hF I).pullback π h.contMDiff) =
      (monomialPart F hF I).pullback π h.contMDiff :=
  monomialPart_eq_self_of_nonmonomialPart_eq_top _ _ _
    (nonmonomialPart_totalTransform_monomialPart_eq_top hY h F hF hsnc I)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The total transform of the monomial part `M(𝓘)` is a locally finite product of powers of the
component ideals of the transformed boundary family `F'`: the exponents are its own component
exponents with respect to `F'`, for which the right-hand side is its monomial part, and it equals
its monomial part by `monomialPart_totalTransform_monomialPart_eq_self`. -/
theorem exists_comap_monomialPart_eq_monomial :
    ∃ a : ComponentIndex (F.totalTransform π Y) → ℕ,
      (monomialPart F hF I).pullback π h.contMDiff =
        IdealSheaf.locallyFiniteProduct (structureSheaf 𝕜 E M')
          (fun i => componentIdeal (F.totalTransform π Y)
            (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc) i
            ^ a i)
          (componentSet (F.totalTransform π Y))
          (componentSet_locallyFinite (F.totalTransform π Y)
            (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc))
          (componentIdeal_pow_stalkIdeal_top_of_notMem (F.totalTransform π Y)
            (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc) a) := by
  refine ⟨componentExponent (F.totalTransform π Y)
    (HypersurfaceFamily.isSnc_totalTransform hY h hF hsnc)
    ((monomialPart F hF I).pullback π h.contMDiff), ?_⟩
  exact (monomialPart_totalTransform_monomialPart_eq_self hY h F hF hsnc I).symm

end Assembly

end Hironaka.Manifold.BMO

end
