/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.IdealSheaf.Monoid
public import Hironaka.Resolution.Analytic.OrderReduction.BMO.NonmonomialPart
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.BlowUp.Transform.MarkedAlgebra
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.BlowUp.Transform.OrderAlong
import Hironaka.Manifold.BlowUp.Transform.StrictCharts
import Hironaka.Manifold.BlowUp.Transform.StrictIdeal
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.Snc.Coherence
import Hironaka.Manifold.Snc.Dictionary
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Split
import Hironaka.Resolution.Analytic.OrderReduction.BMO.Step1Measure
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# The order along a smooth hypersurface is a valuation; the exponents of the monomial part

The order `ord_D J` of an ideal sheaf `J` along a subvariety `D` is the largest `p` with `J ⊆ 𝓘_D^p`
at the point ([Kol07, Definition 47]; [BM97, §3] in the analytic setting). This file proves that at
a point where the ideal of `D` is generated by a prime element `c` of the stalk, a domain, the order
along `D` is the `c`-adic valuation of ideals: additive on products
(`IdealSheaf.ordAlongIdeal_mul_of_stalkIdeal_eq_span`), with the forms for powers and finite
products, `ord_D D = 1`, and `ord_D J = ⊤` exactly when the stalk of `J` is zero (Krull's
intersection theorem in the Noetherian local stalk). The inequality
`ord_D (J·K) ≥ ord_D J + ord_D K` is elementary; for the other inequality, elements `f ∈ J`, `g ∈ K`
of exact `c`-multiplicities `k`, `l` have `f g` of exact multiplicity `k + l`. Along a smooth
hypersurface `S` of an analytic manifold these hold at every point of `S`, where the coordinate
adapted to `S` is a prime element of the factorial stalk; off `S` every order along `S` is `⊤`.

For a boundary family `F` with simple normal crossings and the decomposition `𝓘 = M(𝓘) · N(𝓘)` of
[Kol07, Definition–Lemma 110] (`BMO/MonomialPart.lean`, `BMO/NonmonomialPart.lean`), the
consequences are: the exponent `ord_D 𝓘` of a component `D` can be read at any point of `D`
(`componentExponent_eq_toNat_ordAlongIdeal`); `ord_D M(𝓘) = ord_D 𝓘` at every point of `D`; the
exponents of the nonmonomial part all vanish (`componentExponent_nonmonomialPart_eq_zero`, the
statement "cosupp `N(I)` does not contain any of the `Eⁱ`" of Kollár's lemma, component by
component), so `M(N(𝓘)) = ⊤` and `N(N(𝓘)) = N(𝓘)`; and the exponents are additive on products of
ideal sheaves that are nonzero at every point, so multiplying by a power of the ideal of a component
raises exactly that component's exponent: the monomial part absorbs monomial factors
(`monomialPart_componentIdeal_pow_mul`) and the nonmonomial part ignores them
(`nonmonomialPart_componentIdeal_pow_mul`), which is the one-component form of the remark of [Kol07,
111, Step 1] that an ideal of boundary divisors changes only the monomial part.
-/

public section

open Set
open scoped Manifold ContDiff Topology
open IsManifold (maximalAtlas)

universe u

namespace Manifold

open Hironaka.Manifold

/-! ### A. Ring lemmas: exact multiplicity and the `c`-adic filtration -/

section RingHelpers

variable {R : Type*} [CommRing R]

/-- If `J ⊆ (c)^k` but `J ⊄ (c)^(k+1)`, some element of `J` has `c`-multiplicity exactly `k`. -/
theorem _root_.Ideal.exists_mem_emultiplicity_eq {c : R} {J : Ideal R} {k : ℕ}
    (h₁ : J ≤ Ideal.span {c} ^ k) (h₂ : ¬ J ≤ Ideal.span {c} ^ (k + 1)) :
    ∃ f ∈ J, emultiplicity c f = k := by
  obtain ⟨f, hfJ, hf⟩ : ∃ f ∈ J, f ∉ Ideal.span {c} ^ (k + 1) := by
    by_contra h
    exact h₂ fun f hf => not_not.mp fun hn => h ⟨f, hf, hn⟩
  refine ⟨f, hfJ, ?_⟩
  rw [emultiplicity_eq_coe]
  constructor
  · have := h₁ hfJ
    rwa [Ideal.span_singleton_pow, Ideal.mem_span_singleton] at this
  · intro hdvd
    apply hf
    rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    exact hdvd

end RingHelpers

/-! ### B. The order along a divisor at a point: generic stalk-level facts -/

section Generic

variable {X : TopCat} {𝒪 : TopCat.Sheaf CommRingCat X}

/-- Where the stalk of `D` is the unit ideal (off the divisor), every order along `D` is `⊤`. -/
theorem IdealSheaf.ordAlongIdeal_of_stalkIdeal_eq_top (D J : IdealSheaf 𝒪) (a : X)
    (hD : D.stalkIdeal a = ⊤) : IdealSheaf.ordAlongIdeal D J a = ⊤ := by
  refine ENat.eq_top_iff_forall_ge.mpr fun m => ?_
  rw [IdealSheaf.le_ordAlongIdeal_iff, hD, Ideal.top_pow]
  exact le_top

/-- An ideal sheaf whose stalk at `a` is the unit ideal (for instance the unit ideal sheaf) has
order `0` along a divisor whose stalk at `a` is proper. -/
theorem IdealSheaf.ordAlongIdeal_eq_zero_of_stalkIdeal_eq_top (D J : IdealSheaf 𝒪) (a : X)
    (hJ : J.stalkIdeal a = ⊤) (hD : D.stalkIdeal a ≠ ⊤) : IdealSheaf.ordAlongIdeal D J a = 0 := by
  refine le_antisymm ?_ zero_le
  by_contra h
  rw [not_le] at h
  have h1 : ((1 : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D J a := by
    rw [Nat.cast_one]
    exact Order.one_le_iff_ne_zero.mpr h.ne'
  rw [IdealSheaf.le_ordAlongIdeal_iff, hJ, pow_one] at h1
  exact hD (top_le_iff.mp h1)

/-- Along a divisor whose stalk is `(c)`, an ideal sheaf whose stalk is `(d)` has order `0` when
`c ∤ d`. -/
theorem IdealSheaf.ordAlongIdeal_eq_zero_of_stalkIdeal_eq_span_of_not_dvd (D J : IdealSheaf 𝒪)
    (a : X) {c d : 𝒪.presheaf.stalk a} (hD : D.stalkIdeal a = Ideal.span {c})
    (hJ : J.stalkIdeal a = Ideal.span {d}) (hcd : ¬ c ∣ d) :
    IdealSheaf.ordAlongIdeal D J a = 0 := by
  refine le_antisymm ?_ zero_le
  by_contra h
  rw [not_le] at h
  have h1 : ((1 : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D J a := by
    rw [Nat.cast_one]
    exact Order.one_le_iff_ne_zero.mpr h.ne'
  rw [IdealSheaf.le_ordAlongIdeal_iff, hD, hJ, pow_one,
    Ideal.span_singleton_le_span_singleton] at h1
  exact hcd h1

variable (D : IdealSheaf 𝒪) (a : X) [hdom : IsDomain (𝒪.presheaf.stalk a)]
  {c : 𝒪.presheaf.stalk a} (hD : D.stalkIdeal a = Ideal.span {c}) (hc : Prime c)

include hD hc in
/-- Along a divisor whose stalk is the prime `(c)` of the domain stalk, the divisor itself has order
exactly `1`: `c ∉ (c)²`, since `c` is neither zero nor a unit. -/
theorem IdealSheaf.ordAlongIdeal_self_of_stalkIdeal_eq_span :
    IdealSheaf.ordAlongIdeal D D a = 1 := by
  apply le_antisymm
  · by_contra h
    rw [not_le] at h
    have h2 : ((2 : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D D a := by
      have := (ENat.add_one_le_iff (ENat.natCast_ne_top 1)).mpr (by exact_mod_cast h)
      exact_mod_cast this
    rw [IdealSheaf.le_ordAlongIdeal_iff, hD, Ideal.span_singleton_pow] at h2
    have hc2 : c ∈ Ideal.span {c ^ 2} := h2 (Ideal.mem_span_singleton_self c)
    rw [Ideal.mem_span_singleton] at hc2
    obtain ⟨u, hu⟩ := hc2
    have hzero : c * (1 - c * u) = 0 := by
      rw [mul_sub, mul_one, ← mul_assoc, ← pow_two]
      exact sub_eq_zero.mpr hu
    rcases mul_eq_zero.mp hzero with h0 | h0
    · exact hc.ne_zero h0
    · have hcu : c * u = 1 := (sub_eq_zero.mp h0).symm
      exact hc.not_isUnit ⟨⟨c, u, hcu, (mul_comm u c).trans hcu⟩, rfl⟩
  · have h1 : ((1 : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D D a := by
      rw [IdealSheaf.le_ordAlongIdeal_iff, pow_one]
    exact_mod_cast h1

include hD hc in
/-- The order along a divisor is a valuation: at a point where the stalk of the divisor is the prime
`(c)` of the domain stalk, `ord_D (J · K) = ord_D J + ord_D K` in `ℕ∞`. The inequality `≥` is
`le_ordAlongIdeal_mul`; for `≤`, elements `f ∈ J_a`, `g ∈ K_a` of exact `c`-multiplicities `k`, `l`
(`Ideal.exists_mem_emultiplicity_eq`) have `f g` of multiplicity `k + l` (`emultiplicity_mul`), so
`f g ∈ (J K)_a` is not in `(c)^(k+l+1)`; the cases with a `⊤` are those of a zero stalk. -/
theorem IdealSheaf.ordAlongIdeal_mul_of_stalkIdeal_eq_span (J K : IdealSheaf 𝒪) :
    IdealSheaf.ordAlongIdeal D (J * K) a =
      IdealSheaf.ordAlongIdeal D J a + IdealSheaf.ordAlongIdeal D K a := by
  rcases eq_or_ne (IdealSheaf.ordAlongIdeal D J a) ⊤ with hJ | hJ
  · rw [hJ, top_add]
    refine ENat.eq_top_iff_forall_ge.mpr fun m => ?_
    rw [IdealSheaf.le_ordAlongIdeal_iff, IdealSheaf.stalkIdeal_mul]
    exact Ideal.mul_le_left.trans ((IdealSheaf.le_ordAlongIdeal_iff D J a m).mp (hJ ▸ le_top))
  rcases eq_or_ne (IdealSheaf.ordAlongIdeal D K a) ⊤ with hK | hK
  · rw [hK, add_top]
    refine ENat.eq_top_iff_forall_ge.mpr fun m => ?_
    rw [IdealSheaf.le_ordAlongIdeal_iff, IdealSheaf.stalkIdeal_mul]
    exact Ideal.mul_le_right.trans ((IdealSheaf.le_ordAlongIdeal_iff D K a m).mp (hK ▸ le_top))
  lift IdealSheaf.ordAlongIdeal D J a to ℕ using hJ with k hk
  lift IdealSheaf.ordAlongIdeal D K a to ℕ using hK with l hl
  apply le_antisymm
  · by_contra hlt
    rw [not_le] at hlt
    have h1 : ((k + l + 1 : ℕ) : ℕ∞) ≤ IdealSheaf.ordAlongIdeal D (J * K) a := by
      have := (ENat.add_one_le_iff (ENat.natCast_ne_top (k + l))).mpr (by exact_mod_cast hlt)
      exact_mod_cast this
    rw [IdealSheaf.le_ordAlongIdeal_iff, IdealSheaf.stalkIdeal_mul, hD] at h1
    have hJk : J.stalkIdeal a ≤ Ideal.span {c} ^ k := by
      rw [← hD, ← IdealSheaf.le_ordAlongIdeal_iff, ← hk]
    have hJk' : ¬ J.stalkIdeal a ≤ Ideal.span {c} ^ (k + 1) := by
      rw [← hD, ← IdealSheaf.le_ordAlongIdeal_iff, ← hk]
      exact_mod_cast Nat.not_succ_le_self k
    have hKl : K.stalkIdeal a ≤ Ideal.span {c} ^ l := by
      rw [← hD, ← IdealSheaf.le_ordAlongIdeal_iff, ← hl]
    have hKl' : ¬ K.stalkIdeal a ≤ Ideal.span {c} ^ (l + 1) := by
      rw [← hD, ← IdealSheaf.le_ordAlongIdeal_iff, ← hl]
      exact_mod_cast Nat.not_succ_le_self l
    obtain ⟨f, hfJ, hf⟩ := Ideal.exists_mem_emultiplicity_eq hJk hJk'
    obtain ⟨g, hgK, hg⟩ := Ideal.exists_mem_emultiplicity_eq hKl hKl'
    have hfg : f * g ∈ Ideal.span {c} ^ (k + l + 1) := h1 (Ideal.mul_mem_mul hfJ hgK)
    rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton, pow_dvd_iff_le_emultiplicity,
      emultiplicity_mul hc, hf, hg] at hfg
    have hfg' : k + l + 1 ≤ k + l := by exact_mod_cast hfg
    omega
  · have := le_ordAlongIdeal_mul D hk.le hl.le
    exact_mod_cast this

include hD hc in
/-- Along a divisor whose stalk is a prime principal ideal, the order of a power is the multiple of
the order (in `ℕ∞`, where `0 · ⊤ = 0` and the unit ideal sheaf has order `0`). -/
theorem IdealSheaf.ordAlongIdeal_pow_of_stalkIdeal_eq_span (J : IdealSheaf 𝒪) (s : ℕ) :
    IdealSheaf.ordAlongIdeal D (J ^ s) a = (s : ℕ∞) * IdealSheaf.ordAlongIdeal D J a := by
  induction s with
  | zero =>
    rw [pow_zero, Nat.cast_zero, zero_mul]
    have hne : D.stalkIdeal a ≠ ⊤ := by
      rw [hD]
      exact fun h => hc.not_isUnit (Ideal.span_singleton_eq_top.mp h)
    exact IdealSheaf.ordAlongIdeal_eq_zero_of_stalkIdeal_eq_top D 1 a (IdealSheaf.stalkIdeal_one a)
      hne
  | succ s ih =>
    rw [pow_succ, IdealSheaf.ordAlongIdeal_mul_of_stalkIdeal_eq_span D a hD hc, ih, Nat.cast_succ,
      add_mul, one_mul]

include hD hc in
/-- Along a divisor whose stalk is a prime principal ideal, the order of a finite product is the sum
of the orders. -/
theorem IdealSheaf.ordAlongIdeal_finset_prod_of_stalkIdeal_eq_span {ι : Type*} (F : Finset ι)
    (G : ι → IdealSheaf 𝒪) :
    IdealSheaf.ordAlongIdeal D (∏ i ∈ F, G i) a = ∑ i ∈ F, IdealSheaf.ordAlongIdeal D (G i) a := by
  classical
  induction F using Finset.induction_on with
  | empty =>
    rw [Finset.prod_empty, Finset.sum_empty]
    have hne : D.stalkIdeal a ≠ ⊤ := by
      rw [hD]
      exact fun h => hc.not_isUnit (Ideal.span_singleton_eq_top.mp h)
    exact IdealSheaf.ordAlongIdeal_eq_zero_of_stalkIdeal_eq_top D 1 a (IdealSheaf.stalkIdeal_one a)
      hne
  | insert i F hi ih =>
    rw [Finset.prod_insert hi, Finset.sum_insert hi,
      IdealSheaf.ordAlongIdeal_mul_of_stalkIdeal_eq_span D a hD hc, ih]

/-- At a point where the stalk of the divisor is a proper principal ideal `(c)` of a Noetherian
local stalk, the order along the divisor is `⊤` exactly when the stalk of the ideal sheaf is zero:
Krull's intersection theorem, `⋂ₚ (c)^p = 0`. -/
theorem IdealSheaf.ordAlongIdeal_eq_top_iff_of_stalkIdeal_eq_span (D J : IdealSheaf 𝒪) (a : X)
    [hnoeth : IsNoetherianRing (𝒪.presheaf.stalk a)] [hloc : IsLocalRing (𝒪.presheaf.stalk a)]
    {c : 𝒪.presheaf.stalk a} (hD : D.stalkIdeal a = Ideal.span {c}) (hc : ¬ IsUnit c) :
    IdealSheaf.ordAlongIdeal D J a = ⊤ ↔ J.stalkIdeal a = ⊥ := by
  constructor
  · intro h
    have hne : Ideal.span {c} ≠ ⊤ := fun ht => hc (Ideal.span_singleton_eq_top.mp ht)
    rw [eq_bot_iff, ← Ideal.iInf_pow_eq_bot_of_isLocalRing (Ideal.span {c}) hne]
    refine le_iInf fun p => ?_
    rw [← hD, ← IdealSheaf.le_ordAlongIdeal_iff, h]
    exact le_top
  · intro h
    refine ENat.eq_top_iff_forall_ge.mpr fun m => ?_
    rw [IdealSheaf.le_ordAlongIdeal_iff, h]
    exact bot_le

end Generic

/-! ### C. Along a smooth hypersurface -/

section Hypersurface

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M] {S : Set M}

/-- At a point of a smooth hypersurface `S`, the stalk of the ideal sheaf `𝓘_S` is generated by a
prime element of the stalk, the coordinate of a chart adapted to `S` that vanishes along `S`. -/
theorem IsClosedSubmanifold.exists_stalkIdeal_idealSheaf_eq_span_prime
    (hS : IsClosedSubmanifold ψ S 1) {x : M} (hx : x ∈ S) :
    ∃ c : (structureSheaf 𝕜 E M).presheaf.stalk x,
      Prime c ∧ hS.idealSheaf.stalkIdeal x = Ideal.span {c} := by
  obtain ⟨φ, σ, hxφ, hφ⟩ := hS.exists_adaptedChart x hx
  refine ⟨coord E ψ φ hφ.1 hxφ (σ default), ?_, ?_⟩
  · exact prime_coord_of_eq_zero φ hφ.1 hxφ ((hφ.2 x hxφ).mp hx default)
  · rw [hS.stalkIdeal_idealSheaf_eq_span hx hφ hxφ, Set.range_unique]

/-- At a point of the hypersurface the stalk of `𝓘_S` is a proper ideal. -/
theorem IsClosedSubmanifold.stalkIdeal_idealSheaf_ne_top (hS : IsClosedSubmanifold ψ S 1) {x : M}
    (hx : x ∈ S) : hS.idealSheaf.stalkIdeal x ≠ ⊤ := by
  obtain ⟨c, hc, hD⟩ := hS.exists_stalkIdeal_idealSheaf_eq_span_prime hx
  rw [hD]
  exact fun h => hc.not_isUnit (Ideal.span_singleton_eq_top.mp h)

/-- Off the hypersurface every order along it is `⊤`. -/
theorem IsClosedSubmanifold.ordAlongIdeal_idealSheaf_of_notMem (hS : IsClosedSubmanifold ψ S 1)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) {x : M} (hx : x ∉ S) :
    IdealSheaf.ordAlongIdeal hS.idealSheaf J x = ⊤ :=
  IdealSheaf.ordAlongIdeal_of_stalkIdeal_eq_top _ _ _ (hS.stalkIdeal_idealSheaf_of_notMem hx)

/-- At a point of the hypersurface the unit ideal sheaf has order `0` along it. -/
theorem IsClosedSubmanifold.ordAlongIdeal_idealSheaf_one (hS : IsClosedSubmanifold ψ S 1) {x : M}
    (hx : x ∈ S) : IdealSheaf.ordAlongIdeal hS.idealSheaf 1 x = 0 := by
  exact IdealSheaf.ordAlongIdeal_eq_zero_of_stalkIdeal_eq_top hS.idealSheaf 1 x
    (IdealSheaf.stalkIdeal_one _) (hS.stalkIdeal_idealSheaf_ne_top hx)

/-- The order along a smooth hypersurface `S` is additive on products, at every point of `M`: on `S`
because the stalk of `𝓘_S` is generated by a prime element of the domain stalk
(`IdealSheaf.ordAlongIdeal_mul_of_stalkIdeal_eq_span`), off `S` because both sides are `⊤`. -/
theorem IsClosedSubmanifold.ordAlongIdeal_idealSheaf_mul (hS : IsClosedSubmanifold ψ S 1)
    (J K : IdealSheaf (structureSheaf 𝕜 E M)) (x : M) :
    IdealSheaf.ordAlongIdeal hS.idealSheaf (J * K) x =
      IdealSheaf.ordAlongIdeal hS.idealSheaf J x + IdealSheaf.ordAlongIdeal hS.idealSheaf K x := by
  by_cases hx : x ∈ S
  · obtain ⟨φ, σ, hxφ, hφ⟩ := hS.exists_adaptedChart x hx
    have hdom : IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk x) := isDomain_stalk ψ hφ.1 hxφ
    obtain ⟨c, hc, hD⟩ := hS.exists_stalkIdeal_idealSheaf_eq_span_prime hx
    exact IdealSheaf.ordAlongIdeal_mul_of_stalkIdeal_eq_span hS.idealSheaf x (hdom := hdom) hD hc
      J K
  · rw [hS.ordAlongIdeal_idealSheaf_of_notMem J hx, hS.ordAlongIdeal_idealSheaf_of_notMem K hx,
      hS.ordAlongIdeal_idealSheaf_of_notMem (J * K) hx, top_add]

/-- At a point of the hypersurface, the order along it of a power is the multiple of the order. (Off
the hypersurface the statement fails for the zeroth power, whose order is `⊤`.) -/
theorem IsClosedSubmanifold.ordAlongIdeal_idealSheaf_pow (hS : IsClosedSubmanifold ψ S 1)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) (s : ℕ) {x : M} (hx : x ∈ S) :
    IdealSheaf.ordAlongIdeal hS.idealSheaf (J ^ s) x =
      (s : ℕ∞) * IdealSheaf.ordAlongIdeal hS.idealSheaf J x := by
  induction s with
  | zero => rw [pow_zero, Nat.cast_zero, zero_mul, hS.ordAlongIdeal_idealSheaf_one hx]
  | succ s ih => rw [pow_succ, hS.ordAlongIdeal_idealSheaf_mul, ih, Nat.cast_succ, add_mul, one_mul]

/-- At a point of the hypersurface, the order along it of a finite product is the sum of the
orders. -/
theorem IsClosedSubmanifold.ordAlongIdeal_idealSheaf_finset_prod (hS : IsClosedSubmanifold ψ S 1)
    {ι : Type*} (F : Finset ι) (G : ι → IdealSheaf (structureSheaf 𝕜 E M)) {x : M} (hx : x ∈ S) :
    IdealSheaf.ordAlongIdeal hS.idealSheaf (∏ i ∈ F, G i) x =
      ∑ i ∈ F, IdealSheaf.ordAlongIdeal hS.idealSheaf (G i) x := by
  classical
  induction F using Finset.induction_on with
  | empty => rw [Finset.prod_empty, Finset.sum_empty, hS.ordAlongIdeal_idealSheaf_one hx]
  | insert i F hi ih =>
    rw [Finset.prod_insert hi, Finset.sum_insert hi, hS.ordAlongIdeal_idealSheaf_mul, ih]

/-- A smooth hypersurface has order `1` along itself at each of its points. -/
theorem IsClosedSubmanifold.ordAlongIdeal_idealSheaf_self (hS : IsClosedSubmanifold ψ S 1) {x : M}
    (hx : x ∈ S) : IdealSheaf.ordAlongIdeal hS.idealSheaf hS.idealSheaf x = 1 := by
  obtain ⟨φ, σ, hxφ, hφ⟩ := hS.exists_adaptedChart x hx
  have hdom : IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk x) := isDomain_stalk ψ hφ.1 hxφ
  obtain ⟨c, hc, hD⟩ := hS.exists_stalkIdeal_idealSheaf_eq_span_prime hx
  exact IdealSheaf.ordAlongIdeal_self_of_stalkIdeal_eq_span hS.idealSheaf x (hdom := hdom) hD hc

/-- At a point of the hypersurface, the order along it is `⊤` exactly when the stalk of the ideal
sheaf is zero (Krull's intersection theorem in the Noetherian local stalk). -/
theorem IsClosedSubmanifold.ordAlongIdeal_idealSheaf_eq_top_iff (hS : IsClosedSubmanifold ψ S 1)
    (J : IdealSheaf (structureSheaf 𝕜 E M)) {x : M} (hx : x ∈ S) :
    IdealSheaf.ordAlongIdeal hS.idealSheaf J x = ⊤ ↔ J.stalkIdeal x = ⊥ := by
  obtain ⟨φ, σ, hxφ, hφ⟩ := hS.exists_adaptedChart x hx
  have hnoeth : IsNoetherianRing ((structureSheaf 𝕜 E M).presheaf.stalk x) :=
    isNoetherianRing_stalk_of_chart E ψ φ hxφ hφ.1
  obtain ⟨c, hc, hD⟩ := hS.exists_stalkIdeal_idealSheaf_eq_span_prime hx
  exact IdealSheaf.ordAlongIdeal_eq_top_iff_of_stalkIdeal_eq_span hS.idealSheaf J x (hnoeth :=
  hnoeth)
    hD hc.not_isUnit

/-- The generic order along a smooth hypersurface is additive: on `S` it is the pointwise order,
which is constant along the connected components, and off `S` it is `⊤`. -/
theorem IsClosedSubmanifold.genericOrdAlong_idealSheaf_mul (hS : IsClosedSubmanifold ψ S 1)
    (J K : IdealSheaf (structureSheaf 𝕜 E M)) (x : M) :
    IdealSheaf.genericOrdAlong hS.idealSheaf (J * K) x =
      IdealSheaf.genericOrdAlong hS.idealSheaf J x + IdealSheaf.genericOrdAlong hS.idealSheaf K x
        := by
  by_cases hx : x ∈ S
  · rw [genericOrdAlong_eq_ordAlong hS _ hx, genericOrdAlong_eq_ordAlong hS _ hx,
      genericOrdAlong_eq_ordAlong hS _ hx, hS.ordAlongIdeal_idealSheaf_mul]
  · have h : ∀ L : IdealSheaf (structureSheaf 𝕜 E M),
        IdealSheaf.genericOrdAlong hS.idealSheaf L x = ⊤ := fun L => by
      rw [IdealSheaf.genericOrdAlong_def, hS.cosupport_idealSheaf, connectedComponentIn_eq_empty hx]
      simp
    rw [h, h, h, top_add]

end Hypersurface

end Manifold

namespace Hironaka.Manifold.BMO

open Hironaka.Manifold
open _root_.Manifold

/-! ### D. The components of the boundary family and the decomposition `𝓘 = M(𝓘)·N(𝓘)` -/

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  [IsManifold 𝓘(𝕜, E) ω M]

variable (F : HypersurfaceFamily M)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The representative point of the component `i` lies on its component set. -/
theorem out_mem_componentSet (i : ComponentIndex F) :
    (i.2.out : F.hyp i.1).val ∈ componentSet F i :=
  ⟨i.2.out, by rw [Set.mem_preimage, Set.mem_singleton_iff]; exact Quotient.out_eq' i.2, rfl⟩

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- A component set is preconnected, being the image of a connected component of the member. -/
theorem isPreconnected_componentSet (i : ComponentIndex F) : IsPreconnected (componentSet F i) := by
  have hset : (ConnectedComponents.mk ⁻¹' {i.2} : Set (F.hyp i.1)) =
      connectedComponent i.2.out := by
    conv_lhs => rw [← Quotient.out_eq' i.2]
    exact connectedComponents_preimage_singleton
  rw [componentSet, hset]
  exact isPreconnected_connectedComponent.image _ continuous_subtype_val.continuousOn

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The exponent `ord_D 𝓘` of the monomial part at a component `D` can be read at any point `x` of
`D`: the generic order is the pointwise order at the representative, and the order along a smooth
hypersurface is constant on the connected component. -/
theorem componentExponent_eq_toNat_ordAlongIdeal (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (i : ComponentIndex F) {x : M}
    (hx : x ∈ componentSet F i) :
    componentExponent F hF I i =
      (IdealSheaf.ordAlongIdeal (componentIdeal F hF i) I x).toNat := by
  unfold componentExponent componentIdeal
  rw [genericOrdAlong_eq_ordAlong (componentSubmanifold F hF i) I (out_mem_componentSet F i),
    ordAlong_eq_of_isPreconnected (componentSubmanifold F hF i) I subset_rfl
      (isPreconnected_componentSet F i) (out_mem_componentSet F i) hx]

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- A component has order `1` along itself at each of its points. -/
theorem componentIdeal_ordAlongIdeal_self (hF : F.IsSnc ψ) (i : ComponentIndex F) {x : M}
    (hx : x ∈ componentSet F i) :
    IdealSheaf.ordAlongIdeal (componentIdeal F hF i) (componentIdeal F hF i) x = 1 :=
  (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_self hx

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- Along a component `D`, another component `D'` not passing through the point `x` has order `0`
there, its ideal sheaf being the unit ideal at `x`. -/
theorem componentIdeal_ordAlongIdeal_of_notMem (hF : F.IsSnc ψ) (i i' : ComponentIndex F) {x : M}
    (hx : x ∈ componentSet F i) (hx' : x ∉ componentSet F i') :
    IdealSheaf.ordAlongIdeal (componentIdeal F hF i) (componentIdeal F hF i') x = 0 := by
  refine IdealSheaf.ordAlongIdeal_eq_zero_of_stalkIdeal_eq_top (componentIdeal F hF i)
    (componentIdeal F hF i') x ?_ ?_
  · change (componentSubmanifold F hF i').idealSheaf.stalkIdeal x = ⊤
    exact (componentSubmanifold F hF i').stalkIdeal_idealSheaf_of_notMem hx'
  · change (componentSubmanifold F hF i).idealSheaf.stalkIdeal x ≠ ⊤
    exact (componentSubmanifold F hF i).stalkIdeal_idealSheaf_ne_top hx

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- Along a component `D`, a different component `D'` through the same point has order `0`: in a
chart of simple normal crossings at the point ([Kol07, Definition 24]) the two are distinct
coordinate hyperplanes, whose coordinates do not divide each other. -/
theorem componentIdeal_ordAlongIdeal_of_ne (hF : F.IsSnc ψ) {i i' : ComponentIndex F} (hne : i ≠ i')
    {x : M} (hx : x ∈ componentSet F i) (hx' : x ∈ componentSet F i') :
    IdealSheaf.ordAlongIdeal (componentIdeal F hF i) (componentIdeal F hF i') x = 0 := by
  obtain ⟨φ, c, hc⟩ := hF.exists_isSncChartAt x
  have hxi : x ∈ F.hyp i.1 := Subtype.coe_image_subset _ _ hx
  have hxi' : x ∈ F.hyp i'.1 := Subtype.coe_image_subset _ _ hx'
  have hstalk : ∀ (k : ComponentIndex F) (hk : x ∈ componentSet F k) (hkm : x ∈ F.hyp k.1),
      (componentIdeal F hF k).stalkIdeal x =
        Ideal.span {coord E ψ φ hc.1 hc.2.1 (c ⟨k.1, hkm⟩)} := by
    intro k hk hkm
    have hadapt : IsAdaptedChart ψ (F.hyp k.1) φ (singleEmb (c ⟨k.1, hkm⟩)) :=
      isAdaptedChart_singleIdx hc.1 fun y hy => hc.mem_iff ⟨k.1, hkm⟩ hy
    rw [componentIdeal_stalkIdeal_eq F hF k hk,
      (hF.isClosedSubmanifold k.1).stalkIdeal_idealSheaf_eq_span hkm hadapt hc.2.1,
      range_singleIdx_coord]
  refine IdealSheaf.ordAlongIdeal_eq_zero_of_stalkIdeal_eq_span_of_not_dvd (componentIdeal F hF i)
    (componentIdeal F hF i') x (hstalk i hx hxi) (hstalk i' hx' hxi') ?_
  refine hc.not_coord_dvd fun h => hne ?_
  exact active_component_injective_fst F hx hx' (congrArg Subtype.val h)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The order of the monomial part along a component is the exponent: at every point `x` of `D`,
`ord_D M(𝓘) = ord_D 𝓘`. The stalk of `M(𝓘)` is the product of the factors `𝓘_{D'}^{e_{D'}}` of the
components through `x`, the order along `D` is additive, `ord_D 𝓘_D = 1`, and `ord_D 𝓘_{D'} = 0` for
the other components. -/
theorem ordAlongIdeal_componentIdeal_monomialPart (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (i : ComponentIndex F) {x : M}
    (hx : x ∈ componentSet F i) :
    IdealSheaf.ordAlongIdeal (componentIdeal F hF i) (monomialPart F hF I) x =
      componentExponent F hF I i := by
  classical
  set T : Finset (ComponentIndex F) :=
    IdealSheaf.activeFinset (componentSet F) (componentSet_locallyFinite F hF) x with hT
  have hiT : i ∈ T := IdealSheaf.mem_activeFinset.mpr hx
  have hstalk : (monomialPart F hF I).stalkIdeal x =
      (∏ k ∈ T, componentFactor F hF I k).stalkIdeal x := by
    rw [stalkIdeal_monomialPart, IdealSheaf.stalkIdeal_finset_prod]
  have hD : componentIdeal F hF i = (componentSubmanifold F hF i).idealSheaf := rfl
  rw [IdealSheaf.ordAlongIdeal_congr_stalk (componentIdeal F hF i) _ _ x hstalk, hD,
    (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_finset_prod T _ hx,
    Finset.sum_eq_single i]
  · change IdealSheaf.ordAlongIdeal (componentIdeal F hF i)
      (componentIdeal F hF i ^ componentExponent F hF I i) x = _
    rw [hD, (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_pow _ _ hx, ← hD,
      componentIdeal_ordAlongIdeal_self F hF i hx, mul_one]
  · intro k hkT hki
    change IdealSheaf.ordAlongIdeal (componentIdeal F hF i)
      (componentIdeal F hF k ^ componentExponent F hF I k) x = 0
    rw [hD, (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_pow _ _ hx, ← hD,
      componentIdeal_ordAlongIdeal_of_ne F hF (Ne.symm hki) hx (IdealSheaf.mem_activeFinset.mp hkT),
      mul_zero]
  · intro hi
    exact absurd hiT hi

/-- The exponents of the nonmonomial part vanish: at the representative point of the component `D`,
`ord_D 𝓘 = ord_D M(𝓘) + ord_D N(𝓘) = e_D + ord_D N(𝓘)` by the decomposition `M(𝓘) · N(𝓘) = 𝓘` and
additivity; if `ord_D 𝓘 = ⊤` then `e_D = 0` and `ord_D N(𝓘) = ⊤`, otherwise cancellation gives
`ord_D N(𝓘) = 0`; in both cases the exponent is `0`. This is the clause of
[Kol07, Definition–Lemma 110] that the cosupport of `N(I)` contains no boundary divisor, taken
component by component. -/
theorem componentExponent_nonmonomialPart_eq_zero (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (i : ComponentIndex F) :
    componentExponent F hF (nonmonomialPart F hF I) i = 0 := by
  have hyD : (i.2.out : F.hyp i.1).val ∈ componentSet F i := out_mem_componentSet F i
  set y := (i.2.out : F.hyp i.1).val with hy
  have hsplit : IdealSheaf.ordAlongIdeal (componentIdeal F hF i)
      (monomialPart F hF I * nonmonomialPart F hF I) y =
        IdealSheaf.ordAlongIdeal (componentIdeal F hF i) I y := by
    rw [monomialPart_mul_nonmonomialPart]
  have hD : componentIdeal F hF i = (componentSubmanifold F hF i).idealSheaf := rfl
  rw [hD, (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_mul, ← hD,
    ordAlongIdeal_componentIdeal_monomialPart F hF I i hyD,
    componentExponent_eq_toNat_ordAlongIdeal F hF I i hyD] at hsplit
  rw [componentExponent_eq_toNat_ordAlongIdeal F hF _ i hyD]
  rcases eq_or_ne (IdealSheaf.ordAlongIdeal (componentIdeal F hF i) I y) ⊤ with htop | hfin
  · rw [htop, ENat.toNat_top, Nat.cast_zero, zero_add] at hsplit
    rw [hsplit, ENat.toNat_top]
  · rw [ENat.natCast_toNat_eq_self.mpr hfin] at hsplit
    have h0 : IdealSheaf.ordAlongIdeal (componentIdeal F hF i) (nonmonomialPart F hF I) y = 0 :=
      WithTop.add_left_cancel hfin (hsplit.trans (add_zero _).symm)
    rw [h0, ENat.toNat_zero]

/-- The monomial part of the nonmonomial part is the unit ideal sheaf, `M(N(𝓘)) = ⊤`: every exponent
of `N(𝓘)` is `0`. -/
theorem monomialPart_nonmonomialPart_eq_top (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) :
    monomialPart F hF (nonmonomialPart F hF I) = ⊤ :=
  IdealSheaf.ext fun x => by
    rw [stalkIdeal_monomialPart, IdealSheaf.stalkIdeal_top, ← Ideal.one_eq_top]
    refine Finset.prod_eq_one fun i _ => ?_
    change (componentIdeal F hF i ^ componentExponent F hF (nonmonomialPart F hF I) i).stalkIdeal x
      = 1
    rw [componentExponent_nonmonomialPart_eq_zero, pow_zero, IdealSheaf.stalkIdeal_one,
      Ideal.one_eq_top]

/-- The nonmonomial part is idempotent, `N(N(𝓘)) = N(𝓘)`: the colon by the unit ideal `M(N(𝓘)) = ⊤`
is the identity. The analytic counterpart of `Hironaka.BMO.nonmonomialPart_nonmonomialPart`. -/
theorem nonmonomialPart_nonmonomialPart (hF : F.IsSnc ψ) (I : IdealSheaf (structureSheaf 𝕜 E M)) :
    nonmonomialPart F hF (nonmonomialPart F hF I) = nonmonomialPart F hF I :=
  IdealSheaf.ext fun x => by
    rw [stalkIdeal_nonmonomialPart, monomialPart_nonmonomialPart_eq_top, IdealSheaf.stalkIdeal_top,
      Submodule.top_coe, Submodule.colon_univ]

end Hironaka.Manifold.BMO

namespace Hironaka.Manifold.BMO

open Hironaka.Manifold
open _root_.Manifold

/-! ### E. Exponents of products; the nonmonomial part ignores monomial factors
-/

section ExponentsOfProducts

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  [IsManifold 𝓘(𝕜, E) ω M]

variable (F : HypersurfaceFamily M)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- Along a component, an ideal sheaf that is nonzero at every point has finite order at every point
of the component (Krull's intersection theorem). -/
theorem ordAlongIdeal_componentIdeal_ne_top (hF : F.IsSnc ψ) (I : IdealSheaf (structureSheaf 𝕜 E M))
    (hI : I.IsNonzeroEverywhere) (i : ComponentIndex F) {x : M} (hx : x ∈ componentSet F i) :
    IdealSheaf.ordAlongIdeal (componentIdeal F hF i) I x ≠ ⊤ := fun h =>
  hI x (((componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_eq_top_iff I hx).mp h)

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The component exponents are additive on products of ideal sheaves that are nonzero at every
point (the hypotheses exclude the orders `⊤`, which `toNat` would read as `0`). -/
theorem componentExponent_mul (hF : F.IsSnc ψ) (I J : IdealSheaf (structureSheaf 𝕜 E M))
    (hI : I.IsNonzeroEverywhere) (hJ : J.IsNonzeroEverywhere) (i : ComponentIndex F) :
    componentExponent F hF (I * J) i = componentExponent F hF I i + componentExponent F hF J i := by
  have hyD := out_mem_componentSet F i
  have hD : componentIdeal F hF i = (componentSubmanifold F hF i).idealSheaf := rfl
  rw [componentExponent_eq_toNat_ordAlongIdeal F hF _ i hyD,
    componentExponent_eq_toNat_ordAlongIdeal F hF I i hyD,
    componentExponent_eq_toNat_ordAlongIdeal F hF J i hyD, hD,
    (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_mul, ← hD,
    ENat.toNat_add (ordAlongIdeal_componentIdeal_ne_top F hF I hI i hyD)
      (ordAlongIdeal_componentIdeal_ne_top F hF J hJ i hyD)]

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- Multiplying by the `k`-th power of the ideal of a component raises that component's exponent by
`k`. -/
theorem componentExponent_componentIdeal_pow_mul (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (hI : I.IsNonzeroEverywhere) (i : ComponentIndex F)
    (k : ℕ) :
    componentExponent F hF (componentIdeal F hF i ^ k * I) i = k + componentExponent F hF I i := by
  have hyD := out_mem_componentSet F i
  have hD : componentIdeal F hF i = (componentSubmanifold F hF i).idealSheaf := rfl
  rw [componentExponent_eq_toNat_ordAlongIdeal F hF _ i hyD,
    componentExponent_eq_toNat_ordAlongIdeal F hF I i hyD, hD,
    (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_mul,
    (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_pow _ _ hyD, ← hD,
    componentIdeal_ordAlongIdeal_self F hF i hyD, mul_one,
    ENat.toNat_add (ENat.natCast_ne_top k) (ordAlongIdeal_componentIdeal_ne_top F hF I hI i hyD),
    ENat.toNat_natCast]

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- Multiplying by a power of the ideal of another component does not change the exponent: the
other component has order `0` along this one at every point, whether or not the two meet there. -/
theorem componentExponent_componentIdeal_pow_mul_of_ne (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) {i i' : ComponentIndex F} (hne : i ≠ i') (k : ℕ) :
    componentExponent F hF (componentIdeal F hF i' ^ k * I) i = componentExponent F hF I i := by
  have hyD := out_mem_componentSet F i
  have hD : componentIdeal F hF i = (componentSubmanifold F hF i).idealSheaf := rfl
  have h0 : IdealSheaf.ordAlongIdeal (componentIdeal F hF i) (componentIdeal F hF i')
      (i.2.out : F.hyp i.1).val = 0 := by
    by_cases hy' : (i.2.out : F.hyp i.1).val ∈ componentSet F i'
    · exact componentIdeal_ordAlongIdeal_of_ne F hF hne hyD hy'
    · exact componentIdeal_ordAlongIdeal_of_notMem F hF i i' hyD hy'
  rw [componentExponent_eq_toNat_ordAlongIdeal F hF _ i hyD,
    componentExponent_eq_toNat_ordAlongIdeal F hF I i hyD, hD,
    (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_mul,
    (componentSubmanifold F hF i).ordAlongIdeal_idealSheaf_pow _ _ hyD, ← hD, h0, mul_zero,
    zero_add]

/-- In a domain, a nonzero `a` cancels from both sides of a colon: `(a·I : a·J) = (I : J)`. -/
theorem _root_.Ideal.colon_span_singleton_mul_mul {R : Type*} [CommRing R] [IsDomain R] {a : R}
    (ha : a ≠ 0) (I J : Ideal R) :
    Submodule.colon (Ideal.span {a} * I) (↑(Ideal.span {a} * J) : Set R) =
      Submodule.colon I (↑J : Set R) := by
  ext r
  simp only [Submodule.mem_colon, SetLike.mem_coe, smul_eq_mul]
  constructor
  · intro h j hj
    obtain ⟨z, hzI, hz⟩ := Ideal.mem_span_singleton_mul.mp (h (a * j)
      (Ideal.mem_span_singleton_mul.mpr ⟨j, hj, rfl⟩))
    have : a * z = a * (r * j) := by rw [hz]; ring
    rwa [← mul_left_cancel₀ ha this]
  · intro h s hs
    obtain ⟨j, hj, rfl⟩ := Ideal.mem_span_singleton_mul.mp hs
    exact Ideal.mem_span_singleton_mul.mpr ⟨r * j, h j hj, by ring⟩

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The monomial part absorbs a monomial factor: `M(𝓘_D^k · 𝓘) = 𝓘_D^k · M(𝓘)` for a component `D`
and `𝓘` nonzero at every point. The exponent at `D` rises by `k` and the other exponents are
unchanged. -/
theorem monomialPart_componentIdeal_pow_mul (hF : F.IsSnc ψ) (I : IdealSheaf (structureSheaf 𝕜 E M))
    (hI : I.IsNonzeroEverywhere) (i : ComponentIndex F) (k : ℕ) :
    monomialPart F hF (componentIdeal F hF i ^ k * I) =
      componentIdeal F hF i ^ k * monomialPart F hF I :=
  IdealSheaf.ext fun x => by
    classical
    rw [IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_pow, stalkIdeal_monomialPart,
      stalkIdeal_monomialPart]
    set T := IdealSheaf.activeFinset (componentSet F) (componentSet_locallyFinite F hF) x with hT
    have hother : ∀ j ∈ T, j ≠ i →
        (componentFactor F hF (componentIdeal F hF i ^ k * I) j).stalkIdeal x =
          (componentFactor F hF I j).stalkIdeal x := by
      intro j _ hji
      unfold componentFactor
      rw [componentExponent_componentIdeal_pow_mul_of_ne F hF I hji k]
    by_cases hiT : i ∈ T
    · rw [← Finset.mul_prod_erase T _ hiT, ← Finset.mul_prod_erase T _ hiT,
        Finset.prod_congr rfl fun j hj => hother j (Finset.mem_of_mem_erase hj)
          (Finset.ne_of_mem_erase hj)]
      unfold componentFactor
      rw [componentExponent_componentIdeal_pow_mul F hF I hI i k, IdealSheaf.stalkIdeal_pow,
        IdealSheaf.stalkIdeal_pow, pow_add, mul_assoc]
    · rw [Finset.prod_congr rfl fun j hj => hother j hj (fun h => hiT (h ▸ hj))]
      have hx : x ∉ componentSet F i := fun h => hiT (IdealSheaf.mem_activeFinset.mpr h)
      change _ = ((componentSubmanifold F hF i).idealSheaf.stalkIdeal x) ^ k * _
      rw [(componentSubmanifold F hF i).stalkIdeal_idealSheaf_of_notMem hx, Ideal.top_pow,
        Ideal.top_mul]

/-- The nonmonomial part ignores a monomial factor: `N(𝓘_D^k · 𝓘) = N(𝓘)` for a component `D` and
`𝓘` nonzero at every point ([Kol07, 111, Step 1]: multiplying by an ideal of boundary divisors
changes only the monomial part). On `D` the common factor `c^k` cancels from the colon
(`Ideal.colon_span_singleton_mul_mul`), off `D` the factor is the unit ideal. The analytic
counterpart of `Hironaka.BMO.nonmonomialPart_monomial_mul` for one component. -/
theorem nonmonomialPart_componentIdeal_pow_mul (hF : F.IsSnc ψ)
    (I : IdealSheaf (structureSheaf 𝕜 E M)) (hI : I.IsNonzeroEverywhere) (i : ComponentIndex F)
    (k : ℕ) :
    nonmonomialPart F hF (componentIdeal F hF i ^ k * I) = nonmonomialPart F hF I :=
  IdealSheaf.ext fun x => by
    rw [stalkIdeal_nonmonomialPart, stalkIdeal_nonmonomialPart,
      monomialPart_componentIdeal_pow_mul F hF I hI i k, IdealSheaf.stalkIdeal_mul,
      IdealSheaf.stalkIdeal_mul, IdealSheaf.stalkIdeal_pow]
    by_cases hx : x ∈ componentSet F i
    · obtain ⟨φ, σ, hxφ, hφ⟩ := (componentSubmanifold F hF i).exists_adaptedChart x hx
      have hdom : IsDomain ((structureSheaf 𝕜 E M).presheaf.stalk x) := isDomain_stalk ψ hφ.1 hxφ
      obtain ⟨c, hc, hD⟩ :=
        (componentSubmanifold F hF i).exists_stalkIdeal_idealSheaf_eq_span_prime hx
      change Submodule.colon ((componentSubmanifold F hF i).idealSheaf.stalkIdeal x ^ k * _)
        ↑((componentSubmanifold F hF i).idealSheaf.stalkIdeal x ^ k * _) = _
      rw [hD, Ideal.span_singleton_pow]
      exact Ideal.colon_span_singleton_mul_mul (pow_ne_zero k hc.ne_zero) _ _
    · change Submodule.colon ((componentSubmanifold F hF i).idealSheaf.stalkIdeal x ^ k * _)
        ↑((componentSubmanifold F hF i).idealSheaf.stalkIdeal x ^ k * _) = _
      rw [(componentSubmanifold F hF i).stalkIdeal_idealSheaf_of_notMem hx, Ideal.top_pow,
        Ideal.top_mul, Ideal.top_mul]

end ExponentsOfProducts

end Hironaka.Manifold.BMO

