/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.ChartRing
import Hironaka.Algebra.Local.Chart
import Hironaka.Algebra.Local.Regular
import Hironaka.Algebra.Local.RegularSystem

/-!
# The local ring of the chart at its origin is regular of dimension `n`

Kollár's `yᵢ` "give local coordinates on a chart of `B_Z X`" [Kol07, Definition 60]; in the
local model this is the statement that `A' := R'_{𝔪'}`, the local ring of the chart ring
`R' = R[xᵢ/x_r : i < r]` at the origin `𝔪' = ⟨y₀, …, y_{n-1}⟩` of the chart, is a regular local
ring of dimension `n` whose maximal ideal is generated by the `n` images of the `yᵢ` (a regular
system of parameters).

**The argument** closes a chain of primes against a bound on the generators by Krull's height
theorem, as for the quotients by a regular system of parameters in
`Hironaka/Algebra/Local/RegularSystem.lean`, and needs no intermediate description of `A'/x_r A'`:

* `R'` is Noetherian, as a quotient of `R[Y₀, …, Y_{r-1}]` (the presentation of
  `Hironaka/Algebra/Local/Chart.lean` is surjective), so `A'` is a Noetherian local ring; its
  maximal ideal `𝔪' A'` is generated by the `n` images of the `yᵢ`, hence `spanFinrank ≤ n`;
* `dim A' = ht 𝔪' ≥ n` by a chain of `n + 1` primes of `R'` ending at `𝔪'`: with `x'` the regular
  system of parameters obtained from `x` by moving `x_r` to the last place, the ideals
  `Qⱼ = ⟨x'₀, …, x'_{j-1}⟩`, `j ≤ n − 1`, are primes of `R` not containing `x_r`
  (`Hironaka/Algebra/Local/RegularSystem.lean`), so they extend to primes of `R[1/x_r]` and contract
  to primes `𝔮ⱼ` of `R' ⊆ R[1/x_r]`, strictly increasing because `x'ⱼ ∈ Q_{j+1} ∖ Qⱼ`, and
  `𝔮_{n-1} ⊊ 𝔪'`: every element of `𝔮_{n-1}` is killed by the map `ψ : R[1/x_r] → Frac(R/Q_{n-1})`
  used for `1 ∉ 𝔪'` in `Hironaka/Algebra/Local/Chart.lean`, which characterizes `𝔪'` inside `R'` as
  the preimage of the maximal ideal of `R/Q_{n-1}` (`R' = R + 𝔪'` and `𝔪' ∩ R = 𝔪`), while
  `x_r ∈ 𝔪' ∖ 𝔮_{n-1}`.
* `spanFinrank 𝔪'A' ≤ n ≤ dim A'` and Krull's height theorem give regularity
  (`IsRegularLocalRing.of_spanFinrank_maximalIdeal_le`) and `dim A' = n`.
-/

@[expose] public section

namespace IsLocalRing

open IsLocalRing

section ChartLocal

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] {n : ℕ} (x : Fin n → R) (r : Fin n)

/-- `R'` is Noetherian: a quotient of the Noetherian ring `R[Y₀, …, Y_{r-1}]`. -/
theorem isNoetherianRing_chartRing : IsNoetherianRing (chartRing x r) :=
  isNoetherianRing_of_surjective (MvPolynomial (Fin r) R) (chartRing x r)
    (chartPresentation x r).toRingHom (chartPresentation_surjective x r)

omit [IsRegularLocalRing R] in
/-- The maximal ideal of `R'_{𝔪'}` is generated by the images of the `yᵢ`. -/
theorem maximalIdeal_localization_chartOrigin [(chartOrigin x r).IsPrime] :
    maximalIdeal (Localization.AtPrime (chartOrigin x r)) =
      Ideal.span (Set.range fun i =>
        algebraMap (chartRing x r) (Localization.AtPrime (chartOrigin x r)) (chartYR x r i)) := by
  refine (Localization.AtPrime.map_eq_maximalIdeal).symm.trans ?_
  change Ideal.map _ (Ideal.span (Set.range (chartYR x r))) = _
  rw [Ideal.map_span, ← Set.range_comp]
  rfl

omit [IsRegularLocalRing R] in
theorem spanFinrank_maximalIdeal_localization_chartOrigin_le [(chartOrigin x r).IsPrime] :
    (maximalIdeal (Localization.AtPrime (chartOrigin x r))).spanFinrank ≤ n := by
  rw [maximalIdeal_localization_chartOrigin x r]
  refine le_trans (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)) ?_
  rw [← Set.image_univ]
  exact le_trans (Set.ncard_image_le Set.finite_univ)
    (by rw [Set.ncard_univ, Nat.card_eq_fintype_card, Fintype.card_fin])

/-! ### The chain of primes below the origin -/

/-- The last index `n - 1` (`Fin n` is nonempty since `r : Fin n`). -/
abbrev lastIdx (r : Fin n) : Fin n := ⟨n - 1, by have := r.2; omega⟩

/-- The regular system of parameters with `x_r` moved to the last position. -/
noncomputable abbrev swapLast : Fin n → R :=
  x ∘ Equiv.swap r (lastIdx r)

omit [CommRing R] [IsRegularLocalRing R] in
theorem swapLast_last : swapLast x r (lastIdx r) = x r := by
  simp [swapLast]

theorem span_range_swapLast (hx : maximalIdeal R = Ideal.span (Set.range x)) :
    maximalIdeal R = Ideal.span (Set.range (swapLast x r)) := by
  rw [hx, swapLast, (Equiv.swap _ _).surjective.range_comp]

/-- `Qⱼ = ⟨x'₀, …, x'_{j-1}⟩`, a prime of `R` not containing `x_r` for `j ≤ n − 1`. -/
noncomputable abbrev swapPrime (j : ℕ) : Ideal R :=
  Ideal.span (swapLast x r '' {i : Fin n | i.val < j})

theorem swapPrime_isPrime (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (j : ℕ) : (swapPrime x r j).IsPrime :=
  isPrime_span_image_lt (swapLast x r) (span_range_swapLast x r hx) hn j

omit [IsRegularLocalRing R] in
theorem swapPrime_mono {j j' : ℕ} (h : j ≤ j') : swapPrime x r j ≤ swapPrime x r j' :=
  Ideal.span_mono (Set.image_mono fun _ hi => lt_of_lt_of_le hi h)

theorem x_notMem_swapPrime (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {j : ℕ} (hj : j ≤ n - 1) : x r ∉ swapPrime x r j := by
  intro h
  have h1 := swapPrime_mono x r hj h
  rw [← swapLast_last x r] at h1
  exact notMem_span_image_lt (swapLast x r) (span_range_swapLast x r hx) hn
    (i := n - 1) (by have := r.2; omega) h1

omit [IsRegularLocalRing R] in
theorem swapLast_mem_swapPrime_succ (j : ℕ) (hj : j < n) :
    swapLast x r ⟨j, hj⟩ ∈ swapPrime x r (j + 1) :=
  Ideal.subset_span ⟨⟨j, hj⟩, Nat.lt_succ_self _, rfl⟩

theorem swapLast_notMem_swapPrime (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (j : ℕ) (hj : j < n) :
    swapLast x r ⟨j, hj⟩ ∉ swapPrime x r j :=
  notMem_span_image_lt (swapLast x r) (span_range_swapLast x r hx) hn hj

theorem disjoint_powers_swapPrime (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {j : ℕ} (hj : j ≤ n - 1) :
    Disjoint (Submonoid.powers (x r) : Set R) (swapPrime x r j : Set R) := by
  rw [Set.disjoint_left]
  rintro y ⟨k, rfl⟩ hy
  exact x_notMem_swapPrime x r hx hn hj
    ((swapPrime_isPrime x r hx hn j).mem_of_pow_mem k hy)

/-- The prime `𝔮ⱼ` of `R'`: the contraction of `Qⱼ R[1/x_r]`. -/
noncomputable abbrev chartPrime (j : ℕ) : Ideal (chartRing x r) :=
  ((swapPrime x r j).map (algebraMap R (Localization.Away (x r)))).comap
    ((chartRing x r).val : chartRing x r →+* Localization.Away (x r))

theorem chartPrime_isPrime (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {j : ℕ} (hj : j ≤ n - 1) :
    (chartPrime x r j).IsPrime := by
  have := IsLocalization.isPrime_of_isPrime_disjoint (Submonoid.powers (x r))
    (Localization.Away (x r)) (swapPrime x r j) (swapPrime_isPrime x r hx hn j)
    (disjoint_powers_swapPrime x r hx hn hj)
  exact Ideal.IsPrime.comap _

omit [IsRegularLocalRing R] in
theorem chartPrime_mono {j j' : ℕ} (h : j ≤ j') : chartPrime x r j ≤ chartPrime x r j' :=
  Ideal.comap_mono (Ideal.map_mono (swapPrime_mono x r h))

theorem algebraMap_mem_chartPrime_iff (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {j : ℕ} (hj : j ≤ n - 1) (a : R) :
    algebraMap R (chartRing x r) a ∈ chartPrime x r j ↔ a ∈ swapPrime x r j := by
  rw [chartPrime, Ideal.mem_comap]
  change a ∈ Ideal.under R ((swapPrime x r j).map (algebraMap R (Localization.Away (x r)))) ↔ _
  rw [IsLocalization.under_map_of_isPrime_disjoint (Submonoid.powers (x r))
    (Localization.Away (x r)) (swapPrime_isPrime x r hx hn j)
    (disjoint_powers_swapPrime x r hx hn hj)]

theorem chartPrime_lt_succ (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {j : ℕ} (hj : j + 1 ≤ n - 1) :
    chartPrime x r j < chartPrime x r (j + 1) := by
  refine lt_of_le_of_ne (chartPrime_mono x r (Nat.le_succ j)) fun heq => ?_
  have hjn : j < n := by omega
  have hmem : algebraMap R (chartRing x r) (swapLast x r ⟨j, hjn⟩) ∈ chartPrime x r (j + 1) :=
    (algebraMap_mem_chartPrime_iff x r hx hn hj _).mpr (swapLast_mem_swapPrime_succ x r j hjn)
  rw [← heq, algebraMap_mem_chartPrime_iff x r hx hn (by omega)] at hmem
  exact swapLast_notMem_swapPrime x r hx hn j hjn hmem

/-! ### `𝔮_{n-1} ⊊ 𝔪'`, through the fraction field of `R/Q_{n-1}` -/

theorem chartPrime_le_chartOrigin (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) :
    chartPrime x r (n - 1) ≤ chartOrigin x r := by
  classical
  intro z hz
  set x' := swapLast x r with hx'def
  have hx' : maximalIdeal R = Ideal.span (Set.range x') := span_range_swapLast x r hx
  set Q : Ideal R := swapPrime x r (n - 1) with hQ
  have hQle : Q ≤ maximalIdeal R := by
    rw [hx']
    exact Ideal.span_mono (Set.image_subset_range _ _)
  have hS : IsRegularLocalRing (R ⧸ Q) :=
    isRegularLocalRing_quotient_span_image_lt x' hx' hn (n - 1)
  set S := R ⧸ Q with hSdef
  let F := FractionRing S
  let g : R →+* F := (algebraMap S F).comp (Ideal.Quotient.mk Q)
  have hinj : Function.Injective (algebraMap S F) := IsFractionRing.injective S F
  have hg : IsUnit (g (x r)) := by
    rw [isUnit_iff_ne_zero]
    intro h0
    apply x_notMem_swapPrime x r hx hn le_rfl
    rw [← Ideal.Quotient.eq_zero_iff_mem]
    exact hinj (by rw [map_zero]; exact h0)
  let ψ : Localization.Away (x r) →+* F := IsLocalization.Away.lift (x r) hg
  have hψ : ∀ a, ψ (algebraMap R _ a) = g a := fun a => IsLocalization.Away.lift_eq (x r) hg a
  have hmk : ∀ i, Ideal.Quotient.mk Q (x i) ∈ maximalIdeal S := fun i => by
    rw [maximalIdeal_quotient_eq_map]
    exact Ideal.mem_map_of_mem _ (x_mem_maximalIdeal_of_span_eq x hx i)
  have hmemQ : ∀ i, i ≠ r → x i ∈ Q := by
    intro i hi
    refine Ideal.subset_span
      ⟨Equiv.swap r (lastIdx r) i, ?_, congrArg x (Equiv.swap_apply_self _ _ _)⟩
    have hne : Equiv.swap r (lastIdx r) i ≠ lastIdx r := by
      intro h
      apply hi
      have := congrArg (Equiv.swap r (lastIdx r)) h
      rwa [Equiv.swap_apply_self, Equiv.swap_apply_right] at this
    have h2 := (Equiv.swap r (lastIdx r) i).2
    have h3 : (Equiv.swap r (lastIdx r) i).val ≠ n - 1 := fun h => hne (Fin.ext h)
    change (Equiv.swap r (lastIdx r) i).val < n - 1
    omega
  have hy : ∀ i, ψ (chartY x r i) ∈ algebraMap S F '' (maximalIdeal S : Set S) := by
    intro i
    by_cases hi : i < r
    · rw [chartY_of_lt x r hi, map_mul, hψ]
      have : g (x i) = 0 := by
        change algebraMap S F (Ideal.Quotient.mk Q (x i)) = 0
        rw [Ideal.Quotient.eq_zero_iff_mem.mpr (hmemQ i hi.ne), map_zero]
      rw [this, zero_mul]
      exact ⟨0, zero_mem _, map_zero _⟩
    · rw [chartY_eq_algebraMap_of_not_lt x r hi, hψ]
      exact ⟨Ideal.Quotient.mk Q (x i), hmk i, rfl⟩
  have hR' : ∀ w ∈ chartRing x r, ψ w ∈ Set.range (algebraMap S F) := by
    intro w hw
    refine Algebra.adjoin_induction (p := fun w _ => ψ w ∈ Set.range (algebraMap S F))
      ?_ ?_ ?_ ?_ hw
    · rintro _ ⟨i, hi, rfl⟩
      have hi' : i < r := hi
      obtain ⟨s, -, hs⟩ := hy i
      rw [chartY_eq_mk_of_lt x r hi'] at hs
      exact ⟨s, hs⟩
    · intro a
      exact ⟨Ideal.Quotient.mk Q a, (hψ a).symm⟩
    · rintro w v _ _ ⟨s, hs⟩ ⟨t, ht⟩
      exact ⟨s + t, by rw [map_add, map_add, hs, ht]⟩
    · rintro w v _ _ ⟨s, hs⟩ ⟨t, ht⟩
      exact ⟨s * t, by rw [map_mul, map_mul, hs, ht]⟩
  have hM : ∀ w ∈ chartOrigin x r,
      ψ (w : Localization.Away (x r)) ∈ algebraMap S F '' (maximalIdeal S : Set S) := by
    intro w hw
    refine Submodule.span_induction
      (p := fun (w : chartRing x r) _ =>
        ψ (w : Localization.Away (x r)) ∈ algebraMap S F '' (maximalIdeal S : Set S))
      ?_ ?_ ?_ ?_ hw
    · rintro _ ⟨i, rfl⟩
      exact hy i
    · exact ⟨0, zero_mem _, by rw [Subalgebra.coe_zero, map_zero, map_zero]⟩
    · rintro w v _ _ ⟨s, hs, hs'⟩ ⟨t, ht, ht'⟩
      exact ⟨s + t, add_mem hs ht, by rw [map_add, Subalgebra.coe_add, map_add, hs', ht']⟩
    · rintro b w _ ⟨s, hs, hs'⟩
      obtain ⟨t, ht⟩ := hR' b b.2
      exact ⟨t * s, Ideal.mul_mem_left _ _ hs,
        by rw [map_mul, smul_eq_mul, Subalgebra.coe_mul, map_mul, ht, hs']⟩
  -- `ψ z = 0` because `z` is a fraction over `Q`
  have hz0 : ψ (z : Localization.Away (x r)) = 0 := by
    have hz' : (z : Localization.Away (x r)) ∈ Q.map (algebraMap R (Localization.Away (x r))) := hz
    rw [IsLocalization.mem_map_algebraMap_iff (Submonoid.powers (x r))] at hz'
    obtain ⟨⟨q, s⟩, hqs⟩ := hz'
    dsimp only at hqs
    have h1 := congrArg ψ hqs
    rw [map_mul, hψ, hψ] at h1
    have hq0 : g q = 0 := by
      change algebraMap S F (Ideal.Quotient.mk Q q) = 0
      rw [Ideal.Quotient.eq_zero_iff_mem.mpr q.2, map_zero]
    obtain ⟨k, hk⟩ := s.2
    have hsu : IsUnit (g s) := by
      rw [show (s : R) = x r ^ k from hk.symm, map_pow]
      exact hg.pow k
    rw [hq0] at h1
    exact (hsu.mul_left_eq_zero).mp h1
  -- `z ≡ a (mod 𝔪')` with `a ∈ R`, and then `a ∈ 𝔪`
  obtain ⟨a, ha⟩ := exists_algebraMap_sub_mem_chartOriginOf x r (x r) z
  obtain ⟨t, ht, ht'⟩ := hM _ ha
  rw [Subalgebra.coe_sub, map_sub, hz0, zero_sub, Subalgebra.coe_algebraMap, hψ] at ht'
  have hta : Ideal.Quotient.mk Q a = -t := by
    apply hinj
    rw [map_neg, ht', neg_neg]
    rfl
  have hmem : a ∈ maximalIdeal R := by
    have h1 : Ideal.Quotient.mk Q a ∈ maximalIdeal S := by
      rw [hta]; exact neg_mem ht
    rw [maximalIdeal_quotient_eq_map, ← Ideal.mem_comap, Ideal.comap_map_of_surjective _
      Ideal.Quotient.mk_surjective, ← RingHom.ker_eq_comap_bot, Ideal.mk_ker,
      sup_eq_left.mpr hQle] at h1
    exact h1
  have h2 : algebraMap R (chartRing x r) a ∈ chartOrigin x r :=
    maximalIdeal_le_comap_chartOrigin x r hx hmem
  have : z = (z - algebraMap R (chartRing x r) a) + algebraMap R (chartRing x r) a := by ring
  rw [this]
  exact add_mem ha h2

theorem chartPrime_lt_chartOrigin (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) :
    chartPrime x r (n - 1) < chartOrigin x r := by
  refine lt_of_le_of_ne (chartPrime_le_chartOrigin x r hx hn) fun heq => ?_
  have := algebraMap_x_mem_chartOrigin x r r
  rw [← heq, algebraMap_mem_chartPrime_iff x r hx hn le_rfl] at this
  exact x_notMem_swapPrime x r hx hn le_rfl this

/-! ### Regularity and dimension -/

/-- The chain `𝔮₀ ⊊ ⋯ ⊊ 𝔮_{n-1} ⊊ 𝔪'` as a function on `Fin (n + 1)`. -/
noncomputable def chartChain (i : ℕ) : Ideal (chartRing x r) :=
  if i < n then chartPrime x r i else chartOrigin x r

theorem chartChain_isPrime (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (i : ℕ) : (chartChain x r i).IsPrime := by
  unfold chartChain
  split_ifs with h
  · exact chartPrime_isPrime x r hx hn (by omega)
  · exact (chartOrigin_isMaximal x r hx hn).isPrime

theorem chartChain_lt_succ (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {i : ℕ} (hi : i < n) :
    chartChain x r i < chartChain x r (i + 1) := by
  unfold chartChain
  rw [ite_eq_left hi]
  split_ifs with h
  · exact chartPrime_lt_succ x r hx hn (by omega)
  · have : i = n - 1 := by omega
    subst this
    exact chartPrime_lt_chartOrigin x r hx hn

/-- `ht 𝔪' ≥ n`. -/
theorem natCast_le_height_chartOrigin (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) : (n : ℕ∞) ≤ (chartOrigin x r).height := by
  have hP := (chartOrigin_isMaximal x r hx hn).isPrime
  let chain : LTSeries (PrimeSpectrum (chartRing x r)) := LTSeries.mk n
    (fun i : Fin (n + 1) => ⟨chartChain x r i, chartChain_isPrime x r hx hn i⟩)
    (Fin.strictMono_iff_lt_succ.mpr fun i => by
      rw [← PrimeSpectrum.asIdeal_lt_asIdeal]
      exact chartChain_lt_succ x r hx hn i.2)
  have hlast : chain.last ≤ ⟨chartOrigin x r, hP⟩ := by
    change (⟨chartChain x r (Fin.last n : ℕ), _⟩ : PrimeSpectrum (chartRing x r)) ≤ _
    rw [← PrimeSpectrum.asIdeal_le_asIdeal]
    change chartChain x r n ≤ chartOrigin x r
    unfold chartChain
    rw [ite_eq_right (lt_irrefl n)]
  have h := Order.length_le_height hlast
  rw [PrimeSpectrum.height_eq_orderHeight ⟨_, hP⟩]
  exact h

theorem natCast_le_ringKrullDim_localization_chartOrigin
    (hx : maximalIdeal R = Ideal.span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    [(chartOrigin x r).IsPrime] :
    (n : WithBot ℕ∞) ≤ ringKrullDim (Localization.AtPrime (chartOrigin x r)) := by
  rw [IsLocalization.AtPrime.ringKrullDim_eq_height (chartOrigin x r)
    (Localization.AtPrime (chartOrigin x r)), ← WithBot.coe_natCast, WithBot.coe_le_coe]
  exact natCast_le_height_chartOrigin x r hx hn

/-- `R'_{𝔪'}` is a regular local ring: the `yᵢ` are local coordinates on the chart
[Kol07, Definition 60]. -/
theorem isRegularLocalRing_localization_chartOrigin
    (hx : maximalIdeal R = Ideal.span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    [(chartOrigin x r).IsPrime] : IsRegularLocalRing (Localization.AtPrime (chartOrigin x r)) := by
  have := isNoetherianRing_chartRing x r
  exact IsRegularLocalRing.of_spanFinrank_maximalIdeal_le (Localization.AtPrime (chartOrigin x r))
    (le_trans (Nat.cast_le.mpr (spanFinrank_maximalIdeal_localization_chartOrigin_le x r))
      (natCast_le_ringKrullDim_localization_chartOrigin x r hx hn))

/-- `dim R'_{𝔪'} = n`. -/
theorem ringKrullDim_localization_chartOrigin
    (hx : maximalIdeal R = Ideal.span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    [(chartOrigin x r).IsPrime] : ringKrullDim (Localization.AtPrime (chartOrigin x r)) = n := by
  have := isRegularLocalRing_localization_chartOrigin x r hx hn
  refine le_antisymm ?_ (natCast_le_ringKrullDim_localization_chartOrigin x r hx hn)
  rw [← IsRegularLocalRing.spanFinrank_maximalIdeal]
  exact Nat.cast_le.mpr (spanFinrank_maximalIdeal_localization_chartOrigin_le x r)

end ChartLocal

end IsLocalRing
