/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.BirationalTransform
public import Hironaka.Algebra.Local.Order
import Hironaka.Algebra.Local.Chart
import Hironaka.Algebra.Local.ChartPresentation
import Hironaka.Algebra.Local.Regular
import Hironaka.Algebra.Local.Transform
import Hironaka.Algebra.Local.TransformOrder
import Mathlib.Combinatorics.Matroid.Init

/-!
# The exceptional divisor of the chart at the generic point

Let `R` be a regular local ring with a regular system of parameters `x : Fin n → R` (`𝔪 = (x)`,
`n = dim R`), and let `r` be the **last** index (`r + 1 = n`), so that the centre
`P = (x₀, …, x_r)` is `𝔪` itself and the chart ring `R' = R[xᵢ/x_r : i < r]` is the chart dividing
by `x_r` of the blow-up of the closed point. Geometrically this is the local blow-up of a smooth
variety at the generic point of a smooth centre `Z`, in coordinates adapted to `Z`. In this chart:

* an element `f` of order exactly `m` is `∑_{|α| = m} c_α x^α` with some coefficient a unit
  (`exists_leading_form`, `exists_sum_monomials_unit_coeff`); the monomials of degree `m` span
  `𝔪ᵐ` (`span_range_pow_eq_span_monomials`), and those in `x₀, …, x_r` span `Pᵐ`
  (`span_image_pow_eq_span_monomials`);
* `R'/(x_r) ≅ κ[Yᵢ : i < r]` with `κ = R/𝔪` (`exists_quotient_span_algebraMap_x_ringEquiv`), from
  the presentation `R' = R[Y]/(x_r Yᵢ − xᵢ)` of `Hironaka/Algebra/Local/ChartPresentation.lean` and
  `(x_r Yᵢ − xᵢ, x_r) = 𝔪 R[Y]`; so `(x_r)` is a prime of `R'` (`isPrime_span_algebraMap_x`), the
  generic point of the exceptional divisor of the chart, and for `f` of order `m`,
  `f = x_rᵐ (∑ c_α y^{α'} + x_r(…))` in `R'` does not lie in `(x_r)^{m+1}`
  (`algebraMap_notMem_span_pow_succ`);
* the order of `I R'` along the prime `(x_r)`, that is, in the discrete valuation ring
  `R'_{(x_r)}`, equals `ord I` (`ordAlong_span_algebraMap_x_map`). This is the remark after
  [Kol07, Definition 47] that `ord_Z I` equals the multiplicity of `π^* I` along the exceptional
  divisor, and the definition of the strict transform of an ideal in [Hau14, §6] (following
  Definition 6.2), where the maximal exponent `k` in `f^* = h^k f^s` is the order of `f^*` along
  the exceptional divisor.

The computation of the leading form in the divided coordinates is that of the proof of
[Kol07, Lemma 61]: for `f ∈ Pᵐ` of order exactly `m`, `f / x_rᵐ = Q(y)` for a polynomial `Q` of
degree `≤ m` with a coefficient outside `𝔪` (`exists_transformElem_eq_chartPresentation`).

Several statements are also proved for a partial centre `P = (x₀, …, x_r)` with `r` not the last
index: `(x_r Yᵢ − xᵢ, x_r) = P R[Y]` (`chartRelations_sup_span_C_eq_map_C_chartCenter`),
`R'/(x_r) ≅ (R/P)[Yᵢ : i < r]` (`exists_quotient_span_algebraMap_x_ringEquiv_chartCenter`), `(x_r)`
is prime in `R'` (`isPrime_span_algebraMap_x_of_chartCenter`) and `(x_r) ∩ R = P`
(`comap_span_algebraMap_x_eq_chartCenter`); and the fibre of the chart over the closed point is
`R'/𝔪R' ≅ κ[Yᵢ : i < r]` for every `r` (`exists_quotient_map_maximalIdeal_ringEquiv`).

Used for the order of the transform at every point of the fibre
(`Hironaka/Algebra/Local/ChartFibre.lean`), for the order along the exceptional divisor
(`Hironaka/Scheme/IdealSheaf/Order/ExceptionalOrder.lean`,
`Hironaka/Scheme/BlowUpSequence/OrderAlongCenter.lean`,
`Hironaka/Resolution/Algebraic/Wlo05/EmbeddedCP3Exceptional.lean`), for the strict transform of a
hypersurface of maximal contact (`Hironaka/Resolution/Algebraic/MaximalContact/Transform.lean`) and
on manifolds (`Hironaka/Resolution/Analytic/OrderReduction/BMO/Step1Purity.lean`).
-/

@[expose] public section

universe u

namespace IsLocalRing

open IsLocalRing MvPolynomial

variable {R : Type u} [CommRing R] [IsRegularLocalRing R] {n : ℕ} (x : Fin n → R)

/-! ### Leading forms -/

section LeadingForm

omit [IsRegularLocalRing R] in
/-- Monomials are multiplicative in the exponent. -/
theorem prod_pow_add (α β : Fin n →₀ ℕ) :
    ∏ j, x j ^ (α + β) j = (∏ j, x j ^ α j) * ∏ j, x j ^ β j := by
  simp only [Finsupp.add_apply, pow_add, Finset.prod_mul_distrib]

omit [IsRegularLocalRing R] in
/-- The monomial of the exponent `single i 1` is `x_i`. -/
theorem prod_pow_single (i : Fin n) : ∏ j, x j ^ (Finsupp.single i 1) j = x i := by
  rw [Finset.prod_eq_single i (fun j _ hj => by rw [Finsupp.single_eq_of_ne hj, pow_zero])
    (fun h => absurd (Finset.mem_univ i) h)]
  rw [Finsupp.single_eq_same, pow_one]

omit [IsRegularLocalRing R] in
/-- The `m`-th power of the ideal generated by the `xᵢ`, `i ∈ s`, is spanned by the monomials of
degree `m` in those `xᵢ` (applied to the powers of the centre `P = (x₀, …, x_r)`). -/
theorem span_image_pow_eq_span_monomials (s : Set (Fin n)) (m : ℕ) :
    Ideal.span (x '' s) ^ m =
      Ideal.span {z : R | ∃ α : Fin n →₀ ℕ, (α.degree = m ∧ ∀ i, i ∉ s → α i = 0) ∧
        z = ∏ i, x i ^ α i} := by
  classical
  induction m with
  | zero =>
    rw [pow_zero, Ideal.one_eq_top]
    have h1 : ∃ α : Fin n →₀ ℕ, (α.degree = 0 ∧ ∀ i, i ∉ s → α i = 0) ∧
        (1 : R) = ∏ i, x i ^ α i := ⟨0, ⟨by simp, fun _ _ => rfl⟩, by simp⟩
    exact ((Ideal.eq_top_iff_one _).mpr (Ideal.subset_span h1)).symm
  | succ m ih =>
    rw [pow_succ, ih, Ideal.span_mul_span']
    refine le_antisymm (Ideal.span_le.mpr ?_) (Ideal.span_le.mpr ?_)
    · rintro _ ⟨a, ⟨α, ⟨hα, hs⟩, rfl⟩, b, ⟨i, hi, rfl⟩, rfl⟩
      refine Ideal.subset_span ⟨α + Finsupp.single i 1, ⟨?_, ?_⟩, ?_⟩
      · rw [map_add, hα, Finsupp.degree_single]
      · intro j hj
        rw [Finsupp.add_apply, hs j hj, Finsupp.single_apply, if_neg (fun h : i = j => hj (h ▸ hi))]
        rfl
      · rw [prod_pow_add, prod_pow_single]
    · rintro _ ⟨α, ⟨hα, hs⟩, rfl⟩
      have hne : α ≠ 0 := by
        rintro rfl
        simp at hα
      obtain ⟨i, hi⟩ := Finsupp.support_nonempty_iff.mpr hne
      have hi0 : α i ≠ 0 := Finsupp.mem_support_iff.mp hi
      have his : i ∈ s := by
        by_contra h
        exact hi0 (hs i h)
      have hi1 : 1 ≤ α i := Nat.one_le_iff_ne_zero.mpr hi0
      have hle : Finsupp.single i 1 ≤ α := Finsupp.single_le_iff.mpr hi1
      have hsplit : α = (α - Finsupp.single i 1 : Fin n →₀ ℕ) + Finsupp.single i 1 :=
        (tsub_add_cancel_of_le hle).symm
      have hdeg : (α - Finsupp.single i 1 : Fin n →₀ ℕ).degree = m := by
        have := congrArg Finsupp.degree hsplit
        rw [map_add, Finsupp.degree_single, hα] at this
        omega
      have hs' : ∀ j, j ∉ s → (α - Finsupp.single i 1 : Fin n →₀ ℕ) j = 0 := fun j hj => by
        rw [Finsupp.tsub_apply, hs j hj, Nat.zero_sub]
      have hprod : ∏ j, x j ^ α j =
          (∏ j, x j ^ (α - Finsupp.single i 1 : Fin n →₀ ℕ) j) * x i := by
        conv_lhs => rw [hsplit]
        rw [prod_pow_add, prod_pow_single]
      rw [hprod]
      exact Ideal.subset_span (Set.mul_mem_mul ⟨_, ⟨hdeg, hs'⟩, rfl⟩ ⟨i, his, rfl⟩)

omit [IsRegularLocalRing R] in
/-- The `m`-th power of the ideal generated by `x` is spanned by the monomials of degree `m` in
the `x_i`. -/
theorem span_range_pow_eq_span_monomials (m : ℕ) :
    Ideal.span (Set.range x) ^ m =
      Ideal.span {z : R | ∃ α : Fin n →₀ ℕ, α.degree = m ∧ z = ∏ i, x i ^ α i} := by
  rw [← Set.image_univ, span_image_pow_eq_span_monomials]
  congr 1
  ext z
  simp

omit [IsRegularLocalRing R] in
/-- Every element of the span of the monomials with exponents satisfying `p` is a finite
combination of them. -/
theorem exists_sum_monomials_of_mem_span {p : (Fin n →₀ ℕ) → Prop} {f : R}
    (hf : f ∈ Ideal.span {z : R | ∃ α : Fin n →₀ ℕ, p α ∧ z = ∏ i, x i ^ α i}) :
    ∃ (S : Finset (Fin n →₀ ℕ)) (c : (Fin n →₀ ℕ) → R),
      (∀ α ∈ S, p α) ∧ f = ∑ α ∈ S, c α * ∏ i, x i ^ α i := by
  classical
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hf
  · rintro _ ⟨α, hα, rfl⟩
    exact ⟨{α}, fun _ => 1, by simpa using hα, by simp⟩
  · exact ⟨∅, fun _ => 0, by simp, by simp⟩
  · rintro f g - - ⟨S, c, hS, rfl⟩ ⟨T, d, hT, rfl⟩
    refine ⟨S ∪ T, fun α => (if α ∈ S then c α else 0) + (if α ∈ T then d α else 0), ?_, ?_⟩
    · intro α hα
      rcases Finset.mem_union.mp hα with h | h
      · exact hS α h
      · exact hT α h
    · simp only [add_mul, Finset.sum_add_distrib]
      congr 1
      · rw [← Finset.sum_subset Finset.subset_union_left
          (f := fun α => (if α ∈ S then c α else 0) * ∏ i, x i ^ α i)
          (fun α _ hα => by simp [hα])]
        exact Finset.sum_congr rfl fun α hα => by simp [hα]
      · rw [← Finset.sum_subset Finset.subset_union_right
          (f := fun α => (if α ∈ T then d α else 0) * ∏ i, x i ^ α i)
          (fun α _ hα => by simp [hα])]
        exact Finset.sum_congr rfl fun α hα => by simp [hα]
  · rintro a f - ⟨S, c, hS, rfl⟩
    exact ⟨S, fun α => a * c α, hS, by simp [Finset.mul_sum, mul_assoc]⟩

variable (hx : maximalIdeal R = Ideal.span (Set.range x))
include hx

/-- If every coefficient of a combination of degree-`m` monomials lies in `𝔪`, the element lies in
`𝔪^{m+1}`; so a combination of order exactly `m` has a coefficient outside `𝔪`. -/
theorem exists_coeff_notMem_of_ordElem_eq {m : ℕ} {S : Finset (Fin n →₀ ℕ)}
    {c : (Fin n →₀ ℕ) → R} (hS : ∀ α ∈ S, α.degree = m) {f : R}
    (hfeq : f = ∑ α ∈ S, c α * ∏ i, x i ^ α i) (hf : ordElem f = m) :
    ∃ α ∈ S, c α ∉ maximalIdeal R := by
  by_contra hcon
  simp only [not_exists, not_and, not_not] at hcon
  have hmem : f ∈ maximalIdeal R ^ (m + 1) := by
    rw [hfeq]
    refine Ideal.sum_mem _ fun α hα => ?_
    rw [pow_succ']
    refine Ideal.mul_mem_mul (hcon α hα) ?_
    rw [hx, span_range_pow_eq_span_monomials]
    exact Ideal.subset_span ⟨α, hS α hα, rfl⟩
  have := mem_maximalIdeal_pow_iff_le_ordElem.mp hmem
  rw [hf] at this
  exact absurd this (by exact_mod_cast Nat.not_succ_le_self m)

/-- An element of order exactly `m` is a combination of degree-`m` monomials with some
coefficient a unit. -/
theorem exists_sum_monomials_unit_coeff (f : R) (m : ℕ) (hf : ordElem f = m) :
    ∃ (S : Finset (Fin n →₀ ℕ)) (c : (Fin n →₀ ℕ) → R),
      (∀ α ∈ S, α.degree = m) ∧ f = ∑ α ∈ S, c α * ∏ i, x i ^ α i ∧
        ∃ α ∈ S, c α ∉ maximalIdeal R := by
  have hfm : f ∈ maximalIdeal R ^ m := mem_maximalIdeal_pow_iff_le_ordElem.mpr (by rw [hf])
  rw [hx, span_range_pow_eq_span_monomials] at hfm
  obtain ⟨S, c, hS, rfl⟩ := exists_sum_monomials_of_mem_span x hfm
  exact ⟨S, c, hS, rfl, exists_coeff_notMem_of_ordElem_eq x hx hS rfl hf⟩

/-- (The proof of [Kol07, Lemma 61].) An element of `Pᵐ = (x₀, …, x_r)ᵐ` of order exactly `m` is
a combination of degree-`m` monomials in `x₀, …, x_r` with some coefficient a unit. -/
theorem exists_sum_monomials_unit_coeff_of_mem_chartCenter_pow (r : Fin n) {f : R} {m : ℕ}
    (hf : f ∈ chartCenter x r ^ m) (hord : ordElem f = m) :
    ∃ (S : Finset (Fin n →₀ ℕ)) (c : (Fin n →₀ ℕ) → R),
      (∀ α ∈ S, α.degree = m ∧ ∀ i, r < i → α i = 0) ∧
        f = ∑ α ∈ S, c α * ∏ i, x i ^ α i ∧ ∃ α ∈ S, c α ∉ maximalIdeal R := by
  rw [chartCenter, span_image_pow_eq_span_monomials] at hf
  obtain ⟨S, c, hS, rfl⟩ := exists_sum_monomials_of_mem_span x hf
  exact ⟨S, c, fun α hα => ⟨(hS α hα).1, fun i hi => (hS α hα).2 i (not_le.mpr hi)⟩, rfl,
    exists_coeff_notMem_of_ordElem_eq x hx (fun α hα => (hS α hα).1) rfl hord⟩

/-- An element `f` of order exactly `m` of a regular local ring with regular system of parameters
`x` is `∑_{|α| = m} c_α x^α + g` with `g ∈ 𝔪^{m+1}` (in fact `g = 0` here) and some coefficient
`c_α` a unit: its leading form is a nonzero form of degree `m`. -/
theorem exists_leading_form (f : R) (m : ℕ) (hf : ordElem f = m) :
    ∃ (S : Finset (Fin n →₀ ℕ)) (c : (Fin n →₀ ℕ) → R) (g : R),
      (∀ α ∈ S, α.degree = m) ∧ f = ∑ α ∈ S, c α * ∏ i, x i ^ α i + g ∧
        g ∈ maximalIdeal R ^ (m + 1) ∧ ∃ α ∈ S, c α ∉ maximalIdeal R := by
  obtain ⟨S, c, hS, hfeq, hunit⟩ := exists_sum_monomials_unit_coeff x hx f m hf
  exact ⟨S, c, 0, hS, by rw [add_zero]; exact hfeq, zero_mem _, hunit⟩

end LeadingForm

/-! ### The exceptional divisor of the chart is affine space over the residue field -/

section Quotient

variable (hx : maximalIdeal R = Ideal.span (Set.range x))
  (hn : (n : WithBot ℕ∞) = ringKrullDim R) (r : Fin n) (hr : r.val + 1 = n)

include hr in
/-- Every index other than the last one is `Fin.castLE` of an index below `r`. -/
theorem exists_castLE_eq_of_ne {j : Fin n} (hj : j ≠ r) : ∃ i : Fin r, Fin.castLE r.2.le i = j := by
  have hlt : j.val < r.val := by
    have := j.2
    have hne : j.val ≠ r.val := fun h => hj (Fin.ext h)
    omega
  exact ⟨⟨j.val, hlt⟩, Fin.ext rfl⟩

include hx hr in
/-- The relations of the presentation together with `x_r` generate `𝔪 R[Y]`: `(x_r Y_i − x_i, x_r)
= (x_0, …, x_r) R[Y]`. -/
theorem chartRelations_sup_span_C_eq_map_C_maximalIdeal :
    chartRelations x r ⊔ Ideal.span {C (x r)} =
      (maximalIdeal R).map (C : R →+* MvPolynomial (Fin r) R) := by
  rw [hx, Ideal.map_span]
  refine le_antisymm (sup_le (Ideal.span_le.mpr ?_) (Ideal.span_le.mpr ?_)) (Ideal.span_le.mpr ?_)
  · rintro _ ⟨i, rfl⟩
    exact Ideal.sub_mem _ (Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨x r, ⟨r, rfl⟩, rfl⟩))
      (Ideal.subset_span ⟨_, ⟨_, rfl⟩, rfl⟩)
  · rintro _ rfl
    exact Ideal.subset_span ⟨x r, ⟨r, rfl⟩, rfl⟩
  · rintro _ ⟨_, ⟨j, rfl⟩, rfl⟩
    by_cases hj : j = r
    · subst hj
      exact Ideal.mem_sup_right (Ideal.subset_span rfl)
    · obtain ⟨i, rfl⟩ := exists_castLE_eq_of_ne r hr hj
      have h1 : C (x r) * X i ∈ chartRelations x r ⊔ Ideal.span {C (x r)} :=
        Ideal.mem_sup_right (Ideal.mul_mem_right _ _ (Ideal.subset_span rfl))
      have h2 : C (x r) * X i - C (x (Fin.castLE r.2.le i)) ∈
          chartRelations x r ⊔ Ideal.span {C (x r)} :=
        Ideal.mem_sup_left (Ideal.subset_span ⟨i, rfl⟩)
      have := Ideal.sub_mem _ h1 h2
      rwa [sub_sub_cancel] at this

include hx hn

omit [IsRegularLocalRing R] hx hn in
/-- For any ideal `P` of `R`: the quotient of the chart ring by the image of an ideal `L ≤ R[Y]`
with `ker ⊔ L = P R[Y]` is `(R/P)[Y]`, with `Yᵢ ↦ yᵢ = xᵢ/x_r` and the constants the classes of `R`,
from the presentation `R' = R[Y]/(x_r Yᵢ − xᵢ)` (`ker_chartPresentation`). -/
theorem exists_quotient_map_ringEquiv_of_sup_eq_map (P : Ideal R)
    (L : Ideal (MvPolynomial (Fin r) R))
    (hsup : RingHom.ker (chartPresentation x r) ⊔ L = P.map (C : R →+* MvPolynomial (Fin r) R)) :
    ∃ e : (chartRing x r ⧸ L.map (chartPresentation x r).toRingHom) ≃+*
        MvPolynomial (Fin r) (R ⧸ P),
      (∀ a : R, e (Ideal.Quotient.mk _ (algebraMap R (chartRing x r) a)) =
          MvPolynomial.C (Ideal.Quotient.mk P a)) ∧
        ∀ i : Fin r, e (Ideal.Quotient.mk _ (chartYR x r (Fin.castLE r.2.le i))) =
          MvPolynomial.X i := by
  classical
  set J : Ideal (chartRing x r) := L.map (chartPresentation x r).toRingHom with hJ
  set K : Ideal (MvPolynomial (Fin r) R) := RingHom.ker (chartPresentation x r) with hK
  let e₁ : (MvPolynomial (Fin r) R ⧸ K) ≃ₐ[R] chartRing x r :=
    Ideal.quotientKerAlgEquivOfSurjective (chartPresentation_surjective x r)
  have he₁ : ∀ p, e₁ (Ideal.Quotient.mk K p) = chartPresentation x r p := fun p =>
    Ideal.quotientKerAlgEquivOfSurjective_mk _ p
  have hPC : ∀ a : R, chartPresentation x r (C a) = algebraMap R (chartRing x r) a := fun a =>
    (chartPresentation x r).commutes a
  have hPX : ∀ i : Fin r, chartPresentation x r (X i) = chartYR x r (Fin.castLE r.2.le i) :=
    fun i => MvPolynomial.aeval_X _ i
  have h1 : ∀ p : MvPolynomial (Fin r) R,
      e₁.symm.toRingEquiv (chartPresentation x r p) = Ideal.Quotient.mk K p := fun p => by
    change e₁.symm (chartPresentation x r p) = _
    rw [← he₁, e₁.symm_apply_apply]
  have hJ' : L.map (Ideal.Quotient.mk K) =
      J.map (e₁.symm.toRingEquiv : chartRing x r →+* MvPolynomial (Fin r) R ⧸ K) := by
    rw [hJ, Ideal.map_map]
    congr 1
    exact RingHom.ext fun p => (h1 p).symm
  -- `R[Y]/PR[Y] ≅ (R/P)[Y]`, as `RingEquiv.ofRingHom` of the two explicit maps whose inverse laws
  -- Mathlib proves (`quotientEquivQuotientMvPolynomial_{left,right}Inverse`); the packaged
  -- `quotientEquivQuotientMvPolynomial` does not compute on classes within the heartbeat limit.
  let φ : MvPolynomial (Fin r) R ⧸ P.map (C : R →+* MvPolynomial (Fin r) R) →+*
      MvPolynomial (Fin r) (R ⧸ P) :=
    Ideal.Quotient.lift _ (MvPolynomial.eval₂Hom (C.comp (Ideal.Quotient.mk P)) X)
      fun _ ha => MvPolynomial.eval₂_C_mk_eq_zero ha
  let ψ : MvPolynomial (Fin r) (R ⧸ P) →+*
      MvPolynomial (Fin r) R ⧸ P.map (C : R →+* MvPolynomial (Fin r) R) :=
    MvPolynomial.eval₂Hom (Ideal.Quotient.lift P ((Ideal.Quotient.mk _).comp C)
      fun _ hi => MvPolynomial.quotient_map_C_eq_zero hi) fun i => Ideal.Quotient.mk _ (X i)
  have hφψ : φ.comp ψ = RingHom.id _ := RingHom.ext fun p =>
    MvPolynomial.quotientEquivQuotientMvPolynomial_rightInverse (σ := Fin r) P p
  have hψφ : ψ.comp φ = RingHom.id _ := RingHom.ext fun p =>
    MvPolynomial.quotientEquivQuotientMvPolynomial_leftInverse (σ := Fin r) P p
  let e₅ : MvPolynomial (Fin r) R ⧸ P.map (C : R →+* MvPolynomial (Fin r) R) ≃+*
      MvPolynomial (Fin r) (R ⧸ P) := RingEquiv.ofRingHom φ ψ hφψ hψφ
  have h5C : ∀ a : R,
      e₅ (Ideal.Quotient.mk (P.map (C : R →+* MvPolynomial (Fin r) R)) (C a)) =
        C (Ideal.Quotient.mk P a) := fun a =>
    (Ideal.Quotient.lift_mk (P.map (C : R →+* MvPolynomial (Fin r) R))
      (MvPolynomial.eval₂Hom (C.comp (Ideal.Quotient.mk P)) X)
      (fun _ ha => MvPolynomial.eval₂_C_mk_eq_zero ha)).trans (MvPolynomial.eval₂Hom_C _ _ _)
  have h5X : ∀ i : Fin r,
      e₅ (Ideal.Quotient.mk (P.map (C : R →+* MvPolynomial (Fin r) R)) (X i)) =
        X i := fun i =>
    (Ideal.Quotient.lift_mk (P.map (C : R →+* MvPolynomial (Fin r) R))
      (MvPolynomial.eval₂Hom (C.comp (Ideal.Quotient.mk P)) X)
      (fun _ ha => MvPolynomial.eval₂_C_mk_eq_zero ha)).trans (MvPolynomial.eval₂Hom_X' _ _ _)
  let e₄ : MvPolynomial (Fin r) R ⧸ (K ⊔ L) ≃+*
      MvPolynomial (Fin r) R ⧸ P.map (C : R →+* MvPolynomial (Fin r) R) :=
    Ideal.quotEquivOfEq hsup
  have h4 : ∀ p : MvPolynomial (Fin r) R, e₄ (Ideal.Quotient.mk _ p) = Ideal.Quotient.mk _ p :=
    fun p => Ideal.quotEquivOfEq_mk hsup p
  refine ⟨((Ideal.quotientEquiv J _ e₁.symm.toRingEquiv hJ').trans
    (DoubleQuot.quotQuotEquivQuotSup K (L))).trans (e₄.trans e₅),
    fun a => ?_, fun i => ?_⟩
  · rw [RingEquiv.trans_apply, RingEquiv.trans_apply, RingEquiv.trans_apply,
      Ideal.quotientEquiv_mk, ← hPC, h1]
    change e₅ (e₄ (DoubleQuot.quotQuotEquivQuotSup K _
      (DoubleQuot.quotQuotMk K (L) (C a)))) = _
    rw [DoubleQuot.quotQuotEquivQuotSup_quotQuotMk, h4]
    exact h5C a
  · rw [RingEquiv.trans_apply, RingEquiv.trans_apply, RingEquiv.trans_apply,
      Ideal.quotientEquiv_mk, ← hPX, h1]
    change e₅ (e₄ (DoubleQuot.quotQuotEquivQuotSup K _
      (DoubleQuot.quotQuotMk K (L) (X i)))) = _
    rw [DoubleQuot.quotQuotEquivQuotSup_quotQuotMk, h4]
    exact h5X i

omit hx hn in
/-- The quotient of the chart ring by the image of an ideal `L ≤ R[Y]` with `ker ⊔ L = 𝔪 R[Y]` is
`κ[Y]`, with `Yᵢ ↦ yᵢ = xᵢ/x_r` and the constants the residues of `R`: the case `P = 𝔪` of
`exists_quotient_map_ringEquiv_of_sup_eq_map` (`κ = R/𝔪`, and `residue` is `Ideal.Quotient.mk 𝔪`
definitionally). -/
theorem exists_quotient_map_ringEquiv (L : Ideal (MvPolynomial (Fin r) R))
    (hsup : RingHom.ker (chartPresentation x r) ⊔ L =
      (maximalIdeal R).map (C : R →+* MvPolynomial (Fin r) R)) :
    ∃ e : (chartRing x r ⧸ L.map (chartPresentation x r).toRingHom) ≃+*
        MvPolynomial (Fin r) (ResidueField R),
      (∀ a : R, e (Ideal.Quotient.mk _ (algebraMap R (chartRing x r) a)) =
          MvPolynomial.C (residue R a)) ∧
        ∀ i : Fin r, e (Ideal.Quotient.mk _ (chartYR x r (Fin.castLE r.2.le i))) =
          MvPolynomial.X i :=
  exists_quotient_map_ringEquiv_of_sup_eq_map x r (maximalIdeal R) L hsup


/-- The fibre of the chart dividing by `x_r` over the closed point of `Spec R` is affine `r`-space
over the residue field: `R'/𝔪R' ≅ κ[Yᵢ : i < r]`, for every index `r`. When `r` is the last index,
`𝔪R' = (x_r)` and this is `exists_quotient_span_algebraMap_x_ringEquiv`. -/
theorem exists_quotient_map_maximalIdeal_ringEquiv :
    ∃ e : (chartRing x r ⧸ (maximalIdeal R).map (algebraMap R (chartRing x r))) ≃+*
        MvPolynomial (Fin r) (ResidueField R),
      (∀ a : R, e (Ideal.Quotient.mk _ (algebraMap R (chartRing x r) a)) =
          MvPolynomial.C (residue R a)) ∧
        ∀ i : Fin r, e (Ideal.Quotient.mk _ (chartYR x r (Fin.castLE r.2.le i))) =
          MvPolynomial.X i := by
  have hL : (maximalIdeal R).map (algebraMap R (chartRing x r)) =
      ((maximalIdeal R).map (C : R →+* MvPolynomial (Fin r) R)).map
        (chartPresentation x r).toRingHom := by
    rw [Ideal.map_map]
    congr 1
    exact RingHom.ext fun a => ((chartPresentation x r).commutes a).symm
  rw [hL]
  refine exists_quotient_map_ringEquiv x r _ ?_
  rw [ker_chartPresentation x r hx hn, sup_eq_right]
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨i, rfl⟩
  refine Ideal.sub_mem _ (Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ ?_))
    (Ideal.mem_map_of_mem _ ?_)
  · rw [hx]
    exact Ideal.subset_span ⟨r, rfl⟩
  · rw [hx]
    exact Ideal.subset_span ⟨_, rfl⟩

include hr in
/-- The exceptional divisor of the chart dividing by `x_r`, `r` the last index, is affine space
over the residue field: `R'/(x_r) ≅ κ[Yᵢ : i < r]` with `Yᵢ ↦ yᵢ = xᵢ/x_r` and the constants the
residues of `R`, from the presentation `R' = R[Y]/(x_r Yᵢ − xᵢ)` (`ker_chartPresentation`). -/
theorem exists_quotient_span_algebraMap_x_ringEquiv :
    ∃ e : (chartRing x r ⧸ Ideal.span {algebraMap R (chartRing x r) (x r)}) ≃+*
        MvPolynomial (Fin r) (ResidueField R),
      (∀ a : R, e (Ideal.Quotient.mk _ (algebraMap R (chartRing x r) a)) =
          MvPolynomial.C (residue R a)) ∧
        ∀ i : Fin r, e (Ideal.Quotient.mk _ (chartYR x r (Fin.castLE r.2.le i))) =
          MvPolynomial.X i := by
  have hL : Ideal.span {algebraMap R (chartRing x r) (x r)} =
      (Ideal.span {C (x r)}).map (chartPresentation x r).toRingHom := by
    rw [Ideal.map_span, Set.image_singleton]
    congr 2
    exact ((chartPresentation x r).commutes (x r)).symm
  rw [hL]
  refine exists_quotient_map_ringEquiv x r _ ?_
  rw [ker_chartPresentation x r hx hn]
  exact chartRelations_sup_span_C_eq_map_C_maximalIdeal x hx r hr

/-! ### The partial centre `P = (x₀, …, x_r)`: `R'/(x_r) ≅ (R/P)[Y]` -/

omit [IsRegularLocalRing R] hx hn in
/-- The relations of the presentation together with `x_r` generate `P R[Y]` for the partial centre
`P = chartCenter x r = (x₀, …, x_r)`: `(x_r Yᵢ − xᵢ, x_r) = (x₀, …, x_r) R[Y]`. No hypothesis on `x`
or `r` is needed; `chartRelations_sup_span_C_eq_map_C_maximalIdeal` is the case of the last
index, where `P = 𝔪`. -/
theorem chartRelations_sup_span_C_eq_map_C_chartCenter :
    chartRelations x r ⊔ Ideal.span {C (x r)} =
      (chartCenter x r).map (C : R →+* MvPolynomial (Fin r) R) := by
  rw [chartCenter, Ideal.map_span]
  refine le_antisymm (sup_le (Ideal.span_le.mpr ?_) (Ideal.span_le.mpr ?_)) (Ideal.span_le.mpr ?_)
  · rintro _ ⟨i, rfl⟩
    refine Ideal.sub_mem _
      (Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨x r, ⟨r, by simp, rfl⟩, rfl⟩))
      (Ideal.subset_span ⟨_, ⟨Fin.castLE r.2.le i, ?_, rfl⟩, rfl⟩)
    change Fin.castLE r.2.le i ≤ r
    exact Fin.le_def.mpr i.2.le
  · rintro _ rfl
    exact Ideal.subset_span ⟨x r, ⟨r, by simp, rfl⟩, rfl⟩
  · rintro _ ⟨_, ⟨j, hj, rfl⟩, rfl⟩
    have hj' : j ≤ r := hj
    by_cases hjr : j = r
    · subst hjr
      exact Ideal.mem_sup_right (Ideal.subset_span rfl)
    · have hlt : j.val < r.val := lt_of_le_of_ne hj' (fun h => hjr (Fin.ext h))
      obtain ⟨i, rfl⟩ : ∃ i : Fin r, Fin.castLE r.2.le i = j := ⟨⟨j.val, hlt⟩, Fin.ext rfl⟩
      have h1 : C (x r) * X i ∈ chartRelations x r ⊔ Ideal.span {C (x r)} :=
        Ideal.mem_sup_right (Ideal.mul_mem_right _ _ (Ideal.subset_span rfl))
      have h2 : C (x r) * X i - C (x (Fin.castLE r.2.le i)) ∈
          chartRelations x r ⊔ Ideal.span {C (x r)} :=
        Ideal.mem_sup_left (Ideal.subset_span ⟨i, rfl⟩)
      have := Ideal.sub_mem _ h1 h2
      rwa [sub_sub_cancel] at this

/-- For a partial centre: the exceptional divisor of the chart dividing by `x_r` of the blow-up of
`P = (x₀, …, x_r)` is affine `r`-space over `R/P`: `R'/(x_r) ≅ (R/P)[Yᵢ : i < r]` with
`Yᵢ ↦ yᵢ = xᵢ/x_r` and the constants the classes of `R`, from the presentation
`R' = R[Y]/(x_r Yᵢ − xᵢ)` (`ker_chartPresentation`) and `(x_r Yᵢ − xᵢ, x_r) = P R[Y]`
(`chartRelations_sup_span_C_eq_map_C_chartCenter`). -/
theorem exists_quotient_span_algebraMap_x_ringEquiv_chartCenter :
    ∃ e : (chartRing x r ⧸ Ideal.span {algebraMap R (chartRing x r) (x r)}) ≃+*
        MvPolynomial (Fin r) (R ⧸ chartCenter x r),
      (∀ a : R, e (Ideal.Quotient.mk _ (algebraMap R (chartRing x r) a)) =
          MvPolynomial.C (Ideal.Quotient.mk (chartCenter x r) a)) ∧
        ∀ i : Fin r, e (Ideal.Quotient.mk _ (chartYR x r (Fin.castLE r.2.le i))) =
          MvPolynomial.X i := by
  have hL : Ideal.span {algebraMap R (chartRing x r) (x r)} =
      (Ideal.span {C (x r)}).map (chartPresentation x r).toRingHom := by
    rw [Ideal.map_span, Set.image_singleton]
    congr 2
    exact ((chartPresentation x r).commutes (x r)).symm
  rw [hL]
  refine exists_quotient_map_ringEquiv_of_sup_eq_map x r _ _ ?_
  rw [ker_chartPresentation x r hx hn]
  exact chartRelations_sup_span_C_eq_map_C_chartCenter x r

/-- `(x_r)` is a prime of the chart ring of the partial centre `P = (x₀, …, x_r)`:
`R'/(x_r) ≅ (R/P)[Y]` is a domain, `P` being prime (`isPrime_chartCenter`). -/
theorem isPrime_span_algebraMap_x_of_chartCenter :
    (Ideal.span {algebraMap R (chartRing x r) (x r)}).IsPrime := by
  obtain ⟨e, -, -⟩ := exists_quotient_span_algebraMap_x_ringEquiv_chartCenter x hx hn r
  have := isPrime_chartCenter x hx hn r
  exact (Ideal.Quotient.isDomain_iff_prime _).mp (MulEquiv.isDomain _ e.toMulEquiv)

/-- `(x_r) ∩ R = P` for the partial centre `P = (x₀, …, x_r)`: the constants killed in
`R'/(x_r) ≅ (R/P)[Y]` are those with class `0` in `R/P`. -/
theorem comap_span_algebraMap_x_eq_chartCenter :
    (Ideal.span {algebraMap R (chartRing x r) (x r)}).comap (algebraMap R (chartRing x r)) =
      chartCenter x r := by
  obtain ⟨e, he, -⟩ := exists_quotient_span_algebraMap_x_ringEquiv_chartCenter x hx hn r
  ext a
  rw [Ideal.mem_comap, ← Ideal.Quotient.eq_zero_iff_mem, ← e.map_eq_zero_iff, he,
    ← Ideal.Quotient.eq_zero_iff_mem (I := chartCenter x r)]
  exact ⟨fun h => by rwa [← MvPolynomial.C_0, MvPolynomial.C_inj] at h,
    fun h => by rw [h, MvPolynomial.C_0]⟩

include hr

/-- `(x_r)` is a prime of the chart ring when `r` is the last index: the generic point of the
exceptional divisor in the chart dividing by `x_r`. -/
theorem isPrime_span_algebraMap_x :
    (Ideal.span {algebraMap R (chartRing x r) (x r)}).IsPrime := by
  obtain ⟨e, -, -⟩ := exists_quotient_span_algebraMap_x_ringEquiv x hx hn r hr
  exact (Ideal.Quotient.isDomain_iff_prime _).mp (MulEquiv.isDomain _ e.toMulEquiv)

end Quotient

/-! ### The order along the exceptional divisor of the chart -/

section Exceptional

variable (hx : maximalIdeal R = Ideal.span (Set.range x))
  (hn : (n : WithBot ℕ∞) = ringKrullDim R) (r : Fin n) (hr : r.val + 1 = n)

omit [IsRegularLocalRing R] in
/-- The exponents of the divided coordinates: the restriction of `α : Fin n →₀ ℕ` to the indices
below `r`. -/
noncomputable def restrictExp (α : Fin n →₀ ℕ) : Fin r →₀ ℕ :=
  Finsupp.equivFunOnFinite.symm fun i => α (Fin.castLE r.2.le i)

omit [IsRegularLocalRing R] in
theorem restrictExp_apply (α : Fin n →₀ ℕ) (i : Fin r) :
    restrictExp r α i = α (Fin.castLE r.2.le i) := by
  simp [restrictExp]

omit [IsRegularLocalRing R] in
/-- When `r` is the last index, no index exceeds it. -/
theorem not_lt_of_succ_eq (hr : r.val + 1 = n) (i : Fin n) : ¬ r < i := fun h => by
  rw [Fin.lt_def] at h
  have := i.2
  omega

omit [IsRegularLocalRing R] in
/-- A product over `Fin n` of factors that are `1` beyond `r` is a product over the indices
`≤ r`. -/
theorem prod_eq_prod_castLE_of_forall_gt {M : Type*} [CommMonoid M] (g : Fin n → M)
    (hg : ∀ i, r < i → g i = 1) :
    ∏ j, g j = ∏ i : Fin (r.val + 1), g (Fin.castLE r.2 i) := by
  classical
  have h : ∏ i : Fin (r.val + 1), g (Fin.castLE r.2 i) =
      ∏ j ∈ Finset.univ.map (Fin.castLEEmb r.2), g j :=
    (Finset.prod_map Finset.univ (Fin.castLEEmb r.2) g).symm
  rw [h]
  refine (Finset.prod_subset (Finset.subset_univ _) fun j _ hj => hg j ?_).symm
  by_contra h
  apply hj
  rw [Finset.mem_map]
  refine ⟨⟨j.val, ?_⟩, Finset.mem_univ _, Fin.ext rfl⟩
  have := Fin.le_def.mp (not_lt.mp h)
  omega

omit [IsRegularLocalRing R] in
/-- A sum over `Fin n` of terms that vanish beyond `r` is a sum over the indices `≤ r`. -/
theorem sum_eq_sum_castLE_of_forall_gt {M : Type*} [AddCommMonoid M] (g : Fin n → M)
    (hg : ∀ i, r < i → g i = 0) :
    ∑ j, g j = ∑ i : Fin (r.val + 1), g (Fin.castLE r.2 i) := by
  classical
  have h : ∑ i : Fin (r.val + 1), g (Fin.castLE r.2 i) =
      ∑ j ∈ Finset.univ.map (Fin.castLEEmb r.2), g j :=
    (Finset.sum_map Finset.univ (Fin.castLEEmb r.2) g).symm
  rw [h]
  refine (Finset.sum_subset (Finset.subset_univ _) fun j _ hj => hg j ?_).symm
  by_contra h
  apply hj
  rw [Finset.mem_map]
  refine ⟨⟨j.val, ?_⟩, Finset.mem_univ _, Fin.ext rfl⟩
  have := Fin.le_def.mp (not_lt.mp h)
  omega

omit [IsRegularLocalRing R] in
/-- The degree of an exponent supported in `x_0, …, x_r` is the exponent of `x_r` plus the degree
of its restriction to the divided coordinates. -/
theorem degree_eq_apply_add_sum' (α : Fin n →₀ ℕ) (hα : ∀ i, r < i → α i = 0) :
    α.degree = α r + ∑ i : Fin r, α (Fin.castLE r.2.le i) := by
  rw [Finsupp.degree_eq_sum, sum_eq_sum_castLE_of_forall_gt r α hα, Fin.sum_univ_castSucc,
    add_comm]
  exact congrArg₂ (· + ·) (congrArg α (Fin.ext rfl))
    (Finset.sum_congr rfl fun i _ => congrArg α (Fin.ext rfl))

omit [IsRegularLocalRing R] in
/-- Two exponents of the same degree supported in `x_0, …, x_r` with the same restriction agree. -/
theorem eq_of_restrictExp_eq' {α β : Fin n →₀ ℕ} {m : ℕ} (hα : α.degree = m) (hβ : β.degree = m)
    (hα' : ∀ i, r < i → α i = 0) (hβ' : ∀ i, r < i → β i = 0)
    (h : restrictExp r α = restrictExp r β) : α = β := by
  have hrest : ∀ i : Fin r, α (Fin.castLE r.2.le i) = β (Fin.castLE r.2.le i) := fun i => by
    have := congrArg (fun γ : Fin r →₀ ℕ => γ i) h
    simpa [restrictExp_apply] using this
  ext j
  by_cases hjr : j = r
  · rw [hjr]
    have h1 := degree_eq_apply_add_sum' r α hα'
    have h2 := degree_eq_apply_add_sum' r β hβ'
    rw [hα] at h1
    rw [hβ] at h2
    have h3 : ∑ i : Fin r, α (Fin.castLE r.2.le i) = ∑ i : Fin r, β (Fin.castLE r.2.le i) :=
      Finset.sum_congr rfl fun i _ => hrest i
    omega
  · rcases lt_or_gt_of_ne hjr with hj | hj
    · have hj' : j = Fin.castLE r.2.le ⟨j.val, Fin.lt_def.mp hj⟩ := Fin.ext rfl
      rw [hj']
      exact hrest _
    · rw [hα' j hj, hβ' j hj]

omit [IsRegularLocalRing R] in
/-- Kollár's substitution `x_i ↦ y_i x_r` on a monomial supported in `x_0, …, x_r`:
`φ(x^α) = x_r^{|α|} · y^{α'}` with `α'` the restriction of `α` to the divided coordinates. -/
theorem prod_algebraMap_pow_eq' (α : Fin n →₀ ℕ) (hα : ∀ i, r < i → α i = 0) :
    ∏ j, algebraMap R (chartRing x r) (x j) ^ α j =
      algebraMap R (chartRing x r) (x r) ^ α.degree *
        ∏ i : Fin r, chartYR x r (Fin.castLE r.2.le i) ^ α (Fin.castLE r.2.le i) := by
  classical
  rw [prod_eq_prod_castLE_of_forall_gt r (fun j => algebraMap R (chartRing x r) (x j) ^ α j)
    (fun i hi => by rw [hα i hi, pow_zero]), Fin.prod_univ_castSucc]
  have e2 : Fin.castLE r.2 (Fin.last r.val) = r := Fin.ext rfl
  have hL : ∏ i : Fin r.val,
      algebraMap R (chartRing x r) (x (Fin.castLE r.2 (Fin.castSucc i))) ^
        α (Fin.castLE r.2 (Fin.castSucc i)) =
      ∏ i : Fin r, algebraMap R (chartRing x r) (x r) ^ α (Fin.castLE r.2.le i) *
        chartYR x r (Fin.castLE r.2.le i) ^ α (Fin.castLE r.2.le i) := by
    refine Finset.prod_congr rfl fun i _ => ?_
    have e1 : Fin.castLE r.2 (Fin.castSucc i) = Fin.castLE r.2.le i := Fin.ext rfl
    have hlt : Fin.castLE r.2.le i < r := by
      rw [Fin.lt_def]
      exact i.2
    rw [e1, algebraMap_x_eq_mul_chartYR x r hlt, mul_pow]
  rw [hL, e2, Finset.prod_mul_distrib, Finset.prod_pow_eq_pow_sum,
    degree_eq_apply_add_sum' r α hα, pow_add]
  ring

include hr in
omit [IsRegularLocalRing R] in
/-- The indices other than the last one are the `castLE` images of `Fin r`. -/
theorem univ_erase_eq_map_castLEEmb :
    (Finset.univ : Finset (Fin n)).erase r =
      (Finset.univ : Finset (Fin r)).map (Fin.castLEEmb r.2.le) := by
  ext j
  simp only [Finset.mem_erase, Finset.mem_univ, and_true, Finset.mem_map, true_and]
  constructor
  · intro hj
    obtain ⟨i, rfl⟩ := exists_castLE_eq_of_ne r hr hj
    exact ⟨i, rfl⟩
  · rintro ⟨i, rfl⟩
    intro h
    have := congrArg Fin.val h
    simp only [Fin.castLEEmb_apply, Fin.val_castLE] at this
    have := i.2
    omega

include hr in
omit [IsRegularLocalRing R] in
/-- The degree of an exponent is the exponent of `x_r` plus the degree of its restriction. -/
theorem degree_eq_apply_add_sum (α : Fin n →₀ ℕ) :
    α.degree = α r + ∑ i : Fin r, α (Fin.castLE r.2.le i) :=
  degree_eq_apply_add_sum' r α fun i hi => absurd hi (not_lt_of_succ_eq r hr i)

include hr in
omit [IsRegularLocalRing R] in
/-- Two exponents of the same degree with the same restriction agree. -/
theorem eq_of_restrictExp_eq {α β : Fin n →₀ ℕ} {m : ℕ} (hα : α.degree = m) (hβ : β.degree = m)
    (h : restrictExp r α = restrictExp r β) : α = β :=
  eq_of_restrictExp_eq' r hα hβ (fun i hi => absurd hi (not_lt_of_succ_eq r hr i))
    (fun i hi => absurd hi (not_lt_of_succ_eq r hr i)) h

include hr in
omit [IsRegularLocalRing R] in
/-- Kollár's substitution `x_i ↦ y_i x_r` on a monomial of degree `m`: `φ(x^α) = x_r^m · y^{α'}`
with `α'` the restriction of `α` to the divided coordinates. -/
theorem prod_algebraMap_pow_eq (α : Fin n →₀ ℕ) :
    ∏ j, algebraMap R (chartRing x r) (x j) ^ α j =
      algebraMap R (chartRing x r) (x r) ^ α.degree *
        ∏ i : Fin r, chartYR x r (Fin.castLE r.2.le i) ^ α (Fin.castLE r.2.le i) :=
  prod_algebraMap_pow_eq' x r α fun i hi => absurd hi (not_lt_of_succ_eq r hr i)

omit [IsRegularLocalRing R] in
/-- When `r` is the last index, the centre `P = (x_0, …, x_r)` is the whole `(x)`. -/
theorem chartCenter_eq_span_range_of_succ_eq (hr : r.val + 1 = n) :
    chartCenter x r = Ideal.span (Set.range x) := by
  rw [chartCenter, ← Set.image_univ]
  congr 2
  ext i
  simp only [Set.mem_ofPred_eq, Set.mem_univ, iff_true]
  exact not_lt.mp (not_lt_of_succ_eq r hr i)

include hx in
/-- (The proof of [Kol07, Lemma 61].) For `f ∈ Pᵐ` of order exactly `m`, the transform `f / x_rᵐ`
is `Q(y)` for a polynomial `Q` of degree `≤ m` with a coefficient outside `𝔪`: the leading form of
`f` read in the divided coordinates. -/
theorem exists_transformElem_eq_chartPresentation {f : R} {m : ℕ} (hf : f ∈ chartCenter x r ^ m)
    (hord : ordElem f = m) :
    ∃ Q : MvPolynomial (Fin r) R, transformElem x r f hf = chartPresentation x r Q ∧
      Q.totalDegree ≤ m ∧ ∃ β, coeff β Q ∉ maximalIdeal R := by
  classical
  obtain ⟨S, c, hS, hfeq, α₀, hα₀S, hc⟩ :=
    exists_sum_monomials_unit_coeff_of_mem_chartCenter_pow x hx r hf hord
  refine ⟨∑ α ∈ S, monomial (restrictExp r α) (c α), ?_, ?_, restrictExp r α₀, ?_⟩
  · symm
    apply eq_transformElem_of_pow_mul_eq
    rw [hfeq, map_sum, map_sum, Finset.mul_sum]
    refine Finset.sum_congr rfl fun α hα => ?_
    rw [map_mul, map_prod]
    simp only [map_pow]
    rw [prod_algebraMap_pow_eq' x r α (hS α hα).2, (hS α hα).1]
    simp only [chartPresentation, aeval_monomial]
    rw [Finsupp.prod_fintype _ _ (fun i => pow_zero _)]
    simp only [restrictExp_apply]
    ring
  · refine (totalDegree_finsetSum _ _).trans (Finset.sup_le fun α hα => ?_)
    refine (totalDegree_monomial_le _ _).trans ?_
    have h1 := degree_eq_apply_add_sum' r α (hS α hα).2
    rw [(hS α hα).1] at h1
    have hsum : ((restrictExp r α).sum fun _ => id) = ∑ i : Fin r, α (Fin.castLE r.2.le i) := by
      rw [Finsupp.sum_fintype _ _ (fun _ => rfl)]
      simp only [restrictExp_apply, id]
    omega
  · rw [coeff_sum, Finset.sum_eq_single α₀]
    · rwa [coeff_monomial, if_pos rfl]
    · intro α hα hne
      rw [coeff_monomial, if_neg]
      exact fun h => hne (eq_of_restrictExp_eq' r (hS α hα).1 (hS α₀ hα₀S).1 (hS α hα).2
        (hS α₀ hα₀S).2 h)
    · intro h
      exact absurd hα₀S h

include hx hr in
/-- (The proof of [Kol07, Lemma 61].) For `f` of order exactly `m` and `r` the last index,
`f = x_rᵐ · Q(y)` in `R'` for a polynomial `Q` with a coefficient outside `𝔪`, the leading form of
`f` read in the divided coordinates. -/
theorem exists_algebraMap_eq_pow_mul_chartPresentation (f : R) (m : ℕ) (hf : ordElem f = m) :
    ∃ Q : MvPolynomial (Fin r) R,
      algebraMap R (chartRing x r) f =
          algebraMap R (chartRing x r) (x r) ^ m * chartPresentation x r Q ∧
        ∃ β, coeff β Q ∉ maximalIdeal R := by
  have hmem : f ∈ chartCenter x r ^ m := by
    rw [chartCenter_eq_span_range_of_succ_eq x r hr, ← hx]
    exact mem_maximalIdeal_pow_iff_le_ordElem.mpr (by rw [hf])
  obtain ⟨Q, hQ, -, β, hβ⟩ := exists_transformElem_eq_chartPresentation x hx r hmem hf
  exact ⟨Q, by rw [← hQ, algebraMap_pow_mul_transformElem], β, hβ⟩

include hx hn hr in
/-- For `f` of order exactly `m`, `f = x_rᵐ (∑ c_α y^α + x_r (…))` in `R'` lies in `(x_r)ᵐ` but not
in `(x_r)^{m+1}`: modulo `x_r` the bracket is the nonzero polynomial `∑ c̄_α y^α`. This is the
maximality of the exponent `k` in `f^* = h^k f^s` in the definition of the strict transform of an
ideal in [Hau14, §6] (following Definition 6.2). -/
theorem algebraMap_notMem_span_pow_succ (f : R) (m : ℕ) (hf : ordElem f = m) :
    algebraMap R (chartRing x r) f ∉ Ideal.span {algebraMap R (chartRing x r) (x r)} ^ (m + 1) := by
  intro hmem
  obtain ⟨Q, hQ, β, hβ⟩ := exists_algebraMap_eq_pow_mul_chartPresentation x hx r hr f m hf
  obtain ⟨e, heC, heX⟩ := exists_quotient_span_algebraMap_x_ringEquiv x hx hn r hr
  rw [Ideal.span_singleton_pow] at hmem
  obtain ⟨h, hh⟩ := Ideal.mem_span_singleton'.mp hmem
  have hPQ : chartPresentation x r Q = algebraMap R (chartRing x r) (x r) * h := by
    apply algebraMap_pow_mul_right_injective x r m
    change algebraMap R (chartRing x r) (x r) ^ m * chartPresentation x r Q =
      algebraMap R (chartRing x r) (x r) ^ m * (algebraMap R (chartRing x r) (x r) * h)
    rw [← hQ, ← hh, pow_succ]
    ring
  have hmk : Ideal.Quotient.mk (Ideal.span {algebraMap R (chartRing x r) (x r)})
      (chartPresentation x r Q) = 0 := by
    rw [Ideal.Quotient.eq_zero_iff_mem, hPQ]
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
  have hcomp : (e : (chartRing x r ⧸ Ideal.span {algebraMap R (chartRing x r) (x r)}) →+*
      MvPolynomial (Fin r) (ResidueField R)).comp
        ((Ideal.Quotient.mk _).comp (chartPresentation x r : MvPolynomial (Fin r) R →+* _)) =
      MvPolynomial.map (residue R) := by
    apply MvPolynomial.ringHom_ext
    · intro a
      change e (Ideal.Quotient.mk _ (chartPresentation x r (C a))) =
        MvPolynomial.map (residue R) (C a)
      rw [show chartPresentation x r (C a) = algebraMap R (chartRing x r) a from
        MvPolynomial.aeval_C _ a, MvPolynomial.map_C]
      exact heC a
    · intro i
      change e (Ideal.Quotient.mk _ (chartPresentation x r (X i))) =
        MvPolynomial.map (residue R) (X i)
      rw [MvPolynomial.map_X, show chartPresentation x r (X i) = chartYR x r (Fin.castLE r.2.le i)
        from MvPolynomial.aeval_X _ i]
      exact heX i
  have h0 : MvPolynomial.map (residue R) Q = 0 := by
    have := congrArg (fun ψ : MvPolynomial (Fin r) R →+* MvPolynomial (Fin r) (ResidueField R) =>
      ψ Q) hcomp
    change e (Ideal.Quotient.mk _ (chartPresentation x r Q)) = MvPolynomial.map (residue R) Q
      at this
    rw [hmk, map_zero] at this
    exact this.symm
  have := congrArg (MvPolynomial.coeff β) h0
  rw [MvPolynomial.coeff_map, MvPolynomial.coeff_zero, IsLocalRing.residue_eq_zero_iff] at this
  exact hβ this

include hx hn hr in
/-- **The order along the exceptional divisor equals the order at the centre** (the remark
following [Kol07, Definition 47]; [Hau14, §6], following Definition 6.2), local form: the order of
`I R'` along the prime `(x_r)`, that is, in the discrete valuation ring `R'_{(x_r)}`, the local ring
of the blow-up at the generic point of the exceptional divisor, is the order of `I`. -/
theorem ordAlong_span_algebraMap_x_map (I : Ideal R) :
    haveI := isPrime_span_algebraMap_x x hx hn r hr
    ordAlong (Ideal.span {algebraMap R (chartRing x r) (x r)})
        (I.map (algebraMap R (chartRing x r))) = ord I := by
  classical
  have hP := isPrime_span_algebraMap_x x hx hn r hr
  set P : Ideal (chartRing x r) := Ideal.span {algebraMap R (chartRing x r) (x r)} with hPdef
  have hmC : maximalIdeal R = chartCenter x r := by
    rw [hx, chartCenter]
    congr 1
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      refine ⟨i, ?_, rfl⟩
      change i.val ≤ r.val
      have := i.2
      omega
    · rintro ⟨i, -, rfl⟩
      exact ⟨i, rfl⟩
  have hmap : (maximalIdeal R).map (algebraMap R (chartRing x r)) = P := by
    rw [hmC]
    exact map_chartCenter x r
  have hmax : maximalIdeal (Localization.AtPrime P) = P.map (algebraMap _ _) :=
    (IsLocalization.AtPrime.map_eq_maximalIdeal P (Localization.AtPrime P)).symm
  rcases eq_or_ne (ord I) ⊤ with htop | hne
  · rw [htop, ord_eq_top_iff.mp htop, Ideal.map_bot]
    unfold ordAlong
    rw [Ideal.map_bot]
    exact ord_bot
  · obtain ⟨m, hm⟩ := WithTop.ne_top_iff_exists.mp hne
    rw [ENat.some_eq_natCast] at hm
    rw [← hm]
    unfold ordAlong
    apply le_antisymm
    · obtain ⟨f, hfI, hfm⟩ := exists_mem_ordElem_eq_of_ord_eq hm.symm
      have hmem : algebraMap _ (Localization.AtPrime P) (algebraMap R (chartRing x r) f) ∈
          (I.map (algebraMap R (chartRing x r))).map (algebraMap _ (Localization.AtPrime P)) :=
        Ideal.mem_map_of_mem _ (Ideal.mem_map_of_mem _ hfI)
      refine le_trans ((ord_eq_iInf _).le.trans (iInf₂_le _ hmem)) ?_
      by_contra hlt
      have hle : ((m + 1 : ℕ) : ℕ∞) ≤
          ordElem (algebraMap _ (Localization.AtPrime P) (algebraMap R (chartRing x r) f)) := by
        rw [Nat.cast_succ]
        exact Order.add_one_le_of_lt (not_le.mp hlt)
      have hmem' := mem_maximalIdeal_pow_iff_le_ordElem.mpr hle
      rw [hmax, ← Ideal.map_pow,
        IsLocalization.mem_map_algebraMap_iff P.primeCompl (Localization.AtPrime P)] at hmem'
      obtain ⟨⟨⟨y, hy⟩, ⟨s, hs⟩⟩, hys⟩ := hmem'
      rw [← map_mul, IsLocalization.eq_iff_exists P.primeCompl (Localization.AtPrime P)] at hys
      obtain ⟨t, ht⟩ := hys
      dsimp only at ht hy hs
      have hne0 : algebraMap R (chartRing x r) (x r) ≠ 0 := fun h =>
        x_ne_zero_of_span_eq x hx hn r
          ((algebraMap_chartRing_injective x r hx hn) (h.trans (map_zero _).symm))
      have hprime : Prime (algebraMap R (chartRing x r) (x r)) :=
        (Ideal.span_singleton_prime hne0).mp hP
      rw [hPdef, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hy
      have hdvd : algebraMap R (chartRing x r) (x r) ^ (m + 1) ∣
          ((t : chartRing x r) * s) * algebraMap R (chartRing x r) f := by
        have : ((t : chartRing x r) * s) * algebraMap R (chartRing x r) f = t * y := by
          rw [← ht]
          ring
        rw [this]
        exact Dvd.dvd.mul_left hy _
      have hts : ¬ algebraMap R (chartRing x r) (x r) ∣ (t : chartRing x r) * s := by
        intro h
        have hmemP : (t : chartRing x r) * s ∈ P := Ideal.mem_span_singleton.mpr h
        rcases hP.mem_or_mem hmemP with h1 | h1
        · exact (t.2 : (t : chartRing x r) ∉ P) h1
        · exact (hs : s ∉ P) h1
      have hfin := hprime.pow_dvd_of_dvd_mul_left _ hts hdvd
      exact algebraMap_notMem_span_pow_succ x hx hn r hr f m hfm
        (by rw [Ideal.span_singleton_pow]; exact Ideal.mem_span_singleton.mpr hfin)
    · refine le_ord_iff.mpr ?_
      have h1 : I ≤ maximalIdeal R ^ m := le_ord_iff.mp hm.le
      calc (I.map (algebraMap R (chartRing x r))).map (algebraMap _ (Localization.AtPrime P))
          ≤ ((maximalIdeal R ^ m).map (algebraMap R (chartRing x r))).map
              (algebraMap _ (Localization.AtPrime P)) := Ideal.map_mono (Ideal.map_mono h1)
        _ = maximalIdeal (Localization.AtPrime P) ^ m := by
          rw [Ideal.map_pow, hmap, Ideal.map_pow, hmax]

end Exceptional

end IsLocalRing
