/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.BirationalTransform

/-!
# The `x_r`-saturation of an ideal in the chart ring is generated by the transforms

The algebraic half of Bierstone–Milman's description of the ideal of the strict transform,
`I_{X'} = ⋃_k (I_{π⁻¹(X)} : y_exc^k)` [BM97, Proposition 3.13]: in the chart ring
`R' = R[x_i/x_r : i < r] ⊆ R[1/x_r]` of Kollár's chart (60.2) [Kol07, Definition 60]
(`IsLocalRing.chartRing x r`), the `x_r`-saturation `⋃_k (I R' : x_r^k)` of the extension of
an ideal `I ⊆ R` is the ideal generated by the transforms `x_r^{-m} φ(f)` of the elements `f ∈ I`
(`transformIdeal x r I m` of `Hironaka/Algebra/Local/BirationalTransform.lean`, all `m`).  The
argument is elementary: every element of `R'` is `φ(c)/x_r^M` (`R'` is generated over `R` by the
`x_i/x_r`), so `x_r^k g ∈ I R'` gives `x_r^{k+M} g = φ(f)` with `f ∈ I`, i.e. `g` is a transform;
conversely a transform `g = x_r^{-m} φ(f)` satisfies `x_r^m g ∈ I R'`.  This is the Rees-algebra
picture of the strict transform of a subscheme under a blow-up ([Kol07, Definition 25]; Hironaka's
definition through the monoidal transformation of the ambient space, [Hir64, Chapter 0, §2]).
The analytic statement follows by transporting this along the chart-ring homomorphism into the
stalk `𝒪_{M',a'}` in `Hironaka/Manifold/BlowUp/Transform/StrictSubspaceProp313.lean`.
-/

@[expose] public section

open IsLocalRing

universe u

namespace IsLocalRing

variable {R : Type u} [CommRing R] {n : ℕ} (x : Fin n → R) (r : Fin n)

/-- Every element of the chart ring is a quotient `φ(c)/x_r^M`: the generators `x_i/x_r` are, and
sums and products of such quotients are (the Rees-algebra form of the chart ring of
[Kol07, Definition 60, (60.2)]). -/
theorem exists_pow_mul_eq_algebraMap (g : chartRing x r) :
    ∃ (M : ℕ) (c : R),
      algebraMap R (chartRing x r) (x r) ^ M * g = algebraMap R (chartRing x r) c := by
  obtain ⟨g, hg⟩ := g
  have key : ∃ (M : ℕ) (c : R), algebraMap R (Localization.Away (x r)) (x r) ^ M * g =
      algebraMap R (Localization.Away (x r)) c := by
    refine Algebra.adjoin_induction (hx := hg) ?_ ?_ ?_ ?_
    · rintro _ ⟨i, -, rfl⟩
      refine ⟨1, x i, ?_⟩
      dsimp only
      rw [pow_one, Localization.mk_eq_mk'_apply]
      exact IsLocalization.mk'_spec' (Localization.Away (x r)) (x i)
        ⟨x r, Submonoid.mem_powers (x r)⟩
    · intro c
      exact ⟨0, c, by rw [pow_zero, one_mul]⟩
    · rintro z₁ z₂ - - ⟨M₁, c₁, h₁⟩ ⟨M₂, c₂, h₂⟩
      refine ⟨M₁ + M₂, x r ^ M₂ * c₁ + x r ^ M₁ * c₂, ?_⟩
      rw [map_add, map_mul, map_mul, map_pow, map_pow, ← h₁, ← h₂]
      ring
    · rintro z₁ z₂ - - ⟨M₁, c₁, h₁⟩ ⟨M₂, c₂, h₂⟩
      refine ⟨M₁ + M₂, c₁ * c₂, ?_⟩
      rw [map_mul, ← h₁, ← h₂]
      ring
  obtain ⟨M, c, h⟩ := key
  exact ⟨M, c, Subtype.ext (by simpa using h)⟩

variable (I : Ideal R)

/-- The transforms of the elements of `I`: the `g ∈ R'` with `x_r^M g = φ(f)` for some `f ∈ I`. -/
def IsTransformOf (g : chartRing x r) : Prop :=
  ∃ (M : ℕ) (f : R), f ∈ I ∧
    algebraMap R (chartRing x r) (x r) ^ M * g = algebraMap R (chartRing x r) f

theorem IsTransformOf.zero : IsTransformOf x r I 0 :=
  ⟨0, 0, I.zero_mem, by simp⟩

theorem IsTransformOf.add {g₁ g₂ : chartRing x r} (h₁ : IsTransformOf x r I g₁)
    (h₂ : IsTransformOf x r I g₂) : IsTransformOf x r I (g₁ + g₂) := by
  obtain ⟨M₁, f₁, hf₁, e₁⟩ := h₁
  obtain ⟨M₂, f₂, hf₂, e₂⟩ := h₂
  refine ⟨M₁ + M₂, x r ^ M₂ * f₁ + x r ^ M₁ * f₂,
    I.add_mem (I.mul_mem_left _ hf₁) (I.mul_mem_left _ hf₂), ?_⟩
  rw [map_add, map_mul, map_mul, map_pow, map_pow, ← e₁, ← e₂]
  ring

theorem IsTransformOf.mul (a : chartRing x r) {g : chartRing x r} (h : IsTransformOf x r I g) :
    IsTransformOf x r I (a * g) := by
  obtain ⟨M, f, hf, e⟩ := h
  obtain ⟨M', c, e'⟩ := exists_pow_mul_eq_algebraMap x r a
  refine ⟨M' + M, c * f, I.mul_mem_left _ hf, ?_⟩
  rw [map_mul, ← e, ← e']
  ring

/-- A transform is saturated: if `x_r^k g` is a transform then so is `g`. -/
theorem IsTransformOf.of_pow_mul {k : ℕ} {g : chartRing x r}
    (h : IsTransformOf x r I (algebraMap R (chartRing x r) (x r) ^ k * g)) :
    IsTransformOf x r I g := by
  obtain ⟨M, f, hf, e⟩ := h
  exact ⟨M + k, f, hf, by rw [pow_add, mul_assoc]; exact e⟩

/-- The transforms of the elements of `I` form an ideal of the chart ring. -/
def transformsIdeal : Ideal (chartRing x r) where
  carrier := {g | IsTransformOf x r I g}
  zero_mem' := IsTransformOf.zero x r I
  add_mem' h₁ h₂ := IsTransformOf.add x r I h₁ h₂
  smul_mem' a g h := by
    change IsTransformOf x r I (a • g)
    rw [smul_eq_mul]
    exact IsTransformOf.mul x r I a h

theorem mem_transformsIdeal {g : chartRing x r} :
    g ∈ transformsIdeal x r I ↔ IsTransformOf x r I g :=
  Iff.rfl

/-- Every element of `I R'` is a transform (with `M = 0`). -/
theorem map_le_transformsIdeal :
    I.map (algebraMap R (chartRing x r)) ≤ transformsIdeal x r I :=
  Ideal.map_le_iff_le_comap.mpr fun f hf => ⟨0, f, hf, by rw [pow_zero, one_mul]⟩

/-- The ideal of transforms is the union of the `transformIdeal x r I m` of
`Hironaka/Algebra/Local/BirationalTransform.lean`. -/
theorem transformsIdeal_eq_iSup_transformIdeal :
    transformsIdeal x r I = ⨆ m : ℕ, transformIdeal x r I m := by
  refine le_antisymm (fun g hg => ?_) (iSup_le fun m => Ideal.span_le.mpr ?_)
  · obtain ⟨M, f, hf, e⟩ := hg
    exact Submodule.mem_iSup_of_mem M (Ideal.subset_span ⟨f, hf, e⟩)
  · rintro g ⟨f, hf, e⟩
    exact ⟨m, f, hf, e⟩

/-- **The `x_r`-saturation of `I R'` is the ideal of the transforms of the elements of `I`**,
`⋃_k (I R' : x_r^k) = {x_r^{-M} φ(f) : f ∈ I}`: [BM97, Proposition 3.13] in the chart ring
(the strict transform of [Kol07, Definition 25] and the transform (60.1) of
[Kol07, Definition 60]). -/
theorem iSup_colon_pow_map_eq_transformsIdeal :
    (⨆ k : ℕ, Submodule.colon (I.map (algebraMap R (chartRing x r)))
      (SetLike.coe (Ideal.span {algebraMap R (chartRing x r) (x r)} ^ k))) =
      transformsIdeal x r I := by
  refine le_antisymm (iSup_le fun k g hg => ?_) fun g hg => ?_
  · refine IsTransformOf.of_pow_mul x r I (k := k) (map_le_transformsIdeal x r I ?_)
    have := Submodule.mem_colon.mp hg (algebraMap R (chartRing x r) (x r) ^ k)
      (by rw [SetLike.mem_coe, Ideal.span_singleton_pow]; exact Ideal.mem_span_singleton_self _)
    rw [smul_eq_mul, mul_comm] at this
    exact this
  · obtain ⟨M, f, hf, e⟩ := hg
    refine Submodule.mem_iSup_of_mem M (Submodule.mem_colon.mpr fun p hp => ?_)
    rw [SetLike.mem_coe, Ideal.span_singleton_pow, Ideal.mem_span_singleton'] at hp
    obtain ⟨b, rfl⟩ := hp
    rw [smul_eq_mul, show g * (b * algebraMap R (chartRing x r) (x r) ^ M) =
      b * (algebraMap R (chartRing x r) (x r) ^ M * g) by ring, e]
    exact Ideal.mul_mem_left _ b (Ideal.mem_map_of_mem _ hf)

/-- The saturation theorem with the colons by the elements `x_r^k` (the form the transport lemma
of `Hironaka.Algebra.SaturationDescent` produces). -/
theorem iSup_colon_pow_singleton_map_eq_transformsIdeal :
    (⨆ k : ℕ, (I.map (algebraMap R (chartRing x r))).colon
      {algebraMap R (chartRing x r) (x r) ^ k}) = transformsIdeal x r I := by
  rw [← iSup_colon_pow_map_eq_transformsIdeal]
  simp_rw [Ideal.span_singleton_pow, Submodule.colon_span]

/-- The saturation in the form of the union of the `transformIdeal x r I m`. -/
theorem iSup_colon_pow_map_eq_iSup_transformIdeal :
    (⨆ k : ℕ, Submodule.colon (I.map (algebraMap R (chartRing x r)))
      (SetLike.coe (Ideal.span {algebraMap R (chartRing x r) (x r)} ^ k))) =
      ⨆ m : ℕ, transformIdeal x r I m := by
  rw [iSup_colon_pow_map_eq_transformsIdeal, transformsIdeal_eq_iSup_transformIdeal]

end IsLocalRing
