/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.RegularLocalRing.Defs
public import Mathlib.RingTheory.Derivation.Basic
import Mathlib.Algebra.CharP.Algebra
import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv
import Mathlib.RingTheory.Derivation.Lie

/-!
# Regular local rings with coordinates

This file fixes the setting of the local algebra shared by the algebraic and the analytic parts
of the library: a regular local ring `R` containing `ℚ`, a regular system of parameters
`x₁, …, xₙ` and derivations `∂₁, …, ∂ₙ` with `∂ᵢ xⱼ = δᵢⱼ`.  It is the ring-level form of
Kollár's "local coordinates at a point of a smooth variety" [Kol07, Definition 55] together with
the partial derivatives `∂/∂xᵢ` that generate the derivations there [Kol07, Definition 73]; the
same structure is carried by the rings of real- and complex-analytic germs.

## Main declarations

* `IsLocalRing.RegularCoords R n`: the coordinate structure.  The four propositional fields
  say that the `xᵢ` generate the maximal ideal, that `n` is the Krull dimension (so `x` is a
  regular system of parameters), that `∂ᵢ xⱼ = δᵢⱼ`, and that the `∂ᵢ` commute.
* `IsLocalRing.isUnit_natCast`, `charZero_residueField`: how "characteristic zero" enters —
  nonzero natural numbers are units of `R` and of its residue field.
* `IsLocalRing.RegularCoords.jacobian`, `transportPderiv`, `isUnit_jacobian`, `changeCoords`:
  a second generating system `x'` of the maximal ideal has an invertible Jacobian matrix
  `Mᵢⱼ = ∂ᵢ x'ⱼ`, and the transported derivations `∂'ⱼ = ∑ₗ (M⁻¹)ⱼₗ ∂ₗ` satisfy `∂'ⱼ x'ᵢ = δᵢⱼ`.
* `IsLocalRing.RegularCoords.span_range_transportPderiv`: the `R`-span of the derivations
  does not depend on the coordinates.
* `IsLocalRing.RegularCoords.SpansDerivations`: the condition every instance of the
  structure supplies, that the `∂ᵢ` generate all derivations.

## The change-of-coordinates argument

Kollár chooses local coordinates adapted to a subvariety without comment, for instance when
computing a blow-up in coordinates [Kol07, Definition 60] or in the proof of
[Kol07, Proposition 99]; the underlying algebra is the following.  Let `x'` be another
generating system of the maximal ideal `𝔪` and `M` the matrix `Mᵢⱼ = ∂ᵢ x'ⱼ`.  If `det M` were
not a unit, its residue would vanish and the residue matrix would have a nonzero kernel vector
`v`; lifting `v` to `w : Fin n → R`, the element `y = ∑ⱼ wⱼ x'ⱼ` lies in `𝔪` and all its partials
`∂ᵢ y = ∑ⱼ wⱼ ∂ᵢ x'ⱼ + ∑ⱼ (∂ᵢ wⱼ) x'ⱼ` lie in `𝔪`.  An element of `𝔪` all of whose partials lie
in `𝔪` lies in `𝔪²`: writing `y = ∑ aₗ xₗ`, the relation `∂ᵢ y ≡ aᵢ (mod 𝔪)` forces every
`aₗ ∈ 𝔪`.  Some `wⱼ₀` is a unit, so `x'ⱼ₀ ∈ 𝔪² + ⟨x'ⱼ : j ≠ j₀⟩`, and Nakayama's lemma gives
`𝔪 = ⟨x'ⱼ : j ≠ j₀⟩`, generated by `n - 1` elements.  But the minimal number of generators of
the maximal ideal of a regular local ring is its dimension `n`, a contradiction.  This is where
regularity of `R` (through `dim R = n`) is used; nothing else in the file needs it.

## Index convention

With the pair of conventions `Mᵢⱼ = ∂ⱼ x'ᵢ` and `∂'ⱼ = ∑ₗ (M⁻¹)ⱼₗ ∂ₗ` one would get
`∂'ⱼ x'ᵢ = (M · (M⁻¹)ᵀ)ᵢⱼ`, which is `δᵢⱼ` only for symmetric `M`.  We take the Jacobian
convention `Mᵢⱼ = ∂ᵢ x'ⱼ` and keep `∂'ⱼ = ∑ₗ (M⁻¹)ⱼₗ ∂ₗ`, so that `∂'ⱼ x'ᵢ = (M⁻¹ M)ⱼᵢ = δⱼᵢ`.

## Instances

`RegularCoords` is data, not a class: a ring carries many coordinate systems, and the change of
coordinates above moves between them.  The instances constructed in the library are the stalks
of smooth `k`-schemes at their points, the power series ring `K⟦X₁, …, Xₙ⟧`
(`Hironaka.Algebra.Local.PowerSeries`) and the rings of analytic germs; each also supplies
`SpansDerivations` for the derivations of its setting.
-/

@[expose] public section

namespace IsLocalRing

open IsLocalRing

universe u v

variable (R : Type u) [CommRing R]

/-- **The coordinate structure** [Kol07, Definitions 55 and 73].  A regular system of
parameters `x` of the regular local ring `R ⊇ ℚ` together with commuting derivations
`pderiv i` satisfying
`pderiv i (x j) = δᵢⱼ`.  The field `card` says `n = dim R`; with `span_x` it makes `x` a minimal
generating system of the maximal ideal. -/
structure RegularCoords [IsRegularLocalRing R] [Algebra ℚ R] (n : ℕ) where
  /-- The regular system of parameters `x₁, …, xₙ`. -/
  x : Fin n → R
  /-- The partial derivatives `∂₁, …, ∂ₙ`, as `ℚ`-derivations of `R`. -/
  pderiv : Fin n → Derivation ℚ R R
  /-- The `xᵢ` generate the maximal ideal. -/
  span_x : maximalIdeal R = Ideal.span (Set.range x)
  /-- `n` is the Krull dimension of `R`. -/
  card : (n : WithBot ℕ∞) = ringKrullDim R
  /-- `∂ᵢ xⱼ = δᵢⱼ`. -/
  pderiv_x : ∀ i j, pderiv i (x j) = if i = j then 1 else 0
  /-- The partial derivatives commute. -/
  pderiv_comm : ∀ i j f, pderiv i (pderiv j f) = pderiv j (pderiv i f)

section CharZero

variable [Algebra ℚ R]

/-- A nonzero natural number is a unit of the `ℚ`-algebra `R`. -/
theorem isUnit_natCast {a : ℕ} (ha : a ≠ 0) : IsUnit (a : R) := by
  rw [← map_natCast (algebraMap ℚ R) a]
  exact (IsUnit.mk0 (a : ℚ) (by exact_mod_cast ha)).map _

variable [IsLocalRing R]

/-- The residue field of a local `ℚ`-algebra has characteristic zero (Mathlib's
`algebraRat.charZero`, made an instance; the `Algebra ℚ` structure is Mathlib's
`IsLocalRing.ResidueField.algebra`). -/
instance charZero_residueField : CharZero (ResidueField R) :=
  algebraRat.charZero _

end CharZero

section Sum

/-- Evaluating a finite sum of derivations (Mathlib has `Derivation.coeFnAddMonoidHom` but no
summed evaluation lemma). -/
theorem derivation_sum_apply {R A M ι : Type*} [CommSemiring R] [CommSemiring A]
    [AddCommMonoid M] [Algebra R A] [Module A M] [Module R M] (s : Finset ι)
    (D : ι → Derivation R A M) (a : A) : (∑ i ∈ s, D i) a = ∑ i ∈ s, D i a := by
  change Derivation.coeFnAddMonoidHom (∑ i ∈ s, D i) a = _
  rw [map_sum, Finset.sum_apply]
  rfl

end Sum

namespace RegularCoords

variable {R} [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ} (c : RegularCoords R n)

theorem x_mem_maximalIdeal (i : Fin n) : c.x i ∈ maximalIdeal R := by
  rw [c.span_x]
  exact Ideal.subset_span ⟨i, rfl⟩

/-- The partial derivatives lower the `𝔪`-adic filtration by one step at the first level: an
element of `𝔪` all of whose partials lie in `𝔪` lies in `𝔪²`.  (A step of the
change-of-coordinates argument; the Euler-identity computation `∂ᵢ (∑ aₗ xₗ) ≡ aᵢ (mod 𝔪)`.) -/
theorem mem_maximalIdeal_sq_of_pderiv_mem {y : R} (hy : y ∈ maximalIdeal R)
    (h : ∀ i, c.pderiv i y ∈ maximalIdeal R) : y ∈ maximalIdeal R ^ 2 := by
  rw [c.span_x] at hy
  obtain ⟨a, rfl⟩ := Ideal.mem_span_range_iff_exists_fun.mp hy
  have ha : ∀ i, a i ∈ maximalIdeal R := by
    intro i
    have hi := h i
    simp only [map_sum, smul_eq_mul, Derivation.leibniz, c.pderiv_x, mul_ite, mul_one,
      mul_zero, Finset.sum_add_distrib, Finset.sum_ite_eq, Finset.mem_univ, if_true] at hi
    have : a i = c.pderiv i (∑ l, a l * c.x l) - ∑ l, c.x l * c.pderiv i (a l) := by
      simp only [map_sum, smul_eq_mul, Derivation.leibniz, c.pderiv_x, mul_ite, mul_one,
        mul_zero, Finset.sum_add_distrib, Finset.sum_ite_eq, Finset.mem_univ, if_true]
      ring
    rw [this]
    exact Submodule.sub_mem _ (h i)
      (Ideal.sum_mem _ fun l _ => Ideal.mul_mem_right _ _ (c.x_mem_maximalIdeal l))
  rw [pow_two]
  exact Ideal.sum_mem _ fun l _ => Ideal.mul_mem_mul (ha l) (c.x_mem_maximalIdeal l)

/-- The Jacobian matrix `Mᵢⱼ = ∂ᵢ x'ⱼ` of a second family `x'` with respect to the coordinates
`c` (index convention in the module docstring). -/
def jacobian (x' : Fin n → R) : Matrix (Fin n) (Fin n) R :=
  Matrix.of fun i j => c.pderiv i (x' j)

@[simp]
theorem jacobian_apply (x' : Fin n → R) (i j : Fin n) : c.jacobian x' i j = c.pderiv i (x' j) :=
  rfl

/-- The derivations `∂'ⱼ = ∑ₗ (M⁻¹)ⱼₗ ∂ₗ` transported to a second family `x'`. -/
noncomputable def transportPderiv (x' : Fin n → R) : Fin n → Derivation ℚ R R :=
  fun j => ∑ l, (c.jacobian x')⁻¹ j l • c.pderiv l

theorem transportPderiv_apply (x' : Fin n → R) (j : Fin n) (f : R) :
    c.transportPderiv x' j f = ∑ l, (c.jacobian x')⁻¹ j l * c.pderiv l f := by
  rw [transportPderiv, derivation_sum_apply]
  simp only [Derivation.smul_apply, smul_eq_mul]

/-- If `x'` also generates the maximal ideal, the Jacobian matrix `∂ᵢ x'ⱼ` is invertible over
`R`.  Uses `dim R = n` (regularity) through the minimal number of generators of the maximal
ideal; see the module docstring for the argument. -/
theorem isUnit_jacobian (x' : Fin n → R) (hx' : maximalIdeal R = Ideal.span (Set.range x')) :
    IsUnit (c.jacobian x') := by
  classical
  have hx'm : ∀ j, x' j ∈ maximalIdeal R := fun j => by
    rw [hx']; exact Ideal.subset_span ⟨j, rfl⟩
  rw [Matrix.isUnit_iff_isUnit_det, ← residue_ne_zero_iff_isUnit, RingHom.map_det]
  intro hdet
  obtain ⟨v, hv0, hv⟩ := Matrix.exists_mulVec_eq_zero_iff.mpr hdet
  choose w hw using fun j => residue_surjective (R := R) (v j)
  obtain ⟨j₀, hj₀⟩ : ∃ j₀, v j₀ ≠ 0 := by
    by_contra h
    push Not at h
    exact hv0 (funext h)
  -- the element `y = ∑ wⱼ x'ⱼ` lies in `𝔪²`
  set y : R := ∑ j, w j * x' j with hy_def
  have hy : y ∈ maximalIdeal R := Ideal.sum_mem _ fun j _ => Ideal.mul_mem_left _ _ (hx'm j)
  have hdy : ∀ i, c.pderiv i y ∈ maximalIdeal R := by
    intro i
    have h1 : c.pderiv i y = ∑ j, w j * c.pderiv i (x' j) + ∑ j, x' j * c.pderiv i (w j) := by
      simp only [hy_def, map_sum, Derivation.leibniz, smul_eq_mul, Finset.sum_add_distrib]
    have h2 : ∑ j, w j * c.pderiv i (x' j) ∈ maximalIdeal R := by
      have hv' := congr_fun hv i
      simp only [Matrix.mulVec, dotProduct, RingHom.mapMatrix_apply, Matrix.map_apply,
        jacobian_apply, Pi.zero_apply] at hv'
      rw [← Ideal.Quotient.eq_zero_iff_mem]
      change residue R _ = 0
      rw [map_sum, ← hv']
      exact Finset.sum_congr rfl fun j _ => by rw [map_mul, hw, mul_comm]
    rw [h1]
    exact Ideal.add_mem _ h2 (Ideal.sum_mem _ fun j _ => Ideal.mul_mem_right _ _ (hx'm j))
  have hy2 := c.mem_maximalIdeal_sq_of_pderiv_mem hy hdy
  -- `wⱼ₀` is a unit, so `x'ⱼ₀ ∈ 𝔪² + ⟨x'ⱼ : j ≠ j₀⟩`
  have hu : IsUnit (w j₀) := (residue_ne_zero_iff_isUnit _).mp (by rw [hw]; exact hj₀)
  set N : Ideal R := Ideal.span (x' '' {j₀}ᶜ) with hN_def
  have hgen : Set.range x' ⊆ (N ⊔ maximalIdeal R • maximalIdeal R : Ideal R) := by
    rintro _ ⟨j, rfl⟩
    by_cases hj : j = j₀
    · subst hj
      have hrest : ∑ l ∈ Finset.univ.erase j, w l * x' l ∈ N :=
        Ideal.sum_mem _ fun l hl =>
          Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨l, Finset.ne_of_mem_erase hl, rfl⟩)
      have hsplit : w j * x' j = y - ∑ l ∈ Finset.univ.erase j, w l * x' l := by
        rw [hy_def, ← Finset.add_sum_erase _ _ (Finset.mem_univ j)]; ring
      have hmem : w j * x' j ∈ N ⊔ maximalIdeal R • maximalIdeal R := by
        rw [hsplit]
        refine Submodule.sub_mem _ (Ideal.mem_sup_right ?_) (Ideal.mem_sup_left hrest)
        rwa [Ideal.smul_eq_mul, ← pow_two]
      have := Ideal.mul_mem_left _ (↑hu.unit⁻¹ : R) hmem
      rwa [← mul_assoc, IsUnit.val_inv_mul, one_mul] at this
    · exact Ideal.mem_sup_left (Ideal.subset_span ⟨j, hj, rfl⟩)
  have hle : maximalIdeal R ≤ N ⊔ maximalIdeal R • maximalIdeal R :=
    hx'.le.trans (Ideal.span_le.mpr hgen)
  have hNle : maximalIdeal R ≤ N :=
    Submodule.le_of_le_smul_of_le_jacobson_bot (IsNoetherian.noetherian _)
      (le_of_eq (jacobson_eq_maximalIdeal (⊥ : Ideal R) bot_ne_top).symm) hle
  have hNeq : maximalIdeal R = N := by
    refine le_antisymm hNle ?_
    rw [hN_def, Ideal.span_le]
    rintro _ ⟨j, -, rfl⟩
    exact hx'm j
  -- the maximal ideal is generated by `n - 1` elements, contradicting `dim R = n`
  have hrank : (maximalIdeal R).spanFinrank ≤ n - 1 := by
    rw [hNeq, hN_def]
    refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.toFinite _)).trans ?_
    refine (Set.ncard_image_le (Set.toFinite _)).trans ?_
    rw [Set.ncard_compl, Set.ncard_singleton, Nat.card_fin]
  have hdim : (maximalIdeal R).spanFinrank = n := by
    have h := IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)
    rw [← c.card] at h
    exact_mod_cast h
  have hn : 0 < n := Fin.pos j₀
  omega

/-- The transported derivations satisfy `∂'ᵢ x'ⱼ = δᵢⱼ`. -/
theorem transportPderiv_x (x' : Fin n → R) (hx' : maximalIdeal R = Ideal.span (Set.range x'))
    (i j : Fin n) : c.transportPderiv x' i (x' j) = if i = j then 1 else 0 := by
  classical
  have hdet : IsUnit (c.jacobian x').det :=
    (Matrix.isUnit_iff_isUnit_det _).mp (c.isUnit_jacobian x' hx')
  rw [transportPderiv_apply]
  have := congr_fun (congr_fun (Matrix.nonsing_inv_mul _ hdet) i) j
  rw [Matrix.mul_apply, Matrix.one_apply] at this
  simpa [jacobian_apply] using this

/-- A second generating system `x'` of the maximal ideal, together with the transported
derivations, is again a coordinate structure, once the transported derivations are known to
commute (a hypothesis here; `changeCoordsOfSpans` derives it from `SpansDerivations`). -/
noncomputable def changeCoords (x' : Fin n → R) (hx' : maximalIdeal R = Ideal.span (Set.range x'))
    (hcomm : ∀ i j f, c.transportPderiv x' i (c.transportPderiv x' j f) =
      c.transportPderiv x' j (c.transportPderiv x' i f)) : RegularCoords R n where
  x := x'
  pderiv := c.transportPderiv x'
  span_x := hx'
  card := c.card
  pderiv_x := c.transportPderiv_x x' hx'
  pderiv_comm := hcomm

@[simp]
theorem changeCoords_x (x' : Fin n → R) (hx' : maximalIdeal R = Ideal.span (Set.range x'))
    (hcomm : ∀ i j f, c.transportPderiv x' i (c.transportPderiv x' j f) =
      c.transportPderiv x' j (c.transportPderiv x' i f)) :
    (c.changeCoords x' hx' hcomm).x = x' := rfl

@[simp]
theorem changeCoords_pderiv (x' : Fin n → R) (hx' : maximalIdeal R = Ideal.span (Set.range x'))
    (hcomm : ∀ i j f, c.transportPderiv x' i (c.transportPderiv x' j f) =
      c.transportPderiv x' j (c.transportPderiv x' i f)) :
    (c.changeCoords x' hx' hcomm).pderiv = c.transportPderiv x' := rfl

/-- The old derivations in terms of the transported ones: `∂ᵢ = ∑ⱼ Mᵢⱼ ∂'ⱼ`. -/
theorem pderiv_eq_sum_transportPderiv (x' : Fin n → R)
    (hx' : maximalIdeal R = Ideal.span (Set.range x')) (i : Fin n) :
    c.pderiv i = ∑ j, c.jacobian x' i j • c.transportPderiv x' j := by
  classical
  have hdet : IsUnit (c.jacobian x').det :=
    (Matrix.isUnit_iff_isUnit_det _).mp (c.isUnit_jacobian x' hx')
  have hmul := Matrix.mul_nonsing_inv _ hdet
  ext f
  rw [derivation_sum_apply]
  have h1 : ∀ j, (c.jacobian x' i j • c.transportPderiv x' j) f =
      ∑ l, c.jacobian x' i j * ((c.jacobian x')⁻¹ j l * c.pderiv l f) := by
    intro j
    rw [Derivation.smul_apply, smul_eq_mul, transportPderiv_apply, Finset.mul_sum]
  rw [Finset.sum_congr rfl fun j _ => h1 j, Finset.sum_comm]
  have h2 : ∀ l, ∑ j, c.jacobian x' i j * ((c.jacobian x')⁻¹ j l * c.pderiv l f) =
      (c.jacobian x' * (c.jacobian x')⁻¹) i l * c.pderiv l f := by
    intro l
    rw [Matrix.mul_apply, Finset.sum_mul]
    exact Finset.sum_congr rfl fun j _ => by ring
  rw [Finset.sum_congr rfl fun l _ => h2 l, hmul]
  simp [Matrix.one_apply]

/-- The `R`-submodule of `Derivation ℚ R R` spanned by the transported derivations equals that
spanned by the original ones. -/
theorem span_range_transportPderiv (x' : Fin n → R)
    (hx' : maximalIdeal R = Ideal.span (Set.range x')) :
    Submodule.span R (Set.range (c.transportPderiv x')) =
      Submodule.span R (Set.range c.pderiv) := by
  refine le_antisymm (Submodule.span_le.mpr ?_) (Submodule.span_le.mpr ?_)
  · rintro _ ⟨j, rfl⟩
    exact Submodule.sum_mem _ fun l _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨l, rfl⟩)
  · rintro _ ⟨i, rfl⟩
    rw [c.pderiv_eq_sum_transportPderiv x' hx' i]
    exact Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ (Submodule.subset_span ⟨j, rfl⟩)

/-- **The spanning condition** [Kol07, Definition 73], [Wlo05, Definition 2.6.1]: the partial
derivatives generate the derivations of `R` over the base `k`, `δ = ∑ᵢ δ(xᵢ) ∂ᵢ` for every
`k`-derivation `δ`.  Kollár takes the derivative ideal `D(I)` over all derivations and says the
`∂/∂xᵢ` generate them; here `D(I)` is defined with the fixed `∂ᵢ`
(`Hironaka/Algebra/Local/Derivative.lean`), and this predicate is what each instance supplies to
identify the two (for smooth stalks, freeness of `Ω_{X/k}` on the `dxᵢ`; for analytic germs,
uniqueness of Taylor coefficients). -/
def SpansDerivations (k : Type v) [CommRing k] [Algebra k R] : Prop :=
  ∀ (δ : Derivation k R R) (f : R), δ f = ∑ i, δ (c.x i) * c.pderiv i f

/-- The spanning identity in transported coordinates: if the `∂ᵢ` span the `ℚ`-derivations,
then so do the `∂'ⱼ` of a second generating system, `δ = ∑ₖ δ(x'ₖ) ∂'ₖ`.  (Proof:
`δ(x'ₖ) = ∑ₗ δ(xₗ) Mₗₖ` by the spanning identity, and `∑ₖ Mₗₖ (M⁻¹)ₖₚ = δₗₚ`.) -/
theorem SpansDerivations.transport (hs : c.SpansDerivations ℚ) (x' : Fin n → R)
    (hx' : maximalIdeal R = Ideal.span (Set.range x')) (δ : Derivation ℚ R R) (f : R) :
    δ f = ∑ k, δ (x' k) * c.transportPderiv x' k f := by
  classical
  have hdet : IsUnit (c.jacobian x').det :=
    (Matrix.isUnit_iff_isUnit_det _).mp (c.isUnit_jacobian x' hx')
  have hmul := Matrix.mul_nonsing_inv _ hdet
  have h1 : ∀ k, δ (x' k) = ∑ l, δ (c.x l) * c.jacobian x' l k := fun k => hs δ (x' k)
  calc δ f = ∑ l, δ (c.x l) * c.pderiv l f := hs δ f
    _ = ∑ l, ∑ p, δ (c.x l) * ((c.jacobian x' * (c.jacobian x')⁻¹) l p * c.pderiv p f) := by
        refine Finset.sum_congr rfl fun l _ => ?_
        rw [hmul]
        simp [Matrix.one_apply]
    _ = ∑ l, ∑ p, ∑ k, δ (c.x l) * c.jacobian x' l k * ((c.jacobian x')⁻¹ k p * c.pderiv p f) := by
        refine Finset.sum_congr rfl fun l _ => Finset.sum_congr rfl fun p _ => ?_
        rw [Matrix.mul_apply, Finset.sum_mul, Finset.mul_sum]
        exact Finset.sum_congr rfl fun k _ => by ring
    _ = ∑ l, ∑ k, ∑ p, δ (c.x l) * c.jacobian x' l k * ((c.jacobian x')⁻¹ k p * c.pderiv p f) :=
        Finset.sum_congr rfl fun l _ => Finset.sum_comm
    _ = ∑ k, ∑ l, ∑ p, δ (c.x l) * c.jacobian x' l k * ((c.jacobian x')⁻¹ k p * c.pderiv p f) :=
        Finset.sum_comm
    _ = ∑ k, δ (x' k) * c.transportPderiv x' k f := by
        refine Finset.sum_congr rfl fun k _ => ?_
        rw [h1, transportPderiv_apply, Finset.sum_mul_sum]

/-- If the `∂ᵢ` span the `ℚ`-derivations, the transported derivations of a second generating
system commute — their commutator is a derivation killing every `x'ₖ`, hence zero by the
spanning identity.  This discharges the commutation hypothesis of `changeCoords` for every
coordinate structure with spanning derivations. -/
theorem transportPderiv_comm (hs : c.SpansDerivations ℚ) (x' : Fin n → R)
    (hx' : maximalIdeal R = Ideal.span (Set.range x')) (i j : Fin n) (f : R) :
    c.transportPderiv x' i (c.transportPderiv x' j f) =
      c.transportPderiv x' j (c.transportPderiv x' i f) := by
  have hδ : ∀ k, ⁅c.transportPderiv x' i, c.transportPderiv x' j⁆ (x' k) = 0 := by
    intro k
    rw [Derivation.commutator_apply, c.transportPderiv_x x' hx', c.transportPderiv_x x' hx']
    split_ifs <;> simp
  have := SpansDerivations.transport c hs x' hx' ⁅c.transportPderiv x' i, c.transportPderiv x' j⁆ f
  simp only [hδ, zero_mul, Finset.sum_const_zero] at this
  rw [Derivation.commutator_apply] at this
  exact sub_eq_zero.mp this

/-- Change of coordinates for a structure whose derivations span: no commutation hypothesis is
needed. -/
noncomputable def changeCoordsOfSpans (hs : c.SpansDerivations ℚ) (x' : Fin n → R)
    (hx' : maximalIdeal R = Ideal.span (Set.range x')) : RegularCoords R n :=
  c.changeCoords x' hx' (c.transportPderiv_comm hs x' hx')

/-- The transported coordinate structure again has spanning derivations. -/
theorem spansDerivations_changeCoords (hs : c.SpansDerivations ℚ) (x' : Fin n → R)
    (hx' : maximalIdeal R = Ideal.span (Set.range x'))
    (hcomm : ∀ i j f, c.transportPderiv x' i (c.transportPderiv x' j f) =
      c.transportPderiv x' j (c.transportPderiv x' i f)) :
    (c.changeCoords x' hx' hcomm).SpansDerivations ℚ :=
  fun δ f => SpansDerivations.transport c hs x' hx' δ f

end RegularCoords

end IsLocalRing
