/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.Coords
public import Hironaka.Algebra.Local.Marked

/-!
# Derivative ideals

On a smooth scheme the *first derivative* `D(I)` of an ideal sheaf `I` is the ideal generated by
all derivatives of elements of `I`, and `Dʳ⁺¹(I) := D(Dʳ(I))`; in local coordinates
`D(f₁, …, fₛ) = (fᵢ, ∂fᵢ/∂xⱼ)` [Kol07, Definition 73].  Here, for a regular local ring `R ⊇ ℚ`
with a coordinate structure `c` (`Hironaka/Algebra/Local/Coords.lean`), the derivative ideal is
defined with the fixed derivations `c.pderiv i`; the spanning condition `c.SpansDerivations` (the
`∂ᵢ` span all derivations) identifies it with Kollár's coordinate-free definition (`Dimg_eq_D`).

## Main declarations

* `RegularCoords.D`, `RegularCoords.Dpow`, and `RegularCoords.markedD`, the marked derivative
  `Dʳ(I, m) = (Dʳ I, m - r)` of [Kol07, Definition 73, (73.3)].
* `le_D`, `D_le_iff`, `pderiv_mem_D`, `D_mono`, `Dpow_mono`, `Dpow_mono_left`, `le_Dpow`;
  `D_span`, `Dpow_span` (generators and iterated partials); `D_sup`, `D_iSup`;
  `D_changeCoords` (independence of the coordinates); `D_mul_le` (the product rule of
  [Kol07, Lemma 74(2)] for `r = 1`); `D_maximalIdeal_pow`, `Dpow_maximalIdeal_pow`; `Dimg_eq_D`.
* `Dpow_eq_top_of_ord_le`: `ord I ≤ m → Dᵐ(I) = R`, Kollár's remark that the `Dʳ(I)` form an
  ascending chain ending in `𝒪_X` [Kol07, Definition 73].
* The local forms of [Kol07, Lemma 74]: `Dpow_Dpow` (iteration, (1)), `Dpow_mul_le` (the
  product rule, (2)), `le_ord_iff_le_ord_Dpow` (the order under derivatives, (3),
  characteristic zero only), `D_map` (compatibility with a ring map compatible with the
  coordinates, the local content of (4)); and the Euler identity `euler_sub_nsmul_mem`
  behind (3).

That the top-order partials alone generate `Dʳ(I)` in characteristic zero (Kollár's
parenthetical remark in Definition 73) is proved in `Hironaka/Algebra/Local/TopPartials.lean`.
-/

@[expose] public section

namespace IsLocalRing.RegularCoords

open IsLocalRing

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ}
  (c : RegularCoords R n)

/-- **The first derivative ideal** [Kol07, Definition 73, (73.1)]: the ideal generated by `I` and
all `∂ᵢ f`, `f ∈ I`. -/
def D (I : Ideal R) : Ideal R :=
  I ⊔ ⨆ i, Ideal.span ((c.pderiv i) '' I)

/-- `I ≤ D(I)` (built into the definition). -/
theorem le_D (I : Ideal R) : I ≤ c.D I := le_sup_left

theorem pderiv_mem_D {I : Ideal R} {f : R} (hf : f ∈ I) (i : Fin n) : c.pderiv i f ∈ c.D I :=
  Ideal.mem_sup_right (Submodule.mem_iSup_of_mem i (Ideal.subset_span ⟨f, hf, rfl⟩))

theorem D_le_iff {I J : Ideal R} : c.D I ≤ J ↔ I ≤ J ∧ ∀ i, ∀ g ∈ I, c.pderiv i g ∈ J := by
  constructor
  · intro h
    exact ⟨(c.le_D I).trans h, fun i g hg => h (c.pderiv_mem_D hg i)⟩
  · rintro ⟨hIJ, hd⟩
    refine sup_le hIJ (iSup_le fun i => Ideal.span_le.mpr ?_)
    rintro _ ⟨g, hg, rfl⟩
    exact hd i g hg

/-- `D` is monotone. -/
theorem D_mono {I J : Ideal R} (h : I ≤ J) : c.D I ≤ c.D J :=
  c.D_le_iff.mpr ⟨h.trans (c.le_D J), fun i _ hf => c.pderiv_mem_D (h hf) i⟩

theorem D_top : c.D ⊤ = ⊤ := top_le_iff.mp (c.le_D ⊤)

/-- **Higher derivative ideals** [Kol07, Definition 73, (73.2)]: `D⁰(I) = I`,
`Dʳ⁺¹(I) = D(Dʳ(I))`. -/
def Dpow (r : ℕ) (I : Ideal R) : Ideal R :=
  (c.D)^[r] I

@[simp] theorem Dpow_zero (I : Ideal R) : c.Dpow 0 I = I := rfl

@[simp] theorem Dpow_succ (r : ℕ) (I : Ideal R) : c.Dpow (r + 1) I = c.D (c.Dpow r I) :=
  Function.iterate_succ_apply' _ _ _

theorem Dpow_succ' (r : ℕ) (I : Ideal R) : c.Dpow (r + 1) I = c.Dpow r (c.D I) :=
  Function.iterate_succ_apply _ _ _

theorem Dpow_one (I : Ideal R) : c.Dpow 1 I = c.D I := rfl

/-- `Dʳ` is monotone in the ideal. -/
theorem Dpow_mono (r : ℕ) {I J : Ideal R} (h : I ≤ J) : c.Dpow r I ≤ c.Dpow r J := by
  induction r with
  | zero => exact h
  | succ r ih => rw [Dpow_succ, Dpow_succ]; exact c.D_mono ih

theorem le_Dpow (r : ℕ) (I : Ideal R) : I ≤ c.Dpow r I := by
  induction r with
  | zero => exact le_rfl
  | succ r ih => rw [Dpow_succ]; exact ih.trans (c.le_D _)

/-- The ascending chain `I ⊆ D(I) ⊆ D²(I) ⊆ ⋯` of [Kol07, Definition 73]: `Dʳ(I) ≤ Dʳ'(I)` for
`r ≤ r'`. -/
theorem Dpow_mono_left {r r' : ℕ} (h : r ≤ r') (I : Ideal R) : c.Dpow r I ≤ c.Dpow r' I := by
  induction r', h using Nat.le_induction with
  | base => exact le_rfl
  | succ r' _ ih => rw [Dpow_succ]; exact ih.trans (c.le_D _)

/-- `D(⟨S⟩)` is generated by `S` and the `∂ⱼ s`, `s ∈ S` (Leibniz: `∂ⱼ(a s) = a ∂ⱼ s + s ∂ⱼ a`):
Kollár's `D(f₁, …, fₛ) = (fᵢ, ∂fᵢ/∂xⱼ)` [Kol07, Definition 73]. -/
theorem D_span (S : Set R) :
    c.D (Ideal.span S) = Ideal.span (S ∪ ⋃ i, c.pderiv i '' S) := by
  refine le_antisymm (c.D_le_iff.mpr ⟨Ideal.span_mono Set.subset_union_left, ?_⟩) ?_
  · intro i f hf
    induction hf using Submodule.span_induction with
    | mem f hf =>
      exact Ideal.subset_span (Set.mem_union_right _ (Set.mem_iUnion.mpr ⟨i, f, hf, rfl⟩))
    | zero => simp
    | add f g _ _ hf hg => rw [map_add]; exact Ideal.add_mem _ hf hg
    | smul a f hf' hf =>
      rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ hf) (Ideal.mul_mem_right _ _ ?_)
      exact Ideal.span_mono Set.subset_union_left hf'
  · rw [Ideal.span_le]
    rintro f (hf | hf)
    · exact c.le_D _ (Ideal.subset_span hf)
    · obtain ⟨i, hi⟩ := Set.mem_iUnion.mp hf
      obtain ⟨s, hs, rfl⟩ := hi
      exact c.pderiv_mem_D (Ideal.subset_span hs) i

/-- The iterated partial derivative along a list of indices, `∂_{i₁} ⋯ ∂_{iₖ} f`. -/
def iterPderiv (l : List (Fin n)) (f : R) : R :=
  l.foldr (fun i g => c.pderiv i g) f

@[simp] theorem iterPderiv_nil (f : R) : c.iterPderiv [] f = f := rfl

@[simp] theorem iterPderiv_cons (i : Fin n) (l : List (Fin n)) (f : R) :
    c.iterPderiv (i :: l) f = c.pderiv i (c.iterPderiv l f) := rfl

/-- The iterated partials of order at most `r` of the elements of `S`. -/
def iterPderivSet (S : Set R) (r : ℕ) : Set R :=
  ⋃ (l : List (Fin n)) (_ : l.length ≤ r), c.iterPderiv l '' S

theorem mem_iterPderivSet {S : Set R} {r : ℕ} {f : R} :
    f ∈ c.iterPderivSet S r ↔ ∃ l : List (Fin n), l.length ≤ r ∧ ∃ s ∈ S, c.iterPderiv l s = f := by
  simp [iterPderivSet]

theorem iterPderivSet_zero (S : Set R) : c.iterPderivSet S 0 = S := by
  ext f
  rw [mem_iterPderivSet]
  constructor
  · rintro ⟨l, hl, s, hs, rfl⟩
    rw [List.length_eq_zero_iff.mp (Nat.le_zero.mp hl), iterPderiv_nil]
    exact hs
  · intro hf
    exact ⟨[], le_rfl, f, hf, rfl⟩

theorem iterPderivSet_succ (S : Set R) (r : ℕ) :
    c.iterPderivSet S (r + 1) = c.iterPderivSet S r ∪ ⋃ i, c.pderiv i '' c.iterPderivSet S r := by
  ext f
  rw [mem_iterPderivSet, Set.mem_union, mem_iterPderivSet, Set.mem_iUnion]
  constructor
  · rintro ⟨l, hl, s, hs, rfl⟩
    cases l with
    | nil => exact Or.inl ⟨[], by simp, s, hs, rfl⟩
    | cons i l =>
      refine Or.inr ⟨i, c.iterPderiv l s, ?_, rfl⟩
      exact c.mem_iterPderivSet.mpr ⟨l, by simpa using hl, s, hs, rfl⟩
  · rintro (⟨l, hl, s, hs, rfl⟩ | ⟨i, g, hg, rfl⟩)
    · exact ⟨l, hl.trans (Nat.le_succ r), s, hs, rfl⟩
    · obtain ⟨l, hl, s, hs, rfl⟩ := c.mem_iterPderivSet.mp hg
      exact ⟨i :: l, by simpa using hl, s, hs, rfl⟩

/-- `Dʳ(⟨S⟩)` is generated by the iterated partials of order at most `r` of the elements of `S`
[Wlo05, Definition 2.6.1]; compare the parenthetical remark in [Kol07, Definition 73]. -/
theorem Dpow_span (S : Set R) (r : ℕ) :
    c.Dpow r (Ideal.span S) = Ideal.span (c.iterPderivSet S r) := by
  induction r with
  | zero => rw [Dpow_zero, iterPderivSet_zero]
  | succ r ih => rw [Dpow_succ, ih, D_span, iterPderivSet_succ]

/-- `D` commutes with finite sums of ideals. -/
theorem D_sup (I J : Ideal R) : c.D (I ⊔ J) = c.D I ⊔ c.D J := by
  refine le_antisymm (c.D_le_iff.mpr ⟨sup_le_sup (c.le_D I) (c.le_D J), ?_⟩)
    (sup_le (c.D_mono le_sup_left) (c.D_mono le_sup_right))
  intro i f hf
  obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp hf
  rw [map_add]
  exact Ideal.add_mem _ (Ideal.mem_sup_left (c.pderiv_mem_D ha i))
    (Ideal.mem_sup_right (c.pderiv_mem_D hb i))

/-- `D` commutes with arbitrary sums of ideals. -/
theorem D_iSup {ι : Sort*} (I : ι → Ideal R) : c.D (⨆ k, I k) = ⨆ k, c.D (I k) := by
  refine le_antisymm (c.D_le_iff.mpr ⟨iSup_le fun k =>
      (c.le_D (I k)).trans (le_iSup (fun k => c.D (I k)) k), ?_⟩)
    (iSup_le fun k => c.D_mono (le_iSup I k))
  intro i f hf
  induction hf using Submodule.iSup_induction' with
  | mem k f hf => exact Submodule.mem_iSup_of_mem k (c.pderiv_mem_D hf i)
  | zero => simp
  | add f g _ _ hf hg => rw [map_add]; exact Ideal.add_mem _ hf hg

/-- The derivative ideal does not depend on the coordinate structure (Kollár's definition
[Kol07, Definition 73] is coordinate-free). -/
theorem D_changeCoords (x' : Fin n → R) (hx' : maximalIdeal R = Ideal.span (Set.range x'))
    (hcomm : ∀ i j f, c.transportPderiv x' i (c.transportPderiv x' j f) =
      c.transportPderiv x' j (c.transportPderiv x' i f)) (I : Ideal R) :
    (c.changeCoords x' hx' hcomm).D I = c.D I := by
  classical
  refine le_antisymm ((c.changeCoords x' hx' hcomm).D_le_iff.mpr ⟨c.le_D I, ?_⟩)
    (c.D_le_iff.mpr ⟨(c.changeCoords x' hx' hcomm).le_D I, ?_⟩)
  · intro j f hf
    rw [changeCoords_pderiv, transportPderiv_apply]
    exact Ideal.sum_mem _ fun l _ => Ideal.mul_mem_left _ _ (c.pderiv_mem_D hf l)
  · intro i f hf
    have h := congrArg (fun δ : Derivation ℚ R R => δ f) (c.pderiv_eq_sum_transportPderiv x' hx' i)
    simp only [derivation_sum_apply, Derivation.smul_apply, smul_eq_mul] at h
    rw [h]
    exact Ideal.sum_mem _ fun j _ =>
      Ideal.mul_mem_left _ _ (by
        have := (c.changeCoords x' hx' hcomm).pderiv_mem_D hf j
        rwa [changeCoords_pderiv] at this)

/-- The product rule for derivative ideals, `D(IJ) ≤ D(I) J + I D(J)`: [Kol07, Lemma 74(2)] for
`r = 1`, [BM08, Lemma 3.2(2)]. -/
theorem D_mul_le (I J : Ideal R) : c.D (I * J) ≤ c.D I * J ⊔ I * c.D J := by
  refine c.D_le_iff.mpr ⟨le_sup_left.trans' (Ideal.mul_mono (c.le_D I) le_rfl), ?_⟩
  intro i f hf
  refine Submodule.mul_induction_on hf (fun a ha b hb => ?_) (fun f g hf hg => ?_)
  · rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    exact Ideal.add_mem _ (Ideal.mem_sup_right (Ideal.mul_mem_mul ha (c.pderiv_mem_D hb i)))
      (Ideal.mem_sup_left (mul_comm b _ ▸ Ideal.mul_mem_mul (c.pderiv_mem_D ha i) hb))
  · rw [map_add]
    exact Ideal.add_mem _ hf hg

/-- `D(𝔪^(a+1)) ≤ 𝔪^a`, by the product rule. -/
theorem D_maximalIdeal_pow_succ (a : ℕ) :
    c.D (maximalIdeal R ^ (a + 1)) ≤ maximalIdeal R ^ a := by
  induction a with
  | zero => rw [pow_zero, Ideal.one_eq_top]; exact le_top
  | succ a ih =>
    calc c.D (maximalIdeal R ^ (a + 2)) = c.D (maximalIdeal R * maximalIdeal R ^ (a + 1)) := by
          rw [pow_succ']
      _ ≤ c.D (maximalIdeal R) * maximalIdeal R ^ (a + 1) ⊔
          maximalIdeal R * c.D (maximalIdeal R ^ (a + 1)) := c.D_mul_le _ _
      _ ≤ maximalIdeal R ^ (a + 1) ⊔ maximalIdeal R * maximalIdeal R ^ a :=
          sup_le_sup (Ideal.mul_le_right) (Ideal.mul_mono le_rfl ih)
      _ = maximalIdeal R ^ (a + 1) := by rw [← pow_succ', sup_idem]

/-- `D(𝔪^a) ≤ 𝔪^(a-1)` for `a ≥ 1` (and `D(𝔪^0) = R`, `D_maximalIdeal_pow_zero`). -/
theorem D_maximalIdeal_pow {a : ℕ} (ha : 1 ≤ a) :
    c.D (maximalIdeal R ^ a) ≤ maximalIdeal R ^ (a - 1) := by
  obtain ⟨b, rfl⟩ : ∃ b, a = b + 1 := ⟨a - 1, by omega⟩
  simpa using c.D_maximalIdeal_pow_succ b

theorem D_maximalIdeal_pow_zero : c.D (maximalIdeal R ^ 0) = ⊤ := by
  rw [pow_zero, Ideal.one_eq_top, D_top]

/-- `Dʳ(𝔪^a) ≤ 𝔪^(a-r)` for `r ≤ a`. -/
theorem Dpow_maximalIdeal_pow {r a : ℕ} (h : r ≤ a) :
    c.Dpow r (maximalIdeal R ^ a) ≤ maximalIdeal R ^ (a - r) := by
  induction r with
  | zero => simp
  | succ r ih =>
    rw [Dpow_succ]
    calc c.D (c.Dpow r (maximalIdeal R ^ a)) ≤ c.D (maximalIdeal R ^ (a - r)) :=
          c.D_mono (ih (Nat.le_of_succ_le h))
      _ ≤ maximalIdeal R ^ (a - r - 1) := c.D_maximalIdeal_pow (by omega)
      _ = maximalIdeal R ^ (a - (r + 1)) := by rw [Nat.sub_sub]

/-- "If `max-ord I ≤ m`, then `Dᵐ(I) = 𝒪_X`" [Kol07, Definition 73], in the local form
`ord I ≤ m → Dᵐ(I) = R`, conditional on the order statement (3) of [Kol07, Lemma 74], which is
proved below (`le_ord_iff_le_ord_Dpow`); `Dpow_eq_top_of_ord_le` is the unconditional form. -/
theorem Dpow_eq_top_of_ord_le_of_forall
    (h74 : ∀ (I : Ideal R) {r m : ℕ}, r < m →
      ((m : ℕ∞) ≤ ord I ↔ ((m - r : ℕ) : ℕ∞) ≤ ord (c.Dpow r I)))
    {I : Ideal R} {m : ℕ} (hord : ord I ≤ m) : c.Dpow m I = ⊤ := by
  by_contra hne
  have h1 : (1 : ℕ∞) ≤ ord (c.Dpow m I) :=
    Order.one_le_iff_ne_zero.mpr fun h0 => hne (ord_eq_zero_iff.mp h0)
  have h2 : ((m + 1 : ℕ) : ℕ∞) ≤ ord I :=
    (h74 I (r := m) (m := m + 1) (Nat.lt_succ_self m)).mpr (by simpa using h1)
  have h3 : ((m + 1 : ℕ) : ℕ∞) ≤ (m : ℕ∞) := h2.trans hord
  exact absurd (by exact_mod_cast h3 : m + 1 ≤ m) (by omega)

/-- **The marked derivative** [Kol07, Definition 73, (73.3)]: `Dʳ(I, m) := (Dʳ(I), m - r)` for
`r ≤ m`. -/
def markedD (J : MarkedIdeal R) (r : ℕ) (_ : r ≤ J.m) : MarkedIdeal R :=
  ⟨c.Dpow r J.I, J.m - r⟩

@[simp] theorem markedD_I (J : MarkedIdeal R) (r : ℕ) (h : r ≤ J.m) :
    (c.markedD J r h).I = c.Dpow r J.I := rfl

@[simp] theorem markedD_m (J : MarkedIdeal R) (r : ℕ) (h : r ≤ J.m) :
    (c.markedD J r h).m = J.m - r := rfl

/-! ### Kollár's image definition

Kollár defines `D(I)` as the image of `Der_X × I → 𝒪_X` over all derivations
[Kol07, Definition 73, (73.1)], and notes `I ⊂ D(I)` through `f = ∂(x f) - x ∂f`.  With the fixed
`∂ᵢ` the inclusion is built in; the two definitions agree once the `∂ᵢ` span the derivations
(`SpansDerivations`) and a coordinate exists. -/

/-- Kollár's definition of the derivative ideal: the ideal generated by `δ f` for all
`ℚ`-derivations `δ` and all `f ∈ I` [Kol07, Definition 73, (73.1)]; it does not refer to
coordinates. -/
def _root_.IsLocalRing.Dimg (I : Ideal R) : Ideal R :=
  ⨆ δ : Derivation ℚ R R, Ideal.span (δ '' I)

/-- When the `∂ᵢ` span the derivations and there is at least one coordinate, Kollár's image
definition agrees with `D`; the inclusion `I ≤ Dimg I` is Kollár's `f = ∂₁(x₁ f) - x₁ ∂₁ f`
[Kol07, Definition 73]. -/
theorem Dimg_eq_D (hs : c.SpansDerivations ℚ) (hn : n ≠ 0) (I : Ideal R) : Dimg I = c.D I := by
  refine le_antisymm (iSup_le fun δ => Ideal.span_le.mpr ?_) (sup_le ?_ (iSup_le fun i => ?_))
  · rintro _ ⟨f, hf, rfl⟩
    rw [hs δ f]
    exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_left _ _ (c.pderiv_mem_D hf i)
  · intro f hf
    obtain ⟨i⟩ : Nonempty (Fin n) := ⟨⟨0, Nat.pos_of_ne_zero hn⟩⟩
    have key : f = c.pderiv i (c.x i * f) - c.x i * c.pderiv i f := by
      rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x, if_pos rfl, mul_one]
      ring
    rw [key]
    refine Ideal.sub_mem _ ?_ (Ideal.mul_mem_left _ _ ?_)
    · exact Submodule.mem_iSup_of_mem (c.pderiv i)
        (Ideal.subset_span ⟨c.x i * f, Ideal.mul_mem_left _ _ hf, rfl⟩)
    · exact Submodule.mem_iSup_of_mem (c.pderiv i) (Ideal.subset_span ⟨f, hf, rfl⟩)
  · exact le_iSup (fun δ : Derivation ℚ R R => Ideal.span (δ '' I)) (c.pderiv i)

/-! ### Kollár's Lemma 74

Kollár: "Higher derivatives have the usual properties" [Kol07, Lemma 74], stated without proof
(likewise [Wlo05, Lemma 2.6.2] and [BM08, Lemma 3.2]).  Item (1) is iteration; (2) is Leibniz;
(3) rests on the Euler identity `∑ᵢ xᵢ ∂ᵢ f ≡ a f (mod 𝔪^(a+1))` for `f ∈ 𝔪^a`, and on `a`
being a unit in characteristic zero; (4) in local form is a computation on generators. -/

section Lemma74

/-- `Dʳ (Dˢ I) = Dʳ⁺ˢ I` [Kol07, Lemma 74(1)]. -/
theorem Dpow_Dpow (r s : ℕ) (I : Ideal R) : c.Dpow r (c.Dpow s I) = c.Dpow (r + s) I :=
  (Function.iterate_add_apply _ _ _ _).symm

/-- The product rule `Dʳ (I J) ≤ ∑_{i ≤ r} Dⁱ I · Dʳ⁻ⁱ J` [Kol07, Lemma 74(2)]. -/
theorem Dpow_mul_le (r : ℕ) (I J : Ideal R) :
    c.Dpow r (I * J) ≤ ⨆ i ∈ Finset.range (r + 1), c.Dpow i I * c.Dpow (r - i) J := by
  induction r with
  | zero => exact le_iSup₂_of_le 0 (Finset.mem_range.mpr Nat.zero_lt_one) le_rfl
  | succ r ih =>
    rw [Dpow_succ]
    calc c.D (c.Dpow r (I * J))
        ≤ c.D (⨆ i ∈ Finset.range (r + 1), c.Dpow i I * c.Dpow (r - i) J) := c.D_mono ih
      _ = ⨆ i ∈ Finset.range (r + 1), c.D (c.Dpow i I * c.Dpow (r - i) J) := by
          rw [D_iSup]
          exact iSup_congr fun i => c.D_iSup _
      _ ≤ ⨆ i ∈ Finset.range (r + 1 + 1), c.Dpow i I * c.Dpow (r + 1 - i) J := by
          refine iSup₂_le fun i hi => ?_
          have hi' : i ≤ r := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
          refine (c.D_mul_le _ _).trans (sup_le ?_ ?_)
          · rw [← Dpow_succ, show r - i = r + 1 - (i + 1) by omega]
            exact le_iSup₂_of_le (i + 1) (Finset.mem_range.mpr (by omega)) le_rfl
          · rw [← Dpow_succ, show r - i + 1 = r + 1 - i by omega]
            exact le_iSup₂_of_le i (Finset.mem_range.mpr (by omega)) le_rfl

/-- `D (J^k) ≤ D J · J^(k-1)` for `k ≥ 1` (the product rule as used in the proof of
[Kol07, Proposition 99]). -/
theorem D_pow_le (J : Ideal R) {k : ℕ} (hk : 1 ≤ k) : c.D (J ^ k) ≤ c.D J * J ^ (k - 1) := by
  induction k, hk using Nat.le_induction with
  | base => simp
  | succ k hk ih =>
    rw [pow_succ']
    refine (c.D_mul_le _ _).trans (sup_le ?_ ?_)
    · simp
    · calc J * c.D (J ^ k) ≤ J * (c.D J * J ^ (k - 1)) := Ideal.mul_mono le_rfl ih
        _ = c.D J * J ^ (k + 1 - 1) := by
            rw [mul_left_comm, ← pow_succ', Nat.add_sub_cancel, Nat.sub_add_cancel hk]

/-- The product rule for a nonempty finite product of ideals. -/
theorem D_finset_prod_le {ι : Type*} [DecidableEq ι] {s : Finset ι} (hs : s.Nonempty)
    (J : ι → Ideal R) :
    c.D (∏ k ∈ s, J k) ≤ ⨆ k ∈ s, c.D (J k) * ∏ l ∈ s.erase k, J l := by
  induction hs using Finset.Nonempty.cons_induction with
  | singleton a =>
    refine le_iSup₂_of_le a (Finset.mem_singleton_self a) ?_
    simp
  | cons a s ha hs ih =>
    rw [Finset.prod_cons]
    refine (c.D_mul_le _ _).trans (sup_le ?_ ?_)
    · refine le_iSup₂_of_le a (Finset.mem_cons_self a s) ?_
      rw [Finset.erase_cons]
    · calc J a * c.D (∏ k ∈ s, J k)
          ≤ J a * ⨆ k ∈ s, c.D (J k) * ∏ l ∈ s.erase k, J l := Ideal.mul_mono le_rfl ih
        _ = ⨆ k ∈ s, J a * (c.D (J k) * ∏ l ∈ s.erase k, J l) := by
            rw [Ideal.mul_iSup]
            exact iSup_congr fun k => Ideal.mul_iSup _ _
        _ ≤ ⨆ k ∈ Finset.cons a s ha, c.D (J k) * ∏ l ∈ (Finset.cons a s ha).erase k, J l := by
            refine iSup₂_le fun k hk => ?_
            have hak : a ≠ k := fun h => ha (h ▸ hk)
            refine le_iSup₂_of_le k (Finset.mem_cons_of_mem hk) ?_
            rw [Finset.erase_cons_of_ne ha hak, Finset.prod_cons, mul_left_comm]

/-- The product rule for a nonempty finite product of powers with positive exponents.  (A sum
over the `k` with `cₖ ≥ 1` would be false when every exponent vanishes, since `D R = R`; the
restriction to the support of the exponent vector is left to the caller.) -/
theorem D_finset_prod_pow_le {ι : Type*} [DecidableEq ι] (s : Finset ι) (hs : s.Nonempty)
    (J : ι → Ideal R) (e : ι → ℕ) (he : ∀ k ∈ s, 1 ≤ e k) :
    c.D (∏ k ∈ s, J k ^ e k) ≤
      ⨆ k ∈ s, c.D (J k) * J k ^ (e k - 1) * ∏ l ∈ s.erase k, J l ^ e l := by
  refine (c.D_finset_prod_le hs fun k => J k ^ e k).trans (iSup₂_le fun k hk => ?_)
  exact le_iSup₂_of_le k hk (Ideal.mul_mono (c.D_pow_le (J k) (he k hk)) le_rfl)

/-- The easy inclusion of [Kol07, Lemma 74(3)]: `m ≤ ord I` implies `m - r ≤ ord (Dʳ I)` for
`r ≤ m`, from `Dʳ(𝔪^m) ≤ 𝔪^(m-r)`. -/
theorem le_ord_Dpow {I : Ideal R} {m r : ℕ} (hm : (m : ℕ∞) ≤ ord I) (hr : r ≤ m) :
    ((m - r : ℕ) : ℕ∞) ≤ ord (c.Dpow r I) :=
  le_ord_iff.mpr ((c.Dpow_mono r (le_ord_iff.mp hm)).trans (c.Dpow_maximalIdeal_pow hr))

/-! #### The Euler identity -/

/-- The Euler operator `∑ᵢ xᵢ ∂ᵢ`. -/
noncomputable def euler : Derivation ℚ R R := ∑ i, c.x i • c.pderiv i

theorem euler_apply (f : R) : c.euler f = ∑ i, c.x i * c.pderiv i f := by
  rw [euler, derivation_sum_apply]
  simp only [Derivation.smul_apply, smul_eq_mul]

theorem euler_x (i : Fin n) : c.euler (c.x i) = c.x i := by
  classical
  rw [euler_apply]
  simp [c.pderiv_x, eq_comm]

theorem euler_mem_maximalIdeal (f : R) : c.euler f ∈ maximalIdeal R := by
  rw [euler_apply]
  exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_right _ _ (c.x_mem_maximalIdeal i)

/-- `E h ≡ h (mod 𝔪²)` for `h ∈ 𝔪` (Euler's identity in degree one). -/
theorem euler_sub_self_mem_sq {h : R} (hh : h ∈ maximalIdeal R) :
    c.euler h - h ∈ maximalIdeal R ^ 2 := by
  rw [c.span_x] at hh
  induction hh using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    rw [euler_x, sub_self]
    exact zero_mem _
  | zero => simp
  | add x y _ _ hx hy =>
    rw [map_add]
    convert Ideal.add_mem _ hx hy using 1
    ring
  | smul r x hx' hx =>
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    have : r * c.euler x + x * c.euler r - r * x = r * (c.euler x - x) + x * c.euler r := by ring
    rw [this]
    refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ hx) ?_
    rw [pow_two]
    exact Ideal.mul_mem_mul (by rw [c.span_x]; exact hx') (c.euler_mem_maximalIdeal r)

/-- **The Euler identity**: `E f ≡ a f (mod 𝔪^(a+1))` for `f ∈ 𝔪^a`, `a ≥ 1`. -/
theorem euler_sub_nsmul_mem {a : ℕ} (ha : 1 ≤ a) {f : R} (hf : f ∈ maximalIdeal R ^ a) :
    c.euler f - (a : R) * f ∈ maximalIdeal R ^ (a + 1) := by
  induction a, ha using Nat.le_induction generalizing f with
  | base =>
    rw [pow_one] at hf
    simpa using c.euler_sub_self_mem_sq hf
  | succ a _ ih =>
    rw [pow_succ] at hf
    refine Submodule.mul_induction_on hf (fun g hg h hh => ?_) (fun x y hx hy => ?_)
    · rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      have : g * c.euler h + h * c.euler g - ((a + 1 : ℕ) : R) * (g * h) =
          g * (c.euler h - h) + h * (c.euler g - (a : R) * g) := by
        push_cast
        ring
      rw [this]
      refine Ideal.add_mem _ ?_ ?_
      · rw [show a + 1 + 1 = a + 2 by ring, pow_add]
        exact Ideal.mul_mem_mul hg (c.euler_sub_self_mem_sq hh)
      · rw [pow_succ']
        exact Ideal.mul_mem_mul hh (ih hg)
    · rw [map_add]
      convert Ideal.add_mem _ hx hy using 1
      ring

/-- An element of `𝔪^a ∖ 𝔪^(a+1)`, `a ≥ 1`, has a partial derivative outside `𝔪^a` (the
characteristic-zero fact behind [Kol07, Lemma 74(3)], "char. 0 only!", and
[Wlo05, Lemma 2.6.2]).  If all `∂ᵢ f ∈ 𝔪^a` then `E f ∈ 𝔪^(a+1)`, so `a f ∈ 𝔪^(a+1)` by the
Euler identity, and `a` is a unit. -/
theorem exists_pderiv_notMem_of_notMem_pow_succ {a : ℕ} (ha : 1 ≤ a) {f : R}
    (hf : f ∈ maximalIdeal R ^ a) (hf' : f ∉ maximalIdeal R ^ (a + 1)) :
    ∃ i, c.pderiv i f ∉ maximalIdeal R ^ a := by
  by_contra h
  push Not at h
  apply hf'
  have hE : c.euler f ∈ maximalIdeal R ^ (a + 1) := by
    rw [euler_apply, pow_succ']
    exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_mul (c.x_mem_maximalIdeal i) (h i)
  have haf : (a : R) * f ∈ maximalIdeal R ^ (a + 1) := by
    have := Ideal.sub_mem _ hE (c.euler_sub_nsmul_mem ha hf)
    rwa [sub_sub_cancel] at this
  have hu : IsUnit (a : R) := isUnit_natCast R (Nat.one_le_iff_ne_zero.mp ha)
  have := Ideal.mul_mem_left _ (↑hu.unit⁻¹ : R) haf
  rwa [← mul_assoc, IsUnit.val_inv_mul, one_mul] at this

/-- `D 0 = 0`. -/
theorem D_bot : c.D ⊥ = ⊥ := by
  refine le_antisymm (c.D_le_iff.mpr ⟨le_rfl, fun i f hf => ?_⟩) bot_le
  rw [Ideal.mem_bot] at hf ⊢
  rw [hf, map_zero]

/-- If `ord I = 0` then `D I = R`. -/
theorem D_eq_top_of_ord_eq_zero {I : Ideal R} (hI : ord I = 0) : c.D I = ⊤ := by
  rw [ord_eq_zero_iff.mp hI, D_top]

/-- If `ord I = a ≥ 1` then `ord (D I) = a - 1`. -/
theorem ord_D_of_ord_eq {a : ℕ} (ha : 1 ≤ a) {I : Ideal R} (hI : ord I = a) :
    ord (c.D I) = ((a - 1 : ℕ) : ℕ∞) := by
  refine le_antisymm ?_
    (le_ord_iff.mpr ((c.D_mono (le_ord_iff.mp hI.ge)).trans (c.D_maximalIdeal_pow ha)))
  have hnot : ¬ I ≤ maximalIdeal R ^ (a + 1) := fun hle => by
    have := le_ord_iff.mpr hle
    rw [hI] at this
    exact absurd (by exact_mod_cast this : a + 1 ≤ a) (by omega)
  obtain ⟨f, hfI, hf'⟩ := Set.not_subset.mp hnot
  have hfa : f ∈ maximalIdeal R ^ a := le_ord_iff.mp hI.ge hfI
  obtain ⟨i, hi⟩ := c.exists_pderiv_notMem_of_notMem_pow_succ ha hfa hf'
  have hlt : ord (c.D I) < a :=
    not_le.mp fun hle => hi (le_ord_iff.mp hle (c.pderiv_mem_D hfI i))
  obtain ⟨b, hb⟩ := ENat.ne_top_iff_exists.mp (ne_top_of_lt hlt)
  rw [← hb] at hlt ⊢
  have hba : b < a := by exact_mod_cast hlt
  exact_mod_cast (show b ≤ a - 1 by omega)

/-- `ord (Dʳ I) = a - r` for `ord I = a` and `r ≤ a`. -/
theorem ord_Dpow_of_ord_eq {a : ℕ} {I : Ideal R} (hI : ord I = a) {r : ℕ} (hr : r ≤ a) :
    ord (c.Dpow r I) = ((a - r : ℕ) : ℕ∞) := by
  induction r with
  | zero => simpa using hI
  | succ r ih =>
    rw [Dpow_succ, c.ord_D_of_ord_eq (by omega) (ih (Nat.le_of_succ_le hr)), Nat.sub_sub]

/-- For `r < m`, `m ≤ ord I ↔ m - r ≤ ord (Dʳ I)`: the local form of
`cosupp(I, m) = cosupp(Dʳ(I), m − r)` [Kol07, Lemma 74(3)], [Wlo05, Lemma 2.6.2],
[BM08, Lemma 3.2(3)]. -/
theorem le_ord_iff_le_ord_Dpow (I : Ideal R) {r m : ℕ} (h : r < m) :
    (m : ℕ∞) ≤ ord I ↔ ((m - r : ℕ) : ℕ∞) ≤ ord (c.Dpow r I) := by
  refine ⟨fun hm => c.le_ord_Dpow hm h.le, fun hD => ?_⟩
  by_contra hlt
  push Not at hlt
  obtain ⟨a, ha⟩ := ENat.ne_top_iff_exists.mp (ne_top_of_lt hlt)
  have ham : a < m := by rw [← ha] at hlt; exact_mod_cast hlt
  by_cases hra : r ≤ a
  · rw [c.ord_Dpow_of_ord_eq ha.symm hra] at hD
    have : m - r ≤ a - r := by exact_mod_cast hD
    omega
  · push Not at hra
    have h0 : ord (c.Dpow a I) = 0 := by simpa using c.ord_Dpow_of_ord_eq ha.symm le_rfl
    have htop : c.Dpow r I = ⊤ :=
      top_le_iff.mp ((ord_eq_zero_iff.mp h0) ▸ c.Dpow_mono_left hra.le I)
    rw [htop, ord_top] at hD
    have : m - r ≤ 0 := by exact_mod_cast hD
    omega

/-- If `ord I ≤ m` then `Dᵐ I = R` [Kol07, Definition 73] (from `le_ord_iff_le_ord_Dpow`). -/
theorem Dpow_eq_top_of_ord_le {I : Ideal R} {m : ℕ} (hord : ord I ≤ m) : c.Dpow m I = ⊤ :=
  c.Dpow_eq_top_of_ord_le_of_forall (fun I {_ _} h => c.le_ord_iff_le_ord_Dpow I h) hord

/-- The derivative of a power of a coordinate: `D ⟨xᵢ^m⟩ = ⟨xᵢ^(m-1)⟩` for `m ≥ 1` (`m` is a unit
in characteristic zero). -/
theorem D_span_singleton_x_pow (i : Fin n) {m : ℕ} (hm : 1 ≤ m) :
    c.D (Ideal.span {c.x i ^ m}) = Ideal.span {c.x i ^ (m - 1)} := by
  classical
  refine le_antisymm (c.D_le_iff.mpr ⟨?_, ?_⟩) ?_
  · rw [Ideal.span_singleton_le_span_singleton]
    exact pow_dvd_pow _ (Nat.sub_le m 1)
  · intro j g hg
    obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton'.mp hg
    rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, Derivation.leibniz_pow, smul_eq_mul]
    refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ (nsmul_mem (Ideal.mul_mem_right _ _
      (Ideal.mem_span_singleton_self _)) m)) (Ideal.mul_mem_right _ _ ?_)
    exact Ideal.mem_span_singleton.mpr (pow_dvd_pow _ (Nat.sub_le m 1))
  · rw [Ideal.span_singleton_le_iff_mem]
    have hu : IsUnit (m : R) := isUnit_natCast R (by omega)
    have h1 : c.pderiv i (c.x i ^ m) = (m : R) * c.x i ^ (m - 1) := by
      rw [Derivation.leibniz_pow, c.pderiv_x, if_pos rfl, smul_eq_mul, mul_one, nsmul_eq_mul]
    have h2 := Ideal.mul_mem_left _ (↑hu.unit⁻¹ : R)
      (c.pderiv_mem_D (Ideal.mem_span_singleton_self (c.x i ^ m)) i)
    rwa [h1, ← mul_assoc, IsUnit.val_inv_mul, one_mul] at h2

/-- `Dʳ ⟨xᵢ^m⟩ = ⟨xᵢ^(m-r)⟩` for `r ≤ m`. -/
theorem Dpow_span_singleton_x_pow (i : Fin n) {r m : ℕ} (hr : r ≤ m) :
    c.Dpow r (Ideal.span {c.x i ^ m}) = Ideal.span {c.x i ^ (m - r)} := by
  induction r with
  | zero => simp
  | succ r ih =>
    rw [Dpow_succ, ih (by omega), c.D_span_singleton_x_pow i (by omega), Nat.sub_sub]

/-- `D ⟨xᵢ xⱼ⟩ = ⟨xᵢ, xⱼ⟩` for `i ≠ j`. -/
theorem D_span_singleton_x_mul_x {i j : Fin n} (hij : i ≠ j) :
    c.D (Ideal.span {c.x i * c.x j}) = Ideal.span {c.x i, c.x j} := by
  classical
  refine le_antisymm (c.D_le_iff.mpr ⟨?_, ?_⟩) ?_
  · rw [Ideal.span_singleton_le_iff_mem]
    exact Ideal.mem_span_pair.mpr ⟨c.x j, 0, by ring⟩
  · intro k g hg
    obtain ⟨a, rfl⟩ := Ideal.mem_span_singleton'.mp hg
    rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ ?_) (Ideal.mul_mem_right _ _ ?_)
    · rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      exact Ideal.add_mem _ (Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp)))
        (Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp)))
    · exact Ideal.mem_span_pair.mpr ⟨c.x j, 0, by ring⟩
  · rw [Ideal.span_le]
    rintro y (rfl | rfl)
    · have h1 : c.pderiv j (c.x i * c.x j) = c.x i := by
        simp [Derivation.leibniz, c.pderiv_x, hij.symm]
      have h2 := c.pderiv_mem_D (Ideal.mem_span_singleton_self (c.x i * c.x j)) j
      rwa [h1] at h2
    · have h1 : c.pderiv i (c.x i * c.x j) = c.x j := by
        simp [Derivation.leibniz, c.pderiv_x, hij]
      have h2 := c.pderiv_mem_D (Ideal.mem_span_singleton_self (c.x i * c.x j)) i
      rwa [h1] at h2

/-- The local content of "`D(f^* I) = f^*(D(I))` for smooth `f`" [Kol07, Lemma 74(4)],
[Wlo05, Lemma 2.6.5], [BM08, Lemma 3.2(4)]: for `φ : R → R'` compatible with the derivations
(`∂'_{e i} ∘ φ = φ ∘ ∂ᵢ`, and `∂'ⱼ ∘ φ = 0` off the image of `e`), `D' (φ(I) R') = φ(D I) R'`. -/
theorem D_map {R' : Type*} [CommRing R'] [IsRegularLocalRing R'] [Algebra ℚ R'] {n' : ℕ}
    (c' : RegularCoords R' n') (φ : R →+* R') (e : Fin n → Fin n')
    (hφ : ∀ i f, c'.pderiv (e i) (φ f) = φ (c.pderiv i f))
    (hφ' : ∀ j, j ∉ Set.range e → ∀ f, c'.pderiv j (φ f) = 0) (I : Ideal R) :
    c'.D (I.map φ) = (c.D I).map φ := by
  refine le_antisymm (c'.D_le_iff.mpr ⟨Ideal.map_mono (c.le_D I), ?_⟩) ?_
  · intro j g hg
    change g ∈ Ideal.span (φ '' (I : Set R)) at hg
    induction hg using Submodule.span_induction with
    | mem g hg =>
      obtain ⟨f, hf, rfl⟩ := hg
      by_cases hj : j ∈ Set.range e
      · obtain ⟨i, rfl⟩ := hj
        rw [hφ]
        exact Ideal.mem_map_of_mem φ (c.pderiv_mem_D hf i)
      · rw [hφ' j hj]
        exact zero_mem _
    | zero => simp
    | add x y _ _ hx hy => rw [map_add]; exact Ideal.add_mem _ hx hy
    | smul r g hg' hg =>
      rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hg)
        (Ideal.mul_mem_right _ _ (Ideal.map_mono (c.le_D I) hg'))
  · rw [Ideal.map_le_iff_le_comap]
    refine c.D_le_iff.mpr ⟨fun f hf => ?_, fun i f hf => ?_⟩
    · exact Ideal.mem_comap.mpr (c'.le_D _ (Ideal.mem_map_of_mem φ hf))
    · rw [Ideal.mem_comap, ← hφ]
      exact c'.pderiv_mem_D (Ideal.mem_map_of_mem φ hf) (e i)

/-- If every coordinate derivation of `R'` is induced along `φ` by one of `R`
(`∂'ⱼ ∘ φ = φ ∘ ∂_{e j}`), then `D' (φ I) ≤ φ (D I)`: the local content of Kollár's
`(DI)|_S ⊃ D(I|_S)` for the restriction to a smooth subvariety (the discussion preceding
[Kol07, Definition 83]).  For the restriction to `R̄ = R/⟨x₁⟩` with coordinates `x₂, …, xₙ` the
extra generators `∂₁ f` only enlarge the right side. -/
theorem D_map_le {R' : Type*} [CommRing R'] [IsRegularLocalRing R'] [Algebra ℚ R'] {n' : ℕ}
    (c' : RegularCoords R' n') (φ : R →+* R') (e : Fin n' → Fin n)
    (hφ : ∀ j f, c'.pderiv j (φ f) = φ (c.pderiv (e j) f)) (I : Ideal R) :
    c'.D (I.map φ) ≤ (c.D I).map φ := by
  refine c'.D_le_iff.mpr ⟨Ideal.map_mono (c.le_D I), fun j g hg => ?_⟩
  change g ∈ Ideal.span (φ '' (I : Set R)) at hg
  induction hg using Submodule.span_induction with
  | mem g hg =>
    obtain ⟨f, hf, rfl⟩ := hg
    rw [hφ]
    exact Ideal.mem_map_of_mem φ (c.pderiv_mem_D hf (e j))
  | zero => simp
  | add x y _ _ hx hy => rw [map_add]; exact Ideal.add_mem _ hx hy
  | smul r g hg' hg =>
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hg)
      (Ideal.mul_mem_right _ _ (Ideal.map_mono (c.le_D I) hg'))

/-- `D'ʳ (φ I) ≤ φ (Dʳ I)` under the hypothesis of `D_map_le`. -/
theorem Dpow_map_le {R' : Type*} [CommRing R'] [IsRegularLocalRing R'] [Algebra ℚ R'] {n' : ℕ}
    (c' : RegularCoords R' n') (φ : R →+* R') (e : Fin n' → Fin n)
    (hφ : ∀ j f, c'.pderiv j (φ f) = φ (c.pderiv (e j) f)) (r : ℕ) (I : Ideal R) :
    c'.Dpow r (I.map φ) ≤ (c.Dpow r I).map φ := by
  induction r with
  | zero => simp
  | succ r ih =>
    rw [Dpow_succ, Dpow_succ]
    exact (c'.D_mono ih).trans (c.D_map_le c' φ e hφ _)

end Lemma74

end IsLocalRing.RegularCoords
