/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.KrullDimension.Basic
public import Mathlib.RingTheory.Spectrum.Prime.RingHom
public import Mathlib.Algebra.Module.SpanRank
public import Mathlib.RingTheory.IntegralClosure.IsIntegral.Defs
import Mathlib.RingTheory.Ideal.KrullsHeightTheorem

/-!
# Krull dimension under integral extensions

The theorem of Cohen–Seidenberg [Fre17, VII 5.7]: "if `A ⊂ B` is an integral ring extension of
noetherian rings then `dim A = dim B`" — the fact behind the uniqueness of the `d` of Noether
normalization [Fre17, I 7.2] ("the number `d` is unique (it is the Krull dimension)"). Mathlib
has lying over and going up (`Ideal.exists_ideal_over_prime_of_isIntegral`) and incomparability
(`Ideal.IsIntegral.under_lt_under`) but no statement about `ringKrullDim`; this module assembles
the two inequalities on `PrimeSpectrum`:

* `ringKrullDim_le_of_isIntegral`: an integral ring homomorphism `f : A →+* B` (no injectivity)
  gives `dim B ≤ dim A` — `comap f` is strictly monotone on primes by incomparability.
* `exists_ltSeries_comap_eq`: along an injective integral `f`, every chain of primes of `A` lifts to
  a chain of primes of `B` with the same preimages (lying over for the first prime, going up for
  each step; induction on the length with `RelSeries.snoc`).
* `ringKrullDim_eq_of_isIntegral_of_injective`, `ringKrullDim_eq_of_finite_of_injective`: the
  equality; the finite case through `RingHom.Finite.to_isIntegral`.

No Noetherian hypothesis is needed for either inequality. The second section reads the Krull
dimension of a quotient `R ⧸ I` on the zero locus of `I` in `Spec R`
(`Ideal.primeSpectrumQuotientOrderIsoZeroLocus`): `dim R ⧸ √I = dim R ⧸ I`
(`ringKrullDim_quotient_radical`) and `dim R ⧸ I = max` over the minimal primes `P` of `I` of
`dim R ⧸ P` (`ringKrullDim_quotient_eq_iSup_minimalPrimes`; this is the argument of
[Fre17, II 5.12]: chains of prime ideals in `𝒪_{X,a}` correspond to chains `a ⊂ p₀ ⊂ … ⊂ p_m` of
primes of `𝒪_n`, and `p₀` contains one of the minimal primes over `a`).

The third section is Krull's height theorem in the form of a system of parameters ([Fre17,
VII 5.6]: a local noetherian ring whose maximal ideal can be generated by `n` elements has
dimension at most `n`, applied to `R ⧸ I`): `d` elements `s` of the maximal ideal with
`𝔪 ≤ √(I ⊔ (s))` give `dim R ⧸ I ≤ d` (`ringKrullDim_quotient_le_of_maximalIdeal_le_radical_sup`,
from Mathlib's `ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank`) — the tool for the upper
semicontinuity of the dimension of an analytic germ at the points near a Noether normalization.

Standard commutative algebra, assembled from Mathlib's Cohen–Seidenberg lemmas, prime-spectrum
order isomorphisms and Krull's height theorem; used in the dimension theory of analytic germs
(Rückert's Noether normalization, the dimension of a germ through its minimal primes).
-/

public section

namespace IsLocalRing

variable {A B : Type*} [CommRing A] [CommRing B]

/-- Incomparability: an integral ring homomorphism does not raise the Krull dimension. -/
theorem ringKrullDim_le_of_isIntegral (f : A →+* B) (hf : f.IsIntegral) :
    ringKrullDim B ≤ ringKrullDim A := by
  let _ := f.toAlgebra
  have : Algebra.IsIntegral A B := ⟨hf⟩
  refine Order.krullDim_le_of_strictMono (PrimeSpectrum.comap f) ?_
  intro p q hpq
  rw [← PrimeSpectrum.asIdeal_lt_asIdeal] at hpq ⊢
  exact Ideal.IsIntegral.under_lt_under (R := A) hpq

/-- Lying over: for an injective integral homomorphism every prime of `A` is the preimage of a
prime of `B` containing a given prime `Q₀` whose preimage lies below it (going up; `Q₀ = ⊥`
gives lying over). -/
theorem exists_comap_eq_of_le (f : A →+* B) (hf : f.IsIntegral) (P : PrimeSpectrum A)
    (Q₀ : Ideal B) (hle : Ideal.comap f Q₀ ≤ P.asIdeal) :
    ∃ Q : PrimeSpectrum B, Q₀ ≤ Q.asIdeal ∧ PrimeSpectrum.comap f Q = P := by
  let _ := f.toAlgebra
  have : Algebra.IsIntegral A B := ⟨hf⟩
  obtain ⟨Q, hQ₀, hQprime, hQ⟩ :=
    Ideal.exists_ideal_over_prime_of_isIntegral (S := B) P.asIdeal Q₀ hle
  exact ⟨⟨Q, hQprime⟩, hQ₀, PrimeSpectrum.ext hQ⟩

/-- Lying over and going up: a chain of primes of `A` lifts along an injective integral `f` to a
chain of primes of `B` of the same length with the given preimages (the proof of
[Fre17, VII 5.7]). -/
theorem exists_ltSeries_comap_eq (f : A →+* B) (hf : f.IsIntegral) (hinj : Function.Injective f)
    (n : ℕ) :
    ∀ l : LTSeries (PrimeSpectrum A), ∀ hl : l.length = n,
      ∃ (m : LTSeries (PrimeSpectrum B)) (hm : m.length = n),
        ∀ i : Fin (n + 1),
          PrimeSpectrum.comap f (m (Fin.cast (by rw [hm]) i)) = l (Fin.cast (by rw [hl]) i) := by
  induction n with
  | zero =>
    intro l hl
    obtain ⟨Q, -, hQ⟩ := exists_comap_eq_of_le f hf l.head ⊥ (by
      rw [Ideal.comap_bot_of_injective f hinj]
      exact bot_le)
    refine ⟨RelSeries.singleton _ Q, rfl, fun i => ?_⟩
    have hi : i = 0 := Fin.ext (Nat.lt_one_iff.mp i.2)
    subst hi
    exact hQ
  | succ n ih =>
    intro l hl
    have hl0 : l.length ≠ 0 := by omega
    obtain ⟨m', hm', hcomap⟩ := ih l.eraseLast (by simp [RelSeries.eraseLast_length, hl])
    have hlast : PrimeSpectrum.comap f m'.last = l.eraseLast.last := by
      have := hcomap (Fin.last n)
      simpa [RelSeries.last, Fin.last, hm', RelSeries.eraseLast_length, hl] using this
    have hlt : l.eraseLast.last < l.last := l.eraseLast_last_rel_last hl0
    obtain ⟨Q, hQ₀, hQ⟩ := exists_comap_eq_of_le f hf l.last m'.last.asIdeal (by
      rw [← PrimeSpectrum.comap_asIdeal, hlast]
      exact hlt.le)
    have hQlt : m'.last < Q := by
      rw [← PrimeSpectrum.asIdeal_lt_asIdeal]
      refine lt_of_le_of_ne hQ₀ fun heq => ?_
      have h1 : PrimeSpectrum.comap f m'.last = PrimeSpectrum.comap f Q := by
        ext1; simp only [PrimeSpectrum.comap_asIdeal, heq]
      rw [hlast, hQ] at h1
      exact hlt.ne h1
    subst hm'
    refine ⟨m'.snoc Q hQlt, by simp, fun i => ?_⟩
    refine Fin.lastCases ?_ (fun j => ?_) i
    · rw [show (Fin.last (m'.length + 1) : Fin (m'.snoc Q hQlt).length.succ) =
          Fin.last (m'.snoc Q hQlt).length from rfl]
      erw [RelSeries.last_snoc']
      rw [hQ]
      change l (Fin.last l.length) = l _
      congr 1
      ext
      rw [Fin.val_last]
      exact hl
    · erw [RelSeries.snoc_castSucc]
      exact (hcomap j).trans rfl

/-- The theorem of Cohen–Seidenberg [Fre17, VII 5.7]: an injective integral ring homomorphism
preserves the Krull dimension. -/
theorem ringKrullDim_eq_of_isIntegral_of_injective (f : A →+* B) (hf : f.IsIntegral)
    (hinj : Function.Injective f) : ringKrullDim B = ringKrullDim A := by
  refine le_antisymm (ringKrullDim_le_of_isIntegral f hf) ?_
  unfold ringKrullDim Order.krullDim
  refine iSup_le fun l => ?_
  obtain ⟨m, hm, -⟩ := exists_ltSeries_comap_eq f hf hinj l.length l rfl
  rw [← hm]
  exact le_iSup (fun p : LTSeries (PrimeSpectrum B) => (p.length : WithBot ℕ∞)) m


/-- Cohen–Seidenberg for a finite injective ring homomorphism (`f.Finite` gives `f.IsIntegral`). -/
theorem ringKrullDim_eq_of_finite_of_injective (f : A →+* B) (hf : f.Finite)
    (hinj : Function.Injective f) : ringKrullDim B = ringKrullDim A :=
  ringKrullDim_eq_of_isIntegral_of_injective f hf.to_isIntegral hinj

/-- A finite ring homomorphism does not raise the Krull dimension. -/
theorem ringKrullDim_le_of_finite (f : A →+* B) (hf : f.Finite) :
    ringKrullDim B ≤ ringKrullDim A :=
  ringKrullDim_le_of_isIntegral f hf.to_isIntegral

/-! ### Krull dimension of quotients: the radical, the minimal primes -/

variable {R : Type*} [CommRing R]

/-- The Krull dimension of `R ⧸ I` is that of the zero locus of `I` in `Spec R`. -/
theorem ringKrullDim_quotient_eq_krullDim_zeroLocus (I : Ideal R) :
    ringKrullDim (R ⧸ I) = Order.krullDim (PrimeSpectrum.zeroLocus (R := R) (I : Set R)) :=
  Order.krullDim_eq_of_orderIso (Ideal.primeSpectrumQuotientOrderIsoZeroLocus I)

/-- `R ⧸ I` and `R ⧸ √I` have the same Krull dimension (same zero locus). -/
theorem ringKrullDim_quotient_radical (I : Ideal R) :
    ringKrullDim (R ⧸ I.radical) = ringKrullDim (R ⧸ I) := by
  rw [ringKrullDim_quotient_eq_krullDim_zeroLocus, ringKrullDim_quotient_eq_krullDim_zeroLocus]
  exact Order.krullDim_eq_of_orderIso
    (Set.orderIsoOfEq _ _ (PrimeSpectrum.zeroLocus_radical I))

/-- A quotient by a larger ideal has smaller dimension. -/
theorem ringKrullDim_quotient_le_quotient_of_le {I J : Ideal R} (h : I ≤ J) :
    ringKrullDim (R ⧸ J) ≤ ringKrullDim (R ⧸ I) :=
  ringKrullDim_le_of_surjective (Ideal.Quotient.factor h) (Ideal.Quotient.factor_surjective h)

/-- The dimension of `R ⧸ I` is the maximum of the dimensions of `R ⧸ P` over the minimal primes
`P` of `I` [Fre17, II 5.12] — a chain of primes over `I` starts at a prime containing a minimal
prime of `I`, hence lies over it. -/
theorem ringKrullDim_quotient_eq_iSup_minimalPrimes (I : Ideal R) :
    ringKrullDim (R ⧸ I) = ⨆ P ∈ I.minimalPrimes, ringKrullDim (R ⧸ P) := by
  apply le_antisymm
  · rw [ringKrullDim_quotient_eq_krullDim_zeroLocus]
    unfold Order.krullDim
    refine iSup_le fun l => ?_
    -- the head of the chain contains a minimal prime `P`
    have hI : I ≤ (l.head : PrimeSpectrum R).asIdeal := by
      have := (l.head).2
      rw [PrimeSpectrum.mem_zeroLocus] at this
      exact this
    have : ((l.head : PrimeSpectrum R).asIdeal).IsPrime := (l.head : PrimeSpectrum R).2
    obtain ⟨P, hP, hPle⟩ := Ideal.exists_minimalPrimes_le hI
    -- the chain lies in the zero locus of `P`
    have hsub : ∀ i, (l i : PrimeSpectrum R) ∈ PrimeSpectrum.zeroLocus (R := R) (P : Set R) := by
      intro i
      rw [PrimeSpectrum.mem_zeroLocus]
      refine hPle.trans ?_
      have hmono : l.head ≤ l i := l.head_le i
      exact hmono
    let m : LTSeries (PrimeSpectrum.zeroLocus (R := R) (P : Set R)) :=
      { length := l.length
        toFun := fun i => ⟨(l i : PrimeSpectrum R), hsub i⟩
        step := fun i => l.step i }
    calc ((l.length : ℕ∞) : WithBot ℕ∞) = m.length := rfl
      _ ≤ Order.krullDim (PrimeSpectrum.zeroLocus (R := R) (P : Set R)) :=
          Order.LTSeries.length_le_krullDim m
      _ = ringKrullDim (R ⧸ P) := (ringKrullDim_quotient_eq_krullDim_zeroLocus P).symm
      _ ≤ ⨆ P ∈ I.minimalPrimes, ringKrullDim (R ⧸ P) :=
          le_iSup₂ (f := fun P _ => ringKrullDim (R ⧸ P)) P hP
  · refine iSup₂_le fun P hP => ?_
    exact ringKrullDim_quotient_le_quotient_of_le hP.1.2


/-! ### Systems of parameters: Krull's height theorem in a local Noetherian ring -/

section Parameters

variable {R : Type*} [CommRing R]

/-- A quotient of a local ring by an ideal whose radical contains the maximal ideal has Krull
dimension `≤ 0`. -/
theorem ringKrullDim_quotient_le_zero_of_maximalIdeal_le_radical [IsLocalRing R] (J : Ideal R)
    (hm : IsLocalRing.maximalIdeal R ≤ J.radical) : ringKrullDim (R ⧸ J) ≤ 0 := by
  have : Ring.KrullDimLE 0 (R ⧸ J) := by
    rw [Ideal.krullDimLE_zero_quotient_iff_forall_minimalPrimes_isMaximal]
    intro P hP
    have hPprime : P.IsPrime := hP.1.1
    have hle : IsLocalRing.maximalIdeal R ≤ P := hm.trans (hPprime.radical_le_iff.mpr hP.1.2)
    rw [le_antisymm (IsLocalRing.le_maximalIdeal hPprime.ne_top) hle]
    exact IsLocalRing.maximalIdeal.isMaximal _
  have h := Ring.krullDimLE_iff.mp this
  simpa using h

/-- An ideal inside the maximal ideal maps into the Jacobson radical of any quotient. -/
theorem map_quotientMk_le_jacobson_of_le_maximalIdeal [IsLocalRing R] (I B : Ideal R)
    (hBm : B ≤ IsLocalRing.maximalIdeal R) :
    Ideal.map (Ideal.Quotient.mk I) B ≤ Ring.jacobson (R ⧸ I) := by
  refine le_sInf fun M hM => ?_
  have hc : (Ideal.comap (Ideal.Quotient.mk I) M).IsMaximal :=
    Ideal.comap_isMaximal_of_surjective (H := ⟨hM⟩) _ Ideal.Quotient.mk_surjective
  rw [Ideal.map_le_iff_le_comap, IsLocalRing.eq_maximalIdeal hc]
  exact hBm

/-- The image of an ideal generated by `d` elements has span rank `≤ d`. -/
theorem spanFinrank_map_span_range_le {d : ℕ} (I : Ideal R) (g : Fin d → R) :
    (Ideal.map (Ideal.Quotient.mk I) (Ideal.span (Set.range g))).spanFinrank ≤ d := by
  classical
  rw [Ideal.map_span, ← Set.range_comp]
  refine (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)).trans ?_
  rw [← Set.image_univ, ← Finset.coe_univ, ← Finset.coe_image, Set.ncard_coe_finset]
  exact Finset.card_image_le.trans (by simp)

/-- Krull's height theorem, in the form of a system of parameters: if `d` elements `s j` of the
maximal ideal of the local Noetherian ring `R` satisfy `𝔪 ≤ √(I ⊔ (s))`, then `dim R ⧸ I ≤ d`
([Fre17, VII 5.6], a local noetherian ring whose maximal ideal can be generated by `n` elements
has dimension at most `n`, applied to `R ⧸ I`, whose maximal ideal is the radical of `(s)`). -/
theorem ringKrullDim_quotient_le_of_maximalIdeal_le_radical_sup [IsLocalRing R] [IsNoetherianRing R]
    {d : ℕ} (I : Ideal R)
    (s : Fin d → R) (hs : ∀ j, s j ∈ IsLocalRing.maximalIdeal R)
    (hm : IsLocalRing.maximalIdeal R ≤ (I ⊔ Ideal.span (Set.range s)).radical) :
    ringKrullDim (R ⧸ I) ≤ (d : WithBot ℕ∞) := by
  have hBm : Ideal.span (Set.range s) ≤ IsLocalRing.maximalIdeal R := by
    rw [Ideal.span_le]
    rintro _ ⟨j, rfl⟩
    exact hs j
  have h0 := ringKrullDim_quotient_le_zero_of_maximalIdeal_le_radical _ hm
  have hdim := ringKrullDim_le_ringKrullDim_quotient_add_spanFinrank _
    (map_quotientMk_le_jacobson_of_le_maximalIdeal I _ hBm)
  rw [ringKrullDim_eq_of_ringEquiv (DoubleQuot.quotQuotEquivQuotSup I _)] at hdim
  have hrank := spanFinrank_map_span_range_le I s
  have hcast : ((Ideal.map (Ideal.Quotient.mk I) (Ideal.span (Set.range s))).spanFinrank :
      WithBot ℕ∞) ≤ (d : WithBot ℕ∞) := by
    rw [← WithBot.coe_natCast, ← WithBot.coe_natCast]
    exact WithBot.coe_le_coe.mpr (Nat.cast_le.mpr hrank)
  refine hdim.trans ?_
  refine (add_le_add h0 hcast).trans ?_
  rw [zero_add]

end Parameters

end IsLocalRing
