/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.DerivationLocalization
public import Hironaka.Algebra.Local.Coords
import Hironaka.Algebra.Local.RegularSystem

/-!
# Coordinates on the localization at a coordinate prime

Kollár defines the order along a subvariety `Z` at its generic point, `ord_Z I := ord_η I`
[Kol07, Definition 47]; with local coordinates `Z = (x₁ = ⋯ = x_r = 0)` [Kol07, Definition 60] the
local ring at `η` is `R_{P_r}`, `P_r = ⟨x₁, …, x_r⟩`.  Serre's theorem that every localization of
a regular local ring is regular is not in Mathlib (an open pull request); for a prime generated
by part of a regular system of parameters there is a direct argument, which this file follows:

* `P₀ ⊊ P₁ ⊊ ⋯ ⊊ P_r` is a chain of primes (each `Pᵢ` is prime by
  `Hironaka/Algebra/Local/RegularSystem.lean`, and `xᵢ ∈ P_{i+1} ∖ Pᵢ`), so `dim R_{P_r} = ht P_r ≥
  r` (`Order.length_le_height`);
* `P_r R_{P_r}` is generated by the `r` elements `x₀, …, x_{r-1}`, so `spanFinrank ≤ r`;
* Krull's height theorem closes the circle: `R_{P_r}` is regular (`of_spanFinrank_maximalIdeal_le`)
  of dimension exactly `r`.

The coordinate derivations extend to `R_{P_r}` by the quotient rule (`Derivation.localization`),
agree with the `∂ᵢ` on the image of `R`, hence satisfy `∂̃ᵢ x̃ⱼ = δᵢⱼ`; they commute because the
commutator of two derivations is a derivation, and a derivation of the localization vanishing on
the image of `R` is zero (`eq_localization_of_algebraMap` with `D = 0`).  So `R_{P_r}` carries a
`RegularCoords` structure on `r` coordinates (`localizationCoords`).
-/

@[expose] public section

namespace IsLocalRing

open IsLocalRing

/-! ### Commuting derivations extend to commuting derivations -/

section Commutator

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A] (M : Submonoid A)

end Commutator

/-! ### The localization at `P_r` -/

section Localization

variable {R : Type*} [CommRing R] {n : ℕ} (x : Fin n → R) {r : ℕ}

omit [CommRing R] in
/-- The generators of `P_r`, indexed by `Fin r`. -/
theorem image_lt_eq_range (hr : r ≤ n) :
    x '' {j : Fin n | j.val < r} = Set.range fun i : Fin r => x (Fin.castLE hr i) := by
  ext y
  constructor
  · rintro ⟨j, hj, rfl⟩
    exact ⟨⟨j.val, hj⟩, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨Fin.castLE hr i, i.2, rfl⟩

/-- `P_r R_{P_r}` is generated by the images of `x₀, …, x_{r-1}`. -/
theorem maximalIdeal_localization_span_image_lt (hr : r ≤ n)
    [(Ideal.span (x '' {j : Fin n | j.val < r})).IsPrime] :
    maximalIdeal (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r}))) =
      Ideal.span (Set.range fun i : Fin r =>
        algebraMap R (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r})))
          (x (Fin.castLE hr i))) := by
  refine (Localization.AtPrime.map_eq_maximalIdeal).symm.trans ?_
  rw [Ideal.map_span]
  congr 1
  ext y
  constructor
  · rintro ⟨_, ⟨j, hj, rfl⟩, rfl⟩
    exact ⟨⟨j.val, hj⟩, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨x (Fin.castLE hr i), ⟨Fin.castLE hr i, i.2, rfl⟩, rfl⟩

theorem spanFinrank_maximalIdeal_localization_le (hr : r ≤ n)
    [(Ideal.span (x '' {j : Fin n | j.val < r})).IsPrime] :
    (maximalIdeal (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r})))).spanFinrank
      ≤ r := by
  rw [maximalIdeal_localization_span_image_lt x hr]
  refine le_trans (Submodule.spanFinrank_span_le_ncard_of_finite (Set.finite_range _)) ?_
  rw [← Set.image_univ]
  exact le_trans (Set.ncard_image_le Set.finite_univ)
    (by rw [Set.ncard_univ, Nat.card_eq_fintype_card, Fintype.card_fin])

variable [IsRegularLocalRing R]

/-- The chain `P₀ ⊊ ⋯ ⊊ P_r` gives `ht P_r ≥ r`. -/
theorem natCast_le_height_span_image_lt (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (hr : r ≤ n) :
    (r : ℕ∞) ≤ (Ideal.span (x '' {j : Fin n | j.val < r})).height := by
  have hP := isPrime_span_image_lt x hx hn r
  let chain : LTSeries (PrimeSpectrum R) := LTSeries.mk r
    (fun i : Fin (r + 1) =>
      ⟨Ideal.span (x '' {j : Fin n | j.val < i}), isPrime_span_image_lt x hx hn i⟩)
    (Fin.strictMono_iff_lt_succ.mpr fun i => by
      rw [← PrimeSpectrum.asIdeal_lt_asIdeal]
      change Ideal.span (x '' {j : Fin n | j.val < (i : ℕ)}) <
        Ideal.span (x '' {j : Fin n | j.val < (i : ℕ) + 1})
      refine lt_of_le_of_ne (Ideal.span_mono (Set.image_mono fun j hj => ?_)) ?_
      · exact Nat.lt_succ_of_lt hj
      · intro heq
        have hi : (i : ℕ) < n := lt_of_lt_of_le i.2 hr
        apply notMem_span_image_lt x hx hn hi
        rw [heq]
        exact Ideal.subset_span ⟨⟨i, hi⟩, Nat.lt_succ_self _, rfl⟩)
  have hlast : chain.last ≤ ⟨Ideal.span (x '' {j : Fin n | j.val < r}), hP⟩ := le_rfl
  have h := Order.length_le_height hlast
  rw [PrimeSpectrum.height_eq_orderHeight ⟨_, hP⟩]
  exact h

theorem natCast_le_ringKrullDim_localization_span_image_lt
    (hx : maximalIdeal R = Ideal.span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    (hr : r ≤ n) [(Ideal.span (x '' {j : Fin n | j.val < r})).IsPrime] :
    (r : WithBot ℕ∞) ≤
      ringKrullDim (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r}))) := by
  rw [IsLocalization.AtPrime.ringKrullDim_eq_height (Ideal.span (x '' {j : Fin n | j.val < r}))
    (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r}))), ← WithBot.coe_natCast,
    WithBot.coe_le_coe]
  exact natCast_le_height_span_image_lt x hx hn hr

/-- `R_{P_r}` is a regular local ring (the local ring at the generic point of the coordinate
subspace `Z = (x₁ = ⋯ = x_r = 0)`, [Kol07, Definition 47]). -/
theorem isRegularLocalRing_localization_span_image_lt
    (hx : maximalIdeal R = Ideal.span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    (hr : r ≤ n) [(Ideal.span (x '' {j : Fin n | j.val < r})).IsPrime] :
    IsRegularLocalRing (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r}))) :=
  IsRegularLocalRing.of_spanFinrank_maximalIdeal_le
    (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r})))
    (le_trans (Nat.cast_le.mpr (spanFinrank_maximalIdeal_localization_le x hr))
      (natCast_le_ringKrullDim_localization_span_image_lt x hx hn hr))

/-- `dim R_{P_r} = r`. -/
theorem ringKrullDim_localization_span_image_lt
    (hx : maximalIdeal R = Ideal.span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    (hr : r ≤ n) [(Ideal.span (x '' {j : Fin n | j.val < r})).IsPrime] :
    ringKrullDim (Localization.AtPrime (Ideal.span (x '' {j : Fin n | j.val < r}))) = r := by
  have := isRegularLocalRing_localization_span_image_lt x hx hn hr
  refine le_antisymm ?_ (natCast_le_ringKrullDim_localization_span_image_lt x hx hn hr)
  rw [← IsRegularLocalRing.spanFinrank_maximalIdeal]
  exact Nat.cast_le.mpr (spanFinrank_maximalIdeal_localization_le x hr)

end Localization

/-! ### The coordinate structure on `R_{P_r}` -/

section Coords

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ}
  (c : RegularCoords R n) {r : ℕ} (hr : r ≤ n)
  [(Ideal.span (c.x '' {j : Fin n | j.val < r})).IsPrime]

/-- The localized derivations satisfy `∂̃ᵢ x̃ⱼ = δᵢⱼ`. -/
theorem localization_pderiv_algebraMap_x (i j : Fin r) :
    (c.pderiv (Fin.castLE hr i)).localization
        (Ideal.span (c.x '' {j : Fin n | j.val < r})).primeCompl
        (algebraMap R (Localization.AtPrime (Ideal.span (c.x '' {j : Fin n | j.val < r})))
          (c.x (Fin.castLE hr j))) =
      if i = j then 1 else 0 := by
  rw [Derivation.localization_algebraMap, c.pderiv_x]
  by_cases h : i = j
  · subst h
    simp
  · rw [ite_eq_right (fun h' => h (Fin.castLE_inj.mp h')), ite_eq_right h, map_zero]

/-- The coordinate structure on `R_{P_r}`: parameters `x̃₀, …, x̃_{r-1}`, derivations
`∂̃₀, …, ∂̃_{r-1}` (the local ring at the generic point of `Z = (x₁ = ⋯ = x_r = 0)`,
[Kol07, Definitions 47 and 60]). -/
noncomputable def localizationCoords :
    haveI := isRegularLocalRing_localization_span_image_lt c.x c.span_x c.card hr
    RegularCoords (Localization.AtPrime (Ideal.span (c.x '' {j : Fin n | j.val < r}))) r :=
  haveI := isRegularLocalRing_localization_span_image_lt c.x c.span_x c.card hr
  { x := fun i => algebraMap R _ (c.x (Fin.castLE hr i))
    pderiv := fun i => (c.pderiv (Fin.castLE hr i)).localization
      (Ideal.span (c.x '' {j : Fin n | j.val < r})).primeCompl
    span_x := maximalIdeal_localization_span_image_lt c.x hr
    card := (ringKrullDim_localization_span_image_lt c.x c.span_x c.card hr).symm
    pderiv_x := localization_pderiv_algebraMap_x c hr
    pderiv_comm := fun i j f => Derivation.localization_comm _ (c.pderiv (Fin.castLE hr i))
      (c.pderiv (Fin.castLE hr j)) (c.pderiv_comm _ _) f }

/-- The coordinate structure on `R_{P_r}` in existential form: `R_{P_r}` is regular local and
carries coordinates whose parameters are the images of `x₀, …, x_{r-1}`. -/
theorem exists_localization_coords :
    ∃ _ : IsRegularLocalRing
      (Localization.AtPrime (Ideal.span (c.x '' {j : Fin n | j.val < r}))),
      ∃ c' : RegularCoords (Localization.AtPrime (Ideal.span (c.x '' {j : Fin n | j.val < r}))) r,
        c'.x = (fun i => algebraMap R _ (c.x (Fin.castLE hr i))) ∧
        c'.pderiv = fun i => (c.pderiv (Fin.castLE hr i)).localization
          (Ideal.span (c.x '' {j : Fin n | j.val < r})).primeCompl :=
  ⟨isRegularLocalRing_localization_span_image_lt c.x c.span_x c.card hr,
    localizationCoords c hr, rfl, rfl⟩

end Coords

end IsLocalRing
