/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.IdealSheaf.Derivative.Logarithmic
public import Hironaka.Algebra.Local.LogDeriv
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Logarithmic derivations in coordinates

[Kol07, 87]: in local coordinates with `S = (x₁ = 0)`, the sheaf `Der_X(−log S)` of logarithmic
derivations is generated by `x₁ ∂₁, ∂₂, …, ∂ₙ`, and `D(−log S)(I)` is generated by `I` and their
values on `I`. Here the coordinate system is `RegularCoords` on a regular local ring `R`, with the
hypotheses of `Hironaka/Algebra/Local/CoordsOver.lean` that the coordinate derivations `∂ᵢ` are
`k`-linear (`IsLinearOver`) and span the `k`-derivations (`SpansDerivations`: every `k`-derivation
is `δ = ∑ᵢ δ(xᵢ) ∂ᵢ`, `eq_sum_smul_pderivOver`), and `S = V(x_h)`.

* The `k`-derivations preserving `(x_h)` are the `R`-span of `x_h ∂_h` and the `∂_j`, `j ≠ h`
  (`preserving_span_x_eq`). The generators preserve `(x_h)` (`x_smul_pderivOver_preservesIdeal`,
  `pderivOver_preservesIdeal_of_ne`, from `Hironaka/Algebra/Local/LogDeriv.lean`); conversely
  `δ = ∑ᵢ δ(xᵢ) ∂ᵢ` with `δ(x_h) = b · x_h`, so `δ = b · (x_h ∂_h) + ∑_{j ≠ h} δ(x_j) ∂_j`.
* Kollár's ideal `D(−log (x_h))(I)` over all `k`-derivations preserving `(x_h)`
  (`Ideal.logDerivative`, `Hironaka/Scheme/IdealSheaf/Derivative/Logarithmic.lean`) is the
  coordinate logarithmic derivative ideal `c.Dlog h I` of `Hironaka/Algebra/Local/LogDeriv.lean`
  (`logDerivative_eq_Dlog`), and the iterates agree (`logDerivativeIter_eq_Dlogpow`), just as
  `derivative_eq_D` of `Hironaka/Algebra/Derivative/Basic.lean` identifies `D(I)` with `c.D I`.

Used for the stalks of the logarithmic derivative sheaves on manifolds
(`Hironaka/Manifold/IdealSheaf/LogDerivLemmas.lean`).
-/

public section

namespace IsLocalRing.RegularCoords

variable {k : Type*} [CommRing k] {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R]
  [Algebra k R] {n : ℕ} (c : RegularCoords R n)

section Generators

variable (hk : c.IsLinearOver k) (hs : c.SpansDerivations k) (h : Fin n)

/-- `x_i ∂_i` preserves `(x_h)` for every `i` (`x_smul_pderiv_mem_logDerE`,
`Hironaka/Algebra/Local/LogDeriv.lean`). -/
theorem x_smul_pderivOver_preservesIdeal (i : Fin n) :
    (c.x i • c.pderivOver hk i).PreservesIdeal (Ideal.span {c.x h}) := by
  intro f hf
  have := (c.mem_logDerE.mp (c.x_smul_pderiv_mem_logDerE {h} i)).2 h (Finset.mem_singleton_self h)
    f hf
  simpa only [Derivation.smul_apply, pderivOver_apply, smul_eq_mul] using this

/-- `∂_j` preserves `(x_h)` for `j ≠ h` (`pderiv_mem_span_x_of_ne'`). -/
theorem pderivOver_preservesIdeal_of_ne {j : Fin n} (hj : j ≠ h) :
    (c.pderivOver hk j).PreservesIdeal (Ideal.span {c.x h}) := fun f hf => by
  rw [pderivOver_apply]
  exact c.pderiv_mem_span_x_of_ne' h hj hf

include hk hs

/-- A `k`-derivation is the `R`-combination `∑ᵢ δ(xᵢ) ∂ᵢ` of the `k`-linear coordinate
derivations, when these span the `k`-derivations. -/
theorem eq_sum_smul_pderivOver (δ : Derivation k R R) :
    δ = ∑ i, δ (c.x i) • c.pderivOver hk i := by
  ext f
  rw [hs δ f, derivation_sum_apply]
  simp only [Derivation.smul_apply, pderivOver_apply, smul_eq_mul]

/-- [Kol07, 87], `Der_X(−log S) = ⟨x₁ ∂/∂x₁, ∂/∂x₂, …, ∂/∂xₙ⟩` in coordinates with `S = (x₁ = 0)`:
the `k`-derivations preserving `(x_h)` are the `R`-span of `x_h ∂_h` and the `∂_j`, `j ≠ h`. -/
theorem preserving_span_x_eq :
    Derivation.preserving k (Ideal.span {c.x h}) =
      Submodule.span R
        ({c.x h • c.pderivOver hk h} ∪ (fun j => c.pderivOver hk j) '' {j | j ≠ h}) := by
  classical
  refine le_antisymm ?_ (Submodule.span_le.mpr ?_)
  · intro δ hδ
    rw [Derivation.mem_preserving] at hδ
    obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp (hδ (c.x h) (Ideal.mem_span_singleton_self _))
    rw [c.eq_sum_smul_pderivOver hk hs δ, ← Finset.add_sum_erase _ _ (Finset.mem_univ h)]
    refine Submodule.add_mem _ ?_ (Submodule.sum_mem _ fun j hj => ?_)
    · rw [← hb, ← smul_smul]
      exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inl rfl))
    · exact Submodule.smul_mem _ _
        (Submodule.subset_span (Or.inr ⟨j, Finset.ne_of_mem_erase hj, rfl⟩))
  · rintro δ (rfl | ⟨j, hj, rfl⟩)
    · exact c.x_smul_pderivOver_preservesIdeal hk h h
    · exact c.pderivOver_preservesIdeal_of_ne hk h hj

/-- The ideal `D(−log (x_h))(I)` of [Kol07, 87] over all `k`-derivations preserving `(x_h)` is the
coordinate logarithmic derivative ideal `c.Dlog h I` of `Hironaka/Algebra/Local/LogDeriv.lean`. -/
theorem logDerivative_eq_Dlog (I : Ideal R) :
    Ideal.logDerivative k (Ideal.span {c.x h}) I = c.Dlog h I := by
  refine le_antisymm (Ideal.logDerivative_le_iff.mpr ⟨c.le_DlogE _ I, fun δ hδ f hf => ?_⟩)
    ((c.Dlog_le_iff h).mpr ⟨Ideal.le_logDerivative _ I, fun f hf => ?_, fun j hj f hf => ?_⟩)
  · rw [hs δ f]
    refine Ideal.sum_mem _ fun i _ => ?_
    by_cases hi : i = h
    · subst hi
      obtain ⟨b, hb⟩ :=
        Ideal.mem_span_singleton'.mp (hδ (c.x i) (Ideal.mem_span_singleton_self _))
      rw [← hb, mul_assoc]
      exact Ideal.mul_mem_left _ _ (c.x_mul_pderiv_mem_DlogE (Finset.mem_singleton_self i) hf)
    · exact Ideal.mul_mem_left _ _
        (c.pderiv_mem_DlogE (fun e => hi (Finset.mem_singleton.mp e)) hf)
  · have := Ideal.derivation_apply_mem_logDerivative
      (c.x_smul_pderivOver_preservesIdeal hk h h) hf
    simpa only [Derivation.smul_apply, pderivOver_apply, smul_eq_mul] using this
  · exact Ideal.derivation_apply_mem_logDerivative (c.pderivOver_preservesIdeal_of_ne hk h hj) hf

/-- The iterates: `D^s(−log (x_h))(I) = c.Dlogpow h s I`. -/
theorem logDerivativeIter_eq_Dlogpow (s : ℕ) (I : Ideal R) :
    Ideal.logDerivativeIter k (Ideal.span {c.x h}) s I = c.Dlogpow h s I := by
  induction s with
  | zero => rfl
  | succ s ih =>
    rw [Ideal.logDerivativeIter_succ, ih, Dlogpow_succ, c.logDerivative_eq_Dlog hk hs h]

end Generators

end IsLocalRing.RegularCoords
