/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.Derivative
public import Hironaka.Algebra.Local.QuotientCoords
import Hironaka.Algebra.Local.Chart

/-!
# Logarithmic derivations along coordinate hypersurfaces

For a smooth hypersurface `S = (x₁ = 0)`, `Der_X(−log S)` is the largest subsheaf of `Der_X`
mapping `𝒪_X(−S)` into itself; in coordinates it is generated by `x₁ ∂₁, ∂₂, …, ∂ₙ`
[Kol07, 87].  For an ideal `I`, `D(−log S)(I) := im[Der_X(−log S) × I → 𝒪_X]` and
`D^{r+1}(−log S)(I) := D(−log S)(D^r(−log S)(I))`.  Three properties: (87.1) restriction,
`(D^r(−log S)(I))|_S = D^r(I|_S)`; the filtration `D^s(−log S)(I) ⊂ D^{s−1}(−log S)(D(I)) ⊂ ⋯ ⊂
D^s(I)`; and (87.2) `D^s(I) = D^s(−log S)(I) + D^{s−1}(−log S)(⟨∂I/∂x₁⟩) + ⋯ + ⟨∂^s I/∂x₁^s⟩`, the
first `j + 1` summands spanning `D^{s−j}(−log S)(D^j(I))`.  Bierstone–Milman use the
several-divisor version `D_E` with `E = V(x₁) + ⋯ + V(x_q)` [BM08, §3].

Here the hypersurfaces are `V(xᵢ)`, `i ∈ E`, for a finite set `E` of coordinates (`logDerE`,
`DlogE`), and Kollár's `S = V(x_h)` is `E = {h}` (`logDer`, `Dlog`, `Dlogpow`).  The restriction
(87.1) is stated in `R̄ = R/⟨x_h⟩` with the coordinate structure `quotientCoords` of
`Hironaka/Algebra/Local/QuotientCoords.lean`.  The logarithmic derivative ideals are the local form
of the ideals whose birational transform is controlled in
`Hironaka/Algebra/Local/TransformLogDeriv.lean`.
-/

@[expose] public section

namespace IsLocalRing

open IsLocalRing

namespace RegularCoords

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ}
  (c : RegularCoords R n)

/-! ### `Der(−log E)` and its generators -/

/-- The `ℚ`-derivations of `R` preserving an ideal `J` (an `R`-submodule). -/
def preservingDer (J : Ideal R) : Submodule R (Derivation ℚ R R) where
  carrier := {δ | ∀ f ∈ J, δ f ∈ J}
  add_mem' {δ₁ δ₂} h₁ h₂ f hf := by
    rw [Derivation.add_apply]
    exact J.add_mem (h₁ f hf) (h₂ f hf)
  zero_mem' f _ := by
    rw [Derivation.zero_apply]
    exact J.zero_mem
  smul_mem' a {δ} h f hf := by
    rw [Derivation.smul_apply, smul_eq_mul]
    exact J.mul_mem_left a (h f hf)

omit [IsRegularLocalRing R] in
theorem mem_preservingDer {J : Ideal R} {δ : Derivation ℚ R R} :
    δ ∈ preservingDer J ↔ ∀ f ∈ J, δ f ∈ J := Iff.rfl

/-- `∂ⱼ` preserves `⟨xᵢ⟩` for `j ≠ i` (Leibniz and `∂ⱼ xᵢ = 0`; `pderiv_mem_span_x_of_ne` of
`Hironaka/Algebra/Local/QuotientCoords.lean` for a general `n`). -/
theorem pderiv_mem_span_x_of_ne' (i : Fin n) {j : Fin n} (hj : j ≠ i) {f : R}
    (hf : f ∈ Ideal.span {c.x i}) : c.pderiv j f ∈ Ideal.span {c.x i} := by
  obtain ⟨g, rfl⟩ := Ideal.mem_span_singleton.mp hf
  rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x, if_neg hj, mul_zero, add_zero]
  exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)

/-- `Der(−log E)`, the derivations in the span of the `∂ᵢ` that preserve every `⟨xᵢ⟩`, `i ∈ E`
(the derivations preserving the ideal of the divisor `E`, [BM08, §3]; for `E = {h}`, Kollár's
`Der_X(−log S)`, [Kol07, 87]). -/
def logDerE (E : Finset (Fin n)) : Submodule R (Derivation ℚ R R) :=
  Submodule.span R (Set.range c.pderiv) ⊓ ⨅ i ∈ E, preservingDer (Ideal.span {c.x i})

/-- `Der(−log S)` for `S = V(x_h)` [Kol07, 87]. -/
abbrev logDer (h : Fin n) : Submodule R (Derivation ℚ R R) := c.logDerE {h}

theorem mem_logDerE {E : Finset (Fin n)} {δ : Derivation ℚ R R} :
    δ ∈ c.logDerE E ↔
      δ ∈ Submodule.span R (Set.range c.pderiv) ∧
        ∀ i ∈ E, ∀ f ∈ Ideal.span {c.x i}, δ f ∈ Ideal.span {c.x i} := by
  simp only [logDerE, Submodule.mem_inf, Submodule.mem_iInf, mem_preservingDer]

/-- `(∑ₗ aₗ ∂ₗ)(xᵢ) = aᵢ`. -/
theorem sum_smul_pderiv_apply_x (a : Fin n → R) (i : Fin n) :
    (∑ l, a l • c.pderiv l) (c.x i) = a i := by
  rw [Derivation.finset_sum_apply]
  simp only [Derivation.smul_apply, smul_eq_mul, c.pderiv_x]
  rw [Finset.sum_eq_single i (fun l _ hl => by rw [if_neg hl, mul_zero]) (by simp)]
  rw [if_pos rfl, mul_one]

/-- `δ = ∑ᵢ aᵢ ∂ᵢ` preserves every `⟨xᵢ⟩`, `i ∈ E`, iff `aᵢ ∈ ⟨xᵢ⟩` for every `i ∈ E`. -/
theorem sum_smul_pderiv_mem_logDerE_iff (E : Finset (Fin n)) (a : Fin n → R) :
    (∑ i, a i • c.pderiv i) ∈ c.logDerE E ↔ ∀ i ∈ E, a i ∈ Ideal.span {c.x i} := by
  rw [mem_logDerE]
  constructor
  · rintro ⟨-, hpres⟩ i hi
    have := hpres i hi (c.x i) (Ideal.mem_span_singleton_self _)
    rwa [c.sum_smul_pderiv_apply_x] at this
  · intro ha
    refine ⟨Submodule.sum_mem _ fun l _ =>
      Submodule.smul_mem _ _ (Submodule.subset_span ⟨l, rfl⟩), ?_⟩
    intro i hi f hf
    rw [Derivation.finset_sum_apply]
    refine Ideal.sum_mem _ fun l _ => ?_
    rw [Derivation.smul_apply, smul_eq_mul]
    by_cases hl : l = i
    · rw [hl]
      exact Ideal.mul_mem_right _ _ (ha i hi)
    · exact Ideal.mul_mem_left _ _ (c.pderiv_mem_span_x_of_ne' i hl hf)

/-- `∑ᵢ aᵢ ∂ᵢ ∈ Der(−log S)` iff `a_h ∈ ⟨x_h⟩`. -/
theorem sum_smul_pderiv_mem_logDer_iff (h : Fin n) (a : Fin n → R) :
    (∑ i, a i • c.pderiv i) ∈ c.logDer h ↔ a h ∈ Ideal.span {c.x h} := by
  rw [logDer, sum_smul_pderiv_mem_logDerE_iff]
  simp only [Finset.mem_singleton, forall_eq]

/-- The generators of `Der(−log E)`: `xᵢ ∂ᵢ` for `i ∈ E` and `∂ⱼ` for `j ∉ E`. -/
def logGens (E : Finset (Fin n)) : Set (Derivation ℚ R R) :=
  (fun i => c.x i • c.pderiv i) '' (E : Set (Fin n)) ∪ c.pderiv '' ((E : Set (Fin n))ᶜ)

/-- `xᵢ ∂ᵢ` preserves every `⟨x_l⟩`, so it lies in `Der(−log E)` for every `E`. -/
theorem x_smul_pderiv_mem_logDerE (E : Finset (Fin n)) (i : Fin n) :
    c.x i • c.pderiv i ∈ c.logDerE E := by
  refine c.mem_logDerE.mpr ⟨Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩), ?_⟩
  intro l _ f hf
  rw [Derivation.smul_apply, smul_eq_mul]
  by_cases hil : i = l
  · subst hil
    exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)
  · exact Ideal.mul_mem_left _ _ (c.pderiv_mem_span_x_of_ne' l hil hf)

theorem pderiv_mem_logDerE {E : Finset (Fin n)} {j : Fin n} (hj : j ∉ E) :
    c.pderiv j ∈ c.logDerE E := by
  refine c.mem_logDerE.mpr ⟨Submodule.subset_span ⟨j, rfl⟩, ?_⟩
  intro l hl f hf
  exact c.pderiv_mem_span_x_of_ne' l (by rintro rfl; exact hj hl) hf

/-- `Der(−log E)` is generated by `xᵢ ∂ᵢ` (`i ∈ E`) and `∂ⱼ` (`j ∉ E`) (Kollár's
`Der_X(−log S) = ⟨x₁ ∂₁, ∂₂, …, ∂ₙ⟩` [Kol07, 87]; [BM08, §3]); for `δ = ∑ᵢ cᵢ ∂ᵢ` the condition
`δ(⟨xᵢ⟩) ≤ ⟨xᵢ⟩` says exactly `cᵢ ∈ ⟨xᵢ⟩`. -/
theorem logDerE_eq_span (E : Finset (Fin n)) :
    c.logDerE E = Submodule.span R (c.logGens E) := by
  classical
  refine le_antisymm ?_ (Submodule.span_le.mpr ?_)
  · intro δ hδ
    obtain ⟨hspan, hpres⟩ := c.mem_logDerE.mp hδ
    obtain ⟨a, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun R).mp hspan
    -- for `i ∈ E`, the coefficient `aᵢ = δ(xᵢ)` lies in `⟨xᵢ⟩`
    have hcoef : ∀ i ∈ E, ∃ b, b * c.x i = a i := by
      intro i hi
      have h1 := hpres i hi (c.x i) (Ideal.mem_span_singleton_self _)
      rw [c.sum_smul_pderiv_apply_x] at h1
      exact Ideal.mem_span_singleton'.mp h1
    choose! b hb using hcoef
    rw [← Finset.sum_add_sum_compl E]
    refine Submodule.add_mem _ (Submodule.sum_mem _ fun i hi => ?_)
      (Submodule.sum_mem _ fun j hj => ?_)
    · rw [← hb i hi, ← smul_smul]
      exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inl ⟨i, hi, rfl⟩))
    · exact Submodule.smul_mem _ _ (Submodule.subset_span
        (Or.inr ⟨j, Finset.mem_compl.mp hj, rfl⟩))
  · rintro δ (⟨i, -, rfl⟩ | ⟨j, hj, rfl⟩)
    · exact c.x_smul_pderiv_mem_logDerE E i
    · exact c.pderiv_mem_logDerE hj

/-- `Der(−log S)`, `S = V(x_h)`, is generated by `x_h ∂_h` and the `∂ⱼ`, `j ≠ h` [Kol07, 87]. -/
theorem logDer_eq_span (h : Fin n) :
    c.logDer h = Submodule.span R ({c.x h • c.pderiv h} ∪ c.pderiv '' {j | j ≠ h}) := by
  rw [logDer, logDerE_eq_span, logGens, Finset.coe_singleton, Set.image_singleton,
    Set.compl_singleton_eq]

/-! ### The logarithmic derivative ideals -/

/-- The logarithmic derivative ideal
`D_E(I) := I + ⟨xᵢ ∂ᵢ f : i ∈ E, f ∈ I⟩ + ⟨∂ⱼ f : j ∉ E, f ∈ I⟩` ([BM08, §3]; for `E = {h}`,
Kollár's `D(−log S)(I)`, [Kol07, 87]). -/
def DlogE (E : Finset (Fin n)) (I : Ideal R) : Ideal R :=
  I ⊔ (⨆ i ∈ E, Ideal.span ((fun f => c.x i * c.pderiv i f) '' I)) ⊔
    ⨆ (j) (_ : j ∉ E), Ideal.span (c.pderiv j '' I)

/-- The iterated logarithmic derivative ideal `D_E^r(I)`. -/
def DlogEpow (E : Finset (Fin n)) (r : ℕ) (I : Ideal R) : Ideal R := (c.DlogE E)^[r] I

/-- `D(−log S)(I)` for `S = V(x_h)` [Kol07, 87]. -/
abbrev Dlog (h : Fin n) (I : Ideal R) : Ideal R := c.DlogE {h} I

/-- `D^r(−log S)(I)`. -/
abbrev Dlogpow (h : Fin n) (r : ℕ) (I : Ideal R) : Ideal R := c.DlogEpow {h} r I

@[simp] theorem DlogEpow_zero (E : Finset (Fin n)) (I : Ideal R) : c.DlogEpow E 0 I = I := rfl

theorem DlogEpow_succ (E : Finset (Fin n)) (r : ℕ) (I : Ideal R) :
    c.DlogEpow E (r + 1) I = c.DlogE E (c.DlogEpow E r I) :=
  Function.iterate_succ_apply' _ _ _

theorem DlogEpow_succ' (E : Finset (Fin n)) (r : ℕ) (I : Ideal R) :
    c.DlogEpow E (r + 1) I = c.DlogEpow E r (c.DlogE E I) :=
  Function.iterate_succ_apply _ _ _

theorem DlogEpow_add (E : Finset (Fin n)) (r s : ℕ) (I : Ideal R) :
    c.DlogEpow E r (c.DlogEpow E s I) = c.DlogEpow E (r + s) I :=
  (Function.iterate_add_apply _ _ _ _).symm

theorem le_DlogE (E : Finset (Fin n)) (I : Ideal R) : I ≤ c.DlogE E I :=
  le_sup_left.trans le_sup_left

theorem x_mul_pderiv_mem_DlogE {E : Finset (Fin n)} {i : Fin n} (hi : i ∈ E) {I : Ideal R} {f : R}
    (hf : f ∈ I) : c.x i * c.pderiv i f ∈ c.DlogE E I :=
  Ideal.mem_sup_left (Ideal.mem_sup_right (Ideal.mem_iSup_of_mem i
    (Ideal.mem_iSup_of_mem hi (Ideal.subset_span ⟨f, hf, rfl⟩))))

theorem pderiv_mem_DlogE {E : Finset (Fin n)} {j : Fin n} (hj : j ∉ E) {I : Ideal R} {f : R}
    (hf : f ∈ I) : c.pderiv j f ∈ c.DlogE E I :=
  Ideal.mem_sup_right (Ideal.mem_iSup_of_mem j (Ideal.mem_iSup_of_mem hj
    (Ideal.subset_span ⟨f, hf, rfl⟩)))

theorem DlogE_le_iff {E : Finset (Fin n)} {I J : Ideal R} :
    c.DlogE E I ≤ J ↔
      I ≤ J ∧ (∀ i ∈ E, ∀ f ∈ I, c.x i * c.pderiv i f ∈ J) ∧
        ∀ j, j ∉ E → ∀ f ∈ I, c.pderiv j f ∈ J := by
  constructor
  · intro h
    exact ⟨(c.le_DlogE E I).trans h, fun _ hi _ hf => h (c.x_mul_pderiv_mem_DlogE hi hf),
      fun _ hj _ hf => h (c.pderiv_mem_DlogE hj hf)⟩
  · rintro ⟨h1, h2, h3⟩
    refine sup_le (sup_le h1 (iSup_le fun i => iSup_le fun hi => Ideal.span_le.mpr ?_))
      (iSup_le fun j => iSup_le fun hj => Ideal.span_le.mpr ?_)
    · rintro _ ⟨f, hf, rfl⟩
      exact h2 i hi f hf
    · rintro _ ⟨f, hf, rfl⟩
      exact h3 j hj f hf

theorem DlogE_mono {E : Finset (Fin n)} {I J : Ideal R} (h : I ≤ J) : c.DlogE E I ≤ c.DlogE E J :=
  c.DlogE_le_iff.mpr ⟨h.trans (c.le_DlogE E J), fun _ hi _ hf => c.x_mul_pderiv_mem_DlogE hi (h hf),
    fun _ hj _ hf => c.pderiv_mem_DlogE hj (h hf)⟩

theorem DlogEpow_mono {E : Finset (Fin n)} (r : ℕ) {I J : Ideal R} (h : I ≤ J) :
    c.DlogEpow E r I ≤ c.DlogEpow E r J := by
  induction r with
  | zero => exact h
  | succ r ih => rw [DlogEpow_succ, DlogEpow_succ]; exact c.DlogE_mono ih

theorem le_DlogEpow (E : Finset (Fin n)) (r : ℕ) (I : Ideal R) : I ≤ c.DlogEpow E r I := by
  induction r with
  | zero => exact le_rfl
  | succ r ih => rw [DlogEpow_succ]; exact ih.trans (c.le_DlogE E _)

theorem DlogEpow_mono_left {E : Finset (Fin n)} {r s : ℕ} (h : r ≤ s) (I : Ideal R) :
    c.DlogEpow E r I ≤ c.DlogEpow E s I := by
  obtain ⟨t, rfl⟩ := Nat.exists_eq_add_of_le h
  rw [add_comm, ← DlogEpow_add]
  exact c.le_DlogEpow E t _

theorem DlogE_sup (E : Finset (Fin n)) (I J : Ideal R) :
    c.DlogE E (I ⊔ J) = c.DlogE E I ⊔ c.DlogE E J := by
  refine le_antisymm (c.DlogE_le_iff.mpr ⟨sup_le_sup (c.le_DlogE E I) (c.le_DlogE E J), ?_, ?_⟩)
    (sup_le (c.DlogE_mono le_sup_left) (c.DlogE_mono le_sup_right))
  · intro i hi f hf
    obtain ⟨g₁, hg₁, g₂, hg₂, rfl⟩ := Submodule.mem_sup.mp hf
    rw [map_add, mul_add]
    exact Ideal.add_mem _ (Ideal.mem_sup_left (c.x_mul_pderiv_mem_DlogE hi hg₁))
      (Ideal.mem_sup_right (c.x_mul_pderiv_mem_DlogE hi hg₂))
  · intro j hj f hf
    obtain ⟨g₁, hg₁, g₂, hg₂, rfl⟩ := Submodule.mem_sup.mp hf
    rw [map_add]
    exact Ideal.add_mem _ (Ideal.mem_sup_left (c.pderiv_mem_DlogE hj hg₁))
      (Ideal.mem_sup_right (c.pderiv_mem_DlogE hj hg₂))

theorem DlogE_iSup {ι : Sort*} (E : Finset (Fin n)) (I : ι → Ideal R) :
    c.DlogE E (⨆ k, I k) = ⨆ k, c.DlogE E (I k) := by
  refine le_antisymm (c.DlogE_le_iff.mpr ⟨iSup_le fun k =>
      (c.le_DlogE E (I k)).trans (le_iSup (fun k => c.DlogE E (I k)) k), ?_, ?_⟩)
    (iSup_le fun k => c.DlogE_mono (le_iSup I k))
  · intro i hi f hf
    induction hf using Submodule.iSup_induction' with
    | mem k f hf => exact Ideal.mem_iSup_of_mem k (c.x_mul_pderiv_mem_DlogE hi hf)
    | zero => rw [map_zero, mul_zero]; exact Ideal.zero_mem _
    | add f g _ _ hf hg => rw [map_add, mul_add]; exact Ideal.add_mem _ hf hg
  · intro j hj f hf
    induction hf using Submodule.iSup_induction' with
    | mem k f hf => exact Ideal.mem_iSup_of_mem k (c.pderiv_mem_DlogE hj hf)
    | zero => rw [map_zero]; exact Ideal.zero_mem _
    | add f g _ _ hf hg => rw [map_add]; exact Ideal.add_mem _ hf hg

theorem DlogEpow_sup (E : Finset (Fin n)) (r : ℕ) (I J : Ideal R) :
    c.DlogEpow E r (I ⊔ J) = c.DlogEpow E r I ⊔ c.DlogEpow E r J := by
  induction r with
  | zero => rfl
  | succ r ih => rw [DlogEpow_succ, ih, DlogE_sup, DlogEpow_succ, DlogEpow_succ]

theorem DlogEpow_iSup {ι : Sort*} (E : Finset (Fin n)) (r : ℕ) (I : ι → Ideal R) :
    c.DlogEpow E r (⨆ k, I k) = ⨆ k, c.DlogEpow E r (I k) := by
  induction r with
  | zero => rfl
  | succ r ih => simp only [DlogEpow_succ, ih, DlogE_iSup]

/-- Kollár's image definition `D(−log E)(I) = im[Der(−log E) × I → 𝒪]` [Kol07, 87] agrees with
the generator description. -/
theorem DlogE_eq_iSup_logDerE (E : Finset (Fin n)) (I : Ideal R) :
    c.DlogE E I = I ⊔ ⨆ δ ∈ c.logDerE E, Ideal.span (δ '' I) := by
  refine le_antisymm (c.DlogE_le_iff.mpr ⟨le_sup_left, ?_, ?_⟩) (sup_le (c.le_DlogE E I) ?_)
  · intro i _ f hf
    refine Ideal.mem_sup_right (Ideal.mem_iSup_of_mem (c.x i • c.pderiv i)
      (Ideal.mem_iSup_of_mem (c.x_smul_pderiv_mem_logDerE E i) (Ideal.subset_span ⟨f, hf, ?_⟩)))
    rw [Derivation.smul_apply, smul_eq_mul]
  · intro j hj f hf
    exact Ideal.mem_sup_right (Ideal.mem_iSup_of_mem (c.pderiv j)
      (Ideal.mem_iSup_of_mem (c.pderiv_mem_logDerE hj) (Ideal.subset_span ⟨f, hf, rfl⟩)))
  · refine iSup_le fun δ => iSup_le fun hδ => Ideal.span_le.mpr ?_
    rintro _ ⟨f, hf, rfl⟩
    rw [c.logDerE_eq_span] at hδ
    induction hδ using Submodule.span_induction with
    | mem δ hgen =>
      rcases hgen with ⟨i, hi, rfl⟩ | ⟨j, hj, rfl⟩
      · rw [Derivation.smul_apply, smul_eq_mul]
        exact c.x_mul_pderiv_mem_DlogE hi hf
      · exact c.pderiv_mem_DlogE hj hf
    | zero => rw [Derivation.zero_apply]; exact Ideal.zero_mem _
    | add δ₁ δ₂ _ _ h₁ h₂ => rw [Derivation.add_apply]; exact Ideal.add_mem _ h₁ h₂
    | smul a δ _ h => rw [Derivation.smul_apply, smul_eq_mul]; exact Ideal.mul_mem_left _ _ h

/-- Kollár's image definition of `D(−log S)(I)` [Kol07, 87] agrees with the generator
description. -/
theorem Dlog_eq_iSup_logDer (h : Fin n) (I : Ideal R) :
    c.Dlog h I = I ⊔ ⨆ δ ∈ c.logDer h, Ideal.span (δ '' I) :=
  c.DlogE_eq_iSup_logDerE {h} I

/-- `D(−log S)(I) ≤ J` iff `J` contains `I`, the `x_h ∂_h f` and the `∂ⱼ f` (`j ≠ h`), `f ∈ I`. -/
theorem Dlog_le_iff (h : Fin n) {I J : Ideal R} :
    c.Dlog h I ≤ J ↔
      I ≤ J ∧ (∀ f ∈ I, c.x h * c.pderiv h f ∈ J) ∧ ∀ j, j ≠ h → ∀ f ∈ I, c.pderiv j f ∈ J := by
  rw [Dlog, DlogE_le_iff]
  simp only [Finset.mem_singleton, forall_eq, ne_eq]

@[simp] theorem Dlogpow_zero (h : Fin n) (I : Ideal R) : c.Dlogpow h 0 I = I := rfl

/-- `D^{r+1}(−log S)(I) = D(−log S)(D^r(−log S)(I))` [Kol07, 87]. -/
theorem Dlogpow_succ (h : Fin n) (r : ℕ) (I : Ideal R) :
    c.Dlogpow h (r + 1) I = c.Dlog h (c.Dlogpow h r I) :=
  c.DlogEpow_succ {h} r I

/-! ### The decomposition of `D(J)` and the filtration -/

theorem DlogE_le_D (E : Finset (Fin n)) (I : Ideal R) : c.DlogE E I ≤ c.D I :=
  c.DlogE_le_iff.mpr ⟨c.le_D I, fun i _ _ hf => Ideal.mul_mem_left _ _ (c.pderiv_mem_D hf i),
    fun j _ _ hf => c.pderiv_mem_D hf j⟩

/-- `D(J) = D(−log S)(J) + ⟨∂_h J⟩`, the first step of (87.2) of [Kol07, 87]. -/
theorem D_eq_Dlog_sup (h : Fin n) (J : Ideal R) :
    c.D J = c.Dlog h J ⊔ Ideal.span (c.pderiv h '' J) := by
  refine le_antisymm (c.D_le_iff.mpr ⟨(c.le_DlogE _ J).trans le_sup_left, fun i f hf => ?_⟩)
    (sup_le (c.DlogE_le_D _ J) (Ideal.span_le.mpr ?_))
  · by_cases hi : i = h
    · subst hi
      exact Ideal.mem_sup_right (Ideal.subset_span ⟨f, hf, rfl⟩)
    · exact Ideal.mem_sup_left (c.pderiv_mem_DlogE (by simpa using hi) hf)
  · rintro _ ⟨f, hf, rfl⟩
    exact c.pderiv_mem_D hf h

/-- One step of the filtration of [Kol07, 87]: `D^{s+1}(−log S)(J) ≤ D^s(−log S)(D(J))`. -/
theorem Dlogpow_succ_le (h : Fin n) (s : ℕ) (J : Ideal R) :
    c.Dlogpow h (s + 1) J ≤ c.Dlogpow h s (c.D J) := by
  rw [Dlogpow, DlogEpow_succ']
  exact c.DlogEpow_mono s (c.DlogE_le_D _ J)

/-- The filtration
`D^s(−log S)(I) ≤ D^{s−j}(−log S)(D^j(I)) ≤ D^{s−j−1}(−log S)(D^{j+1}(I)) ≤ ⋯ ≤ D^s(I)` of
[Kol07, 87]. -/
theorem Dlogpow_Dpow_le (h : Fin n) {s j : ℕ} (hj : j < s) (I : Ideal R) :
    c.Dlogpow h (s - j) (c.Dpow j I) ≤ c.Dlogpow h (s - (j + 1)) (c.Dpow (j + 1) I) := by
  obtain ⟨t, rfl⟩ : ∃ t, s = j + 1 + t := ⟨s - (j + 1), by omega⟩
  rw [show j + 1 + t - j = t + 1 by omega, show j + 1 + t - (j + 1) = t by omega, Dpow_succ]
  exact c.Dlogpow_succ_le h t _

theorem Dlogpow_le_Dpow (h : Fin n) (s : ℕ) (I : Ideal R) : c.Dlogpow h s I ≤ c.Dpow s I := by
  induction s with
  | zero => exact le_rfl
  | succ s ih =>
    rw [Dlogpow, DlogEpow_succ, Dpow_succ]
    exact (c.DlogE_le_D _ _).trans (c.D_mono ih)

/-! ### The case `E = ∅` -/

theorem DlogE_empty (I : Ideal R) : c.DlogE ∅ I = c.D I := by
  refine le_antisymm (c.DlogE_le_D ∅ I) (c.D_le_iff.mpr ⟨c.le_DlogE ∅ I, fun j _ hf =>
    c.pderiv_mem_DlogE (Finset.notMem_empty j) hf⟩)

theorem DlogEpow_empty (r : ℕ) (I : Ideal R) : c.DlogEpow ∅ r I = c.Dpow r I := by
  induction r with
  | zero => rfl
  | succ r ih => rw [DlogEpow_succ, ih, DlogE_empty, Dpow_succ]

theorem DlogEpow_le_Dpow (E : Finset (Fin n)) (r : ℕ) (I : Ideal R) :
    c.DlogEpow E r I ≤ c.Dpow r I := by
  induction r with
  | zero => exact le_rfl
  | succ r ih => rw [DlogEpow_succ, Dpow_succ]; exact (c.DlogE_le_D _ _).trans (c.D_mono ih)

/-- The boundary case showing that the equality of [BM08, Lemma 3.2(3)] needs `E = ∅`: for
`h ∈ E`, `D_E(⟨x_h⟩) = ⟨x_h⟩` — the logarithmic derivative ideal of the divisor itself does not
grow. -/
theorem DlogE_span_x_self {E : Finset (Fin n)} {h : Fin n} (hh : h ∈ E) :
    c.DlogE E (Ideal.span {c.x h}) = Ideal.span {c.x h} := by
  refine le_antisymm (c.DlogE_le_iff.mpr ⟨le_rfl, fun i _ f hf => ?_,
    fun j hj f hf => c.pderiv_mem_span_x_of_ne' h (by rintro rfl; exact hj hh) hf⟩) (c.le_DlogE E _)
  by_cases hi : i = h
  · rw [hi]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self _)
  · exact Ideal.mul_mem_left _ _ (c.pderiv_mem_span_x_of_ne' h hi hf)

/-! ### The decomposition (87.2): `∂_h` against the logarithmic derivative ideals -/

/-- For a derivation `δ` and an ideal `K`, the set `{f ∈ K | δ f ∈ K}` is an ideal (Leibniz);
the device for showing `δ(J) ≤ K` on generators of `J`. -/
def derivStable (δ : Derivation ℚ R R) (K : Ideal R) : Ideal R where
  carrier := {f | f ∈ K ∧ δ f ∈ K}
  add_mem' {f g} hf hg := ⟨K.add_mem hf.1 hg.1, by rw [map_add]; exact K.add_mem hf.2 hg.2⟩
  zero_mem' := ⟨K.zero_mem, by rw [map_zero]; exact K.zero_mem⟩
  smul_mem' a {f} hf := ⟨K.mul_mem_left a hf.1, by
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    exact K.add_mem (K.mul_mem_left _ hf.2) (K.mul_mem_right _ hf.1)⟩

omit [IsRegularLocalRing R] in
theorem mem_derivStable {δ : Derivation ℚ R R} {K : Ideal R} {f : R} :
    f ∈ derivStable δ K ↔ f ∈ K ∧ δ f ∈ K := Iff.rfl

/-- `∂_h (⟨S⟩) ≤ ⟨S⟩ + ⟨∂_h S⟩` (Leibniz). -/
theorem span_pderiv_image_span_le (h : Fin n) (S : Set R) :
    Ideal.span (c.pderiv h '' Ideal.span S) ≤ Ideal.span S ⊔ Ideal.span (c.pderiv h '' S) := by
  have hle : Ideal.span S ≤
      derivStable (c.pderiv h) (Ideal.span S ⊔ Ideal.span (c.pderiv h '' S)) :=
    Ideal.span_le.mpr fun f hf => ⟨Ideal.mem_sup_left (Ideal.subset_span hf),
      Ideal.mem_sup_right (Ideal.subset_span ⟨f, hf, rfl⟩)⟩
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨f, hf, rfl⟩
  exact (hle hf).2

theorem span_pderiv_image_mono (h : Fin n) {J₁ J₂ : Ideal R} (hJ : J₁ ≤ J₂) :
    Ideal.span (c.pderiv h '' J₁) ≤ Ideal.span (c.pderiv h '' J₂) :=
  Ideal.span_mono (Set.image_mono hJ)

theorem span_pderiv_image_iSup_le {ι : Sort*} (h : Fin n) (J : ι → Ideal R) :
    Ideal.span (c.pderiv h '' (⨆ k, J k : Ideal R)) ≤ ⨆ k, Ideal.span (c.pderiv h '' J k) := by
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨f, hf, rfl⟩
  induction hf using Submodule.iSup_induction' with
  | mem k f hf => exact Ideal.mem_iSup_of_mem k (Ideal.subset_span ⟨f, hf, rfl⟩)
  | zero => rw [map_zero]; exact Ideal.zero_mem _
  | add f g _ _ hf hg => rw [map_add]; exact Ideal.add_mem _ hf hg

/-- The key step for (87.2): on the generators of `D_E(J)`, `∂_h f ∈ ⟨∂_h J⟩`,
`∂_h(xᵢ ∂ᵢ f) = xᵢ ∂ᵢ(∂_h f) + [i = h] ∂_h f`, `∂_h ∂ⱼ f = ∂ⱼ ∂_h f`; hence
`∂_h (D_E(J)) ≤ D_E(⟨∂_h J⟩) + D_E(J)`. -/
theorem span_pderiv_image_DlogE_le (E : Finset (Fin n)) (h : Fin n) (J : Ideal R) :
    Ideal.span (c.pderiv h '' c.DlogE E J) ≤
      c.DlogE E (Ideal.span (c.pderiv h '' J)) ⊔ c.DlogE E J := by
  have hΔ : ∀ f ∈ J, c.pderiv h f ∈ Ideal.span (c.pderiv h '' J) :=
    fun f hf => Ideal.subset_span ⟨f, hf, rfl⟩
  have hle : c.DlogE E J ≤
      derivStable (c.pderiv h) (c.DlogE E (Ideal.span (c.pderiv h '' J)) ⊔ c.DlogE E J) := by
    refine c.DlogE_le_iff.mpr ⟨fun f hf => ⟨Ideal.mem_sup_right (c.le_DlogE E J hf),
      Ideal.mem_sup_left (c.le_DlogE E _ (hΔ f hf))⟩, fun i hi f hf =>
      ⟨Ideal.mem_sup_right (c.x_mul_pderiv_mem_DlogE hi hf), ?_⟩, fun j hj f hf =>
      ⟨Ideal.mem_sup_right (c.pderiv_mem_DlogE hj hf), ?_⟩⟩
    · rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x, c.pderiv_comm]
      refine Ideal.add_mem _ (Ideal.mem_sup_left (c.x_mul_pderiv_mem_DlogE hi (hΔ f hf))) ?_
      split_ifs with hih
      · rw [mul_one, ← hih]
        exact Ideal.mem_sup_left (c.le_DlogE E _ (hΔ f hf))
      · rw [mul_zero]
        exact Ideal.zero_mem _
    · rw [c.pderiv_comm]
      exact Ideal.mem_sup_left (c.pderiv_mem_DlogE hj (hΔ f hf))
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨f, hf, rfl⟩
  exact (hle hf).2

/-- Iterating the key step: `∂_h (D_E^t(J)) ≤ D_E^t(⟨∂_h J⟩) + D_E^t(J)`. -/
theorem span_pderiv_image_DlogEpow_le (E : Finset (Fin n)) (h : Fin n) (t : ℕ) (J : Ideal R) :
    Ideal.span (c.pderiv h '' c.DlogEpow E t J) ≤
      c.DlogEpow E t (Ideal.span (c.pderiv h '' J)) ⊔ c.DlogEpow E t J := by
  induction t generalizing J with
  | zero => exact le_sup_left
  | succ t ih =>
    simp only [DlogEpow_succ']
    refine (ih _).trans (sup_le_sup_right (c.DlogEpow_mono t (c.span_pderiv_image_DlogE_le E h J)) _
      |>.trans ?_)
    rw [DlogEpow_sup, sup_assoc, sup_idem]

/-- `⟨∂_h^j I⟩`, the ideal generated by the `j`-fold `h`-partials of the elements of `I`
(Kollár's `⟨∂^j I/∂x_1^j⟩` in (87.2) of [Kol07, 87]). -/
def iterPderivIdeal (h : Fin n) (j : ℕ) (I : Ideal R) : Ideal R :=
  Ideal.span ((⇑(c.pderiv h))^[j] '' I)

@[simp] theorem iterPderivIdeal_zero (h : Fin n) (I : Ideal R) : c.iterPderivIdeal h 0 I = I := by
  rw [iterPderivIdeal, Function.iterate_zero, Set.image_id, Ideal.span_eq]

/-- `∂_h^j f ∈ D^j(I)` for `f ∈ I`. -/
theorem iterate_pderiv_mem_Dpow (h : Fin n) {I : Ideal R} {f : R} (hf : f ∈ I) (j : ℕ) :
    (⇑(c.pderiv h))^[j] f ∈ c.Dpow j I := by
  induction j with
  | zero => exact hf
  | succ j ih => rw [Function.iterate_succ_apply', Dpow_succ]; exact c.pderiv_mem_D ih h

theorem iterPderivIdeal_le_Dpow (h : Fin n) (j : ℕ) (I : Ideal R) :
    c.iterPderivIdeal h j I ≤ c.Dpow j I :=
  Ideal.span_le.mpr (by rintro _ ⟨f, hf, rfl⟩; exact c.iterate_pderiv_mem_Dpow h hf j)

/-- `∂_h ⟨∂_h^j I⟩ ≤ ⟨∂_h^j I⟩ + ⟨∂_h^{j+1} I⟩` (Leibniz). -/
theorem span_pderiv_image_iterPderivIdeal_le (h : Fin n) (j : ℕ) (I : Ideal R) :
    Ideal.span (c.pderiv h '' c.iterPderivIdeal h j I) ≤
      c.iterPderivIdeal h j I ⊔ c.iterPderivIdeal h (j + 1) I := by
  refine (c.span_pderiv_image_span_le h _).trans (sup_le_sup_left (le_of_eq ?_) _)
  rw [iterPderivIdeal, Set.image_image, Function.iterate_succ']
  rfl

/-- The filtration of [Kol07, 87] in one statement:
`D^{s-i}(−log S)(D^i(I)) ≤ D^{s-j}(−log S)(D^j(I))` for `i ≤ j ≤ s`. -/
theorem Dlogpow_Dpow_le_of_le (h : Fin n) {s i j : ℕ} (hij : i ≤ j) (hj : j ≤ s) (I : Ideal R) :
    c.Dlogpow h (s - i) (c.Dpow i I) ≤ c.Dlogpow h (s - j) (c.Dpow j I) := by
  induction j, hij using Nat.le_induction with
  | base => exact le_rfl
  | succ j hij ih => exact (ih (by omega)).trans (c.Dlogpow_Dpow_le h (by omega) I)

/-- The inclusion `⊇` of (87.2): the summands `D^{s-i}(−log S)(⟨∂_h^i I⟩)`, `i ≤ j`, lie in
`D^{s-j}(−log S)(D^j(I))`. -/
theorem iSup_Dlogpow_iterPderivIdeal_le (h : Fin n) {s j : ℕ} (hj : j ≤ s) (I : Ideal R) :
    ⨆ i ≤ j, c.Dlogpow h (s - i) (c.iterPderivIdeal h i I) ≤ c.Dlogpow h (s - j) (c.Dpow j I) :=
  iSup₂_le fun i hi => (c.DlogEpow_mono _ (c.iterPderivIdeal_le_Dpow h i I)).trans
    (c.Dlogpow_Dpow_le_of_le h hi hj I)

/-- The inclusion `⊆` of (87.2), by induction on `j`: the step uses `D_eq_Dlog_sup`, the case
`s = j` of the induction hypothesis (`D^j(I) = ∑_{i ≤ j} D^{j-i}(−log S)(⟨∂_h^i I⟩)`), and the
key step `∂_h D^t(−log S)(J) ≤ D^t(−log S)(⟨∂_h J⟩) + D^t(−log S)(J)`. -/
theorem Dlogpow_Dpow_le_iSup (h : Fin n) (j : ℕ) (I : Ideal R) :
    ∀ s, j ≤ s → c.Dlogpow h (s - j) (c.Dpow j I) ≤
      ⨆ i ≤ j, c.Dlogpow h (s - i) (c.iterPderivIdeal h i I) := by
  induction j with
  | zero =>
    intro s _
    exact le_iSup₂_of_le 0 le_rfl (le_of_eq (by rw [Dpow_zero, iterPderivIdeal_zero]))
  | succ j ih =>
    intro s hs
    obtain ⟨t, rfl⟩ : ∃ t, s = j + 1 + t := ⟨s - (j + 1), by omega⟩
    -- the expansion of `D^j(I)` at `s = j`
    have hDj : c.Dpow j I ≤ ⨆ i ≤ j, c.DlogEpow {h} (j - i) (c.iterPderivIdeal h i I) := by
      have := ih j le_rfl
      rwa [Nat.sub_self, Dlogpow, DlogEpow_zero] at this
    -- `∂_h D^j(I)` through that expansion and the key step
    have h2 : Ideal.span (c.pderiv h '' c.Dpow j I) ≤ ⨆ i ≤ j,
        (c.DlogEpow {h} (j - i) (c.iterPderivIdeal h i I) ⊔
          c.DlogEpow {h} (j - i) (c.iterPderivIdeal h (i + 1) I)) := by
      refine (c.span_pderiv_image_mono h hDj).trans ((c.span_pderiv_image_iSup_le h _).trans
        (iSup_mono fun i => (c.span_pderiv_image_iSup_le h _).trans (iSup_mono fun _ => ?_)))
      refine (c.span_pderiv_image_DlogEpow_le {h} h _ _).trans (sup_le ?_ le_sup_left)
      refine (c.DlogEpow_mono _ (c.span_pderiv_image_iterPderivIdeal_le h i I)).trans ?_
      rw [DlogEpow_sup]
    have h1 := ih (j + 1 + t) (by omega)
    rw [show j + 1 + t - j = t + 1 by omega] at h1
    rw [show j + 1 + t - (j + 1) = t by omega, Dpow_succ, c.D_eq_Dlog_sup h]
    simp only [Dlogpow, Dlog] at h1 ⊢
    rw [DlogEpow_succ'] at h1
    rw [DlogEpow_sup]
    refine sup_le (h1.trans (iSup₂_mono' fun i hi => ⟨i, by omega, le_rfl⟩)) ?_
    refine (c.DlogEpow_mono t h2).trans ?_
    simp only [DlogEpow_iSup, DlogEpow_sup, DlogEpow_add]
    refine iSup₂_le fun i hi => sup_le ?_ ?_
    · exact le_iSup₂_of_le i (by omega) (c.DlogEpow_mono_left (by omega) _)
    · rw [show t + (j - i) = j + 1 + t - (i + 1) by omega]
      exact le_iSup₂_of_le (i + 1) (by omega) le_rfl

/-- The second clause of (87.2) of [Kol07, 87]: the first `j + 1` summands span
`D^{s-j}(−log S)(D^j(I))`. -/
theorem Dlogpow_Dpow_eq_iSup (h : Fin n) {s j : ℕ} (hj : j ≤ s) (I : Ideal R) :
    c.Dlogpow h (s - j) (c.Dpow j I) = ⨆ i ≤ j, c.Dlogpow h (s - i) (c.iterPderivIdeal h i I) :=
  le_antisymm (c.Dlogpow_Dpow_le_iSup h j I s hj) (c.iSup_Dlogpow_iterPderivIdeal_le h hj I)

/-- The decomposition (87.2) of [Kol07, 87]: `D^s(I) = ∑_{j=0}^{s} D^{s-j}(−log S)(⟨∂_h^j I⟩)`
(the sum of ideals is their supremum). -/
theorem Dpow_eq_sum_Dlogpow (h : Fin n) (s : ℕ) (I : Ideal R) :
    c.Dpow s I = ⨆ j ≤ s, c.Dlogpow h (s - j) (c.iterPderivIdeal h j I) := by
  have := c.Dlogpow_Dpow_eq_iSup h le_rfl (s := s) I
  rwa [Nat.sub_self, Dlogpow, DlogEpow_zero] at this

end RegularCoords

/-! ### Restriction to the hypersurface, (87.1) -/

namespace RegularCoords

open Ideal

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {k : ℕ}
  (c : RegularCoords R (k + 1)) (h : Fin (k + 1))

/-- One step of (87.1): the image of `D(−log S)(J)` in `R̄ = R/⟨x_h⟩` is `D_{R̄}(J̄)` —
`x_h ∂_h f ↦ 0`, `∂ⱼ f ↦ ∂̄ⱼ f̄` (the coordinates `quotientCoords` of the hypersurface). -/
theorem Dlog_map_quotient (J : Ideal R) :
    (c.Dlog h J).map (Ideal.Quotient.mk (span {c.x h})) =
      (c.quotientCoords h).D (J.map (Ideal.Quotient.mk (span {c.x h}))) := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    refine c.DlogE_le_iff.mpr ⟨fun f hf => ?_, fun i hi f _ => ?_, fun j hj f hf => ?_⟩
    · exact Ideal.mem_comap.mpr ((c.quotientCoords h).le_D _ (Ideal.mem_map_of_mem _ hf))
    · rw [Finset.mem_singleton.mp hi, Ideal.mem_comap, map_mul,
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mem_span_singleton_self _), zero_mul]
      exact Ideal.zero_mem _
    · obtain ⟨j', rfl⟩ := Fin.exists_succAbove_eq (Finset.mem_singleton.not.mp hj)
      rw [Ideal.mem_comap, ← c.quotientCoords_pderiv_mk h j' f]
      exact (c.quotientCoords h).pderiv_mem_D (Ideal.mem_map_of_mem _ hf) j'
  · refine (c.quotientCoords h).D_le_iff.mpr
      ⟨Ideal.map_mono (c.le_DlogE _ J), fun j' g hg => ?_⟩
    obtain ⟨f, hf, rfl⟩ :=
      (Ideal.mem_map_iff_of_surjective _ Ideal.Quotient.mk_surjective).mp hg
    rw [c.quotientCoords_pderiv_mk h j' f]
    exact Ideal.mem_map_of_mem _
      (c.pderiv_mem_DlogE (fun e => Fin.succAbove_ne h j' (Finset.mem_singleton.mp e)) hf)

/-- The restriction property (87.1) of [Kol07, 87] (compare the proof of [Wlo05, Lemma 2.10.4]):
the image of `D^r(−log S)(I)` in `R̄ = R/⟨x_h⟩` is `D^r_{R̄}(Ī)`. -/
theorem Dlogpow_map_quotient (r : ℕ) (I : Ideal R) :
    (c.Dlogpow h r I).map (Ideal.Quotient.mk (span {c.x h})) =
      (c.quotientCoords h).Dpow r (I.map (Ideal.Quotient.mk (span {c.x h}))) := by
  induction r with
  | zero => rfl
  | succ r ih => rw [Dlogpow, DlogEpow_succ, Dpow_succ, ← ih]; exact c.Dlog_map_quotient h _

end RegularCoords

end IsLocalRing
