/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.OrderFlat
import Hironaka.Algebra.Local.CompletionMap
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.RingTheory.Flat.FaithfullyFlat.Basic

/-!
# The order under localizations of polynomial rings

For a prime `q` of `R[X₁, …, Xₙ]` over the prime `p` of `R`, the local map `R_p → R[X₁, …, Xₙ]_q`
reflects the powers of the maximal ideal (`OrdFaithful`, `Hironaka/Algebra/Local/OrderFlat.lean`),
so the order of an ideal is preserved (`ord_map_eq_of_atPrime_mvPolynomial`). This is the polynomial
case of the invariance of the order under smooth morphisms ([Hau03, Appendix A]). A retraction
`Xᵢ ↦ 0` would treat only the primes `q` at which the `Xᵢ` reduce to residue-field elements, the
points rational over the residue field; the proof here, the library's own, treats every prime,
variable by variable:

* One variable over a local base `R` (`ordFaithful_algebraMap_atPrime_polynomial`): a prime `Q` of
  `R[X]` containing `𝔪 R[X]` reduces to a prime of `κ[X]`, `κ = R/𝔪`, which is `0` or `(ḡ)` with `ḡ`
  monic.  In the first case `Q = 𝔪 R[X]`; in the second `Q = (G) + 𝔪 R[X]` for a monic lift `G` of
  `ḡ`, and `D = R[X]/(G)` is finite free over `R` with `Q D = 𝔪 D` a prime.  In both cases
  `R → R[X]_Q` factors through the flat local map `R → D_{QD}` with `𝔪 D_{QD} = 𝔪_{D_{QD}}`
  (`D = R[X]` in the first case), and a flat local map with this property reflects the powers of
  the maximal ideal by faithful flatness (`ordFaithful_algebraMap_atPrime_of_flat`,
  `OrdFaithful.of_comp`).
* One variable over any base (`ordFaithful_localRingHom_C`): `R_p[X]` is the localization of `R[X]`
  at `C(R ∖ p)`, so `R[X]_Q ≅ R_p[X]_{Q R_p[X]}` and the local case applies.
* `n` variables (`ordFaithful_localRingHom_mvPolynomial_C`): induction on `n` through
  `R[X₁, …, Xₙ₊₁] ≅ R[X₁, …, Xₙ][X]` (Mathlib's `MvPolynomial.finSuccEquiv`); the property composes.

Used for the smooth case in `Hironaka/Algebra/Local/OrderSmooth.lean`.
-/

public section

namespace IsLocalRing

open IsLocalRing Polynomial

section OneVariableLocal

variable {R : Type*} [CommRing R] [IsLocalRing R]

/-- The polynomial case in one variable over a local base `R`: for a prime `Q` of `R[X]`
containing `𝔪 R[X]`, the local map `R → R[X]_Q` reflects the powers of the maximal ideal.  The
image of `Q` in `κ[X]` is `0` (then `Q = 𝔪 R[X]`) or generated by a monic `ḡ` (then
`Q = (G) + 𝔪 R[X]` for a monic lift `G`, and `R[X]_Q → (R[X]/(G))_{𝔪}` is a local map to a flat
local `R`-algebra whose maximal ideal is generated by `𝔪`). -/
theorem ordFaithful_algebraMap_atPrime_polynomial (Q : Ideal R[X]) [Q.IsPrime]
    (hQ : (maximalIdeal R).map (C : R →+* R[X]) ≤ Q) :
    OrdFaithful (algebraMap R (Localization.AtPrime Q)) := by
  classical
  set π : R[X] →+* (ResidueField R)[X] := mapRingHom (residue R) with hπdef
  have hπ : Function.Surjective π := Polynomial.map_surjective _ residue_surjective
  have hker : RingHom.ker π = (maximalIdeal R).map (C : R →+* R[X]) := by
    rw [hπdef, Polynomial.ker_mapRingHom, ker_residue]
  have hkerQ : RingHom.ker π ≤ Q := by rw [hker]; exact hQ
  have : (Q.map π).IsPrime := Ideal.map_isPrime_of_surjective hπ hkerQ
  have hmapker : (RingHom.ker π).map π = ⊥ := by
    rw [RingHom.ker_eq_comap_bot]
    exact le_bot_iff.mp Ideal.map_comap_le
  obtain ⟨g, hg⟩ : ∃ g : (ResidueField R)[X], Q.map π = Ideal.span {g} :=
    ⟨_, (Ideal.span_singleton_generator _).symm⟩
  by_cases hg0 : g = 0
  · -- `Q = 𝔪 R[X]`
    have hQeq : Q = (maximalIdeal R).map (algebraMap R R[X]) := by
      refine le_antisymm (fun x hx => ?_) (by rwa [Polynomial.algebraMap_eq])
      have hx' : π x ∈ Q.map π := Ideal.mem_map_of_mem π hx
      rw [hg, hg0, Ideal.span_singleton_zero, Ideal.mem_bot] at hx'
      have hx'' := RingHom.mem_ker.mpr hx'
      rwa [hker, ← Polynomial.algebraMap_eq] at hx''
    exact ordFaithful_algebraMap_atPrime_of_flat Q hQeq
  · -- `Q = (G) + 𝔪 R[X]` with `G` a monic lift of the monic generator of the fibre prime
    have hmon : (normalize g).Monic := Polynomial.monic_normalize hg0
    obtain ⟨G, hGπ, -, hGmon⟩ := Polynomial.lifts_and_natDegree_eq_and_monic
      ((Polynomial.mem_lifts _).mpr (Polynomial.map_surjective _ residue_surjective (normalize g)))
      hmon
    have hQg : Q.map π = Ideal.span {normalize g} := by
      rw [hg, Ideal.span_singleton_eq_span_singleton]
      exact (normalize_associated g).symm
    have hQeq : Q = Ideal.span {G} ⊔ (maximalIdeal R).map (C : R →+* R[X]) := by
      have h1 : (Ideal.span {G} ⊔ (maximalIdeal R).map (C : R →+* R[X])).map π = Q.map π := by
        rw [Ideal.map_sup, Ideal.map_span, Set.image_singleton, ← hker, hmapker, sup_bot_eq, hQg,
          hπdef, coe_mapRingHom, hGπ]
      have h2 := congrArg (Ideal.comap π) h1
      rw [Ideal.comap_map_of_surjective _ hπ, Ideal.comap_map_of_surjective _ hπ,
        ← RingHom.ker_eq_comap_bot, sup_eq_left.mpr hkerQ, sup_assoc, hker, sup_idem] at h2
      exact h2.symm
    -- the finite free algebra `D = R[X]/(G)` and the prime `Q D = 𝔪 D`
    have : Module.Free R (AdjoinRoot G) :=
      Module.Free.of_basis (AdjoinRoot.powerBasis' hGmon).basis
    have hkerG : RingHom.ker (AdjoinRoot.mk G) ≤ Q := by
      intro x hx
      rw [RingHom.mem_ker, AdjoinRoot.mk_eq_zero, ← Ideal.mem_span_singleton] at hx
      rw [hQeq]
      exact Ideal.mem_sup_left hx
    have : (Q.map (AdjoinRoot.mk G)).IsPrime :=
      Ideal.map_isPrime_of_surjective AdjoinRoot.mk_surjective hkerG
    have hQt : Q.map (AdjoinRoot.mk G) = (maximalIdeal R).map (algebraMap R (AdjoinRoot G)) := by
      rw [hQeq, Ideal.map_sup, Ideal.map_span, Set.image_singleton, AdjoinRoot.mk_self,
        Ideal.span_singleton_zero, bot_sup_eq, Ideal.map_map, AdjoinRoot.algebraMap_eq]
      rfl
    have hQQt : Q = (Q.map (AdjoinRoot.mk G)).comap (AdjoinRoot.mk G) := by
      rw [Ideal.comap_map_of_surjective _ AdjoinRoot.mk_surjective, ← RingHom.ker_eq_comap_bot,
        sup_eq_left.mpr hkerG]
    have := Localization.isLocalHom_localRingHom Q _ (AdjoinRoot.mk G) hQQt
    refine OrdFaithful.of_comp (ψ := Localization.localRingHom Q _ (AdjoinRoot.mk G) hQQt)
      ((ordFaithful_algebraMap_atPrime_of_flat _ hQt).congr ?_)
    refine RingHom.ext fun r => ?_
    rw [RingHom.comp_apply, IsScalarTower.algebraMap_apply R R[X] (Localization.AtPrime Q),
      Localization.localRingHom_to_map, IsScalarTower.algebraMap_apply R (AdjoinRoot G)
        (Localization.AtPrime (Q.map (AdjoinRoot.mk G))), Polynomial.algebraMap_eq,
      AdjoinRoot.mk_C, AdjoinRoot.algebraMap_eq]

end OneVariableLocal

section OneVariable

variable {R : Type*} [CommRing R]

attribute [local instance] Polynomial.algebra

/-- The polynomial case in one variable over any base: for a prime `Q` of `R[X]` over the prime
`p = Q ∩ R`, the local map `R_p → R[X]_Q` reflects the powers of the maximal ideal.  `R_p[X]` is
the localization of `R[X]` at `C(R ∖ p)`, so `R[X]_Q ≅ R_p[X]_{Q'}` with `Q' = Q R_p[X]` a prime
containing `𝔪_p R_p[X]`, and the local case applies. -/
theorem ordFaithful_localRingHom_C (Q : Ideal R[X]) [Q.IsPrime] {p : Ideal R} [p.IsPrime]
    (hpQ : p = Q.comap (C : R →+* R[X])) :
    OrdFaithful (Localization.localRingHom p Q (C : R →+* R[X]) hpQ) := by
  have : IsLocalization (p.primeCompl.map (C : R →+* R[X])) (Localization.AtPrime p)[X] :=
    Polynomial.isLocalization p.primeCompl (Localization.AtPrime p)
  have hdisj : Disjoint (p.primeCompl.map (C : R →+* R[X]) : Set R[X]) (Q : Set R[X]) := by
    rw [Set.disjoint_left]
    rintro _ ⟨r, hr, rfl⟩ hrQ
    refine hr ?_
    rw [hpQ]
    exact Ideal.mem_comap.mpr hrQ
  have hQ' : (Q.map (algebraMap R[X] (Localization.AtPrime p)[X])).IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint _ (Localization.AtPrime p)[X] Q inferInstance hdisj
  have hQ'Q : (Q.map (algebraMap R[X] (Localization.AtPrime p)[X])).comap
      (algebraMap R[X] (Localization.AtPrime p)[X]) = Q :=
    IsLocalization.under_map_of_isPrime_disjoint _ (Localization.AtPrime p)[X] inferInstance hdisj
  have : IsLocalization.AtPrime
      (Localization.AtPrime (Q.map (algebraMap R[X] (Localization.AtPrime p)[X]))) Q := by
    have := IsLocalization.isLocalization_isLocalization_atPrime_isLocalization
      (p.primeCompl.map (C : R →+* R[X])) (S := (Localization.AtPrime p)[X])
      (Localization.AtPrime (Q.map (algebraMap R[X] (Localization.AtPrime p)[X])))
      (Q.map (algebraMap R[X] (Localization.AtPrime p)[X]))
    have hM : (Ideal.comap (algebraMap R[X] (Localization.AtPrime p)[X])
        (Q.map (algebraMap R[X] (Localization.AtPrime p)[X]))).primeCompl = Q.primeCompl :=
      Submonoid.ext fun x => by rw [Ideal.mem_primeCompl_iff, Ideal.mem_primeCompl_iff, hQ'Q]
    unfold IsLocalization.AtPrime at this ⊢
    rw [hM] at this
    exact this
  let e : Localization.AtPrime Q ≃ₐ[R[X]]
      Localization.AtPrime (Q.map (algebraMap R[X] (Localization.AtPrime p)[X])) :=
    IsLocalization.algEquiv Q.primeCompl _ _
  have hmQ' : (maximalIdeal (Localization.AtPrime p)).map (C : Localization.AtPrime p →+* _) ≤
      Q.map (algebraMap R[X] (Localization.AtPrime p)[X]) := by
    rw [← Localization.AtPrime.map_eq_maximalIdeal, Ideal.map_map]
    have hCC : (C : Localization.AtPrime p →+* _).comp (algebraMap R (Localization.AtPrime p)) =
        (algebraMap R[X] (Localization.AtPrime p)[X]).comp (C : R →+* R[X]) :=
      RingHom.ext fun r => (Polynomial.map_C _).symm
    rw [hCC, ← Ideal.map_map]
    exact Ideal.map_mono (Ideal.map_le_iff_le_comap.mpr hpQ.le)
  have h0 := ordFaithful_algebraMap_atPrime_polynomial _ hmQ'
  refine (h0.comp_ringEquiv (e.symm : Localization.AtPrime
    (Q.map (algebraMap R[X] (Localization.AtPrime p)[X])) ≃+* Localization.AtPrime Q)).congr ?_
  refine (Localization.localRingHom_unique p Q C hpQ fun r => ?_).symm
  have hCr : (C : Localization.AtPrime p →+* _) (algebraMap R (Localization.AtPrime p) r) =
      algebraMap R[X] (Localization.AtPrime p)[X] (C r) := (Polynomial.map_C _).symm
  rw [RingHom.comp_apply, IsScalarTower.algebraMap_apply (Localization.AtPrime p)
    (Localization.AtPrime p)[X], Polynomial.algebraMap_eq, hCr, ← IsScalarTower.algebraMap_apply]
  exact e.symm.commutes (C r)

end OneVariable

section MvPolynomial

variable {R : Type*} [CommRing R]

/-- The polynomial case in `n` variables over any base: for a prime `q` of `R[X₁, …, Xₙ]` over the
prime `p = q ∩ R`, the local map `R_p → R[X₁, …, Xₙ]_q` reflects the powers of the maximal ideal.
Induction on `n` through `R[X₁, …, Xₙ₊₁] ≅ R[X₁, …, Xₙ][X]` (`MvPolynomial.finSuccEquiv`), the
one-variable case (`ordFaithful_localRingHom_C`) and composition. -/
theorem ordFaithful_localRingHom_mvPolynomial_C (n : ℕ) (q : Ideal (MvPolynomial (Fin n) R))
    [q.IsPrime] {p : Ideal R} [p.IsPrime]
    (hpq : p = q.comap (MvPolynomial.C : R →+* MvPolynomial (Fin n) R)) :
    OrdFaithful (Localization.localRingHom p q MvPolynomial.C hpq) := by
  induction n with
  | zero =>
    exact ordFaithful_localRingHom_of_bijective _
      ⟨MvPolynomial.C_injective (Fin 0) R, MvPolynomial.C_surjective (Fin 0)⟩ q hpq
  | succ n ih =>
    let e : Polynomial (MvPolynomial (Fin n) R) ≃+* MvPolynomial (Fin (n + 1)) R :=
      (MvPolynomial.finSuccEquiv R n).symm.toRingEquiv
    have hC : (MvPolynomial.C : R →+* MvPolynomial (Fin (n + 1)) R) =
        (e : Polynomial (MvPolynomial (Fin n) R) →+* _).comp
          ((C : MvPolynomial (Fin n) R →+* _).comp MvPolynomial.C) := by
      refine RingHom.ext fun r => ?_
      rw [RingHom.comp_apply, RingHom.comp_apply,
        ← MvPolynomial.algebraMap_eq (R := R) (σ := Fin n), ← Polynomial.algebraMap_apply,
        ← MvPolynomial.algebraMap_eq (R := R) (σ := Fin (n + 1))]
      exact ((MvPolynomial.finSuccEquiv R n).symm.commutes r).symm
    have : (q.comap (e : Polynomial (MvPolynomial (Fin n) R) →+* _)).IsPrime :=
      Ideal.IsPrime.comap _
    have : ((q.comap (e : Polynomial (MvPolynomial (Fin n) R) →+* _)).comap
        (C : MvPolynomial (Fin n) R →+* _)).IsPrime := Ideal.IsPrime.comap _
    have hp₁ : p = ((q.comap (e : Polynomial (MvPolynomial (Fin n) R) →+* _)).comap
        (C : MvPolynomial (Fin n) R →+* _)).comap MvPolynomial.C := by
      rw [hpq, hC, ← Ideal.comap_comap, ← Ideal.comap_comap]
    have h₁ := ih _ hp₁
    have h₂ := ordFaithful_localRingHom_C (q.comap (e : Polynomial (MvPolynomial (Fin n) R) →+* _))
      (p := (q.comap (e : Polynomial (MvPolynomial (Fin n) R) →+* _)).comap
        (C : MvPolynomial (Fin n) R →+* _)) rfl
    have h₃ := ordFaithful_localRingHom_of_bijective
      (e : Polynomial (MvPolynomial (Fin n) R) →+* _) e.bijective q
      (p := q.comap (e : Polynomial (MvPolynomial (Fin n) R) →+* _)) rfl
    refine ((h₁.comp h₂).comp h₃).congr ?_
    refine (Localization.localRingHom_unique p q _ hpq fun r => ?_).symm
    rw [RingHom.comp_apply, RingHom.comp_apply, Localization.localRingHom_to_map,
      Localization.localRingHom_to_map, Localization.localRingHom_to_map, hC]
    rfl

/-- **The order is preserved by localizations of polynomial rings**: for a prime `q` of
`R[X₁, …, Xₙ]` over the maximal ideal of the local ring `R`, `ord (J R[X₁, …, Xₙ]_q) = ord J`.  The
local map `R → R[X₁, …, Xₙ]_q` is `R ≅ R_𝔪 → R[X₁, …, Xₙ]_q`, which reflects the powers of the
maximal ideal (`ordFaithful_localRingHom_mvPolynomial_C`). -/
theorem ord_map_eq_of_atPrime_mvPolynomial [IsLocalRing R] {n : ℕ}
    (q : Ideal (MvPolynomial (Fin n) R)) [q.IsPrime]
    (hq : q.comap (algebraMap R (MvPolynomial (Fin n) R)) = maximalIdeal R) (J : Ideal R) :
    ord (J.map (algebraMap R (Localization.AtPrime q))) = ord J := by
  rw [MvPolynomial.algebraMap_eq] at hq
  have h1 := ordFaithful_localRingHom_mvPolynomial_C n q hq.symm
  let e : R ≃ₐ[R] Localization.AtPrime (maximalIdeal R) :=
    IsLocalization.atUnits R (maximalIdeal R).primeCompl fun _ hx => notMem_maximalIdeal.mp hx
  have he : ∀ r, e r = algebraMap R (Localization.AtPrime (maximalIdeal R)) r := fun r => by
    simpa using e.commutes r
  have hEq : (Localization.localRingHom (maximalIdeal R) q MvPolynomial.C hq.symm).comp
      (e.toRingEquiv : R →+* Localization.AtPrime (maximalIdeal R)) =
      algebraMap R (Localization.AtPrime q) := by
    refine RingHom.ext fun r => ?_
    change Localization.localRingHom (maximalIdeal R) q MvPolynomial.C hq.symm (e r) = _
    rw [he, Localization.localRingHom_to_map,
      IsScalarTower.algebraMap_apply R (MvPolynomial (Fin n) R) (Localization.AtPrime q),
      MvPolynomial.algebraMap_eq]
  have : IsLocalHom (algebraMap R (Localization.AtPrime q)) := by
    rw [← hEq]
    have := Localization.isLocalHom_localRingHom (maximalIdeal R) q MvPolynomial.C hq.symm
    exact RingHom.isLocalHom_comp _ _
  exact ord_map_eq_of_ordFaithful ((h1.ringEquiv_comp e.toRingEquiv).congr hEq) J

end MvPolynomial

end IsLocalRing
