/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.Derivation.Basic
public import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Ideal.Operations

/-!
# The Euler operator along a subset of coordinates and the Taylor criterion

The order of a function `f` along a closed subspace `C` at a point is the largest `p` with
`f ∈ I_C^p` [BM97, Chapter I, §3]; in coordinates adapted to a submanifold it is read off the
Taylor expansion of `f` in the coordinates defining the submanifold.  This file proves the
algebra behind that reading.  In a commutative algebra `R` over a field `k` of characteristic
zero with elements `x_i` and derivations `∂_i` (`pd i`) satisfying `∂_i x_j = δ_ij` on a finite
index set `S`, let `J_S = (x_i : i ∈ S)`.  The Euler operator `E_S f = ∑_{i ∈ S} x_i ∂_i f`
satisfies `E_S f − a f ∈ J_S^{a+1}` for `f ∈ J_S^a` (`eulerS_sub_nsmul_mem`: the Euler identity
behind the characteristic-zero clause (3) of [Kol07, Lemma 74], with the maximal ideal replaced
by `J_S`), hence `f ∈ J_S^a` and `∂_i f ∈ J_S^a` for all `i ∈ S` force `f ∈ J_S^{a+1}`
(`mem_pow_succ_of_forall_pderiv_mem`; `a` is invertible in characteristic zero).  By induction
this gives the Taylor criterion along `S`: `f ∈ J_S^p` iff every iterated derivative of `f` along
fewer than `p` coordinates of `S` lies in `J_S` (`mem_coordIdeal_pow_iff`; the easy direction is
that a derivation lowers the power of an ideal by one, `derivation_apply_mem_pow_of_mem_pow_succ`).
On the stalk of an analytic manifold with the coordinate derivations of a chart adapted to a
submanifold `Y`, and `S` the indices of the coordinates defining `Y`, `J_S` is the ideal of `Y`
and "`∂_S^l f ∈ J_S`" reads "`∂_S^l f` vanishes on `Y`" — the coefficient functions of the
expansion `f = ∑_α f_α(w) z^α` in `Hironaka/Manifold/BlowUp/Transform/OrderAlong.lean`, where
this criterion computes the order of an ideal sheaf along the centre of a blow-up.
-/

@[expose] public section

namespace IsLocalRing

variable {k : Type*} [Field k] {R : Type*} [CommRing R] [Algebra k R] {ι : Type*}
  (x : ι → R) (pd : ι → Derivation k R R) (S : Finset ι)

/-- The ideal `J_S` generated by the coordinates indexed by `S` (on a stalk, with `S` the indices
of the coordinates defining a submanifold `Y` in an adapted chart, the ideal of `Y`). -/
def coordIdeal : Ideal R := Ideal.span (x '' S)

/-- The coordinates indexed by `S` lie in `J_S`. -/
theorem x_mem_coordIdeal {i : ι} (hi : i ∈ S) : x i ∈ coordIdeal x S :=
  Ideal.subset_span ⟨i, hi, rfl⟩

/-- A derivation lowers the power of an ideal by one. -/
theorem derivation_apply_mem_pow_of_mem_pow_succ (D : Derivation k R R) (J : Ideal R) (m : ℕ) :
    ∀ {f : R}, f ∈ J ^ (m + 1) → D f ∈ J ^ m := by
  induction m with
  | zero => intro f _; simp
  | succ m ih =>
    intro f hf
    rw [pow_succ] at hf
    refine Submodule.mul_induction_on hf (fun g hg h hh => ?_) (fun a b ha hb => ?_)
    · rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul]
      refine Ideal.add_mem _ (Ideal.mul_mem_right _ _ hg) ?_
      rw [pow_succ']
      exact Ideal.mul_mem_mul hh (ih hg)
    · rw [map_add]
      exact Ideal.add_mem _ ha hb

/-- Iterated derivatives along a list of indices,
`iterD [i₁, …, iₖ] f = ∂_{i₁} (∂_{i₂} (… (∂_{iₖ} f)))`. -/
def iterD (l : List ι) (f : R) : R := l.foldr (fun i g => pd i g) f

/-- The empty iterated derivative is the identity. -/
theorem iterD_nil (f : R) : iterD pd [] f = f := rfl

/-- One more derivative in front. -/
theorem iterD_cons (i : ι) (l : List ι) (f : R) : iterD pd (i :: l) f = pd i (iterD pd l f) := rfl

/-- One more derivative at the back. -/
theorem iterD_append_singleton (l : List ι) (i : ι) (f : R) :
    iterD pd (l ++ [i]) f = iterD pd l (pd i f) := by
  unfold iterD
  rw [List.foldr_append]
  rfl

/-- Iterated derivatives lower the power of an ideal by the length. -/
theorem iterD_mem_pow (J : Ideal R) (l : List ι) :
    ∀ {p : ℕ} {f : R}, f ∈ J ^ (p + l.length) → iterD pd l f ∈ J ^ p := by
  induction l with
  | nil => intro p f hf; rw [iterD_nil]; simpa using hf
  | cons i l ih =>
    intro p f hf
    rw [iterD_cons]
    refine derivation_apply_mem_pow_of_mem_pow_succ (pd i) J p (ih ?_)
    rw [List.length_cons, ← add_assoc, add_right_comm] at hf
    exact hf

/-- The Euler operator along `S`, `E_S f = ∑_{i ∈ S} x_i ∂_i f`. -/
def eulerS (f : R) : R := ∑ i ∈ S, x i * pd i f

/-- The Euler operator is additive. -/
theorem eulerS_add (f g : R) : eulerS x pd S (f + g) = eulerS x pd S f + eulerS x pd S g := by
  simp only [eulerS, map_add, mul_add, Finset.sum_add_distrib]

/-- The Leibniz rule for the Euler operator. -/
theorem eulerS_mul (f g : R) :
    eulerS x pd S (f * g) = f * eulerS x pd S g + g * eulerS x pd S f := by
  simp only [eulerS, Derivation.leibniz, smul_eq_mul, mul_add, Finset.sum_add_distrib,
    Finset.mul_sum]
  congr 1 <;> exact Finset.sum_congr rfl fun i _ => by ring

/-- `E_S f ∈ J_S` for every `f`. -/
theorem eulerS_mem (f : R) : eulerS x pd S f ∈ coordIdeal x S :=
  Submodule.sum_mem _ fun _ hi => Ideal.mul_mem_right _ _ (x_mem_coordIdeal x S hi)

variable [DecidableEq ι] (hx : ∀ i ∈ S, ∀ j ∈ S, pd i (x j) = if i = j then 1 else 0)
include hx

/-- `E_S x_j = x_j` for `j ∈ S` (the Euler identity on the coordinates). -/
theorem eulerS_x {j : ι} (hj : j ∈ S) : eulerS x pd S (x j) = x j := by
  unfold eulerS
  rw [Finset.sum_eq_single j (fun i hi hij => by rw [hx i hi j hj, if_neg hij, mul_zero])
    (fun h => (h hj).elim), hx j hj j hj, if_pos rfl, mul_one]

/-- `E_S h − h ∈ J_S²` for `h ∈ J_S`. -/
theorem eulerS_sub_self_mem_sq {h : R} (hh : h ∈ coordIdeal x S) :
    eulerS x pd S h - h ∈ coordIdeal x S ^ 2 := by
  refine Submodule.span_induction (p := fun h _ => eulerS x pd S h - h ∈ coordIdeal x S ^ 2)
    ?_ ?_ ?_ ?_ hh
  · rintro _ ⟨j, hj, rfl⟩
    rw [eulerS_x x pd S hx hj, sub_self]
    exact zero_mem _
  · simp [eulerS]
  · intro a b _ _ ha hb
    have : eulerS x pd S (a + b) - (a + b) = (eulerS x pd S a - a) + (eulerS x pd S b - b) := by
      rw [eulerS_add]; ring
    rw [this]
    exact Ideal.add_mem _ ha hb
  · intro c a ha' ha
    rw [smul_eq_mul, eulerS_mul]
    have : c * eulerS x pd S a + a * eulerS x pd S c - c * a =
        c * (eulerS x pd S a - a) + a * eulerS x pd S c := by ring
    rw [this, pow_two]
    refine Ideal.add_mem _ (Ideal.mul_mem_left _ _ (by rwa [← pow_two])) ?_
    exact Ideal.mul_mem_mul ha' (eulerS_mem x pd S c)

/-- The Euler identity along `S`: `E_S f − a f ∈ J_S^{a+1}` for `f ∈ J_S^a`, `a ≥ 1`. -/
theorem eulerS_sub_nsmul_mem {a : ℕ} (ha : 1 ≤ a) {f : R} (hf : f ∈ coordIdeal x S ^ a) :
    eulerS x pd S f - (a : R) * f ∈ coordIdeal x S ^ (a + 1) := by
  induction a, ha using Nat.le_induction generalizing f with
  | base =>
    rw [pow_one] at hf
    simpa using eulerS_sub_self_mem_sq x pd S hx hf
  | succ a _ ih =>
    rw [pow_succ] at hf
    refine Submodule.mul_induction_on hf (fun g hg h hh => ?_) (fun u v hu hv => ?_)
    · rw [eulerS_mul]
      have : g * eulerS x pd S h + h * eulerS x pd S g - ((a + 1 : ℕ) : R) * (g * h) =
          g * (eulerS x pd S h - h) + h * (eulerS x pd S g - (a : R) * g) := by
        push_cast
        ring
      rw [this]
      refine Ideal.add_mem _ ?_ ?_
      · rw [show a + 1 + 1 = a + 2 by ring, pow_add]
        exact Ideal.mul_mem_mul hg (eulerS_sub_self_mem_sq x pd S hx hh)
      · rw [pow_succ']
        exact Ideal.mul_mem_mul hh (ih hg)
    · rw [eulerS_add]
      convert Ideal.add_mem _ hu hv using 1
      ring

variable [CharZero k]

/-- If `f ∈ J_S^a` and all `∂_i f`, `i ∈ S`, lie in `J_S^a`, then `f ∈ J_S^{a+1}` (`a ≥ 1`). -/
theorem mem_pow_succ_of_forall_pderiv_mem {a : ℕ} (ha : 1 ≤ a) {f : R}
    (hf : f ∈ coordIdeal x S ^ a) (hd : ∀ i ∈ S, pd i f ∈ coordIdeal x S ^ a) :
    f ∈ coordIdeal x S ^ (a + 1) := by
  have hE : eulerS x pd S f ∈ coordIdeal x S ^ (a + 1) := by
    unfold eulerS
    rw [pow_succ']
    exact Submodule.sum_mem _ fun i hi => Ideal.mul_mem_mul (x_mem_coordIdeal x S hi) (hd i hi)
  have h1 : (a : R) * f ∈ coordIdeal x S ^ (a + 1) := by
    have := Ideal.sub_mem _ hE (eulerS_sub_nsmul_mem x pd S hx ha hf)
    simpa using this
  have hu : IsUnit ((a : R)) := by
    have : (a : R) = algebraMap k R (a : k) := by simp
    rw [this]
    exact (isUnit_iff_ne_zero.mpr (Nat.cast_ne_zero.mpr (by omega))).map (algebraMap k R)
  obtain ⟨u, hu⟩ := hu
  have : f = ↑u⁻¹ * ((a : R) * f) := by rw [← hu, ← mul_assoc, Units.inv_mul, one_mul]
  rw [this]
  exact Ideal.mul_mem_left _ _ h1

/-- The Taylor criterion along `S`: `f ∈ J_S^p` iff every iterated derivative of `f` along fewer
than `p` coordinates of `S` lies in `J_S` (the algebraic form of the order along a closed
subspace, [BM97, Chapter I, §3]). -/
theorem mem_coordIdeal_pow_iff (p : ℕ) (f : R) :
    f ∈ coordIdeal x S ^ p ↔
      ∀ l : List ι, (∀ i ∈ l, i ∈ S) → l.length < p → iterD pd l f ∈ coordIdeal x S := by
  constructor
  · intro hf l _ hl
    have : f ∈ coordIdeal x S ^ (1 + l.length) := Ideal.pow_le_pow_right (by omega) hf
    simpa using iterD_mem_pow pd (coordIdeal x S) l this
  · induction p generalizing f with
    | zero => intro _; simp
    | succ p ih =>
      intro hl
      rcases Nat.eq_zero_or_pos p with hp | hp
      · subst hp
        have := hl [] (by simp) (by simp)
        rw [iterD_nil] at this
        simpa using this
      · have hf : f ∈ coordIdeal x S ^ p :=
          ih f fun l hlS hlen => hl l hlS (Nat.lt_succ_of_lt hlen)
        refine mem_pow_succ_of_forall_pderiv_mem x pd S hx hp hf fun i hi => ?_
        refine ih (pd i f) fun l hlS hlen => ?_
        rw [← iterD_append_singleton]
        refine hl (l ++ [i]) ?_ ?_
        · intro j hj
          rcases List.mem_append.mp hj with hj | hj
          · exact hlS j hj
          · rw [List.mem_singleton.mp hj]; exact hi
        · rw [List.length_append, List.length_singleton]; omega

end IsLocalRing
