/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.Coords
public import Mathlib.RingTheory.MvPowerSeries.Derivative
public import Hironaka.Algebra.Local.Order
public import Mathlib.Algebra.Algebra.Rat

/-!
# The power series ring as a coordinate structure

Kollár works in `R = K⟦x₁, …, xₙ⟧`, a field `K` of characteristic zero, with its maximal ideal
`𝔪` [Kol07, Notation 93]; the formal automorphisms of the form `1 + B` live there, and the
Cohen structure theorem identifies the completion of every regular local `ℚ`-algebra with
coordinates with such a ring.  This file makes `MvPowerSeries (Fin n) K` an instance of the
coordinate structure `IsLocalRing.RegularCoords`:

* `MvPowerSeries.pderiv_pderiv_comm`: the formal partial derivatives commute.
  Mathlib has no such lemma; it follows coefficientwise from
  `MvPowerSeries.coeff_pderiv`, because both iterated derivatives have `n`-th coefficient
  `(nᵢ + 1)(nⱼ + 1)` (or `(nᵢ + 1)(nᵢ + 2)` when `i = j`) times the coefficient at
  `n + eᵢ + eⱼ`.
* `MvPowerSeries.exists_eq_sum_X_mul`, `mem_span_range_X_of_constantCoeff_eq_zero`,
  `mem_span_range_X_pow_iff_le_order`, `maximalIdeal_eq_span_range_X`: for finitely many
  variables the maximal ideal of `K⟦X⟧` is generated by the variables, and `f ∈ (X)^k` iff
  every monomial of `f` has degree at least
  `k`, i.e. `k ≤ order f`.  The decomposition `f = ∑ᵢ Xᵢ gᵢ` is built one variable at a time:
  the monomials of `f` containing `Xₐ` form `Xₐ · gₐ`, and the rest is handled by induction on
  the set of variables.
* `MvPowerSeries.ordElem_eq_order`: hence the order of an element in the sense of
  `Hironaka/Algebra/Local/Order.lean` is Mathlib's `MvPowerSeries.order`.
* `IsLocalRing.RegularCoords.mvPowerSeries`: the structure with `x = X` and
  `∂ᵢ = pderiv K i` (restricted to a `ℚ`-derivation).  Two of its fields are taken as explicit
  hypotheses: that the maximal ideal is generated by the `Xᵢ` (`maximalIdeal_eq_span_range_X`
  below) and that the Krull dimension is `n` (proved together with the regularity of `K⟦X⟧`,
  an instance argument, in `Hironaka/Algebra/Local/PowerSeriesRegular.lean`).
-/

@[expose] public section

namespace MvPowerSeries

variable {σ : Type*} {R : Type*} [CommSemiring R]

/-- The formal partial derivatives of a multivariate power series commute. -/
theorem pderiv_pderiv_comm (i j : σ) (f : MvPowerSeries σ R) :
    pderiv R i (pderiv R j f) = pderiv R j (pderiv R i f) := by
  classical
  ext n
  simp only [coeff_pderiv, Finsupp.add_apply, Finsupp.single_apply]
  rw [add_right_comm n (Finsupp.single j 1) (Finsupp.single i 1)]
  by_cases h : i = j
  · subst h; ring
  · simp only [h, Ne.symm h, if_false, add_zero]; ring

end MvPowerSeries

namespace MvPowerSeries

section Span

variable {σ : Type*} {R : Type*} [CommSemiring R]

/-- Every power series whose monomials all involve a variable from the finite set `s` is a
combination `∑ᵢ Xᵢ gᵢ` over `s`, and the monomials of `gᵢ` are those of `f` shifted by `Xᵢ`
(the finite-`σ` decomposition behind `𝔪 = (X)`). -/
theorem exists_eq_sum_X_mul (s : Finset σ) (f : MvPowerSeries σ R)
    (hf : ∀ m : σ →₀ ℕ, (∀ i ∈ s, m i = 0) → coeff m f = 0) :
    ∃ g : σ → MvPowerSeries σ R, f = ∑ i ∈ s, X i * g i ∧
      ∀ i ∈ s, ∀ d, coeff d (g i) ≠ 0 → coeff (d + Finsupp.single i 1) f ≠ 0 := by
  classical
  induction s using Finset.induction_on generalizing f with
  | empty =>
    refine ⟨0, ?_, by simp⟩
    ext m
    simpa using hf m (by simp)
  | insert a t hat ih =>
    set ga : MvPowerSeries σ R := fun d => coeff (d + Finsupp.single a 1) f with hga
    have hXga : ∀ m, coeff m (X a * ga) = if 1 ≤ m a then coeff m f else 0 := by
      intro m
      rw [X_def, coeff_monomial_mul]
      by_cases h : 1 ≤ m a
      · rw [if_pos (Finsupp.single_le_iff.mpr h), if_pos h, one_mul]
        change coeff (m - Finsupp.single a 1 + Finsupp.single a 1) f = coeff m f
        rw [tsub_add_cancel_of_le (Finsupp.single_le_iff.mpr h)]
      · rw [if_neg (fun h' => h (Finsupp.single_le_iff.mp h')), if_neg h]
    set φ₁ : MvPowerSeries σ R := fun m => if m a = 0 then coeff m f else 0 with hφ₁
    have hφ₁c : ∀ m, coeff m φ₁ = if m a = 0 then coeff m f else 0 := fun m => rfl
    have hsplit : f = φ₁ + X a * ga := by
      ext m
      rw [map_add, hXga, hφ₁c]
      by_cases h : m a = 0
      · simp [h]
      · simp [h, Nat.one_le_iff_ne_zero.mpr h]
    have hφ₁' : ∀ m : σ →₀ ℕ, (∀ i ∈ t, m i = 0) → coeff m φ₁ = 0 := by
      intro m hm
      rw [hφ₁c]
      by_cases h : m a = 0
      · rw [if_pos h]
        exact hf m fun i hi => by
          rcases Finset.mem_insert.mp hi with rfl | hi
          · exact h
          · exact hm i hi
      · exact if_neg h
    obtain ⟨g', hg', hsupp⟩ := ih φ₁ hφ₁'
    refine ⟨Function.update g' a ga, ?_, ?_⟩
    · rw [Finset.sum_insert hat, Function.update_self, hsplit, hg', add_comm]
      congr 1
      exact Finset.sum_congr rfl fun i hi => by
        rw [Function.update_of_ne (ne_of_mem_of_not_mem hi hat)]
    · intro i hi d hd
      rcases Finset.mem_insert.mp hi with rfl | hi
      · rwa [Function.update_self] at hd
      · rw [Function.update_of_ne (ne_of_mem_of_not_mem hi hat)] at hd
        intro h0
        apply hsupp i hi d hd
        rw [hφ₁c]
        split_ifs <;> simp [h0]

/-- A power series with zero constant coefficient in finitely many variables lies in the ideal
generated by the variables. -/
theorem mem_span_range_X_of_constantCoeff_eq_zero [Finite σ] {f : MvPowerSeries σ R}
    (hf : constantCoeff f = 0) : f ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) := by
  classical
  cases nonempty_fintype σ
  obtain ⟨g, hg, -⟩ := exists_eq_sum_X_mul Finset.univ f fun m hm => by
    have : m = 0 := Finsupp.ext fun i => hm i (Finset.mem_univ i)
    rw [this, coeff_zero_eq_constantCoeff_apply, hf]
  rw [hg]
  exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, rfl⟩)

/-- The powers of the ideal of variables, in finitely many variables: `f ∈ (X)^k` iff every
monomial of `f` has degree at least `k`, i.e. `k ≤ order f`. -/
theorem mem_span_range_X_pow_iff_le_order [Finite σ] (k : ℕ) (f : MvPowerSeries σ R) :
    f ∈ Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) ^ k ↔ (k : ℕ∞) ≤ f.order := by
  classical
  induction k generalizing f with
  | zero => simp
  | succ k ih =>
    constructor
    · intro hf
      rw [pow_succ] at hf
      refine Submodule.mul_induction_on hf (fun r hr s hs => ?_) (fun x y hx hy => ?_)
      · have h1 : (1 : ℕ∞) ≤ s.order := by
          rw [one_le_order_iff_constCoeff_eq_zero]
          have : Ideal.span (Set.range (X : σ → MvPowerSeries σ R)) ≤
              RingHom.ker (constantCoeff (σ := σ) (R := R)) :=
            Ideal.span_le.mpr (by rintro _ ⟨i, rfl⟩; simp [RingHom.mem_ker])
          exact this hs
        calc ((k + 1 : ℕ) : ℕ∞) = (k : ℕ∞) + 1 := by push_cast; rfl
          _ ≤ r.order + s.order := add_le_add ((ih r).mp hr) h1
          _ ≤ (r * s).order := le_order_mul
      · exact le_trans (le_min hx hy) min_order_le_add
    · intro hf
      have hc : constantCoeff f = 0 := by
        rw [← one_le_order_iff_constCoeff_eq_zero]
        exact le_trans (by exact_mod_cast Nat.one_le_iff_ne_zero.mpr (Nat.succ_ne_zero k)) hf
      cases nonempty_fintype σ
      obtain ⟨g, hg, hsupp⟩ := exists_eq_sum_X_mul Finset.univ f fun m hm => by
        have : m = 0 := Finsupp.ext fun i => hm i (Finset.mem_univ i)
        rw [this, coeff_zero_eq_constantCoeff_apply, hc]
      have hgi : ∀ i, (k : ℕ∞) ≤ (g i).order := by
        intro i
        apply le_order
        intro d hd
        by_contra hne
        have h1 := order_le (hsupp i (Finset.mem_univ i) d hne)
        rw [map_add, Finsupp.degree_single] at h1
        have h2 : (f.order : ℕ∞) ≤ (d.degree : ℕ∞) + 1 := by exact_mod_cast h1
        have h3 : ((k + 1 : ℕ) : ℕ∞) ≤ (d.degree : ℕ∞) + 1 := hf.trans h2
        have h4 : (d.degree : ℕ∞) < (k : ℕ∞) := hd
        have h5 : (k : ℕ∞) + 1 ≤ (d.degree : ℕ∞) + 1 := by push_cast at h3; exact h3
        exact absurd (ENat.add_le_add_iff_right ENat.one_ne_top |>.mp h5) (not_le.mpr h4)
      rw [hg, pow_succ']
      exact Ideal.sum_mem _ fun i _ =>
        Ideal.mul_mem_mul (Ideal.subset_span ⟨i, rfl⟩) ((ih (g i)).mpr (hgi i))

end Span

/-- The maximal ideal of `K⟦Xₛ : s ∈ σ⟧`, `σ` finite, is generated by the variables (the `𝔪` of
[Kol07, Notation 93]). -/
theorem maximalIdeal_eq_span_range_X (σ : Type*) [Finite σ] (K : Type*) [Field K] :
    IsLocalRing.maximalIdeal (MvPowerSeries σ K) =
      Ideal.span (Set.range (X : σ → MvPowerSeries σ K)) := by
  refine le_antisymm (fun f hf => ?_) (Ideal.span_le.mpr ?_)
  · apply mem_span_range_X_of_constantCoeff_eq_zero
    by_contra h
    exact (IsLocalRing.mem_maximalIdeal f).mp hf
      (isUnit_iff_constantCoeff.mpr (isUnit_iff_ne_zero.mpr h))
  · rintro _ ⟨i, rfl⟩
    rw [SetLike.mem_coe, IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, isUnit_iff_constantCoeff,
      constantCoeff_X]
    exact not_isUnit_zero

/-- In `K⟦Xₛ : s ∈ σ⟧`, `σ` finite, the order of an element as defined here is Mathlib's
`MvPowerSeries.order` (via `𝔪 = (X)` and `mem_span_range_X_pow_iff_le_order`). -/
theorem ordElem_eq_order {σ : Type*} [Finite σ] {K : Type*} [Field K] (f : MvPowerSeries σ K) :
    IsLocalRing.ordElem f = f.order := by
  refine le_antisymm ?_ ?_ <;> rw [← ENat.forall_natCast_le_iff_le] <;> intro r hr
  · rwa [← IsLocalRing.mem_maximalIdeal_pow_iff_le_ordElem, maximalIdeal_eq_span_range_X,
      mem_span_range_X_pow_iff_le_order] at hr
  · rwa [← IsLocalRing.mem_maximalIdeal_pow_iff_le_ordElem, maximalIdeal_eq_span_range_X,
      mem_span_range_X_pow_iff_le_order]

end MvPowerSeries

namespace IsLocalRing.RegularCoords

open MvPowerSeries IsLocalRing

variable (K : Type*) [Field K] [CharZero K] (n : ℕ)

/-- The coordinate structure on `K⟦X₁, …, Xₙ⟧` of [Kol07, Notation 93], with `x = X` and
`∂ᵢ = pderiv K i`.  The hypotheses `hspan` and `hcard` (the maximal ideal is generated by the
variables; the Krull dimension is `n`) and the regularity instance are supplied by
`MvPowerSeries.maximalIdeal_eq_span_range_X` and `Hironaka/Algebra/Local/PowerSeriesRegular.lean`.
-/
noncomputable def mvPowerSeries [IsRegularLocalRing (MvPowerSeries (Fin n) K)]
    (hspan : maximalIdeal (MvPowerSeries (Fin n) K) = Ideal.span (Set.range (X (R := K))))
    (hcard : (n : WithBot ℕ∞) = ringKrullDim (MvPowerSeries (Fin n) K)) :
    RegularCoords (MvPowerSeries (Fin n) K) n where
  x := X
  pderiv i := (MvPowerSeries.pderiv K i).restrictScalars ℚ
  span_x := hspan
  card := hcard
  pderiv_x i j := by
    rw [Derivation.restrictScalars_apply]
    split_ifs with h
    · subst h; exact pderiv_X_self
    · exact pderiv_X_of_ne (Ne.symm h)
  pderiv_comm i j f := pderiv_pderiv_comm i j f

end IsLocalRing.RegularCoords
