/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.Ideal.MinimalPrime.Basic

/-!
# Products of pairwise non-associated primes: divisibility, minimal primes, radicality

Pure commutative algebra behind the ideal sheaf of a simple normal crossings divisor, on the
analytic side (`Hironaka/Manifold/Snc/NormalCrossings.lean`, `Snc/Dictionary.lean`,
`Snc/Bundled.lean`) and on the algebraic side
(`Hironaka/Resolution/Algebraic/Snc/DictionaryBoundary.lean`,
`Hironaka/Resolution/Algebraic/Kol07/UnionIdealInvertible.lean`): a germ vanishing on each of
finitely many coordinate hyperplanes through a point is divisible by each coordinate, and the
coordinates are pairwise non-associated prime elements of the regular local ring `𝒪_{M,a}`, so the
germ is divisible by their product (`prod_dvd_of_prime_of_not_dvd`); the minimal primes of the
principal ideal of the product are exactly the principal ideals of the factors
(`minimalPrimes_span_prod`, `mem_minimalPrimes_span_prod`); the ideal is radical
(`isRadical_span_prod`); a product of two ideals of a commutative ring is the unit ideal iff both
are (`Ideal.mul_ne_top_iff`).

This is the algebra of Hironaka's definition of normal crossings — "the ideal of each irreducible
component of `E` is generated by one of the `z_i`" [Hir64, Definition 2] — iterated over the
components; the statements themselves are standard and not in the sources.
-/

public section

/-- A product of two ideals of a commutative ring is the unit ideal iff both are. -/
theorem Ideal.mul_ne_top_iff {R : Type*} [CommRing R] (I J : Ideal R) :
    I * J ≠ ⊤ ↔ I ≠ ⊤ ∨ J ≠ ⊤ := by
  constructor
  · intro h
    by_contra hc
    rw [not_or, not_not, not_not] at hc
    exact h (by rw [hc.1, hc.2, Ideal.top_mul])
  · rintro (hI | hJ) heq
    · have h1 : I * J ≤ I := Ideal.mul_le_left
      rw [heq] at h1
      exact hI (top_le_iff.mp h1)
    · have h1 : I * J ≤ J := Ideal.mul_le_right
      rw [heq] at h1
      exact hJ (top_le_iff.mp h1)

namespace IsLocalRing

variable {R : Type*} [CommRing R] {ι : Type*}

/-- In a commutative ring, if finitely many prime elements, none dividing another, each divide `z`,
then their product divides `z` (the iteration of "each `z_i`" in [Hir64, Definition 2]). -/
theorem prod_dvd_of_prime_of_not_dvd (s : Finset ι) (f : ι → R) (hp : ∀ i ∈ s, Prime (f i))
    (hnd : ∀ i ∈ s, ∀ j ∈ s, i ≠ j → ¬ f i ∣ f j) {z : R} (hz : ∀ i ∈ s, f i ∣ z) :
    ∏ i ∈ s, f i ∣ z := by
  classical
  induction s using Finset.induction_on generalizing z with
  | empty => simp
  | insert a s has ih =>
    rw [Finset.prod_insert has]
    obtain ⟨t, rfl⟩ := hz a (Finset.mem_insert_self a s)
    have ht : ∀ j ∈ s, f j ∣ t := by
      intro j hj
      have hja : j ≠ a := fun h => has (h ▸ hj)
      have hdvd : f j ∣ f a * t := hz j (Finset.mem_insert_of_mem hj)
      rcases (hp j (Finset.mem_insert_of_mem hj)).dvd_or_dvd hdvd with h | h
      · exact absurd h (hnd j (Finset.mem_insert_of_mem hj) a (Finset.mem_insert_self a s) hja)
      · exact h
    exact mul_dvd_mul_left (f a) (ih (fun i hi => hp i (Finset.mem_insert_of_mem hi))
      (fun i hi j hj hij => hnd i (Finset.mem_insert_of_mem hi) j (Finset.mem_insert_of_mem hj) hij)
      ht)

/-- A minimal prime over the principal ideal generated by a product of prime elements is generated
by one of the factors. -/
theorem minimalPrimes_span_prod {s : Finset ι} {p : ι → R} (hp : ∀ i ∈ s, Prime (p i))
    {P : Ideal R} (hP : P ∈ (Ideal.span {∏ i ∈ s, p i}).minimalPrimes) :
    ∃ i ∈ s, P = Ideal.span {p i} := by
  have hPp : P.IsPrime := hP.1.1
  have hmem : ∏ i ∈ s, p i ∈ P := hP.1.2 (Ideal.mem_span_singleton_self _)
  obtain ⟨i, hi, hpi⟩ := Ideal.IsPrime.prod_mem_iff.mp hmem
  refine ⟨i, hi, ?_⟩
  have hprime : (Ideal.span {p i}).IsPrime :=
    (Ideal.span_singleton_prime (hp i hi).ne_zero).mpr (hp i hi)
  have hle : Ideal.span {∏ i ∈ s, p i} ≤ Ideal.span {p i} :=
    Ideal.span_singleton_le_span_singleton.mpr (Finset.dvd_prod_of_mem p hi)
  have hP' : Minimal (fun q : Ideal R => q.IsPrime ∧ Ideal.span {∏ i ∈ s, p i} ≤ q) P := hP
  exact hP'.eq_of_ge ⟨hprime, hle⟩ ((Ideal.span_singleton_le_iff_mem P).mpr hpi)

/-- Each factor of a product of pairwise non-associated prime elements generates a minimal prime of
the principal ideal of the product. -/
theorem mem_minimalPrimes_span_prod {s : Finset ι} {p : ι → R} (hp : ∀ i ∈ s, Prime (p i))
    (hnd : ∀ i ∈ s, ∀ j ∈ s, i ≠ j → ¬ p i ∣ p j) {j : ι} (hj : j ∈ s) :
    Ideal.span {p j} ∈ (Ideal.span {∏ i ∈ s, p i}).minimalPrimes := by
  change Minimal (fun q : Ideal R => q.IsPrime ∧ Ideal.span {∏ i ∈ s, p i} ≤ q) (Ideal.span {p j})
  refine ⟨⟨(Ideal.span_singleton_prime (hp j hj).ne_zero).mpr (hp j hj),
    Ideal.span_singleton_le_span_singleton.mpr (Finset.dvd_prod_of_mem p hj)⟩, ?_⟩
  rintro P ⟨hP, hle⟩ hPj
  have hmem : ∏ i ∈ s, p i ∈ P := hle (Ideal.mem_span_singleton_self _)
  obtain ⟨k, hk, hpk⟩ := Ideal.IsPrime.prod_mem_iff.mp hmem
  have hkj : Ideal.span {p k} ≤ Ideal.span {p j} :=
    ((Ideal.span_singleton_le_iff_mem P).mpr hpk).trans hPj
  by_cases hjk : j = k
  · subst hjk
    exact (Ideal.span_singleton_le_iff_mem P).mpr hpk
  · exact absurd (Ideal.span_singleton_le_span_singleton.mp hkj) (hnd j hj k hk hjk)

/-- The principal ideal generated by a product of pairwise non-associated prime elements is
radical. -/
theorem isRadical_span_prod {s : Finset ι} {p : ι → R} (hp : ∀ i ∈ s, Prime (p i))
    (hnd : ∀ i ∈ s, ∀ j ∈ s, i ≠ j → ¬ p i ∣ p j) :
    (Ideal.span {∏ i ∈ s, p i}).IsRadical := by
  intro r hr
  obtain ⟨m, hm⟩ := Ideal.mem_radical_iff.mp hr
  rw [Ideal.mem_span_singleton] at hm ⊢
  exact prod_dvd_of_prime_of_not_dvd s p hp hnd fun i hi =>
    (hp i hi).dvd_of_dvd_pow ((Finset.dvd_prod_of_mem p hi).trans hm)

end IsLocalRing
