/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.RegularLocalRing.Defs
import Hironaka.Algebra.Local.Regular
import Hironaka.Algebra.Local.RegularSystem
import Mathlib.RingTheory.KrullDimension.Regular

/-!
# Regular quotients of a regular local ring

If `R` is a regular local ring and `R/I` is regular local, then `I` is generated by an initial
segment `x_1, …, x_c` of a regular system of parameters `x_1, …, x_n` of `R`, and then
`c = dim R - dim R/I` [Sta, Tag 00NR].  This is Kollár's silent "choose local coordinates such
that `Z = (x₁ = ⋯ = x_r = 0)`" for a smooth subvariety `Z` [Kol07, Definition 60], and the
algebra behind the Jacobian criterion: the kernel of the map from a polynomial ring to the
local ring of a smooth point is generated by part of a regular system of parameters
(`Hironaka/Algebra/RegularSmooth/RegularImpliesSmooth.lean`).

The proof follows [Sta, Tag 00NR].  *The classes of `I`.*  Let `t ⊆ 𝔪/𝔪²` be the set of classes
of the elements of `I`; a maximal linearly independent subset `b ⊆ t` spans the same subspace and
has `c := |b|` elements (`exists_linearIndependent`).  *Counting.*  Lifting a minimal generating
system `ȳ_1, …, ȳ_d` of `𝔪̄ = 𝔪/I` to `y_i ∈ 𝔪` (`d = dim R/I` by regularity of `R/I`) gives
`𝔪 = (y_1, …, y_d) + I`, so by Nakayama (`Hironaka/Algebra/Local/RegularSystem.lean`) the classes of
the `y_i` together with `t` span `𝔪/𝔪²`, whence `n := dim 𝔪/𝔪² ≤ d + c`.  *The parameters.*
Extending `b` to a basis of `𝔪/𝔪²` (`Basis.sumExtend`) and lifting, with the `c` elements of `I`
first, produces `x_1, …, x_n` whose classes form a basis of `𝔪/𝔪²`, hence a regular system of
parameters, with `J := (x_1, …, x_c) ⊆ I`.  *Equality.*  `R/J` is regular local of dimension
`n - c ≤ d`, and `R/J → R/I` is surjective, so `d ≤ dim R/J`; hence `dim R/J = dim R/I`.  A
regular local ring is a domain (`Hironaka/Algebra/Local/Regular.lean`), and a nonzero element `z` of
a Noetherian local domain drops the dimension by exactly one (Mathlib's
`ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors`), so a proper
ideal of `R/J` with a quotient of the full dimension is zero: `I/J = 0`, i.e. `I = J`.
-/

public section

universe u

open IsLocalRing Ideal

open IsLocalRing

variable {R : Type u} [CommRing R]

/-- In a Noetherian local domain, a proper ideal whose quotient has the full Krull dimension is
zero, since a nonzero element of the maximal ideal is a nonzerodivisor and drops the dimension by
one (the last step of [Sta, Tag 00NR], "`R/J → R/I` is an isomorphism"; also used for the
dimension theory of analytic germs, `Hironaka/AnalyticSpace/ConvDimension.lean`). -/
theorem Ideal.eq_bot_of_ringKrullDim_quotient_eq [IsLocalRing R] [IsNoetherianRing R] [IsDomain R]
    {J : Ideal R} (hJ : J ≤ maximalIdeal R) (hdim : ringKrullDim (R ⧸ J) = ringKrullDim R) :
    J = ⊥ := by
  by_contra hne
  obtain ⟨z, hzJ, hz0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hne
  have hzm : z ∈ maximalIdeal R := hJ hzJ
  have h1 := ringKrullDim_quotient_span_singleton_succ_eq_ringKrullDim_of_mem_nonZeroDivisors
    (mem_nonZeroDivisors_of_ne_zero hz0) hzm
  have h2 : ringKrullDim (R ⧸ J) ≤ ringKrullDim (R ⧸ span {z}) :=
    ringKrullDim_le_of_surjective _
      (Ideal.Quotient.factor_surjective ((span_singleton_le_iff_mem J).mpr hzJ))
  rw [hdim, ← h1] at h2
  have : IsLocalRing (R ⧸ span {z}) :=
    isLocalRing_quotient_of_le_maximalIdeal ((span_singleton_le_iff_mem _).mpr hzm)
  obtain ⟨m, hm⟩ := exists_ringKrullDim_eq_natCast (R ⧸ span {z})
  rw [hm] at h2
  have : m + 1 ≤ m := by exact_mod_cast h2
  omega

/-- If `R` and `R/I` are regular local, then `I` is generated by an initial segment of a regular
system of parameters `x : Fin n → R` of `R` [Sta, Tag 00NR]; the argument is in the module
docstring. -/
theorem IsRegularLocalRing.exists_span_eq_maximalIdeal_and_eq_span_image_lt [IsRegularLocalRing R]
    (I : Ideal R) [IsRegularLocalRing (R ⧸ I)] :
    ∃ (n c : ℕ) (x : Fin n → R), c ≤ n ∧ (n : WithBot ℕ∞) = ringKrullDim R ∧
      maximalIdeal R = span (Set.range x) ∧ I = span (x '' {j | j.val < c}) := by
  classical
  have hIne : I ≠ ⊤ := Ideal.Quotient.nontrivial_iff.mp inferInstance
  have hIle : I ≤ maximalIdeal R := le_maximalIdeal hIne
  -- a minimal generating system of `𝔪̄`, lifted to `𝔪`
  set d := (maximalIdeal (R ⧸ I)).spanFinrank with hd_def
  have hd : (d : WithBot ℕ∞) = ringKrullDim (R ⧸ I) := IsRegularLocalRing.spanFinrank_maximalIdeal
  obtain ⟨s, hs_card, hs_span⟩ := Submodule.FG.exists_span_finset_card_eq_spanFinrank
    (IsNoetherian.noetherian (maximalIdeal (R ⧸ I)))
  have hmax : maximalIdeal (R ⧸ I) = (maximalIdeal R).map (Ideal.Quotient.mk I) :=
    maximalIdeal_quotient_eq_map I
  have hlift : ∀ a : s, ∃ y : R, y ∈ maximalIdeal R ∧ Ideal.Quotient.mk I y = a := fun a => by
    have ha : (a : R ⧸ I) ∈ maximalIdeal (R ⧸ I) := by
      rw [← hs_span]
      exact Submodule.subset_span (Finset.mem_coe.mpr a.2)
    rw [hmax] at ha
    exact (Ideal.mem_map_iff_of_surjective _ Ideal.Quotient.mk_surjective).mp ha
  choose y hy using hlift
  -- `𝔪 = (y_a) + I`
  have hmy : maximalIdeal R = span (Set.range y) ⊔ I := by
    apply le_antisymm
    · intro m hm
      have hrange : Set.range (Ideal.Quotient.mk I ∘ y) = (s : Set (R ⧸ I)) := by
        ext z
        simp only [Set.mem_range, Function.comp_apply, Finset.mem_coe]
        constructor
        · rintro ⟨a, rfl⟩
          rw [(hy a).2]
          exact a.2
        · intro hz
          exact ⟨⟨z, hz⟩, (hy ⟨z, hz⟩).2⟩
      have h1 : Ideal.Quotient.mk I m ∈ (span (Set.range y)).map (Ideal.Quotient.mk I) := by
        rw [Ideal.map_span, ← Set.range_comp, hrange]
        change Ideal.Quotient.mk I m ∈ Submodule.span (R ⧸ I) (s : Set (R ⧸ I))
        rw [hs_span, hmax]
        exact Ideal.mem_map_of_mem _ hm
      have h2 : m ∈ ((span (Set.range y)).map (Ideal.Quotient.mk I)).comap (Ideal.Quotient.mk I) :=
        Ideal.mem_comap.mpr h1
      rwa [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
        ← RingHom.ker_eq_comap_bot, Ideal.mk_ker] at h2
    · exact sup_le (span_le.mpr (by rintro _ ⟨a, rfl⟩; exact (hy a).1)) hIle
  -- the classes of `I` in `𝔪/𝔪²`, and those of the `y_a`
  let tc : maximalIdeal R →ₗ[R] CotangentSpace R := (maximalIdeal R).toCotangent
  let y' : s → maximalIdeal R := fun a => ⟨y a, (hy a).1⟩
  let i' : I → maximalIdeal R := fun i => ⟨i, hIle i.2⟩
  set t : Set (CotangentSpace R) := Set.range fun i : I => tc (i' i) with ht
  set A := Submodule.span (ResidueField R) (Set.range fun a : s => tc (y' a)) with hA
  set B := Submodule.span (ResidueField R) t with hB
  -- Nakayama: the classes of the `y_a` and of `I` span `𝔪/𝔪²`
  have hsup : A ⊔ B = ⊤ := by
    have hspanI : span (Set.range fun i : I => (i : R)) = I :=
      le_antisymm (span_le.mpr (by rintro _ ⟨i, rfl⟩; exact i.2))
        fun x hx => subset_span ⟨⟨x, hx⟩, rfl⟩
    have hfam : maximalIdeal R = span (Set.range (Sum.elim y fun i : I => (i : R))) := by
      rw [Set.Sum.elim_range, span_union, hspanI]
      exact hmy
    have hmem : ∀ p, Sum.elim y (fun i : I => (i : R)) p ∈ maximalIdeal R := fun p => by
      rcases p with a | i
      exacts [(hy a).1, hIle i.2]
    have := (span_eq_maximalIdeal_iff_span_toCotangent_eq_top _ hmem).mp hfam
    rw [hA, hB, ← Submodule.span_union, ← this]
    congr 1
    ext v
    constructor
    · rintro (⟨a, rfl⟩ | ⟨i, rfl⟩)
      · exact ⟨Sum.inl a, rfl⟩
      · exact ⟨Sum.inr i, rfl⟩
    · rintro ⟨a | i, rfl⟩
      · exact Or.inl ⟨a, rfl⟩
      · exact Or.inr ⟨i, rfl⟩
  -- a maximal linearly independent subset `b` of the classes of `I`
  obtain ⟨b, hbt, hbspan, hbli⟩ := exists_linearIndependent (ResidueField R) t
  have hbfin : Finite b := hbli.set_finite_of_isNoetherian.to_subtype
  set c := Nat.card b with hc
  have hBcard : Module.finrank (ResidueField R) B = c := by
    have hspan' : Submodule.span (ResidueField R) (Set.range ((↑) : b → CotangentSpace R)) = B := by
      rw [Subtype.range_coe, hbspan]
    have := Module.finrank_eq_nat_card_basis (Module.Basis.span hbli)
    rwa [hspan'] at this
  -- counting: `dim 𝔪/𝔪² ≤ d + c`
  have hcount : Module.finrank (ResidueField R) (CotangentSpace R) ≤ d + c := by
    have h := Submodule.finrank_add_le_finrank_add_finrank A B
    rw [hsup, finrank_top] at h
    refine h.trans (add_le_add ?_ hBcard.le)
    exact (finrank_range_le_card _).trans (by rw [Fintype.card_coe, hs_card])
  -- a basis of `𝔪/𝔪²` extending `b`, reindexed by `Fin (c + e)` with `b` first
  set B0 := Module.Basis.sumExtend hbli with hB0
  have hfin := Module.Finite.finite_basis B0
  have hJfin : Finite (Module.Basis.sumExtendIndex hbli) :=
    Finite.of_injective (Sum.inr : Module.Basis.sumExtendIndex hbli → b ⊕ _) Sum.inr_injective
  set e := Nat.card (Module.Basis.sumExtendIndex hbli) with he
  have hn : Module.finrank (ResidueField R) (CotangentSpace R) = c + e := by
    rw [Module.finrank_eq_nat_card_basis B0, Nat.card_sum]
  have hed : e ≤ d := by omega
  let E : b ⊕ Module.Basis.sumExtendIndex hbli ≃ Fin (c + e) :=
    (Equiv.sumCongr (Finite.equivFin b) (Finite.equivFin _)).trans finSumFinEquiv
  have hb_inl : ∀ i : b, B0 (Sum.inl i) = (i : CotangentSpace R) := fun i => by
    rw [hB0]
    unfold Module.Basis.sumExtend
    rw [Module.Basis.reindex_apply, Module.Basis.extend_apply_self]
    rfl
  -- lifts: elements of `I` for the `b`-part, elements of `𝔪` for the rest
  choose f hf using fun i : b => (show ∃ j : I, tc (i' j) = (i : CotangentSpace R) from hbt i.2)
  choose g hg using fun j : Module.Basis.sumExtendIndex hbli =>
    (maximalIdeal R).toCotangent_surjective (B0 (Sum.inr j))
  let lift0 : b ⊕ Module.Basis.sumExtendIndex hbli → maximalIdeal R :=
    Sum.elim (fun i => i' (f i)) g
  have hlift0 : ∀ p, tc (lift0 p) = B0 p := by
    rintro (i | j)
    · exact (hf i).trans (hb_inl i).symm
    · exact hg j
  let x : Fin (c + e) → R := fun k => (lift0 (E.symm k) : R)
  have hxm : ∀ k, x k ∈ maximalIdeal R := fun k => (lift0 (E.symm k)).2
  have hBx : ∀ k, (B0.reindex E) k = (maximalIdeal R).toCotangent ⟨x k, hxm k⟩ := fun k => by
    rw [Module.Basis.reindex_apply, ← hlift0]
  obtain ⟨hx, hcard⟩ :=
    (span_eq_maximalIdeal_and_card_eq_spanFinrank_iff x hxm).mpr ⟨B0.reindex E, hBx⟩
  have hnR : ((c + e : ℕ) : WithBot ℕ∞) = ringKrullDim R := by
    rw [← IsRegularLocalRing.spanFinrank_maximalIdeal (R := R), ← hcard, Fintype.card_fin]
  -- the initial segment `J = (x_0, …, x_{c-1})` lies in `I`
  set J := span (x '' {j : Fin (c + e) | j.val < c}) with hJ
  have hJI : J ≤ I := by
    rw [hJ, span_le]
    rintro _ ⟨k, hk, rfl⟩
    have hk' : k.val < c := hk
    have hE : E.symm k = Sum.inl ((Finite.equivFin b).symm ⟨k.val, hk'⟩) := by
      have hk2 : k = Fin.castAdd e ⟨k.val, hk'⟩ := Fin.ext rfl
      conv_lhs => rw [hk2]
      change ((Equiv.sumCongr (Finite.equivFin b) (Finite.equivFin _)).trans finSumFinEquiv).symm
        (Fin.castAdd e ⟨k.val, hk'⟩) = _
      rw [Equiv.symm_trans_apply, finSumFinEquiv_symm_apply_castAdd, Equiv.sumCongr_symm,
        Equiv.sumCongr_apply, Sum.map_inl]
    change (lift0 (E.symm k) : R) ∈ I
    rw [hE]
    exact (f _).2
  -- `R/J` is regular of dimension `e ≤ d`, and `R/J → R/I` is onto: `dim R/J = dim R/I`
  have hcle : c ≤ c + e := Nat.le_add_right c e
  have hregJ := isRegularLocalRing_quotient_span_image_lt x hx hnR c
  have hdimJ := ringKrullDim_quotient_span_image_lt x hx hnR hcle
  have hsurjJ : ringKrullDim (R ⧸ I) ≤ ringKrullDim (R ⧸ J) :=
    ringKrullDim_le_of_surjective _ (Ideal.Quotient.factor_surjective hJI)
  have hm : ((maximalIdeal (R ⧸ J)).spanFinrank : WithBot ℕ∞) = ringKrullDim (R ⧸ J) :=
    IsRegularLocalRing.spanFinrank_maximalIdeal
  set m := (maximalIdeal (R ⧸ J)).spanFinrank with hm_def
  have hme : m + c = c + e := by
    have h := hdimJ
    rw [← hm, ← hnR] at h
    exact_mod_cast h
  have hdm : d ≤ m := by
    have h := hsurjJ
    rw [← hm, ← hd] at h
    exact_mod_cast h
  have hmd : ringKrullDim (R ⧸ I) = ringKrullDim (R ⧸ J) := by
    rw [← hm, ← hd]
    congr 1
    omega
  -- `I/J` is a proper ideal of the regular local domain `R/J` with a quotient of full dimension
  have hIJ : I.map (Ideal.Quotient.mk J) = ⊥ := by
    have hle : I.map (Ideal.Quotient.mk J) ≤ maximalIdeal (R ⧸ J) := by
      rw [maximalIdeal_quotient_eq_map J]
      exact Ideal.map_mono hIle
    refine Ideal.eq_bot_of_ringKrullDim_quotient_eq hle ?_
    rw [← hmd]
    exact ringKrullDim_eq_of_ringEquiv
      ((DoubleQuot.quotQuotEquivQuotSup J I).trans (Ideal.quotEquivOfEq (sup_eq_right.mpr hJI)))
  refine ⟨c + e, c, x, hcle, hnR, hx, ?_⟩
  rw [← hJ]
  exact le_antisymm (((Ideal.map_eq_bot_iff_le_ker _).mp hIJ).trans_eq Ideal.mk_ker) hJI

