/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.Regular.RegularSequence
public import Mathlib.RingTheory.RegularLocalRing.Defs
import Hironaka.Algebra.Local.Regular
import Mathlib.LinearAlgebra.Dimension.OrzechProperty

/-!
# Regular systems of parameters: bases of `𝔪/𝔪²` and regular sequences

`R` is a Noetherian local ring with maximal ideal `𝔪`, residue field `K` and cotangent space
`𝔪/𝔪²`.  This file proves the two ring-level facts about regular systems of parameters that the
chart ring of a blow-up and the Cohen structure theorem need: a regular system of parameters is
a basis of `𝔪/𝔪²`, and it is a regular sequence whose initial segments cut out regular local
quotients.

## Generating systems and the cotangent space

By Nakayama's lemma a family `s ⊆ 𝔪` generates `𝔪` iff its classes span `𝔪/𝔪²` (Mathlib's
`IsLocalRing.CotangentSpace.span_image_eq_top_iff`, transported from submodules of `𝔪` to ideals
of `R` along the inclusion `𝔪 ⊆ R`).  Since `spanFinrank 𝔪 = dim_K 𝔪/𝔪²`
(`spanFinrank_maximalIdeal_eq_finrank_cotangentSpace`), a generating family of `spanFinrank 𝔪`
elements has linearly independent classes (a spanning family of the right cardinality is a
basis) and conversely a basis of classes comes from a minimal generating system.  For a regular
local ring `spanFinrank 𝔪 = dim R`, so a regular system of parameters `x₁, …, xₙ` is a basis of
`𝔪/𝔪²`; in particular no `xᵢ` lies in `𝔪²` (`notMem_sq_of_span_eq`, the fact the induction below
needs).  An element `y ∈ 𝔪 ∖ 𝔪²` is completed to a regular system of parameters by the exchange
lemma of `Hironaka/Algebra/Local/Regular.lean` (`exists_span_insert_eq_maximalIdeal`: `𝔪 = ⟨y⟩ +
⟨t⟩` with `card t + 1 = spanFinrank 𝔪 = n`), enumerated by `Fin n`.

## Quotients by initial segments and regular sequences

For a regular system of parameters `x : Fin n → R` and `i ≤ n` let `Pᵢ = ⟨x₀, …, x_{i-1}⟩`.  By
induction on `i`: `R/Pᵢ` is regular local with `dim R/Pᵢ + i = dim R`.  The step uses that the
maximal ideal of `R/Pᵢ` is generated by the classes of `xᵢ, …, x_{n-1}`
(`map_maximalIdeal_quotient_span_image_lt`: the other generators die), so these `n − i`
classes are a regular system of parameters of `R/Pᵢ` and the class of `xᵢ` is not in the square
of the maximal ideal (the cotangent-space fact above, applied to `R/Pᵢ`);
`IsRegularLocalRing.quotient_span_singleton` then makes `(R/Pᵢ)/(x̄ᵢ)` regular of one dimension
less, and `(R/Pᵢ)/(x̄ᵢ) ≅ R/P_{i+1}` (`DoubleQuot.quotQuotEquivQuotSup`).  Each `R/Pᵢ` is a
domain (`isDomain_of_isRegularLocalRing`), so `Pᵢ` is prime and `x̄ᵢ ≠ 0` is a nonzerodivisor
of `R/Pᵢ`: a regular system of parameters is a regular sequence [Sta, Tag 00NQ], stated in the
list form `isRegular_of_span_eq_maximalIdeal` of Mathlib pull request 28683.  For `i ≥ n`,
`Pᵢ = 𝔪`.
-/

public section

namespace IsLocalRing

open IsLocalRing Ideal

universe u v

variable {R : Type u} [CommRing R]

section Cotangent

variable [IsLocalRing R] [IsNoetherianRing R] {ι : Type v} (s : ι → R)
  (hs : ∀ i, s i ∈ maximalIdeal R)

/-- By Nakayama's lemma, a family of elements of `𝔪` generates `𝔪` iff its classes span
`𝔪/𝔪²`. -/
theorem span_eq_maximalIdeal_iff_span_toCotangent_eq_top :
    maximalIdeal R = span (Set.range s) ↔
      Submodule.span (ResidueField R)
        (Set.range fun i => (maximalIdeal R).toCotangent ⟨s i, hs i⟩) = ⊤ := by
  have h1 : (Set.range fun i => (maximalIdeal R).toCotangent ⟨s i, hs i⟩) =
      (maximalIdeal R).toCotangent '' Set.range (fun i => (⟨s i, hs i⟩ : maximalIdeal R)) := by
    rw [← Set.range_comp]; rfl
  rw [h1, CotangentSpace.span_image_eq_top_iff,
    ← (Submodule.map_injective_of_injective (Submodule.injective_subtype (maximalIdeal R))).eq_iff,
    Submodule.map_span, Submodule.map_top, Submodule.range_subtype]
  have h2 : (maximalIdeal R).subtype '' Set.range (fun i => (⟨s i, hs i⟩ : maximalIdeal R)) =
      Set.range s := by
    rw [← Set.range_comp]; rfl
  rw [h2]
  exact eq_comm

/-- Minimal generating systems of `𝔪` are exactly the families whose classes form a basis of
`𝔪/𝔪²`. -/
theorem span_eq_maximalIdeal_and_card_eq_spanFinrank_iff [Fintype ι] :
    (maximalIdeal R = span (Set.range s) ∧ Fintype.card ι = (maximalIdeal R).spanFinrank) ↔
      ∃ b : Module.Basis ι (ResidueField R) (CotangentSpace R),
        ∀ i, b i = (maximalIdeal R).toCotangent ⟨s i, hs i⟩ := by
  rw [span_eq_maximalIdeal_iff_span_toCotangent_eq_top s hs,
    spanFinrank_maximalIdeal_eq_finrank_cotangentSpace R]
  constructor
  · rintro ⟨hsp, hcard⟩
    have hli : LinearIndependent (ResidueField R)
        (fun i => (maximalIdeal R).toCotangent ⟨s i, hs i⟩) := by
      rw [linearIndependent_iff_card_eq_finrank_span, hcard]
      change _ = Module.finrank _ (Submodule.span _ _)
      rw [hsp, finrank_top]
    exact ⟨Module.Basis.mk hli hsp.ge, fun i => Module.Basis.mk_apply hli hsp.ge i⟩
  · rintro ⟨b, hb⟩
    have hbv : ⇑b = fun i => (maximalIdeal R).toCotangent ⟨s i, hs i⟩ := funext hb
    exact ⟨by rw [← hbv]; exact b.span_eq, Module.finrank_eq_card_basis b ▸ rfl⟩

end Cotangent

section Regular

variable [IsRegularLocalRing R] {n : ℕ} (x : Fin n → R)

/-- A regular system of parameters lies in `𝔪`. -/
theorem x_mem_maximalIdeal_of_span_eq (hx : maximalIdeal R = span (Set.range x)) (i : Fin n) :
    x i ∈ maximalIdeal R :=
  hx ▸ Ideal.subset_span ⟨i, rfl⟩

/-- In a regular local ring of dimension `n`, `𝔪` needs `n` generators. -/
theorem spanFinrank_maximalIdeal_eq_of_natCast_eq (hn : (n : WithBot ℕ∞) = ringKrullDim R) :
    (maximalIdeal R).spanFinrank = n := by
  have h := IsRegularLocalRing.spanFinrank_maximalIdeal (R := R)
  rw [← hn] at h
  exact_mod_cast h

/-- A regular system of parameters is a basis of `𝔪/𝔪²`. -/
theorem exists_basis_cotangentSpace_of_span_eq (hx : maximalIdeal R = span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) :
    ∃ b : Module.Basis (Fin n) (ResidueField R) (CotangentSpace R),
      ∀ i, b i = (maximalIdeal R).toCotangent ⟨x i, hx ▸ Ideal.subset_span ⟨i, rfl⟩⟩ :=
  (span_eq_maximalIdeal_and_card_eq_spanFinrank_iff x (x_mem_maximalIdeal_of_span_eq x hx)).mp
    ⟨hx, by rw [Fintype.card_fin, spanFinrank_maximalIdeal_eq_of_natCast_eq hn]⟩

/-- No member of a regular system of parameters lies in `𝔪²`. -/
theorem notMem_sq_of_span_eq (hx : maximalIdeal R = span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (k : Fin n) : x k ∉ maximalIdeal R ^ 2 := by
  obtain ⟨b, hb⟩ := exists_basis_cotangentSpace_of_span_eq x hx hn
  intro hk
  apply b.ne_zero k
  rw [hb k]
  exact (Ideal.toCotangent_eq_zero _ _).mpr hk

/-- An element of `𝔪 ∖ 𝔪²` can be completed to a regular system of parameters (by the exchange
lemma `exists_span_insert_eq_maximalIdeal`). -/
theorem exists_span_eq_maximalIdeal_of_notMem_sq (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    {y : R} (hy : y ∈ maximalIdeal R) (hy2 : y ∉ maximalIdeal R ^ 2) :
    ∃ x' : Fin n → R, (∃ i, x' i = y) ∧ maximalIdeal R = span (Set.range x') := by
  classical
  obtain ⟨t, -, hcard, hspan⟩ := exists_span_insert_eq_maximalIdeal hy hy2
  rw [spanFinrank_maximalIdeal_eq_of_natCast_eq hn] at hcard
  let e : Fin (t.card + 1) → R := Fin.cons y fun j => ((t.equivFin.symm j : t) : R)
  have hrange : Set.range e = insert y (t : Set R) := by
    ext z
    simp only [Set.mem_range, Set.mem_insert_iff, Finset.mem_coe]
    constructor
    · rintro ⟨i, rfl⟩
      refine Fin.cases ?_ (fun j => ?_) i
      · exact Or.inl (Fin.cons_zero _ _)
      · exact Or.inr (by simp only [e, Fin.cons_succ]; exact (t.equivFin.symm j).2)
    · rintro (rfl | hz)
      · exact ⟨0, Fin.cons_zero _ _⟩
      · exact ⟨(t.equivFin ⟨z, hz⟩).succ, by simp [e, Fin.cons_succ]⟩
  refine ⟨e ∘ finCongr hcard.symm, ⟨finCongr hcard 0, ?_⟩, ?_⟩
  · simp [e]
  · rw [hspan, ← hrange, (finCongr hcard.symm).surjective.range_comp e]

/-! ### Quotients by initial segments of a regular system of parameters -/

omit [IsRegularLocalRing R] in
theorem span_image_lt_zero : span (x '' {j : Fin n | j.val < 0}) = ⊥ := by
  have : {j : Fin n | j.val < 0} = ∅ :=
    Set.eq_empty_of_forall_notMem fun j hj => Nat.not_lt_zero _ hj
  rw [this, Set.image_empty, Ideal.span_empty]

theorem span_image_lt_of_le (hx : maximalIdeal R = span (Set.range x)) {i : ℕ} (hi : n ≤ i) :
    span (x '' {j : Fin n | j.val < i}) = maximalIdeal R := by
  have : {j : Fin n | j.val < i} = Set.univ := Set.eq_univ_of_forall fun j => lt_of_lt_of_le j.2 hi
  rw [this, Set.image_univ, hx]

omit [IsRegularLocalRing R] in
theorem span_image_lt_succ {i : ℕ} (hi : i < n) :
    span (x '' {j : Fin n | j.val < i + 1}) =
      span (x '' {j : Fin n | j.val < i}) ⊔ span {x ⟨i, hi⟩} := by
  have : {j : Fin n | j.val < i + 1} = insert ⟨i, hi⟩ {j : Fin n | j.val < i} := by
    ext j
    simp only [Set.mem_ofPred_eq, Set.mem_insert_iff, Fin.ext_iff]
    omega
  rw [this, Set.image_insert_eq, Ideal.span_insert, sup_comm]

/-- The classes of `xᵢ, …, x_{n-1}` generate the maximal ideal of `R/Pᵢ`. -/
theorem map_maximalIdeal_quotient_span_image_lt (hx : maximalIdeal R = span (Set.range x))
    (i : ℕ) :
    (maximalIdeal R).map (Ideal.Quotient.mk (span (x '' {j : Fin n | j.val < i}))) =
      span ((Ideal.Quotient.mk (span (x '' {j : Fin n | j.val < i})) ∘ x) '' {j | i ≤ j.val}) := by
  rw [hx, Ideal.map_span, ← Set.range_comp]
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨j, rfl⟩
    by_cases hj : i ≤ j.val
    · exact Ideal.subset_span ⟨j, hj, rfl⟩
    · have h0 : (Ideal.Quotient.mk (span (x '' {j : Fin n | j.val < i})) ∘ x) j = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span ⟨j, not_le.mp hj, rfl⟩)
      rw [h0]
      exact zero_mem _
  · exact Ideal.span_mono (Set.image_subset_range _ _)

/-- The step of the induction: if `R/Pᵢ` is regular of dimension `dim R − i`, the class of `xᵢ`
is not in the square of its maximal ideal, because the classes of `xᵢ, …, x_{n-1}` are a regular
system of parameters of `R/Pᵢ`. -/
theorem mk_notMem_maximalIdeal_sq_of (hx : maximalIdeal R = span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {i : ℕ} (hi : i < n)
    [IsRegularLocalRing (R ⧸ span (x '' {j : Fin n | j.val < i}))]
    (hdim : ringKrullDim (R ⧸ span (x '' {j : Fin n | j.val < i})) + i = ringKrullDim R) :
    Ideal.Quotient.mk (span (x '' {j : Fin n | j.val < i})) (x ⟨i, hi⟩) ∉
      maximalIdeal (R ⧸ span (x '' {j : Fin n | j.val < i})) ^ 2 := by
  set P := span (x '' {j : Fin n | j.val < i}) with hP
  let y : Fin (n - i) → R ⧸ P := fun k => Ideal.Quotient.mk P (x ⟨i + k, by omega⟩)
  have hy : maximalIdeal (R ⧸ P) = span (Set.range y) := by
    rw [maximalIdeal_quotient_eq_map, map_maximalIdeal_quotient_span_image_lt x hx i]
    congr 1
    ext z
    simp only [Set.mem_image, Set.mem_ofPred_eq, Function.comp_apply, Set.mem_range, y]
    constructor
    · rintro ⟨j, hj, rfl⟩
      refine ⟨⟨j.val - i, by omega⟩, ?_⟩
      exact congrArg (fun k => Ideal.Quotient.mk P (x k))
        (Fin.ext (show i + (j.val - i) = j.val by omega))
    · rintro ⟨k, rfl⟩
      exact ⟨⟨i + k.val, by omega⟩, show i ≤ i + k.val by omega, rfl⟩
  have hn' : ((n - i : ℕ) : WithBot ℕ∞) = ringKrullDim (R ⧸ P) := by
    obtain ⟨m, hm⟩ := exists_ringKrullDim_eq_natCast (R ⧸ P)
    rw [hm] at hdim ⊢
    rw [← hn] at hdim
    have : m + i = n := by exact_mod_cast hdim
    congr 1
    omega
  have := notMem_sq_of_span_eq y hy hn' ⟨0, by omega⟩
  simpa [y] using this

/-- The induction: for `i ≤ n`, `R/Pᵢ` is regular local with `dim R/Pᵢ + i = dim R`
[Sta, Tag 00NQ]. -/
theorem isRegularLocalRing_quotient_span_image_lt_and_ringKrullDim
    (hx : maximalIdeal R = span (Set.range x)) (hn : (n : WithBot ℕ∞) = ringKrullDim R)
    {i : ℕ} (hi : i ≤ n) :
    IsRegularLocalRing (R ⧸ span (x '' {j : Fin n | j.val < i})) ∧
      ringKrullDim (R ⧸ span (x '' {j : Fin n | j.val < i})) + i = ringKrullDim R := by
  induction i with
  | zero =>
    rw [span_image_lt_zero]
    refine ⟨IsRegularLocalRing.of_ringEquiv (RingEquiv.quotientBot R).symm, ?_⟩
    rw [ringKrullDim_eq_of_ringEquiv (RingEquiv.quotientBot R), Nat.cast_zero, add_zero]
  | succ i ih =>
    have hi' : i < n := hi
    obtain ⟨hreg, hdim⟩ := ih hi'.le
    set P := span (x '' {j : Fin n | j.val < i}) with hP
    have hxi : Ideal.Quotient.mk P (x ⟨i, hi'⟩) ∈ maximalIdeal (R ⧸ P) := by
      rw [maximalIdeal_quotient_eq_map]
      exact Ideal.mem_map_of_mem _ (x_mem_maximalIdeal_of_span_eq x hx _)
    have hxi2 := mk_notMem_maximalIdeal_sq_of x hx hn hi' hdim
    obtain ⟨hQ, hQdim⟩ := IsRegularLocalRing.quotient_span_singleton hxi hxi2
    have hmap : span {Ideal.Quotient.mk P (x ⟨i, hi'⟩)} =
        (span {x ⟨i, hi'⟩}).map (Ideal.Quotient.mk P) := by
      rw [Ideal.map_span, Set.image_singleton]
    let e : ((R ⧸ P) ⧸ span {Ideal.Quotient.mk P (x ⟨i, hi'⟩)}) ≃+*
        R ⧸ span (x '' {j : Fin n | j.val < i + 1}) :=
      (Ideal.quotEquivOfEq hmap).trans
        ((DoubleQuot.quotQuotEquivQuotSup P (span {x ⟨i, hi'⟩})).trans
          (Ideal.quotEquivOfEq (span_image_lt_succ x hi').symm))
    refine ⟨IsRegularLocalRing.of_ringEquiv e, ?_⟩
    rw [← ringKrullDim_eq_of_ringEquiv e, Nat.cast_succ, add_comm (i : WithBot ℕ∞) 1,
      ← add_assoc, hQdim, hdim]

/-- `R/Pᵢ` is a regular local ring. -/
theorem isRegularLocalRing_quotient_span_image_lt (hx : maximalIdeal R = span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (i : ℕ) :
    IsRegularLocalRing (R ⧸ span (x '' {j : Fin n | j.val < i})) := by
  by_cases hi : i ≤ n
  · exact (isRegularLocalRing_quotient_span_image_lt_and_ringKrullDim x hx hn hi).1
  · rw [span_image_lt_of_le x hx (not_le.mp hi).le, ← span_image_lt_of_le x hx le_rfl]
    exact (isRegularLocalRing_quotient_span_image_lt_and_ringKrullDim x hx hn le_rfl).1

/-- `dim R/Pᵢ + i = dim R` for `i ≤ n`. -/
theorem ringKrullDim_quotient_span_image_lt (hx : maximalIdeal R = span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {i : ℕ} (hi : i ≤ n) :
    ringKrullDim (R ⧸ span (x '' {j : Fin n | j.val < i})) + i = ringKrullDim R :=
  (isRegularLocalRing_quotient_span_image_lt_and_ringKrullDim x hx hn hi).2

/-- `Pᵢ = ⟨x₀, …, x_{i-1}⟩` is prime. -/
theorem isPrime_span_image_lt (hx : maximalIdeal R = span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (i : ℕ) :
    (span (x '' {j : Fin n | j.val < i})).IsPrime := by
  have := isRegularLocalRing_quotient_span_image_lt x hx hn i
  exact (Ideal.Quotient.isDomain_iff_prime _).mp inferInstance

/-- `xᵢ ∉ Pᵢ`. -/
theorem notMem_span_image_lt (hx : maximalIdeal R = span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) {i : ℕ} (hi : i < n) :
    x ⟨i, hi⟩ ∉ span (x '' {j : Fin n | j.val < i}) := by
  intro h
  have hreg := isRegularLocalRing_quotient_span_image_lt_and_ringKrullDim x hx hn hi.le
  have := hreg.1
  exact mk_notMem_maximalIdeal_sq_of x hx hn hi hreg.2
    (by rw [Ideal.Quotient.eq_zero_iff_mem.mpr h]; exact zero_mem _)

/-- A regular system of parameters is a regular sequence [Sta, Tag 00NQ] (named as in Mathlib
pull request 28683). -/
theorem isRegular_of_span_eq_maximalIdeal (rs : List R) (hspan : Ideal.ofList rs = maximalIdeal R)
    (len : (rs.length : WithBot ℕ∞) = ringKrullDim R) : RingTheory.Sequence.IsRegular R rs := by
  classical
  let x : Fin rs.length → R := fun i => rs[i]
  have hx : maximalIdeal R = span (Set.range x) := by
    rw [← hspan]
    change span {r | r ∈ rs} = span (Set.range x)
    congr 1
    ext a
    simp only [Set.mem_ofPred_eq, Set.mem_range, x, List.mem_iff_getElem, Fin.exists_iff,
      Fin.getElem_fin]
  have hP : ∀ i : ℕ, Ideal.ofList (rs.take i) = span (x '' {j : Fin rs.length | j.val < i}) := by
    intro i
    change span {r | r ∈ rs.take i} = span (x '' {j : Fin rs.length | j.val < i})
    congr 1
    ext a
    simp only [Set.mem_ofPred_eq, Set.mem_image, x, List.mem_take_iff_getElem, Fin.getElem_fin]
    constructor
    · rintro ⟨j, hj, rfl⟩
      exact ⟨⟨j, (lt_min_iff.mp hj).2⟩, (lt_min_iff.mp hj).1, rfl⟩
    · rintro ⟨j, hj, rfl⟩
      exact ⟨j.val, lt_min_iff.mpr ⟨hj, j.2⟩, rfl⟩
  refine ⟨⟨fun i hi => ?_⟩, ?_⟩
  · rw [hP i, Ideal.smul_eq_mul, Ideal.mul_top]
    have hreg := isRegularLocalRing_quotient_span_image_lt_and_ringKrullDim x hx len hi.le
    have := hreg.1
    have hne : Ideal.Quotient.mk (span (x '' {j : Fin rs.length | j.val < i})) (x ⟨i, hi⟩) ≠ 0 :=
      fun h => notMem_span_image_lt x hx len hi (Ideal.Quotient.eq_zero_iff_mem.mp h)
    intro a b hab
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective b
    have key : ∀ c : R, rs[i] • Ideal.Quotient.mk (span (x '' {j : Fin rs.length | j.val < i})) c =
        Ideal.Quotient.mk (span (x '' {j : Fin rs.length | j.val < i})) (x ⟨i, hi⟩ * c) :=
      fun c => rfl
    dsimp only at hab
    rw [key, key, map_mul, map_mul] at hab
    exact mul_left_cancel₀ hne hab
  · rw [hspan, Ideal.smul_eq_mul, Ideal.mul_top]
    exact fun h => (maximalIdeal.isMaximal R).ne_top h.symm

end Regular

section Existence

/-- A regular local ring has a regular system of parameters — a family `x : Fin d → R` with
`𝔪 = ⟨x⟩` and `d = dim R` (a generating finset of `𝔪` of cardinality `spanFinrank 𝔪 = dim R`). -/
theorem exists_regularSystem (R : Type u) [CommRing R] [IsRegularLocalRing R] :
    ∃ (d : ℕ) (x : Fin d → R),
      maximalIdeal R = Ideal.span (Set.range x) ∧ (d : WithBot ℕ∞) = ringKrullDim R := by
  obtain ⟨s, hs, hspan⟩ := Submodule.FG.exists_span_finset_card_eq_spanFinrank
    (maximalIdeal R).fg_of_isNoetherianRing
  refine ⟨s.card, fun i => ((s.equivFin.symm i : s) : R), ?_, ?_⟩
  · rw [← hspan]
    congr 1
    ext r
    constructor
    · intro hr
      exact ⟨s.equivFin ⟨r, Finset.mem_coe.mp hr⟩, by simp⟩
    · rintro ⟨i, rfl⟩
      exact Finset.mem_coe.mpr (s.equivFin.symm i).2
  · rw [hs, IsRegularLocalRing.spanFinrank_maximalIdeal]

end Existence

end IsLocalRing
