/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.Derivative

/-!
# The top-order partials generate `Dʳ(I)` in characteristic zero

Kollár remarks, in [Kol07, Definition 73], that `Dʳ(I)` contains all `r`-th partial derivatives of
elements of `I` but is bigger over general rings ("try second derivatives over `ℤ[x]`"), while
over fields of characteristic zero the two agree, by formulas such as
`∂f/∂y = ∂²(xf)/∂y∂x − x ∂²f/∂y∂x` and `2 ∂f/∂x = ∂²(xf)/∂x² − x ∂²f/∂x²`.

`Dʳ(I)` is generated by the iterated partials of order `≤ r` of the elements of `I`
(`Dpow_span`, `Hironaka/Algebra/Local/Derivative.lean`); this file shows that in characteristic zero
(`Algebra ℚ R`, the standing hypothesis of `RegularCoords`) the partials of order exactly `r`
suffice, as long as there is a coordinate to differentiate along (`0 < n`).  The general form of
Kollár's two identities is `∂^{i₀ ∷ l}(x_{i₀} f) = x_{i₀} ∂^{i₀ ∷ l} f + (k + 1) ∂^l f`, `k` the
number of occurrences of `i₀` in `l` (`iterPderiv_x_mul`), and `k + 1` is a unit.  The result is
a remark on the definition; nothing else in the library depends on it.
-/

@[expose] public section

namespace IsLocalRing

namespace RegularCoords

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ}
  (c : RegularCoords R n)

/-- The partials of order exactly `r` of the elements of `S` (compare `iterPderivSet`, order
`≤ r`). -/
def topPderivSet (S : Set R) (r : ℕ) : Set R :=
  ⋃ (l : List (Fin n)) (_ : l.length = r), c.iterPderiv l '' S

theorem mem_topPderivSet {S : Set R} {r : ℕ} {f : R} :
    f ∈ c.topPderivSet S r ↔ ∃ l : List (Fin n), l.length = r ∧ ∃ s ∈ S, c.iterPderiv l s = f := by
  simp [topPderivSet]

theorem topPderivSet_subset_iterPderivSet (S : Set R) (r : ℕ) :
    c.topPderivSet S r ⊆ c.iterPderivSet S r := fun f hf => by
  obtain ⟨l, hl, s, hs, rfl⟩ := c.mem_topPderivSet.mp hf
  exact c.mem_iterPderivSet.mpr ⟨l, hl.le, s, hs, rfl⟩

/-- Iterated partials do not depend on the order of differentiation. -/
theorem iterPderiv_perm {l l' : List (Fin n)} (h : l.Perm l') (f : R) :
    c.iterPderiv l f = c.iterPderiv l' f := by
  induction h with
  | nil => rfl
  | cons i _ ih => rw [iterPderiv_cons, iterPderiv_cons, ih]
  | swap i j l => simp only [iterPderiv_cons]; exact c.pderiv_comm j i _
  | trans _ _ ih1 ih2 => exact ih1.trans ih2

/-- Every `r`-th partial of an element of `I` lies in `Dʳ(I)` [Kol07, Definition 73]. -/
theorem iterPderiv_mem_Dpow {I : Ideal R} {f : R} (hf : f ∈ I) (l : List (Fin n)) :
    c.iterPderiv l f ∈ c.Dpow l.length I := by
  induction l with
  | nil => simpa using hf
  | cons i l ih => rw [iterPderiv_cons, List.length_cons, Dpow_succ]; exact c.pderiv_mem_D ih i

/-- The `r`-th partials of elements of `I` lie in `Dʳ(I)`. -/
theorem span_topPderivSet_le (I : Ideal R) (r : ℕ) :
    Ideal.span (c.topPderivSet (I : Set R) r) ≤ c.Dpow r I := by
  refine Ideal.span_le.mpr fun g hg => ?_
  obtain ⟨l, hl, f, hf, rfl⟩ := c.mem_topPderivSet.mp hg
  rw [← hl]
  exact c.iterPderiv_mem_Dpow hf l

/-- Kollár's first identity [Kol07, Definition 73]: for `j ≠ i`,
`∂ⱼ f = ∂ⱼ∂ᵢ(xᵢ f) − xᵢ ∂ⱼ∂ᵢ f`. -/
theorem pderiv_eq_of_ne {i j : Fin n} (h : j ≠ i) (f : R) :
    c.pderiv j f = c.pderiv j (c.pderiv i (c.x i * f)) - c.x i * c.pderiv j (c.pderiv i f) := by
  rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x, ite_eq_left rfl, mul_one, map_add,
    Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x, ite_eq_right h, mul_zero, add_zero]
  ring

/-- Kollár's second identity [Kol07, Definition 73]: `2 ∂ᵢ f = ∂ᵢ²(xᵢ f) − xᵢ ∂ᵢ² f`. -/
theorem two_nsmul_pderiv (i : Fin n) (f : R) :
    2 • c.pderiv i f = c.pderiv i (c.pderiv i (c.x i * f)) - c.x i * c.pderiv i (c.pderiv i f) := by
  rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x, ite_eq_left rfl, mul_one, map_add,
    Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x, ite_eq_left rfl, mul_one, two_smul]
  ring

/-- The general form of Kollár's identities: `∂^l(xᵢ f) = xᵢ ∂^l f + k ∂^{l ∖ i} f`, where `k` is
the number of occurrences of `i` in `l` and `l ∖ i` erases one of them. -/
theorem iterPderiv_x_mul (l : List (Fin n)) (i : Fin n) (f : R) :
    c.iterPderiv l (c.x i * f) =
      c.x i * c.iterPderiv l f + (l.count i) • c.iterPderiv (l.erase i) f := by
  induction l with
  | nil => simp
  | cons j l ih =>
    rw [iterPderiv_cons, ih, map_add, Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.pderiv_x,
      map_nsmul, ← iterPderiv_cons, ← iterPderiv_cons]
    by_cases hij : j = i
    · subst hij
      rw [ite_eq_left rfl, mul_one, List.count_cons_self, List.erase_cons_head, add_smul, one_smul]
      by_cases hmem : j ∈ l
      · rw [c.iterPderiv_perm (List.perm_cons_erase hmem).symm]
        simp only [nsmul_eq_mul]
        ring
      · rw [List.count_eq_zero.mpr hmem]
        simp
    · rw [ite_eq_right hij, mul_zero, add_zero, List.count_cons_of_ne hij,
        List.erase_cons_tail (by simpa using hij)]

/-- In characteristic zero, every `r`-th partial of an element of `I` is a combination of
`(r+1)`-th partials of elements of `I`, provided there is a coordinate (`0 < n`):
`(k + 1) ∂^l f = ∂^{i₀ ∷ l}(x_{i₀} f) − x_{i₀} ∂^{i₀ ∷ l} f` with `k + 1` a unit. -/
theorem iterPderiv_mem_span_topPderivSet_succ (hn : 0 < n) {I : Ideal R} {f : R} (hf : f ∈ I)
    (l : List (Fin n)) :
    c.iterPderiv l f ∈ Ideal.span (c.topPderivSet (I : Set R) (l.length + 1)) := by
  set i₀ : Fin n := ⟨0, hn⟩
  have hid := c.iterPderiv_x_mul (i₀ :: l) i₀ f
  rw [List.count_cons_self, List.erase_cons_head] at hid
  have hmem : ((l.count i₀ + 1 : ℕ) : R) * c.iterPderiv l f ∈
      Ideal.span (c.topPderivSet (I : Set R) (l.length + 1)) := by
    have h2 : (l.count i₀ + 1) • c.iterPderiv l f =
        c.iterPderiv (i₀ :: l) (c.x i₀ * f) - c.x i₀ * c.iterPderiv (i₀ :: l) f :=
      eq_sub_of_add_eq' hid.symm
    rw [← nsmul_eq_mul, h2]
    refine Ideal.sub_mem _ (Ideal.subset_span ?_) (Ideal.mul_mem_left _ _ (Ideal.subset_span ?_))
    · exact c.mem_topPderivSet.mpr ⟨i₀ :: l, List.length_cons, c.x i₀ * f,
        Ideal.mul_mem_left I _ hf, rfl⟩
    · exact c.mem_topPderivSet.mpr ⟨i₀ :: l, List.length_cons, f, hf, rfl⟩
  have hu := isUnit_natCast (R := R) (Nat.succ_ne_zero (l.count i₀))
  have := Ideal.mul_mem_left _ (↑hu.unit⁻¹ : R) hmem
  rwa [← mul_assoc, hu.val_inv_mul, one_mul] at this

/-- In characteristic zero the `r`-th partials of elements of `I` lie in the span of the
`(r+1)`-th partials (`0 < n`). -/
theorem span_topPderivSet_le_succ (hn : 0 < n) (I : Ideal R) (r : ℕ) :
    Ideal.span (c.topPderivSet (I : Set R) r) ≤
      Ideal.span (c.topPderivSet (I : Set R) (r + 1)) := by
  refine Ideal.span_le.mpr fun g hg => ?_
  obtain ⟨l, hl, f, hf, rfl⟩ := c.mem_topPderivSet.mp hg
  rw [← hl]
  exact c.iterPderiv_mem_span_topPderivSet_succ hn hf l

theorem span_topPderivSet_mono (hn : 0 < n) (I : Ideal R) {r s : ℕ} (hrs : r ≤ s) :
    Ideal.span (c.topPderivSet (I : Set R) r) ≤ Ideal.span (c.topPderivSet (I : Set R) s) := by
  induction s, hrs using Nat.le_induction with
  | base => exact le_rfl
  | succ s _ ih => exact ih.trans (c.span_topPderivSet_le_succ hn I s)

/-- **In characteristic zero, `Dʳ(I)` is generated by the `r`-th iterated partials of the elements
of `I` alone**, provided there is a coordinate (`0 < n`) (Kollár's remark in
[Kol07, Definition 73]). -/
theorem Dpow_eq_span_topPderivSet (hn : 0 < n) (I : Ideal R) (r : ℕ) :
    c.Dpow r I = Ideal.span (c.topPderivSet (I : Set R) r) := by
  refine le_antisymm ?_ (c.span_topPderivSet_le I r)
  conv_lhs => rw [← Ideal.span_eq I]
  rw [Dpow_span]
  refine Ideal.span_le.mpr fun g hg => ?_
  obtain ⟨l, hl, f, hf, rfl⟩ := c.mem_iterPderivSet.mp hg
  exact c.span_topPderivSet_mono hn I hl
    (Ideal.subset_span (c.mem_topPderivSet.mpr ⟨l, rfl, f, hf, rfl⟩))

end RegularCoords

end IsLocalRing
