/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.TransformLogDeriv
import Hironaka.Algebra.Local.ChartCoords
import Hironaka.Algebra.Local.Transform
import Hironaka.Algebra.Local.TransformDerivIter

/-!
# The inclusion `⊆` of Kollár's (88.1) in a chart

[Kol07, Theorem 88]: for a smooth blow-up sequence of order `≥ m` whose centres lie in the
birational transforms of a smooth hypersurface `S`,
`D^s Π⁻¹_*(I, m) = ∑_{j ≤ s} D^{s−j}(−log S_r) Π⁻¹_*(D^j I, m − j)` (88.1). The inclusion `⊇`
follows from [Kol07, Theorem 76]. This module proves the inclusion `⊆` for one blow-up in the
chart of the blow-up of `P = (x₀, …, x_r)` dividing by `x_r`, with `S = V(x_h)`, `h < r`, and
`S₁ = V(y_h)` its transform: for `I ≤ Pᵐ` and `s ≤ m`,

`D'^s π⁻¹_*(I, m) ≤ ∑_{j ≤ s} D'^{s−j}(−log S₁) π⁻¹_*(D^j I, m − j)`
(`iterate_chartD_transformIdeal_le`),

where `D' = chartD` is the derivative ideal of the chart ring for all the transported derivations
`∂'ᵢ` (`Hironaka/Algebra/Local/TransformDeriv.lean`) and `D'(−log S₁) = chartDlog` the logarithmic
one, for `y_h ∂'_h` and the `∂'ᵢ`, `i ≠ h`, which preserve `(y_h)`
(`Hironaka/Algebra/Local/TransformLogDeriv.lean`).

Kollár's proof applies the decomposition [Kol07, (87.2)],
`D^s(I) = D^s(−log S)(I) + D^{s−1}(−log S)(∂I/∂x₁) + ⋯ + (∂^s I/∂x₁^s)`, to the transform and
then commutes `∂/∂y₁` with the transform by (75.1). Here the inclusion is obtained directly from
the generators of the transform, in three steps:

* **Leibniz on generators.** A derivation maps `span G` into `span G + span (δ '' G)`
  (`Derivation.mem_span_sup_span_image`), so `D'^s (span G)` is generated by the `≤ s`-fold chart
  derivatives of the elements of `G` (`chartWords`, `iterate_chartD_span_le`).
* **Moving `∂'_h` to the right.** The commutators `[∂'_h, y_h ∂'_h] = ∂'_h` and `[∂'_h, ∂'_i] = 0`
  give `∂'_h D'(−log S₁)(K) ⊆ D'(−log S₁)(K) + D'(−log S₁)(∂'_h K)` (`span_image_chartDlog_le`),
  hence the same for the iterates `D'^t(−log S₁)` (`span_image_chartDlogpow_le`): a `∂'_h`
  applied after `t` logarithmic derivations is a `∂'_h` applied before them, up to logarithmic
  terms.
* **The normal form.** Every `≤ s`-fold chart derivative of an element of `G` lies in
  `∑_{j ≤ s} D'^{s−j}(−log S₁) (∂'_h^j G)` (`chartWords_subset_iSup`, with `pivotDerivs` the ideal
  of the `j`-fold `∂'_h`-derivatives of `G`), and for the generators `g = π⁻¹_*(f, m)`, `f ∈ I`,
  `∂'_h^j g = π⁻¹_*(∂_h^j f, m − j) ∈ π⁻¹_*(D^j I, m − j)` by (75.1) iterated
  (`Hironaka/Algebra/Local/TransformDerivIter.lean`).

The argument on generators is the library's own. It is needed because the intermediate identity
(88.2) of Kollár's proof, read as a statement about all elements of the ideal `π⁻¹_*(I, m)`, does
not hold in general (`HironakaExamples/Theorem88Counterexample.lean`).

Used for Theorem 88 on schemes (`Hironaka/Resolution/Algebraic/Kol07/Theorem88BlowUp.lean`) and on
manifolds (`Hironaka/Manifold/BlowUp/Transform/LogDerivBlowUp.lean`), and for the logarithmic
derivations of the chart (`Hironaka/Algebra/Local/ChartLogDerivations.lean`).
-/

@[expose] public section

namespace Derivation

variable {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]

/-- Leibniz on generators: a derivation maps `span S` into `span S ⊔ span (δ '' S)`. -/
theorem mem_span_sup_span_image (δ : Derivation k A A) (S : Set A) {z : A}
    (hz : z ∈ Ideal.span S) : δ z ∈ Ideal.span S ⊔ Ideal.span (δ '' S) := by
  induction hz using Submodule.span_induction with
  | mem s hs => exact Ideal.mem_sup_right (Ideal.subset_span ⟨s, hs, rfl⟩)
  | zero => rw [map_zero]; exact zero_mem _
  | add a b _ _ ha hb => rw [map_add]; exact add_mem ha hb
  | smul a b hb hδb =>
    rw [smul_eq_mul, Derivation.leibniz, smul_eq_mul, smul_eq_mul]
    exact add_mem (Ideal.mul_mem_left _ _ hδb) (Ideal.mem_sup_left (Ideal.mul_mem_right _ _ hb))

end Derivation

namespace IsLocalRing.RegularCoords

open IsLocalRing

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ}
  (c : RegularCoords R n) (r : Fin n)

/-! ### `D'` on spans: Leibniz on the generators -/

theorem chartD_mono {J K : Ideal (chartRing c.x r)} (hJK : J ≤ K) : c.chartD r J ≤ c.chartD r K :=
  sup_le_sup hJK (iSup_mono fun _ => Ideal.span_mono (Set.image_mono hJK))

/-- `D'(span W) ⊆ span (W ∪ ⋃ᵢ ∂'ᵢ W)`. -/
theorem chartD_span_le (W : Set (chartRing c.x r)) :
    c.chartD r (Ideal.span W) ≤ Ideal.span (W ∪ ⋃ i, c.chartDerivRing r i '' W) := by
  refine sup_le (Ideal.span_mono Set.subset_union_left) (iSup_le fun i => Ideal.span_le.mpr ?_)
  rintro _ ⟨z, hz, rfl⟩
  have hle : Ideal.span W ⊔ Ideal.span (c.chartDerivRing r i '' W) ≤
      Ideal.span (W ∪ ⋃ i, c.chartDerivRing r i '' W) :=
    sup_le (Ideal.span_mono Set.subset_union_left) (Ideal.span_mono
      (Set.subset_union_of_subset_right
        (Set.subset_iUnion (fun i => c.chartDerivRing r i '' W) i) W))
  exact hle ((c.chartDerivRing r i).mem_span_sup_span_image W hz)

/-- The `≤ s`-fold chart derivatives of the elements of `G`. -/
noncomputable def chartWords (G : Set (chartRing c.x r)) : ℕ → Set (chartRing c.x r)
  | 0 => G
  | s + 1 => chartWords G s ∪ ⋃ i, c.chartDerivRing r i '' chartWords G s

@[simp] theorem chartWords_zero (G : Set (chartRing c.x r)) : c.chartWords r G 0 = G := rfl

theorem chartWords_succ (G : Set (chartRing c.x r)) (s : ℕ) :
    c.chartWords r G (s + 1) =
      c.chartWords r G s ∪ ⋃ i, c.chartDerivRing r i '' c.chartWords r G s := rfl

/-- `D'^s (span G)` is generated by the `≤ s`-fold chart derivatives of the elements of `G`. -/
theorem iterate_chartD_span_le (G : Set (chartRing c.x r)) (s : ℕ) :
    (c.chartD r)^[s] (Ideal.span G) ≤ Ideal.span (c.chartWords r G s) := by
  induction s with
  | zero => exact le_rfl
  | succ s ih =>
    rw [Function.iterate_succ_apply', chartWords_succ]
    exact (c.chartD_mono r ih).trans (c.chartD_span_le r _)

/-! ### `D'(−log S₁)` and sums -/

theorem chartDlog_sup_le (h : Fin n) (A B : Ideal (chartRing c.x r)) :
    c.chartDlog r h (A ⊔ B) ≤ c.chartDlog r h A ⊔ c.chartDlog r h B := by
  refine (c.chartDlog_le_iff r h).mpr
    ⟨sup_le_sup (c.le_chartDlog r h A) (c.le_chartDlog r h B), ?_, ?_⟩
  · intro z hz
    obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp hz
    rw [map_add, mul_add]
    exact add_mem (Ideal.mem_sup_left (c.chartYR_mul_chartDerivRing_mem_chartDlog r h ha))
      (Ideal.mem_sup_right (c.chartYR_mul_chartDerivRing_mem_chartDlog r h hb))
  · intro j hj z hz
    obtain ⟨a, ha, b, hb, rfl⟩ := Submodule.mem_sup.mp hz
    rw [map_add]
    exact add_mem (Ideal.mem_sup_left (c.chartDerivRing_mem_chartDlog r hj ha))
      (Ideal.mem_sup_right (c.chartDerivRing_mem_chartDlog r hj hb))

theorem chartDlogpow_sup_le (h : Fin n) (t : ℕ) (A B : Ideal (chartRing c.x r)) :
    c.chartDlogpow r h t (A ⊔ B) ≤ c.chartDlogpow r h t A ⊔ c.chartDlogpow r h t B := by
  induction t with
  | zero => exact le_rfl
  | succ t ih =>
    rw [chartDlogpow_succ, chartDlogpow_succ, chartDlogpow_succ]
    exact (c.chartDlog_mono r h ih).trans (c.chartDlog_sup_le r h _ _)

theorem chartDlogpow_le_succ (h : Fin n) (t : ℕ) (A : Ideal (chartRing c.x r)) :
    c.chartDlogpow r h t A ≤ c.chartDlogpow r h (t + 1) A := by
  rw [chartDlogpow_succ]
  exact c.le_chartDlog r h _

/-! ### Moving `∂'_h` past the logarithmic derivations -/

/-- The generating set of `D'(−log S₁)(K)`: `K`, `y_h ∂'_h K`, `∂'_j K` for `j ≠ h`. -/
noncomputable def chartDlogGen (h : Fin n) (K : Ideal (chartRing c.x r)) :
    Set (chartRing c.x r) :=
  (K : Set (chartRing c.x r)) ∪ (fun z => chartYR c.x r h * c.chartDerivRing r h z) '' K ∪
    ⋃ (j : Fin n) (_ : j ≠ h), c.chartDerivRing r j '' K

theorem chartDlog_eq_span (h : Fin n) (K : Ideal (chartRing c.x r)) :
    c.chartDlog r h K = Ideal.span (c.chartDlogGen r h K) := by
  simp only [chartDlog, chartDlogGen, Ideal.span_union, Ideal.span_iUnion, Ideal.span_eq]

/-- `[∂'_h, y_h ∂'_h] = ∂'_h` and `[∂'_h, ∂'_j] = 0`: `∂'_h D'(−log S₁)(K) ⊆ D'(−log S₁)(K) +
D'(−log S₁)(∂'_h K)`. -/
theorem span_image_chartDlog_le (h : Fin n) (K : Ideal (chartRing c.x r)) :
    Ideal.span (c.chartDerivRing r h '' (c.chartDlog r h K : Set (chartRing c.x r))) ≤
      c.chartDlog r h K ⊔
        c.chartDlog r h (Ideal.span (c.chartDerivRing r h '' (K : Set (chartRing c.x r)))) := by
  rw [Ideal.span_le]
  rintro _ ⟨z, hz, rfl⟩
  have hz' : z ∈ Ideal.span (c.chartDlogGen r h K) := by
    rw [← c.chartDlog_eq_span r h]
    exact hz
  have hle : Ideal.span (c.chartDlogGen r h K) ⊔
      Ideal.span (c.chartDerivRing r h '' c.chartDlogGen r h K) ≤
        c.chartDlog r h K ⊔
          c.chartDlog r h (Ideal.span (c.chartDerivRing r h '' (K : Set (chartRing c.x r)))) := by
    refine sup_le ((le_of_eq (c.chartDlog_eq_span r h K).symm).trans le_sup_left)
      (Ideal.span_le.mpr ?_)
    rintro _ ⟨g, hg, rfl⟩
    rcases hg with (hg | ⟨k, hk, rfl⟩) | hg
    · -- `∂'_h k ∈ ∂'_h K`
      exact Ideal.mem_sup_right (c.le_chartDlog r h _ (Ideal.subset_span ⟨g, hg, rfl⟩))
    · -- `∂'_h (y_h ∂'_h k) = y_h ∂'_h (∂'_h k) + ∂'_h k`
      rw [Derivation.leibniz, smul_eq_mul, smul_eq_mul, c.chartDerivRing_chartYR r, ite_eq_left rfl,
        mul_one]
      refine Ideal.mem_sup_right (add_mem (c.chartYR_mul_chartDerivRing_mem_chartDlog r h ?_)
        (c.le_chartDlog r h _ ?_)) <;> exact Ideal.subset_span ⟨k, hk, rfl⟩
    · -- `∂'_h (∂'_j k) = ∂'_j (∂'_h k)` for `j ≠ h`
      simp only [Set.mem_iUnion] at hg
      obtain ⟨j, hj, k, hk, rfl⟩ := hg
      rw [c.chartDerivRing_comm r h j]
      exact Ideal.mem_sup_right
        (c.chartDerivRing_mem_chartDlog r hj (Ideal.subset_span ⟨k, hk, rfl⟩))
  exact hle ((c.chartDerivRing r h).mem_span_sup_span_image _ hz')

/-- `∂'_h D'^t(−log S₁)(K) ⊆ D'^t(−log S₁)(K) + D'^t(−log S₁)(∂'_h K)`: a `∂'_h` applied after `t`
logarithmic derivations is a `∂'_h` applied before them, up to logarithmic terms. -/
theorem span_image_chartDlogpow_le (h : Fin n) (t : ℕ) (K : Ideal (chartRing c.x r)) :
    Ideal.span (c.chartDerivRing r h '' (c.chartDlogpow r h t K : Set (chartRing c.x r))) ≤
      c.chartDlogpow r h t K ⊔
        c.chartDlogpow r h t
          (Ideal.span (c.chartDerivRing r h '' (K : Set (chartRing c.x r)))) := by
  induction t with
  | zero => exact le_sup_right
  | succ t ih =>
    simp only [chartDlogpow_succ]
    refine (c.span_image_chartDlog_le r h _).trans (sup_le le_sup_left ?_)
    exact ((c.chartDlog_mono r h ih).trans (c.chartDlog_sup_le r h _ _)).trans
      (sup_le le_sup_left le_sup_right)

/-! ### The normal form -/

/-- The ideal generated by the `j`-fold `∂'_h`-derivatives of the elements of `G`. -/
noncomputable def pivotDerivs (h : Fin n) (G : Set (chartRing c.x r)) (j : ℕ) :
    Ideal (chartRing c.x r) :=
  Ideal.span ((⇑(c.chartDerivRing r h))^[j] '' G)

theorem span_image_pivotDerivs_le (h : Fin n) (G : Set (chartRing c.x r)) (j : ℕ) :
    Ideal.span (c.chartDerivRing r h '' (c.pivotDerivs r h G j : Set (chartRing c.x r))) ≤
      c.pivotDerivs r h G j ⊔ c.pivotDerivs r h G (j + 1) := by
  rw [Ideal.span_le]
  rintro _ ⟨z, hz, rfl⟩
  have hle : c.pivotDerivs r h G j ⊔
      Ideal.span (c.chartDerivRing r h '' ((⇑(c.chartDerivRing r h))^[j] '' G)) ≤
        c.pivotDerivs r h G j ⊔ c.pivotDerivs r h G (j + 1) := by
    refine sup_le le_sup_left (le_sup_of_le_right (Ideal.span_mono ?_))
    rw [← Set.image_comp]
    rintro _ ⟨g, hg, rfl⟩
    exact ⟨g, hg, Function.iterate_succ_apply' _ _ _⟩
  exact hle ((c.chartDerivRing r h).mem_span_sup_span_image _ hz)

/-- The raise of the level: `∑_{j ≤ s} D'^{s−j}(−log) A_j ⊆ ∑_{j ≤ s+1} D'^{s+1−j}(−log) A_j`. -/
theorem iSup_chartDlogpow_le_succ (h : Fin n) (A : ℕ → Ideal (chartRing c.x r)) (s : ℕ) :
    (⨆ j ≤ s, c.chartDlogpow r h (s - j) (A j)) ≤
      ⨆ j ≤ s + 1, c.chartDlogpow r h (s + 1 - j) (A j) := by
  refine iSup₂_mono' fun j hj => ⟨j, hj.trans (Nat.le_succ s), ?_⟩
  rw [show s + 1 - j = s - j + 1 by omega]
  exact c.chartDlogpow_le_succ r h _ _

/-- **The normal form**: every `≤ s`-fold chart derivative of an element of `G` lies in
`∑_{j ≤ s} D'^{s−j}(−log S₁) (∂'_h^j G)`. -/
theorem chartWords_subset_iSup (h : Fin n) (G : Set (chartRing c.x r)) (s : ℕ) :
    ∀ z ∈ c.chartWords r G s,
      z ∈ ⨆ j ≤ s, c.chartDlogpow r h (s - j) (c.pivotDerivs r h G j) := by
  induction s with
  | zero =>
    intro z hz
    have hmem : z ∈ c.pivotDerivs r h G 0 := Ideal.subset_span ⟨z, hz, rfl⟩
    have hle : c.pivotDerivs r h G 0 ≤
        ⨆ j ≤ 0, c.chartDlogpow r h (0 - j) (c.pivotDerivs r h G j) :=
      le_iSup₂_of_le 0 le_rfl le_rfl
    exact hle hmem
  | succ s ih =>
    intro z hz
    rcases hz with hz | hz
    · exact c.iSup_chartDlogpow_le_succ r h _ s (ih z hz)
    simp only [Set.mem_iUnion] at hz
    obtain ⟨i, w, hw, rfl⟩ := hz
    -- `w` lies in the sum of the `D'^{s−j}(−log) A_j`; Leibniz on their union
    have hsup : (⨆ j ≤ s, c.chartDlogpow r h (s - j) (c.pivotDerivs r h G j)) =
        Ideal.span (⋃ j, ⋃ (_ : j ≤ s),
          (c.chartDlogpow r h (s - j) (c.pivotDerivs r h G j) : Set (chartRing c.x r))) := by
      simp only [Ideal.span_iUnion, Ideal.span_eq]
    have hw' : w ∈ Ideal.span (⋃ j, ⋃ (_ : j ≤ s),
        (c.chartDlogpow r h (s - j) (c.pivotDerivs r h G j) : Set (chartRing c.x r))) :=
      hsup ▸ ih w hw
    refine (sup_le (hsup.symm.le.trans (c.iSup_chartDlogpow_le_succ r h _ s)) ?_)
      ((c.chartDerivRing r i).mem_span_sup_span_image _ hw')
    rw [Set.image_iUnion₂]
    simp only [Ideal.span_iUnion]
    refine iSup₂_le fun j hj => ?_
    by_cases hi : i = h
    · -- the pivot derivation: move it to the right
      rw [hi]
      refine (c.span_image_chartDlogpow_le r h _ _).trans (sup_le ?_ ?_)
      · refine le_iSup₂_of_le j (hj.trans (Nat.le_succ s)) ?_
        rw [show s + 1 - j = s - j + 1 by omega]
        exact c.chartDlogpow_le_succ r h _ _
      · refine ((c.chartDlogpow_mono r h _ (c.span_image_pivotDerivs_le r h G j)).trans
          (c.chartDlogpow_sup_le r h _ _ _)).trans (sup_le ?_ ?_)
        · refine le_iSup₂_of_le j (hj.trans (Nat.le_succ s)) ?_
          rw [show s + 1 - j = s - j + 1 by omega]
          exact c.chartDlogpow_le_succ r h _ _
        · refine le_iSup₂_of_le (j + 1) (Nat.succ_le_succ hj) ?_
          rw [show s + 1 - (j + 1) = s - j by omega]
    · -- a logarithmic derivation
      refine le_iSup₂_of_le j (hj.trans (Nat.le_succ s)) ?_
      rw [show s + 1 - j = s - j + 1 by omega, chartDlogpow_succ, Ideal.span_le]
      rintro _ ⟨z, hz, rfl⟩
      exact c.chartDerivRing_mem_chartDlog r hi hz

/-! ### The inclusion `⊆` of (88.1) -/

/-- **The inclusion `⊆` of [Kol07, (88.1)] for one blow-up in the chart** (the proof of
[Kol07, Theorem 88]): in the chart dividing by `x_r`, for the hypersurface coordinate `x_h`,
`h < r`, `I ≤ Pᵐ` and `s ≤ m`,
`D'^s π⁻¹_*(I, m) ≤ ∑_{j ≤ s} D'^{s−j}(−log (y_h)) π⁻¹_*(D^j I, m − j)`. -/
theorem iterate_chartD_transformIdeal_le {h : Fin n} (hh : h < r) {I : Ideal R} {m : ℕ}
    (hI : I ≤ chartCenter c.x r ^ m) {s : ℕ} (hs : s ≤ m) :
    (c.chartD r)^[s] (transformIdeal c.x r I m) ≤
      ⨆ j ≤ s, c.chartDlogpow r h (s - j) (transformIdeal c.x r (c.Dpow j I) (m - j)) := by
  rw [transformIdeal_eq_span_range_transformElem c.x r hI]
  refine (c.iterate_chartD_span_le r _ s).trans
    ((Ideal.span_le.mpr fun z hz => c.chartWords_subset_iSup r h _ s z hz).trans ?_)
  refine iSup₂_mono fun j hj => c.chartDlogpow_mono r h _ ?_
  rw [pivotDerivs, Ideal.span_le]
  rintro _ ⟨_, ⟨⟨f, hf⟩, rfl⟩, rfl⟩
  exact c.iterate_chartDerivRing_transformElem_mem r hh hI (hj.trans hs) hf

end IsLocalRing.RegularCoords
