/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.Chart
public import Hironaka.Algebra.Local.Derivative
public import Hironaka.Algebra.Local.BirationalTransform
import Hironaka.Algebra.Local.Transform

/-!
# Birational transform of derivatives

Let `R` be a regular local ring containing `ℚ` with coordinates `x₀, …, x_{n−1}` (`RegularCoords`),
`P = (x₀, …, x_r)` the centre of the blow-up, `R' = R[xᵢ/x_r : i < r] ⊆ R[1/x_r]` the chart ring
dividing by `x_r`, with the coordinates `yᵢ = xᵢ/x_r` (`i < r`), `yⱼ = xⱼ` (`j ≥ r`), and `∂'ⱼ` the
derivations of `R'` transported from the partial derivatives `∂ⱼ` of `R` (`chartDerivRing`,
`Hironaka/Algebra/Local/Chart.lean`). For `f ∈ Pᵐ` the transform `π⁻¹_*(f, m) = f / x_rᵐ` lies in
`R'` (`transformElem`, `Hironaka/Algebra/Local/BirationalTransform.lean`). This module computes the
derivatives of transforms, [Kol07, 75]:

* (75.1) `π⁻¹_*(∂ⱼ f, m) = ∂'ⱼ π⁻¹_*(f, m+1)` for `j < r` (`transform_pderiv_lt`);
* (75.2) `π⁻¹_*(∂ⱼ f, m) = y_r ∂'ⱼ π⁻¹_*(f, m+1)` for `j > r` (`transform_pderiv_gt`);
* (75.3) `π⁻¹_*(∂_r f, m) = y_r ∂'_r π⁻¹_*(f, m+1) − ∑_{i<r} yᵢ ∂'ᵢ π⁻¹_*(f, m+1)
  + (m+1) π⁻¹_*(f, m+1)` (`transform_pderiv_eq`);
* (75.4) `π⁻¹_*(xⱼ ∂ⱼ f, m) = y_r yⱼ ∂'ⱼ π⁻¹_*(f, m+1)` for `j < r` (`transform_x_pderiv`).

All four follow from one computation in `R[1/x_r]`: with `u = 1/x_r`,
`∂ⱼ(f uᵐ) = (∂ⱼ f) uᵐ − m [j = r] f u^{m+1}` (`awayPderiv_algebraMap_mul_invX_pow`).

Kollár observes that the right-hand sides lie in the derivative ideal of `π⁻¹_*(f, m)`, which is
the case of one blow-up and `j = 1` of [Kol07, Theorem 76]: for an ideal `I ≤ Pᵐ⁺¹`,
`π⁻¹_*(D(I), m) ≤ D'(π⁻¹_*(I, m+1))` (`transform_D_le_chartD`), where `D'` is the derivative ideal
of the chart ring with respect to the `∂'ⱼ` (`chartD`); the same holds with the derivative ideal
for all `ℚ`-derivations of `R'` (`transform_D_le_Dimg_transform`). The proof uses that `D(I)` is
generated by the elements of `I` and their partial derivatives, and that transforms are additive
and `R`-linear (`transformElem_add`, `transformElem_smul`), with `π⁻¹_*(f, m) = x_r π⁻¹_*(f, m+1)`
(`transformElem_succ`).

The same computation in the form of [Wlo05, Lemma 2.6.3] (and, with the coordinates of the centre
indexed last, [BM08, Lemma 3.1]): the derivations `x_r ∂ⱼ` of `R[1/x_r]` preserve the chart ring
(`smul_awayPderiv_mem`), with `x_r ∂ⱼ = ∂'ⱼ` for `j < r`, `x_r ∂_r = y_r ∂'_r − ∑_{i<r} yᵢ ∂'ᵢ`, and
`x_r ∂ⱼ = y_r ∂'ⱼ` for `j > r` (`smul_awayPderiv_of_lt`, `smul_awayPderiv_self`,
`smul_awayPderiv_of_gt`).

Conventions: indices are zero-based, so Kollár's `x₁, …, x_r` are `x₀, …, x_r` here, and the
marks are shifted by one: the statements are for `f ∈ Pᵐ⁺¹`, with `π⁻¹_*(∂ⱼ f, m)` defined because
`∂ⱼ(Pᵐ⁺¹) ≤ Pᵐ` (`pderiv_mem_chartCenter_pow`).

The inclusion `transform_D_le_chartD` is the local input of Theorem 76 for one blowing-up on
manifolds (`Hironaka/Manifold/BlowUp/Transform/DerivTransform.lean`) and of the worked example
`HironakaExamples/DerivativeSequence.lean`; the logarithmic version is
`Hironaka/Algebra/Local/TransformLogDeriv.lean`, the iterated version on a generator
`Hironaka/Algebra/Local/TransformDerivIter.lean`, and the derivations `x_r ∂ⱼ` are lifted to the
blow-up in `Hironaka/Algebra/Local/BlowUpLift.lean`.
-/

@[expose] public section

namespace IsLocalRing

open IsLocalRing

namespace RegularCoords

variable {R : Type*} [CommRing R] [IsRegularLocalRing R] [Algebra ℚ R] {n : ℕ}
  (c : RegularCoords R n) (r : Fin n)

/-! ### Derivatives lower the power of the centre -/

/-- `∂ⱼ(Pᵐ) ≤ Pᵐ⁻¹`: the partial derivative of an element of `Pᵐ` lies in `Pᵐ⁻¹`, so
`π⁻¹_*(∂ⱼ f, m − 1)` is defined for `f ∈ Pᵐ`. -/
theorem pderiv_mem_chartCenter_pow {m : ℕ} {f : R} (hf : f ∈ chartCenter c.x r ^ m) (j : Fin n) :
    c.pderiv j f ∈ chartCenter c.x r ^ (m - 1) := by
  rcases m with _ | m
  · simp
  · have h := (c.D_pow_le (chartCenter c.x r) (Nat.succ_pos m)) (c.pderiv_mem_D hf j)
    simp only [Nat.succ_sub_one] at h ⊢
    exact Ideal.mul_le_right h

/-- For ideals: `I ≤ Pᵐ⁺¹` gives `D(I) ≤ Pᵐ`. -/
theorem D_le_chartCenter_pow {I : Ideal R} {m : ℕ} (hI : I ≤ chartCenter c.x r ^ (m + 1)) :
    c.D I ≤ chartCenter c.x r ^ m :=
  c.D_le_iff.mpr ⟨hI.trans (Ideal.pow_le_pow_right (Nat.le_succ m)), fun j f hf => by
    have := c.pderiv_mem_chartCenter_pow r (hI hf) j
    rwa [Nat.add_sub_cancel] at this⟩

/-! ### The computation in `R[1/x_r]` -/

theorem mk_eq_algebraMap_mul_invX_pow (f : R) (m : ℕ) :
    Localization.mk f ⟨c.x r ^ m, Submonoid.pow_mem _ (Submonoid.mem_powers _) m⟩ =
      algebraMap R (Localization.Away (c.x r)) f * invX c.x r ^ m := by
  rw [← Localization.mk_one_eq_algebraMap, invX, Localization.mk_pow, Localization.mk_mul]
  congr 1
  · simp
  · exact Subtype.ext (by simp)

theorem algebraMap_mul_invX_pow_succ (m : ℕ) :
    algebraMap R (Localization.Away (c.x r)) (c.x r) * invX c.x r ^ (m + 1) = invX c.x r ^ m := by
  rw [pow_succ, ← mul_assoc, mul_comm (algebraMap R _ (c.x r)), mul_assoc, algebraMap_mul_invX,
    mul_one]

theorem awayPderiv_invX_pow (j : Fin n) (m : ℕ) :
    c.awayPderiv r j (invX c.x r ^ m) =
      -((m : ℕ) • (invX c.x r ^ (m + 1) * if j = r then 1 else 0)) := by
  rw [Derivation.leibniz_pow, awayPderiv_invX]
  rcases m with _ | m
  · simp
  · rw [Nat.add_sub_cancel, smul_eq_mul, nsmul_eq_mul, nsmul_eq_mul]
    ring

/-- The chain-rule computation behind [Kol07, 75]: in `R[1/x_r]`,
`∂ⱼ(f uᵐ) = (∂ⱼ f) uᵐ − m [j = r] f u^{m+1}` with `u = 1/x_r`. -/
theorem awayPderiv_algebraMap_mul_invX_pow (j : Fin n) (f : R) (m : ℕ) :
    c.awayPderiv r j (algebraMap R (Localization.Away (c.x r)) f * invX c.x r ^ m) =
      algebraMap R (Localization.Away (c.x r)) (c.pderiv j f) * invX c.x r ^ m -
        (m : ℕ) • (algebraMap R (Localization.Away (c.x r)) f * invX c.x r ^ (m + 1) *
          if j = r then 1 else 0) := by
  rw [Derivation.leibniz, awayPderiv_invX_pow, awayPderiv_algebraMap, smul_eq_mul, smul_eq_mul,
    nsmul_eq_mul, nsmul_eq_mul]
  ring

theorem coe_transformElem_eq (f : R) {m : ℕ} (hf : f ∈ chartCenter c.x r ^ m) :
    (transformElem c.x r f hf : Localization.Away (c.x r)) =
      algebraMap R (Localization.Away (c.x r)) f * invX c.x r ^ m := by
  rw [coe_transformElem, mk_eq_algebraMap_mul_invX_pow]

/-! ### Kollár's formulas (75.1)–(75.4) -/

/-- [Kol07, (75.1)] (also [Wlo05, Lemma 2.6.3]): for `j < r` and `f ∈ Pᵐ⁺¹`,
`π⁻¹_*(∂ⱼ f, m) = ∂'ⱼ π⁻¹_*(f, m+1)`. -/
theorem transform_pderiv_lt {j : Fin n} (hj : j < r) {m : ℕ} {f : R}
    (hf : f ∈ chartCenter c.x r ^ (m + 1)) :
    transformElem (m := m) c.x r (c.pderiv j f)
        (by simpa using c.pderiv_mem_chartCenter_pow r hf j) =
      c.chartDerivRing r j (transformElem c.x r f hf) := by
  refine Subtype.ext ?_
  rw [coe_chartDerivRing, coe_transformElem_eq, coe_transformElem_eq, chartDeriv_of_lt _ _ hj,
    Derivation.smul_apply, awayPderiv_algebraMap_mul_invX_pow, if_neg hj.ne, mul_zero, nsmul_zero,
    sub_zero, smul_eq_mul, mul_left_comm, algebraMap_mul_invX_pow_succ]

/-- [Kol07, (75.2)]: for `j > r` and `f ∈ Pᵐ⁺¹`, `π⁻¹_*(∂ⱼ f, m) = y_r ∂'ⱼ π⁻¹_*(f, m+1)`. -/
theorem transform_pderiv_gt {j : Fin n} (hj : r < j) {m : ℕ} {f : R}
    (hf : f ∈ chartCenter c.x r ^ (m + 1)) :
    transformElem (m := m) c.x r (c.pderiv j f)
        (by simpa using c.pderiv_mem_chartCenter_pow r hf j) =
      chartYR c.x r r * c.chartDerivRing r j (transformElem c.x r f hf) := by
  refine Subtype.ext ?_
  rw [Subalgebra.coe_mul, coe_chartDerivRing, coe_transformElem_eq, coe_transformElem_eq,
    chartDeriv_of_gt _ _ hj, coe_chartYROf, chartYOf_self, awayPderiv_algebraMap_mul_invX_pow,
    if_neg hj.ne', mul_zero, nsmul_zero, sub_zero, mul_left_comm, algebraMap_mul_invX_pow_succ]

/-- [Kol07, (75.3)], by the chain rule (also [Wlo05, Lemma 2.6.3] and [BM08, Lemma 3.1]): for
`f ∈ Pᵐ⁺¹`,
`π⁻¹_*(∂_r f, m) = y_r ∂'_r π⁻¹_*(f, m+1) − ∑_{i<r} yᵢ ∂'ᵢ π⁻¹_*(f, m+1) + (m+1)·π⁻¹_*(f, m+1)`,
the last term being `(m+1, −1)·π⁻¹_*(f, m+1)` in Kollár's notation: multiply by `m+1` and lower
the mark by one. -/
theorem transform_pderiv_eq {m : ℕ} {f : R} (hf : f ∈ chartCenter c.x r ^ (m + 1)) :
    transformElem (m := m) c.x r (c.pderiv r f)
        (by simpa using c.pderiv_mem_chartCenter_pow r hf r) =
      chartYR c.x r r * c.chartDerivRing r r (transformElem c.x r f hf) -
        ∑ i ∈ Finset.univ.filter (· < r),
          chartYR c.x r i * c.chartDerivRing r i (transformElem c.x r f hf) +
        (m + 1) • transformElem c.x r f hf := by
  refine Subtype.ext ?_
  have hx1 := c.algebraMap_mul_invX_pow_succ r m
  have hx2 := c.algebraMap_mul_invX_pow_succ r (m + 1)
  -- the two sums agree termwise
  have hsum : ∀ i ∈ Finset.univ.filter (· < r),
      (((chartYR c.x r i * c.chartDerivRing r i (transformElem c.x r f hf) : chartRing c.x r)) :
        Localization.Away (c.x r)) =
        algebraMap R _ (c.x r) * (chartY c.x r i *
          (algebraMap R _ (c.pderiv i f) * invX c.x r ^ (m + 1))) := by
    intro i hi
    have hi' := (Finset.mem_filter.mp hi).2
    rw [Subalgebra.coe_mul, coe_chartDerivRing, coe_transformElem_eq, chartDeriv_of_lt _ _ hi',
      Derivation.smul_apply, smul_eq_mul, coe_chartYROf, awayPderiv_algebraMap_mul_invX_pow,
      if_neg hi'.ne, mul_zero, nsmul_zero, sub_zero]
    ring
  have hinner : ∀ i ∈ Finset.univ.filter (· < r),
      (chartY c.x r i • c.awayPderiv r i) (algebraMap R _ f * invX c.x r ^ (m + 1)) =
        chartY c.x r i * (algebraMap R _ (c.pderiv i f) * invX c.x r ^ (m + 1)) := by
    intro i hi
    have hi' := (Finset.mem_filter.mp hi).2
    rw [Derivation.smul_apply, smul_eq_mul, awayPderiv_algebraMap_mul_invX_pow, if_neg hi'.ne,
      mul_zero, nsmul_zero, sub_zero]
  rw [Subalgebra.coe_add, Subalgebra.coe_sub, Subalgebra.coe_mul, AddSubmonoidClass.coe_finsetSum,
    Finset.sum_congr rfl hsum, ← Finset.mul_sum, AddSubmonoidClass.coe_nsmul, coe_chartDerivRing,
    coe_transformElem_eq, coe_transformElem_eq, chartDeriv_self, Derivation.add_apply,
    Derivation.finset_sum_apply, Finset.sum_congr rfl hinner, coe_chartYROf, chartYOf_self,
    awayPderiv_algebraMap_mul_invX_pow, if_pos rfl, mul_one, nsmul_eq_mul, nsmul_eq_mul]
  linear_combination (-(algebraMap R (Localization.Away (c.x r)) (c.pderiv r f))) * hx1 +
    (((m + 1 : ℕ) : Localization.Away (c.x r)) * algebraMap R (Localization.Away (c.x r)) f) * hx2

/-- [Kol07, (75.4)]: for `j < r` and `f ∈ Pᵐ⁺¹`, `π⁻¹_*(xⱼ ∂ⱼ f, m) = y_r yⱼ ∂'ⱼ π⁻¹_*(f, m+1)`. -/
theorem transform_x_pderiv {j : Fin n} (hj : j < r) {m : ℕ} {f : R}
    (hf : f ∈ chartCenter c.x r ^ (m + 1)) :
    transformElem (m := m) c.x r (c.x j * c.pderiv j f)
        (Ideal.mul_mem_left _ _ (by simpa using c.pderiv_mem_chartCenter_pow r hf j)) =
      chartYR c.x r r * chartYR c.x r j * c.chartDerivRing r j (transformElem c.x r f hf) := by
  rw [← transform_pderiv_lt c r hj hf]
  refine Subtype.ext ?_
  rw [Subalgebra.coe_mul, Subalgebra.coe_mul, coe_transformElem_eq, coe_transformElem_eq,
    coe_chartYROf, coe_chartYROf, chartYOf_self, chartYOf_of_lt _ _ _ hj,
    mk_eq_algebraMap_mul_invX, map_mul]
  have hx := algebraMap_mul_invX c.x r
  linear_combination (-(algebraMap R (Localization.Away (c.x r)) (c.x j) *
    algebraMap R (Localization.Away (c.x r)) (c.pderiv j f) * invX c.x r ^ m)) * hx

/-! ### The derivative ideal of a transform: `π⁻¹_*(D(I), m) ≤ D'(π⁻¹_*(I, m+1))` -/

/-- The derivative ideal of an ideal `J` of the chart ring with respect to the transported
derivations `∂'ⱼ`: `J + ∑ⱼ ∂'ⱼ(J) R'`. -/
noncomputable def chartD (J : Ideal (chartRing c.x r)) : Ideal (chartRing c.x r) :=
  J ⊔ ⨆ j : Fin n, Ideal.span (c.chartDerivRing r j '' J)

theorem le_chartD (J : Ideal (chartRing c.x r)) : J ≤ c.chartD r J := le_sup_left

theorem chartDerivRing_mem_chartD {J : Ideal (chartRing c.x r)} {z : chartRing c.x r} (hz : z ∈ J)
    (j : Fin n) : c.chartDerivRing r j z ∈ c.chartD r J :=
  Ideal.mem_sup_right (Ideal.mem_iSup_of_mem j (Ideal.subset_span ⟨z, hz, rfl⟩))

/-- Transforms are additive and `R`-linear, by their uniqueness: `π⁻¹_*(f, m)` is the only element
`g` of the chart ring with `x_rᵐ g = f` (`eq_transformElem_of_pow_mul_eq`). -/
theorem transformElem_add {m : ℕ} {f g : R} (hf : f ∈ chartCenter c.x r ^ m)
    (hg : g ∈ chartCenter c.x r ^ m) (hfg : f + g ∈ chartCenter c.x r ^ m) :
    transformElem c.x r (f + g) hfg = transformElem c.x r f hf + transformElem c.x r g hg := by
  symm
  apply eq_transformElem_of_pow_mul_eq
  rw [mul_add, algebraMap_pow_mul_transformElem, algebraMap_pow_mul_transformElem, map_add]

theorem transformElem_smul {m : ℕ} (a : R) {g : R} (hg : g ∈ chartCenter c.x r ^ m)
    (hag : a • g ∈ chartCenter c.x r ^ m) :
    transformElem c.x r (a • g) hag = algebraMap R _ a * transformElem c.x r g hg := by
  symm
  apply eq_transformElem_of_pow_mul_eq
  rw [mul_left_comm, algebraMap_pow_mul_transformElem, ← map_mul, smul_eq_mul]

theorem transformElem_zero {m : ℕ} (h0 : (0 : R) ∈ chartCenter c.x r ^ m) :
    transformElem c.x r 0 h0 = 0 := by
  symm
  apply eq_transformElem_of_pow_mul_eq
  rw [mul_zero, map_zero]

/-- Lowering the mark multiplies by `x_r`: `π⁻¹_*(f, m) = x_r · π⁻¹_*(f, m+1)`. -/
theorem transformElem_succ {m : ℕ} {f : R} (hf : f ∈ chartCenter c.x r ^ (m + 1))
    (hf' : f ∈ chartCenter c.x r ^ m) :
    transformElem c.x r f hf' = algebraMap R _ (c.x r) * transformElem c.x r f hf := by
  symm
  apply eq_transformElem_of_pow_mul_eq
  rw [← mul_assoc, ← pow_succ, algebraMap_pow_mul_transformElem]

/-- **The derivative ideal of a transform** ([Kol07, 75]: "the right-hand sides of these
equations are in `D(π⁻¹_*(f, m))`"; [Wlo05, Lemma 2.6.3]), the case of one blow-up and `j = 1` of
[Kol07, Theorem 76]: for `I ≤ Pᵐ⁺¹`, `π⁻¹_*(D(I), m) ≤ D'(π⁻¹_*(I, m+1))`, with `D'` the derivative
ideal of the chart ring with respect to the `∂'ⱼ`. -/
theorem transform_D_le_chartD {I : Ideal R} {m : ℕ} (hI : I ≤ chartCenter c.x r ^ (m + 1)) :
    transformIdeal c.x r (c.D I) m ≤ c.chartD r (transformIdeal c.x r I (m + 1)) := by
  classical
  have hDI : c.D I ≤ chartCenter c.x r ^ m := c.D_le_chartCenter_pow r hI
  have hDspan := c.D_span (I : Set R)
  rw [Ideal.span_eq] at hDspan
  have hT : ∀ (f : R) (hf : f ∈ I),
      transformElem c.x r f (hI hf) ∈ transformIdeal c.x r I (m + 1) := by
    intro f hf
    rw [transformIdeal_eq_span_range_transformElem _ _ hI]
    exact Ideal.subset_span ⟨⟨f, hf⟩, rfl⟩
  have hgen : ∀ (f : R) (hf : f ∈ I) (j : Fin n),
      transformElem (m := m) c.x r (c.pderiv j f)
          (by simpa using c.pderiv_mem_chartCenter_pow r (hI hf) j) ∈
        c.chartD r (transformIdeal c.x r I (m + 1)) := by
    intro f hf j
    rcases lt_trichotomy j r with hj | hj | hj
    · rw [c.transform_pderiv_lt r hj (hI hf)]
      exact c.chartDerivRing_mem_chartD r (hT f hf) j
    · subst hj
      rw [c.transform_pderiv_eq j (hI hf)]
      refine Ideal.add_mem _ (Ideal.sub_mem _ ?_ ?_) ?_
      · exact Ideal.mul_mem_left _ _ (c.chartDerivRing_mem_chartD j (hT f hf) j)
      · exact Ideal.sum_mem _ fun i _ =>
          Ideal.mul_mem_left _ _ (c.chartDerivRing_mem_chartD j (hT f hf) i)
      · exact nsmul_mem (c.le_chartD j _ (hT f hf)) _
    · rw [c.transform_pderiv_gt r hj (hI hf)]
      exact Ideal.mul_mem_left _ _ (c.chartDerivRing_mem_chartD r (hT f hf) j)
  suffices key : ∀ g, g ∈ Ideal.span ((I : Set R) ∪ ⋃ j, c.pderiv j '' (I : Set R)) →
      ∀ hg : g ∈ chartCenter c.x r ^ m,
        transformElem c.x r g hg ∈ c.chartD r (transformIdeal c.x r I (m + 1)) by
    rw [transformIdeal_eq_span_range_transformElem _ _ hDI]
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨⟨g, hg⟩, rfl⟩
    exact key g (hDspan ▸ hg) (hDI hg)
  intro g hg
  induction hg using Submodule.span_induction with
  | mem g hmem =>
    intro hgP
    rcases hmem with hgI | hgD
    · rw [c.transformElem_succ r (hI hgI) hgP]
      exact Ideal.mul_mem_left _ _ (c.le_chartD r _ (hT g hgI))
    · obtain ⟨_, ⟨j, rfl⟩, f, hfI, rfl⟩ := hgD
      exact hgen f hfI j
  | zero =>
    intro h0
    rw [c.transformElem_zero r h0]
    exact Ideal.zero_mem _
  | add g₁ g₂ hg₁ hg₂ ih₁ ih₂ =>
    intro hsum
    have h₁ : g₁ ∈ chartCenter c.x r ^ m := hDI (hDspan ▸ hg₁)
    have h₂ : g₂ ∈ chartCenter c.x r ^ m := hDI (hDspan ▸ hg₂)
    rw [c.transformElem_add r h₁ h₂ hsum]
    exact Ideal.add_mem _ (ih₁ h₁) (ih₂ h₂)
  | smul a g hg ih =>
    intro hag
    have h₁ : g ∈ chartCenter c.x r ^ m := hDI (hDspan ▸ hg)
    rw [c.transformElem_smul r a h₁ hag]
    exact Ideal.mul_mem_left _ _ (ih h₁)

/-- `∂'_r y_r = 1`, so the identity `g = ∂(y g) − y ∂g` of [Kol07, Definition 73] puts `J` inside
`Dimg J`, the derivative ideal of the chart ring for all `ℚ`-derivations. -/
theorem le_Dimg_chartRing (J : Ideal (chartRing c.x r)) : J ≤ Dimg J := by
  intro z hz
  have h1 : c.chartDerivRing r r (chartYR c.x r r * z) =
      z + chartYR c.x r r * c.chartDerivRing r r z := by
    refine Subtype.ext ?_
    rw [coe_chartDerivRing, Subalgebra.coe_add, Subalgebra.coe_mul, Subalgebra.coe_mul,
      coe_chartDerivRing, Derivation.leibniz, smul_eq_mul, smul_eq_mul, coe_chartYROf,
      chartDeriv_chartY, if_pos rfl, mul_one, add_comm]
  have h2 : z = c.chartDerivRing r r (chartYR c.x r r * z) -
      chartYR c.x r r * c.chartDerivRing r r z := by rw [h1]; ring
  rw [h2]
  unfold Dimg
  refine Ideal.mem_iSup_of_mem (c.chartDerivRing r r) (Ideal.sub_mem _ ?_ ?_)
  · exact Ideal.subset_span ⟨_, Ideal.mul_mem_left _ _ hz, rfl⟩
  · exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨z, hz, rfl⟩)

theorem chartD_le_Dimg (J : Ideal (chartRing c.x r)) : c.chartD r J ≤ Dimg J := by
  have h1 := c.le_Dimg_chartRing r J
  unfold chartD Dimg at h1 ⊢
  exact sup_le h1 (iSup_le fun j => le_iSup
    (fun δ : Derivation ℚ (chartRing c.x r) (chartRing c.x r) => Ideal.span (δ '' J))
    (c.chartDerivRing r j))

/-- The inclusion `transform_D_le_chartD` in the coordinate-free form of [Kol07, (73.1)]:
`π⁻¹_*(D(I), m) ≤ D(π⁻¹_*(I, m+1))` with `D` the derivative ideal for all `ℚ`-derivations of the
chart ring. -/
theorem transform_D_le_Dimg_transform {I : Ideal R} {m : ℕ}
    (hI : I ≤ chartCenter c.x r ^ (m + 1)) :
    transformIdeal c.x r (c.D I) m ≤ Dimg (transformIdeal c.x r I (m + 1)) :=
  (c.transform_D_le_chartD r hI).trans (c.chartD_le_Dimg r _)

/-! ### The derivations `x_r ∂ⱼ` of the chart ring ([Wlo05, Lemma 2.6.3], [BM08, Lemma 3.1]) -/

/-- `x_r ∂ⱼ = ∂'ⱼ` for `j < r` ([Wlo05, Lemma 2.6.3]). -/
theorem smul_awayPderiv_of_lt {j : Fin n} (hj : j < r) :
    algebraMap R (Localization.Away (c.x r)) (c.x r) • c.awayPderiv r j = c.chartDeriv r j :=
  (chartDeriv_of_lt c r hj).symm

/-- `x_r ∂ⱼ = y_r ∂'ⱼ` for `j > r`, that is, `∂ⱼ = ∂'ⱼ` on the coordinates outside the centre
([Wlo05, Lemma 2.6.3]; the first line of [BM08, Lemma 3.1]). -/
theorem smul_awayPderiv_of_gt {j : Fin n} (hj : r < j) :
    algebraMap R (Localization.Away (c.x r)) (c.x r) • c.awayPderiv r j =
      chartY c.x r r • c.chartDeriv r j := by
  rw [chartDeriv_of_gt c r hj, chartY, chartYOf_self]

/-- `x_r ∂_r = y_r ∂'_r − ∑_{i<r} yᵢ ∂'ᵢ` ([Wlo05, Lemma 2.6.3]; the second line of
[BM08, Lemma 3.1]). -/
theorem smul_awayPderiv_self :
    algebraMap R (Localization.Away (c.x r)) (c.x r) • c.awayPderiv r r =
      chartY c.x r r • c.chartDeriv r r -
        ∑ i ∈ Finset.univ.filter (· < r), chartY c.x r i • c.chartDeriv r i := by
  refine Derivation.ext fun z => ?_
  have hsum : ∀ i ∈ Finset.univ.filter (· < r),
      (chartY c.x r i • c.chartDeriv r i) z =
        algebraMap R _ (c.x r) * (chartY c.x r i * c.awayPderiv r i z) := by
    intro i hi
    rw [Derivation.smul_apply, chartDeriv_of_lt _ _ (Finset.mem_filter.mp hi).2,
      Derivation.smul_apply, smul_eq_mul, smul_eq_mul]
    ring
  rw [Derivation.sub_apply, Derivation.finset_sum_apply, Finset.sum_congr rfl hsum,
    ← Finset.mul_sum,
    Derivation.smul_apply, Derivation.smul_apply, chartDeriv_self, Derivation.add_apply,
    Derivation.finset_sum_apply, chartY, chartYOf_self, smul_eq_mul, smul_eq_mul]
  simp only [Derivation.smul_apply, smul_eq_mul]
  ring

/-- `x_r ∂ⱼ` preserves the chart ring for every `j`; in the words of [Wlo05, Lemma 2.6.3], "any
derivation `D` of `O_X` induces a derivation `yσ^*(D)` of `O_{X'}`". -/
theorem smul_awayPderiv_mem (j : Fin n) {z : Localization.Away (c.x r)}
    (hz : z ∈ chartRing c.x r) :
    (algebraMap R (Localization.Away (c.x r)) (c.x r) • c.awayPderiv r j) z ∈ chartRing c.x r := by
  rcases lt_trichotomy j r with hj | hj | hj
  · rw [smul_awayPderiv_of_lt c r hj]
    exact c.chartDeriv_mem r j hz
  · subst hj
    rw [smul_awayPderiv_self, Derivation.sub_apply, Derivation.finset_sum_apply,
      Derivation.smul_apply, smul_eq_mul]
    refine Subalgebra.sub_mem _ (Subalgebra.mul_mem _ (chartY_mem _ _ _) (c.chartDeriv_mem j j hz))
      (Subalgebra.sum_mem _ fun i _ => ?_)
    rw [Derivation.smul_apply, smul_eq_mul]
    exact Subalgebra.mul_mem _ (chartY_mem _ _ _) (c.chartDeriv_mem j i hz)
  · rw [smul_awayPderiv_of_gt c r hj, Derivation.smul_apply, smul_eq_mul]
    exact Subalgebra.mul_mem _ (chartY_mem _ _ _) (c.chartDeriv_mem r j hz)

end RegularCoords

end IsLocalRing
