/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.MarkedOrderReduction.MonomialPart
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
import Hironaka.Algebra.Local.Regular
import Hironaka.Resolution.Algebraic.Snc.ComponentStalks
import Hironaka.Resolution.Algebraic.Snc.DictionaryGenericPoints
import Hironaka.Scheme.IdealSheaf.Invertible
import Hironaka.Scheme.IdealSheaf.StalkLe
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Snc.ParameterAlgebra
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The monomial split, I: monomials of a normal-crossings family at a point

The monomial and nonmonomial parts of [Kol07, Definition–Lemma 110]
(`Hironaka/Resolution/Algebraic/MarkedOrderReduction/MonomialPart.lean`) are products over the
irreducible components of the members of a family with normal crossings. This module computes them
at a point of a scheme smooth over a field, in Kollár's coordinates ([Kol07, Definition 24]): at
`x`, a member through `x` has stalk `(z_c)` for one parameter `z_c` of a regular system of
parameters of `𝒪_{X,x}`, exactly one of its irreducible components passes through `x` (its reduced
ideal has the same stalk `(z_c)`, the unique minimal prime over the prime `(z_c)`), and every other
component has the unit stalk. Hence the stalk of `𝒪_X(−∑_D a_D D)` at `x` is the principal ideal
generated by the monomial `∏_c z_c^{a_c}` over the members through `x`, a nonzerodivisor of the
domain `𝒪_{X,x}`, which gives the invertibility of the monomial ideals.

* `stalkIdeal_monomial`: the stalk of a monomial in algebraic form; the two evaluations of a
  member's inner product are `finprod_stalk_eq_of_specializes` and
  `finprod_stalk_eq_one_of_notMem` (`Hironaka/Resolution/Algebraic/Snc/ComponentStalks.lean`);
* `Snc.stalkIdeal_monomial_eq_span` (a principal ideal generated by a nonzero element) and
  `Snc.isInvertible_monomial` (every monomial ideal of a normal-crossings family on a smooth
  Noetherian scheme is invertible).

The parameter algebra, the generic points of the components and the regular-subscheme forms used
here are in `Hironaka/Scheme/Snc/ParameterAlgebra.lean`,
`Hironaka/Resolution/Algebraic/Snc/DictionaryGenericPoints.lean`,
`Hironaka/Resolution/Algebraic/Snc/DictionaryRegular.lean` and
`Hironaka/Resolution/Algebraic/Snc/ComponentStalks.lean`. The statements on a triple are in
`Hironaka/Resolution/Algebraic/MarkedOrderReduction/SplitTriple.lean`.
-/

public section

universe u

open CategoryTheory AlgebraicGeometry TopologicalSpace Scheme Scheme.IdealSheafData IsLocalRing
  Ideal

namespace Hironaka.BMO

/-! ### The components of a member at a point -/

/-- The stalk of `𝒪_X(−∑_D a_D D)` at `x` is the product over the members and their components of
the powers of the components' stalks. -/
theorem stalkIdeal_monomial {X : Scheme.{u}} (E : DivisorFamily X)
    (hfin : ∀ i, ((E.component i).support.genericPoints).Finite) (a : X → ℕ) (x : X) :
    (E.monomial a).stalkIdeal x =
      ∏ i, ∏ᶠ η ∈ (E.component i).support.genericPoints,
        ((IdealSheafData.vanishingIdeal (Closeds.closure {η})).stalkIdeal x) ^ a η := by
  unfold DivisorFamily.monomial
  rw [IdealSheafData.stalkIdeal_finset_prod]
  refine Finset.prod_congr rfl fun i _ => ?_
  rw [stalkIdeal_finprod_mem (hfin i)]
  exact finprod_mem_congr rfl fun η _ => IdealSheafData.stalkIdeal_pow _ _ _

namespace Snc

/-! The general setting: a normal-crossings family `E` on a scheme `X` smooth over `k` (regular
stalks), the scheme Noetherian where the components have to be finitely many. The statements on
triples are the instances of this setting at `T.X.left ↘ Spec k`, `T.E`, `T.I` (`SplitTriple.lean`);
the smooth-pull-back and base-change identities apply it on the source with `T.E.comap h`. -/

variable {k : Type u} [Field k] {X : Scheme.{u}} (f : X ⟶ Spec (.of k)) [Smooth f]
  (E : DivisorFamily X) (hE : E.IsSnc)

/-! ### The stalk of a monomial -/

include f hE in
/-- The stalk of a monomial of a normal-crossings family at `x` is the principal ideal of a nonzero
element: the product over the members through `x` of `z_c^{a}` in Kollár's coordinates, a nonzero
element of the domain `𝒪_{X,x}`. This is the local form of the invertibility of `M(I)`. -/
theorem stalkIdeal_monomial_eq_span [NoetherianSpace X] (a : X → ℕ) (x : X) :
    ∃ g : X.presheaf.stalk x, g ≠ 0 ∧ (E.monomial a).stalkIdeal x = Ideal.span {g} := by
  classical
  have hreg := isRegularLocalRing_stalk f x
  rw [stalkIdeal_monomial E (genericPoints_component_finite E) a x]
  refine Finset.prod_induction _ (fun J => ∃ g : X.presheaf.stalk x, g ≠ 0 ∧ J = Ideal.span {g})
    ?_ ⟨1, one_ne_zero, Ideal.one_eq_top.trans Ideal.span_singleton_one.symm⟩ fun i _ => ?_
  · rintro J J' ⟨g, hg, rfl⟩ ⟨g', hg', rfl⟩
    exact ⟨g * g', mul_ne_zero hg hg', Ideal.span_singleton_mul_span_singleton g g'⟩
  · by_cases hx : x ∈ (E.component i).support
    · obtain ⟨η₀, hη₀, h₀⟩ := exists_genericPoint_specializes _ hx
      obtain ⟨m, z, hz, c, hc⟩ := exists_stalkIdeal_component_eq_span_of_isSnc E hE hx
      refine ⟨z c ^ a η₀, pow_ne_zero _ (ne_zero_of_parameters hz.1.1.symm hz.1.2 c), ?_⟩
      rw [finprod_stalk_eq_of_specializes E hE hη₀ h₀, hc, Ideal.span_singleton_pow]
    · exact ⟨1, one_ne_zero, by
        rw [finprod_stalk_eq_one_of_notMem E hx, Ideal.span_singleton_one]
        exact Ideal.one_eq_top⟩

include f hE in
/-- Every monomial ideal of a normal-crossings family on a smooth Noetherian scheme is invertible
(the invertibility of `M(I)` in [Kol07, Definition–Lemma 110]). -/
theorem isInvertible_monomial [NoetherianSpace X] (a : X → ℕ) :
    (E.monomial a).IsInvertible := by
  have := LocallyOfFiniteType.isLocallyNoetherian f
  refine Scheme.IdealSheafData.isInvertible_of_forall_stalkIdeal_eq_span _ fun x => ?_
  obtain ⟨g, hg, hJ⟩ := stalkIdeal_monomial_eq_span f E hE a x
  have hreg := isRegularLocalRing_stalk f x
  exact ⟨g, mem_nonZeroDivisors_of_ne_zero hg, hJ⟩

end Snc

end Hironaka.BMO
