/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.MarkedOrderReduction.MonomialPart
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
import Hironaka.Resolution.Algebraic.MarkedOrderReduction.Split
import Hironaka.Resolution.Algebraic.Snc.ComponentStalks
import Hironaka.Resolution.Algebraic.Snc.DictionaryGenericPoints
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The monomial split, II: orders at the generic points of the components

At the generic point `η` of an irreducible component `D` of a member `E^i` of a normal-crossings
family, the local ring `𝒪_{X,η}` has maximal ideal `(E^i)_η = (z_c)`, generated by the one
parameter of the member (the reduced ideal of `D` at `η` is both the maximal ideal and, by the
minimal-prime dictionary of `Hironaka/Resolution/Algebraic/Snc/DictionaryGenericPoints.lean`, the
stalk of `E^i`); no other member passes through `η`, since two distinct parameters cannot both
generate `𝔪_η`. Hence at `η` the stalk of a monomial `𝒪_X(−∑_D a_D D)` is `(z_c)^{a_D}`, of order
`a_D`, and the order of `(z_c)^a · J` is `a + ord J`, by the multiplicativity of the order on the
regular local ring `𝒪_{X,η}` containing `ℚ`. The membership half of [Kol07, Definition–Lemma 110],
that `I ⊆ (z_c)^{ord_D I}` at every point of `D`, is the propagation of [Kol07, Definition 47] from
the generic point: `ordAlong_stalkIdeal_eq_ord_stalkIdeal` for the integral component subscheme
together with the local lemma `le_pow_of_le_ordAlong_span_singleton` (`m ≤ ord_{(p)} I ⟹ I ⊆ (p)^m`
for a prime element `p`).

* `Snc.stalkIdeal_monomial_genericPoint`: the stalk of a monomial at a generic point.
* `Snc.ord_monomial_genericPoint`: the order of a monomial at a generic point.

The local algebra used here is in `Hironaka/Scheme/Snc/ParameterAlgebra.lean`,
`Hironaka/Resolution/Algebraic/Snc/DictionaryGenericPoints.lean`,
`Hironaka/Resolution/Algebraic/Snc/DictionaryRegular.lean` and
`Hironaka/Resolution/Algebraic/Snc/ComponentStalks.lean`.
-/

public section

universe u

open CategoryTheory AlgebraicGeometry TopologicalSpace Scheme Scheme.IdealSheafData IsLocalRing
  Ideal

namespace Hironaka.BMO

/-! ### The component at its generic point -/

namespace Snc

variable {k : Type u} [Field k] {X : Scheme.{u}} (f : X ⟶ Spec (.of k)) [Smooth f]
  (E : DivisorFamily X) (hE : E.IsSnc)

include f hE

/-- At the generic point of a component of `E^i` the stalk of a monomial is the power of `(E^i)_η`
at the component's exponent. -/
theorem stalkIdeal_monomial_genericPoint [NoetherianSpace X] {i : E.ι} {η : X}
    (hη : η ∈ (E.component i).support.genericPoints) (a : X → ℕ) :
    (E.monomial a).stalkIdeal η = ((E.component i).stalkIdeal η) ^ a η := by
  rw [stalkIdeal_monomial E (genericPoints_component_finite E) a η, Finset.prod_eq_single i]
  · exact finprod_stalk_eq_of_specializes E hE hη (specializes_refl η) a
  · intro j _ hji
    exact finprod_stalk_eq_one_of_notMem E (notMem_support_of_ne f E hE hji hη) a
  · intro h
    exact absurd (Finset.mem_univ i) h

/-! ### Orders at the generic point -/

variable [CharZero k]

/-- The order of a monomial at the generic point of a component is the component's exponent (the
reading of `𝒪_X(−∑_D a_D D)` in [Kol07, Definition–Lemma 110]). -/
theorem ord_monomial_genericPoint [NoetherianSpace X] {i : E.ι} {η : X}
    (hη : η ∈ (E.component i).support.genericPoints) (a : X → ℕ) :
    (E.monomial a).ord η = a η := by
  rw [IdealSheafData.ord_eq_ord_stalkIdeal, stalkIdeal_monomial_genericPoint f E hE hη,
    ord_stalkIdeal_component_pow f E hE hη]

end Snc

end Hironaka.BMO
