/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.Smooth.Graph
public import Hironaka.Algebra.Derivative.Basic
public import Hironaka.Algebra.RegularSmooth.Stalk
public import Hironaka.Scheme.IdealSheaf.Defs
import Hironaka.Algebra.Derivative.Localization
import Hironaka.Algebra.Local.CohenIso
import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Membership
import Hironaka.Scheme.BlowUp.CoordinateSubspace.Smooth
import Hironaka.Scheme.IdealSheaf.Derivative.Cosupport
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Hironaka.Scheme.Smooth.AdaptedCoordinates

/-!
# The order of an ideal at the rational points of affine space

[Hau03, Appendix B, Exercises 3 and 4] compute the strata of constant order of `f = x³ + yᵏzᵐ` on
`𝔸³` and of the four coordinate hyperplanes on `𝔸⁴` at the points `a = (a₁, …, aₙ) ∈ 𝔸ⁿ`; over an
algebraically closed field these are all the closed points. This module supplies the vocabulary
and the tools for such computations (the exercises themselves are worked out in
`HironakaExamples/HauserExercisesOrderStrata.lean`):

* the `K`-rational point `ratPoint a` of `𝔸ⁿ_K = Spec K[x₁, …, xₙ]`, the prime ideal of the
  polynomials vanishing at `a` (the kernel of evaluation at `a`; defined in
  `Hironaka/Scheme/Smooth/CoordinateSystem.lean`, where the origin is `ratPoint 0`);
* the derivative criterion for the order at a point of `𝔸ⁿ_K` (`K` of characteristic zero):
  `c ≤ ord_p I ⟺ D^{c-1}(I) ⊆ 𝔭` (`le_ord_specIdealSheaf_iff`), from the cosupport transfer
  `c ≤ ord_x I ⟺ x ∈ V(D^{c-1} I)` ([Kol07, Lemma 74 (3)], [Wlo05, Lemma 2.6.2];
  `Hironaka/Scheme/IdealSheaf/Derivative/Cosupport.lean`) read at the stalk `𝒪_{𝔸ⁿ,p} = K[x]_𝔭`
  (Mathlib's `StructureSheaf.IsLocalization.to_stalk`), where the derivative ideal is the
  localization of the derivative ideal (`Hironaka/Algebra/Derivative/Localization.lean`); on `K[x]`
  the derivative ideal of `(f)` is spanned by `f` and its partial derivatives ([Kol07, Definition
  73]: the `∂/∂xᵢ` generate `Der_K(K[x])`, `derivative_span_eq`), and `D^r((f))` by the iterated
  partials of order `≤ r` (`derivativeIter_span_singleton`). At a rational point this is Hauser's
  description of the order by the vanishing of the Taylor coefficients ([Hau03, Appendix A, Exercise
  1]; in characteristic zero the Taylor coefficients are the partial derivatives divided by
  factorials): `c ≤ ord_a f ⟺` all partial derivatives of `f` of order `< c` vanish at `a`
  (`le_ord_specIdealSheaf_span_singleton_iff`);
* the multiplicativity of the order at a point of `𝔸ⁿ_K` (the stalk is a regular local ring
  containing `ℚ`, where the order of a product is the sum, `ordElem_mul_of_algebraRat` of
  `Hironaka/Algebra/Local/CohenIso.lean`): `ord_p(fg) = ord_p f + ord_p g`
  (`ord_specIdealSheaf_span_singleton_mul`), and `ord_a xᵢ = 1` or `0` according as `aᵢ = 0` or not
  (`ord_specIdealSheaf_span_singleton_X`).

The last section works [Hau03, Appendix B, Exercise 3] for `f = x³ + yᵏzᵐ` on `𝔸³`: the locus of
order `≥ 2` and the locus of order `3` (`two_le_ord_hauserEx3_iff`, `ord_hauserEx3_eq_three_iff`).

Used for the examples (`HironakaExamples/OrderStrata.lean`,
`HironakaExamples/HauserExercisesOrderStrata.lean`,
`HironakaExamples/OrderReduction/Example106.lean`, `HironakaExamples/MaximalContact/Example82.lean`,
`HironakaExamples/Sequence/CuspWitness.lean`, `HironakaExamples/Sequence/Remark33OrderSeq.lean`).
-/

@[expose] public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory MvPolynomial KaehlerDifferential
open AlgebraicGeometry

universe u

variable {K : Type u} [Field K] {n : ℕ}

/-! ### Derivations of `K[x]` are generated by the partial derivatives ([Kol07, Definition 73]) -/

/-- [Kol07, Definition 73] ("the derivations `∂/∂x₁, …, ∂/∂xₙ` are local generators of `Der_X`")
on `𝔸ⁿ`: every `K`-derivation of `K[x]` is `∑ᵢ δ(xᵢ) ∂/∂xᵢ`. -/
theorem derivation_eq_sum_smul_pderiv
    (δ : Derivation K (MvPolynomial (Fin n) K) (MvPolynomial (Fin n) K)) :
    δ = ∑ i, δ (X i) • pderiv i := by
  refine MvPolynomial.derivation_ext fun j => ?_
  have hc : (⇑(∑ i, δ (X i) • pderiv i : Derivation K (MvPolynomial (Fin n) K)
      (MvPolynomial (Fin n) K)) : MvPolynomial (Fin n) K → MvPolynomial (Fin n) K) =
      ∑ i, ⇑(δ (X i) • (pderiv i : Derivation K (MvPolynomial (Fin n) K)
        (MvPolynomial (Fin n) K))) :=
    map_sum Derivation.coeFnAddMonoidHom _ _
  rw [hc, Finset.sum_apply, Finset.sum_eq_single j]
  · rw [Derivation.smul_apply, pderiv_X_self, smul_eq_mul, mul_one]
  · intro i _ hij
    rw [Derivation.smul_apply, pderiv_X_of_ne hij.symm, smul_zero]
  · intro h
    exact absurd (Finset.mem_univ j) h

/-- The `∂/∂xᵢ` span `Der_K(K[x])` over `K[x]`. -/
theorem derivation_mem_span_range_pderiv
    (δ : Derivation K (MvPolynomial (Fin n) K) (MvPolynomial (Fin n) K)) :
    δ ∈ Submodule.span (MvPolynomial (Fin n) K)
      (Set.range fun i : Fin n =>
        (pderiv i : Derivation K (MvPolynomial (Fin n) K) (MvPolynomial (Fin n) K))) := by
  rw [derivation_eq_sum_smul_pderiv δ]
  exact Submodule.sum_mem _ fun i _ =>
    Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

/-- [Kol07, Definition 73], `D(f₁, …, f_s) = (fᵢ, ∂fᵢ/∂xⱼ)`, on `𝔸ⁿ`: `D(⟨S⟩) = ⟨S, ∂s/∂xᵢ⟩`. -/
theorem derivative_span_eq (S : Set (MvPolynomial (Fin n) K)) :
    Ideal.derivative K (Ideal.span S) = Ideal.span (S ∪ ⋃ i, pderiv i '' S) :=
  Ideal.derivative_span_eq_of_span (fun i : Fin n => pderiv i) derivation_mem_span_range_pderiv S

/-- The iterated partial derivative `∂_{l₀} ∂_{l₁} ⋯ f` along a list of indices. -/
noncomputable def pderivList (l : List (Fin n)) (f : MvPolynomial (Fin n) K) :
    MvPolynomial (Fin n) K :=
  l.foldr (fun i g => pderiv i g) f

@[simp] theorem pderivList_nil (f : MvPolynomial (Fin n) K) :
    pderivList ([] : List (Fin n)) f = f := rfl

@[simp] theorem pderivList_cons (i : Fin n) (l : List (Fin n))
    (f : MvPolynomial (Fin n) K) : pderivList (i :: l) f = pderiv i (pderivList l f) := rfl

/-- `Dʳ((f))` is spanned by the iterated partial derivatives of `f` of order at most `r` (the
higher derivatives of [Kol07, Definition 73] on `𝔸ⁿ`). -/
theorem derivativeIter_span_singleton (r : ℕ) (f : MvPolynomial (Fin n) K) :
    Ideal.derivativeIter K r (Ideal.span {f}) =
      Ideal.span {g | ∃ l : List (Fin n), l.length ≤ r ∧ pderivList l f = g} := by
  induction r with
  | zero =>
    rw [Ideal.derivativeIter_zero]
    congr 1
    ext g
    simp only [Set.mem_singleton_iff, Set.mem_ofPred_eq, Nat.le_zero, List.length_eq_zero_iff]
    constructor
    · rintro rfl
      exact ⟨[], rfl, rfl⟩
    · rintro ⟨l, rfl, rfl⟩
      rfl
  | succ r ih =>
    rw [Ideal.derivativeIter_succ, ih, derivative_span_eq]
    congr 1
    ext g
    simp only [Set.mem_union, Set.mem_ofPred_eq, Set.mem_iUnion, Set.mem_image]
    constructor
    · rintro (⟨l, hl, rfl⟩ | ⟨i, g', ⟨l, hl, rfl⟩, rfl⟩)
      · exact ⟨l, by omega, rfl⟩
      · exact ⟨i :: l, by simp only [List.length_cons]; omega, rfl⟩
    · rintro ⟨l, hl, rfl⟩
      cases l with
      | nil => exact Or.inl ⟨[], by simp, rfl⟩
      | cons i l =>
        simp only [List.length_cons] at hl
        exact Or.inr ⟨i, pderivList l f, ⟨l, by omega, rfl⟩, rfl⟩

/-- `Dʳ((f)) ⊆ 𝔭` iff every iterated partial derivative of `f` of order `≤ r` lies in `𝔭`. -/
theorem derivativeIter_span_singleton_le_iff (r : ℕ) (f : MvPolynomial (Fin n) K)
    (p : Ideal (MvPolynomial (Fin n) K)) :
    Ideal.derivativeIter K r (Ideal.span {f}) ≤ p ↔
      ∀ l : List (Fin n), l.length ≤ r → pderivList l f ∈ p := by
  rw [derivativeIter_span_singleton, Ideal.span_le]
  exact ⟨fun h l hl => h ⟨l, hl, rfl⟩, fun h g ⟨l, hl, hg⟩ => hg ▸ h l hl⟩

/-! ### The stalk of `𝔸ⁿ_K` at a point, as the localization of `K[x]` -/

/-- `Dʳ(J B) = Dʳ(J) B` for a localization `B` of `A` with `Ω_{A/k}` finitely presented
(`Ideal.derivative_map` of `Hironaka/Algebra/Derivative/Localization.lean`, iterated). -/
theorem _root_.Ideal.derivativeIter_map {k A B : Type*} [CommRing k] [CommRing A] [CommRing B]
    [Algebra k A] [Algebra A B] [Algebra k B] [IsScalarTower k A B] (M : Submonoid A)
    [IsLocalization M B] [Module.FinitePresentation A (Ω[A⁄k])] (r : ℕ) (J : Ideal A) :
    Ideal.derivativeIter k r (J.map (algebraMap A B)) =
      (Ideal.derivativeIter k r J).map (algebraMap A B) := by
  induction r with
  | zero => rfl
  | succ r ih =>
    rw [Ideal.derivativeIter_succ, Ideal.derivativeIter_succ, ih, Ideal.derivative_map M]

/-- The stalk of the ideal sheaf of `J ⊆ R` on `Spec R` at `𝔭` is `J R_𝔭` (`specIdealSheaf` of
`Hironaka/Scheme/BlowUp/AffineBlowUp/Universal/Admissible.lean`, Mathlib's `toStalk`):
`stalkIdeal_ofIdealTop` of `Hironaka/Scheme/BlowUp/AffineBlowUp/Universal/Membership.lean` in the
`toStalk` spelling. -/
theorem stalkIdeal_specIdealSheaf {R : Type u} [CommRing R] (J : Ideal R) (p : Spec (.of R)) :
    (specIdealSheaf J).stalkIdeal p = J.map (StructureSheaf.toStalk R p).hom := by
  rw [stalkIdeal_ofIdealTop, Ideal.map_map]
  rfl

/-- The order of the ideal sheaf `(f)` at `𝔭` is the order (`ordElem`) of the image of `f` in the
stalk `R_𝔭`. -/
theorem ord_specIdealSheaf_span_singleton {R : Type u} [CommRing R] (f : R) (p : Spec (.of R)) :
    (specIdealSheaf (Ideal.span {f})).ord p =
      IsLocalRing.ordElem (R := (Spec (.of R)).presheaf.stalk p)
        ((StructureSheaf.toStalk R p).hom f) := by
  rw [Scheme.IdealSheafData.ord_eq_ord_stalkIdeal, stalkIdeal_specIdealSheaf, Ideal.map_span,
    Set.image_singleton]
  rfl

/-- The unit ideal has order `0` everywhere. -/
theorem ord_specIdealSheaf_span_singleton_one (p : Spec (.of (MvPolynomial (Fin n) K))) :
    (specIdealSheaf (Ideal.span {(1 : MvPolynomial (Fin n) K)})).ord p = 0 := by
  rw [ord_specIdealSheaf_span_singleton, map_one]
  exact IsLocalRing.ordElem_one

/-- The `K`-algebra structure of the stalk `𝒪_{𝔸ⁿ,p}` induced by the structure morphism is
`K → K[x] → K[x]_𝔭` (the stalk as an algebra over `K[x]` through Mathlib's `toStalk`). -/
theorem algebraMap_stalkAlgebra_affineSpaceToSpec (p : Spec (.of (MvPolynomial (Fin n) K))) :
    letI := (affineSpaceToSpec K n).stalkAlgebra p
    letI : Algebra (MvPolynomial (Fin n) K)
        ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) :=
      (StructureSheaf.toStalk (MvPolynomial (Fin n) K) p).hom.toAlgebra
    algebraMap K ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) =
      (algebraMap (MvPolynomial (Fin n) K)
        ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p)).comp
        (algebraMap K (MvPolynomial (Fin n) K)) := by
  refine RingHom.ext fun c => ?_
  have h := congrArg (fun g => g.hom c)
    (Scheme.ΓSpecIso_inv_naturality (CommRingCat.ofHom (algebraMap K (MvPolynomial (Fin n) K))))
  simp only [CommRingCat.hom_comp, RingHom.comp_apply, CommRingCat.hom_ofHom] at h
  exact congrArg ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.germ ⊤ p trivial) h.symm

/-- The scalar tower `K → K[x] → 𝒪_{𝔸ⁿ,p}` for the structures induced by the structure morphism and
by `toStalk`. -/
theorem isScalarTower_affineSpace_stalk (p : Spec (.of (MvPolynomial (Fin n) K))) :
    letI := (affineSpaceToSpec K n).stalkAlgebra p
    letI : Algebra (MvPolynomial (Fin n) K)
        ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) :=
      (StructureSheaf.toStalk (MvPolynomial (Fin n) K) p).hom.toAlgebra
    IsScalarTower K (MvPolynomial (Fin n) K)
      ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) :=
  letI := (affineSpaceToSpec K n).stalkAlgebra p
  letI : Algebra (MvPolynomial (Fin n) K)
      ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) :=
    (StructureSheaf.toStalk (MvPolynomial (Fin n) K) p).hom.toAlgebra
  IsScalarTower.of_algebraMap_eq' (algebraMap_stalkAlgebra_affineSpaceToSpec p)

section CharZero

variable [CharZero K]

/-- The derivative criterion for the order on `𝔸ⁿ_K` ([Kol07, Lemma 74 (3)] and
[Wlo05, Lemma 2.6.2], read at the stalk `K[x]_𝔭`): for `c ≥ 1`, `c ≤ ord_𝔭 J` iff
`D^{c-1}(J) ⊆ 𝔭`. -/
theorem le_ord_specIdealSheaf_iff (J : Ideal (MvPolynomial (Fin n) K))
    (p : Spec (.of (MvPolynomial (Fin n) K))) {c : ℕ} (hc : 1 ≤ c) :
    (c : ℕ∞) ≤ (specIdealSheaf J).ord p ↔ Ideal.derivativeIter K (c - 1) J ≤ p.asIdeal := by
  have : SmoothOfRelativeDimension n (affineSpaceToSpec K n) :=
    CoordinateSubspace.smoothOfRelativeDimension_Spec_map_algebraMap_mvPolynomial K n
  have : Smooth (affineSpaceToSpec K n) := SmoothOfRelativeDimension.smooth n _
  rw [Scheme.IdealSheafData.le_ord_iff_mem_support_derivativeIter (affineSpaceToSpec K n) n _ p hc,
    Scheme.IdealSheafData.mem_support_iff_stalkIdeal_le_maximalIdeal,
    Scheme.IdealSheafData.stalkIdeal_derivativeIter (affineSpaceToSpec K n) (c - 1) _ p,
    stalkIdeal_specIdealSheaf]
  let _ := (affineSpaceToSpec K n).stalkAlgebra p
  let _ : Algebra (MvPolynomial (Fin n) K)
      ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) :=
    (StructureSheaf.toStalk (MvPolynomial (Fin n) K) p).hom.toAlgebra
  have := isScalarTower_affineSpace_stalk (K := K) p
  have hp : p.asIdeal.IsPrime := p.isPrime
  have hloc : IsLocalization.AtPrime ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p)
      p.asIdeal :=
    StructureSheaf.IsLocalization.to_stalk (MvPolynomial (Fin n) K) p
  have hmap := Ideal.derivativeIter_map (k := K)
    (B := (Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) p.asIdeal.primeCompl (c - 1) J
  change Ideal.derivativeIter K (c - 1) (J.map (algebraMap (MvPolynomial (Fin n) K)
    ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p))) ≤ _ ↔ _
  rw [hmap, Ideal.map_le_iff_le_comap]
  exact ⟨fun h x hx => (IsLocalization.AtPrime.to_map_mem_maximal_iff _ p.asIdeal x).mp (h hx),
    fun h x hx => (IsLocalization.AtPrime.to_map_mem_maximal_iff _ p.asIdeal x).mpr (h hx)⟩

/-- Hauser's criterion ([Hau03, Appendix A, Exercise 1], in derivative form): at a rational point
`a`, `c ≤ ord_a f` iff all partial derivatives of `f` of order `< c` vanish at `a`. -/
theorem le_ord_specIdealSheaf_span_singleton_iff (f : MvPolynomial (Fin n) K) (a : Fin n → K)
    {c : ℕ} (hc : 1 ≤ c) :
    (c : ℕ∞) ≤ (specIdealSheaf (Ideal.span {f})).ord (ratPoint a) ↔
      ∀ l : List (Fin n), l.length ≤ c - 1 → aeval a (pderivList l f) = 0 := by
  rw [le_ord_specIdealSheaf_iff _ _ hc, derivativeIter_span_singleton_le_iff]
  exact forall_congr' fun l => forall_congr' fun _ => mem_ratPoint_asIdeal_iff a _

/-- The order is multiplicative on `𝔸ⁿ_K`, `ord_𝔭(fg) = ord_𝔭 f + ord_𝔭 g`: the stalk is a regular
local ring containing `ℚ` (`ordElem_mul_of_algebraRat`). -/
theorem ord_specIdealSheaf_span_singleton_mul (f g : MvPolynomial (Fin n) K)
    (p : Spec (.of (MvPolynomial (Fin n) K))) :
    (specIdealSheaf (Ideal.span {f * g})).ord p =
      (specIdealSheaf (Ideal.span {f})).ord p + (specIdealSheaf (Ideal.span {g})).ord p := by
  have : SmoothOfRelativeDimension n (affineSpaceToSpec K n) :=
    CoordinateSubspace.smoothOfRelativeDimension_Spec_map_algebraMap_mvPolynomial K n
  have : Smooth (affineSpaceToSpec K n) := SmoothOfRelativeDimension.smooth n _
  have : IsRegularLocalRing ((Spec (.of (MvPolynomial (Fin n) K))).presheaf.stalk p) :=
    isRegularLocalRing_stalk (affineSpaceToSpec K n) p
  let _ := (affineSpaceToSpec K n).stalkAlgebra p
  let _ := (affineSpaceToSpec K n).stalkAlgebraRat p
  rw [ord_specIdealSheaf_span_singleton, ord_specIdealSheaf_span_singleton,
    ord_specIdealSheaf_span_singleton, map_mul]
  exact IsLocalRing.ordElem_mul_of_algebraRat _ _ _

theorem ord_specIdealSheaf_span_singleton_prod {ι : Type*} (s : Finset ι)
    (g : ι → MvPolynomial (Fin n) K) (p : Spec (.of (MvPolynomial (Fin n) K))) :
    (specIdealSheaf (Ideal.span {∏ i ∈ s, g i})).ord p =
      ∑ i ∈ s, (specIdealSheaf (Ideal.span {g i})).ord p := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    rw [Finset.prod_empty, Finset.sum_empty]
    exact ord_specIdealSheaf_span_singleton_one p
  | insert i s hi ih =>
    rw [Finset.prod_insert hi, Finset.sum_insert hi, ord_specIdealSheaf_span_singleton_mul, ih]

theorem ord_specIdealSheaf_span_singleton_pow (f : MvPolynomial (Fin n) K) (e : ℕ)
    (p : Spec (.of (MvPolynomial (Fin n) K))) :
    (specIdealSheaf (Ideal.span {f ^ e})).ord p = e * (specIdealSheaf (Ideal.span {f})).ord p := by
  induction e with
  | zero =>
    rw [pow_zero, Nat.cast_zero, zero_mul]
    exact ord_specIdealSheaf_span_singleton_one p
  | succ e ih =>
    rw [pow_succ, ord_specIdealSheaf_span_singleton_mul, ih, Nat.cast_succ, add_mul, one_mul]

open scoped Classical in
/-- `ord_a xᵢ = 1` where `xᵢ` vanishes and `0` elsewhere — `xᵢ ∈ 𝔪_a ∖ 𝔪_a²` since
`∂xᵢ/∂xᵢ = 1`. -/
theorem ord_specIdealSheaf_span_singleton_X (i : Fin n) (a : Fin n → K) :
    (specIdealSheaf (Ideal.span {(X i : MvPolynomial (Fin n) K)})).ord (ratPoint a) =
      if a i = 0 then 1 else 0 := by
  have h1 : (1 : ℕ∞) ≤ (specIdealSheaf (Ideal.span {(X i : MvPolynomial (Fin n) K)})).ord
      (ratPoint a) ↔ a i = 0 := by
    have key := le_ord_specIdealSheaf_iff (K := K) (Ideal.span {(X i : MvPolynomial (Fin n) K)})
      (ratPoint a) (c := 1) le_rfl
    rw [Nat.cast_one, Nat.sub_self, Ideal.derivativeIter_zero, Ideal.span_le,
      Set.singleton_subset_iff, SetLike.mem_coe] at key
    exact key.trans ((mem_ratPoint_asIdeal_iff a _).trans (by rw [aeval_X]))
  have h2 : ¬ (2 : ℕ∞) ≤ (specIdealSheaf (Ideal.span {(X i : MvPolynomial (Fin n) K)})).ord
      (ratPoint a) := by
    have key := le_ord_specIdealSheaf_iff (K := K) (Ideal.span {(X i : MvPolynomial (Fin n) K)})
      (ratPoint a) (c := 2) (by norm_num)
    rw [Nat.cast_ofNat] at key
    rw [key]
    intro h
    have hone : (1 : MvPolynomial (Fin n) K) ∈
        Ideal.derivativeIter K (2 - 1) (Ideal.span {(X i : MvPolynomial (Fin n) K)}) := by
      rw [show 2 - 1 = 0 + 1 from rfl, Ideal.derivativeIter_succ, Ideal.derivativeIter_zero,
        ← pderiv_X_self i]
      exact Ideal.derivation_apply_mem_derivative (pderiv i) (Ideal.mem_span_singleton_self _)
    exact (ratPoint a).isPrime.ne_top ((Ideal.eq_top_iff_one _).mpr (h hone))
  by_cases ha : a i = 0
  · rw [ite_eq_left ha]
    refine le_antisymm ?_ (h1.mpr ha)
    rw [← not_lt]
    intro hlt
    exact h2 (by rw [← one_add_one_eq_two]; exact (ENat.add_one_le_iff ENat.one_ne_top).mpr hlt)
  · rw [ite_eq_right ha]
    exact Order.lt_one_iff.mp (not_le.mp fun h => ha (h1.mp h))

open scoped Classical in
/-- [Hau03, Appendix B, Exercise 4], the divisor `Y = V(∏ xᵢ^{eᵢ})`: the order of a monomial at a
rational point is the sum of the exponents of the vanishing coordinates. -/
theorem ord_specIdealSheaf_span_singleton_prod_pow_X (e : Fin n → ℕ) (a : Fin n → K) :
    (specIdealSheaf (Ideal.span {∏ i, (X i : MvPolynomial (Fin n) K) ^ e i})).ord (ratPoint a) =
      ∑ i, if a i = 0 then (e i : ℕ∞) else 0 := by
  rw [ord_specIdealSheaf_span_singleton_prod]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [ord_specIdealSheaf_span_singleton_pow, ord_specIdealSheaf_span_singleton_X]
  split_ifs <;> simp

/-- [Hau03, Appendix B, Exercise 4], the union of the coordinate hyperplanes `X = V(∏ xᵢ)`: the
order at a rational point is the number of vanishing coordinates. -/
theorem ord_specIdealSheaf_span_singleton_prod_X (a : Fin n → K) :
    (specIdealSheaf (Ideal.span {∏ i, (X i : MvPolynomial (Fin n) K)})).ord (ratPoint a) =
      Nat.card {i : Fin n // a i = 0} := by
  classical
  have h := ord_specIdealSheaf_span_singleton_prod_pow_X (K := K) (fun _ : Fin n => 1) a
  simp only [pow_one, Nat.cast_one] at h
  rw [h, Nat.card_eq_fintype_card, Fintype.card_subtype, Finset.card_filter, Nat.cast_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  split_ifs <;> simp

end CharZero
/-! ### [Hau03, Appendix B, Exercise 3]: `f = x³ + yᵏzᵐ` on `𝔸³` -/

/-- A numeral constant has zero partial derivatives (the `OfNat` form of
`Derivation.map_natCast`, for `simp`). -/
@[simp] theorem pderiv_ofNat {σ R : Type*} [CommSemiring R] (i : σ) (c : ℕ) [c.AtLeastTwo] :
    pderiv i (ofNat(c) : MvPolynomial σ R) = 0 := by
  rw [← Nat.cast_ofNat]
  exact Derivation.map_natCast _ _

section HauserEx3

variable (K) (k m : ℕ)

/-- Hauser's `f = x³ + yᵏzᵐ` ([Hau03, Appendix B, Exercise 3]), with `x = x₀, y = x₁, z = x₂`. -/
noncomputable abbrev hauserEx3Poly : MvPolynomial (Fin 3) K := X 0 ^ 3 + X 1 ^ k * X 2 ^ m

theorem pderiv_zero_hauserEx3Poly : pderiv 0 (hauserEx3Poly K k m) = 3 * X 0 ^ 2 := by
  simp only [hauserEx3Poly, map_add, pderiv_pow, pderiv_X_self, Derivation.leibniz, smul_eq_mul,
    pderiv_X_of_ne (show (1 : Fin 3) ≠ 0 by decide),
    pderiv_X_of_ne (show (2 : Fin 3) ≠ 0 by decide)]
  ring

theorem pderiv_one_hauserEx3Poly :
    pderiv 1 (hauserEx3Poly K k m) = (k : MvPolynomial (Fin 3) K) * X 1 ^ (k - 1) * X 2 ^ m := by
  simp only [hauserEx3Poly, map_add, pderiv_pow, pderiv_X_self, Derivation.leibniz, smul_eq_mul,
    pderiv_X_of_ne (show (0 : Fin 3) ≠ 1 by decide),
    pderiv_X_of_ne (show (2 : Fin 3) ≠ 1 by decide)]
  ring

theorem pderiv_two_hauserEx3Poly :
    pderiv 2 (hauserEx3Poly K k m) = (m : MvPolynomial (Fin 3) K) * X 1 ^ k * X 2 ^ (m - 1) := by
  simp only [hauserEx3Poly, map_add, pderiv_pow, pderiv_X_self, Derivation.leibniz, smul_eq_mul,
    pderiv_X_of_ne (show (0 : Fin 3) ≠ 2 by decide),
    pderiv_X_of_ne (show (1 : Fin 3) ≠ 2 by decide)]
  ring

end HauserEx3

section HauserEx3Main

variable [CharZero K] (k m : ℕ)

/-- Every index of `Fin 3` is `0`, `1` or `2`. -/
theorem fin3_cases (i : Fin 3) : i = 0 ∨ i = 1 ∨ i = 2 := by decide +revert

/-- [Hau03, Appendix B, Exercise 3]: the locus of order `≥ 2` of `x³ + yᵏzᵐ` (`k, m ≥ 1`) — the
`z`-axis if `k ≥ 2`, the `y`-axis if `m ≥ 2`, and the origin. -/
theorem two_le_ord_hauserEx3_iff (hk : 1 ≤ k) (hm : 1 ≤ m) (a : Fin 3 → K) :
    (2 : ℕ∞) ≤ (specIdealSheaf (Ideal.span {hauserEx3Poly K k m})).ord (ratPoint a) ↔
      a 0 = 0 ∧ ((a 1 = 0 ∧ (2 ≤ k ∨ a 2 = 0)) ∨ (a 2 = 0 ∧ (2 ≤ m ∨ a 1 = 0))) := by
  have key := le_ord_specIdealSheaf_span_singleton_iff (hauserEx3Poly K k m) a (c := 2)
    (by norm_num)
  rw [Nat.cast_ofNat] at key
  rw [key]
  have E0 : aeval a (hauserEx3Poly K k m) = a 0 ^ 3 + a 1 ^ k * a 2 ^ m := by
    simp [hauserEx3Poly]
  have E1 : aeval a (pderiv 0 (hauserEx3Poly K k m)) = 3 * a 0 ^ 2 := by
    rw [pderiv_zero_hauserEx3Poly]; simp
  have E2 : aeval a (pderiv 1 (hauserEx3Poly K k m)) = k * a 1 ^ (k - 1) * a 2 ^ m := by
    rw [pderiv_one_hauserEx3Poly]; simp
  have E3 : aeval a (pderiv 2 (hauserEx3Poly K k m)) = m * a 1 ^ k * a 2 ^ (m - 1) := by
    rw [pderiv_two_hauserEx3Poly]; simp
  have hk0 : k ≠ 0 := by omega
  have hm0 : m ≠ 0 := by omega
  constructor
  · intro h
    have e0 := h [] (by simp)
    have e1 := h [0] (by simp)
    have e2 := h [1] (by simp)
    have e3 := h [2] (by simp)
    rw [pderivList_nil, E0] at e0
    rw [pderivList_cons, pderivList_nil, E1] at e1
    rw [pderivList_cons, pderivList_nil, E2] at e2
    rw [pderivList_cons, pderivList_nil, E3] at e3
    have ha0 : a 0 = 0 :=
      (pow_eq_zero_iff (by norm_num)).mp ((mul_eq_zero.mp e1).resolve_left (by norm_num))
    refine ⟨ha0, ?_⟩
    rw [ha0, zero_pow (by norm_num), zero_add, mul_eq_zero, pow_eq_zero_iff hk0,
      pow_eq_zero_iff hm0] at e0
    rcases e0 with ha1 | ha2
    · refine Or.inl ⟨ha1, ?_⟩
      by_cases hk2 : 2 ≤ k
      · exact Or.inl hk2
      · obtain rfl : k = 1 := by omega
        rw [ha1, Nat.sub_self, pow_zero, mul_one, Nat.cast_one, one_mul] at e2
        exact Or.inr ((pow_eq_zero_iff hm0).mp e2)
    · refine Or.inr ⟨ha2, ?_⟩
      by_cases hm2 : 2 ≤ m
      · exact Or.inl hm2
      · obtain rfl : m = 1 := by omega
        rw [ha2, Nat.sub_self, pow_zero, mul_one, Nat.cast_one, one_mul] at e3
        exact Or.inr ((pow_eq_zero_iff hk0).mp e3)
  · rintro ⟨ha0, h⟩ l hl
    rcases l with _ | ⟨i, _ | ⟨j, l⟩⟩
    · rw [pderivList_nil, E0, ha0, zero_pow (by norm_num), zero_add]
      rcases h with ⟨ha1, _⟩ | ⟨ha2, _⟩
      · rw [ha1, zero_pow hk0, zero_mul]
      · rw [ha2, zero_pow hm0, mul_zero]
    · rcases fin3_cases i with rfl | rfl | rfl
      · rw [pderivList_cons, pderivList_nil, E1, ha0]; ring
      · rw [pderivList_cons, pderivList_nil, E2]
        rcases h with ⟨ha1, hk2 | ha2⟩ | ⟨ha2, _⟩
        · rw [ha1, zero_pow (by omega)]; ring
        · rw [ha2, zero_pow hm0]; ring
        · rw [ha2, zero_pow hm0]; ring
      · rw [pderivList_cons, pderivList_nil, E3]
        rcases h with ⟨ha1, _⟩ | ⟨ha2, hm2 | ha1⟩
        · rw [ha1, zero_pow hk0]; ring
        · rw [ha2, zero_pow (by omega)]; ring
        · rw [ha1, zero_pow hk0]; ring
    · simp at hl

/-- `ord_a(x³ + yᵏzᵐ) ≤ 3` at every rational point, since `∂³f/∂x³ = 6 ≠ 0`. -/
theorem ord_hauserEx3_le_three (a : Fin 3 → K) :
    (specIdealSheaf (Ideal.span {hauserEx3Poly K k m})).ord (ratPoint a) ≤ 3 := by
  rw [← not_lt]
  intro hlt
  have h4 : (4 : ℕ∞) ≤ (specIdealSheaf (Ideal.span {hauserEx3Poly K k m})).ord (ratPoint a) := by
    rw [show (4 : ℕ∞) = 3 + 1 by norm_num]
    exact (ENat.add_one_le_iff (by simp)).mpr hlt
  have key := le_ord_specIdealSheaf_span_singleton_iff (hauserEx3Poly K k m) a (c := 4)
    (by norm_num)
  rw [Nat.cast_ofNat] at key
  have e := key.mp h4 [0, 0, 0] (by simp)
  rw [pderivList_cons, pderivList_cons, pderivList_cons, pderivList_nil,
    pderiv_zero_hauserEx3Poly] at e
  simp [Derivation.leibniz] at e

/-- [Hau03, Appendix B, Exercise 3]: the locus of order `3` of `x³ + yᵏzᵐ` (`k, m ≥ 1`) — the
`z`-axis if `k ≥ 3`, the `y`-axis if `m ≥ 3`, and the origin if `k + m ≥ 3`. -/
theorem ord_hauserEx3_eq_three_iff (hk : 1 ≤ k) (hm : 1 ≤ m) (a : Fin 3 → K) :
    (specIdealSheaf (Ideal.span {hauserEx3Poly K k m})).ord (ratPoint a) = 3 ↔
      a 0 = 0 ∧ ((a 1 = 0 ∧ 3 ≤ k) ∨ (a 2 = 0 ∧ 3 ≤ m) ∨ (a 1 = 0 ∧ a 2 = 0 ∧ 3 ≤ k + m)) := by
  rw [le_antisymm_iff, and_iff_right (ord_hauserEx3_le_three k m a)]
  have key := le_ord_specIdealSheaf_span_singleton_iff (hauserEx3Poly K k m) a (c := 3)
    (by norm_num)
  rw [Nat.cast_ofNat] at key
  rw [key]
  have hk0 : k ≠ 0 := by omega
  have hm0 : m ≠ 0 := by omega
  have E0 : aeval a (hauserEx3Poly K k m) = a 0 ^ 3 + a 1 ^ k * a 2 ^ m := by
    simp [hauserEx3Poly]
  have E1 : aeval a (pderivList [0] (hauserEx3Poly K k m)) = 3 * a 0 ^ 2 := by
    rw [pderivList_cons, pderivList_nil, pderiv_zero_hauserEx3Poly]; simp
  have E2 : aeval a (pderivList [1] (hauserEx3Poly K k m)) = k * a 1 ^ (k - 1) * a 2 ^ m := by
    rw [pderivList_cons, pderivList_nil, pderiv_one_hauserEx3Poly]; simp
  have E3 : aeval a (pderivList [2] (hauserEx3Poly K k m)) = m * a 1 ^ k * a 2 ^ (m - 1) := by
    rw [pderivList_cons, pderivList_nil, pderiv_two_hauserEx3Poly]; simp
  have E00 : aeval a (pderivList [0, 0] (hauserEx3Poly K k m)) = 6 * a 0 := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_zero_hauserEx3Poly]
    simp [Derivation.leibniz]; ring
  have E11 : aeval a (pderivList [1, 1] (hauserEx3Poly K k m)) =
      k * ((k - 1 : ℕ) : K) * a 1 ^ (k - 1 - 1) * a 2 ^ m := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_one_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (2 : Fin 3) ≠ 1 by decide)]; ring
  have E22 : aeval a (pderivList [2, 2] (hauserEx3Poly K k m)) =
      m * ((m - 1 : ℕ) : K) * a 1 ^ k * a 2 ^ (m - 1 - 1) := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_two_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (1 : Fin 3) ≠ 2 by decide)]; ring
  have E12 : aeval a (pderivList [1, 2] (hauserEx3Poly K k m)) =
      k * m * a 1 ^ (k - 1) * a 2 ^ (m - 1) := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_two_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (2 : Fin 3) ≠ 1 by decide)]; ring
  have E21 : aeval a (pderivList [2, 1] (hauserEx3Poly K k m)) =
      k * m * a 1 ^ (k - 1) * a 2 ^ (m - 1) := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_one_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (1 : Fin 3) ≠ 2 by decide)]; ring
  have E01 : aeval a (pderivList [0, 1] (hauserEx3Poly K k m)) = 0 := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_one_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (1 : Fin 3) ≠ 0 by decide),
      pderiv_X_of_ne (show (2 : Fin 3) ≠ 0 by decide)]
  have E02 : aeval a (pderivList [0, 2] (hauserEx3Poly K k m)) = 0 := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_two_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (1 : Fin 3) ≠ 0 by decide),
      pderiv_X_of_ne (show (2 : Fin 3) ≠ 0 by decide)]
  have E10 : aeval a (pderivList [1, 0] (hauserEx3Poly K k m)) = 0 := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_zero_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (0 : Fin 3) ≠ 1 by decide)]
  have E20 : aeval a (pderivList [2, 0] (hauserEx3Poly K k m)) = 0 := by
    rw [pderivList_cons, pderivList_cons, pderivList_nil, pderiv_zero_hauserEx3Poly]
    simp [Derivation.leibniz, pderiv_X_of_ne (show (0 : Fin 3) ≠ 2 by decide)]
  constructor
  · intro h
    have e0 := h [] (by simp)
    have e1 := h [0] (by simp)
    have e2 := h [1] (by simp)
    have e3 := h [2] (by simp)
    have e11 := h [1, 1] (by simp)
    have e22 := h [2, 2] (by simp)
    have e12 := h [1, 2] (by simp)
    rw [pderivList_nil, E0] at e0
    rw [E1] at e1
    rw [E2] at e2
    rw [E3] at e3
    rw [E11] at e11
    rw [E22] at e22
    rw [E12] at e12
    have ha0 : a 0 = 0 :=
      (pow_eq_zero_iff (by norm_num)).mp ((mul_eq_zero.mp e1).resolve_left (by norm_num))
    refine ⟨ha0, ?_⟩
    rw [ha0, zero_pow (by norm_num), zero_add, mul_eq_zero, pow_eq_zero_iff hk0,
      pow_eq_zero_iff hm0] at e0
    by_cases ha1 : a 1 = 0
    · by_cases ha2 : a 2 = 0
      · refine Or.inr (Or.inr ⟨ha1, ha2, ?_⟩)
        by_contra hlt
        obtain ⟨rfl, rfl⟩ : k = 1 ∧ m = 1 := by omega
        rw [ha1, ha2] at e12
        simp at e12
      · refine Or.inl ⟨ha1, ?_⟩
        have hk2 : 2 ≤ k := by
          by_contra hlt
          obtain rfl : k = 1 := by omega
          rw [ha1, Nat.sub_self, pow_zero, mul_one, Nat.cast_one, one_mul] at e2
          exact ha2 ((pow_eq_zero_iff hm0).mp e2)
        by_contra hlt
        obtain rfl : k = 2 := by omega
        rw [ha1] at e11
        have h2 : a 2 ^ m = 0 := by simpa using e11
        exact ha2 ((pow_eq_zero_iff hm0).mp h2)
    · have ha2 : a 2 = 0 := e0.resolve_left ha1
      refine Or.inr (Or.inl ⟨ha2, ?_⟩)
      have hm2 : 2 ≤ m := by
        by_contra hlt
        obtain rfl : m = 1 := by omega
        rw [ha2, Nat.sub_self, pow_zero, mul_one, Nat.cast_one, one_mul] at e3
        exact ha1 ((pow_eq_zero_iff hk0).mp e3)
      by_contra hlt
      obtain rfl : m = 2 := by omega
      rw [ha2] at e22
      have h1 : a 1 ^ k = 0 := by simpa using e22
      exact ha1 ((pow_eq_zero_iff hk0).mp h1)
  · rintro ⟨ha0, h⟩ l hl
    have hz : a 1 ^ k * a 2 ^ m = 0 := by
      rcases h with ⟨ha1, _⟩ | ⟨ha2, _⟩ | ⟨ha1, _, _⟩
      · rw [ha1, zero_pow hk0, zero_mul]
      · rw [ha2, zero_pow hm0, mul_zero]
      · rw [ha1, zero_pow hk0, zero_mul]
    rcases l with _ | ⟨i, _ | ⟨j, _ | ⟨l, tl⟩⟩⟩
    · rw [pderivList_nil, E0, ha0, zero_pow (by norm_num), zero_add, hz]
    · rcases fin3_cases i with rfl | rfl | rfl
      · rw [E1, ha0]; ring
      · rw [E2]
        rcases h with ⟨ha1, hk3⟩ | ⟨ha2, _⟩ | ⟨ha1, ha2, _⟩
        · rw [ha1, zero_pow (by omega)]; ring
        · rw [ha2, zero_pow hm0]; ring
        · rw [ha2, zero_pow hm0]; ring
      · rw [E3]
        rcases h with ⟨ha1, _⟩ | ⟨ha2, hm3⟩ | ⟨ha1, ha2, _⟩
        · rw [ha1, zero_pow hk0]; ring
        · rw [ha2, zero_pow (by omega)]; ring
        · rw [ha1, zero_pow hk0]; ring
    · rcases fin3_cases i with rfl | rfl | rfl <;> rcases fin3_cases j with rfl | rfl | rfl
      · rw [E00, ha0]; ring
      · exact E01
      · exact E02
      · exact E10
      · rw [E11]
        rcases h with ⟨ha1, hk3⟩ | ⟨ha2, _⟩ | ⟨ha1, ha2, _⟩
        · rw [ha1, zero_pow (by omega)]; ring
        · rw [ha2, zero_pow hm0]; ring
        · rw [ha2, zero_pow hm0]; ring
      · rw [E12]
        rcases h with ⟨ha1, hk3⟩ | ⟨ha2, hm3⟩ | ⟨ha1, ha2, hkm⟩
        · rw [ha1, zero_pow (by omega)]; ring
        · rw [ha2, zero_pow (by omega)]; ring
        · rcases Nat.lt_or_ge 1 k with hk2 | hk2
          · rw [ha1, zero_pow (by omega)]; ring
          · rw [ha2, zero_pow (by omega)]; ring
      · exact E20
      · rw [E21]
        rcases h with ⟨ha1, hk3⟩ | ⟨ha2, hm3⟩ | ⟨ha1, ha2, hkm⟩
        · rw [ha1, zero_pow (by omega)]; ring
        · rw [ha2, zero_pow (by omega)]; ring
        · rcases Nat.lt_or_ge 1 k with hk2 | hk2
          · rw [ha1, zero_pow (by omega)]; ring
          · rw [ha2, zero_pow (by omega)]; ring
      · rw [E22]
        rcases h with ⟨ha1, _⟩ | ⟨ha2, hm3⟩ | ⟨ha1, ha2, _⟩
        · rw [ha1, zero_pow hk0]; ring
        · rw [ha2, zero_pow (by omega)]; ring
        · rw [ha1, zero_pow hk0]; ring
    · simp at hl

end HauserEx3Main

end AlgebraicGeometry
