/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Algebra.Local.BirationalTransform
public import Hironaka.Algebra.Local.Order
public import Hironaka.Scheme.BlowUp.Defs
public import Hironaka.Scheme.IdealSheaf.Defs
public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
import Hironaka.Algebra.Local.TransformOrder
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.BlowUp.Glue.Global
import Hironaka.Scheme.BlowUp.InvertibleSheaf
import Hironaka.Scheme.BlowUp.Transform
import Hironaka.Scheme.BlowUp.Transform.StrictTransform
import Hironaka.Scheme.BlowUp.Transform.WeakTransform
import Hironaka.Scheme.IdealSheaf.Derivative.Sheaf
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Hironaka.Scheme.IdealSheaf.Order.Specialization
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.IdealSheaf.StalkLe
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Smooth.SubschemeStalk
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The order along a smooth centre and the exceptional divisor

[Kol07, Definition 47], last paragraph: "the number `ord_Z I` equals the multiplicity of `π^* I`
along the exceptional divisor of the blow-up"; [Kol07, Definition 60] assumes `m ≤ ord_Z I`;
[Hau14, Definition 6.8]: for `c` at most the order `d` of `I` along the centre, "`I^*` has order
`≥ c` along `E`".

For a smooth irreducible centre `Z` with generic point `η` and `m ≤ ord_Z I = ord_η I`, every
section of `I` lies in `Z^m` near `Z`, `I ≤ Z ^ m` as ideal sheaves (`le_pow_of_le_ord`), and hence
`F^m ∣ I^*` on the blow-up (`exceptionalDivisor_pow_dvd_comap_of_le_ord`). Kollár's argument reads
`I_η ⊆ 𝔪_η^m = (x₁, …, x_r)^m 𝒪_{X,η}` at the generic point and propagates to the points of `Z`;
here the propagation is `Pᵐ R_P ∩ R = Pᵐ` (the symbolic power equals the ordinary power for a
prime `P = Z_z` generated by part of a regular system of parameters,
`le_ordAlong_chartCenter_iff` of `Hironaka/Algebra/Local/SymbolicPower.lean`) applied at every point
`z` of `Z`, through the identification of `𝒪_{X,η}` with the localization of `𝒪_{X,z}` at `Z_z`
(`ordAlong_stalkIdeal_eq_ord_stalkIdeal`: on an affine open `U ∋ z` both stalks are localizations
of `Γ(U)`, Mathlib's `IsAffineOpen.isLocalization_stalk`, and `Z_z ∩ Γ(U) = Z(U)` is the prime of
`η`, `Z` being integral). Integrality of the centre: `Z` is irreducible (the generic point) and
its stalks are regular (smooth over `k`), so reduced (`isIntegral_subscheme_of_smooth`, via
`isIntegral_subscheme_of_isRegularLocalRing_stalk` of
`Hironaka/Scheme/BlowUp/Transform/WeakTransform.lean`).

Used for the order along centres and the strict transforms of components
(`Hironaka/Scheme/BlowUpSequence/OrderAlongCenter.lean`,
`Hironaka/Scheme/BlowUpSequence/StrictTransformIntegral.lean`,
`Hironaka/Resolution/Algebraic/MarkedOrderReduction/SplitOrder.lean`,
`Hironaka/Resolution/Algebraic/Snc/ComponentStalks.lean`) and for the sharpness `F^{m+1} ∤ I^*`
(`Hironaka/Scheme/IdealSheaf/Order/ExceptionalOrder.lean`).
-/

public section

universe u

open AlgebraicGeometry CategoryTheory IsLocalRing TopologicalSpace Scheme.IdealSheafData

namespace AlgebraicGeometry

variable {X : Scheme.{u}}

/-! ### Integrality of an irreducible smooth center -/

/-- The subscheme of an ideal sheaf whose support has a generic point is irreducible. -/
theorem irreducibleSpace_subscheme_of_isGenericPoint (Z : X.IdealSheafData) {η : X}
    (hη : IsGenericPoint η (Z.support : Set X)) : IrreducibleSpace Z.subscheme := by
  obtain ⟨p, hp⟩ := Z.exists_subschemeι_eq hη.mem
  rw [irreducibleSpace_def]
  have hcl : closure ({p} : Set Z.subscheme) = Set.univ := by
    refine Set.eq_univ_iff_forall.mpr fun q => ?_
    rw [← specializes_iff_mem_closure, ← Z.subschemeι.isEmbedding.isInducing.specializes_iff, hp]
    exact hη.specializes (Z.range_subschemeι ▸ ⟨q, rfl⟩)
  rw [Set.top_eq_univ, ← hcl]
  exact isIrreducible_singleton.closure

/-- A centre smooth over `k` with a generic point is integral. -/
theorem isIntegral_subscheme_of_smooth {k : Type u} [Field k] (f : X ⟶ Spec (.of k))
    (Z : X.IdealSheafData) [Smooth (Z.subschemeι ≫ f)] {η : X}
    (hη : IsGenericPoint η (Z.support : Set X)) : IsIntegral Z.subscheme := by
  have := irreducibleSpace_subscheme_of_isGenericPoint Z hη
  exact isIntegral_subscheme_of_isRegularLocalRing_stalk Z fun z =>
    isRegularLocalRing_stalk (Z.subschemeι ≫ f) z

/-! ### The order along the center at a point equals the order at the generic point -/

section Generic

variable (Z I : X.IdealSheafData) [IsIntegral Z.subscheme]

/-- For an integral center, the stalk of its ideal sheaf at a point of the center is prime. -/
theorem isPrime_stalkIdeal_of_mem_support {z : X} (hz : z ∈ Z.support) :
    (Z.stalkIdeal z).IsPrime := by
  obtain ⟨U, hzU⟩ := exists_affineOpens_mem z
  have hU : IsAffineOpen U.1 := U.2
  obtain ⟨z', hz'⟩ := Z.exists_subschemeι_eq hz
  have hprime : (Z.ideal U).IsPrime := isPrime_ideal_of_isIntegral_subscheme Z U (hz' ▸ hzU)
  have hle : Z.ideal U ≤ (hU.primeIdealOf ⟨z, hzU⟩).asIdeal :=
    (mem_zeroLocus_iff_le_primeIdealOf U hzU _).mp ((mem_support_iff_of_mem hzU).mp hz)
  let := TopCat.Presheaf.algebra_section_stalk X.presheaf (⟨z, hzU⟩ : U.1)
  have := hU.isLocalization_stalk ⟨z, hzU⟩
  rw [stalkIdeal_eq_map_germ _ U hzU]
  exact IsLocalization.isPrime_of_isPrime_disjoint (hU.primeIdealOf ⟨z, hzU⟩).asIdeal.primeCompl
    (X.presheaf.stalk z) _ hprime (Set.disjoint_left.mpr fun a ha haI => ha (hle haI))

/-- The propagation from the generic point: at a point `z` of an integral centre `Z` with generic
point `η`, the order of `I_z` along the prime `Z_z` — the order in the localization
`(𝒪_{X,z})_{Z_z} = 𝒪_{X,η}` — is `ord_η I`. -/
theorem ordAlong_stalkIdeal_eq_ord_stalkIdeal {η z : X}
    (hη : IsGenericPoint η (Z.support : Set X)) (hz : z ∈ Z.support)
    [hP : (Z.stalkIdeal z).IsPrime] :
    IsLocalRing.ordAlong (Z.stalkIdeal z) (I.stalkIdeal z) =
      IsLocalRing.ord (I.stalkIdeal η) := by
  classical
  obtain ⟨U, hzU⟩ := exists_affineOpens_mem z
  have hU : IsAffineOpen U.1 := U.2
  have hηz : η ⤳ z := hη.specializes hz
  have hηU : η ∈ U.1 := hηz.mem_open U.1.2 hzU
  obtain ⟨z', hz'⟩ := Z.exists_subschemeι_eq hz
  have hprime : (Z.ideal U).IsPrime := isPrime_ideal_of_isIntegral_subscheme Z U (hz' ▸ hzU)
  have hle : Z.ideal U ≤ (hU.primeIdealOf ⟨z, hzU⟩).asIdeal :=
    (mem_zeroLocus_iff_le_primeIdealOf U hzU _).mp ((mem_support_iff_of_mem hzU).mp hz)
  have hdisj : Disjoint ((hU.primeIdealOf ⟨z, hzU⟩).asIdeal.primeCompl : Set Γ(X, U))
      (Z.ideal U : Set Γ(X, U)) :=
    Set.disjoint_left.mpr fun a ha haI => ha (hle haI)
  -- the generic point of `Z` is the point of the prime `Z(U)`
  let y : PrimeSpectrum Γ(X, U) := ⟨Z.ideal U, hprime⟩
  have hyU : hU.fromSpec y ∈ (U.1 : Set X) := by
    rw [← hU.range_fromSpec]
    exact ⟨y, rfl⟩
  have hyη : hU.fromSpec y = η := by
    have hpid : hU.primeIdealOf ⟨hU.fromSpec y, hyU⟩ = y :=
      hU.fromSpec.isOpenEmbedding.injective (hU.fromSpec_primeIdealOf ⟨hU.fromSpec y, hyU⟩)
    have hmem : hU.fromSpec y ∈ Z.support :=
      (mem_support_iff_of_mem hyU).mpr ((mem_zeroLocus_iff_le_primeIdealOf U hyU _).mpr
        (by rw [hpid]))
    have h1 : hU.fromSpec y ⤳ η := by
      have hηy : Z.ideal U ≤ (hU.primeIdealOf ⟨η, hηU⟩).asIdeal :=
        (mem_zeroLocus_iff_le_primeIdealOf U hηU _).mp ((mem_support_iff_of_mem hηU).mp hη.mem)
      have h2 : y ⤳ hU.primeIdealOf ⟨η, hηU⟩ := (PrimeSpectrum.le_iff_specializes _ _).mp hηy
      have h3 := h2.map hU.fromSpec.continuous
      rwa [hU.fromSpec_primeIdealOf] at h3
    have hgen : IsGenericPoint (hU.fromSpec y) (Z.support : Set X) := by
      rw [isGenericPoint_iff_specializes]
      intro q
      constructor
      · intro h
        exact h.mem_closed Z.support.isClosed hmem
      · intro hq
        exact h1.trans (hη.specializes hq)
    exact hgen.eq hη
  subst hyη
  -- the two stalks as localizations of `Γ(U)`
  let := TopCat.Presheaf.algebra_section_stalk X.presheaf (⟨z, hzU⟩ : U.1)
  have hloc_z := hU.isLocalization_stalk ⟨z, hzU⟩
  let := TopCat.Presheaf.algebra_section_stalk X.presheaf (⟨hU.fromSpec y, hyU⟩ : U.1)
  have hloc_η := hU.isLocalization_stalk' y hyU
  set P := Z.stalkIdeal z with hPdef
  have hPmap : P = (Z.ideal U).map (algebraMap Γ(X, U) (X.presheaf.stalk z)) :=
    stalkIdeal_eq_map_germ Z U hzU
  have hcomap : P.comap (algebraMap Γ(X, U) (X.presheaf.stalk z)) = Z.ideal U := by
    rw [hPmap]
    exact IsLocalization.under_map_of_isPrime_disjoint
      (hU.primeIdealOf ⟨z, hzU⟩).asIdeal.primeCompl (X.presheaf.stalk z) hprime hdisj
  have hT : IsLocalization (Z.ideal U).primeCompl (Localization.AtPrime P) := by
    have h1 := IsLocalization.isLocalization_isLocalization_atPrime_isLocalization
      (hU.primeIdealOf ⟨z, hzU⟩).asIdeal.primeCompl (Localization.AtPrime P) P
    have hsub : (Z.ideal U).primeCompl =
        (P.comap (algebraMap Γ(X, U) (X.presheaf.stalk z))).primeCompl := by
      ext a
      change a ∉ Z.ideal U ↔ a ∉ P.comap (algebraMap Γ(X, U) (X.presheaf.stalk z))
      rw [hcomap]
    rw [hsub]
    exact h1
  have hloc_η' : IsLocalization (Z.ideal U).primeCompl (X.presheaf.stalk (hU.fromSpec y)) :=
    hloc_η
  let e := IsLocalization.algEquiv (Z.ideal U).primeCompl (Localization.AtPrime P)
    (X.presheaf.stalk (hU.fromSpec y))
  unfold IsLocalRing.ordAlong
  have hI : I.stalkIdeal z = (I.ideal U).map (algebraMap Γ(X, U) (X.presheaf.stalk z)) :=
    stalkIdeal_eq_map_germ I U hzU
  have hIη : I.stalkIdeal (hU.fromSpec y) =
      (I.ideal U).map (algebraMap Γ(X, U) (X.presheaf.stalk (hU.fromSpec y))) :=
    stalkIdeal_eq_map_germ I U hyU
  rw [hI, Ideal.map_map, hIη, ← ord_map_ringEquiv e.toRingEquiv, Ideal.map_map]
  congr 2
  refine RingHom.ext fun a => ?_
  change e ((algebraMap (X.presheaf.stalk z) (Localization.AtPrime P))
    ((algebraMap Γ(X, U) (X.presheaf.stalk z)) a)) = _
  rw [← IsScalarTower.algebraMap_apply]
  exact e.commutes a

end Generic

/-- `le_ordAlong_chartCenter_iff` of `Hironaka/Algebra/Local/SymbolicPower.lean` transported along
an identification of the prime with a `chartCenter`: `m ≤ ord_P I` gives `I ≤ P^m`. -/
theorem le_pow_of_le_ordAlong_of_eq_chartCenter {R : Type u} [CommRing R] [IsRegularLocalRing R]
    [Algebra ℚ R] {n : ℕ} (x : Fin n → R) (hx : maximalIdeal R = Ideal.span (Set.range x))
    (hn : (n : WithBot ℕ∞) = ringKrullDim R) (r : Fin n) (P : Ideal R) [P.IsPrime]
    (hP : P = chartCenter x r) (I : Ideal R) (m : ℕ) (h : (m : ℕ∞) ≤ IsLocalRing.ordAlong P I) :
    I ≤ P ^ m := by
  subst hP
  exact (le_ordAlong_chartCenter_iff x hx hn r I m).mp h

/-! ### The order along the centre bounds the exceptional multiplicity from below -/

section Global

variable {k : Type u} [Field k] [CharZero k] (f : X ⟶ Spec (.of k)) (n r : ℕ)
  [SmoothOfRelativeDimension n f] (Z : X.IdealSheafData)
  [SmoothOfRelativeDimension (n - r) (Z.subschemeι ≫ f)] (hr : 1 ≤ r) (hrn : r ≤ n)
  (I : X.IdealSheafData) {η : X} (hη : IsGenericPoint η (Z.support : Set X))

include f n r hr hrn hη

/-- If `m ≤ ord_Z I` then `I ≤ Z^m` (the hypothesis of [Kol07, Definition 60]; the argument at
every point of `Z` is the library's own). -/
theorem le_pow_of_le_ord (m : ℕ) (hm : (m : ℕ∞) ≤ I.ord η) : I ≤ Z ^ m := by
  classical
  have : Smooth f := SmoothOfRelativeDimension.smooth n f
  have : Smooth (Z.subschemeι ≫ f) := SmoothOfRelativeDimension.smooth (n - r) _
  have hint : IsIntegral Z.subscheme := isIntegral_subscheme_of_smooth f Z hη
  refine le_of_stalkIdeal_le fun z => ?_
  rw [stalkIdeal_pow]
  by_cases hz : z ∈ Z.support
  · have hP := isPrime_stalkIdeal_of_mem_support Z hz
    have hord : (m : ℕ∞) ≤ IsLocalRing.ordAlong (Z.stalkIdeal z) (I.stalkIdeal z) := by
      rw [ordAlong_stalkIdeal_eq_ord_stalkIdeal Z I hη hz, ← ord_eq_ord_stalkIdeal]
      exact hm
    have := isRegularLocalRing_stalk f z
    let := f.stalkAlgebraRat z
    obtain ⟨m', y, hm', hy, hZ⟩ := exists_adaptedParameters Z f n r hrn hz
    rcases Nat.eq_zero_or_pos m' with hm0 | hm0
    · -- `𝒪_{X,z}` is a field: `Z_z = 0` and `I_z = 0` (the order at `z` is at least `m ≥ 1`)
      subst hm0
      have hZ0 : Z.stalkIdeal z = ⊥ := by
        rw [hZ, Set.eq_empty_of_isEmpty ({j : Fin 0 | j.val < r}), Set.image_empty,
          Ideal.span_empty]
      have hmax : maximalIdeal (X.presheaf.stalk z) = ⊥ := by
        rw [hy, Set.range_eq_empty, Ideal.span_empty]
      rw [hZ0]
      rcases Nat.eq_zero_or_pos m with h0 | h0
      · subst h0
        rw [pow_zero, Ideal.one_eq_top]
        exact le_top
      · rw [Ideal.bot_pow (Nat.pos_iff_ne_zero.mp h0), ← hmax, ← pow_one (maximalIdeal _)]
        refine (Scheme.IdealSheafData.le_ord_iff I z).mp ?_
        exact le_trans (by exact_mod_cast h0) (hm.trans (ord_le_ord_of_specializes I f n
          (hη.specializes hz)))
    · -- `Z_z = chartCenter y ρ`; the symbolic power is the ordinary power
      let ρ : Fin m' := ⟨min (r - 1) (m' - 1), by omega⟩
      have hset : {j : Fin m' | j.val < r} = {j | j ≤ ρ} := by
        ext j
        change j.val < r ↔ j ≤ ρ
        rw [Fin.le_def]
        change j.val < r ↔ j.val ≤ min (r - 1) (m' - 1)
        have := j.2
        omega
      have hZ' : Z.stalkIdeal z = chartCenter y ρ := by
        rw [hZ, hset]
        rfl
      exact le_pow_of_le_ordAlong_of_eq_chartCenter y hy hm' ρ (Z.stalkIdeal z) hZ'
        (I.stalkIdeal z) m hord
  · rw [stalkIdeal_eq_top_of_notMem_support Z hz, Ideal.top_pow]
    exact le_top

/-- [Kol07, Definition 47]; [Hau14, Definition 6.8]: if `m ≤ ord_Z I` then `F^m` divides the
total transform `I^*` — `F = Z·𝒪_B` being invertible, `I^* ≤ F^m` suffices. -/
theorem exceptionalDivisor_pow_dvd_comap_of_le_ord (m : ℕ) (hm : (m : ℕ∞) ≤ I.ord η) :
    (Z.comap (blowUpπ Z)) ^ m ∣ I.comap (blowUpπ Z) := by
  have h1 : I.comap (blowUpπ Z) ≤ (Z ^ m).comap (blowUpπ Z) :=
    comap_mono (blowUpπ Z) (le_pow_of_le_ord f n r Z hr hrn I hη m hm)
  rw [comap_pow] at h1
  exact pow_dvd_of_le_pow_of_isInvertible (blowUp.isBlowUp Z).admissible h1

end Global

end AlgebraicGeometry
