/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Wlo05.EmbeddedAdmissibleStratum
public import Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4Chart
import Hironaka.Algebra.RegularSmooth.RegularSmoothEquiv
import Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4NewCoords
import Hironaka.Scheme.IdealSheaf.Order.Semicontinuity
import Hironaka.Scheme.Snc.HasSncWith
import Hironaka.Scheme.Snc.TotalTransformOnCentre
import Hironaka.Scheme.Snc.TotalTransformSnc
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# One blow-up along an admissible chain stratum (CP4)

The statement CP4 of the embedded desingularization
(`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedChainRelative`): blowing up an admissible chain
stratum `Z` (`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedAdmissibleStratum`) of a protected
component `Γ` keeps the strict transform `Γ̃` smooth and with simple normal crossings with the total
transform of the boundary, and transports the K-shape of `K` (and the un-isolated form of `I`, also
along a terminal-normal stratum) to the mark-`1` transforms along `Γ̃`
(`chainRelativeKAt_strictTransform`, `chainRelativeAt_strictTransform`).

**The proof.** Everything is pointwise at a point `q` of the blow-up on `Γ̃`, over `p = π(q) ∈ Γ`.
Off the exceptional divisor `π^*` is an isomorphism of stalks and the forms transport verbatim
(`chainRelativeKAt_totalTransform_of_notMem`,
`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4NewCoords`). On the exceptional divisor `p ∈ Z ∩ Γ`
and admissibility gives chain coordinates `z` at `p` with `Z_p = (f_i : i < l) + (e_j : j ∈ s)`; the
chart datum of `Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4Chart` (the pivot `e_{j₀}`, the
induced coordinates `w`, the new parameters `z'`) computes `Γ̃_q = (w ∘ σ)` and the members' strict
transforms, and — with the ε-order bookkeeping of
`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4Algebra` under the admissibility condition (★) — the
mark-`1` transforms as chain forms in the new parameters. The local rings of the blow-up are regular
by the chart theorem in its pointwise form
(`exists_totalTransformData_of_mem_support_of_specializes`: the snc data are needed only at the
points of `Z` below `p`, all in `Z ∩ Γ`). Smoothness of `Γ̃` over `k` is regularity of its local
rings — `𝒪_{B,q}/Γ̃_q` with `Γ̃_q` generated by part of a regular system of parameters
(`isRegularLocalRing_stalk_subscheme`) — through `Scheme.smooth_iff_isRegular`.

The chart is that of [Kol07, Definition 60]. CP4 is not in the literature; it is consumed by the
loop invariant CP5 (`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP5`).
-/

@[expose] public section

universe u

open CategoryTheory AlgebraicGeometry TopologicalSpace IsLocalRing Ideal
  Scheme.IdealSheafData Scheme BlowUpSequence IdealSheafData

namespace Hironaka.Resolution

variable {X : Scheme.{u}}

/-! ### snc data with the stratum as a coordinate subspace -/

section Data

variable (E : DivisorFamily X) (Γ Z : X.IdealSheafData)

/-- Kollár's snc data at `x` with `Z` a coordinate subspace ([Kol07, Definition 24]) — the
pointwise hypothesis of the chart theorem. -/
def SncDataWith (x : X) : Prop :=
  ∃ (n : ℕ) (z : Fin n → X.presheaf.stalk x),
    (span (Set.range z) = maximalIdeal (X.presheaf.stalk x) ∧
      (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk x)) ∧
    (∃ c : {i : E.ι // x ∈ (E.component i).support} → Fin n, Function.Injective c ∧
      ∀ i, (E.component i.1).stalkIdeal x = span {z (c i)}) ∧
    ∃ s : Finset (Fin n), Z.stalkIdeal x = span (z '' ↑s)

/-- An admissible chain stratum (K-form) carries snc data with `Z` a coordinate subspace. -/
theorem sncDataWith_of_admissibleK {K : X.IdealSheafData} {x : X}
    (h : AdmissibleChainStratumKAt E K Γ Z x) : SncDataWith E Z x := by
  obtain ⟨n, z, c, r, σ, a, b, l, -, s, ⟨hz, hcinj, hc, -, -, -, -⟩, -, -, -, hZ, -⟩ := h
  exact ⟨n, z, hz, ⟨c, hcinj, hc⟩, stratumCoords σ s l, hZ.trans (span_image_comp_sup_eq σ s z l)⟩

/-- An admissible chain stratum (un-isolated form) carries snc data with `Z` a coordinate
subspace. -/
theorem sncDataWith_of_admissibleAt {I : X.IdealSheafData} {x : X}
    (h : AdmissibleChainStratumAt E I Γ Z x) : SncDataWith E Z x := by
  obtain ⟨n, z, c, r, σ, a, b, l, -, s, ⟨hz, hcinj, hc, -, -, -, -⟩, -, -, -, hZ, -⟩ := h
  exact ⟨n, z, hz, ⟨c, hcinj, hc⟩, stratumCoords σ s l, hZ.trans (span_image_comp_sup_eq σ s z l)⟩

/-- The chain and the whole coordinate range agree at level `r + 1`. -/
theorem span_range_comp_sup_eq {R : Type*} [CommRing R] {n r : ℕ} (z : Fin n → R)
    (σ : Fin (r + 1) → Fin n) (s : Finset (Fin n)) :
    span (Set.range (z ∘ σ)) ⊔ span (z '' ↑s) = span (z '' ↑(stratumCoords σ s (r + 1))) := by
  rw [← span_image_comp_sup_eq σ s z (r + 1)]
  congr 2
  rw [show {i : Fin (r + 1) | i.val < r + 1} = Set.univ from Set.eq_univ_of_forall fun i => i.2,
    Set.image_univ]

/-- A terminal-normal stratum carries snc data with `Z` a coordinate subspace. -/
theorem sncDataWith_of_terminalNormal {I : X.IdealSheafData} {x : X}
    (h : TerminalNormalStratumAt E I Γ Z x) : SncDataWith E Z x := by
  obtain ⟨n, z, c, r, σ, a, b, s, ⟨hz, hcinj, hc, -, -, -, -⟩, -, -, -, -, hZ⟩ := h
  exact ⟨n, z, hz, ⟨c, hcinj, hc⟩, stratumCoords σ s (r + 1),
    hZ.trans (span_range_comp_sup_eq z σ s)⟩

variable {k : Type u} [Field k] [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]

include f in
/-- The regularity of the blow-up's local rings, pointwise: at a point `q` of the exceptional
divisor over a point of `Γ`, when every point of `Z ∩ Γ` carries snc data with `Z`. -/
theorem isRegularLocalRing_stalk_blowUp_of_sncDataWith {q : IdealSheafData.blowUp Z}
    (hq : q ∈ (Z.comap (IdealSheafData.blowUpπ Z)).support) (hΓ : IdealSheafData.blowUpπ Z q ∈
        Γ.support)
    (hdata : ∀ x ∈ Z.support, x ∈ Γ.support → SncDataWith E Z x) :
    IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q) :=
  (exists_totalTransformData_of_mem_support_of_specializes f E.component Z q hq
    fun x hx hspec => hdata x hx (hspec.mem_closed Γ.support.isClosed hΓ)).1.1

end Data

/-! ### The ε-order conditions from (★) -/

section Star

variable {n r : ℕ} (σ : Fin (r + 1) → Fin n) (s : Finset (Fin n))

/-- The ε-order `[i < l]` of the `i`-th chain equation along the stratum `(f_i : i < l) + (e_s)`. -/
def δAdm (l : ℕ) (i : Fin (r + 1)) : ℕ := if i.val < l then 1 else 0

theorem δAdm_eq (hσ : Function.Injective σ) (hs : ∀ i, σ i ∉ s) (l : ℕ) (i : Fin (r + 1)) :
    (if σ i ∈ stratumCoords σ s l then 1 else 0) = δAdm l i := by
  unfold δAdm
  simp only [mem_stratumCoords_iff σ s hσ hs]

/-- A positive entry makes the total exponent positive. -/
theorem one_le_sum_of_exists {c : Fin n → ℕ} (h : ∃ k ∈ s, c k ≠ 0) : 1 ≤ ∑ k ∈ s, c k := by
  obtain ⟨k, hk, hck⟩ := h
  exact le_trans (Nat.one_le_iff_ne_zero.mpr hck)
    (Finset.single_le_sum (fun _ _ => Nat.zero_le _) hk)

variable (a : Fin (r + 1) → Fin n → ℕ) (b : Fin n → ℕ) (hb : ∀ k, b k ≠ 0 → k ∉ Set.range σ)
  (ha : ∀ i k, a i k ≠ 0 → k ∉ Set.range σ) (l : ℕ) (hl : l ≤ r)

include hb hl in
/-- (★) at level `0`: the K-form's first ε-order is positive. -/
theorem one_le_epsOrderC_K (h₁ : l = 0 → ∃ k ∈ s, b k ≠ 0) :
    1 ≤ epsOrderC (stratumCoords σ s l) a b (Function.update (δAdm l) (Fin.last r) 0) 0 := by
  rw [epsOrderC, epsOrder_zero, sum_stratumCoords_eq σ s l b hb]
  by_cases hl0 : l = 0
  · have := one_le_sum_of_exists s (h₁ hl0)
    omega
  · rcases Nat.eq_zero_or_pos r with hr | hr
    · omega
    · have hne : (0 : Fin (r + 1)) ≠ Fin.last r := by
        intro h
        have := congrArg Fin.val h
        simp only [Fin.val_zero, Fin.val_last] at this
        omega
      rw [Function.update_of_ne hne, δAdm, ite_eq_left (by simp only [Fin.val_zero]; omega)]
      omega

include hb in
/-- (★) at level `0`: the un-isolated form's first ε-order is positive. -/
theorem one_le_epsOrderC_I (h₁ : l = 0 → ∃ k ∈ s, b k ≠ 0) :
    1 ≤ epsOrderC (stratumCoords σ s l) a b (δAdm l) 0 := by
  rw [epsOrderC, epsOrder_zero, sum_stratumCoords_eq σ s l b hb]
  by_cases hl0 : l = 0
  · have := one_le_sum_of_exists s (h₁ hl0)
    omega
  · rw [δAdm, ite_eq_left (by simp only [Fin.val_zero]; omega)]
    omega

include ha hl in
/-- (★) at the stratum's level: the un-isolated form's ε-orders are non-decreasing. -/
theorem epsOrderC_I_mono (h₂ : 0 < l → ∃ k ∈ s, a ⟨l - 1, by omega⟩ k ≠ 0) (i : Fin r) :
    epsOrderC (stratumCoords σ s l) a b (δAdm l) i.castSucc ≤
      epsOrderC (stratumCoords σ s l) a b (δAdm l) i.succ := by
  refine epsOrder_mono_of _ _ _ (fun i => ?_) i
  simp only [sum_stratumCoords_eq σ s l (a _) (ha _), δAdm, Fin.val_castSucc, Fin.val_succ]
  by_cases hi : i.val < l
  · rw [ite_eq_left hi]
    by_cases hi1 : i.val + 1 < l
    · rw [ite_eq_left hi1]
      omega
    · have hl' : l = i.val + 1 := by omega
      have := one_le_sum_of_exists s (h₂ (by omega))
      have hidx : (⟨l - 1, by omega⟩ : Fin (r + 1)) = i.castSucc := Fin.ext (by
        simp only [Fin.val_castSucc]; omega)
      rw [hidx] at this
      omega
  · rw [ite_eq_right hi]
    omega

include ha hl in
/-- (★) at the stratum's level: the K-form's ε-orders are non-decreasing (the last generator
carries no equation). -/
theorem epsOrderC_K_mono (h₂ : 0 < l → ∃ k ∈ s, a ⟨l - 1, by omega⟩ k ≠ 0) (i : Fin r) :
    epsOrderC (stratumCoords σ s l) a b (Function.update (δAdm l) (Fin.last r) 0) i.castSucc ≤
      epsOrderC (stratumCoords σ s l) a b (Function.update (δAdm l) (Fin.last r) 0) i.succ := by
  refine epsOrder_mono_of _ _ _ (fun i => ?_) i
  have hcs : Function.update (δAdm l) (Fin.last r) 0 i.castSucc = δAdm l i.castSucc :=
    Function.update_of_ne (Fin.castSucc_lt_last i).ne _ _
  rw [hcs, sum_stratumCoords_eq σ s l (a _) (ha _)]
  simp only [δAdm, Fin.val_castSucc]
  by_cases hi : i.val < l
  · rw [ite_eq_left hi]
    by_cases hsucc : i.succ = Fin.last r
    · have hval : i.val + 1 = r := by
        have := congrArg Fin.val hsucc
        simpa using this
      have := one_le_sum_of_exists s (h₂ (by omega))
      have hidx : (⟨l - 1, by omega⟩ : Fin (r + 1)) = i.castSucc := Fin.ext (by
        simp only [Fin.val_castSucc]; omega)
      rw [hidx] at this
      omega
    · rw [Function.update_of_ne hsucc]
      simp only [δAdm, Fin.val_succ]
      by_cases hi1 : i.val + 1 < l
      · rw [ite_eq_left hi1]
        omega
      · have := one_le_sum_of_exists s (h₂ (by omega))
        have hidx : (⟨l - 1, by omega⟩ : Fin (r + 1)) = i.castSucc := Fin.ext (by
          simp only [Fin.val_castSucc]; omega)
        rw [hidx] at this
        omega
  · rw [ite_eq_right hi]
    omega

/-- Along a terminal-normal stratum every chain equation is an equation of the centre. -/
theorem δ_terminal_eq (hσ : Function.Injective σ) (hs : ∀ i, σ i ∉ s) (i : Fin (r + 1)) :
    (if σ i ∈ stratumCoords σ s (r + 1) then 1 else 0) = 1 := by
  rw [ite_eq_left ((mem_stratumCoords_iff σ s hσ hs (r + 1) i).mpr i.2)]

/-- The un-isolated form's ε-orders along a terminal-normal stratum are positive and
non-decreasing without any exponent condition. -/
theorem one_le_epsOrderC_terminal :
    1 ≤ epsOrderC (stratumCoords σ s (r + 1)) a b (fun _ => 1) 0 := by
  rw [epsOrderC, epsOrder_zero]
  omega

theorem epsOrderC_terminal_mono (i : Fin r) :
    epsOrderC (stratumCoords σ s (r + 1)) a b (fun _ => 1) i.castSucc ≤
      epsOrderC (stratumCoords σ s (r + 1)) a b (fun _ => 1) i.succ :=
  epsOrder_mono_of _ _ _ (fun _ => by omega) i

end Star

section Increments

variable {r : ℕ}

/-- The exponent increments `E_{i+1} − E_i` of a sequence of ε-orders (`0` at the last index). -/
def Dexp (Efun : Fin (r + 1) → ℕ) (i : Fin (r + 1)) : ℕ :=
  if h : i.val < r then Efun ⟨i.val + 1, Nat.succ_lt_succ h⟩ - Efun i else 0

theorem Dexp_castSucc (Efun : Fin (r + 1) → ℕ) (i : Fin r) :
    Dexp Efun i.castSucc = Efun i.succ - Efun i.castSucc := by
  unfold Dexp
  rw [dite_eq_left (by simp)]
  rfl

end Increments

/-! ### The pointwise transforms on the exceptional divisor -/

section Pointwise

variable {k : Type u} [Field k] [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]
  (E : DivisorFamily X) (Γ Z : X.IdealSheafData) {q : IdealSheafData.blowUp Z}

/-- The chain avoids `s` when `s` consists of members' coordinates. -/
theorem σ_notMem_of_subset_range {n r : ℕ} {σ : Fin (r + 1) → Fin n} {s : Finset (Fin n)}
    {ι : Type*} {c : ι → Fin n} (hσc : ∀ i j, σ i ≠ c j) (hs : ↑s ⊆ Set.range c) (i : Fin (r + 1)) :
    σ i ∉ s := fun hi => by
  obtain ⟨j, hj⟩ := hs hi
  exact hσc i j hj.symm

/-- Exponents supported on members' coordinates vanish on the chain. -/
theorem notMem_range_of_ne_zero {n r : ℕ} {σ : Fin (r + 1) → Fin n} {ι : Type*} {c : ι → Fin n}
    (hσc : ∀ i j, σ i ≠ c j) {cc : Fin n → ℕ} (hcc : ∀ k, cc k ≠ 0 → k ∈ Set.range c) (k : Fin n)
    (hk : cc k ≠ 0) : k ∉ Set.range σ := fun ⟨i, hi⟩ => by
  obtain ⟨j, hj⟩ := hcc k hk
  exact hσc i j (hi.trans hj.symm)

include f in
/-- **CP4 for the K-shape at a point of the exceptional divisor**: the K-shape transports, and `Γ̃`
has snc data with the total transform at `q`; the stalk is regular. -/
theorem chainRelativeKAt_of_mem_support (K : X.IdealSheafData)
    [IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q)] (hq : q ∈ (Z.comap
        (IdealSheafData.blowUpπ Z)).support)
    (hqΓ : q ∈ (Γ.strictTransform Z).support)
    (h : AdmissibleChainStratumKAt E K Γ Z (IdealSheafData.blowUpπ Z q)) :
    ChainRelativeKAt (E.totalTransform Z) (K.markedTransform Z 1) (Γ.strictTransform Z) q ∧
      ∃ (m : ℕ) (z' : Fin m → (IdealSheafData.blowUp Z).presheaf.stalk q),
          (E.totalTransform Z).IsSncAt q z' ∧
        ∃ t : Finset (Fin m), (Γ.strictTransform Z).stalkIdeal q = span (z' '' ↑t) := by
  classical
  have hregp : IsRegularLocalRing (X.presheaf.stalk (IdealSheafData.blowUpπ Z q)) :=
    isRegularLocalRing_stalk f _
  obtain ⟨n, z, c, r, σ, a, b, l, hl, s, hcoords, hb, hK, hs, hZ, h₁, h₂⟩ := h
  obtain ⟨hz, hcinj, hc, hσinj, hσc, ha, hΓ⟩ := id hcoords
  have hσs : ∀ i, σ i ∉ s := σ_notMem_of_subset_range hσc hs
  have hb' : ∀ k, b k ≠ 0 → k ∉ Set.range σ := notMem_range_of_ne_zero hσc hb
  have ha' : ∀ i k, a i k ≠ 0 → k ∉ Set.range σ := fun i => notMem_range_of_ne_zero hσc (ha i)
  have hZC : Z.stalkIdeal (IdealSheafData.blowUpπ Z q) = span (z '' ↑(stratumCoords σ s l)) :=
    hZ.trans (span_image_comp_sup_eq σ s z l)
  obtain ⟨D⟩ := nonempty_chartAt Z q f hz (stratumCoords σ s l) hZC
  have hσc₀ := D.σ_ne_c₀ Γ σ hΓ hqΓ
  have hmem := (D.w_σ_mem_and_stalkIdeal_strictTransform Γ σ hq hΓ hqΓ).1
  have hδ : ∀ i, δAdm l i = if σ i ∈ stratumCoords σ s l then 1 else 0 :=
    fun i => (δAdm_eq σ s hσinj hσs l i).symm
  set δK := Function.update (δAdm l) (Fin.last r) 0 with hδK
  refine ⟨⟨D.m, D.z', fun j' => D.newMemberIdx E c hq j'.1, r, D.newChain σ hmem,
    fun i => D.newExp (Dexp (epsOrderC (stratumCoords σ s l) a b δK) i) (a i),
    D.newExp (epsOrderC (stratumCoords σ s l) a b δK 0 - 1) b,
    D.chainCoords_totalTransform E Γ c σ a hq hcoords hqΓ _,
    fun k' hk' => D.newExp_support E c hq hz hc _ _ hb k' hk', ?_⟩,
    D.m, D.z', D.isSncAt_totalTransform E c hq hz hcinj hc,
    Finset.univ.image (D.newChain σ hmem), ?_⟩
  · exact D.stalkIdeal_markedTransform_chainKIdeal σ a hq hσc₀ hmem b K hK (δAdm l) hδ
      (one_le_epsOrderC_K σ s a b hb' l hl h₁) (epsOrderC_K_mono σ s a b ha' l hl h₂) _
      (fun i => Dexp_castSucc _ i)
  · rw [(D.w_σ_mem_and_stalkIdeal_strictTransform Γ σ hq hΓ hqΓ).2, Finset.coe_image,
      Finset.coe_univ, Set.image_univ, ← Set.range_comp]
    exact congrArg span (congrArg Set.range (funext fun i => (D.z'_newChain σ hmem i).symm))

include f in
/-- **CP4 for the un-isolated form at a point of the exceptional divisor, admissible
stratum**. -/
theorem chainRelativeAt_of_mem_support_of_admissible (I : X.IdealSheafData)
    [IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q)] (hq : q ∈ (Z.comap
        (IdealSheafData.blowUpπ Z)).support)
    (hqΓ : q ∈ (Γ.strictTransform Z).support)
    (h : AdmissibleChainStratumAt E I Γ Z (IdealSheafData.blowUpπ Z q)) :
    ChainRelativeAt (E.totalTransform Z) (I.markedTransform Z 1) (Γ.strictTransform Z) q := by
  classical
  have hregp : IsRegularLocalRing (X.presheaf.stalk (IdealSheafData.blowUpπ Z q)) :=
    isRegularLocalRing_stalk f _
  obtain ⟨n, z, c, r, σ, a, b, l, hl, s, hcoords, hb, hI, hs, hZ, h₁, h₂⟩ := h
  obtain ⟨hz, hcinj, hc, hσinj, hσc, ha, hΓ⟩ := id hcoords
  have hσs : ∀ i, σ i ∉ s := σ_notMem_of_subset_range hσc hs
  have hb' : ∀ k, b k ≠ 0 → k ∉ Set.range σ := notMem_range_of_ne_zero hσc hb
  have ha' : ∀ i k, a i k ≠ 0 → k ∉ Set.range σ := fun i => notMem_range_of_ne_zero hσc (ha i)
  have hZC : Z.stalkIdeal (IdealSheafData.blowUpπ Z q) = span (z '' ↑(stratumCoords σ s l)) :=
    hZ.trans (span_image_comp_sup_eq σ s z l)
  obtain ⟨D⟩ := nonempty_chartAt Z q f hz (stratumCoords σ s l) hZC
  have hσc₀ := D.σ_ne_c₀ Γ σ hΓ hqΓ
  have hmem := (D.w_σ_mem_and_stalkIdeal_strictTransform Γ σ hq hΓ hqΓ).1
  have hδ : ∀ i, δAdm l i = if σ i ∈ stratumCoords σ s l then 1 else 0 :=
    fun i => (δAdm_eq σ s hσinj hσs l i).symm
  refine ⟨D.m, D.z', fun j' => D.newMemberIdx E c hq j'.1, r, D.newChain σ hmem,
    fun i => D.newExp (Dexp (epsOrderC (stratumCoords σ s l) a b (δAdm l)) i) (a i),
    D.newExp (epsOrderC (stratumCoords σ s l) a b (δAdm l) 0 - 1) b,
    D.chainCoords_totalTransform E Γ c σ a hq hcoords hqΓ _,
    fun k' hk' => D.newExp_support E c hq hz hc _ _ hb k' hk', ?_⟩
  exact D.stalkIdeal_markedTransform_chainIdeal σ a hq hσc₀ hmem b I hI (δAdm l) hδ
    (one_le_epsOrderC_I σ s a b hb' l h₁) (epsOrderC_I_mono σ s a b ha' l hl h₂) _
    (fun i => Dexp_castSucc _ i)

include f in
/-- **CP4 for the un-isolated form at a point of the exceptional divisor, terminal-normal
stratum**. -/
theorem chainRelativeAt_of_mem_support_of_terminal (I : X.IdealSheafData)
    [IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q)] (hq : q ∈ (Z.comap
        (IdealSheafData.blowUpπ Z)).support)
    (hqΓ : q ∈ (Γ.strictTransform Z).support)
    (h : TerminalNormalStratumAt E I Γ Z (IdealSheafData.blowUpπ Z q)) :
    ChainRelativeAt (E.totalTransform Z) (I.markedTransform Z 1) (Γ.strictTransform Z) q := by
  classical
  have hregp : IsRegularLocalRing (X.presheaf.stalk (IdealSheafData.blowUpπ Z q)) :=
    isRegularLocalRing_stalk f _
  obtain ⟨n, z, c, r, σ, a, b, s, hcoords, hb, hI, hs, -, hZ⟩ := h
  obtain ⟨hz, hcinj, hc, hσinj, hσc, ha, hΓ⟩ := id hcoords
  have hσs : ∀ i, σ i ∉ s := σ_notMem_of_subset_range hσc hs
  have hZC : Z.stalkIdeal (IdealSheafData.blowUpπ Z q) = span (z '' ↑(stratumCoords σ s (r + 1))) :=
    hZ.trans (span_range_comp_sup_eq z σ s)
  obtain ⟨D⟩ := nonempty_chartAt Z q f hz (stratumCoords σ s (r + 1)) hZC
  have hσc₀ := D.σ_ne_c₀ Γ σ hΓ hqΓ
  have hmem := (D.w_σ_mem_and_stalkIdeal_strictTransform Γ σ hq hΓ hqΓ).1
  have hδ : ∀ i, (fun _ : Fin (r + 1) => (1 : ℕ)) i =
      if σ i ∈ stratumCoords σ s (r + 1) then 1 else 0 :=
    fun i => (δ_terminal_eq σ s hσinj hσs i).symm
  refine ⟨D.m, D.z', fun j' => D.newMemberIdx E c hq j'.1, r, D.newChain σ hmem,
    fun i => D.newExp (Dexp (epsOrderC (stratumCoords σ s (r + 1)) a b fun _ => 1) i) (a i),
    D.newExp (epsOrderC (stratumCoords σ s (r + 1)) a b (fun _ => 1) 0 - 1) b,
    D.chainCoords_totalTransform E Γ c σ a hq hcoords hqΓ _,
    fun k' hk' => D.newExp_support E c hq hz hc _ _ hb k' hk', ?_⟩
  exact D.stalkIdeal_markedTransform_chainIdeal σ a hq hσc₀ hmem b I hI (fun _ => 1) hδ
    (one_le_epsOrderC_terminal σ s a b) (epsOrderC_terminal_mono σ s a b) _
    (fun i => Dexp_castSucc _ i)

end Pointwise

/-! ### The statements -/

section Main

variable {k : Type u} [Field k] [CharZero k]

/-- Membership in the meet of two supports. -/
theorem mem_inf_support {Z Γ : X.IdealSheafData} {p : X} (hZ : p ∈ Z.support) (hΓ : p ∈ Γ.support) :
    p ∈ Z.support ⊓ Γ.support := by
  change p ∈ ((Z.support ⊓ Γ.support : Closeds X) : Set X)
  rw [Closeds.coe_inf]
  exact ⟨hZ, hΓ⟩

/-- The pointwise content of CP4-K at every point of `Γ̃`, with the regularity of the stalk. -/
theorem cp4K_pointwise (f : X ⟶ Spec (CommRingCat.of k)) [Smooth f] (E : DivisorFamily X)
    (K Γ Z : X.IdealSheafData) (hΓ : E.HasSncWith Γ)
    (hK : ∀ p ∈ Γ.support, ChainRelativeKAt E K Γ p)
    (hZ : ∀ p ∈ Z.support ⊓ Γ.support, AdmissibleChainStratumKAt E K Γ Z p)
    (q : IdealSheafData.blowUp Z) (hqΓ : q ∈ (Γ.strictTransform Z).support) :
    IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q) ∧
      ChainRelativeKAt (E.totalTransform Z) (K.markedTransform Z 1) (Γ.strictTransform Z) q ∧
      ∃ (m : ℕ) (z' : Fin m → (IdealSheafData.blowUp Z).presheaf.stalk q),
          (E.totalTransform Z).IsSncAt q z' ∧
        ∃ t : Finset (Fin m), (Γ.strictTransform Z).stalkIdeal q = span (z' '' ↑t) := by
  have : PerfectField k := PerfectField.ofCharZero
  have hpΓ : IdealSheafData.blowUpπ Z q ∈ Γ.support :=
    π_mem_support_of_mem_support_strictTransformAlong Z Γ q hqΓ
  by_cases hq : q ∈ (Z.comap (IdealSheafData.blowUpπ Z)).support
  · have hpZ : IdealSheafData.blowUpπ Z q ∈ Z.support := (mem_support_comap_iff' Z _ q).mp hq
    have hreg : IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q) :=
      isRegularLocalRing_stalk_blowUp_of_sncDataWith E Γ Z f hq hpΓ fun x hx hxΓ =>
        sncDataWith_of_admissibleK E Γ Z (hZ x (mem_inf_support hx hxΓ))
    exact ⟨hreg, chainRelativeKAt_of_mem_support f E Γ Z K hq hqΓ (hZ _ (mem_inf_support hpZ hpΓ))⟩
  · have hiso := isIso_stalkMap_π_of_notMem_support Z hq
    have hreg : IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q) := by
      have := isRegularLocalRing_stalk f (IdealSheafData.blowUpπ Z q)
      exact IsRegularLocalRing.of_ringEquiv (stalkMapπEquiv Z hq)
    obtain ⟨n, z, hsnc, t, ht⟩ := hΓ _ hpΓ
    obtain ⟨z', hsnc', ht'⟩ := exists_isSncAt_totalTransform_of_notMem E Z hq Γ hsnc ht
    exact ⟨hreg, chainRelativeKAt_totalTransform_of_notMem E Z hq K Γ (hK _ hpΓ), n, z', hsnc', t,
      ht'⟩

/-- **CP4 for the K-shape**: blowing up an admissible chain stratum `Z` — admissibility (★) at
every point of `Z ∩ Γ` — keeps the protected component's strict transform smooth over `k` and snc
with the total transform of the boundary, and transports the K-shape of `K` to the mark-`1`
transform along `Γ̃`. -/
theorem chainRelativeKAt_strictTransform (f : X ⟶ Spec (CommRingCat.of k)) [Smooth f]
    (E : DivisorFamily X) (K Γ Z : X.IdealSheafData) (hE : E.IsSnc)
    (hΓ : E.HasSncWith Γ) (hsm : Smooth (Γ.subschemeι ≫ f))
    (hK : ∀ p ∈ Γ.support, ChainRelativeKAt E K Γ p)
    (hZ : ∀ p ∈ Z.support ⊓ Γ.support, AdmissibleChainStratumKAt E K Γ Z p) :
    Smooth ((Γ.strictTransform Z).subschemeι ≫ Z.blowUpπ ≫ f) ∧
      (E.totalTransform Z).HasSncWith (Γ.strictTransform Z) ∧
      ∀ q ∈ (Γ.strictTransform Z).support,
        ChainRelativeKAt (E.totalTransform Z) (K.markedTransform Z 1) (Γ.strictTransform Z) q := by
  have _hE := hE
  have _hsm := hsm
  have : PerfectField k := PerfectField.ofCharZero
  have haux := cp4K_pointwise f E K Γ Z hΓ hK hZ
  refine ⟨?_, fun q hq => (haux q hq).2.2, fun q hq => (haux q hq).2.1⟩
  have hLN : IsLocallyNoetherian X := f.isLocallyNoetherian_of_field
  have hπ : IsProper Z.blowUpπ := blowUp.isProper_π Z
  rw [Scheme.smooth_iff_isRegular]
  refine ⟨fun w => ?_⟩
  have hqw := subschemeι_mem_support (Γ.strictTransform Z) w
  obtain ⟨hreg, -, m, z', hsnc, t, ht⟩ := haux _ hqw
  exact isRegularLocalRing_stalk_subscheme (Γ.strictTransform Z) w hsnc.1 ht

/-- **CP4 for the un-isolated form**: the chain-relative form of `I` is transported along the
blow-up of an admissible chain stratum (one unit of exponent consumed at the stratum's level) or of
a terminal-normal stratum (no unit consumed) — one statement, two transform rules inside. -/
theorem chainRelativeAt_strictTransform (f : X ⟶ Spec (CommRingCat.of k)) [Smooth f]
    (E : DivisorFamily X) (I Γ Z : X.IdealSheafData)
    (hE : E.IsSnc) (hΓ : E.HasSncWith Γ) (hI : ∀ p ∈ Γ.support, ChainRelativeAt E I Γ p)
    (hZ : ∀ p ∈ Z.support ⊓ Γ.support,
      AdmissibleChainStratumAt E I Γ Z p ∨ TerminalNormalStratumAt E I Γ Z p) :
    ∀ q ∈ (Γ.strictTransform Z).support,
      ChainRelativeAt (E.totalTransform Z) (I.markedTransform Z 1) (Γ.strictTransform Z) q := by
  have _hE := hE
  have _hΓ := hΓ
  have : PerfectField k := PerfectField.ofCharZero
  intro q hqΓ
  have hpΓ : IdealSheafData.blowUpπ Z q ∈ Γ.support :=
    π_mem_support_of_mem_support_strictTransformAlong Z Γ q hqΓ
  by_cases hq : q ∈ (Z.comap (IdealSheafData.blowUpπ Z)).support
  · have hpZ : IdealSheafData.blowUpπ Z q ∈ Z.support := (mem_support_comap_iff' Z _ q).mp hq
    have hreg : IsRegularLocalRing ((IdealSheafData.blowUp Z).presheaf.stalk q) :=
      isRegularLocalRing_stalk_blowUp_of_sncDataWith E Γ Z f hq hpΓ fun x hx hxΓ =>
        (hZ x (mem_inf_support hx hxΓ)).elim (sncDataWith_of_admissibleAt E Γ Z)
          (sncDataWith_of_terminalNormal E Γ Z)
    rcases hZ _ (mem_inf_support hpZ hpΓ) with h | h
    · exact chainRelativeAt_of_mem_support_of_admissible f E Γ Z I hq hqΓ h
    · exact chainRelativeAt_of_mem_support_of_terminal f E Γ Z I hq hqΓ h
  · exact chainRelativeAt_totalTransform_of_notMem E Z hq I Γ (hI _ hpΓ)

end Main

end Hironaka.Resolution
