/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4Algebra
import Hironaka.Algebra.Local.Chart
import Hironaka.Algebra.Local.Regular
import Hironaka.Resolution.Algebraic.Wlo05.ChainIdealColonRegular
import Hironaka.Resolution.Algebraic.Wlo05.ChainRelativeLift
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.IdealSheaf.StalkLe
import Hironaka.Scheme.Snc.ChartIndex
import Hironaka.Scheme.Snc.InducedCoordinates
import Hironaka.Scheme.Snc.ParameterSubset
import Hironaka.Scheme.Snc.TotalTransformSnc
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The chart of the blow-up at a point of the exceptional divisor

The local computation for the statement CP4 of the embedded desingularization
(`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedChainRelative`) at a point `q` of the exceptional
divisor `F` of the blow-up `π : B_Z X → X` of a coordinate subspace `Z_p = (z_c : c ∈ C)` of a
regular system of parameters `z` at `p = π(q)`.

* **The pivot** ([Kol07, Definition 60]; [Hau14, Proposition 5.4 (5)]): `F_q` is principal and
  generated by the pullback of ONE centre coordinate `z_{c₀}`, `c₀ ∈ C` — `q` lies in the chart of
  `z_{c₀}` (`exists_pivot_of_mem_support`: `F_q = (π^* z_c : c ∈ C)` is a nonzero principal ideal
  of a local domain, so one generator suffices, `exists_span_singleton_eq_of_span_range_eq`).
* **The induced coordinates** ([Hau14, Proposition 5.4 (6)];
  `exists_isRegularSystemOfParameters_induced`, after the reindexing that puts the centre's
  coordinates last): `w_i = π^* z_i` for `i ∉ C` and for the pivot, `π^* z_i = w_i · π^* z_{c₀}`
  for the other centre coordinates; the `w_i` vanishing at `q` are part of a regular system of
  parameters `z'` of `𝒪_{B,q}` (`exists_inducedCoords`). In the notation of the chain forms,
  `ε = π^* e_{j₀}`, `f_l = ε f_l'` for the centre's chain equations, `e_j = ε e_j'` for the
  centre's other members, `f_l`, `g`, `e_j` unchanged otherwise.
* **The chart datum** `ChartAt` packages the pivot, the induced coordinates and the new parameters;
  the strict transforms of coordinate subspaces through the centre are computed in the chart
  (`stalkIdeal_strictTransformAlong_eq_span_range`: the saturation by `ε` of the pulled-back ideal),
  and the mark-`1` transforms of the chain forms are read in the induced coordinates
  (`stalkIdeal_controlledTransformAlong_chainKIdeal`,
  `stalkIdeal_controlledTransformAlong_chainIdeal`) through the algebra of
  `Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4Algebra`. The passage to the new regular system of
  parameters is `Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP4NewCoords`.
-/

@[expose] public section

universe u

open CategoryTheory AlgebraicGeometry TopologicalSpace IsLocalRing Ideal Scheme.IdealSheafData
  Scheme IdealSheafData

namespace Hironaka.Resolution

variable {X : Scheme.{u}}

/-! ### The pivot coordinate -/

section Pivot

variable (Z : X.IdealSheafData) (q : blowUp Z)

/-- [Hau14, Proposition 5.4 (5)] at a point `q` of the exceptional divisor over a point where `Z`
is the coordinate subspace `(z_c : c ∈ C)`: `F_q` is generated by the pullback of one of the centre
coordinates, which is nonzero. -/
theorem exists_pivot_of_mem_support [IsRegularLocalRing ((blowUp Z).presheaf.stalk q)]
    {n : ℕ}
    {z : Fin n → X.presheaf.stalk (blowUpπ Z q)} (C : Finset (Fin n))
    (hZC : Z.stalkIdeal (blowUpπ Z q) = span (z '' ↑C)) :
    ∃ c₀ ∈ C, (Z.comap (blowUpπ Z)).stalkIdeal q = span {(blowUpπ Z).stalkMap q (z c₀)} ∧
      (blowUpπ Z).stalkMap q (z c₀) ≠ 0 := by
  classical
  obtain ⟨e, he, hFe⟩ := IsInvertible.exists_mem_nonZeroDivisors_stalkIdeal_eq_span
    (blowUp.isInvertible_comap_π Z) q
  have he0 : e ≠ 0 := nonZeroDivisors.ne_zero he
  have hF : (Z.comap (blowUpπ Z)).stalkIdeal q =
      span (Set.range fun c : (↑C : Set (Fin n)) => (blowUpπ Z).stalkMap q (z c)) := by
    rw [stalkIdeal_comap, hZC, Ideal.map_span, Set.image_image, Set.image_eq_range]
  have : Finite (↑C : Set (Fin n)) := C.finite_toSet.to_subtype
  obtain ⟨c, hc⟩ := exists_span_singleton_eq_of_span_range_eq
    (fun c : (↑C : Set (Fin n)) => (blowUpπ Z).stalkMap q (z c)) he0 (hF.symm.trans hFe)
  refine ⟨c.1, c.2, hFe.trans hc.symm, fun h0 => he0 ?_⟩
  rw [h0, span_singleton_eq_bot.mpr rfl, eq_comm, span_singleton_eq_bot] at hc
  exact hc

end Pivot

/-! ### The induced coordinates of the chart -/

section Induced

variable {k : Type u} [Field k] [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]
  (Z : X.IdealSheafData) (q : blowUp Z) [IsRegularLocalRing ((blowUp Z).presheaf.stalk q)]

include f in
/-- [Hau14, Proposition 5.4 (6)] in the pivot's chart (`exists_isRegularSystemOfParameters_induced`,
reindexed so that the centre's coordinates come last): with `Z_p = (z_c : c ∈ C)` and
`F_q = (π^* z_{c₀})`, `c₀ ∈ C`, there are induced coordinates `w` — `w_i = π^* z_i` off `C` and at
the pivot, `π^* z_i = w_i · π^* z_{c₀}` on `C ∖ {c₀}` — whose members vanishing at `q` are
coordinates of a regular system of parameters `z'` of `𝒪_{B,q}`. -/
theorem exists_inducedCoords {n : ℕ} {z : Fin n → X.presheaf.stalk (blowUpπ Z q)}
    (hz : IsRegularSystemOfParameters z) (C : Finset (Fin n))
    (hZC : Z.stalkIdeal (blowUpπ Z q) = span (z '' ↑C)) {c₀ : Fin n} (hc₀ : c₀ ∈ C)
    (hF : (Z.comap (blowUpπ Z)).stalkIdeal q = span {(blowUpπ Z).stalkMap q (z c₀)})
    (hne : (blowUpπ Z).stalkMap q (z c₀) ≠ 0) :
    ∃ w : Fin n → (blowUp Z).presheaf.stalk q,
      (∀ i, i ∉ C ∨ i = c₀ → w i = (blowUpπ Z).stalkMap q (z i)) ∧
      (∀ i ∈ C, i ≠ c₀ →
        (blowUpπ Z).stalkMap q (z i) = w i * (blowUpπ Z).stalkMap q (z c₀)) ∧
      ∃ (m : ℕ) (z' : Fin m → (blowUp Z).presheaf.stalk q), IsRegularSystemOfParameters z' ∧
        ∃ τ : {i : Fin n // w i ∈ maximalIdeal ((blowUp Z).presheaf.stalk q)} → Fin m,
          Function.Injective τ ∧ ∀ i, z' (τ i) = w i.1 := by
  classical
  obtain ⟨σ, hσ, hσc⟩ := exists_equiv_image_eq C hc₀
  set kk := C.card with hkk
  have hk : 1 ≤ kk := Finset.card_pos.mpr ⟨c₀, hc₀⟩
  have hkn : kk ≤ n := by
    have := Finset.card_le_univ C
    rwa [Fintype.card_fin] at this
  -- `ρ = σ ∘ rev` puts the centre's coordinates last
  set ρ : Fin n ≃ Fin n := Fin.revPerm.trans σ with hρ
  have hρapp : ∀ i, ρ i = σ (Fin.rev i) := fun i => rfl
  have hρmem : ∀ i : Fin n, ρ i ∈ C ↔ n - kk ≤ i.val := by
    intro i
    rw [hρapp, hσ, Fin.val_rev]
    have := i.2
    omega
  have hjlt : n - kk < n := by omega
  set j : Fin n := ⟨n - kk, hjlt⟩ with hj
  have hρj : ρ j = c₀ := by
    have h1 : kk - 1 < n := by omega
    have hrev : Fin.rev j = ⟨kk - 1, h1⟩ := Fin.ext (by rw [Fin.val_rev, hj]; simp; omega)
    rw [hρapp, hrev]
    exact hσc h1
  set zR : Fin n → X.presheaf.stalk (blowUpπ Z q) := z ∘ ρ with hzR
  have hzRrs : span (Set.range zR) = maximalIdeal (X.presheaf.stalk (blowUpπ Z q)) ∧
      (n : WithBot ℕ∞) = ringKrullDim (X.presheaf.stalk (blowUpπ Z q)) := by
    refine ⟨?_, hz.2⟩
    rw [hzR, ρ.surjective.range_comp]
    exact hz.1
  have himg : ρ '' {i : Fin n | n - kk ≤ i.val} = ↑C := by
    ext c
    constructor
    · rintro ⟨i, hi, rfl⟩
      exact (hρmem i).mpr hi
    · intro hc
      refine ⟨ρ.symm c, ?_, ρ.apply_symm_apply c⟩
      change n - kk ≤ (ρ.symm c).val
      rw [← hρmem, ρ.apply_symm_apply]
      exact hc
  have hZzR : Z.stalkIdeal (blowUpπ Z q) = span (zR '' {i : Fin n | n - kk ≤ i.val}) := by
    rw [hZC, hzR, Set.image_comp, himg]
  have hjv : n - kk ≤ j.val := le_rfl
  have hzRj : zR j = z c₀ := by rw [hzR, Function.comp_apply, hρj]
  have hF' : (Z.comap (blowUpπ Z)).stalkIdeal q = span {(blowUpπ Z).stalkMap q (zR j)} := by
    rw [hzRj]
    exact hF
  have hne' : (blowUpπ Z).stalkMap q (zR j) ≠ 0 := by
    rw [hzRj]
    exact hne
  -- the induced coordinates in the `zR`-indexing
  have hex : ∀ i : Fin n, n - kk ≤ i.val → i ≠ j → ∃ y : (blowUp Z).presheaf.stalk q,
      (blowUpπ Z).stalkMap q (zR i) = y * (blowUpπ Z).stalkMap q (zR j) := by
    intro i hi _
    have hmem : (blowUpπ Z).stalkMap q (zR i) ∈ (Z.comap (blowUpπ Z)).stalkIdeal q := by
      rw [stalkIdeal_comap, hZzR]
      exact Ideal.mem_map_of_mem _ (subset_span ⟨i, hi, rfl⟩)
    rw [hF'] at hmem
    obtain ⟨y, hy⟩ := mem_span_singleton'.mp hmem
    exact ⟨y, hy.symm⟩
  choose! yy hyy using hex
  set wR : Fin n → (blowUp Z).presheaf.stalk q := fun i =>
    if i.val < n - kk ∨ i = j then (blowUpπ Z).stalkMap q (zR i) else yy i with hwR
  have hw : ∀ i : Fin n, i.val < n - kk ∨ i = j → wR i = (blowUpπ Z).stalkMap q (zR i) :=
    fun i hi => if_pos hi
  have hw' : ∀ i : Fin n, n - kk ≤ i.val → i ≠ j →
      (blowUpπ Z).stalkMap q (zR i) = wR i * (blowUpπ Z).stalkMap q (zR j) := by
    intro i h1 h2
    have : wR i = yy i := if_neg fun h => h.elim (fun h => by omega) h2
    rw [this]
    exact hyy i h1 h2
  obtain ⟨m, z', hz', τ', hτ'inj, hτ'⟩ :=
    exists_isRegularSystemOfParameters_induced f Z q hk hkn hzRrs hZzR hjv hF' hne' wR hw hw'
  -- back to the `z`-indexing
  have hzRsymm : ∀ i, zR (ρ.symm i) = z i := fun i => by
    rw [hzR, Function.comp_apply, ρ.apply_symm_apply]
  have hρsymm_j : ρ.symm c₀ = j := by
    rw [← hρj, ρ.symm_apply_apply]
  refine ⟨fun i => wR (ρ.symm i), ?_, ?_, m, z', hz', fun i => τ' ⟨ρ.symm i.1, i.2⟩, ?_, ?_⟩
  · intro i hi
    change wR (ρ.symm i) = (blowUpπ Z).stalkMap q (z i)
    rcases hi with hi | hi
    · have hlt : (ρ.symm i).val < n - kk := by
        have h1 : ¬ n - kk ≤ (ρ.symm i).val := by
          rw [← hρmem, ρ.apply_symm_apply]
          exact hi
        omega
      rw [hw _ (Or.inl hlt), hzRsymm]
    · rw [hi, hw _ (Or.inr hρsymm_j), hzRsymm]
  · intro i hi hne
    change (blowUpπ Z).stalkMap q (z i) = wR (ρ.symm i) * (blowUpπ Z).stalkMap q (z c₀)
    have h1 : n - kk ≤ (ρ.symm i).val := by
      rw [← hρmem, ρ.apply_symm_apply]
      exact hi
    have h2 : ρ.symm i ≠ j := fun h => hne (by rw [← ρ.apply_symm_apply i, h, hρj])
    have := hw' _ h1 h2
    rwa [hzRsymm, hzRj] at this
  · intro i₁ i₂ h
    have := hτ'inj h
    exact Subtype.ext (ρ.symm.injective (Subtype.mk.inj this))
  · intro i
    exact hτ' ⟨ρ.symm i.1, i.2⟩

end Induced

/-! ### The chart datum -/

section Datum

variable (Z : X.IdealSheafData) (q : blowUp Z)

/-- **The chart datum at `q`**: the pivot `c₀ ∈ C` with `F_q = (π^* z_{c₀})`, the induced
coordinates `w` (`w_i = π^* z_i` off `C` and at the pivot, `π^* z_i = w_i · π^* z_{c₀}` on
`C ∖ {c₀}`), and a regular system of parameters `z'` of `𝒪_{B,q}` containing the induced
coordinates vanishing at `q` (`z' (τ i) = w i`). -/
structure ChartAt {n : ℕ} (z : Fin n → X.presheaf.stalk (blowUpπ Z q)) (C : Finset (Fin n)) where
  /-- The pivot: the centre coordinate whose pull-back generates `F_q`. -/
  c₀ : Fin n
  /-- The pivot is a centre coordinate. -/
  mem : c₀ ∈ C
  /-- `F_q = (π^* z_{c₀})`. -/
  hF : (Z.comap (blowUpπ Z)).stalkIdeal q = span {(blowUpπ Z).stalkMap q (z c₀)}
  /-- The pivot's pull-back is nonzero. -/
  ε_ne : (blowUpπ Z).stalkMap q (z c₀) ≠ 0
  /-- The induced coordinates. -/
  w : Fin n → (blowUp Z).presheaf.stalk q
  /-- Off the centre and at the pivot the induced coordinate is the pull-back. -/
  hw : ∀ i, i ∉ C ∨ i = c₀ → w i = (blowUpπ Z).stalkMap q (z i)
  /-- On the centre the pull-back is the induced coordinate times the pivot's pull-back. -/
  hw' : ∀ i ∈ C, i ≠ c₀ → (blowUpπ Z).stalkMap q (z i) = w i * (blowUpπ Z).stalkMap q (z c₀)
  /-- The number of parameters at `q`. -/
  m : ℕ
  /-- A regular system of parameters at `q`. -/
  z' : Fin m → (blowUp Z).presheaf.stalk q
  /-- It is a regular system of parameters. -/
  hz' : IsRegularSystemOfParameters z'
  /-- The induced coordinates vanishing at `q` among the parameters. -/
  τ : {i : Fin n // w i ∈ maximalIdeal ((blowUp Z).presheaf.stalk q)} → Fin m
  /-- Distinct induced coordinates are distinct parameters. -/
  τ_injective : Function.Injective τ
  /-- The parameter of an induced coordinate is the induced coordinate. -/
  hτ : ∀ i, z' (τ i) = w i.1

variable {k : Type u} [Field k] [PerfectField k] (f : X ⟶ Spec (.of k)) [Smooth f]

include f in
/-- At a point of the exceptional divisor over a point where the centre is a coordinate subspace of
a regular system of parameters, a chart datum exists (the pivot, then the induced coordinates). -/
theorem nonempty_chartAt [IsRegularLocalRing ((blowUp Z).presheaf.stalk q)] {n : ℕ}
    {z : Fin n → X.presheaf.stalk (blowUpπ Z q)} (hz : IsRegularSystemOfParameters z)
    (C : Finset (Fin n)) (hZC : Z.stalkIdeal (blowUpπ Z q) = span (z '' ↑C)) :
    Nonempty (ChartAt Z q z C) := by
  obtain ⟨c₀, hc₀, hF, hne⟩ := exists_pivot_of_mem_support Z q C hZC
  obtain ⟨w, hw, hw', m, z', hz', τ, hτinj, hτ⟩ :=
    exists_inducedCoords f Z q hz C hZC hc₀ hF hne
  exact ⟨⟨c₀, hc₀, hF, hne, w, hw, hw', m, z', hz', τ, hτinj, hτ⟩⟩

end Datum

/-! ### Definitional bridges: the transforms and the total transform's members -/

section Bridges

variable (E : DivisorFamily X) (Z : X.IdealSheafData)

/-- The exceptional divisor is the pull-back of the centre (definitional unfolding). -/
theorem exceptionalDivisor_eq_comap : Z.exceptionalDivisor = Z.comap (blowUpπ Z) := rfl

/-- The strict transform is the strict transform along the exceptional divisor (definitional
unfolding). -/
theorem strictTransform_eq_strictTransformAlong (Y : X.IdealSheafData) :
    Y.strictTransform Z = Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z)) := rfl

/-- The mark-`1` transform is the controlled transform along the exceptional divisor (definitional
unfolding). -/
theorem markedTransform_one_eq (K : X.IdealSheafData) :
    K.markedTransform Z 1 = K.controlledTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z)) 1 := rfl

theorem totalTransform_component_toLex_inr (u : PUnit.{u + 1}) :
    (E.totalTransform Z).component (toLex (Sum.inr u)) = Z.exceptionalDivisor := rfl

/-- The index of a member of the total transform is `inl j` or `inr u`. -/
theorem eq_toLex_inl_or_inr (j' : (E.totalTransform Z).ι) :
    (∃ j : E.ι, j' = toLex (Sum.inl j)) ∨ ∃ u : PUnit.{u + 1}, j' = toLex (Sum.inr u) := by
  match h : ofLex j' with
  | Sum.inl j => exact Or.inl ⟨j, by rw [← h]; rfl⟩
  | Sum.inr u => exact Or.inr ⟨u, by rw [← h]; rfl⟩

end Bridges

/-- The ε-orders of a chart with centre coordinates `C`: `e₀ = b(C)`, `e_i = a_i(C)`, `δ` given. -/
def epsOrderC {n r : ℕ} (C : Finset (Fin n)) (a : Fin (r + 1) → Fin n → ℕ) (b : Fin n → ℕ)
    (δ : Fin (r + 1) → ℕ) : Fin (r + 1) → ℕ :=
  epsOrder (∑ k ∈ C, b k) (fun i => ∑ k ∈ C, a i k) δ

/-! ### The chart datum's arithmetic -/

namespace ChartAt

variable {Z : X.IdealSheafData} {q : blowUp Z} {n : ℕ}
  {z : Fin n → X.presheaf.stalk (blowUpπ Z q)} {C : Finset (Fin n)} (D : ChartAt Z q z C)

/-- The exceptional coordinate `ε = π^* z_{c₀}`. -/
noncomputable def ε : (blowUp Z).presheaf.stalk q := (blowUpπ Z).stalkMap q (z D.c₀)

/-- The ε-free induced coordinates: `w` with the pivot's entry replaced by `1`. -/
noncomputable def wHat : Fin n → (blowUp Z).presheaf.stalk q := Function.update D.w D.c₀ 1

theorem ε_def : D.ε = (blowUpπ Z).stalkMap q (z D.c₀) := rfl

theorem w_c₀ : D.w D.c₀ = D.ε := D.hw D.c₀ (Or.inr rfl)

theorem hF_ε : (Z.comap (blowUpπ Z)).stalkIdeal q = span {D.ε} := D.hF

theorem ε_ne_zero : D.ε ≠ 0 := D.ε_ne

/-- The exceptional coordinate vanishes at a point of the exceptional divisor. -/
theorem ε_mem_maximalIdeal (hq : q ∈ (Z.comap (blowUpπ Z)).support) :
    D.ε ∈ maximalIdeal ((blowUp Z).presheaf.stalk q) :=
  (mem_support_iff_stalkIdeal_le_maximalIdeal (I := Z.comap (blowUpπ Z)) (x := q)).mp hq
    (D.hF_ε ▸ mem_span_singleton_self _)

/-- Hauser's chart substitution `x_i ↦ x_i x_j` on the centre, the identity off it: every
pull-back `π^* z_i` is `ŵ_i · ε^{[i ∈ C]}`. -/
theorem stalkMap_eq (i : Fin n) :
    (blowUpπ Z).stalkMap q (z i) = D.wHat i * if i ∈ C then D.ε else 1 := by
  classical
  by_cases hi : i = D.c₀
  · subst hi
    rw [wHat, Function.update_self, if_pos D.mem, one_mul, ε_def]
  · rw [wHat, Function.update_of_ne hi]
    by_cases hiC : i ∈ C
    · rw [if_pos hiC, ε_def]
      exact D.hw' i hiC hi
    · rw [if_neg hiC, mul_one]
      exact (D.hw i (Or.inl hiC)).symm

/-- The pull-back of a monomial: `π^* z^a = ŵ^a · ε^{a(C)}`. -/
theorem stalkMap_monomialOf (a : Fin n → ℕ) :
    (blowUpπ Z).stalkMap q (monomialOf z a) =
      D.ε ^ (∑ i ∈ C, a i) * monomialOf D.wHat a := by
  classical
  rw [monomialOf_map]
  have : ((blowUpπ Z).stalkMap q).hom ∘ z =
      fun i => D.wHat i * if i ∈ C then D.ε else 1 := funext fun i => D.stalkMap_eq i
  rw [this, monomialOf_mul, monomialOf_ite_mem, mul_comm]

/-- The ε-order `[i ∈ C]` of a coordinate. -/
theorem stalkMap_eq_pow (i : Fin n) :
    (blowUpπ Z).stalkMap q (z i) = D.ε ^ (if i ∈ C then 1 else 0) * D.wHat i := by
  classical
  rw [D.stalkMap_eq i, mul_comm]
  congr 1
  split_ifs <;> simp

/-- Off the pivot the ε-free coordinate is the induced coordinate. -/
theorem wHat_of_ne {i : Fin n} (hi : i ≠ D.c₀) : D.wHat i = D.w i :=
  Function.update_of_ne hi _ _

/-- An induced coordinate not vanishing at `q` is a unit. -/
theorem isUnit_w_of_notMem {i : Fin n}
    (hi : D.w i ∉ maximalIdeal ((blowUp Z).presheaf.stalk q)) :
    IsUnit (D.w i) :=
  IsLocalRing.notMem_maximalIdeal.mp hi

/-- Off the centre the induced coordinate vanishes at `q` (`π^*` is local). -/
theorem w_mem_maximalIdeal_of_notMem {i : Fin n} (hi : i ∉ C)
    (hz : z i ∈ maximalIdeal (X.presheaf.stalk (blowUpπ Z q))) :
    D.w i ∈ maximalIdeal ((blowUp Z).presheaf.stalk q) := by
  rw [D.hw i (Or.inl hi)]
  exact stalkMap_mem_maximalIdeal_of_mem Z q hz

/-! ### Strict transforms in the chart -/

section StrictTransforms

variable {Z : X.IdealSheafData} {q : blowUp Z} {n : ℕ}
  {z : Fin n → X.presheaf.stalk (blowUpπ Z q)} {C : Finset (Fin n)} (D : ChartAt Z q z C)

/-- The saturation defining a strict transform at `q`, with `F_q = (ε)`. -/
theorem stalkIdeal_strictTransformAlong_eq (Y : X.IdealSheafData) :
    (Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z))).stalkIdeal q =
      ⨆ i : ℕ, ((Y.stalkIdeal (blowUpπ Z q)).map ((blowUpπ Z).stalkMap q).hom).colon
        ((span {D.ε} ^ i : Ideal ((blowUp Z).presheaf.stalk q)) :
          Set ((blowUp Z).presheaf.stalk q)) := by
  rw [strictTransformAlong, stalkIdeal_saturate_of_isInvertible _ (blowUp.isInvertible_comap_π Z),
    stalkIdeal_comap, D.hF_ε]

/-- **The charts of the chain equations**: if the pivot is one of the equations of `Y` then the
strict transform of `Y` misses `q`. -/
theorem stalkIdeal_strictTransformAlong_eq_top_of_mem (Y : X.IdealSheafData)
    (hY : z D.c₀ ∈ Y.stalkIdeal (blowUpπ Z q)) :
    (Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z))).stalkIdeal q = ⊤ := by
  rw [strictTransformAlong, stalkIdeal_saturate_of_isInvertible _ (blowUp.isInvertible_comap_π Z),
    stalkIdeal_comap, D.hF_ε]
  exact iSup_colon_pow_eq_top_of_pow_mem (t := 1)
    (by rw [pow_one, ChartAt.ε_def]; exact Ideal.mem_map_of_mem _ hY)

/-- The chain coordinates of a coordinate subspace `Y = (z (σ i) : i)` through the centre vanish at
every point `q` of its strict transform on the exceptional divisor (no `z (σ i)` the pivot). -/
theorem w_σ_mem_of_mem_support {r : ℕ} (σ : Fin r → Fin n) (hσc₀ : ∀ i, σ i ≠ D.c₀)
    (Y : X.IdealSheafData) (hY : Y.stalkIdeal (blowUpπ Z q) = span (Set.range (z ∘ σ)))
    (hqY : q ∈ (Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z))).support) :
    ∀ i, D.w (σ i) ∈ maximalIdeal ((blowUp Z).presheaf.stalk q) := by
  classical
  have hsat := D.stalkIdeal_strictTransformAlong_eq Y
  -- the pulled-back ideal is generated by `ε^{δ_i} w (σ i)`
  set J := (Y.stalkIdeal (blowUpπ Z q)).map ((blowUpπ Z).stalkMap q).hom with hJ
  have hJgen : J = span (Set.range fun i => D.ε ^ (if σ i ∈ C then 1 else 0) * D.w (σ i)) := by
    rw [hJ, hY, Ideal.map_span, ← Set.range_comp]
    congr 1
    refine congrArg Set.range (funext fun i => ?_)
    rw [Function.comp_apply, Function.comp_apply, D.stalkMap_eq_pow, D.wHat_of_ne (hσc₀ i)]
  have hgen : ∀ i, D.w (σ i) * D.ε ∈ J := by
    intro i
    rw [hJgen]
    by_cases hi : σ i ∈ C
    · rw [mul_comm]
      exact subset_span ⟨i, by simp [hi]⟩
    · exact mul_mem_right _ _ (subset_span ⟨i, by simp [hi]⟩)
  -- every `w (σ i)` lies in `J : (ε)`, hence in the strict transform's stalk, hence in `𝔪_q`
  have hle : ∀ i, D.w (σ i) ∈
      (Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z))).stalkIdeal q := by
    intro i
    rw [hsat]
    refine le_iSup (fun i : ℕ => J.colon ((span {D.ε} ^ i : Ideal _) : Set _)) 1 ?_
    rw [pow_one, Submodule.mem_colon_span_singleton, smul_eq_mul]
    exact hgen i
  exact fun i => (mem_support_iff_stalkIdeal_le_maximalIdeal (I := _) (x := q)).mp hqY (hle i)

/-- **The strict transform of a coordinate subspace through the centre**, given that its chain
coordinates vanish at `q`: the strict transform of `Y = (z (σ i) : i)` at `q` is `(w (σ i) : i)`
(the saturation of `(ε^{δ_i} w (σ i) : i)` by `ε`, a coordinate prime not containing `ε`). -/
theorem stalkIdeal_strictTransformAlong_eq_span_range_of_mem
    [IsRegularLocalRing ((blowUp Z).presheaf.stalk q)]
        (hq : q ∈ (Z.comap (blowUpπ Z)).support)
    {r : ℕ} (σ : Fin r → Fin n) (hσc₀ : ∀ i, σ i ≠ D.c₀) (Y : X.IdealSheafData)
    (hY : Y.stalkIdeal (blowUpπ Z q) = span (Set.range (z ∘ σ)))
    (hmem : ∀ i, D.w (σ i) ∈ maximalIdeal ((blowUp Z).presheaf.stalk q)) :
    (Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z))).stalkIdeal q =
      span (Set.range fun i => D.w (σ i)) := by
  classical
  have hsat := D.stalkIdeal_strictTransformAlong_eq Y
  set J := (Y.stalkIdeal (blowUpπ Z q)).map ((blowUpπ Z).stalkMap q).hom with hJ
  have hJgen : J = span (Set.range fun i => D.ε ^ (if σ i ∈ C then 1 else 0) * D.w (σ i)) := by
    rw [hJ, hY, Ideal.map_span, ← Set.range_comp]
    congr 1
    refine congrArg Set.range (funext fun i => ?_)
    rw [Function.comp_apply, Function.comp_apply, D.stalkMap_eq_pow, D.wHat_of_ne (hσc₀ i)]
  set P := span (Set.range fun i => D.w (σ i)) with hP
  have hJP : J ≤ P := by
    rw [hJgen, span_le]
    rintro _ ⟨i, rfl⟩
    exact mul_mem_left _ _ (subset_span ⟨i, rfl⟩)
  have hPJ : ∀ x ∈ P, x * D.ε ^ 1 ∈ J := by
    intro x hx
    rw [pow_one]
    have hgen : ∀ i, D.w (σ i) * D.ε ∈ J := by
      intro i
      rw [hJgen]
      by_cases hi : σ i ∈ C
      · rw [mul_comm]
        exact subset_span ⟨i, by simp [hi]⟩
      · exact mul_mem_right _ _ (subset_span ⟨i, by simp [hi]⟩)
    have : P ≤ J.colon (span {D.ε}) := by
      rw [hP, span_le]
      rintro _ ⟨i, rfl⟩
      exact Submodule.mem_colon_span_singleton.mpr (by rw [smul_eq_mul]; exact hgen i)
    exact Submodule.mem_colon_span_singleton.mp (this hx)
  -- `P` is the coordinate prime of the parameters `τ ⟨σ i, _⟩`, and `ε` is another parameter
  have hεmem := D.ε_mem_maximalIdeal hq
  have hPimg : P = span (D.z' '' ↑(Finset.univ.image fun i => D.τ ⟨σ i, hmem i⟩)) := by
    rw [hP, Finset.coe_image, Finset.coe_univ, Set.image_univ, ← Set.range_comp]
    congr 1
    exact congrArg Set.range (funext fun i => (D.hτ ⟨σ i, hmem i⟩).symm)
  have hPprime : P.IsPrime := by
    rw [hPimg]
    exact isPrime_span_image_finset D.hz'.1.symm D.hz'.2 _
  have hεP : D.ε ∉ P := by
    rw [hPimg]
    have hεz : D.ε = D.z' (D.τ ⟨D.c₀, D.w_c₀ ▸ hεmem⟩) := by rw [D.hτ, D.w_c₀]
    rw [hεz]
    refine notMem_span_image_of_notMem D.hz'.1.symm D.hz'.2 fun h => ?_
    obtain ⟨i, -, hi⟩ := Finset.mem_image.mp h
    exact hσc₀ i (Subtype.mk.inj (D.τ_injective hi))
  rw [hsat]
  exact iSup_colon_pow_span_singleton_eq_of_isPrime hPprime hεP hJP hPJ

/-- **The strict transform of a coordinate subspace through the centre**: with `Y_p = (z (σ i) : i)`
and no `z (σ i)` the pivot, the strict transform of `Y` at `q` is `(w (σ i) : i)`, provided `q`
lies on it — and then every `w (σ i)` vanishes at `q`. -/
theorem stalkIdeal_strictTransformAlong_eq_span_range
    [IsRegularLocalRing ((blowUp Z).presheaf.stalk q)]
        (hq : q ∈ (Z.comap (blowUpπ Z)).support)
    {r : ℕ} (σ : Fin r → Fin n) (hσc₀ : ∀ i, σ i ≠ D.c₀) (Y : X.IdealSheafData)
    (hY : Y.stalkIdeal (blowUpπ Z q) = span (Set.range (z ∘ σ)))
    (hqY : q ∈ (Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z))).support) :
    (∀ i, D.w (σ i) ∈ maximalIdeal ((blowUp Z).presheaf.stalk q)) ∧
      (Y.strictTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z))).stalkIdeal q =
        span (Set.range fun i => D.w (σ i)) :=
  ⟨D.w_σ_mem_of_mem_support σ hσc₀ Y hY hqY,
    D.stalkIdeal_strictTransformAlong_eq_span_range_of_mem hq σ hσc₀ Y hY
      (D.w_σ_mem_of_mem_support σ hσc₀ Y hY hqY)⟩

end StrictTransforms

/-! ### The transforms of the chain forms in the chart -/

section Transforms

variable {Z : X.IdealSheafData} {q : blowUp Z} {n : ℕ}
  {z : Fin n → X.presheaf.stalk (blowUpπ Z q)} {C : Finset (Fin n)} (D : ChartAt Z q z C)

/-- The stalk of the mark-`1` transform: the colon of the pull-back by `(ε)`. -/
theorem stalkIdeal_controlledTransformAlong_one (K : X.IdealSheafData) :
    (K.controlledTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z)) 1).stalkIdeal q =
      ((K.stalkIdeal (blowUpπ Z q)).map ((blowUpπ Z).stalkMap q).hom).colon (span {D.ε}) := by
  rw [controlledTransformAlong, pow_one,
    stalkIdeal_colon_of_isInvertible _ (blowUp.isInvertible_comap_π Z), stalkIdeal_comap, D.hF_ε]

/-- The pull-back of a K-shape in the chart: the equations gain `ε^{[σ i ∈ C]}`, the monomials
gain `ε` to their total exponent on `C`. -/
theorem map_span_mul_chainKIdeal {r : ℕ} (σ : Fin (r + 1) → Fin n) (a : Fin (r + 1) → Fin n → ℕ)
    (b : Fin n → ℕ) :
    (span {monomialOf z b} * chainKIdeal (z ∘ σ) fun i => monomialOf z (a i)).map
        ((blowUpπ Z).stalkMap q).hom =
      span {D.ε ^ (∑ k ∈ C, b k) * monomialOf D.wHat b} *
        chainKIdeal (fun i => D.ε ^ (if σ i ∈ C then 1 else 0) * D.wHat (σ i))
          (fun i => D.ε ^ (∑ k ∈ C, a i k) * monomialOf D.wHat (a i)) := by
  classical
  rw [Ideal.map_mul, Ideal.map_span, Set.image_singleton, ← chainKIdeal_comp,
    D.stalkMap_monomialOf]
  congr 2
  · funext i
    rw [Function.comp_apply, Function.comp_apply, D.stalkMap_eq_pow]
  · funext i
    rw [Function.comp_apply, D.stalkMap_monomialOf]

/-- The pull-back of an un-isolated chain form in the chart. -/
theorem map_span_mul_chainIdeal {r : ℕ} (σ : Fin (r + 1) → Fin n) (a : Fin (r + 1) → Fin n → ℕ)
    (b : Fin n → ℕ) :
    (span {monomialOf z b} * chainIdeal (z ∘ σ) fun i => monomialOf z (a i)).map
        ((blowUpπ Z).stalkMap q).hom =
      span {D.ε ^ (∑ k ∈ C, b k) * monomialOf D.wHat b} *
        chainIdeal (fun i => D.ε ^ (if σ i ∈ C then 1 else 0) * D.wHat (σ i))
          (fun i => D.ε ^ (∑ k ∈ C, a i k) * monomialOf D.wHat (a i)) := by
  classical
  rw [Ideal.map_mul, Ideal.map_span, Set.image_singleton, ← chainIdeal_comp,
    D.stalkMap_monomialOf]
  congr 2
  · funext i
    rw [Function.comp_apply, Function.comp_apply, D.stalkMap_eq_pow]
  · funext i
    rw [Function.comp_apply, D.stalkMap_monomialOf]

/-- **The K-shape in the chart's induced coordinates**: under the admissibility condition (★) in
the form of the ε-order conditions, the mark-`1` transform of a K-shape at `p` has, at `q`, the
K-shape with equations `ŵ (σ i)`, level monomials `ε^{D_i} ŵ^{a_i}` and top monomial
`ε^{E_0 − 1} ŵ^{b}`. -/
theorem stalkIdeal_controlledTransformAlong_chainKIdeal
    [IsRegularLocalRing ((blowUp Z).presheaf.stalk q)] {r : ℕ} (σ : Fin (r + 1) → Fin n)
    (a : Fin (r + 1) → Fin n → ℕ) (b : Fin n → ℕ) (K : X.IdealSheafData)
    (hK : K.stalkIdeal (blowUpπ Z q) =
      span {monomialOf z b} * chainKIdeal (z ∘ σ) fun i => monomialOf z (a i))
    (δ : Fin (r + 1) → ℕ) (hδ : ∀ i, δ i = if σ i ∈ C then 1 else 0)
    (hpos : 1 ≤ epsOrderC C a b (Function.update δ (Fin.last r) 0) 0)
    (hmono : ∀ i : Fin r, epsOrderC C a b (Function.update δ (Fin.last r) 0) i.castSucc ≤
      epsOrderC C a b (Function.update δ (Fin.last r) 0) i.succ)
    (Dexp : Fin (r + 1) → ℕ)
    (hD : ∀ i : Fin r, Dexp i.castSucc =
      epsOrderC C a b (Function.update δ (Fin.last r) 0) i.succ -
        epsOrderC C a b (Function.update δ (Fin.last r) 0) i.castSucc) :
    (K.controlledTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z)) 1).stalkIdeal q =
      span {D.ε ^ (epsOrderC C a b (Function.update δ (Fin.last r) 0) 0 - 1) *
          monomialOf D.wHat b} *
        chainKIdeal (fun i => D.wHat (σ i)) (fun i => D.ε ^ Dexp i * monomialOf D.wHat (a i)) := by
  classical
  rw [D.stalkIdeal_controlledTransformAlong_one, hK, D.map_span_mul_chainKIdeal]
  have hδ' : (fun i => D.ε ^ (if σ i ∈ C then 1 else 0) * D.wHat (σ i)) =
      fun i => D.ε ^ δ i * D.wHat (σ i) := funext fun i => by rw [hδ i]
  rw [hδ']
  exact colon_span_mul_chainKIdeal_pow D.ε_ne_zero _ _ δ _ _ _ hpos hmono Dexp hD

/-- **The un-isolated form in the chart's induced coordinates**. -/
theorem stalkIdeal_controlledTransformAlong_chainIdeal
    [IsRegularLocalRing ((blowUp Z).presheaf.stalk q)] {r : ℕ} (σ : Fin (r + 1) → Fin n)
    (a : Fin (r + 1) → Fin n → ℕ) (b : Fin n → ℕ) (I : X.IdealSheafData)
    (hI : I.stalkIdeal (blowUpπ Z q) =
      span {monomialOf z b} * chainIdeal (z ∘ σ) fun i => monomialOf z (a i))
    (δ : Fin (r + 1) → ℕ) (hδ : ∀ i, δ i = if σ i ∈ C then 1 else 0)
    (hpos : 1 ≤ epsOrderC C a b δ 0)
    (hmono : ∀ i : Fin r, epsOrderC C a b δ i.castSucc ≤ epsOrderC C a b δ i.succ)
    (Dexp : Fin (r + 1) → ℕ)
    (hD : ∀ i : Fin r, Dexp i.castSucc =
      epsOrderC C a b δ i.succ - epsOrderC C a b δ i.castSucc) :
    (I.controlledTransformAlong (blowUpπ Z) (Z.comap (blowUpπ Z)) 1).stalkIdeal q =
      span {D.ε ^ (epsOrderC C a b δ 0 - 1) * monomialOf D.wHat b} *
        chainIdeal (fun i => D.wHat (σ i)) (fun i => D.ε ^ Dexp i * monomialOf D.wHat (a i)) := by
  classical
  rw [D.stalkIdeal_controlledTransformAlong_one, hI, D.map_span_mul_chainIdeal]
  have hδ' : (fun i => D.ε ^ (if σ i ∈ C then 1 else 0) * D.wHat (σ i)) =
      fun i => D.ε ^ δ i * D.wHat (σ i) := funext fun i => by rw [hδ i]
  rw [hδ']
  exact colon_span_mul_chainIdeal_pow D.ε_ne_zero _ _ δ _ _ _ hpos hmono Dexp hD

end Transforms

end ChartAt

end Hironaka.Resolution
