/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Wlo05.EmbeddedHypotheses
import Hironaka.Resolution.Algebraic.Wlo05.EmbeddedAbsorbed
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.BlowUpSequence.BaseChangeOrder
import Hironaka.Scheme.BlowUpSequence.InducedData
import Hironaka.Scheme.IdealSheaf.Order.Basic
import Hironaka.Scheme.Snc.HasSncWith
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The absorbed strict transform and the members of the boundary

Two facts about the position of an absorbed strict transform `c̃` relative to the boundary `E_n`
at the absorbing stage `n` of a run of `BMO_1`, both needed for the isolation of the absorbed
component in the loop `BED` (`Hironaka.Resolution.Algebraic.Wlo05.Embedded`; the isolation passage
of the proof of [Wlo05, Theorem 4.7.1]).

* **No member of the boundary contains `c̃` near any of its points**
  (`notContainedInMembers_strictTransformSeq_of_absorbed`): the generic point of `c̃` lies on no
  member (the proof of [Kol07, Corollary 22], `exists_genericPoint_strictTransformSeq_of_absorbed`
  of `Hironaka.Resolution.Algebraic.Wlo05.EmbeddedAbsorbed`), and a containment near a point would
  specialise to it. This is unconditional.
* **The generic point of an irreducible component of a member does not lie on `c̃`**
  (`notMem_strictTransformSeq_support_of_mem_genericPoints_component`): at such a point the stalk
  of the member is the maximal ideal, generated by one of the snc coordinates; the stalk of `c̃`
  there is generated by other coordinates (the first point), yet lies in the maximal ideal, which
  contradicts the independence of a regular system of parameters unless it is the zero ideal, and
  the marked ideal (nonzero everywhere, contained in the centre, which equals `c̃` near `c̃`)
  forbids that. The equality of the centre and `c̃` used here is the CONDITIONAL
  `stalkIdeal_center_eq_of_absorbed`, so this lemma assumes `ClaimKC`
  (`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedHypotheses`), which is false for the transcribed
  order; the unconditional treatment of the isolated state is
  `Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP2Entry`. The second point is what makes the colon
  by `c̃` invisible to the monomial part: the exponents of `M(I_n)` are the orders at these generic
  points, where the colon changes nothing.

Simple normal crossings and the total transform are those of [Kol07, Definition 24] and
[Kol07, Definition 25]. Used in `Hironaka.Resolution.Algebraic.Wlo05.EmbeddedCP1Step22Core`,
`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedIsolatedState` and
`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedIsolatedIdeal`.
-/

public section

universe u

open CategoryTheory AlgebraicGeometry TopologicalSpace Hironaka Scheme BlowUpSequence
  Scheme.IdealSheafData Hironaka.BMO IsLocalRing

namespace Hironaka.Resolution

variable {k : Type u} [Field k] [CharZero k]

/-- [Kol07, Definition 24 (4)] for a member of an snc family itself: a member has simple normal
crossings with the family (its stalk at a point through which it passes is generated by one of the
snc coordinates). -/
theorem hasSncWith_component_of_isSnc {X : Scheme.{u}} {E : DivisorFamily X} (hE : E.IsSnc)
    (i : E.ι) : E.HasSncWith (E.component i) := by
  intro x hx
  obtain ⟨n, z, hrs, c, hcinj, hc⟩ := hE.2 x
  refine ⟨n, z, ⟨hrs, c, hcinj, hc⟩, {c ⟨i, hx⟩}, ?_⟩
  rw [hc ⟨i, hx⟩, Finset.coe_singleton, Set.image_singleton]

section Absorbed

variable (T : MarkedTriple k) (hm : T.m = 1) {η : T.X.left}
  (hη : η ∈ T.I.support.genericPoints) (hηE : ∀ i, η ∉ (T.E.component i).support)
  (hIc : T.I.stalkIdeal η = (IdealSheafData.vanishingIdeal (Closeds.closure {η})).stalkIdeal η)
  (n : Fin (bmoOneRun T hm).length)
  (habs : CenterContains (bmoOneRun T hm) (IdealSheafData.vanishingIdeal (Closeds.closure {η})) n)
  (hfirst : ∀ m < n.val,
    ¬ CenterContains (bmoOneRun T hm) (IdealSheafData.vanishingIdeal (Closeds.closure {η})) m)

include hηE hfirst in
/-- No member of the boundary at stage `n` contains `c̃` near any of its points (the last sentence
of [Kol07, Definition 24] for the absorbed strict transform): the generic point of `c̃` lies on no
member (`exists_genericPoint_strictTransformSeq_of_absorbed`), and a containment of stalks at a
point of `c̃` would generize to it. -/
theorem notContainedInMembers_strictTransformSeq_of_absorbed :
    NotContainedInMembers ((bmoOneRun T hm).totalTransformSeq T.E n.castSucc)
      ((bmoOneRun T hm).strictTransformSeq (IdealSheafData.vanishingIdeal (Closeds.closure {η}))
        n.castSucc) := by
  intro p hp i _ hle
  obtain ⟨η', hgen, -, -, -, -, hηE'⟩ :=
    exists_genericPoint_strictTransformSeq_of_absorbed T hm hηE n hfirst
  have hsp : η' ⤳ p := by
    rw [specializes_iff_mem_closure, hgen.def]
    exact hp
  have hle' : (((bmoOneRun T hm).totalTransformSeq T.E n.castSucc).component i).stalkIdeal η' ≤
      ((bmoOneRun T hm).strictTransformSeq (IdealSheafData.vanishingIdeal (Closeds.closure {η}))
        n.castSucc).stalkIdeal η' := by
    rw [IdealSheafData.stalkIdeal_specializes _ hsp, IdealSheafData.stalkIdeal_specializes _ hsp]
    exact Ideal.map_mono hle
  exact hηE' i ((IdealSheafData.mem_support_iff_stalkIdeal_le_maximalIdeal _ _).mpr
    (hle'.trans ((IdealSheafData.mem_support_iff_stalkIdeal_le_maximalIdeal _ _).mp hgen.mem)))

include hη hηE hIc habs hfirst in
/-- **The generic point of an irreducible component of a member of the boundary at stage `n` does
not lie on the absorbed strict transform `c̃`** — conditional on `ClaimKC`, which is false for the
transcribed order (`Hironaka.Resolution.Algebraic.Wlo05.EmbeddedHypotheses`). At such a point `ζ`
the stalk of the member is the maximal ideal (`stalkIdeal_eq_maximalIdeal_of_mem_genericPoints`),
generated by one snc coordinate `z_c`; if `ζ ∈ c̃`, then the stalk of `c̃` is `(z_j : j ∈ s)` with
`c ∉ s` (`notContainedInMembers_strictTransformSeq_of_absorbed`) and `s ≠ ∅` (the marked ideal is
nonzero at `ζ` and lies in the centre, whose stalk is that of `c̃` by
`stalkIdeal_center_eq_of_absorbed`), so some `z_j` with `j ≠ c` lies in `(z_c)`, impossible for a
regular system of parameters. -/
theorem notMem_strictTransformSeq_support_of_mem_genericPoints_component (hKC : ClaimKC k)
    (i : ((bmoOneRun T hm).totalTransformSeq T.E n.castSucc).ι)
    {ζ : (bmoOneRun T hm).stage n.castSucc}
    (hζ : ζ ∈ Closeds.genericPoints
      (((bmoOneRun T hm).totalTransformSeq T.E n.castSucc).component i).support) :
    ζ ∉ ((bmoOneRun T hm).strictTransformSeq (IdealSheafData.vanishingIdeal (Closeds.closure {η}))
      n.castSucc).support := by
  intro hmem
  have hrun := isOrderGeSeq_bmoOneRun T hm
  obtain ⟨d, hd⟩ := T.smoothOfRelativeDimension
  have hsm : Smooth ((bmoOneRun T hm).stageMap n.castSucc ≫ (T.X.left ↘ Spec (.of k))) :=
    IsSmooth.smooth_stageMap (n := d) hrun.1 n.castSucc
  have hE₀ : ((bmoOneRun T hm).totalTransformSeq T.E n.castSucc).IsSnc :=
    IsOrderGeSeq.isSnc_totalTransformSeq (T.X.left ↘ Spec (.of k)) d hrun T.isSnc n.castSucc
  -- the member is smooth over `k`, so its stalk at its generic point is the maximal ideal
  have hVsm : Smooth ((((bmoOneRun T hm).totalTransformSeq T.E n.castSucc).component i).subschemeι
      ≫ (bmoOneRun T hm).stageMap n.castSucc ≫ (T.X.left ↘ Spec (.of k))) :=
    HasSncWith.smooth _ (hasSncWith_component_of_isSnc hE₀ i)
  have hmax := stalkIdeal_eq_maximalIdeal_of_mem_genericPoints
    ((bmoOneRun T hm).stageMap n.castSucc ≫ (T.X.left ↘ Spec (.of k))) _ hζ
  have := isRegularLocalRing_stalk
    ((bmoOneRun T hm).stageMap n.castSucc ≫ (T.X.left ↘ Spec (.of k))) ζ
  -- the snc data of `c̃` at `ζ`
  obtain ⟨m, z, ⟨⟨hspan, hdim⟩, c, hcinj, hc⟩, s, hs⟩ :=
    hasSncWith_strictTransformSeq_of_absorbed T hm hη hηE hIc n habs hfirst hKC ζ hmem
  have hs' : ((bmoOneRun T hm).strictTransformSeq (IdealSheafData.vanishingIdeal (Closeds.closure
      {η}))
      n.castSucc).stalkIdeal ζ = Ideal.span (z '' ↑s) := hs
  have hci : (((bmoOneRun T hm).totalTransformSeq T.E n.castSucc).component i).stalkIdeal ζ =
      Ideal.span {z (c ⟨i, hζ.1⟩)} := hc ⟨i, hζ.1⟩
  have hnle := notContainedInMembers_strictTransformSeq_of_absorbed T hm hηE n hfirst ζ hmem i hζ.1
  have hcs : c ⟨i, hζ.1⟩ ∉ s :=
    notMem_of_not_stalkIdeal_le ⟨hspan, hdim⟩ hs' hci hnle
  -- `s` is nonempty: the marked ideal is nonzero at `ζ` and lies in the centre (stalk `c̃`'s)
  have hne : s.Nonempty := by
    by_contra hemp
    rw [Finset.not_nonempty_iff_eq_empty] at hemp
    have hbot : ((bmoOneRun T hm).strictTransformSeq (IdealSheafData.vanishingIdeal
        (Closeds.closure {η}))
        n.castSucc).stalkIdeal ζ = ⊥ := by
      rw [hs', hemp, Finset.coe_empty, Set.image_empty, Ideal.span_empty]
    have hIle : ((bmoOneRun T hm).markedTransformSeq T.I 1 n.castSucc).stalkIdeal ζ ≤
        ((bmoOneRun T hm).strictTransformSeq (IdealSheafData.vanishingIdeal (Closeds.closure {η}))
          n.castSucc).stalkIdeal ζ := by
      rw [← stalkIdeal_center_eq_of_absorbed T hm hη hηE hIc n habs hfirst hKC hmem]
      exact IdealSheafData.stalkIdeal_mono (markedTransformSeq_le_center_of_absorbed T hm n) ζ
    have hnz := (T.induced (bmoOneRun T hm) hrun n.castSucc).isNonzeroEverywhere ζ
    have h1 : T.m = 1 := hm
    rw [hbot, le_bot_iff] at hIle
    apply hnz
    change ((bmoOneRun T hm).markedTransformSeq T.I T.m n.castSucc).stalkIdeal ζ = ⊥
    rw [h1]
    exact hIle
  obtain ⟨j, hj⟩ := hne
  -- `z_j ∈ c̃_ζ ≤ 𝔪_ζ = (z_c)`, hence `j = c`
  have hzj : z j ∈ Ideal.span {z (c ⟨i, hζ.1⟩)} := by
    rw [← hci, hmax]
    have hmem' : z j ∈ ((bmoOneRun T hm).strictTransformSeq (IdealSheafData.vanishingIdeal
        (Closeds.closure {η}))
        n.castSucc).stalkIdeal ζ := by
      rw [hs']
      exact Ideal.subset_span ⟨j, hj, rfl⟩
    exact ((IdealSheafData.mem_support_iff_stalkIdeal_le_maximalIdeal _ _).mp hmem) hmem'
  have hjc : j ∈ ({c ⟨i, hζ.1⟩} : Finset (Fin m)) := by
    rw [← span_singleton_le_span_image_iff hspan.symm hdim, Finset.coe_singleton,
      Set.image_singleton]
    exact (Ideal.span_singleton_le_iff_mem _).mpr hzj
  exact hcs (Finset.mem_singleton.mp hjc ▸ hj)

end Absorbed

end Hironaka.Resolution
