/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Algebraic.Monomial.Geometric.Pieces
import Hironaka.Resolution.Algebraic.Kol07.ComponentwiseBlowUp
import Hironaka.Resolution.Algebraic.Kol07.Thm35.Disjoin.Center
import Hironaka.Resolution.Algebraic.Monomial.Geometric.Nerve
import Hironaka.Resolution.Algebraic.Snc.DictionaryBoundary
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.IdealSheaf.StalkLe
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Nat.Choose.Multinomial
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

/-!
# The local structure of a realising piece family and of its centres

At a point `x` of a piece `piece c` of a family realising an snc boundary `E`
(`Hironaka/Resolution/Algebraic/Monomial/Geometric/Pieces.lean`), the piece is the member `E^{label
c}` near `x`: the other pieces of that label are closed and miss `x`
(`exists_affineOpens_piece_eq`), so the vanishing ideal of the piece has, at `x`, the stalk of the
member, the prime `(z_c)` in Kollár's coordinates (`stalkIdeal_vanishingIdeal_piece`). At a point of
the centre of a centre `S` of the state exactly one face `P ∈ S` passes
(`Hironaka/Resolution/Algebraic/Monomial/Geometric/Nerve.lean`), so the stalk of the centre is the
stalk of the ideal of `P`, generated by the coordinates `z_{c(i)}` of the members of the pieces of
`P` (`exists_stalkIdeal_centerOf_eq_span`): the centre has simple normal crossings with `E` in the
sense of [Kol07, Definition 24] (4) (`hasSncWith_centerOf`) and is smooth over `k`
(`smooth_centerOf`, Kollár's "in particular, `Z` is smooth"). These are conditions (2) and (3) of a
smooth blow-up sequence of order `≥ m`, [Kol07, Definition 66], for the blow-ups of Step 3; not in
the sources as statements, Kollár taking them as evident for the intersections `E^{j₁} ∩ ⋯ ∩
E^{j_r}`.

Two general facts are used: the stalk of the vanishing ideal of a closed set depends only on
the trace of the set on an affine neighbourhood (`stalkIdeal_vanishingIdeal_congr`), and a
point outside a finite union of closed sets has an affine neighbourhood outside it
(`exists_affineOpens_of_not_mem_sup`), both from
`Hironaka/Resolution/Algebraic/Kol07/Thm35/Disjoin/Center.lean`.
-/

@[expose] public section

universe u

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing Ideal Scheme
  Scheme.IdealSheafData

namespace Hironaka.Monomial

variable {X : Scheme.{u}}

namespace PieceFamily

open AlgebraicGeometry

variable {k : Type u} [Field k] (Φ : PieceFamily X) {E : DivisorFamily X}

/-! ### A piece is its member near each of its points -/

/-- The member of the label of a live component. -/
def memberOf (e : E.ι ≃o Fin Φ.nextLabel) (c : ℕ) (hc : c < Φ.nextComp) : E.ι :=
  e.symm ⟨Φ.label c, Φ.label_lt c hc⟩

@[simp] theorem coe_apply_memberOf (e : E.ι ≃o Fin Φ.nextLabel) (c : ℕ) (hc : c < Φ.nextComp) :
    ((e (Φ.memberOf e c hc) : Fin Φ.nextLabel) : ℕ) = Φ.label c := by
  simp [memberOf]

variable {e : E.ι ≃o Fin Φ.nextLabel}

/-- Near a point of a piece, the piece is the member of its label: an affine neighbourhood of
the point avoiding the other pieces of the label (closed, and missing the point since two pieces
of one label are disjoint). -/
theorem exists_affineOpens_piece_eq (hΦ : Φ.Realizes E e) {c : ℕ} (hc : c < Φ.nextComp) {x : X}
    (hx : x ∈ Φ.piece c) :
    ∃ U : X.affineOpens, x ∈ U.1 ∧
      ∀ y ∈ U.1, y ∈ Φ.piece c ↔ y ∈ (E.component (Φ.memberOf e c hc)).support := by
  classical
  set others : Finset ℕ :=
    (Finset.range Φ.nextComp).filter fun c' => c' ≠ c ∧ Φ.label c' = Φ.label c with hothers
  have hxo : x ∉ others.sup Φ.piece := by
    rw [mem_finset_sup_iff]
    rintro ⟨c', hc', hxc'⟩
    obtain ⟨hc'r, hne, hlab⟩ := Finset.mem_filter.mp hc'
    exact Φ.not_mem_piece_of_label_eq hΦ (Finset.mem_range.mp hc'r) hc hne hlab hxc' hx
  obtain ⟨U, hxU, hU⟩ := exists_affineOpens_of_not_mem_sup others Φ.piece hxo
  refine ⟨U, hxU, fun y hy => ⟨fun hyc => Φ.mem_support_component_of_mem_piece hΦ hc hyc, ?_⟩⟩
  intro hys
  rw [hΦ.support_eq, mem_finset_sup_iff] at hys
  obtain ⟨c', hc', hyc'⟩ := hys
  obtain ⟨hc'r, hlab⟩ := Finset.mem_filter.mp hc'
  rw [Φ.coe_apply_memberOf] at hlab
  by_cases hcc : c' = c
  · exact hcc ▸ hyc'
  · exact absurd ((mem_finset_sup_iff others Φ.piece y).mpr
      ⟨c', Finset.mem_filter.mpr ⟨hc'r, hcc, hlab⟩, hyc'⟩) (hU y hy)

/-- At a point of a piece, the vanishing ideal of the piece has the stalk of the member of its
label: the piece is the member near the point, and the member's stalk is prime (the member is a
regular subscheme, [Kol07, Definition 24] (1)), its own radical. -/
theorem stalkIdeal_vanishingIdeal_piece (hE : E.IsSnc) (hΦ : Φ.Realizes E e) {c : ℕ}
    (hc : c < Φ.nextComp) {x : X} (hx : x ∈ Φ.piece c) :
    (IdealSheafData.vanishingIdeal (Φ.piece c)).stalkIdeal x =
      (E.component (Φ.memberOf e c hc)).stalkIdeal x := by
  obtain ⟨U, hxU, hU⟩ := Φ.exists_affineOpens_piece_eq hΦ hc hx
  rw [stalkIdeal_vanishingIdeal_congr U hxU hU, IdealSheafData.vanishingIdeal_support]
  have hprime := Hironaka.Sequence.isPrime_stalkIdeal_of_isRegular _ (hE.1 _)
    (Φ.mem_support_component_of_mem_piece hΦ hc hx)
  refine le_antisymm ?_ (Hironaka.Sequence.stalkIdeal_le_stalkIdeal_radical _ x)
  exact (Hironaka.Sequence.stalkIdeal_radical_le _ x).trans hprime.radical.le

/-- Kollár's coordinate of a piece through `x`: with the snc coordinates `z` at `x`, the vanishing
ideal of a piece through `x` has stalk `(z_j)` for the coordinate `j` of its member. -/
theorem exists_stalkIdeal_vanishingIdeal_piece_eq_span (hE : E.IsSnc) (hΦ : Φ.Realizes E e)
    {c : ℕ} (hc : c < Φ.nextComp) {x : X} (hx : x ∈ Φ.piece c) {nx : ℕ}
    {z : Fin nx → X.presheaf.stalk x} (hz : E.IsSncAt x z) :
    ∃ j : Fin nx, (IdealSheafData.vanishingIdeal (Φ.piece c)).stalkIdeal x = span {z j} := by
  obtain ⟨-, cE, -, hcE⟩ := id hz
  have hmem : x ∈ (E.component (Φ.memberOf e c hc)).support :=
    Φ.mem_support_component_of_mem_piece hΦ hc hx
  exact ⟨cE ⟨Φ.memberOf e c hc, hmem⟩,
    (Φ.stalkIdeal_vanishingIdeal_piece hE hΦ hc hx).trans (hcE ⟨Φ.memberOf e c hc, hmem⟩)⟩

/-! ### The stalk of a center -/

/-- The ideal of a face `P` through `x` has, at `x`, the stalk generated by the coordinates of
the members of the pieces of `P` (the computation of `exists_stalkIdeal_disjoinCenter_eq_span`
in `Hironaka/Resolution/Algebraic/Kol07/Thm35/Disjoin/Center.lean`). -/
theorem exists_stalkIdeal_faceIdeal_eq_span (hE : E.IsSnc) (hΦ : Φ.Realizes E e) {P : Finset ℕ}
    (hP : ∀ c ∈ P, c < Φ.nextComp) {x : X} (hx : x ∈ Φ.faceSet P) {nx : ℕ}
    {z : Fin nx → X.presheaf.stalk x} (hz : E.IsSncAt x z) :
    ∃ s : Finset (Fin nx), (Φ.faceIdeal P).stalkIdeal x = span (z '' ↑s) ∧
      (∀ c ∈ P, ∃ j ∈ s, (IdealSheafData.vanishingIdeal (Φ.piece c)).stalkIdeal x = span {z j}) ∧
      ∀ j ∈ s, ∃ c ∈ P, (IdealSheafData.vanishingIdeal (Φ.piece c)).stalkIdeal x = span {z j} := by
  classical
  have hstalk : ∀ c ∈ P, ∃ j : Fin nx, (IdealSheafData.vanishingIdeal
      (Φ.piece c)).stalkIdeal x = span {z j} :=
    fun c hc => Φ.exists_stalkIdeal_vanishingIdeal_piece_eq_span hE hΦ (hP c hc)
      (Φ.mem_faceSet.mp hx c hc) hz
  rcases P.eq_empty_or_nonempty with rfl | ⟨c₀, hc₀⟩
  · refine ⟨∅, ?_, by simp, by simp⟩
    unfold faceIdeal
    rw [Hironaka.Sequence.stalkIdeal_biSup_finset]
    simp
  have : Nonempty (Fin nx) := ⟨(hstalk c₀ hc₀).choose⟩
  choose! g hg using hstalk
  refine ⟨P.image g, ?_, fun c hc => ⟨g c, Finset.mem_image_of_mem g hc, hg c hc⟩, fun j hj => ?_⟩
  · unfold faceIdeal
    rw [Hironaka.Sequence.stalkIdeal_biSup_finset, Finset.coe_image, Set.image_image,
      Set.image_eq_iUnion, Ideal.span_iUnion]
    exact iSup_congr fun c => by
      rw [Ideal.span_iUnion]
      exact iSup_congr fun hc => hg c (Finset.mem_coe.mp hc)
  · obtain ⟨c, hc, rfl⟩ := Finset.mem_image.mp hj
    exact ⟨c, hc, hg c hc⟩

variable {n m : ℕ} {hV : Φ.IsValid n m}

/-- At a point of `Z_P`, `P` a face of a center `S` of the state, the stalk of the center is the
stalk of the ideal of `P`: every other face of `S` misses the point
(`eq_of_mem_faceSet_of_isCenter`), so its factor has the unit stalk. -/
theorem stalkIdeal_centerOf_eq_faceIdeal {S : Finset (Finset ℕ)}
    (hS : (Φ.toState n m hV).IsCenter S) {P : Finset ℕ} (hP : P ∈ S) {x : X}
    (hx : x ∈ Φ.faceSet P) : (Φ.centerOf S).stalkIdeal x = (Φ.faceIdeal P).stalkIdeal x := by
  unfold centerOf
  rw [IdealSheafData.stalkIdeal_finset_prod, Finset.prod_eq_single P]
  · intro Q hQ hQP
    have hxQ : x ∉ (Φ.faceIdeal Q).support := by
      rw [Φ.support_faceIdeal]
      exact fun hxQ => hQP (Φ.eq_of_mem_faceSet_of_isCenter hS hQ hP hxQ hx)
    rw [Ideal.one_eq_top]
    exact IdealSheafData.stalkIdeal_eq_top_of_notMem_support _ hxQ
  · exact fun h => absurd hP h

/-- At a point of the centre of a centre of the state, the stalk of the centre is generated by
Kollár's coordinates of the pieces of the unique face through the point, as
[Kol07, Definition 24] (4) requires. -/
theorem exists_stalkIdeal_centerOf_eq_span (hE : E.IsSnc) (hΦ : Φ.Realizes E e)
    {S : Finset (Finset ℕ)} (hS : (Φ.toState n m hV).IsCenter S) {x : X}
    (hx : x ∈ (Φ.centerOf S).support) {nx : ℕ} {z : Fin nx → X.presheaf.stalk x}
    (hz : E.IsSncAt x z) :
    ∃ s : Finset (Fin nx), (Φ.centerOf S).stalkIdeal x = span (z '' ↑s) := by
  obtain ⟨P, hP, hxP⟩ := (Φ.mem_support_centerOf_iff S x).mp hx
  obtain ⟨s, hs, -, -⟩ := Φ.exists_stalkIdeal_faceIdeal_eq_span hE hΦ
    (fun c hc => Φ.lt_nextComp_of_mem_nerve (hS.1 hP) hc) hxP hz
  exact ⟨s, (Φ.stalkIdeal_centerOf_eq_faceIdeal hS hP hxP).trans hs⟩

/-- The centre of a centre of the state has simple normal crossings with `E`,
[Kol07, Definition 24] (4); this is condition (1) of a smooth blow-up of order `m` in
[Kol07, Definition 65]. -/
theorem hasSncWith_centerOf (hE : E.IsSnc) (hΦ : Φ.Realizes E e) {S : Finset (Finset ℕ)}
    (hS : (Φ.toState n m hV).IsCenter S) : E.HasSncWith (Φ.centerOf S) := by
  intro x hx
  obtain ⟨nx, z, hz⟩ := hE.2 x
  obtain ⟨s, hs⟩ := Φ.exists_stalkIdeal_centerOf_eq_span hE hΦ hS hx hz
  exact ⟨nx, z, hz, s, hs⟩

/-- The centre of a centre of the state is smooth over `k` (Kollár's "in particular, `Z` is
smooth" after [Kol07, Definition 24]; `smooth_of_hasSncWith` of
`Hironaka/Resolution/Algebraic/Kol07/Thm35/Disjoin/Center.lean`). -/
theorem smooth_centerOf [PerfectField k] (f : X ⟶ Spec (CommRingCat.of k)) [Smooth f]
    (hE : E.IsSnc) (hΦ : Φ.Realizes E e) {S : Finset (Finset ℕ)}
    (hS : (Φ.toState n m hV).IsCenter S) :
    Smooth ((Φ.centerOf S).subschemeι ≫ f) :=
  Hironaka.Sequence.smooth_of_hasSncWith f (Φ.hasSncWith_centerOf hE hΦ hS)

end PieceFamily

end Hironaka.Monomial
