/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUpAlgebra
public import Mathlib.RingTheory.Localization.Away.Basic

/-!
# The affine blow-up algebra `R[I/a]`: elements, basic properties, lifting

For a ring `R`, an ideal `I ⊆ R` and an element `a ∈ R`, the affine blow-up algebra `R[I/a]` is
the `R`-subalgebra of `R_a = R[1/a]` generated by the fractions `x/a`, `x ∈ I` [Sta, Tag 052P];
[Hau14, Definition 4.13] (the rings `R[g₁/gⱼ, …, g_k/gⱼ] ⊆ R_{gⱼ}`); [Hau14, Definition 4.16] (the
degree-zero part of the localized Rees algebra).  `Spec R[I/a]` is the chart of the blow-up of
`Spec R` along `I` at the generator `a` (`Hironaka.Scheme.BlowUp.AffineBlowUp.Chart`).  The
definition `AlgebraicGeometry.affineBlowUpAlgebra` is in
`Hironaka.Scheme.BlowUp.AffineBlowUpAlgebra`; this module builds its properties.

## Main declarations

* `affineBlowUpAlgebra.frac hx = x/a` for `x ∈ I`, the generators, written as
  `algebraMap x * invSelf a` (`coe_frac`; `coe_frac_eq_awayFrac` relates them to the fraction
  `awayFrac a 1 x` of the definition module); `affineBlowUpAlgebra_eq_adjoin` and the induction
  principle `affineBlowUpAlgebra.induction_on`.
* `affineBlowUpAlgebra.mem_iff`: for `a ∈ I` the elements of `R[I/a]` are the fractions `x/aⁿ`
  with `x ∈ Iⁿ`; `algebraMap_mul_pow_eq_iff`: `x/aⁿ = y/aᵐ` in `R_a` iff `aᵏ(aᵐx − aⁿy) = 0`
  for some `k`.
* `affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors`, `map_algebraMap_eq_span_singleton`,
  `isLocalization_away` [Sta, Tag 07Z3]: `a` is a nonzerodivisor of `R[I/a]`,
  `I·R[I/a] = a·R[I/a]` for `a ∈ I`, and `R[I/a]_a = R_a`.
* `affineBlowUpAlgebra.lift` with `lift_comp_algebraMap`, `lift_unique`, `mul_pow_of_comp_eq`
  [Hau14, Theorem 4.18, proof (d)]: if `β : R → S` sends `f ∈ I` to a nonzerodivisor generating
  `β(I)S`, there is a unique ring map `δ : R[I/f] → S` extending `β`, and it is given by
  "division by `β(f)`": `δ(x/fⁿ)·β(f)ⁿ = β(x)`.

## The arguments

*Elements.*  A generator `x/a` is `x/a¹`; `r ∈ R` is `r/a⁰`; a sum
`x/aⁿ + y/aᵐ = (x aᵐ + y aⁿ)/aⁿ⁺ᵐ` needs `a ∈ I` to keep the numerator in `Iⁿ⁺ᵐ`; a product is
`xy/aⁿ⁺ᵐ`.  Conversely `x/aⁿ ∈ R[I/a]` for `x ∈ Iⁿ` by induction on `n`, since `Iⁿ⁺¹ = I·Iⁿ`.

*Basic properties.*  `a` is a unit of `R_a ⊇ R[I/a]`, so multiplication by `a` is injective on
`R[I/a]`.  For `x ∈ I`, `x = a·(x/a)` shows `I·R[I/a] ⊆ (a)`, and `a ∈ I` gives the other
inclusion.  `R_a` is the localization of `R[I/a]` at `a` because `a` is a unit of `R_a`, every
element of `R_a` is `p/aⁿ = (image of p)·a⁻ⁿ`, and `R[I/a] → R_a` is injective.

*Lifting.*  Hauser defines `δ(hₗ/fˡ) = aₗ` where `β(hₗ) = aₗ β(f)ˡ`, the quotient being unique
because `β(f)` is a nonzerodivisor.  This division is realized as follows: `β` induces
`R_f → S_{β(f)}` on localizations; restricted to `R[I/f]` its values lie in the image of `S`,
because `β(x) ∈ (β(I)S)ⁿ = (β(f)ⁿ)` for `x ∈ Iⁿ`; and `S → S_{β(f)}` is injective because `β(f)` is
a nonzerodivisor.  So `δ` is the composite of the restricted map with the inverse of this
injection.  Uniqueness: a ring map `δ'` extending `β` satisfies `δ'(z) β(f)ⁿ = β(x)` whenever
`z fⁿ = x`, which pins `δ'(z)` by cancellation.

## Conventions

The definition takes any `a : R`; the hypothesis `a ∈ I` of the sources enters only the lemmas
that need it.  The fraction `x/a` is `algebraMap R R_a x * invSelf a` with
`IsLocalization.Away.invSelf a = 1/a`, and `x/aⁿ` is written multiplicatively (`y * aⁿ = x`).

## Boundary cases

`a = 0`: `R_a` and `R[I/a]` are the zero ring.  `a = 1`: `R[I/1]` is the image of `R` in
`R_1 ≅ R`.  `I = ⊥`: `R[⊥/a]` is the image of `R` in `R_a`.  `I = ⊤`, `a ∈ I` arbitrary:
`R[R/a] = R_a`.
-/

@[expose] public section

universe u v

namespace AlgebraicGeometry

variable {R : Type u} [CommRing R] (I : Ideal R) (a : R)

variable {a} in
/-- The fraction `x/a` of `R_a` (the generator shape of the definition module) is
`algebraMap x * invSelf a` with `invSelf a = 1/a`. -/
theorem awayFrac_one_eq (x : R) :
    awayFrac a 1 x = algebraMap R (Localization.Away a) x * IsLocalization.Away.invSelf a := by
  rw [awayFrac_one, Localization.mk_eq_mk', IsLocalization.mk'_eq_mul_mk'_one]
  rfl

/-- `R[I/a]` is generated by the fractions `algebraMap x * invSelf a`, `x ∈ I` (the definition's
generators `Localization.mk x a` rewritten). -/
theorem affineBlowUpAlgebra_eq_adjoin :
    affineBlowUpAlgebra I a = Algebra.adjoin R
      ((fun x : R => algebraMap R (Localization.Away a) x * IsLocalization.Away.invSelf a) ''
        I) := by
  unfold affineBlowUpAlgebra
  congr 1
  exact Set.image_congr fun x _ => (awayFrac_one x).symm.trans (awayFrac_one_eq x)

namespace affineBlowUpAlgebra

open IsLocalization.Away

variable {I a}

theorem mul_invSelf_mem {x : R} (hx : x ∈ I) :
    algebraMap R (Localization.Away a) x * invSelf a ∈ affineBlowUpAlgebra I a := by
  rw [affineBlowUpAlgebra_eq_adjoin]
  exact Algebra.subset_adjoin ⟨x, hx, rfl⟩

/-- The generator `x/a ∈ R[I/a]` for `x ∈ I`. -/
noncomputable def frac {x : R} (hx : x ∈ I) : affineBlowUpAlgebra I a :=
  ⟨algebraMap R (Localization.Away a) x * invSelf a, mul_invSelf_mem hx⟩

@[simp]
theorem coe_frac {x : R} (hx : x ∈ I) :
    (frac (a := a) hx : Localization.Away a) = algebraMap R (Localization.Away a) x * invSelf a :=
  rfl

theorem coe_frac_eq_awayFrac {x : R} (hx : x ∈ I) :
    (frac (a := a) hx : Localization.Away a) = awayFrac a 1 x :=
  (awayFrac_one_eq x).symm

/-- Induction over `R[I/a]` along its generators `x/a`, the constants, sums and products. -/
@[elab_as_elim]
theorem induction_on {p : ∀ y : Localization.Away a, y ∈ affineBlowUpAlgebra I a → Prop}
    (mem : ∀ x (hx : x ∈ I),
      p (algebraMap R (Localization.Away a) x * invSelf a) (mul_invSelf_mem hx))
    (algebraMap : ∀ r, p (algebraMap R (Localization.Away a) r) (Subalgebra.algebraMap_mem _ r))
    (add : ∀ y z hy hz, p y hy → p z hz → p (y + z) (add_mem hy hz))
    (mul : ∀ y z hy hz, p y hy → p z hz → p (y * z) (mul_mem hy hz))
    {y : Localization.Away a} (hy : y ∈ affineBlowUpAlgebra I a) : p y hy := by
  have heq := affineBlowUpAlgebra_eq_adjoin I a
  have hmem := heq.ge
  refine Algebra.adjoin_induction (p := fun y _ => ∀ hy : y ∈ affineBlowUpAlgebra I a, p y hy)
    ?_ ?_ ?_ ?_ (heq.le hy) hy
  · rintro _ ⟨x, hx, rfl⟩ _
    exact mem x hx
  · intro r _
    exact algebraMap r
  · intro y z hy hz ihy ihz _
    exact add y z (hmem hy) (hmem hz) (ihy _) (ihz _)
  · intro y z hy hz ihy ihz _
    exact mul y z (hmem hy) (hmem hz) (ihy _) (ihz _)

/-- `x/aⁿ ∈ R[I/a]` for `x ∈ Iⁿ`. -/
theorem mul_invSelf_pow_mem :
    ∀ (n : ℕ) {x : R}, x ∈ I ^ n →
      algebraMap R (Localization.Away a) x * invSelf a ^ n ∈ affineBlowUpAlgebra I a
  | 0, x, _ => by simp only [pow_zero, mul_one]; exact Subalgebra.algebraMap_mem _ x
  | n + 1, x, hx => by
    rw [pow_succ'] at hx
    refine Submodule.mul_induction_on hx (fun m hm k hk => ?_) (fun y z hy hz => ?_)
    · have : algebraMap R (Localization.Away a) (m * k) * invSelf a ^ (n + 1) =
          (algebraMap R (Localization.Away a) m * invSelf a) *
            (algebraMap R (Localization.Away a) k * invSelf a ^ n) := by
        rw [map_mul, pow_succ']; ring
      rw [this]
      exact mul_mem (mul_invSelf_mem hm) (mul_invSelf_pow_mem n hk)
    · rw [map_add, add_mul]
      exact add_mem hy hz

/-- For `a ∈ I`, `y ∈ R[I/a]` iff `y · aⁿ = x` in `R_a` for some `n` and `x ∈ Iⁿ`
[Sta, Tag 052P]. -/
theorem mem_iff (ha : a ∈ I) (y : Localization.Away a) :
    y ∈ affineBlowUpAlgebra I a ↔
      ∃ n : ℕ, ∃ x ∈ I ^ n, y * algebraMap R (Localization.Away a) a ^ n =
        algebraMap R (Localization.Away a) x := by
  constructor
  · intro hy
    induction hy using induction_on with
    | mem x hx =>
      exact ⟨1, x, by simpa using hx, by rw [pow_one, mul_assoc, mul_comm (invSelf a),
        mul_invSelf, mul_one]⟩
    | algebraMap r => exact ⟨0, r, by simp, by simp⟩
    | add y z _ _ hy hz =>
      obtain ⟨n, x, hx, hxy⟩ := hy
      obtain ⟨m, x', hx', hx'z⟩ := hz
      refine ⟨n + m, x * a ^ m + x' * a ^ n, ?_, ?_⟩
      · refine add_mem ?_ ?_
        · rw [pow_add]; exact Ideal.mul_mem_mul hx (Ideal.pow_mem_pow ha m)
        · rw [pow_add, mul_comm (I ^ n)]; exact Ideal.mul_mem_mul hx' (Ideal.pow_mem_pow ha n)
      · rw [map_add, map_mul, map_mul, map_pow, map_pow, ← hxy, ← hx'z, pow_add]; ring
    | mul y z _ _ hy hz =>
      obtain ⟨n, x, hx, hxy⟩ := hy
      obtain ⟨m, x', hx', hx'z⟩ := hz
      refine ⟨n + m, x * x', by rw [pow_add]; exact Ideal.mul_mem_mul hx hx', ?_⟩
      rw [map_mul, ← hxy, ← hx'z, pow_add]; ring
  · rintro ⟨n, x, hx, hxy⟩
    have : y = algebraMap R (Localization.Away a) x * invSelf a ^ n := by
      calc y = y * (algebraMap R (Localization.Away a) a * invSelf a) ^ n := by
            rw [mul_invSelf, one_pow, mul_one]
        _ = algebraMap R (Localization.Away a) x * invSelf a ^ n := by
            rw [mul_pow, ← mul_assoc, hxy]
    rw [this]
    exact mul_invSelf_pow_mem n hx

/-- `x/aⁿ = y/aᵐ` in `R_a` iff `aᵏ(aᵐx − aⁿy) = 0` in `R` for some `k` [Sta, Tag 052P]. -/
theorem algebraMap_mul_pow_eq_iff (x y : R) (n m : ℕ) :
    algebraMap R (Localization.Away a) x * algebraMap R (Localization.Away a) a ^ m =
        algebraMap R (Localization.Away a) y * algebraMap R (Localization.Away a) a ^ n ↔
      ∃ k : ℕ, a ^ k * (a ^ m * x - a ^ n * y) = 0 := by
  rw [← map_pow, ← map_pow, ← map_mul, ← map_mul,
    IsLocalization.eq_iff_exists (Submonoid.powers a)]
  constructor
  · rintro ⟨⟨c, k, rfl⟩, hc⟩
    refine ⟨k, ?_⟩
    rw [mul_sub, sub_eq_zero, mul_comm (a ^ m), mul_comm (a ^ n)]
    exact hc
  · rintro ⟨k, hk⟩
    refine ⟨⟨a ^ k, k, rfl⟩, ?_⟩
    rw [mul_sub, sub_eq_zero, mul_comm (a ^ m), mul_comm (a ^ n)] at hk
    exact hk

/-! ### Basic properties -/

/-- `a` is a nonzerodivisor of `R[I/a]`, being a unit of `R_a ⊇ R[I/a]` [Sta, Tag 07Z3]. -/
theorem algebraMap_mem_nonZeroDivisors :
    algebraMap R (affineBlowUpAlgebra I a) a ∈ nonZeroDivisors (affineBlowUpAlgebra I a) := by
  have key : ∀ z : affineBlowUpAlgebra I a,
      z * algebraMap R (affineBlowUpAlgebra I a) a = 0 → z = 0 := fun z hz =>
    Subtype.ext ((algebraMap_isUnit (S := Localization.Away a) a).mul_left_eq_zero.mp
      (congrArg Subtype.val hz))
  exact mem_nonZeroDivisors_iff.mpr ⟨fun z hz => key z (by rw [mul_comm]; exact hz), key⟩

/-- `I·R[I/a] = a·R[I/a]` for `a ∈ I`, since `x = a·(x/a)` for `x ∈ I` [Sta, Tag 07Z3]. -/
theorem map_algebraMap_eq_span_singleton (ha : a ∈ I) :
    I.map (algebraMap R (affineBlowUpAlgebra I a)) =
      Ideal.span {algebraMap R (affineBlowUpAlgebra I a) a} := by
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro x hx
    rw [Ideal.mem_comap, Ideal.mem_span_singleton']
    refine ⟨frac hx, Subtype.ext ?_⟩
    change algebraMap R (Localization.Away a) x * invSelf a * algebraMap R (Localization.Away a) a
      = algebraMap R (Localization.Away a) x
    rw [mul_assoc, mul_comm (invSelf a), mul_invSelf, mul_one]
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    exact Ideal.mem_map_of_mem _ ha

/-- `R[I/a]_a = R_a`: the ring `R_a` is the localization of its subring `R[I/a]` at `a`
[Sta, Tag 07Z3]. -/
theorem isLocalization_away :
    IsLocalization.Away (algebraMap R (affineBlowUpAlgebra I a) a) (Localization.Away a) := by
  refine IsLocalization.Away.mk _ (algebraMap_isUnit (S := Localization.Away a) a) ?_ ?_
  · intro s
    obtain ⟨n, p, hp⟩ := IsLocalization.Away.surj (S := Localization.Away a) a s
    exact ⟨n, algebraMap R (affineBlowUpAlgebra I a) p, hp⟩
  · intro x y h
    exact ⟨0, by rw [pow_zero, one_mul, one_mul]; exact Subtype.ext h⟩

/-- Two `R`-algebra maps out of `R[I/a]` agreeing on the generators `x/a` are equal. -/
theorem algHom_ext {A : Type v} [Semiring A] [Algebra R A] {φ ψ : affineBlowUpAlgebra I a →ₐ[R] A}
    (h : ∀ x (hx : x ∈ I), φ (frac hx) = ψ (frac hx)) : φ = ψ := by
  refine AlgHom.ext fun z => ?_
  obtain ⟨z, hz⟩ := z
  induction hz using induction_on with
  | mem x hx => exact h x hx
  | algebraMap r =>
    exact (φ.commutes r).trans (ψ.commutes r).symm
  | add y z hy hz ihy ihz =>
    change φ (⟨y, hy⟩ + ⟨z, hz⟩) = ψ (⟨y, hy⟩ + ⟨z, hz⟩)
    rw [map_add, map_add, ihy, ihz]
  | mul y z hy hz ihy ihz =>
    change φ (⟨y, hy⟩ * ⟨z, hz⟩) = ψ (⟨y, hy⟩ * ⟨z, hz⟩)
    rw [map_mul, map_mul, ihy, ihz]

/-! ### The lifting lemma -/

section Lift

variable {S : Type v} [CommRing S] (β : R →+* S) {f : R}

/-- The map `R_f → S_{β(f)}` induced by `β` on localizations. -/
noncomputable def liftAux : Localization.Away f →+* Localization.Away (β f) :=
  IsLocalization.Away.map (Localization.Away f) (Localization.Away (β f)) β f

theorem liftAux_algebraMap (r : R) :
    liftAux β (algebraMap R (Localization.Away f) r) =
      algebraMap S (Localization.Away (β f)) (β r) := by
  unfold liftAux IsLocalization.Away.map
  exact IsLocalization.map_eq _ _

variable (hf : f ∈ I) (hβf : β f ∈ nonZeroDivisors S) (hI : I.map β = Ideal.span {β f})
include hf hI

/-- The restriction of `R_f → S_{β(f)}` to `R[I/f]` lands in the image of `S`: for `x ∈ Iⁿ`,
`β(x) ∈ (β(I)S)ⁿ = (β(f)ⁿ)`, so `β(x)/β(f)ⁿ` comes from `S`. -/
theorem liftAux_mem_range (z : affineBlowUpAlgebra I f) :
    liftAux β (z : Localization.Away f) ∈ (algebraMap S (Localization.Away (β f))).range := by
  obtain ⟨n, x, hx, hz⟩ := (mem_iff hf z).mp z.2
  have hx' : β x ∈ Ideal.span {β f ^ n} := by
    rw [← Ideal.span_singleton_pow, ← hI, ← Ideal.map_pow]
    exact Ideal.mem_map_of_mem β hx
  obtain ⟨s, hs⟩ := Ideal.mem_span_singleton'.mp hx'
  refine ⟨s, ?_⟩
  have hu : IsUnit (algebraMap S (Localization.Away (β f)) (β f) ^ n) :=
    (algebraMap_isUnit (S := Localization.Away (β f)) (β f)).pow n
  apply hu.mul_left_injective
  calc algebraMap S (Localization.Away (β f)) s * algebraMap S (Localization.Away (β f)) (β f) ^ n
      = algebraMap S (Localization.Away (β f)) (β x) := by rw [← hs, map_mul, map_pow]
    _ = liftAux β (algebraMap R (Localization.Away f) x) := (liftAux_algebraMap β x).symm
    _ = liftAux β ((z : Localization.Away f) * algebraMap R (Localization.Away f) f ^ n) := by
        rw [hz]
    _ = liftAux β z * algebraMap S (Localization.Away (β f)) (β f) ^ n := by
        rw [map_mul, map_pow, liftAux_algebraMap]

omit hf hI
include hβf

theorem injective_algebraMap_away :
    Function.Injective (algebraMap S (Localization.Away (β f))) :=
  IsLocalization.injective (M := Submonoid.powers (β f)) (Localization.Away (β f))
    (Submonoid.powers_le.mpr hβf)

include hf hI

/-- The ring map `δ : R[I/f] → S` extending `β`, given by division by the nonzerodivisor `β(f)`
[Hau14, Theorem 4.18, proof (d)]. -/
noncomputable def lift : affineBlowUpAlgebra I f →+* S :=
  ((RingEquiv.ofBijective (algebraMap S (Localization.Away (β f))).rangeRestrict
    ⟨fun _ _ h => injective_algebraMap_away β hβf (congrArg Subtype.val h),
      (algebraMap S (Localization.Away (β f))).rangeRestrict_surjective⟩).symm : _ →+* S).comp
    (((liftAux β).comp (affineBlowUpAlgebra I f).val.toRingHom).codRestrict _
      (liftAux_mem_range β hf hI))

theorem algebraMap_lift (z : affineBlowUpAlgebra I f) :
    algebraMap S (Localization.Away (β f)) (lift β hf hβf hI z) = liftAux β z := by
  set e := RingEquiv.ofBijective (algebraMap S (Localization.Away (β f))).rangeRestrict
    ⟨fun _ _ h => injective_algebraMap_away β hβf (congrArg Subtype.val h),
      (algebraMap S (Localization.Away (β f))).rangeRestrict_surjective⟩
  have : algebraMap S (Localization.Away (β f)) (lift β hf hβf hI z) =
      (e (e.symm ⟨liftAux β z, liftAux_mem_range β hf hI z⟩) : Localization.Away (β f)) := rfl
  rw [this, RingEquiv.apply_symm_apply]

/-- The lift extends `β`. -/
theorem lift_comp_algebraMap :
    (lift β hf hβf hI).comp (algebraMap R (affineBlowUpAlgebra I f)) = β := by
  refine RingHom.ext fun r => injective_algebraMap_away β hβf ?_
  rw [RingHom.comp_apply, algebraMap_lift]
  exact liftAux_algebraMap β r

omit hf hβf hI

/-- Every ring map `δ : R[I/f] → S` extending `β` satisfies `δ(z)·β(f)ⁿ = β(x)` whenever
`z·fⁿ = x`; this is Hauser's formula `δ(hₗ/fˡ) = aₗ` with `β(hₗ) = aₗ β(f)ˡ`
[Hau14, Theorem 4.18, proof (d)]. -/
theorem mul_pow_of_comp_eq (δ : affineBlowUpAlgebra I f →+* S)
    (hδ : δ.comp (algebraMap R (affineBlowUpAlgebra I f)) = β) (z : affineBlowUpAlgebra I f)
    (x : R) (n : ℕ)
    (hz : (z : Localization.Away f) * algebraMap R (Localization.Away f) f ^ n =
      algebraMap R (Localization.Away f) x) :
    δ z * β f ^ n = β x := by
  have hz' : z * algebraMap R (affineBlowUpAlgebra I f) f ^ n =
      algebraMap R (affineBlowUpAlgebra I f) x := Subtype.ext hz
  rw [← hδ, RingHom.comp_apply, RingHom.comp_apply, ← map_pow, ← map_mul, hz']

include hf hβf hI

/-- A ring map `R[I/f] → S` extending `β` is the lift: `δ` is unique with this property
[Hau14, Theorem 4.18, proof (d)]. -/
theorem lift_unique (δ : affineBlowUpAlgebra I f →+* S)
    (hδ : δ.comp (algebraMap R (affineBlowUpAlgebra I f)) = β) : δ = lift β hf hβf hI := by
  refine RingHom.ext fun z => ?_
  obtain ⟨n, x, hx, hz⟩ := (mem_iff hf z).mp z.2
  have h₁ := mul_pow_of_comp_eq β δ hδ z x n hz
  have h₂ := mul_pow_of_comp_eq β (lift β hf hβf hI) (lift_comp_algebraMap β hf hβf hI) z x n hz
  exact (mul_cancel_right_mem_nonZeroDivisors (pow_mem hβf n)).mp (h₁.trans h₂.symm)

end Lift

end affineBlowUpAlgebra

end AlgebraicGeometry
