/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.GroupTheory.MonoidLocalization.Away
public import Mathlib.Algebra.Algebra.Subalgebra.Lattice
public import Mathlib.RingTheory.Ideal.Defs
public import Mathlib.RingTheory.OreLocalization.Ring
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Localization.Defs

/-!
# The affine blow-up algebra `R[I/a]`

For an ideal `I ⊆ R` and `a ∈ I`, the affine blow-up algebra `R[I/a]` is the `R`-subalgebra of
the localization `R_a = R[1/a]` generated by the fractions `x/a`, `x ∈ I` [Sta, Tag 052P]; it is
Hauser's ring extension `R_j = R[g₁/g_j, …, g_k/g_j] ⊆ R_{g_j}` [Hau14, Definition 4.13] and the
degree-zero part of the localized Rees algebra, consisting of the fractions `f/gˡ` with `f ∈ Iˡ`
[Hau14, Definition 4.16].  Its elements are exactly the fractions `x/aⁿ` with `x ∈ Iⁿ`
(`mem_affineBlowUpAlgebra_iff`): the set of such fractions contains the generators and the
constants and is closed under sums (`x/aⁿ + y/aᵐ = (aᵐx + aⁿy)/aⁿ⁺ᵐ`, with `aᵐx ∈ Iⁿ⁺ᵐ` because
`a ∈ I`) and products, and conversely `x/aⁿ⁺¹ = ∑ (d/aⁿ)(c/a)` for `x = ∑ dc ∈ Iⁿ · I`.
Equality of fractions is that of `R_a`: `x/aⁿ = y/aᵐ` iff `aᵏ(aᵐx − aⁿy) = 0` for some `k`
(`IsLocalization.mk'_eq_iff_eq`).

The definition makes sense for every `a`; the membership lemma uses `a ∈ I` (as the sources
assume) exactly once, to place `aᵐx` in `Iⁿ⁺ᵐ` when adding two fractions — for `a ∉ I` it fails
(`R = k[a, b]`, `I = (b)`: `b/a + b²/a²` is no `z/aⁿ` with `z ∈ (bⁿ)`).  Boundary cases: `a = 1`
gives `R_1 ≅ R` and `R[I/1] = R_1` (every constant is a fraction `x/1⁰`); `a` nilpotent gives
the zero ring `R_a`.  The properties of `R[I/a]` (its generators, `a` a nonzerodivisor,
`I·R[I/a] = a·R[I/a]`, the lifting property) are in `Hironaka.Scheme.BlowUp.AffineAlgebra`; its
spectrum is the chart of the affine blow-up at `a` (`Hironaka.Scheme.BlowUp.Rees.ChartRing`).
-/

@[expose] public section

namespace AlgebraicGeometry

universe u

variable {R : Type u} [CommRing R]

/-- The fraction `x / aⁿ` in `R_a`, the shape of the elements of `R[I/a]`. -/
noncomputable abbrev awayFrac (a : R) (n : ℕ) (x : R) : Localization.Away a :=
  Localization.mk x ⟨a ^ n, n, rfl⟩

/-- **The affine blow-up algebra** `R[I/a]` [Sta, Tag 052P]; [Hau14, Definitions 4.13 and 4.16]:
the `R`-subalgebra of `R_a` generated by the fractions `x/a`, `x ∈ I`.  Its elements are the
fractions `x/aⁿ` with `x ∈ Iⁿ` (`mem_affineBlowUpAlgebra_iff`). -/
noncomputable def affineBlowUpAlgebra (I : Ideal R) (a : R) : Subalgebra R (Localization.Away a) :=
  Algebra.adjoin R ((fun x => Localization.mk x ⟨a, Submonoid.mem_powers a⟩) '' (I : Set R))

variable {I : Ideal R} {a : R}

theorem awayFrac_one (x : R) : awayFrac a 1 x = Localization.mk x ⟨a, Submonoid.mem_powers a⟩ := by
  unfold awayFrac
  congr 1
  exact Subtype.ext (pow_one a)

theorem awayFrac_zero (x : R) : awayFrac a 0 x = algebraMap R (Localization.Away a) x := by
  rw [← Localization.mk_one_eq_algebraMap]
  unfold awayFrac
  congr 1
  exact Subtype.ext (pow_zero a)

theorem awayFrac_add (n m : ℕ) (x y : R) :
    awayFrac a n x + awayFrac a m y = awayFrac a (n + m) (a ^ m * x + a ^ n * y) := by
  unfold awayFrac
  rw [Localization.add_mk]
  congr 1
  · ring
  · exact Subtype.ext (pow_add a n m).symm

theorem awayFrac_mul (n m : ℕ) (x y : R) :
    awayFrac a n x * awayFrac a m y = awayFrac a (n + m) (x * y) := by
  unfold awayFrac
  rw [Localization.mk_mul]
  congr 1
  exact Subtype.ext (pow_add a n m).symm

/-- The fractions `x/aⁿ`, `x ∈ Iⁿ`, lie in `R[I/a]` [Sta, Tag 052P]. -/
theorem awayFrac_mem_affineBlowUpAlgebra (n : ℕ) {x : R} (hx : x ∈ I ^ n) :
    awayFrac a n x ∈ affineBlowUpAlgebra I a := by
  induction n generalizing x with
  | zero =>
    rw [awayFrac_zero]
    exact Subalgebra.algebraMap_mem _ x
  | succ n ih =>
    rw [pow_succ] at hx
    refine Submodule.mul_induction_on'
      (C := fun x _ => awayFrac a (n + 1) x ∈ affineBlowUpAlgebra I a) ?_ ?_ hx
    · intro d hd c hc
      rw [← awayFrac_mul, awayFrac_one]
      exact Subalgebra.mul_mem _ (ih hd) (Algebra.subset_adjoin ⟨c, hc, rfl⟩)
    · intro x _ y _ hx' hy'
      have : awayFrac a (n + 1) (x + y) = awayFrac a (n + 1) x + awayFrac a (n + 1) y := by
        unfold awayFrac
        rw [Localization.add_mk_self]
      rw [this]
      exact Subalgebra.add_mem _ hx' hy'

/-- The membership lemma [Sta, Tag 052P]: the elements of `R[I/a]` are exactly the fractions
`x/aⁿ` with `x ∈ Iⁿ`. -/
theorem mem_affineBlowUpAlgebra_iff (ha : a ∈ I) {y : Localization.Away a} :
    y ∈ affineBlowUpAlgebra I a ↔ ∃ n, ∃ x ∈ I ^ n, y = awayFrac a n x := by
  constructor
  · intro hy
    refine Algebra.adjoin_induction (p := fun y _ => ∃ n, ∃ x ∈ I ^ n, y = awayFrac a n x)
      ?_ ?_ ?_ ?_ hy
    · rintro _ ⟨x, hx, rfl⟩
      exact ⟨1, x, by simpa using hx, (awayFrac_one x).symm⟩
    · intro r
      exact ⟨0, r, by simp, (awayFrac_zero r).symm⟩
    · rintro _ _ _ _ ⟨n, x, hx, rfl⟩ ⟨m, y, hy, rfl⟩
      refine ⟨n + m, a ^ m * x + a ^ n * y, Ideal.add_mem _ ?_ ?_, awayFrac_add n m x y⟩
      · rw [add_comm n m, pow_add]
        exact Ideal.mul_mem_mul (Ideal.pow_mem_pow ha m) hx
      · rw [pow_add]
        exact Ideal.mul_mem_mul (Ideal.pow_mem_pow ha n) hy
    · rintro _ _ _ _ ⟨n, x, hx, rfl⟩ ⟨m, y, hy, rfl⟩
      exact ⟨n + m, x * y, (pow_add I n m).symm ▸ Ideal.mul_mem_mul hx hy, awayFrac_mul n m x y⟩
  · rintro ⟨n, x, hx, rfl⟩
    exact awayFrac_mem_affineBlowUpAlgebra n hx

end AlgebraicGeometry
