/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.RingTheory.Ideal.Maps
public import Mathlib.RingTheory.LocalRing.Defs
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic

/-!
# Cancellation by a nonzerodivisor and the local criterion for a generator

Two elementary facts about principal ideals generated by nonzerodivisors, both extracted from
step (c) of the proof of the universal property of the blow-up [Hau14, Theorem 4.18, proof (c)].

## Main declarations

* `AlgebraicGeometry.isUnit_of_span_mul_eq_span`: if `b` is a nonzerodivisor and `(bc) = (b)`,
  then `c` is a unit — write `b = r·bc` and cancel `b`, so `rc = 1`.
* `AlgebraicGeometry.exists_unit_mul_of_span_eq_span`, `mem_nonZeroDivisors_of_span_eq_span`: a
  generator of an ideal generated by a nonzerodivisor `b` is a unit multiple of `b`, hence itself
  a nonzerodivisor.
* `AlgebraicGeometry.exists_generator_of_isLocalRing` [Hau14, Theorem 4.18, proof (c)]: for
  `β : R → S` with `S` local and `β(I)S = (h)`, `h` a nonzerodivisor, some `f ∈ I` has `β(f)`
  generating `β(I)S`.  As printed: `h = ∑ β(fᵢ) sᵢ` with `fᵢ ∈ I`, `β(fᵢ) = tᵢ h`, so
  `(∑ sᵢ tᵢ) h = h` and `∑ sᵢ tᵢ = 1` by cancellation; in a local ring some `sᵢ tᵢ`, hence
  some `tᵢ`, is a unit, and then `β(fᵢ) = tᵢ h` generates `(h)`.

## Boundary cases

In the zero ring every element is a nonzerodivisor and a unit, and every statement is trivially
true.  A local ring is nontrivial by definition, so `1 ∉ 𝔪` in the last argument.
-/

public section

universe u v

namespace AlgebraicGeometry

variable {S : Type u} [CommRing S]

/-- If `b` is a nonzerodivisor and `(bc) = (b)`, then `c` is a unit: the cancellation step of
[Hau14, Theorem 4.18, proof (c)]. -/
theorem isUnit_of_span_mul_eq_span {b c : S} (hb : b ∈ nonZeroDivisors S)
    (h : Ideal.span {b * c} = Ideal.span {b}) : IsUnit c := by
  have hmem : b ∈ Ideal.span {b * c} := h ▸ Ideal.mem_span_singleton_self b
  obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.mp hmem
  refine isUnit_iff_exists_inv.mpr ⟨r, ?_⟩
  rw [← mul_cancel_right_mem_nonZeroDivisors hb, one_mul]
  calc c * r * b = r * (b * c) := by ring
    _ = b := hr

/-- A generator of the ideal generated by a nonzerodivisor `b` is a unit multiple of `b`. -/
theorem exists_unit_mul_of_span_eq_span {b b' : S} (hb : b ∈ nonZeroDivisors S)
    (h : Ideal.span {b'} = Ideal.span {b}) : ∃ u : Sˣ, b' = u * b := by
  have hmem : b' ∈ Ideal.span {b} := h ▸ Ideal.mem_span_singleton_self b'
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp hmem
  have hu : IsUnit c := isUnit_of_span_mul_eq_span hb (by rw [mul_comm, hc]; exact h)
  exact ⟨hu.unit, by rw [IsUnit.unit_spec, hc]⟩

/-- A generator of the ideal generated by a nonzerodivisor is a nonzerodivisor. -/
theorem mem_nonZeroDivisors_of_span_eq_span {b b' : S} (hb : b ∈ nonZeroDivisors S)
    (h : Ideal.span {b'} = Ideal.span {b}) : b' ∈ nonZeroDivisors S := by
  obtain ⟨u, rfl⟩ := exists_unit_mul_of_span_eq_span hb h
  exact mul_mem u.isUnit.mem_nonZeroDivisors hb

/-- If `β : R → S` with `S` local and `β(I)S = (h)` for a nonzerodivisor `h`, then some `f ∈ I`
has `β(f)` generating `β(I)S` [Hau14, Theorem 4.18, proof (c)]. -/
theorem exists_generator_of_isLocalRing {R : Type v} [CommRing R] [IsLocalRing S] (β : R →+* S)
    (I : Ideal R) {h : S} (hh : h ∈ nonZeroDivisors S) (hI : I.map β = Ideal.span {h}) :
    ∃ f ∈ I, I.map β = Ideal.span {β f} := by
  have hmem : h ∈ I.map β := hI ▸ Ideal.mem_span_singleton_self h
  have hmem' : h ∈ Submodule.span S (β '' (I : Set R)) := hmem
  obtain ⟨t, hts, hht⟩ := Submodule.mem_span_finite_of_mem_span hmem'
  obtain ⟨c, -, hc⟩ := Submodule.mem_span_finset.mp hht
  have hd : ∀ i ∈ t, ∃ d : S, d * h = i := fun i hi =>
    Ideal.mem_span_singleton'.mp (hI ▸ Ideal.subset_span (hts hi))
  choose! d hd using hd
  have hsum : (∑ i ∈ t, c i * d i) * h = h :=
    calc (∑ i ∈ t, c i * d i) * h = ∑ i ∈ t, c i * (d i * h) := by
          rw [Finset.sum_mul]; exact Finset.sum_congr rfl fun i _ => mul_assoc _ _ _
      _ = ∑ i ∈ t, c i • i := Finset.sum_congr rfl fun i hi => by rw [hd i hi, smul_eq_mul]
      _ = h := hc
  have hsum' : ∑ i ∈ t, c i * d i = 1 :=
    (mul_cancel_right_mem_nonZeroDivisors hh).mp (by rw [one_mul]; exact hsum)
  obtain ⟨i, hi, hu⟩ : ∃ i ∈ t, IsUnit (c i * d i) := by
    by_contra hcon
    push Not at hcon
    have hmax : (∑ i ∈ t, c i * d i) ∈ IsLocalRing.maximalIdeal S :=
      Submodule.sum_mem _ fun i hi =>
        (IsLocalRing.mem_maximalIdeal _).mpr (mem_nonunits_iff.mpr (hcon i hi))
    rw [hsum'] at hmax
    exact (IsLocalRing.maximalIdeal.isMaximal S).ne_top ((Ideal.eq_top_iff_one _).mpr hmax)
  have hdu : IsUnit (d i) := isUnit_of_mul_isUnit_right hu
  obtain ⟨f, hf, hfi⟩ := hts hi
  refine ⟨f, hf, ?_⟩
  rw [hI, hfi, ← hd i hi, Ideal.span_singleton_mul_left_unit hdu]

end AlgebraicGeometry
