/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.Invertible
public import Hironaka.Scheme.IdealSheaf.Defs
public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial

/-!
# Invertible ideal sheaves: locality and stability

Invertibility of an ideal sheaf (`IdealSheafData.IsInvertible`) is local and stable under
localization, and the unit ideal sheaf, products of invertible ideal sheaves and comaps along open
immersions are invertible.  The ring-level statements are in `Hironaka.Scheme.BlowUp.Invertible`;
compare the proof of [Sta, Tag 01WS].

## Main declarations

* `Ideal.IsInvertible.map_ringEquiv`, `Ideal.IsInvertible.map_of_isLocalization_away`: transport of
  invertibility along ring isomorphisms and to any localization away from an element.
* `AlgebraicGeometry.Scheme.IdealSheafData.isInvertible_iff_forall_ideal`,
  `isInvertible_iff_of_iSup_eq_top`, `isInvertible_ideal_affineBasicOpen`: locality.
* `AlgebraicGeometry.Scheme.IdealSheafData.isInvertible_top`, `IsInvertible.mul`,
  `IsInvertible.comap_of_isOpenImmersion`: stability.

## The arguments

*Locality.*  The defining condition of `Ideal.IsInvertible` is pointwise on primes, and the
points of an affine open `U` are the primes of `Γ(X, U)` (`IsAffineOpen.primeIdealOf`,
`fromSpec`).  If `J(U)` is invertible at the prime of `x`, the basic open `D(s) ∋ x` of `U` has
`J(D(s)) = J(U)_s = (a)` with `a` a nonzerodivisor.  Conversely if `J` is invertible at `x ∈ U`,
with `J(V) = (g)` on an affine `V ∋ x`, a basic open `D(s) = D(t)` of both `U` and `V` around `x`
has `J(D(s)) = (g)` with `g` a nonzerodivisor (localization preserves nonzerodivisors), and `g` is
a unit multiple of the image of an element `a ∈ J(U)`, which is the datum at the prime of `x`.

*Stability.*  Local generators multiply on a common basic open; the unit ideal is generated by
`1`; for an open immersion `f`, `(J.comap f)(V) = J(f(V))` transported along the isomorphism
`Γ(X, f(V)) ≅ Γ(Y, V)`, and a basic open of `X` inside the image of `f` is the image of an
affine open of `Y`.

## Conventions

Statements about `J(W)` for a basic open `W = D(s) ⊆ U` are transported along the equality of
affine opens `D(s) = D(t)` as propositions, never by rewriting the section rings.
-/

public section

universe u

open AlgebraicGeometry CategoryTheory

namespace Ideal

variable {A : Type u} {B : Type u} [CommRing A] [CommRing B]

/-- The datum of a regular generator passes along a ring isomorphism of the base. -/
theorem IsRegularGeneratorIn.map_ringEquiv (e : A ≃+* B) {J : Ideal A} {s a : A}
    (h : J.IsRegularGeneratorIn (Localization.Away s) a) :
    (J.map (e : A →+* B)).IsRegularGeneratorIn (Localization.Away (e s)) (e a) := by
  obtain ⟨h₁, h₂⟩ := h
  have hpow : (Submonoid.powers s).map e.toMonoidHom = Submonoid.powers (e s) :=
    Submonoid.map_powers _ _
  let ρ : Localization.Away s ≃+* Localization.Away (e s) :=
    IsLocalization.ringEquivOfRingEquiv (Localization.Away s) (Localization.Away (e s)) e hpow
  have hρ : ∀ x, ρ (algebraMap A (Localization.Away s) x) =
      algebraMap B (Localization.Away (e s)) (e x) := fun x =>
    IsLocalization.ringEquivOfRingEquiv_eq hpow x
  have hcomp : (algebraMap B (Localization.Away (e s))).comp (e : A →+* B) =
      (ρ : Localization.Away s →+* Localization.Away (e s)).comp
        (algebraMap A (Localization.Away s)) :=
    RingHom.ext fun x => (hρ x).symm
  refine ⟨?_, ?_⟩
  · rw [Ideal.map_map, hcomp, ← Ideal.map_map, h₁, Ideal.map_span, Set.image_singleton,
      RingEquiv.coe_toRingHom, hρ]
  · rw [← hρ]
    exact map_mem_nonZeroDivisors_of_ringEquiv ρ h₂

/-- Invertibility passes along ring isomorphisms. -/
theorem IsInvertible.map_ringEquiv (e : A ≃+* B) {J : Ideal A} (hJ : J.IsInvertible) :
    (J.map (e : A →+* B)).IsInvertible := by
  intro q
  obtain ⟨s, hs, a, ha, h⟩ := hJ (PrimeSpectrum.comap (e : A →+* B) q)
  rw [PrimeSpectrum.comap_asIdeal, Ideal.mem_comap] at hs
  exact ⟨e s, hs, e a, Ideal.mem_map_of_mem _ ha, IsRegularGeneratorIn.map_ringEquiv e h⟩

/-- Invertibility passes to any localization away from an element. -/
theorem IsInvertible.map_of_isLocalization_away {J : Ideal A} (hJ : J.IsInvertible) (s : A)
    (C : Type u) [CommRing C] [Algebra A C] [IsLocalization.Away s C] :
    (J.map (algebraMap A C)).IsInvertible := by
  have e := IsLocalization.algEquiv (Submonoid.powers s) (Localization.Away s) C
  have : algebraMap A C = (e.toRingEquiv : Localization.Away s →+* C).comp
      (algebraMap A (Localization.Away s)) := by
    ext x; simp
  rw [this, ← Ideal.map_map]
  exact (hJ.map_away s).map_ringEquiv e.toRingEquiv

end Ideal

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : Scheme.{u}} (J : X.IdealSheafData)

/-- The ideal of `J` on a basic open `D(s) ⊆ U` is the extension of `J(U)` along the localization
map `Γ(X, U) → Γ(X, D(s))`. -/
theorem ideal_affineBasicOpen_eq_map (U : X.affineOpens) (s : Γ(X, U)) :
    J.ideal (X.affineBasicOpen s) =
      (J.ideal U).map (algebraMap Γ(X, U) Γ(X, X.basicOpen s)) :=
  (J.map_ideal_basicOpen U s).symm

/-- A regular generator of `J(U)` restricts to a regular generator of `J(D(s))`. -/
theorem exists_regular_generator_affineBasicOpen (U : X.affineOpens) {f : Γ(X, U)}
    (hf : f ∈ nonZeroDivisors Γ(X, U)) (hJ : J.ideal U = Ideal.span {f}) (s : Γ(X, U)) :
    ∃ g ∈ nonZeroDivisors Γ(X, X.basicOpen s),
      J.ideal (X.affineBasicOpen s) = Ideal.span {g} := by
  have := U.2.isLocalization_basicOpen s
  refine ⟨algebraMap Γ(X, U) Γ(X, X.basicOpen s) f,
    IsLocalization.nonZeroDivisors_le_comap (Submonoid.powers s) _ hf, ?_⟩
  rw [ideal_affineBasicOpen_eq_map, hJ, Ideal.map_span, Set.image_singleton]

/-- `J(U)` invertible implies `J(D(s))` invertible. -/
theorem isInvertible_ideal_affineBasicOpen (U : X.affineOpens) (hU : (J.ideal U).IsInvertible)
    (s : Γ(X, U)) : (J.ideal (X.affineBasicOpen s)).IsInvertible := by
  have := U.2.isLocalization_basicOpen s
  rw [ideal_affineBasicOpen_eq_map]
  exact hU.map_of_isLocalization_away s Γ(X, X.basicOpen s)

/-- The point of `U` at a prime of `Γ(X, U)` lies in `D(s)` iff `s` is not in the prime. -/
theorem fromSpec_mem_basicOpen_iff {U : X.Opens} (hU : IsAffineOpen U)
    (p : PrimeSpectrum Γ(X, U)) (s : Γ(X, U)) :
    hU.fromSpec p ∈ X.basicOpen s ↔ s ∉ p.asIdeal := by
  have h1 : hU.fromSpec p ∈ X.basicOpen s ↔ p ∈ hU.fromSpec ⁻¹ᵁ X.basicOpen s := Iff.rfl
  rw [h1, hU.fromSpec_preimage_basicOpen]
  exact PrimeSpectrum.mem_basicOpen _ _

theorem exists_affineOpens_mem (x : X) : ∃ U : X.affineOpens, x ∈ U.1 := by
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x) isOpen_univ
  exact ⟨⟨U, hU⟩, hxU⟩

/-- Pointwise form of locality: `J` is invertible if every point has an affine open neighbourhood
on which the ideal of `J` is invertible. -/
theorem isInvertible_of_forall_exists_affine
    (h : ∀ x : X, ∃ U : X.affineOpens, x ∈ U.1 ∧ (J.ideal U).IsInvertible) : J.IsInvertible := by
  intro x
  obtain ⟨U, hxU, hinv⟩ := h x
  obtain ⟨s, hs, a, ha, hgen⟩ := hinv (U.2.primeIdealOf ⟨x, hxU⟩)
  have hxs : x ∈ X.basicOpen s := by
    have := (fromSpec_mem_basicOpen_iff U.2 (U.2.primeIdealOf ⟨x, hxU⟩) s).mpr hs
    rwa [IsAffineOpen.fromSpec_primeIdealOf U.2 ⟨x, hxU⟩] at this
  have := U.2.isLocalization_basicOpen s
  have hgen' : (J.ideal U).IsRegularGeneratorIn Γ(X, X.basicOpen s) a :=
    Ideal.IsRegularGeneratorIn.of_algEquiv (IsLocalization.algEquiv (Submonoid.powers s) _ _) hgen
  refine ⟨X.affineBasicOpen s, hxs, algebraMap Γ(X, U) Γ(X, X.basicOpen s) a, hgen'.2, ?_⟩
  rw [ideal_affineBasicOpen_eq_map, hgen'.1]
  rfl

/-- The ideal of an invertible ideal sheaf on any affine open is invertible (compare the proof of
[Sta, Tag 01WS]). -/
theorem IsInvertible.ideal (hJ : J.IsInvertible) (U : X.affineOpens) :
    (J.ideal U).IsInvertible := by
  intro p
  have hxU : U.2.fromSpec p ∈ U.1 := by
    rw [← SetLike.mem_coe, ← U.2.range_fromSpec]
    exact ⟨p, rfl⟩
  obtain ⟨V, hxV, g, hg, hJV⟩ := hJ (U.2.fromSpec p)
  obtain ⟨s, t, hst, hxs⟩ := exists_basicOpen_le_affine_inter U.2 V.2 _ ⟨hxU, hxV⟩
  have hs : s ∉ p.asIdeal := (fromSpec_mem_basicOpen_iff U.2 p s).mp hxs
  obtain ⟨g', hg', hJs⟩ : ∃ g' ∈ nonZeroDivisors Γ(X, X.basicOpen s),
      J.ideal (X.affineBasicOpen s) = Ideal.span {g'} := by
    have key : ∀ (W : X.Opens) (hW : IsAffineOpen W), W = X.basicOpen t →
        ∃ g' ∈ nonZeroDivisors Γ(X, W), J.ideal ⟨W, hW⟩ = Ideal.span {g'} := by
      rintro W hW rfl
      exact exists_regular_generator_affineBasicOpen J V hg hJV t
    exact key _ (X.affineBasicOpen s).2 hst
  have := U.2.isLocalization_basicOpen s
  -- `g'` is a unit multiple of the image of an element `a ∈ J(U)`
  have hmem : g' ∈ (J.ideal U).map (algebraMap Γ(X, U) Γ(X, X.basicOpen s)) := by
    rw [← ideal_affineBasicOpen_eq_map, hJs]
    exact Ideal.mem_span_singleton_self g'
  obtain ⟨⟨⟨a, ha⟩, ⟨_, k, rfl⟩⟩, hga⟩ :=
    (IsLocalization.mem_map_algebraMap_iff (Submonoid.powers s) _).mp hmem
  have hga' : g' * algebraMap Γ(X, U) Γ(X, X.basicOpen s) (s ^ k) =
      algebraMap Γ(X, U) Γ(X, X.basicOpen s) a := hga
  have hu : IsUnit (algebraMap Γ(X, U) Γ(X, X.basicOpen s) (s ^ k)) := by
    rw [map_pow]; exact (IsLocalization.Away.algebraMap_isUnit s).pow k
  have hgen : (J.ideal U).IsRegularGeneratorIn Γ(X, X.basicOpen s) a := by
    refine ⟨?_, ?_⟩
    · rw [← ideal_affineBasicOpen_eq_map, hJs, ← hga', Ideal.span_singleton_mul_right_unit hu]
    · rw [← hga']; exact mul_mem hg' hu.mem_nonZeroDivisors
  exact ⟨s, hs, a, ha, Ideal.IsRegularGeneratorIn.of_algEquiv
    (IsLocalization.algEquiv (Submonoid.powers s) _ _) hgen⟩

/-- An ideal sheaf is invertible iff its ideal on every affine open is invertible. -/
theorem isInvertible_iff_forall_ideal :
    J.IsInvertible ↔ ∀ U : X.affineOpens, (J.ideal U).IsInvertible :=
  ⟨fun h U => IsInvertible.ideal J h U, fun h => isInvertible_of_forall_exists_affine J fun x =>
    let ⟨U, hxU⟩ := exists_affineOpens_mem x
    ⟨U, hxU, h U⟩⟩

/-- An ideal sheaf is invertible iff its ideals on the members of an affine open cover are
invertible. -/
theorem isInvertible_iff_of_iSup_eq_top {ι : Type*} (U : ι → X.affineOpens)
    (hU : ⨆ i, (U i).1 = ⊤) : J.IsInvertible ↔ ∀ i, (J.ideal (U i)).IsInvertible :=
  ⟨fun h i => IsInvertible.ideal J h (U i), fun h => isInvertible_of_forall_exists_affine J
    fun x => by
    have hx : x ∈ ⨆ i, (U i).1 := by rw [hU]; exact TopologicalSpace.Opens.mem_top x
    obtain ⟨i, hi⟩ := TopologicalSpace.Opens.mem_iSup.mp hx
    exact ⟨U i, hi, h i⟩⟩

/-- The unit ideal sheaf is invertible. -/
theorem isInvertible_top : (⊤ : X.IdealSheafData).IsInvertible := fun x => by
  obtain ⟨U, hxU⟩ := exists_affineOpens_mem x
  exact ⟨U, hxU, 1, one_mem _, Ideal.span_singleton_one.symm⟩

/-- A product of invertible ideal sheaves is invertible: multiply the local generators on a
common basic open. -/
theorem IsInvertible.mul {J₁ J₂ : X.IdealSheafData} (h₁ : J₁.IsInvertible)
    (h₂ : J₂.IsInvertible) : (J₁ * J₂).IsInvertible := fun x => by
  obtain ⟨U₁, hx₁, f₁, hf₁, e₁⟩ := h₁ x
  obtain ⟨U₂, hx₂, f₂, hf₂, e₂⟩ := h₂ x
  obtain ⟨s, t, hst, hxs⟩ := exists_basicOpen_le_affine_inter U₁.2 U₂.2 x ⟨hx₁, hx₂⟩
  obtain ⟨g₁, hg₁, hJ₁⟩ := exists_regular_generator_affineBasicOpen J₁ U₁ hf₁ e₁ s
  obtain ⟨g₂, hg₂, hJ₂⟩ : ∃ g ∈ nonZeroDivisors Γ(X, X.basicOpen s),
      J₂.ideal (X.affineBasicOpen s) = Ideal.span {g} := by
    have key : ∀ (W : X.Opens) (hW : IsAffineOpen W), W = X.basicOpen t →
        ∃ g ∈ nonZeroDivisors Γ(X, W), J₂.ideal ⟨W, hW⟩ = Ideal.span {g} := by
      rintro W hW rfl
      exact exists_regular_generator_affineBasicOpen J₂ U₂ hf₂ e₂ t
    exact key _ (X.affineBasicOpen s).2 hst
  refine ⟨X.affineBasicOpen s, hxs, g₁ * g₂, mul_mem hg₁ hg₂, ?_⟩
  rw [ideal_mul, Pi.mul_apply, hJ₁, hJ₂]
  exact Ideal.span_singleton_mul_span_singleton g₁ g₂

/-- The comap of an invertible ideal sheaf along an open immersion is invertible. -/
theorem IsInvertible.comap_of_isOpenImmersion {Y : Scheme.{u}} (f : Y ⟶ X) [IsOpenImmersion f]
    {J : X.IdealSheafData} (hJ : J.IsInvertible) : (J.comap f).IsInvertible := fun y => by
  obtain ⟨U, hxU, g, hg, hJU⟩ := hJ (f y)
  obtain ⟨s, hs_le, hxs⟩ :=
    U.2.exists_basicOpen_le (V := f.opensRange) ⟨f y, Set.mem_range_self y⟩ hxU
  have hWaff : IsAffineOpen (f ⁻¹ᵁ X.basicOpen s) :=
    (X.affineBasicOpen s).2.preimage_of_isOpenImmersion f hs_le
  have himg : f ''ᵁ (f ⁻¹ᵁ X.basicOpen s) = X.basicOpen s := by
    rw [f.image_preimage_eq_opensRange_inf, inf_eq_right.mpr hs_le]
  obtain ⟨g', hg', hJW⟩ := exists_regular_generator_affineBasicOpen J U hg hJU s
  refine ⟨⟨f ⁻¹ᵁ X.basicOpen s, hWaff⟩, hxs, ?_⟩
  rw [ideal_comap_of_isOpenImmersion]
  obtain ⟨g'', hg'', hJ''⟩ : ∃ g'' ∈ nonZeroDivisors Γ(X, f ''ᵁ (f ⁻¹ᵁ X.basicOpen s)),
      J.ideal ⟨f ''ᵁ (f ⁻¹ᵁ X.basicOpen s), hWaff.image_of_isOpenImmersion f⟩ =
        Ideal.span {g''} := by
    have key : ∀ (W' : X.Opens) (hW' : IsAffineOpen W'), W' = X.basicOpen s →
        ∃ g'' ∈ nonZeroDivisors Γ(X, W'), J.ideal ⟨W', hW'⟩ = Ideal.span {g''} := by
      rintro W' hW' rfl
      exact ⟨g', hg', hJW⟩
    exact key _ _ himg
  set e := (f.appIso (f ⁻¹ᵁ X.basicOpen s)).commRingCatIsoToRingEquiv with he
  have hψ : (f.appIso (f ⁻¹ᵁ X.basicOpen s)).inv.hom = (e.symm : _ →+* _) :=
    RingHom.ext fun _ => rfl
  refine ⟨e g'', map_mem_nonZeroDivisors_of_ringEquiv e hg'', ?_⟩
  rw [hJ'', hψ]
  ext z
  rw [Ideal.mem_comap, Ideal.mem_span_singleton, Ideal.mem_span_singleton]
  change g'' ∣ e.symm z ↔ e g'' ∣ z
  constructor
  · rintro ⟨c, hc⟩
    exact ⟨e c, by rw [← map_mul, ← hc, RingEquiv.apply_symm_apply]⟩
  · rintro ⟨c, hc⟩
    exact ⟨e.symm c, by rw [hc, map_mul, RingEquiv.symm_apply_apply]⟩

end AlgebraicGeometry.Scheme.IdealSheafData
