/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
public import Hironaka.Scheme.IdealSheaf.Defs
import Hironaka.Scheme.BlowUp.InvertibleSheaf

/-!
# The affine computation of the inverse image ideal sheaf

For `f : Y ⟶ X` and affine opens `U ⊆ X`, `V ⊆ Y` with `f(V) ⊆ U`, the ideal of `I.comap f` on
`V` is the extension `I(U)·Γ(Y, V)` along `f♯ : Γ(X, U) → Γ(Y, V)`: the ideal sheaf of the inverse
image is the image of `f^*I → 𝒪_Y` (compare the proof of [Sta, Tag 0805]).  Mathlib defines
`I.comap f` as the kernel of the first projection of `Y ×_X V(I)` and has only the open-immersion
case (`ideal_comap_of_isOpenImmersion`) and the pushforward direction (`ideal_map_of_isAffineHom`).

## Main declarations

* `ker_appTop_Spec_map`: the kernel of `Γ(Spec R) → Γ(Spec S)` induced by `φ : R → S` is `ker φ`
  transported along `ΓSpecIso`.
* `comap_ofIdealTop_Spec_map` (the case `f = Spec.map φ`): the comap of the ideal sheaf of `I ⊆ R`
  along `Spec S → Spec R` is the ideal sheaf of `IS`.
* `ideal_comap_of_le`: the general affine formula; `map_germ_ideal_comap`: its stalk form.
* `exists_affineOpen_generator_of_isInvertible`: for `f` admissible for `I` (the inverse image
  ideal sheaf invertible), every point has an affine neighbourhood on which the inverse image
  ideal is generated by the image of an element of `I(U)`, a nonzerodivisor.

## The argument (Spec case)

`Spec (R/I) → Spec R` is a closed immersion with kernel the ideal sheaf of `I`, so `I.comap f` is
the kernel of `Spec S ×_{Spec R} Spec (R/I) → Spec S` (`ker_fst_of_isClosedImmersion`); the fibre
product is `Spec (S ⊗_R R/I)` (`pullbackSpecIso`), the projection corresponds to
`S → S ⊗_R R/I`, `s ↦ s ⊗ 1`, and its kernel is `IS` because `S ⊗_R R/I ≅ S/IS`
(`quotIdealMapEquivTensorQuot`).  A kernel of a morphism into an affine scheme is the ideal sheaf
of the kernel of its global sections (`ker_of_isAffine`).
-/

public section

universe u

open CategoryTheory Limits TensorProduct

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {R S : CommRingCat.{u}}

theorem appTop_Spec_map (φ : R ⟶ S) :
    (Spec.map φ).appTop = (Scheme.ΓSpecIso R).hom ≫ φ ≫ (Scheme.ΓSpecIso S).inv := by
  rw [← Category.comp_id (Spec.map φ).appTop, ← (Scheme.ΓSpecIso S).hom_inv_id, ← Category.assoc,
    Scheme.ΓSpecIso_naturality, Category.assoc]

theorem injective_ΓSpecIso_inv : Function.Injective (Scheme.ΓSpecIso S).inv.hom :=
  (Scheme.ΓSpecIso S).symm.commRingCatIsoToRingEquiv.injective

/-- The kernel of the map on global sections induced by `φ : R → S` is `ker φ`, transported to
`Γ(Spec R, ⊤)`. -/
theorem ker_appTop_Spec_map (φ : R ⟶ S) :
    RingHom.ker (Spec.map φ).appTop.hom = (RingHom.ker φ.hom).map (Scheme.ΓSpecIso R).inv.hom := by
  rw [appTop_Spec_map, CommRingCat.hom_comp, CommRingCat.hom_comp, ← RingHom.comap_ker,
    RingHom.ker_comp_of_injective _ injective_ΓSpecIso_inv]
  ext x
  rw [Ideal.mem_comap, Ideal.mem_map_iff_of_surjective (Scheme.ΓSpecIso R).inv.hom
    (fun y => ⟨(Scheme.ΓSpecIso R).hom.hom y,
      (Scheme.ΓSpecIso R).commRingCatIsoToRingEquiv.symm_apply_apply y⟩)]
  constructor
  · intro hx
    exact ⟨(Scheme.ΓSpecIso R).hom x, hx,
      (Scheme.ΓSpecIso R).commRingCatIsoToRingEquiv.symm_apply_apply x⟩
  · rintro ⟨y, hy, rfl⟩
    have h : (Scheme.ΓSpecIso R).hom.hom ((Scheme.ΓSpecIso R).inv.hom y) = y :=
      (Scheme.ΓSpecIso R).commRingCatIsoToRingEquiv.apply_symm_apply y
    rw [h]
    exact hy

/-- The closed immersion `Spec (R/I) → Spec R` has kernel the ideal sheaf of `I`. -/
theorem ker_Spec_map_mk (I : Ideal R) :
    (Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk I))).ker =
      ofIdealTop (I.map (Scheme.ΓSpecIso R).inv.hom) := by
  rw [Scheme.ker_of_isAffine, ker_appTop_Spec_map, CommRingCat.hom_ofHom, Ideal.mk_ker]
  rfl

/-- The case `f = Spec.map φ`: the comap of the ideal sheaf of `I ⊆ R` along `Spec S → Spec R` is
the ideal sheaf of `IS`. -/
theorem comap_ofIdealTop_Spec_map (φ : R ⟶ S) (I : Ideal R) :
    (ofIdealTop (I.map (Scheme.ΓSpecIso R).inv.hom)).comap (Spec.map φ) =
      ofIdealTop ((I.map φ.hom).map (Scheme.ΓSpecIso S).inv.hom) := by
  let _ := φ.hom.toAlgebra
  have hfst : (pullbackSpecIso R S (R ⧸ I)).inv ≫
      Limits.pullback.fst (Spec.map φ) (Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk I))) =
      Spec.map (CommRingCat.ofHom (Algebra.TensorProduct.includeLeftRingHom :
        S →+* S ⊗[R] (R ⧸ I))) :=
    pullbackSpecIso_inv_fst R S (R ⧸ I)
  rw [← ker_Spec_map_mk, ← ker_fst_of_isClosedImmersion,
    ← Scheme.Hom.ker_comp_of_isIso (pullbackSpecIso R S (R ⧸ I)).inv, hfst,
    Scheme.ker_of_isAffine, ker_appTop_Spec_map, CommRingCat.hom_ofHom]
  have hincl : (Algebra.TensorProduct.includeLeftRingHom : S →+* S ⊗[R] (R ⧸ I)) =
      ((Algebra.TensorProduct.quotIdealMapEquivTensorQuot S I :
        S ⧸ I.map (algebraMap R S) →ₐ[S] S ⊗[R] (R ⧸ I)) : _ →+* _).comp
        (Ideal.Quotient.mk (I.map (algebraMap R S))) :=
    RingHom.ext fun s => (Algebra.TensorProduct.quotIdealMapEquivTensorQuot_mk S I s).symm
  rw [hincl, RingHom.ker_comp_of_injective _
    (Algebra.TensorProduct.quotIdealMapEquivTensorQuot S I).injective, Ideal.mk_ker]
  rfl


variable {X Y : Scheme.{u}}

/-- The closed subscheme of `J` over the affine open `U` is `Spec (Γ(X, U)/J(U))`: the square with
`hU.fromSpec` and `J.subschemeι` is a pullback. -/
theorem isPullback_fromSpec (J : X.IdealSheafData) (U : X.affineOpens) :
    IsPullback (Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk (J.ideal U))))
      (J.subschemeCover.f U) U.2.fromSpec J.subschemeι := by
  have hU : IsAffineOpen U.1 := U.2
  have hopen : IsOpenImmersion (J.subschemeCover.f U) := J.subschemeCover.map_prop U
  change IsPullback _ _ hU.fromSpec _
  refine @IsOpenImmersion.isPullback _ _ _ _
    (Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk (J.ideal U))))
    (J.subschemeCover.f U) hU.fromSpec J.subschemeι hopen inferInstance ?_ ?_
  · exact (subschemeCover_map_subschemeι J U).trans (glueDataObjι_ι J U)
  · rw [IsAffineOpen.opensRange_fromSpec]
    exact (opensRange_subschemeCover_map J U).symm

/-- The comap of an ideal sheaf along `hU.fromSpec` is the ideal sheaf of `J(U)` on `Spec Γ(X, U)`
(the `ΓSpecIso` compatibility of `ofIdealTop`). -/
theorem comap_fromSpec (J : X.IdealSheafData) (U : X.affineOpens) :
    J.comap U.2.fromSpec = ofIdealTop ((J.ideal U).map (Scheme.ΓSpecIso Γ(X, U)).inv.hom) := by
  have hP := isPullback_fromSpec J U
  have hfst : Limits.pullback.fst U.2.fromSpec J.subschemeι =
      hP.isoPullback.inv ≫ Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk (J.ideal U))) := by
    rw [Iso.eq_inv_comp, hP.isoPullback_hom_fst]
  rw [comap, hfst, Scheme.Hom.ker_comp_of_isIso, ker_Spec_map_mk]

/-- For affine opens `U ⊆ X`, `V ⊆ Y` with `f(V) ⊆ U`, the ideal of `I.comap f` on `V` is
`I(U)·Γ(Y, V)` (compare the proof of [Sta, Tag 0805]). -/
theorem ideal_comap_of_le (I : X.IdealSheafData) (f : Y ⟶ X) (U : X.affineOpens)
    (V : Y.affineOpens) (e : V.1 ≤ f ⁻¹ᵁ U.1) :
    (I.comap f).ideal V = (I.ideal U).map (f.appLE U.1 V.1 e).hom := by
  have h1 : (I.comap f).comap V.2.fromSpec =
      ofIdealTop (((I.comap f).ideal V).map (Scheme.ΓSpecIso Γ(Y, V)).inv.hom) :=
    comap_fromSpec _ V
  have h2 : (I.comap f).comap V.2.fromSpec =
      ofIdealTop (((I.ideal U).map (f.appLE U.1 V.1 e).hom).map
        (Scheme.ΓSpecIso Γ(Y, V)).inv.hom) := by
    rw [← comap_comp, ← IsAffineOpen.SpecMap_appLE_fromSpec f U.2 V.2 e, comap_comp,
      comap_fromSpec, comap_ofIdealTop_Spec_map]
  have h3 := h1.symm.trans h2
  have hinj : Function.Injective (ofIdealTop (X := Spec Γ(Y, V))) :=
    equivOfIsAffine.symm.injective
  have h4 := hinj h3
  -- cancel the isomorphism `ΓSpecIso`
  set e : Γ(Y, V) ≃+* Γ(Spec Γ(Y, V), ⊤) :=
    (Scheme.ΓSpecIso Γ(Y, V)).symm.commRingCatIsoToRingEquiv with he_def
  have he : (Scheme.ΓSpecIso Γ(Y, V)).inv.hom = (e : Γ(Y, V) →+* Γ(Spec Γ(Y, V), ⊤)) := rfl
  rw [he, Ideal.map_comap_of_equiv, Ideal.map_comap_of_equiv] at h4
  exact Ideal.comap_injective_of_surjective _ e.symm.surjective h4


/-- The stalk of `I.comap f` at `y`, spelled through affine opens `V ∋ y` and `U ∋ f y` with
`f(V) ⊆ U`, is generated by the image under `f.stalkMap y` of the stalk of `I` at `f y`. -/
theorem map_germ_ideal_comap (I : X.IdealSheafData) (f : Y ⟶ X) (y : Y) (U : X.affineOpens)
    (V : Y.affineOpens) (hy : y ∈ V.1) (e : V.1 ≤ f ⁻¹ᵁ U.1) :
    ((I.comap f).ideal V).map (Y.presheaf.germ V.1 y hy).hom =
      ((I.ideal U).map (X.presheaf.germ U.1 (f y) (e hy)).hom).map (f.stalkMap y).hom := by
  have hfy : f y ∈ U.1 := e hy
  change _ = ((I.ideal U).map (X.presheaf.germ U.1 (f y) hfy).hom).map (f.stalkMap y).hom
  rw [ideal_comap_of_le I f U V e, Ideal.map_map, Ideal.map_map, ← CommRingCat.hom_comp,
    ← CommRingCat.hom_comp]
  congr 2
  rw [Scheme.Hom.germ_stalkMap, Scheme.Hom.appLE, Category.assoc, TopCat.Presheaf.germ_res]

/-- For an open immersion `j` the stalk map is an isomorphism, so `a` generates the stalk ideal
of `I` at `j y` iff `j♯a` generates the stalk ideal of `I.comap j` at `y`. -/
theorem span_germ_appLE_eq_iff_of_isOpenImmersion (I : X.IdealSheafData) (j : Y ⟶ X)
    [IsOpenImmersion j] (y : Y) (U : X.affineOpens) (V : Y.affineOpens) (hy : y ∈ V.1)
    (e : V.1 ≤ j ⁻¹ᵁ U.1) (a : Γ(X, U)) :
    Ideal.span {Y.presheaf.germ V.1 y hy (j.appLE U.1 V.1 e a)} =
        ((I.comap j).ideal V).map (Y.presheaf.germ V.1 y hy).hom ↔
      Ideal.span {X.presheaf.germ U.1 (j y) (e hy) a} =
        (I.ideal U).map (X.presheaf.germ U.1 (j y) (e hy)).hom := by
  have hfy : j y ∈ U.1 := e hy
  change _ ↔ Ideal.span {X.presheaf.germ U.1 (j y) hfy a} =
    (I.ideal U).map (X.presheaf.germ U.1 (j y) hfy).hom
  rw [map_germ_ideal_comap I j y U V hy e]
  have hnat : Y.presheaf.germ V.1 y hy (j.appLE U.1 V.1 e a) =
      j.stalkMap y (X.presheaf.germ U.1 (j y) hfy a) := by
    rw [Scheme.Hom.germ_stalkMap_apply, Scheme.Hom.appLE, CommRingCat.comp_apply,
      TopCat.Presheaf.germ_res_apply]
  rw [hnat]
  set σ : X.presheaf.stalk (j y) ≃+* Y.presheaf.stalk y :=
    (asIso (j.stalkMap y)).commRingCatIsoToRingEquiv with hσ_def
  have hσ : (j.stalkMap y).hom = (σ : X.presheaf.stalk (j y) →+* Y.presheaf.stalk y) := rfl
  rw [hσ]
  have hinj : Function.Injective
      (Ideal.map (σ : X.presheaf.stalk (j y) →+* Y.presheaf.stalk y)) := by
    intro A B h
    rw [Ideal.map_comap_of_equiv, Ideal.map_comap_of_equiv] at h
    exact Ideal.comap_injective_of_surjective _ σ.symm.surjective h
  rw [show Ideal.span {j.stalkMap y (X.presheaf.germ U.1 (j y) hfy a)} =
      (Ideal.span {X.presheaf.germ U.1 (j y) hfy a}).map
        (σ : X.presheaf.stalk (j y) →+* Y.presheaf.stalk y) by
    rw [Ideal.map_span, Set.image_singleton]; rfl]
  exact hinj.eq_iff

/-- For `f : Y ⟶ X` admissible for `I` (the inverse image ideal sheaf invertible), an affine open
`U ⊆ X` and `y ∈ f⁻¹(U)`, there are an affine open `V ∋ y` with `f(V) ⊆ U` and `a ∈ I(U)` such
that `(I.comap f)(V) = (f♯a)` with `f♯a` a nonzerodivisor of `Γ(Y, V)`.  This is the argument of
[Hau14, Theorem 4.18, proof (c)] (compare the proof of [Sta, Tag 0806]) carried from the local
ring at `y` to an affine neighbourhood: a generator `h₀` of the inverse image ideal near `y` is a
combination `∑ cᵢ f♯(xᵢ)` with `xᵢ ∈ I(U)`, each `f♯(xᵢ)` is `tᵢ h₀`, so `∑ cᵢ tᵢ = 1` by
cancellation and some `tᵢ` is not in the prime of `y`; on the basic open `D(tᵢ)` the element
`f♯(xᵢ) = tᵢ h₀` is a unit multiple of `h₀`. -/
theorem exists_affineOpen_generator_of_isInvertible (I : X.IdealSheafData) (f : Y ⟶ X)
    (hf : (I.comap f).IsInvertible) (U : X.affineOpens) (y : Y) (hy : y ∈ f ⁻¹ᵁ U.1) :
    ∃ V : Y.affineOpens, y ∈ V.1 ∧ ∃ e : V.1 ≤ f ⁻¹ᵁ U.1, ∃ a ∈ I.ideal U,
      (I.comap f).ideal V = Ideal.span {f.appLE U.1 V.1 e a} ∧
        f.appLE U.1 V.1 e a ∈ nonZeroDivisors Γ(Y, V) := by
  obtain ⟨V₁, hyV₁, h, hh, hJ₁⟩ := hf y
  obtain ⟨s, hs_le, hys⟩ := V₁.2.exists_basicOpen_le (V := f ⁻¹ᵁ U.1) ⟨y, hy⟩ hyV₁
  set V₀ : Y.affineOpens := Y.affineBasicOpen s with hV₀
  obtain ⟨h₀, hh₀, hJ₀⟩ : ∃ g ∈ nonZeroDivisors Γ(Y, V₀), (I.comap f).ideal V₀ = Ideal.span {g} :=
    exists_regular_generator_affineBasicOpen (I.comap f) V₁ hh hJ₁ s
  have e₀ : V₀.1 ≤ f ⁻¹ᵁ U.1 := hs_le
  have hyV₀ : y ∈ V₀.1 := hys
  -- `h₀ = ∑ cᵢ f♯(xᵢ)` with `xᵢ ∈ I(U)`
  have hmem : h₀ ∈ (I.ideal U).map (f.appLE U.1 V₀.1 e₀).hom := by
    rw [← ideal_comap_of_le I f U V₀ e₀, hJ₀]
    exact Ideal.mem_span_singleton_self h₀
  have hmem' : h₀ ∈ Submodule.span Γ(Y, V₀)
      ((f.appLE U.1 V₀.1 e₀).hom '' (I.ideal U : Set Γ(X, U))) := hmem
  obtain ⟨T, hTs, hhT⟩ := Submodule.mem_span_finite_of_mem_span hmem'
  obtain ⟨c, -, hc⟩ := Submodule.mem_span_finset.mp hhT
  -- each `f♯(xᵢ) = tᵢ h₀`
  have hTJ : ∀ z ∈ T, z ∈ (I.comap f).ideal V₀ := fun z hz => by
    rw [ideal_comap_of_le I f U V₀ e₀]
    obtain ⟨x, hx, rfl⟩ := hTs hz
    exact Ideal.mem_map_of_mem _ hx
  have ht : ∀ z ∈ T, ∃ t : Γ(Y, V₀), t * h₀ = z := fun z hz =>
    Ideal.mem_span_singleton'.mp (hJ₀ ▸ hTJ z hz)
  choose! t ht using ht
  have hsum : (∑ z ∈ T, c z * t z) * h₀ = h₀ :=
    calc (∑ z ∈ T, c z * t z) * h₀ = ∑ z ∈ T, c z * (t z * h₀) := by
          rw [Finset.sum_mul]; exact Finset.sum_congr rfl fun z _ => mul_assoc _ _ _
      _ = ∑ z ∈ T, c z • z := Finset.sum_congr rfl fun z hz => by rw [ht z hz, smul_eq_mul]
      _ = h₀ := hc
  have hsum' : ∑ z ∈ T, c z * t z = 1 :=
    (mul_cancel_right_mem_nonZeroDivisors hh₀).mp (by rw [one_mul]; exact hsum)
  -- some `tᵢ` is not in the prime of `y`
  set p := V₀.2.primeIdealOf ⟨y, hyV₀⟩ with hp
  obtain ⟨z₀, hz₀, htp⟩ : ∃ z ∈ T, t z ∉ p.asIdeal := by
    by_contra hcon
    push Not at hcon
    have h1 : (1 : Γ(Y, V₀)) ∈ p.asIdeal :=
      hsum' ▸ Submodule.sum_mem _ fun z hz => Ideal.mul_mem_left _ _ (hcon z hz)
    exact p.isPrime.ne_top ((Ideal.eq_top_iff_one _).mpr h1)
  obtain ⟨x, hx, hxz⟩ := hTs hz₀
  -- `V := D(tᵢ) ⊆ V₀`
  have hloc := V₀.2.isLocalization_basicOpen (t z₀)
  have hu : IsUnit (algebraMap Γ(Y, V₀) Γ(Y, Y.basicOpen (t z₀)) (t z₀)) :=
    IsLocalization.Away.algebraMap_isUnit _
  have hres : f.appLE U.1 (Y.basicOpen (t z₀)) ((Y.basicOpen_le _).trans e₀) =
      f.appLE U.1 V₀.1 e₀ ≫ Y.presheaf.map (homOfLE (Y.basicOpen_le (t z₀))).op :=
    (Scheme.Hom.appLE_map f e₀ (homOfLE (Y.basicOpen_le (t z₀))).op).symm
  have hval : (f.appLE U.1 (Y.basicOpen (t z₀)) ((Y.basicOpen_le _).trans e₀)).hom x =
      algebraMap Γ(Y, V₀) Γ(Y, Y.basicOpen (t z₀)) (t z₀) *
        algebraMap Γ(Y, V₀) Γ(Y, Y.basicOpen (t z₀)) h₀ := by
    rw [hres, CommRingCat.hom_comp, RingHom.comp_apply, hxz]
    exact (congrArg (Y.presheaf.map (homOfLE (Y.basicOpen_le (t z₀))).op).hom
      (ht z₀ hz₀).symm).trans (map_mul _ _ _)
  refine ⟨Y.affineBasicOpen (t z₀), ?_, (Y.basicOpen_le _).trans e₀, x, hx, ?_, ?_⟩
  · have := (fromSpec_mem_basicOpen_iff V₀.2 p (t z₀)).mpr htp
    rwa [hp, IsAffineOpen.fromSpec_primeIdealOf V₀.2 ⟨y, hyV₀⟩] at this
  · rw [ideal_affineBasicOpen_eq_map (I.comap f) V₀ (t z₀), hJ₀, Ideal.map_span,
      Set.image_singleton]
    change _ = Ideal.span {(f.appLE U.1 (Y.basicOpen (t z₀)) ((Y.basicOpen_le _).trans e₀)).hom x}
    rw [hval, Ideal.span_singleton_mul_left_unit hu]
  · change (f.appLE U.1 (Y.basicOpen (t z₀)) ((Y.basicOpen_le _).trans e₀)).hom x ∈
      nonZeroDivisors Γ(Y, Y.basicOpen (t z₀))
    rw [hval]
    exact mul_mem hu.mem_nonZeroDivisors
      (IsLocalization.nonZeroDivisors_le_comap (Submonoid.powers (t z₀)) _ hh₀)

end AlgebraicGeometry.Scheme.IdealSheafData
