/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineAlgebra
public import Mathlib.Algebra.MvPolynomial.Eval
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The presentation of the affine blow-up algebra

For `I = (a, gᵢ : i ∈ ι)` the `R`-algebra map `R[xᵢ : i ∈ ι]/(a xᵢ − gᵢ) → R[I/a]`, `xᵢ ↦ gᵢ/a`,
is surjective, and its kernel is the `a`-power torsion of the source [Sta, Tag 0G8S]; when the
generators form a regular sequence the torsion vanishes and the chart ring is the quotient
itself [Hau14, Theorem 4.20 (b)].

## Main declarations

* `AlgebraicGeometry.affineBlowUpAlgebra.presentationIdeal a g`: the ideal `(a xᵢ − gᵢ : i ∈ ι)` of
  `MvPolynomial ι R`.
* `affineBlowUpAlgebra.presentationHom a g hg : R[xᵢ]/(a xᵢ − gᵢ) →ₐ[R] R[I/a]` with
  `presentationHom_mk_X` and `presentationHom_unique` (existence and uniqueness).
* `affineBlowUpAlgebra.presentationHom_surjective` (for `I = (a, gᵢ)`).
* `affineBlowUpAlgebra.presentationHom_apply_eq_zero_iff`: `φ(z) = 0` iff `aᵏ z = 0` for some `k`.

## The argument

The Stacks Project proves the kernel statement by base change from the universal case
`P = ℤ[t₁, …, tₙ]`, `I = (t₁, …, tₙ)`, `a = t₁`, where source and target are `t₁`-torsion free and
the map is an isomorphism after inverting `t₁`.  Here the argument is run directly over `R`,
where the source is not torsion free, and it gives the kernel:

* the target `R[I/a] ⊆ R_a` has `a` as a nonzerodivisor
  (`affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors`), so `a`-power torsion of the source maps
  to zero;
* conversely, for a polynomial `p` there are `d` and a constant `c ∈ R` with
  `a^d p ≡ c (mod (a xᵢ − gᵢ))`: this is the elimination `a xᵢ ≡ gᵢ`, by induction on `p`
  (`a^{d+1} p xᵢ = a^d p (a xᵢ − gᵢ) + gᵢ a^d p ≡ gᵢ c`).  If the class of `p` maps to zero then
  `c = 0` in `R_a`, i.e. `a^k c = 0` in `R`, and then `a^{k+d} p ≡ a^k c = 0`, so the class of `p`
  is `a`-power torsion.

The only place the description of `I` enters is surjectivity: `R[I/a]` is generated by the `x/a`,
`x ∈ I`, and `x = r a + ∑ rᵢ gᵢ` gives `x/a = r + ∑ rᵢ (gᵢ/a)`.  The construction and the kernel
computation only need `gᵢ ∈ I`.

## Conventions

The index type `ι` is arbitrary (the sources have `n` generators); the proofs do not use
finiteness.  The `a`-power torsion of the quotient module is written `∃ k, a ^ k • z = 0`.

## Boundary cases

`ι` empty: `I = (a)` and the presentation says `R/T_a ≅ R[(a)/a]` with `T_a` the `a`-power
torsion (compare [Hau14, Example 4.31], the blow-up along a zero divisor).  `a = 0`: `R[I/0]` is
the zero ring and every element of the source is `0`-power torsion (`0¹ • z = 0`), consistently.
-/

@[expose] public section

universe u v

namespace AlgebraicGeometry.affineBlowUpAlgebra

open MvPolynomial IsLocalization.Away

variable {R : Type u} [CommRing R] {ι : Type v} (a : R) (g : ι → R) (I : Ideal R)

/-- The relation ideal `(a xᵢ − gᵢ : i ∈ ι)` of the presentation. -/
noncomputable def presentationIdeal : Ideal (MvPolynomial ι R) :=
  Ideal.span (Set.range fun i => C a * X i - C (g i))

theorem sub_mem_presentationIdeal (i : ι) : C a * X i - C (g i) ∈ presentationIdeal a g :=
  Ideal.subset_span ⟨i, rfl⟩

variable {I} (hg : ∀ i, g i ∈ I)

theorem aeval_frac_mem_ker (p : MvPolynomial ι R) (hp : p ∈ presentationIdeal a g) :
    aeval (fun i => frac (a := a) (hg i)) p = 0 := by
  have : presentationIdeal a g ≤
      RingHom.ker (aeval (fun i => frac (a := a) (hg i)) : MvPolynomial ι R →ₐ[R] _) := by
    refine Ideal.span_le.mpr ?_
    rintro _ ⟨i, rfl⟩
    rw [SetLike.mem_coe, RingHom.mem_ker]
    change aeval (fun i => frac (a := a) (hg i)) (C a * X i - C (g i)) = 0
    rw [map_sub, map_mul, aeval_C, aeval_X, aeval_C]
    apply Subtype.ext
    change algebraMap R (Localization.Away a) a *
      (algebraMap R (Localization.Away a) (g i) * invSelf a) -
        algebraMap R (Localization.Away a) (g i) = 0
    rw [mul_left_comm, mul_invSelf, mul_one, sub_self]
  exact this hp

/-- The presentation map `R[xᵢ]/(a xᵢ − gᵢ) → R[I/a]`, `xᵢ ↦ gᵢ/a` [Sta, Tag 0G8S]. -/
noncomputable def presentationHom :
    (MvPolynomial ι R ⧸ presentationIdeal a g) →ₐ[R] affineBlowUpAlgebra I a :=
  Ideal.Quotient.liftₐ (presentationIdeal a g) (aeval fun i => frac (a := a) (hg i))
    (aeval_frac_mem_ker a g hg)

@[simp]
theorem presentationHom_mk (p : MvPolynomial ι R) :
    presentationHom a g hg (Ideal.Quotient.mk _ p) = aeval (fun i => frac (a := a) (hg i)) p :=
  Ideal.Quotient.liftₐ_apply _ _ _ _

theorem presentationHom_mk_X (i : ι) :
    presentationHom a g hg (Ideal.Quotient.mk _ (X i)) = frac (a := a) (hg i) := by
  rw [presentationHom_mk, aeval_X]

/-- The presentation map is the unique `R`-algebra map with `xᵢ ↦ gᵢ/a`. -/
theorem presentationHom_unique
    (φ : (MvPolynomial ι R ⧸ presentationIdeal a g) →ₐ[R] affineBlowUpAlgebra I a)
    (hφ : ∀ i, φ (Ideal.Quotient.mk _ (X i)) = frac (a := a) (hg i)) :
    φ = presentationHom a g hg := by
  refine Ideal.Quotient.algHom_ext R (MvPolynomial.algHom_ext fun i => ?_)
  simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk, hφ, presentationHom_mk_X]

/-- For `I = (a, gᵢ : i ∈ ι)` the presentation map is surjective [Sta, Tag 0G8S], since `R[I/a]`
is generated by the `x/a`, `x ∈ I`, and `x = r a + ∑ rᵢ gᵢ` gives `x/a = r + ∑ rᵢ (gᵢ/a)`. -/
theorem presentationHom_surjective (hI : I = Ideal.span (insert a (Set.range g))) :
    Function.Surjective (presentationHom a g hg) := by
  intro z
  -- the image of the range in `R_a` contains the generators `x/a`, `x ∈ I`
  have key : ∀ x ∈ I, algebraMap R (Localization.Away a) x * invSelf a ∈
      ((presentationHom a g hg).range.map (affineBlowUpAlgebra I a).val) := by
    intro x hx
    rw [hI] at hx
    induction hx using Submodule.span_induction with
    | mem y hy =>
      rcases hy with rfl | ⟨i, rfl⟩
      · rw [mul_invSelf]
        exact one_mem _
      · exact ⟨frac (a := a) (hg i), ⟨Ideal.Quotient.mk _ (X i), presentationHom_mk_X a g hg i⟩,
          rfl⟩
    | zero => simp only [map_zero, zero_mul]; exact zero_mem _
    | add y z _ _ hy hz => rw [map_add, add_mul]; exact add_mem hy hz
    | smul r y _ hy =>
      rw [smul_eq_mul, map_mul, mul_assoc]
      exact mul_mem (Subalgebra.algebraMap_mem _ r) hy
  have hle : affineBlowUpAlgebra I a ≤
      (presentationHom a g hg).range.map (affineBlowUpAlgebra I a).val :=
    (affineBlowUpAlgebra_eq_adjoin I a).le.trans
      (Algebra.adjoin_le fun _ ⟨x, hx, hxz⟩ => hxz ▸ key x hx)
  obtain ⟨w, ⟨q, hq⟩, hw⟩ := hle z.2
  exact ⟨q, Subtype.ext ((congrArg Subtype.val hq).trans hw)⟩

/-- Elimination of the variables: `a^d p ≡ c (mod (a xᵢ − gᵢ))` for some `d` and constant `c`. -/
theorem exists_pow_mul_sub_C_mem (p : MvPolynomial ι R) :
    ∃ (d : ℕ) (c : R), C (a ^ d) * p - C c ∈ presentationIdeal a g := by
  induction p using MvPolynomial.induction_on with
  | C r => exact ⟨0, r, by rw [pow_zero, map_one, one_mul, sub_self]; exact zero_mem _⟩
  | add p q hp hq =>
    obtain ⟨d₁, c₁, h₁⟩ := hp
    obtain ⟨d₂, c₂, h₂⟩ := hq
    refine ⟨d₁ + d₂, a ^ d₂ * c₁ + a ^ d₁ * c₂, ?_⟩
    have : C (a ^ (d₁ + d₂)) * (p + q) - C (a ^ d₂ * c₁ + a ^ d₁ * c₂) =
        C (a ^ d₂) * (C (a ^ d₁) * p - C c₁) + C (a ^ d₁) * (C (a ^ d₂) * q - C c₂) := by
      simp only [map_add, map_mul, map_pow, pow_add]; ring
    rw [this]
    exact add_mem (Ideal.mul_mem_left _ _ h₁) (Ideal.mul_mem_left _ _ h₂)
  | mul_X p i hp =>
    obtain ⟨d, c, h⟩ := hp
    refine ⟨d + 1, c * g i, ?_⟩
    have : C (a ^ (d + 1)) * (p * X i) - C (c * g i) =
        C (a ^ d) * p * (C a * X i - C (g i)) + C (g i) * (C (a ^ d) * p - C c) := by
      simp only [map_mul, map_pow, pow_succ]; ring
    rw [this]
    exact add_mem (Ideal.mul_mem_left _ _ (sub_mem_presentationIdeal a g i))
      (Ideal.mul_mem_left _ _ h)

omit hg in
/-- The kernel of any `R`-algebra map from the presentation ring `R[xᵢ]/(a xᵢ − gᵢ)` to `R[I/a]`
is the `a`-power torsion of the source [Sta, Tag 0G8S]; the values on the variables play no role,
only the relations `a xᵢ = gᵢ` and the regularity of `a` on `R[I/a]`. -/
theorem algHom_apply_eq_zero_iff
    (φ : (MvPolynomial ι R ⧸ presentationIdeal a g) →ₐ[R] affineBlowUpAlgebra I a)
    (z : MvPolynomial ι R ⧸ presentationIdeal a g) :
    φ z = 0 ↔ ∃ k : ℕ, a ^ k • z = 0 := by
  constructor
  · intro hz
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective z
    obtain ⟨d, c, hdc⟩ := exists_pow_mul_sub_C_mem a g p
    have h0 : φ (Ideal.Quotient.mk _ (C (a ^ d)) * Ideal.Quotient.mk _ p -
        Ideal.Quotient.mk _ (C c)) = 0 := by
      rw [← map_mul, ← map_sub, Ideal.Quotient.eq_zero_iff_mem.mpr hdc, map_zero]
    rw [map_sub, map_mul, hz, mul_zero, zero_sub, neg_eq_zero, ← MvPolynomial.algebraMap_eq,
      Ideal.Quotient.mk_algebraMap, AlgHom.commutes] at h0
    have hc : algebraMap R (Localization.Away a) c = 0 := congrArg Subtype.val h0
    obtain ⟨⟨_, k, rfl⟩, hk⟩ := (IsLocalization.map_eq_zero_iff (Submonoid.powers a) _ c).mp hc
    have hk' : a ^ k * c = 0 := hk
    refine ⟨k + d, ?_⟩
    have hsplit : C (a ^ (k + d)) * p = C (a ^ k) * (C (a ^ d) * p - C c) + C (a ^ k * c) := by
      simp only [map_mul, map_pow, pow_add]; ring
    change Ideal.Quotient.mk _ (a ^ (k + d) • p) = 0
    rw [← MvPolynomial.C_mul', hsplit, map_add,
      Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.mul_mem_left _ _ hdc), zero_add, hk', map_zero,
      map_zero]
  · rintro ⟨k, hk⟩
    have : algebraMap R (affineBlowUpAlgebra I a) a ^ k * φ z = 0 := by
      rw [← map_pow, ← Algebra.smul_def, ← map_smul, hk, map_zero]
    exact (mem_nonZeroDivisors_iff.mp (pow_mem (algebraMap_mem_nonZeroDivisors (I := I) (a := a))
      k)).1 _ this

/-- The kernel of the presentation map is the `a`-power torsion of the source
[Sta, Tag 0G8S]. -/
theorem presentationHom_apply_eq_zero_iff (z : MvPolynomial ι R ⧸ presentationIdeal a g) :
    presentationHom a g hg z = 0 ↔ ∃ k : ℕ, a ^ k • z = 0 :=
  algHom_apply_eq_zero_iff a g _ z

end AlgebraicGeometry.affineBlowUpAlgebra
