/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Admissible
public import Hironaka.Scheme.BlowUp.UniversalProperty
import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Membership
import Hironaka.Scheme.BlowUp.Glue.Global
import Hironaka.Scheme.BlowUp.InverseImage
import Hironaka.Scheme.BlowUp.InvertibleSheaf
import Hironaka.Scheme.BlowUp.Transform.StrictTransform
import Mathlib.Algebra.Order.BigOperators.Ring.Finset

/-!
# Blowing up a product centre: the generic layer

Blowing up `X` along `I` and then blowing up the result along the inverse image of `J` is the
blow-up of `X` along `I·J` [Sta, Tag 080A].  This module proves the mathematics of that lemma
once, for arbitrary morphisms carrying the relevant clause of the universal property
[Hau14, Definition 4.4] — admissibility (the inverse image of the centre is invertible) and
universality (unique lifts of admissible morphisms) — so that the statements about the blow-up
`AlgebraicGeometry.Scheme.IdealSheafData.blowUp` (`Hironaka.Scheme.BlowUp.Glue.Product`) are
instances.  The chart lemmas are also used for the charts of blow-ups of smooth centres
(`Hironaka.Scheme.Smooth.ChartIso`, `Hironaka.Scheme.Smooth.BlowUpSmoothChart`) and for normal
crossings divisors (`Hironaka.Resolution.Algebraic.Snc.SncInvertible`).

## Main declarations

* `AlgebraicGeometry.Scheme.IdealSheafData.IsInvertible.of_mul`: the factors of an invertible
  ideal sheaf are invertible (from `Ideal.IsInvertible.of_mul`); powers of an invertible ideal sheaf
  are invertible by `isInvertible_pow` of `Hironaka.Scheme.BlowUp.Transform`.
* `affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors_of_mem`: a nonzerodivisor of `R` is a
  nonzerodivisor of `R[I/a]`.
* `isInvertible_comap_of_charts`: a morphism covered by charts `Spec R[I/a]` pulls invertible
  ideal sheaves back to invertible ones.
* `isInvertible_comap_mul_comp`: the composite of two admissible morphisms is admissible for the
  product centre.
* `existsUnique_lift_comp`: the composite of two universal morphisms is universal for the product
  centre.
* `exists_iso_of_universal`: two admissible universal morphisms for the same centre are
  isomorphic over the base by a unique isomorphism [Hau14, Remark 4.5].
* `IsBlowUp.comp`, `IsBlowUp.exists_iso`, `IsBlowUp.comp_iso`: the same, packaged with the
  predicate `IsBlowUp` of `Hironaka.Scheme.BlowUp.UniversalProperty`.

## The arguments

*Multiplicativity* of the inverse image ideal sheaf (`comap_mul`, `comap_pow`) is proved in
`Hironaka.Scheme.BlowUp.Transform.StrictTransform`.

*Pullback of an invertible ideal sheaf along a chart-covered morphism.*  Let `y ∈ B` and
`x = π y`.  Invertibility of `K` gives an affine `U ∋ x` with `K.ideal U = (k)`, `k` a
nonzerodivisor of `Γ(X, U)`; `y ∈ π⁻¹U` lies in the image of some chart `chart U a`.  The inverse
image of `K.comap π` along the chart is the inverse image of `K` along `chart U a ≫ π =
Spec (Γ(X, U) → Γ(X, U)[I(U)/a]) ≫ fromSpec`, i.e. (`comap_fromSpec`, `comap_ofIdealTop_Spec_map`)
the ideal sheaf of the principal ideal generated by the image of `k` in `Γ(X, U)[I(U)/a]`; that
image is a nonzerodivisor (`R → R_a` preserves nonzerodivisors, and `R[I/a] ⊆ R_a` is a subring),
so this ideal sheaf is invertible (`isInvertible_ofIdealTop_span_singleton`); the charts of this
kind cover `B`, and invertibility descends along a cover by open immersions
(`IsInvertible.of_forall_comap_isOpenImmersion`).

*Admissibility of the composite.*  `(I·J).comap (b' ≫ b) = I.comap (b' ≫ b) ·
(J.comap b).comap b'` is a product of two invertible ideal sheaves (`IsInvertible.mul`).

*Universality of the composite.*  A morphism `f` admissible for `I·J` is admissible for
`I` and for `J` (`IsInvertible.of_mul`), so lifts uniquely to `g₁` along `b`; then
`(J.comap b).comap g₁ = J.comap (g₁ ≫ b) = J.comap f` is invertible, so `g₁` lifts uniquely to `g₂`
along `b'`; and any lift `g` of `f` along `b' ≫ b` has `g ≫ b'` a lift of `f` along `b`, hence
`g ≫ b' = g₁`, hence `g = g₂`.

*Uniqueness of universal objects.*  With `π₁`, `π₂` both admissible and universal for `K`,
`π₁` lifts along `π₂` to `u` and `π₂` lifts along `π₁` to `v`; `u ≫ v` and `𝟙` are both lifts of
`π₁` along `π₁`, so they coincide, and symmetrically; `u` is the unique morphism over `X`.

The pullback of an effective Cartier divisor along a blow-up is [Sta, Tag 0809]; the universal
property of the blow-up is [Sta, Tag 0806]; [Hau14, Definition 4.4].
-/

@[expose] public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory Scheme.IdealSheafData TopologicalSpace

universe u

section Multiplicativity

variable {X Y : Scheme.{u}}

/-- The ideal sheaf of an ideal of `R` on `Spec R` (`specIdealSheaf`) is
multiplicative: `ofIdealTop` is a ring isomorphism (`equivOfIsAffine`) and `Ideal.map` is
multiplicative. -/
theorem specIdealSheaf_mul {R : Type u} [CommRing R] (I J : Ideal R) :
    specIdealSheaf (I * J) = specIdealSheaf I * specIdealSheaf J := by
  change Scheme.IdealSheafData.ofIdealTop ((I * J).map _) = Scheme.IdealSheafData.ofIdealTop
      (I.map _) * Scheme.IdealSheafData.ofIdealTop (J.map _)
  rw [Ideal.map_mul]
  exact map_mul (Scheme.IdealSheafData.equivOfIsAffine (X := Spec (.of R))).symm _ _

end Multiplicativity

section Factors

variable {X : Scheme.{u}}

/-- The factors of an invertible ideal sheaf are invertible (from `Ideal.IsInvertible.of_mul`
through the affine-local criterion `isInvertible_iff_forall_ideal`): if `I * J` is invertible, so
are `I` and `J`. -/
theorem Scheme.IdealSheafData.IsInvertible.of_mul
    {I J : X.IdealSheafData} (h : (I * J).IsInvertible) : I.IsInvertible ∧ J.IsInvertible := by
  have h' := (Scheme.IdealSheafData.isInvertible_iff_forall_ideal _).mp h
  refine ⟨(Scheme.IdealSheafData.isInvertible_iff_forall_ideal I).mpr fun U => ?_,
    (Scheme.IdealSheafData.isInvertible_iff_forall_ideal J).mpr fun U => ?_⟩
  · have := h' U
    rw [Scheme.IdealSheafData.ideal_mul, Pi.mul_apply] at this
    exact (Ideal.IsInvertible.of_mul this).1
  · have := h' U
    rw [Scheme.IdealSheafData.ideal_mul, Pi.mul_apply] at this
    exact (Ideal.IsInvertible.of_mul this).2

/-- The converse for `m ≥ 1`: if `I ^ m` is invertible, so is `I`. -/
theorem Scheme.IdealSheafData.IsInvertible.of_pow {I : X.IdealSheafData}
    {m : ℕ} (hm : 1 ≤ m) (h : (I ^ m).IsInvertible) : I.IsInvertible := by
  obtain ⟨k, rfl⟩ := Nat.exists_eq_add_of_le' hm
  rw [pow_succ] at h
  exact (Scheme.IdealSheafData.IsInvertible.of_mul h).2

end Factors

section NonZeroDivisors

variable {R : Type u} [CommRing R] (I : Ideal R) (a : R)

/-- The image in `R[I/a]` of a nonzerodivisor of `R` is a nonzerodivisor, because `R → R_a`
preserves nonzerodivisors
(`IsLocalization.map_nonZeroDivisors_le`) and `R[I/a] ⊆ R_a` is a subring
(`mem_nonZeroDivisors_of_injective`). -/
theorem affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors_of_mem {r : R}
    (hr : r ∈ nonZeroDivisors R) :
    algebraMap R (affineBlowUpAlgebra I a) r ∈ nonZeroDivisors (affineBlowUpAlgebra I a) := by
  apply mem_nonZeroDivisors_of_injective (f := (affineBlowUpAlgebra I a).val)
    (fun x y h => Subtype.ext h)
  rw [(affineBlowUpAlgebra I a).val.commutes r]
  exact IsLocalization.map_nonZeroDivisors_le (M := Submonoid.powers a)
    (S := Localization.Away a) (Submonoid.mem_map_of_mem _ hr)


/-- The ideal sheaf on `Spec R[I/a]` of the extension of a principal ideal `J = (k)` of `R` with
`k` a nonzerodivisor is invertible: its generator, the image of `k`, is a nonzerodivisor of
`R[I/a]` and hence of `Γ(Spec R[I/a], ⊤)`.  (Stated with `R` a plain ring: the chart computation
`comap_comap_eq_of_chart_π` lands exactly here with `R = Γ(X, U)`.) -/
theorem isInvertible_ofIdealTop_map_algebraMap_of_eq_span {J : Ideal R} {k : R}
    (hJ : J = Ideal.span {k}) (hk : k ∈ nonZeroDivisors R) :
    (Scheme.IdealSheafData.ofIdealTop ((J.map (algebraMap R (affineBlowUpAlgebra I a))).map
      (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra I a))).inv.hom)).IsInvertible := by
  subst hJ
  rw [Ideal.map_span, Set.image_singleton, Ideal.map_span, Set.image_singleton]
  exact isInvertible_ofIdealTop_span_singleton (map_mem_nonZeroDivisors_of_ringEquiv
    (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra I a))).symm.commRingCatIsoToRingEquiv
    (affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors_of_mem I a hk))

end NonZeroDivisors

section Charts

variable {X : Scheme.{u}} (I : X.IdealSheafData)

/-- The inverse image of `K.comap π` along a chart `chart U a` with
`chart U a ≫ π = Spec (algebraMap) ≫ fromSpec` is the ideal sheaf on `Spec Γ(X, U)[I(U)/a]` of the
extension of `K.ideal U` (`comap_fromSpec`, `comap_ofIdealTop_Spec_map`). -/
theorem comap_comap_eq_of_chart_π {B : Scheme.{u}} (π : B ⟶ X) (U : X.affineOpens) (a : I.ideal U)
    (chart : Spec (.of (affineBlowUpAlgebra (I.ideal U) a)) ⟶ B)
    (hπ : chart ≫ π =
      Spec.map (CommRingCat.ofHom (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a))) ≫
        (U.2 : IsAffineOpen U.1).isoSpec.inv ≫ U.1.ι)
    (K : X.IdealSheafData) :
    (K.comap π).comap chart =
      Scheme.IdealSheafData.ofIdealTop (((K.ideal U).map (algebraMap Γ(X, U) (affineBlowUpAlgebra
          (I.ideal U) a))).map
        (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (I.ideal U) a))).inv.hom) := by
  -- term-mode steps: `rw` would compare `comap`-headed subterms by unfolding `comap` (pullbacks)
  have s1 : (K.comap π).comap chart = K.comap (chart ≫ π) := (Scheme.IdealSheafData.comap_comp K
      chart π).symm
  have s2 : K.comap (chart ≫ π) = K.comap (Spec.map (CommRingCat.ofHom
      (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a))) ≫
      (U.2 : IsAffineOpen U.1).isoSpec.inv ≫ U.1.ι) := congrArg (K.comap ·) hπ
  have s3 : K.comap (Spec.map (CommRingCat.ofHom
      (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a))) ≫
      (U.2 : IsAffineOpen U.1).isoSpec.inv ≫ U.1.ι) =
      (K.comap U.2.fromSpec).comap (Spec.map (CommRingCat.ofHom
        (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a)))) :=
    Scheme.IdealSheafData.comap_comp K _ U.2.fromSpec
  have s4 : (K.comap U.2.fromSpec).comap (Spec.map (CommRingCat.ofHom
      (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a)))) =
      (Scheme.IdealSheafData.ofIdealTop ((K.ideal U).map (Scheme.ΓSpecIso Γ(X, U)).inv.hom)).comap
        (Spec.map (CommRingCat.ofHom
          (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a)))) :=
    congrArg (fun L : (Spec Γ(X, U)).IdealSheafData => L.comap _)
        (Scheme.IdealSheafData.comap_fromSpec K U)
  have s5 : (Scheme.IdealSheafData.ofIdealTop ((K.ideal U).map (Scheme.ΓSpecIso Γ(X,
      U)).inv.hom)).comap
      (Spec.map (CommRingCat.ofHom
        (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a)))) =
      Scheme.IdealSheafData.ofIdealTop (((K.ideal U).map (CommRingCat.ofHom
        (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a))).hom).map
          (Scheme.ΓSpecIso (.of (affineBlowUpAlgebra (I.ideal U) a))).inv.hom) :=
    Scheme.IdealSheafData.comap_ofIdealTop_Spec_map _ (K.ideal U)
  exact s1.trans (s2.trans (s3.trans (s4.trans s5)))

/-- Every point of `B` lies on a chart over an affine open `U` on which the invertible `K` has a
nonzerodivisor generator (the pointwise definition of `IsInvertible` and the chart cover of
`π⁻¹U`). -/
theorem exists_mem_range_chart_of_isInvertible {B : Scheme.{u}} (π : B ⟶ X)
    (chart : ∀ (U : X.affineOpens) (a : I.ideal U),
      Spec (.of (affineBlowUpAlgebra (I.ideal U) a)) ⟶ B)
    (hcov : ∀ U : X.affineOpens,
      ⋃ a : I.ideal U, Set.range (chart U a) = (π ⁻¹ᵁ U.1 : Set B))
    (K : X.IdealSheafData) (hK : K.IsInvertible) (y : B) :
    ∃ (U : X.affineOpens) (a : I.ideal U), y ∈ Set.range (chart U a) ∧
      ∃ k ∈ nonZeroDivisors Γ(X, U), K.ideal U = Ideal.span {k} := by
  obtain ⟨U, hyU, k, hk, hKU⟩ := hK (π y)
  have hy : y ∈ ⋃ a : I.ideal U, Set.range (chart U a) := by rw [hcov U]; exact hyU
  obtain ⟨a, ha⟩ := Set.mem_iUnion.mp hy
  exact ⟨U, a, ha, k, hk, hKU⟩

/-- On a chart over an affine open `U` where `K.ideal U = (k)` with `k` a nonzerodivisor, the
inverse image of `K.comap π` is the ideal sheaf of the principal ideal generated by the image of
`k` in `Γ(X, U)[I(U)/a]`, a nonzerodivisor (`algebraMap_mem_nonZeroDivisors_of_mem`), hence
invertible (`isInvertible_ofIdealTop_span_singleton`). -/
theorem isInvertible_comap_comap_chart {B : Scheme.{u}} (π : B ⟶ X) (U : X.affineOpens)
    (a : I.ideal U) (chart : Spec (.of (affineBlowUpAlgebra (I.ideal U) a)) ⟶ B)
    (hπ : chart ≫ π =
      Spec.map (CommRingCat.ofHom (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a))) ≫
        (U.2 : IsAffineOpen U.1).isoSpec.inv ≫ U.1.ι)
    (K : X.IdealSheafData) {k : Γ(X, U)} (hk : k ∈ nonZeroDivisors Γ(X, U))
    (hKU : K.ideal U = Ideal.span {k}) : ((K.comap π).comap chart).IsInvertible :=
  (congrArg Scheme.IdealSheafData.IsInvertible (comap_comap_eq_of_chart_π I π U a chart hπ K)).mpr
    (isInvertible_ofIdealTop_map_algebraMap_of_eq_span (I.ideal U) a hKU hk)

/-- Bookkeeping for `isInvertible_comap_of_charts`: the charts relevant to an invertible `K` — an
affine open `U`,
a chart index `a ∈ I(U)`, and a nonzerodivisor generator `k` of `K(U)`.  (A structure rather than
a subtype of a sigma type: it keeps the index terms small for unification.) -/
structure ChartIndex (I K : X.IdealSheafData) where
  /-- The affine open. -/
  U : X.affineOpens
  /-- The chart over `U`. -/
  a : I.ideal U
  /-- A generator of `K(U)`. -/
  k : Γ(X, U)
  /-- The generator is a nonzerodivisor. -/
  hk : k ∈ nonZeroDivisors Γ(X, U)
  /-- `K(U) = (k)`. -/
  hKU : K.ideal U = Ideal.span {k}

/-- **A chart-covered morphism pulls invertible ideal sheaves back to invertible ones**
([Sta, Tag 080A]; the pullback of an effective Cartier divisor along a blow-up, [Sta, Tag 0809]):
a morphism `π : B ⟶ X` covered by charts — open immersions
`chart U a : Spec Γ(X, U)[I(U)/a] ⟶ B` with
`chart U a ≫ π = Spec (algebraMap) ≫ U.isoSpec.inv ≫ U.ι` whose images cover `π⁻¹U` — pulls
every invertible ideal sheaf `K` on `X` back to an invertible ideal sheaf on `B`. -/
theorem isInvertible_comap_of_charts {B : Scheme.{u}} (π : B ⟶ X)
    (chart : ∀ (U : X.affineOpens) (a : I.ideal U),
      Spec (.of (affineBlowUpAlgebra (I.ideal U) a)) ⟶ B)
    (hoi : ∀ (U : X.affineOpens) (a : I.ideal U), IsOpenImmersion (chart U a))
    (hπ : ∀ (U : X.affineOpens) (a : I.ideal U), chart U a ≫ π =
      Spec.map (CommRingCat.ofHom (algebraMap Γ(X, U) (affineBlowUpAlgebra (I.ideal U) a))) ≫
        (U.2 : IsAffineOpen U.1).isoSpec.inv ≫ U.1.ι)
    (hcov : ∀ U : X.affineOpens,
      ⋃ a : I.ideal U, Set.range (chart U a) = (π ⁻¹ᵁ U.1 : Set B))
    (K : X.IdealSheafData) (hK : K.IsInvertible) : (K.comap π).IsInvertible := by
  have : ∀ p : ChartIndex I K, IsOpenImmersion (chart p.U p.a) := fun p => hoi _ _
  refine Scheme.IdealSheafData.IsInvertible.of_forall_comap_isOpenImmersion (K.comap π) (ι :=
      ChartIndex I K)
    (fun p => chart p.U p.a) (fun y => ?_) (fun p => ?_)
  · obtain ⟨U, a, hy, k, hk, hKU⟩ := exists_mem_range_chart_of_isInvertible I π chart hcov K hK y
    exact ⟨⟨U, a, k, hk, hKU⟩, hy⟩
  · exact isInvertible_comap_comap_chart I π p.U p.a (chart p.U p.a) (hπ _ _) K p.hk p.hKU

end Charts

section Universal

variable {X X' X'' : Scheme.{u}} (I J : X.IdealSheafData) (b : X' ⟶ X) (b' : X'' ⟶ X')

/-- Admissibility of the composite [Sta, Tag 080A] (the ideal of `E'' = E' + (b')⁻¹E` is
`(b ∘ b')⁻¹𝓘 (b ∘ b')⁻¹𝓙 𝓞_{X''}`): if `I` pulls back along `b' ≫ b` to an invertible ideal sheaf
and `J.comap b` pulls back along `b'` to an invertible ideal sheaf (the exceptional
ideal of `b'`), then `b' ≫ b` is admissible for `I * J` (`comap_mul`, `IsInvertible.mul`). -/
theorem isInvertible_comap_mul_comp (hI : (I.comap (b' ≫ b)).IsInvertible)
    (hJ : ((J.comap b).comap b').IsInvertible) : ((I * J).comap (b' ≫ b)).IsInvertible := by
  rw [Scheme.IdealSheafData.comap_mul]
  exact hI.mul (by rw [Scheme.IdealSheafData.comap_comp]; exact hJ)

/-- Universality of the composite [Sta, Tag 080A]; [Hau14, Definition 4.4] (clause (ii)): if `b`
is universal for `I` and `b'` is universal for `J.comap b` (unique lifts of admissible morphisms),
then `b' ≫ b` is universal for `I * J`.  An `f` admissible
for `I * J` is admissible for `I` (`IsInvertible.of_mul`) and lifts uniquely to `g₁` along `b`;
`(J.comap b).comap g₁ = J.comap f` is invertible, so `g₁` lifts uniquely to `g₂` along `b'`; a lift
`g` of `f` along `b' ≫ b` has `g ≫ b'` a lift of `f` along `b`, so `g ≫ b' = g₁` and `g = g₂`. -/
theorem existsUnique_lift_comp
    (hub : ∀ {Y : Scheme.{u}} (f : Y ⟶ X), (I.comap f).IsInvertible →
      ∃! g : Y ⟶ X', g ≫ b = f)
    (hub' : ∀ {Y : Scheme.{u}} (f : Y ⟶ X'), ((J.comap b).comap f).IsInvertible →
      ∃! g : Y ⟶ X'', g ≫ b' = f)
    {Y : Scheme.{u}} (f : Y ⟶ X) (hf : ((I * J).comap f).IsInvertible) :
    ∃! g : Y ⟶ X'', g ≫ (b' ≫ b) = f := by
  rw [Scheme.IdealSheafData.comap_mul] at hf
  obtain ⟨hfI, hfJ⟩ := Scheme.IdealSheafData.IsInvertible.of_mul hf
  obtain ⟨g₁, hg₁, hg₁u⟩ := hub f hfI
  have hg₁J : ((J.comap b).comap g₁).IsInvertible :=
      by rw [← Scheme.IdealSheafData.comap_comp, hg₁]; exact hfJ
  obtain ⟨g₂, hg₂, hg₂u⟩ := hub' g₁ hg₁J
  refine ⟨g₂, ?_, fun g hg => ?_⟩
  · change g₂ ≫ (b' ≫ b) = f
    rw [← Category.assoc, hg₂, hg₁]
  · exact hg₂u g (hg₁u (g ≫ b') (by change (g ≫ b') ≫ b = f; rw [Category.assoc]; exact hg))

end Universal

section Iso

variable {X : Scheme.{u}}

/-- **Uniqueness of the blow-up up to unique isomorphism** [Hau14, Remark 4.5]; [Sta, Tag 080A]:
two morphisms `π₁ : B₁ ⟶ X`, `π₂ : B₂ ⟶ X`, both admissible and universal for `K`, are isomorphic
over
`X` by a unique isomorphism: `e.hom` is the lift of `π₁` along `π₂`, `e.inv` the lift of `π₂`
along `π₁`, and the composites are identities because `𝟙` is the unique lift of `πᵢ` along `πᵢ`. -/
theorem exists_iso_of_universal {B₁ B₂ : Scheme.{u}} (K : X.IdealSheafData) (π₁ : B₁ ⟶ X)
    (π₂ : B₂ ⟶ X) (h₁ : (K.comap π₁).IsInvertible)
    (hu₁ : ∀ {Y : Scheme.{u}} (f : Y ⟶ X), (K.comap f).IsInvertible →
      ∃! g : Y ⟶ B₁, g ≫ π₁ = f)
    (h₂ : (K.comap π₂).IsInvertible)
    (hu₂ : ∀ {Y : Scheme.{u}} (f : Y ⟶ X), (K.comap f).IsInvertible →
      ∃! g : Y ⟶ B₂, g ≫ π₂ = f) :
    ∃ e : B₁ ≅ B₂, e.hom ≫ π₂ = π₁ ∧ ∀ ψ : B₁ ⟶ B₂, ψ ≫ π₂ = π₁ → ψ = e.hom := by
  obtain ⟨u, hu, huu⟩ := hu₂ π₁ h₁
  obtain ⟨v, hv, -⟩ := hu₁ π₂ h₂
  obtain ⟨_, -, hid₁⟩ := hu₁ π₁ h₁
  obtain ⟨_, -, hid₂⟩ := hu₂ π₂ h₂
  refine ⟨⟨u, v, ?_, ?_⟩, hu, fun ψ hψ => huu ψ hψ⟩
  · exact (hid₁ (u ≫ v) (show (u ≫ v) ≫ π₁ = π₁ by rw [Category.assoc, hv, hu])).trans
      (hid₁ (𝟙 _) (Category.id_comp _)).symm
  · exact (hid₂ (v ≫ u) (show (v ≫ u) ≫ π₂ = π₂ by rw [Category.assoc, hu, hv])).trans
      (hid₂ (𝟙 _) (Category.id_comp _)).symm

/-- Two morphisms over `X` from a source admissible for `K` into a target universal for `K`
coincide (`hom_ext` for any universal morphism). -/
theorem hom_ext_of_universal {B Y : Scheme.{u}} (K : X.IdealSheafData) (π : B ⟶ X)
    (hu : ∀ {Y : Scheme.{u}} (f : Y ⟶ X), (K.comap f).IsInvertible → ∃! g : Y ⟶ B, g ≫ π = f)
    (f : Y ⟶ X) (hf : (K.comap f).IsInvertible) (g g' : Y ⟶ B) (e : g ≫ π = f)
    (e' : g' ≫ π = f) : g = g' := by
  obtain ⟨g₀, -, hg₀⟩ := hu f hf
  exact (hg₀ g e).trans (hg₀ g' e').symm

/-- **The composite of two blow-ups is the blow-up of the product centre** [Sta, Tag 080A], with
the predicate `IsBlowUp` [Hau14, Definition 4.4]: if `b` is a blow-up of `X` along `I`, `b'` a
blow-up of `X'` along `J.comap b`, and `I` pulls back along `b' ≫ b` to an invertible ideal sheaf,
then `b' ≫ b` is a blow-up of `X` along `I * J`. -/
theorem IsBlowUp.comp {X' X'' : Scheme.{u}} {I J : X.IdealSheafData} {b : X' ⟶ X} {b' : X'' ⟶ X'}
    (hb : IsBlowUp I b) (hb' : IsBlowUp (J.comap b) b') (hI : (I.comap (b' ≫ b)).IsInvertible) :
    IsBlowUp (I * J) (b' ≫ b) :=
  ⟨isInvertible_comap_mul_comp I J b b' hI hb'.admissible,
    fun f hf => existsUnique_lift_comp I J b b' hb.existsUnique_lift hb'.existsUnique_lift f hf⟩

/-- Two blow-ups of `X` along `K` are isomorphic over `X` by a unique isomorphism
[Hau14, Remark 4.5]. -/
theorem IsBlowUp.exists_iso {B₁ B₂ : Scheme.{u}} {K : X.IdealSheafData} {π₁ : B₁ ⟶ X}
    {π₂ : B₂ ⟶ X} (h₁ : IsBlowUp K π₁) (h₂ : IsBlowUp K π₂) :
    ∃ e : B₁ ≅ B₂, e.hom ≫ π₂ = π₁ ∧ ∀ ψ : B₁ ⟶ B₂, ψ ≫ π₂ = π₁ → ψ = e.hom :=
  exists_iso_of_universal K π₁ π₂ h₁.admissible h₁.existsUnique_lift h₂.admissible
    h₂.existsUnique_lift

/-- The blow-up predicate transported along an isomorphism of the base (used to read the blow-up
of an affine chart over `Spec Γ(U)`, [Hau14, Theorem 4.19]) — if `π : B ⟶ X`
is a blow-up along `I`, then `π ≫ e.hom : B ⟶ X'` is a blow-up along `I.comap e.inv`. -/
theorem IsBlowUp.comp_iso {X X' B : Scheme.{u}} {I : X.IdealSheafData} {π : B ⟶ X}
    (h : IsBlowUp I π) (e : X ≅ X') : IsBlowUp (I.comap e.inv) (π ≫ e.hom) where
  admissible := by
    rw [← Scheme.IdealSheafData.comap_comp, Category.assoc, e.hom_inv_id, Category.comp_id]
    exact h.admissible
  existsUnique_lift f hf := by
    rw [← Scheme.IdealSheafData.comap_comp] at hf
    obtain ⟨g, hg, huniq⟩ := h.existsUnique_lift (f ≫ e.inv) hf
    refine ⟨g, ?_, fun g' hg' => huniq g' ?_⟩
    · change g ≫ π ≫ e.hom = f
      rw [← Category.assoc, hg, Category.assoc, e.inv_hom_id, Category.comp_id]
    · change g' ≫ π = f ≫ e.inv
      have hg'' : g' ≫ π ≫ e.hom = f := hg'
      rw [← hg'', Category.assoc, Category.assoc, e.hom_inv_id, Category.comp_id]

end Iso

end AlgebraicGeometry
