/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.Transform.Defs
public import Mathlib.AlgebraicGeometry.Noetherian
public import Hironaka.Scheme.BlowUp.Invertible
import Hironaka.Scheme.BlowUp.InverseImage
import Hironaka.Scheme.BlowUp.InvertibleSheaf

/-!
# Colon and saturation of ideal sheaves; transforms under a blow-up

The transforms of an ideal sheaf under a blow-up — total, strict, controlled and weak
[Hau14, Definitions 6.1, 6.2 and 6.8]; [Hir64, Ch. 0, §5, p. 142] — are built from two operations on
ideal sheaves: the colon ideal sheaf `(I : K)` (`IdealSheafData.colon`) and the `K`-power torsion
saturation `⋃ᵢ (I : Kⁱ)` (`IdealSheafData.saturate`); they are defined along any morphism
`π : B ⟶ X` with a distinguished ideal sheaf `E` on `B` (`strictTransformAlong π E J`,
`controlledTransformAlong π E J c`, `exceptionalOrderAlong π E J`, `weakTransformAlong π E J`), the
blow-up and its exceptional divisor in the applications. This module proves the calculus of the
two operations and the elementary properties of the transforms, and defines Kollár's birational
transform of a marked ideal under the blow-up with centre `D`, `J.markedTransform D m`
[Kol07, Definition 60], the controlled transform along `D.blowUpπ` with control `m`.

## Main declarations

* `le_colon_iff_mul_le`: `(I : K)` is the largest ideal sheaf `J` with `J * K ≤ I`; its sections on
  an affine open are the colon ideal `(I(U) : K(U))` whenever every `K(U)` is finitely generated
  (`ideal_colon_of_fg`), in particular for `K` invertible (`ideal_colon_of_isInvertible`, via
  `Ideal.IsInvertible.fg`).
* `ideal_saturate`, `coe_support_saturate`: the sections and the support of the saturation.
* `pow_mul_colon_of_dvd`: `E ^ c * (I : E ^ c) = I` when `E ^ c ∣ I`; `colon_pow_eq_of_mul_eq`:
  for invertible `E` the quotient is unique.
* `controlledTransformAlong_le_strictTransformAlong`, `ideal_controlledTransformAlong_of_appLE`:
  the controlled transforms lie below the strict transform; the chart formula.
* `IdealSheafData.markedTransform J D m`.

## The arguments

*Colon and localization.* For a finitely generated ideal `J = (j₁, …, jₙ)` of `R` and a
localization `S` of `R` at `M`, `(I : J) S = (I S : J S)` (`map_colon_of_fg`): the inclusion `⊆`
is formal; for `⊇`, an element `z = x/m` with `z jₖ ∈ I S` for every `k` has `cₖ x jₖ ∈ I` for some
`cₖ ∈ M`, so `c x ∈ (I : J)` for `c = ∏ cₖ` and `z = (c x)/(c m)`. Hauser's Lemma 6.3 is the
case of a principal `J`.

*Finite generation of invertible ideals.* An invertible ideal `J` of `A` is generated, on a
basic open `D(s)` around each prime, by one element `a ∈ J`; finitely many such `D(sₖ)` cover
`Spec A`; for `x ∈ J` some power `sₖ^N x` lies in `(aₖ)` for every `k`, and the `sₖ^N` generate
the unit ideal, so `J = (a₁, …, aₙ)`.

*Uniqueness of the quotient.* If `E ^ c * K = I` with `E` invertible then `K ≤ (I : E ^ c)` by
definition, and conversely on an affine open where `E ^ c` is generated by a nonzerodivisor `e`,
`u e ∈ e K` forces `u ∈ K`; such opens cover the scheme.

## Conventions

The colon of ideals is Mathlib's `Submodule.colon` with the divisor coerced to a set:
`(I.ideal U).colon (K.ideal U : Set Γ(X, U))`. The exceptional order is a natural number: the
supremum in `ℕ` of the exponents `c` with `E ^ c ∣ J.comap π` (`0` when unbounded, i.e. when
`J.comap π = 0`, and `0` when only `c = 0` qualifies).

## Boundary cases

`K = ⊤`: `(I : ⊤) = I`, the saturation is `I`. `K = ⊥`: `(I : ⊥) = ⊤`. `I = ⊤`: every colon is
`⊤`. `J.comap π = 0`: the exceptional order is `0` and the weak transform is `0`. `c = 0`: the
controlled transform is the total transform.
-/

@[expose] public section

universe u v w

open AlgebraicGeometry CategoryTheory

/-! ### Ring-level lemmas -/

namespace AlgebraicGeometry

/-- `J ≤ (I : K)` iff `J K ≤ I`, for ideals. -/
theorem le_colon_iff_mul_le {R : Type u} [CommRing R] {I J K : Ideal R} :
    J ≤ I.colon (K : Set R) ↔ J * K ≤ I := by
  constructor
  · intro h
    rw [Ideal.mul_le]
    intro r hr s hs
    exact Submodule.mem_colon.mp (h hr) s hs
  · intro h r hr
    exact Submodule.mem_colon.mpr fun s hs => Ideal.mul_le.mp h r hr s hs

/-- The colon by a finitely generated ideal commutes with localization, `(I : J) S = (I S : J S)`
(the case of a principal divisor is [Hau14, Lemma 6.3]). -/
theorem map_colon_of_fg {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]
    (M : Submonoid R) [IsLocalization M S] (I J : Ideal R) (hJ : J.FG) :
    (I.colon (J : Set R)).map (algebraMap R S) =
      (I.map (algebraMap R S)).colon (J.map (algebraMap R S) : Set S) := by
  classical
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap]
    intro x hx
    rw [Ideal.mem_comap]
    have h1 : Ideal.span {x} * J ≤ I :=
      le_colon_iff_mul_le.mp (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hx))
    have h2 : Ideal.span {algebraMap R S x} * J.map (algebraMap R S) ≤ I.map (algebraMap R S) := by
      rw [← Set.image_singleton, ← Ideal.map_span, ← Ideal.map_mul]
      exact Ideal.map_mono h1
    exact le_colon_iff_mul_le.mpr h2 (Ideal.mem_span_singleton_self _)
  · intro z hz
    obtain ⟨s, rfl⟩ := hJ
    obtain ⟨⟨x, m⟩, rfl⟩ := IsLocalization.mk'_surjective M z
    have key : ∀ j ∈ s, ∃ c ∈ M, c * (x * j) ∈ I := by
      intro j hj
      have hzj : IsLocalization.mk' S x m * algebraMap R S j ∈ I.map (algebraMap R S) :=
        Submodule.mem_colon.mp hz _ (Ideal.mem_map_of_mem _ (Ideal.subset_span hj))
      rw [← IsLocalization.mk'_one (M := M) S j, ← IsLocalization.mk'_mul, mul_one] at hzj
      exact (IsLocalization.mk'_mem_map_algebraMap_iff M S I (x * j) m).mp hzj
    choose! c hcM hcI using key
    refine (IsLocalization.mk'_mem_map_algebraMap_iff M S _ x m).mpr ⟨∏ j ∈ s, c j, ?_, ?_⟩
    · exact Submonoid.prod_mem _ fun j hj => hcM j hj
    · rw [Ideal.colon_span]
      refine Submodule.mem_colon.mpr fun j hj => ?_
      rw [smul_eq_mul, mul_assoc, ← Finset.prod_erase_mul _ _ hj, mul_assoc]
      exact Ideal.mul_mem_left _ _ (hcI j hj)

/-- An invertible ideal is finitely generated: it is principal on finitely many basic opens
covering the spectrum, and the generators, together with the covering relation, generate it. -/
theorem _root_.Ideal.IsInvertible.fg {A : Type u} [CommRing A] {J : Ideal A} (hJ : J.IsInvertible) :
    J.FG := by
  classical
  rcases subsingleton_or_nontrivial A with hA | hA
  · have : Subsingleton (Ideal A) := (Submodule.subsingleton_iff A).mpr hA
    exact ⟨∅, Subsingleton.elim _ _⟩
  -- around every prime, a basic open on which `J` is generated by an element of `J`
  choose s hs a ha hJa _ using hJ
  -- the `s p` generate the unit ideal
  have htop : Ideal.span (Set.range s) = ⊤ := by
    by_contra hne
    obtain ⟨m, hm, hle⟩ := Ideal.exists_le_maximal _ hne
    exact hs ⟨m, hm.isPrime⟩ (hle (Ideal.subset_span ⟨_, rfl⟩))
  obtain ⟨T, hTs, hT⟩ := (Ideal.span_eq_top_iff_finite _).mp htop
  -- each `t ∈ T` is `s p` for some prime `p`; choose it
  have hT' : ∀ t ∈ T, ∃ p, s p = t := fun t ht => hTs ht
  choose! p hp using hT'
  -- for `x ∈ J` and `t ∈ T`, some power of `t` times `x` lies in `(a (p t))`
  have hloc : ∀ x ∈ J, ∀ t ∈ T, ∃ n : ℕ, t ^ n * x ∈ Ideal.span {a (p t)} := by
    intro x hx t ht
    have hx' : algebraMap A (Localization.Away (s (p t))) x ∈
        Ideal.span {algebraMap A (Localization.Away (s (p t))) (a (p t))} := by
      rw [← hJa (p t)]
      exact Ideal.mem_map_of_mem _ hx
    obtain ⟨y, hy⟩ := Ideal.mem_span_singleton'.mp hx'
    obtain ⟨n, y', hy'⟩ :=
      IsLocalization.Away.surj (S := Localization.Away (s (p t))) (s (p t)) y
    have h3 : algebraMap A (Localization.Away (s (p t))) (x * s (p t) ^ n) =
        algebraMap A (Localization.Away (s (p t))) (a (p t) * y') := by
      rw [map_mul, map_mul, map_pow, ← hy, ← hy']; ring
    obtain ⟨c, hc⟩ := (IsLocalization.eq_iff_exists (Submonoid.powers (s (p t))) _).mp h3
    obtain ⟨k, hk⟩ := (Submonoid.mem_powers_iff (c : A) (s (p t))).mp c.2
    rw [← hk] at hc
    refine ⟨k + n, Ideal.mem_span_singleton'.mpr ⟨s (p t) ^ k * y', ?_⟩⟩
    have ht' : t ^ (k + n) * x = s (p t) ^ (k + n) * x := by rw [hp t ht]
    rw [ht', pow_add]
    calc s (p t) ^ k * y' * a (p t) = s (p t) ^ k * (a (p t) * y') := by ring
      _ = s (p t) ^ k * (x * s (p t) ^ n) := hc.symm
      _ = s (p t) ^ k * s (p t) ^ n * x := by ring
  -- a common exponent
  refine ⟨T.image fun t => a (p t), le_antisymm ?_ ?_⟩
  · rw [Ideal.span_le]
    intro y hy
    obtain ⟨t, -, rfl⟩ := Finset.mem_image.mp (Finset.mem_coe.mp hy)
    exact ha (p t)
  · intro x hx
    choose! n hn using hloc x hx
    set N := T.sup n with hN
    have hxN : ∀ t ∈ T, t ^ N * x ∈ Ideal.span (T.image fun t => a (p t) : Set A) := by
      intro t ht
      have hle : n t ≤ N := Finset.le_sup (f := n) ht
      obtain ⟨d, hd⟩ := Nat.exists_eq_add_of_le hle
      rw [hd, pow_add, mul_comm (t ^ n t), mul_assoc]
      refine Ideal.mul_mem_left _ _ (Ideal.span_mono ?_ (hn t ht))
      rintro _ rfl
      exact Finset.mem_coe.mpr (Finset.mem_image_of_mem _ ht)
    have hpow : Ideal.span ((fun t => t ^ N) '' (T : Set A)) = ⊤ := Ideal.span_pow_eq_top _ hT N
    -- the powers `t ^ N` lie in the colon ideal `(span {a (p t)} : x)`, hence so does `1`
    have hle : Ideal.span ((fun t => t ^ N) '' (T : Set A)) ≤
        (Ideal.span (T.image fun t => a (p t) : Set A)).colon {x} := by
      rw [Ideal.span_le]
      rintro _ ⟨t, ht, rfl⟩
      exact Submodule.mem_colon_singleton.mpr (hxN t (Finset.mem_coe.mp ht))
    have h1 : (1 : A) ∈ (Ideal.span (T.image fun t => a (p t) : Set A)).colon {x} :=
      hle (hpow ▸ Submodule.mem_top)
    simpa using Submodule.mem_colon_singleton.mp h1

/-- For `f : R → S`, an ideal `I ⊆ R` and `s ∈ R`, `⋃ᵢ (Iᵉ : f(s)ⁱ) = (I·R_s)ᵉ ∩ S`: the extension
of `I·R_s` along `f_s : R_s → S_{f(s)}`, pulled back to `S` [Hau14, Lemma 6.3]. Hauser's
computation: `u f(s)ⁱ = ∑ aⱼ f(xⱼ)` iff `u = ∑ aⱼ f(xⱼ/sⁱ)`. -/
theorem iSup_colon_pow_eq {R : Type u} {S : Type v} [CommRing R] [CommRing S] (f : R →+* S)
    (I : Ideal R) (s : R) :
    ⨆ i : ℕ, (I.map f).colon {f s ^ i} =
      ((I.map (algebraMap R (Localization.Away s))).map
        (IsLocalization.Away.map (Localization.Away s) (Localization.Away (f s)) f s)).comap
          (algebraMap S (Localization.Away (f s))) := by
  have hφ : (IsLocalization.Away.map (Localization.Away s) (Localization.Away (f s)) f s).comp
      (algebraMap R (Localization.Away s)) = (algebraMap S (Localization.Away (f s))).comp f := by
    ext r
    simp [IsLocalization.Away.map]
  rw [Ideal.map_map, hφ, ← Ideal.map_map]
  have hmono : Monotone fun i : ℕ => (I.map f).colon ({f s ^ i} : Set S) := by
    intro i j hij z hz
    rw [Submodule.mem_colon_singleton] at hz ⊢
    obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_le hij
    rw [smul_eq_mul] at hz ⊢
    rw [pow_add, ← mul_assoc]
    exact Ideal.mul_mem_right _ _ hz
  ext z
  rw [Submodule.mem_iSup_of_directed _ hmono.directed_le, Ideal.mem_comap,
    IsLocalization.algebraMap_mem_map_algebraMap_iff (M := Submonoid.powers (f s))]
  constructor
  · rintro ⟨i, hi⟩
    refine ⟨f s ^ i, Submonoid.pow_mem _ (Submonoid.mem_powers _) i, ?_⟩
    rw [mul_comm]
    exact Submodule.mem_colon_singleton.mp hi
  · rintro ⟨m, hm, hmz⟩
    obtain ⟨i, rfl⟩ := (Submonoid.mem_powers_iff m (f s)).mp hm
    refine ⟨i, Submodule.mem_colon_singleton.mpr ?_⟩
    rw [smul_eq_mul, mul_comm]
    exact hmz

/-- In a domain, a prime `h` not dividing `g`: if `g ∣ z hⁱ` then `g ∣ z` (cancel `h` one factor
at a time, using that `h` divides the cofactor). -/
theorem dvd_of_dvd_mul_pow {R : Type u} [CommRing R] [IsDomain R] {h g : R} (hh : Prime h)
    (hg : ¬ h ∣ g) {z : R} : ∀ i : ℕ, g ∣ z * h ^ i → g ∣ z
  | 0, hz => by simpa using hz
  | i + 1, hz => by
    obtain ⟨w, hw⟩ := hz
    have hdvd : h ∣ g * w := ⟨z * h ^ i, by rw [← hw]; ring⟩
    obtain ⟨w', rfl⟩ := (hh.dvd_or_dvd hdvd).resolve_left hg
    refine dvd_of_dvd_mul_pow hh hg i ⟨w', mul_left_cancel₀ hh.ne_zero ?_⟩
    rw [pow_succ] at hw
    linear_combination hw

/-- The ring form of "for principal ideals the weak and strict transforms coincide"
[Hau14, Remark 6.9]: in a domain, for a prime `h` not dividing `g`, `⋃ᵢ ((hᵏ g) : hⁱ) = (g)`. -/
theorem iSup_colon_pow_span_singleton_eq {R : Type u} [CommRing R] [IsDomain R] {h g : R}
    (hh : Prime h) (hg : ¬ h ∣ g) (k : ℕ) :
    ⨆ i : ℕ, (Ideal.span {h ^ k * g}).colon {h ^ i} = Ideal.span {g} := by
  apply le_antisymm
  · refine iSup_le fun i z hz => ?_
    rw [Submodule.mem_colon_singleton, smul_eq_mul, Ideal.mem_span_singleton] at hz
    rw [Ideal.mem_span_singleton]
    obtain ⟨w, hw⟩ := hz
    exact dvd_of_dvd_mul_pow hh hg i ⟨w * h ^ k, by rw [hw]; ring⟩
  · refine le_iSup_of_le k ?_
    rw [Ideal.span_le, Set.singleton_subset_iff]
    exact Submodule.mem_colon_singleton.mpr
      (Ideal.mem_span_singleton'.mpr ⟨1, by rw [smul_eq_mul]; ring⟩)

end AlgebraicGeometry

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X : Scheme.{u}} (I J K : X.IdealSheafData)

/-! ### The colon of ideal sheaves -/

theorem ideal_colon_le (U : X.affineOpens) :
    (I.colon K).ideal U ≤ (I.ideal U).colon (K.ideal U : Set Γ(X, U)) :=
  ideal_ofIdeals_le _ U

theorem le_colon_iff :
    J ≤ I.colon K ↔ ∀ U, J.ideal U ≤ (I.ideal U).colon (K.ideal U : Set Γ(X, U)) :=
  le_ofIdeals_iff

theorem le_colon_iff_mul_le : J ≤ I.colon K ↔ J * K ≤ I := by
  rw [le_colon_iff, le_def]
  exact forall_congr' fun U => AlgebraicGeometry.le_colon_iff_mul_le

theorem mul_le_self_left : I * K ≤ I := fun _ => Ideal.mul_le_left

theorem le_colon_self : I ≤ I.colon K :=
  (le_colon_iff_mul_le I I K).mpr (mul_le_self_left I K)

theorem colon_mul_le : I.colon K * K ≤ I :=
  (le_colon_iff_mul_le I (I.colon K) K).mp le_rfl

theorem colon_mono_left (h : I ≤ J) : I.colon K ≤ J.colon K :=
  (le_colon_iff_mul_le J _ K).mpr ((colon_mul_le I K).trans h)

theorem colon_anti_right {K K' : X.IdealSheafData} (h : K ≤ K') : I.colon K' ≤ I.colon K :=
  (le_colon_iff_mul_le I _ K).mpr <| by
    have h1 : I.colon K' * K ≤ I.colon K' * K' := le_def.mpr fun U => Ideal.mul_mono_right (h U)
    exact h1.trans (colon_mul_le I K')

theorem colon_top : I.colon ⊤ = I :=
  le_antisymm ((mul_top _).symm.le.trans (colon_mul_le I ⊤)) (le_colon_self I ⊤)

/-- `((I : K) : L) = (I : K L)`. -/
theorem colon_colon (L : X.IdealSheafData) : (I.colon K).colon L = I.colon (K * L) := by
  apply le_antisymm
  · rw [le_colon_iff_mul_le, mul_comm K L, ← mul_assoc]
    have h1 : (I.colon K).colon L * L * K ≤ I.colon K * K :=
      le_def.mpr fun U => Ideal.mul_mono_left (colon_mul_le (I.colon K) L U)
    exact h1.trans (colon_mul_le I K)
  · rw [le_colon_iff_mul_le, le_colon_iff_mul_le, mul_assoc, mul_comm L K]
    exact colon_mul_le I (K * L)

/-- On every affine open the sections of the colon sheaf are the colon ideal, provided the divisor
is finitely generated on every affine open: the family `U ↦ (I(U) : K(U))` is then itself an ideal
sheaf (`AlgebraicGeometry.map_colon_of_fg`), and `colon` recovers it. -/
theorem ideal_colon_of_fg (hK : ∀ U : X.affineOpens, (K.ideal U).FG) (U : X.affineOpens) :
    (I.colon K).ideal U = (I.ideal U).colon (K.ideal U : Set Γ(X, U)) := by
  refine le_antisymm (ideal_colon_le I K U) ?_
  let G : X.IdealSheafData :=
    { ideal := fun U => (I.ideal U).colon (K.ideal U : Set Γ(X, U))
      map_ideal_basicOpen := fun U f => by
        let _ : Algebra Γ(X, U) Γ(X, X.affineBasicOpen f) :=
          (X.presheaf.map (homOfLE (X.basicOpen_le f)).op).hom.toAlgebra
        have : IsLocalization.Away f Γ(X, X.basicOpen f) :=
          U.2.isLocalization_of_eq_basicOpen _ _ rfl
        have h1 := I.map_ideal_basicOpen U f
        have h2 := K.map_ideal_basicOpen U f
        exact (map_colon_of_fg (Submonoid.powers f) (S := Γ(X, X.basicOpen f))
          (I.ideal U) (K.ideal U) (hK U)).trans (by rw [← h1, ← h2]; rfl) }
  have hG : G ≤ I.colon K := (le_colon_iff I G K).mpr fun _ => le_rfl
  exact hG U

theorem ideal_colon_of_isInvertible (hK : K.IsInvertible) (U : X.affineOpens) :
    (I.colon K).ideal U = (I.ideal U).colon (K.ideal U : Set Γ(X, U)) :=
  ideal_colon_of_fg I K (fun U => (hK.ideal K U).fg) U

/-! ### The power-torsion saturation -/

theorem colon_pow_le_saturate (i : ℕ) : I.colon (K ^ i) ≤ I.saturate K :=
  le_iSup (fun i => I.colon (K ^ i)) i

theorem le_saturate : I ≤ I.saturate K :=
  (le_colon_self I (K ^ 0)).trans (colon_pow_le_saturate I K 0)

theorem ideal_saturate (U : X.affineOpens) :
    (I.saturate K).ideal U = ⨆ i : ℕ, (I.colon (K ^ i)).ideal U := by
  simp only [saturate, ideal_iSup, iSup_apply]

theorem saturate_mono_left (h : I ≤ J) : I.saturate K ≤ J.saturate K :=
  iSup_mono fun i => colon_mono_left I J (K ^ i) h

/-- If `I` is `K`-saturated, `(I : K) = I`, then every colon `(I : K^i)` is `I` and the saturation
is `I` itself. -/
theorem saturate_eq_self_of_colon_eq (h : I.colon K = I) : I.saturate K = I := by
  have hpow : ∀ i : ℕ, I.colon (K ^ i) = I := by
    intro i
    induction i with
    | zero => rw [pow_zero]; exact colon_top I
    | succ n ih => rw [pow_succ, ← colon_colon, ih, h]
  rw [saturate]
  exact le_antisymm (iSup_le fun i => (hpow i).le) (le_saturate I K)

theorem isInvertible_pow {E : X.IdealSheafData} (hE : E.IsInvertible) (c : ℕ) :
    (E ^ c).IsInvertible := by
  induction c with
  | zero => rw [pow_zero]; exact isInvertible_top
  | succ n ih => rw [pow_succ]; exact ih.mul hE

/-- The colon formula on a chart [Hau14, Definition 6.2]: for an invertible `K` generated on the
affine open `U` by `e`, the saturation has sections `⋃ᵢ (I(U) : eⁱ)`. -/
theorem ideal_saturate_of_isInvertible {K : X.IdealSheafData} (hK : K.IsInvertible)
    (U : X.affineOpens) (e : Γ(X, U)) (he : K.ideal U = Ideal.span {e}) :
    (I.saturate K).ideal U = ⨆ i : ℕ, (I.ideal U).colon {e ^ i} := by
  rw [ideal_saturate]
  refine iSup_congr fun i => ?_
  rw [ideal_colon_of_isInvertible I (K ^ i) (isInvertible_pow hK i), ideal_pow, Pi.pow_apply, he,
    Ideal.span_singleton_pow, Ideal.colon_span]

/-! ### Division by an invertible power -/

theorem pow_mul_colon_of_dvd (E : X.IdealSheafData) (c : ℕ) (h : E ^ c ∣ I) :
    E ^ c * I.colon (E ^ c) = I := by
  refine le_antisymm ((mul_comm _ _).le.trans (colon_mul_le I (E ^ c))) ?_
  obtain ⟨L, hL⟩ := h
  have hle : L ≤ I.colon (E ^ c) :=
    (le_colon_iff_mul_le I L (E ^ c)).mpr (by rw [mul_comm]; exact hL.ge)
  calc I = E ^ c * L := hL
    _ ≤ E ^ c * I.colon (E ^ c) := fun U => Ideal.mul_mono_right (hle U)

/-- For invertible `E`, the quotient of `I` by `E ^ c` is unique: `E ^ c * K = I → K = (I : E ^ c)`.
-/
theorem colon_pow_eq_of_mul_eq {E : X.IdealSheafData} (hE : E.IsInvertible) (c : ℕ)
    (K : X.IdealSheafData) (h : E ^ c * K = I) : I.colon (E ^ c) = K := by
  refine le_antisymm ?_ ((le_colon_iff_mul_le I K (E ^ c)).mpr (by rw [mul_comm]; exact h.le))
  have hEc := isInvertible_pow hE c
  choose U hxU e he hEe using hEc
  refine le_of_iSup_eq_top (I := I.colon (E ^ c)) (J := K) U ?_ fun x => ?_
  · refine top_le_iff.mp fun y _ => ?_
    exact TopologicalSpace.Opens.mem_iSup.mpr ⟨y, hxU y⟩
  · intro u hu
    have hu' := ideal_colon_le I (E ^ c) (U x) hu
    rw [hEe x] at hu'
    have hue : u * e x ∈ I.ideal (U x) := by
      simpa using Submodule.mem_colon.mp hu' (e x) (Ideal.mem_span_singleton_self _)
    have hI : I.ideal (U x) = Ideal.span {e x} * K.ideal (U x) := by
      rw [← h, ideal_mul, Pi.mul_apply, hEe x]
    rw [hI] at hue
    obtain ⟨z, hz, hez⟩ := Ideal.mem_span_singleton_mul.mp hue
    have hzu : e x * z = e x * u := by rw [hez, mul_comm]
    exact (mul_cancel_left_mem_nonZeroDivisors (he x)).mp hzu ▸ hz

/-! ### The support of the saturation -/

/-- A point `fromSpec q` of the affine open `U` lies in the zero locus of `s ⊆ Γ(X, U)` iff
`s ⊆ q`. -/
theorem fromSpec_mem_zeroLocus_iff {U : X.Opens} (hU : IsAffineOpen U)
    (q : PrimeSpectrum Γ(X, U)) (s : Set Γ(X, U)) :
    hU.fromSpec q ∈ X.zeroLocus (U := U) s ↔ s ⊆ q.asIdeal := by
  rw [mem_zeroLocus_iff]
  refine forall₂_congr fun f _ => ?_
  rw [fromSpec_mem_basicOpen_iff hU q f, not_not]
  exact Iff.rfl

/-- For `x` in the affine open `U` with prime `𝔭 = primeIdealOf x`, `x` lies in the zero locus of
`s ⊆ Γ(X, U)` iff `s ⊆ 𝔭`. -/
theorem mem_zeroLocus_iff_le_primeIdealOf (U : X.affineOpens) {x : X} (hx : x ∈ U.1)
    (s : Set Γ(X, U)) :
    x ∈ X.zeroLocus (U := U.1) s ↔ s ⊆ ((U.2 : IsAffineOpen U.1).primeIdealOf ⟨x, hx⟩).asIdeal := by
  have hU : IsAffineOpen U.1 := U.2
  have hx' : x ∈ X.zeroLocus (U := U.1) s ↔
      hU.fromSpec (hU.primeIdealOf ⟨x, hx⟩) ∈ X.zeroLocus (U := U.1) s := by
    rw [IsAffineOpen.fromSpec_primeIdealOf]
  rw [hx', fromSpec_mem_zeroLocus_iff hU]

theorem colon_pow_mono (I K : X.IdealSheafData) : Monotone fun i : ℕ => I.colon (K ^ i) :=
  fun _ _ h => colon_anti_right I fun _ => Ideal.pow_le_pow_right h

/-- On a locally Noetherian scheme the underlying set of `V((I : K^∞))` is the closure of
`V(I) ∖ V(K)`: the strict transform is the closure of the part off the exceptional divisor
[Hau14, Definition 6.2]; [Sta, Tag 080D]. -/
theorem coe_support_saturate [IsLocallyNoetherian X] (I K : X.IdealSheafData) :
    ((I.saturate K).support : Set X) = closure ((I.support : Set X) \ (K.support : Set X)) := by
  have hfg : ∀ U : X.affineOpens, (K.ideal U).FG := fun U =>
    (isNoetherianRing_iff_ideal_fg _).mp (IsLocallyNoetherian.component_noetherian U) _
  apply le_antisymm
  · -- a point of `V((I : K^∞))` lies in the closure: otherwise an affine neighbourhood `V` has
    -- `V(I) ∩ V ⊆ V(K)`, so `K(V) ≤ √I(V)`, `K(V)^n ≤ I(V)` by finite generation, and
    -- `1 ∈ (I(V) : K(V)^n) ⊆ (I : K^∞)(V)`, contradicting `x ∈ V((I : K^∞))`.
    intro x hx
    by_contra hcl
    simp only [mem_closure_iff, not_forall, Set.not_nonempty_iff_eq_empty] at hcl
    obtain ⟨W, hWo, hxW, hW⟩ := hcl
    obtain ⟨_, ⟨U, hU, rfl⟩, hxU, hUW⟩ :=
      X.isBasis_affineOpens.exists_subset_of_mem_open hxW hWo
    let V : X.affineOpens := ⟨U, hU⟩
    have hV : IsAffineOpen V.1 := hU
    have hxV : x ∈ V.1 := hxU
    -- every point of `V` in `V(I)` lies in `V(K)`
    have hVIK : ∀ y ∈ V.1, y ∈ I.support → y ∈ K.support := by
      intro y hyV hyI
      by_contra hyK
      have : y ∈ W ∩ ((I.support : Set X) \ (K.support : Set X)) := ⟨hUW hyV, hyI, hyK⟩
      rw [hW] at this
      exact (Set.mem_empty_iff_false y).mp this
    -- hence `K(V) ≤ √I(V)`: every prime of `Γ(V)` containing `I(V)` contains `K(V)`
    have hrad : K.ideal V ≤ (I.ideal V).radical := by
      rw [Ideal.radical_eq_sInf]
      refine le_sInf fun q ⟨hIq, hq⟩ => ?_
      let q' : PrimeSpectrum Γ(X, V) := ⟨q, hq⟩
      have hyV : hV.fromSpec q' ∈ V.1 := by
        have : q' ∈ hV.fromSpec ⁻¹ᵁ V.1 := by rw [hV.fromSpec_preimage_self]; trivial
        exact this
      have hyI : hV.fromSpec q' ∈ I.support := by
        rw [mem_support_iff_of_mem hyV, fromSpec_mem_zeroLocus_iff hV]
        exact hIq
      have hyK := hVIK _ hyV hyI
      rw [mem_support_iff_of_mem hyV, fromSpec_mem_zeroLocus_iff hV] at hyK
      exact hyK
    obtain ⟨n, hn⟩ := Ideal.exists_pow_le_of_le_radical_of_fg hrad (hfg V)
    have hone : (1 : Γ(X, V)) ∈ (I.saturate K).ideal V := by
      refine colon_pow_le_saturate I K n V ?_
      rw [ideal_colon_of_fg I (K ^ n) (fun U => ?_) V]
      · exact Submodule.mem_colon.mpr fun k hk => by simpa using hn hk
      · rw [ideal_pow, Pi.pow_apply]
        exact (hfg U).pow
    have hx' := (mem_support_iff_of_mem hxV).mp hx
    rw [mem_zeroLocus_iff_le_primeIdealOf V hxV] at hx'
    exact (hV.primeIdealOf ⟨x, hxV⟩).isPrime.ne_top ((Ideal.eq_top_iff_one _).mpr (hx' hone))
  · -- the support is closed and contains `V(I) ∖ V(K)`: at such a point the prime `𝔭` contains
    -- `I(U)` but not `K(U)`, and `z K(U)^i ⊆ I(U) ⊆ 𝔭` forces `z ∈ 𝔭`.
    refine closure_minimal ?_ (I.saturate K).support.isClosed'
    rintro x ⟨hxI, hxK⟩
    obtain ⟨U, hxU⟩ := exists_affineOpens_mem x
    rw [SetLike.mem_coe] at hxI hxK ⊢
    rw [mem_support_iff_of_mem hxU, mem_zeroLocus_iff_le_primeIdealOf U hxU] at hxI hxK ⊢
    obtain ⟨k, hkK, hkp⟩ := Set.not_subset.mp hxK
    intro z hz
    rw [SetLike.mem_coe, ideal_saturate] at hz
    have hdir : Directed (· ≤ ·) fun i : ℕ => (I.colon (K ^ i)).ideal U :=
      (show Monotone (fun i : ℕ => (I.colon (K ^ i)).ideal U) from
        fun _ _ h => colon_pow_mono I K h U).directed_le
    obtain ⟨i, hi⟩ := (Submodule.mem_iSup_of_directed _ hdir).mp hz
    have hi' := ideal_colon_le I (K ^ i) U hi
    have hk : k ^ i ∈ (K ^ i).ideal U := by
      rw [ideal_pow, Pi.pow_apply]
      exact Ideal.pow_mem_pow hkK i
    have hzk : z * k ^ i ∈ I.ideal U := by simpa using Submodule.mem_colon.mp hi' _ hk
    rcases (U.2 : IsAffineOpen U.1).primeIdealOf ⟨x, hxU⟩ |>.isPrime.mem_or_mem (hxI hzk) with
      hz' | hk'
    · exact hz'
    · exact absurd (((U.2 : IsAffineOpen U.1).primeIdealOf ⟨x, hxU⟩).isPrime.mem_of_pow_mem i hk')
        hkp

end AlgebraicGeometry.Scheme.IdealSheafData

/-! ### Transforms along a morphism with a distinguished divisor -/

namespace AlgebraicGeometry

open Scheme.IdealSheafData

section Along

variable {B X : Scheme.{u}}

variable (π : B ⟶ X) (E : B.IdealSheafData) (J : X.IdealSheafData)

theorem controlledTransformAlong_zero : J.controlledTransformAlong π E 0 = J.comap π := by
  simp [controlledTransformAlong, Scheme.IdealSheafData.colon_top]

theorem comap_le_controlledTransformAlong (c : ℕ) :
    J.comap π ≤ J.controlledTransformAlong π E c :=
  Scheme.IdealSheafData.le_colon_self _ _

theorem controlledTransformAlong_le_strictTransformAlong (c : ℕ) :
    J.controlledTransformAlong π E c ≤ J.strictTransformAlong π E :=
  Scheme.IdealSheafData.colon_pow_le_saturate _ _ c

theorem controlledTransformAlong_mono {c d : ℕ} (h : c ≤ d) :
    J.controlledTransformAlong π E c ≤ J.controlledTransformAlong π E d :=
  Scheme.IdealSheafData.colon_anti_right _ fun _ => Ideal.pow_le_pow_right h

/-- The chart formula for the controlled transform [Kol07, Definition 60, (60.2)–(60.3)]: on an
affine open `U'` of `B` over an affine open `U` of `X` on which the invertible divisor `E` is
generated by the pullback of `a ∈ Γ(X, U)`, the controlled transform with control `m` has
sections `(J(U)·Γ(U') : (π♯a)ᵐ)` (the total transform's sections are `J(U)·Γ(U')`,
`ideal_comap_of_le`). -/
theorem ideal_controlledTransformAlong_of_appLE (hE : E.IsInvertible) (U : X.affineOpens)
    (U' : B.affineOpens) (e : U'.1 ≤ π ⁻¹ᵁ U.1) (a : Γ(X, U))
    (ha : E.ideal U' = Ideal.span {π.appLE U.1 U'.1 e a}) (m : ℕ) :
    (J.controlledTransformAlong π E m).ideal U' =
      ((J.ideal U).map (π.appLE U.1 U'.1 e).hom).colon {π.appLE U.1 U'.1 e a ^ m} := by
  rw [controlledTransformAlong,
    Scheme.IdealSheafData.ideal_colon_of_isInvertible _ _
      (Scheme.IdealSheafData.isInvertible_pow hE m),
    Scheme.IdealSheafData.ideal_pow, Pi.pow_apply, ha, Ideal.span_singleton_pow,
    Ideal.colon_span, Scheme.IdealSheafData.ideal_comap_of_le J π U U' e]

end Along

/-! ### The marked transform under a blow-up -/

section Marked

variable {X : Scheme.{u}}

/-- Kollár's birational transform of the marked ideal `(J, m)` under the blow-up with centre `D`,
`π_*^{-1}(J, m) = (𝒪(mF) · π^* J, m)` [Kol07, Definition 60, (60.1)]: the controlled transform
of `J` with control `m` along `D.blowUpπ` with respect to the exceptional divisor
`F = D.exceptionalDivisor`. Kollár defines it for `m ≤ ord_D J`; the colon ideal
`(π^* J : F^m)` is defined for every `J` and `m`, and satisfies `F^m · π_*^{-1}(J, m) = π^* J`
exactly when `F^m` divides `π^* J`. The mark `m` is carried alongside the ideal
(`MarkedTriple`). -/
noncomputable abbrev Scheme.IdealSheafData.markedTransform (J D : X.IdealSheafData) (m : ℕ) :
    D.blowUp.IdealSheafData :=
  J.controlledTransformAlong D.blowUpπ D.exceptionalDivisor m

end Marked

end AlgebraicGeometry
