/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineAlgebra

/-!
# Chart transitions of the affine blow-up algebras

For `a, b ∈ I` the localizations `R[I/a]_{b/a}` and `R[I/b]_{a/b}` are canonically isomorphic
`R`-algebras: both are the subring of `R_{ab}` generated by `I/a`, `I/b`, `a/b`, `b/a`.  This is
the gluing of the charts of the blow-up along the inclusions `R_{gⱼ}, R_{gₗ} ⊆ R_{gⱼgₗ}`
[Hau14, Definition 4.13], the identity `D₊(f) ∩ D₊(g) = D₊(fg)` for `Proj`.

## Main declarations

* `AlgebraicGeometry.awayToAwayₐ x c h : Localization.Away x →ₐ[R] Localization.Away c` for `x ∣ c`.
* `affineBlowUpAlgebra.toAway I hac : R[I/a] →ₐ[R] Localization.Away c` for `a ∣ c`.
* `affineBlowUpAlgebra.embed I hac s hs : Localization.Away s →ₐ[R] Localization.Away c` for an
  element `s` of `R[I/a]` whose image in `R_c` is a unit; `embed_injective` when
  `c = s · aᵐ` in `R[I/a]`.
* `affineBlowUpAlgebra.transitionEquiv I ha hb : R[I/a]_{b/a} ≃ₐ[R] R[I/b]_{a/b}` with
  `transitionEquiv_spec`, `transitionEquiv_unique`, and `embedAB_injective`,
  `range_embedAB_eq` for the "subring of `R_{ab}`" statement.

## The argument

The unlocalized map `R[I/a] → R_{ab}` need not be injective when `b` is a zero divisor, so all
identities are proved *after* localizing at `b/a`.  The map `R[I/a]_{b/a} → R_{ab}` is injective:
if `w/(b/a)ᵐ ↦ 0` then `w ↦ 0` in `R_{ab}`; writing `w = r/aⁿ` in `R_a`, `(ab)ᵏ r = 0` in `R`, so
`bᵏ w = 0` in `R_a`, hence in `R[I/a]`; since `b = (b/a)·a` with `b/a` a unit of the localization
and `a` a nonzerodivisor of `R[I/a]` (`affineBlowUpAlgebra.algebraMap_mem_nonZeroDivisors`),
`w = 0` there.  The two images coincide: each is the `R`-subalgebra of `R_{ab}` generated by the
`x/a`, the `x/b` and `a/b`, `b/a` (the inverse of `b/a` is `a/b`, an element of the other chart).
The transition is the composite of the two embeddings through their common image.  Uniqueness:
an `R`-algebra map out of `R[I/a]_{b/a}` is determined by its values on `R[I/a]`, hence on the
generators `x/a`, and the value at `x/a` is pinned by `e(x/a)·(a/b) = x/b` since `a/b` is a unit.

## Conventions

The target `R_c` is kept general (`a ∣ c`): `c = ab` for the pairwise transition and `c = abc'`
for the triple one, so that both sides of a transition land in the same ring.  Fractions are
handled through multiplicative identities in `R_c`, never through inverses.

## Boundary cases

`b = a`: the transition is the identity of `R[I/a]_{1}` up to the identification `1 = a/a`.
Zero divisors among `a`, `b` are allowed.  If `ab = 0` then `R_{ab} = 0` and both localizations
are the zero ring, consistently.
-/

@[expose] public section

universe u

namespace AlgebraicGeometry

open IsLocalization.Away

variable {R : Type u} [CommRing R]

/-- The map `R_x → R_c` for `x ∣ c`, as an `R`-algebra map. -/
noncomputable def awayToAwayₐ (x c : R) (h : x ∣ c) :
    Localization.Away x →ₐ[R] Localization.Away c :=
  IsLocalization.Away.liftAlgHom x (f := Algebra.ofId R (Localization.Away c))
    (by rw [Algebra.ofId_apply]; exact IsLocalization.Away.isUnit_of_dvd c h)

theorem awayToAwayₐ_algebraMap (x c : R) (h : x ∣ c) (r : R) :
    awayToAwayₐ x c h (algebraMap R (Localization.Away x) r) =
      algebraMap R (Localization.Away c) r := by
  rw [awayToAwayₐ, IsLocalization.Away.liftAlgHom_apply, IsLocalization.Away.lift_eq]
  rfl

namespace affineBlowUpAlgebra

variable (I : Ideal R) {a c : R} (hac : a ∣ c)

/-- The natural map `R[I/a] ⊆ R_a → R_c` for `a ∣ c`. -/
noncomputable def toAway : affineBlowUpAlgebra I a →ₐ[R] Localization.Away c :=
  (awayToAwayₐ a c hac).comp (affineBlowUpAlgebra I a).val

theorem toAway_algebraMap (r : R) :
    toAway I hac (algebraMap R (affineBlowUpAlgebra I a) r) =
      algebraMap R (Localization.Away c) r := by
  rw [toAway, AlgHom.comp_apply, Subalgebra.coe_val, Subalgebra.coe_algebraMap,
    awayToAwayₐ_algebraMap]

theorem toAway_frac_mul {x : R} (hx : x ∈ I) :
    toAway I hac (frac hx) * algebraMap R (Localization.Away c) a =
      algebraMap R (Localization.Away c) x := by
  rw [toAway, AlgHom.comp_apply, Subalgebra.coe_val, coe_frac, ← awayToAwayₐ_algebraMap a c hac a,
    ← map_mul, mul_assoc, mul_comm (invSelf a), mul_invSelf, mul_one, awayToAwayₐ_algebraMap]

theorem isUnit_algebraMap_of_dvd {x : R} (hxc : x ∣ c) :
    IsUnit (algebraMap R (Localization.Away c) x) :=
  IsLocalization.Away.isUnit_of_dvd c hxc

/-- For `x ∈ I` with `x ∣ c`, the image of `x/a` in `R_c` is a unit. -/
theorem isUnit_toAway_frac {x : R} (hx : x ∈ I) (hxc : x ∣ c) : IsUnit (toAway I hac (frac hx)) :=
  isUnit_of_mul_isUnit_left ((toAway_frac_mul I hac hx).symm ▸ isUnit_algebraMap_of_dvd hxc)

variable (s : affineBlowUpAlgebra I a) (hs : IsUnit (toAway I hac s))

/-- The embedding `R[I/a]_s → R_c` extending `R[I/a] → R_c`, for `s` with unit image. -/
noncomputable def embed : Localization.Away s →ₐ[R] Localization.Away c :=
  IsLocalization.Away.liftAlgHom s (f := toAway I hac) hs

theorem embed_algebraMap (z : affineBlowUpAlgebra I a) :
    embed I hac s hs (algebraMap _ _ z) = toAway I hac z := by
  rw [embed, IsLocalization.Away.liftAlgHom_apply, IsLocalization.Away.lift_eq]
  rfl

/-- `R[I/a]_s → R_c` is injective when `c = s · aᵐ` in `R[I/a]`: an element `w/sᵐ` mapping to zero
has `w ↦ 0` in `R_c`, so `cᵏ w = 0` in `R[I/a]`; `s` is a unit of the localization and `a` a
nonzerodivisor, so `w = 0` there. -/
theorem embed_injective {m : ℕ} (hcs : algebraMap R (affineBlowUpAlgebra I a) c =
    s * algebraMap R (affineBlowUpAlgebra I a) a ^ m) : Function.Injective (embed I hac s hs) := by
  rw [injective_iff_map_eq_zero]
  intro z hz
  obtain ⟨k, w, hw⟩ := IsLocalization.Away.surj (S := Localization.Away s) s z
  -- `w ↦ 0` in `R_c`
  have hw0 : toAway I hac w = 0 := by
    rw [← embed_algebraMap I hac s hs, ← hw, map_mul, hz, zero_mul]
  -- write `w = r/aⁿ` in `R_a`; then `r ↦ 0` in `R_c`, so `cʲ r = 0` in `R`
  obtain ⟨n, r, hr⟩ :=
    IsLocalization.Away.surj (S := Localization.Away a) a (w : Localization.Away a)
  have hr' : algebraMap R (affineBlowUpAlgebra I a) r =
      algebraMap R (affineBlowUpAlgebra I a) (a ^ n) * w :=
    Subtype.ext (by
      rw [Subalgebra.coe_mul, Subalgebra.coe_algebraMap, Subalgebra.coe_algebraMap, map_pow,
        mul_comm]
      exact hr.symm)
  have hr0 : algebraMap R (Localization.Away c) r = 0 := by
    rw [← toAway_algebraMap I hac, hr', map_mul, hw0, mul_zero]
  obtain ⟨⟨_, j, rfl⟩, hj⟩ := (IsLocalization.map_eq_zero_iff (Submonoid.powers c) _ r).mp hr0
  have hj' : c ^ j * r = 0 := hj
  -- hence `cʲ w = 0` in `R[I/a]`, as `aⁿ (cʲ w) = cʲ r = 0` and `a` is a nonzerodivisor
  have hcw : algebraMap R (affineBlowUpAlgebra I a) (c ^ j) * w = 0 := by
    have h1 : algebraMap R (affineBlowUpAlgebra I a) (a ^ n) *
        (algebraMap R (affineBlowUpAlgebra I a) (c ^ j) * w) = 0 := by
      rw [mul_left_comm, ← hr', ← map_mul, hj', map_zero]
    rw [map_pow] at h1
    exact (mem_nonZeroDivisors_iff.mp
      (pow_mem (algebraMap_mem_nonZeroDivisors (I := I) (a := a)) n)).1 _ h1
  -- in the localization, `s` is a unit and `a` a nonzerodivisor, so `w = 0` there
  have hz0 : algebraMap (affineBlowUpAlgebra I a) (Localization.Away s) w = 0 := by
    have h2 := congrArg (algebraMap (affineBlowUpAlgebra I a) (Localization.Away s)) hcw
    rw [map_mul, map_zero, map_pow, hcs, mul_pow, map_mul, mul_assoc, map_pow, map_pow, map_pow,
      ← pow_mul] at h2
    have hsu : IsUnit (algebraMap (affineBlowUpAlgebra I a) (Localization.Away s) s ^ j) :=
      (IsLocalization.Away.algebraMap_isUnit s).pow j
    have h3 := hsu.mul_right_eq_zero.mp h2
    have hanz : algebraMap (affineBlowUpAlgebra I a) (Localization.Away s)
        (algebraMap R (affineBlowUpAlgebra I a) a) ∈ nonZeroDivisors (Localization.Away s) :=
      IsLocalization.nonZeroDivisors_le_comap (Submonoid.powers s) _
        (algebraMap_mem_nonZeroDivisors (I := I) (a := a))
    exact (mem_nonZeroDivisors_iff.mp (pow_mem hanz (m * j))).1 _ h3
  have hu : IsUnit (algebraMap (affineBlowUpAlgebra I a) (Localization.Away s) s ^ k) :=
    (IsLocalization.Away.algebraMap_isUnit s).pow k
  rw [← hu.mul_left_eq_zero, hw, hz0]

theorem frac_mul_algebraMap {x : R} (hx : x ∈ I) :
    frac (a := a) hx * algebraMap R (affineBlowUpAlgebra I a) a =
      algebraMap R (affineBlowUpAlgebra I a) x := by
  apply Subtype.ext
  rw [Subalgebra.coe_mul, coe_frac, Subalgebra.coe_algebraMap, Subalgebra.coe_algebraMap,
    mul_assoc, mul_comm (invSelf a), mul_invSelf, mul_one]

theorem toAway_mem_of_frac_mem (T : Subalgebra R (Localization.Away c))
    (hT : ∀ x (hx : x ∈ I), toAway I hac (frac hx) ∈ T) (w : affineBlowUpAlgebra I a) :
    toAway I hac w ∈ T := by
  have hle : (affineBlowUpAlgebra I a).map (awayToAwayₐ a c hac) ≤ T := by
    rw [affineBlowUpAlgebra_eq_adjoin, AlgHom.map_adjoin, Algebra.adjoin_le_iff]
    rintro _ ⟨_, ⟨x, hx, rfl⟩, rfl⟩
    exact hT x hx
  exact hle ⟨w, w.2, rfl⟩

/-- A subalgebra of `R_c` containing the images of the `x/a` and an inverse of the image of `s`
contains the image of `R[I/a]_s`. -/
theorem range_embed_le_of (T : Subalgebra R (Localization.Away c))
    (hT : ∀ x (hx : x ∈ I), toAway I hac (frac hx) ∈ T)
    (hsT : ∃ t ∈ T, t * toAway I hac s = 1) : (embed I hac s hs).range ≤ T := by
  obtain ⟨t, htT, ht⟩ := hsT
  rintro _ ⟨z, rfl⟩
  obtain ⟨k, w, hw⟩ := IsLocalization.Away.surj (S := Localization.Away s) s z
  have h1 : embed I hac s hs z * toAway I hac s ^ k = toAway I hac w := by
    rw [← embed_algebraMap I hac s hs w, ← hw, map_mul, map_pow, embed_algebraMap]
  have h3 : (toAway I hac s * t) ^ k = 1 := by rw [mul_comm, ht, one_pow]
  have h2 : embed I hac s hs z = toAway I hac w * t ^ k := by
    calc embed I hac s hs z = embed I hac s hs z * (toAway I hac s * t) ^ k := by
          rw [h3, mul_one]
      _ = embed I hac s hs z * toAway I hac s ^ k * t ^ k := by rw [mul_pow, mul_assoc]
      _ = toAway I hac w * t ^ k := by rw [h1]
  change embed I hac s hs z ∈ T
  rw [h2]
  exact mul_mem (toAway_mem_of_frac_mem I hac T hT w) (pow_mem htT k)

section Pairwise

variable {b : R} (ha : a ∈ I) (hb : b ∈ I) (hbc : b ∣ c)

/-- The image of `R[I/a]_{b/a}` in `R_c` lies in the image of `R[I/b]_{a/b}` (for `a ∣ c`,
`b ∣ c`): `x/a = (x/b)·(a/b)⁻¹` and `(b/a)⁻¹ = a/b`. -/
theorem range_embed_le :
    (embed I hac (frac (a := a) hb) (isUnit_toAway_frac I hac hb hbc)).range ≤
      (embed I hbc (frac (a := b) ha) (isUnit_toAway_frac I hbc ha hac)).range := by
  have hu : IsUnit (algebraMap R (Localization.Away c) a) := isUnit_algebraMap_of_dvd hac
  have hv : IsUnit (algebraMap R (Localization.Away c) b) := isUnit_algebraMap_of_dvd hbc
  have hWv : toAway I hbc (frac (a := b) ha) * algebraMap R (Localization.Away c) b =
      algebraMap R (Localization.Away c) a := toAway_frac_mul I hbc ha
  have hQW : embed I hbc (frac (a := b) ha) (isUnit_toAway_frac I hbc ha hac)
      (invSelf (frac (a := b) ha)) * toAway I hbc (frac (a := b) ha) = 1 := by
    rw [← embed_algebraMap I hbc (frac (a := b) ha) (isUnit_toAway_frac I hbc ha hac), ← map_mul,
      mul_comm, mul_invSelf, map_one]
  refine range_embed_le_of I hac _ _ _ (fun x hx => ?_)
    ⟨toAway I hbc (frac (a := b) ha), ⟨algebraMap _ _ (frac (a := b) ha),
      embed_algebraMap I hbc (frac (a := b) ha) (isUnit_toAway_frac I hbc ha hac) _⟩, ?_⟩
  · -- `x/a = (x/b) · (a/b)⁻¹`
    refine ⟨algebraMap _ _ (frac (a := b) hx) * invSelf (frac (a := b) ha), ?_⟩
    change embed I hbc (frac (a := b) ha) (isUnit_toAway_frac I hbc ha hac)
      (algebraMap _ _ (frac (a := b) hx) * invSelf (frac (a := b) ha)) = toAway I hac (frac hx)
    rw [map_mul, embed_algebraMap]
    apply hu.mul_left_injective
    change toAway I hbc (frac hx) * _ * algebraMap R (Localization.Away c) a =
      toAway I hac (frac hx) * algebraMap R (Localization.Away c) a
    rw [toAway_frac_mul I hac hx, ← hWv, mul_assoc,
      ← mul_assoc (embed I hbc (frac (a := b) ha) (isUnit_toAway_frac I hbc ha hac) _), hQW,
      one_mul, toAway_frac_mul]
  · -- `(a/b) · (b/a) = 1`
    apply (hu.mul hv).mul_left_injective
    change toAway I hbc (frac ha) * toAway I hac (frac hb) * (algebraMap R (Localization.Away c) a *
      algebraMap R (Localization.Away c) b) = 1 * _
    rw [one_mul, mul_comm (algebraMap R (Localization.Away c) a), mul_mul_mul_comm, hWv,
      toAway_frac_mul, mul_comm]

/-- The images of `R[I/a]_{b/a}` and `R[I/b]_{a/b}` in `R_c` coincide. -/
theorem range_embed_eq :
    (embed I hac (frac (a := a) hb) (isUnit_toAway_frac I hac hb hbc)).range =
      (embed I hbc (frac (a := b) ha) (isUnit_toAway_frac I hbc ha hac)).range :=
  le_antisymm (range_embed_le I hac ha hb hbc) (range_embed_le I hbc hb ha hac)

end Pairwise

section Transition

variable {b : R} (ha : a ∈ I) (hb : b ∈ I)

theorem algebraMap_mul_eq_frac_mul_sq :
    algebraMap R (affineBlowUpAlgebra I a) (a * b) =
      frac (a := a) hb * algebraMap R (affineBlowUpAlgebra I a) a ^ 2 := by
  rw [pow_two, ← mul_assoc, frac_mul_algebraMap, map_mul, mul_comm]

/-- The embedding `R[I/a]_{b/a} → R_{ab}`. -/
noncomputable def embedAB (a : R) :
    Localization.Away (frac (a := a) hb) →ₐ[R] Localization.Away (a * b) :=
  embed I (dvd_mul_right a b) (frac (a := a) hb)
    (isUnit_toAway_frac I (dvd_mul_right a b) hb (dvd_mul_left b a))

/-- The embedding `R[I/b]_{a/b} → R_{ab}`. -/
noncomputable def embedBA (b : R) :
    Localization.Away (frac (a := b) ha) →ₐ[R] Localization.Away (a * b) :=
  embed I (dvd_mul_left b a) (frac (a := b) ha)
    (isUnit_toAway_frac I (dvd_mul_left b a) ha (dvd_mul_right a b))

theorem embedAB_algebraMap (z : affineBlowUpAlgebra I a) :
    embedAB I hb a (algebraMap _ _ z) = toAway I (dvd_mul_right a b) z :=
  embed_algebraMap _ _ _ _ z

theorem embedBA_algebraMap (z : affineBlowUpAlgebra I b) :
    embedBA I ha b (algebraMap _ _ z) = toAway I (dvd_mul_left b a) z :=
  embed_algebraMap _ _ _ _ z

/-- `R[I/a]_{b/a} → R_{ab}` is injective: `R[I/a]_{b/a}` is a subring of `R_{ab}`. -/
theorem embedAB_injective : Function.Injective (embedAB I hb a) :=
  embed_injective I (dvd_mul_right a b) _ _ (algebraMap_mul_eq_frac_mul_sq I hb)

theorem embedBA_injective : Function.Injective (embedBA I ha b) := by
  have h : algebraMap R (affineBlowUpAlgebra I b) (a * b) =
      frac (a := b) ha * algebraMap R (affineBlowUpAlgebra I b) b ^ 2 := by
    rw [mul_comm a b]; exact algebraMap_mul_eq_frac_mul_sq I ha
  exact embed_injective I (dvd_mul_left b a) _ _ h

theorem range_embedAB_eq : (embedAB I hb a).range = (embedBA I ha b).range :=
  range_embed_eq I (dvd_mul_right a b) ha hb (dvd_mul_left b a)

/-- The transition isomorphism `R[I/a]_{b/a} ≃ R[I/b]_{a/b}` [Hau14, Definition 4.13]: the
composite of the two embeddings into `R_{ab}` through their common image. -/
noncomputable def transitionEquiv :
    Localization.Away (frac (a := a) hb) ≃ₐ[R] Localization.Away (frac (a := b) ha) :=
  (AlgEquiv.ofInjective (embedAB I hb a) (embedAB_injective I hb)).trans
    ((Subalgebra.equivOfEq (embedAB I hb a).range (embedBA I ha b).range
      (range_embedAB_eq I ha hb)).trans
      (AlgEquiv.ofInjective (embedBA I ha b) (embedBA_injective I ha)).symm)

theorem embedBA_transitionEquiv (z : Localization.Away (frac (a := a) hb)) :
    embedBA I ha b (transitionEquiv I ha hb z) = embedAB I hb a z := by
  rw [transitionEquiv, AlgEquiv.trans_apply, AlgEquiv.trans_apply,
    ← AlgEquiv.ofInjective_apply (embedBA I ha b) (embedBA_injective I ha),
    AlgEquiv.apply_symm_apply, Subalgebra.equivOfEq_apply, AlgEquiv.ofInjective_apply]

/-- The transition sends `x/a` to `(x/b)·(a/b)⁻¹`, i.e. `e(x/a) · (a/b) = x/b`. -/
theorem transitionEquiv_spec {x : R} (hx : x ∈ I) :
    transitionEquiv I ha hb (algebraMap _ _ (frac (a := a) hx)) *
        algebraMap _ _ (frac (a := b) ha) =
      algebraMap _ _ (frac (a := b) hx) := by
  apply embedBA_injective I ha
  have hv : IsUnit (algebraMap R (Localization.Away (a * b)) b) :=
    isUnit_algebraMap_of_dvd (dvd_mul_left b a)
  apply hv.mul_left_injective
  change embedBA I ha b (_ * _) * _ = embedBA I ha b _ * _
  rw [map_mul, embedBA_transitionEquiv, embedAB_algebraMap, embedBA_algebraMap,
    embedBA_algebraMap, mul_assoc, toAway_frac_mul I (dvd_mul_left b a) ha,
    toAway_frac_mul I (dvd_mul_right a b) hx, toAway_frac_mul I (dvd_mul_left b a) hx]

/-- The transition is the unique `R`-algebra isomorphism with `e(x/a) · (a/b) = x/b` for all
`x ∈ I`. -/
theorem transitionEquiv_unique
    (e : Localization.Away (frac (a := a) hb) ≃ₐ[R] Localization.Away (frac (a := b) ha))
    (he : ∀ x (hx : x ∈ I),
      e (algebraMap _ _ (frac (a := a) hx)) * algebraMap _ _ (frac (a := b) ha) =
        algebraMap _ _ (frac (a := b) hx)) : e = transitionEquiv I ha hb := by
  have hu : IsUnit (algebraMap (affineBlowUpAlgebra I b) (Localization.Away (frac (a := b) ha))
      (frac (a := b) ha)) := IsLocalization.Away.algebraMap_isUnit _
  have key : (e : Localization.Away (frac (a := a) hb) →ₐ[R] _).comp
      (IsScalarTower.toAlgHom R (affineBlowUpAlgebra I a) _) =
      (transitionEquiv I ha hb : Localization.Away (frac (a := a) hb) →ₐ[R] _).comp
        (IsScalarTower.toAlgHom R (affineBlowUpAlgebra I a) _) :=
    algHom_ext fun x hx => hu.mul_left_injective (by
      change e (algebraMap _ _ (frac hx)) * _ =
        transitionEquiv I ha hb (algebraMap _ _ (frac hx)) * _
      rw [he x hx, transitionEquiv_spec])
  have h2 : (e : Localization.Away (frac (a := a) hb) →ₐ[R] Localization.Away (frac (a := b) ha)) =
      (transitionEquiv I ha hb :
        Localization.Away (frac (a := a) hb) →ₐ[R] Localization.Away (frac (a := b) ha)) := by
    apply AlgHom.coe_ringHom_injective
    apply IsLocalization.ringHom_ext (Submonoid.powers (frac (a := a) hb))
    ext w
    exact AlgHom.congr_fun key w
  exact AlgEquiv.ext fun z => AlgHom.congr_fun h2 z

end Transition

end affineBlowUpAlgebra

end AlgebraicGeometry
