/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.IdealSheaf.Defs
public import Hironaka.Scheme.Smooth.EtaleCoordinatesDefs
import Hironaka.Scheme.BlowUp.Descent
import Hironaka.Scheme.IdealSheaf.StalkIdeal
import Hironaka.Scheme.Smooth.EtaleCoordinates
import Mathlib.RingTheory.RegularLocalRing.Defs

/-!
# Adaptedness of a chart: `Z ∩ U = g⁻¹(L)` from the stalk

Let `Z` be an ideal sheaf on `X`, `x ∈ X`, `v_0, …, v_{n-1}` sections of an affine open `V ∋ x`
with coordinate morphism `g = toAffineSpace f U v : U ⟶ 𝔸ⁿ_k`, and `L = V(t_0, …, t_{r-1}) ⊆ 𝔸ⁿ_k`
the coordinate subspace. The main theorem, `exists_comap_eq_comap_coordinateSubspace`, is the
local statement behind Kollár's "`Z = (z_{j_1} = ⋯ = z_{j_s} = 0)` in some open neighborhood of
`x`" [Kol07, Definition 24, (4)]: if the stalk `Z_x` is generated by the germs of `v_0, …, v_{r-1}`,
then on a basic open `U = D(s) ∋ x` of `V` the ideal sheaf `Z ∩ U` is the pullback `g⁻¹(L)`. Not
stated as such in the sources; the argument:

* `exists_mem_map_eq_map_of_localization`: two finitely generated ideals of `S` with the same
  localization at a prime `𝔭` agree after localizing away from one `s ∉ 𝔭` (each generator of one
  has a multiple in the other; take the product of the multipliers). Applied to `Z(V)` and
  `(v_0, …, v_{r-1})`, whose localizations at `x` agree by hypothesis (`Z_x = Z(V)·𝒪_{X,x}`), this
  gives `Z(U) = (v_0, …, v_{r-1}) Γ(U)` on `U = D(s)` (`Z(U) = Z(V) Γ(U)` is Mathlib's
  `IdealSheafData.map_ideal`).
* The two ideal sheaves on `U` are then compared stalk by stalk (`ext_stalkIdeal`): at `u ∈ U`
  both stalks are generated by the germs of the `v_i`, `i < r`; for `Z ∩ U` because `Z(U)` is, for
  `g⁻¹(L)` because the stalk of `L` at `g(u)` is generated by the `t_i` and `g^*(t_i) = v_i`
  (`toAffineSpace_appTop_X`).

This is the adaptedness clause of `EtaleCoordinatesAdapted` (`EtaleCoordinatesDefs.lean`), which
`Hironaka/Scheme/Smooth/EtaleCoordinatesAdapted.lean` establishes at the closed points of a smooth
center.
-/

public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory

universe u

section Ideals

variable {S T : Type u} [CommRing S] [CommRing T] [Algebra S T] (M : Submonoid S)
  [IsLocalization M T]

/-- If `a` lies in `Q` after localizing at `M`, some multiple `s * a`, `s ∈ M`, lies in `Q`. -/
theorem exists_mem_mul_mem_of_algebraMap_mem_map (Q : Ideal S) {a : S}
    (ha : algebraMap S T a ∈ Q.map (algebraMap S T)) : ∃ s ∈ M, s * a ∈ Q := by
  obtain ⟨⟨q, m⟩, h⟩ := (IsLocalization.mem_map_algebraMap_iff M T).mp ha
  rw [← map_mul, IsLocalization.eq_iff_exists M T] at h
  obtain ⟨c, hc⟩ := h
  refine ⟨c.1 * m.1, M.mul_mem c.2 m.2, ?_⟩
  rw [show c.1 * m.1 * a = c.1 * (a * m.1) by ring, hc]
  exact Q.mul_mem_left _ q.2

/-- Finitely generated ideals with the same localization at `M` agree after localizing away from
a single element `s ∈ M`. -/
theorem exists_mem_map_eq_map_of_localization (I Q : Ideal S) (hI : I.FG) (hQ : Q.FG)
    (h : I.map (algebraMap S T) = Q.map (algebraMap S T)) :
    ∃ s ∈ M, ∀ (S' : Type u) [CommRing S'] [Algebra S S'] [IsLocalization.Away s S'],
      I.map (algebraMap S S') = Q.map (algebraMap S S') := by
  classical
  obtain ⟨gI, hgI⟩ := hI
  obtain ⟨gQ, hgQ⟩ := hQ
  have keyI : ∀ a ∈ gI, ∃ s ∈ M, s * a ∈ Q := fun a ha =>
    exists_mem_mul_mem_of_algebraMap_mem_map M Q
      (h ▸ Ideal.mem_map_of_mem _ (hgI ▸ Ideal.subset_span ha))
  have keyQ : ∀ a ∈ gQ, ∃ s ∈ M, s * a ∈ I := fun a ha =>
    exists_mem_mul_mem_of_algebraMap_mem_map M I
      (h.symm ▸ Ideal.mem_map_of_mem _ (hgQ ▸ Ideal.subset_span ha))
  choose! sI hsI hsIQ using keyI
  choose! sQ hsQ hsQI using keyQ
  refine ⟨(∏ a ∈ gI, sI a) * ∏ a ∈ gQ, sQ a,
    M.mul_mem (M.prod_mem fun a ha => hsI a ha) (M.prod_mem fun a ha => hsQ a ha), ?_⟩
  intro S' _ _ _
  set s := (∏ a ∈ gI, sI a) * ∏ a ∈ gQ, sQ a with hsdef
  have hunit : IsUnit (algebraMap S S' s) := IsLocalization.Away.algebraMap_isUnit s
  have gen : ∀ (J : Ideal S) (a t : S), t ∣ s → t * a ∈ J →
      algebraMap S S' a ∈ J.map (algebraMap S S') := by
    intro J a t ht hta
    obtain ⟨u, hu⟩ := ht
    have hu' : IsUnit (algebraMap S S' t) :=
      isUnit_of_mul_isUnit_left (x := algebraMap S S' t) (y := algebraMap S S' u)
        (by rw [← map_mul, ← hu]; exact hunit)
    have : algebraMap S S' a = ↑hu'.unit⁻¹ * algebraMap S S' (t * a) := by
      rw [map_mul, ← mul_assoc, IsUnit.val_inv_mul, one_mul]
    rw [this]
    exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ hta)
  apply le_antisymm
  · rw [Ideal.map_le_iff_le_comap, ← hgI, Ideal.span_le]
    intro a ha
    exact gen Q a (sI a) (dvd_mul_of_dvd_left (Finset.dvd_prod_of_mem sI ha) _) (hsIQ a ha)
  · rw [Ideal.map_le_iff_le_comap, ← hgQ, Ideal.span_le]
    intro a ha
    exact gen I a (sQ a) (dvd_mul_of_dvd_right (Finset.dvd_prod_of_mem sQ ha) _) (hsQI a ha)

end Ideals

section Coordinates

variable {k : Type u} [Field k] {X : Scheme.{u}} (f : X ⟶ Spec (.of k)) {n : ℕ}

/-- The coordinate morphism pulls the coordinate function `t_i` of `𝔸ⁿ_k` back to `v i`. -/
theorem toAffineSpace_appTop_X (U : X.Opens) (v : Fin n → Γ(X, U)) (i : Fin n) :
    (toAffineSpace f U v).appTop
        ((Scheme.ΓSpecIso (.of (MvPolynomial (Fin n) k))).inv (MvPolynomial.X i)) =
      U.topIso.inv (v i) := by
  let _ := f.sectionsAlgebra U
  have h1 : ∀ a, (Spec.map (CommRingCat.ofHom (MvPolynomial.aeval (R := k) v).toRingHom)).appTop
      ((Scheme.ΓSpecIso (.of (MvPolynomial (Fin n) k))).inv a) =
      (Scheme.ΓSpecIso Γ(X, U)).inv (MvPolynomial.aeval v a) := by
    intro a
    rw [← CommRingCat.comp_apply, ← Scheme.ΓSpecIso_inv_naturality, CommRingCat.comp_apply]
    rfl
  have h2 : ∀ b, U.toSpecΓ.appTop ((Scheme.ΓSpecIso Γ(X, U)).inv b) = U.topIso.inv b := by
    intro b
    rw [Scheme.Opens.toSpecΓ_appTop, CommRingCat.comp_apply, Iso.inv_hom_id_apply]
  unfold toAffineSpace
  rw [Scheme.Hom.comp_appTop, CommRingCat.comp_apply, h1, h2, MvPolynomial.aeval_X]

/-- `toAffineSpace_appTop_X` with `app ⊤` in place of `appTop` (the form produced by
`Scheme.Hom.germ_stalkMap_apply`). -/
theorem toAffineSpace_app_top_X (U : X.Opens) (v : Fin n → Γ(X, U)) (i : Fin n) :
    (toAffineSpace f U v).app ⊤
        ((Scheme.ΓSpecIso (.of (MvPolynomial (Fin n) k))).inv (MvPolynomial.X i)) =
      U.topIso.inv (v i) :=
  toAffineSpace_appTop_X f U v i

omit f in
/-- The stalk of the coordinate subspace `L = V(t_0, …, t_{r-1})` at a point of `𝔸ⁿ_k` is generated
by the germs of `t_0, …, t_{r-1}`. -/
theorem stalkIdeal_coordinateSubspace (r : ℕ) (y : Spec (.of (MvPolynomial (Fin n) k))) :
    (coordinateSubspace k n r).stalkIdeal y =
      Ideal.span ((fun i : Fin n => (Spec (.of (MvPolynomial (Fin n) k))).presheaf.germ ⊤ y
        (TopologicalSpace.Opens.mem_top y)
        ((Scheme.ΓSpecIso (.of (MvPolynomial (Fin n) k))).inv (MvPolynomial.X i))) ''
          {i | i.val < r}) := by
  have hy : y ∈ (⊤ : (Spec (.of (MvPolynomial (Fin n) k))).Opens) :=
    TopologicalSpace.Opens.mem_top y
  rw [Scheme.IdealSheafData.stalkIdeal_eq_map_germ _ ⟨⊤, isAffineOpen_top _⟩ hy]
  have hid : (coordinateSubspace k n r).ideal ⟨⊤, isAffineOpen_top _⟩ =
      (affineBlowUpAlgebra.coordinateIdeal k {j : Fin n | j.val < r}).map
        ((Scheme.ΓSpecIso (.of (MvPolynomial (Fin n) k))).inv ≫
          (Spec (.of (MvPolynomial (Fin n) k))).presheaf.map (homOfLE le_top).op).hom := by
    simp only [coordinateSubspace, Scheme.IdealSheafData.ofIdealTop_ideal, Ideal.map_map,
      CommRingCat.hom_comp]
  rw [hid, Ideal.map_map, affineBlowUpAlgebra.coordinateIdeal, Ideal.map_span,
    Set.image_image]
  refine congrArg Ideal.span (Set.image_congr fun i _ => ?_)
  rw [← CommRingCat.hom_comp, Category.assoc, TopCat.Presheaf.germ_res, CommRingCat.hom_comp,
    RingHom.comp_apply]

end Coordinates

section

variable {k : Type u} [Field k] {X : Scheme.{u}} (f : X ⟶ Spec (.of k)) (n r : ℕ)
  [SmoothOfRelativeDimension n f]

/-- If the stalk of `Z` at `x` is generated by the germs of the first `r` coordinates
`v_0, …, v_{r-1}` (sections of an affine open `V ∋ x`), then on a smaller affine open `U ∋ x` the
ideal sheaf `Z ∩ U` is the pullback of the coordinate subspace `V(t_0, …, t_{r-1})` under the
coordinate morphism `U ⟶ 𝔸ⁿ_k`: the local form of [Kol07, Definition 24, (4)]. -/
theorem exists_comap_eq_comap_coordinateSubspace (Z : X.IdealSheafData) {x : X}
    (V : X.affineOpens) (hxV : x ∈ V.1) (v : Fin n → Γ(X, V.1))
    (hZ : Z.stalkIdeal x =
      Ideal.span ((fun i => X.presheaf.germ V.1 x hxV (v i)) '' {i | i.val < r})) :
    ∃ (U : X.affineOpens) (_ : x ∈ U.1) (hUV : U.1 ≤ V.1),
      Z.comap U.1.ι = (coordinateSubspace k n r).comap
        (toAffineSpace f U.1 fun i => X.presheaf.map (homOfLE hUV).op (v i)) := by
  classical
  -- the ideals `Z(V)` and `Q = (v_0, …, v_{r-1})` of `Γ(X, V)` have the same stalk at `x`
  let _ := X.presheaf.algebra_section_stalk ⟨x, hxV⟩
  have hloc := V.2.isLocalization_stalk ⟨x, hxV⟩
  set p := (V.2.primeIdealOf ⟨x, hxV⟩).asIdeal with hpdef
  set Q : Ideal Γ(X, V.1) := Ideal.span (v '' {i | i.val < r}) with hQdef
  have hI : (Z.ideal V).map (algebraMap Γ(X, V.1) (X.presheaf.stalk x)) =
      Q.map (algebraMap Γ(X, V.1) (X.presheaf.stalk x)) := by
    change (Z.ideal V).map (X.presheaf.germ V.1 x hxV).hom = Q.map (X.presheaf.germ V.1 x hxV).hom
    rw [← Scheme.IdealSheafData.stalkIdeal_eq_map_germ Z V hxV, hZ, hQdef, Ideal.map_span,
      Set.image_image]
  have hs : Smooth f := SmoothOfRelativeDimension.smooth n f
  have hnoeth : IsNoetherianRing Γ(X, V.1) := by
    let _ := f.sectionsAlgebra V.1
    have : Algebra.FiniteType k Γ(X, V.1) := f.finiteType_sectionsAlgebra V.2
    exact Algebra.FiniteType.isNoetherianRing k Γ(X, V.1)
  have hIfg : (Z.ideal V).FG := IsNoetherian.noetherian _
  have hQfg : Q.FG := Submodule.fg_span ((Set.toFinite _).image v)
  obtain ⟨s, hsp, hs⟩ := exists_mem_map_eq_map_of_localization p.primeCompl (Z.ideal V) Q hIfg
    hQfg hI
  -- the basic open `U = D(s)`
  set U : X.Opens := X.basicOpen s with hUdef
  have hU : IsAffineOpen U := V.2.basicOpen s
  set Ua : X.affineOpens := ⟨U, hU⟩ with hUadef
  have hUV : U ≤ V.1 := X.basicOpen_le s
  have hxU : x ∈ U := (mem_basicOpen_iff_notMem_primeIdealOf V.2 hxV s).mpr hsp
  let _ := restrictAlgebra (X := X) hUV
  have hloc' : IsLocalization.Away s Γ(X, U) :=
    V.2.isLocalization_of_eq_basicOpen s (homOfLE hUV) rfl
  have hideal : Z.ideal Ua =
      Ideal.span ((fun i => X.presheaf.map (homOfLE hUV).op (v i)) '' {i | i.val < r}) := by
    rw [← Scheme.IdealSheafData.map_ideal Z (U := Ua) (V := V) hUV]
    change (Z.ideal V).map (algebraMap Γ(X, V.1) Γ(X, U)) = _
    rw [hs Γ(X, U), hQdef, Ideal.map_span, Set.image_image]
    rfl
  refine ⟨Ua, hxU, hUV, Scheme.IdealSheafData.ext_stalkIdeal fun u => ?_⟩
  have hu : Ua.1.ι u ∈ Ua.1 := u.2
  rw [Scheme.IdealSheafData.stalkIdeal_comap, Scheme.IdealSheafData.stalkIdeal_comap,
    Scheme.IdealSheafData.stalkIdeal_eq_map_germ Z Ua hu, hideal,
    stalkIdeal_coordinateSubspace, Ideal.map_map, Ideal.map_span, Ideal.map_span,
    Set.image_image, Set.image_image]
  refine congrArg Ideal.span (Set.image_congr fun i _ => ?_)
  rw [RingHom.comp_apply, Scheme.Hom.germ_stalkMap_apply, Scheme.Hom.germ_stalkMap_apply,
    toAffineSpace_app_top_X]
  refine TopCat.Presheaf.germ_ext _ ⊤ (TopologicalSpace.Opens.mem_top u) (homOfLE ?_)
    (homOfLE ?_) ?_
  · exact fun w _ => w.2
  · exact fun _ _ => trivial
  · have htop : Ua.1.topIso.inv = X.presheaf.map (eqToHom Ua.1.ι_image_top).op := rfl
    rw [Scheme.Opens.toScheme_presheaf_map, Scheme.Opens.toScheme_presheaf_map,
      Scheme.Opens.ι_app_self, htop]
    change (X.presheaf.map _ ≫ X.presheaf.map _) (X.presheaf.map _ (v i)) =
      (X.presheaf.map _ ≫ X.presheaf.map _) (X.presheaf.map _ (v i))
    repeat erw [← Functor.map_comp]
    change (X.presheaf.map _ ≫ X.presheaf.map _) (v i) = (X.presheaf.map _ ≫ X.presheaf.map _) (v i)
    repeat erw [← Functor.map_comp]

end

end AlgebraicGeometry
