/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.Smooth.EtaleCoordinatesDefs

/-!
# The standard charts of a smooth blow-up: the definitions

For a chart `E : EtaleCoordinatesAdapted f n r Z x` (an affine open `U ∋ x` with étale
coordinates `v` and `Z ∩ U = V(v_0, …, v_{r-1})`), Kollár's ideal `(x_1, …, x_r)` of the center
on `U` [Kol07, Definition 60] is `E.centerIdeal = (v_0, …, v_{r-1}) ⊆ Γ(X, U)`, and
`E.coord j hj` is `x_j` as an element of it: the generator whose chart
`Spec Γ(U)[J/x_j] ⟶ B_J` (`affineBlowUp.chart`, the chart of Hauser's local blow-up
[Hau14, Definition 4.16]) is the standard chart of `x_j`, on which Kollár's coordinates (60.2)
live. Germs of elements of an affine ring at a point of `Spec` are `AlgebraicGeometry.specGerm`.
-/

@[expose] public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory

universe u

variable {k : Type u} [Field k] {X : Scheme.{u}} {f : X ⟶ Spec (.of k)} {n r : ℕ}
  {Z : X.IdealSheafData} {x : X}

namespace EtaleCoordinatesAdapted

/-- Kollár's ideal `(x_1, …, x_r)` of the center [Kol07, Definition 60]: the ideal
`J = (v_0, …, v_{r-1})` of `Γ(X, U)` generated by the first `r` coordinates of the chart, the
ideal of `Z ∩ U`. -/
noncomputable def centerIdeal (E : EtaleCoordinatesAdapted f n r Z x) : Ideal Γ(X, E.U) :=
  Ideal.span (Set.range fun i : {i : Fin n // i.val < r} => E.v i.1)

theorem v_mem_centerIdeal (E : EtaleCoordinatesAdapted f n r Z x) {j : Fin n} (hj : j.val < r) :
    E.v j ∈ E.centerIdeal :=
  Ideal.subset_span (Set.mem_range_self (⟨j, hj⟩ : {i : Fin n // i.val < r}))

/-- `x_j` (`j < r`) as an element of `J`, the generator of the standard chart of `x_j`. -/
noncomputable def coord (E : EtaleCoordinatesAdapted f n r Z x) (j : Fin n) (hj : j.val < r) :
    E.centerIdeal :=
  ⟨E.v j, E.v_mem_centerIdeal hj⟩

@[simp]
theorem coe_coord (E : EtaleCoordinatesAdapted f n r Z x) (j : Fin n) (hj : j.val < r) :
    (E.coord j hj : Γ(X, E.U)) = E.v j := rfl

end EtaleCoordinatesAdapted

end AlgebraicGeometry
