/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.BlowUp.AffineBlowUp.Universal.Membership
public import Hironaka.Scheme.BlowUp.Defs
public import Hironaka.Scheme.Smooth.ChartDefs
import Hironaka.Scheme.BlowUp.Glue.Global
import Hironaka.Scheme.BlowUp.InverseImage
import Hironaka.Scheme.BlowUp.ProductCenter
import Hironaka.Scheme.Smooth.BlowUpSmoothChart
import Hironaka.Scheme.Smooth.StandardChart
import Mathlib.Algebra.Order.BigOperators.Ring.Finset

/-!
# The blow-up of a chart is the affine blow-up of its ring; the exceptional ideal on a chart

For a chart `E` of étale coordinates adapted to `Z` on the affine open `U ≅ Spec Γ(U)`, with
`J = (x_1, …, x_r) = Z(U)` the ideal of the center:

* `B_{Z∩U} U` is the affine blow-up `affineBlowUp J` of `Γ(U)` along `J`
  (`exists_iso_blowUp_affineBlowUp`; [Hau14, Theorem 4.19] with [Hau14, Definition 4.16]): both
  are blow-ups in Hauser's sense along the same ideal sheaf (`comap_toSpecΓ_specIdealSheaf`, from
  `Z(U) = J`), so they are isomorphic by the uniqueness of the blow-up (`IsBlowUp.exists_iso`,
  with `IsBlowUp.comp_iso` of `Hironaka/Scheme/BlowUp/ProductCenter.lean` transporting the predicate
  along `U ≅ Spec Γ(U)`).
* On the chart of `x_j`, from the chart-stalk lemmas of
  `Hironaka/Scheme/BlowUp/AffineBlowUp/Universal/Membership.lean`: the stalk of the exceptional
  ideal at a point `x'` of the chart is generated by `x_j` (`stalkIdeal_exceptionalIdeal_chart`; the
  local equation `u_m = y` of the exceptional divisor in the proof of [Wlo05, Lemma 2.6.3]); `π^*`
  is the localized chart map on germs (`stalkMap_π_specGerm`); and the stalk at a point of the chart
  is the localization of the chart ring (`exists_ringEquiv_stalk_localization`, Mathlib's
  `Spec.stalkIso`), Hauser's local blow-up [Hau14, Definitions 4.15, 4.16].

These identify the local rings of `B_Z X` at points of the standard charts with localizations of
the chart rings `Γ(U)[J/x_j]`, the form in which the order of an ideal is computed after a blow-up
(`Hironaka/Scheme/Snc/ChartStalk.lean`).
-/

public section

open AlgebraicGeometry CategoryTheory

universe u

namespace AlgebraicGeometry

open AlgebraicGeometry Scheme.IdealSheafData affineBlowUpAlgebra

variable {k : Type u} [Field k] {X : Scheme.{u}} {f : X ⟶ Spec (.of k)} {n r : ℕ}
  {Z : X.IdealSheafData} {x : X}

/-- The `Γ(X, U)`-algebra structure of `Γ(U, ⊤)` through `U.toSpecΓ` is the canonical
isomorphism. -/
theorem sectionsHom_toSpecΓ_top (U : X.Opens) :
    sectionsHom U.toSpecΓ ⊤ = U.topIso.inv.hom := by
  unfold sectionsHom
  have happ : U.toSpecΓ.appLE ⊤ ⊤ le_top = U.toSpecΓ.app ⊤ := Scheme.Hom.appLE_eq_app _
  rw [happ]
  change (U.toSpecΓ.appTop).hom.comp _ = _
  rw [Scheme.Opens.toSpecΓ_appTop, CommRingCat.hom_comp, RingHom.comp_assoc, ← CommRingCat.hom_comp,
    Iso.inv_hom_id, CommRingCat.hom_id, RingHom.comp_id]

/-- The ideal sheaf `Z ∩ U` on the affine chart `U ≅ Spec Γ(U)` is the ideal sheaf of `J = Z(U)`. -/
theorem comap_toSpecΓ_specIdealSheaf (E : EtaleCoordinatesAdapted f n r Z x) :
    (specIdealSheaf E.centerIdeal).comap E.U.1.toSpecΓ = Z.comap E.U.1.ι := by
  have : IsAffine (E.U.1 : Scheme.{u}) := E.U.2
  refine Scheme.IdealSheafData.ext_of_isAffine ?_
  have e : (⊤ : (E.U.1 : Scheme.{u}).Opens) ≤ E.U.1.ι ⁻¹ᵁ E.U.1 := fun y _ => y.2
  have h1 : (Z.comap E.U.1.ι).ideal ⟨⊤, isAffineOpen_top _⟩ =
      E.centerIdeal.map E.U.1.topIso.inv.hom := by
    rw [Z.ideal_comap_of_le E.U.1.ι E.U ⟨⊤, isAffineOpen_top _⟩ e, ideal_eq_centerIdeal E]
    exact congrArg (fun φ : Γ(X, E.U) ⟶ Γ(E.U.1, ⊤) => E.centerIdeal.map φ.hom)
      (ι_appLE_top_eq_topIso_inv E.U.1 e)
  have h2 : ((specIdealSheaf E.centerIdeal).comap E.U.1.toSpecΓ).ideal ⟨⊤, isAffineOpen_top _⟩ =
      E.centerIdeal.map E.U.1.topIso.inv.hom := by
    rw [ideal_comap_specIdealSheaf]
    exact congrArg (fun φ => Ideal.map φ E.centerIdeal) (sectionsHom_toSpecΓ_top E.U.1)
  exact h2.trans h1.symm

/-- `B_{Z∩U} U` is the affine blow-up of `Γ(U)` along `J`, over `U ≅ Spec Γ(U)`, by the uniqueness
of the blow-up ([Hau14, Theorem 4.19]). -/
theorem exists_iso_blowUp_affineBlowUp (E : EtaleCoordinatesAdapted f n r Z x) :
    ∃ e : blowUp (Z.comap E.U.1.ι) ≅ affineBlowUp E.centerIdeal,
      e.hom ≫ affineBlowUp.π E.centerIdeal = blowUpπ (Z.comap E.U.1.ι) ≫ E.U.1.toSpecΓ := by
  have h₁ := (blowUp.isBlowUp (Z.comap E.U.1.ι)).comp_iso E.U.2.isoSpec
  have hI : (Z.comap E.U.1.ι).comap E.U.2.isoSpec.inv = specIdealSheaf E.centerIdeal := by
    rw [← comap_toSpecΓ_specIdealSheaf E, ← Scheme.IdealSheafData.comap_comp]
    change (specIdealSheaf _).comap (E.U.2.isoSpec.inv ≫ E.U.2.isoSpec.hom) = _
    rw [Iso.inv_hom_id, Scheme.IdealSheafData.comap_id]
  rw [hI] at h₁
  obtain ⟨e, he, -⟩ := IsBlowUp.exists_iso h₁ (affineBlowUp.isBlowUp E.centerIdeal)
  exact ⟨e, he⟩

/-- At a point `x'` of the chart of `x_j`, the stalk of the exceptional ideal is generated by `x_j`
(`= y_j`), read in the stalk of the chart through the chart's stalk map (an isomorphism, the
chart being an open immersion): the local equation of the exceptional divisor on the chart of
[Kol07, Definition 60] and of the proof of [Wlo05, Lemma 2.6.3]. -/
theorem stalkIdeal_exceptionalIdeal_chart (E : EtaleCoordinatesAdapted f n r Z x) {j : Fin n}
    (hj : j.val < r) (p : Spec (.of (affineBlowUpAlgebra E.centerIdeal (E.coord j hj)))) :
    ((affineBlowUp.exceptionalIdeal E.centerIdeal).stalkIdeal
        (affineBlowUp.chart E.centerIdeal (E.coord j hj) p)).map
        ((affineBlowUp.chart E.centerIdeal (E.coord j hj)).stalkMap p).hom =
      Ideal.span {specGerm (S := .of (affineBlowUpAlgebra E.centerIdeal (E.coord j hj))) p
        (algebraMap Γ(X, E.U) (affineBlowUpAlgebra E.centerIdeal (E.coord j hj)) (E.v j))} :=
  stalkIdeal_exceptionalIdeal_chart_map E.centerIdeal (E.coord j hj) p

/-- `π^* : 𝒪_{X,x} → 𝒪_{B,x'}` is the localization of the chart map ([Hau14, Definitions 4.15,
4.16 and Remark 4.17]): on the germ of a section `s` of `U`, `π^*(s)` read in the stalk of the
chart is the germ of `(chart map)(s)`. -/
theorem stalkMap_π_specGerm (E : EtaleCoordinatesAdapted f n r Z x) {j : Fin n} (hj : j.val < r)
    (p : Spec (.of (affineBlowUpAlgebra E.centerIdeal (E.coord j hj)))) (s : Γ(X, E.U)) :
    (affineBlowUp.chart E.centerIdeal (E.coord j hj)).stalkMap p
        ((affineBlowUp.π E.centerIdeal).stalkMap
          (affineBlowUp.chart E.centerIdeal (E.coord j hj) p) (specGerm (S := Γ(X, E.U)) _ s)) =
      specGerm (S := .of (affineBlowUpAlgebra E.centerIdeal (E.coord j hj))) p
        (algebraMap Γ(X, E.U) (affineBlowUpAlgebra E.centerIdeal (E.coord j hj)) s) :=
  specGerm_apply (S := Γ(X, E.U)) _ s ▸ stalkMap_chart_stalkMap_π E.centerIdeal (E.coord j hj) p s

/-- The stalk of `B_{Z∩U} U` at the point `x'` of the chart of `x_j` given by the prime `𝔭'` is the
localization `Γ(U)[J/x_j]_{𝔭'}`, compatibly with germs through the chart's stalk map (Hauser's
local blow-up, [Hau14, Definitions 4.15, 4.16]). -/
theorem exists_ringEquiv_stalk_localization (E : EtaleCoordinatesAdapted f n r Z x) {j : Fin n}
    (hj : j.val < r) (p : Spec (.of (affineBlowUpAlgebra E.centerIdeal (E.coord j hj)))) :
    ∃ e : (affineBlowUp E.centerIdeal).presheaf.stalk
        (affineBlowUp.chart E.centerIdeal (E.coord j hj) p) ≃+*
        Localization.AtPrime (PrimeSpectrum.asIdeal p) (hp := PrimeSpectrum.isPrime p),
      ∀ c : affineBlowUpAlgebra E.centerIdeal (E.coord j hj),
        (affineBlowUp.chart E.centerIdeal (E.coord j hj)).stalkMap p (e.symm (algebraMap _ _ c)) =
          specGerm (S := .of (affineBlowUpAlgebra E.centerIdeal (E.coord j hj))) p c :=
  exists_ringEquiv_stalk_chart E.centerIdeal (E.coord j hj) p

end AlgebraicGeometry
