/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Mathlib.AlgebraicGeometry.Morphisms.Smooth
import Mathlib.AlgebraicGeometry.Morphisms.Etale

/-!
# Stalks of a scheme étale over a field are fields

Kollár starts the induction on the dimension at `dim X = 0`, where `I = 𝒪_X` because `I` is
assumed nonzero on every irreducible component, and "everything is resolved without blow-ups"
([Kol07, 70]). In this library a scheme of dimension `≤ 0` over `k` has a structure morphism
smooth of relative dimension `0`, i.e. étale (Mathlib's `Etale.iff_smoothOfRelativeDimension_zero`),
and the local rings of a scheme étale and locally of finite type over a field are fields: the
stalk map `𝒪_{Spec k, f x} → 𝒪_{X, x}` is a formally unramified local homomorphism essentially of
finite type, so it carries the maximal ideal of its source onto that of its target
([Sta, Tag 00UW], Mathlib's `Algebra.FormallyUnramified.map_maximalIdeal`), and the source, the
localization of the field `k` at its only prime, is `k` itself. No perfectness of `k` is used (the
route through the regularity of the stalk and the dimension formula
`Scheme.ringKrullDim_stalk_add_trdeg_residueField_of_smoothOfRelativeDimension` would need
`[PerfectField k]`): the statement holds over every field. Used for the base case of the
induction on the dimension (`Hironaka/Resolution/Algebraic/Stage/DimZero.lean`).
-/

public section

universe u

open CategoryTheory AlgebraicGeometry

namespace AlgebraicGeometry

variable {k : Type u} [Field k]

-- Instance synthesis in the proof (`Algebra k K'`, primality of `(f x).asIdeal`) needs to unfold
-- definitions that the transparency-respecting unifier keeps folded; the older behaviour is
-- restored for this declaration.
set_option backward.isDefEq.respectTransparency false in
/-- The stalks of a scheme étale (smooth of relative dimension `0`) and locally of finite type over
a field are fields ([Sta, Tag 00UW]; the case `dim X = 0` of [Kol07, 70]): the stalk map is a
formally unramified local homomorphism essentially of finite type, so the maximal ideal of
`𝒪_{X, x}` is generated by that of the base stalk, which is the field `k`. -/
theorem isField_stalk_of_smoothOfRelativeDimension_zero {X : Scheme.{u}} (f : X ⟶ Spec (.of k))
    [SmoothOfRelativeDimension 0 f] (x : X) : IsField (X.presheaf.stalk x) := by
  have := SmoothOfRelativeDimension.smooth 0 f
  have : Etale f := (Etale.iff_smoothOfRelativeDimension_zero f).mpr inferInstance
  have hfu : (f.stalkMap x).hom.FormallyUnramified := FormallyUnramified.stalkMap f x
  have hft : (f.stalkMap x).hom.EssFiniteType := LocallyOfFiniteType.stalkMap f x
  algebraize [(f.stalkMap x).hom]
  have : IsLocalHom (algebraMap ((Spec (.of k)).presheaf.stalk (f x)) (X.presheaf.stalk x)) :=
    inferInstanceAs <| IsLocalHom (f.stalkMap x).hom
  have : Algebra.EssFiniteType ((Spec (.of k)).presheaf.stalk (f x)) (X.presheaf.stalk x) := by
    rw [← RingHom.essFiniteType_algebraMap, RingHom.algebraMap_toAlgebra]
    exact hft
  have : Algebra.FormallyUnramified ((Spec (.of k)).presheaf.stalk (f x)) (X.presheaf.stalk x) := by
    rw [← RingHom.formallyUnramified_algebraMap, RingHom.algebraMap_toAlgebra]
    exact hfu
  have hmap := Algebra.FormallyUnramified.map_maximalIdeal
    (R := (Spec (.of k)).presheaf.stalk (f x)) (S := X.presheaf.stalk x)
  let K' := (Spec.structureSheaf k).presheaf.stalk (f x)
  let e : k ≃ₐ[k] K' := IsLocalization.atUnits _ (f x).asIdeal.primeCompl
    (fun y hy ↦ by aesop (add simp IsUnit.mem_submonoid_iff))
  have hK' : IsField K' := e.toRingEquiv.symm.isField (Field.toIsField k)
  have hbot : IsLocalRing.maximalIdeal ((Spec (.of k)).presheaf.stalk (f x)) = ⊥ :=
    (IsLocalRing.isField_iff_maximalIdeal_eq).mp hK'
  rw [hbot, Ideal.map_bot] at hmap
  exact (IsLocalRing.isField_iff_maximalIdeal_eq).mpr hmap.symm

end AlgebraicGeometry
