/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Scheme.Smooth.EtaleCoordinatesDefs
import Hironaka.Scheme.Smooth.Adapted
import Hironaka.Scheme.Smooth.AdaptedCoordinates
import Hironaka.Scheme.Smooth.DifferentialBasis
import Hironaka.Scheme.Smooth.EtaleCoordinates
import Hironaka.Scheme.Smooth.EtaleLocal

/-!
# Étale coordinates adapted to a smooth center

At a closed point `x` of a center `Z` smooth of relative dimension `n − r` in `X` smooth of
relative dimension `n` over the perfect field `k`, there are étale coordinates adapted to `Z`: an
affine open `U ∋ x` with an étale coordinate morphism `g : U ⟶ 𝔸ⁿ_k` and
`Z ∩ U = g⁻¹(V(t_0, …, t_{r-1}))` (`nonempty_etaleCoordinatesAdapted`). This is Kollár's choice
of local coordinates with `Z = (z_{j_1} = ⋯ = z_{j_s} = 0)` near `x` ([Kol07, Definition 24, (4)];
`Z = (x_1 = ⋯ = x_r = 0)` in [Kol07, Definition 60]), with the coordinates made an étale chart.

The construction assembles the preceding modules: `exists_adaptedCoordinates`
(`AdaptedCoordinates.lean`) gives a regular system of parameters `y` of `𝒪_{X,x}` with
`Z_x = (y_0, …, y_{r-1})`; the `y_i` lift to sections `w_i` of an affine open around `x`
(`exists_affineOpen_germ_eq`); their differentials `1 ⊗ d w_i` form a basis of `κ(x) ⊗ Ω`
(`DifferentialBasis.lean`); so `(w_i)` are étale coordinates on a smaller affine open
(`exists_etale_toAffineSpace_of_basis`); and `Z ∩ U = g⁻¹(L)` holds on a yet smaller one
(`exists_comap_eq_comap_coordinateSubspace`, `Adapted.lean`), where the coordinates stay étale
(`etale_toAffineSpace_restrict`).

These charts cover the closed points of the center; `Hironaka/Scheme/Smooth/BlowUpSmooth.lean` and
`ExceptionalDivisor.lean` glue the smoothness of `B_Z X` and of its exceptional divisor from them.
-/

public section

namespace AlgebraicGeometry

open AlgebraicGeometry CategoryTheory IsLocalRing KaehlerDifferential TensorProduct

universe u

variable {k : Type u} [Field k] [PerfectField k] {X : Scheme.{u}} (f : X ⟶ Spec (.of k))
  (n r : ℕ) [SmoothOfRelativeDimension n f] (Z : X.IdealSheafData)
  [SmoothOfRelativeDimension (n - r) (Z.subschemeι ≫ f)]

/-- At a closed point `x` of a center `V(Z)` smooth of relative dimension `n − r` in `X` smooth of
relative dimension `n`, there are étale coordinates adapted to `Z` ([Kol07, Definition 24, (4)]
and [Kol07, Definition 60], as an étale chart). -/
theorem nonempty_etaleCoordinatesAdapted (hrn : r ≤ n) {x : X} (hxZ : x ∈ Z.support)
    (hx : IsClosed ({x} : Set X)) : Nonempty (EtaleCoordinatesAdapted f n r Z x) := by
  classical
  let _ := f.stalkAlgebra x
  -- adapted parameters at the stalk
  obtain ⟨y, -, hspan, hZ⟩ := exists_adaptedCoordinates Z f n r hrn hxZ hx
  -- lift them to sections of an affine open `V ∋ x`
  obtain ⟨_, ⟨V₀, hV₀, rfl⟩, hxV₀, -⟩ :=
    X.isBasis_affineOpens.exists_subset_of_mem_open (Set.mem_univ x) isOpen_univ
  obtain ⟨V, hxV, -, w, hw⟩ := exists_affineOpen_germ_eq ⟨V₀, hV₀⟩ hxV₀ y
  -- their differentials form a basis at `x`
  obtain ⟨b, hb⟩ := exists_basis_tensor_kaehlerDifferential_of_span_eq_maximalIdeal f n hx y hspan
  have hb' : ∃ b' : Module.Basis (Fin n) (ResidueField (X.presheaf.stalk x))
      (ResidueField (X.presheaf.stalk x) ⊗[X.presheaf.stalk x] Ω[X.presheaf.stalk x⁄k]),
      ∀ i, b' i = 1 ⊗ₜ D k (X.presheaf.stalk x) (X.presheaf.germ V.1 x hxV (w i)) :=
    ⟨b, fun i => by rw [hb i, hw i]⟩
  -- étale coordinates on a smaller affine open `U`
  obtain ⟨U, hxU, hUV, hE⟩ := exists_etale_toAffineSpace_of_basis f n V hxV w hb'
  set w' : Fin n → Γ(X, U.1) := fun i => X.presheaf.map (homOfLE hUV).op (w i) with hw'def
  -- the stalk of `Z` is generated by the germs of `w'_0, …, w'_{r-1}`
  have hZ' : Z.stalkIdeal x =
      Ideal.span ((fun i => X.presheaf.germ U.1 x hxU (w' i)) '' {i | i.val < r}) := by
    rw [hZ]
    congr 1
    refine Set.image_congr fun i _ => ?_
    rw [hw'def]
    change y i = X.presheaf.germ U.1 x hxU (X.presheaf.map (homOfLE hUV).op (w i))
    rw [X.presheaf.germ_res_apply, hw i]
  -- adaptedness on a smaller affine open `U'`
  obtain ⟨U', hxU', hU'U, hAd⟩ :=
    exists_comap_eq_comap_coordinateSubspace f n r Z U hxU w' hZ'
  have : Etale (toAffineSpace f U.1 w') := hE
  exact ⟨⟨U', hxU', fun i => X.presheaf.map (homOfLE hU'U).op (w' i),
    etale_toAffineSpace_restrict f hU'U w', hAd⟩⟩

end AlgebraicGeometry
