/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Manifold.BlowUp.Transform.Defs
public import Hironaka.Manifold.StructureSheaf
import Hironaka.Algebra.ColonPow
import Hironaka.Algebra.Local.CohenIso
import Hironaka.Manifold.BlowUp.Divisor
import Hironaka.Manifold.BlowUp.Transform.Colon
import Hironaka.Manifold.Germ.CoordDeriv
import Hironaka.Manifold.Germ.StalkNoetherian
import Hironaka.Manifold.IdealSheaf.Pullback
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init

/-!
# The order of the colon stalk of a total transform

Two steps of Kollár's argument rest on one local computation: in the proof of [Kol07, Lemma 102],
the order of `I_0` along `E^{jk}` is that of `I` diminished by `m` ("`max-ord_{E^{jk}} I_0 ≤ 0`"),
and in the one-dimensional case of the induction [Kol07, 70], "`max-ord I ⊗ 𝒪_X(Z) < max-ord I`".
Both concern a point `a'` of the blown-up manifold over the centre `Y` at which the blowing-up is a
local analytic isomorphism, as it is for a centre of codimension one ([Kol07, Warning 20]: the
blow-up of a Cartier divisor is an isomorphism). There the total transform `π⁻¹(𝓘)_{a'}` has the
order of `𝓘_{π a'}`, at most `m`; it lies in the `m`-th power of the exceptional ideal `(u)`, `u`
the scaling coordinate of a blow-up chart, as soon as `ord_Y 𝓘 ≥ m` at `π a'`; and the colon
`(π⁻¹(𝓘)_{a'} : u^m)`, which is the stalk of the controlled transform of `(𝓘, m)` and of the weak
transform when `m` is the order of `𝓘` along the centre, is then the unit ideal: writing
`J = u^m · (J : u^m)` gives `m + ord (J : u^m) ≤ ord J ≤ m`, the order being additive on the
regular local stalk.

* `ord_colon_totalTransform_eq_zero` — the computation, as an equality of orders.

The general fact about a Noetherian local ring behind it is
`IsLocalRing.colon_span_singleton_pow_eq_top_of_ord_le`. The result is used for the first
centre of Lemma 102 (`FirstStep.lean`) and for the one-dimensional case (`BaseCases.lean`).
-/

public section

noncomputable section

open Set Topology
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

section Algebra

variable {R : Type*} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]

end Algebra

namespace Hironaka.Manifold

open _root_.Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E] {n : ℕ}
  {ψ : E ≃L[𝕜] (Fin n → 𝕜)} {M : Type u} [TopologicalSpace M] [ChartedSpace E M]
  [IsManifold 𝓘(𝕜, E) ω M] {Y : Set M} {c : ℕ} {M' : Type u} [TopologicalSpace M']
  [ChartedSpace E M'] [IsManifold 𝓘(𝕜, E) ω M'] [T2Space M'] [SecondCountableTopology M']
  {π : M' → M}

omit [IsManifold 𝓘(𝕜, E) ω M] in
/-- The computation behind the proof of [Kol07, Lemma 102] ("`max-ord_{E^{jk}} I_0 =
max-ord_{E^{jk}} I − m ≤ 0`") and the one-dimensional case of [Kol07, 70]: at a point `a'` over the
centre where the blowing-up is a local analytic isomorphism, if `ord 𝓘 ≤ m` at `π a'` and
`ord_Y 𝓘 ≥ m` at `π a'`, the colon `(π⁻¹(𝓘)_{a'} : I_{F,a'}^m)` of the total transform by the
`m`-th power of the exceptional ideal (the stalk of the controlled transform of `(𝓘, m)`, and of
the weak transform when `m` is the order along the centre) is the unit ideal, so it has order `0`.
The exceptional stalk is generated by the scaling coordinate `u` of a blow-up chart; the total
transform lies in `(u)^m` and has the order of `𝓘` at `π a'`, at most `m`; and the order is
additive on the regular local stalk. -/
theorem ord_colon_totalTransform_eq_zero (hY : IsClosedSubmanifold ψ Y c)
    (h : IsBlowUp ψ Y c π) (I : IdealSheaf (structureSheaf 𝕜 E M)) {m : ℕ} {a' : M'}
    (hloc : IsLocalDiffeomorphAt 𝓘(𝕜, E) 𝓘(𝕜, E) ω π a') (hle : I.ord (π a') ≤ m)
    (ha : π a' ∈ Y) (hord : (m : ℕ∞) ≤ IdealSheaf.ordAlongIdeal hY.idealSheaf I (π a')) :
    IsLocalRing.ord (((I.pullback π h.contMDiff).stalkIdeal a').colon
      ↑((hY.idealSheaf.pullback π h.contMDiff).stalkIdeal a' ^ m)) = 0 := by
  -- the exceptional stalk is generated by the scaling coordinate `u` of a blow-up chart
  obtain ⟨φ, σ, haφ, hφ⟩ := hY.exists_adaptedChart _ ha
  obtain ⟨i, Φ, hΦ, ha'Φ⟩ := h.cover φ σ hφ a' haφ
  have hexc := stalkIdeal_exceptionalIdealSheaf_eq_span_coord hY h hφ hΦ ha'Φ
  have hu : coord E ψ Φ hΦ.mem_maximalAtlas ha'Φ (σ i) ∈ IsLocalRing.maximalIdeal _ := by
    rw [mem_maximalIdeal_iff_eval, eval_coord]
    exact (IsBlowUpChart.mem_preimage_iff hφ hΦ ha'Φ).mp ha
  -- `π⁻¹(𝓘)_{a'} ⊆ (u)^m` and `ord π⁻¹(𝓘)_{a'} = ord 𝓘_{π a'} ≤ m`
  have hle' := h.totalTransform_stalkIdeal_le hY I hord
  rw [hexc] at hle' ⊢
  have hord' : IsLocalRing.ord ((I.pullback π h.contMDiff).stalkIdeal a') ≤ m := by
    change (I.pullback π h.contMDiff).ord a' ≤ m
    rw [IdealSheaf.ord_pullback_of_isLocalDiffeomorphAt _ _ I hloc]
    exact hle
  -- the order is additive on the regular local stalk
  have hreg := isRegularLocalRing_stalk_of_chart E ψ (chartAt E a') (mem_chart_source E a')
    (IsManifold.chart_mem_maximalAtlas a')
  have hmul := IsLocalRing.ordElem_mul_of_algebraRat
    ((structureSheaf 𝕜 E M').presheaf.stalk a')
  rw [IsLocalRing.colon_span_singleton_pow_eq_top_of_ord_le hmul hu hle' hord',
    IsLocalRing.ord_top]

end Hironaka.Manifold

end
