/-
Copyright (c) 2026 Resolution. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Elliott (Resolution): formalization performed by Claude Fable 5.1
-/
module

public import Hironaka.Resolution.Analytic.OrderReduction.Basic
import Hironaka.Manifold.BlowUp.Transform.Object
import Hironaka.Manifold.BlowUp.Transform.OrderAlong
import Hironaka.Manifold.Chart.Adapted
import Hironaka.Manifold.Chart.MaximalContact
import Hironaka.Manifold.FiniteSuccession.Functor.LocalCover
import Hironaka.Manifold.IdealSheaf.CosupportDeriv
import Hironaka.Manifold.IdealSheaf.DerivLocality
import Hironaka.Manifold.IdealSheaf.Pullback
import Hironaka.Resolution.Analytic.OrderReduction.ClassPullback
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Combinatorics.Matroid.Init
import Mathlib.Data.Nat.Choose.Multinomial

/-!
# Every point has a neighbourhood with a hypersurface of maximal contact

Step 2 of the proof of [Kol07, Theorem 103] assumes a smooth hypersurface of maximal contact, a
condition "always satisfied in a suitable open neighborhood of any point" by Theorem 80 (2):
[Kol07, Theorem 80 (2)] states that every point has an open neighbourhood on which a section of
`MC(I)` has a smooth zero divisor. Step 3 covers `X` by such open subsets `X^{(j)}`.

`AnalyticTriple.exists_isPullbackOf_localMCClass` is the analytic form: for a triple of the class
`BOClass m` and a point `x`, the triple restricted to a suitable open neighbourhood `V` of `x` lies
in the class `LocalMCClass m`: it is in `BOClass m` (`ClassPullback.lean`) and carries a global
hypersurface of maximal contact. At a point of maximal order `m`, a section `h` of `MC(𝓘)` of order
`1` at `x` exists (`exists_mem_carrier_iteratedDeriv_ordElem_eq_one`), and the analytic implicit
function theorem gives an adapted chart `e` with `h` as one of its coordinates on its source
(`exists_adapted_chart_of_ord_eq_one'`); take `V := e.source` and `H := {h = 0} ⊆ V`, read on the
bundled manifold `V`. Then the ideal sheaf of `H` lies in `MC(h^* 𝓘)` stalkwise: at a point of `H`
the stalk of the ideal sheaf of `H` is generated by the coordinate `h`, a section of `MC(𝓘)`; off
`H` the germ of `h` is a unit of `MC(h^* 𝓘)`. At a point of order `< m`, `MC(𝓘)` is the unit
ideal sheaf near `x` and the empty hypersurface serves.

This is the local existence that Step 3 of the proof of Theorem 103 globalizes
(`GlobalizeCover.lean`, `GlobalizeFamCover.lean`).
-/

public section

noncomputable section

open Set Topology TopologicalSpace Filter
open scoped Manifold ContDiff
open IsManifold (maximalAtlas)

universe u

namespace Manifold

variable {𝕜 : Type} [RCLike 𝕜] {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [hfd : FiniteDimensional 𝕜 E] {n : ℕ} {ψ₀ : E ≃L[𝕜] (Fin n → 𝕜)}

-- The finite-dimensionality `[FiniteDimensional 𝕜 E]` of the model space belongs to every statement
-- here, as to Kollár's varieties; a proof that does not need it names it (`have _hfd := hfd`) so
-- that it remains part of the statement.

section Restrict

variable {M : AnalyticManifold.{u} 𝕜 E} (U : Opens M)

end Restrict

/-- Every point of a triple of the class `BOClass m` has an open neighbourhood, embedded by the
inclusion, whose pulled-back triple lies in `LocalMCClass m` (Step 2 of the proof of
[Kol07, Theorem 103] with [Kol07, Theorem 80 (2)]; the cover of Step 3): at a point of order `m`
the hypersurface `{h = 0}` cut out by a section `h` of `MC(𝓘)` of order `1`, an adapted coordinate
by the implicit function theorem; at a point of order `< m` the empty hypersurface, `MC(𝓘)` being
the unit ideal sheaf there. -/
theorem AnalyticTriple.exists_isPullbackOf_localMCClass {m : ℕ} {M : AnalyticManifold.{u} 𝕜 E}
    {T : AnalyticTriple ψ₀ M} (hT : AnalyticTriple.BOClass m T) (x : M) :
    ∃ (N : AnalyticManifold.{u} 𝕜 E) (T' : AnalyticTriple ψ₀ N) (g : AnalyticMap N M),
      IsAnalyticOpenEmbedding g ∧ x ∈ Set.range g ∧ T'.IsPullbackOf T g ∧
        AnalyticTriple.LocalMCClass m T' := by
  have _hfd := hfd
  obtain ⟨hm, hord, -⟩ := id hT
  -- the common shape: an open `V ∋ x` on which the pulled-back triple has maximal contact
  suffices h : ∃ (V : Opens M) (_ : x ∈ V), AnalyticTriple.HasMaximalContact m
      (T.pullback (M.inclusion V) (isLocalDiffeomorph_inclusion M V)) by
    obtain ⟨V, hxV, hmc⟩ := h
    exact ⟨M.restrict V, T.pullback (M.inclusion V) (isLocalDiffeomorph_inclusion M V),
      M.inclusion V, isAnalyticOpenEmbedding_inclusion M V, ⟨⟨x, hxV⟩, rfl⟩,
      T.isPullbackOf_pullback _ _,
      AnalyticTriple.boClass_of_isPullbackOf hT (isLocalDiffeomorph_inclusion M V)
        (T.isPullbackOf_pullback _ _), hmc⟩
  by_cases hx : T.I.ord x = m
  · -- Theorem 80 at a point of maximal order: `h ∈ MC(𝓘)` of order `1`, an adapted coordinate
    obtain ⟨U, hxU, h, hh, hord1⟩ := exists_mem_carrier_iteratedDeriv_ordElem_eq_one T.I hm hx
    obtain ⟨e, σ, he, hxe, heU, -, hcoord, hadapt, hclosed⟩ :=
      exists_adapted_chart_of_ord_eq_one' E ψ₀ hxU h hord1
    let V : Opens M := ⟨e.source, e.open_source⟩
    have hV : ∀ p : M.restrict V, p.1 ∈ e.source := fun p => p.2
    let g := M.inclusion V
    have hg : IsLocalDiffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) ω g := isLocalDiffeomorph_inclusion M V
    have hH := IsClosedSubmanifoldOn.restrict (ψ₀ := ψ₀) V hclosed
    refine ⟨V, hxe, ⇑g ⁻¹' (e.source ∩ {y | extendSection 𝕜 E h y = 0}), hH, ?_⟩
    -- `𝓘_H ⊆ MC(g^*𝓘) = g^*MC(𝓘)`, stalkwise
    have h2 := iteratedDeriv_pullback_of_isLocalDiffeomorph (⇑g) g.contMDiff T.I hg (m - 1)
    refine le_of_le_of_eq ?_ h2.symm
    rw [IdealSheaf.le_def]
    intro p
    rw [IdealSheaf.stalkIdeal_pullback]
    have hpU : g p ∈ U := heU (hV p)
    have hmem : germMap (⇑g) g.contMDiff p
        ((structureSheaf 𝕜 E M).presheaf.germ U (g p) hpU h) ∈
        Ideal.map (germMap (⇑g) g.contMDiff p) ((T.I.iteratedDeriv (m - 1)).stalkIdeal (g p)) :=
      Ideal.mem_map_of_mem _ (IdealSheaf.germ_mem_stalkIdeal _ hpU hh)
    by_cases hp : p ∈ ⇑g ⁻¹' (e.source ∩ {y | extendSection 𝕜 E h y = 0})
    · -- on `H`: the stalk of `𝓘_H` is generated by the coordinate `z_{σ 0} = h`
      have hφ' := isAdaptedChart_transportChart (inclusionPartialDiffeomorph M V p).symm
        (image_inclusionInv_eq V p (e.source ∩ {y | extendSection 𝕜 E h y = 0})) hadapt
      have hpφ' : p ∈ (transportChart (inclusionPartialDiffeomorph M V p).symm e).source := by
        rw [transportChart_source]
        exact ⟨Set.mem_univ _, hV p⟩
      rw [hH.stalkIdeal_idealSheaf_eq_span hp hφ' hpφ', Set.range_unique, Ideal.span_le,
        Set.singleton_subset_iff]
      -- the coordinate of the transported chart is the germ of `h ∘ g`
      have hcoord' : coord E ψ₀ (transportChart (inclusionPartialDiffeomorph M V p).symm e) hφ'.1
          hpφ' (σ default) = germMap (⇑g) g.contMDiff p
            ((structureSheaf 𝕜 E M).presheaf.germ U (g p) hpU h) := by
        apply stalkToGerm_injective 𝓘(𝕜, E) ω (M.restrict V) p
        have hs := stalkToGerm_germMap (⇑g) g.contMDiff p
          ((structureSheaf 𝕜 E M).presheaf.germ U (g p) hpU h)
        rw [coord, stalkToGerm_structureSheaf_germ, hs, stalkToGerm_structureSheaf_germ,
          Germ.coe_compTendsto, Germ.coe_eq]
        filter_upwards [(transportChart_source (inclusionPartialDiffeomorph M V p).symm ▸
          (transportChart (inclusionPartialDiffeomorph M V p).symm e).open_source).mem_nhds hpφ']
          with q hq
        rw [extendSection_of_mem 𝕜 E _ hq, Function.comp_apply,
          extendSection_of_mem 𝕜 E h (show g q ∈ U from heU (hV q))]
        change ψ₀ (e q.1) (σ default) = h ⟨q.1, heU (hV q)⟩
        rw [Subsingleton.elim (default : Fin 1) 0, ← hcoord _ (hV q),
          extendSection_of_mem 𝕜 E h (heU (hV q))]
      rw [hcoord']
      exact hmem
    · -- off `H`: the germ of `h` is a unit of `MC(g^*𝓘)`
      have hne : extendSection 𝕜 E h p.1 ≠ 0 := fun h0 => hp ⟨hV p, h0⟩
      have hunit : IsUnit (germMap (⇑g) g.contMDiff p
          ((structureSheaf 𝕜 E M).presheaf.germ U (g p) hpU h)) := by
        refine IsUnit.map _ (IsLocalRing.notMem_maximalIdeal.mp ?_)
        rw [mem_maximalIdeal_iff_eval, eval_germ' U hpU h]
        exact hne
      rw [Ideal.eq_top_of_isUnit_mem _ hmem hunit]
      exact le_top
  · -- off the maximal-order locus: `MC(𝓘)` is the unit ideal sheaf near `x`
    have hlt : T.I.ord x < m := lt_of_le_of_ne (hord x) hx
    let V : Opens M := ⟨(T.I.iteratedDeriv (m - 1)).supportᶜ,
      (IdealSheaf.isClosed_support _).isOpen_compl⟩
    have hxV : x ∈ V := by
      change x ∉ (T.I.iteratedDeriv (m - 1)).support
      rw [IdealSheaf.support_iteratedDeriv T.I hm]
      exact not_le.mpr hlt
    let g := M.inclusion V
    have hg : IsLocalDiffeomorph 𝓘(𝕜, E) 𝓘(𝕜, E) ω g := isLocalDiffeomorph_inclusion M V
    refine ⟨V, hxV, ∅, ⟨isClosed_empty, fun _ ha => ha.elim⟩, ?_⟩
    have h2 := iteratedDeriv_pullback_of_isLocalDiffeomorph (⇑g) g.contMDiff T.I hg (m - 1)
    refine le_of_le_of_eq ?_ h2.symm
    rw [IdealSheaf.le_def]
    intro p
    have htop : (T.I.iteratedDeriv (m - 1)).stalkIdeal (g p) = ⊤ := by
      by_contra hne
      exact p.2 ((IdealSheaf.mem_support _).mpr hne)
    rw [IdealSheaf.stalkIdeal_pullback, htop, Ideal.map_top]
    exact le_top

end Manifold

end
